src/modules/commander/Arming/PreFlightCheck/checks/airspeedCheck.cpp
src/modules/commander/Arming/PreFlightCheck/checks/powerCheck.cpp
src/modules/commander/Commander.cpp
src/modules/commander/state_machine_helper.cpp

Fixes some serious bugs around preflight checks:
- fix `prearm` flag to preflightCheck
This was inverted, i.e. set to false in most cases, whereas it should be true.
As a consequence, both powerCheck and airspeed.confidence checks were not executed.
- fix commander: run preflight checks on GCS connection
Regression from 6dec451, leading to preflight failures not being reported at all. Only after a failed arming attempt the messages would be sent. And for GPS check failures, in case they are set to optional (default), arming would be possible, but switching to position would be rejected w/o error.
We need to run the preflight checks periodically, but this at least restores the previous behavior.

Commander: preflight check fixes

---

src/modules/commander/Commander.cpp

Quick follow up to https://github.com/PX4/Firmware/pull/14022.
If the re-connect triggers preflight during calibration (eg intermittant connection) it disrupts QGC calibration. Preflight is re-run after calibration finishes.

commander: don't run preflightCheck during calibration on reconnect

---

Tools/gazebo_sitl_multiple_run.sh

This adds support to multivehicle simulation with `standard_vtol` by extending #13729 #13806
Generate the sdf file of `standard_vtol` using xacro so that mavlink port / sysid can be configured
Full video: [video](https://youtu.be/lAjjTFFZebI)
To test this can be run with the following command
```
Tools/gazebo_sitl_multiple_run.sh -m standard_vtol
```
- This PR depends on the implementation in the submodule https://github.com/PX4/sitl_gazebo/pull/398
- The distance between models have been increased since the vtol model has a bigger wingspan and makes the vehicles collide
- Fixes https://github.com/PX4/Firmware/issues/10835

Add support for VTOL multivehicle simulation in SITL gazebo

---

msg/CMakeLists.txt
msg/tools/uorb_rtps_message_ids.yaml
msg/vehicle_angular_acceleration.msg
src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.hpp
src/modules/sensors/vehicle_angular_velocity/imu_gyro_parameters.c

@jlecoeur I was going to bring in sensors/vehicle_angular_acceleration from https://github.com/PX4/Firmware/pull/13219, but a lot of the duplicate structure started to seem a bit wasteful compared to doing it in place next to angular velocity.
This also sets us up for using the raw FIFO data later (https://github.com/PX4/ecl/issues/621#issuecomment-507429494) if desired.

sensors: add vehicle_angular_acceleration

---

.github/workflows/sitl_tests_coverage.yml
Makefile
cmake/coverage.cmake
cmake/px4_add_common_flags.cmake
codecov.yml
src/modules/simulator/simulator_mavlink.cpp
test/mavsdk_tests/CMakeLists.txt
test/mavsdk_tests/autopilot_tester.cpp
test/mavsdk_tests/autopilot_tester.h
test/mavsdk_tests/mavsdk_test_runner.py
test/mavsdk_tests/test_mission_plane.cpp
test/mavsdk_tests/test_mission_vtol.cpp

This enables code coverage on the MAVSDK tests. We still need much tighter acceptance criteria there, but we're starting to form up a pipeline for integration testing that gives us real insights what is going on.

Enable Code Coverage on MAVSDK tests with Codecov

---

src/modules/navigator/mission_feasibility_checker.cpp

Prior this fix VTOL missions get rejected if they have a DO_LAND_START marker, but then do
not end with a LAND but a VTOL transition and land.

mission feasibilty check: fix for VTOL transition and land waypoint

---

src/modules/commander/Arming/PreFlightCheck/checks/preArmCheck.cpp

This is a follow up from https://github.com/PX4/Firmware/pull/13987
No changes of functionality, just following the suggestion of @dagar to first check if vehicle is vtol and only if that is true run the vtol specific checks.
@sfuhrer @dagar FYI

prearmCheck: vtol cleanup

---

test/mavsdk_tests/mavsdk_test_runner.py
test/mavsdk_tests/test_mission_vtol.cpp

This enables the VTOL transition test. All I changed was the TEST_CASE name which was not picked up by the catch2 filter correctly. It runs on my machine :man_shrugging:.

Enable VTOL transition test

---

ROMFS/px4fmu_common/init.d-posix/1017_iris_opt_flow_mockup
platforms/posix/cmake/sitl_target.cmake

This PR adds a mockup optical flow model, that computes a flow measurement without rendering an image.
This is useful for CI SITL tests, where we want to speed up the simulation. This is not possible with the existing image based optical flow plugin as it relies on the camera plugin.
SITL_gazebo: https://github.com/PX4/sitl_gazebo/pull/400

Flow mockup

---

src/drivers/imu/invensense/mpu9250/CMakeLists.txt
src/drivers/imu/invensense/mpu9250/InvenSense_MPU9250_registers.hpp
src/drivers/imu/invensense/mpu9250/MPU9250.cpp
src/drivers/imu/invensense/mpu9250/MPU9250.hpp
src/drivers/imu/invensense/mpu9250/mpu9250_main.cpp

Initially used for vibration analysis. Doesn't include mag support.
Currently needs to be manually enabled and started.

new mpu9250 driver using FIFO and raw sampling (8 kHz gyro, 4 kHz accel)

---

src/lib/flight_tasks/tasks/ManualAltitude/FlightTaskManualAltitude.cpp
src/modules/mc_pos_control/PositionControl/ControlMath.cpp
src/modules/mc_pos_control/PositionControl/ControlMath.hpp
src/modules/mc_pos_control/PositionControl/ControlMathTest.cpp
src/modules/mc_pos_control/PositionControl/PositionControl.cpp
src/modules/mc_pos_control/PositionControl/PositionControl.hpp
src/modules/mc_pos_control/PositionControl/PositionControlTest.cpp
src/modules/mc_pos_control/mc_pos_control_main.cpp

This is part 6 of the refactoring from the monster pr #12072 and should be easy to understand and review since the diff is manageable.
- Replace velocity PID calculations for each axis separate spread across the whole function with a one-line `Vector3f` formula. https://github.com/PX4/Firmware/commit/af3ede01353fdb80a4329ab9a91536a46d4ae69a
- Use `addIfNotNan` helper functions for feed-forward summation with potentially NAN values in each axis. This simplifies velocity feed-forward and enables unit thrust feed-forward (acceleration to come in next pr).
- Make sure the hacky way horizontal thrust setpoints get combined with altitude and vertical velocity setpoints in "Altitude" mode still works to not break any …

Position Control Refactoring Part 6

---

boards/px4/fmu-v2/default.cmake
boards/px4/fmu-v5/default.cmake
src/drivers/imu/invensense/icm20602/ICM20602.cpp
src/drivers/imu/invensense/icm20602/ICM20602.hpp
src/drivers/imu/invensense/icm20602/InvenSense_ICM20602_registers.hpp
src/drivers/imu/invensense/icm20608-g/ICM20608G.cpp
src/drivers/imu/invensense/icm20608-g/ICM20608G.hpp
src/drivers/imu/invensense/icm20608-g/InvenSense_ICM20608G_registers.hpp
src/drivers/imu/invensense/icm20689/CMakeLists.txt
src/drivers/imu/invensense/icm20689/ICM20689.cpp
src/drivers/imu/invensense/icm20689/ICM20689.hpp
src/drivers/imu/invensense/icm20689/InvenSense_ICM20689_registers.hpp
src/drivers/imu/invensense/icm20689/icm20689_main.cpp
src/drivers/imu/invensense/mpu6000/CMakeLists.txt
src/drivers/imu/invensense/mpu6000/InvenSense_MPU6000_registers.hpp
src/drivers/imu/invensense/mpu6000/MPU6000.cpp
src/drivers/imu/invensense/mpu6000/MPU6000.hpp
src/drivers/imu/invensense/mpu6000/mpu6000_main.cpp
src/drivers/imu/invensense/mpu9250/InvenSense_MPU9250_registers.hpp
src/drivers/imu/invensense/mpu9250/MPU9250.cpp
src/drivers/imu/invensense/mpu9250/MPU9250.hpp

This PR adds a new mpu6000 and icm20689 IMU driver in the style of the other new IMU drivers.
The overall plan here is to implement opinionated, optimized IMU drivers for our use case that disable all sensor side filtering, transfer all raw data using FIFOs over SPI DMA, and utilize data ready interrupts wherever possible.
Although each driver is relatively small (~ 800 lines) there's still quite a lot of duplication. The idea is to first optimize each individually without compromise (handling the minor but important differences), and then do a follow up refactoring pass.
Within our current mpu6000 driver we currently support the mpu6000, icm20602, icm20608g, icm20689, but here are some of the noteworthy differences a common driver might gloss over.
- output data rates aren't they same …

Updates to new Invensense IMU drivers

---

src/modules/commander/commander_params.c

Astyle failure slipped in with https://github.com/PX4/Firmware/pull/14073.

commander params fix whitespace

---

Tools/jmavsim_run.sh
Tools/setup/ubuntu.sh

This adds a check before running jMAVSim if Java 8 is selected.
It also selects Java 8 by default in the Ubuntu setup script.
Fixes https://github.com/PX4/Devguide/issues/926.

jMAVSim: warn if not Java 8 is used, select Java 8 in setup script

---

src/modules/logger/logged_topics.cpp

New logger versions do not allow to log multiple instances of a topic when using 'logger_topics.txt'
This commit restores the previous behavior (log all instances of a topic) and add an option to specify an instance to log
Tested with default (all instances) and a specific instance

logger: choose logged instances by logger_topics file

---

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp
platforms/common/px4_work_queue/WorkQueueManager.cpp
src/lib/rc/sbus.cpp

Previous version of code could not set the serial device properly, which leads to incorrect read of `_rcs_buf`. This PR solves that problem.
Code comes from existing `drivers/linux_sbus`, which works well.
A problem still exists that `rc_input` will report
`ERROR [px4_work_queue] unknown serial port: /dev/ttyAMA0`
for that customised ttyAMA0 is not defined which is necessary for function `px4::serial_port_to_wq()`
``````
pxh> rc_input status
INFO  [rc_input] Running
INFO  [rc_input] Max update rate: 250 Hz
INFO  [rc_input] Serial device: /dev/ttyAMA0
INFO  [rc_input] RC scan state: SBUS, locked: yes
INFO  [rc_input] CRSF Telemetry: no
INFO  [rc_input] SBUS frame drops: 0
rc_input: cycle …

SBUS on Linux: replace termios with termios2

---

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp

This is a quick initial pass to update fw_pos_control_l1 param usage. Needs to be reviewed carefully, then tested.

fw_pos_control_l1: move to px4::params

---

Makefile

Currently there is no way to specify which version of python you want to build px4 with.  It will pick up the first instance of python/python3 found in the path.
If the manual build process used cmake we could pass -DPYTHON_EXECUTABLE but because there is a make wrapper we can't do that.  This PR adds to the Makefile to pass PYTHON_EXECUTABLE if environment variable is set.

Honour PYTHON_EXECUTABLE environment variable pass to cmake #14077

---

src/drivers/batt_smbus/batt_smbus.cpp

fix `error: variable-sized object ‘lifetime_block_one’ may not be initialized`

fix batt_smbus build error

---

src/lib/circuit_breaker/circuit_breaker_params.c

Fixes https://github.com/PX4/Firmware/issues/14053
Clarifies that driver not started when circuit breaker enabled. A feature, as described in https://github.com/PX4/Firmware/issues/14053#issuecomment-580556456

CBRK_AIRSPD_CHK: Doc driver not started

---

src/modules/sensors/sensor_corrections/CMakeLists.txt
src/modules/sensors/sensor_corrections/SensorCorrections.cpp
src/modules/sensors/sensor_corrections/SensorCorrections.hpp
src/modules/sensors/sensors.cpp
src/modules/sensors/vehicle_acceleration/CMakeLists.txt
src/modules/sensors/vehicle_acceleration/VehicleAcceleration.cpp
src/modules/sensors/vehicle_acceleration/VehicleAcceleration.hpp
src/modules/sensors/vehicle_angular_velocity/CMakeLists.txt
src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.hpp
src/modules/sensors/vehicle_imu/CMakeLists.txt
src/modules/sensors/vehicle_imu/VehicleIMU.cpp

This PR refactors the duplicated board rotation and sensor correction (if available) handling in the sensors module.
It saves about 1.5 kB of flash.

sensors: refactor common corrections and rotation helpers

---

boards/av/x-v1/init/rc.board_sensors
boards/holybro/durandal-v1/init/rc.board_sensors
boards/holybro/kakutef7/init/rc.board_sensors
boards/intel/aerofc-v1/init/rc.board_sensors
boards/modalai/fc-v1/init/rc.board_sensors
boards/mro/ctrl-zero-f7/init/rc.board_sensors
boards/mro/x21-777/init/rc.board_sensors
boards/mro/x21/init/rc.board_sensors
boards/nxp/fmuk66-v3/init/rc.board_sensors
boards/nxp/fmurt1062-v1/init/rc.board_sensors
boards/px4/fmu-v2/init/rc.board_sensors
boards/px4/fmu-v3/init/rc.board_sensors
boards/px4/fmu-v5/init/rc.board_sensors
boards/px4/fmu-v5x/init/rc.board_sensors
src/drivers/magnetometer/ist8310/ist8310.cpp

- it does nothing useful
- increases boot time by 2 seconds on pixhawk 4 due to a poll timeout:
```
IST8310 on I2C bus 3 at 0x0e (bus: 100 KHz, max: 400 KHz)
WARN  [ist8310] ERROR: TIMEOUT 2
```

ist8310: remove calibration code

---

msg/ekf2_timestamps.msg
src/modules/ekf2/ekf2_main.cpp
src/modules/replay/ReplayEkf2.cpp
src/modules/replay/ReplayEkf2.hpp

Replaces https://github.com/PX4/Firmware/pull/14092
Solves original issue reported [here](https://github.com/PX4/Firmware/issues/13953)
Remove relative timestamps of GPS measurements. The benefit of this is that all GPS data that is logged will actually be published during EKF replay even if the ekf2_timestamps topic has dropouts. The downside is that the accuracy of the measurement timestamps is reduced slightly.
Publish the GPS data anyway if no relative timestamp is found during replay. The upside would be more accurate time stamping and the downside more data to log
**Tests**
Here are the relative timestamps of two GPS modules (logged in microseconds / 10)
As can be seen the …

replay: remove GPS relative timestamps

---

src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/standard.h
src/modules/vtol_att_control/tiltrotor.cpp
src/modules/vtol_att_control/tiltrotor.h
src/modules/vtol_att_control/vtol_att_control_main.cpp
src/modules/vtol_att_control/vtol_att_control_main.h
src/modules/vtol_att_control/vtol_type.cpp
src/modules/vtol_att_control/vtol_type.h

This PR enables the controller for tiltrotor VTOL to use tilting of the motors to accelerate forward (similar as the standard VTOL can use its pusher/pull motor to do so).
Initial testing looked promising, but need to do some more as I've changed the thrust compensation when tilting is applied. 
Also needs to be tested on a standard VTOL to check for regressions.
This a video of the first flight: https://drive.google.com/file/d/1gHhwEUxHKgazkDOrzRixyPfx4gMYRJ-x/view?usp=sharing
It was with flying in altitude mode (I've enabled pusher/tilt assist also in altitude mode to test this PR - do you think it's a good idea to enable that in general @RomanBapst ?).

VTOL tiltrotor tilt ("pusher") support in hover

---

src/modules/sensors/vehicle_acceleration/VehicleAcceleration.cpp
src/modules/sensors/vehicle_acceleration/VehicleAcceleration.hpp
src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.hpp

The perf counter intervals aren't numerically stable over extended periods (https://github.com/PX4/Firmware/pull/14046), so are obviously not ideal for automatically setting filter sample rates. Here's a simpler solution.

sensors: filter sample rate calculate with simple interval average instead of perf count

---

msg/tools/generate_microRTPS_bridge.py

When I compile ```make px4_sitl_rtps```, I found the error like below with just standalone, no ROS.
```
stmoon@stmoon-XPS-13-9370:/home/px4/firmware.rtps/Firmware.stmoon/build/px4_sitl_rtps/src/modules/micrortps_bridge/micrortps_client/micrortps_agent/build$ make 
Scanning dependencies of target micrortps_agent
[  0%] Building CXX object CMakeFiles/micrortps_agent.dir/RtpsTopics.cpp.o
In file included from /home/px4/firmware.rtps/Firmware.stmoon/build/px4_sitl_rtps/src/modules/micrortps_bridge/micrortps_client/micrortps_agent/RtpsTopics.h:38:0,
from /home/px4/firmware.rtps/Firmware.stmoon/build/px4_sitl_rtps/src/modules/micrortps_bridge/micrortps_client/micrortps_agent/RtpsTopics.cpp:34: …
```

fix the encoding problem for subprocess.check_output

---

.vscode/.gitignore
.vscode/c_cpp_properties.json
.vscode/extensions.json
.vscode/settings.json
platforms/nuttx/cmake/jlink.cmake

Nothing too exciting here.
- updates to `.vscode/c_cpp_properties.json` that help things resolve a little better if you don't have a proper compile_commands.json from a successful configure (split for Mac and Linux)
- add yaml extension to recommended
- add shellcheck extension to recommended
- decrease workspace parsing priority
- disable annoying c++ file extension auto add
- terminal increase scrollback buffer and make it easier to copy and paste
- cmake jlink helpers add path hints for macos (eg jlink_debug_ozone target)

vscode small improvements

---

src/modules/logger/logger.cpp

This was accidentally dropped in a rebase of https://github.com/PX4/Firmware/pull/14050.

logger: restore buffer statistics update

---

.vscode/cmake-variants.yaml
platforms/nuttx/CMakeLists.txt
platforms/nuttx/src/px4/nxp/imxrt/hrt/hrt.c
platforms/nuttx/src/px4/nxp/kinetis/hrt/hrt.c
platforms/nuttx/src/px4/stm/stm32_common/hrt/hrt.c
platforms/posix/src/px4/common/drv_hrt.cpp
platforms/qurt/src/px4/common/drv_hrt.cpp
src/drivers/drv_hrt.h
src/lib/perf/perf_counter.cpp
src/lib/perf/perf_counter.h
src/modules/px4iofirmware/CMakeLists.txt
src/modules/px4iofirmware/adc.c
src/modules/px4iofirmware/controls.c
src/modules/px4iofirmware/px4io.c
src/modules/px4iofirmware/px4io.h
src/modules/px4iofirmware/serial.c

This saves a paltry 64 bytes of ram, but it seems to be enough to get us out of the immediate bind (https://github.com/PX4/Firmware/issues/14116). 
On the upside it does save a good chunk of flash (nearly 1 kB).
``` Console
$ make px4_io-v2_default bloaty_compare_master
VM SIZE    
-------------- 
[NEW]     +12    channels_cache.7449
[NEW]      +8    base_time.7109
[NEW]      +8    last_mem_time.7465
[NEW]      +4    brightness.7477
[NEW]      +4    brightness_counter.7478
[NEW]      +4    counter.7476
[NEW]      +4    last_count.7110
[NEW]      +4    new_channel_count.7087
[NEW]      +4    new_channel_holdoff.7088
[NEW]      +4    on_counter.7479
[NEW]      +1    abort_on_idle.7147
[NEW]      +1    failsafe.7178
[NEW]      +1    heartbeat.7471
[ = ]       0    [Unmapped]
[ = ]       0 …
```

px4iofirmware: add PX4IO_PERF define to completely disable perf counters

---

src/drivers/px4io/px4io.cpp

may cause memory override if _max_controls larger then _max_actuators
probably _max_controls is not larger then _max_actuators. or there is no use of the memory after, in the code scenario. so we never seen an issue
fix array size

px4io - Fix array regs[] size

---

src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_main.h
src/modules/mavlink/mavlink_params.c

This PR turns the previously hard-coded timeout for RADIO_STATUS into a parameter. The previous hard-coding was there because there was only one kind of radio (3DR/SiK), but now that other types of radios are possible, this is no longer okay.

Parameterize timeout for radio status

---

CMakeLists.txt

This was just wrong. `devel` might be correct on Fedora but no on Ubuntu :).

cmake: fix Python 3 libs name

---

src/modules/simulator/simulator.h
src/modules/simulator/simulator_mavlink.cpp

Extends `simulator` to support publishing data from multiple distance sensors, which are differentiated by the sensor ID.
Add support for multi-sensor subscription in Gazebo, which sets a different sensor ID per stream. The sensor ID is what then allows to create a different `uORB::PublicationMulti<distance_sensor_s>` per sensor.
Extend to use a `PX4RangeFinder` per sensor stream coming from the simulation side.
To be added as soon as I add an example model with multiple sensors.
**Note:** Right now, the update to the `sitl_gazebo` submodule also brings the multiple-VTOL simulation capability.

simulator: add support for multi-distance_sensor instances

---

Tools/mavlink_shell.py
Tools/mavlink_ulog_streaming.py
Tools/serial/generate_config.py
Tools/upload_log.py
Tools/validate_yaml.py
msg/tools/px_generate_uorb_topic_files.py
src/lib/mixer/MultirotorMixer/geometries/tools/px_generate_mixers.py
src/lib/parameters/px_generate_params.py

The problem with printing the exception was that starting with Python 3.6 the ImportError is yet another (sub) exception called `ModuleNotFoundError` which can't be printed as a string and then triggers
another exception:
```
Traceback (most recent call last):
File "/home/julianoes/src/Firmware/Tools/serial/generate_config.py", line 11, in <module>
import jinja2
ModuleNotFoundError: No module named 'jinja2'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/julianoes/src/Firmware/Tools/serial/generate_config.py", line 13, in <module>
print("Failed to import jinja2: " + e)
TypeError: must be str, not ModuleNotFoundError
```
As per @bkueng's suggestion the easiest is to cast the exception to str and that way prevent the second …

Tools: make Python import error more readable

---

src/modules/land_detector/VtolLandDetector.cpp
src/modules/land_detector/VtolLandDetector.h

It seems that the multicopter free fall function is running in fixed-wing mode, which triggers freefall when making parabolic flight maneuvers (eg pitching strongly down), as then the vertical acceleration is low.
It is though not relevant for land detection, as this is currently switched off (landing = false) for the fixed-wing portion of the flight. The error message though still pops up, so this PR is mainly there to fix that.
To enable a proper land detection in the future for VTOL, I didn't just kill off the free fall detection for VTOL in FW flight, but added a VTOL-specific one that also takes into account airspeed, and thus disabling free fall detection if the airspeed is above the stall speed of the vehicle.

VTOL land detector: disable freefall detection if FW and move to airspeed_validated

---

src/lib/flight_tasks/tasks/ManualAltitude/FlightTaskManualAltitude.cpp

In terrain hold mode, the drone holds its height over the terrain when it's stopped, but follows sea level altitude when moving. Every time the drone stops, the height over terrain setpoint is computed to match the current altitude setpoint, given the current height over the terrain. The opposite is also done to give an altitude setpoint matching the current terrain setpoint when the drone starts moving. These setpoint calculations seem to have a sign error, which will give an error in the computed setpoints when the drone starts/stops terrain holding.
Example illustrating the issue:
* z position = - 10 m (this is in NED frame)
* z position setpoint = - 10.5 m (also NED frame, so setpoint is 0.5 m above current z position)
* height over …

FlightTaskManualAltitude: Fix sign error in terrain hold setpoint reset

---

ROMFS/px4fmu_common/init.d-posix/rcS

Previously, the number of vehicles that were able to be simulated was limited to 10 vehicles. This was due to a overlap on port numbering that overlapped in the rcS definition.
Redefine gcs udp port from `14570` to `18570` in rcS.
Tested up to 100 instances of vehicles on a desktop.
Image below shows 30 vehicles

Support large number of vehicles in multivehicle SITL

---

src/lib/flight_tasks/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.cpp
src/lib/flight_tasks/tasks/AutoMapper/FlightTaskAutoMapper.cpp
src/lib/flight_tasks/tasks/AutoMapper/FlightTaskAutoMapper.hpp

We want to be able to track a moving setpoint from the avoidance interface. However, right now velocity setpoints are used as constraints, which prevents their being used for the feedforward term to be able to specify the position setpoint as a moving target
Use the _velocity_setpoint as a feedforward (which the name would imply), instead of using it as a constraint.
~~Use the _constraints to constrain the takeoff velocity, which was the only usage of the velocity setpoint term for contraining velocities from position setpoints before.~~ _constraints is used in mc_pos_control which introduces lots of discontinuities.
Ported the the only previous usage of the velocity constraint (takeoff speed) in the …

Use velocity_setpoint for feedforward instead of constraint

---

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp

It turns out that ekf2 needs more stack when sideslip fusion fails.
Sideslip fusion is currently only enabled for fixedwing by default and not executed in testing.
Should fix the crash seen in #14134.

platforms: prevent stackoverflow for ekf2 sideslip

---

boards/px4/fmu-v4/cannode.cmake
boards/px4/fmu-v4/default.cmake
msg/sensor_accel_status.msg
msg/sensor_gyro_fifo.msg
msg/sensor_gyro_status.msg
platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp
src/drivers/imu/invensense/icm20602/ICM20602.cpp
src/drivers/imu/invensense/icm20602/ICM20602.hpp
src/drivers/imu/invensense/icm20602/InvenSense_ICM20602_registers.hpp
src/drivers/imu/invensense/mpu9250/InvenSense_MPU9250_registers.hpp
src/drivers/imu/invensense/mpu9250/MPU9250.cpp
src/drivers/imu/invensense/mpu9250/MPU9250.hpp
src/lib/drivers/accelerometer/PX4Accelerometer.cpp
src/lib/drivers/gyroscope/PX4Gyroscope.cpp
src/lib/drivers/gyroscope/PX4Gyroscope.hpp

- checked register mechanism and simple watchdog
- driver checks for errors gradually and can reconfigure itself
- respect IMU_GYRO_RATEMAX at the driver level
- fixed sensor INT16_MIN and INT16_MAX handling (y & z axis are flipped before publishing)
- increased sensor_gyro_fifo max size (enables running the driver much slower, but still transferring all raw data)
- PX4Accelerometer/PX4Gyroscope remove unnecessary memsets
In particular the driver actually respecting the `IMU_GYRO_RATEMAX` parameter could be quite valuable once rolled out to all Invensense drivers and configured appropriately per platform. These sensors have large FIFOs, so we can configure them to fill with all raw data, then minimize how often they're transferred. Due to the fixed overhead of setting up DMA transactions, …

new Invensense icm20602 driver improvements

---

ROMFS/px4fmu_common/init.d-posix/rcS
Tools/gazebo_sitl_multiple_run.sh

Previously, the number of vehicles that were able to be simulated was limited to 10 vehicles. This was due to a overlap on port numbering that overlapped in the rcS definition.
Resubmitted #14126 
- Redefine gcs udp port from `14570` to `18570` in rcS.
- Increment remote udp port from 14540 to 14549 to limit overlap with port 14550 which is the default listening port of qgc
- Also since mavlink only supports 255 IDs to be assigned the script errors if you try to spawn more than 255 vehicles
Tested up to 100 instances of vehicles on a desktop.
Image below shows 30 vehicles

Support large number of vehicles for mutlivehicle SITL

---

src/modules/commander/Commander.cpp

As I understand the existing code, the `if` statement is only entered if `status_local->hil_state` is `vehicle_status_s::HIL_STATE_ON`. I.e. for all real vehicles, this check is skipped.

Commander: fix preflight check condition to fail if not in HIL mode

---

src/modules/rc_update/rc_update.cpp

RC Failsafe isn't triggered when PPM signal is valid. These changes
update Failsafe trigger logic for RC input. RF Modules keep sending
valid PPM signal when the RC Transmitter is lost.
RF Modules which are in the air send PPM signal with same type when lost
the signal from ground.
Replacement for #12595.
Fixes #12381.

RC Failsafe fix for RFD 868+/900 Modems

---

src/modules/mavlink/mavlink_log_handler.cpp

Fixes https://github.com/PX4/Firmware/issues/14157

fix mavlink_log_handler: close file descriptor if still open in destructor

---

src/drivers/px4io/px4io.cpp
src/modules/commander/Commander.cpp

Regression from https://github.com/PX4/Firmware/pull/13613.
VEHICLE_CMD_COMPONENT_ARM_DISARM from CLI would enter the
ARMING_STATE_IN_AIR_RESTORE logic. This was never intended for disarming
(and leads to state machine transition failures), and IMO it is also not
intended for commands from CLI.

commander: fix broken 'commander arm/disarm' CLI

---

src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_main.h
src/modules/mavlink/mavlink_receiver.cpp

This is a very tiny change, but I thought I'd PR it anyway.
I was looking at the mavlink receiver, and I found the statement `if (_mavlink->get_manual_input_mode_generation())` to be confusing.
I renamed the getter so that the client code now looks like `if (_mavlink->should_generate_virtual_rc_input())` which better reflects what the code does.
I also renamed the setter from `set_manual_input_mode_generation` to `set_generate_virtual_rc_input`.
None.

Rename Mavlink class generate virtual RC setter/getter

---

ROMFS/px4fmu_common/init.d-posix/rcS

Sometimes in CI for VTOL we saw disarms before the spoolup and ramp were over and the takeoff would actually happen. By raising the auto-disarm time we should be able to work around this and get CI less flaky.
Fixes #14200.

ROMFS: prevent auto-disarm before takeoff in CI

---

src/lib/battery/battery.cpp
src/lib/battery/battery.h
src/modules/battery_status/battery_status.cpp
src/modules/commander/Commander.cpp
src/modules/commander/Commander.hpp

As described in https://github.com/PX4/Firmware/pull/14021, the Commander only subscribes to Instance 0 of the `battery_status` uORB topic. Therefore, when supporting multiple batteries, drivers must swap uORB topics such that the currently-selected power source is on uORB instance 0.
Change Commander to check all uORB instances. This also changes the following behavior:
- Arming will now be denied if _any_ battery has a warning, rather than only if the currently-selected power source has a warning
The alternative is the uORB topic switching discussed in https://github.com/PX4/Firmware/pull/14021, but the general consensus is that that is a bad way to do things.
**Test data / …

Changed commander to check all instances of battery_status uORB topic

---

src/drivers/barometer/bmp388/bmp388.h
src/drivers/barometer/bmp388/bmp388_i2c.cpp
src/drivers/barometer/bmp388/bmp388_main.cpp
src/drivers/barometer/bmp388/bmp388_spi.cpp

'interface' is freed in BMP388's destructor.
I had hardfaults on v5x because of this.
@davids5 @dinomani fyi

bmp388: fix double free in case the driver probing fails 

---

boards/px4/fmu-v5/init/rc.board_sensors
src/drivers/imu/invensense/icm20602/CMakeLists.txt
src/drivers/imu/invensense/icm20602/ICM20602.cpp
src/drivers/imu/invensense/icm20602/ICM20602.hpp
src/drivers/imu/invensense/icm20602/InvenSense_ICM20602_registers.hpp
src/drivers/imu/invensense/icm20608g/ICM20608G.cpp
src/drivers/imu/invensense/icm20608g/ICM20608G.hpp
src/drivers/imu/invensense/icm20608g/InvenSense_ICM20608G_registers.hpp
src/drivers/imu/invensense/icm20689/ICM20689.cpp
src/drivers/imu/invensense/icm20689/ICM20689.hpp
src/drivers/imu/invensense/mpu9250/InvenSense_MPU9250_registers.hpp
src/drivers/imu/invensense/mpu9250/MPU9250.cpp
src/drivers/imu/invensense/mpu9250/MPU9250.hpp
src/lib/drivers/accelerometer/PX4Accelerometer.hpp
src/lib/drivers/gyroscope/PX4Gyroscope.hpp

- refactor Run() into simple state machine
- all sleeps removed
- perform reset and configuration in sensor bus thread
- when using data ready interrupt skip checking FIFO count
- fix periodic temperature sampling (rate limit to 1 Hz)
- propagate error counts (eg errors in FIFO duplicated accel samples)
At default rates (1000 Hz) saves roughly 2-3% cpu per sensor instance (https://github.com/PX4/Firmware/pull/14184#issuecomment-589921946)

new Invensense IMU drivers improvements and fixes

---

src/modules/mc_rate_control/mc_rate_control_params.c

Currently the minimum value for the K parameter is at 0. I find this a bit dangerous during tuning, as an unintended setting to 0 results in complete loss of control around the corresponding axis. Setting any other PID gain to 0 should not be quite as fatal, as in these cases you at least have some control from the other 2 parts (limiting the P to something >0 could though also make sense, no?).
The minimum limit of 0.3 that I propose here is pretty random, but should at least leave some control authority to bring the system safely to the ground. If a smaller than 0.3 value is necessary there is still the option of using a forced-safe. 
What's your opinion @bresch ? Do you know of any system requiring K values smaller than 0.3?

MC rate controller: limit K values of PID controller to [0.3, 5.0] in pitch and roll

---

src/modules/mavlink/mavlink_mission.cpp

This adds support for MAV_MISSION_OPERATION_CANCELLED which can be used
to cancel an ongoing upload or download of mission/geofence/rally items.
Tested in SITL against MAVSDK integration test:
```
cmake --build build -j8 && build/src/integration_tests/integration_tests_runner --gtest_filter="SitlTest.Mission*Cancellation"
```
As added in: https://github.com/mavlink/mavlink/pull/1044

mavlink: support mission transfer cancellation

---

src/modules/simulator/simulator_mavlink.cpp

This PR changes the orientation for simulated distance sensor from the mavlink enum to the uorb distance sensor orientation enum used in the rest of the Firmware

map mavlink orientation enum to uorb distance_sensor orientation

---

src/modules/ekf2/ekf2_main.cpp

The logic to determine if the two GPS modules were running at the same rate was bugged leading to time jitter clearly visible in the position innovations.
Here is a logfile replayed on v1.10.1 and on this PR

EKF2: Fix GPS blending time jitter

---

src/modules/logger/logger.cpp
src/modules/logger/logger.h

- this is disabled in replay builds to ensure all data in ekf2 replay logs only contains the same time range, otherwise the plots can be unreadable using common tools
- fixes #14230

logger: disable logger_status publiation in replay builds

---

src/modules/commander/Commander.cpp

I find myself and other users looking for why the pilot is not able to take over control by moving the sticks during the auto takeoff. The use cases can be
- the pilot seeing things going wrong during takeoff e.g. suddenly something is above the drone
- takeoff altitude being to high
- pilot being impatient
- takeoff waypoint doesn't get reached for some reason like with the problem described in
https://github.com/PX4/Firmware/pull/14193#issuecomment-589091770
I'm adding the `AUTO_TAKEOFF` mode to the modes where the pilot can take over control using the sticks. Also I'm adding the remaining other auto flight modes which are used more rarely from the list here: …

Commander: enable RC override during takeoff

---

src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp
src/modules/local_position_estimator/BlockLocalPositionEstimator.hpp

This fixes SITL with lockstep when using LPE and q estimator.
The required changes are:
- Publish ekf2_timestamps because simulator_mavlink expects them.
- Run LPE at 250 Hz instead of 80 Hz in order to keep everything in lockstep running at 250 Hz.

LPE: make compatible with lockstep simulation

---

msg/vehicle_attitude_setpoint.msg
src/examples/fixedwing_control/main.cpp
src/modules/fw_att_control/FixedwingAttitudeControl.cpp
src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/mavlink_receiver.cpp
src/modules/mc_att_control/mc_att_control_main.cpp
src/modules/mc_pos_control/PositionControl/ControlMath.cpp
src/modules/mc_pos_control/PositionControl/PositionControlTest.cpp
src/modules/navigator/gpsfailure.cpp
src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/tailsitter.cpp
src/modules/vtol_att_control/vtol_type.cpp

While writing tests for the multicopter position controller I realized that the `q_d_valid` flag in the attitude setpoint was probably used to transition from euler angles to quaterionion attitude setpoints. I couldn't find a single place where it was useful. Today I was also trying to free up some flash space on omnibus for https://github.com/PX4/Firmware/pull/14212 and hence went through to remove the flag.
I remove the flag. It is only ever set to true and never set to false explicitly. The only place where it's used is in mavlink_messages to send out the attitude setpoint as a quaternion in any case but the conversion is already everywhere.
@RomanBapst Since a lot of attitude setpoint magic is for VTOL do you …

vehicle_attitude_setpoint: get rid of unused q_d_valid flag

---

src/modules/mavlink/mavlink_main.cpp

This PR solve the [Issue #10788](https://github.com/PX4/Firmware/issues/10788).
This introduces a special handling of the serial device in the mavlink module in the iridium mode. As of now [getting the uart config](https://github.com/PX4/Firmware/blob/master/src/modules/mavlink/mavlink_main.cpp#L621) fails for the iridium driver.

Fix crashing for the mavlink module in the iridium mode

---

platforms/common/include/px4_platform_common/bitmask.h
src/modules/simulator/simulator.h
src/modules/simulator/simulator_mavlink.cpp

Fixes https://github.com/PX4/Firmware/issues/14220.
A check is made to the bitmask field in `HIL_SENSOR` Mavlink message and according to how the bitmask is set, the respective sensors get updated. This allows to properly set the sensor rate for each sensor source.
In SITL, running `uorb top sensor_accel sensor_gyro sensor_baro sensor_mag`:
```console
update: 1s, num topics: 69
TOPIC NAME            INST #SUB #MSG #LOST #QSIZE
sensor_gyro              0    1  249   248 4
sensor_accel             0    1  249   248 4
sensor_gyro_integrated   0    2  249     0 1
sensor_accel_integrated  0    2  249     1 1
sensor_baro              0    1   42    41 1
sensor_mag               0    1   84    83 …
```

simulator: set sensor update rate according to HIL_SENSOR bitmask

---

.vscode/c_cpp_properties.json
.vscode/settings.json

The vscode cpp extension cpu usage can get stuck at 100%, which may go unnoticed on a fast desktop, but destroys laptop battery life and turns macbooks into toasters.
This PR is experimenting with several proposed fixes.
@MaEtUgR FYI
- https://github.com/microsoft/vscode-cpptools/issues/1816
- https://github.com/microsoft/vscode-cpptools/issues/286

vscode: possible fixes for cpp extension cpu usage

---

src/modules/vtol_att_control/vtol_att_control_main.cpp

Currently the VTOL transition state update is only run when there is a setpoint change of either a the mc_attitude controller or the fw_attitude controller. This is a big problem if, for some reason, they are not updated for some time, eg because of a malfunction. This happened to me recently: After doing a transition to fixed-wing mode in altitude control mode, with a vehicle without GPS, it froze the attitude sp (see https://github.com/PX4/Firmware/issues/14243). Switching back to multicopter was not possible due to the above noted, and it only switched to MC when I also changed to stabilized. 
Ability to switch VTOL state independently of attitude sp changes.
Check the VTOL transition switch every time the VTOL …

VTOL: run vtol state update not only when mc or fw sp are updated

---

src/modules/commander/Commander.cpp

A small fix to make clang-tidy stop complaining.

Improve readibility of ternary

---

Makefile
Tools/run-clang-tidy.py

Fixes the path, and works with python2/python3

make clang-tidy fixes

---

src/modules/attitude_estimator_q/attitude_estimator_q_main.cpp

When lockstep is enabled and LPE is not running, the attitude_estimator_q needs to publish ekf2_timestamps in order to signal to the simulator module that it has fully run.
This essentially fixes flying in lockstep when SYS_MC_EST_GROUP is 3.
Tested in SITL.

attitude_estimator_q: enable lockstep without LPE

---

ROMFS/px4fmu_common/init.d-posix/rcS
msg/vehicle_status_flags.msg
src/modules/commander/Commander.cpp
src/modules/commander/Commander.hpp
src/modules/commander/commander_params.c
src/modules/commander/state_machine_helper.cpp

The implementation before this change had two timeouts, a hard-coded timeout of 0.5 seconds as well as a by param configurable timeout with certain failsafe actions set.
This change aims to fix two problems:
1. The hard-coded offboard timeout can be triggered easily with sped up lockstep simulation. Since it is hard-coded it can't be adapted to the speed factor.
2. The offboard signal can time out but no action will be taken just yet. This means we end up in an in-between stage where no warning or failsafe action has happened yet, even though certain flags are set to a timeout state.
This patch aims to fix this by unifying the two timeouts to the existing configurable param. The convoluted double timeout logic is replaced by a simple hysteresis.
For anyone that has previously not changed …

commander: unify offboard timeouts

---

src/modules/vtol_att_control/tiltrotor.cpp

This PR changes some comments and a variable inside tiltrotor.cpp to indicate that also the rear motor(s) can be used for actuation in fixed-wing flight . 
No logical changes.

tiltrotor: improve comments and renaming of one variable

---

src/modules/logger/log_writer_file.cpp

Logger sometimes doesn't create a log file.
If the logger gets stopped at an unfortunate time, the `buffer.close_file()` function can be skipped, in the log_writer_file run loop.
The lock gets unlocked here
https://github.com/PX4/Firmware/blob/master/src/modules/logger/log_writer_file.cpp#L274-L277
which allows for `_buffers[0]._should_run` to change to false. The file didn't close yet since the `_buffers[0]._should_run` was true when that check happened.
The logger now does't have new data so the `notify()` is not called, which results in:
https://github.com/PX4/Firmware/blob/master/src/modules/logger/log_writer_file.cpp#L299
waiting indefinitely.
When the logger is started again, this while loop runs infinitely, waiting for the file to …

logger: fix thread deadlock

---

src/modules/logger/logger.cpp

this is very small change but can fix small annoying issue.
now when new log is opened, the string sent with mavlink log to ground concatenate the last digit of the filename. so its look like _"info: [logger] file: /fs/microsd/log/2020-03-06/17_23_4"_
its a bit annoying, the last digit missed... 
removed one space so the last digit will be shown
alternatives can be not to sent the full path at all, so the announcer will be shorter, and focus on what is important

logger - announce full file name (with the last missed digit)

---

ROMFS/px4fmu_common/init.d/airframes/50004_dfrobot_gpx_asurada
ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt
ROMFS/px4fmu_common/mixers/CMakeLists.txt
ROMFS/px4fmu_common/mixers/rover_diff_and_servo.main.mix

Added a new airframe for the DF Robot GPX:Asurada rover. This rover has 2 motors and one servo.
Added the airframe _50004_dfrobot_gpx_asurada_ and the mixer _rover_diff_and_servo.main.mix_. The airframe is based on the Generic Ground Vehicle airframe. The default PWM values for output 3 and 4 are changed because the included ESCs have other default values.
The mixer file was designed as follows: The servo controls the front wheels via PWM Output 2. The 2 motors control each rear wheel. The PWM Output 3 controls the right rear wheel and PWM Output 4 controls the left rear wheel. A light differential is integrated in the motors. So that the outer wheel runs faster than the inner wheel during steering.
**Describe …

Airframe and mixer for rover DF Robot GPX:Asurada

---

platforms/common/include/px4_platform_common/px4_work_queue/WorkItem.hpp
platforms/common/px4_work_queue/ScheduledWorkItem.cpp
platforms/common/px4_work_queue/WorkItem.cpp
platforms/common/px4_work_queue/WorkQueue.cpp
src/lib/mixer_module/mixer_module.cpp
src/modules/sensors/vehicle_acceleration/VehicleAcceleration.cpp
src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
src/modules/sensors/vehicle_imu/VehicleIMU.cpp

- ScheduledWorkItem::ScheduleClear: remove item from runnable queue
The existing behavior is unexpected: if the work item is already on the
runnable queue, it will still be triggered after a call to ScheduleClear().
This can lead to race conditions.
- uorb callbacks: fix unregister ordering to avoid race conditions 
Mostly only relevant for driver/module stopping, so not critical for current users.

work queue: fix some race conditions

---

src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp

Message in log:
> WARNING [load_mon] frsky_telementry low on stack! (276 bytes left)
It is found in:
https://github.com/PX4/Firmware/issues/9389
https://discuss.px4.io/t/warning-with-frsky-telemetry/12951
Describe:
If use telemetry by FrSky and GPS module when he will be work - then this message (warning) will be show in logs. Apparently a bit lacking if the variables get larger.
Increase stack size
Check on my FMU - Pixhawk 4

Up stack for frsky_telemetry

---

src/modules/logger/logged_topics.cpp

In the previous PR https://github.com/PX4/Firmware/pull/14018, we forgot to add logging of uORB messages from RPM sensor. This PR only enables this logging in FW.

Enable logging of RPM sensor messages

---

README.md

Add 'autogyro' to experimentally supported airframes in readme.

Update README, add autogyro to supported airframes

---

src/modules/fw_att_control/FixedwingAttitudeControl.cpp
src/modules/fw_att_control/FixedwingAttitudeControl.hpp
src/modules/fw_att_control/fw_att_control_params.c

Autogyro (and [rotorcrafts](https://en.wikipedia.org/wiki/Rotorcraft) in general) requires the possibility to disable airspeed scaling.. This pull-request adds a parameter ```FW_ARSP_SCALE``` to the possibility to disable airspeed scaling.
This parameter is two-state. Zero (0) disables airspeed scaling, 1 enables airspeed scaling. 
This issue is solved with setting variable ```_airspeed_scaling``` to 1 for disabling airspeed-scaling. 
https://github.com/ThunderFly-aerospace/PX4Firmware/blob/94feac2b5c96a6f5f102b00dbd7952c179dbab90/src/modules/fw_att_control/FixedwingAttitudeControl.cpp#L267-L268

Ability to disable airspeed scaling

---

msg/templates/urtps/Publisher.cpp.em
msg/templates/urtps/Publisher.h.em
msg/templates/urtps/RtpsTopics.cpp.em
msg/templates/urtps/RtpsTopics.h.em
msg/templates/urtps/Subscriber.cpp.em
msg/templates/urtps/Subscriber.h.em
msg/templates/urtps/microRTPS_timesync.cpp.em
msg/templates/urtps/microRTPS_timesync.h.em
msg/templates/urtps/msg.idl.em
msg/tools/generate_microRTPS_bridge.py
msg/tools/px_generate_uorb_topic_files.py

https://github.com/PX4/Firmware/pull/14297 added timesync for the microRTPS bridge, but was only tested using `px4_ros_com`. While testing it with the raw microRTPS bridge (not `px4_msgs` dependent), I have found that the member function naming was different from the ones generated when using the `px4_ros_com` generation, which resulted on compiler errors. This lead to the need of adding some getters and setters to access some required fields on the bridge itself.
So this PR:
1. makes sure that the timesync works in both `px4_ros_com` and the Firmware generated agent by adding getters and setters to class member functions (which access the msg fields);
2. adds a check for the Fast-RTPS lib version and uses it for the template code specialisation, instead of the FastRTPSGen version, which …

microRTPS: fix timesync support and general cleanup

---

platforms/common/include/px4_platform_common/tasks.h
src/modules/sensors/sensors.cpp
src/modules/sensors/voted_sensors_update.h

Running the `sensors` module out of the same WQ thread as the estimator and position controller is a bit safer and prevents potential priority and starvation issues. There will likely be a small increase in latency between `sensors` and `ekf2` execution (on average), but I expect it to be small and I'll verify on hardware before merging. This also saves a little bit of memory (~ 3 kB) and cpu (~1-1.5% total depending on the board).
I still intend to continue to carve up the sensors module into separate pieces per data type, but this is a safer thing to do short term. (eg https://github.com/PX4/Firmware/pull/14096)

sensors: move to WQ

---

msg/tools/uorb_rtps_message_ids.yaml

This was missed in https://github.com/PX4/Firmware/pull/14106. [`px4_ros_com` CI](https://travis-ci.com/github/PX4/px4_ros_com/jobs/296984584#L4442-L4445) immediately complained.
Note to self: need to add a check to make these mandatory and not just warn when the main message is added.

RTPS: add IDs to 'orb_test' related multitopics

---

Tools/sitl_run.sh

There is no need in day-to-day development to run verbose and it is preventing regular PX4 status output from properly rendering.

Gazebo: Do not run verbose

---

src/modules/mc_hover_thrust_estimator/zero_order_hover_thrust_ekf.cpp
src/modules/mc_hover_thrust_estimator/zero_order_hover_thrust_ekf.hpp
src/modules/mc_hover_thrust_estimator/zero_order_hover_thrust_ekf_test.cpp
src/modules/mc_pos_control/PositionControl/PositionControl.cpp
src/modules/mc_pos_control/PositionControl/PositionControl.hpp
src/modules/mc_pos_control/PositionControl/PositionControlTest.cpp
src/modules/mc_pos_control/mc_pos_control_main.cpp

Follows #14182
Summary of the changes:
- Use a low-passed value of the signed innovation test ratio to trigger
the state variance boost. The threshold of 0.2 has been chosen using log
replay and simulation scenarii.
- Do not reset the learned accel noise during a state variance boost.
After a few tests, this does not seem to help at all.
- Continue to learn the accel noise even if the measurement got rejected
to avoid ignoring sudden changes of noise
- Lower the acceleration noise time constant and increase min/max
values to avoid learning quickly a small variance that could temporary
destabilize the filter
- Update filter time constants. Increasing the speed of the residual lpf
improves the quality of the learned accel noise
Replay from log …

MC_HTE: Stability improvements

---

src/modules/fw_att_control/CMakeLists.txt
src/modules/fw_att_control/FixedwingAttitudeControl.hpp
src/modules/fw_att_control/ecl_controller.cpp
src/modules/fw_att_control/ecl_controller.h
src/modules/fw_att_control/ecl_pitch_controller.cpp
src/modules/fw_att_control/ecl_pitch_controller.h
src/modules/fw_att_control/ecl_roll_controller.cpp
src/modules/fw_att_control/ecl_roll_controller.h
src/modules/fw_att_control/ecl_wheel_controller.cpp
src/modules/fw_att_control/ecl_wheel_controller.h
src/modules/fw_att_control/ecl_yaw_controller.cpp
src/modules/fw_att_control/ecl_yaw_controller.h

Let's merge this back into PX4/Firmware. A large proportion of the code simply goes away if the work is handled in place.
ECL side (required first): https://github.com/PX4/ecl/pull/765
First step is to copy in place as is, then we can incrementally refactor easily with the submodule gone.

fw_att_control: move ecl/attitude_fw into fw_att_control

---

src/lib/flight_tasks/tasks/Auto/FlightTaskAuto.cpp
src/lib/flight_tasks/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.cpp
src/lib/flight_tasks/tasks/Orbit/FlightTaskOrbit.cpp
src/lib/flight_tasks/tasks/Utility/VelocitySmoothing.cpp
src/lib/mathlib/math/Functions.hpp
src/modules/mc_att_control/AttitudeControl/AttitudeControl.cpp
src/modules/mc_att_control/AttitudeControl/AttitudeControlTest.cpp
src/modules/mc_hover_thrust_estimator/zero_order_hover_thrust_ekf.cpp
src/modules/mc_pos_control/PositionControl/PositionControl.cpp
src/modules/rover_pos_control/RoverPositionControl.cpp

As a follow up to https://github.com/PX4/Matrix/pull/116/
- I want to take advantage of the very useful `canonical()` method that @kamilritz added for quaternions instead of implementing different variants in multiple places.
- I make sure the `sign()` function that I originally added to the mathlib is not a duplicate because it got copied for use in the matrix library here https://github.com/PX4/Matrix/pull/116/files#diff-54949d0fd557988a948ea903fee99e69R81. We can just use the one version that gets included.
- I added arbitrary antipodal quaternions in the AttitudeControl unit tests and made sure the tests fail without the "canonicalization" and pass with.
- I made sure the sign function is to the character the …

Use new quaternion.canonical(), reuse matrix::sign()

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

Follow up to #13973 reported and proposed by @dusan19.
Summary: The takeoff ramp can get stuck with an upwards velocity limit of NAN which is a valid value in the interface and means do not limit.
I propose to make sure just before the takeoff ramp calculation that the value is already the maximum and not NAN anymore. This leaves the interface for flight tasks and solves the problem described in #13973.
I admit it's not the nicest of all solutions but with the context that
- we want to move towards not constraining the velocity setpoint more than necessary in the middle of the position controller (which is what that variable was originally created for)
- having the takeoff ramp class used in in flight tasks
I …

mc_pos_control: hotfix for takeoff ramp stuck with NAN

---

.github/workflows/compile_linux.yml
boards/beaglebone/blue/src/CMakeLists.txt
boards/beaglebone/blue/src/spi.cpp

We temporarily lost linux builds (raspberry pi, beagle bone blue, etc) when moving the majority of the CI compile jobs from Jenkins to Github Actions.

github actions add linux builds

---

src/modules/mc_pos_control/mc_pos_control_params.c

Following the decision taken during today's DevCall, we're going to enable the hover thrust estimator by default for the beta to see if there are any issues. We can still disable just before the release if we see that something is really broken and that we can't fix it immediately.
FYI: @mrpollo

HTE: enable by default

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

@jkflying reported an effect I've seen before:
During a normal landing procedure the thrust gets first cut by the reaction to ground detected and then cut by the takeoff logic because the vehicle is back ready for another takeoff.
The problem is that the thrust and attitude limit while landing is in the loop order after the position controller ran and directly operates on the attitude setpoint skipping the position controllers minimum thrust limit. The takeoff thrust limitation on the other had is before the position controller and amends the input to it.
I'm unifying the thrust and attitude limit logic to be in one place where it already was for the takeoff. Both logics for takeoff and landing do these things in …

mc_pos_control: handle landed and takeoff setpoint limiting the same way

---

src/drivers/batt_smbus/batt_smbus.cpp
src/lib/drivers/smbus/SMBus.cpp

as in the commit note this pr do some staff related to the smbuss batt driver:
1. fixed hardfault if failed to create bus or device
2. fixed forgotten deleting failed device
3. fixed wrong calculation of max_cell_voltage
4. adding missed max_cell_voltage_delta
5. some code beautify
This changes has been tested with different device (BQ40Z80) than this driver has been written to (BQ40Z50). but it seems that the changes are still relevant.

Pr batt smbus stability

---

src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_messages.cpp

Continuing from https://github.com/PX4/Firmware/pull/14411.
We directly have the vibration metrics from each sensor now, so we don't need to get them from ekf2 (estimator_status).

Mavlink: split ESTIMATOR_STATUS and VIBRATION streams

---

src/modules/ekf2/ekf2_main.cpp
src/modules/ekf2/ekf2_params.c

This adds the ability to select range finder and/or optical flow fusion for terrain estimate.
Requires https://github.com/PX4/ecl/pull/783

Terrain estimator: Add sensor aiding bitmask

---

src/modules/logger/logger.cpp

write_all_add_logged_msg() requires at least some subscriptions to be added
initially, as this message is used to separate ULog header from data.
Fixes https://github.com/PX4/Firmware/issues/14422

logger: fix initial subscribing to topics

---

src/modules/mavlink/mavlink_mission.cpp

This PR handles incoming `MISSION_REQUEST_LIST` messages such that
they are no longer ignored if the previously requested mission has
sent all mission items but the ACK has never been received.
In addition, the wording of the warning message in case a new mission is requested while the old one hasn't finished downloading yet, is changed to be a bit more user friendly than "IGN REQUEST LIST: Busy", and its severity is reduced to INFO
Background: I'm trying to fix this user experience:

Robustify against IGN REQUEST LIST: Busy

---

boards/airmind/mindpx-v2/init/rc.board_sensors

hmc5883 is discontinued and draining out on inventory. qmc5883 is a drop-in replacement. This PR enable qmc5883 driver on all MindPX /MindRacer hardware.
enable qmc5883 driver on init scripts.
Tested against MindPX/MindRacer on v1.10.x and v1.11.x
This is a one line change on MindPX specific code. Should be pretty safe to merge.
@LorenzMeier @dagar @jinger26 Could you please help to make this into v1.10 & v1.11 release?
thanks.

Add onboard qmc5883 support for MindPX/MindRacer hardware

---

src/drivers/uavcannode/UavcanNode.cpp

Added satellite count, timestamp, covariance, and corrected integer overflow on lat/lon.
This supplements #14447

[bugfix] cannode GPS

---

src/modules/mavlink/mavlink_log_handler.cpp

In case of failed allocation of LogListHelper, the next lines can cause hardfault.
This didn't happen to me, but still its good practice to protect from that.
As more widen question, why LogListHelper is a class at all? why its not part of MavlinkLogHandler?
I think that removing as much as possible dynamic allocations is good practice.
My only thought is to save some RAM, and try to allocate it only if and when Log need to be download. LogListHelper is about 150 bytes.

return with error from _log_request_list() in case of failed allocation

---

src/drivers/distance_sensor/tfmini/TFMINI.cpp
src/include/containers/IntrusiveQueue.hpp

@limhyon noticed that tfmini was not working anymore on master, and traced it down to https://github.com/PX4/Firmware/blob/004d916095321c01c08719e12ca971d1e45a5453/src/drivers/distance_sensor/tfmini/TFMINI.cpp#L248 
The driver was suddenly not scheduled anymore, and removing the line 'fixed' it.
The underlying problem is however an incorrect implementation of `IntrusiveQueue::remove`, and it got revealed with https://github.com/PX4/Firmware/pull/14331.
Also, tfmini was scheduled at 10kHz which seems excessive given the sensor outputs data at 100Hz. It is now reduced to 500Hz.
@limhyon can you test this?

 fix IntrusiveQueue::remove: several bugs that led to improper state of the queue

---

Tools/sitl_run.sh
platforms/posix/cmake/sitl_target.cmake
platforms/posix/cmake/sitl_tests.cmake
test/mavsdk_tests/mavsdk_test_runner.py
test/mavsdk_tests/process_helper.py
test/mavsdk_tests/waitforgz.sh

Previously, the name of the world in gazebo always needed to match the name of the model. This has created a lot of world files that are identical but required just to spawn the model inside the world.
In gazebo, the world files are designed to be interchangable between models. Therefore, there is no need use the world file as a tool to spawn the models. 
This PR creates a logic in the `sitl_run.sh` script so that the model is spawned into gazebo, and not included as part of the world. The logic is as the following.
- If there is no <model>.world existing in the worlds directory, the model is spawned in `empty.world` 
- If there is a model specific world in the worlds directory, the world '<model>.world` is …

Spawn world separately from model in sitl gazebo

---

src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/mc_pos_control/mc_pos_control_params.c

fixes https://github.com/PX4/Firmware/issues/14456
The following condition is now enforced and the parameters are automatically corrected if a condition is violated:
`MPC_TILTMAX_LND <= MPC_TILTMAX_AIR <= 89 degrees`
I decided to restrict the parameter instead of adding a constraint in the position controller itself as the used needs to know that something was wrong in his setup. @MaEtUgR In addition to that, do you want to protect the `tanf` ? https://github.com/PX4/Firmware/blob/315135c07ec3c5cc111288562ca652b5dcda186e/src/modules/mc_pos_control/PositionControl/PositionControl.cpp#L199 and https://github.com/PX4/Firmware/blob/315135c07ec3c5cc111288562ca652b5dcda186e/src/modules/mc_pos_control/PositionControl/PositionControl.cpp#L176
Tested in SITL:
```
pxh> param set MPC_TILTMAX_LND 90 …
```

MPC: limit tilt to maximum safe value of 89 degrees

---

src/modules/commander/Commander.cpp
src/modules/commander/Commander.hpp

During the first few seconds after takeoff, the failure detector is allowed to trigger motor lockdown.
This is done for safety reasons to detect tipping-over or unstable tuning gains.
SITL test: takeoff with unstable gains
https://logs.px4.io/plot_app?log=b43c05ec-0330-414a-b069-41309ce13cf5
FYI @Jaeyoung-Lim

Flight termination: terminate if failure is detected on takeoff

---

.ci/Jenkinsfile-SITL_tests
.ci/Jenkinsfile-SITL_tests_ASan
.ci/Jenkinsfile-SITL_tests_coverage
.ci/Jenkinsfile-compile
.ci/Jenkinsfile-hardware
.circleci/config.yml
.github/workflows/bloaty.yml
.github/workflows/build_tests.yml
.github/workflows/ccpp.yml
.github/workflows/compile_linux.yml
.github/workflows/compile_nuttx.yml
.github/workflows/sitl_tests.yml
Jenkinsfile
Tools/docker_run.sh
Tools/setup/requirements.txt
appveyor.yml
msg/templates/urtps/Publisher.cpp.em
msg/templates/urtps/Publisher.h.em
msg/templates/urtps/RtpsTopics.h.em
msg/templates/urtps/Subscriber.cpp.em
msg/templates/urtps/Subscriber.h.em
msg/templates/urtps/microRTPS_timesync.h.em
msg/templates/urtps/msg.idl.em
msg/tools/generate_microRTPS_bridge.py
msg/tools/px_generate_uorb_topic_files.py

Supersedes and fixes the reported in https://github.com/PX4/Firmware/pull/14393.
@stmoon after some research I found that `packaging.version` is suited to these kind of comparisons, and so there's no need for parsing the major and minor to numerical. I tested this with FastRTPS master built and installed from source, matching the 1.10 version, and this works as it should. Please test on your side and thanks for the contribution!

microRTPS: use packaging.version to compare FastRTPS lib versions

---

msg/templates/urtps/Publisher.cpp.em
msg/templates/urtps/Subscriber.cpp.em

This is a quick fix for the agent code where the version verification was comparing a `major.minor.patch` with a `major.minor` (in this specific case, `1.8.2` with `1.8`), and the comparison was looking if they were equal, and they aren't. But the major and minor are, which is what matters here.

microRTPS: templates: check only the major and minor of FastRTPS

---

msg/templates/urtps/Publisher.cpp.em
msg/templates/urtps/Publisher.h.em
msg/templates/urtps/RtpsTopics.h.em
msg/templates/urtps/Subscriber.h.em
msg/templates/urtps/microRTPS_timesync.h.em
msg/templates/urtps/msg.idl.em
msg/tools/px_generate_uorb_topic_files.py

Apparently for 1.7 check is also required to do an adjustment on the comparison. Though since 1.7.2 is the latest release for ROS 2 Crystal (https://github.com/ros2-gbp/fastrtps-release#fastrtps-crystal---172-0), we are safe to use the patch version as well in the comparison.
Reported in `px4_ros_com` CI: https://travis-ci.com/github/PX4/px4_ros_com/jobs/301916502.

microRTPS: templates: use full version comparison when checking for version 1.7

---

platforms/posix/cmake/sitl_target.cmake

This PR adds a make target to spawn the `sonoma_raceway`
This is needed to enable https://github.com/PX4/sitl_gazebo/pull/441
[![Demo](https://img.youtube.com/vi/caPbIHKRUCs/0.jpg)](https://youtu.be/caPbIHKRUCs)

Add sonoma raceway world for SITL gazebo

---

src/modules/ekf2/ekf2_params.c

Depends on https://github.com/PX4/ecl/pull/770
@priseborough Parameter information is generated from the source tree. You made a docs change in the _generated_ source in the link above https://github.com/PX4/ecl/pull/770#issuecomment-601094939
This needs to be done in source.
Please check update correct.

[DO NOT MERGE]ekf2_params.c: EKF2_MAG_TYPE: Info about yaw without mag

---

src/drivers/camera_trigger/camera_trigger.cpp

Camera trigger has a polling rate of 200Hz. This PR lowers it to 20Hz which saves a tiny amount of CPU (0.25% on a pixracer board).
Was there a good reason for running this module so frequently?

camera_trigger: lower the polling rate from 200Hz to 20Hz

---

boards/px4/fmu-v5/optimized.cmake
src/lib/mag_compensation/CMakeLists.txt
src/lib/mag_compensation/MagCompensation.cpp
src/lib/mag_compensation/MagCompensation.hpp
src/lib/mag_compensation/mag_compensation_params.c
src/lib/mag_compensation/python/mag_compensation.py
src/modules/sensors/CMakeLists.txt
src/modules/sensors/parameters.cpp
src/modules/sensors/sensor_params_mag0.c
src/modules/sensors/sensor_params_mag1.c
src/modules/sensors/sensor_params_mag2.c
src/modules/sensors/sensor_params_mag3.c
src/modules/sensors/sensors.cpp
src/modules/sensors/voted_sensors_update.cpp
src/modules/sensors/voted_sensors_update.h

New feature to compensate compass for current/throttle:
Parameters for each axis have to be identified offline using the provided python script. If there is no current reading available, there is the option to compensate for thrust, only advisable if the relationship is linear for the given setup (In my tests I've observed that for some setups the relationship is linear and it works well, for others it is not).
Offline parameter identification:
Log from drone with parameters for current compensation applied:
https://logs.px4.io/plot_app?log=cf3ca047-ea1b-43c0-b8dd-a425bea539d4

Mag current/throttle compensation

---

src/lib/flight_tasks/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.cpp
src/lib/flight_tasks/tasks/AutoLineSmoothVel/TrajectoryConstraints.hpp

This fixes the issue that makes the drone slow-down even in straight lines due to the Z component being constrained to a really small value.
With master:
https://logs.px4.io/plot_app?log=f7efacca-6262-4a65-b4e2-39c7e4f2f5bb
This PR:
https://logs.px4.io/plot_app?log=1692b126-f195-48c1-8150-2b1b499a900e
Thanks @jkflying for the help.

AutoSmoothVel: Fix straight line autocontinue

---

ROMFS/px4fmu_common/init.d-posix/rc.replay

Currently, replay module params are loaded after starting ekf2 module in rc.replay. This causes log file being replayed and the replay session having mismatch in some ekf2 parameters.
Run 'replay tryapplyparams' before starting ekf2 module
Possibly fixes the issue #14260

apply replay module params before starting ekf2 module

---

boards/modalai/fc-v1/src/board_config.h

I somehow missed breaking RC input on the last commit when updating a define (RC_SERIAL_SINGLEWIRE).  This broke RC input.  
I'm also cleaning up two (currently) unused FSYNC pins pulling them to GND to be safe here (recommended by data sheet and caught recently).

modalai_fc-v1: Fix broken RC input, set unused FSYNC pins to 0

---

CMakeLists.txt

When not building for testing, test_mixer_multirotor is not available and causes a waraning with cmake 3.17:
```
This project specifies custom command DEPENDS on files in the build tree
that are not specified as the OUTPUT or BYPRODUCTS of any
add_custom_command or add_custom_target:
test_mixer_multirotor
```

cmake: fix warning

---

ROMFS/px4fmu_common/init.d/rc.interface
ROMFS/px4fmu_common/init.d/rc.io
ROMFS/px4fmu_common/init.d/rcS

rc.io is called from 2 places in rc.interface:
- `if [ $OUTPUT_MODE = io -o $OUTPUT_MODE = uavcan_esc ]`:
- `set OUTPUT_MODE io` is only set within USE_IO=yes, so removing
the check in rc.io has no effect.
- in case of UAVCAN, we also want the IO for RC, now covered in the next
case.
- Further down ('Start IO for RC input if needed.').
This is intended to start IO for RC only, when fmu is already started.
However the previous check '$USE_IO = yes' in rc.io prevented that.
In addition we don't start rc_input in case of $USE_IO = no.
Fixes no RC on Pixhawk 2 with SYS_USE_IO=0.
Tested on (with SYS_USE_IO=1/0):
- Pixhawk 4
- Pixhawk 4 mini
- Pixhawk Cube 2

rcS: fixes for SYS_USE_IO=0

---

boards/nxp/rddrone-uavcan146/nuttx-config/include/board.h
boards/nxp/rddrone-uavcan146/src/board_config.h
boards/nxp/rddrone-uavcan146/src/buttons.c
boards/nxp/rddrone-uavcan146/src/clockconfig.c
platforms/nuttx/src/px4/nxp/s32k1xx/hrt/hrt.c

Removed non-existing SW2 button
Fixed SW3 button pinmux
Added FlexCAN pin definition
hrt use external sirc clock
rtc use 32khz lpo clock
RTC & HRT uses the same input clock, which can be only be resetted using a power cycle. Yielding weird hrt.c behavior if when RTCCLKSEL is different then we expect.

rddrone-uavcan146 removed shared clock between hrt & rtc

---

src/modules/mc_att_control/AttitudeControl/AttitudeControl.cpp
src/modules/mc_att_control/AttitudeControl/AttitudeControl.hpp
src/modules/mc_att_control/AttitudeControl/AttitudeControlTest.cpp
src/modules/mc_att_control/mc_att_control.hpp
src/modules/mc_att_control/mc_att_control_main.cpp
src/modules/mc_att_control/mc_att_control_params.c

instead of infering the yaw weight from the gains which can lead to
unexpected results depending on the particular vehicle tuning.

AttitudeControl: let the user set yaw weight directly via parameter

---

platforms/nuttx/NuttX/tools/kconfig-conf
src/drivers/uavcan/CMakeLists.txt

Ubuntu 20.04 and latest Cygwin come with no Python 2 and no link
from python to python3. To not mess with the system we detect
python3 for seamless support.
- Use cmake's official FindPythonInterp detection also in libuavcan:
https://github.com/PX4/libuavcan/pull/3
- Detect `python3` in the kconfig script
We could cut python 2 in that script and directly call `python3`
I built PX4 successfully on Ubuntu 20.04 current daily.
SITL works out of the box with the existing ubuntu setup script:
`fmu-v5` needs this pr if the system is not adjusted with a link from `/usr/bin/python` to `python3`.
It was exactly the same problem that made the …

Support python3 only systems like Ubuntu 20.04

---

platforms/posix/cmake/sitl_target.cmake

This PR adds world targets for running SITL gazebo in worlds provided by the gazebo model database. To load the worlds, a internet connection is required.
- baylands
```
make px4_sitl gazebo_iris__baylands
```
[![Demo](https://img.youtube.com/vi/ir1fwOLcd4E/0.jpg)](https://youtu.be/ir1fwOLcd4E)
- yosemite
```
make px4_sitl gazebo_iris__yosemite
```
[![Demo](https://img.youtube.com/vi/7bAz36IsBko/0.jpg)](https://youtu.be/7bAz36IsBko)
- ksq_airport
```
make px4_sitl gazebo_iris__ksq_airport
```
The contribution for the new worlds were made by @ahcorde and @tfoote Thanks!

Add world targets for SITL gazebo

---

.github/workflows/bloaty.yml
.github/workflows/compile_linux.yml
.github/workflows/compile_nuttx.yml
.github/workflows/python_checks.yml
README.md

I think some status view of our main stages in Github Actions CI makes sense.

CI: Add GitHub actions status token for Nuttx targets and SITL tests

---

boards/airmind/mindpx-v2/src/spi.cpp

@rolandash 
The current l3gd20 driver doesn't use the data ready interrupt, but at some point I'll refactor it into the same form as the new InvenSense drivers which do use interrupts.

boards: airmind mindpx-v2 fix L3GD20 DRDY pin

---

msg/rpm.msg
src/drivers/rpm/pcf8583/PCF8583.cpp
src/drivers/rpm/pcf8583/parameters.c
src/modules/logger/logged_topics.cpp

* Duplicate data
Original message for our RPM counter contains duplicate data to uORB message. The original message contained rpm and Hz in one message. It was redundant. In this message, I would like to remove HZ values from the message.
I decided to maintain RPM because it is "bigger" number. Related to this is the question of whether to let unchanged data type or use some integer? Currently is used ```float32```. 
* Logging
Next modification contained in thes PR is to enable logging of RPM message. Here is screenshot of some log from our review fork (PR will follow)  
* Parameters
I also modified the parameter labels and the correct assignment to the group.

Remove duplicite data from RPM message and enable logging of RPM message

---

boards/omnibus/f4sd/default.cmake
boards/omnibus/f4sd/init/rc.board_sensors

I'm seeing 'mpu6000: FIFO empty: 49 events' increasing, but that is expected as there's no DRDY.
What's unfortunate is that it only goes to 1kHz rate loop due to the accel.
Tested on the BetaFPV Whoop.

Omnibus F4SD: switch over mpu6000 to new driver

---

platforms/common/i2c_spi_buses.cpp
src/drivers/magnetometer/ist8310/ist8310.cpp

Fixes https://github.com/PX4/Firmware/issues/14526

fix ist8310: pass I2C address to I2CSPIDriver

---

src/drivers/uavcan/sensors/sensor_bridge.cpp

Fixes case where a UAVCAN SensorBridge has callback channels available, but NuttX / uORB does not have an additional driver / topic instance available.
Previously, the callback would call the function get_channel_for_node() and receive a valid pointer, even though the backend driver initialization failed and no NuttX driver exists (i.e. attempt to register /dev/baro4 fails but the sensor bridge tries to use it anyways).
This bug applies to barometers and magnetometers connected to PX4 via UAVCAN.

uavcan: bug fix sensor bridge init failure

---

src/drivers/roboclaw/roboclaw_main.cpp

The old link was broken. This is a matching link from (what appears to be) the actual vendor. The version matches last version I could find on wayback machine.
Please merge as well as approve, as I can't .

roboclaw: Link to user manual updated

---

msg/mavlink_log.msg
src/modules/mavlink/mavlink_messages.cpp

This PR implements https://github.com/PX4/Firmware/issues/14169. A status message (msg/mavlink_log.msg) longer than 50 bytes is being chunked and multiple STATUSMESSAGE are sent. Now the only limitation is the buffer size in msg/mavlink_log.msg which got resized to 127 bytes in this PR, which is the same size as in log_message.
With sitl_gazebo and a modification of the line `mavlink_and_console_log_info(&mavlink_log_pub, "Takeoff detected");`. After takeoff I got the following status messages:
```
STATUSTEXT {severity : 6, text : [logger] file: ./log/2020-03-04/06_02_49.ulg, id : 0, chunk_seq : 0}
STATUSTEXT {severity : 6, text : Using minimum takeoff altitude: 2.50 m, id : 1, chunk_seq : 0}
STATUSTEXT {severity : …
```

Support for multi-part STATUSMESSAGE

---

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp

With this PR the fixed-wing position controller is changed to consume local instead of global position updates wherever possible (global position is still required for lat/long estimation feedback and thus for lateral position control). It thus enables the use of the altitude control flight mode for fixed-wing/VTOL systems that don't have a GPS sensor, or the GPS fails (thus eg fixes https://github.com/PX4/Firmware/issues/14243). 
Have a working fw altitude controller without global pos updates.
Move subscription of fw pos controller from global to local pos where possible.
Sitl tested with a VTOL and plane.
All credits to @dagar for initializing and implementing …

FW position controller: move from global to local position

---

msg/sensor_accel_fifo.msg
src/lib/drivers/accelerometer/PX4Accelerometer.hpp

Possible fix for the modalai test rack hard fault. The FIFO max sample calculations are based on the max gyro FIFO samples we can handle (currently 32), but this breaks down in the newer ICM4xxxx devices where accel is no longer 1/2 or 1/8th of the gyro data rate. Keeping sensor_accel_fifo and sensor_gyro_fifo sized the same is the simplest option.

sensor_accel_fifo increase to 32 samples

---

src/modules/commander/Commander.cpp

Previously if in a cycle only a disconnected battery status updated, the
battery health state would switch to unhealthy during that time.
Fixes intermittent 'Arming denied! Check battery' preflight failures on
v5x with 1 power module connected.

fix commander: need to copy all battery states in a cycle

---

src/lib/flight_tasks/tasks/Transition/FlightTaskTransition.cpp
src/lib/flight_tasks/tasks/Transition/FlightTaskTransition.hpp
src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/tiltrotor.cpp
src/modules/vtol_att_control/vtol_att_control_main.cpp
src/modules/vtol_att_control/vtol_att_control_main.h
src/modules/vtol_att_control/vtol_att_control_params.c
src/modules/vtol_att_control/vtol_type.cpp
src/modules/vtol_att_control/vtol_type.h

This PR enables following features for standard VTOL and tiltrotors:
- deceleration control via pitch during transition
- lateral control using fixed wing L1 controller
The above features can greatly improve path tracking during transition and reduce overshooting effects. Below you can see an example of a simple mission with the old state and the new state.
This PR also enables direction control in manual modes for both front and back-transition. This is very useful as you can still try to avoid obstacles during transitions.
This now needs a lot of testing in order to identify corner cases and improvements.
**Master:**
**This pull request:**

Towards controlled VTOL transitions

---

.ci/Jenkinsfile-SITL_tests
.ci/Jenkinsfile-SITL_tests_ASan
.ci/Jenkinsfile-SITL_tests_coverage
.ci/Jenkinsfile-compile
.ci/Jenkinsfile-hardware
.circleci/config.yml
.github/workflows/bloaty.yml
.github/workflows/build_tests.yml
.github/workflows/ccpp.yml
.github/workflows/compile_linux.yml
.github/workflows/compile_nuttx.yml
.github/workflows/sitl_tests.yml
Jenkinsfile
Tools/docker_run.sh
msg/templates/urtps/Publisher.cpp.em
msg/templates/urtps/Subscriber.cpp.em
msg/tools/generate_microRTPS_bridge.py

Before, we were weren't able to connect our microRTPS bridge to ROS2 Dashing, since the generated type naming from `fastrtpsgen` was incompatible with the type naming expected in ROS2. While I found a workaround solution for this by overwriting the type naming directly in the Publisher and Subscriber templates (https://github.com/PX4/Firmware/pull/13907), this was more an hack than an actual solution.
The solution was added first in a [PR to FastRTPSGen](https://github.com/eProsima/Fast-RTPS-Gen/pull/22), by adding an option to the script called `-typeros2`, which allows to generate the required type naming without having overwrite it in the Publisher and Subscriber templates.
Tested with …

microRTPS: use fastrtpsgen '-typeros2' option

---

src/drivers/px4io/px4io.cpp
src/drivers/telemetry/iridiumsbd/IridiumSBD.cpp
src/drivers/telemetry/iridiumsbd/IridiumSBD.h
src/drivers/uavcan/CMakeLists.txt
src/lib/parameters/flashparams/CMakeLists.txt
src/systemcmds/tests/CMakeLists.txt
src/systemcmds/tests/test_time.c

Follow up to https://github.com/PX4/Firmware/pull/13375 and https://github.com/PX4/Firmware/pull/13448.
There are less problems e.g. the new NuttX version is compatible. As discussed with @dagar the main remaining blocking issue is the linker script / flash region error like last time. It seems out of my reach to solve this by myself.
```
/usr/lib/gcc/arm-none-eabi/9.2.0/../../../../arm-none-eabi/bin/ld.gold: warning: creating a segment to contain the file and program headers outside of any MEMORY region
/usr/lib/gcc/arm-none-eabi/9.2.0/../../../../arm-none-eabi/bin/ld.gold: error: section .text overflows end of region flash
/usr/lib/gcc/arm-none-eabi/9.2.0/../../../../arm-none-eabi/bin/ld.gold: error: section …
```

Get PX4 compile on ARM GCC 9

---

msg/esc_report.msg
msg/esc_status.msg
src/drivers/dshot/dshot.cpp
src/drivers/mkblctrl/mkblctrl.cpp
src/drivers/tap_esc/tap_esc.cpp
src/drivers/uavcan/actuators/esc.cpp

This PR is the first piece required for start handling ESC failures.
Currently esc telemetry is not yet used in PX4 architecture to monitor and react to possible ESCs failures.
esc_status field in esc_report.msg is currently defined as _State of ESC - depend on Vendor_  
Which makes the development of a generic logic to handle such states very hard.
By introducing a standard convention of ESCs states that the various drivers can report would allow PX4 architecture to actually use this info for detecting and reacting to ESC failures.
To do so, an additional bitfield, **failures** (uint8), has been introduced with a subset of common ESC failures that a "smart esc" might report.
To indicate which ESCs are ready to …

msg/esc_status: added fields to handle ESCs failures

---

test/mavsdk_tests/configs/sitl.json
test/mavsdk_tests/mavsdk_test_runner.py
test/mavsdk_tests/process_helper.py

This fixes the issue where the last lines of the log output was not printed in case of error or on the verbose setting. This meant that essentially the actual test error was not printed.
The fix involves two parts:
1. Firstly collect the output again even if a process has exited.
2. Collect all lines at once and not one line per iteration.
This also raises the timeout for the gazebospawn command.

Fix MAVSDK testing output

---

msg/tools/generate_microRTPS_bridge.py

Fix required after `px4_ros_com` CI failed for ROS2 Bouncy and Crystal.

microRTPS: only use '-typeros2' FastRTPSGen option for Dashing and later ROS2 distros

---

Tools/upload.sh

While our bootloader updated, we've simplified naming scheme so we update upload.sh to make the script detect boards properly.
Tested with different boards.

UVify bootloader was not recognized properly because of wildcard

---

src/lib/avoidance/ObstacleAvoidance.cpp
src/lib/avoidance/ObstacleAvoidanceTest.cpp

Previously the bezier curve tracking for the avoidance interface scaled the velocities in the wrong direction.
This fixes it, and also adds a unit test to make sure the velocity for the full bezier interface is working.

Fix bezier scaling

---

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueue.hpp
platforms/common/px4_work_queue/WorkQueue.cpp

This is only a precaution, not something that seems to actually be happening normally.

px4_work_queue: sem_wait add loop as the wait may be interrupted by a signal

---

ROMFS/px4fmu_common/init.d/rcS
boards/bitcraze/crazyflie/syslink/syslink_main.cpp
boards/px4/fmu-v2/default.cmake
boards/px4/fmu-v3/default.cmake
boards/px4/fmu-v4/default.cmake
boards/px4/fmu-v4pro/default.cmake
boards/px4/fmu-v5/default.cmake
boards/px4/fmu-v5x/default.cmake
msg/battery_status.msg
src/drivers/power_monitor/ina226/ina226.cpp
src/drivers/power_monitor/voxlpm/voxlpm.cpp
src/drivers/uavcan/sensors/battery.cpp
src/lib/battery/battery.cpp
src/lib/battery/battery.h
src/lib/battery/module.yaml
src/modules/battery_status/analog_battery.cpp
src/modules/battery_status/analog_battery.h
src/modules/battery_status/battery_status.cpp
src/modules/commander/Commander.cpp
src/modules/esc_battery/CMakeLists.txt
src/modules/esc_battery/EscBattery.cpp
src/modules/esc_battery/EscBattery.hpp
src/modules/simulator/simulator_mavlink.cpp

This PR includes two things:
1. Addition of `esc_battery` module to publish the `battery_status` from `esc_status`.
2. Refactoring of how `BAT%d_SOURCE` param is used. The param is now checked inside of the battery library. If the source set matches the data fed to the library, then it is published, otherwise it isn't.

Add battery status from ESCs, refactor battery source param

---

src/drivers/imu/invensense/mpu6000/MPU6000.cpp
src/drivers/imu/invensense/mpu6500/MPU6500.cpp
src/drivers/imu/invensense/mpu9250/MPU9250.cpp

In the new InvenSense drivers we use the data ready interrupts if they're available. As a precaution there's also a backup scheduled call that in regular operation is pushed back another 10 milliseconds.
This PR fixes that logic in the mpu6000/mpu6500/mpu9250. It's a failure case I've never actually seen, but it's not impossible (eg sensor brownout, external IMU with intermittent connection, etc).

new mpu6000/mpu6500/mpu9250 always schedule backup cycle if using data ready

---

src/modules/mavlink/mavlink_receiver.cpp

Fills offboard attitude thrust setpoints with a coaxial airframe.
The thrust setpoint was silently ignored. We should either cast _mavlink->get_system_type() to the enum type to make sure all cases are covered, or add a default case that rejects the offboard mode.

Enable offboard attitude for coaxial airframes

---

msg/templates/urtps/Publisher.cpp.em
msg/templates/urtps/Subscriber.cpp.em

For a raw usage of the microRTPS bridge (without ROS2), the generated listener topic Subscriber wasn't matching the topic name we have on the Publisher/Subscriber template. This fixes it by removing the extra underscore in the naming.

microRTPS: fix topic name when ROS2 is not being used

---

src/drivers/uavcannode/UavcanNode.cpp

Fix units on temperature publication in UavcanNode RawAirData (Message definition specifies all temperature units as Kelvin).

uavcannode: Fix Kelvin/Celcius in RawAirData pub

---

integrationtests/python_src/px4_it/mavros/mavros_offboard_attctl_test.py

update the sitl_gazebo submodule to get more realistic rotor drag for iris: https://github.com/PX4/sitl_gazebo/pull/451

update sitl_gazebo to include realistic iris drag coeff

---

src/modules/commander/Commander.cpp
src/modules/commander/Commander.hpp

This brings 2 fixes:
- set _have_taken_off_since_arming when !landed upon arming
If arming and already !landed, _have_taken_off_since_arming will not be set
and thus auto-disarm after 10s will be triggered (with default config).
This can only happen due to quick state changes, as land detector generally
sets landed=true if !armed.
- set _was_landed before _land_detector topic update
Before _was_landed was set to the same value as the current
_land_detector.landed, thus outside of the update condition,
_was_landed && !_land_detector.landed could never be true.
This affects setting the home position, which is now set upon arming AND
upon takeoff.
According to the existing code this is how it was intended to work (not sure if we want that though).

Logic fixes in commander (takeoff data)

---

Tools/setup/arch.sh

This makes installation a lot faster and less error prone.
Use @`bionade24`'s arch binary repository https://wiki.archlinux.org/index.php/Unofficial_user_repositories#oscloud
I tested on two Manjaro machines. More feedback welcome @julianoes @bresch @DanielePettenuzzo

arch.sh: use community binary repository for gazebo

---

test/mavsdk_tests/mavsdk_test_runner.py
test/mavsdk_tests/process_helper.py
test/mavsdk_tests/waitforgz.sh

This is an attempt to workaround the gz spawn timeout in CI.
Let's just hard-code a sleep before spawning the model.

mavsdk_tests: remove waitforgz helper, add sleep

---

ROMFS/px4fmu_common/init.d/airframes/4016_holybro_px4vision
src/modules/mc_pos_control/mc_pos_control_params.c

During flight testing the PX4Vision, we noticed that the default values for `MPC_LAND_ALT1` and `MPC_LAND_ALT2` are rather tuned towards large vehicles and yield unpleasant pilot experience on such a small racer.
This PR adjusts them to values that are more reasonable for a racer.

PX4Vision: tune MPC_LAND_ALT

---

ROMFS/px4fmu_common/init.d/rc.mc_defaults

As discussed in the estimation call with @priseborough and @bresch :
Multicopter position controlled flight is in our experience always <1g. Acrobatic flying definitely exceeds the acceleration but if control doesn't rely on the GPS velocity and position for navigation we don't expect any problems.
I changed the parameter default to 6 - <1g for multicopter defaults only. 
We are successfully flying this setting on multiple platforms.
While looking at the configuration for fixed wing I saw the fixed wing defaults configuring 8 - <4g
https://github.com/PX4/Firmware/blob/15332a7e56d189bcb52605ce5181e16bf898d799/ROMFS/px4fmu_common/init.d/rc.fw_defaults#L52
but VTOL not …

GPS Dynamic model default <1g for multicopter

---

boards/av/x-v1/nuttx-config/scripts/script.ld
boards/modalai/fc-v1/nuttx-config/scripts/script.ld
boards/mro/ctrl-zero-f7/nuttx-config/scripts/script.ld
boards/mro/x21-777/nuttx-config/scripts/script.ld
boards/px4/fmu-v5/nuttx-config/scripts/script.ld
boards/px4/fmu-v5x/nuttx-config/scripts/script.ld

- this doesn't currently change anything, but gets us ready to start
experimenting with using the small amount (16 kB) of instruction tightly coupled memory
on STM32F7
- the .ramfuncs section works with NuttX CONFIG_ARCH_RAMFUNCS
- these are all identical for stm32f76* and stm32f77* other than the mRo control zero which has another 2 reserved sectors after the bootloader

boards: STM32F76xxx/STM32F77xxx linker add ITCM RAM and .ramfuncs handling

---

src/modules/commander/Commander.cpp

If the user disconnects USB we reboot the system to bring it back into a nominal condition before arming. Otherwise we would either have the USB stack running without a cable connected (code running for no reason, which is violating the principle of not running unnecessary code in aviation). Or we would not allow to arm at all if USB was ever connected, which can be confusing if the system is powered off a battery.

Commander: Add more documentation around USB reboots

---

src/modules/vtol_att_control/tiltrotor.cpp
src/modules/vtol_att_control/tiltrotor.h
src/modules/vtol_att_control/tiltrotor_params.c

As some tiltrotor systems need a certain tilt angle of their motors in order to spin up freely,
this PR introduces an additional parameter VT_TILT_SPINUP and sets the motor tilt to
this value if disarmed or within 1s since arming. It will then over the next 0.7s ramp the motor tilt to the nominal hover tilt. 
This spinup phase is disabled if the VT_TILT_SPINUP param is set to 0 (default), the tilt stays at hover tilt in this case. 
Test data / coverage
Bench and flight tested.
Replaces https://github.com/PX4/Firmware/pull/14209.

Tiltrotor VTOL: add spinup phase

---

src/modules/navigator/navigator_main.cpp

This pr fixes the following three issues when repositioning in navigator:
- if the "go to" location sent by QGC was outside a geofenced area and the geofence failsafe was set to HOLD then the drone would just exit the geofence and reach destination
- if the "go to" location sent by QGC was inside a geofenced area, the geofence failsafe was set to HOLD and the path to get to destination went outside the geofence, the drone would just go out of the geofence and then enter again to reach destination
- after an auto takeoff from QGC then user could not perform an altitude change because the current waypoint was still set to Nan for lat and lon after a takeoff. To make it work the user would have to repeat the change altitude action twice
These three issues where fixed by the following …

Pr fix various reposition bugs in navigator module

---

Tools/px4airframes/markdownout.py

Fixes https://github.com/PX4/px4_user_guide/pull/718
This improves the (generated) introductory text in the airframes reference:
1. Provides link to generator script. Not essential, but makes it easier for anyone wanting to improve the generated docs. 
2. Fixes up statement about AUX ports - their existence has nothing to do with being pixhawk or not. Note that I specified PWM AUX ports because of course we might map AUX to some other bus in future.

airframe markdown script: Improve generated information text

---

src/modules/rc_update/params.c

There are a couple of action switches which trigger a behavior if mapped. The behavior is only triggered if the switch is flipped all the way down. So for 3-position switches (1-2-3) only at position 1.
The action switches behaved differently on manual_control_setpoint due to different thresholds. Example:
RTL switch:
switch up: manual_control_setpoint.return_switch=1 (on)
switch middle: manual_control_setpoint.return_switch=3 (off)
switch down: manual_control_setpoint.return_switch=3 (off)
kill switch:
switch up: manual_control_setpoint.return_switch=1 (on)
switch middle: manual_control_setpoint.return_switch=1 (on) -> not correct
switch down: manual_control_setpoint.return_switch=3 (off)
This PR changes the thresholds to be consistent and correct.

RC action switch threshold defaults

---

src/drivers/imu/invensense/icm20602/ICM20602.hpp
src/drivers/imu/invensense/icm20602/icm20602_main.cpp
src/drivers/imu/invensense/icm20608g/ICM20608G.hpp
src/drivers/imu/invensense/icm20608g/icm20608g_main.cpp
src/drivers/imu/invensense/icm20689/ICM20689.hpp
src/drivers/imu/invensense/icm20689/icm20689_main.cpp
src/drivers/imu/invensense/icm40609d/ICM40609D.hpp
src/drivers/imu/invensense/icm40609d/icm40609d_main.cpp
src/drivers/imu/invensense/icm42688p/ICM42688P.hpp
src/drivers/imu/invensense/icm42688p/icm42688p_main.cpp
src/drivers/imu/invensense/mpu6000/MPU6000.hpp
src/drivers/imu/invensense/mpu6000/mpu6000_main.cpp
src/drivers/imu/invensense/mpu6500/MPU6500.hpp
src/drivers/imu/invensense/mpu6500/mpu6500_main.cpp
src/drivers/imu/invensense/mpu9250/MPU9250.hpp
src/drivers/imu/invensense/mpu9250/MPU9250_AK8963.hpp
src/drivers/imu/invensense/mpu9250/mpu9250_main.cpp

- remove leftover Start()
- remove "reset" from command line (stop + start is sufficient)
Reset wasn't even used during development, so I'd rather not even expose it and then drop the custom_method plumbing (start + stop is equivalent). Less is more.

imu/invensense: minor cleanup

---

src/modules/mc_pos_control/PositionControl/PositionControl.cpp
src/modules/mc_pos_control/mc_pos_control_main.cpp

The sign of the acceleration state passed to the position controller is wrong because it's only used as the derivative of the error in the controller which is opposite sign. The variable should contain what the name says and not the negative value because of how it's used.
fixes #13887
Non-functional change, just change the sign in the correct place to avoid further confusion.
Untested but I checked it's the only place the variable is used.

mc_pos_control: correct sign of acceleration state

---

.github/workflows/sitl_tests.yml
platforms/posix/src/px4/common/main.cpp
test/mavsdk_tests/process_helper.py

Work to get core dumps, backtrace in CI and get core dumps saved as a GitHub workflow artifact.

Add core dumps to CI for MAVSDK SITL tests

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

Currently ekf2 publishes `vehicle_local_position` at 125 Hz (8 ms interval). The multicopter position controller is scheduled on new `vehicle_local_position` publications, but we limit it by setting the orb interval. With the current 50 ms interval the module actually ends up running at a variable rate. 
At a glance I don't see anything that assumes a constant rate, so this might be one of those things that only feels like the right thing to do.

mc_pos_control: align updates with ekf2

---

src/drivers/imu/invensense/icm20608g/ICM20608G.cpp
src/drivers/imu/invensense/icm20689/ICM20689.cpp
src/drivers/imu/invensense/icm20689/ICM20689.hpp

The InvenSense icm20608g and icm20689 don't have a FIFO watermark interrupt, but they do have a data ready interrupt and the ability to get the current FIFO count in the same large transfer as the actual FIFO data. So instead of manually checking the FIFO count before every transfer (costs ~ 1-3% cpu) we trust the data ready counts and then verify things are in sync after the large transfer (fifo count + fifo contents).
As a precaution this PR lowers the threshold for forcing a manual FIFO count check BEFORE the large transfer. Forcing the check if out of sync by 2 (or more) samples makes sense because we always do transfers in multiples of 2 (gyro samples per accel). 
The other small cosmetic changes are keeping the icm20608g and icm20689 in sync (they're nearly identical). 
Bench tested …

icm20608g/icm20689: force FIFO count check sooner

---

boards/px4/fmu-v4/init/rc.board_sensors
boards/uvify/core/init/rc.board_extras

Clearly `sensor_reset` seems out of place now.

boards: fmu was renamed pwm_out

---

src/modules/sensors/vehicle_acceleration/VehicleAcceleration.cpp
src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp

With the filter check based on a certain number of samples it takes 4 times longer (or more) in SITL (250 Hz IMU) vs a real vehicle (1 or 2 kHz IMU). 
- fixes #14303

sensors/vehicle_angular_velocity: check filter based on time threshold instead of samples

---

src/systemcmds/tests/test_microbench_hrt.cpp
src/systemcmds/tests/test_microbench_math.cpp
src/systemcmds/tests/test_microbench_matrix.cpp
src/systemcmds/tests/test_microbench_uorb.cpp

This seems to produce comparable results and doesn't choke things as badly on certain configurations like stackcheck where the system is already very heavily loaded.

tests: microbenchmarks reduce iterations and sleep inbetween

---

boards/px4/fmu-v4pro/init/rc.board_sensors

- board has either an icm20602 or icm20608g, not both
- probe all typical externally compasses

boards: px4/fmu-v4pro cleanup rc.board_sensors

---

src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/tiltrotor.cpp

Allows the user to manually control attitude during transitions.

vtol: do not control deceleration during backtransition in stabilize mode

---

src/lib/parameters/param_translation.cpp

On Linux it can be non-zero.
Fixes https://github.com/PX4/Firmware/issues/14649

fix param_translation: set address to 0 only on NuttX

---

src/modules/commander/Arming/PreFlightCheck/CMakeLists.txt
src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp
src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.hpp
src/modules/commander/Arming/PreFlightCheck/checks/manualControlCheck.cpp
src/modules/commander/Arming/PreFlightCheck/checks/preArmCheck.cpp

New preflight checks:
- for home position: There were quite some cases where people took off in altitude without a valid home position and then had issues with RTL. Check is disabled by default, so no behavior change.
- for action switches: Not allowed to arm anymore if KILL, RETURN, GEAR or TRANSITION switch is active.

Preflight checks: home position and action switches

---

src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_main.h

Possible quick work around for https://github.com/PX4/Firmware/issues/12957.
This pull request rearranges the mavlink helpers slightly to shift the the buffer, should_transmit, error count updates into the single final mavlink `mavlink_end_uart_send` call rather than each `mavlink_send_uart_bytes` (called 3 times per mavlink message send).
This is accomplished by unifying some of the uart/udp logic differences. Each write (`mavlink_send_uart_bytes`) goes into a buffer, then that buffer is written out once (`mavlink_end_uart_send`). This should prevent broken mavlink messages from going out over the wire, and will also be slightly more efficient by minimizing work for each send.
TODO:

mavlink send helpers refactor to prevent writing partial messages

---

src/modules/commander/Arming/PreFlightCheck/CMakeLists.txt
src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp
src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.hpp
src/modules/commander/Arming/PreFlightCheck/checks/airframeCheck.cpp

This adds a preflight check when a VTOL airframe is configured on a fmu-v2 where VTOL is no longer included.
Resolves https://github.com/PX4/Firmware/issues/14381.

commander: add check for VTOL airfame on fmu-v2

---

boards/mro/x21/init/rc.board_defaults
boards/px4/fmu-v2/init/rc.board_defaults
boards/px4/fmu-v3/init/rc.board_defaults

The new Invensense IMU drivers have the ability to actually run the driver at a slower (or faster) rate without sacrificing any raw data. The rate at which the driver runs and empties the FIFO is the maximum inner loop (rate controller) update rate (current default is 1000 Hz). Regardless of the configured rate the full FIFO with 8 kHz raw data is transferred (with DMA). 
With focus shifting to newer boards based on stm32f7/h7/imxrt/etc (pixhawk 4 launched 2 years ago) and quite a lot of development activity things have been getting tighter on older boards like fmu-v2/v3. For example, current master on a Pixhawk 2 Cube configured as generic multicopter only has around 15% idle cpu (depending on exact configuration). Configured as a VTOL (quadplane, tiltrotor, etc) it can easily drop below …

[RFC] Consider setting default IMU_GYRO_RATEMAX to 400 Hz

---

ROMFS/px4fmu_common/init.d-posix/rcS
src/modules/commander/Arming/PreFlightCheck/CMakeLists.txt
src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp
src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.hpp
src/modules/commander/Arming/PreFlightCheck/checks/cpuResourceCheck.cpp
src/modules/commander/commander_params.c

We had cases where people were accidentally taking of with a too highly loaded system even already when it was disarmed. There can be a lot of reasons like custom WIP changes or a combination of board and configuration that exceeds the expected load.
I add a preflight check that will prevent arming depending on CPU load because it's a low hanging fruit and would have saved crashes before.
Untested so far, SITL doesn't provide `cpuload`, not even fake so I'll test it on a pixhawk 4.

PreFlightCheck: add checks for CPU load

---

src/lib/flight_tasks/tasks/Offboard/FlightTaskOffboard.cpp

I guess Dennis didn't change it after copying the file skeleton...

FlightTaskOffboard: fix header comment

---

ROMFS/px4fmu_common/init.d-posix/1060_rover
ROMFS/px4fmu_common/init.d-posix/1070_boat
ROMFS/px4fmu_common/init.d/airframes/50000_generic_ground_vehicle
ROMFS/px4fmu_common/init.d/airframes/50002_traxxas_stampede_2wd
ROMFS/px4fmu_common/init.d/airframes/50003_aion_robotics_r1_rover
ROMFS/px4fmu_common/init.d/airframes/50004_dfrobot_gpx_asurada
src/modules/rover_pos_control/RoverPositionControl.cpp
src/modules/rover_pos_control/rover_pos_control_params.c

Currently the rover speed pid initialisation reverse the integral and derivative parameters in the function pid_set_parameters. And all the rover related airframes are using GND_SPEED_I = 0.001 and GND_SPEED_D = 3.
I swapped the Ki and Kd parameters in RoverPositionControl.cpp and in the airframes files. I also set 3 and 0.001 as default value for GND_SPEED_I and GND_SPEED_D parameters.
Tested with gazebo_rover.

Rover speed pid Ki and Kd parameters inversion

---

src/include/containers/List.hpp
src/systemcmds/tests/test_IntrusiveQueue.cpp
src/systemcmds/tests/test_List.cpp

- test for the bug found and fixed in https://github.com/PX4/Firmware/pull/14423
```
INFO  [tests] RUNNING TEST: test_reinsert
ERROR [tests] Assertion failed: result not true - sz2 > sz1 (../../src/systemcmds/tests/test_IntrusiveQueue.cpp:368)
ERROR [tests] TEST FAILED: test_reinsert
```
```
INFO  [tests] RUNNING TEST: test_reinsert
INFO  [tests] TEST PASSED: test_reinsert
```

tests: IntrusiveQueue test re-insert case

---

ROMFS/px4fmu_common/init.d-posix/rcS
src/modules/commander/commander_params.c

Multiple people reported that SITL wasn't arming anymore because the CPU load check was failing and that's because the parameter to disable the check in SITL is only set when the parameters are reset e.g. clean build.
I set the parameter all the time now to prevent more people running into the problem.
SITL should also publish a CPU load but this is the hot fix.
I tested locally with an earlier configuration already built to reproduce the problem without the change and have it fixed with the change.
#14570

posix rcS: always disable CPU load check in SITL

---

Tools/px_uploader.py

Avoids endless looping, and is mostly useful when used in automated upload scripts.

Tools/px_uploader: exit if unsuitable board is connected

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

fixes https://github.com/PX4/Firmware/issues/14704
The hover thrust estimator (HTE) starts to run after the first thrust setpoint is published. Until then, the feedforward of the vertical velocity controller was unitialized (= 0). This is now set to hover thrust parameter until the estimate is available.
Tested in SITL:
**Before**
**After**

MPC: initialize hover thrust with parameter even if using HTE

---

.github/ISSUE_TEMPLATE/1_Bug_report.md
README.md
ROMFS/px4fmu_common/init.d/airframes/3031_phantom
ROMFS/px4fmu_common/init.d/airframes/3033_wingwing
ROMFS/px4fmu_common/init.d/airframes/4051_s250aq
ROMFS/px4fmu_common/init.d/airframes/4052_holybro_qav250
Tools/px_uploader.py
src/drivers/distance_sensor/leddar_one/leddar_one_main.cpp
src/drivers/distance_sensor/ll40ls/ll40ls.cpp
src/drivers/distance_sensor/ll40ls_pwm/ll40ls.cpp
src/drivers/distance_sensor/sf0x/sf0x_main.cpp
src/drivers/distance_sensor/sf1xx/sf1xx.cpp
src/drivers/distance_sensor/teraranger/teraranger_main.cpp
src/drivers/distance_sensor/tfmini/tfmini_main.cpp
src/modules/ekf2/ekf2_main.cpp
src/modules/micrortps_bridge/README.md
src/modules/replay/Replay.cpp
src/modules/vmount/vmount.cpp
src/systemcmds/ver/ver.c

The old link format goes to a redirect, which takes you to the v1.9 version of the docs. I think linking explicitly to docs master branch is generally better.

Fix up doc links to point to master branch

---

Tools/px4.py

AFAIK this is only used by the PX4 homebrew formulae, though it makes sense to at least make it usable and correct.

Fix px4.py

---

Tools/setup/ubuntu.sh

Removing the modemmanager was done to allow firmware upload on any board. However this not needed when working with many boards because they are registered with the manager, and it is not good practice to just remove a feature someone might be using.
So removing this, and will add a note in the docs. If we run into specific boards that aren't covered we'll request they be registered.
As discussed in https://github.com/PX4/Firmware/pull/13111

ubuntu.sh: No automatic removal of modemmanager

---

src/lib/flight_tasks/tasks/AutoMapper/FlightTaskAutoMapper.cpp
src/lib/flight_tasks/tasks/FlightTask/FlightTask.cpp
src/lib/flight_tasks/tasks/FlightTask/FlightTask.hpp
src/lib/flight_tasks/tasks/ManualAltitude/FlightTaskManualAltitude.cpp
src/lib/flight_tasks/tasks/ManualPosition/FlightTaskManualPosition.cpp
src/modules/mc_pos_control/PositionControl/PositionControl.hpp

Adjusting the tilt limit can lead to diverging position control and should only be used by setting a sanity limit for the controller and not to adjust during the descent phase of a Land or RTL. Otherwise it leads to flyaways in important failsafe modes when there's stronger disturbance e.g. wind.
I removed all occurances where flight tasks sets a tilt limit. All of them except for the one in AutoMapper's `_prepareLandSetpoints()` were setting the maximum redundantly. The auto land point one was causing the position control divergence on RTL and Land descend.
As discussed with @RomanBapst the goal landing strategy is to relax xy position control and ramp down the thrust gradually …

FlightTasks: do not adjust tilt limit of the position control

---

src/lib/flight_tasks/FlightTasks.cpp
src/lib/flight_tasks/FlightTasks.hpp
src/lib/flight_tasks/tasks/AutoFollowMe/FlightTaskAutoFollowMe.cpp
src/lib/flight_tasks/tasks/AutoMapper/FlightTaskAutoMapper.cpp
src/lib/flight_tasks/tasks/Descend/FlightTaskDescend.cpp
src/lib/flight_tasks/tasks/Failsafe/FlightTaskFailsafe.cpp
src/lib/flight_tasks/tasks/FlightTask/FlightTask.cpp
src/lib/flight_tasks/tasks/FlightTask/FlightTask.hpp
src/lib/flight_tasks/tasks/ManualAltitude/FlightTaskManualAltitude.cpp
src/lib/flight_tasks/tasks/Offboard/FlightTaskOffboard.cpp
src/lib/flight_tasks/tasks/Orbit/FlightTaskOrbit.cpp
src/lib/flight_tasks/tasks/Transition/FlightTaskTransition.cpp
src/lib/flight_tasks/tasks/Utility/ManualVelocitySmoothingXY.hpp
src/lib/flight_tasks/tasks/Utility/ManualVelocitySmoothingZ.hpp

fixes https://github.com/PX4/Firmware/issues/14677
During a loss of GPS data when using GPS as primary height source, the height is reset to baro and the local position gets invalid at the same time. This triggers a switch to altitude flight task and a setpoint reset.
This combination of events had the effect to ignore the height reset, the large sudden height error could create an abrupt change of altitude or even a crash.
The ekf2 reset is now done at the beginning of each update call.
The ekf reset without a correct compensation of the setpoint can lead to a crash.

FlightTask: Fix ekf2 reset race condition during task switch

---

src/modules/land_detector/MulticopterLandDetector.cpp
src/modules/land_detector/MulticopterLandDetector.h

HTE runs based on the position controller so, even if we wish to use the estimate, it is only available in altitude and position modes.
Therefore, we need to always initialize the `hoverThrottle` using the hover thrust parameter in case we fly in stabilized, otherwise the hover thrust is assumed 0.

MCLandDetector: fix low thrust detection in stabilized mode

---

src/drivers/drv_pwm_output.h
src/modules/vtol_att_control/vtol_att_control_main.cpp
src/modules/vtol_att_control/vtol_att_control_main.h
src/modules/vtol_att_control/vtol_att_control_params.c
src/modules/vtol_att_control/vtol_type.cpp
src/modules/vtol_att_control/vtol_type.h

This PR enables the use of the FMU (AUX) output for the multicopter motors on standard VTOL and tiltrotors.
The device path is needed to apply PWM limits on the motors that are not
used for FW flight (switch them off). With this parameter the device path can be set
to either IO or FMU, depending on whether the motors are on the IO or FMU port.

VTOL: add parameter to set the PWM_OUTPUT_DEVICE_PATH

---

src/modules/vmount/vmount_params.c

There are 6 AUXes that could be possibly used to control vmount's roll, pitch and yaw, but for some reason the maximum values of corresponding parameters were limited to 5. So you can't just choose AUX6 without forcing parameter save.
Changed 5 to 6.
Force save of parameter in an old QGCs or using Mavlink console to set it.
It builds.

Fixes max AUX number for MNT_MAN_ROLL, PITCH and YAW parameters

---

src/modules/navigator/mission_block.cpp

Without this PR, a fixed wing drone will loiter (with LOITER_TIME) indefinitely around the waypoint if no loiter radius is set, because it never "reaches" the waypoint.

fix loiter_time for FW missions

---

src/lib/drivers/accelerometer/PX4Accelerometer.cpp
src/lib/drivers/accelerometer/PX4Accelerometer.hpp
src/lib/drivers/gyroscope/PX4Gyroscope.cpp
src/lib/drivers/gyroscope/PX4Gyroscope.hpp

Possible fix for (part of) https://github.com/PX4/Firmware/issues/14735.

PX4Accelerometer/PX4Gyroscope: integrated data use simple rotate_3f to avoid unnecessary floating point operations

---

src/lib/drivers/accelerometer/PX4Accelerometer.cpp
src/lib/drivers/gyroscope/PX4Gyroscope.cpp

This is a quick follow up fix to https://github.com/PX4/Firmware/pull/14752. In the case of FIFO data (new IMU drivers) the calibration offset wasn't being applied correctly to the result of integrating the FIFO samples.
This slipped through unnoticed with the offsets zeroed (simple bench testing, the test rack, and SITL CI).

PX4Accelerometer/PX4Gyroscope: fix calibration offset for integrated FIFO case

---

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
src/modules/navigator/takeoff.cpp

**This PR contains the following improvement:**
At the start of a front transition the fixed wing position controller creates a virtual position setpoint which is located 1000m in front of the vehicle. This avoids the controller tracking waypoints which are too close to the vehicle, e.g. loiter waypoints.
It would of course be nicer if the navigator would automatically publish this setpoint. However, this would take quite some changes and I'm not comfortable with the attempt just before a release.
Also, the logic in the position controller is straight forward and can be removed very easily. 
**This PR fixes the following bug:**
A takeoff followed by a transition command lead to the vehicle doing a flyaway. This was because the takeoff code did not set valid latitude and longitude for the …

Improve front transition tracking & fix flyaway

---

Tools/gazebo_sitl_multiple_run.sh

Since SITL gazebo now has a clean separation between worlds and vehicles, we can now spawn multiple vehicles to any world we want. 
You can use the `-w` flag to specify which world the vehicle should be spawned in. If no `-w` flag is specified, then the script defaults to `empty.world` 
For e.g.
```
Tools/gazebo_sitl_multiple_run.sh -w baylands
```
This was enabled by separating worlds with models in gazebo definitions. This will also be something useful to test multivehicle fleets in "windy" environments when such worlds are added as in https://github.com/PX4/Firmware/pull/14737

Add options to spawn multiple vehicles in different worlds

---

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp
platforms/common/include/px4_platform_common/tasks.h
src/modules/airspeed_selector/airspeed_selector_main.cpp
src/modules/attitude_estimator_q/attitude_estimator_q_main.cpp
src/modules/ekf2/ekf2_main.cpp
src/modules/fw_att_control/FixedwingAttitudeControl.cpp
src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
src/modules/land_detector/LandDetector.cpp
src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp
src/modules/mc_att_control/mc_att_control_main.cpp
src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/sensors/sensors.cpp
src/modules/sensors/vehicle_acceleration/VehicleAcceleration.cpp
src/modules/sensors/vehicle_air_data/VehicleAirData.cpp
src/modules/sensors/vehicle_imu/VehicleIMU.cpp

Ekf2 runs on every new IMU message (400 Hz sensor_combined) and publishes a new vehicle_attitude immediately, but only runs the filter update every 10 ms. Having mc_att_control in a separate higher priority thread allows it to run immediately on every vehicle_attitude publication.
We basically had this in the past when mc_att_control was a task, but temporarily lost it in an effort to reduce memory (and save a little bit of cpu). Workqueue threads are cheap and the current mc_att_control is cheaper than it used to be, so we can comfortably afford this.
Background: https://github.com/PX4/Firmware/pull/9832

move mc_att_control to new wq:attitude_ctrl

---

src/lib/mag_compensation/MagCompensation.cpp
src/lib/mag_compensation/MagCompensation.hpp
src/lib/mag_compensation/mag_compensation_params.c
src/lib/mag_compensation/python/mag_compensation.py
src/modules/sensors/parameters.cpp
src/modules/sensors/parameters.h
src/modules/sensors/sensors.cpp
src/modules/sensors/voted_sensors_update.cpp
src/modules/sensors/voted_sensors_update.h

In mag power compensation library: Add option to chose instance 1 of battery_status for current compensation. So far automatically instance 0 was used.

Mag power compensation: battery_status instance 1

---

src/modules/mavlink/CMakeLists.txt
src/modules/mavlink/mavlink_receiver.cpp
src/modules/mavlink/mavlink_receiver.h
src/modules/mavlink/tune_publisher.cpp
src/modules/mavlink/tune_publisher.h

The old tune device interface is not working anymore and we need to publish to uORB tune_control.
~This solution is not optimal though because blocks the receiving thread.~

mavlink: add missing uORB publication of tunes

---

msg/vehicle_odometry.msg
src/modules/attitude_estimator_q/attitude_estimator_q_main.cpp
src/modules/ekf2/ekf2_main.cpp
src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp
src/modules/local_position_estimator/sensors/mocap.cpp
src/modules/local_position_estimator/sensors/vision.cpp
src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/mavlink_receiver.cpp
src/modules/simulator/simulator_mavlink.cpp

Currently, there is no straightforward way to track odometry measurement latencies since the delay isn't captured anywhere
By adding a `timestamp_sample` field to `vehicle_odometry` and using it accordingly (`timestamp - timestamp_sample`), we get the latency tracking capabilities.
https://logs.px4.io/plot_app?log=5f50dfcc-8da2-42ea-b3da-53c5930cd6cd

vehicle_odometry: add timestamp_sample field for latency monitoring

---

src/lib/conversion/rotation.cpp

Discussing with @baumanta, @julianoes, @RomanBapst over the coffee break some rotation implementations are just confusing with their extra steps.
Do the minimal swapping which requires only one temporary variable and doesn't do unnecessary confusing assignments.
Untested, please review.
https://github.com/PX4/Firmware/pull/14512#issuecomment-618441246

rotation conversion: deconfuse roll 90 yaw 90

---

.gitmodules

SITL support for Flightgear was added in https://github.com/PX4/Firmware/pull/14539 thanks to the contribution from Thunderfly Aerospace! Thanks @kaklik @slimonslimon @roman-dvorak 
This brings the flightgear bridge submodule to a [fork](https://github.com/PX4/PX4-FlightGear-Bridge) of the [original repo](https://github.com/ThunderFly-aerospace/PX4-FlightGear-Bridge)  under the px4 organization

Switch flightgear bridge submodule to px4 organization

---

.ci/Jenkinsfile-SITL_tests
.ci/Jenkinsfile-SITL_tests_ASan
.ci/Jenkinsfile-SITL_tests_coverage
Makefile
integrationtests/python_src/px4_it/mavros/mavros_offboard_yawrate_test.py
integrationtests/python_src/px4_it/mavros/mavros_test_common.py
test/mavros_posix_tests_offboard_rpyrt_ctl.test

Added Roll Pitch Yawrate Thrust offboard control mode test.
Added a new integration test based on the mavros_posix_offboared_attctl_test.py . Also added the file on the respective links on .ci and Makefile.
@dagar @julianoes , decided to do another PR instead of pushing to master directly.

Roll Pitch Yawrate Thrust (RPYrT) CI integration tests

---

Tools/setup/ubuntu.sh

Gazebo video streaming on ubuntu wasn't working - as per http://dev.px4.io/master/en/simulation/gazebo.html#how-to-view-gazebo-video
I ran the gst-launch-1.0 instructions and it reported that gstreamer1.0-libav is missing. Once added, QGC video worked.
I'm not certain that this is the "right" way to fix the dependency though. 
After this fix, the `gst-launch-1.0` "test"  command at above no longer fails with the warning. It does only display a grey view though, as per https://github.com/PX4/Devguide/issues/1034

ubuntu setup script: add gstreamer1.0-libav

---

src/drivers/pwm_out/CMakeLists.txt
src/drivers/pwm_out/PWMOut.cpp
src/drivers/pwm_out/PWMOut.hpp
src/lib/cdev/CDev.hpp
src/lib/drivers/device/CDev.hpp

This is a quick cleanup of `drivers/pwm_out` that will enable it to be used on Linux platforms like the BeagleBone Blue, Emlid Navio2, Aerotenna Ocpoc if low level PWM routines are implemented.
- up_pwm_servo_init()
- up_pwm_servo_arm()
- up_pwm_servo_set()
- up_pwm_update()
- up_pwm_servo_deinit()

drivers/pwm_out: cleanup for multi-platform use

---

src/modules/mavlink/mavlink_messages.cpp

Previously the ground truth data that is published over the mavlink hil_state_quaternion message, were filled with information from non-groundtruth messages. Some of them such as `vehicle_global_position` message is sent by the EKF only after the passing checks. The ground truth gps coordinate was therefore not available from beginning and only for vehicle flying using GPS data for estimation. This is causing issues during integration tests. https://github.com/PX4/Firmware/issues/14760
Is there a reason why the non groundtruth messages were used?
This PR solves this by using the data from the already existing groundtruth variants that are available during simulation. This message is during simulation runs immediately available. From a conceptually standpoint this is also the correct …

Use ground truth data for ground truth mavlink message

---

src/modules/simulator/simulator_mavlink.cpp

In the mavlink receiver for simulation runs (`simulator_mavlink.cpp`), it was wrongly assumed that the received vision quaternion is from world to body. This is not the case. Therefore the visual linear velocity which needed to be transformed from body frame to local frame, was not correct.
Testing:
Checking quaternion output in terminal while moving drone in gazebo.
Running the offboard position control mission from mavsdk successfully with vision velocity fusion.
@TSC21 After this, I am finally able to add the vision velocity mavsdk test.

Fix vision velocity in simulation

---

src/modules/mavlink/mavlink_command_sender.cpp

According to the mavlink documentation, the confirmation field is supposed to be 0 only for the first transmission. Any retransmissions of commands have the confirmation field incremented with this PR.

mavlink: increment cmd confirmation field

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

I found an issue with the takeoff ramp when real world testing https://github.com/PX4/Firmware/pull/14749 on the Holybro QAV250. But I found the issue is independent of that pr.
The thrust doesn't ramp nicely anymore like it was designed but depending on stick input can go up and down unexpectedly during the ramp up. This can lead to early land detection if the thrust goes up high enough and then back down because the ramp is not yet high enough.
The problem is: Because the takeoff ramp is a vertical velocity limit ramp for the nice user experience but the acceleration feed-forward can add on top of the output and depending on trajectory generation result in unwanted thrust changes during the ramp.
I suppress the …

mc_pos_control: fix takeoff ramp gets amended by feed-forward

---

src/modules/mc_pos_control/PositionControl/PositionControl.cpp
src/modules/mc_pos_control/PositionControl/PositionControl.hpp
src/modules/mc_pos_control/PositionControl/PositionControlTest.cpp
src/modules/mc_pos_control/mc_pos_control_main.cpp

Before #14212 the velocity control gains used in the multicopter position controller were defined as a scale between velocity error in one axis (or it's integral and derivative respectively) and the unit thrust vector. The problem with this is that the normalization of the unit thrust vector changes per vehicle or even vehicle configuration as 0 and 100% thrust get a different physical response. That's why the gains are now defined as scale between velocity error (integral/derivative) and the output acceleration in m/s². E.g. with the default P horizontal velocity gain of 4 m/s² per m/s you would counteract a velocity error of 1m/s with 4m/s² actuation in order to accelerate to the desired velocity. This leads to less dependence of the …

PositionControl: deconflict velocity control gains from thrust

---

ROMFS/px4fmu_common/init.d-posix/1061_r1_rover
platforms/posix/cmake/sitl_target.cmake

Previously, it was not possible to simulate a differential rover in PX4 SITL
This PR adds a gazebo model based on the aion robotics r1 rover as a SITL target.
The models were imported from https://github.com/aionrobotics/r1_ugv_sim 
Here is the video of the rover running a mission in gazebo:
[![Demo](https://img.youtube.com/vi/cL7ZhvNvV3o/0.jpg)](https://youtu.be/cL7ZhvNvV3o) 
- Model implemented in: https://github.com/PX4/sitl_gazebo/pull/394
- Fixes https://github.com/PX4/Firmware/issues/11955

Add aion robotics r1 rover as a sitl target for Gazebo

---

ROMFS/px4fmu_common/init.d-posix/1061_r1_rover

The shibang was missing in the previous commit where this file was added in https://github.com/PX4/Firmware/pull/14652

Fix shibang of r1_rover airframe config

---

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp

http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-hardware/detail/pr-commander_power/13/pipeline
`WARN  [load_mon] wq:attitude_ctrl low on stack! (268 bytes left)`

px4_work_queue: increase wq:attitude_ctrl stack

---

src/modules/logger/logger.cpp

logger: keep typical log path within a single mavlink message

---

test/mavsdk_tests/autopilot_tester.cpp
test/mavsdk_tests/autopilot_tester.h
test/mavsdk_tests/configs/sitl.json
test/mavsdk_tests/test_multicopter_mission.cpp
test/mavsdk_tests/test_multicopter_offboard.cpp

At the moment the CI runs every testcase-vehicle combination of the MAVSDK three times. Each run takes around 8 minutes and 40 seconds.
With the newest fixes for the offboard & vision tests, the vision tests can also run with a speed factor bigger than one. I tested this with a speed-factor=20 40 times in a row without failure.
Additionally there are calls to `poll_condition_with_timeout` in several places. This function tests the condition 10 times during the timeout interval. For example in the `offboard_goto` call or `wait_until_disarmed` call. In those two methods the timeout is set fix to 60 seconds. So if the condition is not satisfied immediately, it will wait for 6 seconds until it will check the condition again.
This timeout should depend on the specific mission. For a …

Speed up mavsdk integration tests

---

src/modules/sensors/voted_sensors_update.cpp

Sensor configuration like priority or enabled is only set in `VotedSensorsUpdate::parametersUpdate()`, so we need that loaded immediately on any sensor change.

sensors: refresh parameters on sensor init

---

src/drivers/magnetometer/bmm150/bmm150.cpp
src/drivers/magnetometer/bmm150/bmm150.hpp

- increased REP_XY and REP_Z: improves accuracy a bit, while increasing measurement time (reduced sampling to 30Hz)
- avoid extra transfer in measure()
- extend regdump output
- general code style cleanup
- implement the normal self-test

BMM150: small improvements

---

src/modules/airspeed_selector/airspeed_selector_main.cpp

This is to prevent a wrong (false positive) failure detection of the airspeed
shortly after system boot due to delays in driver and/or estimator startup (seen in SITL).
https://github.com/PX4/Firmware/issues/14807
In SITL, the airspeed selector has a false positive at startup (probably because there is no airspeed data yet), causing it to first switch to airspeed index -1 (airspeed invalid), and then to 1 (airspeed valid) a bit later once data is there. 
Do not run the airspeed selector as long as hrt_absolute_time() is below 2s. 
Fix it on the SITL airspeed driver side (or if it's not that then find root cause). I think though that waiting 2s after boot until you have an …

Airspeed Selector: do not run it within the first 2s after system boot

---

src/modules/commander/commander_params.c

- these should have been rescaled when the ecl/EKF filter update period
changed from 8 ms -> 10 ms
`1.73e-3 m/s / 0.008 s = 0.21625 m/s/s`
Keeping the same ~ 0.22 m/s^2 accel bias limit for arming means a new COM_ARM_EKF_AB value of `0.0022 m/s`.

commander: update EKF accel & gyro bias arming limits

---

src/drivers/pwm_out/PWMOut.cpp
src/drivers/pwm_out/PWMOut.hpp
src/modules/uORB/SubscriptionInterval.hpp

Let me start by saying I admit this seems hacky, so I'm certainly open to alternatives.
Currently in master in output modules like `drivers/px4fmu` we use a `uORB::SubscriptionCallbackWorkItem` to schedule the module to run on any updates to the relevant (mixed) actuator_controls, but with a max interval set to limit the update appropriately for the actuator.
For example when using typical 400 Hz PWM ESCs we set the interval of the `uORB::SubscriptionCallbackWorkItem` to 2500 us with the intended goal of mixing and updating the actuators at their maximum rate. Unfortunately in reality our actual data rates don't align perfectly due to minor clock differences between sensors and the flight controller, occasional jitter, and minor implementation details with the interval check (timestamp …

uORB::SubscriptionCallback relax interval check to accommodate realistic sensor publication rates and occasional jitter

---

src/modules/fw_att_control/FixedwingAttitudeControl.cpp

This PR makes the FW attitude controller use EAS (equivalent airspeed) and not IAS (indicated airspeed) for the control input scaling depending on airspeed. The EAS is the calibrated airspeed corrected with a scaling factor to account for sensor error/placement of pitot.
The remaining control modules (TECS, VTOL) already are using EAS instead of IAS. Note that per default EAS=IAS (ASPD_SCALE=1).

Fixed-wing attidue controller: replace IAS with EAS

---

src/modules/sensors/voted_sensors_update.cpp

The timestamp actually used by ekf2 for IMU data is the sensor_combined timestamp, so we should be setting it with the actual sample timestamp, rather than the topic publication metadata.
Later the `sensor_combined` message will be replaced with `vehicle_imu` that carries a separate publication timestamp and raw sample timestamp.

sensors: use sensor_gyro timestamp_sample for sensor_combined timestamp

---

src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp

It looks like this snuck in a few months ago when the code was refactored, but the redundant bias removal on the next line was missed (discrepancy with trying to keep VehicleAcceleration and VehicleAngularVelocity roughly in sync).
https://github.com/PX4/Firmware/pull/14036

sensors/vehicle_angular_velocity: don't remove bias twice

---

msg/templates/uorb/msg.cpp.em
msg/tools/px_generate_uorb_topic_helper.py

This is useful for casually inspecting latency across a few areas of the system.
``` Console
nsh> listener sensor_gyro
TOPIC: sensor_gyro 3 instances
Instance 0:
sensor_gyro_s
timestamp: 4122951146  (0.007275 seconds ago)
timestamp_sample: 4122950938  (208 us before timestamp)
device_id: 3670026 (Type: 0x38, SPI:1 (0x00)) 
x: 0.0065
y: -0.0150
z: 0.0040
temperature: 38.4425
Instance 1:
sensor_gyro_s
timestamp: 4122953026  (0.006588 seconds ago)
timestamp_sample: 4122952846  (180 us before timestamp)
device_id: 3932170 (Type: 0x3C, SPI:1 (0x00)) 
x: 0.0033
y: 0.0212
z: -0.0001
temperature: 38.1701
Instance 2:
sensor_gyro_s
timestamp: 4122958142  (0.004024 seconds ago)
timestamp_sample: 4122958116  (26 us before timestamp)
device_id: 4325386 (Type: 0x42, SPI:1 (0x00)) 
x: 0.0085
y: 0.0106 …
```

msg: timestamp_sample print elapsed from timestamp

---

ROMFS/px4fmu_common/init.d/airframes/4016_holybro_px4vision

Reference manual in box, and Holybro's website.

Set Power Monitor to a Neutral Position for PX4 Vision

---

src/drivers/px4io/px4io.cpp
src/lib/systemlib/mavlink_log.h
src/modules/airspeed_selector/airspeed_selector_main.cpp
src/modules/commander/Commander.cpp
src/modules/commander/calibration_routines.h
src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp
src/modules/local_position_estimator/sensors/baro.cpp
src/modules/local_position_estimator/sensors/flow.cpp
src/modules/local_position_estimator/sensors/gps.cpp
src/modules/local_position_estimator/sensors/land.cpp
src/modules/local_position_estimator/sensors/landing_target.cpp
src/modules/local_position_estimator/sensors/lidar.cpp
src/modules/local_position_estimator/sensors/mocap.cpp
src/modules/local_position_estimator/sensors/sonar.cpp
src/modules/local_position_estimator/sensors/vision.cpp
src/modules/mavlink/mavlink_main.cpp
src/modules/navigator/mission.cpp
src/modules/navigator/navigator_main.cpp
src/modules/navigator/rtl.cpp

- any information sent to the ground should also be available for log review
This might be too much information at first, but it's better than being kept in the dark with what a user would have experienced. This came up when debugging https://github.com/PX4/Firmware/pull/14825.

mavlink_log_info: also print PX4_INFO

---

Tools/setup/ubuntu.sh

This just updates the script to state support for Ubuntu 20.04. This works in my testing.
Note, a problem was reported here, but I can't reproduce: https://github.com/PX4/Firmware/issues/14888

Ubuntu.sh - report Ubuntu 20.04 in setup

---

msg/vehicle_odometry.msg
src/modules/ekf2/ekf2_main.cpp
src/modules/ekf2/ekf2_params.c
src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp
src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/mavlink_receiver.cpp
src/modules/simulator/simulator_mavlink.cpp

At the moment we expect the external vision's velocity to be expressed in world/local frame. This PR allows for the vision velocity also being expressed in body frame. For this a field is added to the vehicle_odometry message that stores the frame in which the velocity is expressed;
**Related ECL PR:** https://github.com/PX4/ecl/pull/708
**Solving issue:** https://github.com/PX4/Firmware/issues/13935
FYI @TSC21 @jkflying

Support odometry velocity in body and local frame [REOPENED]

---

src/modules/rover_pos_control/RoverPositionControl.cpp
src/modules/rover_pos_control/RoverPositionControl.hpp

This is my first pull request, so unsure as to whether I should  raise an Issue before creating a pull request, but I'm hoping that this explanation will be sufficiently clear, any feedback welcome. 
When using HOLD/LOITER the rover would not hold position but instead circle/oscillate around the hold position. This was caused by the fact that the current algorithm sets velocity to zero when distance to waypoint is under a certain threshold, the vehicle would decelerate, but not enough to stop before it once again exceeded the threshold. At this point it would then try to return to the hold position and the process would repeat. 
In the proposed solution once the distance to the waypoint is under a threshold the …

Rover hold/loiter

---

src/modules/commander/Arming/PreFlightCheck/checks/powerCheck.cpp

Follow up closes https://github.com/PX4/Firmware/pull/14898
Because of warnings on every flight on setups without
any need for concern. Some even high quality supply voltage regulators
that are rated for 5V can with tolerances and load get lower than 4.9V.
See discussion here: https://github.com/PX4/Firmware/pull/14898#issuecomment-628026895

powerCheck: make 5V warning threshold 0.1V lower

---

platforms/common/include/px4_platform_common/i2c_spi_buses.h

When running make format with astyle 3.1 (which is installed with the setup scripts) the style gets corrected the expected way but CI seems to use an older version that parses the bracketing wrong and corrects it again.
To work around that I put a newline in between. This mutes the constantly failing style checks.
Astyle should be the same version in CI and setup scripts but in between we don't want to annoy developers with this issue.
Passes style check locally, let's see what CI decides.

i2c_spi_buses.h: work around astyle version inconsistency

---

Tools/process_sensor_caldata.py

relates to https://github.com/PX4/Firmware/pull/14776
I found out that the script was assuming that the multi topics instance are appearing in order but it isn't always the case. In my case, the instance 1 appears before the 0.
Before fix (the 2nd IMU was assumed 0)
After fix (primary is 0)

Offboard temp cal: check topic instance

---

src/drivers/uavcannode/UavcanNode.cpp

Simple change - just adding a proper mapping of uORB's distance_sensor sensor type to UAVCAN's range_sensor type.

UavcanNode: Add sensor_type to range_sensor pub

---

launch/px4.launch

I noticed that the px4 shell was not available when starting PX4 SITL with px4.launch. Starting px4 with `posix_sitl.launch` works without problems. 
This seems to be due to the ordering of the sitl arguments. This PR fixes the odering, and the shell is working. 
This is useful when starting px4 sitl through a roslaunch and using one of the airframe configs that exist upstream, but a model that doesn't exist upstream.

Fix interactive shell with roslaunch with px4.launch

---

src/modules/mavlink/mavlink_messages.cpp

This PR makes the MavlinkStreamVFRHUD send true_airspeed_m_s instead of indicated_airspeed_m_s for HUD on groundstation. This makes especially sense when your airspeed setup needs a scale factor (between indicated to equivalent), as otherwise the HUD displays another airspeed than the one that's used in the control modules.
Alternatively we could also display equivalent and not true airspeed. I would prefer true airspeed, such that it is comparable to the groundspeed.
EDIT: it would now send EAS and not TAS.

mavlink_messages for HUD: send EAS instead of IAS

---

Tools/setup/ubuntu.sh

This fixes the error:
`line 149: [: missing `]'`
Fixes #14916, fixes #14888.

Tools: fix ubuntu setup script

---

src/modules/navigator/mission_feasibility_checker.cpp

This reverts the addition of a check against mission items that have the same position. This breaks existing MAVSDK implementations where a LOITER_TIME item is set right after a WAYPOINT with the same coordinates. It is an interim hack to allow the vehicle to hold still
during a photo is captured.
This leaves the check in place for gates where we need to be able to calculate the direction between gate and waypoint.
In my opinion this is a compromise between enabling the gate calculations added by the release and not breaking existing MAVSDK (and maybe other) implementations.
For the future I'm open to tightening to specs to disallow waypoints at the same location and making sure the current use cases can be achieved with existing implementations, DELAY, LOITER, as it makes sense. …

navigator: allow mission items with same position (take 2)

---

src/modules/commander/airspeed_calibration.cpp

`px4_open` on success returns a non-negative integer, so there has been a potential for a leak

airspeed_calibration: Fix FD leak

---

src/lib/controllib/BlockRandGauss.hpp
src/lib/controllib/BlockRandUniform.hpp

```
clang --version
clang version 10.0.0 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

controllib: fix implicit cast warn with clang 10

---

src/drivers/gps/CMakeLists.txt

This is a workaround for a warning in GCC 10.1:
```
src/drivers/gps/devices/src/ubx.cpp:520:8: error: writing 4 bytes into a region of size 0 [-Werror=stringop-overflow=]
```
Also see:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91707
Closes #14908.

gps: workaround spurious GCC 10.1 warning

---

Tools/setup/ubuntu.sh

bc is not always installed on ubuntu machines and since https://github.com/PX4/Firmware/commit/735749e341e51c31abe843593da7ba8f3bc97e0d it is required for the rcS script to run.
```
etc/init.d-posix/rcS: 198: etc/init.d-posix/rcS: bc: not found
COM_DL_LOSS_T set to 
ERROR [param] not enough arguments.
Try 'param set PARAM_NAME 3 [fail]'
etc/init.d-posix/rcS: 202: etc/init.d-posix/rcS: bc: not found
COM_RC_LOSS_T set to 
ERROR [param] not enough arguments.
Try 'param set PARAM_NAME 3 [fail]'
etc/init.d-posix/rcS: 206: etc/init.d-posix/rcS: bc: not found
```
Install bc for all simulation targets.

install bc for all simulations

---

src/lib/flight_tasks/tasks/ManualAltitude/FlightTaskManualAltitude.cpp
src/lib/flight_tasks/tasks/ManualAltitude/FlightTaskManualAltitude.hpp
src/modules/mc_att_control/mc_att_control.hpp
src/modules/mc_att_control/mc_att_control_main.cpp
src/modules/mc_att_control/mc_att_control_params.c
src/modules/rc_update/params.c
src/modules/rc_update/rc_update.cpp
src/modules/rc_update/rc_update.h

An always reoccurring pattern seems people detuning the rate and attitude control loops because "the drone flies too aggressive when moving the sticks".
These are two separate things:
1. The controller trying to follow the setpoint as close as possible and in an ideal world would achieve perfect tracking even with disturbances like wind, motor tolerances and friction, unconsidered aerodynamic effects of the propellers, unbalanced mass distribution, ...
2. Considering perfect tracking of the controller how would the vehicle move given a certain user input. In other words how the setpoint changes when you move the stick.
As discussed with @bresch I used a simple first-order IIR low pass to filter the "x, y" stick …

Add an optional stick tilt input filter

---

src/modules/vtol_att_control/vtol_att_control_main.cpp
src/modules/vtol_att_control/vtol_att_control_main.h

Transitions to fixed-wing mode close to ground are dangerous, plus the current px4 navigation logic doesn't handle it well if you transition in some flight stages (you can end up in a fly-away). I do not see any use case where a transition to FW would be needed during the takeoff or landing flight mode, and in Return mode it is at least controversial.
- Disable transition during takeoff
- Disable transition to FW during Landing and Return mode
While preventing the transitions to FW in takeoff and land probably is of little controversy, doing so in the Return mode can be. E.g. you have a Quad-chute far away, the vehicle is though in hover and in Return. The user knows though that …

VTOL: disable transition command in certain flight modes

---

src/modules/mavlink/mavlink_receiver.cpp
src/modules/mavlink/mavlink_receiver.h

Mavlink receiver handles a case of the LANDING_TARGET message when position flag is invalid which I understood means that the sensor measurements are sent instead of the estimated target position.
Sensor measurements are then published over irlock_report message to be used by the landing target estimator.
This also enables using precision landing in hitl as the irlock measurements are sent in gazebo and not already estimated target position. Fixes issue #14698 
Tested using irlock model in hitl simulation

mavlink_receiver: handle LANDING_TARGET message: publish irlock_report when landing target position invalid

---

src/drivers/adc/ADC.cpp

The test needs to run over time, for values to be compared and cycled.

adc:Restore ADC test's usefulness

---

platforms/nuttx/src/px4/stm/stm32_common/board_hw_info/board_hw_rev_ver.c

Code point 10 (0xa) was mis-printed.
REV 0..10 is shown below
```
HW type:   V6X00
HW type:   V6X01
HW type:   V6X02
HW type:   V6X03
HW type:   V6X04
HW type:   V6X05
HW type:   V6X06
HW type:   V6X07
HW type:   V6X08
HW type:   V6X09
HW type:   V6X0a
```

stm32_common:board_hw_rev_ver Fix printing of REV/VER = 10

---

ROMFS/px4fmu_common/init.d-posix/1014_solo

The solo model was showing visible oscillations while flying. 
Tuning down the rate controller removes the oscillations. 
Before PR: 
Log: https://review.px4.io/plot_app?log=4bd411a0-818e-4cdc-96d7-27f796088eb3
After PR: 
Log: https://review.px4.io/plot_app?log=9aafa587-8c42-4d85-bddb-8a3768d7171e
Fixes https://github.com/PX4/Firmware/issues/11405

Tune down solo attitude rate controller

---

boards/px4/fmu-v3/default.cmake
boards/px4/fmu-v4/default.cmake
boards/px4/fmu-v5/default.cmake
boards/px4/fmu-v5x/default.cmake
src/systemcmds/gpio/CMakeLists.txt
src/systemcmds/gpio/gpio.cpp

In order to debug (read or control) GPIO currently developers need to go through a tweak-compile-flash cycle each time, or use jtag and thus have an expensive hardware connection.
Add a tool which can manipulate the GPIO from the nsh shell.
JTAG
Tested by playing with the power lights on a Pixhawk 4 (read and write)

Add nsh command to manipulate/read GPIO

---

platforms/common/include/px4_platform_common/px4_work_queue/WorkItem.hpp
platforms/common/include/px4_platform_common/px4_work_queue/WorkQueue.hpp
platforms/common/px4_work_queue/ScheduledWorkItem.cpp
platforms/common/px4_work_queue/WorkItem.cpp
platforms/common/px4_work_queue/WorkQueue.cpp
platforms/common/px4_work_queue/WorkQueueManager.cpp

Minor `work_queue status` improvements broken out of https://github.com/PX4/Firmware/pull/14906.
- only record start time on first run rather than init
- increase name length
- round average interval to nearest microsecond
- basic formatting consistency (google style guide)

px4_work_queue: minor status changes

---

src/modules/mavlink/mavlink_log_handler.cpp
src/modules/mavlink/mavlink_log_handler.h

this is followup to 'return with error from _log_request_list() in case of failed allocation #14451'
The class _LogListHelper_ created and destroyed dynamically during logs download process. which mean some `new` and `delete` built in in _MavlinkLogHandler_ code. the existence of the class then checked, to decide the state of the downloader.
This PR remove the dynamic allocation. to ensure enough memory on creation of MavlinkLogHandler (meaning, creation of mavlink instance)
The class LogListHelper removed, all its functions and variants moved into _MavlinkLogHandler_ and created when _MavlinkLogHandler_ allocated.
LOG_HANDLER_STATE::INACTIVE state is the state to indicate that the behavior as if _LogListHelper_ …

bring in class LogListHelper into MavlinkLogHandler

---

boards/bitcraze/crazyflie/syslink/syslink_main.h
src/drivers/power_monitor/ina226/ina226.cpp
src/drivers/power_monitor/ina226/ina226.h
src/drivers/power_monitor/voxlpm/voxlpm.cpp
src/drivers/power_monitor/voxlpm/voxlpm.hpp
src/lib/battery/battery.cpp
src/lib/battery/battery.h
src/modules/battery_status/analog_battery.cpp
src/modules/battery_status/analog_battery.h
src/modules/battery_status/battery_status.cpp
src/modules/esc_battery/EscBattery.cpp
src/modules/esc_battery/EscBattery.hpp
src/modules/simulator/simulator.h
src/modules/simulator/simulator_mavlink.cpp

There are a lot of places using a simple alpha filter/leaky integrator of the form
`y[n] = alpha * y[n-1] + (alpha - 1) * x[n]`
The filter parameter alpha is always hard-coded and is lacking any time abstraction. Also there's code duplication around necessary checks to keep the state from getting NAN.
I made a class LeakyIntegrator based on the prototyping script I used to evaluate here:
https://github.com/Auterion/Flight_Control_Prototyping_Scripts/tree/master/leaky_integrator
~I added unit tests for the LeakyIntegrator class. I'll do battery filtering tests once I'm finished.~
Real world battery filtering tests missing.

Alpha filter/leaky integrator time abstraction

---

src/modules/fw_att_control/FixedwingAttitudeControl.cpp
src/modules/fw_att_control/FixedwingAttitudeControl.hpp

Enables use of the gimbal for VTOL or fixed wings. Parachute is handled by IO based on flight termination.
https://docs.px4.io/master/en/peripherals/parachute.html

FixedWingAttitudeControl: removed parachute from gimbal control group

---

src/modules/mc_att_control/AttitudeControl/AttitudeControl.cpp
src/modules/mc_att_control/AttitudeControl/AttitudeControl.hpp
src/modules/mc_att_control/AttitudeControl/AttitudeControlTest.cpp
src/modules/mc_att_control/mc_att_control.hpp
src/modules/mc_att_control/mc_att_control_main.cpp

When the attitude estimate quaternion is reset the attitude controller uses the new reference in the next loop iteration. But the attitude setpoint is not updates to the new reference until the position controller generates a new attitude setpoint but it runs in a much slower rate. As a result there are glitches in the output rate setpoint. See https://github.com/PX4/Firmware/pull/14676#issuecomment-617969679
The internal setpoint copy is updated with the delta quaaternion upon attitude estimate reset. It will get overwritten with the next attitude setpoint change.
Completely untested, tests still REQUIRED.

mc_att_control: adjust attitude setpoint upon estimate reset

---

ROMFS/px4fmu_common/init.d-posix/1040_standard_vtol
ROMFS/px4fmu_common/init.d-posix/1041_tailsitter
ROMFS/px4fmu_common/init.d-posix/1042_tiltrotor
ROMFS/px4fmu_common/init.d-posix/6011_typhoon_h480
ROMFS/px4fmu_common/init.d-posix/rcS
ROMFS/px4fmu_common/init.d/airframes/1002_standard_vtol.hil
ROMFS/px4fmu_common/init.d/airframes/13006_vtol_standard_delta
ROMFS/px4fmu_common/init.d/airframes/13009_vtol_spt_ranger
ROMFS/px4fmu_common/init.d/airframes/13013_deltaquad
ROMFS/px4fmu_common/init.d/airframes/4016_holybro_px4vision
ROMFS/px4fmu_common/init.d/airframes/4052_holybro_qav250
ROMFS/px4fmu_common/init.d/airframes/4070_aerofc
ROMFS/px4fmu_common/init.d/airframes/4071_ifo
ROMFS/px4fmu_common/init.d/airframes/4073_ifo-s
ROMFS/px4fmu_common/init.d/airframes/4250_teal
ROMFS/px4fmu_common/init.d/airframes/4500_clover4
ROMFS/px4fmu_common/init.d/airframes/4900_crazyflie
ROMFS/px4fmu_common/init.d/airframes/6002_draco_r
src/lib/parameters/param_translation.cpp
src/lib/parameters/param_translation.h
src/modules/mc_pos_control/Takeoff/Takeoff.cpp
src/modules/mc_pos_control/Takeoff/Takeoff.hpp
src/modules/mc_pos_control/Takeoff/TakeoffTest.cpp
src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/mc_pos_control/mc_pos_control_params.c

Second part of #14749 split out. This pr has the goal to make the parameters reflect that reproducible gain scale of m/s error to m/s² acceleration output while still staying backwards compatible.
Replace the existing parameters
`MPC_XY_VEL_P`
`MPC_XY_VEL_I`
`MPC_XY_VEL_D`
`MPC_Z_VEL_P`
`MPC_Z_VEL_I`
`MPC_Z_VEL_D`
with new ones each having `_ACC` appended (They are within 16 charachters) that directly reflect the correctly scaled values.
Test-flown with #14749, see https://github.com/PX4/Firmware/pull/14749#issuecomment-623474947
Also from there:
> I noticed when switching to a new PX4 branch after this commit and to an older one again you lose the custom velocity control tuning e.g. SITL …

mc_pos_control: migrate MPC_*_VEL_* parameter to acceleration scaling

---

src/modules/navigator/navigator_main.cpp

This reset change 4 months ago destroyed the original WV working logic, which caused wv to no longer work under land / loiter, and this PR solved it. It has been tested in gazebo.
Extra thinking:
Will the yaw setting generated by WV destroy RTL?
FYI ： @sfuhrer

navigator_main.cpp: don't reset wv enable status

---

ROMFS/px4fmu_common/init.d/airframes/4015_holybro_s500

This was problematic on @dakejahl's (stock?) holybro s500. Decreasing to a safer conservative default.

ROMFS: holybro s500 decrease filter defaults

---

src/modules/ekf2/ekf2_params.c

As discussed on the dev call.
FYI @priseborough

ekf2: increase default baro noise 2 -> 3.5 m

---

src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/mavlink_receiver.cpp
src/modules/simulator/simulator.h
src/modules/simulator/simulator_mavlink.cpp

Fixes the odometry MAVlink frames of reference and estimation source handling.
Adds the usage of the  and depending on the `MAV_ESTIMATOR_TYPE`, splits the odometry stream where required.
Brings along some other updates in the sitl_gazebo and mavlink submodules, including https://github.com/PX4/sitl_gazebo/pull/506.
Tested in SITL.

mavlink: fix odometry frames of reference setup

---

src/modules/navigator/mission.cpp
src/modules/navigator/precland.cpp
src/modules/navigator/precland.h
src/modules/navigator/rtl.cpp
src/modules/navigator/rtl.h
src/modules/navigator/rtl_params.c

Enables precision landing at the end of RTL, configurable with a parameter
Also mission precland call logic is cleaned up to be more readable, and switched to be at the end of mission on_active, so it can perform an iteration of precland as soon as it switches to using it, keeping precland on_inactiavtion being handled properly.

enable precision landing at the end of RTL

---

src/modules/navigator/precland.cpp

Previous and next position setpoint triplets are used by flight tasks to properly adjust the vehicle velocity depending on the prev-current-next path curving angle.
While performing precision landing there is no such concept as a path in horizontal plan. The goal is to land and to control the desired horizontal position setpoint.
Precland never adjusts previous setpoint so it will be stuck at whatever it was before precision landing for the whole precland procedure. During the precision landing the drone can get pushed away (wind) in any direction and prevoius sp being something old looses sense and can unnecessary impose wrong limits to the velocity sp.
**Proposed solution**
My suggestion is to set the previous triplet to invalid such that …

precland: set the previous position setpoint to invalid

---

src/modules/sensors/sensors.cpp
src/modules/sensors/vehicle_imu/VehicleIMU.cpp
src/modules/sensors/vehicle_imu/VehicleIMU.hpp
src/modules/uORB/SubscriptionInterval.hpp

The IMU integration now in the sensors module has to measure the actual sensor publication rate before relaxing its scheduling. With this PR `sensors/vehicle_imu` consumes every available queued sample until there's an initial measurement for the sensor publication interval.
I've also readded the perf counters for monitoring (they were helpful in https://github.com/PX4/Firmware/pull/15002 and https://github.com/PX4/Firmware/pull/14999).

sensors/vehicle_imu: improve initial sensor interval monitoring

---

src/modules/sensors/vehicle_air_data/VehicleAirData.cpp
src/modules/sensors/vehicle_air_data/VehicleAirData.hpp
src/modules/sensors/voted_sensors_update.cpp
src/modules/sensors/voted_sensors_update.h

- in rare situations spewing these errors at high rate can actually
cause another sensor timeout
``` Console
ERROR [vehicle_air_data] sensor_baro:#0 failed:  TIMEOUT!, reconfiguring priorities
ERROR [vehicle_air_data] sensor_baro:#0 failed:  TIMEOUT!, reconfiguring priorities
ERROR [vehicle_air_data] sensor_baro:#0 failed:  TIMEOUT!, reconfiguring priorities
ERROR [vehicle_air_data] sensor_baro:#0 failed:  TIMEOUT!, reconfiguring priorities
ERROR [vehicle_air_data] sensor_baro:#0 failed:  TIMEOUT!, reconfiguring priorities
ERROR [vehicle_air_data] sensor_baro:#0 failed:  TIMEOUT!, reconfiguring priorities
ERROR [vehicle_air_data] sensor_baro:#0 failed:  TIMEOUT!, reconfiguring priorities
ERROR [vehicle_air_data] sensor_baro:#0 failed:  TIMEOUT!, reconfiguring priorities
ERROR …
```

sensors: don't allow mavlink error spamming

---

src/drivers/barometer/ms5611/ms5611.cpp

This fixes the baro misdetection on fmu-v3.
``` Console
nsh> listener sensor_baro
TOPIC: sensor_baro 2 instances
Instance 0:
sensor_baro_s
timestamp: 35532668  (0.007856 seconds ago)
error_count: 0
device_id: 4063242 (Type: 0x3E, SPI:1 (0x00)) 
pressure: 2028.9800
temperature: 47.0000
Instance 1:
sensor_baro_s
timestamp: 35533604  (0.009471 seconds ago)
error_count: 0
device_id: 3997730 (Type: 0x3D, SPI:4 (0x00)) 
pressure: 1014.1700
temperature: 38.9600
INFO  [vehicle_air_data] selected barometer: 4063242 (0)
INFO  [ecl/validation] validator: best: 0, prev best: 0, failsafe: NO (0 events)
INFO  [ecl/validation] sensor #0, prio: 75, state: OK
INFO  [ecl/validation]  val: 202884.0000, lp: 202882.9531 mean dev:   1.6257 RMS:   6.6592 conf:   1.0000
INFO  [ecl/validation]  val:  46.9100, lp: …
```

ms5611: prevent starting as ms5607 on ms5611

---

src/modules/sensors/vehicle_acceleration/VehicleAcceleration.cpp
src/modules/sensors/vehicle_acceleration/VehicleAcceleration.hpp
src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.hpp

This is a small optimization that limits how often these sensor hub WorkItems are scheduled based on an integer number of sensor_accel/sensor_gyro publications. On run they still consume and filter all available raw (queued) data.
- vehicle_acceleration limit to `IMU_INTEG_RATE`
- this is only used by the land detector (50 Hz), fixed wing position controller (50 Hz), and rover controller, so it's definitely not needed at full raw rate
- vehicle_angular_velocity still available at `IMU_GYRO_RATEMAX`, but now the WorkItem doesn't need to run at full rate (depends on the sensor).

sensors: vehicle_acceleration/vehicle_angular_velocity limit scheduling based on configuration

---

src/modules/navigator/mission.cpp

**Short recap of how things work:**
When uploading a mission item of type waypont a yaw setpoint can be provided and it can be set ether to some value or to NAN.
On the other hand the mission can also contain an ROI.
- If a mission doesnt have ROI set:
- mission item yaw is used if not NAN
- if mission item yaw is NAN then the yaw is computed based on a MPC_YAW_MODE 
parameter
- If a mission contains the ROI, yaw sp is computed from the ROI and that overrides the heading sp from the mission item. If the drone is close to the ROI then no new heading sp is computed and the triplet is unchanged.
**The problem rises when the mission starts close to the ROI:**
Triplet yaw sp is set according to the mission item (NAN since ROI is used), and then when it is supposed to be overridden by the yaw …

mission: keep current heading if close to ROI while heading sp is invalid

---

Makefile

It turns out the `-jN` argument was never actually used in the Makefile but always set to 4 for Makefile build. Ninja seemed to run with whatever is the system default.
With this change both Makefile and Ninja builds will now adhere to the j argument if it is set.
This should allow to build the Gazebo plugins will less core in order not to run out of RAM.
Related to:
https://github.com/PX4/Firmware/issues/14747
https://github.com/PX4/Firmware/issues/14430
https://github.com/PX4/Firmware/issues/14943

Fix `-jN` argument

---

src/modules/ekf2/ekf2_params.c

Actual value needs to be determined with testing. https://github.com/PX4/Firmware/issues/14640#issuecomment-635196525

ekf2: decrease default GPS horizontal velocity noise

---

src/modules/navigator/rtl.cpp
src/modules/navigator/rtl.h

Here's a quick change to reduce the excessive dataman reading coming from RTL.

navigator: RTL destination throttle dataman access

---

boards/px4/fmu-v2/src/spi.cpp
boards/px4/fmu-v3/src/spi.cpp

Possible fix for https://github.com/PX4/Firmware/issues/14745.
This ensures the CS are set to disabled for the unused sensor.

boards: pixhawk mini add unused MPU9250 CS & DRDY pins

---

src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_main.h
src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/mavlink_messages.h
src/modules/mavlink/mavlink_receiver.cpp
src/modules/mavlink/mavlink_receiver.h
src/modules/mavlink/mavlink_stream.cpp
src/modules/mavlink/mavlink_stream.h
src/modules/mavlink/streams/autopilot_version.h
src/modules/mavlink/streams/flight_information.h
src/modules/mavlink/streams/protocol_version.h
src/modules/mavlink/streams/storage_information.h

Implementing the MAV_CMD_REQUEST_MESSAGE as described in https://github.com/PX4/Firmware/issues/11441. So far only STORAGE_INFORMATION is supported.
I would like to use the opportunity and remind about one other PR, where all mavlink streams get their own file instead of having one bloated mavlink_messages.cpp: https://github.com/PX4/Firmware/pull/14259/commits/c1175e0d54cf60a655d2ce4db0323838a596a9cd
This would be helpful to get merged, otherwise I have double work here.
When there is a stream with the same message ID, send the message once. Otherwise create a new stream, send the message once and delete the stream again.
Tested with QGC custom command file https://pastebin.com/maHNSQ1A:

Implement MAV_CMD_REQUEST_MESSAGE

---

src/drivers/imu/bmi088/BMI088_accel.cpp
src/drivers/imu/bmi088/BMI088_gyro.cpp

Removed reading checked registers in status. The reading of the checked register in the breaks the driver and is of no value.

bmi088 remove dump of registers that causes driver to fail

---

boards/hex/cube-orange/nuttx-config/include/board.h

- Remove LSE because there is no LSE available in the Cube Orange
- Fix comment of PLL calc

Hex/Proficnc Cube Orange LSE fix, PLL comment fix

---

boards/mro/ctrl-zero-f7/init/rc.board_sensors

Broken out of https://github.com/PX4/Firmware/pull/14999.

boards: mRo Control Zero fix IMU rotations

---

ROMFS/px4fmu_common/init.d-posix/rcS
ROMFS/px4fmu_common/init.d/airframes/4050_generic_250
ROMFS/px4fmu_common/init.d/airframes/4053_holybro_kopis2
ROMFS/px4fmu_common/init.d/airframes/4070_aerofc
boards/holybro/kakutef7/src/spi.cpp
src/lib/systemlib/system_params.c
src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
src/modules/sensors/vehicle_angular_velocity/imu_gyro_parameters.c

- flying master lately I noticed the D-term is considerably more suspectible to noise on different vehicles. Initially I attributed that to the removal of the on-chip DLPF.
- trying to fly the Kopis 2 on master, it was just unflyable. And no matter how much PID and filter tuning I did, I could not get it to fly.
I then made the filter change here, and it immediately improved things a lot (so apparently the ordering matters). With some further tuning it's flyable again.
Log: https://logs.px4.io/plot_app?log=65497f73-7350-4965-aec1-5ccdce1c628c
@dakejahl I'm pretty sure this helps on your S500 as well.
Some feedback if other people experience the same would be appreciated.

Gyro filtering: apply IMU_GYRO_CUTOFF also to D-term

---

CMakeLists.txt
boards/bitcraze/crazyflie/default.cmake
boards/holybro/durandal-v1/stackcheck.cmake
boards/holybro/kakutef7/default.cmake
boards/px4/fmu-v5/stackcheck.cmake
boards/px4/io-v2/default.cmake
platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp
platforms/common/px4_work_queue/CMakeLists.txt
platforms/nuttx/src/px4/common/CMakeLists.txt
platforms/nuttx/src/px4/stm/stm32_common/dshot/CMakeLists.txt
platforms/nuttx/src/px4/stm/stm32_common/hrt/CMakeLists.txt
platforms/nuttx/src/px4/stm/stm32_common/io_pins/CMakeLists.txt
platforms/nuttx/src/px4/stm/stm32_common/spi/CMakeLists.txt
src/lib/drivers/accelerometer/CMakeLists.txt
src/lib/drivers/gyroscope/CMakeLists.txt
src/lib/perf/CMakeLists.txt
src/lib/systemlib/CMakeLists.txt
src/modules/mc_att_control/AttitudeControl/CMakeLists.txt
src/modules/mc_att_control/CMakeLists.txt
src/modules/mc_rate_control/CMakeLists.txt
src/modules/mc_rate_control/RateControl/CMakeLists.txt
src/modules/sensors/sensor_corrections/CMakeLists.txt
src/modules/sensors/vehicle_acceleration/CMakeLists.txt
src/modules/sensors/vehicle_angular_velocity/CMakeLists.txt
src/modules/sensors/vehicle_imu/CMakeLists.txt
src/modules/uORB/CMakeLists.txt

On an stm32f4 this saves about 4-8% cpu depending on the configuration at a cost of about 16 kB of extra flash.
As a comparison, building the entire system -O2 reduces cpu somewhere around 15% (px4_fmu-v4), but at a cost of several hundred kilobytes of flash (well over the 2MB limit).
``` Console
0 Idle Task                   14746 25.616   244/  512   0 (  0)  READY  3
1 hpwork                          0  0.000   344/ 1260 249 (249)  w:sig  3
2 lpwork                          0  0.000   344/ 1612  50 ( 50)  w:sig  3
3 init                         1420  0.000  2064/ 2924 100 (100)  w:sem  3
4 wq:manager                      1  0.000   408/ 1252 255 (255)  w:sem  4
440 mavlink_rcv_if0               215  0.362 …
```

selectively increase the optimization level per module/library

---

.ci/Jenkinsfile-hardware
src/systemcmds/tests/hrt_test/hrt_test_start.cpp
src/systemcmds/tests/test_dataman.c
src/systemcmds/tests/test_hrt.cpp

- stop logger before running tests to prevent watchdog triggers
- decrease test priorities
- hrt test don't flush output

Jenkins HIL test fix sensor timeouts

---

src/lib/battery/battery_params_common.c

Based on feedback from Thomas Stauber on slack: https://px4.slack.com/archives/C0V533X4N/p1591186808278700
the maxima for the battery capacity thresholds are a bit tight. 
I don't see a problem with allowing earlier lower battery configurations although it's not useful in most cases they do not break anything.

battery_params: relax maximum for capacity thresholds

---

platforms/common/include/px4_platform_common/atomic.h
src/drivers/imu/invensense/icm20608g/ICM20608G.cpp
src/drivers/imu/invensense/icm20608g/ICM20608G.hpp
src/drivers/imu/invensense/icm20608g/InvenSense_ICM20608G_registers.hpp
src/drivers/imu/invensense/icm20689/CMakeLists.txt
src/drivers/imu/invensense/icm20689/ICM20689.cpp
src/drivers/imu/invensense/icm20689/ICM20689.hpp
src/drivers/imu/invensense/icm20689/InvenSense_ICM20689_registers.hpp
src/drivers/imu/invensense/mpu6000/InvenSense_MPU6000_registers.hpp
src/drivers/imu/invensense/mpu6000/MPU6000.cpp
src/drivers/imu/invensense/mpu6000/MPU6000.hpp

Invensense ICM20608-G and ICM20689 minor improvements and potential fixes
- perform full sensor signal path reset and wait for max time (as described in the datasheet)
- issue full sensor reset on any error (100 consecutive failures, or 1000 total)
- always read FIFO count before transfers
- only allocate DRDY perf counter if GPIO is available
- remove perf counter from interrupt (so we can enable lazy fpu stacking later https://github.com/PX4/Firmware/pull/14454)
Possible fix for https://github.com/PX4/Firmware/issues/14994, https://github.com/PX4/Firmware/issues/13083, https://github.com/PX4/Firmware/issues/14644, https://github.com/PX4/Firmware/issues/15042.

Invensense ICM20608-G and ICM20689 minor improvements and potential fixes

---

src/modules/navigator/navigator_main.cpp

Executing `commander takoeff` in SITL lead to the vehicle performing a nice flyaway as there was no lat or longitude set in the position setpoint triplet.
I assume that flighttask is handling this case for multirotor takeoff but fixed wing was broken.
This seems like the best fix to me but maybe there are other suggestions for other hackeries.

navigator: always make sure that we set target lat/lon for fixed wing

---

src/modules/sensors/vehicle_imu/VehicleIMU.cpp
src/modules/sensors/vehicle_imu/VehicleIMU.hpp

Minor optimization in sensors/vehicle_imu. The IMU corrections only need to be applied once before publication, not to every raw sample.

sensors/vehicle_imu: only apply corrections once before publication

---

ROMFS/px4fmu_common/init.d/rcS

Creating these empty files prevents MacOS and Ubuntu (really any gnome file manager and UID 1000) from using the SD card for indexing and storing deleted files. 
- fixes https://github.com/PX4/Firmware/issues/15049

ROMFS: SD card block MacOS and Ubuntu trash and indexing files

---

boards/holybro/kakutef7/src/spi.cpp

This reverts commit 2069576a6ef4919f4e28e6a329bff83eb590c4d1.
PR #15004 fixed the problem.
```
nsh> icm20689 status
INFO  [SPI_I2C] Running on SPI Bus 4
INFO  [icm20689] FIFO empty interval: 500 us (2000.000 Hz)
icm20689: transfer: 221943 events, 17971155us elapsed, 80.97us avg, min 48us max 15011us 36.048us rms
icm20689: bad register: 0 events
icm20689: bad transfer: 0 events
icm20689: FIFO empty: 0 events
icm20689: FIFO overflow: 1 events
icm20689: FIFO reset: 2 events
icm20689: DRDY interval: 221970 events, 510.25us avg, min 152us max 15073us 151.185us rms
```

Revert "kakutef7 spi: disable IMU drdy"

---

src/modules/logger/logged_topics.cpp
src/modules/logger/logged_topics.h
src/modules/logger/logger.cpp
src/modules/logger/params.c

Useful for vibration analysis.
Usage:
- set `IMU_GYRO_RATEMAX` to 400
- use a good SD card (flight review will show the dropouts)
- enable either the gyro or accel high-rate FIFO profile in  `SDLOG_PROFILE` and disable the rest of the entries.
- a single FIFO topic requires ~85 KB/s logging bandwidth
- if a really good SD card is used, you can:
- either enable both accel+gyro
- or enable accel/gyro + default logging profile
Flight Review will show the data as in https://github.com/PX4/flight_review/pull/185.
Caveat: the first topic instance is logged, but it might not be the one used for flying.
@francelico fyi
@hamishwillee yes this will need docs :)

logger: add raw FIFO high-rate IMU logging profiles

---

ROMFS/px4fmu_common/init.d-posix/1042_tiltrotor

Previously, the tilt actuator inputs were being set as a 1 to 1 to the joint poisiton.
This is a problem since the tilt angle ranges [-3.14, 3.14] compared to actuator setpoints [-1, 1]
As a workaround, the firmware was scaling inputs on the firmware side by setting the parameter `VT_TILT_FW` as done in https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d-posix/1042_tiltrotor#L39
This PR sets the input scale on the model side by changing the input scale.
Depends on https://github.com/PX4/sitl_gazebo/pull/468

Fix tiltrotor scaling for sitl gazebo

---

Tools/setup/ubuntu.sh

Using `make px4_fmu-vX_default blackmagic_console` under freshly setup ubuntu leads to an error because screen is not found. Therefore I would like to add screen to NuttX dependencies.

add GNU screen to NUTTX dependencies in ubuntu setup

---

src/drivers/power_monitor/ina226/ina226.cpp
src/drivers/power_monitor/ina226/ina226.h
src/drivers/power_monitor/ina226/ina226_main.cpp

One vehicle we tested can generate temporary negative current draw because of active braking of the ESCs/motors. Whenever this occurred the battery was considered gone because the driver is returning negative error codes the same way as sensor measurements and therefore any negative value is considered an error.
- `read()` just like `write()` handles the data to operate on as a parameter now and the return value is solely to report success or error. The errors get handled accordingly.
- Some general refactoring and simplifications of `collect()` function.
I bench tested the changes on an fmu v5x board on both power module ports.

Revise INA226 return codes to allow negative current

---

src/lib/flight_tasks/tasks/Auto/FlightTaskAuto.cpp

We found out that no yaw feedforward was created when using an auto mode; this makes a significant difference in setpoint tracking between manual and auto modes. To fix that, the flight task auto now creates an artificial yaw speed setpoint if nothing is provided by the child class.
Without FF:
With FF:

FlightTaskAuto: Create artificial yaw speed sp for feedforward

---

src/drivers/imu/invensense/icm20602/ICM20602.cpp
src/drivers/imu/invensense/icm20608g/ICM20608G.cpp
src/drivers/imu/invensense/icm20649/ICM20649.cpp
src/drivers/imu/invensense/icm20689/ICM20689.cpp
src/drivers/imu/invensense/icm20948/ICM20948.cpp
src/drivers/imu/invensense/icm40609d/ICM40609D.cpp
src/drivers/imu/invensense/icm42688p/ICM42688P.cpp
src/drivers/imu/invensense/mpu6000/MPU6000.cpp
src/drivers/imu/invensense/mpu6500/MPU6500.cpp
src/drivers/imu/invensense/mpu9250/MPU9250.cpp

This also apparently gets closer to the actual scaling value (the datasheet is rounded).
ICM20602 at 2000 degree/s, 16.4 LSB/dps (datasheet) is actually 16.384 (32768 / 2000). I doubt the 0.1% difference matters, but this is also simpler.

drivers/imu/invensense: simplify gyro range configuration

---

src/modules/simulator/simulator.h
src/modules/simulator/simulator_mavlink.cpp
src/modules/simulator/simulator_params.c

This removes the gps noise multiplier parameter that can be set on the firmware side. I can see why this can be useful, but I think it creates more confusion and point of failure than give value.
IMHO, the gps noise should be fully configured from the simulation side. Otherwise we should have this for every sensor but I don't think this makes much sense
Remove functionality
Update: I realized the feature was introduced recently from @dagar in https://github.com/PX4/Firmware/pull/13854

Remove gps noise multiplier parameter for simulation

---

ROMFS/px4fmu_common/init.d-posix/10020_if750a
ROMFS/px4fmu_common/init.d-posix/1019_iris_dual_gps
platforms/posix/cmake/sitl_target.cmake
src/modules/simulator/simulator.h
src/modules/simulator/simulator_mavlink.cpp

This add the ability to test GPS blending through simulation by adding the ability to handle multi-GPS sensor streams.
This is done by checking the ID field in the `HIL_GPS` Mavlink message and then create a multi-topic publisher, where each ID is mapped to a specific `vehicle_gps_position` topic.
This also adds an `iris_dual_gps` model to tweak and verify this implementation.
This also required a major refactor on the `sitl_gazebo` side - https://github.com/PX4/sitl_gazebo/pull/517.
Log of a flight with the `iris_dual_gps`: https://logs.px4.io/plot_app?log=c3304662-4e15-476a-874e-57df1a360b0b.
An example output of `listener vehicle_gps_position`: (note that the data is the same as the …

Feature: add multi-GPS input from simulation

---

test/mavsdk_tests/configs/sitl.json

Following https://github.com/PX4/Firmware/pull/15106 and to make sure it gets into the test pipeline.

mavsdk_tests: add iris_dual_gps to the test pipeline

---

src/modules/mc_pos_control/mc_pos_control_params.c

I heared several times that the ground slow down is not something people expect to see by default. Hence I'm proposing to not slow down at all with default parameters.
People that found it confusing I still remember were: @igalloway on slack https://px4.slack.com/archives/C39C4E709/p1588275046070800, @baumanta , @priseborough (today), ...
I brought it up in the dev call before:
https://discuss.px4.io/t/px4-dev-call-may-06-2020/16511
First question under "Multicopter".
Set the ground slow down speed to the default maximum speed. This results in no change with defaults but a slow down to 10m/s if the maxiumum speed is set higher than that.
Original feature pr: …

Default config does not slow down close to ground in position mode

---

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp

`WARN  [load_mon] wq:attitude_ctrl low on stack! (284 bytes left)`

wq:attitude_ctrl small stack increase

---

Makefile

Apply the principles of third normal form for check targets.
The list of check is now sourced from the yaml files in  .github/workflows

Makefile:Create check_{px4,nxp,nuttx,linux} targets from .github/workflows

---

.ci/Jenkinsfile-compile
.github/workflows/compile_nuttx.yml

- jenkins is still responsible for master/beta/stable S3 uploads
TODO:
- move deploy to github actions and put Jenkins (mostly) to rest

Jenkins compile keep in sync with Github Actions NuttX build

---

src/modules/mavlink/mavlink_receiver.cpp
src/modules/simulator/simulator_mavlink.cpp

A range signal quality metric coming from Mavlink allows a proper evaluation of the range sensor being received from both simulation (Gazebo) and an external distance sensor connected to a companion computer.
Following https://github.com/mavlink/mavlink/pull/1403 and https://github.com/PX4/sitl_gazebo/pull/528, this propagates the quality field, normalised to 0..100.
Tested in SITL with the `iris_opt_flow` Gazebo model. 
Example output of `listener distance_sensor` at the ground level:
```sh
pxh> listener distance_sensor
TOPIC: distance_sensor
distance_sensor_s
timestamp: 6248000  (0.012000 seconds ago)
min_distance: 0.2000
max_distance: 15.0000
current_distance: 0.2000
variance: 0.0000 …
```

mavlink: DISTANCE_SENSOR: propagate signal_quality metric

---

.ci/Jenkinsfile-hardware

- this particular hardware on the test rack has a flaky console

Jenkins hardware ignore nxp_fmuk66-v3 status failures

---

.github/workflows/compile_nuttx.yml

The bloaty output is for monitoring and review, but shouldn't be allowed to fail the overall compile job if something goes wrong.

github actions don't allow bloaty output to fail compile job

---

.github/workflows/mavros_mission_tests.yml
test/mavros_posix_tests_missions.test

Previously, the fw hand launch /catapult launch was not part of the tests.
This PR adds `plane_catapult` model in gazebo SITL to test the hand / catapult launch feature for fixed wing
- This is a continuation of https://github.com/PX4/Firmware/pull/14418 moving from Jenkins to github actions
- This PR contains a fix for the plane catapult plugin https://github.com/PX4/sitl_gazebo/pull/529

Add FW hand launch / catapult launch to testing

---

src/examples/fixedwing_control/main.cpp
src/examples/rover_steering_control/main.cpp
src/modules/commander/Arming/PreFlightCheck/checks/manualControlCheck.cpp
src/modules/commander/Commander.cpp
src/modules/commander/Commander.hpp
src/modules/commander/rc_calibration.cpp
src/modules/fw_att_control/FixedwingAttitudeControl.cpp
src/modules/fw_att_control/FixedwingAttitudeControl.hpp
src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
src/modules/logger/logger.cpp
src/modules/logger/logger.h
src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/mavlink_receiver.cpp
src/modules/mavlink/mavlink_receiver.h
src/modules/mc_att_control/mc_att_control.hpp
src/modules/mc_att_control/mc_att_control_main.cpp
src/modules/mc_rate_control/MulticopterRateControl.cpp
src/modules/mc_rate_control/MulticopterRateControl.hpp
src/modules/rc_update/rc_update.cpp
src/modules/rc_update/rc_update.h
src/modules/rover_pos_control/RoverPositionControl.cpp
src/modules/rover_pos_control/RoverPositionControl.hpp
src/modules/uuv_att_control/uuv_att_control.cpp
src/modules/uuv_att_control/uuv_att_control.hpp
src/modules/vtol_att_control/vtol_att_control_main.cpp
src/modules/vtol_att_control/vtol_att_control_main.h

I quickly wanted to see where manual_control_setpoint.z is used. Turns out it's not that quick because the same thing from the same topic has all sorts of names.
I refactored the naming to be consistent:
- `manual_control_setpoint_sub` is the subscription name
- `manual_control_setpoint` is the content name.
We could make the topic name shorter but a longer name is no excuse to have inconsistent naming over the repository.
All done using auto replacing. I just had to find all the different variants.
https://github.com/PX4/Firmware/issues/9331

Refactor: Name manual_control_setpoint the same way everywhere

---

test/mavsdk_tests/test_multicopter_offboard.cpp

This seems to be the bulk of the MAVSDK failures.

mavsdk_tests: temporarily disable offboard position control test

---

boards/hex/cube-orange/init/rc.board_defaults
boards/hex/cube-yellow/init/rc.board_defaults

This PR solves the issue with ICM20948 zmag noise for the Hex CubeYellow and CubeOrange

Hex/Proficnc CubeYellow/CubeOrange: fix default config for IMU heating

---

.github/workflows/checks.yml

Surprisingly the test resources are not unlimited...

Github Actions limit checks to Ubuntu 20.04

---

src/drivers/dshot/dshot.cpp
src/drivers/pwm_out/PWMOut.cpp

Required on durandal if camera triggering is enabled.
@mhkabir this fixes your initial issue, still good to add support for the capture pins though.

{dshot,pwm_out}: allow mode_pwm4 for boards with 5 outputs

---

.github/workflows/compile_macos.yml

- it's large and takes as much time saving/restoring the cache as it saves

Github Actions remove MacOS homebrew cache

---

Tools/sitl_run.sh

When running gazebo SITL simulation multiple times, gzserver will sometimes silently fail. This is due to the fact that `gzserver` didn't exit cleanly from the previous session. The workaround was to run `pkill gzserver` when this happens.
`SIM_PID` was supposed to work to clean the previous gzserver instance but was wrongly taking the pid of the model spawner and not the gzserver. This PR makes the `SIM_PID` take the pid of `gzserver`
Previously model spawning would sometimes hang when starting SITL. After this change, it seems much less likely.

Fix gzserver hanging from multiple executions of gazebo SITL

---

Tools/gazebo_sitl_multiple_run.sh

Previously, multi-vehicle SITL launch script (`Tools/gazebo_multivehicle_sitl_run.sh`) only supported specifying a single type of vehicle and the number of vehicles. This becomes problematic when the user is trying to run a heterogeneous fleet.
This PR adds a scripting option `-s` where a vehicle type and number of vehicle can be specified. For example, ro spawn 3 `iris` vehicles and 2 `plane ` you can run
```
Toos/gazebo_sitl_multiple_run.sh -s "iris:3 plane:2"
```
The script iterates on the list of vehicle / number of instances until the list ends. 
- It does not matter whether the vehicles are repeated. For example
```
Toos/gazebo_sitl_multiple_run.sh -s "iris:3 plane:2 iris:3"
```
will spawn 8 vehicles in …

Enable spawning different vehicle types for multivehicle SITL in gazebo

---

src/modules/navigator/rtl.cpp

The cone logic does not make a lot of sense for fixed wings.

RTL: Do not use cone logic for vehicle flying as fixed wing

---

src/lib/flight_tasks/tasks/Auto/FlightTaskAuto.cpp
src/lib/flight_tasks/tasks/Auto/FlightTaskAuto.hpp

This fixes the corner case where a NAV_DELAY command changes the validity of the next WP but not the rest of the triplet. The logic in FlightTask was ignoring this change because the check was only based on WP position change.
fixes #14909 
@julianoes Could you please double check that this fixes the issue?

FlightTaskAuto: Update prev and next waypoints depending on validity

---

.github/workflows/compile_macos.yml

There's an intermittent crash when running these tests on Github Actions MacOS infrastructure (10.15). 
https://github.com/PX4/Firmware/issues/15225

Github Actions MacOS skip SITL tests

---

src/modules/logger/logged_topics.cpp
src/systemcmds/param/param.cpp

If some bits are set but no topic was added, _subscriptions was null but
later accessed.
During normal use this only happens when switching between different
firmware versions with different SDLOG_PROFILE definition (with custom
config).
Also:  param: also show unused params for 'param show -c' (I find this generally useful for debugging).

logger: fix hardfault for invalid SDLOG_PROFILE setting

---

boards/nxp/fmuk66-v3/src/board_config.h

@PetervdPerk-NXP reported that he had difficulty calibrating the sensors on a new NXP FMUK66 board (Rev. D). After further investigation he only measured about 2.6V on the 3V3_S domain on the NXP FMUK66. I measured a similar voltage level. It may or may not be the cause of the sensor calibration problems, but it's clear that something is not right here.
After studying the schematics and board init code, it seems that up until the Rev. B (not supported anymore) there was a PMOS that enabled the 3V3_S domain. Since Rev. C this voltage is coming from a dedicated low noise LDO. The enable signal is not connected to a PMOS anymore, but to the enable pin of the new LDO. The macro that is used to control the GPIO pin to enable the 3V3_S was never changed, though.
The schematics for different …

NXP FMUK66 - Fix VDD_3V3_SENSORS_EN polarity

---

src/modules/ekf2/ekf2_main.cpp

Fixes #14165. Probably also fixes PX4/Flow#102
Within ekf2, optical flow messages (amongst others) are fused to the state estimates. It might occur that optical flow sensors report unreliable and unrealistic spikes. In that case, the state estimator went crazy so far and just ignored optical flow values from that moment on.
The common thread for all these spikes seems to be a too high integration time span (can be as high as the data type upper limit). Therefore, this fix adds a simple logic that ignores unrealistically high integration time spans. As a threshold, 1 second was chosen. This way, the EKF doesn't go crazy and keeps incorporating optical flow values.
Reported-by: Dominik Natter <dominik.natter@gmail.com>

Ignore optical flow samples with too large integration time spans.

---

msg/templates/urtps/Publisher.cpp.em
msg/templates/urtps/Subscriber.cpp.em

This adds support to FastRTPS release v2.0.0, or the new called FastDDS. The changes on the RTPS API are minimal, and so this allows a simple port. Further iterations on the bridge might consider the complete support for DDS features and API, or simply explore the usage of Micro-XRCE DDS, which shares also some common API on the client proxy/agent side.
As an extra, this also allows bridging with ROS 2 Foxy.
Functionality tested with PX4 SITL and Gazebo. All working as expected.

Feature: add support to FastRTPS 2.0.0 (Fast-DDS)

---

Tools/setup/requirements.txt
Tools/setup/ubuntu.sh

I set up a new Ubuntu 20.04 VM and ran into a bunch of issues. I made some changes to the setup script to avoid all of them.
The commit messages clearly describe the steps.
I retested the changes after resetting the VM to a snapshot just after installation.
The additional python package requirement for matplotlib with an exact old version added in https://github.com/PX4/Firmware/pull/15203 was the main reason the script failed on 20.04.

Fix Ubuntu Script for 20.04

---

msg/vehicle_status.msg
src/modules/commander/Commander.cpp
src/modules/commander/Commander.hpp
src/modules/commander/commander_params.c
src/modules/commander/failure_detector/FailureDetector.cpp
src/modules/commander/failure_detector/FailureDetector.hpp
src/modules/commander/failure_detector/failure_detector_params.c

Main goal of this PR is to extend Failure Detector logic to handle ESC arming state.
Some types of ESC require that you send them an arm command before they can actually spin.
If they succeed transitioning to the armed state, they will send back an acknowledgment to PX4.
This PR extends Failure Detector logic to handle this kind of information:
after the vehicle is armed Failure Detector will wait `300_ms` to get an answer from the ESCs.
If within this time window all the ESCs do not report to be armed Failure Detector will auto disarm the vehicle.
Checks are performed using `esc_status.esc_armed_flags` .
During the development of this PR i've also addressed the following points:
- Added autodisarm if system is in lockdown. Having the …

Extend Failure Detector functionalities

---

platforms/posix/cmake/sitl_target.cmake

Previously, wind was a gazebo model plugin since wind was simulated by applying "force" on a link. Since wind was a element inside the model, models could have different wind simulated even if they are in the same world.
However, this has changed since https://github.com/PX4/sitl_gazebo/pull/462. Therefore, we can make the wind a property of the "world" and make different vehicles be affected to this no matter which vehicle is spawned in the world.
To simulate a windy world, simply run the following.
```
make px4_sitl gazebo_plane__windy
```
Log: https://review.px4.io/plot_app?log=04b3ea46-2489-424d-904c-3e2aadf820cc
Depends on PR …

Enable testing in windy environments

---

ROMFS/px4fmu_common/init.d/airframes/4010_dji_f330
ROMFS/px4fmu_common/init.d/airframes/4011_dji_f450

I saw too many users choose DJI Airframe for their normal ESCs, makes lots of trouble, even hit the ceiling.
So, this change could provent most of these situation.

Raname DJI Airframe name to Provent Large PWM_MIN for normal ESCs

---

Tools/jmavsim_run.sh

This is an attempt to get jMAVSim to run with Java9+.

jMAVSim: try new libs with newer Java versions

---

src/drivers/differential_pressure/sdp3x/SDP3X.cpp
src/drivers/differential_pressure/sdp3x/SDP3X.hpp
src/drivers/differential_pressure/sdp3x/SDP3X_main.cpp

- reconfigure on transfer error (allows recovery from sensor reconnect)
- add State to avoid usleep
- add `-k` option to keep running and retrying even if no sensor present (we have a system that might boot w/o sensor attached).

sdp3x: improve robustness, try to reconfigure on transfer error

---

src/drivers/imu/bosch/bmi055/BMI055_Accelerometer.hpp
src/drivers/imu/bosch/bmi055/BMI055_Gyroscope.hpp
src/drivers/imu/bosch/bmi055/Bosch_BMI055_Accelerometer_Registers.hpp
src/drivers/imu/bosch/bmi055/Bosch_BMI055_Gyroscope_Registers.hpp

- the latch would actually cause more problems if the backup schedule hit
- this reduces the number of cycles where the FIFO is actually empty at max rate (when there's only 1 sample in the FIFO expected)
``` Console
nsh> bmi055 status
INFO  [SPI_I2C] Running on SPI Bus 1
INFO  [bmi055] FIFO empty interval: 500 us (2000.000 Hz)
bmi055_accel: transfer: 127017 events, 1760627us elapsed, 13.86us avg, min 13us max 32us 1.587us rms
bmi055_accel: bad register: 0 events
bmi055_accel: bad transfer: 0 events
bmi055_accel: FIFO empty: 10 events
bmi055_accel: FIFO overflow: 0 events
bmi055_accel: FIFO reset: 1 events
bmi055_accel: DRDY interval: 127047 events, 495.98us avg, min 171us max 1505us 27.462us rms
INFO  [SPI_I2C] Running on SPI Bus 1
INFO  [bmi055] FIFO empty interval: 500 us (2000.000 Hz) …
```

imu/bosch/bmi055: remove interrupt latch

---

src/modules/sensors/vehicle_imu/VehicleIMU.cpp
src/modules/sensors/vehicle_imu/VehicleIMU.hpp
src/modules/sensors/vehicle_imu/imu_parameters.c

- schedule on interval multiple of sensor_gyro publications without increasing the configured integration rate
- run VehicleIMU WorkItem faster (but still on integer multiples of sensor_gyro) to meet `IMU_INTEG_RATE` rather than raise the integration rate
- constrain IMU_INTEG_RATE to [100, IMU_GYRO_RATEMAX] (100 Hz is the minimum for ekf2)
- skip publication interval tracking if gaps in copying sensor_gyro/sensor_accel
In particular this improves the higher rate cases (eg IMU_GYRO_RATEMAX 2-4 kHz). Previously `IMU_INTEG_RATE` would be shifted from 200 Hz -> 250 Hz due to the current sensor_accel/sensor_gyro queue depth (somewhat arbitrary 8). Now in this situation VehicleIMU will still maintain the configured 200 Hz IMU_INTEG_RATE, but instead run twice as fast (400 Hz) to not miss any …

sensors: VehicleIMU improve scheduling

---

src/modules/commander/Arming/PreFlightCheck/checks/manualControlCheck.cpp

This removes the check for the current position of the VTOL switch, as arming is already prevented if in transition mode,
plus also if VTOL and in fixed-wing mode (unless CBRK_VTOL_ARMING is set). That is more general than the check for the RC switch only, and I don't see a problem by removing it.
https://github.com/PX4/Firmware/blob/38fa913fedf49b65d24502182d5af601d41e891b/src/modules/commander/Arming/PreFlightCheck/checks/preArmCheck.cpp#L156
Fixes https://github.com/PX4/Firmware/issues/15212.

PreFlightchecks: remove duplicated VTOL mode prearm check

---

test/mavsdk_tests/process_helper.py

OpenGL options set in the environment like https://github.com/PX4/Firmware/blob/405cb5038d88723bce33b8644ce640798140d053/Tools/setup/ubuntu.sh#L210 are ignored when running `mavsdk_tests` with the `--gui` option to have the gazebo client show what's going on.
Followed https://stackoverflow.com/questions/2231227/python-subprocess-popen-with-a-modified-environment and https://code.tutsplus.com/tutorials/how-to-merge-two-python-dictionaries--cms-26230 to append the local environment to the global one overwriting duplicates.
This could in principle be done for all these invokes, not sure about the potential (dis)advantages. …

mavsdk_tests: load all os environment variables for gazebo client

---

src/drivers/imu/bosch/bmi055/BMI055_Accelerometer.cpp

Small regression with the new driver (https://github.com/PX4/Firmware/pull/15002) that slipped through.

bmi055: accel periodically read temperature

---

src/modules/commander/state_machine_helper.cpp

I found it highly confusing that even though the battery_level can be "dangerous" the commander does not always use the battery_dangerous message to report the current state.
In fact it made me think that there is a problem in the state machine because when battery level was clearly dangerous, commander was still only reporting the critical message.

publish battery_dangerous message if battery level is dangerous

---

src/modules/fw_att_control/ecl_pitch_controller.cpp
src/modules/fw_att_control/ecl_pitch_controller.h
src/modules/fw_att_control/ecl_roll_controller.cpp
src/modules/fw_att_control/ecl_roll_controller.h
src/modules/fw_att_control/ecl_yaw_controller.cpp
src/modules/fw_att_control/ecl_yaw_controller.h

This commit aligns the scaling better with the derivations in
https://dev.px4.io/master/en/flight_stack/controller_diagrams.html#airspeed-scaling
Integrator terms now scale with IAS^2 (all three axes)
To match the roll and pitch controllers:
- Yaw integrator scale is now applied during accumulation, not to
integral value (so now FW_YR_IMAX is respected more intuitively)
- Yaw FF term now scale with IAS instead of IAS^2
Also made a number of small changes to make the three files
(roll, pitch, yaw) 3-way diffable to be clearer about what the
differences among them are.
- Aligns the scaling with the PX4 reference document for scaling: https://dev.px4.io/master/en/flight_stack/controller_diagrams.html#airspeed-scaling
- Aligns the three …

FW attitude control scaling fixes and cleanup

---

Makefile

sed: -e expression #1, char 17: unknown option to `s'
when building with windows toolchain from eclipse

fix sed unknown option to 's'

---

src/modules/commander/Commander.cpp
src/modules/commander/state_machine_helper.cpp

Porting @DanielePettenuzzo 's changes, credit goes to him.
More error rephrasing. These are the ones done in this pr:
- change kill switch from error to info when the vehicle is not flying
- "Data link lost" --> "Connection to ground station lost"
- "Onboard controller lost" --> "Connection to mission computer lost"
- "Failsafe enabled: no RC" --> "Failsafe enabled: Manual control stick input unavailable"
**EDIT:** just found a related non-conflicting pr changing some messageing: https://github.com/PX4/Firmware/pull/14377

Rephrase more errors and warnings

---

msg/orbit_status.msg
src/lib/flight_tasks/tasks/Orbit/FlightTaskOrbit.cpp
src/lib/flight_tasks/tasks/Orbit/FlightTaskOrbit.hpp

Implementing the yaw behaviours for orbit flight mode according the current mavlink specification (https://mavlink.io/en/messages/common.html#MAV_CMD_DO_ORBIT) and an additional yaw behaviour as suggested in https://github.com/mavlink/mavlink/pull/1266. This new addition is important if you have a fpv camera installed in the front of the drone and expect the drone to always look forward.
- For yaw behaviour equals 0, we keep looking at the centre, like the code did before in all cases.
- For 1, we do a yaw setpoint to the heading that we had in the beginning of the flight task.
- For 2, we do no yaw setpoint.
- For 3, we have the yaw setpoint looking always forward.
Tested via QGC (without …

Orbit: Adding orbit yaw behaviours

---

src/lib/flight_tasks/tasks/Orbit/FlightTaskOrbit.cpp

The acceleration setpoint gets implicitly inherited from the altitude flight task since #14212. This feed-forward adds an unwanted acceleration when the right stick is deflected.
Instead of the wrong acceleration setpoint I command the expected centripetal acceleration when flying in a circle as feed-forward for better orbit tracking. This is only possible since #14212.
I SITL tested and the direction and amplitude of the acceleration are exactly like expected.
It also leads to better tracking already with the default orbit radius and a bit increased speed like can be seen in the screenshots below.
Before (malicious feed-forward setpoint removed):
After (adding centripetal acceleration …

FlightTaskOrbit: correct acceleration feed-forward

---

test/mavsdk_tests/autopilot_tester.cpp
test/mavsdk_tests/autopilot_tester.h
test/mavsdk_tests/test_multicopter_mission.cpp

This doesn't change any behavior, just adds a SITL test to make sure the vehicle doesn't slow down when travelling straight through a waypoint.
It also adds 'corridor checks' to allow checking that the vehicle is tracking its mission path during a flight.

Straight line slowdown test

---

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp
src/modules/airspeed_selector/airspeed_selector_main.cpp
src/modules/attitude_estimator_q/attitude_estimator_q_main.cpp
src/modules/ekf2/ekf2_main.cpp
src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
src/modules/land_detector/LandDetector.cpp
src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp
src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/sensors/sensors.cpp
src/modules/sensors/vehicle_acceleration/VehicleAcceleration.cpp
src/modules/sensors/vehicle_air_data/VehicleAirData.cpp
src/modules/sensors/vehicle_imu/VehicleIMU.cpp

The length exceeding the current NuttX limit appears to clobber ps output. I'd rather not find out about the other things in the system it has the potential to smash.
Now's a good time if anyone has a better name in mind.

px4_work_queue: rename navigation_and_controllers -> nav_and_controllers

---

ROMFS/px4fmu_common/init.d-posix/rcS

I just ran SITL and was surprised about the behavior since I studied the code before. I found that there are quite a number of customizations without obvious reason or comment for SITL and e.g. the link loss reaction is different from what we're flying in real.
We should keep SITL simulation as realistic as possible compared to a real flight with default settings such that we either fix the problems or adjust the defaults already in early testing.
I removed various customizations for which I don't see an obvious reason. If those defaults are generally useful we should set them also for real flights or otherwise state clearly why we need to customize?
- Having a different link loss behavior is potentially dangerous …

posix rcS: remove various SITL custom parameters

---

src/systemcmds/tests/CMakeLists.txt

This pr to fix: https://github.com/PX4/Firmware/issues/15275
more detail : https://px4.slack.com/archives/C0W2KUFFT/p1594711366163700
I found the pr that introduced the problem　https://github.com/PX4/Firmware/pull/15301
Ignore compilation warnings
fixed it on my 16.04
@dagar  Is this the correct approach?　

Ignore compilation warnings

---

src/modules/mavlink/CMakeLists.txt
src/modules/mavlink/mavlink_mission.cpp

The `seq` recently changed to an int32.
@romain-chiap FYI

mavlink: mission manager fix signed sequence debug print type

---

test/mavsdk_tests/autopilot_tester.cpp
test/mavsdk_tests/autopilot_tester.h

SITL tests landed state fix

---

test/mavsdk_tests/test_multicopter_mission.cpp

These thresholds sometimes failed on the weak workers, I think due to timing issues

Fix rarely flakey test on Github Actions

---

src/modules/mavlink/mavlink_receiver.cpp

Just a small typo fix in the comments of mavlink_receiver.cpp

Fix comment typo in mavlink_receiver.cpp

---

src/modules/mavlink/mavlink_ftp.cpp

10s inactivity timeout to close session (can be corrected to more suitable timeout).
Without this patch if GCS is disconnected during ftp session, vehicle get stuck with not closed session and GCS will not be able to open new session (FTP: Open failed - out of sessions) until vehicle reboot. Another option is for GCS to send kCmdResetSessions before open any new session, but I suppose it is not right solution (but can be implemented in common).
I'm working with custom GCS, I didn't check this with QGC and don't know will it pass ftp checks.

mavlink_ftp: close inactive session

---

src/lib/mixer_module/mixer_module.cpp

A detail I saw when looking at a control allocation question from @sfuhrer .

mixer_module: use math:constrain

---

src/lib/flight_tasks/tasks/Auto/FlightTaskAuto.cpp
src/lib/flight_tasks/tasks/Auto/FlightTaskAuto.hpp
src/lib/flight_tasks/tasks/AutoMapper/FlightTaskAutoMapper.cpp
src/lib/flight_tasks/tasks/AutoMapper/FlightTaskAutoMapper.hpp
src/lib/flight_tasks/tasks/ManualAltitude/FlightTaskManualAltitude.cpp
src/lib/flight_tasks/tasks/Utility/Sticks.cpp
src/lib/flight_tasks/tasks/Utility/Sticks.hpp
src/modules/mc_pos_control/mc_pos_control_params.c

This is a follow-up to https://github.com/PX4/Firmware/pull/15324 but I didn't want to overload the original pr.
The auto task uses the sticks since https://github.com/PX4/Firmware/pull/12220/ to adjust the land speed during final descend. It did so in a `FlightTaskManual` independent way duplicating the functionality.
- Now it can reuse the `Sticks` library from https://github.com/PX4/Firmware/pull/15324
- For the reusability of the things I copied into the `Sticks` library I had to untangle the landing gear logic since you don't want to override the landing gear automatically set by the land mode using your RC.
- As discussed with @jkflying the stick has a bit more authority to actual stop during slow down and …

FlightTasks: Stick library for auto land

---

src/lib/flight_tasks/tasks/Auto/FlightTaskAuto.cpp

During takeoff, Navigator is sending a constant yaw value.
However, there is always a reset at 1.5m of the yaw estimate in EKF2 that is not handled by Navigator that produces a glitch in the rate controller. Given that in FlightTask, the yaw is already computed and properly corrected in case of an estimator reset event, we just ignore the yaw value sent by navigator during takeoff.
Before:
With this PR:

FlightTaskAuto: fix yaw reset issue during takeoff

---

src/modules/commander/state_machine_helper.cpp

This fixes the takeoff and land CI test where we do a takeoff and land without RC connected.
In my opinion it does not make sense to go into RC lost failsafe if a datalink is still available.
Of course, this can be dangerous if someone has a companion computer connected which gets detected as "data link" but actually has no connection to the ground station.
This is required for the takeoff and land SITL test after https://github.com/PX4/Firmware/pull/15316.

commander: fix takeoff and land CI test

---

src/modules/mavlink/mavlink_messages.cpp

@DonLakeFlyer as discussed.
- the altitude and velocity portions of this message are still relevant without GPS lat/lon
I'm not crazy about the idea of sending this continuously without a way to indicate the lat & lon aren't valid, but let me know what you'd prefer.

mavlink: GLOBAL_POSITION_INT send without lat/lon availability

---

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp

Quick followup to https://github.com/PX4/Firmware/pull/15309.
- vehicle_air_data won't have an update every iteration and these adjusted throttle values aren't stored
This only would have worked in the past because the vast majority of systems were using the ms5611 barometer with a publication rate somewhere around 100 Hz.

fw_pos_control_l1: if using air data (baro) copy every iteration

---

src/drivers/px4io/px4io.cpp
src/drivers/safety_button/SafetyButton.cpp
src/drivers/safety_button/SafetyButton.hpp
src/modules/logger/logged_topics.cpp

For debugging if something goes wrong.

full commander and safety logging by default

---

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp

``` Console
WARN  [load_mon] wq:attitude_ctrl low on stack! (292 bytes left)
WARN  [load_mon] wq:attitude_ctrl low on stack! (292 bytes left)
WARN  [load_mon] wq:attitude_ctrl low on stack! (292 bytes left)
WARN  [load_mon] wq:attitude_ctrl low on stack! (292 bytes left)
WARN  [load_mon] wq:attitude_ctrl low on stack! (292 bytes left)
WARN  [load_mon] wq:attitude_ctrl low on stack! (292 bytes left)
WARN  [load_mon] wq:attitude_ctrl low on stack! (292 bytes left)
```

wq:attitude_ctrl: small stack increase to silence warning

---

msg/CMakeLists.txt
msg/tools/px_generate_uorb_topic_helper.py

- applies to messages with names containing "flags" or "bits" and unsigned fixed width integer type (uint8, uint16, uint32)
``` Console
nsh> listener estimator_status
TOPIC: estimator_status
estimator_status_s
timestamp: 63865011  (0.004478 seconds ago)
states: [0.0499, 0.0007, -0.0241, 0.9984, -0.2369, 0.2916, 0.0396, -0.1543, 0.2069, 0.1159, 0.0000, 0.0000, -0.0001, 0.0000, 0.0000, -0.0001, 0.4105, -0.1005, 0.8565, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]
vibe: [0.0000, 0.0000, 0.0003]
covariances: [0.0002, 0.0000, 0.0000, 0.0000, 0.0483, 0.0482, 0.0427, 0.0809, 0.0808, 0.2147, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]
output_tracking_error: [0.0076, 0.0209, 0.0196]
control_mode_flags: 67109395 …
```

uORB: print individual bits of fields

---

src/drivers/tap_esc/tap_esc.cpp
src/lib/mixer_module/mixer_module.cpp

I changed the input constraint in #15349 but screwed up the usage because I was convinced it's püass by reference. I'll double check for sure next time.
It's pass by value and the return value has to be assigned again like @bkueng pointed out in https://github.com/PX4/Firmware/pull/15349/files#r457096522 Thanks!!

mixer_module/tap_esc: fix usage of constrain() on input

---

src/modules/events/rc_loss_alarm.h

While looking into how the events module works, I found an unimplemented method declaration.
That method was originally used and got removed in https://github.com/PX4/Firmware/commit/dc05ceaad2d3786d1c4929dbe867c044fbffe1dd#diff-70b849148026420261dae206d4aa2c6fL60

rc_loss_alarm: remove unimplemented declaration

---

src/modules/sensors/vehicle_imu/VehicleIMU.cpp

- this lowers the load immediately at boot while still allowing each VehicleIMU instance to properly measure the actual accel/gyro data rates

sensors/vehicle_imu: initially schedule conservatively

---

src/modules/vtol_att_control/tailsitter.cpp

To fix: https://github.com/PX4/Firmware/issues/15037
ensure input quaternions are exactly normalized because acosf(1.00001) == NaN
Test tomorrow
@sfuhrer  Is my solution the best? Or should we start with `acosf` functions?

Fix transition fail on tailsitter

---

src/lib/flight_tasks/tasks/Orbit/FlightTaskOrbit.cpp
src/lib/flight_tasks/tasks/Orbit/FlightTaskOrbit.hpp

Like discussed in https://github.com/PX4/Firmware/pull/13426#issuecomment-657430405 I had some open suggestions. FYI @dayjaby
> - If there is a line break in the Doxygen comment anyways we can put it before the declaration.
> - FlightTaskManualAltitude which orbit is inheriting from is already generating yaw setpoints from RC. I know this is confusing and the goal is to move this stuff into libraries such that you can just write "I want the yaw generation from RC" instead of silently inheriting.
> - Your way of calculating `start_to_circle` is much nicer 👍  I just moved it back into the local scope such that it's only calculated when used. Unrelated I also added some const qualifiers and switched the parameter …

Orbit yaw behaviours addition

---

src/lib/flight_tasks/tasks/Orbit/FlightTaskOrbit.cpp
src/lib/flight_tasks/tasks/Utility/StraightLine.cpp
src/lib/flight_tasks/tasks/Utility/StraightLine.hpp

Credits got to @RomanBapst for finding all of these issues and helping me to fix them:
1. sending a new orbit command during approach lead to finishing the old approach and jumping to the new circle
1. changing the radius during approach lead to approaching to the old radius and jumping to the new one
1. the way setpoint output was not wrapped and could exceed the range
it showed in the log but still executed fine since sin() and cos() work properly also outside of [-pi, pi]
1. reset the approach when a new orbit is commanded
1. reset the approach when the radius is changed
1. wrap the yaw setpoint before it's sent out
I SITL tested.

Orbit approach fixes

---

Makefile

The config file was missing and a speed factor of 20 is much more realistic.

Makefile: fix mavsdk_tests invocation

---

Tools/setup/arch.sh
Tools/setup/ubuntu.sh

On normal desktop distributions dmidecode is preinstalled and I was assuming it's part of the core tools. Thanks to a hint https://github.com/PX4/Firmware/pull/15241#issuecomment-659395458 I found out it's not and am installing the package before using it.
I checked the package to be available and already installed on my systems on Manjaro and Ubuntu 20.04.

setup scripts: install dmidecode before using it

---

ROMFS/px4fmu_common/init.d/airframes/4016_holybro_px4vision
ROMFS/px4fmu_common/init.d/airframes/4041_beta75x
ROMFS/px4fmu_common/init.d/airframes/4050_generic_250
ROMFS/px4fmu_common/init.d/airframes/4052_holybro_qav250
ROMFS/px4fmu_common/init.d/airframes/4071_ifo
ROMFS/px4fmu_common/init.d/airframes/4072_draco
ROMFS/px4fmu_common/init.d/airframes/4073_ifo-s
ROMFS/px4fmu_common/init.d/airframes/6002_draco_r

The parameter `RC_FLT_CUTOFF` was removed in #14896 and I forgot to remove it from all the configurations.
The RC filter is gone because the different modes using RC have the option now to filter the setpoints to get a not "too agressive" reaction. So no need to set the parameter anymore.
Thanks @bkueng for reminding me to take care of the orphan configurations in https://github.com/PX4/Firmware/pull/14896#issuecomment-633910892

ROMFS: remove remaining RC_FLT_CUTOFF

---

src/modules/vtol_att_control/vtol_att_control_main.cpp
src/modules/vtol_att_control/vtol_att_control_main.h

This is to prevent `vtol_att_control` running at absurdly high rates (kilohertz) from every single actuator controls publication from both the multicopter and fixed wing controllers. I don't really like this solution, but it works for now until there are larger VTOL architectural changes in place.
It's not really an issue if `IMU_GYRO_RATEMAX` is set appropriately for these platforms, but currently it's still possible to slip through with the defaults intended for a small multicopter.

vtol_att_control: limit excessive scheduling

---

src/modules/mavlink/mavlink_messages.cpp

Reverts PX4/Firmware#15308
85% of PX4 contributors are working with commercial vendors. So our contributors expect commercial quality out of this open source project, not some hobby entertainment. The fact that APM has been doing this for years doesn't make it a valid approach. Entering magic values into a valid range is against best practices. It is unlikely that a lat / lon of 0/0 ever hits a real system - yes. But if I were to review the PX4 codebase and found stuff like that I would loose trust into the implementers because very apparently they are too lazy to implement things correctly and have all sorts of magic easter eggs hidden.
And magic values are fine until they are not. And it is very simple to objectify this: If a unit test that does an input data sweep would fall over, then …

Revert "mavlink: GLOBAL_POSITION_INT send without lat/lon availability"

---

ROMFS/px4fmu_common/init.d-posix/1042_tiltrotor
ROMFS/px4fmu_common/init.d/airframes/13012_convergence
ROMFS/px4fmu_common/init.d/airframes/13013_deltaquad

```
/**
* Airspeed mode
*
* For small wings or VTOL without airspeed sensor this parameter can be used to
* enable flying without an airspeed reading
*
* @value 0 Normal (use airspeed if available)
* @value 1 Airspeed disabled
* @group FW Attitude Control
*/
PARAM_DEFINE_INT32(FW_ARSP_MODE, 0);
```
not have value 2
By the way, I think the functions of these two parameters are similar　`CBRK_AIRSPD_CHK`   `FW_ARSP_MODE`
Can we just keep `CBRK_AIRSPD_CHK`? Use `CBRK_AIRSPD_CHK` instead of `FW_ARSP_MODE`
FYI @sfuhrer

Correctly set the FW_ARSP_MODE parameter value

---

Tools/sitl_run.sh

Sometimes gzserver seems to not start or not start fast enough. In this case, instead of stalling forever, it would be nice to abort.
Closes #15398.

Tools: abort SITL start if gzserver fails

---

src/drivers/pwm_out/PWMOut.cpp
src/drivers/pwm_out/PWMOut.hpp
src/lib/mixer_module/mixer_module.cpp
src/lib/mixer_module/mixer_module.hpp

When a passthrough or gimbal mixer is loaded in addition to the primary mixer the output module will be schedule to run on both controller updates (new actuator_controls_0 publications) as well as new RC data (actuator_controls_3). This can be problematic for things like OneShot ESCs that don't seem to like very tight back to back updates.
This limits scheduling of the output module (pwm_out) to primarily run on updates to the primary actuator control groups (0 & 1) if in use. Additionally there's a backup should groups 0 & 1 stop publishing for some reason.
- fixes OneShot in certain configurations https://github.com/PX4/Firmware/issues/15043

drivers/pwm_out: limit scheduling to primary actuator controls groups if used

---

src/lib/mathlib/CMakeLists.txt
src/lib/mathlib/math/Functions.hpp
src/lib/mathlib/math/FunctionsTest.cpp
src/modules/mc_att_control/mc_att_control_main.cpp

The function remapping the throttle range such that mid stick you're on hover thrust is very similar to the `gradual` function I already added long time ago. It can be reused for other purposes and I was experimenting with one in the land speed (#15325) adjustment because upwards and downwards speed could be set differently.
I put the function into `Functions.hpp` of the `mathlib` for reuse and testing.
I flew in SITL and it does the same thing as before.

mc_att_control: add gradual3 function to cover hover thrust rescaling

---

src/lib/parameters/px4params/injectxmlparams.py
src/lib/parameters/px4params/srcparser.py
src/lib/parameters/px4params/xmlout.py
src/lib/parameters/px_process_params.py

Param metadata is generated from source param definitions. The xmloutput parser also prefixes the generated parameter.xml file with additional "injected XML" that it pulls in from a local file. The problem with this is that this injected XML is not included in the generated markdown output, and would also need to be  pulled into the [json parameter output](https://github.com/PX4/Firmware/pull/15389) and any future output formats.
What this change does is import the injected XML into parameter groups and prepend these to the parameter group list before it is passed to the output generators. With this change the groups in the XML are added for any new output.
I have tested this and the output is the almost identical to the original XML. 
- Generated output is better in that output field …

Move XML injection to the group level

---

msg/tools/generate_microRTPS_bridge.py

Hi,
When compiling firmware with rtps, I found unnecessary messages by ldconfig in my case
This problem happens in px4_ros_com.
please check it.
```
[769/778] Generating RTPS topic bridge
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
/sbin/ldconfig.real: Can't stat /usr/local/lib/i386-linux-gnu: No such file or directory
/sbin/ldconfig.real: Can't stat /usr/local/lib/i686-linux-gnu: No such file or directory
/sbin/ldconfig.real: Can't stat /lib/i686-linux-gnu: No such file or directory
/sbin/ldconfig.real: Can't stat /usr/lib/i686-linux-gnu: No such file or directory
/sbin/ldconfig.real: Can't stat /usr/local/lib/x86_64-linux-gnu: No such file or directory
/sbin/ldconfig.real: …
```

remove unnecessary stderr msg when checking ldconfig

---

msg/templates/urtps/RtpsTopics.h.em
msg/templates/urtps/microRTPS_timesync.h.em

I found some errors when compiling RTPS.
I think that it is same problem in px4_ros_com.
```
/root/px4_ros_com_ros2/src/px4_ros_com/src/micrortps_agent/microRTPS_timesync.h:170:114: warning: no return statement in function returning non-void [-Wreturn-type]
inline uint64_t setMsgTimestamp(timesync_msg_t* msg, const uint64_t& timestamp) { msg->timestamp() = timestamp; }
```
please check it ..

fix the return type problem of RTPS

---

Tools/sitl_run.sh

This should prevent the race between gzserver and gz model and fix the integration tests which sometimes timeout because the model is not spawned correctly.
This patch also changes the shebang to what's generally recommended.

Tools: retry gz model if gzserver is not ready yet

---

src/modules/load_mon/LoadMon.cpp

Along with other fixes I recently changed the `load_mon` interval from 1000 ms to 300 ms (1 Hz -> 3.33 Hz) with the intention of capturing more cpu load detail in the logs.
Now that we have data from an actual flight I think we're just seeing more distracting noise possibly from load_mon itself being somewhat erratically scheduled in the low priority work queue.
This PR decreases the rate to get a slightly longer cpuload average. 
To really improve this in the future I'd likely move the load calculation so that it's not dependent on work queue scheduling for timing and possibly track multiple averages (somewhat like a linux load average).

load_mon: slightly longer cpu average (300 -> 500 ms)

---

src/drivers/distance_sensor/ll40ls/LidarLiteI2C.cpp

I have found that for lidar lite v3hp setting the quality to 0 if the distance is 0 is not correct. end even 0 distance reading is valid.
note that for v3hp the quality is being set by _ll40ls_signal_strength_ only while the other Lidars has different mechanisiom.
for example, here is one log that I have, that shows that quality field is set to 0, on ground even that the reading is valid.
you can also see the quality value before it was rescaled to 0:100
The PR has splited to two commits, the first is the "important" that has real behavior change, the second is jest simplification of the code (in my opinion)

Lidar Lite v3HP quality

---

src/drivers/optical_flow/paw3902/PAW3902.cpp
src/drivers/optical_flow/paw3902/PAW3902.hpp

1. The spec specifies that the mode change condition should be met for 10
consecutive frames before changing to the next mode.
2. The spec (and comment) says that "PAW3902JF should not operate with Shutter < 0x01F4 in Mode 2" -
however the if condition checked the reverse condition
Signed-off-by: Koby Aizer <koby.aizer@tg-17.com>

PAW3902: align mode change logic with the spec

---

src/drivers/optical_flow/paw3902/PAW3902.cpp

optical_flow/paw3902: silence info output (info -> debug)

---

msg/logger_status.msg
src/modules/logger/logger.cpp
src/modules/logger/logger.h
src/modules/uORB/SubscriptionInterval.hpp

This adds simple logging of gaps in uORB copies for full rate (no interval) messages. Currently it's possible to miss messages while still having no dropouts in the ulg.

logger: record message gaps

---

src/modules/logger/logged_topics.cpp
src/modules/logger/params.c

- unnecessarily wearing out cheap sd cards that come with most flight controllers
- default cards often stop functioning entirely within months of operating on the test rack (logging for ~5 minutes at a time 5-20 times/day)
- default ekf2 replay really needs logging from boot anyway (@priseborough)
- some people actually use USB and Mavlink FTP to transfer log files
- nominal logging rate `~32 KiB/s` (~115 MiB/hour)
- nominal logging rate `~15 KiB/s` (~54 MiB/hour)
As a follow up I would look at further optimizing the default logging rate.

logger: disable estimator replay logging by default

---

ROMFS/px4fmu_common/init.d/rc.io
src/drivers/px4io/px4io.cpp

- delete broken px4io test and if_test
- delete px4io limit (a fixed 400 Hz limit was always set at boot)
Saves 1.05Ki of flash on fmu-v2.

px4io: delete broken test and unnecessary limit

---

msg/templates/uorb_microcdr/microRTPS_client.cpp.em
msg/templates/urtps/Publisher.cpp.em
msg/templates/urtps/RtpsTopics.cpp.em
msg/templates/urtps/Subscriber.cpp.em
msg/templates/urtps/microRTPS_agent.cpp.em
msg/templates/urtps/microRTPS_timesync.cpp.em
msg/templates/urtps/microRTPS_transport.cpp
msg/templates/urtps/microRTPS_transport.h
msg/tools/generate_microRTPS_bridge.py
src/modules/micrortps_bridge/micrortps_client/microRTPS_client.h
src/modules/micrortps_bridge/micrortps_client/microRTPS_client_main.cpp

Currently the microRTPS bridge UART link is broken and it's resulting on continuous CRC errors on the agent side that after some seconds close the link. This is being investigated.
Also, it was verified that a stack increase was required to avoid the `micrortps_client` of causing and hardfault and rebooting the flight controller.

microRTPS: fix UART link

---

msg/input_rc.msg
src/drivers/rc_input/RCInput.cpp
src/lib/rc/dsm.cpp
src/lib/rc/dsm.h
src/lib/rc/rc_tests/RCTest.cpp
src/modules/rc_update/rc_update.cpp
src/modules/rc_update/rc_update.h

- always check system field for validity
- reject any data outside of "servo position" valid range
- properly support XPlus channels (12+)
- warn if channel count changes
Now that the default filter has been removed from the RC input handling it's possible to occasionally see bad RC input data.
For example uncommanded throttle spikes that can't be explained by controllers, or the detected channel count fluctuating.

rc/dsm: decode improvements

---

cmake/metadata.cmake
src/lib/parameters/CMakeLists.txt
src/lib/parameters/px4params/jsonout.py
src/lib/parameters/px_process_params.py

MAVLink has defined a standardised way for a GCS to query a component's parameter metadata (in this case  autopilot) in [Using COMPONENT_INFORMATION to obtain vehicle metadata](https://github.com/mavlink/mavlink/issues/1346).
This does the first part of that work by automatically generating the parameter metadata in Json format.  The generated output for the FIRST version of this can be found here: https://gist.github.com/hamishwillee/3779fcfb6bd368b1cd9fd3f84cbcb5b6
The parser works, but is not ready for merging because the schema defined in https://github.com/mavlink/mavlink/issues/1346 is incomplete/incorrect with respect to the test code provided. 
Once schema is signed off by @DonLakeFlyer the output here can be validated/updated. Further modifications for changes should be fairly …

Generate param metadata as MAVLink-compatible JSON component info

---

src/lib/flight_tasks/tasks/Auto/FlightTaskAuto.cpp

Fixes https://github.com/PX4/Firmware/issues/15409, which was introduced by https://github.com/PX4/Firmware/pull/15358. 
It's certainly not the cleanest solution, but I guess it serves as a quick fix, as we already have the disable_weather_vane flag read in the FlightTask for a very similar purpose (to enable the aligning with the transition wp, weather vane needs to be switched off).
Maybe renaming the flag from "disable_weather_vane" to "enable_navigator_yaw_control" / "enforce_navigator_yaw_setpoint" makes it a bit cleaner. Or I guess even better it would be to have the alignment logic inside the flight task, and not Navigator.

FlightTask Auto: use yaw setpoint from Navigator if aligning for transition in VTOL_takeoff

---

ROMFS/px4fmu_common/init.d/rcS
boards/av/x-v1/src/board_config.h
boards/px4/fmu-v5x/src/board_config.h
src/drivers/camera_capture/camera_capture.cpp
src/drivers/camera_capture/camera_capture.hpp
src/drivers/camera_trigger/interfaces/src/gpio.cpp
src/drivers/dshot/dshot.cpp
src/drivers/pwm_out/PWMOut.cpp

- Fixes camera triggering via PWM (1. commit)
- v5x: use board-specific camera capture pin PI0
- TRIG_PINS: allow triggering on 78 while still using the lower 6 pins for pwm
The whole camera trigger/capture pins config will need a bigger overhaul if we want to have more configurability. For now this should do though.
Replaces #10857

camera triggering fix (PWM) + triggering on 78

---

src/modules/commander/Commander.cpp
src/modules/mavlink/mavlink_main.cpp
src/modules/navigator/navigator_main.cpp
src/modules/uORB/uORBDeviceMaster.cpp
src/modules/uORB/uORBDeviceMaster.hpp
src/modules/uORB/uORBDeviceNode.cpp
src/modules/uORB/uORBDeviceNode.hpp
src/modules/uORB/uORBMain.cpp

Tracking the number of lost messages per uORB publication (uORB::DeviceNode) isn't generally useful because there are too many cases where it's perfectly acceptable for a subscription to only capture a subset of the updates. For the cases where it does matter we now have mechanisms for each subscription to track gaps (see sensors/vehicle_imu or logger message_gaps).
Removing `lost_messages` from each `uORB::DeviceNode` saves a little ram (and a tiny amount of cpu), makes `uorb top` a bit less confusing, and frees up `uorb status` to be used for a better overall status output. 
``` Console
nsh> uorb status
TOPIC NAME                     INST #SUB #Q SIZE PRIO PATH
log_message                       0    0  2  136   75 /obj/log_message0
parameter_update                  0   22  1   16   75 …
```

uORB: remove lost message count per DeviceNode

---

msg/vehicle_status.msg
src/modules/commander/Commander.cpp
src/modules/commander/Commander.hpp
src/modules/commander/commander_tests/state_machine_helper_test.cpp
src/modules/commander/state_machine_helper.cpp
src/modules/commander/state_machine_helper.h

- I've come across multiple logs where the disarming reason was not clear and unexpected.
- There is an increasing number of components that can trigger arming/disarming (e.g. kill-switch or failure detector).
Adding the latest arming/disarming reason to vehicle_status makes things explicit.

vehicle_status: add latest arming/disarming reason

---

platforms/common/include/px4_platform_common/px4_work_queue/WorkItem.hpp
platforms/common/include/px4_platform_common/px4_work_queue/WorkQueue.hpp
platforms/posix/cmake/sitl_tests.cmake
src/include/containers/BlockingList.hpp
src/include/containers/IntrusiveSortedList.hpp
src/modules/uORB/uORBDeviceMaster.hpp
src/modules/uORB/uORBDeviceNode.hpp
src/systemcmds/tests/CMakeLists.txt
src/systemcmds/tests/test_IntrusiveSortedList.cpp
src/systemcmds/tests/tests_main.c
src/systemcmds/tests/tests_main.h

This is a new linked list container (c++ template) that sorts on insertion. It's primarily for convenience for inspecting things in the system like uORB or WorkQueues. These are lists of things that are effectively static for the duration of operation in any normal usage (once booted), so there's no issue with doing slightly more work on insertion.
Usage is nearly identical to the existing `List` container other than having to additionally implement `operator<=` in your `IntrusiveSortedListNode`.
``` Console
update: 1s, num topics: 77
TOPIC NAME                     INST #SUB RATE #LOST #Q SIZE
actuator_armed                    0    4    1     0  1   24 
actuator_controls_0               0    6  800  2654  1   48 
actuator_outputs                  0    3   46    90  1   80 
adc_report …
```

introduce IntrusiveSortedList and use for uORB, WorkQueues, and WorkItems

---

boards/spracing/h7extreme/init/rc.board_extras

This is a simple configuration change that enables OSD. I can confirm that OSD works on this board.

SPRacing H7 extreme - OSD enabled

---

src/lib/parameters/px4params/jsonout.py

Json param field names [changed in MAVLink](https://github.com/mavlink/mavlink/pull/1431) to longDesc, shortDesc, default (for consistency and size reasons).
@bkueng Do we standardise our units? The units accepted by QGC/MAVLink under discussion here: https://github.com/mavlink/mavlink/pull/1431/files#r464716317
The reason I ask is that the UAVCAN ones are inconsistent with the PX4 ones - e.g. Hertz, etc - see https://gist.github.com/hamishwillee/3779fcfb6bd368b1cd9fd3f84cbcb5b6
Should they be the same? If so, you OK with me moving the inject code before the validator, then fixing up the injected XML - OR, should I tidy up the output as expected by MAVLink once this stabilises?

Update json param field names

---

src/lib/flight_tasks/tasks/Auto/FlightTaskAuto.cpp
src/lib/flight_tasks/tasks/Auto/FlightTaskAuto.hpp
src/lib/flight_tasks/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.cpp
src/lib/flight_tasks/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.hpp
src/lib/flight_tasks/tasks/AutoMapper/FlightTaskAutoMapper.cpp
src/lib/flight_tasks/tasks/AutoMapper/FlightTaskAutoMapper.hpp
src/lib/flight_tasks/tasks/Descend/FlightTaskDescend.cpp
src/lib/flight_tasks/tasks/Descend/FlightTaskDescend.hpp
src/lib/flight_tasks/tasks/Failsafe/FlightTaskFailsafe.cpp
src/lib/flight_tasks/tasks/Failsafe/FlightTaskFailsafe.hpp
src/lib/flight_tasks/tasks/FlightTask/FlightTask.cpp
src/lib/flight_tasks/tasks/FlightTask/FlightTask.hpp
src/lib/flight_tasks/tasks/ManualAltitude/FlightTaskManualAltitude.cpp
src/lib/flight_tasks/tasks/ManualAltitude/FlightTaskManualAltitude.hpp
src/lib/flight_tasks/tasks/ManualAltitudeSmoothVel/FlightTaskManualAltitudeSmoothVel.cpp
src/lib/flight_tasks/tasks/ManualAltitudeSmoothVel/FlightTaskManualAltitudeSmoothVel.hpp
src/lib/flight_tasks/tasks/ManualPosition/FlightTaskManualPosition.cpp
src/lib/flight_tasks/tasks/ManualPosition/FlightTaskManualPosition.hpp
src/lib/flight_tasks/tasks/ManualPositionSmoothVel/FlightTaskManualPositionSmoothVel.cpp
src/lib/flight_tasks/tasks/ManualPositionSmoothVel/FlightTaskManualPositionSmoothVel.hpp
src/lib/flight_tasks/tasks/Offboard/FlightTaskOffboard.cpp
src/lib/flight_tasks/tasks/Offboard/FlightTaskOffboard.hpp
src/lib/flight_tasks/tasks/Orbit/FlightTaskOrbit.cpp
src/lib/flight_tasks/tasks/Orbit/FlightTaskOrbit.hpp
src/lib/flight_tasks/tasks/Transition/FlightTaskTransition.cpp
src/lib/flight_tasks/tasks/Transition/FlightTaskTransition.hpp

- perform setpoint checks in place to simplify and avoid copy

flight_tasks: pass previous setpoint as const reference

---

src/lib/cdev/CDev.hpp
src/lib/cdev/CMakeLists.txt

- poll, poll_notify, register_class_devname, unregister_class_devname aren't virtual
- increase max optimization level on platforms that aren't flash constrained (MAX_CUSTOM_OPT_LEVEL)
Saves a little flash.
``` Console
VM SIZE    
-------------- 
+24%     +88    cdev::CDev::poll(file*, pollfd*, bool)
+35%     +22    cdev::CDev::open(file*)
+83%     +20    cdev::cdev_ioctl(file*, int, unsigned long)
+83%     +20    cdev::cdev_read(file*, char*, unsigned int)
+83%     +20    cdev::cdev_seek(file*, int, int)
+83%     +20    cdev::cdev_write(file*, char const*, unsigned int)
+0.0%     +12    [section .text]
+20%     +12    cdev::CDev::close(file*)
+18%     +12    cdev::CDev::poll_notify(unsigned char)
+22%      +8    cdev::CDev::CDev(char const*)
+11%      +4    cdev::CDev::init()
+5.0% …
```

cdev: remove unnecessary virtuals and increase opt level

---

src/modules/uuv_att_control/uuv_att_control.cpp
src/modules/uuv_att_control/uuv_att_control.hpp

The geometric controller of the uuv_att_control module now respects the bodyrate setpoint instead of assuming the bodyrate should always be zero.

added bodyrate setpoint to the geometric controller of the uuv_att_control module

---

msg/CMakeLists.txt
msg/telemetry_heartbeat.msg
msg/telemetry_status.msg
msg/tools/uorb_rtps_message_ids.yaml
src/modules/commander/Commander.cpp
src/modules/commander/Commander.hpp
src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_main.h
src/modules/mavlink/mavlink_receiver.cpp

- one telemetry_status publication per mavlink instance
- each telemetry_status has an array of unique HEARTBEATS
This is useful to monitor what's going on with other mavlink components that are part of the same system (gimbals, etc). It's also more convenient for review to have a telemetry status per mavlink instance rather than mixing them on the same publication instance.

telemetry status updates

---

ROMFS/px4fmu_common/init.d-posix/1016_iris_rtps.post
Tools/gazebo_sitl_multiple_run.sh

Hi,
To operate UAVs based on RTPS, I modified gazebo_sitl_multiple_run.sh.
(refer to #15147)
```
./Tools/gazebo_sitl_multiple_run.sh -m iris_rtps -n 3
```
Thanks 
FYI. @Jaeyoung-Lim

add gazebo simulation based on RTPS for multiple UAVs

---

src/lib/flight_tasks/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.cpp

fixes https://github.com/PX4/Firmware/issues/15408
Because the velocity starts with a positive value (down) to ramp-up slowly the motors, the position setpoint (integral) was going down into the ground, canceling the input of the velocity controller during the early takeoff phase.
Instead of a smooth ramp, the behavior was a delay followed by a quick takeoff or a land detection.
Setting the current altitude setpoint with the current altitude during this phase avoids the canceling effect and creates a takeoff purely velocity-based.
SITL (jMavSim) results:
`MPC_TKO_RAMP_T = 5s` for both tests.
Before, the trajectory_setpoint.z was going down during the early takeoff phase, delaying the thrust ramp:
Now, the thrust ramps properly since the beginning of the velocity ramp:
@ThomasRigi Could …

Tko ramp: fix takeoff issue with large tko ramp time

---

ROMFS/px4fmu_common/init.d/airframes/50004_nxpcup_car_dfrobot_gpx
ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt

The "DF Robot Asurada: GPX Aiframe" is renamed to "NXP Cup car: DF Robot GPX". This was made to give a clear understanding of the purpose of this airframe. This rover is mainly used for the NXP Cup.
Renaming of the 50004_dfrobot_gpx_asurada to 50004_nxpcup_car_dfrobot_gpx.
If this solution is not okay, a new airframe with same parameters but other name can be considered.

Rename of the DF Robot Rover Airframe

---

src/modules/fw_att_control/FixedwingAttitudeControl.cpp
src/modules/fw_att_control/FixedwingAttitudeControl.hpp
src/modules/fw_att_control/ecl_controller.h
src/modules/fw_att_control/ecl_pitch_controller.cpp
src/modules/fw_att_control/ecl_pitch_controller.h
src/modules/fw_att_control/ecl_roll_controller.cpp
src/modules/fw_att_control/ecl_roll_controller.h
src/modules/fw_att_control/ecl_wheel_controller.cpp
src/modules/fw_att_control/ecl_wheel_controller.h
src/modules/fw_att_control/ecl_yaw_controller.cpp
src/modules/fw_att_control/ecl_yaw_controller.h
src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
src/modules/fw_pos_control_l1/launchdetection/CatapultLaunchMethod.cpp
src/modules/fw_pos_control_l1/launchdetection/CatapultLaunchMethod.h
src/modules/fw_pos_control_l1/launchdetection/LaunchDetector.cpp
src/modules/fw_pos_control_l1/launchdetection/LaunchDetector.h
src/modules/fw_pos_control_l1/launchdetection/LaunchMethod.h
src/modules/fw_pos_control_l1/runway_takeoff/RunwayTakeoff.cpp
src/modules/fw_pos_control_l1/runway_takeoff/RunwayTakeoff.h
src/modules/mc_att_control/mc_att_control_main.cpp
src/modules/mc_pos_control/Takeoff/Takeoff.hpp
src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/mc_rate_control/MulticopterRateControl.cpp

The controllers are always scheduled by a publication of `vehicle_angular_velocity`, `vehicle_attitude`,  or `vehicle_local_position`, so for things like calculating dt we can simply use the timestamp from those publications rather than the current time. This is a bit more robust during disruptions and jitter like parameter update and it's slightly cheaper.

controllers dt use topic update timestamp

---

src/modules/mc_att_control/AttitudeControl/AttitudeControl.cpp
src/modules/mc_att_control/AttitudeControl/AttitudeControl.hpp
src/modules/mc_att_control/mc_att_control.hpp
src/modules/mc_att_control/mc_att_control_main.cpp

This is a couple quick optimizations I saw in mc_att_control. In general we should try to avoid keeping unnecessary state (eg full msg copies) when often only a couple fields are needed only when updated.

mc_att_control: a few minor optimizations 

---

src/drivers/distance_sensor/cm8jl65/CM8JL65.cpp

This avoids infinitely spamming `PX4_ERR("read error: %i, errno: %i", bytes_read, errno);`  if the driver is running but no distance sensor is connected.
Tested with real hardware

cm8jl65: avoid flooding console with errors if errno is EAGAIN

---

src/modules/vtol_att_control/vtol_type.cpp

1) The VtolType::init() method was not using the correct pwm output device if motors were attached to the FMU.
2) The filter states used in quadchute were not reset to reset in case TECS was not running.
Still awaiting testing results for 1)

VTOL: Use correct pwm output device & reset quadchute states

---

src/modules/commander/Arming/PreFlightCheck/checks/powerCheck.cpp

- this check isn't relevent during bench testing

commander: preflight power check ignore module count if USB connected

---

src/modules/mavlink/mavlink_timesync.cpp

mavlink_timesync: print sender comp id for 'RTT too high for timesync' msg

---

platforms/common/shutdown.cpp

Fixes bug, where reboot -b would not stay in bootloader. Call was passing bit mask (=4) not integer value of 1.

common/shutdown:All FMU's not staying in bootloader

---

platforms/nuttx/src/bootloader/bl.c

It appear that QGC is not resyncing between operation.
This was causing the bl_state to be reset to STATE_PROTO_GET_SYNC
and loosing the state of (STATE_PROTO_GET_SYNC|STATE_PROTO_GET_DEVICE)
@CUAVcaijie @DonLakeFlyer

NuttX based bootloader:Track QGC change in sequencing

---

boards/px4/fmu-v6x/src/hw_config.h

Was 139 (durandal) is 53 px4_fmu-v6x

px4_fmu-v6x Fix BOARD_TYPE

---

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp

``` Console
WARN  [load_mon] wq:attitude_ctrl low on stack! (284 bytes left)
```

wq:attitude_ctrl increase stack (again)

---

src/modules/logger/logged_topics.cpp

Currently it is required to set the `VISION_AND_AVOIDANCE` bit in the `SDLOG_PROFILE` parameter of PX4 to log performance metrics coming from the mission computer, which doesn't make much sense since this is not specific to a profile like that, even though it does require a connection to a companion/mission computer.
Log the `onboard_computer_status` topic by default. Set to 10 Hz, but can be even lower.

logger: by default, log the onboard_computer_status topic

---

src/drivers/magnetometer/lis2mdl/lis2mdl.cpp
src/drivers/magnetometer/lis3mdl/lis3mdl.cpp
src/drivers/magnetometer/rm3100/rm3100.cpp

Similar to https://github.com/PX4/Firmware/pull/15525, we really need to be conservative with any error messages that have the potential to flood the console and even drag other parts of the system down. 
``` Console
WARN  [lis3mdl] Register read error.
WARN  [lis3mdl] Register read error.
WARN  [lis3mdl] Register read error.
WARN  [lis3mdl] Register read error.
WARN  [lis3mdl] Register read error.
```

magnetometer drivers remove register read error message

---

.github/workflows/metadata.yml
Jenkinsfile
msg/templates/urtps/microRTPS_agent_CMakeLists.txt.em
msg/tools/generate_microRTPS_bridge.py
src/modules/micrortps_bridge/micrortps_client/CMakeLists.txt

To deploy the microRTPS agent in any system, it's currently required that one builds the `_rtps` target and then `cd` inside the `build` folder of the Firmware to get to the source files of the agent and then build it manually. Since the overall bridge was already validated, it made sense to automate the deployment of the different parts of the bridge (excluding the client, since it composes a PX4 Firmware module).
1. Split the microRTPS agent and client destination directories, so one can handle them properly after the CMake build.
2. Add a deploy stage for the microRTPS bridge source code (including the PX4 generated IDL files for convenience) to the https://github.com/PX4/micrortps_agent repo.

[CI/CD] Feature: deploy microRTPS agent to a separate respository

---

boards/modalai/fc-v1/init/rc.board_defaults

Correcting default MAV_1 configuration to use Onboard mode.  Remove MAV_2 configuration, no longer used, and this port will be used by UART ESCs in future pull request.
Simply set new values in board_defaults
N/A
Bench tested with reset of parameters.
N/A

modalai-fc-v1 - update default MAVLink configuration

---

src/lib/flight_tasks/tasks/Offboard/FlightTaskOffboard.cpp
src/modules/uORB/Subscription.cpp
src/modules/uORB/Subscription.hpp
src/modules/uORB/uORBDeviceNode.cpp
src/modules/uORB/uORBDeviceNode.hpp

This finally brings "new" uORB Subscriptions full circle with file descriptor based subscriptions (orb_subscribe/px4_open), unifying `uORB::Subscription` as the internal data structure of a subscription in all cases.
- orb_subscribe/orb_unsubscribe are now equivalent to `uORB::SubscriptionInterval` construction/destruction
- previously we had slightly different logic and lazy subscribing (first update) in `uORB::Subscription`
- update checks or modifying a subscription interval are now identical code paths
The downside is that each old style orb subscription is slightly more expensive (a few extra fields per Subscription), but there's so little remaining usage it's not worth worrying about (real numbers coming).

uORB::DeviceNode replace SubscriptionData with uORB::SubscriptionInterval

---

msg/battery_status.msg
src/drivers/batt_smbus/batt_smbus.cpp
src/drivers/batt_smbus/batt_smbus.h
src/drivers/batt_smbus/parameters.c
src/lib/drivers/smbus/SMBus.cpp
src/lib/drivers/smbus/SMBus.hpp
src/modules/mavlink/mavlink_messages.cpp

The sbmus driver has many fixes and functional updates that can be done.
- fixes - many code clean ups and optimizations
- fixes/upgrade - how to behave when there is smbus interface errors
- upgrade - support BQ40Z80 device
- upgrade - publish mavlink SMART_BATTERY_INFO
This PR is WIP to start and update the driver. it just cleanups before the "real work". 
it can be merged, so the real work will be done on next step
I am working with BQ40Z80 only, and not BQ40Z50. (the code for the BQ40Z80 has not been pushed on first commits)
so if there someone that can test the code with BQ40Z50, to ensure nothing has break, that will be helpful
Pr batt smbus stability #14409 …

Battery Smbus enhancements 

---

boards/modalai/fc-v1/init/rc.board_sensors
src/drivers/power_monitor/voxlpm/voxlpm.cpp
src/drivers/power_monitor/voxlpm/voxlpm.hpp
src/drivers/power_monitor/voxlpm/voxlpm_main.cpp
src/drivers/power_monitor/voxlpm/voxlpm_params.c

This PR adds support or the voxlpm v3 (https://docs.modalai.com/power-module-v3-datasheet/)
This is very similar to the voxlpm v2 but instead uses INA231 sensors.
~~This PR also adds the deprecated BAT_* params that QGC complains about since we aren't using the battery_status module on this board.~~
Detect at runtime which voxlpm is attached by querying the I2C bus for known addresses to determine which is attached to flight controller and initialize accordingly.
Possible alternatives is to create individual drivers for LTC2947 (voxlpm v2) and INA231 (voxlpm v3) and initialize each.... Since the driver work to talk to the INA231 and LTC2947 is very minimal and the 'application' …

modalai_fc-v1 - power_monitor/voxlpm - add support for voxlpm v3 (INA231 sensors)

---

Jenkinsfile

I just verified we weren't building the correct target (any to be clear) and so the content we wanted to copy didn't exist.
Ex: http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2FFirmware/detail/master/2880/pipeline

Jenkins: deploy: build rtps target and then deploy agent

---

src/modules/commander/Commander.cpp
src/modules/commander/commander_params.c

Before it was possible for the sticks to be _not_ centered when entering an auto mode which didn't have RC override enabled (eg. fixed-wing mission). When a scheduled change to a different auto mode which _did_ have RC override enabled happened, it would then cause the RC override to be activated unexpectedly.
This was seen specifically during VTOL back-transition, where it was very dangerous because the manual VTOL switch would still be in fixed wing mode, and would cause the vehicle to transition back to fixed wing.
RC override is entered based on sticks not being centered, not based on sticks _moving_
Do some kind of messaging request for RC override instead, and check for …

Compare RC override from center, not last sticks

---

src/drivers/telemetry/frsky_telemetry/frsky_data.cpp
src/drivers/telemetry/frsky_telemetry/sPort_data.cpp
src/examples/px4_simple_app/px4_simple_app.c
src/examples/uuv_example_app/uuv_example_app.cpp
src/modules/commander/calibration_routines.cpp
src/modules/commander/gyro_calibration.cpp
src/modules/commander/rc_calibration.cpp
src/modules/logger/logged_topics.cpp
src/modules/mavlink/mavlink_messages.cpp
src/modules/muorb/adsp/px4muorb.cpp
src/modules/rover_pos_control/RoverPositionControl.cpp
src/modules/rover_pos_control/RoverPositionControl.hpp

In multi-EKF we have a `sensor_combined` (now `vehicle_imu`) for every EKF instance. Most remaining `sensor_combined` usage in the code base can be easily replaced by `vehicle_acceleration` or `sensor_selection` + `vehicle_imu`.
https://github.com/PX4/Firmware/pull/14650

start replacing sensor_combined usage (multi-EKF preparation)

---

Tools/sitl_run.sh

**Problem**
Since the seperation from the SITL Gazebo model and world files, there is no way to run a simulation on the jinja generated models. These models produce a file called `model-gen.sdf`, but currently it expects a file called `model.sdf`
**Solution**
The solution is to update the `sitl_run.sh` file to rather fetch the SDF filename from the `model.config` file, instead of assuming that the SDF filename is the same as the model's.
**Alternatives**
An alternative solution would be to just rename the generated SDF files to `model.sdf` and omit the `-gen` part. However, this means that these can't be ignored when pushing code and I don't think it is preferable to have generated code living in the codebase. Therefore, I think my current proposed solution is a better one.

Update sitl_run to fetch the SDF filename from the model.config file

---

src/drivers/differential_pressure/sdp3x/SDP3X.cpp

It is not playing nice with other devices on the same bus.
In particular with the FreeFly RTK GPS: once the reset is sent, the whole bus is blocked and becomes unusable (this does not happen with the Pixhawk 4 GPS for example though).

sdp3x: remove reset during init

---

src/lib/parameters/flashparams/flashparams.cpp
src/lib/parameters/param.h
src/lib/parameters/parameters.cpp
src/lib/parameters/parameters_shmem.cpp
src/systemcmds/param/param.cpp

PARAM_TYPE_STRUCT was never really used and potentially gets in the way of newer parameter system development.

parameters: delete unused PARAM_TYPE_STRUCT

---

src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_main.h

Add a new command line argument `-Z` to completely disable hardware flow control on UART interface, even if the low level driver supports that.
Test passed on my RPi with sc16is752 enabled by device tree overlay

Mavlink command: new option to completely disable hardware flow control

---

Tools/px4moduledoc/srcparser.py
src/drivers/optical_flow/thoneflow/CMakeLists.txt
src/drivers/optical_flow/thoneflow/module.yaml
src/drivers/optical_flow/thoneflow/thoneflow.cpp
src/drivers/optical_flow/thoneflow/thoneflow_parser.cpp
src/drivers/optical_flow/thoneflow/thoneflow_parser.h

Driver for the Thoneflow 3901U optical flow sensor connected over UART (https://www.seeedstudio.com/ThoneFlow_3901U_UART_Serial_Version_PMW3901_Optical_Flow_Sensor-p-4040.html).
Still needs flight testing and verification of the pixel to radians scaling factor.

Thoneflow 3901U Driver

---

src/lib/mixer/MultirotorMixer/MultirotorMixer.cpp
src/lib/mixer/MultirotorMixer/test_mixer_multirotor.cpp

Taking off with a powerful enough multirotor which has hover thrust < 50% leads to a vertical flyaway. E.g. SITL jmavsim 
By bisecting I found that #15563 introduced that and after inspection I found that only the idle thrust part has enough influence to make that happen. Apparently the output was scaled with [0,1] instead of [-1,1].
The variable `_idle_speed` which was removed in #15563 was always -1.f so I just followed where it was used before and replaced the previous use with the number.
We should probably reconsider suddenly changing the output scaling in the middle of the mixer. This is just a hotfix to restore previous functionality without `_idle_speed`.
**Test data / …

MultirotorMixer: hotfix [-1,1] scaling

---

src/modules/battery_status/analog_battery.cpp

Without this patch if value of BAT1_A_PER_V parameter is zero and board doesn't support current measurment, that is BOARD_BATTERY1_A_PER_V define is not used (0 by default), batterry_status module will always write this parameter to mtd on each boot and on any paramer update.
Description for BAT1_A_PER_V already says that a value of -1 means to use the board default, so no big deal here.
Besides efficiency it looks like it can be very dangerous to write anything to mtd on boot for systems with unstable and bouncing power on turning on (especially without bootloader). I've got parameters corruptions several times - cluster of mtd get erased but wasn't written due to bouncing power off.

batterry_status: fix checking default a_per_v

---

msg/templates/urtps/microRTPS_agent.cpp.em
msg/templates/urtps/microRTPS_timesync.cpp.em
msg/templates/urtps/microRTPS_timesync.h.em
msg/templates/urtps/microRTPS_transport.cpp
msg/tools/uorb_rtps_message_ids.yaml

In the process of leveraging the [agent_protocol_splitter](https://github.com/Auterion/agent_protocol_splitter), some problems were found on the transport code that resulted on unneeded dropouts of certain msgs. This PR:
1. Solves a small (big) bug on the parsing of the packets when a packet is found to have a CRC error;
2. Adds verbosity control to the timesync functionality;
3. Reduce the number of RTPS streams (a lot didn't make sense to expose on the mission computer).

microRTPS: small tweaks

---

src/drivers/distance_sensor/leddar_one/leddar_one_main.cpp
src/drivers/distance_sensor/ll40ls/ll40ls.cpp
src/drivers/distance_sensor/ll40ls_pwm/ll40ls.cpp
src/drivers/distance_sensor/sf0x/sf0x_main.cpp
src/drivers/distance_sensor/sf1xx/sf1xx.cpp
src/drivers/distance_sensor/srf02/srf02_main.cpp
src/drivers/distance_sensor/teraranger/teraranger_main.cpp
src/drivers/distance_sensor/tfmini/tfmini_main.cpp
src/drivers/distance_sensor/ulanding_radar/ulanding_radar_main.cpp
src/drivers/distance_sensor/vl53l0x/VL53L0X.cpp

This is the default for all the other range finders and the main purpose of this sensor is to measure the distance below the drone. I also changed the minimum value of the `-R` argument to `0` as there is no reason to ban the `no_rotation`.

ll40ls (LidarLite): set default orientation to "downward facing"

---

src/drivers/imu/bosch/bmi055/BMI055_Accelerometer.cpp

- single register output is in 2's complement
I might have caught this earlier if I didn't live in Florida (temp<7:0>=0x00 corresponds to a temperature of 23°C). 
@NicolasM0 can you give this a try?

bosch/bmi055: fix accel temperature reading

---

Tools/process_sensor_caldata.py

I opened a thread here to discuss about an issue and propose a fix: https://discuss.px4.io/t/issue-with-thermal-calibration-fitting/14582
If the temperature ramp is not constant during heat up, the fitting give more weight to temperature with lower change rate. If heating become very slow (typically at the high temperature), the calculated polynomial can not fit at all where the temperature change rate was high (typically at low temperature)
This commit add a re sample before fitting to have a more regular weight over temperature

process_sensor_caldata.py: regularly weighted over temperature thermal fitting

---

src/drivers/imu/bosch/bmi055/BMI055.hpp
src/drivers/imu/bosch/bmi055/BMI055_Accelerometer.cpp
src/drivers/imu/bosch/bmi055/BMI055_Accelerometer.hpp
src/drivers/imu/bosch/bmi055/BMI055_Gyroscope.cpp
src/drivers/imu/bosch/bmi055/BMI055_Gyroscope.hpp
src/drivers/imu/bosch/bmi088/BMI088.hpp
src/drivers/imu/bosch/bmi088/BMI088_Accelerometer.cpp
src/drivers/imu/bosch/bmi088/BMI088_Accelerometer.hpp
src/drivers/imu/bosch/bmi088/BMI088_Gyroscope.cpp
src/drivers/imu/bosch/bmi088/BMI088_Gyroscope.hpp

- track consecutive failures and trigger reset aggressively (if necessary)
- only count missed drdy interrupts, not time
- reset wait times consistent with other drivers (retry timeouts, etc)
- accel improve FIFO count check logic if DRDY isn't available

Bosch IMU minor cleanup and consistency improvements with other drivers

---

src/modules/commander/accelerometer_calibration.cpp

This adds a simple check in the accel calibration to fail if an axis of a sensor measuring +/- gravity has data that's the opposite magnitude expected. Catching this during calibration prevents a "successful" calibration creating negative scale factors.
@hyonlim this would have caught your bad accel rotation.

commander: accel calibration fail early on bad rotations

---

Tools/process_sensor_caldata.py

process_sensor_caldata.py: skip accel or gyro if temperature is NAN

---

ROMFS/px4fmu_common/init.d-posix/rcS
boards/bitcraze/crazyflie/syslink/syslink_main.cpp
boards/bitcraze/crazyflie/syslink/syslink_main.h
src/drivers/power_monitor/ina226/ina226.cpp
src/drivers/power_monitor/ina226/ina226.h
src/drivers/power_monitor/voxlpm/voxlpm.cpp
src/drivers/power_monitor/voxlpm/voxlpm.hpp
src/lib/battery/battery.cpp
src/lib/battery/battery.h
src/lib/battery/battery_params_deprecated.c
src/modules/battery_status/analog_battery.cpp
src/modules/battery_status/analog_battery.h
src/modules/commander/commander_params.c
src/modules/simulator/battery_simulator/BatterySimulator.cpp
src/modules/simulator/battery_simulator/BatterySimulator.hpp

@cmic0 tried to change `BAT1_V_EMPTY`. Parameter was changed, it differed from `BAT_V_EMPTY` and after a reboot (starting simulation again) it was back to the old value.
Battery parameter migration from `BAT_*` to `BAT1_*` had the following issues:
1. In simulation the `SimulatorBattery` broke the chain of ModuleParams parent/child tree which the logic is relying on. Additionally it overwrote the parameters with hardcoded values internally.
1. The parameter migration prefers to migrate old over new if the values differ on boot but the flag `_first_parameter_update` was initialized false and hence always false. This didn't have an effect most of the time because the `previous_old_val` is zero on initialization and if the new parameter isn't …

Fix Battery Parameter Migration

---

src/modules/rover_pos_control/RoverPositionControl.cpp
src/modules/rover_pos_control/RoverPositionControl.hpp

Quick test to see if this fixes https://github.com/PX4/Firmware/issues/15628 (in CI at least).
Note `sensor_combined` isn't even used in this module, it's just for scheduling in certain circumstances.

rover_pos_control: revert sensor_combined purge

---

Jenkinsfile

1. Updates the tags to 2020-08-20 and use Ubuntu Focal (specifically targeting the micro-RTPS agent deploy)
2. Re-add the ROS-related builds

Jenkins: metadata deploy container update

---

Jenkinsfile

Fixes the problem reported in http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2FFirmware/detail/master/2936/pipeline/221.

Jenkins: replace 'python' with '.' to run the uORB to ROS conversion Python scritpt

---

Jenkinsfile

The deployment was being done wrong since we were not updating the src and IDL definitions properly (case where one msg is set to not be used, then we should not have source code for that message being deployed to the repo).
Also spitted the subject per commit, for convenience.

microRTPS agent deploy: split commit subjects and delete src and idl folders before updating them

---

platforms/common/include/px4_platform_common/px4_work_queue/ScheduledWorkItem.hpp
platforms/common/include/px4_platform_common/px4_work_queue/WorkItem.hpp
platforms/common/px4_work_queue/ScheduledWorkItem.cpp
platforms/common/px4_work_queue/WorkItem.cpp

This is a cheap and easy way to get relatively fresh `work_queue status` output.

px4_work_queue: reset statistics after each status print

---

src/modules/uORB/SubscriptionMultiArray.hpp

- uORB::SubscriptionInterval construction requires the interval THEN the instance

uORB:: SubscriptionMultiArray fix construction argument

---

Tools/px4moduledoc/srcparser.py
boards/cubepilot/cubeorange/init/rc.board_sensors
boards/cubepilot/cubeyellow/init/rc.board_sensors
boards/holybro/pix32v5/init/rc.board_sensors
boards/px4/fmu-v5/init/rc.board_sensors
platforms/common/i2c.cpp
platforms/common/i2c_spi_buses.cpp
platforms/common/module.cpp

As boards don't have their external buses labeled consistently, it was not useful to use an abstraction.

i2c: use board-specific bus numbering for '-X -b <bus>' CLI

---

src/modules/ekf2/ekf2_main.cpp
src/modules/sensors/vehicle_acceleration/VehicleAcceleration.cpp
src/modules/sensors/vehicle_acceleration/VehicleAcceleration.hpp
src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.hpp
src/modules/uORB/Subscription.cpp
src/modules/uORB/Subscription.hpp
src/modules/uORB/SubscriptionCallback.hpp

In a few areas of the code base it's necessary to switch between different instances of a uORB topic. For example `sensors/vehicle_angular_velocity` subscribes to the current primary gyro, but might change if the primary selection changes. Currently this is done by maintaining an array of uORB::Subscriptions.
This PR adds a new mechanism to uORB::Subscription that allows you to change the instance of an existing subscription. It's a small piece broken out of https://github.com/PX4/Firmware/pull/14650.

uORB: add Subscription method to change instance

---

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp

The time constant parameters for TECS get mixed up in FixedWingPositionController, which is fixed here.
Mixup was introduced with commit 3dc23afb3e1, exchanging values 5.0 and 8.0:
```
PARAM_DEFINE_FLOAT(FW_T_TIME_CONST, 5.0f);
...
PARAM_DEFINE_FLOAT(FW_T_THRO_CONST, 8.0f);
```
Seems not to have a big impact, therefore we can probably simply swap them back.

swap time parameters in FixedWingPositionControl

---

src/modules/temperature_compensation/TemperatureCompensationModule.cpp
src/modules/temperature_compensation/temperature_calibration/accel.cpp
src/modules/temperature_compensation/temperature_calibration/baro.cpp
src/modules/temperature_compensation/temperature_calibration/common.h
src/modules/temperature_compensation/temperature_calibration/gyro.cpp

If a sensor does not have temperature measurement, the onboard thermal calibration of other sensors will never finish.
This PR also change the message displayed as an error by thermal compensation module if a sensor does not have a thermal compensation. It is now the normal use case for some autopilots (eg: CUAV V5+).
Sensors with no temperature measure are skipped.
The compensation not found error is now displayed as an info.
Tested on V5+ with no temperature data on gyro 2
related to :
https://github.com/PX4/Firmware/pull/15644
https://github.com/PX4/Firmware/issues/15582

fix thermal calibration if a sensor does not have temperature sensor

---

platforms/nuttx/src/px4/common/cpuload.cpp

For some reason the NuttX scheduling note linkage is broken with the updated arm-none-eabi toolchain (on MacOS at least).
``` Console
/usr/local/Cellar/gcc-arm-none-eabi/20200630/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: NuttX/nuttx/sched/libsched.a(nx_start.o): in function `nx_start':
/Users/dagar/git/Firmware/build/px4_fmu-v5_default/NuttX/nuttx/sched/init/nx_start.c:756: undefined reference to `sched_note_start'
/usr/local/Cellar/gcc-arm-none-eabi/20200630/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: NuttX/nuttx/sched/libsched.a(task_activate.o): in function `task_activate':
/Users/dagar/git/Firmware/build/px4_fmu-v5_default/NuttX/nuttx/sched/task/task_activate.c:82: undefined reference to `sched_note_stop' …
```

NuttX sched notes add C linkage to fix arm-none-eabi-gcc 9

---

src/modules/commander/Commander.cpp

- auto disarm when locked down was added in #14766 to prevent user
confusion in regular usage, but also breaks HITL where lockdown is
enabled for safety
- fixes #15686
I'd actually like to purge most of these HITL special cases in commander, but not today.

commander: HITL skip auto disarm if lockdown

---

msg/vehicle_command.msg
src/modules/commander/Commander.cpp
src/modules/commander/mag_calibration.cpp
src/modules/commander/mag_calibration.h

Use proper Mavlink command `MAV_CMD_FIXED_MAG_CAL_YAW` for magnetometer quick calibration that allows specifying the yaw and optionally latitude and longitude if the vehicle doesn't have GPS (indoors, etc). This quickly sets the magnetometer offsets from the world magnetic model. Only recommend for testing or vehicles where it's not viable to do the regular mag cal dance.
https://github.com/mavlink/mavlink/pull/1471

commander: quick mag cal with fixed heading use mavlink message

---

.ci/Jenkinsfile-SITL_tests

The MC safe landing SITL test continues to fail intermittently so I'm disabling it for now.
- http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-15687/3/pipeline
- http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/master/2925/pipeline
FYI @Jaeyoung-Lim @mrivi 
I can dig up more examples if it would help.

Jenkins: temporarily disable MC safe landing SITL test

---

src/modules/ekf2/EKF2.cpp
src/modules/ekf2/EKF2.hpp

Found that while checking https://github.com/PX4/Firmware/pull/15657

ekf2: move "using" keywords to cpp

---

src/lib/flight_tasks/tasks/Auto/FlightTaskAuto.cpp

The waypoints are updated whenever state changes or when triplets update. But, when the drone is offtrack, the target should be the closest point on the path prev-next, which changes every iteration due to the drone moving while offtrack.
In this case we have to update whenever closest point changes.
This had a significant effect in my case when the obstacle avoidance / collision prevention is active. Although we use our custom avoidance / prevention algorithms, I think the same holds for the px4 master case.
When collision prevention is actively changing the setpoints, the drone can get offtrack, and the target is saved at that moment when the state switches to offtrack. When the prevention stops interfering, the drone is at a different position and instead of going to the current …

FlightTaskAuto: update waypoints on every iteration when in offtrack state

---

src/modules/commander/Arming/PreFlightCheck/checks/failureDetectorCheck.cpp
src/modules/commander/Commander.cpp
src/modules/commander/failure_detector/FailureDetector.cpp
src/modules/commander/failure_detector/FailureDetector.hpp

I found:
1. Commander contained two very similar conditions to process failure detector output
1.  Failure detector used different naming conventions
1. Failure detector contained extensive logic to keep track of the state getting updated or not. This can be done by just comparing the one-byte state before and after.
1.  Failure detector reactions to attitude tracking checks are not independent of reactions to ESC checks
No tests done.

Failure detector improvements

---

.ci/Jenkinsfile-hardware
ROMFS/cannode/init.d/rcS
ROMFS/px4fmu_common/init.d-posix/rcS
ROMFS/px4fmu_common/init.d/airframes/4250_teal
ROMFS/px4fmu_common/init.d/rcS
src/lib/parameters/param.h
src/lib/parameters/parameters.cpp
src/systemcmds/param/param.cpp

There is currently no way to reset just one parameter to the default from shell/startup script.
This problem is bugging me for a long time:
You have an airframe that defines a ton of parameters some are defaults (for whatever reason), some not. Some need to be non-default because they are custom e.g. to enable a new non-default feature. Once the PX4 default is improved the airframe that ever had it custom needs to hardcode the default values and follow any upstream change to that part of the configuration from there on because otherwise existing vehicles don't get updated and are in an undefined state. Were they ever completely reset? Do they still have the old custom parameter?
After seeing `param show BAT_V_EMPTY` and `param set …

Enable reseting specific parameters to default from shell

---

src/modules/commander/Arming/ArmAuthorization/ArmAuthorization.cpp

Problem:
Two mavlink log messages for arm authorization have the wrong criticality:
"Arm auth: Requesting authorization..."
"Arm auth: Authorized for the next %u seconds"
Solution:
Change the criticality of these two messages from "critical" to "info"

change mavlink log messages criticality for arm authorization

---

Tools/sitl_run.sh

Currently when running SITL simulations, SITL fails silently when there is something wrong with the gazebo model.
The only way to find out what was wrong about the model was to go into [sitl_run.sh](https://github.com/PX4/Firmware/blob/2128679ab3e4ba888cc3f8b1cb9b00a398847cc5/Tools/sitl_run.sh#L100) and enable the `--verbose` flag after gzserver and look at the errors. 
This allows to add a `VERBOSE=1` in the command line to enable the verbose option on gazebo. I believe this would be useful for other simulators as well, but currently just used for gazebo.
To test, you can run
```
VERBOSE=1 make px4_sitl gazebo
```
For comparison:
**Without PR**
```
$ make px4_sitl gazebo
[0/1] Re-running …
```

Allow gzserver verbose options through command line

---

src/modules/mavlink/mavlink_messages.cpp

Continuation/rebase of #14338.
If I connect two Garmin LidarLite sensors to my vehicle, which is supported now with v1.11.0, then I only get data from one of them sent over mavlink. I want both, so I can ask QGroundControl to display the distance data for both (in my case upwards and downwards).
Modify the distance sensor mavlink streamer class to stream from all uorb instances.
None considered.
Tested by running a Pixhawk 4 with two LidarLites before and after this change. Can see that it works, so I get data from both sensors in QGroundControl.
Before and after:
---
I haven't considered the streaming rate issue discussed previously in #14338 (yet). With …

mavlink_messages: Subscribe to all distance_sensor instances

---

src/modules/uuv_att_control/uuv_att_control.cpp
src/modules/uuv_att_control/uuv_att_control.hpp

The uuv_att_control module did not spawn its task correctly. The problem was mentioned in [Slack](https://px4.slack.com/archives/C0V533X4N/p1599672383139200?thread_ts=1599672135.137400&cid=C0V533X4N). This request should fix it (also `perf_begin` and `perf_end` were placed oddly and are repositioned)

fixed erroneous task_spawn

---

platforms/common/include/px4_platform_common/module.h
src/drivers/gps/gps.cpp

- use px4::atomic instead of volatile
- fix memory leak on module exit (delete _helper)
-  increase max timeout for stopping modules from 2s to 5s. The gps module might take up to 4s to stop (if stopped during module configuration). I've seen hardfaults when stopped in the wrong moment.

some gps driver cleanup

---

src/drivers/uavcan/uavcan_drivers/stm32h7/driver/include/uavcan_stm32h7/can.hpp

STM32H7 CAN: fix uninitialized pending variable

STM32H7 CAN: fix uninitialized pending variable

---

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
src/modules/mavlink/mavlink_receiver.cpp
src/modules/navigator/mission.cpp
src/modules/navigator/navigator.h
src/modules/navigator/navigator_main.cpp

There is currently no way in px4 to enable the vehicle to "glide" along the setpoint. 
This PR enables a soaring behavior while following a position setpoint in offboard mode. A soaring setpoint is sent through a setpoint_type mask, which configures TECS to prioritize kinetic energy and thus enabling the vehicle to soar along it's glide slope, while loitering around its setpoint.
This is needed for autonomous soaring applications, where the fixed wing vehicle needs to soar around a setpoint without activating any throttle.
A test code can be found in https://github.com/Jaeyoung-Lim/mav_soaring, which is a ROS based implementation(WIP) of [Ardusoar](https://arxiv.org/abs/1802.08215)
Video: …

 Support gliding setpoints for autonomous soaring

---

src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_messages.cpp

This PR takes the `esc_status` uORB topic and relays this data through a newly created mavlink stream and message ( see https://github.com/mavlink/mavlink/pull/1322 ).
I used my own judgement and knowledge on what fields to pass and I also had to change the structure of the message slightly. As such any reviews and/or suggestions there are more than welcome.
Regarding starting the actual stream I implement the actual solution that I was given when I posted this issue on slack but I'm almost certain there is a better way to do this.
Looking forward to your comments and reviews.
Many thanks.

Publish ESC_INFO and ESC_STATUS MAVLink messages

---

src/modules/px4iofirmware/px4io.h

Fix was already done with https://github.com/PX4/Firmware/pull/15397 but broken with https://github.com/PX4/Firmware/pull/15415.

CubeOrange and CubeYellow IMU heating fix

---

src/modules/sensors/sensor_params.c
src/modules/sensors/sensor_params_mag.c
src/modules/sensors/sensors.cpp
src/modules/sensors/vehicle_imu/VehicleIMU.cpp
src/modules/sensors/vehicle_imu/VehicleIMU.hpp
src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.hpp
src/modules/sensors/voted_sensors_update.cpp
src/modules/sensors/voted_sensors_update.h

This PR introduces parameters for configuring the behavior of the `sensors` hub module to optionally skip voting/selection and publish all instances. By themselves they aren't that useful, but it enables the multi-EKF use case where the sensor voting/selection moves from the `sensors` to the ekf selector and we need access to all instances of sensor data (calibrated in vehicle body frame).
Yet another small piece broken out of https://github.com/PX4/Firmware/pull/14650.

sensors: add SENS_IMU_MODE and SENS_MAG_MODE to optionally skip voting/selection

---

src/modules/land_detector/MulticopterLandDetector.cpp
src/modules/land_detector/MulticopterLandDetector.h

The hover thrust estimate will typically invalidate upon ground contact, but before the land detector ground_contact triggers. This change gives land detector ground contact a small window (1 s) to continue using the relaxed low throttle threshold.

land_detector: continue to use hover thrust if it was valid recently

---

.devcontainer/devcontainer.json
.vscode/c_cpp_properties.json
.vscode/extensions.json
.vscode/settings.json
.vscode/tasks.json
Tools/sitl_run.sh
platforms/nuttx/Debug/launch.json.in
platforms/posix/Debug/launch_sim.json.in
platforms/posix/cmake/sitl_target.cmake
platforms/posix/cmake/sitl_tests.cmake

- fix gazebo SITL debug
- now prompts you to select vehicle
- devcontainer.json container support https://code.visualstudio.com/docs/remote/containers
- this allows you to jump straight into working within a container (px4-dev-nuttx) on a fresh machine
- also helps with Codespaces https://github.com/features/codespaces
- plugin updates
- cpp extension pack, spell checking, CTest support
- cleanup intellisense
- the backup tag parser was a resource hog and didn't work very well
- fix problemMatcher support so that you can click on a build failure

vscode updates and improvements

---

ROMFS/CMakeLists.txt

- moves process airframe deps to the tar generation, to ensure whenever
airframes are processed, the tar is extracted first.
This is required, because if the airframe processing is done on pruned
ROMFS, it's missing the tags.
- avoid using init.d/rcS in dependencies, use a separate file instead.
This is because pruning modifies the rcS, and the next rebuild was
seeing a changed rcS, resulting in unnecessary regeneration.

ROMFS: change cmake dependencies

---

.ci/Jenkinsfile-compile
.github/workflows/compile_nuttx.yml
boards/nxp/fmuk66-v3/rtps.cmake

To support MicroRTPS you need a separate build target that has RTPS enabled, this PR adds a RTPS target for the FMUK66
-
-
MicroRTPS has been tested with FMUK66 <-> NavQ runing Ubuntu 20.04 with ROS2 Foxy.

Added RTPS target for FMUK66-V3

---

src/lib/sensor_calibration/Accelerometer.cpp
src/lib/sensor_calibration/Gyroscope.cpp
src/lib/sensor_calibration/Magnetometer.cpp

Silence this unnecessary error when initially setting per sensor priorities (now parameters).

sensor_calibration: silence error if priority is -1 (uninitialized parameter value)

---

.gitmodules

This mainly helps tooling update to the tip of the tracking branch.
I've also updated the default branches in https://github.com/PX4/NuttX and https://github.com/PX4/NuttX-apps and enabled appropriate branch protection to ensure any commit we reference in PX4/Firmware never disappears.

gitmodules update NuttX branches

---

platforms/nuttx/NuttX/CMakeLists.txt

- this relative path was incorrect for the px4io build with Makefile generator
FYI @davids5

cmake NuttX build fix path to git dir

---

src/modules/commander/mag_calibration.cpp

@SalimTerryLi would you like to give this a try? If you have valid GPS (even a mediocre 2D fix) mag calibration will use the current mag field as the sphere radius to reject samples that are too close together when rotating. If GPS isn't available it defaults to the minimum value (0.2 Gauss) which lets you slip through calibration without doing full rotations.

commander: mag calibration use WMM sphere radius to reject samples if GPS is available

---

src/include/containers/List.hpp

So that clang 12 does not complain:
loop variable 'child' is always a copy because the range of type 'List<ModuleParams *>' does not return a reference
I'm not entirely sure if the warning refers to the `operator*` or Iterator returned by `begin()`.
Fix for #15756.

List.hpp: let operator* return a reference

---

src/modules/ekf2/EKF2.cpp

120 seconds of learning time in 3D fusion mode was too long for most normal flights. The learned bias is usually really good after a shorter period and was not used to update the parameters. 30s seems to be a good compromise.

ekf2_main: reduce update mag bias minimum learning time to 30s

---

platforms/nuttx/NuttX/CMakeLists.txt
platforms/nuttx/cmake/init.cmake

@davids5 one of the problems was that the `.git` file could have been a hard link back to the actual source tree.

cmake NuttX build modify copied nuttx repo .git to point to actual git dir

---

src/lib/conversion/RotationTest.cpp
src/lib/conversion/rotation.cpp
src/lib/conversion/rotation.h
src/modules/commander/mag_calibration.cpp
src/modules/mavlink/CMakeLists.txt
src/modules/mavlink/mavlink_messages.cpp
src/modules/sensors/sensor_params.c
src/modules/sensors/sensor_params_mag0.c
src/modules/sensors/sensor_params_mag1.c
src/modules/sensors/sensor_params_mag2.c
src/modules/sensors/sensor_params_mag3.c

- fixes https://github.com/PX4/Firmware/issues/15771
We had slightly different options across rotation enum, SENS_BOARD_ROT, CAL_MAGx_ROT, and MAV_SENSOR_ORIENTATION. This has been an ongoing problem at different points and it's extremely frustrating for the occasional user that hits this. I think the only sane thing to do is bring them altogether and keep it that way.
In this PR I've deleted a few rotations. If we want them they have to go in mavlink first and we'll bring them back.
- ROTATION_PITCH_9_YAW_180: added for Bebop, which we no longer support https://github.com/PX4/Firmware/pull/5598
- ROTATION_PITCH_45: https://github.com/PX4/Firmware/pull/8593
- needs to be added to mavlink if actually used
- we already shifted the number earlier this year …

rotations: sync rotation enum, SENS_BOARD_ROT, CAL_MAGx_ROT with MAV_SENSOR_ORIENTATION

---

src/modules/mavlink/mavlink_messages.cpp

Compiling `make sitl_px4` with GCC 10.1 I get the following errors
```
../../src/modules/mavlink/mavlink_messages.cpp:127:40: error: comparison between types ‘MAV_SENSOR_ORIENTATION’ and ‘Rotation’ [-Werror=sign-compare]
127 | static_assert(MAV_SENSOR_ROTATION_NONE == ROTATION_NONE, "Roll: 0, Pitch: 0, Yaw: 0");
```
for all the static asserts added in https://github.com/PX4/Firmware/pull/15784/files#diff-e605251d3710c0f7f0c065b242004e9cR127
I statically cast the internal values which have the internal `Rotation` type defined in https://github.com/PX4/Firmware/blob/d5295ef4e10accd8b5cba07c9afd03367af540d2/src/lib/conversion/rotation.h#L51 to the MAVLink defined `MAV_SENSOR_ORIENTATION` type defined in …

mavlink_messages: cast rotation types for assert

---

src/modules/uORB/Subscription.hpp

The only part of the code base that uses this is logger when the LoggerSubscription is copied into the allocated subscription array.

uORB: Subscription add copy/move constructor and assignment

---

src/modules/commander/Commander.cpp
src/modules/commander/Commander.hpp
src/modules/commander/commander_params.c

RC override is broken on master since https://github.com/PX4/Firmware/pull/15495
- Fix RC override threshold scaling
- Improve parameter description for threshold
- Lower the threshold a bit according to my testing
SITL tested with Joystick input.

Commander: fix rc override threshold scaling

---

src/modules/mc_pos_control/mc_pos_control_params.c

This reverts commit 59bd3e9f6e72db5d1751fc11fe6dccaf1c69b05e from https://github.com/PX4/Firmware/pull/14560. I checked and this change was only introduced because the vertical velocity in position mode got constrained (too much) when getting closer to the ground when testing the relatively samll pixhawk vision. Since then the horizontal slow down was more or less disabled by only limiting to 10 m/s in https://github.com/PX4/Firmware/pull/15029. Also the defaults should represent safe values for a wide variety of suppoerted vehicles and can be adjusted if not "itght" enough for certain use cases.
Since that change we had multiple incidents where also larger drones slowed down too late and hit the ground quite hard and I consider it a safety …

Revert MPC_LAND_ALT1/2 to original defaults to prevent slowing down too late

---

.ci/Jenkinsfile-SITL_tests
platforms/posix/cmake/sitl_target.cmake

- allow ninja build to automatically determine parallelism
This was needed for build slaves with limited memory, let's see if it's still needed.
@bperseghetti

cmake: remove sitl_gazebo build -j2

---

Tools/sitl_run.sh

`VERBOSE=1` was added in https://github.com/PX4/Firmware/pull/15720 to enable verbose outputs from the simulation. However, the term `VERBOSE` is not exactly accurate since it configures the verbose output of the gazebo simulation and nothing else. 
This changes the environment variable `VERBOSE` to `VERBOSE_SIM`, to explicitly state that it configures the verbose output of the simulation

Switch VERBOSE to VERBOSE_SIM

---

src/modules/commander/Commander.cpp
src/modules/commander/Commander.hpp

- possible fix for https://github.com/PX4/Firmware/issues/15810
- the land detector only publishes at ~ 1 Hz, so this timeout was too tight
- the land detector was only updated after the safety button was checked
In the log from https://github.com/PX4/Firmware/issues/15810 you can see that safety was fully off much earlier in the flight, but the disarm in air didn't happen until much later.

commander: disarm from safety relax land detector timeout

---

Tools/ecl_ekf/plotting/pdf_report.py

This fixes the rather annoying `Tools/ecl_ekf/process_logdata_ekf.py` failure when estimator_innovations and estimator_innovation_variances aren't exactly the same size. Quite often they're off by 1.
Suggestions welcome, I suspect this code is embarrassingly unpythonic.
FYI @priseborough @kamilritz

Tools ecl analysis handle estimator_innovations/estimator_innovation_variances size inconsistencies

---

msg/CMakeLists.txt
msg/generator_status.msg
msg/tools/uorb_rtps_message_ids.yaml
src/modules/logger/logged_topics.cpp
src/modules/mavlink/mavlink_receiver.cpp
src/modules/mavlink/mavlink_receiver.h

- only published (ORB_ID(generator_status)) and logged for now
- later this will evolve into something tightly integrated with commander and failsafes

mavlink: handle receiving GENERATOR_STATUS

---

src/modules/mavlink/mavlink_main.cpp

Seems related to the NuttX upgrade.

mavlink: increase stack 2650 -> 2848 bytes

---

src/lib/drivers/smbus/SMBus.cpp

Added buffer length check to SMBus::block_read (triggered hardfault in batt_smbus module by writing beyond buffer end due to device returning longer byte_count than requested/expected)
I ran into a hardfault when reading Smart Battery data with SMBus::block_read.
The fault is triggered in line 126 of
/Firmware/src/lib/drivers/smbus/SMBus.cpp
when memcpy writes beyond the end of the buffer “data” provided by the caller.
In my case the smbus device returned a byte count larger than the requested length (13 instead of 8 bytes).
I fixed this by adding a check for the length limit before the memcpy call, see
I experienced hardfaults working on a SMBUS battery driver based on batt_smbus. They werde triggered by the device returning a bigger byte_count value than was requested (13 bytes in …

Fix proposal for hardfault with batt_smbus module

---

src/systemcmds/motor_test/motor_test.cpp

Motors in Px4 ecosystem are indexed using 1-based indexing (Airframe reference, dshot command, etc.) motor_test command is 0-based. This PR changes motor_test to use 1-based indexing.
This PR refers to Github issue #15721.
motor_test command updated to use 1-based indexing.
Leave status quo with 0-based indexing.
N/A
N/A

motor_test: Use 1-based motor indexing.

---

src/lib/sensor_calibration/CMakeLists.txt

We don't notice most of these because the common dependencies are pulled in by multiple other modules.

sensor_calibration: explicitly add link dependencies

---

src/modules/simulator/simulator.h
src/modules/simulator/simulator_mavlink.cpp

- HIL_SENSOR temperature is only being set with barometer data

simulator: fix airspeed temperature

---

Tools/sitl_run.sh

This fixes a bug in the SITL startup scripts, where the world file path was being corrupted when using non-default world paths
- This was a bug introduced from https://github.com/PX4/Firmware/pull/15720
- Fixes https://github.com/PX4/sitl_gazebo/issues/603

Fix the world path being corrupting when spawning none-default world

---

ROMFS/px4fmu_common/init.d/airframes/50000_generic_ground_vehicle

This allows px4_fmu-v2_rover to function until we have a better mechanism for including or excluding ROMFS dependencies.
https://github.com/PX4/Firmware/issues/15711

ROMFS: 50000_generic_ground_vehicle remove fmu-v2 exclude

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

It seems that z velocity derivative part off multi-copter position controller has a sign error.
Change sign
On master with SIH, try to set MPC_Z_VEL_D_ACC to 2 : vertical oscillations begin. Then try to set it to -2 or even -4 : the drone stabilizes. 
As MPC_Z_VEL_D_ACC default value is 0, it has no impact.
@MaEtUgR: this regression seems linked to this commit: 38093e4

mc_pos_control: fix z velocity derivative sign

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

1:1 port of https://github.com/PX4/Firmware/pull/15836
I checked and the issue is not present on 1.10 but on 1.11. So this is the backport.

[Port 1.11] mc_pos_control: fix z velocity derivative sign

---

src/lib/airspeed/airspeed.cpp
src/modules/sensors/sensors.cpp

- if valid temperature unavailable then use ICAO Standard Atmosphere 15 degrees celcius
This prevents bogus temperature from ruining the true airspeed, which will cause havoc if it gets into the FW position controller.
Example before the simulator module was fixed. https://github.com/PX4/Firmware/pull/15843
https://logs.px4.io/plot_app?log=329cf317-8cae-4932-900d-28f221a8de18

sensors: sanity check differential pressure temperature

---

Tools/gazebo_sitl_multiple_run.sh

Multivehicle simulations in gazebo was run using xacro macros to generate sdf files in the `/tmp` directory with the necessary port assignments to enable it.
However, there are several problem with this infrastructure
- xacros do not support some of the syntaxes that were added in recent sdf versions (e.g. nested models)
- PX4 uses [xacro.py](https://github.com/PX4/sitl_gazebo/blob/master/scripts/xacro.py), which is deprecated
- xacro based macros were not on the same path with the models that they represent, therefore got outdated whenever the models were updated. (see below for the current state of `standard_vtol`)
jina2 templates are now used to generate sdf files at build time. This PR moves the multivehicle …

Use jinja templates for multivehicle simulations

---

.ci/Jenkinsfile-hardware
src/systemcmds/bl_update/bl_update.c

Resolves https://github.com/PX4/Firmware/issues/15786
Track Changes in NuttX stm32h7 flash driver:
The STM32H7 flash driver uses up_progmem_pagesize to
describe minimum write size to satify the block size
requierment for ECC.
Therefore, the image size needs to be padded to a multiple
of up_progmem_pagesize()

bl_update:Respect page size if it matters

---

src/modules/commander/Commander.cpp

Sometimes, the mission_result timestamp is the same as the
internal_state timestamp which would meant that we would not switch to
LOITER even though the takeoff is clearly done at that point.
#15808 but for master.

commander: fix switch to loiter

---

src/modules/commander/Arming/PreFlightCheck/checks/accelerometerCheck.cpp
src/modules/commander/Arming/PreFlightCheck/checks/baroCheck.cpp
src/modules/commander/Arming/PreFlightCheck/checks/gyroCheck.cpp
src/modules/commander/Arming/PreFlightCheck/checks/magnetometerCheck.cpp
src/modules/commander/Arming/PreFlightCheck/checks/manualControlCheck.cpp
src/modules/commander/Arming/PreFlightCheck/checks/powerCheck.cpp
src/modules/commander/mag_calibration.cpp

Two small commander preflight changes here.
1. For sensor checks don't impose additional timeouts (eg checking if the timestamp is < 1 second old)
- the sensors hub is responsible for reporting timeouts and errors, this part of commander preflight can remain focused on simply checking calibrations and minor number of sensors available
2. Subsystem health (ACC, ACC2, GYRO, GYRO2) is now set within the IMU consistency check based on the overall health for each sensor from the sensors module and shouldn't be set in the simple accel and gyro checks.

commander: preflight remove unnecessary additional timeouts and duplicate subsystem health updates

---

src/drivers/uavcan/CMakeLists.txt

I observed hard faults when running `uavcan params list`. A stackcheck build showed that the `uavcan` task overflowed its stack.
I increased the stack size for the `uavcan` command
None
Increasing stack size shouldn't cause any issues, but for what it's worth I have flown with this commit
https://review.px4.io/plot_app?log=d0f658d7-60ab-40ae-b4e2-a32aae84d942

Increase uavcan main stack size

---

boards/holybro/kakutef7/src/timer_config.cpp

Regression from d2254c2e4490f, I overlooked that they were defined in reverse order.
fixes https://github.com/PX4/Firmware/issues/15826

kakutef7: fix output ordering

---

posix-configs/rpi/px4.config
posix-configs/rpi/px4_fw.config
posix-configs/rpi/px4_test.config

Correctly configure telemetry over the UART interface in addition to the existing configuration over /dev/ttyUSB0.
[/dev/ttyAMA0](https://docs.emlid.com/navio2/ardupilot/hardware-setup/#uart-radio) is the primary interface for telemetry radio as defined in the Navio2 [hardware setup page](https://docs.emlid.com/navio2/ardupilot/hardware-setup/) documentation. The proposed changeset adds functionality over UART: it checks first if /dev/ttyUSB0 exists, which translates to possibly telemetry radio being attached through one of the USB ports on RPi ([usb-radio](https://docs.emlid.com/navio2/ardupilot/hardware-setup/#usb-radio)); if not, the code falls back to configuring over UART (/dev/ttyAMA0).
Use stricter check …

px4_raspberrypi: fix mavlink over UART (/dev/ttyAMA0)

---

src/modules/commander/Arming/PreFlightCheck/checks/ekf2Check.cpp
src/modules/commander/Arming/PreFlightCheck/checks/imuConsistencyCheck.cpp
src/modules/commander/Arming/PreFlightCheck/checks/powerCheck.cpp

- this ensures the relevant parameters are marked active immediately
before parameter sync
- fixes https://github.com/PX4/Firmware/issues/15872
@ryanjAA can you give this a try? If it resolves https://github.com/PX4/Firmware/issues/15872 I can backport it for v1.11.1.

commander: PreFlightCheck param_find all parameters immediately

---

src/lib/battery/battery.cpp
src/lib/battery/battery.h
src/modules/battery_status/battery_status.cpp

While debugging I noticed `battery_status` was publishing at 200 Hz.

lib/battery: fix duplicate uORB publish and minor cleanup

---

msg/vehicle_imu_status.msg
src/modules/sensors/vehicle_imu/VehicleIMU.cpp
src/modules/sensors/vehicle_imu/VehicleIMU.hpp

- this PR adds the average accel and gyro readings to the `vehicle_imu_status` message, reset on every publication (10 Hz)
- this makes it slightly easier to gather long term data for an Allan variance
related: https://github.com/PX4/Firmware/issues/6250

sensors/vehicle_imu: vehicle_imu_status add mean accel and gyro

---

msg/airspeed_validated.msg
src/lib/airspeed/airspeed.cpp
src/lib/airspeed/airspeed.h
src/lib/airspeed_validator/AirspeedValidator.cpp
src/lib/airspeed_validator/AirspeedValidator.hpp
src/modules/airspeed_selector/airspeed_selector_main.cpp
src/modules/fw_att_control/FixedwingAttitudeControl.cpp
src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
src/modules/logger/logged_topics.cpp
src/modules/mavlink/mavlink_messages.cpp
src/modules/sensors/sensors.cpp
src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/tailsitter.cpp
src/modules/vtol_att_control/tiltrotor.cpp

With the introduction of the airspeed selector, we added an airspeed corrected for position and instrumental error, to be used instead of indicated airspeed in most of the px4 control modules (like attitude and position controller). We called it `equivalent_airspeed` (EAS), as this was the airspeed type that was already expected by TECS (See [equivalent airspeed](https://en.wikipedia.org/wiki/Equivalent_airspeed))
The correct name of the airspeed we now call EAS would be CAS (calibrated airspeed), as we don't do any correction for compressibility effects, assuming we're always operating in regions where EAS=CAS. Also, CAS is more common than EAS, and the concept of having an equivalent airspeed was creating some confusion I've realized …

Airspeed_validated: rename airspeed_equivalent to airspeed_calibrated

---

ROMFS/px4fmu_common/init.d/CMakeLists.txt

`rc.boat_defaults` were not being added to the ROMFS in https://github.com/PX4/Firmware/pull/15714
This adds the missing `rc.boat_defautls` to ROMFS
Tested with
```
make px4_sitl gazebo_boat
```
Fixes https://github.com/PX4/Firmware/issues/15922

Add rc.boat_defaults to ROMFS

---

ROMFS/px4fmu_common/init.d-posix/airframes/1035_techpod
ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt
platforms/posix/cmake/sitl_target.cmake

**Problem Description**
This PR adds the techpod fixedwing model to this repo. Techpod is a model that is widely used in the research community, that have accurately modeled parameters. 
This will be useful for testing vehicles with higher lift drag ratios compared to the already available cessna
**Test/Verification**
- This model is originally distributed under https://github.com/ethz-asl/rotors_simulator which has been adapted to use the sdf format.
- This PR requires https://github.com/PX4/sitl_gazebo/pull/628 to be functional (now merged and included in this PR)

Add techpod SITL Gazebo target

---

src/modules/sensors/vehicle_imu/VehicleIMU.cpp
src/modules/sensors/vehicle_imu/VehicleIMU.hpp

In `sensors/vehicle_imu` raw gyro & accel data are integrated and published at `IMU_INTEG_RATE`. Up to 8 of these messages are queued (at the uORB leve), allowing the integrator to run at a much lower rate than the driver, but still consume all data. This PR adds a special case to continue consuming and integrating raw data if the integrator gets too far behind the raw data.
This is actually a fix/workaround for potential lockstep issues (https://github.com/PX4/Firmware/pull/15926), but it makes sense in general.

sensors/vehicle_imu: continue consuming raw data if falling behind

---

ROMFS/px4fmu_common/init.d-posix/rcS

It doesn't make sense to apply these to all models.

ROMFS: posix rcS remove all airframe specific defaults

---

Tools/setup/ubuntu.sh

**Problem**
This solves the problem of the install/update script (Tools/setup/ubuntu.sh) failing when trying to install gazebo9 in Ubuntu 20.04. 
**Solution**
This solution uses the Ubuntu release version already being checked in the script. If it is 18.04 the script uses/updates/installs gazebo9 and if on 20.04 uses/updates/installs gazebo11.
**Alternatives**
This could also be solved by checking what version of gazebo might already be installed and using that instead, however, gazebo11 should be the targeted install regardless for Ubuntu 20.04.
**Tests**
Tested on Ubuntu 20.04 and Ubuntu 18.04

fix ubuntu.sh for Ubuntu 20.04 - use gazebo11

---

launch/single_vehicle_spawn.launch

Fixes multi sim ROS launch for new jinja generation.
See https://github.com/PX4/sitl_gazebo/pull/634
I have tested this and it works for me on ROS noetic, 20.04.

Fixes for ROS based multi sim with jinja.

---

src/drivers/barometer/dps310/DPS310.cpp

Pressure was off by 4 millibar, took a look at the driver and found a copy/paste bug. Fixed it and now it agrees with my other barometers.

dps310: fix c11 coeffecient

---

ROMFS/px4fmu_common/init.d/rcS
boards/px4/fmu-v5x/src/board_config.h
src/lib/parameters/flashparams/flashparams.cpp
src/lib/parameters/flashparams/flashparams.h
src/lib/parameters/param.h
src/lib/parameters/parameters.cpp
src/lib/parameters/parameters_shmem.cpp
src/lib/systemlib/system_params.c
src/modules/commander/CMakeLists.txt
src/modules/commander/accelerometer_calibration.cpp
src/modules/commander/factory_calibration_storage.cpp
src/modules/commander/factory_calibration_storage.h
src/modules/commander/gyro_calibration.cpp
src/modules/commander/mag_calibration.cpp
src/modules/sensors/sensors.cpp
src/systemcmds/mtd/mtd.cpp
src/systemcmds/param/param.cpp
src/systemcmds/tests/test_parameters.cpp

- extends support for mtd to multiple devices
- extend `param_import` & `param_export` API's
- enables the EEPROM on the v5x IMU board and uses it as secondary storage (under `/fs/mtd_caldata`)
- if the device is enabled, parameters are loaded from that before the general parameters. This allows to store factory calibration parameters in `/fs/mtd_caldata`, allowing users to recalibrate and reset to factory.
- A parameter (`SYS_FAC_CAL_MODE`) is used to determine where to store the params after calibration. This could alternatively be done via a vehicle command or just an nsh command.
- enable `SYS_FAC_CAL_MODE`
- do sensor calibrations
- disable `SYS_FAC_CAL_MODE`
For later we can use separate parameter names for factory defaults.

multiple devices for mtd, separate (factory) calibration storage

---

src/modules/logger/log_writer_file.cpp
src/modules/mavlink/mavlink_main.cpp

These were increased due to erroneous stack usage reporting in the NuttX upgrade. https://github.com/PX4/Firmware/issues/15839

revert mavlink and logger stack increases

---

src/drivers/uavcan/sensors/gnss.cpp
src/drivers/uavcan/sensors/gnss.hpp
src/drivers/uavcan/sensors/sensor_bridge.hpp
src/drivers/uavcan/uavcan_main.cpp

Forwards messages on the gps_inject_data uORB topic as
uavcan::equipment::gnss::RTCMStream messages on the UAVCAN bus. This
enables differential/RTK GPS over UAVCAN to work.
Tested with CubePilot Cube Orange, Here+ base and Here3 rover.
Signed-off-by: Alex Mikhalev <alexmikhalevalex@gmail.com>
Here3 UAVCAN GNSS rover did not get an RTK fix.
Forward RTCM messages over UAVCAN bus and translate UAVCAN Fix2 status/mode/submode into `sensor_gps` fix_type.
Don't use RTK.
Tested on ground using CubePilot Cube Orange, Here+ base and Here3 rover. Was able to obtain DGPS fix. Proceeding to do further testing now

uavcan: gnss: Implement RTCM data for RTK

---

Tools/px_uploader.py

I'm getting firmware updating over Telem1 going on a Black Cube. I tried to run the px_uploader.py script with
```
python3 Tools/px_uploader.py --port /dev/ttyUSB0 build/px4_fmu-v3_default/px4_fmu-v3_default.px4
```
And it failed at L291 with the error
```
ERROR: unexpected 18 instead of INSYNC
```
But when you look at the value of INSYNC it is 0x12 which is indeed 18 in dec
After making these changes I was able to upload firmware successfully. FWIW I am using Python 3.6.9 and it also failed with Python 2.7.17.

px_uploader: fix bytes and char comparison

---

msg/satellite_info.msg
src/drivers/gps/definitions.h
src/drivers/gps/gps.cpp
src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/mavlink_messages.h
src/modules/mavlink/streams/GPS_STATUS.hpp

Hello,
This PR adds a `GPSStatus` mavlink stream to allow satellite vehicle information to be handled by the `Mavlink` class and adds a PRN code field to the `satellite_info` message.
The current uBlox driver is not currently publishing updates to observe this message, however a subsequent PR to the GpsDrivers submodule has followed to allow that functionality.
This PR has been bench tested on a Holybro pixhawk 4 and gps module. *This message requires subsequent work in the uBlox driver to be published: https://github.com/PX4/GpsDrivers/pull/59.
Please let me know if you have any questions on this PR.  Thanks!
-Mark

Add GPS_STATUS.hpp / MavlinkStreamGPSStatus message and stream to NORMAL, ONBOARD, and CONFIG modes.

---

src/drivers/magnetometer/lis2mdl/lis2mdl.h

This PR reduces the update rate of the lis2mdl mag from 50Hz to 20Hz, which has showed to produce less random spikes in the output.
50Hz, with spike:
20Hz:

lis2mdl: reduce update rate from 50Hz to 20Hz to reduce spikes

---

ROMFS/px4fmu_common/init.d-posix/airframes/1036_malolo
ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt
Tools/setup_jsbsim.bash
platforms/posix/cmake/sitl_target.cmake

This adds support to a flying wing vehicle called [Malolo1](http://wiki.flightgear.org/Malolo_1) to be used in JSBSim and PX4 SITL. 
The vehicle can be flown in PX4 SITL with the following make command
```
make px4_sitl jsbsim_malolo
```
Below shows a screenshot of the vehicle being visualized in flightgear
- This includes other updates in the submodule, that are explained in https://github.com/PX4/px4-jsbsim-bridge/pull/10
- @hamishwillee This will be added as a separate document in the dev guide once the vehicle list is a bit more stable

Add support for malolo flying wing in JSBSim SITL

---

Tools/upload.sh
platforms/nuttx/cmake/upload.cmake

Bootloader is ardupilot,Then use (make Px4_ fmu-v5_ Default upload) does not recognize the USB problem

Add a USB ardupilot * type

---

src/lib/output_limit/CMakeLists.txt

px4_add_library adds uorb dependencies, which since cf26f24387d added libm.
This in turn led to build failures for px4_io-v2 in the form of:
`__aeabi_f2d' wf_sqrt.c:(.text.sqrtf+0x54): undefined reference to __aeabi_ddiv'`
fixes https://github.com/PX4/Firmware/issues/15982

output_limit: use add_library instead of px4_add_library

---

src/modules/mavlink/mavlink_messages.cpp

Kill switch status is important information. For example, we don't want to start the autonomous flight if kill switch is on. This could be dangerous in some situations as well.
`MANUAL_CONTROL`'s `buttons` seems consistent place for it.
_The change seems trivial, haven't tested._

mavlink: expose kill switch status

---

Tools/setup/ubuntu.sh

I ran `./Tools/setup/ubuntu.sh` on a fresh instance of Ubuntu 20.04. Unfortunately, at the end of the process, I was faced with an error above:
```
E: Unable to locate package gazebo11
E: Unable to locate package libgazebo11-dev
```
I found out that `ubuntu.sh`, after adding new entry to source list, does not update it via `apt-get update`. I've added that line between adding gazebo to source list and installing gazebo.
No alternative solutions found, it's pretty straightforward.
Remove `gazebo11` and `libgazebo11-dev` packages, then removed `/etc/apt/sources.list.d/gazebo-stable.list` file and run `apt-get update`. Then re-run `ubuntu.sh` with a fix and …

Add apt-get update after adding gazebo list

---

src/modules/commander/Arming/PreFlightCheck/checks/magnetometerCheck.cpp

QGC reading the device id is a bit annoying and not that useful to a user. This is in sync with accel and gyro checks.

commander: preflight check don't read mag device_id

---

posix-configs/SITL/init/test/test_template.in
src/lib/battery/battery.h
src/lib/battery/module.yaml
src/modules/esc_battery/EscBattery.cpp

Apparently https://github.com/PX4/Firmware/pull/15616 was still incorrect.
- Fixes param migration, e.g. if BAT_N_CELLS is set, migrates to BAT1_N_CELLS.
- disable secondary module by default. This avoids a GCS showing 2 battery indicators. Alternatively we could also check the 'connected' flag, but this is more explicit.
@DonLakeFlyer does this work for you?
Fixes https://github.com/PX4/Firmware/issues/15929

Disable secondary power source by default, fix battery param migration (take 2)

---

src/modules/navigator/rtl.cpp

On startup the RTL can run without a valid home position yet
Don't run the RTL if the home position isn't valid yet

Check that home position is valid in RTL

---

msg/CMakeLists.txt
src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/mavlink_receiver.cpp
src/modules/mavlink/mavlink_receiver.h
src/modules/mavlink/streams/DEBUG.hpp
src/modules/mavlink/streams/DEBUG_FLOAT_ARRAY.hpp
src/modules/mavlink/streams/DEBUG_VECT.hpp
src/modules/mavlink/streams/NAMED_VALUE_FLOAT.hpp
src/modules/micrortps_bridge/CMakeLists.txt
src/systemcmds/topic_listener/CMakeLists.txt
src/systemcmds/topic_listener/generate_listener.py

- mavlink messages DEBUG/DEBUG_FLOAT_ARRAY/DEBUG_VECT/NAMED_VALUE_FLOAT move to separate stream headers and don't include if CONSTRAINED_FLASH
- mavlink receiver DEBUG/DEBUG_FLOAT_ARRAY/DEBUG_VECT/NAMED_VALUE_FLOAT handling excluded if CONSTRAINED_FLASH
- msg: skip debug_array.msg, debug_key_value.msg, debug_value.msg, debug_vect.msg if CONSTRAINED_FLASH
This saves about 2.7 kB of flash on flash constrained boards (fmu-v2, etc).

mavlink debug messages disable on CONSTRAINED_FLASH boards

---

posix-configs/SITL/init/test/test_template.in
src/lib/battery/battery.h
src/lib/battery/module.yaml
src/modules/esc_battery/EscBattery.cpp

https://github.com/PX4/Firmware/pull/15985 to v1.11

[BACKPORT] Disable secondary power source by default, fix battery param migration

---

msg/CMakeLists.txt

Saves 488 bytes of flash on fmu-v2.

msg: only include orb_test messages if PX4_TESTING enabled

---

Tools/mavlink_shell.py

The enumeration changed from usbmodem1 to usbmodem01 and this tracks this OS-level naming change.

Update MAVLink shell default device for modern Mac OS

---

src/lib/parameters/px4params/markdownout.py

The styling on this table is a "hangover" from the original generated docs. I want to remove it as it affects rendering on [vuepress version of docs](https://docs.px4.io/v1.testing/en/advanced_config/parameter_reference.html). 
This change has no effect on gitbook, and IMO is "better HTML".

parameter markdown table - remove styling

---

src/modules/simulator/simulator_mavlink.cpp

Actuator scaling for simulators for `MAV_TYPE_AIRSHIP` was unnecessarily being handled as an exception, while it could be just handled as part of the regular logic.
This removes the exception handling of airship type vehicles when scaling actuators for the simulator
This problem arises partly because we have actuator scaling in the simulator mavlink module. IMHO, there should be no actuator scaling when packing it on the actuator control messages, and should be handled by the simulators itself.

Remove exception of actuator scaling for airships

---

src/modules/sensors/voted_sensors_update.cpp

There's a race condition when you only have 1 mag where the sensors module may not update the parameters (and load the calibration) after that first mag starts publishing data. This doesn't apply to current master where the entire calibration architecture was restructured to avoid these types of issues.
This will be part of PX4 v1.11.2.

sensors: force parameter update if mag device id still isn't set

---

boards/nxp/rddrone-uavcan146/nuttx-config/include/board.h

nxp_rddrone-uavcan146:Fixed wrong SPI CLK Pin

---

platforms/nuttx/NuttX/Make.defs.in

NuttX build using the [Cygwin Toolchain](https://dev.px4.io/master/en/setup/dev_env_windows_cygwin.html) is broken since the NuttX 9.1.0+ upgrade #15139 . The pr was merged nevertheless to unblock core developers using the new NuttX version and with the intent to fix the build shortly after. PX4 stable v1.11 was the officially recommended version to build in case you ran into any problems.
Fixes #15760 
It took me quite some time to figure out:
- NuttX has a new way of configuring the build environment now using multiple flags
- Those flags have to be set before including Config.mk
- The new way of assembling `ARCHINCLUDES` even before the makefile made a new way of converting the include paths that are already …

Fix NuttX build under Cygwin

---

src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp
src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.hpp
src/modules/commander/Arming/PreFlightCheck/checks/accelerometerCheck.cpp

- skipping these sensor checks in HIL no longer makes sense as each sensor has a normal publication (sensor_accel/gyro/etc) regardless of simulation

commander: PreFlightCheck remove HIL special cases

---

src/modules/mc_pos_control/CMakeLists.txt
src/modules/mc_pos_control/MulticopterPositionControl.cpp
src/modules/mc_pos_control/MulticopterPositionControl.hpp

These renames are kind of obnoxious, but this seems like a relatively quiet time to do it.

mc_pos_control: split out header and name consistently

---

boards/spracing/h7extreme/default.cmake
boards/spracing/h7extreme/init/rc.board_sensors
boards/spracing/h7extreme/nuttx-config/include/board.h
boards/spracing/h7extreme/nuttx-config/include/board_dma_map.h

Previously the board used mpu6000 drivers, now it is updated to use icm20602.
Both gyros are enabled. 
Not sure what helped but it seems in the meantime something fixed DMA for SPI, and now gyros started working with updates in this commit.
I've just enabled DMA mux (I tried this same method before but this is the first time that it works)

SP Racing H7 extrem:  updated to use icm20602 drivers

---

ROMFS/px4fmu_common/init.d/rcS
msg/sensor_gyro_fft.msg
src/examples/gyro_fft/CMakeLists.txt
src/examples/gyro_fft/GyroFFT.cpp
src/examples/gyro_fft/GyroFFT.hpp
src/examples/gyro_fft/parameters.c

- add new parameter `IMU_GYRO_FFT_EN` to start
- add 75% overlap in buffer to increase FFT update rate
- space out FFT calls (no more than 1 per cycle)
- increase `IMU_GYRO_FFT_MIN` default
- decrease main stack usage

gyro_fft: improve peak detection, add start parameter

---

src/lib/parameters/px4params/srcparser.py
src/modules/ekf2/EKF2.hpp
src/modules/ekf2/ekf2_params.c

Comments say that ekf2 saved mag bias are in mGauss but it seems to be in the same units as ekf2 magnetic states: Gauss

fix ekf2 saved mag bias comments (mGauss -> Gauss)

---

src/lib/flight_tasks/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.cpp
src/lib/flight_tasks/tasks/ManualAltitudeSmoothVel/FlightTaskManualAltitudeSmoothVel.cpp
src/lib/flight_tasks/tasks/ManualAltitudeSmoothVel/FlightTaskManualAltitudeSmoothVel.hpp
src/lib/flight_tasks/tasks/ManualPositionSmoothVel/FlightTaskManualPositionSmoothVel.cpp

The orriding child class should call the `reActivate()` function of the parent. Otherwise e.g. the base reactivate logic gets overriden and skipped.

FlightTasks: fix reActivate not calling the parent overrided method

---

msg/CMakeLists.txt
msg/estimator_optical_flow_vel.msg
msg/tools/uorb_rtps_message_ids.yaml
src/drivers/optical_flow/pmw3901/PMW3901.cpp
src/modules/ekf2/EKF2.cpp
src/modules/ekf2/EKF2.hpp
src/modules/ekf2/ekf2_params.c
src/modules/logger/logged_topics.cpp

This is really useful to align the flow with the IMU data and verify that the compensation is properly done
update to https://github.com/PX4/ecl/pull/920
includes:
- logging of compensated optical flow data converted to velocity measurement in body and local frames
- logging of un/compensated optical flow data for rate motion and synchronized gyro data
- adjust scaling value of pmw3901 data (was off by 30%)
- adjust delay parameter for pmw3901 for perfect synchronization with gyro data
Bench tested with pmw3901 optical flow sensor and Lanbao PSK-CM8JL65 range finder:
*Note that I recently renamed the fields in `optical_flow_vel` so the signals in the screenshot below don't have the correct names*

Optical flow: compute velocity from corrected flow data for logging

---

src/modules/mc_hover_thrust_estimator/hover_thrust_estimator_params.c
src/modules/mc_hover_thrust_estimator/zero_order_hover_thrust_ekf.cpp
src/modules/mc_hover_thrust_estimator/zero_order_hover_thrust_ekf.hpp

In the prediction step, the process variance was erroneously multiplied by `dt` instead of `dt^2`. The default values are adjusted accordingly to keep the same tuning for the default loop rate of 50Hz.

HTE: fix variance prediction

---

msg/tools/uorb_rtps_message_ids.yaml
msg/vehicle_odometry.msg
src/modules/ekf2/EKF2.cpp
src/modules/ekf2/EKF2.hpp
src/modules/ekf2/EKF2Selector.cpp
src/modules/ekf2/EKF2Selector.hpp
src/modules/logger/logged_topics.cpp

I'm assuming `vehicle_visual_odometry_aligned` only exists for log review purposes (added in https://github.com/PX4/Firmware/pull/12771)?
Renaming this saves a small amount of work for the selector in mult-EKF mode and possibly makes the origin/purpose of each message a little clearer.

rename vehicle_visual_odometry_aligned -> estimator_visual_odometry_aligned

---

ROMFS/px4fmu_common/init.d-posix/rcS
boards/px4/sitl/default.cmake
boards/px4/sitl/nolockstep.cmake
boards/px4/sitl/rtps.cmake
boards/px4/sitl/test.cmake
src/modules/load_mon/LoadMon.cpp
src/modules/load_mon/LoadMon.hpp

`load_mon` get memory allocation information by parsing `/proc/meminfo`.
This provides the same behavior as [free(1)](https://gitlab.com/procps-ng/procps/-/blob/master/proc/sysinfo.c). The module measures system-wide memory usage, without swap included.
Enabled in SITL as well.

load_mon get mem_usage by reading /proc/meminfo on Linux

---

msg/tools/uorb_rtps_message_ids.yaml

`orb_test_medium_wrap_around` is missing an ID on RTPS, and `px4_ros_com` complains about it:
```
AssertionError: 
The following message is not listen under  /home/navq/px4_ros_com_ros2/src/px4_ros_com/templates/uorb_rtps_message_ids.yaml: OrbTestMediumWrapAround
Please add them to the yaml file with the respective ID and, if applicable, mark them to be sent or received by the micro-RTPS bridge.
NOTE: If the message has multi-topics (#TOPICS), these should be added as well.
```
Since the checks for multi-topic is still not in place, this slipt by. Action item to me: robustify the checks.

msg: rtps: add missing ID for orb_test_medium_wrap_around

---

src/modules/ekf2/EKF2.cpp
src/modules/ekf2/EKF2.hpp

Saves about 900 bytes of memory per ekf2 instance.

ekf2: avoid storing message copies

---

.gitmodules

Github magically redirects these, but we might as well update it for consistency.

gitmodules update URLs to renamed PX4 repositories

---

src/modules/ekf2/EKF2.cpp

This saves a little bit of memory in the simple single ekf2 instance case where many configurations will never publish some of these topics.

ekf2: only advertise immediately in multi-EKF mode

---

src/modules/uORB/SubscriptionMultiArray.hpp

And ensure not to dereference.

fix SubscriptionMultiArray: end() iterator needs to point past the end

---

msg/sensor_gyro_fft.msg
src/examples/gyro_fft/GyroFFT.cpp
src/examples/gyro_fft/GyroFFT.hpp
src/lib/mathlib/CMakeLists.txt
src/lib/mathlib/math/filter/MedianFilter.hpp
src/lib/mathlib/math/filter/MedianFilterTest.cpp
src/modules/commander/gyro_calibration.cpp

This is a crude and somewhat lazy MedianFilter that I created to use in the gyro FFT module for peak detection.
There's plenty of room for improvement if anyone's interested. I initially implemented this using a sorting networks (SWAP macros) and a fixed size, but qsort was good enough for now.

FFT add simple median filter

---

Tools/setup/shell.nix
platforms/nuttx/Debug/poor-mans-profiler.sh
platforms/nuttx/NuttX/tools/kconfig-conf
platforms/nuttx/NuttX/tools/kconfig-tweak
platforms/nuttx/NuttX/tools/px4_nuttx_make_olddefconfig.sh
src/drivers/dshot/dshot.cpp

Greetings PX4 developers. These changes make it easier to build PX4 on [NixOS](https://nixos.org/).
I changed the interpreter in some `platforms/nuttx` scripts as `/bin/bash` does not exist on clean NixOS installation. Then I added `Tools/setup/shell.nix`, which you can supply to `nix-shell` to obtain an environment in which PX4 will have its build dependencies.
Also see [this build error I had to fix](https://github.com/PX4/PX4-Autopilot/commit/0b5ee19b6b41383e63c1e3da6b9e3b6c1cce4a81). I guess it might be because of too old an ARM GCC (9-2019-q4-major)? Should I get the `shell.nix` environment to have newer version? That's doable with some additional effort.
Well you could use …

Build on NixOS

---

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c

In manual control, a VTOL atm (in position mode) is controlled to following way:
hover:
up/down: left stick
forward/backward: right stick
fixed-wing:
up/down: right stick, while up is pulling the stick down 'towards oneself', 'pitching up'
fly faster/slower: left stick
For non-trained operators, resp. that are trained with multicopters, this is quite confusing.
This changes the RC stick allocation for fixed-wing position and altitude controlled flight to align fixed-wing with hover controls (same sticks for going up/down (left stick) and accelerate/de-accelerate (right stick).
hover:
up/down: left stick
forward/backward: right stick
fixed-wing:
up/down: left stick, up is up
fly faster/slower: right stick
**Test …

FW Position controller: add option to swap throttle and pitch stick

---

src/drivers/uavcan/rgbled.cpp
src/drivers/uavcan/rgbled.hpp
src/drivers/uavcan/uavcan_params.c

Extends the existing UAVCAN "rgbled" for automatic control of more light types. Publishes commands for beacon, strobe, nav, and landings lights. Each is automatically controlled based on arming state and the behavior of each is configurable via params. For example, nav lights can be set to be always on while beacons turn on when the system is prearmed and strobes turn on only when armed.
This has been tested and works as expected with the soon-to-be-released [Avionics Anonymous UAVCAN light controller](https://docs.avionicsanonymous.com/devices/lightcontroller). It will of course also work with any other system that accepts commands using the standard UAVCAN light_id and color data.

Extend UAVCAN light control

---

README.md

Changes current Maintenance Team structure in README.md in order to be more organized and with a standard.
Signed-off-by: Ricardo Marques <marques.ricardo17@gmail.com>
Before:
After:

README: Cleanup Maintenance Team structure

---

ROMFS/px4fmu_common/init.d-posix/airframes/1041_tailsitter
test/mavsdk_tests/configs/sitl.json

Current hover tuning leads to instability during takeoff.
Some little tweaks to the hover tuning. Don't know exactly which change has the biggest impact, my guess is setting `MPC_XY_VEL_I_ACC` to default (was 10x default)
Some SITL testing.
Should help with https://github.com/PX4/PX4-Autopilot/pull/16074.
I've also removed some params that I deem unnecessary to specify (like takeoff altitude, using the one from vtol_defaults, 20m, should be fine).

Improve tailsitter tuning master

---

Tools/gazebo_sitl_multiple_run.sh

This adds support to simulate multiple rover vehicles at once. Previously this was not easy since the rover vehicle had to be ported into xacro macros to be able to support multivehicle simulations.
This is the result of the migration of rover models into jinja templates in https://github.com/PX4/sitl_gazebo/pull/629
- This PR requires https://github.com/PX4/sitl_gazebo/pull/629 to be merged in the  PX4/sitl_gazebo submodule

Support multivehicle SITL simulations for rover in gazebo

---

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp

This removes a duplicated update of `_pos_sp_triplet_sub` that slipped in with https://github.com/PX4/PX4-Autopilot/pull/16104

FW Position Control: remove duplicated position_sp_triplet update

---

Jenkinsfile

@hamishwillee you'll need to make sure the directory `en/modules` exists.

Jenkins: push module documentation to PX4 user guide as well

---

src/lib/version/px_update_git_header.py
src/systemcmds/tests/test_versioning.cpp

Support for alpha/beta/rc on the vendor version is part of the actual parser, but is disallowed by the regex in the build scripts. This adds support for alpha/beta/rc on the vendor version by changing the regex.
Additionally, this allows the -dev suffix, for anybody who needs to use it.
I tested this on the test data for the parser (hooray for test data), and it all seems to make sense:

Add support for alpha/beta/rc on the vendor version

---

src/drivers/gps/gps.cpp
src/drivers/gps/params.c

- Adds support for heading output using 2 F9P devices. Setup is described here: https://www.u-blox.com/sites/default/files/ZED-F9P-MovingBase_AppNote_%28UBX-19009093%29.pdf.
- Main GPS = Rover
- Secondary GPS = Moving Base
- add `GPS_PROTOCOL` to select the protocol, default to u-blox. This should be a bit faster on startup for module detection.
- attach 2 F9P's (UART1 to Pixhawk) and enable them
- connect their UART2 to each other
- set `GPS_UBX_MODE` to 1
- reboot and wait until both devices have GPS. `gps status` should then show the main GPS going into RTK mode.
- RTK is still possible (the main GPS will show RTK mode even w/o RTK, which might be a bit confusing). The secondary will show the actual RTK mode.
- u-blox also provides an F9H, specifically for heading, replacing one of the …

GPS: add u-blox F9P heading support, and GPS_PROTOCOL param for protocol selection

---

Tools/px4moduledoc/markdownout.py

@bkueng Unfortunately Vuepress can't process explicit anchors in the heading like `## Usage {#thingy_usage}` so this changes the output to:
```
<a id="thingy_usage"></a>
```
Because Vuepress is smarter at linking to a heading might be better to change as below?
```
```
Thoughts? It will make the docs look a bit ugly. UP to you - just check and merge if you prefer what I have done.

module markdownout - explicit anchor not heading

---

platforms/nuttx/src/px4/common/board_crashdump.c

Sometimes my FCU would hang on boot, before the boot tune but after the bootloader.
On boot, if board_hardfault_init finds a hardfault stored in BBSRAM, it
checks if there is any data available on stdin to see if there is
somebody there to respond to a prompt. But on boards such as cubeorange
where there is not a serial console by default, the ioctl fails and
`bytesWaiting` is uninitialized. So it will non-deterministally hang the
boot process with no outside feedback if that value is not zero.
Initialize `bytesWaiting`
N/A
I have tested this and it fixed my boot hang.

Fix non-determinstic boot hang with crashdumps

---

src/drivers/uavcan/sensors/battery.cpp

It seems that battery.voltage_* is no longer used and QGC is getting voltage data from the cell voltage array instead.
MAVLINK 2 requires that if no cell voltage information is available the total voltage is written into the first array element of the voltages array in the battery_status message. This solution writes the voltage data into the first element of the voltages array.

Fix for missing battery voltage from UAVCAN power modules

---

.vscode/cmake-variants.yaml
platforms/posix/CMakeLists.txt
platforms/posix/Debug/launch_rpi.json.in
platforms/posix/cmake/sitl_target.cmake

This adds some basic VScode support for Emlid Navio2 PX4 development.
You can use this to develop and debug directly on a Raspberry pi from VSCode running anywhere. The initial compile is a little slow, but with ccache working it actually becomes quite tolerable. Debugging in place is very useful.
FYI @blazczak @SalimTerryLi

vscode add navio2 variant and native debug launch

---

.github/workflows/sitl_tests.yml

Running all vehicle types at 4 different locations is a bit too slow on Github actions. This breaks it up to dedicate each Github Actions runner to 1 vehicle type.

Github Actions: break up MAVSDK SITL tests

---

src/systemcmds/topic_listener/generate_listener.py

This is a bit wasteful, but we can afford it for now everywhere listener is enabled. The message print helpers can be rewritten as a common function that prints using the msg o_fields we already store for logger, and save about 70 kB of flash in the process.
- fixes https://github.com/PX4/PX4-Autopilot/issues/16135

systemcmds/topic_listener: remove excludes

---

platforms/nuttx/NuttX/CMakeLists.txt

- NuttX Apps no longer generates the .built file
- fixes https://github.com/PX4/PX4-Autopilot/issues/16162

cmake: NuttX apps build updates

---

test/mavsdk_tests/autopilot_tester.cpp
test/mavsdk_tests/autopilot_tester.h

In MAVSDK SITL tests tailsitter is occasionally just outside of the 1 meter threshold.
https://logs.px4.io/plot_app?log=0db3be38-b42f-4e29-b2ab-c249062a2c3a

mavsdk_tests: relax corridor radius default for missions

---

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp

With https://github.com/PX4/PX4-Autopilot/pull/16104/commits/574c7c5d90e328fb8eea0dda1a93353a660dfdee the airspeed_poll() was wrongly removed from the fixed-wing position controller. This PR reverts that.
SITL tested.

FW Position Control: re-add wrongly removed airspeed_poll()

---

boards/intel/aerofc-v1/default.cmake
boards/nxp/fmurt1062-v1/default.cmake
msg/estimator_innovations.msg
platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp
src/drivers/roboclaw/RoboClaw.cpp
src/modules/ekf2/CMakeLists.txt
src/modules/ekf2/EKF2.cpp
src/modules/ekf2/EKF2.hpp

- refactor enormous Run() into separate methods for handling each ecl/EKF sample and each message publication
- GPS, flow, and ExtVision updates skipped if disabled in EKF2_AID_MASK
- preflightChecker only reset on arming state changes instead of constantly when armed
- separate perf counters for ecl/EKF updates where only the output predictor is run
- accel bias not populated in `estimator_sensor_bias` if inhibited by EKF2_AID_MASK
- ekf2 module respect MAX_CUSTOM_OPT_LEVEL optimization level (-O2 unless flash constrained)
- px4_work_queue reduce INSx stacks by 1200 bytes

ekf2: refactor data update and publications into separate methods

---

src/lib/sensor_calibration/Accelerometer.cpp
src/lib/sensor_calibration/Gyroscope.cpp
src/lib/sensor_calibration/Magnetometer.cpp
src/lib/sensor_calibration/Utilities.cpp
src/lib/sensor_calibration/Utilities.hpp
src/modules/commander/accelerometer_calibration.cpp
src/modules/commander/mag_calibration.cpp

Potentially a quick interim solution for https://github.com/PX4/PX4-Autopilot/issues/16126.

sensor calibration: apply board level adjustment to external sensors

---

src/modules/mavlink/mavlink_messages.cpp

Theoretically could help with calibration (https://github.com/PX4/PX4-Autopilot/pull/16166), but should be harmless regardless.

mavlink: STATUSTEXT check TX buffer before sending

---

.ci/Jenkinsfile-hardware

- px4_fmu-v5 debug and stackcheck builds initial configuration is best effort
- nxp_fmuk66-v3 allow overall tests command to fail due to intermittent serial console issues

Jenkins HIL tolerate certain failures

---

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp

Currently, there is a hard-coded limit of 85% on the pitch stick (pulling) setpoint that triggers the climbout mode when flying in fixed-wing position or altitude controlled mode. The vehicle will then give max throttle and try to climb as fast as physics allow. 
This prevents a precise, but still dynamic control of the vehicle, as it is impossible to climb fast without entering the climbout mode, that was (I believe) originally implemented rather as a safety feature. 
~Add parameter to disable climbout mode via sticks (boolean).~
Remove the manually triggered climbout mode (pitch stick below 85% in altitude/position controlled flight). 
Note that this doesn't have any impact on the automatically triggered …

Fixed-wing position control: remove manually triggered climbout mode 

---

ROMFS/px4fmu_common/init.d-posix/rcS
ROMFS/px4fmu_common/init.d/rc.interface
ROMFS/px4fmu_common/init.d/rc.io
ROMFS/px4fmu_common/init.d/rcS

The bootlog could be useful, but our usage is inconsistent and only a small portion of startup errors are captured. We have a few cases that log to both the console and bootlog, some only to the bootlog, and the majority that doesn't go to bootlog at all.
I propose purging the existing bootlog.txt and work towards better mechanisms for getting this information out to users (mavlink most of the time).

ROMFS: startup remove bootlog.txt

---

boards/cubepilot/cubeorange/init/rc.board_sensors
boards/cubepilot/cubeyellow/init/rc.board_sensors

Quick solution to https://github.com/PX4/PX4-Autopilot/issues/16194.
The isolated sensors are on SPI4, but by default we end up using the non-isolated sensors on SPI1 simply because they're started first.
This will probably be one of the first boards where multi-EKF will be enabled by default, but for the startup order is quite important.

boards: cubepilot orange and yellow start icm20602 IMU first

---

Tools/setup/requirements.txt

Needed for `./Tools/mavlink_shell.py`.

Tools/setup: requirments add pymavlink

---

test/mavsdk_tests/process_helper.py
test/mavsdk_tests/test_multicopter_failsafe.cpp
test/mavsdk_tests/test_multicopter_manual.cpp
test/mavsdk_tests/test_multicopter_mission.cpp

This is an experiment to hunt down one of the remaining MAVSDK test intermittent failures.

mavsdk_tests: adjust px4 and gzserver priority relative to mavsdk_test

---

Tools/gazebo_sitl_multiple_run.sh

This commit adds support for the typhoon_h480 model for the gazebo_sitl_multiple_run.sh script. This will allow multiple typhoon_h480 models to run in the simulator at the same time.
Literally just adds typhoon_h480 to SUPPORTED_MODELS.
Depends on [this sitl_gazebo PR](https://github.com/PX4/PX4-SITL_gazebo/pull/655) being merged.

Add typhoon h480 support to gazebo multiple sim

---

src/modules/mavlink/mavlink_receiver.cpp
src/modules/mavlink/mavlink_receiver.h

Removing a function I randomly saw that is not referenced anywhere.
Still compiles.

mavlink_receiver: remove unused decode_switch_pos function

---

Tools/sitl_run.sh

This is a followup on #16214, where a syntax error in `sitl_run.sh` was preventing SITL from running properly
Remove the spaces
Tested locally, with
```
make px4_sitl gazebo
```
- The problem was intrduced in #16214

Fix bash error when running SITL Gazebo

---

boards/nxp/ucans32k146/src/timer_config.cpp

The initial PWM timer configuration was made for and tested on a pre-production version of the hardware. It's about time we change this to enable PWM on the released version of the board. @davids5 @dagar 
FYI @igalloway

NXP UCANS32K146: Configure PWM timer for production version

---

cmake/px4_add_common_flags.cmake

See https://github.com/PX4/PX4-Matrix/pull/146
There is a proper fix for this already on master
but it's a rabbit hole to cherry-pick it:
-> update matrix
-> dependency on changing ecl
-> dependency on a lot of autopilot changes
Disable Wlogical-op since the warning did not exist before.
Using this backported for months now. Since Arch updated to GCC 10.

[1.11] PX4 compile flags: disable Wlogical-op for GCC 10

---

src/modules/temperature_compensation/TemperatureCompensationModule.cpp

The message used is ./msg/sensor_correction.msg, so I think the usage info is outdated...
_If_ this is correct and gets merged, the docs also need an update: http://docs.px4.io/master/en/modules/modules_system.html#temperature-compensation
@dagar please take a look :)

Correct topic name for thermal corrections

---

src/drivers/distance_sensor/ll40ls/LidarLiteI2C.cpp
src/drivers/distance_sensor/ll40ls/LidarLiteI2C.h
src/drivers/distance_sensor/ll40ls/ll40ls.cpp

Backport of https://github.com/PX4/PX4-Autopilot/commit/c0cf144a5a7bbbdd1e23a2d37b608471579837e8
Without this commit, the default orientation is 0
Tested on a Pixhawk4 with a ll40ls

ll40ls: fix rotation -> orientation

---

src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/mavlink_receiver.cpp
src/modules/mavlink/mavlink_receiver.h
src/modules/mavlink/streams/GPS_GLOBAL_ORIGIN.hpp
src/modules/mavlink/streams/RAW_RPM.hpp

External trajectory generating instances cannot really work in the autopilot's local frame because they do not know the origin. They could only use the reported local and global position to to some accuracy infer the local origin reference.
Publish the autopilot global coordinates of its local position reference that is internally available on uORB `vehicle_local_position.ref_*` to the existing MAVLink message every 2 seconds (FYI @JonasVautherin)  https://mavlink.io/en/messages/common.html#GPS_GLOBAL_ORIGIN
- To achieve that I had to replace the existing use of the MAVLink message `GPS_GLOBAL_ORIGIN` to use the also existing `SET_GPS_GLOBAL_ORIGIN`.
- I found an unrelated message length definition bug in …

Send out local position reference GPS_GLOBAL_ORIGIN over MAVLink

---

src/drivers/px4io/px4io_uploader.cpp

The Debug code was broken and not useful.
This rat limits the syncs and fixed the `recv_bytes` to print the data.

Fixed PX4IO uploader debug output

---

src/modules/commander/Arming/PreFlightCheck/checks/accelerometerCheck.cpp
src/modules/commander/Arming/PreFlightCheck/checks/baroCheck.cpp
src/modules/commander/Arming/PreFlightCheck/checks/gyroCheck.cpp
src/modules/commander/Arming/PreFlightCheck/checks/magnetometerCheck.cpp
src/modules/commander/mag_calibration.cpp

- QGroundControl is reading these as "Hash" and I don't think it's ambiguous if removed

commander: preflightcheck and calibration remove hash (#) from mavlink message

---

src/modules/ekf2/EKF2Selector.cpp

Flight testing master with 4 EKF's running using 2  IMU and 2 compass units showed continual changes in the primary EKF selected:
Code inspection showed that the ternary operator used to set the relative error score change threshold to zero when a gyro inconsistency fault had been detected was reversed, meaning that the EKF2_SEL_ERR_RED parameter was not being used.
The fix restores the intent of the EKF2_SEL_ERR_RED parameter and prevents switching to a different EKF instance due to minor improvements in error score.

Fix bug causing excessive EKF primary instance changes

---

src/modules/commander/Commander.cpp

- re-evaluating mode switches on altitude or position validity change can create confusion when also relying on mode changes via mavlink
- limiting this logic to only apply when disarmed solves the original problem (respecting initial switch position) without introducing potential problems mid-flight

commander: limit mode switch re-evaluation logic on estimate validity changes

---

ROMFS/px4fmu_common/init.d/rc.vtol_defaults

By default, the wind estimation in EKF is not enabled for VTOLs, while it is for fixed-wings. Wind estimation is needed for dead-reckoning inside EKF. 
Enable airspeed and sideslip fusing by default also for VTOLs. Set airspeed threshold to 10m/s. 
I've also removed `MPC_LAND_SPEED` from the defaults, because it was actually just set to the normal param default again (0.7m/s).
Would it actually make sense to include `EKF2_FUSE_BETA` in `EKF2_AID_MASK` ? And instad of `EKF2_ARSP_THR`, we could use `ASPD_STALL` (though I'm not sure if we want "external" params used by EKF), and also add it as a boolean in the `EKF2_AID_MASK` "airspeed fusion on".

rc.VTOL_defaults: enable wind estimation in EKF by default

---

src/modules/rc_update/params.c

I had to look up not just in code but also in the git history what `RC_MAP_FAILSAFE` does. Never saw this in action but it seems certain RC receivers report failsafe alias RC link signal loss through a channel instead of not sending any signal anymore. Documentation is to short because I received a report that `RC_MAP_FAILSAFE` doesn't work from someone expecting toggling the channel makes the pwm outputs don't go to their failsafe value.
FYI @hamishwillee

rc_update_params: clarify failsafe channel and threshold

---

msg/templates/urtps/Publisher.cpp.em
msg/templates/urtps/Publisher.h.em
msg/templates/urtps/RtpsTopics.cpp.em
msg/templates/urtps/RtpsTopics.h.em
msg/templates/urtps/Subscriber.cpp.em
msg/templates/urtps/Subscriber.h.em
msg/templates/urtps/microRTPS_agent.cpp.em

When having several drones, each running micrortps agent, in the same ros network, there is a need for a mechanism to separate topics on different drones from each other.
This adds a command line parameter for micrortps_agent " -n <namespace> ", which places all the created publisher and subscriber nodes into the given namespace, that way separating them in the ros network.
Changed code generation templates for micrortps_agent in a way that there is an additional command line …

Add topic namespace support for micrortps agent generation

---

src/modules/simulator/simulator.h
src/modules/simulator/simulator_mavlink.cpp

fixed case that actuator that wasn't set (value 0 "PWM") results output of -3  
using unified way to decide which output should be scale as rotor
more minor cleanups
I notice that if actuator on actuator_outputs (that is on 'pwm' units of 1000-2000) hasn't been set, because it not used. the actuator_controls (which is in units of 0 to +1 to rotors, and -1 to +1 of other actuators) get -3 value.
tested iris, and cloudship

simulator mavlink actuator limits

---

ROMFS/px4fmu_common/init.d/airframes/3033_wingwing
ROMFS/px4fmu_common/init.d/airframes/4051_s250aq

There was an incorrect link in generated docs to https://docs.px4.io/master/en/frames_multicopter/spedix_s250_pixracer.html and https://docs.px4.io/master/en/framebuild_plane/wing_wing_z84.html

Fix incorrect docs URLs in airframes definitions

---

Tools/sitl_run.sh

There was a regression on macOS that was introduced by https://github.com/PX4/PX4-Autopilot/pull/16214, where it searches for available models in `GAZEBO_MODEL_PATH` sequentially.
This commit removes the `readarray` command from the Tools/sitl_run.sh. This fixes the issue where SITL was not able to run due to readarray not being available on macOS
Tested locally on Ubuntu 20.04
- This fixes https://github.com/PX4/PX4-Autopilot/issues/16263

Fix sitl_run to run in macOS

---

src/lib/l1/ECL_L1_Pos_Controller.cpp

Based on [discussion in slack](https://px4.slack.com/archives/C3B9NSHRQ/p1601298551006900?thread_ts=1601131103.003900&cid=C3B9NSHRQ).
The current L1 logic often makes the vehicle first fly through center of loiter waypoint, instead of tracking the loiter circle as soon as it is close to it (or after already being inside the circle). 
Remove check for the tangential velocity to "prevent PD output from turning the wrong way". AFAIK this causes the vehicle to fly straight to the loiter center if the tangential velocity is only slightly in the wrong direction (e.g. because it's hitting the loiter circle at a  91° angle).
Instead of removing check completely, allow small tangential …

L1: remove check for tangent_vel direction for nicer loiter entry behavior

---

ROMFS/px4fmu_common/mixers/vtol_tailsitter_duo.main.mix
src/modules/fw_att_control/FixedwingAttitudeControl.cpp

I realized that there is no integrator on the pitch and roll axis of a tailsitter atm, because it uses the fixed-wing rate controller on these axis and that one had the integrators locked when not in fixed-wing flight or in transition. 
Having integrator action is especially important on the pitch axis, to stabilize the system in wind plus to help to avoid tipping over.
I've further noticed that the elevon deflection is scaled by 0.75 atm, thus reducing the maximal control output around the pitch and yaw axis. 
- Enable integrators in fixed-wing rate controller always when the system is a tailsitter. 
- Remove the elevon scale.
Testflown on a small tailsitter (Xvert).
**Additional …

Tailsitter: remove integrator lock in hover and increase elevon deflection

---

msg/tools/px_generate_uorb_topic_helper.py

On the serialization/deserialization templates, `get_children_fields()` was returning the message fields ordered by the size of the data types, resulting on mismatches between the expect message structure and the received/sent message structure for nested types - this was identified by @mickey13 while using `position_setpoint_triplet` for offboard control.
As uCDR doesn't add padding bytes for serialization purposes, there's no need for byte ordering - this was initially removed in https://github.com/PX4/PX4-Autopilot/pull/12025, but not for nested types. This was now removed from the `get_children_fields()` functions as well.
Resulting `serialize_position_setpoint()` and …

microRTPS: remove byte ordering for nested types

---

src/modules/navigator/mission_block.cpp

Previously, rover vehicles were not able to handle Takeoff waypoints. The behavior when a takeoff waypoint was passed to a rover vehicle was:
- The vehicle would not move since the waypoint was too close
- The takeoff waypoint would not get accepted since rovers are not able to climb and reach the altitude
I think it might be obvious that one "should not" pass takeoff waypoints to a vehicle. However, QGroundControl only lets you plan a mission that starts with a takeoff waypoint. While this should also be an improvement on the QGC side, I think it is still useful to handle this case on the vehicle side so that the vehicle can still progress with the mission even with a takeoff waypoint
This adds a special case …

Handle takeoff waypoints for rover

---

boards/holybro/durandal-v1/default.cmake

Didn't test yet.
Welcome suggestions.
Reference:
tested start TFmini on TELEM3 works fine `tfmini start -d /dev/ttyS4`

Enable TELEM3 for Holybro Durandal

---

src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/streams/ATTITUDE.hpp
src/modules/mavlink/streams/ATTITUDE_QUATERNION.hpp
src/modules/mavlink/streams/ATTITUDE_TARGET.hpp
src/modules/mavlink/streams/COLLISION.hpp
src/modules/mavlink/streams/OPTICAL_FLOW.hpp
src/modules/mavlink/streams/OPTICAL_FLOW_RAD.hpp

Move some Mavlink Streams from mavlink_messages.cpp to streams/
Changes have been tested locally by runing _make px4_sitl_test_ and with _px4_sitl_default jmavsim_ and checking with _QGroundControl_

mavlink: move streams to streams headers

---

src/modules/mavlink/mavlink_receiver.cpp

`typemask` in the `SET_TARGET_POSITION_LOCAL_NED` message is used as a tool to control the behavior of tracking a setpoint in offboard mode. However, the typemasks that are used in PX4 include more typemasks than defined in the mavlink spec. This is confusing to identify since the typemasks are written as numbers directly in the code.
This uses enums of the mavlink `POSITION_TARGET_TYPEMASK` in order to state type masks that are part of the mavlink spec more explicitly
By doing this, I noticed that we have `ignore_alt_hold` which I believe will never get active.  Does anybody have ideas on why this type mask exists? Do we want to keep it?
```
offboard_control_mode.ignore_alt_hold = …
```

Use enums for offboard position setpoint typemasks 

---

src/drivers/tone_alarm/ToneAlarm.cpp
src/lib/tunes/tunes.cpp
src/lib/tunes/tunes.h
src/systemcmds/tune_control/tune_control.cpp

Repeating tunes started by Commander like failsafe would never stop. This is because `tone_alarm` would reject the `tune_control` to stop the tune since the repeating tune is still playing. 
Can reproduce by
```
tune_control play -t 7 # play battery warning slow
tune_control play -t 8 # battery warning fast does not play
tune_control stop # this will stop the tune, but only because it has tune_override = true
``` 
`Tunes` already has some logic for deciding whether a tune should be interrupted or not, as well as special cases
for `tune_id = 0` for stopping tunes. So I expose that logic through return codes and use that to decided whether
or not to interrupt a tune.
Duplicate the …

tunes: Fix repeating tunes that do not stop

---

src/modules/rc_update/rc_update.cpp
src/modules/rc_update/rc_update.h

This updates the RC update pipeline to only do the final mapping + publish if the RC source is stable (source and number of channels consistently the same). It's a minor robustness improvement for certain failure cases.

rc_update: only decode if RC input is stable (channels and source)

---

src/modules/mc_pos_control/MulticopterPositionControl.cpp
src/modules/mc_pos_control/MulticopterPositionControl.hpp

When switching between auto modes the state of the FlightTaskAuto stays which is known but sometimes not desirable because you have to take care of resetting certain member variables in every other possible use case the task will get executed for after the original intent.
I load the flight task from scratch whenever the mode is switched to avoid the initialization problem of switching back and forth between modes that currently use the same task. I do it this way because it's in line with our plans to have one unique implementation per mode and just reusing code through libraries.
I SITL tested and it was real-world tested. The only problem that was found and fixed is that the way of just …

MulticopterPositionControl: Reset task between auto mode switches

---

boards/px4/fmu-v5x/src/manifest.c

VER is on BASE
REV is on FMU
ver|rev
bas|fmu
{0x0000, hw_mft_list_v0500, ...(hw_mft_list_v0500)},
{0x0001, hw_mft_list_v0501, ...(hw_mft_list_v0501)}, <-- was wrong
This falsely selected the NO I/O version

px4_fmu-v5x:Manifest Update Adde Rev 1 HW and fix VER 1

---

src/lib/flight_tasks/FlightTasks.cpp
src/lib/flight_tasks/tasks/ManualAcceleration/FlightTaskManualAcceleration.cpp
src/lib/flight_tasks/tasks/Utility/StickAccelerationXY.cpp
src/lib/mathlib/math/Functions.hpp
src/lib/mathlib/math/FunctionsTest.cpp

Three reported issues from pilots:
1. It takes a long time (~5 seconds) until the position lock setpoint is set.
2. Vehicle flies back to original position when moved on the ground in position mode.
3. Vehicle takes too long to slow down to zero at the very end.
1. See 3.
2. I made the `resetPosition();` function for exactly that purpose but in the end forgot to call it in the `activate()` function of the flight task -> added `_stick_acceleration_xy.resetPosition();` now like it was originally planned.
3. It takes so long to brake at the end because acceleration = velocity_dot = k * velocity results in an exponential decay and has nice characteristics but when velocity reaches close to zero it takes an eternity to …

Acceleration stick mapping improvements

---

src/modules/mavlink/mavlink_receiver.cpp

Previously, mavlink spec defined a bitmask of the attitude setpoint type_masks in the description
This makes it cumbersome to use.
This commit switches the typemask comaparision to enums for better readability, and includes a update on the mavlink library so that the newly defined enums can be used
- The enums were added to mavlink in https://github.com/mavlink/mavlink/pull/1532

Use enums for set attitude setpoint typemasks for offboard mode

---

msg/home_position.msg
src/drivers/telemetry/hott/messages.cpp
src/lib/flight_tasks/tasks/Auto/FlightTaskAuto.cpp
src/modules/commander/Commander.cpp
src/modules/commander/Commander.hpp
src/modules/commander/commander_params.c
src/modules/navigator/navigator.h

When taking off without a home position, RTL is impossible, even if good GPS data is obtained just after takeoff.
If another horizontal aiding source is available, the original home location can be back-computed as soon as a GPS lock is available.
If no aiding source is available, a home position can be set at the current location. Given that this will only occur when flying LOS, doing an RTL to this position is a reasonable choice.
Enable the functionality by setting `COM_HOME_IN_AIR = 1`
Always set the home position to the current position as back-computing could be worse if the local estimate wasn't good.
Gazebo SITL tests with the Iris optical flow: …

In-air home position

---

src/modules/ekf2/EKF2.cpp
src/modules/ekf2/EKF2Selector.cpp
src/modules/ekf2/EKF2Selector.hpp

- fixes https://github.com/PX4/PX4-Autopilot/issues/16278
Depending on the particular sensor configuration and startup timing we were getting an initial `sensor_selection` publication without valid accel & gyro device ids. Only applies to Multi-EKf.

ekf2: multi-ekf force initial selection (and sensor_selection publication)

---

src/lib/battery/battery.cpp

This was flagged as undefined behaviour by fuzz testing.

battery: don't init uint16_t with -1.0f

---

msg/gps_dump.msg
src/drivers/gps/gps.cpp

The newly fixed function of GPS_DUMP (https://github.com/PX4/PX4-Autopilot/issues/16229, https://github.com/PX4/PX4-Autopilot/pull/16247) generates a dump only from the first (main) GPS. This PR extends the dump to all connected GPS receiver (currently main/secondary receiver).
This is resolved, that the 'gps_dump' uOrb message contains an 'instance' value that contains the GPS instance attribute. The main GPS is 0; secondary is 1, etc ..
I also modified a  python script to extract data from the .ulog log. It will be in the next PR in the pyulog repository.

'GPS_DUMP_COMM' dumps only main GNSS reciever. 

---

msg/wind_estimate.msg
src/modules/airspeed_selector/airspeed_selector_main.cpp
src/modules/ekf2/EKF2.cpp

- the "sideslip fusion only" wind estimator in the airspeed selector is updated while in hover (while it is only valid to do so in fixed-wing)
- not easy to distinguish separate `wind_estimate` instances from each other
- add identifier to `wind_estimate` message to distinguish source (EKF, airspeed selector with only beta fusion, airspeed selector for sensor X)
- do not fuse beta in hover
SITL tested.

Wind estimation: add identifier and do not fuse beta in hover

---

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp

To enable gliding, there is a check in fixed-wing position controller that adapts some settings in TECS if the current throttle setpoint is below the min threshold. This is currently done separately for Position and Loiter type waypoints. 
Also, it's not handled the same atm: in loiter, `pos_sp_curr.cruising_throttle` is ignored if above `_param_fw_thr_min` - is there a reason for that?
Do the throttle setpoint adaptions before Position- or Loiter-specific logic, and always use `pos_sp_curr.cruising_throttle` if set. 
SITL tested with standard VTOL.

FW Position Controller: consolidate mission throttle adaptions for position and loiter waypoints

---

src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp

- either way the user action is to recalibrate, so we might as well try to minimize the noise/annoyance

commander: preflightcheck only report failure once per sensor type

---

src/modules/commander/Commander.cpp

- auto transition to LOITER if disarmed with no RC only requires a valid global position
Pretty minor, but there is a difference.

commander: entering LOITER requires global position, not home
