PX4/PX4-Autopilot

src/drivers/lsm303d/lsm303d.cpp

we have logs where the lsm303d gets large fixed values for long
periods. This will detect that error case and raise error_count so the
higher level sensor integration code can choose another sensor

lsm303d: detect large fixed values and report an error

---

src/drivers/frsky_telemetry/frsky_data.c
src/drivers/gps/ashtech.cpp
src/drivers/gps/mtk.cpp
src/drivers/gps/ubx.cpp
src/modules/ekf_att_pos_estimator/ekf_att_pos_estimator_main.cpp
src/modules/mavlink/mavlink_receiver.cpp
src/modules/position_estimator_inav/position_estimator_inav_main.c
src/modules/sdlog2/sdlog2.c
src/modules/uORB/topics/vehicle_global_position.h
src/modules/uORB/topics/vehicle_gps_position.h
src/modules/uavcan/sensors/gnss.cpp

Renaming of GPS time to UTC time

---

ROMFS/px4fmu_common/init.d/rc.usb

This simplyfies verification of the RC setup

send MANUAL_CONTROL stream over usb

---

src/include/mavlink/mavlink_log.h
src/modules/mavlink/mavlink_messages.cpp
src/modules/sdlog2/sdlog2.c
src/systemcmds/nshterm/nshterm.c

Continuing #1577 here. This pull request checks if the microSD card is full and takes appropriate action.

Check for full microSD card

---

Makefile
nuttx-patches/Fixed-Shadow-wanings.patch
src/drivers/boards/px4fmu-v1/px4fmu_init.c
src/drivers/boards/px4fmu-v1/px4fmu_spi.c
src/drivers/boards/px4fmu-v2/px4fmu2_init.c
src/modules/px4iofirmware/px4io.h
src/modules/systemlib/px4_macros.h

Updated to Greg's lates with PX4 specific patches for shadow warnings
make archives will apply patches and distclean will remove them, rejects are not generated.

Nuttx bringup

---

unittests/CMakeLists.txt
unittests/sf0x_test.cpp
unittests/st24_test.cpp

All unittests are now in gtest, although sf0x_test still doesn't actually check anything. Now we can really start expanding the testing.

Move the rest of the unittests to gtest

---

ROMFS/px4fmu_common/init.d/rcS

@LorenzMeier these 2 can go as well I think.

rcS: unset MODE and AUTOCNF

---

src/modules/commander/commander.cpp

Two changes to improve user experience:
* The buzzer plays a neutral tune when the drone goes from armed to disarmed state. This is useful for auto landings so that the user knows when it is safe to approach the vehicle.
* It was kind of hard to know when you pressed the safety switch if it was toggled or not. Now it plays a tune whenever it has safety off (positive tune) or safety on (neutral tune).

Commander: Play tune on disarm and when safety switch is toggled

---

src/drivers/ms5611/ms5611.cpp
src/lib/mathlib/math/filter/LowPassFilter2p.cpp
src/modules/ekf_att_pos_estimator/ekf_att_pos_estimator_main.cpp

use low pass filtered baro and gps altitudes to maintain a dynamic offset
reduce baro temp sample rate to ~1Hz
baro pressure sample rate is ~72Hz

dynamic estimation of baro_gps_offset

---

src/modules/sdlog2/sdlog2.c
src/modules/sdlog2/sdlog2_messages.h
src/modules/uORB/topics/vtol_vehicle_status.h
src/modules/vtol_att_control/vtol_att_control_main.cpp
src/modules/vtol_att_control/vtol_att_control_params.c

Use physical model of propeller to determine total airflow over elevons

New airspeed scaling

---

Tools/px_uploader.py

Reduce the verbosity of the upload status text. A successful upload now looks like this:
Erase  : [====================] 100.0%
Program: [====================] 100.0%
Verify : [====================] 100.0%
Rebooting.

Cleanup px_uploader output.

---

src/drivers/px4fmu/fmu.cpp
src/modules/commander/commander.cpp
src/modules/ekf_att_pos_estimator/estimator_22states.cpp
src/modules/uORB/uORB.cpp

@thomasgubler Please review quickly. These are the most relevant coverity fixes in one package.

Critical coverity fixes.

---

src/drivers/gps/gps_helper.cpp
src/drivers/px4fmu/fmu.cpp
src/drivers/px4io/px4io.cpp
src/modules/commander/mag_calibration.cpp
src/modules/px4iofirmware/controls.c
src/modules/sensors/sensors.cpp
src/modules/systemlib/err.c

Some assorted fixes. Needs mag calibration test.

Coverity fixes

---

src/drivers/drv_range_finder.h
src/drivers/mb12xx/mb12xx.cpp

Mb12xx multi support

---

src/drivers/drv_accel.h
src/drivers/drv_gyro.h
src/drivers/l3gd20/l3gd20.cpp
src/drivers/lsm303d/lsm303d.cpp
src/drivers/mpu6000/mpu6000.cpp
src/modules/sensors/sensors.cpp

@LorenzMeier  as discussed the cleanup prior to your sensor interface work.

Sensors app: clean up

---

src/modules/mc_att_control_multiplatform/mc_att_control_base.cpp
src/modules/mc_pos_control_multiplatform/mc_pos_control.cpp

fixes #1735
Needs rework/porting once #1741 is finished (no conflicts due to the separate files)

Ros fix yaw in non manual mode

---

src/modules/mc_att_control_multiplatform/mc_att_control_base.cpp
src/modules/mc_pos_control_multiplatform/mc_pos_control.cpp

ros/sitl update to master (temporary fix for yaw problems with multiplatform controllers)

---

Tools/ros/docker/px4-ros-full/scripts/setup-workspace.sh
Tools/ros/px4_workspace_setup.sh

ros workspace setup scripts: use master branch

---

launch/gazebo_ardrone_empty_world.launch
launch/gazebo_ardrone_house_world.launch
launch/gazebo_iris_empty_world.launch
launch/gazebo_iris_house_world.launch
launch/gazebo_iris_outdoor_world.launch
src/examples/subscriber/subscriber_example.cpp
src/examples/subscriber/subscriber_example.h
src/modules/mc_att_control_multiplatform/mc_att_control.cpp
src/modules/mc_att_control_multiplatform/mc_att_control.h
src/modules/mc_pos_control_multiplatform/mc_pos_control.cpp
src/modules/mc_pos_control_multiplatform/mc_pos_control.h
src/modules/mc_pos_control_multiplatform/module.mk
src/platforms/px4_defines.h
src/platforms/px4_parameter.h
src/platforms/px4_publisher.h
src/platforms/px4_subscriber.h
src/platforms/ros/nodes/mc_mixer/mc_mixer.cpp

This adds an additonal layer for the parameters in the multiplatform apps. The example subscriber app is fully ported and tested on ROS and NuttX
includes #1754
fixes #1710

multiplatform: improve param api

---

makefiles/config_px4fmu-v2_default.mk
src/examples/flow_position_estimator/flow_position_estimator_main.c

The flow position estimator is very useful indoors and warrants being a default app in  my opinion.

Flow est default apps

---

ROMFS/px4fmu_common/init.d/rc.usb
src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/mavlink_orb_subscription.cpp

Quick fix for actuator control messages which were chewing up far too much bandwidth.

Mavlink act ctrl

---

src/drivers/drv_mag.h

drv_mag: fixed copy paste typo

---

launch/gazebo_ardrone_empty_world.launch
launch/gazebo_ardrone_house_world.launch
launch/gazebo_iris_empty_world.launch
launch/gazebo_iris_house_world.launch
launch/gazebo_iris_outdoor_world.launch

As discussed in PX4/Firmware/pull/1803, Needs PX4/euroc_simulator/pull/10

Use new arguments for euroc launch files

---

src/modules/mc_pos_control_multiplatform/mc_pos_control.cpp

Original diff for mc_pos_control is here https://github.com/PX4/Firmware/pull/1752/files#diff-fc77c3ef569029d45764664c75d4b0c1L985

port #1752 to multiplatform

---

ROMFS/px4fmu_common/init.d/50001_rover
ROMFS/px4fmu_common/init.d/rc.rover_defaults

here is the diff, can u have a look at 50001_rover? maybe the AUTOCNF stuff can be removed since I dont use it anyway ?

modified default pwm values and added comments to the startup scripts

---

src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/mc_pos_control_multiplatform/mc_pos_control.cpp

@AndreasAntener I think this should fix the issue discussed in #1854
This is the same fix for mc_pos_control and mc_pos_control_multiplatform

mc pos ctrl (multiplatform): do not publish att sp in offboard && no position/velocity control

---

integrationtests/demo_tests/direct_manual_input_test.py
integrationtests/demo_tests/direct_offboard_posctl_test.py
integrationtests/demo_tests/direct_tests.launch
integrationtests/demo_tests/flight_path_assertion.py
integrationtests/demo_tests/manual_input.py
integrationtests/demo_tests/mavros_offboard_attctl_test.py
integrationtests/demo_tests/mavros_offboard_posctl_test.py
integrationtests/demo_tests/mavros_tests.launch
launch/gazebo_ardrone_empty_world_offboard_attitudedemo.launch
launch/gazebo_ardrone_empty_world_offboard_positiondemo.launch
launch/mavros_sitl.launch

Supersedes #1847, against master

Mavros test updates

---

integrationtests/demo_tests/manual_input.py
integrationtests/demo_tests/mavros_offboard_attctl_test.py
integrationtests/demo_tests/mavros_offboard_posctl_test.py

This should fix the SITL tests..

Trigger correct offboard mode in mavros IT

---

Tools/px_uploader.py
src/lib/mathlib/math/Quaternion.hpp

Still have to write unit test for this.

added quaternion methods for inverse and vector rotation

---

src/modules/sensors/sensor_params.c

These are used by ground station software as described in the code comments.

Add RC_CHAN_CNT, RC_TH_USER for QGC

---

src/systemcmds/tests/test_mathlib.cpp

added quaternion rotation method test

---

src/modules/ekf_att_pos_estimator/ekf_att_pos_estimator_main.cpp
src/modules/ekf_att_pos_estimator/estimator_22states.cpp
src/modules/ekf_att_pos_estimator/estimator_22states.h
src/modules/ekf_att_pos_estimator/estimator_utilities.cpp
src/modules/ekf_att_pos_estimator/estimator_utilities.h

This fixes #1871 by inhibiting mag offset if we are multicopter that is hovering without any deliberate accelerations (0.5 m/s)

AttPosEKF Fix for inhibit mag state for fly-forward for multicopters

---

msg/vehicle_attitude.msg

improve comments for attitude message

---

integrationtests/demo_tests/direct_manual_input_test.py
integrationtests/demo_tests/direct_offboard_posctl_test.py
integrationtests/demo_tests/manual_input.py
integrationtests/demo_tests/mavros_offboard_attctl_test.py
integrationtests/demo_tests/mavros_offboard_posctl_test.py
integrationtests/demo_tests/mavros_tests.launch
launch/ardrone.launch
launch/gazebo_ardrone_empty_world.launch
launch/gazebo_ardrone_empty_world_offboard_attitudedemo.launch
launch/gazebo_ardrone_empty_world_offboard_positiondemo.launch
launch/gazebo_ardrone_house_world.launch
launch/gazebo_iris_empty_world.launch
launch/gazebo_iris_house_world.launch
launch/gazebo_iris_outdoor_world.launch
launch/iris.launch
launch/mavros_sitl.launch
launch/multicopter.launch
launch/multicopter_w.launch
launch/multicopter_x.launch
src/platforms/ros/nodes/mc_mixer/mc_mixer.cpp

this also removes the duplicated joy node.
rotors_simulator PR: https://github.com/PX4/euroc_simulator/pull/9
mav_comm PR: https://github.com/PX4/mav_comm/pull/1
supersedes #1852  (is the same but against master)

update ros launch files and nodes for update of rotors_simulator

---

src/modules/ekf_att_pos_estimator/AttitudePositionEstimatorEKF.h
src/modules/ekf_att_pos_estimator/ekf_att_pos_estimator_main.cpp
src/modules/ekf_att_pos_estimator/estimator_22states.cpp
src/modules/ekf_att_pos_estimator/estimator_22states.h

Fixes various bugs causing degraded preformance of the EKF (#1902).
Most importantly fixes 5Hz sawtooth on X and Y position. Edge cases should be tested some more before merging (how it handles GPS loss, gaining fixes in-air while in ALT_CTRL mode, etc.)

Fix EKF Attitude Position Estimator bugs

---

src/platforms/ros/nodes/mavlink/mavlink.cpp
src/platforms/ros/nodes/mavlink/mavlink.h

Fixing handling of attitude setpoints

---

src/modules/mc_att_control/mc_att_control_main.cpp
src/modules/mc_att_control/mc_att_control_params.c

This should improve tracking performance of the body rate controller.

Multicopter Attitude Control: Introduce rates setpoint feedforward

---

Tools/boot_now.py
Tools/px_uploader.py
nuttx-configs/px4fmu-v2/scripts/ld.script

Pullrequest boot delay

---

ROMFS/px4fmu_common/init.d/rc.fw_defaults
ROMFS/px4fmu_common/init.d/rc.mc_defaults
ROMFS/px4fmu_common/init.d/rc.vtol_defaults
src/drivers/hmc5883/hmc5883.cpp
src/drivers/l3gd20/l3gd20.cpp
src/drivers/lsm303d/lsm303d.cpp
src/drivers/mpu6000/mpu6000.cpp
src/modules/commander/accelerometer_calibration.cpp
src/modules/commander/commander.cpp
src/modules/commander/commander_helper.cpp
src/modules/commander/gyro_calibration.cpp
src/modules/commander/mag_calibration.cpp
src/modules/commander/module.mk
src/modules/ekf_att_pos_estimator/ekf_att_pos_estimator_main.cpp
src/modules/ekf_att_pos_estimator/ekf_att_pos_estimator_params.c
src/modules/ekf_att_pos_estimator/estimator_22states.cpp

This fixes the use of the IMU delta T for gyro bias compensation and leads to more stable gyro offset results.

EKF gyro offsetfix

---

src/drivers/gimbal/gimbal.cpp

**WIP**
Will test this next week

Gimbal MAVLink configuration and control support

---

src/lib/px4_eigen.h
src/systemcmds/tests/module.mk
src/systemcmds/tests/test_eigen.cpp
src/systemcmds/tests/tests.h
src/systemcmds/tests/tests_main.c

Runs tests similar to test_mathlib to verify correctness of calculations made by Eigen. WIP

Added test_eigen to verify correctness of eigen calculations

---

src/drivers/lsm303d/lsm303d.cpp
src/drivers/mpu6000/mpu6000.cpp

added temperature to accel_report for lsm303d and show temperature in both "lsm303d info" and "mpu6000 info"
This is the first step to doing temperature calibration of accelerometers

Pullrequest imu temperature

---

src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/mc_pos_control_multiplatform/mc_pos_control.cpp

Not flown this yet, but there's not much to it.
Fixes #1951

Write trust setpoint to correct field for logging

---

src/modules/mavlink/mavlink_receiver.cpp
src/modules/mavlink/mavlink_receiver.h

Added handling in mavlink_receiver for ping messages for latency testing.

Ping messages

---

src/drivers/px4io/px4io.cpp
src/modules/px4iofirmware/mixer.cpp
src/modules/px4iofirmware/px4io.h
src/modules/px4iofirmware/registers.c
src/modules/px4iofirmware/sbus.c

This enables 16 channels via S.BUS. Ready for bench-testing.

Support 16 channels on IO via S.BUS

---

integrationtests/demo_tests/direct_manual_input_test.py
integrationtests/demo_tests/direct_offboard_posctl_test.py
integrationtests/demo_tests/direct_tests.launch
integrationtests/demo_tests/flight_path_assertion.py
integrationtests/demo_tests/manual_input.py
integrationtests/demo_tests/mavros_offboard_attctl_test.py
integrationtests/demo_tests/mavros_offboard_posctl_test.py
integrationtests/demo_tests/mavros_tests.launch
launch/mavros_sitl.launch
src/platforms/ros/nodes/demo_offboard_attitude_setpoints/demo_offboard_attitude_setpoints.cpp
src/platforms/ros/nodes/demo_offboard_position_setpoints/demo_offboard_position_setpoints.cpp

**WIP**
@thomasgubler : this updates tests and demo nodes for MAVROS 0.11
More fixes are coming (another NS change) as soon as I get 0.11.1 on Ubuntu, will wait for that before merging.
Fixes #1979

Mavros update

---

src/drivers/hil/hil.cpp
src/drivers/mkblctrl/mkblctrl.cpp
src/drivers/px4fmu/fmu.cpp
src/drivers/px4io/px4io.cpp
src/modules/px4iofirmware/mixer.cpp
src/modules/px4iofirmware/protocol.h
src/modules/px4iofirmware/px4io.h
src/modules/px4iofirmware/registers.c
src/modules/systemlib/mixer/mixer.cpp
src/modules/systemlib/mixer/mixer.h
src/modules/systemlib/mixer/mixer_group.cpp
src/modules/systemlib/mixer/mixer_multirotor.cpp
src/modules/systemlib/mixer/mixer_simple.cpp
src/modules/uORB/topics/multirotor_motor_limits.h
src/modules/uavcan/uavcan_main.cpp
src/systemcmds/tests/test_mixer.cpp

Mixer limit flags are now published.

fixed publication of mixer limit flags

---

src/modules/mavlink/mavlink_receiver.cpp
src/modules/mavlink/mavlink_receiver.h
src/modules/sdlog2/sdlog2.c
src/modules/sdlog2/sdlog2_messages.h
src/modules/uORB/objects_common.cpp
src/modules/uORB/topics/time_offset.h

Added uORB topic so that the time offset is accessible globally. Some general fixes added too.
Don't merge this yet, I wanted to do a couple of things which I'm forgetting now, I think.

timesync: Add uORB topic, general fixes

---

src/modules/navigator/geofence.cpp
src/modules/navigator/geofence.h
src/modules/navigator/geofence_params.c
src/modules/navigator/navigator.h
src/modules/navigator/navigator_main.cpp

I'm still planning to physically test this once I get my hex working well.

Geofence max horizontal and vertical distance

---

Tools/px_mkfw.py
src/modules/commander/commander_params.c
src/modules/fw_pos_control_l1/mtecs/mTecs_params.c
src/modules/navigator/datalinkloss_params.c
src/modules/navigator/navigator_params.c
src/modules/position_estimator_inav/position_estimator_inav_params.c
src/modules/vtol_att_control/vtol_att_control_params.c

This is needed in order to decompress in QGroundControl

Store parameter xml size in .px4 file

---

Tools/px4params/srcparser.py
src/modules/attitude_estimator_ekf/attitude_estimator_ekf_params.c
src/modules/commander/commander_params.c
src/modules/mavlink/mavlink.c
src/modules/navigator/datalinkloss_params.c
src/modules/navigator/gpsfailure_params.c
src/modules/navigator/navigator_params.c
src/modules/navigator/rcloss_params.c
src/modules/navigator/rtl_params.c
src/modules/sensors/sensor_params.c

We now have decent group names for everything. Fixed parser for missing defines. I'm going to call it good from my side.
Still need lots of work with units and short description. But I'll leave that up to the firmware folks to clean up.

Parameter meta data fixes

---

Tools/px4params/xmlout.py

Had to switch to ElementTree to get attribute support

Change to V2 spec of param meta data

---

ROMFS/px4fmu_common/init.d/13002_firefly6

corrected PWM_OUT for firefly6 configuration

---

ROMFS/px4fmu_common/init.d/rc.usb
src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_parameters.cpp
src/modules/sensors/sensors.cpp
src/modules/systemlib/param/param.c
src/modules/systemlib/param/param.h

This uses the right function for individual param transfers.

Param index fix

---

src/modules/commander/accelerometer_calibration.cpp
src/modules/commander/airspeed_calibration.cpp
src/modules/commander/calibration_messages.h
src/modules/commander/calibration_routines.cpp
src/modules/commander/calibration_routines.h
src/modules/commander/commander.cpp
src/modules/commander/gyro_calibration.cpp
src/modules/commander/mag_calibration.cpp
src/modules/sensors/sensors.cpp

- cancel support
- versioned cal messages
- better still detection
- better messaging
@DonLakeFlyer This is your PR rebased.

Sensor cal rework

---

src/modules/commander/PreflightCheck.cpp
src/modules/commander/commander.cpp

This now logs to the console. Still need to add a check for the circuit breaker.

Ensure that the airspeed preflight check logs to the console.

---

src/drivers/px4io/px4io.cpp

For a discussion please refer to: https://github.com/PX4/Firmware/issues/2119

IO output driver robustness

---

src/drivers/px4io/px4io.cpp
src/modules/px4iofirmware/mixer.cpp
src/modules/px4iofirmware/px4io.h
src/modules/px4iofirmware/registers.c
src/modules/px4iofirmware/sbus.c

This reverts commit f8c8876642857520e85ec8ca027146c11b4301e3, reversing
changes made to de3888bed75347eb8aefdc6cb7dbeeedff749988.

Revert "Merge pull request #1819 from PX4/chan16" because of #2113

---

ROMFS/px4fmu_common/init.d/rc.mc_apps
src/modules/attitude_estimator_ekf/attitude_estimator_ekf_params.c

@kd0aij Based on your feedback: This will allow users to choose between filters. I didn't get around to test it yet though.

Attitude filter for multirotors: Let users choose between filters

---

src/drivers/l3gd20/l3gd20.cpp
src/drivers/lsm303d/lsm303d.cpp
src/drivers/mpu6000/mpu6000.cpp

See https://groups.google.com/forum/#!topic/drones-discuss/1svE46ETjPk

fix "whiskers" aliasing issue

---

src/modules/sdlog2/sdlog2.c

This allows to force use of the GPS module's time instead of system time.

Give user a choice which time source to pick

---

Tools/generate_listener.py
src/platforms/posix/drivers/airspeedsim/airspeedsim.cpp

POSIX: changes to support posix build on ARMv7

---

src/modules/dataman/dataman.c

dataman can now be started using:
dataman start -f filepath

Added ability to set OS specific path for dataman file

---

README.md

* add link to releases
* add link to STM32F4Discovery Tutorial on pixhawk.org

Update README.md with links to releases and STM32F4Discovery Tutorial

---

src/drivers/px4flow/px4flow.cpp
src/modules/fw_att_control/fw_att_control_main.cpp
src/modules/land_detector/land_detector_main.cpp
src/modules/mavlink/mavlink_main.cpp
src/modules/position_estimator_inav/position_estimator_inav_main.c
src/platforms/common/px4_getopt.c

Cosmetic startup fixes

---

src/drivers/px4io/px4io.cpp

not sure why this error popped up for me, but submitting PR in case it needs fixing

fix type mismatch

---

src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp

fix posctl heading hold

---

src/modules/commander/commander.cpp

This seems like an improvement to me, but it's not clear whether the autostart ID range of 1000-1999 is reserved for HIL

Hil inhibit sensor check

---

src/modules/commander/commander.cpp
src/modules/commander/state_machine_helper.cpp

remove remaining extraneous preflight check failure messages for HIL platforms

inhibit more sensor checks

---

ROMFS/px4fmu_common/mixers/README.md

-the angle brackets in the tag descriptions were breaking the markdown

fix mixers README.md

---

src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp

- lock desired yaw once yaw speed is small

fixed wing posctrl

---

Tools/generate_listener.py
Tools/posix_apps.py

* The `print """` syntax appears invalid in python3 which is the default
for the python binary on my system (and soon many more).
* Explicitly request python2 until some one with more python-fu can
bring this up to speed.

Tools: Update python files to work with python3

---

.gitmodules

Should be safe to merge, but I'd wait for a report from Travis.

Libuavcan submodule update

---

makefiles/firmware_posix.mk
makefiles/posix/config_posix_default.mk
src/platforms/posix/include/board_config.h
src/platforms/px4_defines.h
src/systemcmds/ver/ver.c

Added systemcmds/ver to posix build and other missing defines.

POSIX: fixes for nuttx-next integration

---

src/modules/mavlink/mavlink_main.cpp

@LorenzMeier This it the fix for mavlink_if0: invalid data rate '(null)' bug
argv from a create_task is has the task name in argv[0]
see comments on line [1294] (https://github.com/PX4/Firmware/compare/master_mavlink_null_fix?expand=1#diff-a067fe2f10623e822f3af3bfd7b74f00R1294) and [1828] 
(https://github.com/PX4/Firmware/compare/master_mavlink_null_fix?expand=1#diff-a067fe2f10623e822f3af3bfd7b74f00R1828)

Backport of Fixes mavlink_if0: invalid data rate '(null)' bug

---

src/modules/sensors/sensor_params.c

Same fix as already merged in master

fix posctl th param meta

---

src/modules/navigator/mission.cpp
src/modules/navigator/mission.h

@tumbili This might be related. I just found this now. The fix is not yet tested.
https://github.com/PX4/Firmware/issues/2326

Navigator: Make logic using previous and current altitudes consistent

---

src/modules/mc_pos_control/mc_pos_control_params.c

This should fix #2279 for good.

Update MC thrust limit default param value and add explanation

---

Tools/check_submodules.sh

Failed without this - https://travis-ci.org/PX4/Firmware/builds/66620528

Recursive submodule checkout

---

src/drivers/hil/hil.cpp

This implements more of the simulated capabilities.

Add more functionality to HIL driver

---

.travis.yml
Makefile
makefiles/setup.mk

@LorenzMeier - this is good to go.

Document the the sizes of sections inside the elf files.

---

src/lib/external_lgpl/tecs/tecs.cpp
src/modules/fw_att_control/fw_att_control_main.cpp

This is experimental, it may or might not help.

Attitude loop speed

---

src/modules/commander/commander.cpp

@kd0aij This is the slightly improved version of #2372. Thanks for highlighting this!

commander: Remove unused param handles

---

src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp

@tumbili Please add this to your test. It might solve the manual flight issues in the climb out modes and also might help a bunch with takeoff already.

FW pos control: Perform climbout if user requests more than 85% pitch up

---

src/platforms/posix/drivers/gyrosim/gyrosim.cpp

gyrosim: removed dead code from gyrosim

---

src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/mc_pos_control/mc_pos_control_params.c

@kd0aij @tumbili This is what we discussed.

MC att control demand: Require a higher minimum throttle

---

src/modules/ekf_att_pos_estimator/ekf_att_pos_estimator_main.cpp
src/modules/sensors/sensors.cpp

@tumbili This is good for testing. It should help with larger altitude control gains.
Please make sure to fly the *very same* mission with this patch set and without.

EKF unfiltered airspeed

---

ROMFS/px4fmu_common/init.d/13001_caipirinha_vtol
ROMFS/px4fmu_common/init.d/13002_firefly6
ROMFS/px4fmu_common/init.d/13003_quad_tailsitter
ROMFS/px4fmu_common/init.d/rc.autostart
ROMFS/px4fmu_common/mixers/quad_x_vtol.main.mix
src/modules/fw_att_control/fw_att_control_main.cpp

- rotate attitude in fw attitude control module if vtol type is tailsitter
- added config and mixer file for a tailsitter in quad x configuration

Vtol new tailsitter

---

src/platforms/posix/main.cpp

@tumbili Please try this and see if that works without your continue statement in the sensors app.

POSIX: Force shell to not immediately return

---

Tools/Matlab/ellipsoid_fit.m
Tools/Matlab/plot_mag.m
src/drivers/hmc5883/hmc5883.cpp
src/modules/commander/calibration_messages.h
src/modules/commander/calibration_routines.cpp
src/modules/commander/mag_calibration.cpp

@DonLakeFlyer This moves to six axis. @tumbili This addresses the mag cal issue.

Mag calibration improvements

---

src/modules/ekf_att_pos_estimator/ekf_att_pos_estimator_main.cpp
src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp

@kd0aij This is good for testing. Hopefully the prop now idles without GPS lock and althold works without GPS as well.

Prop idling in ALTCTL and POSCTL

---

src/drivers/ll40ls/ll40ls.cpp
src/drivers/mb12xx/mb12xx.cpp
src/drivers/sf0x/sf0x.cpp
src/drivers/trone/trone.cpp

Added validity check to some distance drivers

drivers: added validity check

---

makefiles/posix/config_posix_sitl.mk
posix-configs/SITL/init/rcS
src/modules/land_detector/FixedwingLandDetector.cpp
src/modules/land_detector/land_detector_main.cpp
src/modules/navigator/navigator_main.cpp

With this you are able to plan and fly missions.
@LorenzMeier Could you have a look at the changes I made to the land detector? I'm not very sure what you have to return for NuttX (on errors or success) so it would be great if you could review.

Sitl mission enable

---

src/modules/land_detector/land_detector_main.cpp

land_detector: shut up if started correctly

---

src/drivers/device/vdev_posix.cpp
src/platforms/posix/drivers/gyrosim/gyrosim.cpp
src/platforms/posix/include/hrt_work.h
src/platforms/px4_defines.h
src/platforms/qurt/include/hrt_work.h

Changed px4_poll to use a HRT workqueue instead of creating a separate pthread.
Fixed PX4_ISFINITE(x) for QuRT.

Bringup m5

---

Tools/qurt_apps.py
makefiles/posix-arm/config_eagle_hil.mk
makefiles/posix-arm/config_eagle_muorb_test.mk
makefiles/posix-arm/ld.script
makefiles/posix-arm/toolchain_gnu-arm-linux-gnueabihf.mk
makefiles/qurt/config_qurt_hil.mk
makefiles/qurt/config_qurt_muorb_test.mk
makefiles/qurt/qurt_elf.mk
makefiles/qurt/toolchain_hexagon.mk
src/modules/muorb/adsp/module.mk
src/modules/muorb/adsp/muorb_fastrpc.cpp
src/modules/muorb/adsp/muorb_fastrpc.h
src/modules/muorb/adsp/uORBFastRpcChannel.cpp
src/modules/muorb/adsp/uORBFastRpcChannel.hpp
src/modules/muorb/krait/module.mk
src/modules/muorb/krait/muorb_main.cpp
src/modules/muorb/krait/uORBKraitFastRpcChannel.cpp
src/modules/muorb/krait/uORBKraitFastRpcChannel.hpp

The Eagle HW platform contains both a Krait (ARMv4hf compatible) cpu
cluster and a Hexagon DSP running QuRT.
These changes support the PX4 build for Eagle.

Eagle: posix-arm and qurt changes to support Eagle HW platform

---

src/platforms/qurt/tests/muorb/module.mk
src/platforms/qurt/tests/muorb/muorb_test_example.cpp
src/platforms/qurt/tests/muorb/muorb_test_example.h
src/platforms/qurt/tests/muorb/muorb_test_main.cpp
src/platforms/qurt/tests/muorb/muorb_test_start_qurt.cpp

QuRT: Unit tests for QuRT

---

src/modules/uORB/ORBMap.hpp
src/modules/uORB/ORBSet.hpp
src/modules/uORB/Publication.cpp
src/modules/uORB/Publication.hpp
src/modules/uORB/topics/mission.h
src/modules/uORB/topics/multirotor_motor_limits.h
src/modules/uORB/uORB.cpp
src/modules/uORB/uORB.h
src/modules/uORB/uORBCommon.hpp
src/modules/uORB/uORBCommunicator.hpp
src/modules/uORB/uORBDevices_nuttx.cpp
src/modules/uORB/uORBDevices_posix.cpp
src/modules/uORB/uORBTest_UnitTest.cpp
unittests/uorb_unittests/uORBCommunicatorMock.hpp

These are only whitespace changes

Code cleanup - Whitespace changes

---

src/platforms/qurt/include/hrt_work.h
src/platforms/qurt/px4_layer/commands_hil.c
src/platforms/qurt/px4_layer/drv_hrt.c
src/platforms/qurt/px4_layer/hrt_work_cancel.c
src/platforms/qurt/px4_layer/main.cpp
src/platforms/qurt/px4_layer/module.mk
src/platforms/qurt/px4_layer/px4_qurt_impl.cpp
src/platforms/qurt/px4_layer/px4_qurt_tasks.cpp
src/platforms/qurt/px4_layer/qurt_stubs.c

Changes to support QuRT intrgration with DSPAL and move from simulator to real HW.

Qurt layer

---

msg/hil_sensor.msg
src/modules/simulator/simulator.cpp
src/modules/simulator/simulator.h
src/modules/simulator/simulator_mavlink.cpp
src/modules/uORB/Subscription.cpp
src/modules/uORB/objects_common.cpp

The simulator was changed to publish the sensor data that is read by the sensors module when the -p flag is passed.

Simulator updated to publish sensor data for sensors module

---

makefiles/posix/config_posix_sitl.mk

SITL: fixed formatting of config_posix_sitl.mk

---

src/platforms/posix/tests/muorb/module.mk
src/platforms/posix/tests/muorb/muorb_test_example.cpp
src/platforms/posix/tests/muorb/muorb_test_example.h
src/platforms/posix/tests/muorb/muorb_test_main.cpp

Unit tests for muorb on posix build. These run on the Krait processor.

POSIX: added muorb tests

---

ROMFS/px4fmu_common/init.d/3032_skywalker_x5
ROMFS/px4fmu_common/init.d/rc.mc_defaults
src/drivers/px4fmu/fmu.cpp
src/modules/px4iofirmware/mixer.cpp
src/modules/systemlib/pwm_limit/pwm_limit.c
src/modules/systemlib/pwm_limit/pwm_limit.h
src/systemcmds/tests/test_mixer.cpp

@DonLakeFlyer @AndreasAntener This is the new PR, WIP.

Safety prearm

---

src/platforms/qurt/tests/muorb/muorb_test_example.cpp
src/platforms/qurt/tests/muorb/muorb_test_example.h

Added usleep test and fixed code format errors.

Updates to QuRT muorb tests

---

src/modules/uavcan/uavcan_main.hpp

Uavcan timing fix

---

src/modules/sensors/sensor_params.c

change from radians to the correct value of degrees

fix description for SENS_BOARD_?_OFF parameters

---

src/modules/land_detector/FixedwingLandDetector.cpp
src/modules/land_detector/FixedwingLandDetector.h
src/modules/land_detector/LandDetector.cpp
src/modules/land_detector/LandDetector.h
src/modules/land_detector/MulticopterLandDetector.cpp
src/modules/land_detector/MulticopterLandDetector.h
src/modules/land_detector/land_detector_params.c

@sjwilks @AndreasAntener This is my next stab at land detection. I've now made it more forgiving the first second after arming, which I hope will allow it to ride through motor spool up.
I've also added the condition that a fixed wing has to be armed to get airborne in the process.

Land detector robustness

---

src/platforms/posix/work_queue/dq_addlast.c
src/platforms/posix/work_queue/dq_rem.c
src/platforms/posix/work_queue/dq_remfirst.c
src/platforms/posix/work_queue/hrt_queue.c
src/platforms/posix/work_queue/hrt_thread.c
src/platforms/posix/work_queue/hrt_work_cancel.c
src/platforms/posix/work_queue/queue.c
src/platforms/posix/work_queue/sq_addafter.c
src/platforms/posix/work_queue/sq_addlast.c
src/platforms/posix/work_queue/sq_remfirst.c
src/platforms/posix/work_queue/work_cancel.c
src/platforms/posix/work_queue/work_lock.c
src/platforms/posix/work_queue/work_queue.c
src/platforms/posix/work_queue/work_thread.c

Changed the code format of the files derived from NuttX to match the code
style of PX4.

POSIX: code format changes

---

src/modules/muorb/adsp/px4muorb.cpp
src/modules/muorb/krait/uORBKraitFastRpcChannel.cpp

Fixed comments and code formatting

muorb: code cleanup

---

src/modules/mavlink/mavlink_messages.cpp

Fix current scaling for mavlink message

---

ROMFS/px4fmu_common/init.d/rc.interface
ROMFS/px4fmu_common/init.d/rcS
src/modules/mavlink/mavlink_parameters.cpp

@sjwilks This should fix #2644.

AUX fix, better boot messaging

---

makefiles/qurt/toolchain_hexagon.mk

Added missing include path for qurt

---

src/modules/ekf_att_pos_estimator/estimator_22states.cpp
src/modules/ekf_att_pos_estimator/estimator_22states.h

@DrTon @priseborough here is the fix for the coning compensation. Bench tested.

Fix coning handling in att_pos EKF. Fixes #2663

---

makefiles/posix/toolchain_native.mk
src/lib/px4_eigen.h
src/systemcmds/tests/test_eigen.cpp

@TSC21 This will fail build tests - how did you build successfully?

Upgrade Eigen version

---

makefiles/posix/toolchain_native.mk
src/lib/px4_eigen.h
src/systemcmds/tests/test_eigen.cpp

Pushed upstream Eigen lib. Compiled ok.

Upgrade Eigen to latest

---

src/modules/vtol_att_control/standard.cpp

@sjwilks one fix for you :) bench tested

Wait until back transition time has passed (standard VTOL)

---

src/modules/ekf_att_pos_estimator/ekf_att_pos_estimator_main.cpp
src/modules/navigator/mission.cpp

This fixes an annoying error message which was triggered when no onboard mission was present.

Mission fixes

---

posix-configs/SITL/init/rc.fixed_wing
posix-configs/SITL/init/rcS
src/drivers/device/vdev_posix.cpp
src/modules/sdlog2/sdlog2.c
src/modules/systemlib/perf_counter.c

@mcharleb @LorenzMeier These changes make the sdlog2 module work for posix. I have not looked yet why the code which I commented out gives a floating point error. I will look into it and see what the problem is. I'm not too sure about the  way the access function is supposed to be used, so review would be nice.

Sdlog2 posix

---

Makefile
cmake/common/px4_base.cmake
src/firmware/nuttx/CMakeLists.txt
src/firmware/qurt/CMakeLists.txt

Also fixed param support for nuttx and qurt

cmake: Updated makefile to show the available build configs

---

.travis.yml

Travis-ci os-x support for cmake-2 PR #2836.

travis-ci add osx

---

CMakeLists.txt
Makefile
cmake/common/px4_base.cmake
cmake/nuttx/bin_to_obj.py
cmake/toolchains/Toolchain-arm-none-eabi.cmake
src/drivers/boards/aerocore/aerocore_spi.c
src/drivers/boards/px4fmu-v1/px4fmu_spi.c
src/drivers/boards/px4fmu-v2/px4fmu_spi.c
src/drivers/hmc5883/hmc5883.h
src/drivers/ms5611/ms5611.h
src/firmware/nuttx/CMakeLists.txt
src/firmware/nuttx/gdbinit.in
src/modules/uORB/uORB.h

This fixes driver problems with unlinked weak functions in the current build by removing the weak attribute.
This is based upon #2855

Removed weak attributes.

---

src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp

This bug lead to the plane flying at high roll angles when landing.

FW landing bug

---

CMakeLists.txt
Makefile
cmake/common/px4_base.cmake
cmake/nuttx/px4_impl_nuttx.cmake
cmake/test/cmake_tester.py
cmake/toolchains/Toolchain-arm-none-eabi.cmake
src/firmware/nuttx/CMakeLists.txt
src/modules/px4iofirmware/CMakeLists.txt

I added the px4io image to the px4 firmware bundle for cmake. Currently the built io firmware doesn't function correctly. The state light remains rapidly blinking and the driver on the fmu fails to communicate with it.

Cmake: Added px4io bin to ROMFS.

---

src/modules/mavlink/mavlink_main.cpp

@LorenzMeier This should fix the problem with the low rc channels message rate.

fix handling of mavlink mode argument

---

CMakeLists.txt
cmake/common/px4_base.cmake
cmake/configs/qurt_eagle_hello.cmake
cmake/configs/qurt_eagle_hil.cmake
cmake/configs/qurt_eagle_muorb.cmake
cmake/configs/qurt_eagle_release.cmake
cmake/configs/qurt_eagle_test.cmake
cmake/configs/qurt_eagle_travis.cmake
cmake/qurt/px4_impl_qurt.cmake
cmake/qurt/qurt_eigen.patch
cmake/toolchains/Toolchain-hexagon-7.2.cmake
cmake/toolchains/Toolchain-hexagon-7.4.cmake
src/drivers/drv_hrt.h
src/firmware/qurt/CMakeLists.txt
src/modules/attitude_estimator_q/CMakeLists.txt
src/modules/commander/CMakeLists.txt
src/modules/ekf_att_pos_estimator/CMakeLists.txt
src/modules/position_estimator_inav/CMakeLists.txt
src/modules/sensors/sensors.cpp
src/platforms/posix/work_queue/hrt_thread.c
src/platforms/qurt/px4_layer/drv_hrt.c
src/systemcmds/mixer/CMakeLists.txt

Cmake 2 qurt unbreakage

---

Vagrantfile

- Added "zip" package needed for build
- Run shell proviosioner as non-privileged (ie. "vagrant") user
Fixes #2907 & #2908

Fixed Vagrant provisioning

---

CMakeLists.txt
Makefile
cmake/ros-CMakeLists.txt

Ros sitl builds about 95% with this. We will have to fix a few minor issues left.

Added support for ros-sitl on cmake-2

---

cmake/ros-CMakeLists.txt

@LorenzMeier @jgoppert this should do it (#2902)

Remove var for relative include directories

---

.gitmodules
CMakeLists.txt
Makefile
cmake/configs/nuttx_px4fmu-v1_default.cmake
cmake/configs/nuttx_px4fmu-v2_default.cmake
cmake/configs/nuttx_px4fmu-v2_simple.cmake
cmake/configs/nuttx_sim_simple.cmake
cmake/configs/posix_eagle_default.cmake
cmake/configs/posix_eagle_hil.cmake
cmake/configs/posix_eagle_release.cmake
cmake/configs/posix_sitl_simple.cmake
cmake/configs/qurt_eagle_hello.cmake
cmake/configs/qurt_eagle_hil.cmake
cmake/configs/qurt_eagle_muorb.cmake
cmake/configs/qurt_eagle_release.cmake
cmake/configs/qurt_eagle_test.cmake
cmake/configs/qurt_eagle_travis.cmake
src/firmware/nuttx/CMakeLists.txt
src/modules/uavcan/CMakeLists.txt

Work in progress. Need to figure out how to pass extra link flags into external project in cmake.

Working on uavcan building.

---

Makefile
cmake/toolchains/Toolchain-arm-none-eabi.cmake
src/firmware/nuttx/CMakeLists.txt

Added ability to debug nuttx with gdb, gdbtui or ddd debuggers.

Added ddd support.

---

CMakeLists.txt
cmake/common/px4_base.cmake
cmake/configs/nuttx_px4fmu-v1_default.cmake
cmake/configs/nuttx_px4fmu-v2_default.cmake
cmake/configs/nuttx_px4fmu-v2_simple.cmake
cmake/configs/nuttx_sim_simple.cmake
cmake/configs/posix_sitl_simple.cmake
cmake/nuttx/px4_impl_nuttx.cmake
src/firmware/nuttx/CMakeLists.txt
src/modules/param/CMakeLists.txt

@LorenzMeier  See if this fixes #2951 for you.

Fixed param dependencies.

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

If I understand correctly, the usage of L1 here means "length one." However, the wording is easily confused with the L1 norm or L1 sphere.

L1 -> unit, L1 easily confused with L1 norm

---

.travis.yml
Makefile
cmake/common/px4_base.cmake
cmake/nuttx/px4_impl_nuttx.cmake
cmake/toolchains/Toolchain-posix-clang-native.cmake
src/drivers/px4flow/i2c_frame.h
src/drivers/px4fmu/CMakeLists.txt
src/drivers/px4io/CMakeLists.txt
src/lib/launchdetection/CatapultLaunchMethod.cpp
src/modules/attitude_estimator_ekf/CMakeLists.txt
src/modules/attitude_estimator_q/CMakeLists.txt
src/modules/commander/CMakeLists.txt
src/modules/ekf_att_pos_estimator/CMakeLists.txt
src/modules/land_detector/CMakeLists.txt
src/modules/mavlink/CMakeLists.txt
src/modules/mc_att_control/CMakeLists.txt
src/modules/mc_att_control_multiplatform/CMakeLists.txt
src/modules/mc_att_control_multiplatform/mc_att_control.cpp
src/modules/mc_att_control_multiplatform/mc_att_control.h
src/modules/mc_pos_control_multiplatform/CMakeLists.txt
src/modules/position_estimator_inav/CMakeLists.txt
src/modules/sdlog2/CMakeLists.txt
src/modules/simulator/CMakeLists.txt
src/modules/systemlib/param/param.c
src/modules/uavcan/CMakeLists.txt
src/platforms/posix/drivers/gyrosim/CMakeLists.txt
src/systemcmds/mixer/CMakeLists.txt
src/systemcmds/param/param.c

I would have liked to enable ninja by default (if available), but it makes the upload target hard to use because it buffers console output until the command finishes.

CMake fixes

---

src/modules/commander/commander.cpp
src/modules/dataman/dataman.c

@DonLakeFlyer This should allow you to test the mode switching title bar effectively and should allow for mixed RC / tablet flight. Needs more testing / vetting, but looks like we're darn close to be able to get outdoors with QGC on tablet!

Sticky modes

---

Tools/px_generate_params.py
Tools/px_romfs_pruner.py
cmake/nuttx/bin_to_obj.py

Let's see what python2/travis does with these changes...

python3 fixes

---

cmake/configs/nuttx_px4fmu-v1_default.cmake
cmake/configs/nuttx_px4fmu-v2_default.cmake
src/firmware/nuttx/CMakeLists.txt

@LorenzMeier I think this should fix it for you.

Removed uavcan from nuttx firmware for v1.

---

src/modules/mavlink/mavlink_mission.cpp

Fix MAV_FRAME_MISSION usage

---

src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/mc_pos_control/mc_pos_control_params.c

Velocity control

---

Tools/px_romfs_pruner.py

Just ignored .DS_Store in the ROMFS pruner. : )

Ignore .DS_Store in the ROMFS pruner.

---

src/modules/position_estimator_inav/CMakeLists.txt
src/modules/position_estimator_inav/position_estimator_inav_main.c
src/modules/position_estimator_inav/position_estimator_inav_params.c
src/modules/position_estimator_inav/position_estimator_inav_params.h

Sonar was replaced by lidar (SENS_EN_LL40LS has to be 1), gyro compensation was added and weights were changed.

several first changes to INAV optical flow estimation

---

src/drivers/pwm_out_sim/pwm_out_sim.cpp

This is some refactoring of the pwm_out_sim driver in order to support VTOL.
Until now we have only used actuator controls 0, this change enables to use all actuator control groups.
Tested in SITL with the IRIS.

support multiple actuator control groups

---

src/platforms/posix/drivers/accelsim/accelsim.cpp

Removed deadcode from accelsim

---

src/modules/commander/commander.cpp
src/modules/commander/commander_params.c

This needs proper testing, but will make tablet flying more fun!

Commander: Disarm after 5 seconds on the ground.

---

src/modules/commander/commander.cpp

run preflight checks after mode switch has changed

---

src/modules/commander/commander.cpp
src/modules/commander/state_machine_helper.cpp

@tumbili This addresses #3048.

Commander: prevent the user from arming the system with USB

---

msg/home_position.msg
src/modules/commander/CMakeLists.txt
src/modules/commander/commander.cpp
src/modules/navigator/rtl.cpp

@DonLakeFlyer This is what you were suggesting.

Home on takeoff

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

Actually there still was something not good with the logic of pos hold. This is now tested in SITL!

fix position hold logic

---

src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_main.h
src/modules/mavlink/mavlink_receiver.cpp

@AndreasAntener This should kill the receive limit we experienced in HIL. Bad rate limiting code.

MAVLink: Do a better job at receive rate limiting

---

src/drivers/device/vdev.cpp

@tumbili This is a 2nd location which needed locking.

Lock vdev devmap

---

Tools/px_romfs_pruner.py

@AndreasAntener Can you cherry pick this commit and run the pruner tool on the mixer file?
I couldn't reproduce the problem anymore after this fix.

use correct Unix line ending character

---

cmake/configs/posix_sitl_simple.cmake
src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/standard.h
src/modules/vtol_att_control/tailsitter.cpp
src/modules/vtol_att_control/tailsitter.h
src/modules/vtol_att_control/tiltrotor.cpp
src/modules/vtol_att_control/tiltrotor.h
src/modules/vtol_att_control/vtol_att_control_main.cpp
src/modules/vtol_att_control/vtol_att_control_main.h
src/modules/vtol_att_control/vtol_type.cpp
src/modules/vtol_att_control/vtol_type.h

VTOL code now also runs on posix.

ported vtol module to posix

---

src/modules/attitude_estimator_q/attitude_estimator_q_main.cpp

This fixes a recent issue with attitude yaw rate publication.

Attitude estimator hot fix.

---

src/lib/mathlib/math/Matrix.hpp

Fixes to matrix for nuttx LPE build.

Matrix update to fix LPE for nuttx

---

src/modules/commander/commander.cpp

Hotfix : fix commander LED reporting

---

src/drivers/px4io/px4io.cpp
src/modules/sdlog2/sdlog2.c
src/modules/sdlog2/sdlog2_messages.h

Handling and logging the RC RSSI value

---

src/drivers/device/vdev.cpp
src/modules/commander/state_machine_helper.cpp
src/modules/simulator/simulator.cpp
src/platforms/posix/drivers/accelsim/accelsim.cpp
src/platforms/posix/drivers/adcsim/adcsim.cpp
src/platforms/posix/drivers/barosim/baro.cpp
src/platforms/posix/drivers/gyrosim/gyrosim.cpp

Updated to latest DriverFramework

---

CMakeLists.txt
cmake/nuttx/px4_impl_nuttx.cmake
cmake/posix/px4_impl_posix.cmake

The DF_TARGET cmake variable needs to be set to (linux, darwin, qurt, nuttx)
The define __DF_LINUX or __DF_QURT needs to be set.
The __DF_DARWIN target is untested

Set flags for building the proper DriverFramework target

---

src/platforms/posix/main.cpp

This supports arrow up and down in the SITL shell.
Makes it really more fun to use, especially in combination with the topic listener.

implemented better shell for SITL

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

Check first commit for non format changes.

Mc pos alt fix

---

src/drivers/mpu9250/mpu9250.cpp

@LorenzMeier 
This add the integration, 
Please look at a diff between the mpu6000 and this file.
Note the different IOCTL for the HW filter in the 9250 and ho that is done in the mpu6000.
How would you like this reconciled?

Added the integration like on mpu6000

---

src/modules/ekf_att_pos_estimator/ekf_att_pos_estimator_main.cpp
src/modules/ekf_att_pos_estimator/estimator_22states.h
src/modules/land_detector/FixedwingLandDetector.cpp
src/modules/land_detector/FixedwingLandDetector.h
src/modules/land_detector/LandDetector.cpp
src/modules/land_detector/land_detector_params.c

@tumbili This detects takeoffs with zero latency and should help with auto-launching planes considerably.

Takeoff detect

---

ROMFS/px4fmu_common/mixers/quad_h.main.mix
src/modules/systemlib/mixer/mixer_multirotor.cpp
src/modules/systemlib/mixer/multi_tables.py

Mixer for new frame type H-quad

Mixer for H configuration

---

src/modules/mavlink/mavlink_receiver.cpp
src/modules/position_estimator_inav/position_estimator_inav_main.c
src/modules/sensors/sensors.cpp

Driver framework

---

msg/vehicle_gps_position.msg
src/drivers/gps/ubx.cpp

Modification of the GPS message, add height above the ellipsoid info.

GPS: Add height above the ellipsoid info

---

src/modules/commander/commander.cpp
src/modules/mavlink/mavlink_receiver.cpp

Updated variant of #3275
HIL tested

Sub mode support

---

src/drivers/device/vdev_posix.cpp
src/firmware/posix/CMakeLists.txt
src/lib/mathlib/math/filter/LowPassFilter2p.cpp
src/modules/mavlink/mavlink_receiver.cpp

@LorenzMeier please double check my PX4_ISFINITE changes and va_arg type change. I'm not sure if the va_arg change breaks it for others.

Make posix sitl work on my mac

---

msg/vehicle_global_position.msg
src/modules/ekf_att_pos_estimator/ekf_att_pos_estimator_main.cpp
src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp
src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_messages.cpp
src/modules/position_estimator_inav/position_estimator_inav_main.cpp

@LorenzMeier I implemented the new altitude message, primary interest is @tumbili 's terrain altitude :). Current state is working, but I don't know what should be used for the monotonic altitude. Any hints?

WIP: Altitude message

---

.gitignore

https://www.gnu.org/software/global/

ignore gtags/gnu global output files

---

cmake/configs/nuttx_px4fmu-v1_default.cmake
msg/vehicle_global_position.msg
msg/vehicle_gps_position.msg
msg/vehicle_local_position.msg
src/modules/ekf2/ekf2_main.cpp

Publishes missing local and global vehicle position data that was preventing entry into POSCTL mode
Fix bug preventing use of ekf2 with a PX4-v1 board

Fix ekf2 bugs

---

posix-configs/SITL/init/rcS_gazebo_tailsitter
src/drivers/device/vdev_posix.cpp
src/modules/vtol_att_control/tailsitter.cpp

This allows tailsitter sim on OS X. Still pending VDEV bugfix.

VTOL fixes for SITL

---

src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_messages.cpp

This fixes some incorrect limitations that were present on POSIX UARTs.

MAVLink app: Enable network and serial on POSIX

---

src/drivers/px4fmu/fmu.cpp
src/modules/systemlib/pwm_limit/pwm_limit.h

fmu was asserting armed input to pwm_limit_calc prematurely

Fmu pwm limit

---

src/modules/controllib/block/BlockParam.cpp
src/modules/controllib/block/BlockParam.hpp
src/modules/ekf2/ekf2_main.cpp
src/modules/ekf2/ekf2_params.c

@LorenzMeier Can you have a quick look and say if this is what you meant?

Ekf2 blockparam

---

ROMFS/px4fmu_common/init.d/13003_quad_tailsitter
ROMFS/px4fmu_common/init.d/13004_quad+_tailsitter
ROMFS/px4fmu_common/init.d/2106_albatross
Tools/px4airframes/xmlout.py

@DonLakeFlyer This implements the new icons.

Airframe icons

---

src/modules/navigator/mission.cpp
src/modules/navigator/mission_feasibility_checker.cpp
src/modules/navigator/mission_feasibility_checker.h

make sure that the relative altitude of the takeoff waypoint is
at least one meter higher than the acceptance radius of the waypoint.
This makes sure that the takeoff waypoint is not reached before the vehicle
is at least one meter in the air.

multirotor mission feasibility checks:

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

@tumbili FYI, for tomorrow to check if thrust limiting is needed or not

landing without thrust limiting

---

msg/ekf2_innovations.msg
src/modules/ekf2/ekf2_main.cpp
src/modules/sdlog2/sdlog2.c
src/modules/sdlog2/sdlog2_messages.h
src/modules/uORB/objects_common.cpp

@priseborough This is only missing the actual logging of the innovations and innovation variances. I will finish this today.

Ekf2 logging

---

src/modules/navigator/mission.cpp
src/modules/navigator/mission_block.cpp

@tumbili can you quickly verify the revert and pull this?
I'm going to reimplement this in https://github.com/PX4/Firmware/pull/3598

RTL was broken by a recent change, revert

---

Makefile
Tools/check_submodules.sh
nuttx-patches/nsh_parse.patch

Add new NuttX patch to address issue #2434. Also included a merge from build system on master to avoid obstackle incountered when building (nuttx source edits would get discarded on clean builds).

Nuttx next cmake

---

src/modules/mavlink/mavlink_mission.cpp
src/modules/navigator/navigation.h

Fixes https://github.com/PX4/Firmware/issues/3658

Mavlink read back frame fix

---

src/modules/navigator/mission.cpp
src/modules/navigator/mission.h
src/modules/navigator/mission_feasibility_checker.cpp
src/modules/navigator/mission_feasibility_checker.h
src/modules/navigator/navigation.h

- Fixes https://github.com/PX4/Firmware/issues/3656
- Fixes https://github.com/PX4/Firmware/issues/3648
- Corrected spelling on method

Mission feasibility fixes

---

src/modules/ekf2/ekf2_main.cpp
src/modules/sdlog2/sdlog2.c

Not merging this until a corner case in EKF2 has been resolved, but then it should be good to go.

jMAVSim: Enable Zurich as location, enable mag decl lookup

---

src/modules/navigator/mission_block.cpp

fixes https://github.com/PX4/Firmware/issues/3729
only transition to MC when not MC

Fix for transition failsafe

---

msg/fw_virtual_attitude_setpoint.msg
msg/fw_virtual_rates_setpoint.msg
msg/mc_virtual_attitude_setpoint.msg
msg/mc_virtual_rates_setpoint.msg
msg/position_setpoint.msg
msg/vehicle_attitude_setpoint.msg
msg/vehicle_rates_setpoint.msg
src/modules/mc_att_control/mc_att_control_main.cpp
src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/navigator/mission_block.cpp
src/modules/navigator/mission_block.h
src/modules/vtol_att_control/vtol_att_control_main.h
src/modules/vtol_att_control/vtol_att_control_params.c
src/modules/vtol_att_control/vtol_type.h

Fixes https://github.com/PX4/Firmware/issues/3679
@sanderux As discussed I cleaned up the history so that we only remain with three commits.
The diff to the old branch is zero so everything should be inside. Will give this a test in SITL and Ada can maybe test fly it today.
@AndreasAntener  FYI

Vtol weathervane cleaned up history

---

src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/mc_pos_control/mc_pos_control_params.c

Rebased, waiting for tests to pass.

Two point curve

---

.travis.yml

travis-ci only build sitl on OSX

---

ROMFS/px4fmu_common/init.d/13008_QuadRanger

This gives the quadranger fully stable flight and transition:
http://logs.uaventure.com/view/djVcLjJZChq3QsUmoBsrWh#Actuators_PLOT

New params for quadranger

---

src/modules/sdlog2/sdlog2.c
src/modules/sdlog2/sdlog2_messages.h

Add VTOL states to sdlog
SITL tested

Add vtol states to sdlog2

---

ROMFS/px4fmu_common/init.d/rc.vtol_defaults

Fixes https://github.com/PX4/Firmware/issues/3864

VTOL: Change MPC_ACC_HOR_MAX default to 2.0

---

ROMFS/px4fmu_common/init.d/rc.logging
src/modules/sdlog2/sdlog2.c

@kd0aij This should fix your logging issues.

Logging fix

---

src/drivers/px4fmu/fmu.cpp

@tumbili Could you also test this with and without a safety switch? Both cases are working on my S250 racing quad.

V4 safety fix

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

-when switching into vel control mode (xy) choose vel sp such that attitude
setpoint is continuous

mc pos control:

---

src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/standard.h
src/modules/vtol_att_control/vtol_att_control_params.c

Fixes https://github.com/PX4/Firmware/issues/3850
Minimum transition time for front transition for standard vtol

VTOL Front transition minimum time

---

cmake/configs/nuttx_px4fmu-v2_lpe.cmake
src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp
src/modules/local_position_estimator/BlockLocalPositionEstimator.hpp
src/modules/local_position_estimator/params.c

The main difference is that this treats flow as a position estimate in order to reduce long-term drift. It also has a high pass on the flow gyro which effectively removes gyro bias from the flow sensor without having to estimate it directly.
Flight test video, pretty good, mild wind, 5-10 mph, very cold :-/:
https://www.youtube.com/watch?v=0PqPsRMFyhw
Flight Logs:
http://logs.uaventure.com/view/xWtaFRQioDTwiE8j6VDjsG
http://logs.uaventure.com/view/ZPHp2jaXUUbLXZCmzzxGmK

improved position based flow correction for lpe

---

cmake/configs/posix_eagle_release.cmake
posix-configs/eagle/flight/mainapp-flight.config
src/platforms/posix/px4_layer/CMakeLists.txt
src/platforms/posix/px4_layer/px4_posix_impl.cpp
src/platforms/posix/px4_layer/shmem_posix.c
src/platforms/qurt/px4_layer/shmem_qurt.c

This PR is to track the changes to resolve #3956.
Currently it should run even though the locking itself still fails.

Fix shmem locking

---

.travis.yml
Makefile
Tools/check_submodules.sh

@davids5 This also removed a git clean step in the NuttX dir. Fixes https://github.com/PX4/Firmware/issues/3979

Build fixes

---

src/modules/commander/mag_calibration.cpp

This change is an intermediate fix to allow use of an internal mag with large offsets.

change large mag offset from error to warning

---

ROMFS/px4fmu_common/init.d/rc.sensors
src/drivers/px4fmu/fmu.cpp

I2c 100khz init

---

src/modules/mavlink/mavlink_main.cpp

Nuttx next cmake update

---

src/platforms/posix/drivers/df_bmp280_wrapper/df_bmp280_wrapper.cpp

Previously we only published pressure which wasn't enough for the position
estimator.

df_bmp280_wrapper: hack to publish altitude

---

src/modules/navigator/mission_block.cpp

Ignoring requested altitude from target for now.

fixing possible safety issue with altitude

---

cmake/common/px4_base.cmake

This is a follow up to #4153.
It resolved the 100% CPU issue on Snapdragon in the proper way, and without breaking the build on Mac.

Fix CPU usage on Snapdragon take 2

---

src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_main.h

This should fix #4141.
Tested on Linux SITL and on the Snapdragon. Needs cross testing on Mac again.

Broadcast on Mac OS X

---

src/modules/navigator/mission_block.cpp

Fixes https://github.com/PX4/Firmware/issues/4193

Only set virtual waypoint for VTOL_TAKEOFF. Fixes #4193

---

src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/standard.h
src/modules/vtol_att_control/standard_params.c
src/modules/vtol_att_control/vtol_type.h

first attempt at standard vtol using pusher for forward flight in MC mode

WIP: vtol pusher for mc cruise

---

src/drivers/drv_hrt.h

drv_hrt: fix comment

---

Tools/generate_listener.py

listener command was buggy, so that less messages were output than specified. Additionally add a timeout of 2 seconds (abort when no messages are received within 2s).

Fix listener cmd

---

src/modules/ekf2/ekf2_main.cpp

This is the branch needed if you want to try out ekf2 on fixed wing.
It supports wind estimation using an airspeed sensor.

WIP: Ekf2 airspeed

---

src/firmware/posix/CMakeLists.txt
src/firmware/qurt/CMakeLists.txt

Fixes #4300.
Tested on Snapdragon.

posix/qurt cmake: fix eagle upload

---

src/modules/commander/commander.cpp
src/modules/navigator/loiter.cpp
src/modules/navigator/loiter.h
src/modules/navigator/navigator.h
src/modules/navigator/navigator_main.cpp

@dagar @DonLakeFlyer This implements the reposition command. Now I need QGC support / implementing it in order to finish the testing. Pretty close though and will go into 1.3.0.

Support for reposition MAVLink command

---

src/modules/ekf2/ekf2_main.cpp

Need to test on Ubuntu 16.04 `make posix`.
Should fix #4371.

ekf2: replace `!isnan` with `PX4_ISFINITE`

---

src/modules/sdlog2/sdlog2.c

- either sensor combined or the replay topic where copied into
the union buffer but at times the memory was overwritten by other
topics which updated below
- this change makes sure that the two topics are copied into the union
buffer at the correct location in the code

fix bug in the logging app:

---

cmake/configs/qurt_eagle_default.cmake
posix-configs/eagle/flight/px4.config
src/platforms/posix/drivers/df_isl29501_wrapper/CMakeLists.txt
src/platforms/posix/drivers/df_isl29501_wrapper/df_isl29501_wrapper.cpp
src/platforms/posix/drivers/df_isl_wrapper/CMakeLists.txt
src/platforms/posix/drivers/df_isl_wrapper/df_isl_wrapper.cpp

This is #4375 with further style fixes and some more renaming.
Good to merge if travis is happy.

Intersil wrapper continued

---

src/modules/land_detector/LandDetector.cpp

land_detector: fix wrong astyle formatting

---

src/modules/sensors/sensors.cpp

Sorry my bad. I should have not have merged this change without testing earlier.

sensors: the ifdef logic was inverted

---

src/modules/fw_pos_control_l1/CMakeLists.txt
src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp
src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c
src/modules/fw_pos_control_l1/landingslope.cpp
src/modules/fw_pos_control_l1/landingslope.h

This includes https://github.com/PX4/Firmware/pull/4406 and on top of that strips the mtecs implementation. @dagar Could you review this?

Disable mTECS, but retain code for now

---

ROMFS/px4fmu_common/init.d/13009_vtol_spt_ranger

Here's a video of an autonomous flight with the Ranger VTOL: https://www.youtube.com/watch?v=4pTxS9gAY08

added Sparkletech Ranger Quadplane config

---

ROMFS/px4fmu_common/init.d/rc.logging
msg/templates/uorb/msg.cpp.template
msg/templates/uorb/msg.h.template
src/modules/commander/commander.cpp
src/modules/logger/log_writer.cpp
src/modules/logger/log_writer.h
src/modules/logger/logger.cpp
src/modules/logger/logger.h
src/modules/uORB/uORB.h

@dagar I just rebased my working branch on newLogger2; 
commits 	0fd22ca and 	1c98ca6 might be useful to you since they fix problems I was encountering with the logger

[WIP] enhancements and bugfixes for new logger

---

src/modules/ekf_att_pos_estimator/estimator_22states.cpp
src/modules/position_estimator_inav/position_estimator_inav_main.cpp
src/platforms/posix/drivers/airspeedsim/meas_airspeed_sim.cpp
src/platforms/posix/px4_layer/px4_posix_tasks.cpp

Some fixes, found with Clang static analysis.

Memory leaks & uninitialized value fixes

---

Makefile
cmake/configs/posix_eagle_default.cmake
cmake/configs/posix_excelsior_default.cmake
cmake/configs/posix_sdflight_default.cmake
cmake/configs/qurt_eagle_default.cmake
cmake/configs/qurt_excelsior_default.cmake
cmake/configs/qurt_sdflight_default.cmake
cmake/posix/px4_impl_posix.cmake
src/firmware/posix/CMakeLists.txt
src/lib/version/version.h
src/platforms/posix/px4_layer/drv_hrt.c
src/platforms/shmem.h

This PR contains @jywilson's changes (#4416) rebased on master.
Also some comments are added and the re-use pattern suggested for POSIX is used for the QURT build as well.
Needs testing on Snapdragon.

Excelsior Config Changes (rebased)

---

cmake/configs/nuttx_px4fmu-v2_default.cmake

Remove LPE and restore other drivers. 
Fingers crossed it fits

Fit In Flash remove LPE

---

Tools/sdlog2/geotagging.py

This PR adds two enhancements to the geotagging post-processing script:
* Altitude is also written to the EXIF tag.
* Image list is sorted alphabetically before tagging. This enhances the robustness to picture lists read in wrong order.

Geotagging enhancements

---

src/platforms/posix/px4_layer/px4_posix_tasks.cpp
src/platforms/qurt/px4_layer/px4_qurt_tasks.cpp

@julianoes can you test if this works on Snapdragon?

Memory leak & some cleanup

---

src/drivers/camera_trigger/camera_trigger_params.c
src/drivers/mkblctrl/mkblctrl_params.c
src/drivers/px4io/px4io_params.c
src/lib/launchdetection/launchdetection_params.c
src/lib/runway_takeoff/runway_takeoff_params.c
src/modules/attitude_estimator_ekf/attitude_estimator_ekf_params.c
src/modules/attitude_estimator_q/attitude_estimator_q_params.c
src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c
src/modules/fw_pos_control_l1/mtecs/mTecs_params.c
src/modules/local_position_estimator/params.c
src/modules/navigator/mission_params.c
src/modules/position_estimator_inav/position_estimator_inav_params.cpp
src/modules/sdlog2/params.c
src/modules/sdlog2/sdlog2.c
src/modules/sensors/sensor_params.c
src/modules/systemlib/system_params.c
src/modules/uavcan/uavcan_params.c
src/modules/vtol_att_control/vtol_att_control_params.c

Param metadata cleanup as discussed here. https://github.com/mavlink/qgroundcontrol/issues/3012#issuecomment-219168089

Param metadata

---

src/modules/ekf2/ekf2_params.c

Required to use https://github.com/PX4/ecl/pull/148

EKF2 output predictor update

---

integrationtests/run_tests.bash
integrationtests/setup_gazebo_ros.bash
launch/mavros_posix_sitl.launch
launch/posix_sitl.launch

Fixes https://github.com/PX4/Firmware/issues/4578

Align MAVROS env with current SITL build

---

src/modules/navigator/follow_target.cpp
src/modules/navigator/follow_target.h

Testing completed ready to merge.  Refactor of follow target module for readability and complexity.  Fixed yaw smoothing.

more follow target updates

---

src/modules/uavcan/uavcan_main.cpp

See https://github.com/PX4/Firmware/issues/4677

STM32 CAN driver moved from .data to heap; partially resolves #4677

---

cmake/configs/qurt_sdflight_default.cmake
src/modules/systemlib/print_load_posix.c

Fixes two compilaton errors on Snapdragon, fixes #4692.
Can be merged as soon as travis is ok.

Snapdragon: Fix merge

---

src/modules/commander/commander.cpp
src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_main.h
src/modules/mavlink/mavlink_mission.cpp

avoid spamming the console when disconnecting the Network or bcast addr not found

mavlink udp on posix: avoid spamming the console

---

src/systemcmds/param/param.c

param : fix shell handler usage string

---

cmake/toolchains/Toolchain-arm-linux-gnueabihf-raspbian.cmake
cmake/toolchains/Toolchain-native.cmake

Let's cut down on the dependencies.
Don't merge yet, more to come.

cmake: POSIX/RPi build don't need patch/genromfs

---

src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp

Remove isfinite checks to make lpe always publish est status.

Make LPE est always log.

---

src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp
src/modules/local_position_estimator/BlockLocalPositionEstimator.hpp
src/modules/local_position_estimator/params.c
src/modules/local_position_estimator/sensors/baro.cpp
src/modules/local_position_estimator/sensors/gps.cpp

This adds checks for fix type and EPV to GPS for LPE.

Add more GPS checks for LPE

---

Makefile
posix-configs/SITL/init/rcS_gazebo_solo
src/firmware/posix/CMakeLists.txt

Running this:
```
make posix gazebo_solo
```
Results now in:

Add Solo sim model

---

msg/ekf2_replay.msg
src/modules/ekf2/ekf2_main.cpp
src/modules/ekf2/ekf2_params.c
src/modules/ekf2_replay/ekf2_replay_main.cpp
src/modules/sdlog2/sdlog2.c
src/modules/sdlog2/sdlog2_messages.h

Replaces #4755\
This is now properly rebased and can go it as soon as checks pass.

Pr airspeed fusion

---

.travis.yml
Makefile
unittests/CMakeLists.txt

travis-ci docker

---

src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp
src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c

-fixes #4745
I'm going to do a more thorough check of param usage, but here's a quick fix for issue.

fw_pos_control_l1 fix FW_LND_FLALT usage

---

src/modules/commander/commander.cpp

fix #4804 Not all commands are being replied with a COMMAND_ACK

fill missing command ack.

---

src/modules/ekf_att_pos_estimator/AttitudePositionEstimatorEKF.h
src/modules/ekf_att_pos_estimator/ekf_att_pos_estimator_main.cpp
src/modules/land_detector/LandDetector.cpp

Thanks to @bkueng for teaching how to bisect.
@LorenzMeier FYI

Pr master fix

---

.travis.yml

Combining the arguments doesn't seem to work.

travis-ci fix full unshallow clone for git ver

---

ROMFS/px4fmu_common/init.d/4002_qavr5

I just tuned the gains for the QAV-R, flies well.
http://logs.uaventure.com/view/DHwMiu8HtmWzTwuMoXy77a

Added QAV-R (raceblade) 5".

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

@tumbili probably resolves #4904, would be cool if you can double check
I can easily destabilize SITL on my older branch without this, but master SITL seems to be pretty resilient.. (that deltaquad is a magical contraption ;))

do not modify attitude setpoint in velocity controlled mode

---

cmake/configs/nuttx_px4fmu-v2_default.cmake
cmake/configs/nuttx_px4fmu-v2_ekf2.cmake
cmake/configs/nuttx_px4fmu-v2_test.cmake
src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_messages.cpp

Still needs to be tested. The wind_estimate orb topic is empty in Gazebo plane.
- closes #4678
QGC: https://github.com/mavlink/qgroundcontrol/issues/3033

mavlink publish WIND_COV

---

src/modules/navigator/mission.cpp
src/modules/navigator/mission_block.cpp

VTOL land was being forced for FW.

FW vtol landing always forced

---

src/modules/navigator/navigator_main.cpp

@vooon This will work safely with fixed and unfixed QGC versions.

Takeoff: Fix coordinate scaling

---

Tools/check_code_style.sh

Fixes https://github.com/PX4/Firmware/issues/4943

check astyle don't paginate output

---

src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp
src/modules/local_position_estimator/BlockLocalPositionEstimator.hpp
src/modules/local_position_estimator/params.c

This was a request by @mhkabir since indoor 2m default was pretty large threshold.

Made LPE var pub threshold a parameter.

---

src/systemcmds/motor_ramp/motor_ramp.cpp

(side note @LorenzMeier , I used the square wave here to test the camera trigger intervals. We could add something similar to the camera trigger test function in your PR)

motor_ramp: added square wave mode and PWM max parameter

---

src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp
src/modules/local_position_estimator/BlockLocalPositionEstimator.hpp

Taking the difference of two smoothed signals isn't necessarily smooth, so this fixes that. Going to flight test now and then merge if it goes well.
@ecmnet This should help address #4878

Added agl smoothing to LPE.

---

src/drivers/camera_trigger/camera_trigger.cpp
src/drivers/camera_trigger/camera_trigger_params.c
src/drivers/camera_trigger/interfaces/src/camera_interface.h
src/drivers/camera_trigger/interfaces/src/pwm.cpp
src/drivers/camera_trigger/interfaces/src/pwm.h

* Correct initialization of trigger pins
* Keep alive functionality specifically for Sony QX1 camera
Camera turn on/off is not enabled yet. Functionality is unclear right now. Will follow in a separate PR.

Camera trigger update

---

src/drivers/camera_trigger/camera_trigger.cpp

Minor, but fixes the publishing of the trigger stamps

Fixing trigger publishing

---

src/modules/commander/accelerometer_calibration.cpp
src/modules/commander/gyro_calibration.cpp
src/modules/commander/mag_calibration.cpp

Allows for calibration of sensors from GCS.

Adds Calibration Support for RPi2 and Navio2

---

src/modules/mavlink/mavlink_main.cpp

Streams ordered same way in all modes.
Just for easier readability when comparing different modes.

Refactored Mavlink stream configuration

---

src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/mavlink_parameters.cpp
src/modules/mavlink/mavlink_parameters.h
src/modules/mavlink/mavlink_stream.h

@DonLakeFlyer Can you try this branch for RC cal? Things should flow in now a lot faster.

MAVLink app: Fix rate handling

---

msg/att_pos_mocap.msg
src/modules/local_position_estimator/sensors/mocap.cpp
src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/mavlink_receiver.cpp

This is analogous to the latest changes in vision timestamps.

Mocap timestamp cleanup

---

src/drivers/px4io/px4io.cpp
src/modules/commander/rc_calibration.cpp
src/modules/fw_att_control/fw_att_control_main.cpp
src/modules/fw_att_control/fw_att_control_params.c
src/modules/px4iofirmware/mixer.cpp
src/modules/px4iofirmware/protocol.h
src/modules/px4iofirmware/px4io.h
src/modules/px4iofirmware/registers.c

@kd0aij I added a scale parameters to adjust the throws in full manual for fixed wings.
Do you have any comments on that?
Fixes: #4598

Pr man sens

---

msg/CMakeLists.txt
msg/encoders.msg
src/modules/sdlog2/sdlog2.c
src/modules/uORB/Publication.cpp
src/modules/uORB/Subscription.cpp

encoders.msg: remove this topic

---

src/drivers/mpu6000/mpu6000.cpp

@LorenzMeier 
Usage message was wrong

Minor fix usage

---

src/modules/commander/commander.cpp
src/modules/commander/state_machine_helper.cpp

needed for the new logger
@julianoes

commander: write timestamp of commander_state topic on init and state change

---

src/drivers/boards/tap-v1/board_config.h
src/drivers/boards/tap-v1/tap_init.c

@LorenzMeier 
Minor - ensure IO is set properly as init.

TAP:More IO Init

---

src/modules/sensors/sensors.cpp

This is a follow-up to 399d4ef833cd72ac0, #5047
Tested on pixhawk, gyro properly fails over from 0 to 1 with the command `config /dev/gyro0 block` and then `sensors` polls on the second gyro.

sensors: poll on best-voted gyro

---

src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp
src/modules/local_position_estimator/BlockLocalPositionEstimator.hpp
src/modules/local_position_estimator/sensors/flow.cpp
src/modules/local_position_estimator/sensors/gps.cpp
src/modules/local_position_estimator/sensors/lidar.cpp
src/modules/local_position_estimator/sensors/sonar.cpp
src/modules/uORB/Publication.cpp

Added innovation logging to LPE.

---

CMakeLists.txt
Makefile
posix-configs/SITL/init/rcS_lpe_gazebo_iris
posix-configs/SITL/init/rcS_lpe_gazebo_iris_opt_flow
posix-configs/SITL/init/rcS_lpe_jmavsim_iris
src/firmware/posix/CMakeLists.txt
src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp
src/modules/local_position_estimator/sensors/flow.cpp
src/modules/simulator/simulator.h
src/modules/simulator/simulator_mavlink.cpp

This fixes errors with optical flow sim and has been tested in gazebo to work well with LPE estimator. It also adds install targets for mainapp in posix.

Optical flow simulator and install cleanup.

---

src/drivers/gps/gps.cpp

It currently gets cut off on mini-dm, split it into multiple lines so all of it comes through.

Wrap help line to fit through mini-dm.

---

src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp

This is a fix for fixed wing flights in high wind. I've tested this in the field in normal conditions, and in HIL with high winds, but so far not in the field with high winds.

FW navigation in high winds

---

ROMFS/px4fmu_common/init.d/rcS
src/modules/sensors/sensor_params.c

Added mb12xx sensor enable.

---

src/modules/land_detector/LandDetector.cpp

land_detector: remove leftover printf

---

src/modules/systemlib/param/param.c

Since the FRAM and the baro are on the same bus on the Pixracer, we
currently need to lock down everything (instead of just this SPI bus)
for the time when the params are written.
Therefore, we need to keep this locking as short as possible.
This change makes the locking even shorter by moving all param_get and
param_name and param_size calls out of the lock.
This resolves #5170 for me.
@LorenzMeier please review.

param: lock the bus as short as possible

---

src/modules/ekf2/ekf2_main.cpp

1. Don't push bad values from lidar to EKF2
2. Report terrain altitude
http://discuss.px4.io/t/v1-4-1-release-testing/759/6

Don't push bad values from lidar to EKF2 and report terrain altitude

---

src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/standard_params.c
src/modules/vtol_att_control/vtol_att_control_main.cpp
src/modules/vtol_att_control/vtol_att_control_main.h
src/modules/vtol_att_control/vtol_att_control_params.c
src/modules/vtol_att_control/vtol_type.cpp
src/modules/vtol_att_control/vtol_type.h

Quadchute cleanup and instant back transition

---

src/modules/vtol_att_control/standard.cpp

Probably got lost in translation..

use thrust scale parameter for vtol pusher support

---

src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp

As described in https://github.com/PX4/Firmware/issues/4878

Remove LPOS.Z reset

---

src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp
src/modules/local_position_estimator/sensors/baro.cpp
src/modules/local_position_estimator/sensors/flow.cpp
src/modules/local_position_estimator/sensors/gps.cpp
src/modules/local_position_estimator/sensors/sonar.cpp
src/modules/local_position_estimator/sensors/vision.cpp

@julianoes Can you review? This should fix all remaining LPE output challenges.

Remove on arming reset, be less verbose in normal conditions output

---

src/modules/vtol_att_control/vtol_att_control_main.cpp

replaces https://github.com/PX4/Firmware/pull/5251

fix VTOL vehicle_status timestamp

---

src/drivers/hott/hott_telemetry/hott_telemetry.cpp
src/drivers/hott/messages.h

Ua venture hottupdate

---

src/drivers/gps/gps.cpp

fix fake gps bugs

---

msg/cpuload.msg
src/modules/commander/commander.cpp
src/modules/load_mon/load_mon.cpp

This adds a monitor for memory usage and enables warning leds if memory usage or CPU load become an issue.

Memory warning

---

src/modules/mavlink/mavlink_log_handler.cpp

Adding support for new (different) log file extension for log download.
For now it will look for both new and old extensions as there could be old log files on the SD card.

Support for new log file extension.

---

ROMFS/px4fmu_common/init.d/4009_qav250

this adds the new TPA (PID gain scheduling) parameters

Update 4009_qav250 config

---

ROMFS/px4fmu_common/init.d/4050_generic_250

this adds the new TPA (PID gain scheduling) parameters
and updates the pitchrate gains to match those I'm testing with on an S250AQ

Update 4050_generic_250 config

---

ROMFS/px4fmu_common/init.d/rcS
src/modules/sensors/sensor_params.c

Added configuration parameter for TeraRanger One rangefinder.

Configuration parameter for TeraRanger One

---

src/modules/local_position_estimator/sensors/baro.cpp
src/modules/local_position_estimator/sensors/gps.cpp

LPE alt init now allows baro only init without GPS w/o changing flag.

---

src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp
src/modules/local_position_estimator/BlockLocalPositionEstimator.hpp
src/modules/local_position_estimator/params.c
src/modules/local_position_estimator/sensors/flow.cpp
src/modules/local_position_estimator/sensors/gps.cpp
src/modules/mavlink/mavlink_messages.cpp

flight test log:
http://logs.uaventure.com/view/e9pUhK8nVJXCgHa9M4pxm6

Improvements to lpe for flow and gps interaction.

---

src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_main.h
src/modules/mavlink/mavlink_orb_subscription.cpp
src/modules/mavlink/mavlink_orb_subscription.h
src/modules/mavlink/mavlink_params.c
src/modules/mavlink/mavlink_receiver.cpp

Switch to MAVLink 2 on reception.

Mavlink2 mode

---

integrationtests/run_tests.bash

SITL CI: gracefully fail tests early

---

src/modules/mavlink/mavlink_ftp.cpp
src/modules/mavlink/mavlink_log_handler.cpp

readdir_r is deprecated since glibc version 2.24 and glibc manual
recomends usage of readdir instead of readdir_r.
Replacing readdir_r by readdir will also not be a problem for Nuttx,
because readdir_r is using readdir and filling parameters with the
return information.

Use readdir instead of readdir_r

---

src/platforms/posix/px4_layer/px4_posix_tasks.cpp

Here is a commit that fixes my core dump.

Increase stack space on posix 64bit architectures.

---

src/examples/px4_simple_app/px4_simple_app.c
src/platforms/posix/main.cpp

and let it default to CWD
This makes sure we can still use the previous commands for RPi
@julianoes

PX4: make <data_directory> an optional argument

---

src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp

Before we weren't actually saturating accel bias, this fixes that.

Fix for lpe accel bias saturation.

---

Makefile

On second thought, using % just isn't correct. When a make
target looks like:
foo% bar%:
...
Then that implies that it will build BOTH foo% and bar% whenever
that rule is triggered (by either) for any value of the pattern %.
Clearly that is not what we want / intend.
So, this commit goes back to using config targets without a % in it
by generating a full list of them.
It also turns sitl_deprecation into a Hidden Target.
Finally, now that we have those target lists anyway, I added
a 'help' and 'list_config_targets' targets that print the
available targets.

Fix the multi- target targets (#5489)

---

Makefile

make check_format also check git whitespace

---

src/drivers/lps25h/CMakeLists.txt
src/modules/syslink/syslink_main.cpp

Fix wrong timestamp field, from a recent change (d297d31)

Fix crazyflie build

---

Tools/upload.sh
cmake/common/px4_base.cmake

CF2: Linux USB uploading fix

---

src/modules/controllib_test/controllib_test_main.cpp

Just something I've come across.

Fix filename in comments

---

src/modules/commander/PreflightCheck.cpp
src/modules/commander/PreflightCheck.h
src/modules/commander/commander.cpp
src/modules/commander/state_machine_helper.cpp
src/modules/systemlib/rc_check.c
src/modules/systemlib/rc_check.h

Transition switch parameter enforcement

VTOL transition switch parameter checking

---

src/modules/navigator/geofence.cpp
src/modules/navigator/geofence_params.c

- closes https://github.com/PX4/Firmware/issues/5430

Geofence defaults

---

.travis.yml

travis-ci fix s3 deploy

---

circle.yml

Fix for build in https://github.com/PX4/Firmware/pull/5537

circleci better submodules update

---

posix-configs/rpi/px4.config
src/drivers/drv_gps.h
src/drivers/gps/gps.cpp
src/drivers/navio_gpio/navio_gpio.cpp

continuation of #5440 
Tested on Navio2, gps driver works (I did not get a gps signal though, because I tested indoors)

Navio: add SPI GPS continued

---

src/drivers/navio_sysfs_pwm_out/navio_sysfs_pwm_out.cpp
src/drivers/navio_sysfs_rc_in/navio_sysfs_rc_in.cpp

Navio drivers: avoid dynamic allocations

---

src/modules/mavlink/mavlink_main.cpp

output which protocol version & transport layer is used

mavlink: extend status output

---

ROMFS/px4fmu_common/init.d/rcS
src/modules/systemlib/system_params.c

As per https://github.com/PX4/Firmware/issues/5611

Adding support for 19200 and 38400 baud TELEM2

---

Makefile

Makefile error preventing px4fmu-v4_default build

---

eclipse.cproject
eclipse.project

- properly index ECL and generated uORB

eclipse project file updates

---

src/modules/commander/commander.cpp
src/modules/commander/state_machine_helper.cpp
src/modules/commander/state_machine_helper.h

I wasn't able to fly with vision only in auto mission without this patch.
Also adds some strings to tell you why it is failsafe mode.

Fix gps circuit breaker logic in state machine.

---

msg/estimator_status.msg

Fixes an error and adds missing bit positions to the control_mode_flags message documentation

Update estimator_status uORB message documentation

---

msg/vehicle_attitude_setpoint.msg
src/examples/mc_pos_control_multiplatform/mc_pos_control.cpp
src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/mavlink_receiver.cpp
src/modules/mc_att_control/mc_att_control_main.cpp
src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/tailsitter.cpp
src/platforms/ros/nodes/attitude_estimator/attitude_estimator.cpp

Rebase on master once `topic_cleanup` is in. This removes additionally the attitude setpoint rotation matrix.

Topic cleanup continued

---

Tools/px_uploader.py

This mainly fixes an exception that happened sometimes.

Small fix to px_uploader.py

---

.travis.yml
circle.yml

travis-ci GCC 4.8 -> 4.9
circleci GCC 4.9 -> 5.4

travis-ci, circleci update GCC 4.9 and 5.4

---

src/drivers/px4fmu/fmu.cpp

@LorenzMeier @julianoes a bug was introduced from recent commit 78b0d1a, this is a fix for that.

fix typo introduced in commit# 78b0d1a which adds PWM1 mode

---

src/drivers/px4fmu/fmu.cpp
src/lib/rc/dsm.c
src/lib/rc/dsm.h
src/lib/rc/rc_tests/RCTest.cpp

Passes unit tests, needs HW test.

DSM protocol fix

---

src/modules/logger/log_writer_file.cpp
src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/uORB/uORBUtils.hpp
src/modules/uavcan/uavcan_servers.cpp

These are C++ headers not available on NuttX

Remove some includes that potentially cause problems on NuttX

---

Tools/mavlink_shell.py

fix mavlink_shell.py: python3 compat

---

src/drivers/px4fmu/fmu.cpp

We seem to have inadequate testing for fmu-v2

fix another bug in commit# 78b0d1a

---

src/drivers/vmount/input_mavlink.cpp

Thanks @mbraunecker
Fixes #5746

fix vmount: initialize manual control for mavlink inputs

---

src/modules/controllib_test/controllib_test_main.cpp

I was doing some syncing on testing. Can we use `fscanf` on NuttX?

[WIP] Test fixes

---

src/platforms/apps.cpp.in
src/platforms/apps.h.in

See discussion at https://github.com/PX4/Firmware/issues/5756

Export symbols init_app_map and list_builtins

---

ROMFS/px4fmu_common/init.d/4900_crazyflie
src/drivers/boards/crazyflie/board_config.h
src/drivers/stm32/drv_io_timer.c

@dennisss 
Awesome - Thank you!

Removing alternative io timer rate for CF2

---

src/modules/attitude_estimator_q/attitude_estimator_q_main.cpp

small subset of https://github.com/PX4/Firmware/pull/4989

incorporate into Q estimator Bill Premerlani's fast rotation handling from MatrixPilot

---

src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp
src/modules/navigator/mission_block.cpp

FW waypoint loiter to alt

---

src/systemcmds/tests/test_matrix.cpp

dependent on https://github.com/PX4/Matrix/pull/31

add unit test for Dcm.renormalize() in matrix submodule

---

src/modules/ekf2/ekf2_main.cpp
src/modules/sensors/sensors.cpp
src/modules/uORB/uORBManager.cpp
src/modules/uORB/uORBManager.hpp
src/systemcmds/config/config.c

This frees ~1.1 KB in sensors, for boards with only one sensor per type and frees 2.3KB in EKF2.
Requires https://github.com/PX4/ecl/pull/208

Save more RAM

---

msg/mission_result.msg
src/modules/commander/commander.cpp
src/modules/navigator/mission.cpp
src/modules/navigator/mission.h
src/modules/navigator/mission_feasibility_checker.cpp
src/modules/navigator/navigator_main.cpp
src/modules/navigator/navigator_mode.h

Used to start a mission (at a particular index) and arm in a single command.
Only changes to AUTO_MISSION if the mission is valid, and only arms if the mode change wasn't denied.

implement MAV_CMD_MISSION_START

---

src/modules/navigator/geofence.cpp

@LorenzMeier This fixes #5771.

Geofence: Param update fix

---

src/modules/mavlink/mavlink_receiver.cpp
src/modules/mavlink/mavlink_receiver.h

There was no feedback if a CMD_SET_MESSAGE_INTERVAL went through or not.
Please review @bkueng.

mavlink: send ACK for CMD_SET_MESSAGE_INTERVAL

---

msg/CMakeLists.txt
msg/mount_status.msg
src/drivers/vmount/output.cpp
src/drivers/vmount/output.h
src/drivers/vmount/vmount.cpp
src/modules/mavlink/mavlink_ftp.cpp
src/modules/mavlink/mavlink_ftp.h
src/modules/mavlink/mavlink_log_handler.cpp
src/modules/mavlink/mavlink_log_handler.h
src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/mavlink_messages.h
src/modules/mavlink/mavlink_mission.h
src/modules/mavlink/mavlink_parameters.h
src/modules/mavlink/mavlink_stream.h

This updates the mavlink submodules which include the [MOUNT_STATUS](http://mavlink.org/messages/common#MOUNT_STATUS).
Support for the mount attitude is added in vmount and mavlink_messages.
Also, all msg IDs needed be changed from uint8_t to uint16_t in order to accomodate new mavlink messages with an ID > 255.
@bkueng please review.

Report mount attitude

---

src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp
src/modules/local_position_estimator/BlockLocalPositionEstimator.hpp
src/modules/local_position_estimator/sensors/land.cpp

This helps stop the vehicle from wandering after landing.

Added fake landing xy velocity measurement to lpe.

---

Tools/new_nuttx_px_config.sh

Usage: Tools/new_nuttx_px_config.sh oldname newname
For example:
Tools/new_nuttx_px_config.sh px4nucleoF767ZI-v1 new_name-v3

Add Tools/new_nuttx_px_config.sh

---

Tools/fix_headers.sh
src/drivers/mpu9250/mag.h
src/lib/controllib/block/BlockParam.hpp
src/lib/mathlib/math/Matrix.hpp
src/lib/mathlib/mathlib.h
src/modules/mavlink/mavlink_bridge_header.h
src/modules/mavlink/mavlink_log_handler.h
src/modules/mavlink/mavlink_orb_subscription.h
src/modules/px4iofirmware/px4io.c
src/modules/systemlib/board_serial.h
src/modules/systemlib/cpuload.h
src/modules/systemlib/perf_counter.c
src/modules/systemlib/perf_counter.h
src/modules/uavcan/uavcan_servers.hpp
src/platforms/posix/include/queue.h
src/platforms/posix/px4_layer/drv_hrt.c
src/platforms/posix/work_queue/hrt_work_cancel.c
src/platforms/qurt/include/queue.h
src/platforms/qurt/px4_layer/drv_hrt.c

These are the last commits that I have related to the Tools/fix_headers.sh script, including the script itself.
After merging this, an admin can run the script to see what it does. I wouldn't immediately push the result to master because it's a rather large commit and perhaps we can find a smart(er) way to get it in without giving everyone with branches that changed one of more #include's a headache.

Cw fix headers

---

msg/ulog_stream_ack.msg
src/drivers/device/cdev.cpp
src/drivers/device/device_nuttx.h
src/drivers/device/vdev.cpp
src/drivers/device/vdev.h
src/modules/mavlink/mavlink_ulog.cpp

- Save ~2.3KB of RAM
- minor updates to the ulog streaming

Save some more RAM

---

src/modules/mavlink/mavlink_bridge_header.h
src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_main.h

The mavlink_parameters::handle_message method was trying to send responses back immediately from the mavlink_receiver::receive_thread. This conflicts with messages already being sent on the main thread, resulting in random CRC failures, and flakey results from PARAM_REQUEST_READ and PARAM_SET. The following shows a log of the attempts to read a parameter before this fix:
param get SENS_EN_SF1XX
SENS_EN_SF1XX=4
param get SENS_EN_SF1XX
MavLink message 147, seqno 8c has bad CRC 19 received, expecting 1a6d!
Exception: Parameter 'SENS_EN_SF1XX' not found'
param get SENS_EN_SF1XX
SENS_EN_SF1XX=4
param get SENS_EN_SF1XX
SENS_EN_SF1XX=4
param get SENS_EN_SF1XX
MavLink message 30, seqno bb has bad CRC 19 received, expecting a7c5!
MavLink message 21, seqno c5 has bad CRC 15 received, expecting …

Fix multithreading bug in mavlink over serial port.

---

ROMFS/px4fmu_common/init.d/rcS
msg/CMakeLists.txt
msg/sensor_combined.msg
msg/sensor_preflight.msg
src/modules/commander/PreflightCheck.cpp
src/modules/commander/commander.cpp
src/modules/commander/commander_params.c
src/modules/logger/logger.cpp
src/modules/logger/params.c
src/modules/sensors/sensors.cpp

Replaces https://github.com/PX4/Firmware/pull/5850 - rebased and commit history cleaned up.
Addresses #5842
Adds checking of EKF innovation levels and inconsistencies between multiple IMU sensors if fitted.

Improve robustness of pre-flight checking

---

src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/standard.h
src/modules/vtol_att_control/tailsitter.cpp
src/modules/vtol_att_control/tailsitter.h
src/modules/vtol_att_control/tiltrotor.cpp
src/modules/vtol_att_control/tiltrotor.h
src/modules/vtol_att_control/vtol_att_control_main.cpp
src/modules/vtol_att_control/vtol_att_control_main.h
src/modules/vtol_att_control/vtol_type.h

Fixes the bug which updated vtol parameters on every iteration. This should reduce CPU load drastically.
Furthermore, this should fix a memory leak.

Pr vtol params

---

Tools/scp_upload.sh
posix-configs/rpi/px4.config
posix-configs/rpi/px4_fw.config
src/drivers/navio_sysfs_pwm_out/navio_sysfs_pwm_out.cpp
src/firmware/posix/CMakeLists.txt

- use quad_x mixer per default instead of AERT (most people will probably use quadrotors)
- extend & improve upload script. Upload all RPi startup configurations and the mixer files as well

RPi: some general updates

---

posix-configs/SITL/init/ekf2/iris
src/modules/simulator/simulator_mavlink.cpp

This fixes some errors in ground truth recording and also updates sitl gazebo to fix ground truth frame issues there. This is towards closing #5931.

Fixes for sitl gazebo ground truth.

---

ROMFS/px4fmu_common/init.d/4009_qav250
ROMFS/px4fmu_common/init.d/4050_generic_250

add airframe metadata

---

Makefile
ROMFS/px4fmu_common/init.d/rc.sensors
cmake/configs/nuttx_px4fmu-v3_default.cmake
src/modules/sensors/sensors.cpp

Continuing https://github.com/PX4/Firmware/pull/5962

Pixhawk 2 cleanup

---

ROMFS/px4fmu_common/init.d/4070_aerofc
ROMFS/px4fmu_common/init.d/rcS

- parameter tuning from https://github.com/PX4/Firmware/issues/5955
- make sure logging works

Intel aero: config updates

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

This pull request follows the discussion from issue #5815.

Mpc pos control manual mapping

---

src/modules/navigator/loiter.cpp

This fixes the following corner case:
1. Upload a mission.
2. Set mission mode.
3. Set loiter mode.
4. Arm.
At this point it will shoot up and go to the takeoff waypoint even
though we're not in mission but in loiter mode.
The fix makes sure that the triplet is reset to invalid (and idle) in
loiter mode if we're landed and disarmed.
It will lead to the vehcle sit in idle on the ground until you issue a
start mission (or takeoff) command.
Fix tested in SITL. Let's check for CI and maybe outdoor testing.

navigator: don't takeoff in loiter on ground

---

ROMFS/px4fmu_common/init.d/rc.sensors

@davids5 
Added sensor orientation, ADC config coming.

WIP : updates for px4fmu-v4pro

---

src/modules/syslink/CMakeLists.txt
src/modules/syslink/syslink_main.cpp
src/modules/syslink/syslink_main.h

- Mainly the fix for the linked issue
- Resending and monitoring of acknowledgements for setting radio parameters
- Functional reflashing of the radio via the Bitcraze utilities

Syslink improvements

---

Makefile

As requested - https://github.com/mavlink/qgroundcontrol/pull/4316

crazyflie_default upload for QGC

---

cmake/configs/posix_bebop_default.cmake
posix-configs/bebop/px4.config
src/drivers/gps/gps.cpp

This enables gps on the bebop2. Amazing how fast that gps gets a fix, and I'm sitting on the couch in my house.

Pr bebop2 gps

---

Tools/upload_log.py
integrationtests/run_tests.bash
integrationtests/upload_test_logs.bash
posix-configs/SITL/init/ekf2/standard_vtol

@LorenzMeier @bkueng spamming Flight Review (new script called by Jenkins)
The links are now just printed in the console log. Could someone look into pushing those as comment on the PR?

CI log upload

---

ROMFS/px4fmu_common/init.d/10018_tbs_endurance
ROMFS/px4fmu_common/init.d/15001_coax_heli
ROMFS/px4fmu_common/init.d/16001_helicopter
ROMFS/px4fmu_common/init.d/2101_fw_AERT
ROMFS/px4fmu_common/init.d/2105_maja
ROMFS/px4fmu_common/init.d/2106_albatross
ROMFS/px4fmu_common/init.d/3100_tbs_caipirinha
ROMFS/px4fmu_common/init.d/4020_hk_micro_pcb
ROMFS/px4fmu_common/init.d/4040_reaper
ROMFS/px4fmu_common/init.d/4050_generic_250
ROMFS/px4fmu_common/init.d/4080_zmr250
ROMFS/px4fmu_common/init.d/rc.axialracing_ax10_defaults
msg/multirotor_motor_limits.msg
src/drivers/px4fmu/fmu.cpp
src/drivers/px4io/px4io.cpp
src/drivers/tap_esc/tap_esc.cpp
src/modules/mc_att_control/mc_att_control_main.cpp
src/modules/mc_att_control/mc_att_control_params.c
src/modules/px4iofirmware/protocol.h
src/modules/systemlib/mixer/mixer.cpp
src/modules/systemlib/mixer/mixer.h
src/modules/systemlib/mixer/mixer_group.cpp
src/modules/systemlib/mixer/mixer_multirotor.cpp
src/modules/systemlib/mixer/mixer_simple.cpp

@devbharat This might be the more complete attempt at fixing all limitations. It would be great if you could do your integrator fixes on top of this.

Mixer limits

---

src/modules/navigator/navigator_main.cpp

This should fix the matrix submodule checkout trouble.

Fix matrix submodule

---

src/drivers/px4fmu/fmu.cpp

Was unable to push directly to PX4/pr-mixerEnhancements.
I thought this used to work:
git push --set-upstream px4 pr-mixerEnhancements
remote: Permission to PX4/Firmware.git denied to kd0aij.
fatal: unable to access 'https://github.com/PX4/Firmware.git/': The requested URL returned error: 403

add THR_MDL_FAC parameter handling to FMU

---

Tools/px4params/xmlout.py
src/drivers/px4fmu/fmu.cpp
src/modules/sensors/sensor_params.c

flight tested in stabilize and acro modes on QAV250

hotfix: THR_MDL_FAC parameter: bump minor version and default to disabled

---

cmake/configs/qurt_sdflight_default.cmake
src/drivers/snapdragon_pwm_out/CMakeLists.txt
src/drivers/snapdragon_pwm_out/snapdragon_pwm_out.cpp

This request follows #5937. It still requires testing on a real platform.

Snapdragon pwm

---

ROMFS/px4fmu_common/init.d/rcS

@eyeam3 @pavel-kirienko Am I right that this fix is required for UAVCAN?

Start UAVCAN in the two phases required

---

src/drivers/gps/gps.cpp
src/drivers/hmc5883/hmc5883.cpp
src/modules/local_position_estimator/local_position_estimator_main.cpp
src/modules/sensors/voted_sensors_update.cpp
src/modules/simulator/simulator.h
src/modules/uORB/uORBDevices.cpp

These fixes are across the codebase for various memory access fails in POSIX simulation.

Memory access fixes

---

src/drivers/px4fmu/CMakeLists.txt
src/drivers/px4fmu/fmu.cpp
src/drivers/px4fmu/px4fmu_params.c
src/drivers/tap_esc/tap_esc.cpp
src/modules/mavlink/mavlink_mission.cpp
src/modules/uavcan/uavcan_main.cpp
src/systemcmds/tests/test_rc.c

Some files were still using the legacy calls to unsubscribe. This uses the proper API now.

uORB unsubscribe

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

pretty trivial code improvements, this should not change any functionality!

mc_pos_control small refactoring while studying

---

ROMFS/px4fmu_common/init.d/rc.sensors

aerofc: change external mag orientation to 'Yaw 180 deg'

---

posix-configs/bebop/px4.config

Signed-off-by: Roman <bapstroman@gmail.com>

bebop config: updated some gains for decent performance

---

posix-configs/SITL/init/ekf2/iris
posix-configs/SITL/init/ekf2/multiple_iris
posix-configs/SITL/init/ekf2/plane
posix-configs/SITL/init/ekf2/solo
posix-configs/SITL/init/ekf2/standard_vtol
posix-configs/SITL/init/ekf2/tailsitter
posix-configs/SITL/init/ekf2/typhoon_h480
posix-configs/SITL/init/inav/iris
posix-configs/SITL/init/inav/iris_opt_flow
posix-configs/SITL/init/lpe/iris
posix-configs/SITL/init/lpe/iris_opt_flow
posix-configs/SITL/init/lpe/plane
posix-configs/SITL/init/lpe/standard_vtol
posix-configs/SITL/init/lpe/typhoon_h480
posix-configs/bebop/px4.config
posix-configs/eagle/200qx/px4.config
posix-configs/eagle/210qc/px4.config
posix-configs/eagle/flight/px4.config
posix-configs/eagle/hil/px4.config
posix-configs/rpi/px4.config

... so that tools like flight_review know which estimator was used.
@jgoppert

posix-configs: set SYS_MC_EST_GROUP

---

src/modules/commander/commander.cpp
src/modules/mavlink/mavlink_receiver.cpp

@DonLakeFlyer This should fix all instances that you've raised.

Ack fix for commands

---

src/modules/land_detector/LandDetector.h
src/modules/land_detector/MulticopterLandDetector.cpp
src/modules/land_detector/MulticopterLandDetector.h

just naming and large number constants, should have no change in functionality!

land detector: small refactor while studying

---

Tools/sitl_run.sh
src/firmware/posix/CMakeLists.txt
src/firmware/posix/sitl_target.cmake
src/platforms/posix/main.cpp
src/platforms/posix/sitl_runner_main.cpp.in

This builds on #6043, which unfortunately broke other posix builds. I added another ifelse and check if we build a SITL board. If this is the case, I execute the related cmake configuration with the changes made for the IDE.
I tested the build for Bebop2 and various SITL targets, which seemed to be working. I cannot verify if the IDE setup still works.

Restructure posix cmake configuration

---

ROMFS/px4fmu_common/init.d/rc.sensors
Tools/aero_upload.sh
cmake/configs/nuttx_aerofc-v1_default.cmake
src/drivers/aerofc_adc/CMakeLists.txt
src/drivers/aerofc_adc/aerofc_adc.cpp
src/drivers/boards/aerofc-v1/board_config.h
src/modules/sensors/parameters.cpp

This needs the latest release from Dec 20:
https://github.com/intel-aero/meta-intel-aero/wiki/Software-Release-Notes
Make sure to update the FPGA.
@zehortigoza I finished your initial implementation and tested on real hardware. Please take a look.

aerofc: implement ADC and improve upload script

---

integrationtests/python_src/px4_it/mavros/mission_test.py
integrationtests/python_src/px4_it/mavros/multirotor_box.mission
integrationtests/run_tests.bash
launch/mavros_posix_tests_iris.launch
launch/mavros_posix_tests_standard_vtol.launch

Adds ground truth tests to sitl gazebo CI.

---

integrationtests/run_tests.bash
launch/mavros_posix_tests_iris_opt_flow.launch
src/modules/mavlink/mavlink_messages.cpp

* Bash arg handling
* Optical flow rostest script for sitl gazebo
* Groundtruth mavlink stream

Integrations script options and optical flow gazebo sitl support

---

.travis.yml
Makefile
circle.yml

Not expected to pass until docker hub finishes building (a few hours from now).

docker update to 2016-12-26 images

---

cmake/nuttx/px4_impl_nuttx.cmake

Potential fix for #6170 and https://github.com/PX4/Firmware/issues/5717#issuecomment-267677937

cmake nuttx create target for nuttx copy

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

Rebased version of https://github.com/PX4/Firmware/pull/5983

Added checks for setting mpc saturation flags

---

integrationtests/python_src/px4_it/dronekit/MissionCheck.py
integrationtests/python_src/px4_it/dronekit/VTOL_TAKEOFF.mission

Simplifying mode change and apply new json mission format

Dronekit improvements

---

Makefile

I'm not sure this is all that's needed.... this was done inspecting the code only. I have a pending patch to submit to QGC for it to download from the right location. If this is all that's needed please let know.

Add aerofc to QGC

---

posix-configs/SITL/init/ekf2/iris_opt_flow

I also added a config file for ekf2/flow

Update sitl gazebo to use new flow repo

---

posix-configs/SITL/init/lpe/solo

missing solo config, copied the iris one to make it work again

fixed solo gazebo target

---

src/modules/vtol_att_control/vtol_att_control_main.cpp

Fixes https://github.com/PX4/Firmware/issues/6246

Remove double call to publish_att_sp() in VTOL

---

Tools/check_submodules.sh

Using git submodules command going over all the submodules and not only the ones on the whitelist
and fixed white spaces
Fixes issue #6271

Recursevely go over all submodules

---

src/firmware/qurt/px4muorb.idl
src/modules/muorb/adsp/px4muorb.cpp
src/modules/muorb/adsp/px4muorb.hpp
src/modules/muorb/adsp/uORBFastRpcChannel.cpp
src/modules/muorb/adsp/uORBFastRpcChannel.hpp
src/modules/muorb/krait/px4muorb_KraitRpcWrapper.cpp
src/modules/muorb/krait/px4muorb_KraitRpcWrapper.hpp
src/modules/muorb/krait/uORBKraitFastRpcChannel.cpp
src/modules/muorb/krait/uORBKraitFastRpcChannel.hpp
src/modules/sdlog2/sdlog2.c
src/modules/uORB/uORBCommunicator.hpp
src/modules/uORB/uORBDevices.cpp
src/modules/uORB/uORBDevices.hpp
src/modules/uORB/uORBManager.cpp
src/modules/uORB/uORBManager.hpp
src/platforms/apps.cpp.in

This adds support for orb_exists synchronization across the apps processor and the DSP on Eagle platform.  There is also a new builtin: wait_for_topic with will poll for the specified topic to be advertised before continuing. A timeout of 0 means wait forever.

Muorb orb exists 2

---

src/drivers/gps/gps.cpp

currently this baudrate was not added for qurt

gps.cpp: add gps baudrate 230400 to qurt

---

src/modules/navigator/mission.cpp
src/modules/navigator/mission.h

I forgot about fixed-wing.. `do_need_takeoff` was never true for fixed-wing therefore the takeoff waypoint couldn't have been set. We need a fixed-wing SITL test :) @dagar can you review?
TODO: SITL test

Fixed-wing: allow mission takeoff

---

src/lib/rc/rc_tests/RCTest.cpp
src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_parameters.cpp
src/modules/mavlink/mavlink_receiver.cpp
src/modules/px4iofirmware/mixer.cpp
src/modules/sdlog2/sdlog2.c
src/modules/systemlib/mixer/mixer_helicopter.cpp
src/platforms/posix/drivers/tonealrmsim/tone_alarm.cpp
src/systemcmds/tests/test_mixer.cpp
src/systemcmds/tests/test_ppm_loopback.c
src/systemcmds/tests/test_servo.c

This is a set of general fixes for mixer and coverity.

Mixer and Coverity fixes

---

cmake/posix/px4_impl_posix.cmake

This is a left over from cleanup 0acf6db64f0d6a79998879517519df628e388023
Signed-off-by: Nicolae Rosia <nicolae.rosia@gmail.com>

Remove invalid eigen reference

---

ROMFS/px4fmu_common/init.d/rc.mc_apps

 spelling error;

---

src/modules/land_detector/MulticopterLandDetector.cpp
src/modules/land_detector/MulticopterLandDetector.h
src/modules/mc_pos_control/mc_pos_control_main.cpp

@MaEtUgR @Stifael Continued https://github.com/PX4/Firmware/pull/6205, rebased on master and fixed the landing part. SITL tested with GPS drift model. Ready for outdoors.

Position control takeoff

---

Makefile
cmake/configs/posix_excelsior_default.cmake
cmake/configs/posix_excelsior_legacy.cmake
cmake/configs/posix_sdflight_legacy.cmake
cmake/configs/qurt_excelsior_legacy.cmake
cmake/configs/qurt_sdflight_legacy.cmake
cmake/posix/px4_impl_posix.cmake
posix-configs/excelsior/mainapp.config
posix-configs/excelsior/px4.config
src/modules/commander/accelerometer_calibration.cpp
src/modules/commander/gyro_calibration.cpp
src/modules/dataman/dataman.c
src/modules/logger/logger.h
src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/mavlink_orb_subscription.cpp
src/modules/muorb/krait/px4muorb_KraitRpcWrapper.cpp
src/modules/sdlog2/sdlog2.c
src/modules/uORB/uORBDevices.cpp
src/modules/uORB/uORBMain.cpp
src/platforms/posix/main.cpp
src/platforms/px4_defines.h
src/platforms/qurt/px4_layer/shmem_qurt.c

@wangxdflight I rebased and continued https://github.com/PX4/Firmware/pull/6326 here.

Atl flight excelsior legacy support

---

src/drivers/boards/common/board_common.h
src/systemcmds/mtd/24xxxx_mtd.c
src/systemcmds/mtd/mtd.c

This pulls out board specifics from the MTD driver and puts it into the board config (where it belongs).

MTD interface revision

---

cmake/configs/posix_bebop_default.cmake
posix-configs/bebop/px4.config
src/platforms/posix/drivers/bebop_flow/CMakeLists.txt
src/platforms/posix/drivers/bebop_flow/bebop_flow.cpp
src/platforms/posix/drivers/bebop_flow/dump_pgm.cpp
src/platforms/posix/drivers/bebop_flow/dump_pgm.h
src/platforms/posix/drivers/bebop_flow/video_device.cpp
src/platforms/posix/drivers/bebop_flow/video_device.h
src/platforms/posix/drivers/df_bebop_rangefinder_wrapper/CMakeLists.txt
src/platforms/posix/drivers/df_bebop_rangefinder_wrapper/df_bebop_rangefinder_wrapper.cpp

@ChristophTobler Please continue here. @eyeam3 FYI.

Bebop bottom camera including rangefinder

---

src/lib/version/version.h
src/modules/systemlib/hardfault_log.h
src/modules/systemlib/px4_macros.h

@LorenzMeier - this is just clean up

Move common macros to systemlib/px4_macros.h

---

msg/manual_control_setpoint.msg
src/modules/mavlink/mavlink_receiver.cpp
src/modules/sensors/rc_update.cpp

@bkueng Please review. This should help with situations where you have the joystick connected.

RC multi input fix

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

The special calculation for switching from a non-velocity controlled mode into a velocity controlled mode is not needed anymore with the recently introduced feed forward thrust (see https://github.com/PX4/Firmware/blame/0d99ab91aad5a159de9c287383419245b1c6bcb8/src/modules/mc_pos_control/mc_pos_control_main.cpp#L1738).
It even produced unwanted aggressive twitches when still used.
I verified the change in SITL and also tested on a real model.
I got smooth breakdowns when switching from maual to position mode.

Fixed twitch/spike during mode switch

---

msg/vehicle_land_detected.msg
src/modules/land_detector/FixedwingLandDetector.cpp
src/modules/land_detector/FixedwingLandDetector.h
src/modules/land_detector/LandDetector.cpp
src/modules/land_detector/LandDetector.h
src/modules/land_detector/MulticopterLandDetector.cpp
src/modules/land_detector/MulticopterLandDetector.h
src/modules/land_detector/VtolLandDetector.cpp
src/modules/land_detector/VtolLandDetector.h
src/modules/land_detector/land_detector_params.c
src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/simulator/simulator_mavlink.cpp

@MaEtUgR This implements the complete ground-contact detection and setpoint zeroing we discussed.

Land detection

---

src/platforms/posix/drivers/df_bebop_bus_wrapper/df_bebop_bus_wrapper.cpp

Maps scaled thrust values to desired motor speed values.

Pr bebop thrust

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

mc_pos_control: timestamp fix for vel_sp

---

cmake/configs/posix_sitl_default.cmake
src/drivers/l3gd20/l3gd20.cpp
src/modules/commander/accelerometer_calibration.cpp
src/modules/commander/gyro_calibration.cpp
src/modules/events/temperature_calibration/accel.cpp
src/modules/events/temperature_calibration/accel.h
src/modules/events/temperature_calibration/baro.cpp
src/modules/events/temperature_calibration/baro.h
src/modules/events/temperature_calibration/common.h
src/modules/events/temperature_calibration/gyro.cpp
src/modules/events/temperature_calibration/gyro.h
src/modules/events/temperature_calibration/task.cpp
src/modules/systemlib/param/param.c
src/modules/systemlib/param/param.h
src/modules/systemlib/param/param_shmem.c

- fixes problem introduced in https://github.com/PX4/Firmware/pull/6497/commits/24eb72e1ce199909c99c464758bcab178aa1451e
- notifies system after param reset before starting temp calibration
- more refactoring to reduce code duplication
Follow-up to #6497
@priseborough

Thermal calibration updates

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

This pr fixes position setpoint update after transition from velocity to position control. 
i also resets the position setpoint based on current velocity and max acceleration

velocity-position control transition

---

Tools/process_sensor_caldata.py

Tools: update offline sensor calibration script

---

cmake/configs/posix_sitl_default.cmake
src/drivers/camera_trigger/CMakeLists.txt
src/drivers/camera_trigger/camera_trigger.cpp
src/drivers/camera_trigger/camera_trigger_params.c
src/drivers/camera_trigger/interfaces/src/pwm.cpp
src/drivers/camera_trigger/interfaces/src/pwm.h
src/drivers/camera_trigger/interfaces/src/relay.cpp
src/drivers/camera_trigger/interfaces/src/relay.h
src/modules/mavlink/mavlink_messages.cpp

- enable & build `camera_trigger` module for SITL for basic testing
- forward camera triggering via MAVLink
Fixes https://github.com/PX4/Firmware/issues/6520

Camera trigger updates

---

src/modules/sensors/sensors.cpp
src/modules/sensors/voted_sensors_update.h

- _voted_sensors_update.baro_pressure() is already in pascals
Pressure is now converted to pascals here - https://github.com/PX4/Firmware/blob/master/src/modules/sensors/voted_sensors_update.cpp#L785
@tumbili FYI

true airspeed wrong

---

src/platforms/px4_micro_hal.h
src/systemcmds/bl_update/bl_update.c

This 	define PX4_FLASH_BASE in micro HAL

Fix master

---

src/modules/land_detector/MulticopterLandDetector.cpp

land detector (mc)

---

src/systemcmds/tests/test_matrix.cpp

For https://github.com/PX4/Firmware/pull/6513

update matrix and fix test_matrix

---

ROMFS/px4fmu_common/init.d/rcS
Tools/aero_upload.sh
Tools/px_uploader.py

This doesn't change the default baud rate yet since it's not clear what baud rate will be set.  However it enables easier migration from one version to another that has a different baud rate set.

px_uploader: multiple baud rates

---

src/modules/commander/commander.cpp
src/modules/commander/commander_params.c
src/modules/navigator/rtl.cpp
src/modules/navigator/rtl.h

This adds a few fixes for auto flight modes to improve it to have more intuitive user handling.

Fixes for auto flight modes

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

This pr should fix the issue when flying forward with constant roll/pitch demand during velocity demand changes in z-direction. 
In the past the velocity setpoint in xy changed as well:
In addition I deleted the function limit_pos_offset since not used anywhere.

mc_pos_control: manual stick input fix; deletion of unusued function

---

src/modules/ekf2/ekf2_main.cpp
src/modules/ekf2/ekf2_params.c

This updates ecl for changes made to the EKF:
- improvements to terrain estimator and general range finder fusion
- introduction of a pitch offset of the range finder
- improvements to optical flow
The range finder changes were tested outdoor and in SITL.

Pr ecl update

---

src/modules/navigator/navigator_main.cpp

This should reduce the CPU load impact of navigator considerably.

Rate-limit navigator update rate

---

src/modules/ekf2/ekf2_main.cpp
src/modules/fw_att_control/fw_att_control_main.cpp
src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp
src/modules/mavlink/mavlink_receiver.cpp
src/modules/simulator/simulator_mavlink.cpp

Waiting on https://github.com/PX4/Matrix/pull/40

add matrix copyTo

---

src/modules/navigator/datalinkloss.cpp
src/modules/navigator/enginefailure.cpp
src/modules/navigator/follow_target.cpp
src/modules/navigator/gpsfailure.cpp
src/modules/navigator/mission.cpp
src/modules/navigator/navigator_main.cpp
src/modules/navigator/rcloss.cpp
src/modules/navigator/rtl.cpp

This should lower the CPU load impact of navigator.

Navigator: Only update params as they change

---

src/systemcmds/pwm/pwm.c

This allows to use `pwm info` in simulations, which can be handy for debugging.

Port PWM command to POSIX

---

msg/fw_virtual_attitude_setpoint.msg
msg/mc_virtual_attitude_setpoint.msg
src/modules/fw_att_control/fw_att_control_main.cpp
src/modules/mc_pos_control/mc_pos_control_main.cpp

RE: https://github.com/PX4/Firmware/issues/6554#issuecomment-280133417
@sanderux do you want to give this a try? I've test flown the fw_att change many times, but the mc_pos change is new and so far only tested in SITL.

VTOL setpoint and integrator reset

---

src/modules/mavlink/mavlink_messages.cpp

mavlink: Send message to control onboard camera as broadcast

---

src/modules/navigator/rtl.cpp

@dagar This fixes https://github.com/PX4/Firmware/issues/6669#issuecomment-282498134.

Navigator: Re-initialize RTL every time it gets re-enabled

---

Tools/px_uploader.py

This brings some cleanup to the px_uploader. For more info and to review, check the individual commits.
@bkueng I would appreciate a review.

Clean up px_uploader

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

this bug only occurred during transition from downward flight to altitude engaged

mc_pos_control: delta_t needs to be positive

---

src/drivers/boards/px4fmu-v4pro/board_config.h

Enable ICM 20608 on Pixhawk Pro

---

ROMFS/px4fmu_common/init.d/rcS
src/drivers/boards/aerofc-v1/aerofc_init.c
src/drivers/boards/aerofc-v1/board_config.h
src/modules/dataman/dataman.c
src/modules/dataman/dataman.h
src/modules/systemlib/flashparams/flashfs.h

This first 2 commits here was sent in a previous PR https://github.com/PX4/Firmware/pull/6720

modules: dataman: Add a ram_flash backend & Use it in AeroFC

---

src/modules/mavlink/mavlink_mission.cpp

Previously the retry would not actually have been sent if nothing had been received in time. This should make mission uploads a bunch more reliable.

Mission transfer: Fix retry logic

---

src/modules/logger/log_writer_file.cpp

because of messages in the logs
@bkueng Did I change the right spot?

logger: adjusted log_writer_file stack size

---

ROMFS/px4fmu_common/init.d/4090_nanomind

Config for [NanoMind](http://discuss.px4.io/t/nanomind-110-kit-tiny-whoop-running-px4-for-indoor-fpv-racing/2754) from AirMind.

add new config for NanoMind

---

cmake/configs/nuttx_mindpx-v2_default.cmake

MindPX: Start send_events handler in MindPX

---

src/firmware/posix/sitl_target.cmake

in case of soure inside sitl_gazebo has changed

Make sure that external sitl project will be rebuild 

---

ROMFS/px4fmu_common/init.d/12002_steadidrone_mavrik
ROMFS/px4fmu_common/init.d/13008_QuadRanger
ROMFS/px4fmu_common/init.d/13009_vtol_spt_ranger
ROMFS/px4fmu_common/init.d/4030_solo
ROMFS/px4fmu_common/init.d/rc.vtol_defaults
ROMFS/tap_common/init.d/rc.vtol_defaults
posix-configs/SITL/init/ekf2/iris
posix-configs/SITL/init/ekf2/iris_opt_flow
posix-configs/SITL/init/ekf2/multiple_iris
posix-configs/SITL/init/ekf2/solo
posix-configs/SITL/init/ekf2/standard_vtol
posix-configs/SITL/init/ekf2/tailsitter
posix-configs/SITL/init/ekf2/typhoon_h480
posix-configs/SITL/init/inav/iris_opt_flow
posix-configs/SITL/init/lpe/iris
posix-configs/SITL/init/lpe/iris_opt_flow
posix-configs/SITL/init/lpe/solo
posix-configs/SITL/init/lpe/standard_vtol
posix-configs/SITL/init/lpe/typhoon_h480
src/lib/mathlib/math/Expo.hpp
src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/mc_pos_control/mc_pos_control_params.c

This is a branch to test all recent postion control pull requests of @Stifael and me.

Position control merges

---

CMakeLists.txt
Tools/px_process_params.py
cmake/common/px4_base.cmake

make sure params defined in external modules are found

External params

---

Makefile
nuttx-patches/00010-BACKPORT-stm32-flash-F4-dcache-corruption-fix-no-HSI-on.patch

stm32 Updated flash patch to upstream revised

---

src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/standard.h

Implements https://github.com/PX4/Firmware/issues/6709
From SITL:

VTOL transition maintain FW_PSP_OFF

---

src/modules/mavlink/mavlink_messages.cpp

@jonrwat can you verify this still works for your setup?

mavlink stream camera trigger broadcast DO_DIGICAM

---

src/modules/commander/commander.cpp

fix #6930. This issue also happens on Pixhawk.

fix LED status bug when system is armed

---

src/modules/navigator/mission.cpp
src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/standard.h
src/modules/vtol_att_control/vtol_att_control_params.c

A few improvements to transitions
as discussed in https://github.com/PX4/Firmware/issues/6856

Vtol transition improvements

---

src/lib/external_lgpl/tecs/tecs.cpp
src/lib/external_lgpl/tecs/tecs.h
src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c

- fixes #6664
Need to do more testing/comparison. TECS might be slightly easier to tune if we expose a few more things over mavlink.

TECS fix height demand change

---

src/drivers/tap_esc/tap_esc.cpp

Tested on aerofc.
@lucasdemarchi

tap_esc: handle killswitch

---

src/platforms/posix/drivers/df_mpu9250_wrapper/df_mpu9250_wrapper.cpp

This wrapper uses now the same two-pole-filter like the mpu6000. Here's a log http://logs.uaventure.com/view/5MQLXZ3vvAEixayrpoqTnX of a position hold.

add two-pole-filter to mpu9250 wrapper

---

src/drivers/stm32/drv_io_timer.c

This fixes the issue with initializing channels 5,6 without
channels 1-4.
The code assumed all timers actions were in order to be
initialized. This is not the case. This commit fixes that
bad assumption by not stopping the configuration on the
first action entry with a base == 0, but processing all
entries with non-zero base.
fyi @mhkabir

bugfix:drv_io_timer properly initialize non-contiguous timer channels

---

Tools/px4params/markdownout.py

Including increment, enum value, bitmask, module information. This is in response to further feedback on #6913

Update markdown parameter script to include additional information

---

Tools/sdlog2/geo_tag_images.py
Tools/sdlog2/geotagging.py

geotagging.py - print progress info and let script tolerate different number of images and camera triggers.
geo_tag_images.py - make it actually work with PX4 logs

geo taggging scripts minor fixes

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

follows the discussion here:
https://github.com/PX4/Firmware/issues/6914

wip: mc_pos_control: if takeoff setpoint in auto mode, then do not enter ground contact

---

ROMFS/px4fmu_common/init.d/rc.sensors
Tools/px4_snapflight_sanitytest.sh
Tools/px_generate_params.py
posix-configs/SITL/init/lpe/iris_rplidar
src/firmware/posix/sitl_target.cmake

Add support for iris with rplidar.

Add iris_rplidar model

---

src/modules/navigator/rtl.cpp
src/modules/navigator/rtl.h

@PX4TestFlights Please re-test this one. Hopefully it puts your RTL issues to rest.

Navigator: Fix RTL state sequence

---

README.md

README link to github labels

---

src/modules/land_detector/MulticopterLandDetector.cpp

please see here:
https://github.com/PX4/Firmware/issues/6651

landdetector: exit landing state if manual.z is larger than threshold

---

cmake/common/px4_base.cmake
src/drivers/bmi160/CMakeLists.txt
src/drivers/hmc5883/CMakeLists.txt
src/drivers/ist8310/CMakeLists.txt
src/drivers/l3gd20/CMakeLists.txt
src/drivers/lis3mdl/CMakeLists.txt
src/drivers/lps25h/CMakeLists.txt
src/drivers/lsm303d/CMakeLists.txt
src/drivers/meas_airspeed/CMakeLists.txt
src/drivers/mpu6000/CMakeLists.txt
src/drivers/mpu6500/CMakeLists.txt
src/drivers/mpu9250/CMakeLists.txt
src/drivers/px4fmu/CMakeLists.txt
src/drivers/test_ppm/CMakeLists.txt
src/platforms/qurt/fc_addon/mpu_spi/CMakeLists.txt
src/platforms/qurt/fc_addon/rc_receiver/CMakeLists.txt
src/platforms/qurt/fc_addon/uart_esc/CMakeLists.txt

- closes #7040
@bkueng @ndepal FYI

cmake remove -Weffc++

---

src/modules/fw_pos_control_l1/landingslope.cpp
src/modules/fw_pos_control_l1/landingslope.h

No functional change. Just deleting all the unused parts.

FW landingslope delete unused

---

src/modules/mavlink/mavlink_messages.cpp

mavlink EXTENDED_SYS_STATUS add takeoff and landing

---

Makefile
cmake/common/px4_base.cmake
cmake/nuttx/px4_impl_nuttx.cmake
msg/templates/uorb/msg.cpp.template
nuttx-patches/CMakeLists.txt
src/modules/px4iofirmware/CMakeLists.txt

- closes #6501
- closes #6820
- closes #6881

cmake cleanup nuttx dependency handling

---

src/modules/sensors/parameters.cpp

sensors init CAL_ACC0_ID and CAL_GYRO0_ID for QGC

---

src/modules/systemlib/bson/tinybson.c
src/modules/systemlib/bson/tinybson.h

Changed "private" keyword used for argument to "priv"

TinyBson - Compatibility with cpp compiler

---

src/modules/land_detector/LandDetector.cpp
src/modules/land_detector/MulticopterLandDetector.cpp
src/modules/land_detector/MulticopterLandDetector.h
src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/mc_pos_control/mc_pos_control_params.c

There are improvements to the land_detector to work well in altitude and one important fix for it in general.
I tried to make good commit messages.

Fix altitude mode takeoff and landing & general retakeoff delay

---

integrationtests/python_src/px4_it/mavros/mission_test.py
src/modules/commander/commander.cpp
src/modules/commander/commander_params.c
src/modules/commander/commander_tests/state_machine_helper_test.cpp
src/modules/commander/state_machine_helper.cpp
src/modules/commander/state_machine_helper.h
src/modules/systemlib/rc_check.c

- new parameter COM_ARM_MIS_REQ to require valid mission to arm (off by default)

commander add parameter COM_ARM_MIS_REQ

---

src/modules/mavlink/mavlink_messages.cpp

- fixes #6974 
This is kind of crude, but solves the problem in #6974 without making the mavlink module understand vtol states.

mavlink VFR_HUD throttle use first 2 groups

---

msg/actuator_armed.msg
src/modules/commander/commander.cpp
src/modules/uavcan/uavcan_main.cpp
src/modules/uavcan/uavcan_main.hpp

UAVCAN: disable ESCs when in VTOL fixed-wing

---

src/systemcmds/pwm/pwm.c

Prior to oneshot being added to the system. The -r of the
"rate" command would not invoke the ioctl PWM_SERVO_SET_UPDATE_RATE
when -r was not provided on the command line. This may have been a
feature or a bug.
When onshot was added to the pwm command a bug was introduced
that precluded the ioctl PWM_SERVO_SET_UPDATE_RATE from being
called on -r 0.
This commit fixes that issue, and preserves the "prio to oneshot"
behavior of the "rate" command when -r is not specified.

pwm:ensure that a rate of 0 will invoke the PWM_SERVO_SET_UPDATE_RATE ioctl

---

src/modules/sensors/voted_sensors_update.cpp

- fixes #7050
Probably worth taking a look at the QGC X-Plane interface to see if this can be improved.

sensors HIL increase gyro and accel timeout

---

src/modules/systemlib/mixer/mixer_multirotor.cpp

mixer_multirotor: switched to math::constrain a local implementation was used before which is not necessary

Switch mixer to math::constrain

---

src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/mc_pos_control/mc_pos_control_params.c

This pr is to contribute useful improvements of the position controller mostly from @Stifael and me.
These improvements already went through several multicopter flight tests.

Smooth takeoff for altitude controlled flights (including auto takeoff)

---

src/modules/mavlink/mavlink_receiver.cpp
src/modules/mavlink/mavlink_receiver.h

Implement [PLAY_TUNE](http://mavlink.org/messages/common#PLAY_TUNE)

Implement Mavlink PLAY_TUNE

---

README.md

@iZhangHui @rolandash
I've added a Mindpx label for any issues/PRs and added Henry to the main README as the maintainer.
https://github.com/PX4/Firmware/issues?q=is%3Aissue+is%3Aopen+label%3Amindpx

README add MindPX contact

---

README.md

@hamishwillee @mrpollo can you give this a quick review?
https://github.com/dagar/Firmware/blob/pr-readme/README.md

README update links and cleanup

---

msg/vehicle_local_position.msg
src/modules/ekf2/ekf2_main.cpp
src/modules/mc_pos_control/mc_pos_control_main.cpp

Fixes: #6193
TODO
Code review
Compatibility testing with LPE

Prevent height set-point variations due to bad GPS

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

When switching from manual to auto, the commander tell the mc_pos_control and the navigator that the vehicle is now in auto mode. This means that the mc_pos_controller uses the previous position triplet until the navigator sends the new triplet which results in a spike in position setpoints.
This pr is a fix but it is to note that the goal should be to free the position controller from commander where where in auto mode the mc_pos_controller only listens to the navigator,.

[WIP] mc_pos_control: switch to auto only if triplets have been updated

---

src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/navigator/mission_block.cpp
src/modules/navigator/navigator_main.cpp
src/modules/navigator/takeoff.cpp

~~There is still an issue with the takeoff where sometimes the vehicle follows a wrong triplet type. This results in a visible jerk during takeoff.~~

Pr takeoff fix

---

README.md

With great power comes great responsibility!

Add Jose as maintainer for Intel Aero.

---

src/drivers/aerofc_adc/aerofc_adc.cpp

Signed-off-by: Nicolae Rosia <nicolae.rosia@gmail.com>

aerofc_adc: fix error handling in init

---

src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/mavlink_stream.cpp

These are minor fixes that should help improve the stream rate handling and trigger forwarding.

Camera trigger and mavlink rate fixes

---

nuttx-patches/00027-BACKPORT-stm32-sdio-1-bit-and-16G-fix.patch
nuttx-patches/CMakeLists.txt

nuttx-patches FATAL_ERROR and include stm32-sdio-1-bit-and-16G-fix.patch

---

src/modules/commander/PreflightCheck.cpp

See https://github.com/PX4/Firmware/issues/7253

commander: enable partial preflight checks on RPI

---

src/modules/sensors/voted_sensors_update.cpp

@priseborough @LorenzMeier This properly fixes #7325. Please test.

Correctly handle internal magnetometer rotations

---

src/modules/commander/state_machine_helper.cpp

- coverity fix 145492
@lovettchris FYI

commander offboard loss rc act unreachable

---

.travis.yml

- moving to jenkins and merging the report with mission tests

travis-ci remove code coverage build and upload

---

src/platforms/posix/drivers/df_mpu9250_wrapper/df_mpu9250_wrapper.cpp

This PR moves the rotation of the raw mag data to just prior to application of the calibration offsets and scales. The method used for the mag rotation was also changed to match that of the accel and gyro rotations, but this was more for consistency as the previous method works fine as long as it is applied before the calibration.
In my case, testing with Aerotenna OcPoC-Zynq Mini flight controller, the df_mpu9250_wrapper requires a rotation of '-R 10' (Roll 180, Yaw 90), and the current driver (mag rotation after calibration) gives me nonsensical heading estimates.

DF_MPU9250_Wrapper: fix mag rotation

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

fixes transition  to auto mode

Pr triplet pos ctrl handling

---

ROMFS/px4fmu_common/init.d/rc.sensors
ROMFS/px4fmu_common/init.d/rcS
cmake/configs/nuttx_px4fmu-v2_default.cmake
src/drivers/sdp3x_airspeed/CMakeLists.txt
src/drivers/sdp3x_airspeed/SDP3X.cpp
src/drivers/sdp3x_airspeed/SDP3X.hpp
src/drivers/sdp3x_airspeed/SDP3X_main.cpp
src/modules/commander/PreflightCheck.cpp
src/modules/commander/commander.cpp
src/modules/sensors/sensors.cpp

General specs: Good from 0 m/s (it can register 1 m/s) up to 25 m/s / 60 mph / 100 km/h. Impressive sensitivity, virtually no offset. This should not require in-field calibration any more.
The graph below shows a log where I walked about 8 meters indoor from one table to another and put the sensor down. You can even see when I approached the desk at the end of the log - just moving close to it triggered some air circulation.

Sensirion SDP31 pressure sensor driver

---

src/modules/uavcan/sensors/gnss.cpp
src/modules/uavcan/sensors/gnss.hpp

Fixes #7421
Tested with Pixracer and Zubax GNSS2.0
@mhkabir 
@LorenzMeier

Set system real time clock once from GNSS data.

---

Tools/process_sensor_caldata.py

Needed to temperature calibrate full Pixhawk 2 sensor suite.

Add 2nd baro to offline temperature calibration script

---

Tools/ecl_ekf/batch_process_logdata_ekf.py

Just a quick fix to account for spaces in directories and files.

Fix bug in batch ecl_ekf parser

---

msg/CMakeLists.txt
msg/vehicle_global_velocity_setpoint.msg
src/examples/mc_pos_control_multiplatform/mc_pos_control.cpp
src/examples/mc_pos_control_multiplatform/mc_pos_control.h
src/modules/logger/logger.cpp
src/modules/mavlink/mavlink_receiver.h
src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/mc_pos_control/mc_pos_control_params.c
src/modules/sdlog2/sdlog2.c
src/platforms/px4_includes.h

- delete vehicle_global_velocity_setpoint (duplicated in vehicle_local_position_setpoint)
- mc_pos_control delete unused velocity feed forwards

delete unused vehicle_global_velocity_setpoint, MPC_XY_FF,  MPC_Z_FF

---

Tools/sitl_run.sh
posix-configs/SITL/init/ekf2/standard_vtol
src/platforms/posix/px4_layer/px4_posix_tasks.cpp

@bkueng Please review. This improves the reliability of the SITL setup.

SITL fixes

---

ROMFS/px4fmu_common/init.d/rc.fw_defaults

There is potentially a much larger issue here, but this should help in the meantime.
- closes https://github.com/PX4/Firmware/issues/7490
See: https://github.com/PX4/Firmware/issues/7261
FYI @davids5

FW default PWM_RATE 50

---

msg/estimator_status.msg

To match the definition in https://github.com/PX4/ecl/blob/master/EKF/common.h#L354
@priseborough @ChristophTobler

estimator_status.msg: fix documentation of innovation_check_flags

---

src/modules/navigator/mission_block.cpp

- fixes #7510 
I haven't figured out why next isn't populated, but this prevents the flyaway.
Tested in SITL. http://logs.px4.io/plot_app?log=2b554775-45c8-43c0-8be4-15d2ef9ff3bf
The MC yaw after VTOL back transition is wrong, but we can look at that later. FYI @sanderux

navigator mission_block check range for loiter exit

---

src/drivers/gps/gps.cpp
src/drivers/gps/params.c

Fixed wing launch regularly exceeds 2G.
Will flight test this week with EKF2 analysis before and after.
GPS driver PR - https://github.com/PX4/GpsDrivers/pull/25

GPS ublox add dynamic model parameter

---

Tools/px4airframes/markdownout.py
Tools/px4airframes/srcparser.py

Group airframes by type

---

src/drivers/mpu9250/mag.cpp
src/drivers/mpu9250/mag.h
src/drivers/mpu9250/mpu9250.cpp
src/drivers/mpu9250/mpu9250.h

This should fix the mag issues on PixhawkMini https://github.com/PX4/Firmware/issues/7327 and the odd Z reading on FMUv4Pro https://github.com/PX4/Firmware/issues/7541
@klopezal, @bresch, @gbrunso @PX4TestFlights - please give this a try. The console output will help debug this, it is still failing.

mpu 9250 fixes

---

posix-configs/eagle/200qx/px4.config
posix-configs/eagle/210qc/px4.config

Add GPS start command to 200qx and 210c configurations for Snapdragon

Add GPS start command to all eagle configs

---

ROMFS/px4fmu_common/init.d/rc.fw_defaults

FW EKF2 and ublox defaults

---

Tools/px_update_git_header.py
src/lib/version/version.c

Fixed the version tag to number to support numbers with more than one digit.
Also, changed it so that if there are any  local modifications the version will be a dev version.

Fixed the version naming

---

src/modules/uavcan/actuators/esc.cpp
src/modules/uavcan/actuators/esc.hpp

Publish actuator outputs also for the UAVCAN ESCs.

UAVCAN: Publish actuator outputs

---

posix-configs/SITL/init/ekf2/iris_opt_flow

Much more convenient for testing in SITL

stream distance sensor at 10Hz for SITL-EKF testing

---

README.md

Adds a badge for Slack, our group is open to everyone, you can auto-invite yourself through http://slack.px4.io/

Join us on Slack README badge

---

src/platforms/posix/drivers/accelsim/accelsim.cpp
src/platforms/posix/drivers/barosim/baro.cpp
src/platforms/posix/drivers/barosim/barosim.h
src/platforms/posix/drivers/df_ak8963_wrapper/df_ak8963_wrapper.cpp
src/platforms/posix/drivers/df_bebop_rangefinder_wrapper/df_bebop_rangefinder_wrapper.cpp
src/platforms/posix/drivers/df_bmp280_wrapper/df_bmp280_wrapper.cpp
src/platforms/posix/drivers/df_hmc5883_wrapper/df_hmc5883_wrapper.cpp
src/platforms/posix/drivers/df_isl29501_wrapper/df_isl29501_wrapper.cpp
src/platforms/posix/drivers/df_lsm9ds1_wrapper/df_lsm9ds1_wrapper.cpp
src/platforms/posix/drivers/df_mpu6050_wrapper/df_mpu6050_wrapper.cpp
src/platforms/posix/drivers/df_mpu9250_wrapper/df_mpu9250_wrapper.cpp
src/platforms/posix/drivers/df_ms5607_wrapper/df_ms5607_wrapper.cpp
src/platforms/posix/drivers/df_ms5611_wrapper/df_ms5611_wrapper.cpp
src/platforms/posix/drivers/df_trone_wrapper/df_trone_wrapper.cpp
src/platforms/posix/drivers/gyrosim/gyrosim.cpp

Current driver was copy pasted from a MS5611 driver.
The existing driver takes data from Simulator, not from
an actual device.
Signed-off-by: Nicolae Rosia <nicolae.rosia@gmail.com>

barosim: revamp driver

---

src/modules/ekf2/ekf2_main.cpp
src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/simulator/simulator.h
src/modules/systemlib/battery.cpp

Found with valgrind
@priseborough @Stifael please review

Fix uninitialized variables

---

posix-configs/SITL/init/ekf2/typhoon_h480
src/modules/mavlink/mavlink_messages.cpp
src/modules/navigator/mission_block.cpp

This PR enables full survey validation on this target in SITL:
```make posix gazebo_typhoon_h480```
This yields the following results:
Images are stored in ```Firmware/build_../tmp/frames```

Enable the validation of survey missions in SITL

---

src/modules/mavlink/mavlink_messages.cpp

This should enable anyone in need of these additional GPS fields. We had them all internally already but never exposed them.

MAVLink GPS accuracy

---

src/modules/simulator/simulator.h
src/modules/simulator/simulator_mavlink.cpp

includes https://github.com/PX4/sitl_gazebo/pull/114

update sitl_gazebo to use the vision position estimate

---

posix-configs/SITL/init/inav/iris

I found a bug that posix_sitl_inav does not work because of old task name
please check it
from SungTae Moon

fix the bug for posix_sitl_inav

---

src/modules/sensors/sensors.cpp

@dagar fixes CI in #7644 
When trying to move the selected power source to the first publication instance on systems where there is only one power source, the compiler issued the warning
```
../src/modules/sensors/sensors.cpp:512:54: error: array subscript is outside array bounds [-Werror=array-bounds]
tmp_h = _battery_pub[_battery_pub_intance0ndx];
```
because it could not verify that _battery_pub_intance0ndx would always be 0.
Fix: 
Wrap the block between `#if BOARD_NUMBER_BRICKS > 1 [...] #endif` to ensure no out of bound subscript and to remove the warning.
TODO:

sensors: check battery array bounds

---

src/modules/commander/commander.cpp
src/modules/commander/state_machine_helper.cpp

Minor improvements, mostly for convenience.

Commander: Handle HITL state in all places consistently

---

msg/templates/uorb/msg.cpp.template

We can afford a slower performance in this parsers with python2 to
keep compability with python3.
http://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html#xrange

msg: Fix build in python3

---

posix-configs/SITL/init/ekf2/standard_vtol
posix-configs/SITL/init/ekf2/tailsitter
posix-configs/SITL/init/lpe/standard_vtol
src/modules/land_detector/VtolLandDetector.cpp
src/modules/land_detector/VtolLandDetector.h

Fixes https://github.com/PX4/Firmware/issues/7737

Maybe-landed state for VTOL

---

src/lib/rc/rc_tests/RCTest.cpp
src/modules/ekf2_replay/ekf2_replay_main.cpp
src/modules/uORB/uORB_tests/uORBTest_UnitTest.cpp
src/platforms/posix/drivers/tonealrmsim/tone_alarm.cpp
src/systemcmds/sd_bench/sd_bench.c
src/systemcmds/tests/test_file2.c
src/systemcmds/tests/test_mount.c
src/systemcmds/tests/test_ppm_loopback.c
src/systemcmds/tests/test_uart_loopback.c

Fix issues identified by cppcheck including
* Resource leaks
* Memory leaks
* Uninitialized values

Cppcheck fixes

---

src/modules/land_detector/VtolLandDetector.cpp
src/modules/land_detector/VtolLandDetector.h

land_detector add missing header and init all vtol fields

---

.travis.yml
Tools/docker_run.sh
src/modules/px4iofirmware/protocol.h

- closes #7539 
@jlecoeur once this is passing the GCC 7 SITL build is working.

travis-ci add GCC7 SITL build and tests

---

Tools/check_code_style_all.sh

There are bugs in version 2.05.1 (default version in Ubuntu 16.04)

Removed support for astyle 2.05.1

---

src/modules/simulator/simulator.cpp
src/modules/simulator/simulator.h
src/modules/simulator/simulator_mavlink.cpp
src/modules/simulator/simulator_params.c

@DonLakeFlyer `SIM_BAT_DRAIN` should do it with this PR (in seconds).

Simulator: Make battery discharging configurable.

---

src/modules/systemlib/printload.c

We sometimes hit the maximum number of file descriptors, without knowing how many we currently use. This adds a column to the `top` command on NuttX, showing the number of used file descriptors for each task, together with the configured maximum.
This is on Pixracer:
```
0 Idle Task                   12758 44.859   596/  748   0 (  0)  READY  3
1 hpwork                        427  1.653   696/ 1780 192 (192)  w:sig 13
2 lpwork                         26  0.071   640/ 1780  50 ( 50)  w:sig  4
3 init                         4466  0.000  1680/ 2580 100 (100)  w:sem  3
414 top                           225  3.235  1296/ 1684 100 (100)  RUN    3
105 gps                            71  0.071  1056/ 1580 220 (220)  w:sig …
```

top: add a column for the number of used file descriptors

---

msg/actuator_armed.msg
src/modules/commander/state_machine_helper.cpp
src/modules/mavlink/mavlink_receiver.cpp
src/modules/mavlink/mavlink_receiver.h

Adding support for MAV_CMD_REQUEST_FLIGHT_INFORMATION to get flight information.
#7706

mavlink: implement MAV_CMD_REQUEST_FLIGHT_INFORMATION

---

src/drivers/ulanding/ulanding.cpp

@jgs2185 FYI VDev has merged into CDev.

ulanding delete VDev usage

---

src/modules/logger/logger.cpp

@sanderux quick test?
- fixes https://github.com/PX4/Firmware/issues/7911

logger update topics

---

src/modules/logger/logger.cpp

As discussed in https://github.com/PX4/flight_review/issues/60.

logger add manual_control_setpoint

---

src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/mc_pos_control/mc_pos_control_params.c
src/modules/navigator/mission.cpp
src/modules/navigator/navigator.h
src/modules/navigator/navigator_main.cpp

* removes scaling 
* removes slewrate for auto
* fixes overshoots in xy and z
* moves z foh to mc_pos_control
This auto logic is just temporary and will be moved to flight-task as a first step. 
As a second step an auto logic is added to flight-task which uses splines to generate smooth trajectories.

Auto logic refactor

---

src/modules/systemlib/param/param.c

param save is an expensive operation that can take several 100ms. And
previously it was possible that a param_get() caller was blocked on a
save operation. If this happened due to a param change notification,
important modules, such as sensors, could have been blocked for a longer
period (and affecting the flight performance).
With this patch, this situation is not possible anymore, because a param
save now uses the reader lock and a separate file lock.
However it is still possible that a param_set() needs to wait for a save
operation, thus blocking for a longer time. param_set() thus needs to be
avoided in important modules when the system is armed.
In the case of mavlink it works, since it does not affect the flight if
the mavlink receiver is blocked over a longer time. It is only …

param: use separate param save lock

---

src/drivers/px4fmu/fmu.cpp
src/drivers/px4io/px4io.cpp
src/modules/sensors/rc_params.c

QGC initiates the bind over mavlink.

delete unused RC_DSM_BIND param

---

src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/mc_pos_control/mc_pos_control_params.c

This Pr is the same as [here](https://github.com/PX4/Firmware/pull/7242), but squash merged and rebased.

mc_pos_control: smooth positon control from stick input

---

src/modules/mavlink/mavlink_receiver.cpp

Mavlink receiver COMMAND_INT and COMMAND_LONG didn't handle the same set of commands.

mavlink receiver sync COMMAND_INT/COMMAND_LONG

---

msg/system_power.msg
src/drivers/stm32/adc/adc.cpp

@dagar Superseded https://github.com/PX4/Firmware/pull/8022

Fixed typo usb_vaild ->  usb_valid

---

src/systemcmds/hardfault_log/hardfault_log.c

- The hardfault keeps track of the number of reboot without a
commit to disk. A commit to disk is the act of writing the
fault data from the bbsram to the hardfault file, not the
ulog file. The sucessful commit rearms the hardfault system.
When ulog appending was added it treated the lack of a ulog
file as an error. This prevented the `hardfault_log reset`
from being called because the `hardfault_log commit` returned
an error.
```
if hardfault_log check
then
if hardfault_log commit
then
hardfault_log reset
fi
fi
```
This change treats the lack a a ulog as a non error.

hardfault_log:Not having a ulog file to append to is not an error

---

src/modules/commander/PreflightCheck.cpp
src/modules/commander/PreflightCheck.h
src/modules/commander/commander.cpp
src/modules/commander/state_machine_helper.cpp

ekf2Check was running regardless of an estimator_status update and not initializing the struct.

commander preflight ekf2 check estimator_status

---

src/lib/controllib/block/Block.hpp
src/modules/ekf2/ekf2_main.cpp
src/modules/ekf2/ekf2_params.c

@priseborough Could you please check and add the parameter descriptions?
I still get the error:
```
ERROR [lib__controllib] exceeded max params for block: EKF2
```

ekf2 update

---

msg/vehicle_attitude_setpoint.msg
src/modules/mc_pos_control/mc_pos_control_main.cpp

During our work with PX4 we stumbeled upon and fixed a lot of smaller issues which are now hard to track back one by one. Nevertheless we want to contribute this work and hence I'm doing this pull request.
There is:
- refactoring spaces and names
- altitude limitation improvement
- mission flight corner behaviour improvement

Positon Controller: multiple small refinements

---

src/drivers/ist8310/ist8310.cpp

The IST driver did not optimally check the calibration result and could trigger false positives if the mag data aligned with wrong signs.

IST8310 driver: Fix startup / calibration order

---

src/modules/land_detector/land_detector_params.c
src/modules/mc_pos_control/mc_pos_control_main.cpp
src/modules/navigator/enginefailure.cpp
src/modules/navigator/follow_target.cpp
src/modules/navigator/land.cpp
src/modules/navigator/loiter.cpp
src/modules/navigator/mission.cpp
src/modules/navigator/mission_block.cpp
src/modules/navigator/mission_block.h
src/modules/navigator/navigator.h
src/modules/navigator/rcloss.cpp
src/modules/navigator/rtl.cpp
src/modules/navigator/rtl.h
src/modules/navigator/takeoff.cpp
src/modules/systemlib/battery.cpp

fixes https://github.com/PX4/Firmware/issues/7309

Pr altitude max fix

---

src/drivers/px4fmu/fmu.cpp

- initialize rc lost with true
- refactor for simpler downstream code-plugin
- allow for the addition of different binding commands
- fix st24 RC lost logic

fmu: minor refactoring & fixes

---

src/modules/attitude_estimator_q/attitude_estimator_q_main.cpp

- remove unused airspeed subscription and estimator status publication
- remove accel low pass filter (same filter is in the drivers)
- update task priority to use define

attitude_estimator_q remove unused

---

posix-configs/SITL/init/ekf2/typhoon_h480

We need the gimbal attitude and attitude quaternion messages in DroneCore.

Add a few mavlink messages to Typhoon H480 SITL

---

README.md

Adding Sugnan Prabhu as maintainer for Intel Aero.
With great power comes great responsibility!

Adding Sugnan as maintainer for Intel Aero

---

.travis.yml

Stop annoying people until fixed. https://github.com/PX4/Firmware/issues/8131

travis-ci allow coverage failures

---

src/modules/local_position_estimator/sensors/lidar.cpp

Fixes https://github.com/PX4/Firmware/issues/8163.

modules: lpe: fix double correction on lidar

---

src/modules/mc_pos_control/mc_pos_control_main.cpp

avoid abrupt position changes in manual as the estimated delta can be quite big depending on deadreckoning/imu (see https://github.com/PX4/Firmware/issues/8151).

reset setpoint to current position

---

Tools/jmavsim_run.sh

This brings the jMAVSim upgrade from https://github.com/PX4/jMAVSim/pull/62 with better textures and improved rendering settings:
@hamishwillee fyi

New Look for jMAVSim

---

src/drivers/vmount/vmount.cpp

Fixes issue #8178.
Does not interact with #8149 (fyi @mje-nz and @bkueng).

Fix type of MNT_OB_LOCK_MODE and MNT_OB_NORM_MODE parameters

---

src/modules/ekf2/ekf2_main.cpp

See comments here for background: https://github.com/PX4/Firmware/pull/8199

Fix bugs introduced by PR 8199

---

src/modules/sensors/voted_sensors_update.cpp

sensors ignore invalid failover index

---

src/systemcmds/esc_calib/esc_calib.c

esc_calib properly cleanup on failure

---

src/modules/mavlink/mavlink_parameters.cpp

mavlink parameters initialize struct

---

src/drivers/vmount/input_mavlink.cpp
src/drivers/vmount/input_mavlink.h
src/drivers/vmount/vmount.cpp

vmount initialize params

---

src/drivers/protocol_splitter/protocol_splitter.cpp

Fixing compilation warnings which are treated as errors.

Fix protocol_splitter compilation issues

---

src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp
src/modules/local_position_estimator/BlockLocalPositionEstimator.hpp
src/modules/local_position_estimator/sensors/baro.cpp
src/modules/local_position_estimator/sensors/flow.cpp
src/modules/local_position_estimator/sensors/gps.cpp
src/modules/local_position_estimator/sensors/land.cpp
src/modules/local_position_estimator/sensors/lidar.cpp
src/modules/local_position_estimator/sensors/mocap.cpp
src/modules/local_position_estimator/sensors/sonar.cpp
src/modules/local_position_estimator/sensors/vision.cpp

This PR:
1. removes unused subscriber to manual_control_setpoint;
2. correctly publishes the innovation covariance to `ekf2_innovations`;
3. updates `_sensorTimeout` and `_sensorFault` to handle support of more sensor sources (ex: https://github.com/PX4/Firmware/pull/8160 - landing targets)
@ndepal does this fit your needs?
@jgoppert can you review, please?

modules: lpe: small updates and fixes

---

src/modules/ekf2/ekf2_main.cpp

Addresses  loss of height accuracy during sustained yaw spinning and vulnerability to transient sensor errors after in-flight yaw alignment. See:
https://github.com/PX4/ecl/pull/350
https://github.com/PX4/ecl/pull/354
Note the amount of stack allocation has had to be increased to accomodate the potential for larger data buffers created by PR350
One hardware test using a pixracer board https://logs.px4.io/plot_app?log=f3f3826d-f8a7-4fac-91ed-f57c4a2945c1

ecl: Update ekf2 to version that addresses known vulnerabilities
