src/modules/mavlink/mavlink_parameters.cpp
If a MAP_RC_PARAM message is sent with an index > 2, this would lead to undefined behaviour or a segfault/hardfault.
=> mavlink: check index for out-of-bounds

ROMFS/px4fmu_common/init.d/rc.sensors, src/drivers/distance_sensor/vl53l1x/params.c
SENS_EN_VL53L1X parameter is implemented.
Tests
The changes successfully compiled for px4_fmu-v2. 
The driver automatically started, when the parameter is greater than 0.
The driver didn't start, when the parameter is 0.
=> SENS_EN_VL53L1X parameter is implemented to enable VL53L1X distance sensor

boards/px4/fmu-v4pro/default.cmake
The DShot driver is not built in the default.cmake of fmu-v4pro boards. This board has enough flash memory to add this driver.
Enable DShot driver in the default.cmake of fmu-v4pro.
Flashed on a Pixhawk 3 Pro and DSHOT_CONFIG parameter checked.
=> Enable dshot driver for fmu-v4pro

src/lib/airspeed_validator/AirspeedValidator.cpp
The wind estimator uses either true airspeed measurement or sideslip measurement to initialise, whichever comes first.
It makes more sense to initialize with true airspeed as it's more accurate.
Initialize with true airspeed instead.
Flight tested on multiple vehicles.
The plots below show the wind estimates for the main ekf and the wind estimators. At 60s the wind is switched from south wind to west wind. Initialization works as expected (note that instance 02 only uses sideslip measurements and thus converges slower)
=> AirspeedValidator: fuse true airspeed before sideslip

src/modules/vtol_att_control/tiltrotor.cpp
Currently, for tiltrotor the back transition only is finished once the back transition duration is over (VT_B_TRANS_DUR). In high head wind this could lead to situations where the vehicle flies backwards before switching to MC mode. 
Switch to MC mode if either duration is over or groundspeed is below MPC_CRUISE. Similar logic is already in place for standard VTOLs. 
Flight tested on multiple vehicles.
=> Tiltrotor: allow to finish transition if groundspeed is below cruise

src/modules/logger/logged_topics.cpp
We missed some uORB topics from the default log in our recent flight tests:
- transponder_report (ADS-B, UTM_GLOBAL_POSITION) is needed to analyze collision avoidance features, e.g. in UTM systems currently under development
- Publishing of satellite information (uORB satellite_info/ MAVLink GPS_STATUS) can be enabled in the gps driver, but will not be logged at all.
- transponder_report will be logged at full data rate by default
- satellite_info will be logged as part of the debug group. 1 Hz and 2 GPS receivers should be enough?
I don't know, whether it might make more sense to add these two topics to other groups. Please let me know, if I should move them around.
I just want …
=> Also log transponder_report and satellite_info

platforms/common/include/px4_platform_common/module.h, platforms/posix/src/px4/common/tasks.cpp, src/drivers/gps/gps.cpp, src/modules/mavlink/mavlink_main.cpp, src/modules/simulator/simulator.cpp, src/modules/vmount/vmount.cpp, src/systemcmds/tests/test_dataman.c
This is a retry of #12200.
It looks like the behaviour of `px4_task_spawn_cmd` has been fixed in the meantime and the changes from https://github.com/PX4/PX4-Autopilot/pull/12200/commits/51fcd66be1c9ac18c93fc6e7288ba893766f08a3 are no longer required.
I've mostly just removed the remaining ifdefs for NuttX around this.
=> Args consistency between Posix and NuttX

src/lib/flight_tasks/tasks/Auto/FlightTaskAuto.cpp, src/lib/flight_tasks/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.cpp, src/lib/flight_tasks/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.hpp
This creates more rounded turns in multirotor mission using l1-style guidance logic in corners.
Example of what can be done (default acc/jerk, acceptance radius of from 2m to 8m):
https://logs.px4.io/plot_app?log=616bf543-eb2f-44a8-90fa-63cc4b7795f6
- This will only change mission flights
- The drone doesn't stop at each waypoint but decelerates to make a turn at constant speed
- The turning radius is defined by the waypoint acceptance radius `NAV_ACC_RAD`
- A wide range of accelerations (`MPC_ACC_HOR`), jerk (`MPC_JERK_AUTO`) and velocities (`MPC_XY_CRUISE`) should work.
- Use [MPC_YAW_MODE](https://dev.px4.io/master/en/advanced/parameter_reference.html#MPC_YAW_MODE) "along trajectory" for a nice yaw coordinated turn
Other example:
=> Multicopter rounded turns

src/lib/systemlib/system_params.c, src/modules/commander/commander_params.c
There are duplicates terms in param descriptions etc (e.g "the the"). This removes them.
=> Remove duplicate terms in text that is exported

src/modules/ekf2/EKF2.cpp
=> ekf2: fix dist bottom constraint

msg/vehicle_imu_status.msg, src/modules/sensors/vehicle_acceleration/VehicleAcceleration.cpp, src/modules/sensors/vehicle_acceleration/VehicleAcceleration.hpp, src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp, src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.hpp, src/modules/sensors/vehicle_imu/VehicleIMU.cpp
Rather than all of these separate WorkItems independently calculating the sample rate for accel or gyro this PR updates `sensors/vehicle_angular_velocity` and `sensors/vehicle_acceleration` to always use the value calculated by the integrator(s) and published in `vehicle_imu_status`.
Small prelude before https://github.com/PX4/PX4-Autopilot/pull/15820.
=> sensors: filtered control data (accel & gyro) always get measured sample rate from vehicle_imu_status

src/lib/parameters/parameters.cpp
- param_export() already takes the shutdown lock
=> parameters: remove unnecessary shutdown lock in param_save_default()

platforms/posix/cmake/sitl_target.cmake
Building sitl_gazebo in parallel within PX4 can occasionally cause a fast Ubuntu machines to effectively lock up. For now I'll limit the build to a single thread to be safe.
=> sitl_gazebo build single threaded

src/modules/mavlink/streams/ALTITUDE.hpp
The local position timestamp is checked later on and this makes valgrind happy.
=> mavlink: ALTITUDE stream initialize local_pos

src/modules/mc_hover_thrust_estimator/MulticopterHoverThrustEstimator.cpp, src/modules/mc_hover_thrust_estimator/MulticopterHoverThrustEstimator.hpp, src/modules/mc_hover_thrust_estimator/zero_order_hover_thrust_ekf.cpp, src/modules/mc_hover_thrust_estimator/zero_order_hover_thrust_ekf.hpp, src/modules/mc_hover_thrust_estimator/zero_order_hover_thrust_ekf_test.cpp
requires #16401 
The hover thrust estimator (HTE) starts at arming and learns an initial biased value because the vehicle is still touching ground.
It recovers after takeoff but this takes quite some time.
1. Only start to run once truly in air:
Starting the estimator before takeoff makes it converge to a wrong initial value; once the variance is low, it takes then some time to recover after takeoff. The `_landed` flag only is not enough to tell if the drone is still touching ground or not. An additional check based on the altitude AGL is required.
2. Schedule on `vehicle_local_position` instead of `vehicle_position_setpoint`:
To have this in_air detection correctly updated, the module needs to be scheduled on the …
=> Hover thrust estimator improvements

.github/workflows/compile_macos.yml
This commit re-enables SITL testing on macOS
This was removed with intermittent SITL failures in https://github.com/PX4/PX4-Autopilot/pull/15234
- Gazebo builds are being tested in macos-10.15 and macos-11.0 in `sitl_gazebo` : https://github.com/PX4/PX4-SITL_gazebo/pull/663, but the unfortunately firmware is unable to build on Big Sur (macos-11.0)
- Fixes https://github.com/PX4/PX4-Autopilot/issues/15225
- Fixes https://github.com/PX4/PX4-Autopilot/issues/15476
=> Enable SITL tests for macos

src/modules/mavlink/mavlink_ftp.cpp
The MAVLink specs for CreateFile in MAVLink FTP were updated on Dec 23, 2020 (today) with a behavior change to truncate a file if it already existed, following the UNIX standard behavior: https://pubs.opengroup.org/onlinepubs/9699919799/functions/creat.html. This change is tracking that spec change. While it is a functional change, the limited usage of the FTP protocol and the fact that implementations should not rely on error states to determine wether to truncate a file or not makes this a viable change.
=> MAVLink FTP: Update implementation according to updates specs

Tools/setup/requirements.txt
currently installing `pymavlink` without the wheel package results in an error when using Python 3.7 or later
https://github.com/ArduPilot/pymavlink/issues/486
=> Tools: Python >3.7 requires the wheel packge

src/modules/vtol_att_control/standard.cpp, src/modules/vtol_att_control/tailsitter.cpp, src/modules/vtol_att_control/tiltrotor.cpp, src/modules/vtol_att_control/vtol_type.cpp, src/modules/vtol_att_control/vtol_type.h
MC actuators are at disarmed value instead of idle value when back-transition of a standard VTOL is started. 
It is set correctly for tiltrotors.
Sets the PWM for the MC actuators to idle during back-transition, such that they are always spinning.
SITL tested.
=> Standard VTOL: set idle PWM for MC during backtransition

platforms/posix/cmake/sitl_target.cmake
For some reason, the yosemite world was not in the SITL target list
This commit adds yosemite world as a SITL target for gazebo
Tested with the following make target
```
make px4_sitl gazebo_iris__yosemite
```
=> Add yosemite world as SITL target for gazebo

src/modules/uORB/uORB_tests/uORBTest_UnitTest.cpp, src/modules/uORB/uORB_tests/uORBTest_UnitTest.hpp, src/modules/uORB/uORB_tests/uORB_tests_main.cpp, src/systemcmds/tests/test_perf.c
Stripping down the uORB latency tests to a single test topic (orb_test) is sufficient and allows cleaning up some of the mess mixing multiple topics in `uORBTest::UnitTest::pubsublatency_main()`.
=> uORB: tests limit latency to only orb_test and remove some unnecessary output

msg/battery_status.msg, src/modules/mavlink/mavlink_messages.cpp
Mavlink message SMART_BATTERY_INFO changed the serial_number field from uint to string. so this change fixes that.
set the serial number with this format: 'dd/mm/yy-123456'
=> format smart battery serial number as string on mavlink

src/lib/conversion/RotationTest.cpp, src/lib/conversion/rotation.cpp, src/lib/conversion/rotation.h, src/modules/commander/mag_calibration.cpp, src/modules/mavlink/mavlink_messages.cpp, src/modules/sensors/sensor_params.c, src/modules/sensors/sensor_params_acc0.c, src/modules/sensors/sensor_params_acc1.c, src/modules/sensors/sensor_params_acc2.c, src/modules/sensors/sensor_params_acc3.c, src/modules/sensors/sensor_params_gyro0.c, src/modules/sensors/sensor_params_gyro1.c, src/modules/sensors/sensor_params_gyro2.c, src/modules/sensors/sensor_params_gyro3.c, src/modules/sensors/sensor_params_mag0.c, src/modules/sensors/sensor_params_mag1.c, src/modules/sensors/sensor_params_mag2.c, src/modules/sensors/sensor_params_mag3.c
- duplicate of 31 (ROLL_90_PITCH_180)
- removed in https://github.com/mavlink/mavlink/pull/1540
This was only added to PX4 earlier this year (https://github.com/PX4/PX4-Autopilot/pull/14512). Unless anyone objects I'm not going to bother handling the parameter migration because it will only complicate further additions.
=> remove rotation 41 (ROLL_270_YAW_180)

ROMFS/px4fmu_common/init.d/airframes/10015_tbs_discovery, ROMFS/px4fmu_common/init.d/airframes/10016_3dr_iris, ROMFS/px4fmu_common/init.d/airframes/10017_steadidrone_qu4d, ROMFS/px4fmu_common/init.d/airframes/10018_tbs_endurance, ROMFS/px4fmu_common/init.d/airframes/1002_standard_vtol.hil, ROMFS/px4fmu_common/init.d/airframes/12002_steadidrone_mavrik, ROMFS/px4fmu_common/init.d/airframes/13000_generic_vtol_standard, ROMFS/px4fmu_common/init.d/airframes/13001_caipirinha_vtol, ROMFS/px4fmu_common/init.d/airframes/13003_quad_tailsitter, ROMFS/px4fmu_common/init.d/airframes/13005_vtol_AAERT_quad, ROMFS/px4fmu_common/init.d/airframes/13006_vtol_standard_delta, ROMFS/px4fmu_common/init.d/airframes/13007_vtol_AAVVT_quad, ROMFS/px4fmu_common/init.d/airframes/13008_QuadRanger, ROMFS/px4fmu_common/init.d/airframes/13009_vtol_spt_ranger, ROMFS/px4fmu_common/init.d/airframes/13012_convergence, ROMFS/px4fmu_common/init.d/airframes/13013_deltaquad, ROMFS/px4fmu_common/init.d/airframes/13200_generic_vtol_tailsitter, ROMFS/px4fmu_common/init.d/airframes/3031_phantom, ROMFS/px4fmu_common/init.d/airframes/3032_skywalker_x5, ROMFS/px4fmu_common/init.d/airframes/3033_wingwing, ROMFS/px4fmu_common/init.d/airframes/3035_viper, ROMFS/px4fmu_common/init.d/airframes/3036_pigeon, ROMFS/px4fmu_common/init.d/airframes/4014_s500, ROMFS/px4fmu_common/init.d/airframes/4031_3dr_quad, ROMFS/px4fmu_common/init.d/airframes/50000_generic_ground_vehicle
This PR is removing configurations that are not supported on V2 (like VTOL) and is trimming down fixed wing configurations. It is also adding a warning to v2 uploads that people really should be upgrading their bootloader and be using v3.
This is clawing back a whopping 22K of memory (2.2% of 1020169 bytes)
```
[482/485] Linking CXX executable px4_fmu-v2_default.elf
Memory region         Used Size  Region Size  %age Used
flash:     1020169 B      1008 KB     98.84%
sram:       25144 B       192 KB     12.79%
ccsram:          0 GB        64 KB      0.00%
```
=> Pr fmuv 2 exclude unsupported

boards/modalai/fc-v1/default.cmake
**problem solved by this pull request**
To get current and voltage readings from escs when no power module is included
**solution**
Add the new esc_battery module to the fc-v1 build
With the esc_battery module included in a custom build, my voxl-flight now reads out the voltage and current readings from the escs. This was done by using the daily build of QGC and selecting Source as ESCs
=> add esc_battery module to modalai/fc-v1 build

src/modules/commander/Commander.cpp
Minor change to avoid incorrectly sending an error if already landing and LAND is requested again (both CMD_NAV_LAND and CMD_NAV_PRECLAND).
=> commander: CMD_NAV_LAND/CMD_NAV_PRECLAND reply RESULT_ACCEPTED unless transition is denied

src/modules/camera_feedback/CameraFeedback.cpp, src/modules/camera_feedback/CameraFeedback.hpp
If the feedback module is loaded then we want to provide capture feedback.
=> Fixes #16467: Camera feedback: Indicate success

src/drivers/tone_alarm/ToneAlarm.cpp, src/modules/simulator/simulator_mavlink.cpp, test/mavsdk_tests/autopilot_tester.h
Depending on loop iterations for timeouts is not accurate, as usleep behavior depends on the system load and asking for a 0 ms sleep can potentially return immediately.
=> MAVSDK tests: Use full system timeout off

ROMFS/px4fmu_common/init.d/rcS, boards/px4/fmu-v5/init/rc.board_defaults
- avoid keeping this kind of logic in the common rcS
**TODO:** Is the CUAV v5 Nano V560 or V600?
https://github.com/PX4/PX4-Autopilot/blob/adb98d57022dd515e0a2056341280200576deffb/ROMFS/px4fmu_common/init.d/rcS#L283
https://github.com/PX4/PX4-Autopilot/blob/adb98d57022dd515e0a2056341280200576deffb/boards/px4/fmu-v5/src/manifest.c#L157-L163
=> boards: px4/fmu-v5 disable px4io in rc.board_defaults

src/modules/navigator/mission.cpp
This caused the navigator to use the next waypoint (after the vtol takeoff item)
to be used as target during the transition. If the altitude of that waypoint
was much higher than the takeoff altitude then there were FOH effects
after the transition which caused the vehicle to first descend before
climbing again.
Signed-off-by: RomanBapst <bapstroman@gmail.com>
=> Fix FOH effects after VTOL front transition

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueue.hpp, platforms/common/px4_work_queue/WorkQueue.cpp, src/modules/attitude_estimator_q/attitude_estimator_q_main.cpp, src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp, src/modules/ekf2/EKF2Selector.cpp, src/modules/ekf2/EKF2Selector.hpp, src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp, src/modules/local_position_estimator/BlockLocalPositionEstimator.hpp, src/modules/sensors/sensors.cpp
One problem with lockstep is that other than the inner loop (gyro -> rate controller -> output) we don't really have a defined set of "work" that runs every step. The purpose of this change is to ensure that in SITL lockstep every scheduled WorkItem is allowed to run to completion per step. This includes WorkItems scheduled by WorkItems (directed graph).
- per workqueue register a lockstep component whenever a work item is added (if not already registered)
- once the work queue is empty unregister component
- see https://github.com/PX4/PX4-Autopilot/pull/16479 for testing
=> px4_work_queue: directly support SITL lockstep

src/lib/mixer/MixerBase/Mixer.hpp, src/lib/mixer/MixerGroup.cpp, src/lib/mixer/MixerGroup.hpp, src/lib/mixer/SimpleMixer/SimpleMixer.cpp, src/lib/mixer/SimpleMixer/SimpleMixer.hpp, src/lib/mixer_module/mixer_module.cpp, src/lib/mixer_module/mixer_module.hpp, src/modules/px4iofirmware/mixer.cpp
Some actuators don't like it if their setpoint changes too quickly, e.g. as it increases wear on the actuator and increases likelihood of failure. To this end, there exists already the possibility to add slew rate limiting on the Multicopter mixer (see `MOT_SLEW_MAX`). But not yet on simple mixers, used for control of servos mainly. 
This adds the option to limit the rate of change (slew rate) of an output that's mixed by a simple mixer.
To enable it, a positive number has to be added at the end (6th number) of the output scaler line of the mixer,
specifying the min rise time of this output.
E.g. O:      10000  10000      0 -10000  10000 20000 for a rise time of 2s, resp. a max slew rate of 0.5s^-1.
E.g. for a min …
=> Simple mixer: add output slew rate

.ci/Jenkinsfile-hardware
This has board has been removed for developing https://github.com/PX4/PX4-Autopilot/pull/16444.
=> Jenkins hardware temporarily remove px4_fmu-v2

src/modules/vtol_att_control/standard.cpp, src/modules/vtol_att_control/tiltrotor.cpp, src/modules/vtol_att_control/vtol_att_control_main.cpp, src/modules/vtol_att_control/vtol_type.cpp, src/modules/vtol_att_control/vtol_type.h
This is some refactoring of the VTOL PWM settings, that are used to switch off the MC motors in fixed-wing. 
With this changes it's also possible to do add logic for the activation/deactivation of some motors without vtol state changes (e.g. for tiltrotor where all motors are tilted forward in fixed-wing flight, but not all are needed always).
- main motors are the ones which are meant to be used as propulsion in fw mode
- alternate motors are the ones usually meant to be switched off in fw mode
SITL tested with all 3 VTOL types.
=> vtol: refactor of maximum pwm value settings for main and alternate motors

src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp
The EKF module uses true airspeed as published by the sensors module, however this is not corrected for scale factor errors that can be estimated by the wind estimator and corrected using the ASPD_SCALE parameter that is applied to the true airspeed published by the airspeed_selector module. The effect of a scale factor error, learned and applied by the airspeed_selector, but not on the airspeed as used by the EKF is shown below using data from a flight where the uncorrected scale factor in airspeed data used by the EKF resulted in a significant along track position error when dead reckoning without GPS:
The innovations and learned wind states for the EKF (using uncorrected airspeed) and sensor_selector wind estimator (using scale factor corrected airspeed) is shown below and causes large …
=> Correct airspeed used by EKF for calibration errors

src/modules/commander/Commander.cpp
> The case when acceleration setpoints were being passed in offboard mode was triggering control_climbrate_mode. This prevented the vehicle from taking off, since it made the vehicle skip the rampup phase of the takeoff
This commit fixes this by handling the case properly
Port @Jaeyoung-Lim 's important fix from https://github.com/PX4/PX4-Autopilot/pull/15707 to make acceleration setpoints work through the offboard interface. The acceleration based takeoff needs further investigation to not cause unwanted side-effects when a feed-forward is used.
@Jaeyoung-Lim tested and I can clearly see why it was failing before with this incorrect condition.
We could add MAVSDK …
=> Enable offboard acceleration setpoints

src/lib/flight_tasks/tasks/Orbit/CMakeLists.txt, src/lib/flight_tasks/tasks/Orbit/FlightTaskOrbit.cpp, src/lib/flight_tasks/tasks/Orbit/FlightTaskOrbit.hpp, src/lib/slew_rate/CMakeLists.txt, src/lib/slew_rate/SlewRateYaw.hpp, src/lib/slew_rate/SlewRateYawTest.cpp, src/modules/commander/state_machine_helper.cpp
- The yaw setpoint during orbit approaches by previous design makes steps.
- Found during pr testing: Orbit not usable without RC
- Put slew rate calculation for yaw used in mission into a library `SlewRateYaw`
It uses the existing `SlewRate` library but extends with correct handling of shortest turn deliberation and pi wrapping from https://github.com/PX4/PX4-Autopilot/pull/11920
- Allow Orbit without RC in commander only data link loss triggers failsafe
- Simplify circling yaws setpoint calculations based on my new knowledge.
- Use `SlewRateYaw` in Orbit to smooth out the absolute yaw setpoints
I did not use `SlewRateYaw` in missions yet because there's slightly more …
=> Orbit Approach Smooth Yaw

src/modules/uuv_att_control/uuv_att_control.cpp, src/modules/uuv_att_control/uuv_att_control.hpp, src/modules/uuv_att_control/uuv_att_control_params.c
Now it's possible to skip the uuv_att_control module's controller and feed the setpoint to the mixer. 
So the companion computer can either send attitude setpoints and the onboard geometric controller of the uuv_att_control module controls the vehicle or the companion computer can send setpoints that are fed through the UUV's mixer. This depends on the UUV_SKIP_CTRL parameter.
=> UUV introduce param to skip controller

Tools/gazebo_sitl_multiple_run.sh, launch/multi_uav_mavros_sitl.launch, launch/single_vehicle_spawn.launch
This PR complements PR https://github.com/PX4/PX4-SITL_gazebo/pull/687 in PX4_SITL_gazebo repo. This is to enable multi-video stream in SITL 
Parameterizing the communication ports were required in order to differentiate the different streams from different MAVLink cameras, see PR https://github.com/PX4/PX4-SITL_gazebo/pull/687.
**Testing**
* Use this PR, and PR https://github.com/PX4/PX4-SITL_gazebo/pull/687, and then run [multi_uav_mavros_sitl.launch](https://github.com/mzahana/Firmware/blob/pr_multi_video_stream_sitl/launch/multi_uav_mavros_sitl.launch)
* Run QGroundcontrol. You should get the right video stream when you switch vehicles in QGC
=> Update launch files to enable multi-video stream in SITL

msg/log_message.msg, platforms/common/px4_log.cpp
Wherever possible I want to reduce dependence on console and mavlink messages for log review, but there are still situations where we seem to be dropping these.
=> log_message increase queue depth 2->4

src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp, src/modules/uORB/PublicationMulti.hpp
This ensures that ekf2 instance numbering is consistent with uORB publication instances.
For convenience when comparing logged output with specific messages.
=> ekf2: multi instance numbering consistent with uORB publication instances

src/modules/mavlink/mavlink_receiver.cpp
Previously the `coordinate_frame` field in the mavlink message `SET_POSITION_TARGET_GLOBAL_INT` message was not handled correctly. This results in the vehicle not being able handle relative altitude when controlling the vehicle in offboard mode with global position setpoints.
This PR parses the coordinate_frame flag and applies the relative altitude correctly, when the coordinate frame is defined as `MAV_FRAME_GLOBAL_RELATIVE_ALT_INT`
If the coordinate frame is unknown, the behavior falls back to the default behavior considering the altitude as global altitude.
Tested by sending global position setpoints through mavros on topic `~setpoint_raw/global` with coordinate_frame = 6
**Additional …
=> Support relative altitude for offboard global position setpoints

.ci/Jenkinsfile-hardware, boards/av/x-v1/init/rc.board_defaults, boards/cuav/nora/init/rc.board_defaults, boards/cuav/x7pro/init/rc.board_defaults, boards/cubepilot/cubeorange/init/rc.board_defaults, boards/cubepilot/cubeyellow/init/rc.board_defaults, boards/holybro/durandal-v1/init/rc.board_defaults, boards/holybro/pix32v5/init/rc.board_defaults, boards/modalai/fc-v1/init/rc.board_defaults, boards/mro/ctrl-zero-f7/init/rc.board_defaults, boards/mro/pixracerpro/init/rc.board_defaults, boards/mro/x21-777/init/rc.board_defaults, boards/px4/fmu-v4pro/init/rc.board_defaults, boards/px4/fmu-v5/init/rc.board_defaults, boards/px4/fmu-v5x/init/rc.board_defaults, boards/px4/fmu-v6x/init/rc.board_defaults, posix-configs/rpi/pilotpi_mc.config, posix-configs/rpi/px4.config, posix-configs/rpi/px4_fw.config, posix-configs/rpi/px4_hil.config, posix-configs/rpi/px4_test.config
- stm32f7 start with 1 ekf2 instance per IMU
- stm32h7 ekf2 instances across all IMUs and mags
Both have plenty of memory for this, on stm32f7 cpu can start to become limiting with 3 IMUs and multiple mags, especially depending on the configuration of things like IMU_GYRO_RATEMAX. This is a conservative start until we can allocate more effectively.
Enabling this via rc.board_defaults isn't a great mechanism as it will only apply to newly configured systems (SYS_AUTOCONFIG). Later I'd like to do this properly with different defaults per board handled by the parameter system (https://github.com/PX4/PX4-Autopilot/pull/14363).
=> boards: start enabling multi-EKF by default on F7/H7

src/modules/simulator/simulator.cpp, src/modules/simulator/simulator.h, src/modules/simulator/simulator_mavlink.cpp
Added an option to the Simulator module to connect to remote Gazebo servers.
This is usefull when the Gazebo simulation is running on a different host than the PX4 instance.
For example, we are running instances of PX4 with a companion application in multiple Dockers, for swarming simulations, which then connect to a remote Gazebo server.
A "-t" input argument has been added and can be called from the rcS startup script as: `simulator` start -t "192.168.178.122" $simulator_tcp_port`
Signed-off-by: Peter Blom <peterblom.mail@gmail.com>
Closes #15428.
=> Simulator: Added remote host option

src/modules/navigator/geofence_params.c
Clarify that GF_ALTMODE is estimated altitude vs barometer atl (not WGS84 vs AMSL). Comes from discussion on slack: https://px4.slack.com/archives/C581ST17V/p1576169863167400,
=> geofence: GF_ALTMODE clarification

src/modules/simulator/simulator.h
Formatter also complained about `VehicleIMU.cpp` format, which also gets address in this PR.
=> simulator: delete PublicationMulti ptrs for sensor_gps

src/modules/commander/commander_params.c
This reorders the docs on COM_RC_OVERRIDE to make the fact that it is only applying to MC-mode more visible. That is more important in the comment than the bit values, which are in any case listed separately and clearly below.
@MaEtUgR The docs for bit 1 say "bit 0: Enable for auto modes (except for in critical battery reaction),". Is the text *except for in critical battery reaction* also true for bit 1?
If so, then I'd suggest we move that text up in to the comment part, and remove the bit documentation in the comment part (if it is the same for both, then this text is just duplication"
=> COM_RC_OVERRIDE: Make MC only more visible

Tools/serial/generate_config.py, boards/px4/fmu-v4/default.cmake, boards/px4/fmu-v4/init/rc.board_defaults, boards/px4/fmu-v4/init/rc.board_mavlink
Currently, dshot telemetry can only be used on TELEM1, TELEM2, or GPS1 on a PixRacer.
This adds the option of putting it on the UART that usually runs the mavlink instance for the ESP WIFI module.
The parameter description for [DSHOT_TEL_CFG](https://docs.px4.io/master/en/advanced_config/parameter_reference.html#DSHOT_TEL_CFG) implies that 8 different outputs can be selected. This is not true for a PixRacer. Either all of them should be added to the v4 config or the parameter description should indicate which are available for which board.
Open points:
=> fmu v4: add option to run DShot telemetry on WIFI uart

src/modules/commander/state_machine_helper.cpp
fixes issue described on #14479 
When battery goes to emergency/critical levels. and the failsafe parameters set to land or RTL, the drone re-initiate landing/RTL even if the drone is already landing/RTLing
in case of already started landing, don't initiate RTL. and don't re-initiate landing
=> Critical bat landing - don't re-initiate landing and RTL

msg/templates/uorb_microcdr/microRTPS_client.cpp.em, msg/templates/urtps/RtpsTopics.cpp.em
Time-to-time, people might encounter a problem where the micro-RTPS agent or client are not capable of parsing certain messages since the defined messages and ID's are not in sync between the client and the agent. This somehow helps understand which ones are not in sync and provides a hint.
=> msg: rtps: improve verbosity when the the client/agent are not capable of parsing a specific ID

msg/tools/uorb_to_ros_msgs.py
An bug on the `uorb_to_ros_msgs.py` was leading to uORB type names found as part of field names be capitalized as ROS types, leading to wrongly generated fields:
```console
NameError: 'fs_bad_Airspeed' is an invalid field name.  It should have the
pattern '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$'
```
An update to the script, using regex, quickly fixes the issue.
=> tools: make sure that uORB type names found as part of field names are not capitalized as ROS types

ROMFS/px4fmu_common/init.d/airframes/4071_ifo, ROMFS/px4fmu_common/init.d/airframes/4072_draco, ROMFS/px4fmu_common/init.d/airframes/4073_ifo-s, ROMFS/px4fmu_common/init.d/airframes/4250_teal, msg/estimator_sensor_bias.msg, src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp, src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.hpp, src/modules/commander/Arming/PreFlightCheck/checks/ekf2Check.cpp, src/modules/commander/commander_params.c, src/modules/ekf2/EKF2.cpp
There are 2 parts to this, and I could go either way on the 2nd. Commander shouldn't need to have intimate knowledge of everything to function. As much as possible I'd like to avoid having multiple tuning knobs at every level.
1. Commander preflight use `estimator_sensor_bias` message instead of directly using states and covariances at magic indices
2. Instead of independently configuring the bias limits in commander (COM_ARM_EKF_AB/COM_ARM_EKF_GB), publish them in `estimator_sensor_bias`. The commander parameters were a bit unintuitive and dependent on ecl/EKF internals like the filter update period. Commander blocks arming if you exceed 50% of the limit. The accel bias limit is set from the parameter EKF2_ABL_LIM, but the gyro and mag limits are hardcoded.
=> estimated IMU bias preflight checks

launch/single_vehicle_spawn.launch
This fixes a regression/bug introduced by https://github.com/PX4/PX4-Autopilot/pull/16497
The `eval` syntax doesn't seem to work properly with the current syntax. Also, it is unnecessary to add a 1 to the mavlink ID therefore has been removed.
Tested in SITL Gazebo with the following command
```
roslaunch px4 multi_uav_mavros_sitl.launch
```
- Fixes https://github.com/PX4/PX4-Autopilot/issues/16538
=> Fix roslaunch multivehicle regression caused by #16497

boards/mro/ctrl-zero-f7/src/board_config.h
Fixes https://github.com/PX4/PX4-Autopilot/issues/16541
@pkocmoud can you verify the default values?
@matthewoots FYI
=> boards: mro ctrl zero f7 fix default power module calibration

src/drivers/gps/gps.cpp, src/drivers/gps/params.c
Now, that the Galileo GNSS system is is a working condition, it would be nice to be able to select, which GNSS systems are used by the connected GNSS receiver. For example the pixhawk 4 GPS is using the uBlox NEO-M8N chipset, which is capable of receiving three of the four (GPS, Galileo, Beidou, GLONASS) available GNSS systems at once. But by default only GPS and GLONASS are enabled.
This PR will introduce a new configuration parameter `GPS_x_GNSS`, which is a bit vector to enable the individual GNSS systems. When no bits are set, the receiver's configuration should not be changed.
See https://github.com/PX4/PX4-Autopilot/issues/16370 for the general discussion.
This PR depends on changes in …
=> Add parameter to select the set of used GNSS systems

ROMFS/px4fmu_common/init.d/airframes/13001_caipirinha_vtol
When I tested my two motor tailsitter aircraft, I found that the maximum output pwm value did not change (I have set pwm_max to 2100)
=> Ensure that the max/min pwm changes take effect

src/modules/sensors/vehicle_gps_position/VehicleGPSPosition.cpp, src/modules/sensors/vehicle_gps_position/VehicleGPSPosition.hpp
@JacobCrabill @bresch this is the refactor/cleanup of GPS blending originally from https://github.com/PX4/Firmware/pull/14447.
NOT TESTED.
This would be a good excuse to add proper testing in SITL for GPS blending and perhaps even restructure the blending logic to make it unit testable.
=> sensors/vehicle_gps_position: untangle and remove unnecessary state

ROMFS/px4fmu_common/init.d-posix/airframes/1040_standard_vtol, ROMFS/px4fmu_common/init.d-posix/airframes/1041_tailsitter, ROMFS/px4fmu_common/init.d-posix/airframes/1042_tiltrotor
Improves tuning of Standard VTOL and removes unnecessary params from config (e.g. params that got reset to their default values or that are not important to set for STIL in my opinion.
Tuning improvements mainly focused around TECS tuning:
new:
old:
FW fine-tuned with new TECS controller parameters (https://github.com/PX4/PX4-Autopilot/pull/16362). This amount of tuning would not be required to fly safely, but shows how
=> Improve tuning of the SITL VTOL models

ROMFS/px4fmu_common/init.d-posix/airframes/6011_typhoon_h480
**Describe the bug**
Hi, I am having stability issues with Gazebo SITL Typhoon h480. In the hover it gets worse with time, descending and ascending with no major problems.
**To Reproduce**
Steps to reproduce the behavior:
1. Build the repository with `make px4_sitl gazebo_typhoon_h480`
2. Open QGroundControl and Takeoff to any height
3. Oscillation can be observed. While waiting oscillation gets amplified. 
**Expected behavior**
Expected behavior is of course a hover without major oscillations but small tuning errors are always acceptable for simulating the real world conditions. 
**Screenshots**
https://user-images.githubusercontent.com/21319327/104027976-32fb1180-51d9-11eb-8344-c3e1b38ab3ca.mp4
**Drone:**
- Typhoon H480 SITL 
**Proposed Solution**
I have made a rough tuning with [PX4 …
=> Retune Typhoon H480 PID

src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp, src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.hpp, src/modules/commander/Arming/PreFlightCheck/checks/airspeedCheck.cpp, src/modules/commander/commander_params.c
Some updates to the airspeed preflight checks.
- airspeed validity information given by the airspeed selector/validator is checked for preflight checks
- user can set maximal allowed airspeed during arming (new parameter ASPD_MAX_ARM)
- ~~ listen to airspeed_validated instead of airspeed in the airspeed preflight checks~~
- ~~don't allow arming if airspeed_selector is down (as we then have no airspeed_validated data)~~
- ~~add confidence value to the airspeed_validated message, such that this can be checked at instant of arming (later we can also think about how to include it in the general airspeed validation checks)~~
- ~~add new parameter ASPD_MAX_ARM to set maximal allowed airspeed during arming (instead of …
=> Airspeed preflight checks update

Tools/sitl_run.sh
**Problem Description**
When running SITL Gazebo simulations, very often you end up clicking the follow target through the gazebo GUI, and this is cumbersome. To prevent this, gazebo provides you an interface to predefine your visual follow target in your `world` file. However, this makes it complicating if you want to use a single world file for multiple vehicles(as we do in PX4/PX4-sitl_gazebo) or if you have multiple vehicles in your world. 
**Solution**
This commit starts a `user_camera_plugin` which has been added in https://github.com/PX4/PX4-SITL_gazebo/pull/691
Since this interacts directly with the gui API, this would help on further optimizing the viewpoints in the future. (e.g. Simulating view point from the ground)
Note that the plugin is loaded on the `gzclient` side and not …
=> Following vehicle on startup in Gazebo SITL when using make targets

boards/px4/fmu-v3/src/board_config.h, src/drivers/drv_io_heater.h, src/drivers/heater/heater.cpp, src/drivers/heater/heater.h, src/drivers/px4io/px4io.cpp
Adds support for boards which have an IMU heater pin on the IO MCU.  Uses ioctl calls to PX4IO to turn the heater on/off, and abstracts the heater_on / heater_off calls in the heater driver to use either the ioctl call for PX4IO, or to directly toggle an FMU-connected pin, as configured by the board config.
I know the goal is to move away from inter-thread communications via ioctl calls, but this was the easiest method.
Tested using a Black Cube on my desk setup.  This was using custom firmware so I'm not sharing that specific log.  The heater module will still have to be added to whatever board you want to test this on.
FYI @dagar 
@mirkix maybe you would like to test this on a yellow/orange Cube?
=> heater: px4io: Add support for heaters on IO MCU

ROMFS/px4fmu_common/init.d-posix/airframes/3011_hexarotor_x, ROMFS/px4fmu_common/init.d-posix/airframes/6011_typhoon_h480, ROMFS/px4fmu_common/init.d/airframes/1002_standard_vtol.hil, ROMFS/px4fmu_common/init.d/airframes/24001_dodeca_cox, ROMFS/px4fmu_common/init.d/airframes/4016_holybro_px4vision, ROMFS/px4fmu_common/init.d/rc.fw_defaults, ROMFS/px4fmu_common/init.d/rc.mc_defaults, ROMFS/px4fmu_common/init.d/rc.vtol_defaults, src/modules/navigator/rtl_params.c
- find it annoying that RTL_LAND_DELAY is by default at -1 (do not land but loiter), even though for most applications that's not the default (only for FW usually). For FW, RTL_LAND_DELAY is already set to -1 in the defaults.
- the max distance between waypoints is too low with 900m for VTOLs
=> RTL_LAND_DELAY default to 0 and MIS_DIST_WPS to 5km for VTOL

msg/vehicle_local_position.msg, src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp, src/modules/ekf2/ekf2_params.c
Those were some features available in the EKF but not used by PX4.
- `EKF2_RNG_QLTY_T` set the hysteresis time of the quality check
- `EKF2_SYNT_MAG_Z` enables synthetic mag Z fusion mode. Useful in case of high magnetic interference on the Z axis (often due to power cables or batteries under/above the autopilot)
- `dist_bottom_sensor_bitfield` tells if the terrain estimator is currently fusing range finder or optical flow. This field is currently not used by anyone but can be really useful.
=> Expose some EKF2 features

src/modules/vtol_att_control/tailsitter.cpp
Replaces #12518 
Closes #12302
Followed the same logic and just updated the PR with a quick test in SITL.
Log: https://logs.px4.io/plot_app?log=fb7ebb3e-53ac-4c8a-baa7-548dc4a8ede0
@sfuhrer If you could have a look, and perhaps @xdwgood can you test this in a tailsitter as well?
@dagar FYI
=> Fix differential thrust for Tailsitter in FW mode

src/drivers/gps/gps.cpp
I'm open to suggestions for alternative mechanisms with additional granularity. I also considered adding defines to enable each protocol with cmake options to enable, but I suspect no one would actually use them.
Saves 10.3 kB of flash on constrained boards.
``` Console
VM SIZE    
-------------- 
+0.0%      +8    g_cromfs_image
-9.1%      -2    GPSHelper::setBaudrate(int)
-11.1%      -2    GPSHelper::write(void const*, int)
-1.1%      -4    GPSDriverUBX::activateRTCMOutput()
-3.4%      -4    GPSHelper::storeUpdateRates()
[DEL]     -14    GPSDriverMTK::~GPSDriverMTK()
[DEL]     -16    GPSDriverEmlidReach::~GPSDriverEmlidReach()
[DEL]     -20    baudrates_to_try.9701
-6.7%     -24    GPS::GPS(char const*, gps_driver_mode_t, GPSHelper::Interface, bool, bool, GPS::Instance, unsigned int) …
```
=> drivers/gps: limit to ublox only on flash constrained targets

msg/tools/uorb_rtps_classifier.py, msg/tools/uorb_rtps_message_ids.yaml
1. Topics responsible for offboard control are not active to be streamed on the RTPS link, which doesn't allow do Offboard control with DDS/ROS2.
2. We are running short on available ID space for base uORB topics.
1. Add topics responsible for offboard control - this enables https://github.com/PX4/px4_ros_com/blob/master/src/examples/offboard/offboard_control.cpp.
2. Increase RTPS ID space for base messages by 20 IDs.
=> Some RTPS support updates

src/lib/parameters/flashparams/CMakeLists.txt, src/lib/parameters/flashparams/flashfs.c
Follow up to:
https://github.com/PX4/PX4-Autopilot/pull/12319
https://github.com/Auterion/Firmware/pull/9
When we started using ARM GCC 9+ we got valid warnings about the ambiguity of the allignment of `flash_entry_header_t`.
We put compile flags to ignore the warnings and now we can fix it.
Thanks to @Ole2mail and @yuhaim for the suggestions.
A combination of what was suggested telling the compiler explicitly that the struct is `uint32_t` alligned.
Compiles without the warning since the ambiguity is gone.
https://github.com/PX4/PX4-Autopilot/pull/14159 and https://github.com/PX4/PX4-Autopilot/pull/14159/files#diff-df21f531032831043352bb121b8c0f8af21930005a79f3a69244b …
=> flashfs: fix alignment ambiguity

.vscode/settings.json
This option comes down to user preference and I don't see a particular reason to change this based on the workspace. I found it confusing to have this non-default behavior just for PX4 editing.
@dagar Would it be ok for you to set this in the user settings?
Removing it solves my confusion with the search functionality.
=> vscode: do not enable "smart" case search in workspace settings

src/lib/magnetometer_bias_estimator/CMakeLists.txt, src/lib/magnetometer_bias_estimator/FieldSensorBiasEstimator/CMakeLists.txt, src/lib/magnetometer_bias_estimator/FieldSensorBiasEstimator/FieldSensorBiasEstimator.hpp, src/lib/magnetometer_bias_estimator/FieldSensorBiasEstimator/FieldSensorBiasEstimatorTest.cpp, src/lib/magnetometer_bias_estimator/MagnetometerBiasEstimator.cpp, src/lib/magnetometer_bias_estimator/MagnetometerBiasEstimator.hpp
When using a vehicle after transport parts of the vehicle could be magnetized (hard Iron effect). In this case the pilot will likely face issues best case already before takeoff during checks or worst case in air when the check thresholds were widened to not constantly generate false positives or the checks didn't recognize the specific experienced measurement error.
This pr brings the algorithm described in http://www.roboticsproceedings.org/rss09/p50.pdf to PX4. It does online magnetometer bias estimation based on gyroscope and magnetometer data from the same body frame while the body is turned in a constant external magnetic field (earth magnetic field). The idea is to allow an online mag offset calibration on …
=> Add online magnetometer calibration on the ground

src/modules/mc_pos_control/MulticopterPositionControl.cpp
It's not really a bug in current usage, but we should be sure to only update the constraints if the topic has updated.
@MaEtUgR can you verify the desired behavior in the failsafe condition?
=> mc_pos_control: only update constraints if topic updated

boards/mro/ctrl-zero-f7/src/board_config.h
This fixes RSSI for the Control Zero F7 but I have noticed that while this works perfectly for SBUS receivers, for PPM receivers it does not decrease the RSSI visual value in QGC when removing the RC transmitter connection.
When a PPM receiver is connected and the connection is lost the autopilot goes into RC Scan State Mode (in the RC Update Module) to determine what is connected (even though the receiver is already connected).
The main issue with this is that PPM receivers don't go into RC Failsafe but I don't think it is an issue with this autopilot. It looks to be an issue with the RC Update Module and how it is handled at the module level for non I/O coprocessor autopilots. 
Tested with an X8R (SBUS) and a Dragonlink (PPM) as well as a Dragonlink set to SBUS as the output. SBUS …
=> Control Zero F7 - RSSI Fix - SBUS Only/PPM Partial

boards/mro/ctrl-zero-f7/src/board_config.h
Fix to enable standard current/voltage sensor to display voltage and current readings on Control Zero F7.
=> Control Zero F7 - Fix for voltage/current sensing

src/drivers/imu/bosch/bmi088/BMI088_Accelerometer.cpp, src/drivers/imu/bosch/bmi088/Bosch_BMI088_Accelerometer_Registers.hpp
This PR adds support for the Bosch BMI090L IMU. The BMI090L is the long life industrial version of the BMI088. Comparing the datasheets and register sets, only the accelerometer ID value is different.
https://www.bosch-sensortec.com/products/motion-sensors/imus/bmi088.html
https://www.bosch-sensortec.com/products/motion-sensors/imus/bmi090l/
This solution adds a check for the BMI090L accelerometer ID to the BMI088 driver.
An independent BMI090L driver could be created but might pose issues for manufacturers who want to use the BMI090L as an alternate for the BMI088. Since the gyro ID is exactly the same in both devices, you can't differentiate between them without checking which …
=> Add BMI090L IMU Support

Tools/px4airframes/markdownout.py
The airframes reference includes text like this `<p>Maintainer: SomeName <some_email></p>`. The < and > make the email address into an un-closed tag. Browsers handle this, but we should do the right thing as I get errors reported.
This PR just changes those to `&lt;` and `&gt;`
=> Escape < and > in maintainer field

.ci/Jenkinsfile-compile
This build was not yet available in the CI. This is a separate build for the new Rev. E version of FMUK66, previous Rev. C and D boards (fmuk66-v3) will not be abandoned.
@davids5 @dagar
=> Add NXP FMUK66E build to CI

msg/CMakeLists.txt, msg/mag_worker_data.msg, msg/tools/uorb_rtps_message_ids.yaml, src/modules/commander/mag_calibration.cpp, src/modules/logger/logged_topics.cpp
Debugging the mag calibration algorithm is difficult without having the exact data used during calibration. This PR adds logging of the `mag_cal_data` struct, containing the data used by the sphere/ellipsoid fitting algorithms
Tested on Pixhawk4 and Skynode
=> Add logging of mag calibration data

src/modules/commander/mag_calibration.cpp
In some cases, the fitness of the optimizer does not shrink at each iteration, causing the "decreasing fitness check" to fail. This stops the optimization and returns with sub-optimal, or unrealistic results.
Found using some replay data from @sfuhrer 
```
fitness: 0.050174	sphere_lambda: 1.000   radius: -0.222
fitness: 0.050174	sphere_lambda: 10.000  radius: -0.222 <== previously stopped here
fitness: 0.021021	sphere_lambda: 10.000  radius: 0.076
fitness: 0.001488	sphere_lambda: 1.000   radius: 0.346
fitness: 0.000987	sphere_lambda: 0.100   radius: 0.362
fitness: 0.000987	sphere_lambda: 0.010   radius: 0.362 <=== now stops here
```
=> mag_cal: fix race condition causing invalid mag calibration

src/lib/parameters/px4params/markdownout.py
Modifies the parameter markdown output so that instead of having text alignment applied on each table element it is done using a style for the whole page (reduces file from 870Kb to 630Kb). Also changes to use the vuepress note syntax.
=> Parameter markdown use page css for layout

.gitmodules
We renamed some repositories in the PX4 organization the obvious `PX4-` prefixes were adapted in https://github.com/PX4/PX4-Autopilot/pull/16087 but some less obvious capitalization lib prefix not.
I went through every link and checked if it forwards to a different name.
=> .gitmodules: adapt submodule names to repo renaming

src/modules/mavlink/mavlink_main.cpp
I'm not yet sure how, but the presence of this stream appears to be causing the MAVSDK tests to fail.
https://github.com/PX4/PX4-Autopilot/runs/1742431144
=> mavlink: disable ACTUATOR_OUTPUT_STATUS stream

src/modules/ekf2/EKF2Selector.cpp
In EKF2Selector::PublishVehicleLocalPosition(bool reset), _delta_z_reset was used at L380
I hardly know EKF, but _delta_vz_reset seems right in that position.
fixes https://github.com/PX4/PX4-Autopilot/issues/16621
=> fix variable name in EKF2Selector (#16621)

ROMFS/px4fmu_common/init.d-posix/rcS
For simulated instances, it was hard to configure mavlink instances since 4 mavlink instances would start as a default.
Some projects, e.g. [https://github.com/JonasVautherin/px4-gazebo-headless](https://github.com/JonasVautherin/px4-gazebo-headless/blob/ac0611f4eff3ed8eb150bd85c28dd6828b5a935d/edit_rcS.bash#L50) take the approach of directly editing the rcS file.
However, this quickly becomes hard to maintain, since everytime there are changes in the `rcS` file the script editing would break
This commit enables the option for users to add a custom mavlink configuration by adding a file `rc.mavlink_override`
This does not interfere with the default SITL setup, but enables users that want …
=> Add option for custom mavlink configuration for SITL

msg/tecs_status.msg, src/lib/tecs/TECS.cpp, src/lib/tecs/TECS.hpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c, src/modules/mavlink/streams/HIGH_LATENCY2.hpp, src/modules/mavlink/streams/NAV_CONTROLLER_OUTPUT.hpp
[this is purely a renaming, no changes in logic/behavior]
Currently, from the parameter description, in-code comments and uorb messages, it is not clear which airspeeds in TECS are corresponding to true airspeed (TAS) and which are to equivalent (EAS). 
Rename variables (also in message tecs_status), add comment to parameter description 
Should we rename EAS to CAS also in TECS? Currently, it's CAS everywhere beside in TECS, and we just set EAS=CAS when passing it into TECS.
SITL tested:
=> TECS: clarify when airspeed is TAS and when CAS/EAS

src/modules/simulator/simulator_mavlink.cpp
This seems to be an older (minor) definition issue due to the definition that motors mostly have a range of 0..1 while servos have -1..1
However, since PR (https://github.com/PX4/PX4-Autopilot/pull/15861), vehicle type 'uuv' does not work anymore in simulation as UUV motors are now configured for 0..1 instead of the original working -1..1 range. A work-around is proposed by @Zarbokk in PR (https://github.com/PX4/PX4-SITL_gazebo/pull/696) which changes the vehicles sdf-files, what would work of course. However, I feel it makes more sense to address the root of the problem rather than the *.sdf-files:
Historically, px4 see 'motors' only in the 0..1 range.  Their number (represented by the variable 'motor_count') configures the first …
=> bug-fix: indicate motor channel range 0..1 or -1..1 in simulation_mavlink.cpp

src/lib/parameters/px4params/jsonout.py, src/lib/parameters/px4params/srcparser.py, src/lib/parameters/px4params/xmlout.py
its seems that since commit 564b29c0f83737c9065c0f5f8294e0a2897759fe the boolean flag of parameters doesn't expressed on the generated XML file.
that fixes it by adding "Boolean" attribute.
re-add the information as attribute
Note that on pre 564b29c0f83737c9065c0f5f8294e0a2897759fe  the expression were not an attribute but an element.
I am not sure how QGC handled that on the past 15 month, has it stopped to show boolean parameters as checkbox?
What need to be done there in order to make it look at the 'new' attribute?
and small cleanup, make Volatile as bool in the internal variable
=> re-add boolean attribute to the parameters xml

boards/cuav/can-gps-v1/src/board_config.h, boards/cuav/can-gps-v1/src/init.c
``` Console
nsh> param show
Symbols: x = used, + = saved, * = unsaved
x   CANNODE_BITRATE [0,24] : 1000000
x   CANNODE_NODE_ID [1,25] : 120
x   GPS_1_GNSS [2,40] : 0
x   GPS_DUMP_COMM [3,44] : 0
x + GPS_UBX_DYNMODEL [4,45] : 6
x   GPS_UBX_MODE [5,46] : 0
x   GPS_YAW_OFFSET [6,47] : 0.0000
7/74 parameters used.
```
=> boards: CUAV CAN GPS flash based parameters

msg/vehicle_command.msg, src/modules/commander/Commander.cpp, src/modules/flight_mode_manager/FlightModeManager.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp, src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_main.h, src/modules/mavlink/mavlink_messages.cpp, src/modules/navigator/navigator_main.cpp, src/modules/temperature_compensation/TemperatureCompensationModule.cpp, src/modules/vtol_att_control/vtol_att_control_main.cpp, src/modules/vtol_att_control/vtol_att_control_main.h
This is to prevent the possible loss of vehicle_commands. At the moment it's likely only problematic in the case of high rate vehicle_commands from things like vmount, but better safe than sorry.
- fixes https://github.com/PX4/PX4-Autopilot/issues/16630
=> increase vehicle command queue depth and updates modules to consume all available queued commands

src/lib/flight_tasks/FlightTasks.hpp
When you lose GPS estimate and command an Orbit (not already running one) there's a null pointer exception:
1. The flight task update is called because a task is running, current_task not null
2. In the update, the vehicle commands handling gets called which can switch to a different task e.g. Orbit
3. If no GPS is available Orbit activation fails, not yet sure why this results in no task running
4. There's other things called on `_flight_tasks` that access the `current_task` pointer
5. The pointer access was guarded in every single case but people added more calls and ignored guarding which I did not see:
https://github.com/PX4/PX4-Autopilot/pull/10411/files#diff-e300be601083c82735501dd851cd44f0bd564c5a88200e72e7a66a01a9f8c6a5R132 …
=> FlightTasks: hotfix guard against accessing no task

boards/cuav/can-gps-v1/init/rc.board_defaults, src/drivers/uavcannode/indication_controller.cpp
This adds the tone_alarm. 
In testing 
after repeated (suspected too quickly) ` tune_control play -t 3`  the FMU stops sending  `BeepCommand`
=> cuav gps:Add Beep indication

src/drivers/uavcan/beep.cpp
commit 3d668d8 blocks repeated tunes. But that should not stop the tune state machine of the playing tune. It will never finish and that tune can not be played again, without an interposing tune played. This fixes that
=> uavcan:Beep Repeated tunes are OK

src/drivers/uavcannode/UavcanNodeParamManager.cpp, src/lib/parameters/param.h, src/lib/parameters/parameters.cpp
This adds a new param function param_get_default_value() that mirrors param_get(), except it returns the default value. Useful for things like the uavcannode.
=> parameters: add new param_get_default_value()

src/modules/simulator/simulator_mavlink.cpp, src/modules/uuv_att_control/uuv_att_control.cpp, src/modules/uuv_att_control/uuv_att_control.hpp
This PR is related to  PR (https://github.com/PX4/PX4-Autopilot/pull/16610). However, as we want to introduce a 6DOF uuv_pos_control module, we need to extend uuv_att_control with a feed-through for the translational DOF in y- and z- directions
extending the 4DOF to 6DOF by adding feed-through for thrust in y and z-direction
Build individual attitude controller specific for 6DOF UUVs. However, a generalized version which is capable handling both 4 and 6DOF seems preferable.
So far testing is only done in Gazebo.
=> extend uuv_att_control module by thrust in y/z-direction

src/modules/simulator/simulator.cpp
The number of arguments was increased by one, see: https://github.com/PX4/PX4-Autopilot/commit/1719ff9892f3c3d034f2b44e94d15527ab09cec6
Because the above commit was merged before https://github.com/PX4/PX4-Autopilot/pull/15443 . It broke support for the remote host option.
This has been fixed in this commit by increasing all argv's by one.
Signed-off-by: Peter Blom <peterblom.mail@gmail.com>
=> Simulator: Fix for arg count increase breaking remote host option.

src/lib/drivers/device/Device.hpp, src/modules/mavlink/mavlink_receiver.cpp
Continuation of https://github.com/PX4/PX4-Autopilot/pull/16409#discussion_r565695228
Adds `DeviceBusType_MAVLINK` for device IDs, and makes use of it in `MavlinkReceiver`
=> Device: Add MAVLINK bus type

src/modules/logger/logged_topics.cpp
The max instances on the multi topic `actuator_outputs` was incorrectly set to 2 a while ago in #15647. This means that uavcan actuator output data would not be logged as it would be in the third instance (`.02`).
Tested on a Pixhawk 4 benchtest and it's logging fine now.
Closes #16414
=> Correct max instances of actuator_outputs logging

src/modules/mavlink/mavlink_mission.cpp, src/modules/navigator/mission.cpp, src/modules/navigator/mission_block.cpp, src/modules/navigator/mission_block.h, src/modules/navigator/navigator.h, src/modules/navigator/navigator_main.cpp
- "unable to reach heading within timeout" error when loitering to altitude
- "hacky" loiter position acceptance (1.2*loiter_radius)
- MAV_CMD_NAV_LOITER_TIME: param2 (heading required) not considered
- exit via tangent (xtrack) broken for NAV_CMD_LOITER_TIME_LIMIT 
- fix "unable to reach heading" bug when doing loiter to alt with heading wait 
- for loiter acceptance in fixed-wing, it is cleaner to use (loiter radius + L1 acceptance distance) to decide on acceptance, instead of the magic 1.2 factor in front of the loiter radius  
- add ability of "heading wait" for NAV_CMD_LOITER_TIME_LIMIT (possible as mavlink/mavlink#1383 was merged)
- enable exit via tangent (xtrack) for both NAV_CMD_LOITER_TIME_LIMIT and …
=> Navigator: some loiter refactoring and fixes

cmake/px4_add_common_flags.cmake
VIm's Quickfix window doesn't handle escape sequences embedded in compiler output.
Please consider this PR that enables gcc to sense when output device is a terminal and otherwise omit color.
Quickfix opens a new empty file because the escapes remain in the path it uses.
Quickfix opens the right file and positions on the fake error I introduced for sake of example.
=> cmake: Limit color output to terminals

src/modules/mavlink/mavlink_receiver.cpp
This PR brings voltage and temperature for the external battery which is using mavlink to update status.
When selected **BAT1_SOURCE = external** QGC shows this for a battery voltage:
QGC v4.0.11 - without this PR
QGC v4.0.11 - with this PR
QGC v4.1.1 - without this PR (missing voltage and temperature)
QGC v4.1.1 - with this PR (shows battery voltage and temperature)
=> mavlink receiver: battery status - publish cells voltage and temperature

src/lib/drivers/barometer/PX4Barometer.cpp, src/lib/drivers/magnetometer/PX4Magnetometer.cpp, src/lib/drivers/rangefinder/PX4Rangefinder.cpp
Advertising immediately was previously done to ensure consistent numbering between uORB publication instances (eg sensor_mag:0) and character devices (eg /dev/mag0). The character devices have now been removed for all of these driver types so this is no longer necessary. It saves a small amount of memory by preventing the unnecessary allocation of an extra uORBDeviceNode when probing mags at startup.
=> drivers: no longer any need to advertise immediately (baro, mag, rangefinder)

msg/CMakeLists.txt, msg/takeoff_status.msg, msg/tools/uorb_rtps_message_ids.yaml, src/modules/flight_mode_manager/FlightModeManager.cpp, src/modules/flight_mode_manager/FlightModeManager.hpp, src/modules/flight_mode_manager/Takeoff/Takeoff.hpp
The information about where in the takeoff state machine we currently are when getting off the ground in an altitude controller multicopter mode is currently not available outside of the mode itself. The takeoff state machine will move into the modes that are capable to take off but the information is very useful for e.g. ground effect estimation like discussed with @priseborough .
I publish the internally available information because @priseborough could then use it for his work on ground effect estimation.
It could stay internal and the ground effect estimation could only rely on available information like current collective thrust.
Has been tested as …
=> Publish Takeoff Status

platforms/nuttx/src/px4/stm/stm32_common/version/board_mcu_version.c
This P/R adds `REV_ID`s for STM32F427 rev. 5 and B.
Note that, accoding to https://www.st.com/resource/en/errata_sheet/dm00068628-stm32f427437-and-stm32f429439-line-limitations-stmicroelectronics.pdf, both 5 and B share the same `REV_ID`. This patch reports both as rev. 5.
Fixes #15406
=> Add support for STM32F42x/STM32F43x rev. 5/B

src/modules/sih/CMakeLists.txt, src/modules/sih/sih.cpp, src/modules/sih/sih.hpp, src/modules/sih/sih_params.c
@romain-chiap here's a quick minor improvement to `sih`. The pattern of a thread and hrt_call posting a semaphore is replaced with ScheduledWorkItem (like many other modules in the system). The only difference is the actual thread is shared with other modules that are part of the same "pipeline", so it saves a bit of execution time with fewer context switches and memory (try `work_queue status` for a better look).
I also updated the module to respect the GYRO rate parameter (IMU_GYRO_RATEMAX) instead of the hard coded LOOP_INTERVAL and increased the max optimization level if it's not a flash constrained board.
``` Console
nsh> perf
...
sih: cycle interval: 1828 events, 3997.81us avg, min 3954us max 4045us 3.141us rms
sih: cycle: 1832 events, 103362us elapsed, 56.42us avg, min 51us max …
```
=> modules/sih: move to px4 work queue (wq:rate_ctrl)

msg/telemetry_status.msg, src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_messages.cpp, src/modules/mavlink/streams/LINK_NODE_STATUS.hpp
This adds support to Mavlink for sending `LINK_NODE_STATUS`.
In the mavlink receiver I've implemented message sequence id tracking to estimate lost messages. This largely matches the logic implemented in QGC, but with only a subset of total possible system and component ids implemented (we can't afford 256 x 256 bytes).
Once QGC and other systems start broadcasting `LINK_NODE_STATUS` we can factor it into the mavlink transmit throttling (rate multiplier). This serves as congestion control at the mavlink level which is important for serial links that don't have flow control, but it's also quite useful for UDP links that degrade very poorly.
FYI @dogmaphobic @DonLakeFlyer
=> mavlink: send LINK_NODE_STATUS

.github/workflows/compile_macos.yml
This is suboptimal but survivable since MacOS is not a deployment target. We still need to identify the root cause.
=> MacOS: Disable OS tests

.github/workflows/mavros_mission_tests.yml
The overhead of the MAVROS setup means that most developers are not using it, leading to tests that are not suitable for day-to-day workflows. We are replacing these with MAVSDK tests that can be run locally pre-commit.
=> Disable unmaintained MAVROS tests

src/modules/commander/Arming/PreFlightCheck/checks/ekf2Check.cpp
When checking pre_flt_fail_innov_vel_vert, it might not show mavlink log message because status.pre_flt_fail_innov_vel_vert was not caught in if clause.
Instead, pre_flt_fail_innov_horiz was there, so replaced it with pre_flt_fail_innov_vel_vert.
=> fix condition in ekf2Check

src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp, src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.hpp, src/modules/commander/Arming/PreFlightCheck/checks/ekf2Check.cpp, src/modules/commander/Commander.cpp, src/modules/commander/state_machine_helper.cpp
This PR does the following
- Gets rid of checkGNSS parameter in PreFlightCheck::preflightCheck: `COM_ARM_WO_GPS` should be the one defining the result of the check, which can then remain local inside the method.
- Improves use of SUBSYSTEM_TYPE_GPS to flag most of the GPS issues.
- Ensures that AHRS health flag is set taking into account ekf2CheckSensorBias.
Tested and used in already quite some vehicles. 
=> ekf2checks: minor cleanup and enhancements

src/modules/navigator/geofence_params.c
Current geofence action is at "Warning", so to have the fence actually active the user needs to change the settings.
In my opinion, with adding a geofence the user normally has the intent of not allowing the vehicle to go out of the defined area, and not just to get a warning. Thus the default would be changed to 2 (Hold).
=> Navigator: change default of GF_ACTION to 2 (Hold)

src/drivers/distance_sensor/leddar_one/CMakeLists.txt, src/drivers/distance_sensor/lightware_laser_i2c/CMakeLists.txt, src/drivers/distance_sensor/mappydot/CMakeLists.txt, src/drivers/distance_sensor/mb12xx/CMakeLists.txt, src/drivers/distance_sensor/pga460/CMakeLists.txt
- fixes https://github.com/PX4/PX4-Autopilot/issues/16715
These missing linking dependencies go unnoticed in larger builds where something else brings it in.
=> drivers/distance_sensor: add drivers_rangefinder linking dependency

src/modules/mavlink/streams/ATTITUDE_TARGET.hpp
When using the attitude target over mavlink (listening on the setpoint being set by the attitude controller), the thrust field remains 0 the whole time. 
I think the mavlink stream is pulling the wrong entry from the uorb message (being set [here](https://github.com/PX4/PX4-Autopilot/blob/0f411d6820e55f5e7cb58d064095725f28a7820a/src/modules/mc_att_control/mc_att_control_main.cpp#L213)). I just updated the mavlink stream.
I don't know how else to fix this. I think it's just a typo basically.
**Test …
=> fixing the thrust being used in the attitude target raw mavlink messge

boards/cuav/nora/init/rc.board_defaults, boards/cuav/x7pro/init/rc.board_defaults, boards/cubepilot/cubeorange/init/rc.board_defaults, boards/cubepilot/cubeyellow/init/rc.board_defaults, boards/holybro/durandal-v1/init/rc.board_defaults, boards/holybro/pix32v5/init/rc.board_defaults, boards/modalai/fc-v1/init/rc.board_defaults, boards/mro/ctrl-zero-f7/init/rc.board_defaults, boards/mro/pixracerpro/init/rc.board_defaults, boards/mro/x21-777/init/rc.board_defaults, boards/px4/fmu-v4pro/init/rc.board_defaults, boards/px4/fmu-v5/init/rc.board_defaults, boards/px4/fmu-v5x/init/rc.board_defaults, boards/px4/fmu-v6x/init/rc.board_defaults
With a growing number of UAVCAN GPS units readily available (CUAV NEO 3 Pro, Here 3, Zubax GNSS 2) it's worth enabling UAVCAN by default (sensors only) where we can afford it for a better user experience.
I'll verify required resources before merging.
=> boards: enable UAVCAN sensors by default on F7/H7

src/drivers/uavcannode/Publishers/GnssFix2.hpp
or maybe there was a reason to use eph also for the vertical uncertainty?
=> uavcannode: use correct vertical position uncertainty

msg/tools/uorb_rtps_classifier.py, msg/tools/uorb_rtps_message_ids.yaml
Since the alias / multi-topics messages are also being mapped into ROS 2 messages, this means that they also need RTPS IDs assigned to them. Since there was no check regarding if these add IDs associated, but still the ROS message counterparts were being generated, this was resulting on having `px4_ros_com` failing to build because no IDs existed for those messages.
```sh
raise AssertionError(
AssertionError: 
The following messages are not listen under  /home/nuno/PX4/px4_ros_com_ros2/src/px4_ros_com/templates/uorb_rtps_message_ids.yaml: ActuatorControls4, ActuatorControls5
Please add them to the yaml file with the respective ID and, if applicable, mark them to be sent or received by the micro-RTPS bridge.
NOTE: If the message has …
```
=> RTPS: add alias messages RTPS id check

LICENSE
2020 now is in the past.
Date in the license was 2020
Now its 2021 :+1: 
:shrug: 
Looking at a calendar, it is indeed 2021
none
=> Update current year in LICENSE

ROMFS/px4fmu_common/init.d/airframes/50000_generic_ground_vehicle, ROMFS/px4fmu_common/init.d/airframes/50004_nxpcup_car_dfrobot_gpx
It was reported that rover was not moving, when in mission mode. This issue was something not visible in SITL.
It seems that this behavior was caused by setting the `GND_THR_CRUISE` which defines the mission throttle to zero. 
Set the cruise throttle of the rover vehicle to a non-zero value
- TODO
- Fixes https://github.com/PX4/PX4-Autopilot/issues/16586
=> Set cruise trottle to non-zero for Rover

msg/tools/uorb_rtps_message_ids.yaml
For some usecases like starting video recording on a companion computer or triggering a ROS based (offboard control) mission control execution the status of RC channel is needed in ROS(2). This allows the user to start/stop such functionalities from the RC transmitter.
Therefore InputRc to be changed accordingly.
add 'Set send: true' for id: 30
This will solve https://github.com/PX4/PX4-Autopilot/issues/16741
=> update uorb_rtps_message_ids.yaml for id: 30

src/modules/land_detector/MulticopterLandDetector.cpp, src/modules/land_detector/MulticopterLandDetector.h, src/modules/land_detector/land_detector_params_mc.c, src/modules/logger/logged_topics.cpp
Relates to:
https://github.com/PX4/PX4-Autopilot/issues/15141
https://github.com/PX4/PX4-Autopilot/pull/16652
v1.11.0 of the PX4_Autopilot contained code in the ekf2-main.cpp module that set the ground effect flag if the vehicle was close to the ground, eg:
https://github.com/PX4/PX4-Autopilot/blob/21c82a48146fb8afc5a56263a5da21300ba3137e/src/modules/ekf2/ekf2_main.cpp#L1338-L1351
This functionality has subsequently been lost because the ekf2 module now uses the vehicle_land_detected.in_ground_effect message that does not anticipate a takeoff and set the flag accordingly, eg:
https://github.com/PX4/PX4-Autopilot/blob/8b0ec5a78e03514ade6f4ddd231f4db37f8ee500/src/modules/ekf2/EKF2.cpp#L398-L410
The solution proposed is to modify the logic used to set vehicle_land_detected.in_ground_effect …
=> Fix failure to set ground effect flag before takeoff

ROMFS/px4fmu_common/init.d/airframes/4018_s500_ctrlalloc
One-character typo fix.  Found when trying to test the new Control Allocation module.
=> ROMFS: Fix typo in S500 CtrlAlloc airframe

src/modules/sensors/data_validator/DataValidatorGroup.cpp
By removing the no the comment matches the implementation (which I think makes sense).
This was brought up by Yusuf.K in https://px4.slack.com/archives/C0V533X4N/p1607942208088600.
=> sensors: correct comment logic

Tools/ecl_ekf/analysis/post_processing.py, msg/estimator_status.msg, src/modules/commander/Arming/PreFlightCheck/checks/ekf2Check.cpp, src/modules/ekf2/ekf2_params.c
Current master isn't consistent when talking about PDOP. Some files talk about minimum required PDOP while others use maximum allowed PDOP. This PR tries to fix those incorrect nomenclatures.
Lower values of PDOP are better and the code checks that the current value is under a threshold
Replace the definitions of minimum required PDOP to maximum allowed PDOP.
PX4 SITL Gazebo
**Motivation**
This PR fixes #16731
**Extra information**
https://en.wikipedia.org/wiki/Dilution_of_precision_(navigation)
**Other external necessary modifications**
- Submodule https://github.com/PX4/PX4-ECL/ (src/lib/ecl) should also be updated (https://github.com/PX4/PX4-ECL/blob/b919f3ddf41ab422d09af91eaea2b2f9729fa …
=> Fix and unify the maximum allowed PDOP references

msg/vehicle_status.msg, src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/commander/commander_params.c, src/modules/commander/state_machine_helper.cpp, src/modules/commander/state_machine_helper.h
I repetedly see the requirement to have a delay between losing the rc link and triggering the failsafe reaction. The rc loss timeout should not be increased for that because the vehicle will consider the last known stick position and might fly away or into an obstacle not knowing that there's no pilot commanding that. So there has to be an in between state where the vehicle just waits if the link is regained and if so continues as before.
The most simple example use case is flying to the border of RC reception where the signal starts to drop out intermittently. The vehicle immediately switches to RTL and starts to turn 180° even though the pilot might have just not oriented the antenna correctly and would like to continue with the original …
=> RC loss Failsafe Delay

src/modules/ekf2/EKF2.cpp
fixes https://github.com/PX4/PX4-Autopilot/issues/16372
Context: https://github.com/PX4/PX4-Autopilot/pull/16383 is adding a new message with the -correctly parsed- bitmasks. However, the original bitmask is still there and does not match the message definition.
This PR modifies the bitmask received from ECL to match the message definition (i.e.: squash the 2 first bits)
=> ekf2: fix mismatch between ecl and firmware flag definition

ROMFS/px4fmu_common/init.d/rc.vtol_defaults, src/modules/flight_mode_manager/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.cpp, src/modules/flight_mode_manager/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.hpp, src/modules/mc_pos_control/mc_pos_control_params.c
In some cases e.g.: (VTOL in wind) a good tracking cannot be achieved. This condition then needs to be relaxed, otherwise the drone cannot land properly.
Tested on a VTOL standard plane.
=> MC auto: add parameter to set the trajectory slow-down

src/modules/commander/Arming/PreFlightCheck/CMakeLists.txt, src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp, src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.hpp, src/modules/commander/Arming/PreFlightCheck/checks/sdcardCheck.cpp, src/modules/commander/commander_params.c
I've seen many users realizing that they forgot to plug the SDcard before going flight testing, with the result of having no flight data to analyze.
Having an SD card inserted is not only crucial for logging but also for using mission and geofence functionalities. 
To this aim, this PR adds a new preflight check that warns the user if the SD card is missing.
The functionality is enabled/disabled with the `COM_ARM_SDCARD` parameter. By default, it will only trigger a warning if no SD card is detected, but it is also possible to change its behavior to enforce sdcard presence before arming (`COM_ARM_SDCARD=2`).
=> PreFlightCheck: Detect missing FMU SD card

Tools/px_uploader.py
The code was pitching an exception. It was invalid. That then left
the baud rate AFU
=> px_uploader:Fixes breakage for real serial ports caused by 00e6d11

src/modules/sensors/vehicle_gps_position/CMakeLists.txt, src/modules/sensors/vehicle_gps_position/VehicleGPSPosition.hpp, src/modules/sensors/vehicle_gps_position/gps_blending.cpp, src/modules/sensors/vehicle_gps_position/gps_blending.hpp, src/modules/sensors/vehicle_gps_position/gps_blending_test.cpp
gps_blending doesn't really need to be template class, because GPS_MAX_RECEIVERS is const.
the real meaning of templates, that allows several implementations on same section of code doesn't apply here.
even if the future will need several blending implementations, what will happen is that there will be:
bool GpsBlending<2>::blend_gps_data()
+
bool GpsBlending<3>::blend_gps_data()
using template will make that code duplications. doubling Flash size for them, not for real reason.
remove the use of template, and because wanting to keep gps_blending self contained there need to create new const 'GPS_MAX_RECEIVERS_BLEND'. that will be asserted to be same as 'GPS_MAX_RECEIVERS', at least for now.
as side effect, its …
=> Pr gps blend no template

src/modules/mavlink/mavlink_receiver.cpp
I'm missing context here, but given MAVROS only added the estimator_type field ~18 days ago (https://github.com/mavlink/mavros/pull/1525) it seems safer to accept all by default. We can explicitly reject unsupported frames if necessary.
Fixes https://discuss.px4.io/t/offboard-px4-with-t265-and-ros-does-not-take-off/20818/3
=> mavlink: ODOMETRY handler accept all other estimator_types for now

src/modules/mavlink/mavlink_receiver.cpp
=> mavlink: receiver accept ODOMETRY MAV_ESTIMATOR_TYPE_UNKNOWN for legacy support

boards/px4/fmu-v5x/init/rc.board_mavlink
This will ensure that the different baseboard configurations are properly accounted for depending on HW variants.
=> Initialize MAVLink on v5X variants

ROMFS/px4fmu_common/init.d-posix/airframes/1070_boat
The cruise and speed controllers of the Gazebo boat model were not tuned properly, resulting in large yaw oscillation and poor speed tracking.
Those tuning gains are good enough to control the boat in auto mode, even if I do not think the rover controller is good enough for a boat with this amount of drift; a yaw/yaw rate controller should be added.
Test:
`make px4_sitl gazebo_boat`
=> SITL boat: tune L1 and speed controllers

src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.cpp
With a higher responsiveness, after centering the stick, the velocity and
acceleration setpoints could oscillate around 0 and never reach 0, due to
discretization.
This also prevented position lock engagement.
=> fix StickAccelerationXY: avoid setpoint oscillations around 0

Tools/gz_sim.sh
**Problem solved by this pull request**
This PR allows for a clean running of gazebo simulation for sitl and hitl with gz_sim.sh and advanced runtime generation of worlds and models. This is used in conjunction with [PR 651](https://github.com/PX4/PX4-SITL_gazebo/pull/651) in PX4-SITL_gazebo.
Tested extensively.
=> Gazebo simulation tools.

src/modules/flight_mode_manager/tasks/ManualAcceleration/FlightTaskManualAcceleration.cpp, src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.cpp, src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.hpp
@bkueng reported he started seeing noticeable velocity setpoint jumps at the moment the position controller unlocks if there's still a large position error e.g. with more aggressive tuning/settings.
I'm using the velocity setpoint feedback architecture we're already deploying in other mode implementations with the `SmoothVel` trajectory generation. I had this in mind but forgot/neglected to do that in the initial implementation. See last commit.
I quickly tested in SITL jMAVSim on default config where I can't see the difference from the vehicle but and here's the plot with the fix and it's clearly visible that the trajectory_setpoint velocity setpoint takes over where the position …
=> Acceleration stick mapping: take over position error velocity setpoint when unlocking

src/modules/commander/worker_thread.cpp
I found this on FMUK66 on compass calibration.
Caused by https://github.com/PX4/PX4-Autopilot/pull/16625#issuecomment-765602973
```
479 commander_low_prio           1491  0.533  3508/ 3308  50 ( 50)  READY  5
```
@jkflying Testing really needs to be done on real HW and all the the archs before you merge.
=> BUGFIX Hard fault Commander Calibration

Tools/astyle/files_to_check_code_style.sh
Excludes external submodule libcanard from code style check.
=> astyle: excluded libcanard for uavcannode_gps_demo

src/modules/airspeed_selector/airspeed_selector_main.cpp
I think this check was the wrong way round which meant that we would end up with an unsigned int overflow and trigger a reset.
Fixes #16800.
=> airspeed_selector: fix timeout check

src/modules/flight_mode_manager/tasks/ManualAcceleration/FlightTaskManualAcceleration.cpp, src/modules/flight_mode_manager/tasks/ManualAcceleration/FlightTaskManualAcceleration.hpp, src/modules/flight_mode_manager/tasks/ManualPosition/FlightTaskManualPosition.cpp, src/modules/flight_mode_manager/tasks/ManualPositionSmoothVel/FlightTaskManualPositionSmoothVel.cpp, src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp, src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.cpp
EKF position resets not getting handled correctly in position mode.
The mapping itself was seprated out into a calls because it was reused for the experimental nudging implementation. The position resets which were handled correctly before now change the wrong setpoints and I adjusted.
The nudging has to be before any filtering, then these member setpoints which are essentially copies are not needed anymore.
I had prepared functions to reset the position and velocity but didn't use them in the EKF reset event.
@bresch Could you please give this a quick spin?
Report by @bresch :
> While doing some nav failure sitl tests, I found that the EKF position reset isn't …
=> FlightTaskManualAcceleration: adapt position reset to new structure

ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt
When working on custom airframe configs, one would usually pick a random autostart ID to work with. However, whenever there is an airframe config with the same autostartID merged upstream it causes issues for the custom models. 
This proposes reserving some of the autostartIDs for custom models to prevent the above from happening. This commit adds a comment where the autostart IDs 22000-22999 should be reserved for custom models
- Discussed in the dev call 10/Feb/2021
=> Add comment for reserve autostartIDs

test/mavsdk_tests/autopilot_tester.cpp, test/mavsdk_tests/autopilot_tester.h
It seems like we are often missing updates from topics like flight mode or in air state, both topics that are sent out infrequenctly e.g. at 1 Hz. Therefore, instead of polling for that data we should probably subscribe to the updates and that way get notified of each an every update.
For instance this should prevent the case where we miss the mode change from mission to descend and back to mission once landed and disarmed.
=> mavsdk_tests: prevent missing updates

src/drivers/magnetometer/isentek/ist8310/IST8310.hpp, src/drivers/magnetometer/isentek/ist8310/iSentek_IST8310_registers.hpp
The AVGCNTL register has a non-zero default value after reset.
=> ist8310: fix 16 times average configuration

boards/px4/fmu-v5x/src/manifest.c
This is needed to properly identify new variants.
=> v5X: Register board variants

src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp
In most cases, the EKF can recover from a bad yaw using the yaw estimator and commander should not completely stop using the position estimate.
Allow the "nav test" to pass after it failed if the test conditions are fulfilled for a long period of time.
Remove this part of the code completely as EKF2 should handle a bad initial heading properly.
SITL jMAVSim tests
=> commander: rework nav failure check

ROMFS/px4fmu_common/init.d/rc.rover_defaults
The rover position controller goes in a "STOPPING" state when the next waypoint is smaller than the loiter radius(set by `NAV_LOITER_RAD`): https://github.com/PX4/PX4-Autopilot/blob/5b44bd67bb37c91c0b15ceee70c873b8c0e28cfa/src/modules/rover_pos_control/RoverPositionControl.cpp#L233-L234 
However, since the default is `NAV_LOITER_RAD=50` it effectly prevents from anybody planning a mission within a 50m radius from where the vehicle is. 
This problem was not obvious since all vehicles in SITL were effectly already using `NAV_LOITER_RAD=2`
While the stopping logic is something that definitely needs fixing, reducing `NAV_LOITER_RAD` for all rover vehicles as a hot fix. 
- Discussion in …
=> Use smaller loiter radius for rovers

src/modules/uORB/uORB_tests/uORBTest_UnitTest.cpp
Attempting to prevent px4_fmu-v5_stackcheck and px4_fmu-v5_debug test failures.
=> uORB: tests adjust priorities to minimize failures with stackcheck/debug enabled

src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp
EKF2 selects the first downward facing `distance_sensor` publication. This PR updates the requirement to be both downward facing and non-stale data. It also deselects the current if it hasn't updated for more than 1 second.
This shouldn't impact most people, but there are setups where this will be better than doing nothing.
=> ekf2: try reselecting distance_sensor on timeout

integrationtests/python_src/px4_it/mavros/missions/FW_mission_1.plan, integrationtests/python_src/px4_it/mavros/missions/MC_mission_box.plan, integrationtests/python_src/px4_it/mavros/missions/VTOL_mission_1.plan, integrationtests/python_src/px4_it/mavros/missions/avoidance.plan, msg/position_setpoint.msg, src/modules/fw_att_control/FixedwingAttitudeControl.cpp, src/modules/fw_att_control/FixedwingAttitudeControl.hpp, src/modules/fw_att_control/fw_att_control_params.c, src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp, src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c, src/modules/fw_pos_control_l1/runway_takeoff/RunwayTakeoff.cpp, src/modules/fw_pos_control_l1/runway_takeoff/RunwayTakeoff.h, src/modules/mavlink/mavlink_mission.cpp, src/modules/navigator/mission.cpp, src/modules/navigator/mission_block.cpp, src/modules/navigator/mission_block.h, src/modules/navigator/navigation.h
Replaces https://github.com/PX4/PX4-Autopilot/pull/11845.
- replace minimum pitch angle set by mission item during fixed-wing takeoff by vehicle parameter (FW_TKO_PITCH_MIN)
- apply pitch offset centrally in fw_pos_control
- removes (unused/unnecessary) FW_RSP_OFF param
The following parameters are now all referring to the same "absolute" pitch angle. 
FW_P_LIM_MIN (no change for AUTO and LOITER, other modes: now absolute, before PSP_OFF was added to min after TECS)
FW_P_LIM_MAX (no change for AUTO and LOITER, other modes: now absolute, before PSP_OFF was added to max after TECS)
FW_TKO_PITCH_MIN (new param)
FW_LND_FL_PMIN (now absolute, before PSP_OFF was added after TECS)
FW_LND_FL_PMAX (now absolute, before …
=> Fixed-wing pitch and roll offset clean up

src/lib/l1/ECL_L1_Pos_Controller.cpp, src/lib/l1/ECL_L1_Pos_Controller.hpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp, src/modules/fw_pos_control_l1/runway_takeoff/RunwayTakeoff.cpp, src/modules/fw_pos_control_l1/runway_takeoff/RunwayTakeoff.h, src/modules/rover_pos_control/RoverPositionControl.cpp, src/modules/rover_pos_control/RoverPositionControl.hpp
Always use double precision floating point for working with latitude and longitude, otherwise float should be sufficient.
Needs to carefully checked that it covers all aspects of https://github.com/PX4/PX4-Autopilot/issues/16823. We also need to be fully aware of the performance implications on older boards that lack double precision floating point hardware.
- fixes https://github.com/PX4/PX4-Autopilot/issues/16823
=> L1 position controller: use double precision floating point for all lat/lon

ROMFS/px4fmu_common/init.d-posix/airframes/1060_rover, ROMFS/px4fmu_common/init.d-posix/airframes/1061_r1_rover, ROMFS/px4fmu_common/init.d-posix/airframes/1062_tf-r1, ROMFS/px4fmu_common/init.d-posix/airframes/1070_boat, ROMFS/px4fmu_common/init.d/airframes/50000_generic_ground_vehicle, ROMFS/px4fmu_common/init.d/airframes/50003_aion_robotics_r1_rover, ROMFS/px4fmu_common/init.d/airframes/50004_nxpcup_car_dfrobot_gpx, ROMFS/px4fmu_common/mixers/rover_diff_and_servo.main.mix, ROMFS/px4fmu_common/mixers/rover_generic.main.mix, boards/px4/fmu-v5x/init/rc.board_sensors, boards/px4/fmu-v5x/nuttx-config/scripts/script.ld, boards/px4/fmu-v5x/src/board_config.h, boards/px4/fmu-v5x/src/init.cpp, src/lib/circuit_breaker/circuit_breaker_params.c, src/modules/flight_mode_manager/tasks/Utility/Sticks.cpp, src/modules/fw_att_control/FixedwingAttitudeControl.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/mc_att_control/mc_att_control_main.cpp, src/modules/mc_rate_control/MulticopterRateControl.cpp, src/modules/navigator/gpsfailure.cpp, src/modules/rc_update/rc_update.cpp, src/modules/rover_pos_control/RoverPositionControl.cpp, src/modules/rover_pos_control/RoverPositionControl.hpp, src/modules/rover_pos_control/rover_pos_control_params.c, src/modules/sensors/sensor_params.c
This cleans up some rover specific things, but also adds / fixes two fundamentals (@dagar):
- It allows for the manual -1 to +1 input range, as originally designed. This is important for reversing vehicles. I have added hardening because I was concerned about corner cases for multicopters and fixed wings.
- The reverse setting for PWM channels on PX4IO was off by one. While we will refresh this architecture soon, there is no point of leaving it in the current broken state.
To get to a -1 to 1 scaling for reversing vehicles the calibration in QGC will need to be changed - QGC sets the throttle channel MIN == TRIM, effectively eliminating the negative range. We should change that behavior going forward for reversing vehicle classes.
=> Rover cleanup + arch fixes

src/modules/ekf2/EKF2Selector.cpp, src/modules/ekf2/EKF2Selector.hpp
- relax estimator_status timeout unless attitude hasn't published recently
- primary EKF changed message indicate if due to timeout, filter fault, gyro fault, accel fault
This avoids unnecessary EKF switches due to things like parameter updates on the ground while still maintaining a tight timeout if an estimator stops actually updating (IMU stopped or other error).
=> ekf2: selector improve timeout handling and reporting

src/drivers/protocol_splitter/protocol_splitter.cpp
protocol-splitter does not always detect mavlink messages properly, but sometimes it finds mavlink start byte in the middle of rtps 
message causing traffic to go out-of-sync.
New protocol layer added on top of all messages sent over UART. This gives clear single header to parse for all messages, so it reduces the possibility of faulty detection of mavlink message.
With proper state machine and carefully thought sequence of centralized mavlink&rtps header detection it would be possible to handle data …
=> protocol-splitter: Additional protocol layer added

src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp
Commander improvements on top of https://github.com/PX4/PX4-Autopilot/pull/16264.
- keep `vehicle_control_mode` last state in commander and use appropriate flags in place of various main_state and nav_state checks
- consolidate scattered arming requirements in `arm_disarm()`
- there were a number of different requirements from arming via RC vs Mavlink that don't make any sense
- if geofence enabled require valid home before arming
- throttle requirements for manual modes
- remove unnecessary mavlink feedback that differs between arming interfaces (mavlink vs RC)
- let the preflight/prearm checks respond directly in most cases
=> commander: use control mode flags and cleanup arm_disarm

src/modules/micrortps_bridge/micrortps_client/CMakeLists.txt
The log file **micrortps_bridge.log**   is empty if   make *_rtps  .
This PR is to fix the problem.
=> fix empty log file "micrortps_bridge.log"

src/drivers/drv_io_heater.h, src/drivers/heater/heater.cpp, src/drivers/heater/heater.h, src/drivers/heater/heater_params.c
Hi. This PR adds the feed forward term back into the IMU heater driver, adds a corner case check to the integrator gain so that when it is set close to zero the old integration value is reset, and also performs some formatting cleanup.  C-style casts have been converted to static_casts and the order of function definitions has been alphabetized.
@AlexKlimaj has tested this PR on an fmu-v5 based flight controller and custom IMU board with GPIO controlled heating elements.  Results are as expected once values have been tuned for the system:
```
nsh> heater status
INFO  [heater] Sensor ID: 3932170,       Sensor Temperature: 54.865C,   Setpoint: 55.00C,       Duty Cycle (usec): 100000
INFO  [heater] Feed Forward control effort: 5.900%,     Proportional control effort: …
```
=> Minor cleanup and add back feedforward term to the heater driver

src/modules/commander/Commander.cpp
- only consider if in NAVIGATION_STATE_AUTO_TAKEOFF to avoid confusion with failsafes
- limit evaluation to ORB_ID(mission_result) updates when armed and not landed (small optimization)
=> commander: auto TAKEOFF to LOITER/MISSION minor fix to avoid failsafe confusion

msg/CMakeLists.txt, msg/heater_status.msg, msg/tools/uorb_rtps_message_ids.yaml, src/drivers/heater/heater.cpp, src/drivers/heater/heater.h, src/modules/logger/logged_topics.cpp
- new heater_status logging message
- run continously at low rate until configured sensor is found
- fix px4io fd bugs (fd open/close/ioctl must be same thread)
Sensors should never publish empty messages (device id 0), but some have fairly lengthy reset periods (respecting the datasheet) before they start publishing. Instead of only finding the `sensor_accel` publication instance at startup, we can do it at runtime to avoid race conditions and even work if the sensor is started manually later.
=> drivers/heater: add logging and minor improvements

msg/templates/urtps/RtpsTopics.cpp.em, msg/templates/urtps/RtpsTopics.h.em
This needed to use messages which contain timestamp_sample. Without timestamp_sample synchronization PX4 modules will discard them.
This implementation was done at the suggestion of @TSC21 ([previous PR](https://github.com/PX4/px4_ros_com/pull/66#pullrequestreview-588790862))
=> RTPS: adjust timestamp_sample in urtps_agent

Jenkinsfile
`sitl_gazebo` was looking for system-wide installed libs, since it was at the same src level as the firmware code. Ex: http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2FPX4-Autopilot/detail/master/498/pipeline#step-135-log-302. This is blocking the rest of the Jenkins pipeline.
Remove the top level sitl_gazebo, and build it as part of the default Firmware build.
Eventually the build system needs to be adjusted if we want to make the PX4 SITL executable a ROS 2-visible executable.
=> CI: fix colcon build in Jenkins

src/drivers/batt_smbus/batt_smbus.cpp, src/lib/drivers/smbus/SMBus.cpp, src/lib/drivers/smbus/SMBus.hpp
`batt_smbus` running with BQ40Z80 would produce an error from [this line](https://github.com/PX4/PX4-Autopilot/blob/e48a86916006794989cda3d094cfb7a31258f21d/platforms/common/i2c_spi_buses.cpp#L510).
It also reports errors in `perf` under `drivers__smbus: errors:` and does not publish `battery_status`.
Pass device ID to `I2CSPIDriver`.
After some inspection I determined the second problem was due to the PEC failing because `SMBus::read_block` was called with a length of 34. The actual data is only 32 bytes, but devices sends back the 16-bit address of the block before sending the data, so it ends up being 34 bytes. So increase the max buffer size to 34.
I couldn't find a maximum size for this after a quick glance …
=> batt_smbus: A few fixes with BQ40Z80

src/modules/ekf2/EKF2.cpp
I was reviewing a log and noticed `dist_bottom_sensor_bitfield` was random garbage.
=> ekf2: populate local_position dist_bottom_sensor_bitfield

.ci/Jenkinsfile-hardware
- the same boards are used for stackcheck and debug builds which are cpu constrained
=> Jenkins hardware limit px4_fmu-v5 to generic quadcopter at default rates

src/drivers/uavcannode/UavcanNode.cpp
Fixes the AppDescriptor initializer to work with the new uavcan bootloader work.
Initialize union. 
ark_can_flow_default and cuav_can-gps-v1_default were tested and now build.
Closes #16899
=> Fix uavcannode build Closes #16899

src/drivers/px4io/CMakeLists.txt
This is needed for incremental px4io changes to actually make it all the way through to the ROMFS.
=> cmake: add px4io binary as build byproduct

src/modules/mavlink/mavlink_mission.cpp
- this mission rejection was only added recently in https://github.com/PX4/PX4-Autopilot/pull/16792
- causing QGC compatibility issues https://github.com/mavlink/qgroundcontrol/pull/9464
@DonLakeFlyer let's just get rid of it.
=> mavlink: remove MAV_CMD_NAV_TAKEOFF mission rejection if pitch is still being set

test/mavsdk_tests/test_multicopter_mission.cpp
Arguably should be solved at the model level (tuning, etc), but this still seems sufficient.
https://github.com/PX4/PX4-Autopilot/runs/1946715194
=> mavsdk_tests: relax MC "Fly straight" speed threshold

ROMFS/px4fmu_common/init.d/rcS, ROMFS/px4fmu_test/init.d/rcS, src/drivers/px4io/px4io.cpp
These changes remove the two code paths to updates (forceupdate and update) and try to reboot and bootload IO independent of its state, wether it is in bootloader mode already, safety switch is off or if it is in "nominal state" (running and safety on). This ensures that there are no conditions where user error or boot sequence can prevent a successful upgrade. The only state where an upgrade will not be done is if the system is fully armed.
=> PX4IO: Robustify upgrade process

src/modules/navigator/rtl.cpp, src/modules/navigator/rtl.h, src/modules/navigator/rtl_params.c
Followup on https://github.com/PX4/Firmware/pull/14728. To prevent performing a transition while still loitering around the home location, this PR makes sure that the drone heads towards the home location before triggering the transition. For this purpose, it is reasonable to add a new parameter RTL_LOITER_RAD to allow the user to set a loiter radius for the altitude descending that still allows the drone to turn towards the home location before initiating a transition.
Sitl gazebo log: https://review.px4.io/plot_app?log=b71abace-d7ba-4f9d-a2ef-71ac005d09e1
=> RTL: Perform transition towards home location

src/modules/vtol_att_control/standard_params.c, src/modules/vtol_att_control/vtol_type.cpp, src/modules/vtol_att_control/vtol_type.h
Adding 2 new modes for VT_FWD_THRUST_EN to enable activating pusher assist when above MPC_LAND_ALTx AND not during a landing stage.
Reason:
Some vtols, given enough wind, can generate too much lift with pusher assist for a stable landing. Hence during landing it should be disabled. Also for precision landing it should disable when close to the ground (some pushers can hit the ground)
=> Add pusher assist mode above MPC_LAND_ALTx (except LANDING).

src/modules/sih/sih.cpp, src/modules/sih/sih.hpp, src/modules/sih/sih_params.c
This merge request add a way to simulate sensors default in SIH by changing parameters.
- the number of GPS satellites can be changed and GPS can be unfixed if there are less than 4 satellites 
- a barometer bias or pressure change can be simulated
- a magnetic bias can be simulated
Barometer and magnetometer publications can be stopped
=> Sih sensor fault

boards/cuav/nora/init/rc.board_sensors
- waiting on NuttX SPI6 BDMA to be fixed
Without DMA working the cpu usage of these IMU drivers is a bit absurd.
FYI @davids5
=> boards: CUAV Nora don't start icm20649 on SPI6 by default

src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_main.h, src/modules/mavlink/mavlink_parameters.cpp
This avoids parameter message loss because of radio buffer overrun.
Fix a long standing issue with parameter download overrunning the radio's transmit FIFO on slow radio links with no hardware flow control, but, which utilize RADIO_STATUS messages to provide txbuf usage info.
Make the _radio_status_critical bool available via a new predicate method and use it where we check the serial port's transmit buffer,_mavlink->get_free_tx_buf() in the parameter download code.  Note, that because we allow parameter messages to use available space up to RADIO_BUFFER_CRITICAL_LOW_PERCENTAGE, other message streams will have their rate gradually reduced during parameter download by update_radio_status().  This is intentional and desirable.  I also include a change to this function to ensure that the …
=> mavlink: use RADIO_STATUS to regulate parameter sending

.github/workflows/checks.yml, .github/workflows/clang-tidy.yml, .github/workflows/compile_linux.yml, .github/workflows/compile_linux_arm64.yml, .github/workflows/compile_macos.yml, .github/workflows/compile_nuttx.yml, .github/workflows/compile_nuttx_cannode.yml, .github/workflows/mavros_avoidance_tests.yml, .github/workflows/mavros_mission_tests.yml, .github/workflows/mavros_offboard_tests.yml, .github/workflows/sitl_tests.yml
Attempting to reduce a somewhat common GitHub Actions failure we see when things get busy.
=> github actions decrease max ccache size

src/lib/sensor_calibration/Accelerometer.cpp, src/lib/sensor_calibration/Gyroscope.cpp, src/lib/sensor_calibration/Magnetometer.cpp
Sensors were only getting the board rotation (SENS_BOARD_ROT) and level adjustment once they were calibrated.
- fixes https://github.com/PX4/PX4-Autopilot/issues/16873
=> sensor_calibration: respect board rotation even if uncalibrated

src/modules/sih/sih.cpp, src/modules/sih/sih.hpp, src/modules/sih/sih_params.c
This PR add a distance sensor to SIH.
The behavior of this distance sensor is similar to what I can observe with a Lightware lw20 lidar.
A simple way to simulate defaults is also added.
=> Sih: add distance sensor

boards/nxp/fmurt1062-v1/default.cmake
We're right on the edge and causing new unrelated PRs to fail.
=> boards: nxp_fmurt1062-v1 remove irlock and lights/blinkm to save flash

src/modules/sih/sih.cpp
SIH previous horizontal position noise was a white Gaussian noise with std=0.8m. It results in a noise with high frequencies too high making some ekf position tests fail (test ratio to allow arming (I have some reduced COM_ARM* thresholds)).
The new noise values are below real GPS errors but as theses errors are generally low frequency, they cannot be modeled with a white noise.
GPS position noises are now in meters
=> SIH/gps: express gps position noise in meters and reduce noise value

src/lib/sensor_calibration/Accelerometer.cpp, src/lib/sensor_calibration/Gyroscope.cpp, src/lib/sensor_calibration/Magnetometer.cpp
This raises the threshold required for applying a sensor (accel/gyro/mag) calibration change. This is to minimize needlessly writing negligible parameter changes and triggering unnecessary estimator bias resets.
=> sensor_calibration: increase threshold for updating offsets or scale

boards/ark/can-flow/src/boot_config.h, boards/cuav/can-gps-v1/src/boot_config.h, boards/holybro/can-gps-v1/src/boot_config.h
yield keeps the UAVCAN status active during long erase times.
This was previously selected by chip family. But that requires maintenance, that is not needed as it is known by the board.
=> Can bootloaders use yield

boards/mro/ctrl-zero-h7/default.cmake
Mkblctrl needs to be removed for the build to succeed.
=> MRO Ctrl Zero H7 - Remove mkblctrl from default.cmake

boards/mro/ctrl-zero-h7-oem/default.cmake
Mkblctrl needs to be removed for the build to now succeed.
=> MRO Ctrl Zero H7 OEM - Remove mkblctrl from default.cmake

msg/sensor_accel.msg, msg/sensor_gyro.msg, msg/vehicle_imu_status.msg, src/lib/drivers/accelerometer/PX4Accelerometer.cpp, src/lib/drivers/accelerometer/PX4Accelerometer.hpp, src/lib/drivers/gyroscope/PX4Gyroscope.cpp, src/lib/drivers/gyroscope/PX4Gyroscope.hpp, src/modules/sensors/vehicle_imu/VehicleIMU.cpp, src/modules/sensors/vehicle_imu/VehicleIMU.hpp
This is a quick solution to unblock https://github.com/PX4/PX4-Autopilot/pull/15820 and https://github.com/PX4/PX4-Autopilot/pull/16385. We need the gyro and accel sample rates on hand so that if the primary sensor changes we can reset the biquad low pass filter in place immediately with the correct rate.
Ultimately I'd like to perform the IMU integration directly on raw FIFO data, but there's a bit more involved.
=> sensors/vehicle_imu: include accel/gyro full raw FIFO rate

platforms/common/include/px4_platform_common/param.h, platforms/posix/src/px4/common/px4_daemon/pxh.cpp, src/lib/mathlib/math/Functions.hpp, src/lib/mathlib/math/FunctionsTest.cpp, src/modules/commander/mag_calibration.cpp, src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.cpp, src/modules/mc_pos_control/MulticopterPositionControl.cpp, src/modules/mc_pos_control/MulticopterPositionControl.hpp, src/modules/mc_pos_control/mc_pos_control_params.c
The goal of this is to expose the vehicle's responsiveness as one or a few simple sliders in QGC. Probably most people who discussed this, know that:
- responsiveness is subjective, what works for one pilot does not for another,
- it is use-case dependent, e.g. for an inspection the vehicle should react very slowly.
Current configuration is however scattered over multiple parameters, and different conditions/modes use other parameters.
So this adds an overall responsiveness param that automatically sets the rest if enabled (accel, jerk, tilt limits etc).
discussion points:
- I can imagine that the maximum velocity should be separately configurable, and maybe split it into horizonal and vertical (which also adjusts landing speed, etc)
- it should apply to fixed-wing as well, question is if …
=> Discussion: vehicle responsiveness configuration

src/drivers/optical_flow/thoneflow/thoneflow.cpp
two year ago, ThoneFlow-3901UY updated the framerate from 66 (3901U) to 95fps. so the timespan changed.
old version are not much in the market, so chage this value to new version.
Fix #16790
=> Update the data timespan in the driver of ThoneFlow

cmake/px4_add_common_flags.cmake
This reverts commit c1da999748aade38240f47eee179cdd58c144c78.
@dgeorge83616 this broke color output in all my typical usage with ninja-build, can we find another way to disable it more selectively for you? https://github.com/PX4/PX4-Autopilot/pull/16694
Is there a particular environment variable or anything that can be checked?
=> Revert "cmake: Limit color output to terminals"

platforms/posix/cmake/sitl_target.cmake
Fixes the painful sitl build time for those with 4 or more logical cores.
If number of logical cores on system is greater than or equal to 4 use number of logical cores - 2.
Otherwise use 1 logical core.
Tested on: 
2 logical core VM
4 logical core VM
64 core VM
Worked perfectly.
=> Optimize number of logical cores used during sitl builds.

platforms/posix/cmake/sitl_target.cmake
We've really got to find a better way to handle SITL targets because this isn't scaling. The generated ninja build file is 27M.
CMake should build the dependencies, not used for poor scripting like this. Generating targets for every possible permutation of simulator, model, world, debugger is an abuse of the build system that needs to be fixed.
``` Console
27M	px4_sitl_test/build.ninja
```
=> cmake: sitl_target sort lists and trim a few options

platforms/common/uORB/PublicationMulti.hpp
- fixes UAVCANv0 sensor bridge uORB usage, but also a reason thing to do in general
- simple alternative to https://github.com/PX4/PX4-Autopilot/pull/16973
Big thanks to @amikhalev for actually debugging this after I broke it with https://github.com/PX4/PX4-Autopilot/pull/16699.
=> uORB: PublicationMulti get_instance() advertise if not already advertised

src/lib/battery/battery.cpp
QGroundControl display incorrect voltage with 12S battery. When the log shows ~55V, QGC shows ~45V.
This is due to the fact that `battery_status` only allocates room for 10 cells. It fills those in by the average per cell voltage, but truncates to 10 cells. Which [QGC happily sums](https://github.com/PX4/PX4-Autopilot/blob/9d47f7ecda2153cc3fde3a2a63096723b3467651/src/lib/battery/battery.cpp#L161-L163) to obtain 10/12 of the correct voltage.
Average over the number of cell voltages reported, so when QGC sums it gets the correct answer.
* Do what [UAVCAN battery does](https://github.com/PX4/PX4-Autopilot/blob/9d47f7ecda2153cc3fde3a2a63096723b3467651/src/drivers/uavcan/sensors/batter …
=> lib/battery: Fix cell voltages with >10S

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp
Current master with MPC_POS_MODE 3 (ManualPositionSmoothVel) using collision prevention requires more than the current 1824 bytes of stack.
``` Console
376 wq:nav_and_controllers         53  5.296  1864/ 2828 242 (242)  w:sem  5
```
=> px4_work_queue: increase wq:nav_and_controllers stack

src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h, src/modules/rc_update/rc_update.cpp, src/modules/rc_update/rc_update.h
Adds support for using the MAVLink command MAV_CMD_DO_SET_ACTUATOR to
update the actuator values on control group 3 aux{1, 2, 3}. A simple
deconfliction with rc_update is implemented: when a MAVLink command is
sent, RC is disabled for that channel until a major stick movement is
detected.
Closes what was attempted in #10320 and #15281.
The following MAVSDK script can be used to test (minor modification might be necessary based on your setup):
```c++
#include <mavsdk/mavsdk.h>
#include <mavsdk/plugins/mavlink_passthrough/mavlink_passthrough.h>
#include <mavsdk/plugins/info/info.h>
#include <chrono>
#include <cstdint>
#include <iostream>
#include <future>
#include <memory>
using namespace mavsdk;
void send_actuator(MavlinkPassthrough& mavlink_passthrough,
float value1, float value2, float …
```
=> actuator: add support for MAV_CMD_DO_SET_ACTUATOR

boards/px4/fmu-v6x/init/rc.board_sensors
This commit fixes the sensor rotation for the ICM20649 on the FMUv6x board
It flies!
https://review.px4.io/plot_app?log=1ead2f64-2a67-4f5d-8e5a-ccc928262c0d
=> v6x: fix icm20649 rotation

Tools/gazebo_sitl_multiple_run.sh
When runing gazebo_sitl_multiple_run.sh, the label option is added for various airframes using same model.
For example, if we want to use iris_rtps, we run like below
```
$ Tools/gazebo_sitl_multiple_run.sh -t px4_sitl_rtps -m iris -l rtps -n 2
```
=> add label option for various airframes using same model

src/modules/commander/CMakeLists.txt, src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/commander/ManualControl.cpp, src/modules/commander/ManualControl.hpp, src/modules/commander/commander_params.c
**Describe problem/solution in this pull request**
New `ManualControl` class for handling `manual_control_setpoint` (and later switches) holding subscription, parameters and state necessary. It handles in this pr RC loss, RC override, RC arming/disarming.
- RC override: option to ignore throttle stick
- RC override: based on change (not centered stick)
- RC arming: based on Hysteresis instead of "loop ticker"
- RC arming: simplify the logic
- manual_control_setpoint message 
Note: This is the first stab at it and I'd like to do incremental steps to not create a non-understandable monster pr.
I tested the different cases during development but will do a final pass testing all the things with this state.
Follow up after being in the loop from …
=> Commander: Separate out manual control setpoint processing

ROMFS/px4fmu_common/init.d/airframes/4901_crazyflie21
1. Change crazyflie 2.1 default to `EKF2` and no `MAG`
2. Increase `PWM_MAIN_MIN` to spin the motors when armed
=> [UPDATE] - Default to EKF2 with no MAG

src/modules/fw_att_control/FixedwingAttitudeControl.cpp, src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c, src/modules/mc_pos_control/PositionControl/PositionControl.hpp
This prevents the potential divide-by-zero as described in https://github.com/PX4/PX4-Autopilot/issues/16985.
Furthermore the potential divide-by-zero of https://github.com/PX4/PX4-Autopilot/issues/16981 is addressed. @wuruoyu there should be no zero division possible anymore. Feel free to review this.
fixes https://github.com/PX4/PX4-Autopilot/issues/16985
fixes https://github.com/PX4/PX4-Autopilot/issues/16981
=> Adjust some limits to prevent divide-by-zero

src/modules/commander/Commander.cpp
If you're flying in manual position control mode and lose position the state machine will put you in altitude control mode. Extending the reliant on optical flow relaxed position validity thresholds allows you to potential get back into position control mode with flow alone.
=> commander: extend reliant on opt flow to ALTCTL (degraded from POSCTL)

src/modules/mc_pos_control/MulticopterPositionControl.cpp
The emergency failsafe that prevents the vehicle from crashing with invalid setpoints or states broke with #16869 when the scheduling of the position control module and the setpoint generation got independent. The failsafe mechanism assumed the setpoint is overwirtten by the possibly infeasible trajectory_setpoint on every loop iteration which is not the case anymore. As a result the failsafe reset its hysteresis based on the failsafe setpoint from the last loop iteration and would therefore toggle again every time there's a new unfeasible trajectory_setpoint.
Keeping the `failsafe_setpoint` separate solves this issue. Note that these failsafe setpoints do the bare minimum to keep the vehicle safely in the air and …
=> MultiCopterPositionControl: hotfix emergency failsafe

src/lib/tecs/TECS.cpp
There was a bug in TECS which made the `_dt > DT_MAX` part of [this check](https://github.com/PX4/PX4-Autopilot/blob/cec31fd68512988f1eba072e167c4b53d1d1035c/src/lib/tecs/TECS.cpp#L465-L465) never trigger since just before we call the function we limit the _dt to be max `DT_MAX` [here](https://github.com/PX4/PX4-Autopilot/blob/cec31fd68512988f1eba072e167c4b53d1d1035c/src/lib/tecs/TECS.cpp#L539-L539).
This results in the fact that the internal TECS states are not reset if a VTOL vehicle is doing a second transition to cruise
Tested on TECS similar to v1.10.1
=> TECS: Fix internal state init if dt is large

ROMFS/px4fmu_common/init.d/airframes/1000_rc_fw_easystar.hil, ROMFS/px4fmu_common/init.d/airframes/1001_rc_quad_x.hil, ROMFS/px4fmu_common/init.d/airframes/1002_standard_vtol.hil, ROMFS/px4fmu_common/init.d/airframes/1100_rc_quad_x_sih.hil, src/modules/commander/state_machine_helper.cpp
We use HIL for as part as our system validation and we want it to be as close as possible to the real system.
That is why I want to enable some pre-arm check.  In particular, I want to enable authorization request but I think some other tests can be activated.
Enable pre-arm checks in HIL mode but disable some specific tests.
The following test are still disabled: 
- usb check
- power checks
- safety switch
- esc checks
These tests are enabled:
- valid mission
- valid global position
- valid avoidance system
- specific vtol state
- arm authorization request 
I would like to also enable power tests. My tests are done with a (fake) battery and successfully enable power tests by starting …
=> Enable some pre-arm checks in HIL modes

Tools/gazebo_sitl_multiple_run.sh
This commit adds support for specifying the spawn location of vehicles
in the Gazebo multi-vehicle simulator script (`frame:number:x:y`). Adding support for this allows developers more flexibility in how to set up the simulator.
The behavior when x and y are not specified remains the same as before.
=> Add support for specifying spawn location in Gazebo multi sim

ROMFS/px4fmu_common/init.d-posix/airframes/6011_typhoon_h480
Starting up the typhoon_h480 gazebo simulation model (on latest master) resulted in huge roll and pitch oscillations. Retuning the roll-/pitchrate p gain helped achieving nicer flying behavior. 
Change of roll-/pitchrate p gain for the typhoon_h480 model
none
As an example just the Roll-Axis:
As it was: [link to ulog](https://review.px4.io/plot_app?log=69b6d790-1d34-4d5d-ab99-daf9d3d6204a)
Tuned: [link to ulog](https://review.px4.io/plot_app?log=75bb8db5-87ff-45e9-a75b-81e51c7dec5a)
Its not perfectly tuned, but it more or less flies nicely in the simulation. 
-
=> change typhoon_h480 roll-/pitchrate P gain to reduce oscillations

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp, src/drivers/uavcan_v1/CMakeLists.txt, src/drivers/uavcan_v1/NodeManager.cpp, src/drivers/uavcan_v1/NodeManager.hpp, src/drivers/uavcan_v1/Subscribers/NodeIDAllocationData.hpp, src/drivers/uavcan_v1/Uavcan.cpp, src/drivers/uavcan_v1/Uavcan.hpp
Convert UAVCAN.cpp to classes continuation of #16889 furthermore added hash checks so that we don't have singe NodeID anymore
Seperate NodeManager class for assigning Node IDs and set portIDs to UAVCANv1 peripherals
Tested PNP algorithm with FMUK66 and BMS-772
**Open problems**
Double print on startup
```
INFO  [uavcan_v1] Subscribing NodeIDAllocationData.0 on port 0
INFO  [uavcan_v1] Subscribing NodeIDAllocationData.0 on port 0
```
Furthermore for fixed portID gives some UI problems in my class I'm setting _port_id to `PNP1_PORT_ID`
At last we've to think on how to deal with Services (request/response), is the response handler a Subscriber class or should we define another class for that.
=> UAVCANv1 Move PNP from UAVCAN.cpp to NodeManager.cpp

src/modules/mavlink/mavlink_receiver.cpp
This PR fixes the timestamps of `actuator_controls_3` uORB message when `MAV_CMD_DO_SET_ACTUATOR` is being set.
The timestamp was being removed when updating the `actuator_controls_3` uORB message. This messes up when visualizing the log since the timestamp field is empty when running in SITL
Run any SITL simulation, and send `MAV_CMD_DO_SET_ACTUATOR`
e.g.
```
make px4_sitl gazebo_standard_vtol
```
- This is a follow up PR of https://github.com/PX4/PX4-Autopilot/pull/16758
=> Fix actuator controls timestamps for MAV_CMD_DO_SET_ACTUATOR

src/modules/land_detector/MulticopterLandDetector.cpp, src/modules/land_detector/MulticopterLandDetector.h
The hover thrust estimate becomes invalid on final descent, which can disrupt the land detector ground contact logic if MPC_THR_HOVER is sufficiently wrong.
https://logs.px4.io/plot_app?log=3b44224e-4cca-42ad-a1dc-db2acff4f324
=> land_detector: continue respecting hover thrust throughout descent

src/modules/mc_att_control/mc_att_control_params.c
I just saw attitude gains now have the unit Hz and I consider this misleading. Even though 1/s is equivalent to Hz, Hz is used for frequency values and I would not consider the gain a frequency. It's the reciprocal of a timeconstant.
I'd either write explicitly what ratio the gain has (rad/s) / rad if that's allowed to make it very clear. If that's not allowed I'd keep 1/s and if that's not possible anymore remove the units before confusing anyone.
=> mc_att_control_params: remove frequency unit from attitude gains

src/modules/simulator/simulator.h
`uint8_t` is not enough to hold simulated sensor IDs. This caused distance sensor values to be published only 10 times on different distance_sensor instances:
```
ERROR [simulator] 7 has device id 4 and publisher 0x7f998c004360
ERROR [simulator] 8 has device id 4 and publisher (nil)
ERROR [simulator] Publish 2.110000 to 8 with device id 10092548
ERROR [simulator] 0 has device id 4 and publisher 0x7f998c003730
ERROR [simulator] 1 has device id 4 and publisher 0x7f998c0038b0
ERROR [simulator] 2 has device id 4 and publisher 0x7f998c003be0
ERROR [simulator] 3 has device id 4 and publisher 0x7f998c003d60
ERROR [simulator] 4 has device id 4 and publisher 0x7f998c003ee0
ERROR [simulator] 5 has device id 4 and publisher 0x7f998c004060
ERROR [simulator] 6 has device id 4 and publisher …
```
=> simulator: fix lidar sensors

src/drivers/uavcan/sensors/gnss.cpp
**issue:**
When using F9P as RTK BASE in QGC, no data will be sent out from the corresponding CAN interface. 
After debugging, it is found that the RTCM data transmission stays at msg.data = {}; 
**solution:**
msg.data.clear(); Replace msg.data = {};
=> CAN RTCM: Modify the way to clear Data

src/modules/airspeed_selector/airspeed_selector_main.cpp
Stall speed check would otherwise trigger during landing if airspeed falls below
stall speed before landing is detected.
The airspeed checks trigger if the airspeed falls below the specified stall speed. Also when the vehicle is landing (and already on he ground), as the current fixed-wing land detector doesn't detect ground contact.
Disable airspeed validity checks if position setpoint type is LAND.
Add detection of ground_contact flag also to fixed-wing land detector. 
SITL tested with standard VTOL and Plane.
There are currently too many parameters out there for a similar property of an airframe:
`ASPD_STALL` (used in airspeed …
=> Airspeed Selector: do not run checks during landing

ROMFS/px4fmu_common/init.d-posix/airframes/1043_standard_vtol_drop, ROMFS/px4fmu_common/init.d-posix/airframes/1043_standard_vtol_drop.post, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt, ROMFS/px4fmu_common/mixers-sitl/CMakeLists.txt, ROMFS/px4fmu_common/mixers-sitl/package_drop.aux.mix, platforms/posix/cmake/sitl_target.cmake
As drone deliveries are becoming more and more important, we need to add a way to test drone delivery scenarios in PX4.
This PR adds a model called `standard_vtol_drop`, which simulates a drone delivery scenario in SITL Gazebo.
This was tested with a mavsdk application sending `MAV_CMD_DO_SET_ACTUATOR` commands.
```
make px4_sitl gazebo_standard_vtol_drop
```
[![Demo](https://img.youtube.com/vi/RdvxvoZ1rwA/0.jpg)](https://youtu.be/RdvxvoZ1rwA)
- This is based on the `MAV_CMD_DO_SET_ACTUATOR` support added in https://github.com/PX4/PX4-Autopilot/pull/16758
- This PR depends on a sitl_gazebo PR: https://github.com/PX4/PX4-SITL_gazebo/pull/724
=> Add a payload drop model for drone delivery scenarios in SITL Gazebo

Makefile
This can happen if you interrupt cmake generation fairly late when using the ninja-build generator (our default).
=> Makefile: wipe incomplete ninja build generation

ROMFS/px4fmu_common/init.d-posix/airframes/10018_iris_foggy_lidar, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt, platforms/posix/cmake/sitl_target.cmake
A follow-up on https://github.com/PX4/PX4-SITL_gazebo/pull/725, which allows to test the firmware behaviour in foggy environments.
This adds an iris with a lidar that measures distances as if the drone is within dense fog (compare with a real flight https://review.px4.io/plot_app?log=c9482a7a-0608-4cab-9ad3-5a6dbef7f2f7). 
@julianoes would this be a candidate for extending the failure injection?
=> SITL: add iris with fog-simulating lidar

src/modules/flight_mode_manager/FlightModeManager.cpp, src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.hpp, src/modules/flight_mode_manager/tasks/ManualAcceleration/FlightTaskManualAcceleration.cpp, src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.cpp
3 Bugs:
1. In position mode when landing, moving the right stick during ground contact and taking off again in exactly the right timing it's possible to get invalid setpoints.
2. Every mode switch results in the task doing EKF reset handling.
3. The initialization of the acceleration stick mapping sets the wrong state.
1.  When unlocking the position the velocity setpoint feedback is now considered since https://github.com/PX4/PX4-Autopilot/pull/16791. During ground contact the executed setpoint is NAN even though the task commanded a velocity. This is now handled gracefully by not considering the feedback if it's NAN.
2. This is occuring because of an idea to be able to reinitialize any task on mode change e.g. …
=> Acceleration stick mapping invalid setpoint corner case

platforms/nuttx/Debug/flash_bootloader.jlink.in, platforms/nuttx/cmake/jlink.cmake
Works for all boards that build their own bootlooder in tree (eg STM32H7) or carry a bootloader binary in their board directory. The target will not exist if the bootloader isn't available.
``` Console
dagar@dagar-desktop:~/git/PX4-Autopilot$ make cuav_nora_default jlink_flash_bootloader
[0/4] Performing build step for 'bootloader_firmware'
ninja: no work to do.
[3/4] cd /home/dagar/git/PX4-Autopilot/build/cuav_nora_default && /usr/bin/JLinkExe -CommandFile /home/dagar/git/PX4-Autopilot/build/cuav_nora_default/flash_bootloader.jlink
SEGGER J-Link Commander V6.88 (Compiled Nov 12 2020 18:43:04)
DLL version V6.88, compiled Nov 12 2020 18:42:52
J-Link Command File read successfully.
Processing script file...
J-Link connection not established yet but required for command.
Connecting to J-Link …
```
=> add bootloader flash helper target (jlink_flash_bootloader)

src/modules/commander/Commander.cpp, src/modules/mc_pos_control/MulticopterPositionControl.cpp
Reported by @JonasVautherin the acceleration setpoints are not executed in offboard.
I had a look at his log and the position controller is not running because it only listens to the climb_rate control mode flag, not the acceleration one. I made this for him to test. As it stands the position controller has to run for acceleration setpoints and we should probably also add the flag to the velocity controlled modes for completeness.
@JonasVautherin ? :innocent: 
Previous related changes:
- Make acceleration setpoints work: https://github.com/PX4/PX4-Autopilot/pull/16498
- Control flags refactor: https://github.com/PX4/PX4-Autopilot/pull/16266/files#diff-e4b611e75eba3844 …
=> Run mc_pos_control for acceleration control mode flag

src/lib/parameters/CMakeLists.txt, src/lib/parameters/parameters.cpp
This fixes an edge case with the new runtime parameter default mechanism where if you manually set a parameter with a custom runtime default to the underlying default value it will be lost on the next import. This is because the param set during  import wouldn't store anything being set to default, but the custom airframe defaults hadn't been loaded yet (early in boot).
- keep param_set() even if setting to default (runtime or static)
- param export skip defaults
- param_value_is_default() is more expensive now (actually finds the value and compares), but it's used infrequently
- fixes https://github.com/PX4/PX4-Autopilot/issues/17016
=> parameters: fix runtime default edge case

Tools/sitl_run.sh
This adds the env variable PX4_NO_FOLLOW_MODE to disable the follow mode in Gazebo.
This was introduced in https://github.com/PX4/PX4-Autopilot/pull/16568 and I find it quite annoying because it means zoom is hardcoded at 8m, see https://github.com/osrf/gazebo/issues/1251.
FYI @JonasVautherin
=> Tools: add env variable to disable follow mode

src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_messages.cpp
@julianoes can we get rid of this? Unlike all the other mavlink streams "CAMERA_CAPTURE" doesn't actually correspond to a mavlink message.
=> mavlink: delete fake CAMERA_CAPTURE stream

src/modules/gyro_fft/GyroFFT.cpp, src/modules/gyro_fft/GyroFFT.hpp
- this is used for the length of dynamically allocated buffers that aren't resized while running
=> gyro_fft: don't update FFT length while running

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp
``` Console
WARN  [load_mon] wq:rate_ctrl low on stack! (296 bytes left)
WARN  [load_mon] wq:rate_ctrl low on stack! (296 bytes left)
WARN  [load_mon] wq:rate_ctrl low on stack! (296 bytes left)
WARN  [load_mon] wq:rate_ctrl low on stack! (296 bytes left)
WARN  [load_mon] wq:rate_ctrl low on stack! (296 bytes left)
```
=> px4_work_queue: increase wq:rate_ctrl stack

src/lib/parameters/param.h, src/lib/parameters/parameters.cpp, src/modules/logger/logger.cpp, src/modules/logger/logger.h, src/modules/logger/messages.h, src/systemcmds/param/param.cpp
- param: remove set-default print's during bootup 
- adds new ulog message & compatibility flag for default parameter values
- separately add airframe and system-wide defaults
- log only non-volatile defaults that are different from the current value
- additional size is ~3KB for 100 params
=> logging: add parameter defaults

platforms/nuttx/init/stm32h7/rc.board_arch_defaults, src/modules/logger/logged_topics.cpp
On STM32H7 the `gyro_fft` module costs < 2% cpu and runs in wq:lp_default. Let's run it by default to start getting some data.
Note you have to set `IMU_GYRO_DYN_NF` to actually use the detected peak frequencies for the bank of gyro notch filters.
=> gyro_fft: run by default on STM32H7

src/modules/mavlink/mavlink_receiver.cpp
**Describe the problem solved by this pull request**
`YAW_IGNORE` and `YAW_RATE_IGNORE` flag is not checked correctly. The new message handler compares `type_mask` directly with bits, not masking it.
I have changed it to be as with other flags.
Don't see any.
Before my takeoff algorithm was making unwanted yaw corrections, after it works as in 1.11.0.
=> mavlink: fix yaw and yaw_rate ignore mask check

src/modules/sih/sih.cpp, src/modules/sih/sih.hpp, src/modules/sih/sih_params.c
I added a time constant on the thrusters to make it more realistic.
When given a throttle input, the thrust force is not instantaneous (on a vehicle in the real world).
I decided here to model this dynamic as a first order transfer function with time constant tau, associated with the parameter SIH_T_TAU.
I tested the general behaviour in SIH. When tau is increased, the vehicle start to oscillate.
This gives an upper limit on the rate control gains, which brings this simulation a bit closer to the reality.
I will also test the shape of the signal (very soon, I'll post the result here).
I set SIH_T_TAU=0.05 seconds by default, for a vehicle of 1kg. Going from 0 to full thrust takes 0.2s in this case, which seems a fair value to start with. This time constant is 0.005s in jMAVsim, but I …
=> time constant added on thrusters, and minor cleanup

src/modules/mavlink/mavlink_receiver.cpp, src/modules/mc_att_control/AttitudeControl/AttitudeControl.cpp
When sending ignore_yaw_rate flag for attitude setpoints in offboard mode, the case handling seems to be reversed. 
This PR fixes the yaw rate ignore case handling for offboard control using the SET_ATTITUDE_TARGET message.
For multirotors, the fix resulted in invalidating the rate setpoints all together with multiplying the `yawspeed_setpoint =nan` directly to the rates setpoints. Therefore a check was added to the MC attitude controller if the yaw speed setpoint is valid
Before PR: Even if the yaw_rate_ignore flag is set, the vehicle still follows the yaw rate commands in the mavlink message
https://review.px4.io/plot_app?log=a801deb4-346f-48b1-8370-78541b21b832
After PR: :sunglasses: …
=> Fix IGNORE_YAW_RATE handling for attitude setpoints in offboard

boards/cuav/x7pro/default.cmake, src/modules/mavlink/mavlink_shell.cpp
This fixes the MAVLink shell for the X7 Pro (and likely other H7 targets). I would love to have additional hardening so we are not timing dependent. @bkueng could you maybe add a commit for that?
=> Fix mavlink shell

boards/px4/fmu-v5x/default.cmake
PX4 fmu-v5x slipped over the flash limit in master once a number of things had merged.
=> boards: px4/fmu-v5x disable optional external IMU drivers

boards/cuav/x7pro/default.cmake, boards/cubepilot/cubeyellow/console.cmake, boards/cubepilot/cubeyellow/default.cmake, boards/holybro/durandal-v1/default.cmake, boards/holybro/pix32v5/default.cmake, boards/px4/fmu-v3/default.cmake, boards/px4/fmu-v4/default.cmake, boards/px4/fmu-v4/uavcanv1.cmake, boards/px4/fmu-v5/ctrlalloc.cmake, boards/px4/fmu-v5/default.cmake, boards/px4/fmu-v5/fixedwing.cmake, boards/px4/fmu-v5/multicopter.cmake, boards/px4/fmu-v5/rover.cmake, boards/px4/fmu-v5/rtps.cmake, boards/px4/fmu-v5/uavcanv1.cmake, boards/px4/fmu-v5x/base_phy_DP83848C.cmake, boards/px4/fmu-v6x/default.cmake
Looks like we're finally at that point with the 2 MB boards.
=> boards: remove optional external ADIS IMUs to save flash

.ci/Jenkinsfile-compile, .github/workflows/compile_nuttx.yml, boards/px4/fmu-v6u/test.cmake
- create separate `px4_fmu-v6u_test` variant
I think this will become the pattern going forward as we bump up against flash limits in the default variants.
=> boards: px4_fmu-v6u_default address flash shortage

src/modules/commander/Commander.cpp, src/modules/commander/state_machine_helper.cpp, src/modules/commander/state_machine_helper.h
- Added navigation state info to [commander] print_status
- You can see the navigation state when you type commander state in the mavlink shell
- It makes debugging more convenient
=> [commander] more detailed print_status

boards/holybro/kakutef7/default.cmake
@bkueng can you give this a quick try? If this helps then please take a look at the subset of included drivers to add any magnetometer drivers actually needed.
=> boards: holybro/kakutef7 disable CONSTRAINED_FLASH to increase optimization

Tools/setup/ubuntu.sh
When using `ubuntu.sh` the script fails if using an architecture different from the x86-64.
The correct version of the cross-compiler for ARM is get with wget from the correct repository.
Use alternative commands to get CPU architecture.
A check has been made to understand which versions of the `gcc-arm-none-eabi` are available for which architectures.
Tested with Ubuntu 18.04 on Jetson TX2.
=> Update ubuntu.sh to allow multiple host architectures

src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
Thanks to @dagar the coordinates and altitude can now be applied independently see https://github.com/PX4/PX4-Autopilot/commit/263b00b65fc89c7fd9383f0364760fceb15ea12a#diff-89127f427c1fc4e2fb02b97822ec75dc1bc7a4690ae4cd3aba8bc4f811250717R80
But now if the coordinates or altitude could not get set the command is still acknowledged.
- I make sure to send a not acknowledge to the command if any coordinates or altitude were commanded but it failed.
- I also changed the default center location to be exactly where the vehicle currently is to allow exact positioning of the center by flying there manually and command the Orbit without any center coordinates. The radius offset comes from an early testing stage where the …
=> FlightTaskOrbit: NACK command if coordinates could not get applied

boards/ark/can-flow/init/rc.board_sensors
This PR updates the ARK Flow sensor rotations to be correct. 
Moving the board to the right.
```
nsh> listener optical_flow
TOPIC: optical_flow
optical_flow_s
timestamp: 50441474  (0.012599 seconds ago)
pixel_flow_x_integral: 0.0320
pixel_flow_y_integral: 0.0080
gyro_x_rate_integral: nan
gyro_y_rate_integral: nan
gyro_z_rate_integral: nan
ground_distance_m: 0.0000
integration_timespan: 15594
time_since_last_sonar_update: 0
max_flow_rate: 7.4000
min_ground_distance: 0.0800
max_ground_distance: 30.0000
frame_count_since_last_readout: 2
gyro_temperature: 0
sensor_id: 0
quality: 101
mode: 1
```
Moving the board forward.
```
nsh> listener optical_flow
TOPIC: optical_flow
optical_flow_s
timestamp: 59452534  (0.002112 seconds ago)
pixel_flow_x_integral: -0.0000
pixel_flow_y_integral: 0.0480 …
```
=> ARK Flow sensor rotations

ROMFS/px4fmu_common/init.d-posix/rcS, boards/cuav/x7pro/init/rc.board_defaults, src/modules/gyro_fft/CMakeLists.txt, src/modules/gyro_fft/GyroFFT.cpp, src/modules/gyro_fft/GyroFFT.hpp, src/modules/gyro_fft/parameters.c
- the 1st commit updates gyro_fft to optionally consume `sensor_gyro` if `sensor_gyro_fft`
- converting the float gyro data back to int16_t for the FFT is perhaps a bit odd, but at least closes the gap
- the 2nd commit manually inlines a subset of the CMSIS function arm_rfft_init_q15() so that only a subset of FFT lengths are supported
- this saves about 25 kB of flash
=> gyro_fft: support sensor_gyro (non-fifo)

src/drivers/uavcan/uavcan_drivers/stm32h7/driver/include/uavcan_stm32h7/can.hpp, src/drivers/uavcan/uavcan_drivers/stm32h7/driver/src/uc_stm32h7_can.cpp
Referring to the refernece manual:
Tx queue operation is configured by programming FDCAN_TXBC.TFQM to 1. Messages
stored in the Tx queue are transmitted starting with the message with the lowest message
ID (highest priority). **In case that multiple queue buffers are configured with the same
message ID, the queue buffer with the lowest buffer number is transmitted first**
Tx FIFO operation is configured by programming FDCAN_TXBC.TFQM to 0. Messages
stored in the Tx FIFO are transmitted starting with the message referenced by the get index
FDCAN_TXFQS.TFGI. After each transmission the get index is incremented cyclically until
the Tx FIFO is empty. The Tx FIFO enables transmission of messages with the same
message ID from different Tx buffers in the order these messages have been written to …
=> uavcan_stm32h7:can driver preserve ordering & respect timeouts on borked hardware

src/modules/mc_pos_control/mc_pos_control_params.c
It is used in autonomous modes only and has no influence on Position mode.
=> mc_pos_control_params: correct cruise speed description

src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.cpp, src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.hpp
When two or more axes have the same rate limitations, the resulting path is not straight if the endpoint isn't the same. The technique to make straight lines is known as "time synchronization" and can be difficult if multiples derivatives have their rate limited. In our case, the acceleration is controlled and only the jerk is limited, so we can simply adjust the amount of jerk allowed on each axis depending on the direction of the setpoint increment.
Before: Banana
With this PR:
No Banana
=> FlightTaskAcceleration: synchronize XY acceleration profiles

boards/ark/can-flow/debug.cmake
This strips out the command line debug helpers from `ark_can-flow_default` to reduce the binary size. Everything is still available in  `ark_can-flow_debug`.
``` Console
Memory region         Used Size  Region Size  %age Used
flash:      397481 B       448 KB     86.64%
sram:       12672 B       192 KB      6.45%
```
``` Console
Memory region         Used Size  Region Size  %age Used
flash:      268753 B       448 KB     58.58%
sram:       12588 B       192 KB      6.40%
```
=> boards: ark/can-flow add debug build and reduce default

src/systemcmds/netman/netman.cpp
A missing `-`  caused the first boot settings to be set
=> netman:Fix setting on first boot

src/drivers/drv_hrt.h
This is just a small fix, no functional changes, but solves what I assume is a naming error:
The user-defined literals for milli- and microseconds
should have argument names matching their units. The
current argument names 'seconds' is probably an oversight.
=> drv_hrt: Fix hrt_abstime literal argument names

src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp, src/modules/commander/Commander.cpp
This should prevent some of the timeouts we have been seeing in CI tests where arming silently fails.
When reviewing check the individual commit messages.
https://github.com/PX4/PX4-Autopilot/pull/17158/checks?check_run_id=2138194910#step:17:212
https://github.com/PX4/PX4-Autopilot/pull/17158/checks?check_run_id=2138194952#step:17:212
=> Improve ekf2 preflight check

CMakeLists.txt
- this is useful because it installs the python requirements using the python interpreter found and used by cmake
=> cmake: add install_python_requirements helper

src/modules/land_detector/land_detector_params_fw.c, src/modules/land_detector/land_detector_params_mc.c
cc @bresch 
When using units besides the SI system, the description of the units used by the parameter and the unit expected as input don't agree. For example, someone whose ground control software is using mph will see the parameter field take mph as input, but the description claims that this parameter should be given input in m/s.
By removing the units from the descriptive comments in the land_detector_params files, the user should not see disagreeing units between the input field and the description of the parameter.
**Additional …
=> Remove hardcoded units in land_detector_params

platforms/posix/src/px4/common/include/px4_platform/micro_hal.h
Fixes errors in the form of 'error: statement has no effect'
fixes #17173
@Pskoog3 can you test this?
=> micro_hal: use inline methods instead of #define's

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp
``` Console
WARN  [load_mon] wq:UART4 low on stack! (224 bytes left)
```
=> px4_work_queue: increasae UART stack

src/modules/mavlink/mavlink_receiver.cpp
When running multiple vehicles in simulation, all UTM_GLOBAL_POSITION messages are ignored by handle_message_utm_global_position() because uuid is not defined.
This solution ignores the messages that have the same mavlink system id as the current instance of the vehicle.
maybe it is be possible to ignore the uuid of the board and consider only the mavlink system id since it should be unique within a single network.
@LowOrbitIonCannon @dk7xe FYI
=> ignore self published messages in simulation using mavlink system id

.ci/Jenkinsfile-compile, .github/workflows/compile_nuttx.yml
Add nxp_ucans32k146_canbootloader to CI archive to distribute UCANS32K146 bootloader on the web
=> Add nxp_ucans32k146_canbootloader to CI archive to

ROMFS/px4fmu_common/init.d-posix/rcS
I don't think we should be broadcasting by default as we haven't done that in the past. This suddenly spams the network with a lot of messages, and leads to confusing situations in offices where there are multiple PX4 SITL and QGC intances are open.
Thi was introduced in  #14460.
=> Disable MAVLink broadcast by default for SITL

src/drivers/pwm_out/CMakeLists.txt, src/drivers/pwm_out/PWMOut.cpp
- PWM_OUT_MAX_INSTANCES is a constant (static constexpr) not available to the preprocessor
=> pwm_out: check PWM_OUT_MAX_INSTANCES with conditional

src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp, src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.hpp
For efficiency reasons when using FIFO gyro data we perform all filtering (angular velocity, angular acceleration) directly on all available raw data per axis, then apply the sensor calibration and corrections on the filtered value right before publication. This PR unifies that filtering so that it's the same for both FIFO and non-FIFO gyros. The code is a bit uglier, but this reduces the maintenance burden and any surprises when switching between FIFO and non-FIFO gyro sources (could happen midflight).
=> sensors/vehicle_angular_velocity: unify filtering for both FIFO and regular use cases

.github/workflows/deploy_all.yml, .github/workflows/metadata.yml, CMakeLists.txt, Makefile, Tools/generate_board_targets_json.py, Tools/px4.py, Tools/px_mkfw.py, boards/px4/fmu-v4/uavcanv1.cmake, src/lib/version/get_git_tag_or_branch_version.sh, src/lib/version/px_update_git_header.py, src/lib/version/version.c, src/lib/version/version.h, src/modules/logger/logger.cpp
- enumerate all existing build targets & variants automatically (with some excludes, like qurt or sitl replay)
- pushes parameter metadata to S3. This can be extended to other metadata & binaries as well (replacing Jenkins)
- directory structure is as below
- there's some inconsistency with container naming (some add `-focal` while others do not) that should be fixed
- ignores `ext/*` git tags, to allow for external/extra git tags
- general metadata, containing all modules (e.g. for flight review): `Firmware/<version>/_general/`
- per-board: `Firmware/<version>/<board>/`
- `version`: if on a git tag, it's the git tag, if on a `release/x.y` branch, it's `release-x.y`, otherwise it's `master`. This could also be made more granular (e.g. commits on master) if needed.
- `board`: this is the …
=> use github CI to deploy metadata to S3

src/modules/gyro_fft/GyroFFT.cpp
- early in startup the selected gyro may not be published yet
=> gyro_fft: silence initial sensor selection attempt

Tools/process_sensor_caldata.py
fixed the figure numbers to avoid plot conflicts
The first and second barometer plots are overlapping each other as you can see below
Baro0 and Baro1 figure numbers were identical. Separating them solved the issue.
=> process_sensor_caldata.py: Fix 2nd barometer plot

src/modules/commander/Arming/PreFlightCheck/checks/magnetometerCheck.cpp, src/modules/commander/Commander.cpp
The user isn't noticed if EKF2 rejected the mag completely (e.g.: during a yaw emergency reset) and is allowed to takeoff again.
Check the `mag_fault` flag of each estimator and fail the pre-flight check for the used mag. This works with multi-ekfs and multi mags.
Additional modifications:
- increase the "nav failed" timeout to 2s in order to give more time to EKF2 to trigger a yaw emergency reset (that has 1s probation period)
- update ECL to include https://github.com/PX4/PX4-ECL/pull/992, allowing faster convergence when using better GNSS receivers
Sitl and flight tests.
=> Add mag fault preflt check

posix-configs/rpi/pilotpi_fw.config, posix-configs/rpi/pilotpi_mc.config, posix-configs/rpi/px4.config, posix-configs/rpi/px4_fw.config, posix-configs/rpi/px4_hil.config, posix-configs/rpi/px4_test.config
The ekf2 frontend typically runs in the background for up to 30 seconds waiting for all instances to appear, but this isn't supported by the legacy posix launcher.
=> posix-configs: rpi multi-EKF updates

boards/mro/x21/init/rc.board_sensors
- fixes https://github.com/PX4/PX4-Autopilot/issues/17244
=> boards: mRo x21 enable mpu9250 mag (only internal)

msg/vehicle_status_flags.msg, src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp, src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.hpp, src/modules/commander/Arming/PreFlightCheck/checks/sdcardCheck.cpp
statfs accesses the file-system and can be blocking for an extended period. Since the SD card check is part of the preflight checks in the main thread of commander, it could block its execution and cause various issues. Yet, the SD card is only mounted in rcS during boot so the state will not change after the first check.
Store the SD card check result and only run statfs again if the card was not detected before.
Run check in a separate thread or module to not block commander, but unless there are multiple SD cards I don't think this is needed.
Tested on a Pixhawk 4.
None
=> PreFlightCheck: Check if SD card is present only once and store the result

src/modules/ekf2/ekf2_params.c
The range aid defaults are fairly conservative (max horizontal velocity 1 m/s, and range aid gate 1 SD), I think it should be safe to enable by default. This is to help more users get the benefit (by default) and perhaps circumvent the common mistake of setting EKF2_HGT_MODE to range sensor.
=> ekf2: enable range aid by default

msg/commander_state.msg, src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/commander/ManualControl.hpp, src/modules/commander/state_machine_helper.cpp
Currently, the default initial flight mode for systems that are controlled with a Joystick is MANUAL.
This can be a problem as usually systems that use such controllers are mostly flown in Altitude or Position: if an inexperienced user forgets to manually command a different flight mode things can potentially end in a bad way.
Based on the above considerations, Manual mode should be only entered if the user explicitly request it. 
In the case of a RC configuration this does not happen as the Flight Mode switches are evaluated at initialization,
thus the system will switch accordingly.
This PR centralizes the fallback logic for flight modes and introduces an initializes the system to Position Control if the …
=> Clean up logic for flight mode transitions in commander, handle Joystick initialization

src/lib/slew_rate/CMakeLists.txt, src/lib/slew_rate/SlewRateTest.cpp, src/lib/slew_rate/SlewRateYawTest.cpp, src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.hpp, src/modules/mc_pos_control/CMakeLists.txt, src/modules/mc_pos_control/MulticopterPositionControl.cpp, src/modules/mc_pos_control/MulticopterPositionControl.hpp, src/modules/mc_pos_control/Takeoff/Takeoff.cpp, src/modules/mc_pos_control/Takeoff/Takeoff.hpp
When taking off e.g. in altitude mode the maximum tilt is limited to [MPC_TILTMAX_LND](https://docs.px4.io/master/en/advanced_config/parameter_reference.html#MPC_TILTMAX_LND) degree and after takeoff in general flight to [MPC_TILTMAX_AIR](https://docs.px4.io/master/en/advanced_config/parameter_reference.html#MPC_TILTMAX_AIR). The current implementation causes a twitch when relaxing that limit after takeoff.
I was investigating multiple possibilities to solve the issue. The first one was to just ramp the tilt limit with the takeoff ramp but it doesn't result in the correct user experience. But what's left is:
- Refactor the takeoff ramp to work with an internal progress value between 0 and 1. It makes it more …
=> Fix twitch when relaxing takeoff tilt limit

ROMFS/px4fmu_common/init.d-posix/rcS, src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/commander/commander_params.c
1. Onboard computer time-out was hardcoded to 5 seconds, which in general should be enough, but removes flexibility to the developer if it has a system critically dependent on a link to a companion computer (which is the case for VIO or obstacle avoidance integrated systems, where we might want a lower time-out);
2. Besides 1., tests within MAVSDK using onboard computer connections were resulting in commander `Connection to mission computer lost` and `Onboard controller regained` because of the fact we run the tests faster-than-real-time.
With the addition of this parameter, we can now set the value of the time-out according to the `PX4_SIM_SPEED_FACTOR` (similar to what we do with other parameters).
**Describe …
=> commander: add COM_OBC_LOSS_T

msg/templates/uorb_microcdr/microRTPS_client.cpp.em, msg/templates/urtps/microRTPS_timesync.cpp.em, msg/templates/urtps/microRTPS_timesync.h.em
1.  Excessive calls `hrt_absolute_time()` might lead to accumulated skew which in turn can result on having the timesync from the agent setting offsets which when applied, resulting in timestamps from the future.
2. Using different time sources on the agent side was also resulting in wrong timestamps being set on the messages being sent.
1. Clamp the timestamp to be at max equals to the PX4 system time;
2. Use the same time source (`CLOCK_MONOTONIC`).
Tested with PX4 SITL and Gazebo.
=> microRTPS: Timesync fixes

msg/tools/uorb_rtps_message_ids.yaml
Some uORB streams required for PX4/Avoidance to work are not enabled by default.
Enable sending:
- `trajectory_waypoint`
- `vehicle_attitude`
- `vehicle_angular_velocity`
- `vehicle_local_position`
- `vehicle_status`
- `vehicle_trajectory_waypoint_desired`
Enable receiving:
- `telemetry_status`
- `trajectory_bezier`
- `vehicle_trajectory_bezier`
Tested with PX4 SITL and Gazebo.
=> microRTPS: enable required streams for PX4 Avoidance

ROMFS/px4fmu_common/init.d-posix/rcS
**How this PR solves the problem**
changes to the execution of ROMFS/px4fmu_common/init.d-posix/rcS where not applied on the execution of rc.mavlink_override so far.
Simulation is broken with current develop branch otherwise.
=> Make rc.mavlink_override work with change environment 

src/lib/slew_rate/CMakeLists.txt
I realized that https://github.com/PX4/PX4-Autopilot/pull/17066/commits/428be5cbba99d15fc0b15639df488dd4fa5d1b0a broke the Mac build only. Didn't see it in the huge list of successful CI jobs.
I'm adding back the dummy cpp source to hopefully make whatever cmake generator mac uses happy again. It's the only difference I see to how include other libraries.
Let's see CI, I have no mac.
=> SlewRate: add back dummy file for mac build

ROMFS/px4fmu_common/init.d-posix/rcS, ROMFS/px4fmu_common/init.d/airframes/4053_holybro_kopis2, ROMFS/px4fmu_common/init.d/rcS, src/lib/systemlib/system_params.c, src/modules/local_position_estimator/BlockLocalPositionEstimator.hpp, src/modules/mavlink/mavlink_parameters.cpp
With the airframe defaults there's no use for that anymore
=> autostart scripts: remove SYS_PARAM_VER

src/lib/tecs/TECS.cpp, src/lib/tecs/TECS.hpp
The prediction of the true airspeed complementary filter was using a heavily filtered version of the inertial acceleration.
This removes the high frequency content of that signal and is thus not desired.
BEFORE:
AFTER:
=> TECS: Use raw inertial acceleration for true airspeed filter

ROMFS/px4fmu_common/init.d-posix/rcS, src/modules/simulator/simulator.cpp, src/modules/simulator/simulator.h, src/modules/simulator/simulator_mavlink.cpp
This is a branched merge of the work done by FernandezR in [PR 15965](https://github.com/PX4/PX4-Autopilot/pull/15965).
Adds to the existing simulator "-t" support  the "-h" option passing remote host name instead of ip address.
Also adds environment variable support to etc/init.d-posix/rcS.
Added use of PX4_SIM_HOSTNAME and PX4_SIM_HOST_ADDR environment variables to pass simulator hostname or ip address through the …
=> Add support for simulators running on a different host than the PX4 instance

src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp
It's important to track (and eliminate) these message gaps, but printing to the console frequently can hurt realtime performance and even cause additional messages drops.
=> ekf2: replace vehicle_imu lost error message with perf count

src/modules/mavlink/mavlink_receiver.cpp
With the recent developments of control allocation and UUVs and also fully actuated systems, there needs to be a way to conveniently set 3D thrust setpoints when developing controllers.
Offboard mode provides an interface for this, but the interface for setting 3D thrust setpoints were missing in the `SET_ATTITUDE_TARGET` mavlink message
This PR adds support for `thrust_body` where 3D thrust setpoints in the body frame can be set by the new mavlink extension. 
This has been tested with the generated mavlink v2 header library, and works as intended
- This PR is written on top of https://github.com/PX4/PX4-Autopilot/pull/16739
- This requires the mavlink PR …
=> Add support for 3D thrust setpoints for offboard attitude control

src/modules/sensors/vehicle_angular_velocity/imu_gyro_parameters.c
Searching for a less bad conservative default value.
@MaEtUgR
=> IMU_DGYRO_CUTOFF increase default 10 -> 20 Hz

boards/holybro/can-gps-v1/debug.cmake
Certainly not ideal but fixes the build and thus metadata deployment for now.
=> holybro_can-gps-v1_debug: disable ekf & listener due to flash overflow

boards/cuav/x7pro/default.cmake
This was incorrectly dropped in the board sync. https://github.com/PX4/PX4-Autopilot/commit/631d1647d3339cff34dcdbbe55a8c1bcb1e603c1#diff-685d9a8f0fe5b5c6e79261ea48f7a70f7a9d9e18a726240d118c2274b115ba9c
=> boards: cuav x7pro include correct adis IMU

boards/holybro/durandal-v1/default.cmake, boards/holybro/durandal-v1/nuttx-config/include/board.h, boards/px4/fmu-v6x/default.cmake, boards/px4/fmu-v6x/nuttx-config/include/board.h
> @david_s5 uavcan (v0) still disabled on px4_fmu-v6x and holybro_durandal?
@dagar - now enabled. Had to disable tests to fit, is there a better choice of things to disable?
=> Add UAVCAN on FMUv6X and Durandal

src/drivers/uavcan/uavcan_servers.cpp, src/drivers/uavcan/uavcan_servers.hpp
- remove verbose UAVCAN command bridge prefix
- disable many normal PX4_INFO messages entirely (kept as PX4_DEBUG)
- properly exit when arming (silently)
- closes https://github.com/PX4/PX4-Autopilot/issues/17305
@ecmnet can you give this a try?
=> uavcan: quiet server output

src/modules/sensors/vehicle_imu/VehicleIMU.cpp, src/modules/sensors/vehicle_imu/VehicleIMU.hpp
Short term solution to prevent people from missing this critical situation.
Note: We also send this via Mavlink `VIBRATION`. https://github.com/PX4/PX4-Autopilot/blob/b66ae5f2d4269ff9ddf24e68bda69401579b5ae0/src/modules/mavlink/streams/VIBRATION.hpp#L96-L116
=> sensors/vehicle_imu: periodically send mavlink critical message if clipping

src/modules/vtol_att_control/tailsitter.cpp, src/modules/vtol_att_control/vtol_att_control_main.cpp, src/modules/vtol_att_control/vtol_type.h
Tailsitter VTOLs very occasionally gets stuck with zero roll and pitch angle in multicopter mode after
a forward transition command is issued.
Log files with the transition failure:
https://logs.px4.io/plot_app?log=d3c74285-5ae5-430d-a1bd-1b4e6de13938
https://review.px4.io/plot_app?log=8d86e43c-5570-4480-9123-7e25669c5463
In the above logs you can see the pitch and roll sp set to zero during the forward transition. 
This very rare behavior is triggered by the following events:
1> a forward transition is triggered either in auto or manual mode.
2> in the vtol_att_control main loop, if multicopter and fixed wing attitude setpoints are not updated, transition state is not updated
3> the commander changes the vehicle status to transition mode.
4> multicopter pos controller initiated …
=> vtol_att_control: occasional tailsitter forward transition failure

ROMFS/px4fmu_common/init.d/rc.sensors, src/drivers/imu/analog_devices/adis16448/parameters.c
Previously, the adis16448 external IMU had to be started manually, therefore it could not be enabled / disabled through a parameter.
This commit adds enabling adis16448 with a parameter
- @dagar I am having problems understanding how I can expose `SENS_EN_ADIS16448`. How are `parameters.c` being read in other drivers?
=> Enable adis16448 with param

src/modules/commander/commander_params.c
Now that the safety button is disabled by default on most boards I think it also makes sense to disable prearm mode by default as well. By default nothing in the system should be active until a user explicitly arms.
=> commander: COM_PREARM_MODE disable by default

src/modules/fw_att_control/FixedwingAttitudeControl.cpp
Fixes https://github.com/PX4/PX4-Autopilot/issues/16979
=> FW attitude controller: add protection against division by zero in airspeed scaling

ROMFS/px4fmu_common/init.d/rcS
Boards on the test rack are periodically getting stuck playing the IO update tune.
=> ROMFS: tune_control stop if px4io update fails

.ci/Jenkinsfile-compile, .github/workflows/compile_nuttx.yml, boards/modalai/fc-v1/rtps.cmake
Adds rtps support for modalai/fc-v1
Copied modalai/fc-v1/default.cmake to modalai/fc-v1/rtps.cmake and changed the LABEL to rtps and un-commented the micrortps_bridge module, then added "modalai_fc-v1_rtps" to Jenkinsfile-compile
I started the module on Telem1 and connected to voxl's microhard usb port with an FTDI adapter. Running the micrortps_agent, I'm able to echo ros topics
=> boards: modalai fc-v1 add rtps cmake

ROMFS/px4fmu_common/init.d/rcS
Supposedly this largely fixes connectivity issues with the Here 3, although I'd still like to understand and address the core issue. Regardless of that particular issue I think it still makes sense to start UAVCAN as early as possible for the sake of notifications (lights and buzzers on CAN), peripheral parameter sync, etc.
**NEEDS TESTING**
=> ROMFS: rcS start uavcan much earlier

.github/workflows/sitl_tests.yml, test/mavsdk_tests/CMakeLists.txt, test/mavsdk_tests/autopilot_tester.cpp, test/mavsdk_tests/autopilot_tester.h, test/mavsdk_tests/configs/sitl.json, test/mavsdk_tests/mavsdk_test_runner.py, test/mavsdk_tests/process_helper.py, test/mavsdk_tests/test_main.cpp, test/mavsdk_tests/test_vtol_mission.cpp, test/mavsdk_tests/vtol_mission.plan, test/mavsdk_tests/vtol_mission_allmend.plan
This adds VTOL mission tests based on a QGC .plan mission imported using the MAVSDK MissionRaw plugin.
=> mavsdk_tests: add VTOL mission tests

src/modules/sensors/vehicle_imu/VehicleIMU.cpp
Trying to find a reasonable value that doesn't falsely trigger on the ground (eg handling a non-isolated flight controller on a table top).
=> sensors/vehicle_imu: increase threshold for clipping warning

src/modules/mavlink/mavlink_receiver.cpp, src/modules/simulator/simulator_mavlink.cpp
In `MavlinkReceiver::handle_message_landing_target`, if `landing_target.frame != MAV_FRAME_LOCAL_NED` then the message is handled as a "Target Relative to Captured Image" message. [Per MAVLink's documentation](https://mavlink.io/en/services/landing_target.html), PX4 does not handle frames other than `MAV_FRAME_LOCAL_NED`. However, treating messages with other frames as a target relative to a captured image does not seem correct. MAVLink appears to be silent on the issue of default parameter values for this message. Users may supply values of `angle_x`, etc that cause undesirable behavior.
Updated MavlinkReceiver::handle_message_landing_target to warn users when they provide a landing target with an unsupported …
=> Improve Robustness of LANDING_TARGET Message

src/modules/commander/commander_params.c
As per https://github.com/PX4/PX4-user_guide/issues/1177 the docs **must** be incorrect because they are self-conflicting. I think that the thing that is incorrect is the text on the values. 
Further, does this actually mean GPS lock, or does it mean "Position Lock" as defined by EKF fusion. If so, probably docs should also change to reflect that.
=> COM_ARM_WO_GPS - values round the wrong way

src/modules/mavlink/mavlink_receiver.cpp
The mavlink message FOLLOW_TARGET has additional fields that are not being parsed here. See https://mavlink.io/en/messages/common.html#FOLLOW_TARGET for more details.
The follow_target message in PX4 has fields for the velocity:
https://github.com/PX4/PX4-Autopilot/blob/015849b402c67f263225dd81914edff7372b35d1/msg/follow_target.msg#L1-L8
Any reason not to populate these fields in the mavlink_receiver?
I don't think this currently affects any code, as https://github.com/PX4/PX4-Autopilot/blob/master/src/modules/navigator/follow_target.cpp does not use the velocity provided by the target, but rather estimates it from the target's moving position.
=> Parse velocity fields from mavlink's follow_target message

src/lib/parameters/px4params/markdownout.py
This fixes the CSS on the parameters output for sensors table, and generally makes the appearance better: https://docs.px4.io/master/en/advanced_config/parameter_reference.html#sensors
=> Param markdown  - fix sensor param table

boards/modalai/fc-v1/src/board_config.h, boards/omnibus/f4sd/src/board_config.h, boards/px4/fmu-v5/src/board_config.h, src/drivers/rc_input/RCInput.cpp
See issue https://github.com/PX4/PX4-Autopilot/issues/17232
I added BOARD_SUPPORTS_RC_SERIAL_PORT_OUTPUT define to the supported board configs and changed the check for CONFIG_ARCH_BOARD_OMNIBUS_F4SD to BOARD_SUPPORTS_RC_SERIAL_PORT_OUTPUT in RCInput.cpp.
Tested on modalaiFC-V1 board with a crossfire receiver sending telemetry to my radiomaster TX16s transmitter
=> Enable crsf and ghst telemetry on supported boards

boards/px4/fmu-v3/default.cmake, src/drivers/heater/heater.cpp, src/drivers/heater/heater.h
This PR adds support for the Cube Black Heater. It still needs to be tested and tuned. We will likely want to add the tuned parameters into the Cube Black's startup scripts.
@JacobCrabill I see you did the work to support the heater on an IO pin. Did you initially test it on a Cube Black or custom hardware?
=> Fix support for Cube Black Heater

boards/cubepilot/cubeorange/console.cmake, boards/cubepilot/cubeorange/default.cmake, boards/cubepilot/cubeorange/src/board_config.h
Can't use `pwm_input` on CubeOrange.
Enable `pwm_input`. Use same timer/channel/pin as FMU V6X (AUX5)
N/A
Connected main 5 to aux 5:
=> boards: cubeorange enable pwm_input

README.md
New to contributing to open source, not sure what the ettiquite to fixing small typo type things are.  
The problem was that autogyro was denoted twice
proposed solution is just to put the new "high altitude balloons" airframe in its place.
=> Small change/fix to typo to readme - redundant autogyro

src/drivers/pwm_out/PWMOut.cpp, src/drivers/pwm_out/PWMOut.hpp
Bootup failed in some cases with:
`ERROR [mixer] can't reset mixers on /dev/pwm_output1`
The reason was the mode change was not applied yet.
=> fix pwm_out: avoid race condition when setting mode

src/modules/mavlink/mavlink_messages.cpp, src/modules/mavlink/streams/SCALED_IMU2.hpp, src/modules/mavlink/streams/SCALED_IMU3.hpp
These IMU streams weren't correctly reporting size when not advertised which skews the mavlink rate scaling if you don't have all 3 IMUs. This keeps it simple by treating it as 3 separate streams where it's now obvious what's missing compared to other streams.
=> mavlink: streams fix SCALED_IMU size reporting

ROMFS/px4fmu_common/init.d/airframes/13014_vtol_babyshark, src/drivers/pwm_out/PWMOut.cpp, src/drivers/pwm_out/PWMOut.hpp
These fixes are in no particular order, but are all sensitive for the release. Expected additions:
- Checking if we can make the safety switch non-latching (might require the PX4 IO changes - again)
- Set up home location for RTL with relaxed constraints
=> Assorted fixes for the 1.12 release

msg/templates/urtps/microRTPS_agent.cpp.em
The usage description of micrortps_agent was incorrect, the default values of ports were incorrect.
I have corrected the values.
The values could be taken from the constants instead of hard-coded.
I typed `micrortps_agent --help`, read the default values. Then, I run `micrortps_agent -t UDP -r 2020 -s 2019` (i.e., used the default values) and everything is working fine. Before, if I re-typed the values from the usage text, it was not working. `micrortps_client` was started with default settings.
I've created a pull-request in px4_ros_com [https://github.com/PX4/px4_ros_com/pull/80], but got redirected here.
=> fixed micrortps_agent usage description

src/lib/drivers/accelerometer/PX4Accelerometer.hpp, src/lib/drivers/gyroscope/PX4Gyroscope.hpp, src/modules/sensors/vehicle_angular_velocity/imu_gyro_parameters.c
If `IMU_GYRO_RATEMAX` is set to 0 (previous default that meant use per sensor default) some sensors will now run too slow for ekf2, which would then start complaining about missing magnetometer data.
=> IMU_GYRO_RATEMAX: enforce reasonable constraint

boards/holybro/kakutef7/default.cmake, boards/px4/fmu-v5/optimized.cmake, boards/px4/sitl/ctrlalloc.cmake, boards/px4/sitl/default.cmake, boards/px4/sitl/nolockstep.cmake, boards/px4/sitl/rtps.cmake, boards/px4/sitl/test.cmake, cmake/px4_add_board.cmake, src/lib/component_information/CMakeLists.txt
Embed param metadata if not CONSTRAINED_FLASH. The compressed file is about 60KB.
@dagar do you want to create a separate test label for the boards that exceed the limit?
=> COMPONENT_INFORMATION: generally embed param metadata

src/modules/commander/Commander.cpp
When QGC lose connection to FMU next time when connected to FMU user will see the message:
_"Connection to ground station lost"_ 
This can confuse users. 
The solution is using **info** signaling instead of **critical**.
=> Changed message "connection to GCS lost"  from critical to info

src/lib/rc/dsm.cpp, src/lib/rc/rc_tests/RCTest.cpp
The range was artificially limited as an additional precaution after we reverted the more robust system byte base parsing.
- lib/rc: DSM support full Spektrum range (up to 150%) to fix https://github.com/PX4/PX4-Autopilot/issues/17259
- lib/rc: DSM require more channels for DSM guess (improve decoded channel count stability)
- lib/rc: DSM reset guess if duplicate channel numbers are decoded in same packet
- lib/rc: DSM add additional PX4_DEBUG messages in decode
- lib/rc: DSM require stable channel count before returning data
- rc_tests: DSM increase expected drop counts in tests (due to more frames required for guess)
- rc_tests: DSM do one final expected channel count compare regardless of decode count
=> rc: dsm allow full range

src/modules/rc_update/rc_update.cpp
This is a quick RC robustness improvement to prevent sporadic RC from propagating to the rest of the system. We only publish `manual_control_setpoint`, etc if the previous valid RC was less than 1 second before the current. This prevents a sporadic successful decode from going out to the system.
=> rc_update: require consecutive valid input_rc before publishing

src/modules/micrortps_bridge/micrortps_client/microRTPS_client_main.cpp
Fixes issue #17398 
Use px4_get_parameter_value for the baud rate in microRTPS_client_main.cpp to fix this line in rtps_client module.yaml 
[`micrortps_client start -d ${SERIAL_DEV} -b p:${BAUD_PARAM} -l -1`](https://github.com/PX4/PX4-Autopilot/blob/96c7fe4978bab2af970a097f4898e024c2d33440/src/modules/micrortps_bridge/micrortps_client/module.yaml#L12)
This should be cleaned up to match how mavlink does parameter parsing, however the _options structure members can't easily be passed to px4_get_parameter_value. For this reason I suggest removing the _options structure completely and use local members as mavlink does.
Tested on modalai_fc-v1 by setting MAV_0_CONFIG to disabled and RTPS_CONFIG to TELEM1. …
=> Get rtps baud rate as parameter with p: prefix 

boards/px4/fmu-v5/default.cmake, msg/heater_status.msg, src/drivers/heater/heater.cpp, src/drivers/heater/heater.h
Hello,
This PR performs a minor bit of refactoring and adds a status field to the heater_status message to indicate if the temperature setpoint has been achieved within 2.5C.  It also decreases the default heater temperature setpoint to be valid for a wider range of hardware and increases the driver scheduling frequency to reduce potential influence on magnetometers. 
Flight tested on a CubeBlack after resetting the setpoint on the bench from 55C to 35C.  I will post another log from cold shortly.
https://review.px4.io/plot_app?log=3b68e434-421c-4072-8d5d-5385f524fee9
Let me know if you have any questions or would like more information regarding this PR. Thanks!
-Mark
=> Create publish_status() method in the heater driver and add a status field to indicate if the temperature setpoint has been met within 2.5C.

src/modules/rc_update/params_deprecated.c, src/modules/rc_update/rc_update.cpp
This is needed until QGC is fully updated.
=> re-add RC_MAP_RATT_SW (unused) and mark active for QGC

msg/takeoff_status.msg, src/lib/slew_rate/SlewRate.hpp, src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.hpp, src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.cpp, src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.hpp, src/modules/land_detector/MulticopterLandDetector.cpp, src/modules/mc_pos_control/MulticopterPositionControl.cpp, src/modules/mc_pos_control/MulticopterPositionControl.hpp
The acceleration stick mapping checks for setpoint feasibility given the tilt limit. But the tilt is more strictly constrained just during takeoff to ensure the vehicle cannot tip over when leaving the ground. So we got the report that if you go full up full forward input directly off the ground the setpoints are actually unfeasible because of the stricter limit. This results in sluggish bounce back after takeoff because the velocity setpoint is already higher than what was actually achievable.
This issue was there before but got more obvious through the smooth ramp off from the stricter tilt limit:
https://github.com/PX4/PX4-Autopilot/pull/17066
Note: Integrating the velocity setpoint is necessary to allow for straight fast forward flight …
=> Factor in stricter tilt limit during takeoff for acceleration setpoint feasibility check

ROMFS/px4fmu_common/init.d/rc.fw_defaults, src/modules/commander/commander_params.c
Following up on https://discuss.px4.io/t/px4-v1-12-release-coordination/21516/21
I saw that https://github.com/PX4/PX4-Autopilot/commit/1ec8ce58c7e544e96cbda711d85c7f3b21731b9b already directly commited a compromise to master but I'm still suggesting to adjust depending on the vehicle type because the feature clearly interferes with any non-runway fixed wing takeoff and generally makes less sense on fixed-wing.
I suggest to keep the automatic disarm time for multirotors because it proved to be a good value for multirotors. The feature was developed for multirotors and I'd disable it completely for fixed wing. I would honestly did that on my plane and it gets confirmed by the …
=> commander_params: lower COM_DISARM_PRFLT but disable for fixed-wing

Tools/px4airframes/srcparser.py
Followed the [user guide](https://docs.px4.io/master/en/dev_airframes/adding_a_new_frame.html#adding-a-new-airframe-group) to complete the "new" airframe group for the vectored 6 DOF UUV airframe.
Related PRs:
-  PX4/PX4-user_guide#1213
- mavlink/qgroundcontrol#9604
=> srcparser support for  vectored 6 dof uuv airframe added

msg/vehicle_status_flags.msg, src/modules/commander/Arming/PreFlightCheck/checks/preArmCheck.cpp, src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/commander/commander_params.c
Resurrected version of https://github.com/PX4/PX4-Autopilot/pull/14800.
This PR extends monitoring to failures reported by ESCs with telemetry.
ESC checks are enabled/disabled with the `COM_ARM_CHK_ESCS` parameter.
I've been flying this exact code with smart ESCs since the first PR was opened.
=> Commander/preflight checks: Add monitoring to ESC failures

src/lib/parameters/parameters.cpp, src/systemcmds/param/param.cpp
And avoid warning for 'param show -c' or 'param show -a'
=> param: update 'param show-for-airframe' to use set-default

src/modules/logger/logged_topics.cpp
BMS data published every 0.25Sec, but logging is at just abit lower rate of 0.3sec. 
so there are many drops of data.
log battery status every 0.2sec instead of 0.3sec
that should help debugging BMS related issues
=> BMS data logs missing samples

src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.cpp, src/modules/flight_mode_manager/tasks/ManualAcceleration/FlightTaskManualAcceleration.cpp, src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.cpp, src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.hpp
In the default position mode implementation a combination of the default implementation for taking over smoothly:
https://github.com/PX4/PX4-Autopilot/pull/12389/files#diff-3372da232c5d9e1ac174e51bdbbe4d31d63547ce2459b5bbb83e15ea6e54d63eR37
and the recent improvements to take over smoothly from the last mode:
https://github.com/PX4/PX4-Autopilot/pull/17078/files#diff-8d0af4d9e531c4e5b5042aa541daa75f8c8375bfd4467096c2f186a8a501a549R51
lead to the possibility to ramp up the velocity setpoint as if the vehicle was flying because the reset considered its own setpoint from the last loop iteration for taking over smoothly.
The main fix for this is the one line change 9e8d592
It by default reactivates tasks on ground …
=> Fix velocity rampup based on stick while disarmed

Tools/astyle/check_code_style_all.sh
For quite some time now I get this annoying warning message:
`xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value`
when each time when running `make format`.
Looked up the man page: https://man7.org/linux/man-pages/man1/xargs.1.html
> -I replace-str
.... Implies -x and -L 1.
> -L max-lines
Use at most max-lines nonblank input lines per command line. ...
> -n max-args, --max-args=max-args
Use at most max-args arguments per command line. ...
So my interpretation is that `-n 1` is superfluous because `-I string` implies that `-n` cannot be used separately but is implicitly set to one.
I tested and the executed commands of `make …
=> check_code_style_all.sh: remove ignored xargs parameter

src/modules/commander/worker_thread.cpp
- working towards a fix for https://github.com/PX4/PX4-Autopilot/issues/16813
@coderkalyan 
Please use this branch to perform a mag cal (outdoors with GPS) with logging from boot (SDLOG_MODE). From the log we'll be able to set the stack size properly.
=> commander: temporarily increase worker thread stack substantially

src/drivers/imu/invensense/icm42688p/ICM42688P.hpp, src/drivers/imu/invensense/icm42688p/InvenSense_ICM42688P_registers.hpp
Likely no benefit, but saves a bit of cpu (including high rate raw logging) and can be changed later if there's a benefit to the higher rate.
=> icm42688p: limit to 8 kHz for now

src/lib/drivers/accelerometer/PX4Accelerometer.cpp, src/lib/drivers/accelerometer/PX4Accelerometer.hpp, src/lib/drivers/gyroscope/PX4Gyroscope.cpp, src/lib/drivers/gyroscope/PX4Gyroscope.hpp, src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp, src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.hpp
Work in progress fixes for the gyro control data pipeline needed for when the scale factor (FIFO data) changes.
For the sake of efficiency (at 8 kHz) all filtering is performed on the raw data before the calibration and rotation is applied to only the last output. As a result we have to be a bit more careful when switching between sensors or in cases where the gyro scale factor changes (eg icm42688p 20 bit data).
=> sensors/vehicle_angular_velocity: filter reset on scale change fixes

src/modules/sensors/vehicle_imu/VehicleIMU.cpp
- no warning if accel is disabled
- threshold increased 100 -> 1000 (only warn if severe ongoing clipping)
- more generic warning message (vehicle isn't necessarily in air flying)
=> sensors/vehicle_imu: clipping warn increase threshold

src/modules/rover_pos_control/RoverPositionControl.cpp, src/modules/rover_pos_control/RoverPositionControl.hpp
Fixes #17381 
Fix Dshot not initializing on certain ESCs requiring update rate faster than 250Hz, by making the actuator update configurable by adjusting the IMU_GYRO_RATEMAX parameter. 
Make Rover update on `vehicle_angular_velocity` instead of `vehicle_attitude`
Increase the rate of `vehicle_attitude`
Tested on the modalai/fc_v1 board by selecting rover and measuring update rate with oscilloscope and `uorb top actuator` to confirm the actuator_output rate increased.
=> Rover publish actuator controls with rate of gyro

src/drivers/optical_flow/paw3902/paw3902_main.cpp
Can't set paw3902 rotation through parameter.
Change the default if `-Y` is not passed to use the parameter value.
This restores the behavior to what it was previous to #16338 (74083d6).
Leave it.
Before this change, setting the parameter doesn't change orientation (same plots every time)
After change
=> paw3902: Default to using SENS_FLOW_ROT rotation

src/modules/vtol_att_control/vtol_type.cpp, src/modules/vtol_att_control/vtol_type.h
The accel to pitch integrator was not reset after a back-transition, causing issues when a flight included multiple backtransitions.
Reset it when in MC or FW flight modes.
SITL tested.
=> vtol_type: reset accel to pitch integrator

src/modules/land_detector/AirshipLandDetector.h, src/modules/land_detector/FixedwingLandDetector.h, src/modules/land_detector/LandDetector.cpp, src/modules/land_detector/LandDetector.h, src/modules/land_detector/MulticopterLandDetector.cpp, src/modules/land_detector/MulticopterLandDetector.h, src/modules/land_detector/RoverLandDetector.h
False ground-contact detection can happen with multi rotors during a maneuver where the vehicle decelerates horizontally while the user is demanding a sink rate. In this case the vehicle can "float" for a certain amount of time which can be registered as ground-contact by the land detector.
If the vehicle is equipped with a distance sensor we can make use of that data to increase the hysteresis used for the land detection states.
If the system knows that it can measure distance to the ground and the distance is greater than 1m, then the hysteresis values will be increased by a factor of 3 and thus should drastically reduce the chances of false ground contact detection.
Notice that the distance measurement itself is only used to determine the value of the hysteresis, however, it will not …
=> land_detector: robustify land detection by using distance to ground info

src/drivers/imu/bosch/bmi088/BMI088_Accelerometer.cpp, src/drivers/imu/bosch/bmi088/bmi088_i2c/BMI088_Accelerometer.cpp
This affected the clipping limit, which was set too low.
Other drivers are correct.
=> fix bmi088: set correct accel scale

src/drivers/pwm_out/PWMOut.cpp
**solved problem:** 
The PWM pulse frequency is 8 times the setting 
https://github.com/PX4/PX4-Autopilot/issues/17417
After initialization, the configuration pulse frequency will enter The static inline void io_timer_set_oneshot_mode(unsigned timer) function of platforms/nuttx/src/px4/stm/stm32_common/io_pins/io_timer.c will make the division factor 8 times smaller than the normal setting. 
**Test after modification:** 
**Test model:**
13014 vertical take-off and landing 
Parameter configuration ：
CBRK_USB_CHK = 197848
CBRK_SUPPLY_CHK = 894281
RC_MAP_AUX1 = Channel 5
RC_MAP_AUX2 = Channel 6
RC_MAP_AUX3 = Channel 7
RC_MAP_AUX4 = Channel 8
CBRK_AIRSPD_CHK=162128
RC_MAP_TRANS_SW=Channel 8
**Before unlock :**
**After unlocking :**
**Use the pwm info command to see that the result is …
=> Fix the repeated configuration of PWM rate after initialization

ROMFS/px4fmu_common/init.d-posix/CMakeLists.txt, ROMFS/px4fmu_common/init.d-posix/px4-rc.mavlink, ROMFS/px4fmu_common/init.d-posix/px4-rc.params, ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator, ROMFS/px4fmu_common/init.d-posix/rcS
To change parameters, variables and mavlink streams for SITL run user must edit rcS startup script. 
It is especially inconvenient when we run multiple instances of px4 in simulation environment.
This patch split rcS script into parts: rc.vars, rc.params, rc.mavlink that loaded on startup.
In each file we can use instance index variable for multiple px4 logic.
If user wants substitute it's own files, he can change PATH environment variable (shell's sourcing mechanism searches files in PATH)
Unknown …
=> init.d-posix/rcS: split and source data from files in PATH

src/drivers/protocol_splitter/protocol_splitter.cpp
Describe problem solved by this pull request
Protocol_splitter uses currently 8-bytes header, that is relatively long for short messages. Using shorted header would give better performance.
Describe your solution
Protocol_splitter header is reduced from 8-bytes to 4-bytes. This is done by reducing the identifier magic bytes from 3 to 1, including the message type into one bit (either mavlink or rtps) in the MSB of second length byte and finally removing the reserved alignment bytes in the end of header. To compensate reduction of magic bytes and keep detection robust the last byte is used as a checksum over header (excluding the magic byte).
Describe possible alternatives
Considered to increase checksum bits …
=> Protocol_splitter: 4-byte header with checksum

.github/workflows/compile_nuttx.yml, Tools/bloaty_static_ram.bloaty, cmake/bloaty.cmake
Adds make <target> bloaty_ram command that creates a breakdown of statically allocated memory (.data & .bss)
Example
```
[5/6] Linking CXX executable nxp_fmuk66-v3_socketcan.elf
Memory region         Used Size  Region Size  %age Used
vectflash:         464 B         1 KB     45.31%
cfmprotect:          16 B         16 B    100.00%
progflash:     1874040 B    2071536 B     90.47%
datasram:       43800 B       256 KB     16.71%
[5/6] cd /home/hovergames/src/Firmware/build/nxp_fmuk66-v3_socketcan && /usr/local/bin/bloaty -c /home/hovergames/src/Fi...full --domain=vm -s vm -n 200 -w /home/hovergames/src/Firmware/build/nxp_fmuk66-v3_socketcan/nxp_fmuk66-v3_socketcan.elf
VM SIZE    
-------------- 
99.1%  42.2Ki    ram
23.1%  9.74Ki    iob/iob_initialize.c
12.6%  5.32Ki    chip/kinetis_serial.c …
```
=> CMake Bloaty add static ram usage breakout

boards/mro/pixracerpro/src/board_config.h
This fixes DSM decoding on the mRo Pixracer Pro.
We should review this across other new H7 boards.
@berndpfrommer
=> boards: mro pixracerpro set BOARD_SUPPORTS_RC_SERIAL_PORT_OUTPUT instead of RC_SERIAL_SINGLEWIRE

src/modules/flight_mode_manager/CMakeLists.txt, src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.cpp, src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.hpp
Hello,
This PR is a little bit of housekeeping for readability only, no functional changes are created by this PR.  The flight_mode_manager CMakeLists.txt library list is alphabetized, and a few instances in the FlightTask class definition and header file are re-grouped for readability.
Please let me know if you have any questions on this PR.
-Mark
=> Alphabetize flight_mode_manager CMakeLists.txt list, and group/format types in FlightTask.cpp/hpp.

Tools/setup/ubuntu.sh
Updated to reflect current NuttX documentation. https://nuttx.apache.org/docs/latest/quickstart/install.html
One notable difference is that `kconfig-frontends` is available as a package again.
=> Tools/setup: update ubuntu.sh with current NuttX dependencies

msg/telemetry_status.msg, src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_main.h, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h
This contains various cleanup in mavlink and mavlink receiver the most notable being a different handling of how to keep track of sequence numbers for various components.
Extraced out of https://github.com/PX4/PX4-Autopilot/pull/17404.
=> mavlink receiver fixes

src/modules/logger/logged_topics.cpp
CONSTRAINED_MEMORY boards likely aren't running multi-EKF.
=> logger: skip multi-EKF logging if CONSTRAINED_MEMORY

Makefile
This is helpful for submodule dependencies that get into a dirty build state and will otherwise need to be completely reinitialized before the build will succeed again.
=> Makefile: clean use git clean to delete all gitignore files recursively

src/modules/sensors/vehicle_gps_position/gps_blending.cpp
If the GPS data is passed from companion computer, there may be inaccuracies
with timesync. This may cause time deltas to overflow.
Make the time delta calculation using floats directly, wich results in negative
numbers in case there are such inaccuracies.
We are currently using an indoor positioning system, based on HTC Vive trackers, and passing "GPS" coordinates over RTSP from ROS2 (as SensorGps). The latency from the trackers is very low, and timestamps for the samples are close to the current time. …
=> Fix raw_dt and present_dt calculation in gps_blending

src/modules/vtol_att_control/tiltrotor.cpp
To prevent tilt dents like that on initiating a front transition (when there already is some tilt in hover to compensate for wind).
Only allow increasing tilt during the first phase of a transition to FW.
SITL and flight tested.
=> tiltrotor: only allow increasing tilt during first part of transition

src/modules/navigator/mission.cpp, src/modules/navigator/mission.h, src/modules/navigator/mission_block.cpp, src/modules/navigator/mission_block.h
The transition command waypoints, NAV_CMD_DO_VTOL_TRANSITION, are attached to the previous waypoint that contains a location (e.g. normal waypoint). It then triggers a transition as soon as this waypoint is reached, which happens when the vehicle is within L1 distance to it. Is the L1 distance smaller then the needed space for the transition, then the vehicle overshoots. The current logic is that for a transition waypoint, the waypoint has to be reached again in the new VTOL mode (e.g. in hover after a backtransition). Thus, if it overshoots, it turns around to accept it, and only then proceeds to the next waypoint.
I don't really get in which case this would be desired.
This can lead to ugly situations like this: …
=> Navigator: VTOL transition command: make transitions smoother

platforms/nuttx/src/px4/stm/stm32_common/board_reset/board_reset.cpp
The `reboot -b` option has been broken since the can bootloader was integrated. This fixes it.
=> stm32_common:board_reset Fix reboot -b broke by canbootloader

src/systemcmds/reflect/reflect.c
As shown in the CI log here https://github.com/PX4/PX4-Autopilot/pull/17100/checks?check_run_id=2492898789#step:13:12
The reflect systemcmd is pre-allocating 4KB on the HEAP to store the block pointers.
This patch dynamically allocates the the pointer array when running reflect saving some RAM.
=> Reflect dynamically allocate block pointers instead of using heap

Tools/setup/arch.sh
Script failed for me with following error
PX4-Autopilot/Tools/setup/arch.sh: line 159: syntax error near unexpected token `else'
PX4-Autopilot/Tools/setup/arch.sh: line 159: `			else'
Seems like there is nothing to do in case of positive if case.
I have changed if condition logic
Script worked  after changes.
=> arch.sh: Syntax error fix

src/drivers/protocol_splitter/protocol_splitter.cpp
Aligned with agent_protocol_splitter to make byte access easier
for checksum generation
Struct converted to union as done in agent_protocol_splitter side.
-
Tested with Pixhawk4 connected to PC with FTDI-Uart cable from TELEM1 port. RTPS connection verified using micrortps_agent and "ros2 topic echo". Mavlink communicaiton verified using QGC.
-
=> protocol_splitter: Sp2Header defined as union

msg/vehicle_land_detected.msg, src/modules/land_detector/AirshipLandDetector.h, src/modules/land_detector/LandDetector.cpp, src/modules/land_detector/LandDetector.h, src/modules/land_detector/MulticopterLandDetector.cpp, src/modules/land_detector/MulticopterLandDetector.h, src/modules/land_detector/RoverLandDetector.h, src/modules/land_detector/land_detector_params_mc.c
1. Land detector trigger times are hardcoded values:
The tree stages used arbitrary 350, 250 300ms totally 900ms
1. It's hard and error-prone to debug the land detector when you have to calculate each condition manually at every point in time.
1. An efficiently designed multirotor commanded to hold constant altitude but moving fast horizontally can during hard braking maneuvers hit the limit of low thrust because of the additional lift generated by the horizontal movement airflow around the (rather large) propellers. In that case it often has worse altitude tracking and the position controller demands additional downwards velocity to reach the right altitude again. This is with the current land detector implementation intentionally …
=> MulticopterLandDetector: Make land detection time configurable

src/modules/flight_mode_manager/FlightModeManager.cpp, src/modules/flight_mode_manager/FlightModeManager.hpp, src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.cpp, src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.hpp
@RomanBapst was looking into making the VTOL transition smoother and since the task doesn't control velocity but just keeps the vehicle level it needs to not just take over the velocity setpoint from the last task but just the last executed acceleration setpoint including velocity control. That's exactly what the velocity control feedback is for but that data is nto available during task activation for legacy reasons.
FlightTasks was part of the multicopter position controller and the feedback could just be passed in without subscription. But now it doesn't make sense anymore to handle this subscription separately.
It's better to have it inside the base task to have the data available on task activation sucht that …
=> FlightModeManager: move velocity control feedback into FlightTask

.gitmodules
Should fix the auto submodule updater by specifying correct branch see #17497
=> legacy_data_types specify legacy branch

Makefile
This might solve the issue with a partial libuavcan build being interrupted, but not yet verified.
**EDIT:** seems to work, broken incomplete builds are now recoverable with `make clean`.
=> Makefile: keep git clean for submodules to resolve incomplete dependency problems

boards/nxp/ucans32k146/nuttx-config/include/board.h, boards/nxp/ucans32k146/src/bringup.c, boards/nxp/ucans32k146/src/can_boot.c
The UCANS32K146B is a board revision that uses a different CAN phy.
However the behavior of the STB pin on this CAN phy is inverted.
This patch adds a runtime detector to see which revision it's and correctly set the CAN phy STB pin.
=> Add support for UCANS32K146B board revision

src/modules/logger/logged_topics.cpp, src/modules/navigator/follow_target.cpp
This fixes an issue described in https://github.com/PX4/PX4-Autopilot/issues/17473. The message update flag was accidentally deleted.
The update logic of the follow-target flight mode is currently broken and it won't work correctly.
Correctly set `update` flag. As a bonus also parse the velocity fields from the target if it provides these values (Android and iOS do afaik).
Not tested outside of simulation at all.
I'm working on a general rework of the follow-target flight-mode at which point it will also become a flight task. Don't invest too much effort into fixing the existing follow-target now.
=> Fix uORB update logic in Follow-target mode

src/modules/ekf2/EKF2Selector.cpp, src/modules/ekf2/EKF2Selector.hpp
- handle reset count rollover (uint8_t)
- compute full reset delta if primary estimator instance has changed or if we missed a reset
=> ekf2: improve selector reset handling

src/drivers/optical_flow/paw3902/PAW3902.cpp, src/drivers/optical_flow/paw3902/PAW3902.hpp
- respect mode 2 shutter requirements from datasheet (should not operate with Shutter < 0x01F4 in Mode 2)
- sensor reset is handled by mode change
=> drivers/optical_flow/paw3902: properly discard samples after mode change

src/drivers/dshot/DShot.cpp, src/drivers/dshot/DShot.h, src/drivers/dshot/module.yaml
Fixes #17364 
Added 3 DShot parameters to enable 3D DShot.
If DSHOT_3D_ENABLE is selected, the bottom actuator_output range is reversed to comply with DShot specification.
DSHOT_3D_DEAD_H and DSHOT_3D_DEAD_L set the range where output is 0
- Use generic deadband parameters that apply to both DShot and pwm
- Fix actuator output value of 0 not being usable by DShot [see here](https://github.com/benjinne/PX4-Autopilot/blob/4f52c0b6daa93f01b3c02e9457265be107af74be/src/drivers/dshot/DShot.h#L58). 
Tested using a custom rover mixer and both directions worked and deadband/min and max values worked correctly.
=> Add 3D DShot capability

src/modules/vtol_att_control/vtol_type.cpp
In FW, the min PWM of all the motors was set to 900 (PWM_MOTOR_OFF), but it should rather be 1000 (PWM_DEFAULT_MIN). With the min set to PWM_MOTOR_OFF, it also scaled the PWM outputs to 900...2000, what isn't desired in general.
That was leading to the weird factor between motor controls and motor outputs:
Set the min PWM to PWM_DEFAULT_MIN.
Flight tested on several tiltrotor vehicles.
=> vtol_type: in FW, set min PWM to PWM_DEFAULT_MIN instead of PWM_MOTOR_OFF

src/modules/commander/airspeed_calibration.cpp
Current calibration message says blow across the pitot, while actually you should blow in (as the other docs say). This changes the message. This originates from Chris Anderson on Slack - image illustrates the difference.
=> airspeed calibration: instruct to blow into front of pitot

src/modules/ekf2/EKF2Selector.cpp, src/modules/ekf2/EKF2Selector.hpp
Increase `estimator_selector_status` publication (and logging) rate if the relative test ratios are changing towards a potential change of primary estimator instance.
=> ekf2: selector increase status rate before potential instance change

Makefile
- update `clean` to iterate all build directories and use build system clean
- git clean is used to remove submodule generated build artifacts that are left in the source tree
- `distclean` now discards all build directories and any gitignored files that were generated in source directories (but not top level)
@julianoes @bkueng can you give this a try?
Background https://github.com/PX4/PX4-Autopilot/pull/17522#issuecomment-832358757
=> Makefile: clean and distclean updates

boards/px4/fmu-v5x/default.cmake, boards/px4/fmu-v5x/init/rc.board_sensors, boards/px4/fmu-v5x/src/board_config.h, boards/px4/fmu-v5x/src/init.cpp, boards/px4/fmu-v5x/src/manifest.c, boards/px4/fmu-v5x/src/spi.cpp, platforms/common/include/px4_platform_common/board_common.h, platforms/common/include/px4_platform_common/spi.h, platforms/common/spi.cpp, platforms/nuttx/src/px4/stm/stm32_common/include/px4_arch/spi_hw_description.h
This is a Draft because  Orientations are not set yet
=>  px4_fmu-v5x:Add support for Revision 2 FMUM HW using ICM20649 not BMI088

msg/vehicle_status.msg, src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.hpp, src/modules/commander/Arming/PreFlightCheck/checks/preArmCheck.cpp, src/modules/commander/Commander.cpp, src/modules/navigator/navigator_main.cpp
Also avoid navigator spamming "approaching on geofence" when vehicle is not armed.
=> Don't allow arming outside geofence if geofence action is not NONE

ROMFS/px4fmu_common/init.d-posix/airframes/17001_tf-g1, src/lib/parameters/param_translation.cpp, src/modules/airspeed_selector/airspeed_selector_main.cpp, src/modules/airspeed_selector/airspeed_selector_params.c, src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp, src/modules/commander/commander_params.c, src/modules/fw_att_control/FixedwingAttitudeControl.cpp, src/modules/fw_att_control/FixedwingAttitudeControl.hpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp, src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c
User needs two set FW_AIRSPD_TRIM and ASPD_STALL to roughly the same physical value of the system ("what's the minimum speed still safe to fly at").
As we started discussing in https://github.com/PX4/PX4-Autopilot/pull/17051, this PR is one way to improve the configuration experience ~~by removing ASPD_STALL, and instead approximate the stall speed to 60% of FW_AIRSPD_MIN. 
Advantage: only one param to set (FW_AIRSPD_MIN)
Disadvantage: less flexibility and airspeed selector module no longer stand alone (external param required)~~
Update: I've now replaced ASPD_STALL by FW_AIRSPD_STALL.
Advantage: All the important FW tuning variables at the same page
Disadvantage: renaming of a variable.
I've also added some more …
=> replace ASPD_STALL by FW_AIRSPD_STALL

src/drivers/gps/gps.cpp
- Timeout fix
For **Rover with moving base** timeout is prolonged because calculation can take a bit longer if the GPS signal is bad.
https://www.u-blox.com/sites/default/files/ZED-F9P_IntegrationManual_%28UBX-18010802%29.pdf
Page: 21
> The MB rover will wait as long as possible to compute a navigation solution, possibly lowering the navigation rate all the way to 1 Hz while doing so. If not time-matched observations are received in time, the receiver will flag the relative position as invalid.
This can be observed with the `gps status` command in mavlink console:
`INFO  [gps] status: NOT OK, port: /dev/ttyS6, baudrate: 0`
Because of a timeout, GPS will try to reconfigure itself. 
- Heading fix
This is solved as part of the GPS driver …
=> GPS heading and timeout fix for uBlox ZED-F9P

src/modules/logger/log_writer_file.cpp
The allocation got changed to `px4_cache_aligned_alloc`
=> fix logger: use free() instead of 'delete[]' for _buffer

ROMFS/px4fmu_common/init.d/rcS, platforms/nuttx/init/kinetis/rc.board_arch_defaults, platforms/nuttx/init/s32k1xx/rc.board_arch_defaults, platforms/nuttx/init/stm32/rc.board_arch_defaults
Some of the older boards (eg cortex m4) are getting pretty tight on memory outside of the base system (extra mavlink, vmount, etc). Since estimator replay is no longer on by default I think it would be more conservative on these boards, saving memory for actual usage, rather than perfect logging.
In the future we can make `LOGGER_BUF` a parameter if this is a problem.
=> ROMFS: reduce LOGGER_BUF default to 8 kB on older boards

src/modules/mavlink/mavlink_mission.cpp
This is a minor change in a status_text that confused me: the `PX4_DEBUG` just above says "invalid item", so I believe that the status_text should be consistent with it.
=> busy -> invalid item

Makefile, boards/px4/fmu-v6x/default.cmake, src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/streams/ATTITUDE_TARGET.hpp
This is the case in MC acro
And avoid 'stream xy not found' warnings on CONSTRAINED_FLASH targets
e.g.:
```
WARN  [mavlink] stream ADSB_VEHICLE not found
WARN  [mavlink] stream GIMBAL_DEVICE_ATTITUDE_STATUS not found
WARN  [mavlink] stream GIMBAL_MANAGER_STATUS not found
WARN  [mavlink] stream GIMBAL_DEVICE_SET_ATTITUDE not found
WARN  [mavlink] stream GPS2_RAW not found
WARN  [mavlink] stream UTM_GLOBAL_POSITION not found
ERROR [mavlink] configure_streams_to_default() failed
```
=>  mavlink ATTITUDE_TARGET: send also if vehicle_attitude_setpoint is not updated

msg/templates/urtps/RtpsTopics.cpp.em, msg/templates/urtps/RtpsTopics.h.em
While trying the micrortps_agent with ROS2, I found some issues with the synchronization of the timestamp_samples in topics. While timestamps are well synchronized, the timestamps_samples are not. It concerns every topic with timestamp samples.
2 issues have been solved
1- The detection of the existence of the timestamp_sample member in the topic fails (in RtpsTopics.h generated by RtpsTopic.h.em). Probably because the timestamp_sample member is overloaded in the definition of the topic, the detection using SFINAE does not work in the …
=> fix timesync for timestamp sample (including SFINAE detection)

src/drivers/optical_flow/paw3902/CMakeLists.txt, src/drivers/optical_flow/paw3902/PAW3902.cpp, src/drivers/optical_flow/paw3902/PAW3902.hpp, src/drivers/optical_flow/paw3902/PixArt_PAW3902JF_Registers.hpp
I believe this now correctly reflects the intent of the datasheet (valid for > 10 consecutive frames).
- improve mode change requirements comments
- reduce verified read/write retries (these are mostly wasting time)
=> drivers/optical_flow/paw3902: require >= 10 valid consecutive readings before deciding mode changes

platforms/nuttx/src/canbootloader/uavcan/main.c
Issue with UCANS32K146 and the uavcan bootloader where in some circumstances we could get a hardfault from IRQ 15 the systick when booting from the bootloader
```B▒EG
irq_unexpected_isr: ERROR irq: 15
up_assert: Assertion failed at file:irq/irq_unexpectedisr.c line: 65 task: Idle Task
```
Turns out while we kill the systick interrupt the interrupt itself still might be pending 
https://github.com/PX4/PX4-Autopilot/blob/3a3cc33d69dd66735c3a4fffdc823c54c5e47e22/platforms/nuttx/src/canbootloader/uavcan/main.c#L938
This PR adds a routine to clear pending systick interrupts in the SCB.
@davids5 could it be that the USB bootloader could have the same issue?
=> canbootloader clear pending systick interrupts

src/modules/sensors/vehicle_angular_velocity/imu_gyro_parameters.c
Fixes https://github.com/PX4/PX4-Autopilot/issues/17006. Alternative to https://github.com/PX4/PX4-Autopilot/pull/17567.
https://logs.px4.io/plot_app?log=907f56e5-9bd6-4878-950b-ad70865c6324
Closes https://github.com/PX4/PX4-Autopilot/pull/17567
=> IMU_GYRO_CUTOFF and IMU_DGYRO_CUTOFF increase default slightly

boards/cuav/nora/init/rc.board_sensors, boards/cuav/nora/src/spi.cpp, boards/cuav/x7pro/init/rc.board_sensors, boards/cuav/x7pro/src/spi.cpp
Because of the chip, ICM20649 on the new version X7\Nora SPI6 bus will be replaced by ICM20689
=> ICM20649 on SPI6 bus will be replaced by ICM20689

src/modules/mavlink/mavlink_receiver.cpp
This adds support to handle INT32_MAX for COMMAND_INT.x/y by converting it to NAN internally.
It also adds paranoid checks to prevent:
- NAN being used sent by a COMMAND_INT by mistake.
- INT32_MAX being used sent by a COMMAND_LONG by mistake.
=> mavlink: improve command param5/6, x/y handling

Tools/px_uploader.py, Tools/setup/requirements.txt
This check is failing on Ubuntu. On either Mac or Ubuntu the standard install scripts (`./Tools/setup/ubuntu.sh` or `./Tools/setup/macos.sh`) will install these dependencies, so let's try and keep the checks simple rather than introduce more problems.
``` Console
<module 'serial' from '/home/dagar/.local/lib/python3.8/site-packages/serial/__init__.py'>
Error: pyserial not installed!
You may need to install it using:
pip3 install --user pyserial
```
``` Console
...
Requirement already satisfied: pyserial>=3.0 in /home/dagar/.local/lib/python3.8/site-packages (from -r /home/dagar/git/PX4-Autopilot/Tools/setup/requirements.txt (line 18)) (3.5)
```
=> px_uploader.py remove special pyserial checks that fail on some platforms

src/drivers/imu/invensense/mpu9250/MPU9250.cpp, src/drivers/imu/invensense/mpu9250/MPU9250.hpp
When the mpu9250 mag is active it disrupts IMU sampling. This change modifies the simple mpu9250 FIFO integrity checks (comparing duplicate accel samples) to tolerate these samples that don't match if the mag is active. Alternatively we could "fix" this by skipping the check entirely, but I'd rather keep it to catch instances where the data is corrupt due to setting the SPI clock too high, etc.
- fixes https://github.com/PX4/PX4-Autopilot/issues/17615
=> mpu9250: tolerate missing/mismatching FIFO samples if I2C slave mag active

src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp
This error is primarily useful when significant gaps in magnetometer are present, otherwise the occasional gaps at startup, etc are distracting in regular usage.
=> ekf2: replace mag missed error message with perf count

src/modules/sensors/vehicle_acceleration/VehicleAcceleration.cpp, src/modules/sensors/vehicle_acceleration/VehicleAcceleration.hpp
- don't run until successfully getting the sensor's sample rate from vehicle_imu_status
This fixes a minor edge case when you only have a single accelerometer and haven't made any parameter changes, the sensor sample rate (used for filtering) might not have been updated from default.
=> sensors/vehicle_acceleration: require sample rate before running

msg/tools/generate_microRTPS_bridge.py
This as simple as it can be read: we want continuous support to the cutting edge ROS2 distros available.
The quick win here is make sure that at least we can generate the required typesupport and typename for uORB RTPS counterparts. This is achieved easily on the generator scripts.
Not an alternative, but following the above, other functionalities will be made available, including localhost only comms and shared memory transport. Will follow a PR with that.
All tested in SITL.
Support to the above was already brought in https://github.com/PX4/px4_ros_com/pull/84 and https://github.com/PX4/px4_msgs/pull/5. This PR syncs the changes …
=> ROS2/microRTPS: Add support for ROS2 Galactic and ROS2 Rolling

src/lib/tecs/TECS.cpp, src/lib/tecs/TECS.hpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
TECS still need a filled airspeed state in airspeed less mode. That was till now calculated as the average of min and max airspeed. If that is not the same as the setpoint (FW_AIRSPD_TRIM), it will result in an increased energy demand (and that in turn in an increased throttle).
Let TECS know the value of FW_AIRSPD_TRIM, and use that as airspeed state in airspeed less case, such that no airspeed error exists. 
Flight tested on several VTOLs by disabling the airspeed sensor in air.
=> TECS: in airspeed-less mode, set airspeed estimate to cruise airspeed

.gitmodules
I just realized that the previous fix was incomplete. It did fix the cloning for me, but the urls should actually end with .git.
=> fix legacy data types again

platforms/nuttx/NuttX/CMakeLists.txt, platforms/nuttx/cmake/Platform/Generic-riscv64-unknown-elf-gcc-rv64gc.cmake, platforms/nuttx/cmake/Toolchain-riscv64-unknown-elf.cmake
This brings in support for compiling RISC-V based targets. We are building a flight controller / flight computer based on Microchip PolarFire MPFS250T chip.
Please comment if this kind of stuff is wanted in before there is not any targets using it? Or would it make sense to discuss about this kind of additions later on, at the same time if/when new full chip support for some RISC-V would be brought in?
I was thinking that this might be useful for others as well, if someone else is working on RISC-V targets for PX4.
If this is not wanted in at this time, just ignore and close this PR :)
=> Add risc v compiler

boards/holybro/durandal-v1/bootloader.cmake, boards/modalai/fc-v2/bootloader.cmake, boards/px4/fmu-v6u/bootloader.cmake, boards/px4/fmu-v6x/bootloader.cmake
Clean this up before it's copied around even more.
=> boards: bootloader.cmake trivial whitespace cleanup

src/modules/sensors/vehicle_air_data/VehicleAirData.cpp, src/modules/sensors/vehicle_air_data/VehicleAirData.hpp
For the air density calculation we currently assume constant 20°C temperature. As the temperature has a significant effect on air density, it would be nice to use the measurement from an airspeed sensor (differential pressure) if available.
- subscribe to differential_pressure in Sensors/Vehicle_air_data
- use differential_pressure.temperature if that is within valid range (defined as -50..50°C)
Do we also want to handle subscriptions to multiple differential_pressure instances with fallback logic? Sounds a bit like an overkill to me atm, but it also shows that there could be a cleaner way how we handle the publication of estimated values that are not coming from the EKF atm (like mainly airspeed, but also air …
=> Sensors: use temperature data from differential pressure sensor to calculate air density

boards/px4/fmu-v2/default.cmake
- this doesn't impact regular gyro calibration
Master slipped over the limit slightly after back to back merges.
=> boards: px4_fmu-v2_default disable gyro_calibration module to save flash

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp
Testing master on px4_fmu-v4.
``` Console
WARN  [load_mon] wq:UART4 low on stack! (296 bytes left)
```
=> px4_work_queue: increase UART stack

msg/tecs_status.msg, src/lib/tecs/TECS.cpp, src/lib/tecs/TECS.hpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
This PR adds logging of the following quantities:
1) Pitch setpoint: This is useful for VTOL where the final pitch setpoint can be altered by the VTOL attitude controller.
Currently, there is no way to know the original intend of TECS.
2) True airspeed innovation: This gives information about the consistency between accel data and airspeed data. I actually believe that in the future we can use it to detect airspeed failures fairly quickly.
My goal is to remove the second order complementary filter from TECS and put it into the airspeed validator.
3) True airspeed rate derivative. We were using this signal  but the filter we applied had such a  low bandwidth that not much of the signal was still present. This will help to tune the corresponding time constant.
=> Log more TECS data

boards/av/x-v1/src/init.c, boards/cuav/nora/src/init.c, boards/cuav/x7pro/src/init.c, boards/cubepilot/cubeorange/src/init.c, boards/cubepilot/cubeyellow/src/init.c, boards/holybro/durandal-v1/src/init.c, boards/holybro/kakutef7/src/init.c, boards/holybro/pix32v5/src/init.c, boards/modalai/fc-v1/src/init.c, boards/modalai/fc-v2/src/init.c, boards/mro/ctrl-zero-f7-oem/src/init.c, boards/mro/ctrl-zero-f7/src/init.c, boards/mro/ctrl-zero-h7-oem/src/init.c, boards/mro/ctrl-zero-h7/src/init.c, boards/mro/pixracerpro/src/init.c, boards/nxp/fmuk66-e/src/init.c, boards/nxp/fmuk66-v3/src/init.c, boards/px4/fmu-v5/src/init.c, boards/px4/fmu-v5x/src/init.cpp, boards/px4/fmu-v6u/src/init.c, boards/px4/fmu-v6x/src/init.c, boards/spracing/h7extreme/src/init.c, platforms/nuttx/src/px4/nxp/k66/include/px4_arch/micro_hal.h, platforms/nuttx/src/px4/nxp/rt106x/include/px4_arch/micro_hal.h, platforms/nuttx/src/px4/stm/stm32_common/include/px4_arch/micro_hal.h
It has been reported that the some ESC have spun with  the change to PX4_MAKE_GPIO_INPUT_PULL_DOWN.
If the input to the ESC is puled up in the SoC and the FMU pulls it down, the voltage can sit at 1.56V. 
Unfortunately we can be wrong 50% of the time if an ESC uses the pull down against the FMU pull up. 
Prior to the series of commits introducing PX4_MAKE_GPIO_INPUT_PULL_DOWN there were no reports. So this seems like a better choice.
=> Revert:Pull downs - bad levels cause motor spins

src/modules/navigator/mission_block.cpp
This fixes a regression introduced in https://github.com/PX4/PX4-Autopilot/pull/16646 which meant that the acceptance radius was no longer used at all for multicopter, and instead only the NAV_ACC_RAD param was used.
With this change we use the acceptance radius of the mission item again if it is actually set (and not NAN) which we did not do before, and we only do that for multicopter.
Found while working on https://github.com/mavlink/MAVSDK/pull/1443.
=> navigator: fix acceptance radius for multicopter

boards/cuav/nora/default.cmake, boards/cuav/nora/init/rc.board_sensors, boards/cuav/nora/src/spi.cpp, boards/cuav/x7pro/default.cmake, boards/cuav/x7pro/init/rc.board_sensors, boards/cuav/x7pro/src/spi.cpp
Because of the lack of chips, bmi088 on the new version X7\Nora SPI4 bus will be replaced by ICM42688P.This have done a simple test.
=> CUAV X7pro and Nora: use icm42688p instead of bmi088

src/drivers/pwm_out/PWMOut.cpp, src/drivers/px4io/px4io.cpp
- fixes https://github.com/PX4/PX4-Autopilot/issues/17485 (needs verification)
=> px4io/pwm_out: only update PWM MAX/MIN/DIS/FAIL/REV once to prevent VTOL conflict

boards/ark/can-flow/src/init.c, boards/ark/can-gps/src/init.c
This PR adds a call to watchdog_init on ARK boards to ensure the watchdog timer will be paused when debugging with SWD.
=> Add watchdog_init to ARK boards to ensure watchdog pauses during debugging

src/systemcmds/gpio/gpio.cpp
This adds backticks around the generated docs for gpio command. Without this the markup is valid tags, which don't render properly - see : http://docs.px4.io/master/en/modules/modules_command.html#description-3
=> gpio.cpp: Add backticks around gpio command docs

src/modules/mavlink/mavlink_main.cpp
This makes sure that the vehicle_command topic is properly initialized from the beginning.
orb_exists returns -1 or 0 and not a bool as one would expect.
=> mavlink: properly initialize vehicle_command queue

src/lib/tecs/TECS.cpp, src/lib/tecs/TECS.hpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp, src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c
Improve computation of height rate setpoint in TECS. Introduced parameters for target climb-and sinkrates.
Also avoids numerical computation of height rate feed-forward which was prone to jitter in dt.
Got rid of unnecessary filters in height rate computation.
Can now specify target height and sinkrate for TECS instead of using max climb and sink rates.
Tested in SITL using standard vtol model.
Plots:
=> TECS: Improve height rate setpoint calculation

src/modules/mavlink/streams/BATTERY_STATUS.hpp
The current firmware only reports 10 batteries to QGC, MAVLink2 battery status information supports 14 batteries, and now the remaining 4 batteries are also reported to QGC.
=> mavlink: 14S battery support

ROMFS/px4fmu_common/init.d/airframes/13014_vtol_babyshark, src/modules/mc_pos_control/mc_pos_control_params.c
Related to https://github.com/PX4/PX4-user_guide/pull/1305/ and https://github.com/PX4/PX4-user_guide/pull/1310 we should correct the docs to reflect that MPC_POS_MODE 1 was deprecated a long time now and removed in https://github.com/PX4/PX4-Autopilot/pull/16052
Corrected the parameter descriptions.
=> mc_pos_control_params: correct MPC_POS_MODE docs since 1 is depracated

src/modules/mavlink/streams/HEARTBEAT.hpp
MAVLink specs define a way to report when then vehicle was terminated (thanks @julianoes):
https://mavlink.io/en/messages/common.html#MAV_STATE_FLIGHT_TERMINATION
but the issue is that the usually used ways of termination e.g. kill switch, geofence, failsafe reaction do not report this state.
That's what I originally wanted to do when I ran into #17707
This pull request makes sure the termination state is set with the common ways a vehicle is terminated like:
`manual_lockdown`, `lockdown`, `foce_failsafe`.
I'm suggesting to generally unify the termination state such that further confusion can be avoided. There should be one terminated/killed state and everything which is not …
=> mavlink: make sure heartbeat reports flight termination

src/lib/sensor_calibration/Accelerometer.cpp, src/lib/sensor_calibration/Gyroscope.cpp, src/lib/sensor_calibration/Magnetometer.cpp, src/modules/commander/accelerometer_calibration.cpp, src/modules/commander/gyro_calibration.cpp, src/modules/commander/mag_calibration.cpp, src/modules/sensors/sensors.cpp
This addresses an annoying problem on systems where the external peripherals (eg compass) are not powered when only USB is connected. In this case any parameter changes will result in the loss the calibration for these sensors.
=> sensors: preserve all valid calibration parameters even if sensor currently missing

src/modules/mavlink/streams/HEARTBEAT.hpp
I forgot to include the `actuator_armed` header in https://github.com/PX4/PX4-Autopilot/pull/17709. The necessary definitions are available through some include but I'd rather correct it to be clean.
=> mavlink: add actuator_armed header to heartbeat

boards/px4/fmu-v5/default.cmake, src/drivers/uavcan/CMakeLists.txt
Problem:
In CUAV v5+：the uavcan timer5 takes up the led_pwm_timers on the board, that makes board's LED  PWM does't work.
This PR makes board's led pwm works correct.
=> change fmu-v5's uavcan timer5 to timer6

boards/cuav/x7pro/init/rc.board_sensors
https://github.com/PX4/PX4-Autopilot/pull/17692 
Fixed syntax errors in PR above.
The serial port outputs information:
=> Fixed syntax error

platforms/common/i2c_spi_buses.cpp
This is sometimes helpful to see in logs, especially cases where board init script logic grows in complexity.
I'd still very much like to find a way for the rotation to become a static property in the board support.
``` Console
icm20602 #0 on SPI bus 1 rotation 2
icm20689 #0 on SPI bus 1 rotation 2
bmi055 #0 on SPI bus 1 rotation 2
bmi055 #1 on SPI bus 1 rotation 2
ms5611 #0 on SPI bus 4
ist8310 #0 on I2C bus 3 address 0xE rotation 10
ist8310 #1 on I2C bus 1 (external) address 0xE rotation 10
```
=> I2CSPIDriverBase: print rotation and i2c address if set

src/modules/mc_pos_control/MulticopterPositionControl.cpp
This logic was introduced to avoid large altitude drifts in velocity mode (altitude not controlled) due to potential velocity estimate bias in case of IMU problems (see PR #8445). After some refactoring, the logic started to be used in altitude-controlled modes as well, which is not needed.
Original implementation in https://github.com/PX4/PX4-Autopilot/pull/8445/commits/02314f542ac899d1c6183de715134e946d6005b7 . That part of the code was only runing `if (!_run_alt_control)`.
=> MC pos control: use vz<->z_deriv blending in pure vel mode only

src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp
- these checks for messages being lost are largely for monitoring excessive publication rates or scheduling issues, moving to perf counters to prevent unnecessarily distracting/worrying users
- only allocate these perf counters if data source is present
=> ekf2: update message lost errors to perf counters

src/drivers/uavcan_v1/Publishers/Publisher.hpp, src/drivers/uavcan_v1/Subscribers/BaseSubscriber.hpp, src/drivers/uavcan_v1/Subscribers/DynamicPortSubscriber.hpp, src/drivers/uavcan_v1/Uavcan.cpp
The `hrt_abstime` value used to control the 1s pub rate was the value of the `timestamp_usec` of the `CanardTransfer`, which has a timeout of 100ms added to it.
Since `hrt_abstime` is an unsigned datatype, if the `hrt_elapsed_time()` check was called <100ms apart, the negative value between `hrt_absolute_time()` and the future time would result in a large `hrt_elapsed_time`, and the bus would be spammed with Heartbeat messages (or error messages from canardTxPush) at some rate >10Hz.
I also cleaned up the handling of "unset" / "invalid" port ID parameters; the recent changes from using 0 to using 65535 to using -1 for the "disabled" value of the PX4 params was causing unsubscribe()/subscribe() to be called on every parameter update.
=> uavcan_v1: Fix Heartbeat scheduling

Tools/px4airframes/markdownout.py
The airframes page in docs had an autogenerated "edit on github" link to the file used to generate it. This fixes link to moved repo, and makes it a source code not edit link. That makes sense because most people should be editing this code outside of github editor.
=> airframes markdownout.py - fix link to not open file for editing

src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_main.h
We weren't cleaning up `mavlink_module_instances` when exiting, so future `mavlink stop-all` attempts would fail.
@baumanta
=> mavlink: properly cleanup instance on exit

msg/vehicle_control_mode.msg, src/modules/commander/Commander.cpp, src/modules/mc_pos_control/MulticopterPositionControl.cpp
Now that FlightTask is in the flight mode manager module and that the MC position controller runs on local_position updates, the multicopter position controller also runs when a VTOL plane is in fixedwing mode (using 0 velocity as a reference because trajectory_setpoint is all NAN).
Adding a clear control mode flag to tell when the multicopter position controller should run or not.
Updating based on the `trajectory_setpoint` update was an option but it would slow down the loop if the estimate comes faster than the setpoint. Also, since "flight mode manager" will soon be used for all kind of vehicles (fixedwings, rovers, ...) the `trajectory_setpoint` might also be filled with …
=> en-/disable mc position controller using explicit control mode flag

src/modules/mavlink/mavlink_main.cpp
This fixes a tricky bug that we discovered in MAVSDK:
https://github.com/mavlink/MAVSDK/pull/1464
It turns out the target_system and target_component fields can potentially be:
1. at the end of a message payload,
2. and zero,
and therefore they get trimmed. When you then try to read it you potentially read some garbage from the CRC fields.
Found with @JonasVautherin.
=> mavlink: don't read garbage target sysid/compid

src/drivers/uavcan_v1/CanardSocketCAN.cpp, src/drivers/uavcan_v1/Uavcan.cpp
The UAVCANv1 transmit() function was checking deadline the wrong way around and thus only sending timed out frames.
Furthermore fixes the timing conversion in the SocketCAN driver.
=> Correct transmission deadline check & fix SocketCAN tx deadline

cmake/metadata.cmake, src/modules/mavlink/mavlink_main.cpp
This will add the MAV_x_BROADCAST params to the docs.
From https://github.com/PX4/PX4-user_guide/pull/1327
@hamishwillee
=> cmake: enable --ethernet to generate common param metadata

ROMFS/px4fmu_common/init.d/airframes/50003_aion_robotics_r1_rover
The docs URL is broken. Docs have moved to https://docs.aionrobotics.com/ but that no longer includes vehicle links, so not useful. 
This is product link from main website.
@ItsTimmy Long time no see. You touched this so FYI :-)
=> aion robotic frame - fix broken link to R1 UGV docs

Makefile
In cases where some GAct CI workflows were removed, the `make_list` Makefile function will through an error when trying to `cat` a file that doesn't exist (ex. `comple_linux.yml`)
Check if the file exists first.
We could silence/suppress it, but that's not that useful.
Tested locally with some workflow files removed.
N.A.
=> make_list: check if file exists before the other operations

src/modules/commander/Commander.cpp, src/modules/commander/ManualControl.cpp, src/modules/commander/ManualControl.hpp
When user override using the RC sticks is allowed, I would expect this feature to also work in the case where GPS is lost and the vehicle goes into a blind land/descent.
Without this commit, the vehicle would switch to Land mode and a pilot could not take over control unless they switch to Altitude control in a ground station.
With this commit, user override works as I would expect it and it will switch to Altitude control allowing a pilot to recover in this situation.
=> commander: enable user override when GPS is lost

src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp
When using simulated or fake GPS, based on some other positioning
system, the GPS coordinate input can be very accurate due to quantization
or even for true accuracy. In this case this check bites and perfectly valid position
doesn't get published.
For historical reasons, there is a check in EKF2 to only publish global
position if it has moved for 1mm.
This is no longer necessary, and also this if doesn't save any cpu cycles
in real conditions where GPS errors are always much bigger that this.
Just removed this if.
- The value to be compared against could be a parameter which can be set acc. to the global positioning system used.
=> EKF2: Always publish global position

platforms/common/uORB/Subscription.cpp
- this is necessary if uORB::Subscription is used with static storage duration
=> uORB: Subscription check if uORB::Manager instance is valid

src/drivers/protocol_splitter/protocol_splitter.cpp, src/modules/mavlink/mavlink_main.cpp
On NuttX with flow control, if no one was reading from the uart, the
close() call would block indefinitely waiting for data to be sent.
=> mavlink: tcflush() uart before closing it

src/drivers/uavcan_v1/CanardSocketCAN.hpp, src/drivers/uavcan_v1/ParamManager.hpp, src/drivers/uavcan_v1/Subscribers/BaseSubscriber.hpp, src/drivers/uavcan_v1/Subscribers/DS-015/Battery.hpp, src/drivers/uavcan_v1/Subscribers/DynamicPortSubscriber.hpp, src/drivers/uavcan_v1/SubscriptionManager.cpp, src/drivers/uavcan_v1/SubscriptionManager.hpp, src/drivers/uavcan_v1/Uavcan.cpp
UAVCANv1
Fixes handling unset caused by #17733 and correct deinitialization by freeing correct objects.
=> UAVCANv1 port unset fixes and deinitialization

src/modules/sensors/sensors.cpp
- IMU init requires valid published data (device ids, etc)
- orb_group_count will include advertised instances before data is published, so this can't be used to throttle IMU init attempts
=> sensors: fix IMU init race condition

src/modules/navigator/navigator.h, src/modules/navigator/navigator_main.cpp
Currently, when pausing a vehicle during a mission/RTL/Orbit navigator will take the current position of the vehicle as loiter point. This makes the vehicle overshoot the loiter position and then bounce back to the desired setpoint as the braking distance is not taken into account.
This PR takes into account the vehicle braking distance to predict and set as loiter point the position where the vehicle will actually be able to stop.
If we had motion primitives in place we could have used those to predict the braking trajectory, but still this implementation is an enhancement compared to the current state.
Tested in SITL
Add any other …
=> Predict and use braking distance when Pausing auto modes (for multicopters)

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
When using FW_POSCTL_INV_ST, the airspeed cannot be lowered below the trim airspeed.
PR #16847 accidentally over-constrains `_manual_control_setpoint.x` to 0:1. This causes `_manual_control_setpoint_airspeed` to be constrained to 0.5:1, instead of 0:1. The constrain limits have been changed to allow -1:1 input.
N/A
Problem found and fix tested in SITL
=> FW pos control: fix airspeed input constraining

.github/workflows/checks.yml, Makefile, ROMFS/px4fmu_common/init.d-posix/airframes/1016_iris_rtps, ROMFS/px4fmu_common/init.d-posix/airframes/1016_iris_rtps.post, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt, ROMFS/px4fmu_common/init.d-posix/rcS, Tools/build_micrortps_agent.sh, Tools/gazebo_sitl_multiple_run.sh, msg/templates/uorb_microcdr/microRTPS_client.cpp.em, msg/templates/uorb_microcdr/uORBTopics.cpp.em, msg/templates/uorb_microcdr/uORBTopics.hpp.em, msg/templates/urtps/Publisher.cpp.em, msg/templates/urtps/Publisher.h.em, msg/templates/urtps/RtpsTopics.cpp.em, msg/templates/urtps/RtpsTopics.h.em, msg/templates/urtps/Subscriber.cpp.em, msg/templates/urtps/Subscriber.h.em, msg/templates/urtps/microRTPS_agent.cpp.em, msg/templates/urtps/microRTPS_agent_CMakeLists.txt.em, msg/templates/urtps/microRTPS_timesync.cpp.em, msg/templates/urtps/microRTPS_timesync.h.em, msg/templates/urtps/microRTPS_transport.cpp, msg/templates/urtps/microRTPS_transport.h, msg/tools/uorb_rtps_message_ids.yaml, platforms/posix/cmake/sitl_target.cmake, src/modules/micrortps_bridge/micrortps_client/CMakeLists.txt, src/modules/micrortps_bridge/micrortps_client/microRTPS_client.h, src/modules/micrortps_bridge/micrortps_client/microRTPS_client_main.cpp
Brings a major list of improvements. Listed bellow.
Major changes/features:
* **Communications and data exchange in the localhost network only** are now possible with ROS2 Foxy when `ROS_LOCALHOST_ONLY` env variable is set to 1. This will also by default enable the **Shared Memory Transport** feature, which is also the default in ROS2. Known limitation: This will not work with ROS2 Galactic though when the middleware is set to CycloneDDS, so this was limited to when the `rmw` implementation is set to FastRTPS, or unset but defaulted to FastRTPS (which is the case of Foxy);
* The microRTPS client (FMU side) now has **statistics** of the link TX/RX when using `micrortps_client status` and provides also a max …
=> microRTPS bridge improvements

src/modules/ekf2/ekf2_params.c
By default people currently fly without ground effect compensation which spoils barometer-based altitude estimates close to the ground which is a problem especially on landing because the drone amplifies negative effects by decelerating vertically and giving more thrust towards the ground and the altitude estimate is crucial for a linear smooth landing approach and detection.
I suggest enabling the compensation by default. We found in our testing that a deadzone for barometer innovations `EKF2_GND_EFF_DZ` of 4m is a conservative value that helps in most cases where vehicles suffer from landing issues. `EKF2_GND_MAX_HGT` is already set such that the compensation has an effect when less than 0.5m above ground which …
=> ekf2_params: enable baro ground effect compensation by default

src/drivers/optical_flow/thoneflow/thoneflow.cpp
The Thoneflow driver links to a non-existent "thoneflow doc" (possibly deleted). This fixes it up to point to the correct part of the docs: https://docs.px4.io/master/en/sensor/pmw3901.html#thone-thoneflow-3901u
=> Thoneflow - fix up links to docs

src/modules/mc_hover_thrust_estimator/MulticopterHoverThrustEstimator.cpp
On some platforms (such as VTOL planes), the test ratio sometimes jumps above 1 in case of wind gusts or thrust spikes. This isn't harmful to the Hover Thrust Estimator and the current estimate it still correct.
The condition to get valid requires a low variance and test ratio. but
to stay valid, only the variance is required.
SITL test (takeoff, change of mass, landing)
https://logs.px4.io/plot_app?log=12fa674c-3d1c-480c-97b9-2d5c23ed0e14
=> HTE: relax validity condition when already valid

src/drivers/camera_trigger/camera_trigger.cpp
The camera trigger continues to trigger if the camera is enabled but paused
By using two if-statements instead of an if-else-if, the enabled state no longer prevents the camera trigger to be paused. I also refactored the names of two variables to make them more descriptive of what they are.
It was tested in sitl and gave correct results.
=> Camera keeps triggering while enabled but paused

src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/commander/commander_params.c, src/modules/commander/state_machine_helper.cpp, src/modules/commander/state_machine_helper.h
Resolves https://github.com/PX4/PX4-Autopilot/pull/16864
Some Pilots in BVLOS (Beyond Visual Line Of Sight) scenarios want to be able to **fly foremost missions but presumably also loiter/offboard even when they lose the RC link that is present at boot**. To currently do that the only way is disabling the RC (Remote Control) loss reaction https://docs.px4.io/master/en/advanced_config/parameter_reference.html#NAV_RCL_ACT which is generally not safe to do if you ever fly relying on RC stick input because then the vehicle will ignore the link loss and just keep on using the last known value e.g. in stabilized mode.
I also realized that there are **no reactions in takeoff mode for link loss**. This could potentially result in a flyaway with an …
=> Better RC loss failsafe configuration options for BVLOS

src/modules/flight_mode_manager/tasks/ManualPosition/FlightTaskManualPosition.cpp, src/modules/flight_mode_manager/tasks/ManualPosition/FlightTaskManualPosition.hpp, src/modules/mc_pos_control/MulticopterPositionControl.cpp, src/modules/mc_pos_control/MulticopterPositionControl.hpp, src/modules/mc_pos_control/mc_pos_control_params.c
Based on the numerous complaints the feature was disabled by default (only velocities above 10m/s were limited) and since then no one intentionally used it anymore. But there were some minor investigations of drones not reaching their maximum speed which always showed 10m/s.
Introduction: https://github.com/PX4/PX4-Autopilot/pull/13561
Disabling by default: https://github.com/PX4/PX4-Autopilot/pull/15029
I suggest removing it again.
Not specifically tested.
=> Remove horizontal slow down close to ground

msg/tools/uorb_rtps_classifier.py, msg/tools/uorb_rtps_message_ids.yaml, src/drivers/protocol_splitter/protocol_splitter.cpp
- Preventing and actively adding a bit more room to base messages RTPS IDs
- Follow the update and fix to the agent_protocol_splitter in https://github.com/Auterion/agent_protocol_splitter/pull/14.
- Increase the base ID space to 179, and update the alias messages IDs accordingly;
- On the protocol_splitter, now we include the magic number on XOR for checksum.
N.A.
Tested with SITL and the Auterion Skynode.
=> microRTPS: increase base message ID space and update protocol_splitter header

boards/ark/can-flow/debug.cmake, boards/ark/can-flow/default.cmake, boards/ark/can-flow/init/rc.board_sensors, boards/ark/can-flow/src/spi.cpp
This PR adds support for the ARK CAN Flow Rev 2 that swaps out the BMI088 for the ICM-42688-P due to lack of availability of the BMI088.
Add the ICM-42688-P in the build. Check if the ICM-42688-P driver doesn't start, then start the BMI088 driver.
=> ARK CAN Flow Add ICM-42688-P

src/modules/sensors/vehicle_imu/Integrator.hpp, src/modules/sensors/vehicle_imu/VehicleIMU.cpp
- IMU integrator set max based on final return size (uint16)
- improve integration consuming gyro as needed then integrate all available accel until caught up
- increase required number of samples for sensor rate measurement (online Welford mean)
@NicolasM0 minor improvements to the IMU integration that help with slightly less regular sources like the BMI055.
=> sensors/vehicle_imu: minor IMU integration improvements

src/modules/ekf2/EKF2Selector.cpp
- requires https://github.com/PX4/PX4-ECL/pull/1020
=> ekf2: selector handle NAN test ratios as uninitilaized

src/modules/sensors/vehicle_imu/VehicleIMU.cpp
- minor improvement that helps to determine the sensor publication rate as soon as possible
=> sensors/vehicle_imu: continue integrating gyro if there's a gap in data

ROMFS/px4fmu_common/init.d/rc.sensors, src/drivers/imu/analog_devices/adis16448/parameters.c
The orientation of external IMUs such as the ADIS16448 IMU needs to be configurable through parameters, since the imu can be mounted independent to the board orientation.
This PR adds a parameter to specify the board orientation and passes the orientation when starting the driver.
Currently it is only handled for one orientation, just to get it working, since I don't think having a if else definition for all the parameters make sense.
The orientation parameter can be read directly from the driver. However not sure how it should work relative to the command line argument being passed
- Tested with a Pixhawk4 and a ADIS16448AMLZ attached on the external SPI …
=> Specify orientaiton of external imu ADIS16448 through parameters

boards/bitcraze/crazyflie/syslink/syslink_main.cpp, msg/battery_status.msg, src/drivers/batt_smbus/batt_smbus.cpp, src/drivers/smart_battery/batmon/batmon.cpp, src/drivers/uavcan/sensors/battery.cpp, src/drivers/uavcan/sensors/cbat.cpp, src/drivers/uavcan_v1/Subscribers/legacy/LegacyBatteryInfo.hpp, src/lib/battery/battery.cpp, src/lib/battery/battery.h, src/modules/control_allocator/ControlAllocator.hpp, src/modules/fw_att_control/FixedwingAttitudeControl.cpp, src/modules/mc_rate_control/MulticopterRateControl.cpp, src/modules/simulator/battery_simulator/BatterySimulator.cpp
The structure of the battery class annoys me for a long time now. This pr is a first stab at simplifying the structure. The final goal is to be able to reuse everything useful also for smart battery drivers but I'm trying to not change everything at once here.
Refactoring:
- It looks like every battery field is stored in stored in the battery_status message and in a separate member field
- Reset logic is complicated ofr that
- Certain fields are set multiple times
- Publish measured values even if the battery is not connected. The connected field gives information and should be checked.
- Remove outdated comment: https://github.com/PX4/PX4-Autopilot/commit/e360dd34f91628d8d090df10d08250241dcfea7d#diff-3a5252ca9358f …
=> Battery class Refactor

src/modules/uuv_att_control/uuv_att_control_params.c
decimal for the uuv_att_control gain parameters was not defined. So
QGroundControl displays them as integers what is rather unhandy.
=> define decimals for uuv_att_control gains

.vscode/cmake-variants.yaml
Adds fmuv6x default and bootloader to vscode cmake variants for development.
=> Add fmuv6x to vscode cmake variants

src/drivers/px4io/px4io.cpp, src/modules/vtol_att_control/vtol_type.cpp
- px4io: ensure pwm params are loaded before any other module starts
-  fix vtol_att_control: set _current_max_pwm_values to current values on init
=> vtol: fix pwm max init

src/drivers/uavcan_v1/ParamManager.hpp, src/drivers/uavcan_v1/Publishers/Publisher.hpp, src/drivers/uavcan_v1/Publishers/uORB/actuator_outputs.hpp, src/drivers/uavcan_v1/Uavcan.hpp, src/drivers/uavcan_v1/parameters.c
Adds the uORB actuator_outputs publisher
Furthermore fixes the PX4 param binding conversion in the Publisher.cpp base class.
TODO think about somekind of publication manager once we start adding a lot of publisher to save on memory and think about rate limiting functionality.
=> [UAVCANv1] Added uORB actuator_outputs publisher

boards/px4/fmu-v2/fixedwing.cmake, boards/px4/fmu-v2/test.cmake, platforms/common/include/px4_platform_common/module.h, src/drivers/telemetry/CMakeLists.txt, src/drivers/telemetry/iridiumsbd/IridiumSBD.cpp, src/drivers/telemetry/iridiumsbd/IridiumSBD.h
- fixes hardfault on boot if no device attached
- still disabling the module for now as there are more issues (@RomanBapst will provide the details)
I don't have hw to test with.
=> Iridium: disable module for now

ROMFS/px4fmu_common/init.d/rc.interface, src/drivers/pwm_out/PWMOut.cpp, src/lib/pwm/pwm_aux_params.yaml, src/lib/pwm/pwm_main_params.yaml
Like it was noted in the dev call of 16. June PWM default values for the entire output module e.g. `PWM_MAIN_MAX`, `PWM_MAIN_MIN`, `PWM_MAIN_DISARMED` get loaded now to all channels and not just to the ones masked by the `PWM_OUT` environmental variable set in the airframe which was not previously the case. `PWM_OUT` described the outputs going to ESCs that all use these same limits to have safe propeller actuator operation.
I described my first analysis in slack here: https://px4.slack.com/archives/C50RWGQMT/p1623862141134000
> I think we found the PWM disarmed default being loaded issue that was mentioned in the call (FYI @dagar):
Before it only loaded them for the outputs the airframe specified as ESCs with the very descriptive PWM_OUT …
=> PWM: Draft implementation to respect PWM_OUT when loading defaults

boards/freefly/can-rtk-gps/src/led.cpp, src/drivers/lights/rgbled_ncp5623c/rgbled_ncp5623c.cpp
problem solved by this pull request**
Class name and device name are different.
I used the class name as the device name.
None.
No build errors.
None.
=> NCP5623C: Change the class name to the device name

platforms/nuttx/src/px4/common/px4_24xxxx_mtd.c
=> [at24c] free perf counters if px4_at24c_initialize fails

src/drivers/px4io/px4io.cpp
Follow-up to  #17833.
Credits to @dagar
=> drivers/px4io: mirror PWM_MAIN_OUT support

msg/sensor_gyro_fft.msg, src/lib/mathlib/math/filter/MedianFilter.hpp, src/modules/gyro_fft/GyroFFT.cpp, src/modules/gyro_fft/GyroFFT.hpp
On real vehicles the detected peaks tend to jump around quite a bit. This PR is an attempt to track each detected peak primarily to minimize unnecessary notch filter resets, but also make things easier to view.
=> gyro_fft: track closest FFT peaks over time and median filter frequency

msg/sensor_gyro_fft.msg, posix-configs/SITL/init/test/test_imu_filtering, src/modules/gyro_fft/GyroFFT.cpp, src/modules/gyro_fft/GyroFFT.hpp, src/modules/gyro_fft/parameters.c
The `gyro_fft` module is generally working by default, but the latency is still a bit high.
- change default FFT length (1024 -> 512)
- this doubles the update rate because half the number of samples are required for each
- decrease number of peaks (4 -> 3)
- so far 3 seems to be sufficient
- increase median filter window (3 -> 5)
- decrease SNR requirement
For example this throttle change is detected about 150 milliseconds after commanded. 
https://review.px4.io/plot_app?log=332c609f-55b2-421d-96f2-0075b6f1bc82
=> gyro_fft: decrease default length 1024 -> 512

src/modules/mc_pos_control/MulticopterPositionControl.cpp, src/modules/mc_pos_control/MulticopterPositionControl.hpp
Hello,
This PR renames instances of `control_mode` to `vehicle_control_mode` as they all pertain to the `vehicle_control_mode_s` type and related *.msg file.  This PR introduces no functional changes, just helps connect the dots between the messages and states with how/where they are used.  This PR also does a little bit of whitespace formatting and alphabetization for readability.
Test flown here, no issues or differences from current master branch: https://review.px4.io/plot_app?log=1e90cf5b-cc99-4d5f-a746-da8655a19a85
Please let me know if you have any questions or comments on this PR.
Thanks!
-Mark
=> Rename 'control_mode' to 'vehicle_control_mode' in MulticopterPositionControl.cpp/hpp.

src/drivers/distance_sensor/broadcom/afbrs50/AFBRS50.cpp, src/drivers/distance_sensor/broadcom/afbrs50/AFBRS50.hpp
This PR for the Broadcom AFBR-S50LV85D Distance Sensor driver prevents the sensor from publishing invalid measurements when too close or far from the surface. The issue noticed was that before lift off, the drone would measure distances on the scale of 1000's of meters. Once the sensor was an acceptable distance from the ground, measurements recording was accurate.
Measured data is gated to ensure the value is within the sensor's minimum and maximum range before publishing. For invalid measurements, a value of zero meters is published instead with a signal quality of zero.
The driver was tested on an ARK Flow running as a uavcannode with a Pixhawk 4 Mini on 1.12 beta 5. The system was also …
=> Broadcom AFBR-S50LV85D Distance Sensor Driver: Publish Quality

src/modules/navigator/navigator.h, src/modules/navigator/navigator_main.cpp
Users that are using ADS-B such as pingRX from uAvionix are spammed with information of the traffic in configured radius.
This solution will reduce spam. 
This solution will take the ICAO address of the first vehicle detected as traffic, and it will reduce the message time interval to 60 seconds instead of 1 second. If the second vehicle enters into configured radius user will get spam again. 
The solution has the function `buffer_air_traffic` that can be expanded for more than one ICAO detected.
It is done this way because we want to log all traffic in our configured radius despite being spammed. 
in the future, we will need to collect more information from user experience to find out what radius diameter / ICAO …
=> navigator: reduce traffic alert messages

ROMFS/px4fmu_common/mixers/FX79.main.mix
flash overflow on master
```
/opt/gcc/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld: region `flash' overflowed by 9 bytes
```
=> mixers: exclude FX79.main.mix from px4_fmu-v2

src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp, src/modules/ekf2/ekf2_params.c
This adds the required parameters and parameter documentation changes required for compatibility with the addition of a rotor momentum drag model to the EKF's multi-rotor wind estimator function. See https://github.com/PX4/PX4-ECL/pull/1013 for details.  The multi-rotor wind estimation feature remains off by default as before.
TODO: https://docs.px4.io/master/en/advanced_config/tuning_the_ecl_ekf.html#multicopter-wind-estimation-using-drag-specific-forces will also need to be updated in a separate PR
=> Add parameter support for EKF multi-rotor momentum drag model

msg/event.msg, platforms/common/events.cpp, src/modules/logger/logger.cpp, src/modules/mavlink/mavlink_main.cpp
`sequence` is an IDL reserved keyword, which results on failure when parsing with FastRTPSGen.
Renamed `sequence` to `event_sequence`, as aligned with @bkueng.
As a follow-up, I will also add a list of reserved keywords check to our IDL generator so to avoid that these words are used in uORB. List can be found in page 29 of the following PDF: https://www.omg.org/spec/IDL/4.2/PDF.
Changed it as well in `px4_msgs`, and now the bridge builds correctly. Before, this happened: https://github.com/PX4/px4_ros_com/runs/3014970272.
=> events interface: chance uORB 'sequence' to 'event_sequence'

src/modules/sensors/sensor_params.c
During our last testflight we noticed that the tube pressure compensation returns too high calibration factor causing our plane to stall.
Adjust the lower bound of CAL_AIR_TUBED_MM to 1.5 mm such that the users gets warned if they want to set a value lower than 1.5 mm. This limit should be feasible since Sensirion anyway recommends a tube diameter larger than 1.8 mm.
We could also enforce a lower bound in the software but I am not fully convinced that this is the way to go.
Logfile: https://review.px4.io/plot_app?log=0477a18b-4aef-4996-ac17-4aa5391e6303
I implemented a matlab script to visualize the scale factor and the corrected …
=> Adjust lower bound for CAL_AIR_TUBED_MM to 1.5 mm

src/drivers/optical_flow/paw3902/PAW3902.cpp, src/drivers/optical_flow/paw3902/PAW3902.hpp, src/drivers/optical_flow/paw3902/paw3902_main.cpp
- configure a backup schedule when using motion interrupt otherwise the sensor will stop publishing entirely in the dark
- as a precaution issue full reset if sensor is stuck in a bad state (no vaid data for an extended period)
- update light mode change criteria to match datasheet exactly
=> optical_flow/paw3902: minor improvements

README.md
Found a broken link in README.md for bitcraze crazyflie2.0 under 'Manufacturer and community supported' section. 
Fixed broken link to point to https://docs.px4.io/master/en/complete_vehicles/crazyflie2.html.
=> Update README.md to fix broken crazyflie2.0 link

src/modules/mavlink/mavlink_receiver.cpp
When forwarding on MAVlink channel is used there could be other systems/components. When GCS through us send commands to them, these commands are treated as alien commands for this system (default component), and failed acknowledge is sent by us, but must not.
=> mavlink: fix incorrect rejection of forwarded alien commands

ROMFS/px4fmu_common/init.d-posix/airframes/1037_believer, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt, platforms/posix/cmake/sitl_target.cmake
**Problem Description**
This commit adds the [makeflyeasy Believer](https://ardupilot.org/plane/docs/airframe-believer.html) fixedwing vehicle as a Gazebo SITL target.
This commit adds an airframe configuration and make target for believer
**Testing**
```
make px4_sitl gazebo_believer
```
- The model files are added in the PX4/PX4-sitl_gazebo submodule: https://github.com/PX4/PX4-SITL_gazebo/pull/753
=> Add airframe configuration and make target for believer

src/modules/sensors/sensors.cpp
Otherwise specific builds without barometer and several modules can failed with:
`'__orb_sensor_baro' was not declared in this scope`
=> sensors: add include for sensor_baro topic

ROMFS/px4fmu_common/init.d-posix/rcS
In the `rcS` file the `-r` argument is missing for `micrortps_client start`. This is a problem since it won't take in the UDP port and will use the default. In the case for testing multiple vehicles, it will always start each vehicle with a receive port of `2019`. Multiple vehicles cannot be used because of this.
Add in a missing `-r` argument specification.
N/A
Tested locally and by looking at the SITL logs to make sure the second vehicle starts with receive port `2021` …
=> Add missing receive port arg to micrortps_client start

Tools/px4airframes/markdownout.py
This improves the airframe reference generator and generated docs. 
- Pulls out the styling of the generated docs into a style section. This reduces the generated code size quite significantly and improves the table layout.
- Fixes broken rendering in [racerblade](https://docs.px4.io/master/en/airframes/airframe_reference.html#quadrotor-x) caused because it has the " symbol in its name.
- Fixes the note to new standard.
=> Airframe docs

src/modules/mavlink/mavlink_ulog.cpp, src/modules/mavlink/mavlink_ulog.h
Helping mechanism for detecting lost ulog_stream messages
Using perf counter for each lost message. 
=> ulog stream message lost

src/modules/ekf2/EKF/ekf.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/estimator_interface.h, src/modules/ekf2/test/sensor_simulator/range_finder.h, src/modules/ekf2/test/sensor_simulator/sensor_simulator.h
Hello,
There are a few member variable initializers in the Ekf class constructor when the variables are already being initialized to the same value in the header file.  Also, a few Vector2f and Vector3f member variables lacked initializers. This PR deletes the redundant initializations and adds the missing instances.
These changes have no functional impact.
Flight tested previously for this [PR](https://github.com/PX4/PX4-ECL/pull/1024) on a pixhawk 4 mini: https://review.px4.io/plot_app?log=2da62b20-b242-4f10-b9a7-e1c8fc639b86
Please let me know if you have questions regarding this PR. Thanks!
-Mark
=> Delete redundant Ekf constructor initilizations, add missing initializers to the header file.

Tools/HIL/run_nsh_cmd.py
For example, running the command succeeded, but the echo was interrupted by `gyro_calibration`.
http://px4-jenkins.dagar.ca:8080/blue/organizations/jenkins/PX4-Autopilot/detail/PR-17810/3/pipeline
=> Tools/HIL/run_nsh_cmd.py handle missing echo, but cmd succeeded

src/modules/ekf2/EKF2.cpp
Silencing unnecessary console output.
=> ekf2: don't print distance_sensor selection unless there are multiple options

.gitmodules, Tools/setup_ignition.bash, Tools/sitl_run.sh, platforms/posix/cmake/sitl_target.cmake
This commit adds SITL support for [ignition gazebo](https://ignitionrobotics.org/home). Ignition gazebo is a replacement for the "classic" gazebo for future applications.
Since PX4 uses gazebo for a lot of integration testing and simulated environments, it makes a lot of sense to integrate into the new ignition gazebo.
This implementation is a first iteration supporting SITL in the ignition environment.
- a `mavlink_interface_plugin` was implemented as an interface for `HIL_*` mavlink messages between px4 and `ignition gazebo`
- Only a quadrotor is supported in the current implementation
A demonstration of the package is shown in the video below:
[![ignition gazebo …
=> Add ignition gazebo support for PX4 Software-In-The-Loop simulations 

msg/templates/urtps/microRTPS_transport.cpp
bitwise not should be used instead of logical not
I don't use microR, just notice an issue, can't test.
=> microRTPS: fix setting UART communication flags

msg/tools/uorb_rtps_message_ids.yaml
I honestly don't understand why https://github.com/PX4/PX4-Autopilot/pull/17944 was merged, considering that CI was complaining. But anyway, here's the fix.
On the PR description.
N.A.
N.A.
N.A.
=> add missing baro_bias_estimate to RTPS list

boards/nxp/fmuk66-e/src/init.c, boards/nxp/fmuk66-v3/src/init.c
For testing https://github.com/PX4/PX4-Autopilot/issues/17900#event-5014844913
https://github.com/PX4/NuttX/pull/159 - **Merged**
It turns out the DMA polling is needed. The IDLE INT will not happen on repetitive signals.   
This PR will be rebased when https://github.com/PX4/NuttX/pull/159 is merged. - Done
=> Fix Kinetis serial 

src/drivers/camera_trigger/camera_trigger_params.c
This is incorrect and causing QGC unit tests to fail.
=> Fix incorrect max for INT32

src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_main.h, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h
Forward message to other mavlink channels only if it is broadcast or the target component was seen on this link before (at least one message was received)
Each MavlinkReceiver for rx stats already has `_component_states` that collects `system_id` and `component_id` of each component it have seen on this link. So it can be used to explicitly route forwarding messages and to reject alien commands more precisely than in #17871.
Also this PR introduces `_component_states_count` of real number of external systems seen, that optimize corresponding loops a little.
=> mavlink: use explicit routing for message forwarding

src/templates/template_module/template_module.h
I have not tried compiling the template module itself, but when using it as a template, the following where the additions that I had to make in order for it to compile.
- **SubscriptionInterval.hpp** includes **Subscription.hpp**, but not vice versa. So I swapped the two.
- The time literal `1_s` is defined in the namespace **time_literals**
=> Fix template_module header

src/modules/mavlink/mavlink_receiver.cpp
This reverts the behavior for offboard velocity setpoint.
Back in v1.11, the velocity input in NED_BODY was assumed to be in the world frame but rotated by yaw to the vehicle frame. With the current state the frame is completely fixed to the body. While this might be
technically correct, it doesn't seem much intuitive for multicopters and breaks the MAVSDK offboard velocity API.
So as an example, with a velocity setpoint of 5 m/s forward, the drone
would in
- v1.11: fly forward with 5 m/s
- v1.12: start to fly forward by pitching down but then descend rapidly   as the forward velocity would translate to a setpoint in Z into the ground as it is pitched down.
This commit restores the behavior to what we had previously.
This problem was found by @farhangnaderi in …
=> mavlink: fix offboard velocity input

src/modules/sensors/voted_sensors_update.cpp
With multi-EKF enabled the sensors module doesn't decide on the primary IMU, but we can still populate the basic healthy flags in the `sensors_status_imu` message.
- fixes https://github.com/PX4/PX4-Autopilot/issues/17927
@ThomasRigi can you give this a try?
Note that the "full" sensor health should be decided at a higher level combining both these low level checks (timeouts, etc) with estimator status.
=> sensors: populate sensors_status_imu healthy flags even in multi-EKF mode

boards/mro/ctrl-zero-h7-oem/init/rc.board_defaults, boards/mro/ctrl-zero-h7/init/rc.board_defaults, boards/mro/pixracerpro/init/rc.board_defaults, src/lib/battery/battery_params_deprecated.c, src/modules/mavlink/mavlink_parameters.cpp
- BAT_V_EMPTY, BAT_V_CHARGED, BAT_V_LOAD_DROP, BAT_N_CELLS
Otherwise older QGC is nearly unusable with continuous error pop ups.
=> keep minimal legacy battery parameters for older QGC usability

src/modules/sensors/vehicle_imu/VehicleIMU.cpp, src/modules/sensors/vehicle_imu/VehicleIMU.hpp
- this avoids any jitter in the integration timespan from impacting the vibration metrics
- vehicle_imu_status vibration metrics are not consumed by anything (yet), so changing the scaling of the metric shouldn't matter
=> sensors/vehicle_imu: vibration metrics use acceleration and angular velocity

src/modules/airspeed_selector/airspeed_selector_main.cpp
The message thrown at the operator after an Airspeed sensor failure used to not contain any useful information on how to proceed.
Leonardo changed that message to a better wording
=> AirspeedSelector: Improve wording of sensor failure message

.github/ISSUE_TEMPLATE/2_Feature_request.md, .github/slack.svg, README.md
Our previous slack bot has been deprecated. While we move to a new platform (replacing Slack), we should still invite users to join our community on Slack.
=> README: update slack invite and badge

boards/px4/fmu-v2/src/spi.cpp, boards/px4/fmu-v3/src/spi.cpp
- fixes https://github.com/PX4/PX4-Autopilot/issues/17858
Historically it was only PE4 used as the chip select for external SPI.
https://github.com/PX4/PX4-Autopilot/blob/ea48cd4970977f4d189c1a9ba82483ac03852299/boards/px4/fmu-v2/src/board_config.h#L183-L184
=> boards: px4 fmu-v2/v3 swap external SPI chip select order

test/mavsdk_tests/test_multicopter_failsafe.cpp, test/mavsdk_tests/test_multicopter_mission.cpp
Let's ignore the tests which only fly VTOL in multicopter mode for now. They just take time and don't add much.
=> mavsdk tests: remove hover missions for VTOL

src/modules/mc_pos_control/MulticopterPositionControl.cpp
- Before the rampup state and when `!flying`, `_setpoint.acceleration[2]` is set to NAN, `_setpoint` is overwritten by NAN and `_setpoint.acceleration` is set to (0,0,100) 
- When reaching rampup, `_setpoint.acceleration[2]` is still set to NAN, `_setpoint` isn’t overwritten anymore and `_setpoint.acceleration[2]` isn’t set (to 100) anymore
- Since the loop is scheduled on local_pos estimate and not the setpoint, it can be that the `_setpoint` is still NAN (overwritten state) from the previous iteration
- At that exact point in time, `_setpoint.vz(2)` and `_setpoint.acceleration[2]` are NAN, so the output is invalid: triggering `WARN [mc_pos_control] invalid setpoints`
Only apply the overriding logic when there is …
=> Fix invalid setpoint on takeoff

src/drivers/distance_sensor/broadcom/afbrs50/AFBRS50.cpp, src/drivers/distance_sensor/broadcom/afbrs50/AFBRS50.hpp
This PR for the Broadcom AFBR-S50LV85D Distance Sensor driver allows the sensor to use its long range or short range mode based on measured distance. This allows for better measurement results up to distances over 30 meters.
The sensor starts in short range mode at 50 Hz and only transitions to long range mode at 25 Hz once measuring over 6m distance. On descent, the sensor requires distances below 4m to transition back to short range mode.
The driver was tested on an ARK Flow running as a uavcannode with a Pixhawk 4 Mini on 1.12 beta 5. The system was also running an ARK GPS on UAVCAN.
over grass (run 1): https://review.px4.io/plot_app?log=a9743528-3014-45f6-8e6d-b9c1f1a80b84
over grass …
=> Broadcom AFBR-S50LV85D Distance Sensor Driver: Automatic Range Mode Switching

boards/px4/fmu-v2/default.cmake, cmake/px4_add_board.cmake, platforms/common/module.cpp
We are out of flash again on the V2. 
My recollection was there was supposed to be a tool to make the doc from the code.  
This PR replaces the help with the a URL in the defualt.cmake file or if none is provided uses  https://docs.px4.io/master.
=> Add No help Option to CONSTRAINED_FLASH

.ci/Jenkinsfile-compile
Broken during the Snapdragon purge (https://github.com/PX4/PX4-Autopilot/pull/17921) that happened to correspond with the primary Jenkins master (ci.px4.io) being down.
=> Jenkins fix compile job

ROMFS/px4fmu_common/init.d-posix/airframes/1014_solo
The solo model was showing oscillations while flying. 
This issue was discussed in https://discuss.px4.io/t/sitl-gazebo-3dr-solo-oscillation-issue/23557
Tuning down the roll controller to remove the oscillations
Before PR: https://review.px4.io/plot_app?log=7a09b3f9-6f6f-4c5e-9d18-dbbd5c69094f
After PR: https://review.px4.io/plot_app?log=f270ad7e-6dfc-4c51-9770-50a391955789
=> Tune down solo roll rate controller

Tools/px4airframes/markdownout.py
This makes the CSS selectors more specific for airframes reference.
My understanding was that css in the page would be restricted to the page. Perhaps I am wrong, because Css defined in this page was affecting global styles elsewhere  - e.g. images in other pages. This makes the changes to the page "more specific" to this page.
=> More specific airframe css

src/modules/ekf2/CMakeLists.txt
Fixing the error 
```
error: the frame size of 3536 bytes is larger than 3500 bytes [-Werror=frame-larger-than=]
```
@dagar Or should we keep the stack size here as low as possible? On fmu-v3 the required frame size was 3544. Not sure what causes these fluctuations.
=> ekf2: increase stack size to 3600

src/drivers/barometer/mpl3115a2/MPL3115A2.cpp, src/drivers/barometer/ms5611/ms5611_i2c.cpp
A couple of fixes for the i2c reset init branch
Edit:
removed my commit: (ist8308: fix return PX4_ERROR if can't get device id)
It is already fixed here
=> fixes for i2c reset init branch

msg/estimator_event_flags.msg, msg/estimator_status.msg, msg/estimator_status_flags.msg, src/modules/commander/Commander.cpp, src/modules/ekf2/EKF/common.h, src/modules/ekf2/EKF/control.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/ekf_helper.cpp, src/modules/ekf2/EKF/estimator_interface.h, src/modules/ekf2/EKF/gps_checks.cpp, src/modules/ekf2/EKF/gps_yaw_fusion.cpp, src/modules/ekf2/EKF2.cpp, src/modules/ekf2/test/test_EKF_gps_yaw.cpp
Some GNSS receiver (providing heading information) start to output an incorrect value first and then reset a few seconds later (seen on some F9p setup). Also, until now, the yaw emergency estimator was only able to stop a bad heading induced by a faulty magnetometer but not other heading sources.
- use dedicated observation noise instead of mag heading observation noise value
- trigger gyro bias variance reset based on "innovation sequence monitoring" (i.e.: average signed test ratio above some threshold)
- allow multiple resets to GNSS yaw before takeoff
- allow yaw emergency logic to disable GNSS yaw aiding
- added test cases for "GNSS yaw reset on ground" and "GNSS yaw wrong value to yaw emergency reset"
- …
=> GNSS yaw jump and failure handling improvements

src/modules/ekf2/EKF/estimator_interface.cpp, src/modules/ekf2/EKF/estimator_interface.h, src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp
- consume IMU vibration metrics from vehicle_imu_status
- estimator_status vibe_metrics kept for compatibility, but could be removed with corresponding flight review update
- sensors/vehicle_imu vibration metrics could now be computed at higher rates if desired
=> ekf2: remove redundant IMU vibration metrics

src/modules/commander/Commander.cpp
**How this PR solves the problem**
The check for the attitude validity (part of the "AHRS preflight check") is quite sensitive to numerical issues as it makes a lot of computations that can lead to a loss of precision before doing the actual check.
Investigations showed that the `.normalize()` or `.unit()` functions of the quaternion class does not produce a perfect unit quaternion, but is always in the `FLT_EPSILON` tolerance. This PR then changes the attitude check to verify that the norm is in tolerance and that each element of the quaternion is strictly smaller or equal to 1 (in order to avoid NAN in trigonometric functions).
The fix is easily verified in SITL:
Before:
With this PR:
=> Commander: change attitude quaternion check to avoid numerical issues

src/drivers/distance_sensor/broadcom/afbrs50/AFBRS50.cpp, src/drivers/distance_sensor/broadcom/afbrs50/AFBRS50.hpp
This PR fixes the high cpu load on the afbrs50 driver from the mode switching. There was no check to see what mode it was in.
I also added in the get mode call to the status function.
```
nsh> afbrs50 status
afbrs50: sample interval: 6114 events, 10662.56us avg, min 4269us max 648024us 16543.408us rms
distance: 2.772m
mode: 2
dfm mode: 2
rate: 50 Hz
nsh> afbrs50 status
afbrs50: sample interval: 6557 events, 10621.64us avg, min 4269us max 648024us 15976.356us rms
distance: 9.524m
mode: 1
dfm mode: 2
rate: 25 Hz
```
Whats in current master
```
0 Idle Task                   23957 17.683   300/  512   0 (  0)  READY  3
1 hpwork                       1298  2.452  1812/ 2988 254 (254)  w:sig  3
2 lpwork …
```
=> Fix afbrs50 high cpu load from switching

src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h
This commit d997a8d308b132d4f7009eb6b4d04687519346b0 adds variable `map_projection_reference_s _global_local_proj_ref{}` to `mavlink_receiver.h`, so `geo.h` should be include in header.
=> mavlink: receiver move geo.h include to header

ROMFS/CMakeLists.txt
Fixes the build in some environments.
@SalimTerryLi
=> ROMFS cmake remove directory VERBATIM

src/modules/flight_mode_manager/tasks/ManualAcceleration/FlightTaskManualAcceleration.cpp, src/modules/flight_mode_manager/tasks/ManualAcceleration/FlightTaskManualAcceleration.hpp
- fixes https://github.com/PX4/PX4-Autopilot/issues/17911
@taileron @VTOLDavid can you give this a try?
=> flight_mode_manager: ManualAcceleration support weathervane yaw handler

src/drivers/gps/gps.cpp, src/drivers/gps/params.c, src/modules/logger/logged_topics.cpp
to enable, set `GPS_DUMP_COMM` to 2, which enables RTCM output on the Main GPS plus logging
=> gps: enable RTCM output for PPK

Tools/mavlink_ulog_streaming.py, platforms/common/uORB/SubscriptionInterval.hpp, src/modules/logger/logged_topics.cpp, src/modules/logger/logger.cpp, src/modules/logger/logger.h, src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_main.h, src/modules/mavlink/mavlink_receiver.cpp
- send post-flight perf data when stopping mavlink log streaming 
- avoid data bursts by distributing slow subscription updates over time
- turn off lockstep when starting log streaming 
- remove unused topics, move some to debug profile
=> Logger extensions (post-flight perf data over mavlink streaming + more)

ROMFS/px4fmu_common/init.d/rc.sensors, src/drivers/differential_pressure/ets/parameters.c, src/drivers/differential_pressure/ms4525/parameters.c, src/drivers/differential_pressure/ms5525/parameters.c, src/drivers/differential_pressure/sdp3x/parameters.c
- automatically probing for all potential sensors at startup can be problematic in cases that can't be distinguished (eg ms5611 barometer and ms5525 differential pressure sensor)
- by explicitly enabling each sensor we can do thing like start and keep running (-k) even if not found which allows users to attach after initial boot up
NOTE: this is a change in behavior users would need to be made aware of
=> ROMFS: new parameters for starting differential pressure sensors instead of autostart

src/modules/fw_att_control/FixedwingAttitudeControl.cpp
For fixedwings, there were different flap scalings deployed between auto modes and manual flight modes, resulting in the flaps always being deployed halfway in manual flight modes.
- In manual flight modes(stabilized, manual), zero flap input was mapped to flap command 0.5
- In auto modes(mission, hold), zero flap command was mapped to flap command 0.0
This PR removes the special scaling in manual flight modes, so that the flap does not get deployed when switching fixed wing aircraft between manual and auto modes.
This should not influence flaps being deployed in auto modes.
By removing the scaling, we are assuming that flap commands range from [-1, 1]. This makes more sense …
=> Fix flaps being deployed in manual flight modes for fixedwing

src/lib/battery/battery_params_common.c, src/lib/circuit_breaker/circuit_breaker_params.c, src/modules/commander/commander_params.c, src/modules/commander/failure_detector/failure_detector_params.c
It was annoying me since a while that for some parameters, after you change it in QGC, the "reboot required" message pops up, though the change already has an effect. 
Remove the "reboot_required" from couple of parameters that I think don't require it. There probably are more.
=> Remove a couple of unnecessary reboot_required from parameter meta data

msg/sensor_correction.msg, src/lib/parameters/templates/px4_parameters.hpp.jinja, src/lib/sensor_calibration/Accelerometer.cpp, src/lib/sensor_calibration/Accelerometer.hpp, src/lib/sensor_calibration/Gyroscope.cpp, src/lib/sensor_calibration/Gyroscope.hpp, src/lib/sensor_calibration/Magnetometer.cpp, src/lib/sensor_calibration/Magnetometer.hpp, src/lib/sensor_calibration/Utilities.cpp, src/lib/sensor_calibration/Utilities.hpp, src/modules/commander/accelerometer_calibration.cpp, src/modules/commander/gyro_calibration.cpp, src/modules/commander/mag_calibration.cpp, src/modules/gyro_calibration/GyroCalibration.cpp, src/modules/sensors/sensor_params_acc0.c, src/modules/sensors/sensor_params_acc1.c, src/modules/sensors/sensor_params_acc2.c, src/modules/sensors/sensor_params_acc3.c, src/modules/sensors/sensor_params_gyro0.c, src/modules/sensors/sensor_params_gyro1.c, src/modules/sensors/sensor_params_gyro2.c, src/modules/sensors/sensor_params_gyro3.c, src/modules/sensors/sensor_params_mag0.c, src/modules/sensors/sensor_params_mag1.c, src/modules/sensors/sensor_params_mag2.c, src/modules/sensors/sensor_params_mag3.c, src/modules/sensors/sensors.cpp, src/modules/sensors/voted_sensors_update.cpp, src/modules/temperature_compensation/TemperatureCompensationModule.cpp
Temperature change is still the largest source of error for most of the sensors we use. This pull request updates the sensor (accel/gyro/mag) calibration routines to also save the sensor's temperature at calibration time if it was available. Having this information stored along with the calibration will enable us to start casually monitoring the calibration change with respect to temperature.
Depending on what we learn from this data we could start considering the value of automatically storing calibrations at multiple temperatures or in some circumstances warn users if there's a significant difference in calibration temperature vs current operating temperature.
=> sensor calibration: save temperature at calibration time for monitoring

msg/ekf2_timestamps.msg, msg/tools/generate_msg_docs.py
This improves parsing of the uorb message to allow a short description for the summary and a longer description for the uorb itself.
The long description is all "description text" until you get to the actual content. The short description is the first paragraph of the long description - the delineator being an empty line.
This is better - looking at the old version we were forcing arbitrary line lengths and ignoring potentially useful content. If we ever go to a more extended comment syntax this will result in less churn.
=> generate_msg_docs: generate better page title

boards/freefly/can-rtk-gps/src/led.cpp, boards/nxp/ucans32k146/src/CMakeLists.txt, platforms/nuttx/src/px4/common/px4_init.cpp, platforms/nuttx/src/px4/nxp/s32k14x/include/px4_arch/i2c_hw_description.h, platforms/nuttx/src/px4/nxp/s32k1xx/include/px4_arch/i2c_hw_description.h, src/drivers/barometer/lps22hb/LPS22HB_I2C.cpp, src/drivers/barometer/lps25h/lps25h_i2c.cpp, src/drivers/barometer/mpl3115a2/MPL3115A2.cpp, src/drivers/barometer/ms5611/ms5611_i2c.cpp, src/drivers/distance_sensor/ll40ls/LidarLiteI2C.cpp, src/drivers/distance_sensor/teraranger/TERARANGER.cpp, src/drivers/distance_sensor/vl53l0x/VL53L0X.cpp, src/drivers/distance_sensor/vl53l1x/vl53l1x.cpp, src/drivers/lights/rgbled/rgbled.cpp, src/drivers/lights/rgbled_ncp5623c/rgbled_ncp5623c.cpp, src/drivers/magnetometer/hmc5883/hmc5883_i2c.cpp, src/drivers/magnetometer/isentek/ist8308/IST8308.cpp, src/drivers/magnetometer/lis2mdl/lis2mdl_i2c.cpp, src/drivers/magnetometer/lis3mdl/lis3mdl_i2c.cpp, src/drivers/magnetometer/rm3100/rm3100_i2c.cpp, src/drivers/telemetry/bst/bst.cpp, src/lib/drivers/airspeed/airspeed.cpp
This adds a full I2C bus reset in board init, both using the low level I2C driver reset (if enabled), followed by a general call software reset. With a centralized bus reset now handled by the board on all buses we can reduce the retries scattered across most drivers. The current external I2C device probing results in a huge number of I2C reset attempts.
- fixes init for stubborn I2C devices like the Sensirion sdp3x or the QMC588L magnetometer
- minimize the retry count for most I2C drivers as the board now does a reset on each bus
=> platforms/nuttx: px4_init initialize and reset all I2C buses

src/modules/battery_status/analog_battery_params_deprecated.c
The BAT_ADC_CHANNEL  deprecated param points to BAT1_ADC_CHANNEL in docs, but it looks like it should point to BAT1_I_CHANNEL
=> BAT_ADC_CHANNEL should point to BAT1_I_CHANNEL

ROMFS/px4fmu_common/init.d/rc.interface, src/drivers/px4io/CMakeLists.txt, src/drivers/px4io/px4io.cpp, src/drivers/px4io/px4io_params.c, src/modules/px4iofirmware/mixer.cpp
Round 2. Commits can be squashed afterwards.
- SYS_USE_IO: made sure the existing behavior still works - this can still be extended as desired.
- see commit messages for further details
Tested:
- `pwm test`, `motor_test test`
- sbus out
- rc, rc lost
- pwm disarmed ioctl update after bootup
- SYS_USE_IO
- checked all combinations of flight termination, safety circuit breaker settings and arming vs disarming, safety on vs off states: behavior of fmu reboot, hardfaults. Verified failsafe/parachute trigger is entered in the expected conditions.
- pwm: oneshot, 50hz vs 400hz
- SYS_HITL
Oneshot doesn't look great, but it's similar to what we have now (increasing the proc prio helps)
=> px4io mixing on fmu updates (2)

boards/px4/fmu-v6u/default.cmake, boards/px4/fmu-v6u/test.cmake, boards/px4/fmu-v6x/default.cmake, boards/px4/fmu-v6x/test.cmake, src/drivers/uavcan/CMakeLists.txt
More flash overflows that slipped into master during the few days that px4_fmu-v2_default was out of flash.
This updates the test variants to actually include the test material and attempts to keep the defaults in sync other than the core board differences (on board sensors, etc).
=> boards: px4_fmu-v6{u,x} fix test variant flash overflow and sync defaults

src/modules/micrortps_bridge/CMakeLists.txt, src/modules/micrortps_bridge/micrortps_client/CMakeLists.txt
I believe this should address the build dependency issue reported in https://github.com/PX4/px4_ros_com/issues/108.
The main issue is that `msg/tools/urtps_bridge_topics.yaml` needs to be a cmake configure time dependency (CMAKE_CONFIGURE_DEPENDS) because it's processed by `execute_process` in a couple places. https://github.com/PX4/PX4-Autopilot/blob/c0efbe1f9cba86bf112f8b62cc2e35956f30ac1a/src/modules/micrortps_bridge/CMakeLists.txt#L53-L55
=> cmake fix micrortps build dependencies

msg/templates/urtps/microRTPS_transport.cpp, src/drivers/protocol_splitter/protocol_splitter.cpp
This considerably improves the message flow for outgoing data. In particular under high load conditions, like param loading or log download.
Check individual commits for details.
=> Protocol splitter: improve TX message flow

src/lib/systemlib/system_params.c, src/modules/commander/Arming/PreFlightCheck/checks/ekf2Check.cpp, src/modules/sensors/sensors.cpp
- add new SYS_HAS_GPS parameter
- the `sensors` hub aggregators for baro, GPS, mag now start based only on the `SYS_HAS_*` parameters rather than waiting for valid sensor data to mark all parameters active as soon as possible (param sync)
- fixes https://github.com/PX4/PX4-Autopilot/issues/18110
@lukegluke can you give this a try?
=> sensors: always start baro/GPS/mag aggregators if SYS_HAS_* set

src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_receiver.cpp
- this is updated by the mavlink rx thread, but checked in the tx thread
This may be why a system left running overnight will report a number of radio status timeouts.
``` Console
ERROR [mavlink] instance 1: RADIO_STATUS timeout
ERROR [mavlink] instance 1: RADIO_STATUS timeout
ERROR [mavlink] instance 1: RADIO_STATUS timeout
ERROR [mavlink] instance 1: RADIO_STATUS timeout
ERROR [mavlink] instance 1: RADIO_STATUS timeout
ERROR [mavlink] instance 1: RADIO_STATUS timeout
ERROR [mavlink] instance 1: RADIO_STATUS timeout
ERROR [mavlink] instance 1: RADIO_STATUS timeout
ERROR [mavlink] instance 1: RADIO_STATUS timeout
ERROR [mavlink] instance 1: RADIO_STATUS timeout
ERROR [mavlink] instance 1: RADIO_STATUS timeout
```
=> mavlink: update radio status timestamp atomically

src/modules/mavlink/mavlink_timesync.cpp
us is compared to ms. This would cause any offboard time that is after Jan 15th, 1970 to be considered valid, instead of the intended Feb 14th 2009.
Changed seconds * 1000 (ms) to seconds * 1000000 (us).
N/A
We did not test it since it is a simple logical error, but we can of course do that if you would like us to
=> Correct conversion from sec to usec

platforms/common/px4_work_queue/WorkQueueManager.cpp, src/drivers/gps/gps.cpp, src/modules/dataman/dataman.cpp, src/modules/logger/logger.cpp, src/modules/mavlink/mavlink_main.cpp, src/modules/micrortps_bridge/micrortps_client/microRTPS_client_main.cpp, src/modules/navigator/navigator_main.cpp
This uses PX4_STACK_ADJUSTED macro for various modules, to increase stack for 64-bit NuttX targets (RISC-V RV64GC)
This is just a set of modules which we have used so far with MPFS board, I didn't add the macro everywhere.
Also, it may be that some of the systemcmd stacks, defined by build environment (STACK_MAIN etc.), should be increased as well, but so far we didn't see problems with those.
=> Increase stacks for 64 bit

src/lib/component_information/CMakeLists.txt, src/lib/component_information/generate_component_general.py, src/modules/mavlink/CMakeLists.txt
With Makefile build, generate_component_general.py was called twice during
build, which did not happen with the ninja build.
This created a race condition with the following error in rare cases:
```
Traceback (most recent call last):
File "/__w/PX4-Autopilot/PX4-Autopilot/src/lib/component_information/generate_component_general.py", line 79, in <module>
save_compressed(filename)
File "/__w/PX4-Autopilot/PX4-Autopilot/src/lib/component_information/generate_component_general.py", line 33, in save_compressed
with open(filename, 'r') as content_file:
FileNotFoundError: [Errno 2] No such file or directory: '/__w/PX4-Autopilot/PX4-Autopilot/build/px4_sitl_default/component_general.json'
make[3]: *** [src/lib/component_information/CMakeFiles/component_information_header.dir/build.make:68: …
```
=> component_information: merge extra component_information_header target 

src/modules/mavlink/mavlink_main.h, src/modules/mavlink/mavlink_receiver.cpp
We should allow connection as soon as possible to make it easier for errors to get to the end user or even things like starting the console over mavlink if the system doesn't completely boot.
=> mavlink: only block parameter sync until boot complete

src/modules/mavlink/mavlink_mission.cpp
Resending a mission request when a received element is not matching the expected sequence number can cause excessive bandwidth usage making the problem even worse!
When a slow or somewhat "full" telemetry link is used. The mission upload (download from Px4 perspective), can cause an excessive growth of mission requests, making the problem even worse!
When the link is only "slow" and not necessarily bad, every request is answered with a mission item (which is relatively large in number of bytes). This will cause the link to be flooded with unnecessary messages, filling up all available bandwidth. Making the whole problemen even worse.
See also Issue #18082 for more details about the problem.
Since the timeout …
=> Do not resend a mission request for non matching sequences

src/modules/commander/gyro_calibration.cpp
Instead of outputting progress at weird percentages and dropping 100%,
this now sends the progress every 10 %.
Before:
```
INFO  [commander] [cal] progress <9>
INFO  [commander] [cal] progress <14>
INFO  [commander] [cal] progress <19>
INFO  [commander] [cal] progress <24>
INFO  [commander] [cal] progress <28>
INFO  [commander] [cal] progress <33>
INFO  [commander] [cal] progress <38>
INFO  [commander] [cal] progress <43>
INFO  [commander] [cal] progress <48>
INFO  [commander] [cal] progress <52>
INFO  [commander] [cal] progress <57>
INFO  [commander] [cal] progress <62>
INFO  [commander] [cal] progress <67>
INFO  [commander] [cal] progress <72>
INFO  [commander] [cal] progress <76>
INFO  [commander] [cal] progress <81>
INFO  [commander] [cal] progress <86>
INFO  [commander] [cal] …
```
=> commander: improve progress output

platforms/nuttx/src/px4/stm/stm32f7/px4io_serial/px4io_serial.cpp, platforms/nuttx/src/px4/stm/stm32h7/px4io_serial/px4io_serial.cpp
- otherwise the next retry can happen quickly enough that dma setup hangs waiting for the stream
- this failure happens consistently if ardupilot is still on the px4io (eg cubeorange)
=> [WIP] px4io_serial: ensure TX DMA is stopped if exiting early on stream error

boards/cuav/nora/src/init.c, boards/cuav/x7pro/src/init.c, boards/cubepilot/cubeorange/src/init.c, boards/holybro/durandal-v1/src/init.c, boards/mro/ctrl-zero-h7-oem/src/init.c, boards/mro/ctrl-zero-h7/src/init.c, boards/mro/pixracerpro/src/init.c
This is adding more boards with MPU enabled in the bootloader into the correct config domain.
=> H7 MPU BL config

Tools/docker_run.sh
- Get recent docker image to fix missing python jsonschema when compling linux arm based targets
slack thread : https://px4.slack.com/archives/C50RWGQMT/p1630417292050700
when compiling arm 32Bits linux based targets it miss some python package (jasonschema)
docker image that is get by Docker_run.sh is outdated (2021-02-04)
changed to px4io/px4-dev-armhf:2021-08-18
why not use latest ? may be avoiding bad commit in docker image
run a compile from a totally fresh checkout
```
$./Tools/docker_run.sh " export NO_NINJA_BUILD=1; make scumaker_pilotpi_default"
guessing PX4_DOCKER_REPO based on input
PX4_DOCKER_REPO: px4io/px4-dev-armhf:2021-08-18
*Unable to …
```
=> use more recent docker image for fixing missing python package (jsonschema)

src/modules/navigator/GeofenceBreachAvoidance/geofence_breach_avoidance.cpp
Minimum vertical distance to geofence was never calculated. This made it very easy to breach the geofence.
=> GeofenceBreachAvoidance: Fixed vertical geofence

Tools/sitl_run.sh
Previously, the ignition startup script was not using the model name, effectively limiting it to start only one world (`ignition.world`)
This PR extends the script so that multiple models can be added to ignition gazebo
As an addition, this PR, also enables verbose from the `VERBOSE_SIM=1` for ignition gazebo (also available for classical gazebo)
```
VERBOSE_SIM=1 make px4_sitl ignition
```
- Includes submodule update of https://github.com/Auterion/px4-simulation-ignition/pull/14
=> Improve Ignition Gazebo Startup scripts

Tools/sitl_run.sh
While `HEADLESS=1` supports other simulators such as `jsbsim`, `gazebo` this flag doesn't work for ignition gazebo
This adds support for `HEADLESS=1` when starting ignition gazebo with headless mode
Headless mode can be tested with the following command
```
HEADLESS=1 make px4_sitl ignition
```
- This is a follow up PR of https://github.com/PX4/PX4-Autopilot/pull/18187
=> Support headless mode for ignition gazebo

.ci/Jenkinsfile-hardware, boards/cubepilot/cubeorange/test.cmake, boards/px4/fmu-v2/test.cmake, boards/px4/fmu-v5/optimized.cmake, boards/px4/fmu-v5x/test.cmake, src/modules/control_allocator/ControlAllocation/ControlAllocationPseudoInverse.cpp, src/systemcmds/microbench/test_microbench_math.cpp, src/systemcmds/microbench/test_microbench_matrix.cpp, src/systemcmds/tests/test_matrix.cpp
From https://github.com/PX4/PX4-Matrix/pull/165
Also fixes the math benchmark: trying to measure a single instruction with perf counters does not work (similar for atomic ops).
The results make more sense now when measuring over a number of ops (e.g. float div slower than add/sub/mul, double is at least an order of magnitude slower than float).
```
INFO  [microbench] RUNNING TEST: time_single_precision_float
float add (10k ops): 10 events, 4887us elapsed, 488.70us avg, min 488us max 489us 0.483us rms
float sub (10k ops): 10 events, 4890us elapsed, 489.00us avg, min 489us max 489us 0.005us rms
float mul (10k ops): 10 events, 4888us elapsed, 488.80us avg, min 488us max 489us 0.421us rms
float div (10k ops): 10 events, 12625us elapsed, 1262.50us avg, min 1262us max 1263us 0.532us rms
float …
```
=> Matrix inversion speedup

boards/cubepilot/cubeorange/init/rc.board_mavlink
Attempting to fix the console/test build.
=> boards: cubepilot_cubeorange only start ADSB mavlink if console not present

src/drivers/tattu_can/CMakeLists.txt, src/drivers/tattu_can/TattuCan.cpp, src/drivers/tattu_can/TattuCan.hpp
This is a simple standalone driver that supports reading from the Tattu Plus Smart battery over CAN using the NuttX CAN driver.
In the current form this won't peacefully coexist with UAVCANv0 or UAVCANv1, but I'd like to reconcile that soon.
=> Tattu Battery CAN support

integrationtests/python_src/px4_it/mavros/mavros_offboard_posctl_test.py, integrationtests/python_src/px4_it/mavros/mavros_test_common.py, src/modules/commander/state_machine_helper.cpp, test/mavsdk_tests/autopilot_tester.cpp, test/mavsdk_tests/autopilot_tester.h, test/mavsdk_tests/test_multicopter_offboard.cpp
Closes #16534 using 2nd proposal of adding a new parameter to allow for failsafe on RC only.
Change the following:
* When Both offboard and RC are lost, use OBL_ACT instead of OBL_RC_ACT
* When only offboard is lost and RCL_EXCEPT is enabled use OBL_ACT instead of OBL_RC_ACT
* When only RC is lost and RCL_EXCEPT is disabled, use NAV_RCL_ACT
The outcomes in the table were picked by my intuition, but can change if needed.
All scenarios in table tested and verified using jmavsim and offboard_control example in px4_ros_com.
=> Improve offboard failsafe

src/lib/mathlib/math/Functions.hpp, src/modules/mc_pos_control/MulticopterPositionControl.cpp, src/modules/mc_pos_control/MulticopterPositionControl.hpp, src/modules/mc_pos_control/PositionControl/PositionControl.cpp, src/modules/mc_pos_control/PositionControl/PositionControl.hpp, src/modules/mc_pos_control/PositionControl/PositionControlTest.cpp, src/modules/mc_pos_control/mc_pos_control_params.c
Currently, if the NED frame vertical position or velocity error is too large and the collective thrust of the multirotor saturates then the vertical thrust is always prioritized. While this prioritization is by design it can lead to complete starvation of horizontal control for the duration of the saturation. In practice, this can be seen as the drone completely leveling out to zero tilt when it hits its thrust limit.
Given that small horizontal corrections result in a non-linearly smaller loss of vertical thrust it makes sense to keep a small margin for horizontal actuation.
My goal so far was to deal with this in acceleration but that obviously takes too long to get done …
=> MulticopterPositionControl: add horizontal margin for vertical saturation cases

src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp, src/modules/commander/Commander.cpp
EKF2 has a grace period of 10 seconds after boot where it doesn't need to warn the user while the sensors (especially GNSS) are still converging.
A connection to a GCS shouldn't skip this grace period but an arming request should.
SITL test: _Set `EKF2_REQ_EPH` to 0.1 to make the GNSS check fail_
- connecting QGC less than 10s after start does not trigger the ekf2 warnings
- connecting after those 10s does trigger the warnings
- arming withing those 10s triggers the warnings
=> PreFltCheck: do not force to report ekf2 failures on GCS connection

platforms/common/include/px4_platform_common/module_params.h, src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectiveness.hpp, src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessMultirotor.cpp, src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessMultirotor.hpp, src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessStandardVTOL.cpp, src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessStandardVTOL.hpp, src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTiltrotorVTOL.cpp, src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTiltrotorVTOL.hpp, src/modules/control_allocator/ControlAllocator.cpp, src/modules/control_allocator/ControlAllocator.hpp
The parameter loading didn't work as expected when using the "ControlAllocation" module. The parameters were first loaded, then if the drone is a multirotor, the `ActuatorEffectiveness` object is changed and the information previously loaded is lost in the old object.
- Restructure the param update handling
- Add a "force" flag to `getEffectivenessMatrix` to force a parameter reload in case of a param update trigger
- Do not subscribe to `parameter_update` uORB topic inside an `ActuatorEffectiveness` class, rely on the parent to send the force flag
SITL Gazebo tests: `make px4_sitl_ctrlalloc gazebo_iris_ctrlalloc`
fixes https://github.com/PX4/PX4-Autopilot/issues/17926
=> Ctrlalloc: refactor param update

src/modules/rc_update/params.c
There was some confusion for a reader as to whether RC_FAILS_THR referred to "throttle" or "threshold". In fact it is a threshold value for the specified channel, which just happens to default to the throttle.
This attempts to make the relationships more clear.
Also removes specific info about Futaba not supporting this mechanism and makes it clear this "applies to anything that uses this mechanism for RC loss"
=> params.c - RC_FAILS_THR and RC_MAP_FAILSAFE

src/modules/commander/Commander.cpp
Before, CMD_DO_SET_HOME had no yaw angle specified, which renders it a bit useless compared to SET_HOME_POSITION. With this PR param4 will be used as the yaw in degrees. A PR to the mavlink documentation will follow.
=> Added yaw to CMD_DO_SET_HOME

msg/esc_report.msg, src/drivers/dshot/DShot.cpp, src/drivers/tap_esc/TAP_ESC.cpp, src/drivers/telemetry/hott/messages.cpp, src/modules/mavlink/streams/ESC_INFO.hpp
Title is self explanatory. This PR needs to go in after the relative mavlink message is updated, https://github.com/mavlink/mavlink/pull/1663.
@dagar i've also noticed that the UAVCAN spec defines the temperature in Kelvin for `uavcan.equipment.esc.Status` (https://legacy.uavcan.org/Specification/7._List_of_standard_data_types/), looking at the code we've always filled the esc_temperature directly from the UAVCAN message.. not sure who to trust there :|
=>  esc_report: change esc_temperature field to allow negative values [needs mavlink submodule update]

msg/rc_channels.msg, src/modules/commander/Commander.cpp, src/modules/commander/ManualControl.cpp, src/modules/commander/ManualControl.hpp, src/modules/rc_update/params.c, src/modules/rc_update/rc_update.cpp, src/modules/rc_update/rc_update.h
This PR introduces a new configuration option which allows users to setup Toggle Buttons for flight mode switches, over the RC signals (e.g S.BUS).
An example application is for example with the Herelink controller, where the buttons can be assigned to specific RC channels which are then sent over S.BUS.
I also added a 100ms hysteresis before flagging that the signal has been regained, as I could experience some glitches on the S.BUS channels when the controller was rebooted. 
Tested with a herelink controller
=> Add support for toggle buttons via RC channels

src/modules/mc_pos_control/PositionControl/PositionControl.cpp, src/modules/mc_pos_control/PositionControl/PositionControlTest.cpp
The horizontal margin introduced in https://github.com/PX4/PX4-Autopilot/pull/18205 has a bug where it correctly limits the vertical thrust but then clamps again all horizontal thrust if the vertical thrust hits that lower limit that would allow the expected horizontal margin. This results in just a lower thrust limit and no margin again.
Using the full available maximum thrust for limiting the horizontal thrust results in the expected margin.
I also corrected the unit test and made it more clear to make sure it can be understood by future developers.
I ran a SITL test saturating the motors and didn't just visually check the behavior but analyzed the values in the log:
Horizontal control …
=> MulticopterPositionControl: correct horizontal margin calculation

.vscode/settings.json
Analogous to https://github.com/PX4/PX4-Autopilot/pull/16580 I noticed myself during usage and heard other people discuss why autocomplete doesn't work the familiar way. If there's an autocomplete suggestion by the Visual Studio Code IDE you currently need to press tab to accept it. By default you can also press enter but that is currently disabled and you always get a newline.
It's definitely user preference and I'm not suggesting either version is better than the other but the project settings should probably keep the default in such cases. People can then customize the user settings. So I'm removing the customization of this setting on the project level.
Any objections @dagar 😇 ?
=> vscode: do not disable autocomplete on enter

src/drivers/camera_trigger/camera_trigger.cpp
This had triggered an error output for typhoon_h480:
```
ERROR [parameters] get: param 65535 invalid
```
=> camera_trigger: fix getting invalid param

msg/camera_trigger.msg, src/drivers/camera_trigger/camera_trigger.cpp, src/modules/logger/logged_topics.cpp
When enabling the hotshoe feedback via camera capture (setting CAM_CAP_FBACK = 1), the camera trigger module publishes on `camera_trigger_secondary` instead of `camera_trigger`. Yet, MAVlink is still listening to the ‘camera_trigger’ message and as a result, the MAVLink message is never sent. 
Removed camera_trigger_secondary since for multiple camera solutions we need a better mechanism.
=> camera_trigger: remove camera trigger secondary

src/modules/flight_mode_manager/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.cpp, src/modules/flight_mode_manager/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.hpp, src/modules/mc_pos_control/MulticopterPositionControl.cpp
If the drone is sinking really fast (i.e: well above usual maximum descent speed) and if the user switches to an auto mode to recover (RTL or other), the trajectory generator will generate a smooth (from design parameters) that usually creates a too long braking distance. Furthermore, the setpoints are clipped by the velocity controller, creating a hard stop followed by a controlled descent (that looks like an overshoot).
If the drone is falling at a speed above twice the maximum downward speed, the trajectory generator enters an "emergency braking mode" that sets higher acceleration and jerk parameters (9.81m/s2 and 9.81m/s3) until the vertical velocity trajectory reaches 0m/s. After this, it goes back to normal …
=> Add vertical emergency braking in auto mode

Tools/serial/generate_config.py, platforms/common/uORB/uORB_tests/uORBTest_UnitTest.cpp, platforms/nuttx/src/px4/nxp/imxrt/hrt/hrt.c, platforms/nuttx/src/px4/nxp/kinetis/hrt/hrt.c, platforms/nuttx/src/px4/nxp/s32k1xx/hrt/hrt.c, platforms/nuttx/src/px4/stm/stm32_common/hrt/hrt.c, platforms/posix/src/px4/common/drv_hrt.cpp, src/drivers/drv_hrt.h, src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_main.h, src/modules/mavlink/mavlink_receiver.cpp, src/modules/px4iofirmware/controls.c, src/modules/px4iofirmware/px4io.h, src/systemcmds/microbench/test_microbench_hrt.cpp, src/systemcmds/tests/hrt_test/hrt_test.cpp
- hrt_elapsed_time_atomic is not atomic on posix
- other fields like _radio_status_mult need protection as well
I'm also removing `hrt_elapsed_time_atomic` altogether to avoid further problems with that.
=> fix mavlink radio status locking

src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h
Mavlink receiver can't compile if **optical_flow** is not enabled 
Handle optical_flow parameters dynamically
=> updated sens flow parameters to be dynamically handle

src/drivers/px4io/px4io.cpp
There was a wicked race that is most always lost if there is no console.
The Init() registers the pwm0 device but if the task does not run it does not unregister it. (in the case of failure as well). The FS has a inode that is now pointing to a deleted and most likely reclaimed memory. 
So this 
begins a series of Fun that ends in a hardfault
=> px4io:Ensure proper lifecycle of registration of cdev

boards/mro/ctrl-zero-h7-oem/nuttx-config/include/board.h
fix spi pin missmatch PF9=GPIO_SPI5_MOSI_2
Please use PX4 Discuss or Slack to align on pull requests if necessary. You can then open draft pull requests to get early feedback.
Describe problem solved by this pull request
BMI088 doesn't´t start cause the sensor isn´t detected on this bus
Describe your solution
BMI088 gyro and acc now starts properly
Additional context
Board sensors: /etc/init.d/rc.board_sensors
icm20602 #0 on SPI bus 1 rotation 8
bmi088_accel #0 on SPI bus 5 rotation 8
bmi088_gyro #0 on SPI bus 5 rotation 8
icm20948 #0 on SPI bus 1 rotation 8
dps310 #0 on SPI bus 2
=> ctrl-zero-h7-oem spi 5 fix - Update board.h

ROMFS/px4fmu_common/init.d/rc.vtol_defaults, src/modules/mc_hover_thrust_estimator/MulticopterHoverThrustEstimator.cpp, src/modules/mc_hover_thrust_estimator/MulticopterHoverThrustEstimator.hpp, src/modules/mc_hover_thrust_estimator/hover_thrust_estimator_params.c, src/modules/mc_hover_thrust_estimator/zero_order_hover_thrust_ekf.cpp, src/modules/mc_hover_thrust_estimator/zero_order_hover_thrust_ekf.hpp
VTOL planes are getting lift from the wing when flying in MC mode at high speed. They (and some other drones) also get extra drag when climbing and descending at high speed, corrupting the hover thrust estimate (HTE).
To avoid this, two speed thresholds (vertical and horizontal) are defined above which the sensitivity of the estimator is decreased by linearly increasing the observation noise.
Replayed on a log having this issue using https://github.com/Auterion/Flight_Control_Prototyping_Scripts/pull/10
Before this PR, the update was skipped if |vz| > 2m/s:
With this PR, the measurement noise is increased (`_PARAM_HTE_VXY_THR` set to 2m/s) so the estimate isn't biased:
=> HTE: decrease sensitivity with speed

src/modules/mavlink/streams/CAMERA_TRIGGER.hpp
By adding the sequence number we can avoid double triggering due to command retransmissions. This is according to the mavlink spec for MAV_CMD_IMAGE_START_CAPTURE.
=> mavlink: avoid double trigger using sequence

boards/ark/can-gps/debug.cmake, platforms/common/uORB/uORBDeviceMaster.cpp
This helps to see roughly how much data is moving through the system, for example sizing things for real time publish subscribe.
=> uorb top report total publication rate

src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h
This expands `mavlink status` to include simple statistics for each received messages (per mavlink component per mavlink instance). It's helpful for remote debugging/inspecting more complex systems with multiple mavlink components.
It's only activated by running `mavlink status`, otherwise the per message statistics aren't tracked and the small buffer isn't allocated.
=> mavlink: add simple incoming message stats to status

src/modules/mavlink/mavlink_params.c
just fix a typo in a parameter description
=> fix typo in comment

src/modules/ekf2/EKF2Selector.cpp
This additional condition was primarily intended to aggressively catch estimator failures if/when the primary attitude stops publishing, but so far it mainly produces false positives when disarmed and bench testing (parameter changes, etc).
=> ekf2: selector remove special timeout condition

boards/nxp/ucans32k146/nuttx-config/include/board.h, boards/nxp/ucans32k146/src/can_boot.c, platforms/nuttx/src/canbootloader/include/board.h
UCANS32K146-01 uses a CAN tranceiver with ERR pin indicating, CAN tranceiver HW failure e.g. short to ground
This PR adds the functionality of the ERR pin to the UCANS32K146 bootloader and does a HW self test. If an error occurs it indicates an error by the new `hardware_failure` led state
Tested on new UCANS32K146-01 revision, older revisions of this board are detected automatically and do not run this self-test.
=> UCANS32K146-01 Add CAN tranceiver self test

platforms/nuttx/src/px4/nxp/k66/include/px4_arch/micro_hal.h, platforms/nuttx/src/px4/nxp/rt106x/include/px4_arch/micro_hal.h, platforms/nuttx/src/px4/nxp/s32k14x/include/px4_arch/micro_hal.h, src/modules/logger/log_writer_file.cpp
This prevents the logger from reporting and ERROR on systems without hardfault logging
=> Without hardfault logging: Avoid "ERROR:Failed to register ULog file to the hardfault handler"

platforms/nuttx/src/px4/stm/stm32h7/px4io_serial/px4io_serial.cpp
For testing https://github.com/PX4/NuttX/pull/164 while waiting for upstream to take ups second commit.
=> stm32h7:px4io_serial use TRBUFF

src/modules/mavlink/mavlink_parameters.cpp
Removing (seemingly) unused char array and `strncpy` in parameter `send_untransmitted()`
Removed lines
=> Remove unused strncpy in parameter send_untransmitted

Tools/gazebo_sitl_multiple_run.sh
Hi,  
I found a problem when multiple vehicle run using gazebo_sitl_multiple_run.sh like below.
```
Tools/gazebo_sitl_multiple_run.sh -s "rover:2"
Tools/gazebo_sitl_multiple_run.sh -s "rover:2,iris:2"
```
To solve this problem, I update the environment value (PX4_SIM_MODEL) for each vehicle. 
However, I'm not sure that the solution is optimal. 
Could you check this solution?
=> fix the problem related to the sitl multiple vehicle environment

.ci/Jenkinsfile-hardware
This is a quick attempt to stop the builds from starving the Jenkins master.
=> Jenkins: reduce build agent cpu share

posix-configs/SITL/init/test/test_imu_filtering, src/modules/gyro_fft/GyroFFT.cpp, src/modules/gyro_fft/GyroFFT.hpp, src/modules/gyro_fft/parameters.c, src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
On real vehicles the tracked FFT peaks can be a bit erratic. This PR updates the detection in `gyro_fft` to first require a much stronger peak (SNR 10 -> 15db) before initially tracking, but then to continue tracking that threshold is reduced (SNR 5 db).
- prior to takeoff (first half of log) there are false positives
- during flight real frequency peaks (that correspond to motor RPM) are detected, but intermittently lost which increases the number of necessary resets in the bank of notch filters
=> gyro_fft: require higher SNR for initially tracking a peak

src/lib/parameters/parameters.cpp, src/lib/parameters/tinybson/tinybson.cpp
Errors:
```
ERROR [parameters] param import failed (-1) attempt 1, retrying
ERROR [parameters] param import failed (-1) attempt 2, retrying
ERROR [parameters] param import failed (-1) attempt 3, retrying
ERROR [parameters] param import failed (-1) attempt 4, retrying
ERROR [param] importing from '/fs/mtd_caldata' failed (-1)
```
=> param import: avoid printing errors for erased flash devices

src/modules/commander/state_machine_helper.cpp
By default we would leave the LAND failsafe as soon as a link comes back. With this change, we switch to the LAND failsafe like a proper mode change, immediately disabling the failsafe as such.
This is as the same that is done for RTL in fact.
This is not optimal but a workaround for the problem where we switch out of failsafe right on landing and then discover takeoff again and start looping through it again and again without ever disarming.
=> commander: make LAND failsafe stick

src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp, src/modules/flight_mode_manager/tasks/AutoMapper/FlightTaskAutoMapper.cpp, src/modules/flight_mode_manager/tasks/AutoMapper/FlightTaskAutoMapper.hpp, src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.cpp, src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.hpp, src/modules/flight_mode_manager/tasks/Utility/StickYaw.cpp, src/modules/flight_mode_manager/tasks/Utility/StickYaw.hpp, src/modules/flight_mode_manager/tasks/Utility/Sticks.cpp
Feature request to have horizontal input via sticks in the final landing approach of land mode and RTL without switching out of the autonomous mode (which is default now through RC override).
- Use the stick mapping class from FlightTaskManualAcceleration in FlightTaskAutoMapper to adjust the setpoints based on stick input during the final landing approach
- Work around issues/corner cases:
- velocity smoothing overwriting the setpoints but not being happy (flyaway, oscillations) when they are not overwritten by the mapper again
- snapping back to the original land position despite input
- not reaching the exact land position without input e.g. exactly home in RTL
- snapping back to the previous amended land …
=> Add horizontal and yaw nudging for multicopter final descent

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
Currently, in manual Position flight mode the roll setpoint is the unfiltered stick input. I think it would be nice to limit the rate of change, and would actually expect that the same slew rate is used as in Auto flight mode (FW_L1_R_SLEW_MAX)
Use FW_L1_R_SLEW_MAX also in Position mode.
Are we fine to have the roll slew rate in all modes of the FW Position controller? Because then we could add it instead just before the attitdue setpoint is published (https://github.com/PX4/PX4-Autopilot/blob/fef2c4339577c1bccd33c649d63a4a31c8005ef7/src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp#L1793). It would e.g. also be in Altitude flight mode then. …
=> FW Position control: add roll slewrate also in manual Position flight mode

platforms/common/px4_work_queue/ScheduledWorkItem.cpp, platforms/common/px4_work_queue/WorkItem.cpp, platforms/common/px4_work_queue/WorkQueueManager.cpp
The new `mc_autotune_attitude_control` pushed us over the edge.
=> px4_work_queue: adjust status formatting to accommodate longer names (eg mc_autotune_attitude_control)

src/modules/vtol_att_control/tailsitter.cpp, src/modules/vtol_att_control/tiltrotor.cpp, src/modules/vtol_att_control/vtol_att_control_main.cpp
VTOL transition timeout (abort transition to fixed-wing after a certain time is over) was only enabled for standard VTOL. 
Enable it also for Tiltrotor and Tailsitter.
SITL tested.
For Quadchute in general: it would be nice to be able to specify behavior after a it (Hold, RTL, Land, ..).
=> VTOL: add transition timeout also to Tailsitter and Tiltrotor

src/modules/ekf2/EKF/estimator_interface.cpp
Converting a uint64 time to float and back will start producing errors over time as the gaps between consecutive integers represented as float32 increase. See https://github.com/PX4/PX4-Autopilot/pull/18358 for more detail.
=> ekf2: avoid uint64 timestamp conversion to float

.github/workflows/checks.yml, .github/workflows/clang-tidy.yml, .github/workflows/compile_linux.yml, .github/workflows/compile_linux_arm64.yml, .github/workflows/compile_macos.yml, .github/workflows/compile_nuttx.yml, .github/workflows/compile_nuttx_cannode.yml, .github/workflows/deploy_all.yml, .github/workflows/mavros_mission_tests.yml, .github/workflows/mavros_offboard_tests.yml, .github/workflows/sitl_tests.yml
On GitHub Actions our cache hit rate is quite low due to many of the caches being evicted even before the first possible use.
=> GitHub actions ccache improvements

src/lib/mathlib/math/filter/AlphaFilter.hpp, src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp, src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.hpp
We realized that some drones with oscillations generated by the rate feedback loop had less problems when increasing the cutoff frequency of the d-term filter (or by removing it completely). For a 2nd order LPF, the cutoff needs to be carefully set to removing enough noise while not adding too much lag to the signal; if too much lag is added, the derivative part of the rate loop can become unstable and the drone oscillates.
After some discussion with @priseborough it seems that a 1st order LPF is usually enough to remove the noise generated by the differentiation of the signal while (which is a 1st order hpf) without removing too much phase (i.e.: less lag). Having a maximum phase lag of 90 degrees, a 1st order …
=> Improved stability of D-term in the rate controller

src/modules/vtol_att_control/vtol_type.cpp
Currently the PWM ramp down is only called once, as afterwards _main_motor_state = VALUE and set_motor_state() is not called anymore.
Always call set_motor_state() if _main_motor_state = VALUE.
flight tested
We only used it for ramping down the alternative motor(s) during front transition currently btw.
=> vtol_type: fix set_motor_state() for motor_state::VALUE

src/lib/parameters/param_translation.cpp, src/modules/vtol_att_control/standard_params.c, src/modules/vtol_att_control/tiltrotor.cpp, src/modules/vtol_att_control/vtol_att_control_main.cpp, src/modules/vtol_att_control/vtol_att_control_main.h, src/modules/vtol_att_control/vtol_att_control_params.c, src/modules/vtol_att_control/vtol_type.cpp, src/modules/vtol_att_control/vtol_type.h
- clean up logic
- allow positive pitch offsets in hover
- add params for min pitch during not-Land and Land modes
Problem: For VTOLs we want a positive pitch angle while hovering to increase hover efficiency and reduce motor loads in high wind. When descending that can though end up being a problem, as in heavy wind the lift produced by the winds may be enough to not letting it descend even on minimal thrust.
This PR first of all changes the logic behind the pitch setpoint when pusher assist (tilt-forward for tiltrotor) is enabled: Instead of allowing some pitch down via VT_DWN_PITCH_MAX, it will not pitch down at all to create a positive force in x, but use the pusher assist. VT_DWN_PITCH_MAX is removed, and two …
=> VTOL: rework forward actuation assist

src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/commander/commander_params.c
This can be used to notify the user if the current wind speed is getting close to the vehicle limits. 
Publishes periodically (max every 1 min) a warning if the current wind estimate
is above COM_WIND_WARN.
SITL tested.
We need to improve the QGC user notification for  `events::Log::Warning`, or add add things like this to  `events::Log::Critical` such that it appears in the pop up (though it for me belongs to the warning category relating to https://mavlink.io/en/messages/common.html#MAV_SEVERITY).
=> Commander: add wind speed warning

src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp, src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.hpp
Get rid of derivative spikes when navigator is continuously updating the yaw setpoint in the triplet for a POI but is running at a lower rate.
I added a filter for the derivative but for the feed-forward only.
I considered:
- filtering the derivative `dyaw` also for the absolute yaw setpoint generation
- filtering the absolute yaw
but both lead to inherent oscillations that have adverse effects on normal mission flying.
The proper solution is to generate that yaw setpoint with high rate in the flight task and have the triplet just guide to the next waypoint at low rate.
SITL testing with a mission that contains a POI. It's easily reproducable. …
=> FlightTaskAuto: hotfix POI yawspeed feed-forward spikes

src/modules/logger/CMakeLists.txt
- ${MAX_CUSTOM_OPT_LEVEL} is -O2 on boards that aren't flash constrained
On px4_fmu-v5 this saves roughly 1.4% CPU in exchange for about 7 kB of flash.
``` Console
1101 logger                        404  4.867  2676/ 3648 230 (230)  w:sem  4    # master
1101 logger                       2276  3.481  2772/ 3648 230 (230)  w:sem  4    # PR
```
=> logger: increase optimization to ${MAX_CUSTOM_OPT_LEVEL}

src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp, src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.hpp
When commanding an Orbit at a certain altitude, the vehicle does not go to the commanded altitude but stays at the current altitude.
The problem stemmed from the fact that the `FlightTaskOrbit` inherited from `FlightTaskManualAltitudeSmoothVel`. The parent class took ownership over the z-velocity, but not position. So in Orbit approach, the position setpoints set by `FlightTaskOrbit` were ignored. This PR changes the inheritance that `FlightTaskOrbit` directly inherits from `FlightTaskManualAltitude`. All smoothing is done directly in `FlightTaskOrbit`.
- For Orbit approach, the `PositionSmoothing` library smoothes the approach based on position target
- While in Orbit, the `VelocitySmoothing` library smoothes the …
=> Fix Orbit altitude not being followed

boards/modalai/fc-v2/src/hw_config.h
https://github.com/PX4/PX4-Bootloader/blob/dce800bc455703e7132680eff45d5401eec945c3/board_types.txt#L34
@modaltb
=> boards: modalai_fc-v2 fix bootloader board type

msg/CMakeLists.txt, msg/failure_detector_status.msg, msg/vehicle_imu_status.msg, msg/vehicle_status.msg, src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/commander/commander_params.c, src/modules/commander/failure_detector/FailureDetector.cpp, src/modules/commander/failure_detector/FailureDetector.hpp, src/modules/commander/failure_detector/failure_detector_params.c, src/modules/commander/state_machine_helper.cpp, src/modules/commander/state_machine_helper.h, src/modules/logger/logged_topics.cpp, src/modules/sensors/vehicle_imu/VehicleIMU.cpp, src/modules/sensors/vehicle_imu/VehicleIMU.hpp
1. A lot of new users are not aware that their system has a lot of vibrations due to imbalanced propellers
2. A drone with a damaged propeller should usually not continue its mission like if nothing happened.
Assuming that the rotors are spinning in the xy-plane, a metric based on the variance of accelerometer readings is used to detect an imbalanced rotor using the following formula:
`Imbalanced propeller detected if (var(x) + var(x) - var(z)) > threshold`
We tried other methods using the ratio between XY and Z, but the one used in this PR gave the best results.
Tested on many multirotors and standard VTOL planes.
The threshold …
=> Add imbalanced propeller check to failure detector

ROMFS/px4fmu_common/init.d-posix/rcS, ROMFS/px4fmu_common/init.d/rc.mc_apps, ROMFS/px4fmu_common/init.d/rc.vtol_apps, platforms/nuttx/init/imxrt/rc.board_arch_defaults, platforms/nuttx/init/stm32f7/rc.board_arch_defaults, platforms/nuttx/init/stm32h7/rc.board_arch_defaults, src/modules/mc_autotune_attitude_control/mc_autotune_attitude_control_params.c
- only enabled by default on boards that aren't memory constrained
=> mc_autotune_attitude_control: add new MC_AT_EN parameter to enable

src/modules/mavlink/mavlink_receiver.cpp
The SERIAL_CONTROL MAVLink message now contains a target_system and target_component field that we should check.
Without this we might be answering to a command on the network that is meant for another system.
Also see: https://github.com/mavlink/mavlink/pull/1725
=> mavlink: Check target for mavlink shell

platforms/posix/cmake/sitl_target.cmake
Closes #17691
This is far from a perfect solution, it simply tries to offer a minimum of flexibility when deploying automated builds.
This allows the possibility of overriding the parallelism when building sitl_gazebo, which is memory intensive and can result in oom ( see #17691 , other issues have been closed in the past but not actually solved: #14747 #14430  ). This is especially the case as new CPUs have more and more logical cores, but systems still generally have 16GB or less of RAM. In my 16GB system, `master` currently uses 14 parallel jobs which results in oom and with no way of resolving it since it is hardcoded to N-2 jobs in `ExternalProject_Add`.
Example of usage: `BUILD_CORES=8 DONT_RUN=1 make px4_sitl_default gazebo`
An important caveat with this solution is that it only …
=> Allow overriding sitl_gazebo build_cores with an environment variable

msg/offboard_control_mode.msg, src/modules/commander/Commander.cpp, src/modules/mavlink/mavlink_receiver.cpp
Sending actuator setpoints directly from a onboard computer provides a useful way to execute open loop manuevers which is useful for system identification.
While previous to https://github.com/PX4/PX4-Autopilot/pull/16739  it was possible to send actuator commands using the `https://mavlink.io/en/messages/common.html#SET_ACTUATOR_CONTROL_TARGET` mavlink message, this is no longer working since it is not understood as a valid offboard mode.
This commit adds a case for adding offboard actuator commands in the offboard mode
Tested with Gazebo SITL no lockstep target
```
make px4_sitl_nolockstep gazebo
```
As can be observed in the log, actuator setpoint to elevator (output 7) is increased as …
=> Enable offboard actuator setpoints

src/lib/sensor_calibration/Magnetometer.hpp, src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_messages.cpp, src/modules/mavlink/streams/MAG_CAL_REPORT.hpp
Initial support for Mavlink MAG_CAL_REPORT (http://mavlink.io/en/messages/common.html#MAG_CAL_REPORT).
Currently only sends calibration out on parameter changes, but later we can integrate it with the actual calibration user interaction.
https://github.com/PX4/PX4-Autopilot/pull/18421#issuecomment-945908819
=> mavlink: initial support for MAG_CAL_REPORT stream

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
Fixes https://github.com/PX4/PX4-Autopilot/issues/18573
=> FW position controller: only allow switching to AUTO_ALTITDUE or AUTO_CLIMBRATE if  pos_sp_curr_valid

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
Fixes https://github.com/PX4/PX4-Autopilot/issues/18576
While the FW position controller mode was changing, the throttle was not changing accordingly
This seems to be a regression introduced by https://github.com/PX4/PX4-Autopilot/pull/18340
- Before PR: https://logs.px4.io/plot_app?log=4f360063-83eb-43bd-81f1-0749f89a9e4e
- After PR: https://logs.px4.io/plot_app?log=15f471bd-2a86-4855-9206-ce111cd0b393
=> Handle setpoint types properly in fw position controller

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
For fixed wing position control, the position setpoints are overwridden to maintain a certain heading when the vehicle is in transition mode. There are a lot of vtol special cases being handled in various parts of the code. This special case is currently handled inside each auto mode function, which results in a lot of repeated code.
This commit pulls out the vtol transition case handling outside the controller
We might want to limit transition as a standalone position controller mode so we can handle this case more explicitly.
Tested in SITL Gazebo with the standard vtol: https://logs.px4.io/plot_app?log=c70f017a-ec18-490b-91d8-c466f4f7afc5
**Additional …
=> Fixedwing Pos Control: Handle vehicle transition waypoints outside controllers

src/modules/commander/state_machine_helper.cpp
This was missed in https://github.com/PX4/PX4-Autopilot/pull/17547.
=> state_machine_helper: add place holder in array  nav_state_names for removed LANDGPSFAIL mode

Tools/setup/requirements.txt
Since https://github.com/PX4/PX4-Autopilot/pull/18238 the python module `future` seems to have become a requirement. Without it I couldn't build anymore.
I'm adding future to the setup script requirements. After running `python3 -m pip install --user -r Tools/setup/requirements.txt` with this change it builds fine.
Ran into this problem on Ubuntu 20.04 with Python 3 (only) and used the change to fix it which worked.
=> setup/python requirements: add future module

posix-configs/SITL/init/test/test_imu_filtering, src/modules/gyro_fft/GyroFFT.cpp, src/modules/gyro_fft/GyroFFT.hpp, src/modules/gyro_fft/parameters.c, src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
The FFT frequency peak detection isn't great across all platforms by default, but at least this helps by giving you a bit more control to target it between potentially relevant frequencies (IMU_GYRO_FFT_MIN/MAX) .
=> gyro_fft: add IMU_GYRO_FFT_SNR parameter and limit noise floor to configured range (IMU_GYRO_FFT_MIN/MAX)

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
There was a bug introduced in the takeoff logic for fixedwing vehicle takeoff
This was introduced by a rebase between https://github.com/PX4/PX4-Autopilot/pull/18578 and https://github.com/PX4/PX4-Autopilot/pull/18503
Tested in SITL
```
make px4_sitl gazebo_plane
```
=> Fix fixedwing takeoff

src/modules/sensors/CMakeLists.txt
sensors module only works on uORB, it doesn't link to drivers__device
=> Don't link sensors module to drivers__device

platforms/nuttx/src/px4/stm/stm32_common/hrt/hrt.c, src/drivers/drv_hrt.h, src/lib/perf/perf_counter.cpp
Add interface functions for fetching latency buckets and counters and use
those in perf_counter.cpp. This cleans up the usage of perf counters, when variables defined in hrt_drv are not referenced directly from perf.
This also enables implementing kernel-userspace interface for those for
nuttx protected/kernel build.
=> hrt: Add interface functions for latency counters

msg/vehicle_constraints.msg, src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp, src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.hpp, src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.cpp, src/modules/flight_mode_manager/tasks/ManualPosition/FlightTaskManualPosition.cpp, src/modules/flight_mode_manager/tasks/ManualPosition/FlightTaskManualPosition.hpp, src/modules/flight_mode_manager/tasks/ManualPositionSmoothVel/FlightTaskManualPositionSmoothVel.cpp, src/modules/mc_pos_control/MulticopterPositionControl.cpp, src/modules/mc_pos_control/MulticopterPositionControl.hpp, src/modules/mc_pos_control/mc_pos_control_params.c
4 years ago with the original mission implementation there was the need to set a position setpoint far away and just clamp the velocity in the position controller. This solution had a lot of flaws because the vehicle would always travel at the maximum speed and so it was superseded by the smooth mission implementation with the jerk optimized trajectory. The interface to dynamically switch the horizontal speed limit in the controller got obsolete and was only there because of the remaining usages in the flight task hierarchy.
Current symptom: When flying a mission that contains velocities above the cruise speed [`MPC_XY_CRUISE`](https://docs.px4.io/master/en/advanced_config/parameter_reference.html#MPC_XY_CRUISE) the velocity gets clamped …
=> vehicle_constraints: remove deprecated speed_xy constraint

src/lib/drivers/smbus_sbs/CMakeLists.txt
This is causing errors in some of my branches; I guess that in the master the linker language comes implicitly from somewhere else.
CMake can't detect the linker language from this library as it is header-only; it should be explicitly set.
=> smbus_sbs: Define linker language for a header-only library

Tools/check_submodules.sh
This is an attempt to handle the failure when a submodule reference within another submodule changes.
=> Tools/check_submodules.sh: perform submodule sync again after first update to reach nested submodules

src/modules/mavlink/mavlink_main.cpp
The `_MAV_PAYLOAD` macro casts the value to a `char*`. Some compilers treat `char` as signed, so we were getting negative system and component ids if the id was >= 128. This caused later comparisons to fail which resulted in messages not being forwarded.
=> mavlink: fix forwarding to target id >= 128

src/modules/mavlink/mavlink_messages.cpp, src/modules/mavlink/streams/GPS_RTCM_DATA.hpp
In the current code, MAVLINK message stream of GPS_RTCM_DATA is not available / cannot be seen from the autopilot, at least when tested with QGroundControl, as shown in the image below.
The GPS_RTCM_DATA is streamed via uORB from the base to the rover, under the `gps_inject_data` uORB message, as shown in the image below.
The new addition is to stream the `gps_inject_data` uORB messages as GPS_RTCM_DATA to the autopilot, as shown in the image below.
The proposed implementation is adding the initial structure for the GPS_RTCM_DATA stream message for MAVLink.
The test was done with Pixhawk 4 running on DJI F550 Hex platform.
=> Adding MAVLink message stream of GPS_RTCM_DATA to Autopilot

src/lib/version/CMakeLists.txt, src/lib/version/version.h, src/systemcmds/ver/ver.c
```
ver all
HW arch: PX4_FMU_V5
HW type: V500
HW version: 0x00000000
HW revision: 0x00000000
FW git-hash: fc19d173bfcbe0ae81077f7d8df403e246c7a99b
FW version: 1.12.3 0 (17564416)
FW git-branch: board_label_ver
OS: NuttX
OS version: Release 10.0.0 (167772415)
OS git-hash: 80b730cdb35570b3aa8b0062b3fe12acc37e9bf2
Build datetime: Nov 11 2021 10:42:18
Build uri: localhost
Build variant: default
Toolchain: GNU GCC, 9.3.1 20200408 (release)
PX4GUID: 000200000000353436333138511900240029
MCU: STM32F76xxx, rev. Z
```
=> ver: print PX4_BOARD_LABEL for 'ver all'

boards/matek/h743-slim/src/spi.cpp, src/drivers/imu/invensense/mpu6000/MPU6000.cpp, src/drivers/imu/invensense/mpu6000/MPU6000.hpp
- Board: Fixed DRDY pin from PB1 to PB2
- MPU6000: Added 10us delay for R/W of slow registers
=> Fixes for MPU6000 and MatekH743-slim board

src/modules/commander/Commander.cpp
Be course of the numerical computing error . The normalization of the quaternion can't always equal to 1 precisely. It could occasionally trigger the error"attitude estimate no longer valid".
enlarge the threshold from FLT_EPSILON to 1e-6f.
It has been tested. The solution keeps it silence.
none
=> fix the quaternion normalization issue

src/modules/gyro_calibration/GyroCalibration.cpp, src/modules/gyro_calibration/GyroCalibration.hpp
If a sensor goes away and returns for some reason we only want to use fresh data once it's fully back online.
=> gyro_calibration: reset on any sensor timeout

src/modules/commander/Commander.cpp
This otherwise leads to an unnecessary amount of acks which can in turn overflow
the orb queue.
=> Commander: Don't ack gimbal commands

src/drivers/camera_capture/camera_capture.cpp, src/drivers/dshot/DShot.cpp, src/drivers/px4io/px4io.cpp, src/drivers/rpm/pcf8583/PCF8583.cpp, src/drivers/uavcan/actuators/esc.cpp, src/lib/mixer_module/mixer_module.cpp, src/lib/tecs/TECS.hpp, src/modules/airspeed_selector/airspeed_selector_main.cpp, src/modules/angular_velocity_controller/AngularVelocityController.cpp, src/modules/camera_feedback/CameraFeedback.cpp, src/modules/ekf2/EKF2.cpp, src/modules/fw_att_control/FixedwingAttitudeControl.cpp, src/modules/fw_autotune_attitude_control/fw_autotune_attitude_control.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/gyro_fft/GyroFFT.cpp, src/modules/logger/logged_topics.cpp, src/modules/logger/logged_topics.h, src/modules/mag_bias_estimator/MagBiasEstimator.cpp, src/modules/mavlink/mavlink_main.cpp, src/modules/mc_autotune_attitude_control/mc_autotune_attitude_control.cpp, src/modules/mc_pos_control/MulticopterPositionControl.cpp, src/modules/mc_rate_control/MulticopterRateControl.cpp, src/modules/temperature_compensation/TemperatureCompensationModule.cpp, src/modules/vtol_att_control/vtol_att_control_main.cpp
The current practice of adding topics to the default set isn't scalable, as it affects all setups.
By making sure topics are advertised on init, logger can just discard topics that don't exist. This does not work for all topics, so topics are specifically marked as optional. It can be extended to more topics later on though.
This reduces the list of topics by ~35 on a pixracer configured as quad, and reduces RAM usage by ~1KB.
=> logger: introduce optional topics

msg/battery_status.msg, src/drivers/batt_smbus/batt_smbus.cpp, src/drivers/smart_battery/batmon/batmon.cpp, src/drivers/uavcan/sensors/battery.cpp, src/drivers/uavcan/sensors/cbat.cpp, src/drivers/uavcan_v1/Subscribers/legacy/LegacyBatteryInfo.hpp, src/lib/battery/battery.cpp, src/lib/battery/battery.h, src/modules/mavlink/streams/BATTERY_STATUS.hpp
It's useful to show the user an estimate how much longer he can still fly until the battery is empty.
This estimate will also be required to make an informed decision when to return to home automatically to be able to land safely before the battery is empty.
Calculate the remaining flight time based on a very heavily filtered "average" current consumption and the configured battery capacity.
The algorithm was tested on an old version of PX4 this port to the new version wasn't specifically tested yet. I suggest we check logs that fly with this functionality to see if the flight time is accurate.
This is based on the refactor …
=> Estimate remaining flight time

src/modules/ekf2/EKF2.cpp
This avoids a param export the first time a vehicle gets a GPS fix.
=> ekf2: only save mag declination if changed

src/modules/mavlink/mavlink_ftp.cpp, src/modules/mavlink/mavlink_ftp.h
As these files are kept in RAM, it could just fill up the RAM.
Fixes https://github.com/PX4/PX4-Autopilot/issues/18651
=> mavlink_ftp: disallow writes outside of /fs/microsd under NuttX

src/modules/navigator/mission_block.cpp
Navigator sets a 3D waypoint for takeoffs that includes a heading setpoint. When EKF resets the yaw / heading during takeoff, the existing yaw setpoint is outdated and wrong and will never be reached. For this reason the flight task `FlightTaskAuto` is currently not even trying to track yaw during takeoff: https://github.com/PX4/PX4-Autopilot/blob/4a66c8c4c479a1780cbbff45a5e0c400b2cb3517/src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp#L303-L310
This PR implements a similar workaround for mission_block.cpp, allowing it to ignore the yaw setpoints during takeoffs of Multicopters. The "proper" fix would be to modify Navigator such that a heading reset is handled correctly and the waypoint as well as the resulting yaw setpoint are updated.
=> mission_block: always accept yaw in MC takeoff

msg/vehicle_local_position.msg, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF2.cpp, src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp, src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.cpp, src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.hpp, src/modules/flight_mode_manager/tasks/ManualAcceleration/FlightTaskManualAcceleration.cpp, src/modules/flight_mode_manager/tasks/ManualAltitude/FlightTaskManualAltitude.cpp, src/modules/flight_mode_manager/tasks/Utility/StickYaw.cpp, src/modules/flight_mode_manager/tasks/Utility/StickYaw.hpp
During the early takeoff phase, the drone is often affected by local magnetic anomalies (e.g.: steel reinforced concrete) and this makes the estimated heading move a bit. At 1.5m, when EKF2 triggers a yaw reset, the heading is then stable (after a quick re-convergence of the Z gyro bias). Controlling the heading of the drone during that phase leads to some small unwanted corrections and an offset compared to the initial takeoff orientation.
Leave the yaw attitude loop open (control yaw rate only) until reaching the final yaw alignment convergence. After the in air mag reset, an additional 1s is given to the estimate to stabilize its estimate.
The logic is disabled if no mag is used.
In position mode, the rotation …
=> Close yaw loop after final mag alignment only

src/lib/mathlib/math/filter/AlphaFilter.hpp, src/lib/mathlib/math/test/AlphaFilterTest.cpp, src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
Follows the discussion in https://github.com/PX4/PX4-Autopilot/pull/18364#pullrequestreview-795083096
Setting the filter with incorrect values disables it without notifying the user of that filter. 
This PR is an attempt to make clear when to disable the filter on the user side by checking the cutoff parameter and the return value of the setter.
Added unit test
@dagar If you're fine with that method, I can also do the same modification for the other filters.
=> Gyro filters: explicitly disable filter when cutoff <= 0

src/modules/ekf2/EKF2Selector.cpp
In some cases, the selected EKF instance has some fusion problems (e.g.: due to yaw errors) and another fully healthy instance is available. However, if the selected estimator does not report itself unhealthy (e.g.: when trying to recover, waiting for a reset timeout, ...), it the selector takes too long to react.
Example of log investigated with @priseborough : https://review.px4.io/plot_app?log=65558b78-35d9-4118-85a5-8ca7c9052052
Looking at the combined test ratio, that selected instance (3) was obviously bad and another one was available:
Inside the selector, use the combined test ratio to declare an EKF instance unhealthy to request a switch to a better instance.
=> Ekf2Selector: declare filter unhealthy when high test ratio

src/modules/flight_mode_manager/FlightModeManager.cpp, src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp, src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.hpp, src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.hpp
Preparation to be able to tear apart FlightTaskAuto into the different modes like Takeoff, RTL, Mission, ...
In #18618 and #18647 I merged 3 classes together. Now that everything is together in `FlightTaskAuto` I started to simplify it. I keep the changes easy to review such that it doesn't end up in a huge pr that is hard to look at and just generates conflicts.
It's all pure refactoring and moving things around except for small order changes in the setpoint preparation switch case e.g. `WaypointType::velocity`.
=> FlightTaskAuto: refactor reducing number of methods

Tools/px4moduledoc/srcparser.py, platforms/common/i2c_spi_buses.cpp, platforms/common/include/px4_platform_common/i2c_spi_buses.h, platforms/common/include/px4_platform_common/spi.h, platforms/common/module.cpp, platforms/common/spi.cpp
Make possible to define chip-select pin for internal SPI.
By defining chip-select pin, it's possible to start specific SPI device only.
This allows to have several same type of sensors on the same bus with different orientation.
=> Improve SPI bus implementation

src/modules/commander/Commander.cpp
With a rover that supports driving forward and backward the stick is usually mapped to stop in the center so it does not make sense to only allow arming in full reverse stick position.
Do not force the stick to be in the lowest position for a rover in manual mode.
Ideally this would be decided in the rover manual mode but until we have that it needs to be allowed in commander.
We successfully used this change on a rover and armed it through the ground station while the stick was not in full reverse position.
=> Commander: Allow arming a rover with the throttle stick in the middle

src/modules/gyro_fft/CMakeLists.txt
This PR adds initial support native compilation on apple silicon (M1) macos. 
Apple is moving to their own arm64 based processor architecture. While at the moment one can run PX4 sitl perfectly fine in x86 emulation on those machines, having it running natively is more desirable. 
Two things are addressed:
- Submodule for jmavsim set to https://github.com/PX4/jMAVSim/pull/132. This version of jmavsim contains native OpenGL binaries for arm64, this makes it run on M1
- The gyro_fft module uses CMSIS. CMSIS has a lot of functions with inline arm 32-bit assembly. When compiling on x86 or any non-dsp and non-neon arm processor (such as the M1), none of these functions ever get used. This is what allows (presumably) to …
=> Initial Apple M1 support
