PX4/PX4-Autopilot

.github/workflows/metadata.yml, Jenkinsfile
dev guide got merged with the user guide.
=> Jenkinsfile: remove dev-guide metadata deployment

src/lib/controllib/BlockLowPass.hpp, src/modules/mc_pos_control/MulticopterPositionControl.hpp
Just saw these small things while reviewing #15863
=> Really small refactor, Block derivative, mc_pos_control comment

ROMFS/px4fmu_common/init.d-posix/rcS
=> ROMFS: posix rcS set EXTRA_MIXER_MODE

src/lib/airspeed_validator/AirspeedValidator.cpp, src/lib/airspeed_validator/AirspeedValidator.hpp, src/modules/airspeed_selector/airspeed_selector_main.cpp, src/modules/airspeed_selector/airspeed_selector_params.c
- data missing check was not working anymore (e.g. detect disconnected sensor was not working)
- clean up
- fix data missing check
- improve error messaging
- improve innovation checks (logic in code was different from what was defined in the parameter description)
- improve parameter description and make logic consistent with what's specified there
SITL tested (tried to cover most of the functionalities), basic real vehicle flight testing as well. 
Not yet tested on a multiple airspeed sensor setup.
=> Airspeed Selector fixes and improvements

boards/cuav/can-gps-v1/default.cmake, boards/cuav/can-gps-v1/init/rc.board_defaults, boards/cuav/can-gps-v1/nuttx-config/include/board.h, boards/cuav/can-gps-v1/nuttx-config/include/board_dma_map.h, boards/cuav/can-gps-v1/src/CMakeLists.txt, boards/cuav/can-gps-v1/src/board_config.h, boards/cuav/can-gps-v1/src/boot_config.h, boards/cuav/can-gps-v1/src/led.cpp, msg/led_control.msg, platforms/nuttx/src/px4/common/srgbled/CMakeLists.txt, platforms/nuttx/src/px4/common/srgbled/srgbled.cpp, platforms/nuttx/src/px4/stm/stm32_common/srgbled_dma/CMakeLists.txt, platforms/nuttx/src/px4/stm/stm32_common/srgbled_dma/srgbled_dma.cpp, src/drivers/drv_neopixel.h, src/drivers/lights/neopixel/CMakeLists.txt, src/drivers/lights/neopixel/neopixel.cpp, src/drivers/lights/rgbled_pwm/rgbled_pwm.cpp
Dependant on https://github.com/PX4/NuttX/pull/129 coming in.
=> Add Serial LED Driver to Cuav CAN node GPS (This also fixes the pin map)

README.md
Removed old link from dronecode, and updated link to roadmap board
=> updated roadmap link

ROMFS/px4fmu_common/init.d/rcS, src/drivers/uavcan/CMakeLists.txt, src/drivers/uavcan/beep.cpp, src/drivers/uavcan/beep.hpp, src/drivers/uavcan/uavcan_main.cpp, src/drivers/uavcan/uavcan_main.hpp
Splitting off the UAVCAN beep portion of https://github.com/PX4/PX4-Autopilot/pull/16598 by @gitfishup to bring in immediately while we sort out the safety button architecture.
=> uavcan: add tune_control/beep

src/drivers/drv_pwm_output.h, src/drivers/dshot/DShot.cpp, src/drivers/pwm_out/PWMOut.cpp, src/drivers/px4io/px4io.cpp
Broken out of https://github.com/PX4/PX4-Autopilot/pull/16641.
=> drv_pwm_output.h delete completely unused IOCTLs

src/drivers/uavcannode/CMakeLists.txt, src/drivers/uavcannode/UavcanNode.cpp, src/drivers/uavcannode/indication_controller.cpp, src/drivers/uavcannode/indication_controller.hpp
This allows the LED to "work" on the cuav gps. I am not sure the the best way to facilitate the breath given the LED data from uavcan.  @bkueng any good ideas here?
=> uavcannode:Add Indication Controller

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp, src/drivers/uavcannode/CMakeLists.txt, src/drivers/uavcannode/UavcanNode.cpp, src/drivers/uavcannode/UavcanNode.hpp, src/drivers/uavcannode/UavcanNodeParamManager.cpp, src/drivers/uavcannode/UavcanNodeParamManager.hpp
https://github.com/PX4/PX4-Autopilot/pull/16595 without the extra unused parameters.
=> drivers/uavcannode: Add a simple parameter server (simpler version for merging)

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp
=> px4_work_queue: wq:nav_and_controllers increase stack 1730 -> 1760 bytes

src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
=> sensors: magnetometer preserve original mag cal offset for status message

platforms/nuttx/src/px4/stm/stm32_common/srgbled_dma/srgbled_dma.cpp
=> srgbled_dma:Fix wrong timer init

src/modules/ekf2/EKF2.cpp
Simple checks to make sure ekf2 isn't falling behind any sensor data publications.
=> ekf2: error if unable to copy every sensor publication

msg/sensor_gps.msg, msg/vehicle_gps_position.msg, src/modules/sensors/vehicle_gps_position/VehicleGPSPosition.cpp
Follow up work of https://github.com/PX4/PX4-GPSDrivers/pull/71
=> Add jamming_state to vehicle_gps_position message

src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp, src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.hpp
``` Console
update: 1s, num topics: 169
TOPIC NAME         INST #SUB RATE #Q SIZE
vehicle_magnetometer  0    6   41  1   40 
vehicle_magnetometer  1    4   41  1   40 
```
=> sensors: vehicle_magnetometer respect publication rate limit SENS_MAG_RATE

.vscode/cmake-variants.yaml, ROMFS/px4fmu_common/init.d-posix/rcS, platforms/common/include/px4_platform_common/log.h, platforms/common/px4_log.cpp, platforms/posix/src/px4/common/main.cpp, src/systemcmds/param/param.cpp
Minor change to prevent interlaced output.
=> platforms: px4 log build string then print (fputs)

.ci/Jenkinsfile-hardware
4 kHz is expensive with 3 IMUs.
=> Jenkins hardware reduce IMU_GYRO_RATEMAX on some boards

src/drivers/safety_button/SafetyButton.cpp, src/modules/px4iofirmware/safety.c
This needs to be tested on hardware.
=> Latch FMU and IO safety once disabled

.ci/Jenkinsfile-hardware, msg/vehicle_status_flags.msg, src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp
Add `condition_angular_velocity_valid` and `condition_attitude_valid` to vehicle_status_flags. Only monitoring for now, but will be tied into the state machine later.
=> commander: vehicle_status_flags add attitude and angular velocity

.github/workflows/sitl_tests.yml, test/mavsdk_tests/autopilot_tester.cpp, test/mavsdk_tests/autopilot_tester.h, test/mavsdk_tests/test_multicopter_failsafe.cpp
Work in progress to address failing integration tests.
=> Work on failing integration tests

src/drivers/uavcan/uavcan_drivers/stm32h7/driver/src/internal.hpp
=> uavcan: stm32h7 driver silence debug output

src/modules/commander/Arming/PreFlightCheck/checks/sdcardCheck.cpp
I was late for the review in https://github.com/PX4/PX4-Autopilot/pull/16707. Making up for that.
- No unnecessary stack allocation when not doing the actual sdcard check
- No early return
- parameter variable names after convention (I know I forgot this myself before)
- Very explicit check if sd card is present
So far untested
=> sdcardCheck: minor refactor

src/modules/navigator/rtl.cpp, src/modules/navigator/rtl.h
- fixes https://github.com/PX4/PX4-Autopilot/issues/16843
=> navigator: RTL don't get invalid params

.github/workflows/sitl_tests.yml, test/mavsdk_tests/autopilot_tester.cpp, test/mavsdk_tests/autopilot_tester.h, test/mavsdk_tests/mavsdk_test_runner.py
=> More SITL test improvements, take 3

test/mavsdk_tests/autopilot_tester.h, test/mavsdk_tests/mavsdk_test_runner.py
Creating another PR so that @bkueng gets a chance to review the changes regarding the ulog upload, and improving the information displayed in flight review.
Follow up to #16840
=> More SITL test improvements, take 4

msg/estimator_status.msg, src/modules/ekf2/EKF2.cpp
Requires https://github.com/PX4/PX4-ECL/pull/977 first.
From the discussion in https://github.com/PX4/PX4-ECL/pull/961#issuecomment-779259966.
=> ekf2: estimator status log reset counts

src/modules/px4iofirmware/controls.c
It was for example possible that DSM got parsed, and in the next iteration
SBUS got parsed, leading to multiple PX4IO_P_STATUS_FLAGS_RC_ flags set.
input_rc::input_source was then incorrectly set to DSM.
Partially guarding was already done: if SBUS got parsed, DSM and others
were skipped.
The IO will still clear all PX4IO_P_STATUS_FLAGS_RC_* flags on RC loss.
=> px4iofirmware: guard against parsing multiple RC protocols

src/drivers/px4io/px4io.cpp
This adds robustness to system timing and bad link. I've tested this on a normal setup. Needs testing on more problematic setup.
=> PX4 IO: Retry upgrades of IO

src/modules/logger/params.c
- closes https://github.com/PX4/PX4-Autopilot/issues/16904
=> logger: update SDLOG_PROFILE comment to reflect current default

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp
=> px4_work_queue: increase wq:nav_and_controllers stack 1760->1824

src/modules/commander/Arming/PreFlightCheck/checks/ekf2Check.cpp, src/modules/commander/Arming/PreFlightCheck/checks/preArmCheck.cpp, src/modules/commander/commander_params.c
I stumbled into these while working on a bench setup and this helps with more consistent behavior.
=> Commander arming checks

src/modules/ekf2/EKF2.cpp
Unblocking ECL submodule updates while waiting for https://github.com/PX4/PX4-Autopilot/pull/16544.
=> EKF2: update to latest ecl with new global origin helpers

src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/streams/GPS_GLOBAL_ORIGIN.hpp
Another small/safe piece broken out of https://github.com/PX4/PX4-Autopilot/pull/16544.
=> mavlink: GPS_GLOBAL_ORIGIN on by default, but only send on change or when requested

platforms/posix/cmake/sitl_target.cmake
- this was limited to single threaded due to CI issues and even developer machines with limited resources
@bperseghetti
=> platforms/posix: try increasing sitl_gazebo build parallelism

.ci/Jenkinsfile-compile, .vscode/cmake-variants.yaml
=> delete remaining intel aero references

ROMFS/px4fmu_common/init.d/rcS, src/modules/dataman/dataman.cpp, src/modules/dataman/dataman.h
This is no longer used anywhere. It should be a little easier to maintain and extend dataman without this ugly platform specific piece.
=> dataman: remove flash backend

src/drivers/gps/gps.cpp
Function `px4_clock_settime` gets called at the same time while GPS data is collected over UART RX with an interrupt routine. The functions `px4_clock_settime` is disabling interrupts and this can cause loss of GPS data. 
This is especially problematic if the RTC timer is driven by LSE with a lower frequency where the waiting time for synchronization is increased. Frequently calling px4_clock_settime and longer time inside means a higher chance for data to be corrupted. 
This solution will reduce the number of `px4_clock_settime` calls. It will check if the time drift of the internal clock and GPS clock is higher than 5 seconds and it will trigger the clock sync.
This process will reduce the possibility of error …
=> drivers/gps: update RTC only if time drift for 5s

src/modules/commander/Commander.cpp
Came across this unused residue while reviewing #16266 
Remove it.
Compiles
Probably got forgotten in https://github.com/PX4/PX4-Autopilot/pull/5987
=> Commander: remove unused arm mode command residue

src/lib/mathlib/CMakeLists.txt, src/lib/mathlib/math/filter/LowPassFilter2pVector3fTest.cpp
I've heard a few times that some people are skeptical regarding the real effect of this low-pass filter.
Add unit tests
I used https://github.com/Auterion/Flight_Control_Prototyping_Scripts/pull/5 to find the expected phase delay and gain at the tested frequencies.
=> Add unit tests for Butterworth 2nd order low-pass filter

.ci/Jenkinsfile-compile
=> Jenkinsfile-compile:Fix breakage

boards/emlid/navio2/default.cmake, platforms/nuttx/src/px4/common/include/px4_platform/micro_hal.h, platforms/posix/src/px4/common/include/px4_platform/micro_hal.h, src/drivers/imu/adis16477/ADIS16477.cpp, src/drivers/imu/analog_devices/adis16448/ADIS16448.cpp, src/drivers/rc_input/RCInput.cpp
- NuttX: up_udelay and up_mdelay
- Linux/POSIX: usleep and msleep
=> platforms: add px4_udelay and px4_mdelay

src/modules/simulator/simulator.h, src/modules/simulator/simulator_mavlink.cpp
This is to ensure we have coverage of the updated rate control sensor pipeline in simulation after https://github.com/PX4/PX4-Autopilot/pull/15820.
=> simulator: make first accel/gyro simulated FIFO

src/modules/sensors/voted_sensors_update.cpp
- in multi-EKF mode the EKF selector becomes responsible for IMU selection rather than the sensors module
- this updates the sensors module to still make the initial primary IMU selection on startup before the EKF selector is running 
- this ensures there is still angular velocity for the rate controller and acceleration data for the land detector immediately even if ekf2 encounters a problem (misconfiguration, missing data source like baro, etc)
=> sensors: publish sensor_selection initially regardless of SENS_IMU_MODE

ROMFS/px4fmu_common/init.d-posix/rcS, ROMFS/px4fmu_common/init.d/airframes/4017_nxp_hovergames, ROMFS/px4fmu_common/init.d/rc.mc_defaults, ROMFS/px4fmu_common/init.d/rc.vtol_defaults, boards/mro/x21/init/rc.board_defaults, boards/px4/fmu-v2/init/rc.board_defaults, boards/px4/fmu-v3/init/rc.board_defaults, posix-configs/rpi/px4.config, posix-configs/rpi/px4_fw.config, posix-configs/rpi/px4_test.config, src/drivers/imu/bosch/bmi055/BMI055_Accelerometer.cpp, src/drivers/imu/bosch/bmi055/BMI055_Gyroscope.cpp, src/drivers/imu/bosch/bmi088/BMI088_Accelerometer.cpp, src/drivers/imu/bosch/bmi088/BMI088_Gyroscope.cpp, src/drivers/imu/bosch/bmi088/bmi088_i2c/BMI088_Accelerometer.cpp, src/drivers/imu/bosch/bmi088/bmi088_i2c/BMI088_Gyroscope.cpp, src/drivers/imu/invensense/icm20602/ICM20602.cpp, src/drivers/imu/invensense/icm20608g/ICM20608G.cpp, src/drivers/imu/invensense/icm20649/ICM20649.cpp, src/drivers/imu/invensense/icm20689/ICM20689.cpp, src/drivers/imu/invensense/icm20948/ICM20948.cpp, src/drivers/imu/invensense/icm40609d/ICM40609D.cpp, src/drivers/imu/invensense/icm42605/ICM42605.cpp, src/drivers/imu/invensense/icm42688p/ICM42688P.cpp, src/drivers/imu/invensense/mpu6000/MPU6000.cpp, src/drivers/imu/invensense/mpu6500/MPU6500.cpp, src/drivers/imu/invensense/mpu9250/MPU9250.cpp, src/drivers/imu/invensense/mpu9250/MPU9250_I2C.cpp, src/drivers/imu/st/lsm9ds1/LSM9DS1.cpp, src/modules/sensors/vehicle_angular_velocity/imu_gyro_parameters.c
=> IMU_GYRO_RATEMAX set system default to 400 Hz

.ci/Jenkinsfile-compile, boards/nxp/fmuk66-e/rtps.cmake
Add support RTPS agent for K66 builds
=> Add K66-r rtps

src/modules/mc_pos_control/MulticopterPositionControl.cpp
OFFBOARD CI tests are failing on landing due to the takeoff state machine reactivating immediately on landing because OFFBOARD is always setting want_takeoff = true.
This change attempts to capture the takeoff intent in an OFFBOARD (trajectory) setpoint.
Example failure log - https://logs.px4.io/plot_app?log=775688d0-faee-4f31-bb9b-1772ea0b1d9e
=> mc_pos_control: add OFFBOARD takeoff intent

msg/tools/uorb_rtps_message_ids.yaml
Added uORB message required by this [PR](https://github.com/PX4/px4_ros_com/pull/71)
=> added messages required by offboard_control example

msg/sensor_gyro_fft.msg, src/modules/gyro_fft/GyroFFT.cpp
Looking at automatically setting an appropriate threshold or breaking it out for user configuration.
=> gyro_fft: log peak frequency magnitudes

src/drivers/rc_input/RCInput.cpp, src/drivers/rc_input/RCInput.hpp, src/drivers/rc_input/ghst_telemetry.cpp, src/drivers/rc_input/ghst_telemetry.hpp, src/lib/rc/common_rc.h, src/lib/rc/ghst.cpp, src/lib/rc/ghst.hpp, src/lib/rc/rc_tests/RCTest.cpp
Ghost telemetry – send battery status
Hello PX4 community. Here is my pull request for sending battery status using ghost telemetry.
This pull request is addition to pull request:
https://github.com/PX4/PX4-Autopilot/pull/16854
Factors should be applied in order to show correct values of volts, amps and mAh. Minimum step for mAh is 10, because of the factor that needs to be applied.
The solution is tested and here is the video:
https://www.youtube.com/watch?v=xrlBO1FbggU
Also, I changed code for ghost protocol to follow more MISRA C++ guidelines.
Best regards,
Juraj Ciberlin
=> ghst_telemetry: send battery status

msg/sensor_gyro_fifo.msg, platforms/nuttx/init/stm32f7/rc.board_arch_defaults, src/modules/gyro_fft/GyroFFT.cpp
Let's see what this would cost.
=> boards: stm32f7 run gyro_fft by default

src/lib/tecs/TECS.cpp, src/lib/tecs/TECS.hpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp, src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c
Will add motivation, description and testing data in a bit.
=> TECS: Add feedforward gains for energy rates

src/lib/battery/battery.cpp, src/lib/battery/battery.h
=> Factor in total current consumption in battery remaining estimation

src/drivers/camera_trigger/CMakeLists.txt, src/drivers/camera_trigger/camera_trigger.cpp, src/drivers/camera_trigger/camera_trigger_params.c, src/drivers/camera_trigger/interfaces/src/camera_interface.cpp, src/drivers/camera_trigger/interfaces/src/camera_interface.h, src/drivers/camera_trigger/interfaces/src/gpio.cpp, src/drivers/camera_trigger/interfaces/src/gpio.h, src/drivers/camera_trigger/interfaces/src/pwm.cpp, src/drivers/camera_trigger/interfaces/src/pwm.h, src/drivers/camera_trigger/interfaces/src/seagull_map2.cpp, src/drivers/camera_trigger/interfaces/src/seagull_map2.h
- add PX4_DEBUG messages
- add copyright headers
- move initializers to header
=> camera_trigger: cleanup

src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
- requires ~~https://github.com/PX4/PX4-ECL/pull/990~~
=> geo: purge globallocal_converter

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
Possible fix for https://github.com/PX4/PX4-Autopilot/issues/17122#issuecomment-799554102.
@AndreRigi @Jaeyoung-Lim
=> fw_pos_control_l1: OFFBOARD fully populate position_setpoint_triplet

msg/optical_flow.msg, src/drivers/optical_flow/paw3902/PAW3902.cpp, src/drivers/optical_flow/paw3902/PAW3902.hpp, src/drivers/optical_flow/paw3902/PixArt_PAW3902JF_Registers.hpp, src/drivers/optical_flow/paw3902/paw3902_main.cpp
- fully respect datasheet quality and shutter metrics for mode changes
- use MOTION pin for scheduling if available
- log light mode
- refactor common enable LED code
- respect read and write time delays
=> paw3902: fixes and improvements

platforms/common/uORB/uORB_tests/uORBTest_UnitTest.cpp
Avoid a race condition in the builds.
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-hardware/detail/pr-px4_log_build_string/1/pipeline/1581
=> uORB: test multi timestamp requirement only applies per topic instance

msg/sensor_gps.msg
Requires https://github.com/PX4/PX4-GPSDrivers/pull/77
=> gps log automatic gain control (AGC) monitor

src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
- last timestamp sample must be set in FIFO case for ESC RPM dynamic filter update
- slightly relax thresholds for dynamic notch FFT apply or reset
=> sensors/vehicle_angular_velocity: fix dynamic notch ESC in FIFO case

src/modules/fw_pos_control_l1/runway_takeoff/runway_takeoff_params.c
a few small typos in the description at the RWTO_PSP parameter
fixed the typos
=> fixed typo in description of RWTO_PSP parameter

src/drivers/rc_input/RCInput.cpp, src/drivers/rc_input/RCInput.hpp
This is a first take on a lock issue that @dagar has seen.
=> RC Input: Reset lock state when switching to a new protocol

src/drivers/magnetometer/lsm9ds1_mag/LSM9DS1_MAG.cpp, src/drivers/magnetometer/lsm9ds1_mag/LSM9DS1_MAG.hpp, src/drivers/magnetometer/lsm9ds1_mag/ST_LSM9DS1_MAG_Registers.hpp, src/drivers/magnetometer/lsm9ds1_mag/lsm9ds1_mag_main.cpp
- possible fix for https://github.com/PX4/PX4-Autopilot/issues/17199, not yet tested
@Pskoog3 can you give this a quick try?
=> magnetometer/lsm9ds1_mag: refactor to new style with state machine and configuration monitoring

Tools/uorb_graph/create.py
(Updated: Mon 22 Mar 2021 09:14:00 PM EDT )
The script at `Tools/uorb_graph/create.py` was undercounting publications and subscriptions -- particularly C++ definitions.
This PR overhauls & refactors the script to greatly increase the variety of cases it can handle.
This adds additional fields to the regexes when scanning source code.
- Expands the debugging options of this script
- adds '-v', '-vv' => increase output verbosity
- adds '--merge-depends' flag for merging library topics
- Records all warnings -- unhandled or ambiguous matches
- A simple summary is printed on completion
- A listing is printed out in verbose/debug output modes
- only prints out for files found in the supplied source tree (i.e. the `--src-path` argument)
- Library vs Module
- By default, modules don't link to …
=> [uorb-graph][squash][refactor]  Fixes PR #16695 -- Fixes uorb-graph script

src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp
Small suggestion for https://github.com/PX4/PX4-Autopilot/pull/16614.
=> commander: centralize main_state strings and simplify main state change attempts

src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/commander/commander_helper.cpp, src/modules/commander/commander_helper.h, src/modules/commander/commander_tests/state_machine_helper_test.cpp, src/modules/commander/state_machine_helper.cpp, src/modules/commander/state_machine_helper.h
These passed around pointers bug me for a long time. I had to refactor them.
Switch to pass by reference.
It compiles.
I came across this again when reviewing #16614
=> Commander switch to pass by reference

src/modules/mc_pos_control/MulticopterPositionControl.cpp
I accidentally removed the fix from https://github.com/PX4/PX4-Autopilot/pull/14821 in #14665
Se removal in diff (have to unfold MulticopterPositionControl.cpp/FlightModeManager.cpp manually because of some GitHub bug):
https://github.com/PX4/PX4-Autopilot/pull/14665/files#diff-3fd0d86b4d06526da0551f7256a003ae78e84a241f68fc48f15b1aeff0386d9aL351
https://github.com/PX4/PX4-Autopilot/pull/14665/files#diff-75545eaa2cbcbcced0da88552481e3ce674572b655022ed05e642ec07869eaf6R477
Readd what the fix from https://github.com/PX4/PX4-Autopilot/pull/14821
AFAIK we do not have a better solution yet so we better bring the fix back.
=> MulticopterPositionControl: readd takeoff ramp fix

src/modules/commander/Commander.cpp
This allows to trigger a pairing command from the command line.
=> Commander: Add support for pairing via commandline

Tools/serial/generate_config.py, Tools/serial/rc.serial_port.jinja, Tools/serial/serial_params.c.jinja, src/modules/mavlink/module.yaml, validation/module_schema.yaml
Cleanup from https://github.com/PX4/PX4-Autopilot/pull/14460
=> config: cleanup ethernet configuration

src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h, src/modules/simulator/simulator_mavlink.cpp
- fixes https://github.com/PX4/PX4-Autopilot/issues/17325
=> simulator: GPS populate all sensor_gps fields (alt_ellipsoid, etc)

msg/battery_status.msg, src/drivers/uavcan/CMakeLists.txt, src/drivers/uavcan/dsdl/cuav/equipment/power/20300.CBAT.uavcan, src/drivers/uavcan/sensors/cbat.cpp, src/drivers/uavcan/sensors/cbat.hpp, src/drivers/uavcan/sensors/sensor_bridge.cpp, src/drivers/uavcan/uavcan_params.c
Add a UAVCAN V0 protocol for CUAV smart battery.
=> add CUAV smart battery support

src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp
=> Commander: baro check: only report failure of mandatory instances

src/drivers/pwm_out/PWMOut.cpp, src/lib/circuit_breaker/circuit_breaker_params.c
This is a collection of release cleanup commits that are fixing UX / setup issues that users run into.
=> Release polishing

boards/modalai/fc-v1/init/rc.board_defaults
=> boards: modalai simplify defaults with new parameter defaults mechanism (AUTOCNF replacement)

src/modules/ekf2/EKF2.cpp
- this is to minimize missed sensor data (and unnecessary error output) between EKF2 construction and once it actually starts running
=> ekf2: Multi-EKF let new instance schedule itself immediately on successful init

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp
https://logs.px4.io/plot_app?log=be927c5d-c264-47b2-b3c1-094bad17fabc
=> px4_work_queue: increase nav_and_controllers stack

platforms/nuttx/Debug/poor-mans-profiler.sh
As requested on https://github.com/PX4/PX4-user_guide/pull/1221
Now sets the GDB serial device to the path of a DroneCode Probe by default, with optional command-line override.
A few usage instructions also added to the top of the file as well.
FYI @pavel-kirienko
=> poor-mans-profiler: Add documentation

platforms/common/uORB/Subscription.cpp, src/modules/ekf2/EKF2.cpp
Made it impossible to switch away from a non-existing instance.
I didn't see it being a problem in existing code.
=> Subscription: fix ChangeInstance

src/drivers/protocol_splitter/protocol_splitter.cpp
Just complementing https://github.com/PX4/PX4-Autopilot/pull/17415 with some format updates.
=> drivers: protocol_splitter: some style updates

.gitmodules
=> update submodule micro-CDR

Tools/process_sensor_caldata.py
This makes it a bit easier to see what's going on.
=> Tools/process_sensor_caldata.py - median filter sensor data

src/drivers/gps/CMakeLists.txt, src/drivers/gps/gps.cpp, src/drivers/gps/params.c
1. add femtomes gps driver protocol in `gps.cpp`
2. add femtomes in `params.c`
3. run `make format`
=> femtomes : add femtomes gps driver protocol

src/lib/parameters/parameters.cpp
If the parameter import fails all parameters will be reset (and saved to FRAM). We should re-try the import as a precaution.
https://github.com/PX4/PX4-Autopilot/blob/d631a5d39f4bdf0acb1ef5973616633e179877d3/ROMFS/px4fmu_common/init.d/rcS#L154-L157
=> parameters: attempt import multiple times

src/modules/vtol_att_control/vtol_type.h
Missed this here: https://github.com/PX4/PX4-Autopilot/pull/16691#pullrequestreview-650619678
=> vtol: init boolean consistently

src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp, src/modules/flight_mode_manager/tasks/ManualAltitude/FlightTaskManualAltitude.hpp, src/modules/land_detector/LandDetector.cpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/streams/WIND_COV.hpp
This is a set of some implicit NAN&INF float->double conversions, which cause errors on my current risc-v environment. I guess it is proper to fix these for all.
=> Float fixes to upstream

src/modules/commander/mag_calibration.cpp
=> commander: mag_calibration fail immediately if no mags available

src/drivers/imu/analog_devices/adis16448/ADIS16448.cpp, src/drivers/imu/analog_devices/adis16448/ADIS16448.hpp, src/drivers/imu/analog_devices/adis16448/Analog_Devices_ADIS16448_registers.hpp
For debugging https://github.com/PX4/PX4-Autopilot/issues/17509.
=> drivers ADIS16448 minor fixes and compatibility with older model

src/drivers/magnetometer/isentek/ist8308/IST8308.cpp, src/drivers/magnetometer/isentek/ist8308/IST8308.hpp, src/drivers/magnetometer/isentek/ist8308/iSentek_IST8308_registers.hpp
- disable noise suppression filter
- select more appropriate dynamic range
- carefully set and clear all ODR, DR, and OSRCNTL bits
- retry in probe multiple times
=> ist8308: improve configuration

src/modules/mavlink/streams/STATUSTEXT.hpp
- STATUSTEXT stream use perf count for missed messages instead of error message
- don't send stale messages
=> mavlink: STATUSTEXT stream use perf count for missed messages

src/modules/commander/Commander.cpp, src/modules/commander/commander_helper.cpp, src/modules/commander/commander_helper.h, src/modules/navigator/mission_feasibility_checker.cpp, src/modules/navigator/mission_feasibility_checker.h
This includes a couple of fixes, check the commits for more details.
=> Improve blinking and beeping on invalid missions

src/modules/navigator/GeofenceBreachAvoidance/GeofenceBreachAvoidanceTest.cpp
=> navigator: GeofenceBreachAvoidance remove duplicate type alias

src/modules/sensors/vehicle_angular_velocity/imu_gyro_parameters.c
- these need more work and testing before we should encourage wider usage
=> move IMU_GYRO_FFT_EN to developer category

boards/px4/fmu-v5x/init/rc.board_sensors
Merge after https://github.com/PX4/PX4-Autopilot/pull/17649
=> px4_fmu-v5x Remove Second mag

src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
Some systems have enough current (digital radios, companion computers, etc) when disarmed for this to matter.
@baumanta
=> sensors/vehicle_magnetometer: apply current compensation regardless of arming state

src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2Selector.cpp, src/modules/ekf2/EKF2Selector.hpp
=> ekf2: add command line option to manually select instance

src/modules/ekf2/EKF2Selector.cpp
- choose the best instance regardless of yaw alignment
This was added in response to a test flight with EKF2_MAG_TYPE 5 (None). The EKF selector was stuck on the first initial instance due to none of the ekf2 instances completing yaw_align until much later in flight (due to enough movement + yaw estimator).
=> ekf2: selector handle uninitalized test ratios

src/lib/parameters/px4params/markdownout.py
Better error reporting when I build this :-)
=> markdownout for parameters - makes link internal

.github/workflows/python_checks.yml
Hopefully this fixes the CI problem seen in:
https://github.com/PX4/PX4-Autopilot/runs/2779651953#step:5:4
=> workflows: add missing dependency for mypy

.github/workflows/python_checks.yml
The previous PR was merged to optimistically.
Follow up to #17736
=> workflows: add missing s

msg/vehicle_command.msg, src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp
This sends the DO_PARACHUTE command to anyone listening for this command.
=> commander: send parachute command on termination

boards/cuav/nora/init/rc.board_sensors
I am very sorry for the extra work caused by my mistake. This commit is correct.
=> nora:fixed syntax error

Tools/mavlink_shell.py
E.g. `echo free|./Tools/mavlink_shell.py`
Or creating a virtual nsh console:
```
socat pty,rawer,link=/tmp/fmu_nsh_pts exec:"mavlink_shell.py 0.0.0.0\\:14550,pty,rawer"
```
Should be tested on non-linux (@MaEtUgR?)
=> mavlink_shell.py: allow scripted use

src/drivers/imu/invensense/icm20602/CMakeLists.txt, src/drivers/imu/invensense/icm20602/ICM20602.cpp, src/drivers/imu/invensense/icm20602/ICM20602.hpp, src/drivers/imu/invensense/icm20602/InvenSense_ICM20602_registers.hpp, src/drivers/imu/invensense/icm20602/icm20602_main.cpp, src/drivers/imu/invensense/icm20608g/CMakeLists.txt, src/drivers/imu/invensense/icm20608g/ICM20608G.cpp, src/drivers/imu/invensense/icm20608g/ICM20608G.hpp, src/drivers/imu/invensense/icm20608g/InvenSense_ICM20608G_registers.hpp, src/drivers/imu/invensense/icm20608g/icm20608g_main.cpp, src/drivers/imu/invensense/icm20689/CMakeLists.txt, src/drivers/imu/invensense/icm20689/ICM20689.cpp, src/drivers/imu/invensense/icm20689/ICM20689.hpp, src/drivers/imu/invensense/icm20689/InvenSense_ICM20689_registers.hpp, src/drivers/imu/invensense/icm20689/icm20689_main.cpp, src/drivers/imu/invensense/mpu6500/CMakeLists.txt, src/drivers/imu/invensense/mpu6500/InvenSense_MPU6500_registers.hpp, src/drivers/imu/invensense/mpu6500/MPU6500.cpp, src/drivers/imu/invensense/mpu6500/MPU6500.hpp, src/drivers/imu/invensense/mpu6500/mpu6500_main.cpp, src/drivers/imu/invensense/mpu9250/InvenSense_MPU9250_registers.hpp, src/drivers/imu/invensense/mpu9250/MPU9250.cpp, src/drivers/imu/invensense/mpu9250/MPU9250.hpp, src/drivers/imu/invensense/mpu9250/mpu9250_main.cpp
- fix for https://github.com/PX4/PX4-Autopilot/issues/17804
@NicolasM0 could you use this branch for your next attempted reproduce?
=> drivers/imu/invensense: store offset registers on configure, trigger reset on any change

src/lib/cdev/nuttx/cdev_platform.cpp
check if inode is not unlinked before use
=> cdev: fixes hardfaults when device get disconnected (#17846)

src/drivers/gps/gps.cpp
This fixes GPS start on the mRo PixracerPro, although presumably it's covering some other underlying problem yet to be determined.
Ignoring that, it seems like closing and reopening the port on a mode change or configure fail could be somewhere between more robust (bad initialization or in-flight failure) and harmless. Thoughts?
=> drivers/gps: close port if configure fails

platforms/common/include/px4_platform_common/atomic.h, src/systemcmds/tests/test_microbench_atomic.cpp
This extends px4::atomic to use a critical section on NuttX if the size exceeds what can be done with lock-free atomic instructions. The intent it to use this in drivers to get the sample timestamp from the interrupt without littering ifdefs everywhere, although I'm open to alternatives. Later this could be extended to use locks for larger sizes on other platforms like std::atomic (or just use std::atomic directly).
=> px4_platform_common: atomic support larger types with critical sections (on NuttX)

.github/workflows/deploy_all.yml, .github/workflows/metadata.yml, cmake/metadata.cmake
Let's see if this fixes everything
=> Fixes to metadata deployment

src/modules/mavlink/mavlink_main.cpp
Check if a message only for us or heartbeats forwarding is enabled only once before the guard and loop on instances.
=> mavlink: optimize message forwarding

.github/workflows/compile_nuttx.yml, Makefile, boards/cuav/nora/test.cmake, boards/px4/fmu-v2/test.cmake, boards/px4/fmu-v5x/test.cmake, src/modules/commander/CMakeLists.txt
This lowers the number of GitHub actions builds from ~100 -> 75.
=> Makefile: add all_variants_@ helper target and consolidate github actions builds

.ci/Jenkinsfile-hardware, boards/px4/fmu-v5/debug.cmake, boards/px4/fmu-v5/stackcheck.cmake
- attempt to minimize issues on heavily loaded debug and stackcheck builds
- disable systemcmds/bl_update on debug and stackcheck fmu-v5
=> Jenkins: HIL attempt to set certain parameters initially

src/modules/flight_mode_manager/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.cpp, src/modules/flight_mode_manager/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.hpp, src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.cpp, src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.hpp, src/modules/flight_mode_manager/tasks/ManualAcceleration/FlightTaskManualAcceleration.cpp, src/modules/flight_mode_manager/tasks/ManualAcceleration/FlightTaskManualAcceleration.hpp, src/modules/flight_mode_manager/tasks/ManualAltitudeSmoothVel/FlightTaskManualAltitudeSmoothVel.cpp, src/modules/flight_mode_manager/tasks/ManualAltitudeSmoothVel/FlightTaskManualAltitudeSmoothVel.hpp, src/modules/flight_mode_manager/tasks/ManualPositionSmoothVel/FlightTaskManualPositionSmoothVel.cpp, src/modules/flight_mode_manager/tasks/ManualPositionSmoothVel/FlightTaskManualPositionSmoothVel.hpp
Not yet used, but might as well get them in place.
=> flight_mode_manager: pass deltas on estimator reset

src/modules/mavlink/mavlink_receiver.cpp
=> [BACKPORT 1.12] mavlink: fix offboard velocity input

platforms/nuttx/CMakeLists.txt, platforms/nuttx/Debug/flash_bootloader.jlink.in, platforms/nuttx/cmake/jlink.cmake, src/drivers/px4io/CMakeLists.txt, src/systemcmds/bl_update/CMakeLists.txt
=> cmake cleanup jlink flashing helpers

msg/sensors_status_imu.msg, src/modules/sensors/data_validator/DataValidatorGroup.cpp, src/modules/sensors/data_validator/DataValidatorGroup.hpp, src/modules/sensors/voted_sensors_update.cpp
- later the sensor priorities (user configurable) can be factored into the estimator selection criteria
=> sensors: add accel/gyro current priority to sensors_status_imu

src/drivers/px4io/px4io.cpp
Match the description with the process
Match the timeout time to the process
Descriptions describe the process.
Confirmed that SITL starts successfully.
None
=> px4io: Changing the timeout time description (NFC)

src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h
- fixes https://github.com/PX4/PX4-Autopilot/issues/17977
@Ankur1014 can you give this a try?
=> mavlink: receiver fix HIL_STATE_QUATERNION map projection init

src/modules/landing_target_estimator/landing_target_estimator_params.c, src/modules/local_position_estimator/params.c, src/modules/navigator/precland_params.c
A few typos in parameters, originally raised in https://github.com/PX4/PX4-user_guide/pull/1416 - just the ones that are clearly wrong.
=> Minor docs errors in a few parameters

src/drivers/uavcan_v1/Uavcan.cpp, src/drivers/uavcan_v1/Uavcan.hpp
uavcan start
uavcan stop 
would cause a hardfault
=> uavcan_1:Fixed hard fault on stop & leaks

src/modules/navigator/mission_params.c
=> navigator: fix param description

src/drivers/imu/analog_devices/adis16448/ADIS16448.cpp, src/drivers/imu/analog_devices/adis16448/ADIS16448.hpp, src/drivers/imu/analog_devices/adis16448/Analog_Devices_ADIS16448_registers.hpp
- add verified register read method
=> adis16448: add additional delay after transfer in case of back to back transactions

src/drivers/distance_sensor/ll40ls/LidarLiteI2C.cpp, src/drivers/distance_sensor/ll40ls/LidarLiteI2C.h
=> ll40ls: add support for LidarLite V4

src/modules/sih/sih.cpp, src/modules/sih/sih.hpp
minor update
- using `Quatf::expq()`
- added a fuselage
- increased rudder authority
=> using Quatf::expq(), fuselage added

src/drivers/magnetometer/bosch/bmm150/BMM150.cpp
=> magnetometer/bosch/bmm150: free all perf counters

.github/workflows/metadata.yml, Jenkinsfile
https://github.com/PX4/PX4-Autopilot/pull/18052
=> CI fix renamed uorb_to_ros_rtps_ids.py -> uorb_to_ros_urtps_topics.py

.ci/Jenkinsfile-hardware
- board test harness needs to be repaired
=> Jenkins: remove modalai_fc-v1 temporarily

ROMFS/px4fmu_test/init.d/rcS, src/drivers/px4io/px4io.cpp, src/modules/dataman/dataman.cpp, src/modules/px4iofirmware/registers.c
@dagar I took a first pass going through the code and doing some basic testing - I now have pwm after bootup.
=> px4io mixing on fmu updates

src/drivers/distance_sensor/broadcom/afbrs50/AFBRS50.cpp, src/drivers/distance_sensor/broadcom/afbrs50/AFBRS50.hpp, src/drivers/distance_sensor/broadcom/afbrs50/API/Src/timer.c, src/drivers/distance_sensor/broadcom/afbrs50/argus_hal_test.c, src/drivers/distance_sensor/broadcom/afbrs50/argus_hal_test.h
This PR improves the AFBR mode switching, rate switching, and adds the API test. 
```
nsh> afbrs50 status
afbrs50: sample interval: 1555 events, 20014.07us avg, min 18303us max 21647us 1565.481us rms
distance: 0.157m
mode: 2
dfm mode: 2
rate: 50 Hz
```
https://review.px4.io/plot_app?log=20ac37aa-d8a1-4b58-8958-166657605315
https://review.px4.io/plot_app?log=c551d79b-2476-4bdb-be6d-2e9d02cf49e9
=> AFBR mode switching, rate switching, and test

src/modules/replay/Replay.cpp, src/systemcmds/bl_update/bl_update.c
This PR resolves a part of this reported memory bugs (https://github.com/PX4/PX4-Autopilot/issues/17908).
Preventing potential memory leak and null pointer dereference
=> Fix memory bugs

src/modules/commander/Commander.cpp
Just a tiny improvement in messaging towards the user for when the yaw emergency kicks in.
=> Commander: improve user notification for yaw emergency

msg/tools/urtps_bridge_topics.yaml
Adding sensor_combined to the urtps_bridge_topics.yaml file. I believe the PX4BuildBot will also add it to the px4_ros_com repo as well?
=> add sensor_combined to urtps_bridge_topics.yaml

src/modules/ekf2/EKF2.cpp
Not ideal, but this is probably better than nothing.
=> ekf2: multi-mode allow first instance to save EKF2_MAG_DECL

src/drivers/uavcan/uavcan_main.cpp
=> uavcan: save parameter after successful set

src/lib/sensor_calibration/Accelerometer.cpp, src/lib/sensor_calibration/Accelerometer.hpp, src/lib/sensor_calibration/Gyroscope.cpp, src/lib/sensor_calibration/Gyroscope.hpp, src/lib/sensor_calibration/Magnetometer.cpp, src/lib/sensor_calibration/Magnetometer.hpp, src/modules/sensors/sensor_params_acc0.c, src/modules/sensors/sensor_params_acc1.c, src/modules/sensors/sensor_params_acc2.c, src/modules/sensors/sensor_params_acc3.c, src/modules/sensors/sensor_params_gyro0.c, src/modules/sensors/sensor_params_gyro1.c, src/modules/sensors/sensor_params_gyro2.c, src/modules/sensors/sensor_params_gyro3.c, src/modules/sensors/sensor_params_mag0.c, src/modules/sensors/sensor_params_mag1.c, src/modules/sensors/sensor_params_mag2.c, src/modules/sensors/sensor_params_mag3.c
NaN is not supported by JSON, and leads to parsing failure in QGC.
- fixes https://github.com/PX4/PX4-Autopilot/issues/18095
=> calibration params: avoid using NaN as default

msg/templates/uorb_microcdr/microRTPS_client.cpp.em
Modify microRTPS client template file as a temporary fix to multi-instance generation in offboard control example as per https://github.com/PX4/px4_ros_com/issues/106#issuecomment-902790749.
=> change PublicationMulti-> Publication as a temporary fix

src/lib/systemlib/system_params.c, src/modules/sensors/sensors.cpp
- https://github.com/PX4/PX4-Autopilot/pull/18113 backported for v1.12
- @lukegluke FYI
=> sensors: always start baro/GPS/mag aggregators if SYS_HAS_* set

src/modules/vtol_att_control/tailsitter.cpp
To fix:
https://px4.slack.com/archives/C39C4E709/p1630599870001600
=> tailsitter.cpp:If transition timeout,abort transition

src/modules/navigator/rtl.cpp
Signed-off-by: RomanBapst <bapstroman@gmail.com>
Please see [this issue](https://github.com/PX4/PX4-Autopilot/issues/18169) for all the details
=> RTL: Fixed computation of return altitude if destination is not home

src/drivers/imu/invensense/icm42688p/ICM42688P.hpp
=> icm42688p: properly disable anti-aliasing and notch filter

.ci/Jenkinsfile-hardware, ROMFS/cannode/init.d/rcS, ROMFS/px4fmu_common/init.d/rcS, platforms/nuttx/src/px4/common/px4_init.cpp
Another tiny step towards unified init.
=> NuttX mount procfs and binfs in px4 init

src/modules/sensors/vehicle_imu/VehicleIMU.cpp
- check for inconsistent timestamps, zero samples, and numerical issues in online mean
=> sensors/vehicle_imu: add protections for bad sensor data

src/modules/replay/Replay.cpp
If there is a format mismatch whilst doing a replay, the logging truncated a lot of important information:
```
ERROR [replay] Formats for sensors_status_imu don't match. Will ignore it.
WARN  [replay]  Internal format: uint64_t timestamp;uint32_t accel_device_id_primary;uint32_t[4] accel_devi
WARN  [replay]  File format    : uint64_t timestamp;uint32_t accel_device_id_primary;uint32_t[4] accel_devi
ERROR [replay] Formats for estimator_event_flags don't match. Will ignore it.
WARN  [replay]  Internal format: uint64_t timestamp;uint64_t timestamp_sample;uint32_t information_event_ch
WARN  [replay]  File format    : uint64_t timestamp;uint64_t timestamp_sample;uint32_t information_event_ch
ERROR [replay] Formats for estimator_status_flags don't match. Will ignore it.
WARN  [replay]  Internal …
```
=> replay: improved logging for format mismatchs

src/drivers/imu/invensense/icm20602/ICM20602.cpp, src/drivers/imu/invensense/icm20649/ICM20649.cpp, src/drivers/imu/invensense/icm20948/ICM20948.cpp
=> imu/invensense: adjust scheduling dynamically if not using data ready interrupt

src/modules/airspeed_selector/AirspeedValidator.cpp
@sfuhrer  fix for https://github.com/PX4/PX4-Autopilot/issues/18185
=> fix disable airspeed check with negative ASPD_FS_INTEG

Tools/setup/ubuntu.sh
=> Fix Java version for Ubuntu 20.04 setup script

src/modules/commander/Commander.cpp
- fixes https://github.com/PX4/PX4-Autopilot/issues/18054
=> commander: don't play failsafe tune if disarmed

msg/vehicle_local_position.msg
This update comes from https://github.com/PX4/PX4-user_guide/pull/1552. Thanks @max11gen
Note, that it is a comment, so should not affect the actual message functioning. 
PS I can't merge. So if this accepted, please approve AND merge.
=> vehicle_local_position: clarify origin of system

src/drivers/dshot/DShot.cpp
If there is no running thread to process dshot commands it will cause the process to hang. 
(mixer is not properly loaded or mc_rate_control is not running) 
Command will timeout if there is no running thread to process it  (with a warning message).
=> dshot: timeout if commands are not processed

src/modules/commander/Commander.cpp
Allows to do commander disarm -f to disarm no matter what.
=> commander: allow force disarming

src/drivers/magnetometer/lsm9ds1_mag/LSM9DS1_MAG.cpp, src/drivers/tap_esc/tap_esc_uploader.cpp
This PR resolves a part of this reported memory bugs ([here](https://discuss.px4.io/t/some-memory-issues/24308/2)).
1) Preventing potential memory leak
2) Removing an idempotent assignment
=> Fix resource leak

src/modules/ekf2/EKF/ekf.h
Quick bug fix pulled from https://github.com/PX4/PX4-Autopilot/pull/18304.
=> ekf2: Fix dimensional error in gyro and accel bias variance conversions

src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
This fixes a small potential race condition in `sensors/vehicle_magnetometer` where the sensor update is skipped if the sensor is not enabled, but enabled is based on CAL_MAGx_PRIO and the sensor having a calibration.
=> sensors/vehicle_magnetometer: only check if sensor enabled after parameters loaded

src/drivers/uavcannode/Subscribers/RTCMStream.hpp, src/drivers/uavcannode/UavcanNode.cpp
This PR adds a rtcm subscriber for uavcannode. It has not been tested.
=> Add uavcannode RTCM Subscriber

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
Some more ideas how to clean up FW Position control slightly:
-  move nav_speed_2d calculation to function
-  move setting of control_mode_current to separate function
=> FW Position controller: clean up ideas

src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
- some UAVCAN ESCs report negative RPM for reverse rotation
- lower hard coded safety limit RPM limit to 10 Hz (600 RPM)
- avoid disabling notch filters that weren't configured
=> sensors/vehicle_angular_velocity: gyro RPM dynamic notch filter handle negative RPM

msg/vehicle_imu_status.msg, src/modules/sensors/vehicle_imu/VehicleIMU.cpp, src/modules/sensors/vehicle_imu/VehicleIMU.hpp
Possible fix for https://github.com/PX4/PX4-Autopilot/issues/18574.
~~TODO: review cost~~ no measurable change in cpu usage (F4, F7, etc)/
=> sensors/vehicle_imu: use WelfordMean for online mean and variance

src/modules/logger/log_writer_file.cpp
Currently in master when testing across various px4_fmu-v5 units I've found it very difficult to get a complete test log as logger usually quits after a few minutes (quite variable).
- reproducible on px4_fmu-v5 units from both CUAV and Holybro
- cards are a mix of stock units that shipped with units and higher end Sandisk
- all cards have been cleanly formatted (both Linux and Windows) and literally every block checked with multiple passes (`badblocks`, `fsck.vfat`, etc)
No I don't think this is the right solution, but I think it's better than giving up mid-flight.
Previous testing PR. https://github.com/PX4/PX4-Autopilot/pull/18355
=> logger: log write file allow single retry on write failure

src/modules/mavlink/streams/ORBIT_EXECUTION_STATUS.hpp
Otherwise it's checking all ORB_MULTI_MAX_INSTANCES (10).
=> mavlink: ORBIT_EXECUTION_STATUS stream limit to 2 instances

src/modules/sensors/vehicle_imu/VehicleIMU.cpp
- fix confusion between estimated bias and calibration offset when
saving after each flight
- when the stable bias estiamte is retrieved during flight it's
immediately converted to a sensor offset and saved
- fixes https://github.com/PX4/PX4-Autopilot/issues/18658
=> sensors/vehicle_imu: fix accel/gyro learned bias calibration updates

src/modules/sensors/vehicle_imu/VehicleIMU.cpp
- remove regular callback scheduling when sensor is disabled, register if re-enabled
=> sensors/vehicle_imu: improve disabled sensor handling

src/systemcmds/hardfault_log/hardfault_log.c
Formatting was supposed to be in hex.  Fixes #18675
=> hardfault_log:Fix formatting

src/modules/commander/Commander.cpp
Follow-up to https://github.com/PX4/PX4-Autopilot/pull/18693#issuecomment-976211828
In commander I check for the combination of enabled arm stick gesture and mapped arm switch and force disable the gesture in that case also informing the user.
We could move the entire logic into the `manual_control` module to deconvolute commander.
I tested in SITL:
- mapping an arm switch
- trying to enable the gesture while the arm switch is mapped
The logic triggered, the gesture was disabled and there was an information for the user.
Original pr on this topic: https://github.com/PX4/PX4-Autopilot/pull/9622
=> Commander: force disabling the arm stick gesture when arm switch is in use

.ci/Jenkinsfile-hardware, ROMFS/px4fmu_common/init.d/rcS, Tools/HIL/run_tests.py, src/systemcmds/sd_bench/sd_bench.c
PX4/NuttX PR https://github.com/PX4/NuttX/pull/170
- fixes https://github.com/PX4/PX4-Autopilot/issues/18672
=> NuttX stm32f7:sdmmc defer invalidate until after DMA completion

.ci/Jenkinsfile-hardware
- https://github.com/PX4/NuttX/pull/173
- https://github.com/PX4/NuttX-apps/pull/13
=> NuttX fixing mkfatfs continued

platforms/nuttx/src/px4/common/console_buffer.cpp
dmesg was locking the console buffer, then writing to stdout (a pipe in
the case of the MAVLink shell).
This might block, waiting for mavlink to read from the pipe. If however
mavlink tries to write to the console at that time, the lock is already
taken.
This patch avoids nested locking by using a separate buffer.
=> fix console_buffer: avoid potential deadlock when using dmesg over MAVLink shell

src/lib/motion_planning/PositionSmoothing.hpp, src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
Replaces https://github.com/PX4/PX4-Autopilot/pull/18614.
@bresch @MaEtUgR
=> Reapply PR 18614 to refactored FlightTaskAuto [Horizontal emergency braking]

.github/workflows/sitl_tests.yml, ROMFS/px4fmu_common/init.d-posix/rcS, ROMFS/px4fmu_common/init.d/rc.interface, test/mavsdk_tests/mavsdk_test_runner.py, test/mavsdk_tests/process_helper.py
Various tries trying to prevent some of the CI failures and timeouts we're seeing.
=> CI: mavsdk_test fixes

src/drivers/gps/gps.cpp
- fixes https://github.com/PX4/PX4-Autopilot/issues/18597
=> drivers/gps: require valid device to start

src/modules/dataman/dataman.cpp
Still hunting intermittent dataman failure on the test rack.
=> dataman: PX4_ERR on create_work_item failure

src/modules/navigator/navigator_main.cpp
=> navigator: increase stack slightly

src/modules/ekf2/CMakeLists.txt, src/modules/ekf2/EKF/CMakeLists.txt, src/modules/ekf2/EKF/control.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/height_fusion.cpp
This is a non-functional PR.
This part of the code is quite hard to follow and bugs might hide in the noise.
- move non control-related code into a separate file (get observation noise, compute innovation, ...)
- remove some boiler-plate code
With this cleanup, some inconsistencies between the different height aiding sources start to show up. I'll address them in a follow-up PR.
unit tests, change indicator
This is a required step towards multi height sources fusion
=> EKF2: height fusion control cleanup

src/modules/vmount/output.cpp, src/modules/vmount/output_rc.cpp
Unconfirmed report that garbage values were getting out on actuator_controls_2 somewhere, still verifying the root cause.
=> vmount: output rc simple protections

src/modules/dataman/dataman.cpp
It's rare, but on certain NuttX boards on the test rack I've found the lseek in dataman has failed at a very low rate.
This PR updates dataman to explicitly report the specific failures with PX4_ERR and the errno return, and it retries the seek or read/write since that type of failure in flight would be very bad.
=> dataman: retry file read/write failures and report seek errors

src/modules/vmount/input_rc.cpp, src/modules/vmount/input_rc.h, src/modules/vmount/vmount.cpp, src/modules/vmount/vmount_params.c
Fixes I needed to get a simple gimbal pitch servo working reasonably well.
Includes @julianoes changes from https://github.com/PX4/PX4-Autopilot/pull/18214.
=> vmount rc fixes

test/mavsdk_tests/mavsdk_test_runner.py, test/mavsdk_tests/process_helper.py
This adds two checks to make sure gzserver has actually started before continuing, and also whether the gz model call was successful.
=> mavsdk_tests: check gzserver and gz model calls

src/modules/mavlink/mavlink_main.cpp
Mavlink::destroy_all_instances() was holding the lock the entire time, but it's possible an instance would try to acquire it in the main loop.
eg https://github.com/PX4/PX4-Autopilot/blob/08b0ac9654d0041a78c61025a4114a59b0045f4d/src/modules/mavlink/mavlink_main.cpp#L2437-L2439
=> mavlink: destroy all instances fix potential dead lock

src/drivers/uavcan/beep.cpp
This is a PR to improve the UAVCAN/DRONECAN beep driver. Currently, the buzzer on a uavcannode won't sound at times when it should, like during calibration and mode changes.
=> Fix UAVCAN/DRONECAN Beep Driver

src/lib/parameters/param_translation.cpp
- convert float to int for FW_GPSF_LT
- fix comment in FW_GPSF_R as no inversion takes place
=> param translation: fix for FW_GPSF_LT and FW_GPSF_R

msg/vehicle_local_position.msg
Small typo in vehicle_local_position msg.
Fix the typo.
=> Small typo in vehicle_local_position msg

test/mavsdk_tests/mavsdk_test_runner.py
This was probably triggered due to a mypy update.
=> mavsdk_tests: fix type for mypy check

src/modules/simulator/sensor_baro_sim/SensorBaroSim.cpp, src/modules/simulator/sensor_gps_sim/SensorGpsSim.cpp, src/modules/simulator/sensor_mag_sim/SensorMagSim.cpp, src/systemcmds/esc_calib/esc_calib.c
This fixes two warnings that came up when building with clang 13.
=> Clang 13 fixes

src/modules/vmount/input_mavlink.cpp, src/modules/vmount/output.cpp, src/modules/vmount/output_mavlink.cpp, src/modules/vmount/output_mavlink.h, src/modules/vmount/vmount.cpp
Random assortment of vmount fixes that I forgot to upstream earlier.
=> Various vmount fixes

src/modules/navigator/navigator_main.cpp
typo in modules/navigator_main.cpp
=> Fix small typo in (modules/navigator_main)

src/drivers/protocol_splitter/protocol_splitter.cpp
The existing implementation had a flaw: when the buffer was getting full,
mavlink started to busy-loop, as the uart has data (poll returns immediately)
but no new data was read from the uart due to the buffer being full.
As rtps is running at lower prio, it never got the chance to read again,
making the problem even worse.
After 1s the timeout triggered and the buffer was cleared, so it recovered.
Instead of allowing for CPU spikes, we now immediately clear the buffer
(only as much as we have to), ensuring that new data is read from the uart.
=> fix protocol_splitter: remove timeout, drop buffer if too full instead

platforms/nuttx/src/px4/nxp/imxrt/adc/adc.cpp
ADC was returning  65536 on timeout so it was interpreted as a voltage. The was the result of interruption.
=> imxrt:ADC fix timeouts

src/modules/ekf2/EKF2.cpp
The imu and sensor_combined data should not be used when it has not been updated yet, otherwise this triggers a memory sanitizer warning:
```
Conditional jump or move depends on uninitialised value(s)
at 0x2DA7AA: __sanitizer_cov_trace_const_cmp1 (in build/px4_sitl_default-clang/bin/px4)
by 0x3C4E79: EKF2::Run() (src/modules/ekf2/EKF2.cpp:401)
by 0x6EB881: px4::WorkQueue::Run() (platforms/common/px4_work_queue/WorkQueue.cpp:187)
by 0x6ECB9D: px4::WorkQueueRunner(void*) (platforms/common/px4_work_queue/WorkQueueManager.cpp:230)
by 0x4C07258: start_thread (in /usr/lib/libpthread-2.33.so)
by 0x4D415E2: clone (in /usr/lib/libc-2.33.so)
Conditional jump or move depends on uninitialised value(s)
at 0x3C4E7C: EKF2::Run() (src/modules/ekf2/EKF2.cpp:401)
by 0x6EB881: px4::WorkQueue::Run() …
```
=> ekf2: fix uninitalized memory warning

test/mavsdk_tests/autopilot_tester.cpp, test/mavsdk_tests/mavsdk_test_runner.py, test/mavsdk_tests/process_helper.py
A couple of small mavsdk test improvements from last year.
=> MAVSDK test fixes

src/modules/fw_pos_control_l1/CMakeLists.txt, src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
After feedback from @RomanBapst https://github.com/PX4/PX4-Autopilot/pull/18841#discussion_r779360298
SITL.
=> FW Position control: use slew rate library for airspeed slew rate

src/modules/mc_pos_control/PositionControl/PositionControl.cpp
Several users reported having a thrust glitch during takeoff, caused by the hover thrust estimator getting valid.
Fix the equation that pre-loads the integrator when the new hover thrust parameter is applied:
Given that the equation for thrust is
```T = a_sp * Th / g - Th```
with:
```
a_sp = desired acceleration
Th = hover thrust and
g = gravity constant,
```
we want to find the acceleration that needs to be added to the integrator in order obtain the same thrust after replacing the current hover thrust by the new one:
```
T' = T
a_sp' * Th' / g - Th' = a_sp * Th / g - Th
```
so 
```a_sp' = (a_sp - g) * Th / Th' + g```
we can then add a_sp' - a_sp to the current integrator to absorb the effect of changing Th by …
=> Fix thrust step after takeoff

.ci/Jenkinsfile-hardware, Tools/HIL/test_airframes.sh
- this will help catch any DMA conflicts or blatant misconfiguration
=> Tools/HIL/test_airframes.sh enable all mavlink and GPS

src/modules/ekf2/EKF2.cpp
- cleanup obsolete comments
- remove debug helpers
- add additional variance requirements to mag bias stable (matching accel & gyro)
=> ekf2: accel/gyro/mag sensor cal minor cleanup

src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
As discovered by @bresch in https://github.com/PX4/PX4-Autopilot/pull/18953#discussion_r778800553 there are occasions where longer than should be used rather than calculating the vector length with an unnecessary squareroot.
To address this I quickly went though FlightTaskAuto and replaces all occurrences of `vector.length()`.
Untested, should be equivalent refactoring. Please review.
=> FlightTaskAuto: use longerThan() when possible in vector calculations

src/modules/sensors/sensor_params_mag.c
- attempt to reduce estimator 3D mag fusion cpu load
- simple alternative to https://github.com/PX4/PX4-Autopilot/pull/19004
=> sensors: lower SENS_MAG_RATE default

src/modules/ekf2/EKF/EKFGSF_yaw.cpp, src/modules/ekf2/EKF/EKFGSF_yaw.h, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/ekf_helper.cpp
Non-functional change. I just needed to extract this logic for later use.
=> ekf2: yaw emergency estimate availability cleanup

src/modules/sensors/vehicle_gps_position/gps_blending.cpp
As we learned in https://github.com/PX4/PX4-Autopilot/pull/18358 and https://github.com/PX4/PX4-Autopilot/pull/18359 we shouldn't use floats when working with 64 bit timestamps because it starts to introduce errors after a few hours.
=> sensors/vehicle_gps_position: don't work with 64 bit time with 32 bit floats

platforms/nuttx/src/px4/nxp/imxrt/adc/adc.cpp
Timeout was too short when cold.
=> imxrt:ADC extend timeout

Tools/uorb_graph/create.py
I found the link for multiple topics is broken when I use uorb graph. 
I implemented the TODO works.
Please check it
Thanks.
=> Link problem for multi topics in the uorb graph

src/drivers/magnetometer/bosch/bmm150/BMM150.cpp
- if self test fails consistently proceed with startup, but report failure
=> drivers/magnetometer/bosch/bmm150: init and self test improvements

test/mavsdk_tests/catch2/catch.hpp
Fixes this issue on Fedora: https://github.com/catchorg/Catch2/issues/2178
=> mavsdk_tests: update catch2 to 2.13.8

src/modules/commander/Commander.cpp
- used by the new output system
=> commander: don't reject VEHICLE_CMD_DO_SET_ACTUATOR

src/drivers/uavcannode/CMakeLists.txt
=> uavcannode need link conversion

ROMFS/px4fmu_common/init.d-posix/rc.replay, src/modules/logger/logged_topics.cpp
This changed in pyulog at some point.
=> ROMFS: rc.replay fix ulog_params argument

src/modules/navigator/navigator.h, src/modules/navigator/navigator_main.cpp
This PR standardizes whitespace formatting and method definition style in the Navigator class.  No functional changes are accomplished by this PR, just housekeeping.
SITL tested with jmavsim.
Let me know if you have any questions on this PR.  Thanks!
=> Standardize whitespace formatting in navigator_main.cpp and navigator.h

src/modules/logger/logged_topics.cpp, src/modules/logger/logged_topics.h, src/modules/logger/logger.cpp, src/modules/logger/logger.h
Can be displayed with:
ulog_info <file> -m excluded_optional_topics
=> logger: log excluded optional topics

src/systemcmds/serial_test/serial_test.c
Serial_test move g_cl and g_mod from heap to stack to save memory by not preallocating them in the data section
This saves **140 bytes of RAM** when not running serial_test
**Not fully tested** maybe @dagar his CI will cover with the automated test, otherwise it would be great if someone could test this, my current HW setup has some serial/uart problems anyhow.
=> Serial_test move g_cl and g_mod from heap to stack to save memory

src/systemcmds/serial_test/CMakeLists.txt
Please use [PX4 Discuss](http://disc
=> Fix serial_test stack warning

src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp, src/modules/sensors/voted_sensors_update.cpp
http://px4-jenkins.dagar.ca:8080/blue/organizations/jenkins/PX4-Autopilot/detail/pr-serial_test-ss/1/pipeline
=> sensors/vehicle_angular_velocity: print full sensor_selection if device id not found

src/modules/mavlink/mavlink_mission.cpp, src/modules/mavlink/mavlink_mission.h
=> mavlink: send_mission_current fix seq check

src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
Still trying to find the root cause for this rare failure during initial bootup. 
Previous change https://github.com/PX4/PX4-Autopilot/pull/19119
FYI @Igor-Misic
=> sensors/vehicle_angular_velocity: improve error handling (especially during initial selection)

src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp
- fixes https://github.com/PX4/PX4-Autopilot/issues/17380
=> local_position_estimator: move to INS0 work queue (for significantly more stack)

src/modules/sensors/sensors.cpp, src/modules/sensors/vehicle_acceleration/VehicleAcceleration.cpp, src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp, src/modules/sensors/voted_sensors_update.cpp
Trying to track down this intermittent error.
=> sensors/vehicle_angular_velocity: check vehicle_imu_status timestamp validity

src/drivers/gps/gps.cpp, src/drivers/gps/params.c
- this replaces the command line argument -s
=> drivers/gps: add new GPS_SAT_INFO parameter to enable satelitte_info

src/lib/npfg/npfg.cpp, src/lib/npfg/npfg.hpp
cross2D was implemented inside the NPFG class
This removes the use of cross products from NPFG and takes advantage of the matrix library
=> NPFG: use cross product from PX4 matrix library

msg/telemetry_status.msg, src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_main.h, src/modules/mavlink/streams/STATUSTEXT.hpp
RE: https://discuss.px4.io/t/looks-like-status-text-is-not-sent-if-heartbeat-from-gcs-is-lost/26118.
Likely needs more discussion.
=> mavlink: STATUSTEXT increase stale message timeout

src/modules/mavlink/mavlink_main.cpp
https://github.com/PX4/PX4-Autopilot/issues/19215
=> mavlink: don't reset _src_addr_initialized on parameter updates

src/drivers/power_monitor/ina238/ina238.cpp
I2C communication errors are detected and error notifications are sent.
If the processing result is other than PX4_OK, return PX4_ERROR.
None.
None.
None.
=> power_monitor: Determine I2C communication errors

src/modules/dataman/dataman.cpp
Silencing
```
ERROR [dataman] file read lseek failed, incorrect offset 362624 vs 366172 
ERROR [dataman] file read lseek failed, incorrect offset 362624 vs 366172
```
that happens when updating different PX4 versions, where dataman between versions has different file sizes. 
If function `_file_initialize` fails to read dataman file, it will recreate the whole file, so we are silencing ERROR in this case.
=> dataman: add silence flag for _file_initialize

src/modules/ekf2/EKF2.cpp
I don't see the need for this.
=> ekf2: simplify global position publication validity check

Tools/px4moduledoc/srcparser.py
Needed for https://github.com/PX4/PX4-Autopilot/pull/19232.
=> Tools/px4moduledoc: add new rpm_sensor subcategory

msg/estimator_status_flags.msg, msg/vehicle_status_flags.msg, src/lib/events/enums.json, src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/commander/state_machine_helper.cpp, src/modules/ekf2/EKF/airspeed_fusion.cpp, src/modules/ekf2/EKF/common.h, src/modules/ekf2/EKF/control.cpp, src/modules/ekf2/EKF/ekf_helper.cpp, src/modules/ekf2/EKF/estimator_interface.h, src/modules/ekf2/EKF/python/ekf_derivation/generated/beta_fusion_generated_compare.cpp, src/modules/ekf2/EKF/sideslip_fusion.cpp, src/modules/ekf2/EKF2.cpp
Non state machine pieces of https://github.com/PX4/PX4-Autopilot/pull/18787. 
- ekf2: expose dead reckoning as control status flags
- commander: directly monitor GPS validity and dead reckoning
=> commander: monitor GPS validity and EKF2 dead reckoning

src/modules/mavlink/streams/SCALED_IMU.hpp, src/modules/mavlink/streams/SCALED_IMU2.hpp, src/modules/mavlink/streams/SCALED_IMU3.hpp
- preference for accel or gyro temperature before mag
=> mavlink: SCALED_IMU streams add temperature

src/drivers/power_monitor/ina228/ina228.cpp
More could be done here but this fixes the one outstanding bug for now
=> ina228 fix sign error on current reading

platforms/nuttx/src/px4/stm/stm32_common/board_hw_info/board_hw_rev_ver.c, platforms/nuttx/src/px4/stm/stm32h7/adc/adc.cpp
@vincentpoont2 - this should fix the detection issue. Please test on V5X and V6X.
I will also create a branch with the rev 3 sensors and this fix for you to test with.
=> stm32h7 ADC and board_hw_rev_ver fixes

src/drivers/tone_alarm/ToneAlarm.cpp, src/examples/work_item/WorkItemExample.cpp, src/modules/airship_att_control/airship_att_control_main.cpp, src/modules/angular_velocity_controller/AngularVelocityController.cpp, src/modules/attitude_estimator_q/attitude_estimator_q_main.cpp, src/modules/camera_feedback/CameraFeedback.cpp, src/modules/control_allocator/ControlAllocator.cpp, src/modules/esc_battery/EscBattery.cpp, src/modules/flight_mode_manager/FlightModeManager.cpp, src/modules/fw_att_control/FixedwingAttitudeControl.cpp, src/modules/fw_autotune_attitude_control/fw_autotune_attitude_control.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp, src/modules/mc_att_control/mc_att_control_main.cpp, src/modules/mc_autotune_attitude_control/mc_autotune_attitude_control.cpp, src/modules/mc_hover_thrust_estimator/MulticopterHoverThrustEstimator.cpp, src/modules/mc_pos_control/MulticopterPositionControl.cpp, src/modules/mc_rate_control/MulticopterRateControl.cpp, src/modules/rc_update/rc_update.cpp, src/modules/rover_pos_control/RoverPositionControl.cpp, src/modules/sensors/vehicle_acceleration/VehicleAcceleration.cpp, src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp, src/modules/uuv_att_control/uuv_att_control.cpp, src/modules/uuv_pos_control/uuv_pos_control.cpp, src/modules/vtol_att_control/vtol_att_control_main.cpp
=> cleanup module callback registration failed errors

msg/CMakeLists.txt, msg/sensor_gnss_relative.msg, src/drivers/gps/definitions.h, src/drivers/gps/gps.cpp, src/drivers/uavcannode/Publishers/RelPosHeading.hpp, src/drivers/uavcannode/UavcanNode.cpp, src/modules/logger/logged_topics.cpp
- for ublox this corresponds to NAV_RELPOSNED
- requires https://github.com/PX4/PX4-GPSDrivers/pull/101
=> drivers/gps: add new sensor_gnss_relative msg

src/lib/tunes/tunes.cpp
This contains two commits related to tunes:
- The first one fixes unspecified behavior,
-  the second one just adds a warning if a tune could not be parsed.
=> Tune fixes

.ci/Jenkinsfile-compile
Adds holybro kakuteh7 to Travis CI for building and deployment to S3 for QGC
fixes #19432 
cc @vincentpoont2
=> ci: build and deploy kakuteh7

src/drivers/uavcannode/Publishers/SafetyButton.hpp
To bring cannode safety button publishing in alignment with #19413
Tested with Pixhawk4 and ARK RTK GPS
FYI @AlexKlimaj
=> cannode: safety_button topic

src/modules/ekf2/EKF2.cpp
=> ekf2: fix IMU missed perf count when not using multi-EKF

platforms/common/work_queue/hrt_queue.c, platforms/common/work_queue/hrt_thread.c, platforms/common/work_queue/hrt_work_cancel.c, platforms/posix/src/px4/common/drv_hrt.cpp
- possible fix for https://github.com/PX4/PX4-Autopilot/issues/19358
@Ncerzzk could you give this a try?
=> posix: HRT hrt_lock() sem_wait try again if error returned

src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.cpp
small clean up for the if-else statement of the function
=> small cleanup for  FlightTask::_evaluateDistanceToGround if-else

platforms/nuttx/src/px4/common/cdc_acm_check.cpp
- this is helpful with `px_uploader.py` as it doesn't require full Mavlink to be running or `systemcmds/nsh` to be available
=> platforms/nuttx: cdc_acm_check implement mavlink reboot directly

msg/vehicle_thrust_setpoint.msg, msg/vehicle_torque_setpoint.msg, src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessRotors.cpp, src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessRotors.hpp, src/modules/logger/logged_topics.cpp, src/modules/logger/logged_topics.h
- [vehicle_{thrust,torque}_setpoint.msg: fix comment](https://github.com/PX4/PX4-Autopilot/commit/0fb96128e2a6dcbd17ea1312daea51f492d136e6)
- [ActuatorEffectivenessRotors: add missing getEffectivenessMatrix](https://github.com/PX4/PX4-Autopilot/commit/47738e8371c557f195b1e02d635f9359510afee4)
- update logged topics
=> Small dynamic control allocation updates

src/drivers/tattu_can/Kconfig
maybe we can add enable tattu can driver on some board
=> add tattu_can smart battery kconfig

src/modules/mc_pos_control/MulticopterPositionControl.cpp, src/modules/mc_pos_control/MulticopterPositionControl.hpp, src/modules/mc_pos_control/PositionControl/PositionControl.cpp, src/modules/mc_pos_control/PositionControl/PositionControlTest.cpp
- fixes the initial "invalid setpoints" error.
=> mc_pos_control: require current trajectory setpoint to run controller

src/modules/mc_pos_control/MulticopterPositionControl.cpp, src/modules/mc_rate_control/MulticopterRateControl.cpp, src/modules/mc_rate_control/MulticopterRateControl.hpp
- https://github.com/PX4/PX4-Autopilot/pull/17985 had negative side effects but the invalid setpoint problem was addressed in #19162 
- Overriding the vertical acceleration already before takeoff caused problems
- Rate control naming refactoring
- Offboard takeoff was not possible anymore if the land detector didn't consider the vehicle landed (the state should be exclusive)
These changes were done Dec 2021 and I forgot to contribute before but we're flying them for quite some time.
=> Multiple Multicopter Control Improvements

src/drivers/cyphal/CanardHandle.cpp, src/drivers/cyphal/CanardHandle.hpp, src/drivers/cyphal/Cyphal.cpp
#19624 broke O1Heap statistics.
This PR correctly prints O1Heap statistics 
Thanks @JacobCrabill
=> Cyphal restore O1Heap statistics

boards/px4/fmu-v6x/init/rc.board_sensors, boards/px4/fmu-v6x/src/board_config.h, boards/px4/fmu-v6x/src/manifest.c, boards/px4/fmu-v6x/src/spi.cpp
=> px4_fmu-v6x:Add Rev 4 Sensors

src/modules/ekf2/EKF/baro_bias_estimator.cpp, src/modules/ekf2/EKF/baro_bias_estimator.hpp
The baro observation noise parameter is often over-estimated in order as a measure to mitigate temporary offsets in the readings due to wind gusts or poor pressure compensation tuning. The side effect is that the innovation sequence monitoring based on normalized innovation struggles to detect an offset in the state because the innovation isn't statistically significant.
To counter this issue, a simpler check is added to trigger the process noise boost when the innovation has the same sign for a long period of time.
SITL tested
=> Baro bias estimator improvements

boards/px4/fmu-v6c/init/rc.board_sensors
See details and discussion in https://github.com/PX4/PX4-Autopilot/pull/19706
=> px4_fmu-v6c:Fix mag rotation

boards/px4/fmu-v5x/init/rc.board_sensors, boards/px4/fmu-v5x/src/board_config.h, boards/px4/fmu-v5x/src/can.c, boards/px4/fmu-v5x/src/manifest.c, boards/px4/fmu-v5x/src/spi.cpp, boards/px4/fmu-v6x/init/rc.board_sensors, boards/px4/fmu-v6x/src/board_config.h, boards/px4/fmu-v6x/src/can.c, boards/px4/fmu-v6x/src/manifest.c, boards/px4/fmu-v6x/src/spi.cpp, src/drivers/uavcan/uavcan_drivers/stm32h7/driver/include/uavcan_stm32h7/can.hpp, src/drivers/uavcan/uavcan_drivers/stm32h7/driver/src/uc_stm32h7_can.cpp
@vincentpoont2 this is the WIP for the mini. I need to ring out the HW 100% still
=> Added PX4 VxX Mini baseboard

src/modules/attitude_estimator_q/attitude_estimator_q_main.cpp
This PR breaks up the `attitude_estimator_q_main.cpp`  `Run()` method into a sequence granular functions to better encapsulate what each method is accomplishing.
This PR is straightforward refactoring, no functional logic has been changed in the class.
Flight logs to follow when weather is more conducive.
Due to ugly nature of the single diff, I've broken this refactoring into a series of commits that are relatively straightforward to inspect.
If you have any questions or feedback on this PR please let me know!  Thanks!
-Mark
=> attitude_estimator_q Run() method refactoring

src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp, src/modules/sensors/vehicle_imu/VehicleIMU.cpp, src/modules/sensors/vehicle_imu/VehicleIMU.hpp
- fixes https://github.com/PX4/PX4-Autopilot/issues/19760
=> sensors/vehicle_imu: don't bother checking IMU_GYRO_RATEMAX

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
The current state of the fixed-wing position control module is quite dismal. It's quite hard to understand what is happening, and there is very little documentation to help readers along the way. There are also quite some artifacts and mistakenly placed logic throughout specifically because the class is hard to read.
This PR follows #19778. Tackles the second part in #19595.
**What's done?**
- documentation of units, params, returns, and descriptions for variables and methods
- rename ambiguous or erroneous state variables
- remove unused or unnecessary input arguments to functions
- remove ugly header white space
I named things what I thought was clearest. If there are disagreements, please let me know. Also for …
=> Fixed-wing position control: some incremental clean up of the class

boards/px4/fmu-v6x/init/rc.board_sensors
=> px4_fmu-v6x:HB Mini add Ver 3, Ver 4 init

src/drivers/uavcannode/Publishers/StaticPressure.hpp
This PR fixes the units in the dronecan baro receiver.
=> Fix dronecan baro units

README.md
Some links in the readme are broken and others are still pointing to the renamed master branch. 
Fixed the broken links and modified the other ones to point to the new main branch.
=> Fixed broken links in readme

src/modules/ekf2/CMakeLists.txt, src/modules/ekf2/EKF/CMakeLists.txt, src/modules/ekf2/EKF/bias_estimator.cpp, src/modules/ekf2/EKF/bias_estimator.hpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF2.cpp
The implementation is generic enough and could be used to estimate other biases.
=> ekf2: rename BaroBiasEstimator -> BiasEstimator

msg/estimator_aid_source_3d.msg, src/modules/ekf2/EKF/control.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/ekf_helper.cpp, src/modules/ekf2/EKF/estimator_interface.h, src/modules/ekf2/EKF/vel_pos_fusion.cpp, src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp
- also includes velocity and position helpers for using estimator aid
source status messages that will later be used for GPS, EV, etc
Pull request is on top of https://github.com/PX4/PX4-Autopilot/pull/19936.
=> ekf2: add AUX velocity aid src status

src/modules/ekf2/EKF/python/tuning_tools/mc_wind_estimator/readme.md
@bresch This is all pretty clear - most of this is just some cross links and readability updates.
The reason I bothered is to confirm which script to use (see inline comment)
=> mc_wind_estimator - improve readability

src/modules/ekf2/EKF/ekf_helper.cpp
- additionally require GPS speed accuracy is within EKF2_REQ_SACC
=> ekf2: fix yaw estimator velocity accuracy

src/modules/ekf2/EKF2.cpp, src/modules/replay/ReplayEkf2.cpp
We desperately need something added to CI if we want this to stop breaking silently.
fixes https://github.com/PX4/PX4-Autopilot/issues/19969
=> ekf2 replay fixes

src/drivers/imu/invensense/mpu9250/InvenSense_MPU9250_registers.hpp, src/drivers/imu/invensense/mpu9250/mpu9250_i2c_main.cpp
- possible fix for https://github.com/PX4/PX4-Autopilot/issues/19506 (not yet tested)
@navunlimited can you try this?
=> mpu9250: try all I2C addresses if not manually specified

ROMFS/px4fmu_common/init.d-posix/airframes/1042_tiltrotor
- adapt output indexes (together with https://github.com/PX4/PX4-SITL_gazebo/pull/893)
- small tuning improvements (mainly removing unnecessary params)
=> Tiltroror SITL config: fix actuator indexes

src/modules/ekf2/EKF/ekf.cpp
This is a small protection against any potential jitter in an IMU sample integration time (potentially slightly different delta angle vs delta velocity integration intervals).
=> ekf2: scale delta angle and delta velocity bias to particular IMU sample

ROMFS/px4fmu_common/init.d/airframes/4019_x500_v2, ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt
After the new control allocation in [here](https://github.com/PX4/PX4-Autopilot/pull/19990) I have added HoX500-V2 with new allocator params. 
@bkueng You may review if you can.
=> Holybro X500v2 Frame re-addition

src/modules/flight_mode_manager/tasks/AutoFollowTarget/follow_target_params.c
@junwoo091400 This appears to have been renamed. Can you confirm?
=> Fix typo follow height: FLW_TGT_HT

boards/holybro/kakuteh7/init/rc.board_defaults, boards/holybro/kakuteh7/src/board_config.h, src/lib/parameters/flashparams/flashfs.c, src/lib/parameters/flashparams/flashfs32.c
Fixes https://github.com/PX4/PX4-Autopilot/issues/20025
=> Kakuteh7 flash params & flashfs robustness improvements

.vscode/settings.json, ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator, Tools/simulation/ignition/models/x500-Depth/model.sdf, src/modules/simulation/simulator_ignition_bridge/SimulatorIgnitionBridge.cpp, src/modules/simulation/simulator_ignition_bridge/SimulatorIgnitionBridge.hpp
A clear and concise description of the problem this proposed change will solve. Or, what it will improve.
=> Pr test sim ign

src/drivers/imu/invensense/icm42670p/CMakeLists.txt, src/drivers/imu/invensense/icm42670p/ICM42670P.cpp, src/drivers/imu/invensense/icm42670p/ICM42670P.hpp, src/drivers/imu/invensense/icm42670p/InvenSense_ICM42670P_registers.hpp
Backport of #19660.
Closes #20091.
=> [BACKPORT v1.13]  drivers/imu/invensense/icm42670p: cleanup and small fixes

src/modules/navigator/navigator_main.cpp
=> Fix bug with yaw only reposition

boards/px4/fmu-v6x/init/rc.board_sensors
=> [BACKPORT v1.13] px4_fmu-v6x:HB Mini add Ver 3, Ver 4 init

src/modules/fw_att_control/FixedwingAttitudeControl.cpp
For fixedwing attitude control, the rate control was done through different code paths depending on whether the vehicle is in a attitude control mode(stabilized) or only rate control mode(Acro)
This PR unifies the rate control loop so that the rate control is always run through a single code path
We could also separate the rate control loop all together into a separate `fw_rate_control` module. 
- Follow up PR of https://github.com/PX4/PX4-Autopilot/pull/19912
=> Fixedwing att control rate loop cleanup

src/drivers/rc/crsf_rc/CrsfRc.cpp, src/drivers/rc/crsf_rc/CrsfRc.hpp
The dangers of merging stale PRs...
=> crsf_rc: trivial fixes

src/modules/simulation/simulator_ignition_bridge/SimulatorIgnitionBridge.cpp
=> simulator_ignition_bridge: fix double promotions

boards/modalai/fc-v1/src/board_config.h, boards/modalai/fc-v2/src/board_config.h, src/drivers/actuators/modalai_esc/modalai_esc.cpp, src/drivers/actuators/modalai_esc/modalai_esc.hpp, src/drivers/actuators/modalai_esc/modalai_esc_params.c
Was having git hell with trying to get things clean.... just made a new PR:
- updated turtle mode to better reflect user experience expectations
- abstract default UART ESC port to boards file
- fix bug with feedback parsing
=> modalai_esc: maintenance release 1

platforms/posix/src/px4/common/lockstep_scheduler/src/lockstep_scheduler.cpp, src/modules/simulation/simulator_ignition_bridge/SimulatorIgnitionBridge.cpp, src/modules/simulation/simulator_ignition_bridge/SimulatorIgnitionBridge.hpp
=> simulator_ignition_bridge: wait for first clock set before returning successfully

boards/px4/fmu-v5x/src/manifest.c, boards/px4/fmu-v5x/src/spi.cpp, boards/px4/fmu-v6x/src/board_config.h, boards/px4/fmu-v6x/src/manifest.c, boards/px4/fmu-v6x/src/spi.cpp
This includes two fixup commits from #20182 against `main`.
FYI @vincentpoont2.
=> [FORWARDPORT] Add Holybro Pixhawk Pi CM4 Baseboard Support review fixup

boards/px4/fmu-v6c/init/rc.board_sensors, boards/px4/fmu-v6c/src/board_config.h, boards/px4/fmu-v6c/src/i2c.cpp, platforms/common/i2c.cpp, platforms/common/include/px4_platform_common/i2c.h, src/lib/drivers/device/nuttx/I2C.hpp, src/lib/drivers/device/posix/I2C.hpp, src/lib/sensor_calibration/Utilities.cpp
=> [BACKPORT v1.13] Pixhawk 6C external bus hack

platforms/posix/CMakeLists.txt
- possible fix for https://github.com/PX4/PX4-Autopilot/issues/20229
=> platforms/posix: restore none SITL helper target for replay

src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
- if mag calibration parameters change only reset any inflight mag cal for the corresponding magnetometer
=> sensors/vehicle_magnetometer: more granular in flight mag cal reset on parameter changes

boards/modalai/voxl2/voxl-px4, boards/modalai/voxl2/voxl-px4.config, src/modules/muorb/apps/CMakeLists.txt, src/modules/muorb/apps/muorb_main.cpp, src/modules/muorb/apps/uORBAppsProtobufChannel.cpp, src/modules/muorb/apps/uORBAppsProtobufChannel.hpp, src/modules/muorb/slpi/CMakeLists.txt, src/modules/muorb/slpi/uORBProtobufChannel.cpp, src/modules/muorb/slpi/uORBProtobufChannel.hpp, src/modules/muorb/test/MUORBTest.cpp, src/modules/muorb/test/MUORBTest.hpp
Adds a self-test feature to the VOXL 2 muorb module to verify that all dependencies are properly working.
Sends some test messages back and forth and verifies their integrity at the endpoint.
=> Added a self test feature to the VOXL 2 muorb module

src/drivers/cyphal/NodeManager.cpp, src/drivers/distance_sensor/tfmini/tfmini_parser.cpp, src/drivers/gps/gps.cpp
A clear and concise description of the problem this proposed change will solve. Or, what it will improve.
=> fix potential security issues

boards/ark/fmu-v6x/src/board_config.h, boards/ark/fmu-v6x/src/manifest.c, boards/ark/fmu-v6x/src/mtd.cpp, boards/ark/fmu-v6x/src/spi.cpp
https://review.px4.io/plot_app?log=f5f338eb-8b69-4ed4-b4d5-b87e94a96d41
=> 1.13 Backport Fix ARKV6X control allocator with base boards

src/drivers/barometer/ms5611/ms5611.cpp
=> [BACKPORT v1.13] ms5611: ignore reading 0

src/modules/navigator/vtol_takeoff.cpp
Found this typo while reading VTOL code.
=> vtol_takeoff: fix comment typo

Tools/module_config/generate_actuators_metadata.py, src/lib/component_information/CMakeLists.txt, src/lib/component_information/generate_component_general.py, src/lib/component_information/generate_crc.py, src/lib/parameters/px4params/jsonout.py, src/lib/parameters/px_generate_params.py, src/lib/parameters/px_process_params.py, src/modules/logger/CMakeLists.txt, src/modules/logger/logger.cpp, src/modules/logger/logger.h, src/modules/logger/messages.h
Allows to decode events not (yet) on `main`.
The file is currently ~15KB.
=> Log events metadata

ROMFS/px4fmu_common/init.d/rcS
As they might need to reserve the pwm pins.
=> fix ROMFS: run camera trigger, capture and PPS before pwm_out

Tools/setup/ubuntu.sh
update ubuntu.sh comment to include 22.04 and remove 16.04
=> Update ubuntu.sh comment to include 22.04

src/lib/drivers/device/Device.hpp
- constructor use available setters
=> lib/drivers/device: Device.hpp fully init devid

ROMFS/px4fmu_common/init.d/airframes/50003_aion_robotics_r1_rover, ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt
This was dropped in f454dcef6b7e71c742b
@dk7xe
=> airframes: add r1 again

README.md
Replace the Slack badge with our new Discord home!
=> Convert README to Discord

src/drivers/osd/msp_osd/module.yaml, src/drivers/osd/msp_osd/msp_osd.cpp, src/drivers/osd/msp_osd/uorb_to_msp.cpp
This is a cleanup of the msposd driver. A small list of fixes/adds:
* Fixed clearing arming word if  flightmode unknown
* Added power and cell voltage elements
* New OSD layout
* Fixed home direction/distance are now correct
=> MSP OSD misc fixes

.github/ISSUE_TEMPLATE/2_Feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Was checking out other pull request and noticed slack was still linked.
Updated doc
=> PULL_REQUEST_TEMPLATE.md to Discord

platforms/qurt/src/px4/tasks.cpp
On a previous PR made for tasks.cpp for QURT there was some code commented out due to drv_hrt.cpp not being implemented. Now that it is there, this code can be uncommented and is functional.
Uncommented necessary code snippets and included the correct headers.
This was tested on the muorb module on slpi by calling some of the tasks functions to ensure it was running correctly.
=> Qurt Tasks (uncommenting) Implementation

src/modules/commander/HealthAndArmingChecks/checks/sdcardCheck.cpp, src/modules/commander/HealthAndArmingChecks/checks/sdcardCheck.hpp, src/modules/commander/commander_params.c
The check is enabled by default
=> commander: add preflight check for hardfault files on SD card

src/modules/commander/HealthAndArmingChecks/checks/offboardCheck.cpp, src/modules/commander/HealthAndArmingChecks/checks/offboardCheck.hpp
This is a regression from https://github.com/PX4/PX4-Autopilot/pull/20172
Fixes https://github.com/PX4/PX4-Autopilot/issues/20519
=> fix commander: check that offboard_control_mode data is recent

boards/nxp/ucans32k146/src/board_config.h, boards/nxp/ucans32k146/src/timer_config.cpp, platforms/nuttx/src/px4/nxp/s32k1xx/include/px4_arch/io_timer.h
UCANS32K146 Add support for 2nd PWM
=> UCANS32K146 Add support for 2nd PWM

boards/modalai/voxl2/src/board_config.h, platforms/common/include/px4_platform_common/log.h, platforms/qurt/include/qurt_log.h
A clear and concise description of the problem this proposed change will solve. Or, what it will improve.
Minor cleanup of the code to add orb communicator dependency as well as move defines dependency into qurt_log.h.
No alternatives as this is a cleanup.
This was tested by compiling and running the muorb communicator test.
=> Qurt board config cleanup

src/systemcmds/ver/ver.cpp
=> systemcmds/ver: remove duplicate header

platforms/nuttx/src/px4/common/cdc_acm_check.cpp, src/drivers/rc/crsf_rc/CrsfRc.cpp, src/drivers/safety_button/SafetyButton.cpp, src/modules/microdds_client/microdds_client.cpp
With the latest main, I am getting some compilation errors due to missing includes, in my development branches.
These changes fix my issues, I believe that they are correct for others as well
=> Compilation fixes

.ci/Jenkinsfile-hardware
- stackcheck build is so slow it will trigger the logger watchdog (error fails Jenkins)
=> Jenkinsfile-hardware: don't run logger on stack check build

src/lib/mathlib/math/WelfordMean.hpp, src/lib/mathlib/math/WelfordMeanVector.hpp
@bresch pointed this out - so i deleted :D
=> welford mean: remove old comments

platforms/common/uORB/uORBCommunicator.hpp, platforms/common/uORB/uORBDeviceMaster.cpp, platforms/common/uORB/uORBDeviceNode.cpp, platforms/common/uORB/uORBDeviceNode.hpp, platforms/common/uORB/uORBManager.cpp, platforms/common/uORB/uORBManager.hpp, src/modules/muorb/apps/uORBAppsProtobufChannel.cpp, src/modules/muorb/slpi/uORBProtobufChannel.cpp
There was an issue sending a message from slpi to apps. Seems the code was stuck in an loop and crashed when the message was sent from slpi to apps. This PR solves this problem
Adding necessary code to allow slpi to not be caught in advertisement loop and crash.
Currently no alternatives
Tested by running qshell to send message from slpi to apps - no crashing.
=> Qurt UORB Communicator Update

src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/ekf_helper.cpp, src/modules/ekf2/EKF2.cpp
- usage replaced with now public calcRotVecVariances()
=> ekf2: delete orientation_covariances_euler()

platforms/nuttx/src/px4/stm/stm32_common/board_hw_info/board_hw_rev_ver.c
Upstreaming short fixes for board_hw_rev_ver.c file
=> Board hw rev ver fixes

src/lib/drivers/device/CMakeLists.txt, src/lib/drivers/device/i2c.h, src/lib/drivers/device/qurt/I2C.cpp, src/lib/drivers/device/qurt/I2C.hpp, src/lib/drivers/device/qurt/SPI.cpp, src/lib/drivers/device/qurt/SPI.hpp, src/lib/drivers/device/qurt/uart.c, src/lib/drivers/device/qurt/uart.h, src/lib/drivers/device/spi.h
Adding in device driver library support for the Qurt platform
=> Device drivers library for Qurt platform

.github/workflows/sitl_tests.yml
- unfortunately this is often too slow for github actions
=> github actions: diable vtol_standard address sanitizer test

src/modules/vtol_att_control/tailsitter.cpp
Should fix the regression introduced by https://github.com/PX4/PX4-Autopilot/pull/20704
=> Fixed tailsitter not transitioning

boards/px4/fmu-v6x/init/rc.board_sensors
just saw that this got lost while resolving conflicts
=> v6x: bugfix

boards/nxp/mr-canhubk3/src/board_config.h, boards/nxp/mr-canhubk3/src/s32k3xx_clockconfig.c, boards/nxp/mr-canhubk3/src/s32k3xx_periphclocks.c, boards/nxp/ucans32k146/src/board_config.h, boards/nxp/ucans32k146/src/clockconfig.c, boards/nxp/ucans32k146/src/periphclocks.c
Backport S32K periphclocks dynamic periphclocks array
Tested on 
UCANS32K146
MR-CANHUBK3
=> S32K Dynamic periphclocks

ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator
- "ign gazebo" command is now "gz sim" as of Gazebo Garden
=> px4-rc.simulator support launching new Gazebo Garden vs Fortress

ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator
=> px4-rc.simulator shellcheck fixes

src/modules/ekf2/EKF2.cpp
=> ekf2: fix global_pos alt_reset_counter publish

src/modules/sensors/sensor_params_mag.c
follow-up on https://github.com/PX4/PX4-Autopilot/pull/20723#pullrequestreview-1245713011
=> hide legacy read-only parameter under Developer category

src/drivers/actuators/modalai_esc/modalai_esc.cpp
The values in the updateOutput callback are already handling the mapping of output "ID" to motor number...  We were then again re-mapping based upon the same params, causing havoc in most use cases but my first test case!
I've tested this on a couple different hardware setups, and turtle mode, and it looks good now.
=> modalai_esc - fix ESC ID to Motor remap regression

src/lib/wind_estimator/WindEstimator.cpp, src/lib/wind_estimator/WindEstimator.hpp, src/modules/airspeed_selector/airspeed_selector_params.c
No functional changes, just some clean up. See commits for details.
I originally wanted to change how the airspeed scale variance is initialized, but then decided to bring this in independently as I haven't found yet a good solution for the variance init.
=> Wind estimator mini clean up

platforms/nuttx/src/px4/common/px4_mtd.cpp
The compiler says so
Signed-off-by: AuroraRAS <chplee@gmail.com>
compile-time errors:
```
PX4-Autopilot/platforms/nuttx/src/px4/common/px4_mtd.cpp:311:31: error: the address of 'instances' will never be NULL [-Werror=address]
PX4-Autopilot/platforms/nuttx/src/px4/common/px4_mtd.cpp:447:23: error: the address of 'instances' will never be NULL [-Werror=address]
```
- Avoid condition `instances == nullptr`
=> the address of 'instances' will never be NULL

src/modules/mc_pos_control/mc_pos_control_params.c
Got notified that the description of this param is outdated.
=> MPC: improve description of MPC_LAND_RC_HELP

src/modules/simulation/gz_bridge/GZBridge.cpp, src/modules/simulation/gz_bridge/GZBridge.hpp
Use `AirSpeedSensor` message instead of `FluidPressure`
=> Use airspeed sensor msgs

ROMFS/px4fmu_common/init.d-posix/airframes/4003_gz_rc_cessna, Tools/simulation/gz/models/rc_cessna/model.sdf
The plane model (`rc_cessna`) had a few problems with flying
- The control surfaces were quite sluggish due to the joint controller gains being too low
- The vehicle does not have an airspeed sensor, but still checks for one. Resulting in the preflight checks failing
- The prearm mode was disabled and therefore was hard to actuate control surfaces when on the ground.
- The rudder was not actuated since the joint controller was not mapped to do so
- Increased gains on the joint controller of control surfaces
- Map rudder
- Disable airspeed checks and enable pre-arm mode
@ahcorde @bperseghetti FYI
```
make px4_sitl gz_rc_cessna
```
=> Tune GZ plane (rc_cessna) to fly nicely

src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
Rebase of https://github.com/PX4/PX4-Autopilot/pull/19873, because I don't have write permissions there.
=> Landing position updates for precision landing

src/modules/navigator/rtl_params.c
=> typo corrected in file rtl_params.c

boards/holybro/kakuteh7mini/src/board_config.h, boards/holybro/kakuteh7v2/src/board_config.h
This just always switches the VTX+ power on.
=> kakuteh7v2/mini: switch on VTX+

src/modules/navigator/MissionFeasibility/FeasibilityCheckerTest.cpp
=> tests: empty parentheses were disambiguated as a function declaration

src/modules/airspeed_selector/AirspeedValidator.hpp
Left over from https://github.com/PX4/PX4-Autopilot/pull/20678
=> AirspeedSelector: remove unused variable

src/drivers/imu/invensense/icm42688p/ICM42688P.cpp
=> icm42688p: fix comment about gyro and accel bits

.ci/Jenkinsfile-compile
Adds ThePeach FCC-K1 & FCC-R1 to Travis CI for building.
=> ci: build thepeach FCC-K1 & FCC-R1

ROMFS/px4fmu_common/init.d-posix/airframes/4001_gz_x500, ROMFS/px4fmu_common/init.d-posix/airframes/4002_gz_x500_depth, ROMFS/px4fmu_common/init.d-posix/airframes/4003_gz_rc_cessna, ROMFS/px4fmu_common/init.d-posix/airframes/4004_gz_standard_vtol, ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator, Tools/simulation/gz/models/rc_cessna/model.sdf, Tools/simulation/gz/models/standard_vtol/model.sdf, Tools/simulation/gz/models/x500/model.sdf, Tools/simulation/gz/worlds/default.sdf, src/modules/simulation/gz_bridge/GZBridge.cpp, src/modules/simulation/gz_bridge/GZBridge.hpp
Added Airpressure sensor that allows to setup the barometer in Gazebo
FYI @Jaeyoung-Lim @bperseghetti @dagar
=> Simulation Gazebo: Use Gazebo Airpressure sensor

src/systemcmds/mtd/mtd.cpp
This is a fix for systemcmds/mtd **rwtest** where the test was not actually testing the physical device. 
I was debugging the Block Device Driver with **rwtest** when I notice that it execute a little bit too fast (thanks to @bkueng noticing this on EEPROM tests).
Block Device has its own buffer and logic to not write to the device unless it needs to change sector. 
So in the case where the FRAM sector size is 512 bytes and we are writing 128-byte chunks, it will use its buffer to write 4x chunks of 128 bytes before it will physically write data over SPI. This means the read command that is going after write will use data from the 512-byte-sized buffer.
I've decided to use this KISS method by doing `fsync` and `close(fd)` after writing. This way 128-byte chunk will be physically written …
=> systemcmds/mtd: fix rwtest - force data to/from the device 

src/modules/ekf2/EKF/ev_yaw_control.cpp
=> ekf2: fix controlEvYawFusion() yaw reset

Tools/setup/ubuntu.sh
When ubuntu.sh file was updated I found that the script could not be run. Described here: https://github.com/PX4/PX4-Autopilot/commit/22030c1b8ce4c934bcebc71f8a399959a30da935#comments
Fixes issue described here https://github.com/PX4/PX4-Autopilot/commit/22030c1b8ce4c934bcebc71f8a399959a30da935#comments
- Remove comment from line 87
[Related links, screenshot before/after, video](https://github.com/PX4/PX4-Autopilot/commit/22030c1b8ce4c934bcebc71f8a399959a30da935#comments)
=> Remove comment from line 87

Tools/px4moduledoc/srcparser.py
- Add the possibility in the parser to replace the defines made in the current file with their argument (includes are not supported)
- Add the possibility for the parser to parse int argument with bitwise shift operators
@KonradRudin fyi
=> Tools: extend documentation parser

src/modules/ekf2/EKF/mag_control.cpp
Currently in ekf2 mag control mag_3d isn't allowed to update all states until it's been > 5 seconds after mag_aligned_in_flight to "allow the magnetic field state estimates to stabilise". Often mag_aligned_in_flight happens long before mag_3d is ever activated, so I don't think this is correct.
This PR removes the 5s check and replaces it checking the mag bias variance. The requirement is a bit arbitrary and pulled from casually inspecting a few logs.
=> ekf2: mag_3d check mag bias variance before allowed to update all states (orientation)

src/modules/mavlink/Kconfig, src/modules/mavlink/mavlink_parameters.cpp, src/modules/mavlink/mavlink_parameters.h
=> mavlink: add kconfig option to disable UAVCAN parameter bridge

src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/mag_control.cpp
Small safe piece of mag control cleanup broken out of https://github.com/PX4/PX4-Autopilot/pull/20933.
=> ekf2: merge runOnGroundYawReset() + runInAirYawReset() into unified magReset()

src/modules/land_detector/MulticopterLandDetector.cpp
In case of biased velocity measurements (e.g.: due to poor GNSS coverage), the velocity state can be biased and makes land detection impossible.
Z deriv is the numerical derivative of the position state that does not drift when aided by a position measurement even if the velocity state is biased. Using it there allows for a better land detection in presence of bad velocity data.
SITL with artificial biased GNSS vel data
=> MC not disarming due to bad GNSS data

src/drivers/uavcannode/Kconfig, src/drivers/uavcannode/UavcanNode.cpp
- a hygrometer is what measures humidity
FYI @AlexKlimaj
=> drivers/uavcannode: fix typo (hydrometer->hygrometer)

src/drivers/gps/params.c
=> gps: fix protocol param max

src/modules/ekf2/EKF/estimator_interface.cpp
=> ekf2: remove duplicate buffer push of system flags

src/lib/tecs/TECS.cpp
Fixes regression that slipped in with https://github.com/PX4/PX4-Autopilot/pull/21345.
The throttle prediction was completely off.
=> tecs: fix throttle prediction

src/modules/gimbal/output_rc.cpp
- small typo introduced in https://github.com/PX4/PX4-Autopilot/pull/20837
FYI @sfuhrer
=> gimbal: output RC fix actuator_controls_2 -> gimbal_controls regression

src/drivers/gps/CMakeLists.txt, src/drivers/gps/gps.cpp, src/drivers/gps/params.c
=> Sbf heading

src/modules/navigator/mission.cpp, src/modules/navigator/navigator.h, src/modules/navigator/navigator_main.cpp, src/modules/navigator/rtl.cpp, src/modules/navigator/rtl.h
Fixes by parts regressions that came in with https://github.com/PX4/PX4-Autopilot/pull/21390, and in other parts things that were still broken even before that PR.
See commits for more details.
=> RTL: fix Mission RTL vs normal RTL

src/modules/fw_pos_control/FixedwingPositionControl.cpp
While testing https://github.com/PX4/PX4-Autopilot/pull/21345 I realized that setting AIRSPD_MIN or MAX equal to TRIM and enabling the airspeed to throttle prediction can lead to weird behavior due to division by 0.
Guard against division by 0. Also clean up the code a bit by separating the calculation of the slopes from the rest.
=> FWPositionControl: trim throttle calc: guard against min/max=trim airspeed

src/drivers/actuators/modal_io/modal_io_params.c, src/lib/parameters/px4params/srcparser.py, validation/module_schema.yaml
Allow both rpm and RPM units for parameters
=> Allow both rpm and RPM units for parameters

src/modules/ekf2/ekf2_params.c
=> Update ekf2_params.c - typo EKF2 aid mask

src/modules/gimbal/gimbal.cpp
This adds the ability to manually set who has primary control over a gimbal and also adds printing it as part of the status.
This is helpful, especially while working on the QGC gimbal v2 implementation.
=> gimbal: add control setter and status

src/modules/commander/level_calibration.cpp
Unused processes were deleted.
Refactoring
None
None
None
None
=> commander: Delete unused processes

src/modules/mavlink/module.yaml
=> mavlink: flow control param needs reboot

src/modules/mc_pos_control/MulticopterPositionControl.cpp, src/modules/mc_pos_control/PositionControl/PositionControl.cpp, src/modules/mc_pos_control/PositionControl/PositionControl.hpp
=> Fix MC thrust spike

src/systemcmds/netman/netman.cpp
cherry pick of commit 2f448e9d9f3996698dffc5d24e90b405bc55c045 from the main branch
minor update to the netman docs to clarify the usage of netman and how it works
https://github.com/PX4/PX4-Autopilot/pull/21664
=> [BACKPORT] netman: update module description (#21664)

src/systemcmds/netman/netman.cpp
Follow up to #21664 which broke CI.
=> netman: fix line too long

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
- Remove unnecessary text rendering, which made clicking log links harder
- Re adjust markdown elements to make it easier to read / intuitive when creating an issue
- Fix wrong label for feature request template (which prevented automatic labeling)
=> Update Issue templates

src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessHelicopter.cpp, src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessHelicopter.hpp, src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessHelicopterTest.cpp, src/modules/control_allocator/ControlAllocator.cpp, src/modules/control_allocator/ControlAllocator.hpp, src/modules/control_allocator/module.yaml
as a separate CA_AIRFRAME, as the UI cannot switch between servo/motor.
EDIT: untested
=> helicopter: add tail servo support

src/modules/navigator/MissionFeasibility/FeasibilityChecker.cpp
I was poking around code and saw this duplicated line.
removed it
N/A
=> (Mission) FeasibilityChecker: remove duplicate line

src/drivers/distance_sensor/lightware_laser_i2c/lightware_laser_i2c.cpp, src/drivers/distance_sensor/lightware_laser_i2c/parameters.c
=> lightware_laser_i2c: add SF30/D

src/examples/fake_magnetometer/CMakeLists.txt
Add necessary dependencies, otherwise compilation cannot pass！
=> fake_magnetometer: add dpends=fake_magnetometer

src/drivers/barometer/invensense/icp201xx/ICP201XX.cpp
=> [backport] icp201: increase startup delay (FMUv6X)

ROMFS/px4fmu_common/init.d/airframes/4019_x500_v2
From https://github.com/PX4/PX4-Autopilot/pull/21840
=> [1.14] airframes/x500_v2: move motors from AUX to MAIN

ROMFS/px4fmu_common/init.d/airframes/4019_x500_v2
Requested from https://github.com/PX4/PX4-Autopilot/pull/21349#issuecomment-1627770924
@vincentpoont2 fyi
Requires docs to be updated
=> airframes/x500_v2: move motors from AUX to MAIN

src/modules/ekf2/test/test_EKF_gps.cpp
We broke that logic once (https://github.com/PX4/PX4-Autopilot/pull/21871) and I want to make sure it's the last time.
add a unit test
=> ekf2: add more unit tests for GNSS stopping control logic

boards/diatone/mamba-f405-mk2/init/rc.board_defaults, boards/flywoo/gn-f405/init/rc.board_defaults, boards/holybro/kakutef7/init/rc.board_defaults, boards/holybro/kakuteh7/init/rc.board_defaults, boards/omnibus/f4sd/init/rc.board_defaults, boards/raspberrypi/pico/init/rc.board_defaults, boards/spracing/h7extreme/init/rc.board_defaults, src/modules/attitude_estimator_q/attitude_estimator_q_params.c, test/mavsdk_tests/autopilot_tester.cpp
Updates from https://github.com/PX4/PX4-Autopilot/pull/21922, as I've seen the test failing in CI.
=> mavsdk tests offboard attitude updates

Tools/auterion/remote_update_fmu.sh, Tools/auterion/upload_skynode.sh, boards/px4/fmu-v5x/cmake/upload.cmake, boards/px4/fmu-v6x/cmake/upload.cmake
1:1 port for 1.14 to allow developers to flash the release on Skynode https://github.com/PX4/PX4-Autopilot/pull/21842
=> [1.14] Auterion Skynode upload scripts

src/lib/conversion/rotation.h, src/lib/sensor_calibration/Magnetometer.cpp, src/lib/sensor_calibration/Magnetometer.hpp, src/modules/commander/mag_calibration.cpp, src/modules/mavlink/mavlink_messages.cpp, src/modules/sensors/module.yaml
replaces https://github.com/PX4/PX4-Autopilot/pull/20247
```
Allow arbitrary rotation of external mag
New parameter: CAL_MAG[0-3]_[ROLL|PITCH|YAW]
Documentation: need update
```
- Bench tests
=> Enable arbitrary euler angle for Mag rotation [NEW]

src/drivers/differential_pressure/asp5033/ASP5033.cpp
=> asp5033: fix K value

msg/ActuatorTest.msg
https://github.com/PX4/PX4-Autopilot/issues/22029
@spiderkeys
=> msg: set all ORB_QUEUE_LENGTH to actual rounded value

src/drivers/power_monitor/ina228/ina228.h
Update comment wording to "Charge Result" from "Energy Result" as this is reading from the charge register
=> Update ina228.h comment typo

boards/px4/fmu-v6x/init/rc.board_sensors
=> [BACKPORT v1.14] 6x: fix internal mag rotation

src/drivers/optical_flow/paa3905/PAA3905.cpp, src/drivers/optical_flow/paa3905/PAA3905.hpp, src/drivers/optical_flow/paw3902/PAW3902.cpp, src/drivers/optical_flow/paw3902/PAW3902.hpp, src/modules/sensors/vehicle_optical_flow/VehicleOpticalFlow.cpp, src/modules/sensors/vehicle_optical_flow/VehicleOpticalFlow.hpp
Cherry-picking https://github.com/PX4/PX4-Autopilot/pull/22086 for v1.14 release.
=> drivers/optical_flow/paw3902: backup scheduling to fetch 0 flow v1.14 backport

src/modules/fw_pos_control/FixedwingPositionControl.cpp, src/modules/fw_pos_control/FixedwingPositionControl.hpp
port of https://github.com/PX4/PX4-Autopilot/pull/22101
=> [1.14 port] FW Positon Controller: set references to 0 if not provided by local_position

src/modules/uxrce_dds_client/dds_topics.h.em, src/modules/uxrce_dds_client/uxrce_dds_client.cpp
To enable more accurate timing, change uxrce_dds_client to use px4_poll with specific subscription update interval for getting uorb data instead of sleeping with px4_usleep.
In systems where system tick length is long (e.g. 10ms) the uxrce topic update rate is too low for offboard mode control. With 10ms system tick length the px4_usleep(1000) ends up variable 10ms-20ms sleep time, which causes e.g. 100Hz topic update rate dropping down below 50Hz in MicroXRCE-dds-agent end.
Using px4_poll with specified subscription rate to get updates from uORBs instead of sleeping in the end of update loop. New implementation also reduce the uxrce task load: Pixhawk5x case the original load is 5% and with new impl the load is changing between 4.0% - 4.3%.
This solution also …
=> microxrce_client to use px4_poll for uorb subs

src/drivers/uavcan/Kconfig, src/drivers/uavcan/sensors/sensor_bridge.cpp, src/drivers/uavcan/uavcan_main.cpp, src/drivers/uavcan/uavcan_main.hpp
Kconfig for subscribers and controllers for uavcan driver. Implemented to address Issue https://github.com/PX4/PX4-Autopilot/issues/21836
=> Kconfig subs and controllers for uavcan

src/modules/mavlink/streams/VFR_HUD.hpp
https://discord.com/channels/1022170275984457759/1022186266957201480/1156786412729933824
Also check thrust in x for FW.
```
Bugfix: Fix  throttle display in VFR_HUD mavlink message
```
Has to be ported to 1.14.
=> vfr_hud: fix throttle display for FW

src/modules/mavlink/streams/VFR_HUD.hpp
Port of https://github.com/PX4/PX4-Autopilot/pull/22154 to 1.14
=> vfr_hud: fix throttle display for FW and show magnitude for 3D thrust

src/drivers/rc/crsf_rc/CrsfParser.cpp
From https://github.com/PX4/PX4-Autopilot/pull/22152
=> [BACKPORT 1.14] fix crsf_rc: prevent potential buffer overflow for unknown packets

src/modules/ekf2/EKF/airspeed_fusion.cpp, src/modules/ekf2/EKF/common.h, src/modules/ekf2/EKF/covariance.cpp, src/modules/ekf2/EKF/drag_fusion.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/ekf_helper.cpp, src/modules/ekf2/EKF/gps_yaw_fusion.cpp, src/modules/ekf2/EKF/gravity_fusion.cpp, src/modules/ekf2/EKF/mag_fusion.cpp, src/modules/ekf2/EKF/optflow_fusion.cpp, src/modules/ekf2/EKF/python/ekf_derivation/derivation.py, src/modules/ekf2/EKF/python/ekf_derivation/derivation_utils.py, src/modules/ekf2/EKF/python/ekf_derivation/generated/state.h, src/modules/ekf2/EKF/sideslip_fusion.cpp, src/modules/ekf2/EKF/yaw_fusion.cpp
Modifying the state definition requires to update several files carefully. 
Define the state structure in the python derivation and generate all the structures and indexing automatically.
The state is a manifold composite an is defined as follows:
```
State = Values(
quat_nominal = sf.V4(),
vel = sf.V3(),
pos = sf.V3(),
gyro_bias = sf.V3(),
accel_bias = sf.V3(),
mag_I = sf.V3(),
mag_B = sf.V3(),
wind_vel = sf.V2()
)
```
unit tests
=> EKF2: centralized auto-generated state

ROMFS/px4fmu_common/init.d/airframes/4019_x500_v2
=> [BACKPORT 1.14] Fix Default Output Protocol - Airframe 4019_x500_v2

boards/px4/sitl/src/sitl_led.c, platforms/common/work_queue/hrt_thread.c, platforms/common/work_queue/work_thread.c, platforms/posix/include/hrt_work.h, src/lib/rc/rc_tests/RCTest.cpp
Firmware does not build under macOS in current main
Fixes the problems described in this discuss thread: https://discuss.px4.io/t/tbb-disabled-causes-multiple-errors-in-make-px4-sitl-jmavsim/32517/2
=> fix macos compile issues

src/modules/ekf2/EKF/python/tuning_tools/baro_static_pressure_compensation/baro_static_pressure_compensation_tuning.py, src/modules/ekf2/EKF/python/tuning_tools/baro_static_pressure_compensation/requirements.txt
Field name changed in vehicle_gps_position
=> update baro static pressure compensation tuning script

src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTiltrotorVTOL.cpp
Port of https://github.com/PX4/PX4-Autopilot/pull/21990 to 1.14
I think this one is critical enough to be back-ported to 1.14. I've test flown it.
=> TiltrotorEffectiveness: limit thrust axis tilt to z effectiveness scale

src/modules/ekf2/CMakeLists.txt, src/modules/ekf2/EKF/CMakeLists.txt, src/modules/ekf2/EKF/aid_sources/EstimatorAidSource.hpp, src/modules/ekf2/EKF/aid_sources/ZeroGyroUpdate.cpp, src/modules/ekf2/EKF/aid_sources/ZeroGyroUpdate.hpp, src/modules/ekf2/EKF/aid_sources/ZeroVelocityUpdate.cpp, src/modules/ekf2/EKF/aid_sources/ZeroVelocityUpdate.hpp, src/modules/ekf2/EKF/control.cpp, src/modules/ekf2/EKF/ekf.cpp, src/modules/ekf2/EKF/ekf.h
This is nothing fancy, but I figure we can start simple and evolve the interface as needed. The important thing is to get some structure in place rather than having data for absolutely everything scattered in one monster class.
=> ekf2: create simple estimator aid source base class

src/lib/CMakeLists.txt, src/lib/airspeed/airspeed.cpp, src/lib/airspeed/airspeed.h, src/lib/atmosphere/CMakeLists.txt, src/lib/atmosphere/atmosphere.cpp, src/lib/atmosphere/atmosphere.h, src/lib/atmosphere/test_atmosphere.cpp, src/modules/sensors/vehicle_air_data/VehicleAirData.cpp, src/modules/sensors/vehicle_air_data/VehicleAirData.hpp
I need some of these function for the fixed wing performance work, but for the sake of not overloading I separated this from #22091
=> Added library for atmosphere calculations

SECURITY.md
We have received two vulnerability reports over the last few weeks, and going through the report process, I realized we don't explain how to report, and what to expect. This is just a first step, more to come.
=> Security Vulnerability Reporting

Tools/simulation/gz/models/advanced_plane/model.sdf
Moves paths for advanced plane files from personal directory (frede791) to PX4 directory on fuel. 
Adjust url path.
=> updated url paths for gz advanced plane

src/modules/navigator/rtl.cpp
Currently if a VTOl is in multicopter mode or a multicopter is used, the RTL still uses and loiter to alt approach for RTL, if it was uploaded. For multicopter and VTOL in RW mode, we want the system to directly fly to the home or RTL destination without using approaches.
- Only use approaches when it is reported that the system is a vtol and in fixed wing mode.
```
Bugfix Only use RTL approaches for vtols in fixed wing mode
```
=> rtl: Only use approaches for vtols in fixed wing mode

src/modules/simulation/gz_bridge/GZBridge.cpp
updated warning to prevent warning not appearing in .txt file
=> updated warning

src/modules/fw_autotune_attitude_control/fw_autotune_attitude_control.cpp, src/modules/mc_autotune_attitude_control/mc_autotune_attitude_control.cpp
backport of https://github.com/PX4/PX4-Autopilot/pull/22395
=> [RELEASE/1.14] Autotune: fix state machine stuck in "Initializing"

test/mavsdk_tests/test_vtol_figure_eight.cpp
When ... I found that ...
- Add ... for ...
- Refactor ...
```
```
=> mavsdk figure 8 test: Increase time of timeout

src/modules/mavlink/mavlink_mission.cpp, src/modules/navigator/mission.cpp
2 smaller things I found when going through the code:
- [fix comparison logic for saving mission state](https://github.com/PX4/PX4-Autopilot/commit/96c2b51a9b5c32684699b1a47ae21554bc68c8cf)
- [publish mission after updating dataman](https://github.com/PX4/PX4-Autopilot/commit/d982dde3d181b22d140af3e5d811a243333a2f4a)
=> Minor mission fixes

src/modules/ekf2/EKF/aux_global_position.hpp, src/modules/ekf2/EKF/baro_height_control.cpp, src/modules/ekf2/EKF/common.h, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/estimator_interface.cpp, src/modules/ekf2/EKF/ev_height_control.cpp, src/modules/ekf2/EKF/gnss_height_control.cpp, src/modules/ekf2/EKF/gps_control.cpp, src/modules/ekf2/EKF/height_bias_estimator.hpp, src/modules/ekf2/EKF/height_control.cpp, src/modules/ekf2/EKF/position_bias_estimator.hpp, src/modules/ekf2/EKF/range_height_control.cpp, src/modules/ekf2/test/sensor_simulator/ekf_wrapper.cpp
clash between different enums (see https://github.com/PX4/PX4-Autopilot/actions/runs/7088316358/job/19290522490?pr=22411)
scope using `enum class`
=> EKF2: scope fusion control enums

Tools/setup/arch.sh, Tools/setup/ubuntu.sh, platforms/common/spi.cpp, src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessRotors.cpp, src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessRotors.hpp
When I installed Arch on one of my computers. I went through the setup script. With some minor modifications everything builds also with ARM GCC 12.2.
I ran SITL SIH and jMAVsim, fmu-v2, v4, v5 today for a quick test.
Since a NuttX test is required https://github.com/apache/nuttx/pull/8856 (:heavy_check_mark:) and https://github.com/PX4/NuttX/pull/225 (:heavy_check_mark:) need to be merged first.
=> Arch script update + GCC 12 fixes

src/modules/fw_pos_control/fw_path_navigation_params.c
Fixes https://github.com/PX4/PX4-Autopilot/issues/22159
=> FW Position Controller: add missing @decimal 1 for FW_LND_THRTC_SC

ROMFS/px4fmu_common/init.d-posix/airframes/4010_gz_x500_mono_cam, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt
Adds a vehicle with a monocam. The model sdf for this vehicle  and camera are provided in  [this PR](https://github.com/PX4/PX4-gazebo-models/pull/20).
=> adds vehicle with monocam

msg/PositionSetpoint.msg, src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp, src/modules/navigator/mission.cpp, src/modules/navigator/mission_base.cpp, src/modules/navigator/mission_block.cpp, src/modules/navigator/navigator.h, src/modules/navigator/navigator_main.cpp, src/modules/navigator/takeoff.cpp, src/modules/navigator/vtol_takeoff.cpp
Fixes https://github.com/PX4/PX4-Autopilot/pull/22413
Alternative to https://github.com/PX4/PX4-Autopilot/pull/22455
Beside it's also a proposal to make the logic around yaw setpoints in the Navigator vs FlightTasks simpler and cleaner.
Strictly use the following concept: If Navigator publishes a finite yaw setpoint (`position_setpoint_tripplet.current.yaw`), then disable weather vane. This should be used if waypoints have an associated yaw setpoint (eg landings, VTOL transitions or waypoint mission items with the yaw field set). Otherwise leave authority over yaw to the FlightTask - it can then set it e.g. to direction of the next waypoint, to current yaw, or point the vehicle into the wind with the use of weather vane. 
That allows us to remove the `disable_weather_vane` field from the …
=> Navigator/FlightTaskAuto yaw handling improvements/simplifications

boards/px4/fmu-v6xrt/src/CMakeLists.txt, boards/px4/fmu-v6xrt/src/imxrt_flexspi_nor_flash.c, boards/px4/fmu-v6xrt/src/init.c, platforms/nuttx/src/bootloader/nxp/imxrt_common/main.c, platforms/nuttx/src/px4/nxp/imxrt/include/px4_arch/imxrt_flexspi_nor_flash.h, platforms/nuttx/src/px4/nxp/imxrt/include/px4_arch/imxrt_romapi.h, platforms/nuttx/src/px4/nxp/imxrt/romapi/CMakeLists.txt, platforms/nuttx/src/px4/nxp/imxrt/romapi/imxrt_romapi.c, platforms/nuttx/src/px4/nxp/rt117x/include/px4_arch/imxrt_flexspi_nor_flash.h, platforms/nuttx/src/px4/nxp/rt117x/include/px4_arch/imxrt_romapi.h
Moves imxrt romapi headers from boards to imxrt platform
=> v6x-rt: move romapi to platform

src/drivers/optical_flow/thoneflow/thoneflow_parser.cpp
=> Fix scaling issue with thoneflow/holybro optical flow pmw3901 uart driver

src/modules/ekf2/EKF/ekf.cpp, src/modules/ekf2/EKF/ekf.h
=> ekf2: fix resetGlobalPosToExternalObservation whitespace

src/modules/ekf2/EKF/ekf.cpp
Formatting/layout could still be improved.
=> ekf2: verbose debug print status include state variances

src/modules/uuv_att_control/uuv_att_control.cpp
Variable definitions and processing are separated.
Variable definitions are separated from processing.
None.
None.
None.
None.
=> uuv_att_control: Variable definition in processing

src/modules/ekf2/EKF/aid_sources/ZeroVelocityUpdate.cpp
Recompute the innovation between each scalar fusion.
=> ekf2: zvup sequential fusion

src/modules/ekf2/EKF/aux_global_position.cpp, src/modules/ekf2/EKF/aux_global_position.hpp, src/modules/logger/logged_topics.cpp
- Add reset mechanism in case fusion is rejected continuously.
- Reset when AGP reports a measurement reset
=> EKF2-AGP: add reset mechanisms

src/modules/gimbal/input_mavlink.cpp
Checking the value of the same variable in an IF statement.
Change to SWITCH statement.
None.
None.
None.
None.
=> gimbal: Change the IF statement to a SWITCH statement

boards/px4/fmu-v6x/init/rc.board_sensors, boards/px4/fmu-v6x/src/board_config.h, boards/px4/fmu-v6x/src/spi.cpp
px4_fmu-v6x:Add Sensor set 8
@vincentpoont2 please test on all versions of V6X
=> px4_fmu-v6x:Add Sensor set 8

boards/px4/fmu-v6x/init/rc.board_sensors
Change IMU Order, make adis16470 in 1st priority.
=> Change FMU-v6x REV 6 IMU Order

src/modules/navigator/mission_base.cpp
MissionBase did not initialize its mission data, thus could enter an infinite loop in updateDatamanCache() if the initMission() failed to read the mission off, for example, due to the SDCard storage task taking longer than the timeout to respond.
Here you can see the navigator task taking up all idle CPU:
```
(gdb) px4_tasks
╷                        ╷                                   ╷        ╷      
│                        │                                   │        │      
pid │ Task Name              │ Location                          │ CPU(%) │ Prio 
══════╪════════════════════════╪═══════════════════════════════════╪════════╪══════
0 │ Idle Task              │ nx_start                          │    0.0 │    0 
1 │ hpwork                 │ nxsem_wait                        │ …
```
=> Navigator: Prevent busy-looping if Dataman read/write times out

platforms/posix/src/px4/common/px4_init.cpp
The muorb module (used on the voxl2 board) requires initialization during startup on Posix platforms and some reordering of
init calls for other important modules such as uorb, param, etc. This update will do things correctly if the muorb module has
been configured in the build.
=> Added special muorb startup ordering in px4_init for posix platform

src/modules/ekf2/EKF/python/tuning_tools/baro_static_pressure_compensation/baro_static_pressure_compensation_tuning.py
`estimator_baro_bias` requires to have GNSS and baro hgt active and GNSS as the reference. This is quite restrictive. Instead, we can simply use a high-passed version of the baro error.
=> baro static pressure compensation tuning: remove dependency to baro bias

src/lib/matrix/matrix/Matrix.hpp
Fixes #https://github.com/PX4/PX4-Autopilot/issues/22797
=> matrix: remove bold printing of diagonal elements

boards/modalai/voxl2-slpi/src/drivers/dsp_hitl/dsp_hitl.cpp, boards/modalai/voxl2/target/voxl-px4-hitl-start
The Qurt platform has a separate HITL driver. This PR adds optic flow and distance sensor support into that driver. It also updates
some of the GPS units as that message has changed recently.
=> Add new capabilities to Qurt platform HITL driver

src/modules/vtol_att_control/vtol_att_control_main.cpp
=> vtol: only publish generic mavlink stream warning to save flash

src/modules/ekf2/EKF/python/tuning_tools/mc_wind_estimator/mc_wind_estimator_tuning.py
Sometimes GNSS is logged but not used.
Simply add `--gnss` flag to use velocity from `vehicle_gps_position` instead of `vehicle_local_position`
=> mc_wind_estimator_tuning: optionally use GNSS velocity

boards/holybro/kakuteh7/src/spi.cpp
Backport of #22929.
FYI: @vincentpoont2
=> [BACKPORT v1.14] Fix KakuteH7 icm42688p imu issue

src/drivers/rc_input/RCInput.cpp, src/drivers/rc_input/RCInput.hpp
Might fix https://github.com/PX4/PX4-Autopilot/issues/22986 needs testing.
=> drivers: rc_input fix auto scan

platforms/common/pab_manifest.c
@vincentpoont2 @mrpollo This is the code that needs to be checked ones the BASE has had its ID set.
=> px4_fmu-v6x:Add Holybro Pixhawk Jetson Baseboard ver 0x100

src/modules/fw_pos_control/FixedwingPositionControl.cpp
Full description, and solution of the problem is in #23040 .
If you want to see the full story, please see also #22286 .
Fixes #23040 
- Simulation/hardware testing logs:
before : https://logs.px4.io/plot_app?log=7dfd87cc-c486-49c3-8761-b666fdd8f33b
after : https://logs.px4.io/plot_app?log=5a4d0d01-8fd6-456a-8522-9a539464bf0f
=> fw offboard control mode: altitude control enabled

src/modules/ekf2/module.yaml, validation/module_schema.yaml
Max length should be < 70 chars
fixes:
=> ekf2_params: reduce "short" description

src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.cpp
fixes https://github.com/PX4/PX4-Autopilot/pull/22567#issuecomment-2073829260
=> estimatorCheck: get param only if handle is valid

src/modules/camera_feedback/CameraFeedback.cpp
The camera_feedback module doesn't have a description. This explains what it does.
EDITED (removed comment about it being buggy behaviour).
=> Docs for camera_feedback module

Tools/px4moduledoc/srcparser.py, src/drivers/camera_trigger/camera_trigger.cpp, src/drivers/camera_trigger/interfaces/src/camera_interface.h
Adds docs for the camera trigger driver.
=> Module docs for camera trigger driver

Tools/astyle/check_code_style.sh, Tools/astyle/files_to_check_code_style.sh
Previously, that script was printing directories.
Add parenthesis to find argument
=> fix find in "files_to_check_code_style.sh"

src/drivers/gnss/septentrio/util.h
=> gnss: add missing include

src/modules/ekf2/EKF/aid_sources/optical_flow/optical_flow_control.cpp
- additionally don't use flow for reset if magnitude isn't acceptable
This is a protection that the compensated flow isn't enormous.
=> ekf2: optical flow magnitude check compensated

src/lib/pure_pursuit/PurePursuit.hpp, src/modules/rover_ackermann/RoverAckermann.cpp, src/modules/rover_ackermann/RoverAckermann.hpp, src/modules/rover_ackermann/RoverAckermannGuidance/RoverAckermannGuidance.cpp, src/modules/rover_ackermann/RoverAckermannGuidance/RoverAckermannGuidance.hpp
Refactoring some of the ackermann code to make it more readable.
This PR does not change any funcitonality.
=> Ackermann: Refactor code

src/modules/navigator/geofence.cpp
Initialize inter-task message variables.
Declare initialization.
None
None
None
None
=> navigator: Initialize the message variable

src/modules/ekf2/EKF/aid_sources/gnss/gps_checks.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/ekf_helper.cpp
Just use a common logic to update the mag inclination/declination/strength from the WMM.
=> ekf2: extract WMM update logic

src/modules/simulation/gz_bridge/GZBridge.cpp
There was a regression caused by the merge of https://github.com/PX4/PX4-Autopilot/pull/22808
Remove the unused variable
=> Fix build issues with unused variable

src/modules/ekf2/EKF/aid_sources/optical_flow/optical_flow_control.cpp
bugfix from https://github.com/PX4/PX4-Autopilot/pull/23607
=> ekf2: correctly compute vel variance from flow variance

msg/VehicleOpticalFlowVel.msg, src/modules/ekf2/EKF/aid_sources/optical_flow/optical_flow_control.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF2.cpp, src/modules/ekf2/test/test_EKF_flow.cpp
- individual flow samples can be quite erratic
=> ekf2: filter flow vel (used for flow velocity reset)

ROMFS/px4fmu_common/init.d-posix/airframes/4014_gz_x500_mono_cam_down, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt, src/modules/simulation/gz_bridge/CMakeLists.txt
- airframe x500_mono_cam_down
- gz world with aruco tag
=> [gz] X500 mono_cam_down and aruco world

Tools/setup/ubuntu.sh
=> Fix typo where 22.04 still says Gz (Garden)

msg/DistanceSensor.msg, src/drivers/distance_sensor/lightware_laser_i2c/lightware_laser_i2c.cpp, src/lib/drivers/rangefinder/PX4Rangefinder.cpp, src/lib/drivers/rangefinder/PX4Rangefinder.hpp, src/modules/commander/HealthAndArmingChecks/checks/distanceSensorChecks.cpp
follows https://github.com/PX4/PX4-Autopilot/pull/23630
=> Dist-sensor: use enum instead of integer

src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/ekf_helper.cpp
saves about 4.8kB of flash on FMUv5
=> ekf2: move implementation to ekf_helper to reduce flash usage

.github/workflows/mavros_mission_tests.yml, .github/workflows/mavros_offboard_tests.yml
Fixes https://github.com/PX4/PX4-Autopilot/issues/23683
=> ci: try upload-artifacts@v3

src/modules/navigator/rtl_direct.cpp
Test report: Strange-looking vertical deceleration and acceleration during the final landing phase of a multicopter RTL.
Visible in the log, reproducible in default SITL SIH:
Turns out it's because there are additional mission items at the RTL loiter altitude `RTL_DESCEND_ALT`
Skip the RTL states between flight to home/rally point and land if there is no delay configured `RTL_LAND_DELAY = 0` (default).
This was already done
https://github.com/PX4/PX4-Autopilot/blob/26fd4c852c52837e306790e0f86b27d0b0df516e/src/modules/navigator/rtl_direct.cpp#L432-L444
before the refactor https://github.com/PX4/PX4-Autopilot/pull/21049 and was assumed not to be necessary anymore.
Note: To not break the VTOL and fixed-wing use case I had to make sure the states are can only get skipped for multirotors (or a …
=> Bugfix: unexpected vertical deceleration and acceleration during multicopter RTL final land phase

README.md
=> Update README.md - add Christian as rover maintainer

msg/VehicleCommand.msg, src/modules/commander/Commander.cpp
- add PX4_WARN to log unsupported commands
=> commander: ignore REQUEST_CAMERA_INFORMATION

src/drivers/cdcacm_autostart/cdcacm_autostart.cpp
back port https://github.com/PX4/PX4-Autopilot/pull/23751
=> [backport][cdcacm] set file descriptor to -1 after close()

src/modules/mavlink/streams/AUTOPILOT_STATE_FOR_GIMBAL_DEVICE.hpp
The simulated attitude can disturb the gimbal estimator and lead to strange behavior of the gimbal. 
Since the hardware is not moving in HIL/SIH, we fake a static attitude towards the gimbal.
Credit goes to @eyeam3 
```
Fix: Report static attitude to real gimbal in HIL modes
```
We used this change for quite some time when debugging in SIH.
=> Fix: Report static attitude to real gimbal in HIL modes

src/modules/ekf2/EKF/terrain_control.cpp
A large negative hagl can lead lead to a valid result as this value is squared to be compared to a variance.
Never consider a negative hagl as valid. Also make sure the variance is positive.
```
```
unit tests
=> EKF2: robustify terrain validity conditions

boards/holybro/kakuteh7mini/src/hw_config.h
Update KakuteH7 mini board_id in hw_config.h to match https://github.com/PX4/PX4-Autopilot/pull/23832
=> Update KakuteH7 mini board_id in hw_config.h

src/modules/uxrce_dds_client/CMakeLists.txt
- common variable for Micro-XRCE-DDS-Client
- don't mix tabs and spaces
- px4 module include all dependencies
=> uxrce_dds_client: CMakeLists.txt cleanup

Tools/setup/Dockerfile
trim down fat from px4-dev container
=> container: reduce px4-dev container size 

.github/workflows/build_all_targets.yml, .github/workflows/sitl_tests.yml
**spot=capacity-optimized or spot=co:** This strategy prioritizes the allocation of instances from the pools with the most available capacity, reducing the likelihood of interruption.
See https://runs-on.com/configuration/spot-instances/
=> ci: move runners to capacity optimized

.github/workflows/build_all_targets.yml, .github/workflows/compile_ubuntu.yml, .github/workflows/dev_container.yml, .github/workflows/sitl_tests.yml
guarantee execution of jobs
**Tests Needed to Pass for Merge**
=> ci: disable spot instances

.github/workflows/dev_container.yml
Build and push the px4-dev container to the GitHub registry, using the following naming convention:
**Name:** ghcr.io/PX4/px4-dev:{{ docker tag }}
**Link**: https://github.com/PX4/PX4-Autopilot/pkgs/container/px4-dev
```
| Event               | Ref                           | Docker Tags                |
|---------------------|-------------------------------|----------------------------|
| `pull_request`      | `refs/pull/2/merge`           | `pr-2`                     |
| `push`              | `refs/heads/master`           | `master`                   |
| `push`              | `refs/heads/releases/v1`      | `releases-v1`              |
| `push tag`          | `refs/tags/v1.2.3`            | `v1.2.3`, `latest`         |
| `push tag`          | `refs/tags/v2.0.8-beta.67`    | …
```
=> ci: px4-dev container

Tools/setup/ubuntu.sh
Adds a missing build dependency
=> Tools: install ccache on ubuntu

README.md
=> readme: update ci badge

src/lib/lat_lon_alt/lat_lon_alt.cpp, src/lib/lat_lon_alt/test_lat_lon_alt.cpp
I made a mistake when implementing the LatLonAlt -> ECEF position conversion (ref: https://en.wikipedia.org/wiki/Geographic_coordinate_conversion#From_geodetic_to_ECEF_coordinates)
This only affects SIH
fix and add unit test.
=> lla; fix conversion to ECEF

src/systemcmds/topic_listener/listener_main.cpp
=> listener: only clear screen with multiple messages

src/drivers/uavcan/uavcan_main.cpp
Fixes https://github.com/PX4/PX4-Autopilot/issues/24179
=> dronecan: don't init if can interface fails to init

src/modules/ekf2/EKF/aid_sources/gnss/gps_checks.cpp
In SIH, the GNSS signal is zero-mean, but apparently not symmetric. The issue is that saturating such a signal creates an artificial bias. This made the check fail as the bias was above the threshold.
I haven't found why the actual signal is not symmetric. This only occurs on hardware so it could be that the `rand()` function is not a good uniform random number generator when running on hardware.
Note that this issue only surfaced after https://github.com/PX4/PX4-Autopilot/pull/23974/commits/6a667bedffb170f645b864179517332f514e1b84 as prior to this, the EKF was never in "at_rest" state due to the high IMU noise (thus the drift metrics were never computed).
Apply the saturation on the filter's state instead of the input signal. This is a correct way of doing anti-windup as described …
=> SIH: fix GNSS drift false alarm

Tools/px_uploader.py
Fixing my earlier mistake.
This came up in https://github.com/ArduPilot/ardupilot/pull/28492.
=> Tools: remove unused/wrong define and fix comment

src/modules/commander/HealthAndArmingChecks/checks/batteryCheck.cpp
When talking to @cmic0 I learned that it's a worse user experience to have just "Low battery" as a message for all of PX4's low battery states. They represent the urgency of the current situation mostly according to:
| Low battery state | Severity | Desired user action |
| - | - | - |
| Normal | None | Fulfill mission. |
| Low | Warning | Plan to finish mission early if necessary. |
| Critical | Return | Abort, return home and land now. |
| Emergency | Land | No time to return, land now to avoid more damage. |
I added an Event each such that there are different messages with each its description referencing the right parameter.
Disadvantage: Resource use. Presumably worth it for the user experience.
```
Reintroduce separate user messages for low, critical, emergency battery state
```
I …
=> Reintroduce separate user messages for low, critical, emergency battery state

src/modules/mc_att_control/AttitudeControl/AttitudeControl.cpp
I always found the "mix" name a bit misleading as this is just the "delta yaw" part of the desired attitude obtained by removing the reduced attitude from the full attitude.
=> MC att: clarify prioritization algorithm

src/modules/fw_pos_control/FixedwingPositionControl.cpp
Fixes https://github.com/PX4/PX4-Autopilot/issues/24292
=> FW Position controller: transform RWTO_PSP to rad when used

Tools/docker_run.sh, Tools/setup/docker-entrypoint.sh
- modern docker can specify the user at runtime (--user)
=> Tools: docker_run.sh fix entrypoint as user

msg/Buffer128.msg, msg/CMakeLists.txt, src/drivers/actuators/voxl_esc/voxl_esc.cpp, src/drivers/actuators/voxl_esc/voxl_esc.hpp, src/drivers/actuators/voxl_esc/voxl_esc_params.c
* Added the GPIO control feature
* Removed obsolete modal_io_data UORB topic. This will be replaced by mavlink tunnel initially, then serial_control when available.
=> Updates to voxl_esc driver

src/modules/mavlink/streams/DISTANCE_SENSOR.hpp
=> mavlink: add missing fields for DISTANCE_SENSOR

src/drivers/rpm_capture/rpm_capture_params.c
This comment is outdated AFAIK.
=> RPM capture: improve description of param RPM_CAP_ENABLE

.github/workflows/flash_analysis.yml
tries to disable the commenting portion of the flash workflow in ci
Relevant #24408
=> ci: disable flash workflow comments

README.md
* Keeping track of supported hardware is now done on the docs
* Adds a link to the release notes
* Fixes the Dronecode logo
=> readme: update readme to keep up to date

src/modules/commander/HealthAndArmingChecks/checks/opticalFlowCheck.cpp
Quick follow up to https://github.com/PX4/PX4-Autopilot/pull/24375 to clean up the variable declaration...
=> follow up: clean up variable declaration

src/modules/simulation/gz_bridge/server.config, src/modules/simulation/gz_plugins/CMakeLists.txt, src/modules/simulation/gz_plugins/gstreamer/CMakeLists.txt, src/modules/simulation/gz_plugins/gstreamer/GstCameraSystem.cpp, src/modules/simulation/gz_plugins/gstreamer/GstCameraSystem.hpp, src/modules/simulation/gz_plugins/gstreamer/README.md
Streams the first camera found in the world to 127.0.0.1 at port 5600.
=> gz: gstreamer plugin

src/modules/mavlink/streams/GPS2_RAW.hpp
Fill extension fields as in https://github.com/PX4/PX4-Autopilot/blob/f583406558d9f8d8e164089c66a0cba81410e680/src/modules/mavlink/streams/GPS_RAW_INT.hpp#L88-L91
=> GPS2_RAW: fill extension fields

src/drivers/magnetometer/isentek/ist8310/IST8310.cpp
Follow up to #24319.
Respect the CLI address argument during probing.
=> [IST8310] Respect address CLI argument

ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator
=> gz: fix model sdf path

.github/workflows/docs_crowdin_download.yml
UPdated the wrong thing to the right name. No harm done.
=> docs_crowdin_download.yml - revert last change

src/modules/commander/HealthAndArmingChecks/checks/accelerometerCheck.cpp
This must have been a copy paste mistake.
=> commander: fix accel sensor present flag

.github/workflows/docs_crowdin_download.yml, docs/crowdin.yml
Debug crowdin download - add some debug logging to work out whether there is an invalid secret
=> Debug crowdin download

.github/workflows/docs_crowdin_download.yml, docs/crowdin.yml
This cleans up some logging code. Also trying to fix the matching code. If it doesn't work will have to go to crowdin experts.
=> Cleanup docs crowdin download

ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator
Fixes an issue where the world is not ready when the model spawning service is called, causing the model to fail to spawn.
=> gz: Fix startup

src/modules/simulation/gz_plugins/gstreamer/CMakeLists.txt
broke in https://github.com/PX4/PX4-Autopilot/pull/24518
=> gz: fix depends regression

Tools/astyle/check_newlines.sh
excludes docs/* directory from newline checks
=> tools: exclude docs from newline checks

.github/workflows/docs_flaw_checker.yml, docs/en/SUMMARY.md
fixes paths and execution scope for the markdown checker
=> ci: fix markdown flaw check ci

.github/workflows/docs_pr_comment.yml
The flaw checker is now working, but this wasn't running to report the flaws.
This is just a name update
=> Fix up the comment workflow to trigger on flaw checker

.github/workflows/docs_flaw_checker.yml, docs/en/SUMMARY.md
Reverts PX4/PX4-Autopilot#24535
I'll continue working on this. It's broken right now and it might lead to further issues so we need to revert.
=> Revert "ci: fix markdown flaw check ci"

docs/crowdin.yml
Test crowdin integration - modify base path in hope that is cause.
=> crowdin.yml - see if base path affects this.

docs/crowdin.yml
=> crowdin.yml - try fix base path back

docs/crowdin.yml
=> crowdin.yml - fix typo

docs/crowdin.yml
This precisely matches the crowdin for QGC, which might help.
=> crowding to match qgc

docs/en/log/flight_log_analysis.md, docs/en/log/flight_review.md, docs/en/log/plotjuggler_log_analysis.md
The docs/en/logs folder was missing (showed up in translation). 
@mrpollo I am pretty sure that this is omitted because of the `.gitignore` but I can't tell which one is causing it to omit - i.e. there are logs mentioned in that file, but none with a wildcard as far as I can tell. Can you confirm? 
Worse case I can change the folder name to logging, but I'd rather work out why this is happening.
=> Add .gitignored docs/en/log/ folder

docs/ko/config/autotune_mc.md
New PX4 guide Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action) for ko
=> New PX4 guide translations (Crowdin) - ko

docs/uk/airframes/airframe_reference.md, docs/uk/assembly/assembly_fw.md, docs/uk/config/_autotune.md, docs/uk/config/autotune_fw.md, docs/uk/config/autotune_mc.md
New PX4 guide Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action) for uk
=> New PX4 guide translations (Crowdin) - uk

docs/en/config/_autotune.md
Docs build broken in round trip (works find before going through crowdin). Another attempt to make the translation round trip more robust.
=> [Docs] more attempts to fix autotune.md translation sensitivity

.github/workflows/docs_crowdin_download.yml
May fix the chinese language download
=> [Docs] docs_crowdin_download.yml - attempt to fix chinese with code zh-CN

docs/en/config/_autotune.md
Yet another attempt to make crowdin build sensible output from the input.
=> [Docs] Autotune - make the conditional code simpler

docs/en/flight_controller/ark_pi6x.md
Transfer fix from @Claudio-Chies in https://github.com/PX4/PX4-user_guide/pull/3651
=> [Docs] Link and other fixes

.github/workflows/docs_crowdin_download.yml
=> [Docs] docs_crowdin_download.yml - auto label the issue with Documentation

docs/en/config_vtol/vtol_quad_configuration.md
Even more relevant after bringing in https://github.com/PX4/PX4-Autopilot/pull/24521
=> [Docs] document VT_F_TR_OL_TM and VT_TRANS_TIMEOUT

docs/zh/flight_controller/ark_pi6x.md
New PX4 guide Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action) for zh-CN
=> New PX4 guide translations (Crowdin) - zh-CN

src/modules/fw_lateral_longitudinal_control/FwLateralLongitudinalControl.cpp
=> fw-lat-long: advertise fixed_wing_lateral_status

src/modules/control_allocator/module.yaml, src/modules/spacecraft/module.yaml
Fixed a spelling mistake (Automtic -> Automatic)
=> Fix spelling mistake

platforms/nuttx/src/px4/stm/stm32_common/dshot/dshot.c
Changes the bidirectional dshot implementation to only use 1 DMA. The capture channel is rotated through the enabled outputs. So if 4 outputs are used then every fourth measurement is sampled. This reduces the DMA overhead of bidir dshot and fixes reported issues. The ESC telemetry reporting when used in conjunction with bidir dshot has also been fixed.
fixes https://github.com/PX4/PX4-Autopilot/pull/24573
fixes https://github.com/PX4/PX4-Autopilot/issues/24515
@julianoes not sure if you want to look at adding multi-timer support again. It would only require 1 more DMA. It should be relatively easy to do now.
=> bidir dshot: only use 1 DMA and round robin the channels

docs/en/config/safety.md, docs/en/data_links/index.md
=> [Doc] Data link loss exceptions

.github/workflows/docs_flaw_checker.yml
Updates flaw checker to one that better understands non-root docs.
=> docs_flaw_checker.yml - attempt update

.github/workflows/docs_flaw_checker.yml, docs/.vitepress/config.mjs, docs/en/contribute/docs.md, docs/en/data_links/index.md, docs/package.json
Means you can run linkchecker locally again.
=> Updates linkchecker and fixes up the doc contribution sections

docs/en/config/_autotune.md
This adds a section on autotuning large MC vehicles, and falls out of https://discuss.px4.io/t/autotune-for-larger-uavs/44208/7
=> Autotune large MC vehicles

docs/en/dev_log/log_encryption.md
This PR is documents new log encryption functionality (which makes it easier to use) added in:
- https://github.com/PX4/PX4-Autopilot/pull/24489 , 
Should be only merged after the other PR!
=> [Pending] Updated Encrypted logs docs to reflect #24489 ,

.github/workflows/ros_integration_tests.yml, .github/workflows/sitl_tests.yml, ROMFS/px4fmu_common/init.d-posix/rcS, Tools/module_config/output_groups_from_timer_config.py, src/modules/ekf2/EKF2.cpp, src/modules/uxrce_dds_client/dds_topics.h.em, src/modules/uxrce_dds_client/uxrce_dds_client.cpp, src/modules/uxrce_dds_client/uxrce_dds_client.h, test/mavsdk_tests/configs/sitl.json, test/mavsdk_tests/integration_test_runner/logger_helper.py, test/mavsdk_tests/integration_test_runner/process_helper.py, test/mavsdk_tests/integration_test_runner/test_runner.py, test/mavsdk_tests/mavsdk_test_runner.py, test/mavsdk_tests/process_helper.py, test/ros_test_runner.py, test/ros_tests/config.json
This adds integration tests for https://github.com/PX4/PX4-Autopilot/pull/20707 (https://github.com/Auterion/px4-ros2-interface-lib)
- add generic way to override params via ENV variables
- refactors mavsdk_tests to to be a bit more generic and use them for the ros tests
- some color output fixes & improvements
I'm not sure how reliable they are, especially running in CI.
The tests currently check the logic around mode registration & failsafe. If we want to extend them more towards flight testing, we'll need to add lockstep.
=> Integration tests for external modes

src/modules/mavlink/streams/GLOBAL_POSITION_INT.hpp
Oversight from https://github.com/PX4/PX4-Autopilot/pull/23787.
=> mavlink streams: remove unused sub from global pos int

.github/workflows/docs_deploy.yml
The deployment doc failed. 2nd attempt
=> docs_deploy.yml - fixes following first test

cmake/gtest/CMakeLists.txt.in, platforms/posix/src/px4/common/lockstep_scheduler/CMakeLists.txt, platforms/posix/src/px4/common/lockstep_scheduler/test/CMakeLists.txt, src/drivers/ins/vectornav/libvnc/CMakeLists.txt
Intended to fix the github actions MacOS build.
=> cmake bump various minimums to 3.5

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/docs_bug_report.yml
The docs are now in this repo, so no longer want to point elsewhere.
This is how I want it, so I am going to self merge. We can edit later if someone wants to discuss.
FYI @mrpollo
=> Add docs issue template

.github/ISSUE_TEMPLATE/docs_bug_report.yml
Fixes errors in the docs issue template.
=> docs_bug_report.yml - fix errors

docs/en/releases/main.md
This will render a link to the version on the main docs.
=> Update main.md release note to indicate may be out of date if displayed on a branch

ROMFS/px4fmu_common/init.d-posix/px4-rc.gzsim, docs/en/sim_gazebo_gz/index.md
Allows use of PX4_HOME_LAT, PX4_HOME_LON, and PX4_HOME_ALT to adjust world coordinates
=> gz: specify custom world coordinates

docs/en/peripherals/gripper_servo.md
This adds one more option for grippers, namely one that is based on a electro-permanent magnet.
It has been tested with PX4: https://forum.zubax.com/t/fluxgrip-project-drone-airsoft-grenade-dispenser/2398
A video: https://youtu.be/-siXRTYQPZc?si=69hMjiMwoqCIya5C
=> Grippers: added electro-magnetic gripper

docs/en/debug/gdb_debugging.md, docs/en/debug/gdb_hardfault.md
Niklas did a fantastic presentation in 2023 on debugging PX4 - covering many tools and techniques. This adds the video to the GDB debugging section, and also the hard-fault debugging section. 
Fell out of discussion in https://discord.com/channels/1022170275984457759/1031894342731829288/threads/1370292227498315776
=> Add Niklas Debugging Video to GDB and hard fault sections

boards/ark/fmu-v6x/src/board_config.h, src/drivers/imu/analog_devices/adis16507/ADIS16507.cpp, src/drivers/imu/analog_devices/adis16507/ADIS16507.hpp, src/drivers/imu/analog_devices/adis16507/Analog_Devices_ADIS16507_registers.hpp
Backport of https://github.com/PX4/PX4-Autopilot/pull/24691
=> [Backport v1.16] ADIS16507 enhancements

msg/FixedWingLateralGuidanceStatus.msg, msg/versioned/FixedWingLateralSetpoint.msg, msg/versioned/FixedWingLongitudinalSetpoint.msg, msg/versioned/LongitudinalControlConfiguration.msg
=> [against another PR] fw ctrl msgs: extra clarifications in descriptions.

boards/auterion/fmu-v6s/flash-analysis.px4board, boards/auterion/fmu-v6s/nuttx-config/scripts/flash-analysis-script.ld
Adding the flash_analysis for the auterion_v6s board
=> Add flash_analysis for auterion_v6s board

src/lib/dataman_client/DatamanClient.cpp
Separate initialization and setting to variable.
Declare type when first setting variable
None
None
None
None
=> dataman_client: Combine type declarations and processing

docs/en/SUMMARY.md, docs/en/_sidebar.md, docs/en/sim_gazebo_gz/index.md, docs/en/sim_gazebo_gz/plugins.md
Closes https://github.com/PX4/PX4-Autopilot/issues/24497
=> docs: add gazebo plugins doc

docs/_link_checker_sc/ignore_errors.json, docs/en/SUMMARY.md, docs/en/dev_log/log_encryption.md, docs/en/flight_controller/kakuteh7-wing.md, docs/en/flight_modes_rover/ackermann.md, docs/en/flight_modes_rover/differential.md, docs/en/flight_modes_rover/mecanum.md, docs/en/frames_rover/ackermann.md, docs/en/frames_rover/differential.md, docs/en/frames_rover/mecanum.md, docs/en/middleware/uorb.md, docs/en/releases/1.16.md, docs/en/releases/index.md, docs/en/releases/main.md, docs/en/ros2/px4_ros2_control_interface.md, docs/en/ros2/px4_ros2_msg_translation_node.md, docs/en/ros2/user_guide.md, docs/en/sim_gazebo_gz/worlds.md
third attempt at release notes PR
=> docs: second pass at 1.16 release notes

docs/en/telemetry/jfi_telemetry.md
There is a very minor change.
- Change the range from 500 meters to 1000 meters.
=> [Docs] Update jfi_telemetry.md

.github/workflows/build_all_targets.yml
=> ci: updates branch name strategy

platforms/nuttx/src/px4/stm/stm32_common/dshot/dshot.c
Adds a perf counter for the hrt capture complete callback. Profiled at ~15us avg
=> dshot: add perf counter 

msg/versioned/VehicleStatus.msg
Backport of https://github.com/PX4/PX4-Autopilot/pull/25009
=> [BACKPORT 1.16] VehicleStatus.msg: restore VEHICLE_TYPE_* indexes

src/drivers/gnss/septentrio/sbf/decoder.cpp, src/drivers/gnss/septentrio/sbf/decoder.h
See individual commits for details.
Bench tested with a mosaic-go (w/o satellites)
=> fix Septentrio memory bugs

msg/CellularStatus.msg
This just removes topic docs terminating full stops. This is no longer in the standard.
Self merging as this is a pure docs change.
=> [Docs] CellularStatus UORB topic

docs/en/frames_autogyro/index.md, docs/en/frames_autogyro/thunderfly_auto_g2.md
Simply resolving the older [comment](https://github.com/PX4/PX4-user_guide/pull/1723#issuecomment-1011499287) from @hamishwillee and fixing some typos.
=> Docs: Update autogyro airframe page

docs/en/sim_sih/index.md
Docs not sufficient to use this.
=> SIH Hexacopter X - docs update

ROMFS/px4fmu_common/init.d-posix/airframes/50000_gz_rover_differential, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt
Adds airframe for new generic differential rover gazebo model: https://github.com/PX4/PX4-gazebo-models/pull/107
=> Differential: Airframe for new generic differential rover gazebo model

ROMFS/px4fmu_common/init.d-posix/airframes/4009_gz_r1_rover
Fixes a typo
@chfriedrich98 - please take a look
=> Update 4009_gz_r1_rover fix "defatul" typo

.github/labeler.yml
I think the error we're getting is that the labeller was trying to create a new label. Let's see.
=> labeler.yml - attempt to fix labeller workflow

msg/PurePursuitStatus.msg, msg/RoverAttitudeSetpoint.msg, msg/RoverAttitudeStatus.msg, msg/RoverPositionSetpoint.msg, msg/RoverRateSetpoint.msg, msg/RoverRateStatus.msg, msg/RoverSteeringSetpoint.msg, msg/RoverThrottleSetpoint.msg, msg/RoverVelocitySetpoint.msg, msg/RoverVelocityStatus.msg, src/modules/uxrce_dds_client/dds_topics.yaml
This PR formats the rover related uORB messages and exposes the setpoints to DDS to enable direct control over ground vehicles through the API.
=> Rover: Expose rover messages to DDS

docs/en/flight_modes_mc/orbit.md
Follow-up to @hamishwillee 's helpful reminder to adapt the documentation: https://github.com/PX4/PX4-Autopilot/pull/25192#issuecomment-3059198843
=> Doc Orbit: update and clarify configurability and behavior around limits

docs/en/debug/swd_debug.md, docs/en/dev_setup/dev_env_windows_cygwin_packager_setup.md, docs/en/flight_modes_fw/takeoff.md
Docs only fixes. Self merging.
=> Docs: Prettier on takeoff and fix some links

msg/ActionRequest.msg
Updates ActionRequest message to the documentation standard.
=> [Docs] ActionRequest UORB topic

src/drivers/gnss/septentrio/septentrio.cpp, src/drivers/gnss/septentrio/septentrio.h, src/drivers/gps/gps.cpp, src/drivers/uavcan/sensors/gnss.cpp
When working on https://github.com/PX4/PX4-Autopilot/pull/25315 I found that the naming is sometimes hard to follow and there are plenty of timeout checks use subtractions with the unsigned timestamp type which even if they currently don't cause problems wasted many debugging hours before.
I did a pass of refactoring to increase consistency and replace timeout checks in GPS drivers only.
Refactor plus some repeating pattern timeout check robustification pleas look it through but I'm confident it doesn't change the behavior.
=> GPS drivers minor refactor

docs/en/sensor/rangefinders.md
ARK Flow MR name was inaccurate
=> docs: Fixed ARK Flow MR mislabeled in rangefinders.md

.gitmodules
Fixes incorrect submodule branch introduced in https://github.com/PX4/PX4-Autopilot/pull/23858
=> fix submodule

.github/workflows/docs_deploy2.yml
Adds the deployment workflow for docs
=> Add docs-deploy 2 for testing

docs/en/config_rover/basic_setup.md, docs/en/config_rover/velocity_tuning.md
Documentation for the new rover parameters to scale stick inputs introduced in https://github.com/PX4/PX4-Autopilot/pull/25425.
Also clarified some stuff in the basic setup that felt unclear and fixed a typo in the velocity setup in commit [2b1b1ac](https://github.com/PX4/PX4-Autopilot/pull/25427/commits/2b1b1ac032d81f65f2a82f98c00a7f9abc848108).
=> docs: new rover stick input scaling parameters

.github/workflows/docs_flaw_checker.yml
This is an attempt to fix the flaw checker (first attempt failed in #25461)
=> docs_flaw_checker.yml pt 2

src/drivers/uavcan/actuators/esc.cpp
https://discord.com/channels/1022170275984457759/1027935900438642718/1404501339983315097
=> uavcan: esc: init msg to avoid publishing random values

src/modules/commander/accelerometer_calibration.cpp
v1.16 backport of https://github.com/PX4/PX4-Autopilot/pull/25626
=> [BACKPORT] commander: accel cal rotate offsets and scales from body frame back into sensor frame before saving (#25626)

docs/en/actuators/index.md
=> Fix formatting to trigger v1.16 release build for testing

docs/en/index.md
More testing. v1.16 env not updating properly
=> Trigger v1.16 docs build

.github/workflows/docs_deploy_aws.yml
When ... I found that ...
- Add ... for ...
- Refactor ...
```
```
=> AWS docs deployment - revert runs-on from ubuntu for test

.github/workflows/docs_deploy_aws.yml
Updates AWS deploy script to remap release tag to remove the release prefix and add `v` prefox
=> Update aws docs deployment in main branch
