PX4/PX4-Autopilot

- msg/telemetry_status.msg
- msg/vehicle_status_flags.msg
- src/modules/commander/Arming/PreFlightCheck/CMakeLists.txt
- src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp
- src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.hpp
- src/modules/commander/Arming/PreFlightCheck/checks/parachuteCheck.cpp
- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
- src/modules/commander/commander_params.c
- src/modules/mavlink/mavlink_receiver.cpp
- src/modules/mavlink/mavlink_receiver.h
The biggest advantage of a MAVLink enabled parachute system is the standardized communication for presence, status and triggering. This pr aims at adding basic support for evaluating the status of such a parachute after the triggering was added in https://github.com/PX4/PX4-Autopilot/pull/17564 
The parameter `COM_PARACHUTE` enables the requirement for presence and a healthy status of an external MAVLink enabled parachute system. Presence is checked by checking for regular [HEARTBEAT](https://mavlink.io/en/messages/common.html#HEARTBEAT)s from a device with type [MAV_TYPE_PARACHUTE](https://mavlink.io/en/messages/common.html#MAV_TYPE_PARACHUTE) and the status is read out of the `system_status` field of the …
> MAVLink parachute system support improvements

- Tools/gazebo_sitl_multiple_run.sh
Using the command `./Tools/gazebo_sitl_multiple_run.sh -t px4_sitl_rtps -l rtps -n 3` does not work on current master. The startup script will try finding the airfram `iris_rtps` which doesn't exist. 
The exported variable PX4_SIM_MODEL is used by the rcS script as the airframe. So removing the `{LABEL}` and just using `export PX4_SIM_MODEL=${vehicle_model}` will find the correct airframe (iris instead of iris_rtps)
None
Before the change the log in `/home/max/autopilot/build/px4_sitl_rtps/instance_0/out.log` would report a crash. After the change, px4 startup works fine.
> Fix gazebo_sitl_multiple_run.sh for use with uRTPS

- src/modules/simulator/simulator_mavlink.cpp
When running PX4 in SITL (JMAVSim, Gazebo), the logger is expected to record the vehicle's ground-truth state in topic vehicle_local_position_groundtruth.
This PR will fix the missing acceleration data in this topic by adding them to the output message.
Related issue: #18527 
Retrieve the acceleration value, convert it to NED frame by quaternion, and feed it to output.
- Retrieve Gee by global position from simulator
- Retrieve frame convention from simulator
- Calculation adjustment
I test this PR with `make px4_sitl …
> Filling accel value in SITL related topic

- platforms/nuttx/cmake/init.cmake
Any 0 value was being skipped. This only impacts the use of NuttX config variables with PX4 cmake, so we were probably getting away with it so far.
``` Console
-- CONFIG_STACK_USAGE_SAFE_PERCENT 0
-- CONFIG_STM32F7_I2CTIMEOSEC 0
-- CONFIG_BOARD_ASSERT_RESET_VALUE 0
-- CONFIG_RR_INTERVAL 0
-- CONFIG_SEM_PREALLOCHOLDERS 0
-- CONFIG_DEV_FIFO_SIZE 0
-- CONFIG_UART4_PARITY 0
-- CONFIG_UART4_2STOP 0
-- CONFIG_UART7_PARITY 0
-- CONFIG_UART7_2STOP 0
-- CONFIG_UART8_PARITY 0
-- CONFIG_UART8_2STOP 0
-- CONFIG_USART1_PARITY 0
-- CONFIG_USART1_2STOP 0
-- CONFIG_USART2_PARITY 0
-- CONFIG_USART2_2STOP 0
-- CONFIG_USART3_PARITY 0
-- CONFIG_USART3_2STOP 0
-- CONFIG_USART6_PARITY 0
-- CONFIG_USART6_2STOP 0
-- CONFIG_FAT_LFN_ALIAS_TRAILCHARS 0
-- CONFIG_NSH_MMCSDMINOR 0
-- CONFIG_NSH_MMCSDSLOTNO 0
-- …
```
> cmake fix NuttX config import for 0 values

- src/drivers/telemetry/iridiumsbd/IridiumSBD.cpp
- src/drivers/telemetry/iridiumsbd/IridiumSBD.h
Iridiumsbd driver can't be started if the modem is connected after PX4 boot.  
This solution discards all pending data, as close() is blocked otherwise.
> iridiumsbd:  discard all pending data for flow control enabled

- src/lib/parameters/param.h
- use PX4_ERR for CHECK_PARAM_TYPE()
- errors are easier to spot and will cause some tests to fail
- using PX4_ERR rather than printf will show the module origin of most calls
> parameters: param type checking use PX4_ERR and enable in PX4_SITL

- src/modules/mavlink/mavlink_parameters.cpp
This avoids unnecessary errors when check param type is enabled. https://github.com/PX4/PX4-Autopilot/blob/7653bd17575d88545969e5d127c74fa7ca86498f/src/lib/parameters/param.h#L449-L455
> mavlink: param_get proper type to silence errors

- Tools/setup/ubuntu.sh
After `kconfig-frontends` was added as a dependency, there were a lot of confusion with the install script and a lot of people were confusing this with the firmware being broken on Ubuntu 18.04. The setup script fails due to the fact that `kconfig-frontends` are not distributed over `apt`
For Ubuntu 18.04 and earlier, one can follow the documentation in http://nuttx.incubator.apache.org/docs/latest/quickstart/install.html to install `kconfig-frontends`
Even after `kconfig-frontends` is installed the installation script will still fail since `kconfig-frontends` is not a registered package in 18.04
Related to: 
- https://github.com/PX4/PX4-Autopilot/issues/18467
- https://github.com/PX4/homebrew-px4/issues/26#issuecomment-976163098
- …
> Remove kconfig-frontends for ubuntu 18.04 in setup.sh

- src/modules/commander/Commander.cpp
- src/modules/manual_control/ManualControl.cpp
- src/modules/manual_control/ManualControl.hpp
- src/modules/manual_control/manual_control_params.c
During further testing of the recent changes in #17404 I found two issues:
1. Moving the mode switch/button to an unassigned slot results in a message "Switching to Unkown is currently not available"
1. There's no way to disable the stick gesture for arming.
This was previously implicitly (!) possible by either setting `COM_RC_IN_MODE` to joystick or mapping an arm switch.
1. It is possible to enable yaw Airmode even though the stick gesture for arming is enabled
1. I'm not sending out an invalid/"Unkown" mode switch request with `commander_state.main_state` requested to be `-1`. This is the default value representing unassigned slots but when casted to the main_state type `uint8_t` being 255 and hence resulting …
> Follow up improvements for the manual control cleanup

- platforms/common/uORB/Publication.hpp
- platforms/common/uORB/PublicationMulti.hpp
- platforms/common/uORB/Subscription.cpp
- platforms/common/uORB/Subscription.hpp
- platforms/common/uORB/SubscriptionCallback.hpp
- platforms/common/uORB/uORB.cpp
- platforms/common/uORB/uORBDeviceMaster.cpp
- platforms/common/uORB/uORBDeviceMaster.hpp
- platforms/common/uORB/uORBDeviceNode.cpp
- platforms/common/uORB/uORBDeviceNode.hpp
- platforms/common/uORB/uORBManager.cpp
- platforms/common/uORB/uORBManager.hpp
- src/modules/ekf2/EKF2.cpp
- src/modules/ekf2/EKF2.hpp
These are cherry-picks from the protected build PR, but just generic changes which are pre-requisites to make the actual call gates in uORB.
This PR has got 2 changes:
1. Put all the interfaces towards Publishers and Subscribers into just one uORB class, the uORBManager.
2. in EKF2, allocate distance sensor subscriptions as member variables
In addition, it changes some of the inlining in the uORB, to help implementing the protected build in the future. These modifications have a neglible impact on size or performance. The biggest performance hit is for creating …
> Uorb interfaces change

- src/modules/mavlink/mavlink_ftp.cpp
When requesting a limited amount of bytes from a file via ftp over mavlink, I received the maximum amount of data bytes regardless of the amount of requested bytes.
It now listens to the payload->size as per documentation
After a quick chat with @julianoes it was determined that the documentation was correct and that this change does not pose any security flaws.
Sent a read request with the size field set to anything but max allowed size. Response contained the correct amount …
> Fixed mavlink_ftp read

- src/modules/ekf2/EKF2.cpp
Appears when multiple scale factors were introduced in #18442, this line was never updated (still on old scale factor param name). Results that no param is found, and thus no scale is applied to the airspeed in EKF2.
Update the param search for ``ASPD_SCALE_1``.
This is a quick fix.. but I imagine @sfuhrer you will want to advise on how selection of 1st, 2nd, or 3rd scales should be chosen here if someone is using the airspeed selector with multiple sensors.
I ran in SITL - confirmed that the wind estimate is stable after this. Can provide a log if requested.. but so far the fix is quite trivial.
> update correct airsp scale param string in ekf2

- src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
- src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.hpp
This allows `sensors/vehicle_angular_velocity` to select a working enabled gyro immediately on boot-up before the estimator selector is ready or in the event of a timeout.
Could be useful in an in air restart scenario bringing the inner loop online within milliseconds.
Other minor improvements.
- avoid unnecessary filter reset on parameter update
- additional minor optimizations (precomputing dt inverse, etc)
- moving filter reset check and dynamic notch filter update checks out of the update loops
- this were necessary previously when the scale factor wasn't applied prior to filtering the otherwise raw data
> sensors/vehicle_angular_velocity: fallback sensor selection improvements

- src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp
- src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.hpp
- src/modules/commander/Arming/PreFlightCheck/checks/rcCalibrationCheck.cpp
This check enforced setting a VTOL transition switch if an RC was used on a VTOL.
It comes from a time when the only way to transition was through the RC switch,
whereas now we have also a mavlink message in place for it, so enforcing it is
no longer needed.
- some RC don't have a two-way switch
- annoying to be enforced on all VTOLs, even if one doesn't need it
Remove the VTOL switch check in the preflight checks.
Bench tested.
That was the original PR adding the check: https://github.com/PX4/PX4-Autopilot/pull/5545, with the brief discussion about removing it again: https://github.com/PX4/PX4-Autopilot/pull/5545#issuecomment-977618220
> Commander: remove preflight check for VTOL transition switch

- ROMFS/px4fmu_common/init.d-posix/airframes/1030_plane
- ROMFS/px4fmu_common/init.d-posix/airframes/1040_standard_vtol
- ROMFS/px4fmu_common/init.d-posix/airframes/1042_tiltrotor
Remove some tecs params from configs that actually lead to worse performance than defaults.
Mainly checked airspeed and altitude/height rate tracking. Not a huge difference with / without these params, but I think in general we should try to keep the SITL airframe configs as light weight as possible, so use the default tuning gains where possible.
> SITL configs VTOL/plane: improve SITL tuning a bit

- src/modules/mavlink/mavlink_ftp.cpp
- src/modules/mavlink/mavlink_tests/mavlink_ftp_test.cpp
- src/modules/mavlink/mavlink_tests/mavlink_ftp_test.h
In commit 462b5721721122c94bc7a3c43ae7f37c41ee625d the reading operation on the PX4 side was changed to only read as many bytes as requested rather than however many fit in the payload data.
This caused the unit tests to fail which this commit here aims to fix.
What is confusing about MAVLink FTP is that there is a size field which generally signals how many bytes of the payload data are used/set.
However, in the case of a read requst, the size field is used to indicate how many bytes should be read. The payload data is empty in that case though.
This case was, from how I understand it, not implemented/tested in the unit tests and now failed. In order to implement it I had to change a few things:
- Change _setup_ftp_msg and _send_receive_msg so that the params contain a data length rather …
> mavlink_ftp: fix tests after implementation fix

- src/modules/vmount/input_rc.cpp
When scaling manual input, we should only use pitch -90 to +90 instead of -180 to 180 degrees which leads to weird behavior as it gets passed on by a quaternion.
> vmount: fix RC pitch input scale

- src/modules/vmount/input_mavlink.cpp
Without this PR, there are a lot of gimbal_manager_status being published with `flags` incorrectly set to zero. This PR fixes this issue. @julianoes
> vmount: fix gimbal_manager_status

- src/modules/commander/Commander.cpp
- src/modules/navigator/rtl_params.c
Follow up to the review here: https://github.com/PX4/PX4-Autopilot/pull/18646#pullrequestreview-813949240
- Message for the user saying "Remaining flight time low" instead of "Flight time low"
- Add `\t` at the end of the deprecated `mavlink_log_emergency()` message to make it not show in newer ground stations that support the events interface
- Publish an appropriate event over the events interface
- Use a round number of 100s as the default safety margin for flight time still have left after the full RTL
- Increase the maximum value for the time margin parameter to 60 minutes to account for vehicles that are capable of flying multiple hours
I did not specifically test these changes yet.
> Follow up to RTL based on remaining flight time

- msg/gps_inject_data.msg
- msg/sensor_gps.msg
- src/drivers/gps/gps.cpp
- src/drivers/gps/params.c
- src/drivers/uavcan/beep.cpp
- src/drivers/uavcan/safety_state.cpp
- src/drivers/uavcan/sensors/gnss.cpp
- src/drivers/uavcan/sensors/gnss.hpp
- src/drivers/uavcannode/Publishers/BatteryInfo.hpp
- src/drivers/uavcannode/Publishers/FlowMeasurement.hpp
- src/drivers/uavcannode/Publishers/GnssFix2.hpp
- src/drivers/uavcannode/Publishers/MagneticFieldStrength2.hpp
- src/drivers/uavcannode/Publishers/MovingBaselineData.hpp
- src/drivers/uavcannode/Publishers/RangeSensorMeasurement.hpp
- src/drivers/uavcannode/Publishers/RawAirData.hpp
- src/drivers/uavcannode/Publishers/SafetyButton.hpp
- src/drivers/uavcannode/Publishers/StaticPressure.hpp
- src/drivers/uavcannode/Subscribers/MovingBaselineData.hpp
- src/drivers/uavcannode/UavcanNode.cpp
- src/modules/mavlink/streams/GPS2_RAW.hpp
- src/modules/mavlink/streams/GPS_RAW_INT.hpp
This PR adds moving baseline functionality on the ARK RTK GPS using the U-Blox F9P.
Requires https://github.com/PX4/PX4-GPSDrivers/pull/91
> UAVCAN F9P Moving Baseline

- src/drivers/gps/gps.cpp
This fixes the following compile error on Mac:
src/drivers/gps/gps.cpp:562:23: fatal error: use of undeclared identifier 'B921600'
case 921600: speed = B921600; break;
^
> gps: fix compiling on mac

- src/drivers/uavcannode/Publishers/MovingBaselineData.hpp
This is a simple update to prevent a uavcan moving base gps from republishing RTCM messages it receives over uavcan.
> Prevent uavcannode from republishing RTCM data received over uavcan

- cmake/kconfig.cmake
- src/drivers/sw_crypto/crypto.c
- src/lib/crypto/CMakeLists.txt
This PR contains a set of small fixes for current SW crypto implementation, picked from my other branches:
- Always use the same allocation functions for both src/lib/crypto libraries and sw_crypto driver/wrapper
- Fix cmake caching error when building variants with and without crypto enabled
- a type mismatch in crypto_get_min_blocksize function, which triggers a warning on some compilers, but not all
- a cleanup in cmake/kconfig.cmake to remove BOARD_KEYSTORE flag; it is no longer needed when the keystore (if needed as a separate module at all) is just another driver
> Crypto fixes

- src/modules/commander/Commander.cpp
This changes the command handling logic to accept commands which are targeted at any system, signaled by target_system set to 0.
As suggested by @lukegluke in #18572.
Closes #18572.
> commander: handle system broadcast commands

- src/drivers/px4io/px4io.cpp
Possibly closes #18750 
Remove the condition that was added in https://github.com/PX4/PX4-Autopilot/commit/089c962d9208b3616ba505ab927fa399554035d4#diff-ff52cb1224c92cc672316dab2f93a98e7db09fb08ccdfbb9fb0015e8d86f1387R859 not knowing why it was added. @dagar please tell me about the side effects.
~I did not test this but based on the description in https://github.com/PX4/PX4-Autopilot/issues/18750 it should solve the issue.~ Tested the fixed version, see comment below.
> px4io: discover `PWM_MAIN_TRIMx` parameters right away

- src/modules/ekf2/EKF2Selector.cpp
- src/modules/ekf2/EKF2Selector.hpp
The EKF2 selector change in https://github.com/PX4/PX4-Autopilot/pull/18669 also prevents selection when only attitude is available. This PR is one possible solution, but I'm open to suggestions.
> ekf2: selector treat combined test ratio > 1 as a warning

- src/lib/mixer_module/mixer_module.hpp
Small typo I found by accident
> mixer_module: typo con(s)tructor

- .ci/Jenkinsfile-hardware
- platforms/nuttx/Debug/PX4
- platforms/nuttx/Debug/jlink_debug_gdb.sh.in
- platforms/nuttx/Debug/jlink_gdb_backtrace_simple.sh
- platforms/nuttx/cmake/jlink.cmake
- use NuttX gdb script for nxthreads and thread backtrace
- update jlink_gdb_backtrace and jlink_debug_gdb helper targets to use
NuttX gdb script
- Debug/PX4 fix "perf" divide by zero
- Debug/PX4 add "dmesg"
``` Console
$ make px4_fmu-v5x_default jlink_debug_gdb
```
> NuttX debug helper improvements

- src/modules/navigator/mission.cpp
- src/modules/navigator/mission.h
There isn't an actual problem with how it was previously, though it is annoying to have position setpoints 1000km away from the current flight location, that raised questions by users..and having the "set wp far ahead of the vehicle" duplicated doesn't look right. 
Remove generate_waypoint_from_heading() from Navigator, and keep the current position sp coordinates when the transition is started. 
The FW Position controller sets the wp to be tracked during a VTOL front transition, the coordinates sp set here weren't used.
https://github.com/PX4/PX4-Autopilot/blob/4ba84d56c9388f41e9ff366a7f4c73a2c4b5e4b8/src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp#L758
Instead of …
> Navigator: VTOL: remove generate_waypoint_from_heading()

- src/drivers/barometer/ms5611/CMakeLists.txt
- src/drivers/barometer/ms5611/ms5611_main.cpp
- src/drivers/barometer/ms5611/ms5611_spi.cpp
- this was necessary to get the secondary ms5611 working reliably on a particular CubeOrange
- the sensor is transferring very little data, so lowering the speed by default everywhere is harmless
On a particular CubeOrange the ms5611 PROM crc was invalid. After lowering the clock rate slightly the crc was valid, but upon closer inspection the only actual change was at the beginning in the manufacturer reserved portion.
``` Console
ms5611 on SPI bus 4 at 61 (20000 KHz)
DEBUG 1006413    prom[0]=0x8000
DEBUG 1006460    prom[1]=0xb7bd
DEBUG 1006505    prom[2]=0xba8c
DEBUG 1006549    prom[3]=0x7685
DEBUG 1006593    prom[4]=0x6c88
DEBUG 1006639    prom[5]=0x8876
DEBUG 1006683    prom[6]=0x7340
DEBUG 1006727    prom[7]=0x8
INFO  [ms5611] crc read: 8, crc: 0 (0)
```
``` Console
ms5611 on SPI bus …
```
> ms5611: lower SPI clock 20 MHz -> 16 MHz

- src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
The emergency braking logic prevents the vehicle from flying faster than 1.3*MPC_XY_CRUISE atm in auto modes (speed can be set through DO_CHANGE_SPEED mission items).
Use MPC_XY_VEL_MAX instead of MPC_XY_CRUISE.
Did I miss anything, or was this unintentional?
> FlightTaskAuto: use MPC_VEL_MAX instead of MPC_XY_CRUISE for emergency braking thresholds

- src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c
Minor bug - small PR.
I noticed while working on #18810 that the L1 period param has been incorrectly documented for some time now (wrong units -- should be seconds):
https://github.com/PX4/PX4-Autopilot/blob/08b0ac9654d0041a78c61025a4114a59b0045f4d/src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c#L46-L61
It is correct in the L1 library:
https://github.com/PX4/PX4-Autopilot/blob/08b0ac9654d0041a78c61025a4114a59b0045f4d/src/lib/l1/ECL_L1_Pos_Controller.hpp#L220
I guess this is just left over documentation from when the L1 distance was still not dynamic with ground speed (some time ago) and this param was literally the L1 distance.
My suggested changes:
- documentation fix (correct units, etc)
- lower the minimum period and period recommendations to what an L1 distance at ground …
> fix incorrect L1 period param documentation

- platforms/common/px4_work_queue/WorkQueueManager.cpp
- platforms/nuttx/src/px4/common/tasks.cpp
This simplifies launching WorkQueueRunner, by not using pthreads directly
This also allows launching runners on both user and kernel sides in NuttX protected build,
since px4_task_spawn_cmd automatically launches the task on user/kernel sides properly
using nuttx task_create
- For posix builds, the px4_task_spawn_cmd uses pthreads - there is no change
- For nuttx, pthreads are in the end just nuttx tasks - no change
- For nuttx protected builds, the pthreads are only available on user side, this allows task creation also in kernel side
> px4_work_queue: Spawn the WorkQueueRunner using px4_task_spawn_cmd

- src/lib/motion_planning/PositionSmoothing.cpp
- src/lib/motion_planning/PositionSmoothing.hpp
- src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
This adds a "single target" mode for the position smoothing.
For cases, when we simply want to guide the vehicle to a new position, without passing through other waypoints, knowledge of the previous waypoint as well as L1 guidance are not necessary. 
In fact, L1 guidance could potentially get consfused when setting previous waypoints to wrong values in the old API.
This extends the PositionSmoothing library with an API that consumes only a single waypoint and then internally disables L1 guidance on turns. 
An example for such a case is the Orbit approach trajectory.
Tested in SITL and X500 on Skynode
> trajectory-planning: Single target option for PositionSmoothing

- src/modules/land_detector/FixedwingLandDetector.cpp
- src/modules/land_detector/land_detector_params_fw.c
Fixes https://github.com/PX4/PX4-Autopilot/issues/18799
The fixed-wing land detector relies on airspeed, groundspeed and acceleration to detect landings. The groundspeed thresholds (separate for vertical and horizontal) are rather relaxed, and are thus possible to trigger false positive land detections in-air if the airspeed is invalid. 
Tighten the thresholds in the airspeed-less case. I've so far added a 0.7 factor for horizontal and vertical speed limits, happy for other recommendations. 
Fuse the FW with the MC land detector? Not sure if that's worth it, given that land detection for FW should be much easier (at least if one has an airspeed sensor, what most vehicles have). …
> FW land detector: tighten thresholds in airspeed-less case

- src/modules/logger/logged_topics.cpp
With the distance sensor logger set to optional, the ARK Flow distance sensor on uavcan doesn't get logged.
> Fix uavcan distance sensor not being logged

- .gitignore
- ROMFS/px4fmu_common/init.d/rcS
- src/modules/dataman/parameters.c
- src/modules/navigator/navigation.h
- new parameter SYS_DM_BACKEND to configure dataman to use the SD file backend (default) or RAM
- reduce NUM_MISSIONS_SUPPORTED from 2000->500 so RAM backend is viable on typical F7
> dataman: add SYS_DM_BACKEND parameter

- src/modules/commander/commander_params.c
- src/modules/manual_control/ManualControlSelector.cpp
- src/modules/manual_control/ManualControlSelector.hpp
- src/modules/manual_control/ManualControlSelectorTest.cpp
Since https://github.com/PX4/PX4-Autopilot/pull/17404 by default only RC is accepted and the original PX4 behavior of only accepting the first source present since boot is not supported anymore. I received somewhat obvious feedback from multiple users that were not aware that this has to be configured now.
This PR enables the original behavior for default. Additionally I added an option to disable stick input completely which doesn't require specific implementation but should explicitly be possible and documented.
The goal is to make it mandatory for the user to configure what he's planning to use in the UI. Until this UI exists I recover the default behavior to not piss of …
> ManualControlSelector: Enable original PX4 default behavior until QGC catches up

- src/modules/ekf2/EKF/control.cpp
- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/ekf_helper.cpp
- src/modules/ekf2/EKF/sensor_range_finder.hpp
- src/modules/ekf2/test/test_EKF_gps.cpp
The height fusion control logic still contains too many low-level details that should be taken care elsewhere.
Move all the resets/adjustments that need to be done every time a height fusion is started in the corresponding starting function (`startGpsHgtFusion`, `startRngHgtFusion`, `startRngAidHgtFusion`, `startBaroHgtFusion` and `startEvHgtFusion`).
Furthermore, when flying in range height mode (`EKF2_HGT_MODE` = range, for indoor use on flat terrain), it makes sense that the origin of the local frame is at the ground level. This is often expected by users flying indoor in offboard mode and this PR makes sure this is correct.
Unit tests, SITL with range finder, GPS and baro
- …
> Height fusion control cleanup and range height improvements

- src/modules/simulator/sensor_baro_sim/CMakeLists.txt
- src/modules/simulator/sensor_baro_sim/SensorBaroSim.cpp
- src/modules/simulator/sensor_baro_sim/SensorBaroSim.hpp
- src/modules/simulator/sensor_baro_sim/parameters.c
- src/modules/simulator/sensor_gps_sim/CMakeLists.txt
- src/modules/simulator/sensor_gps_sim/SensorGpsSim.cpp
- src/modules/simulator/sensor_gps_sim/SensorGpsSim.hpp
- src/modules/simulator/sensor_gps_sim/parameters.c
- src/modules/simulator/sensor_mag_sim/CMakeLists.txt
- src/modules/simulator/sensor_mag_sim/SensorMagSim.cpp
- src/modules/simulator/sensor_mag_sim/SensorMagSim.hpp
- src/modules/simulator/sensor_mag_sim/parameters.c
This is a new standalone mag simulator "driver" that creates an appropriate magnetic field from simulator ground truth (attitude + global position).
We can use this pattern to start consolidating things across all the different simulators. As far as I know none of them actually get the magnetic field from the simulation, so it's quite a lot of duplicated code/effort.
TODO:
- ~~add noise~~
- configurable
- update SIH, sitl_gazebo, ignition, etc, etc
> simulator: add standalone sensor_mag_sim module

- src/modules/mavlink/mavlink_receiver.cpp
The transponder_report uORB topic is sent whenever an UTM_Global_Position Mavlink message is received or whenever an ADSB_Vehicle Mavlink message is received.
In case of receiving a UTM_Global_Position message, the icao_address field of the transponder_report uORB topic is not set. A system that uses the transponder_report uORB topic to get information about other UAVs and aircraft would need this field to distinguish which vehicle sent which information.
Set the icao_address field of the transponder_report uORB topic to match the mav_id of vehicles after receiving their UTM_Global_Position Mavlink message.
> Set the icao_address of other UAVs to their mav- id

- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/vel_pos_fusion.cpp
Delete unused `_bad_vert_accel_detected` and update fusion helper methods.
- `_bad_vert_accel_detected` was replaced with `_fault_status.flags.bad_acc_vertical` here https://github.com/PX4/PX4-ECL/pull/917 (https://github.com/PX4/PX4-ECL/commit/6e99ebd9286c5b52585d1809ae3ae2a3f00e6bd5)
- an older PR (https://github.com/PX4/PX4-ECL/pull/836) that started months before my change wasn't actually merged until several months after and it restored `_bad_vert_accel_detected`, but in an incomplete state
We really need to be more careful when dealing with old PRs that are dragged along and rebased many times. I've personally found it can be easy to lose sight of real incremental history when rebasing multiple commits. In a lot of cases I think we're safer to merge master into these long lived …
> ekf2: delete obsolete _bad_vert_accel_detected

- src/systemcmds/tests/test_dataman.c
- use %zd for signed size_t (ssize_t)
> tests: dataman fix ssize_t printf

- platforms/common/uORB/uORBDeviceMaster.cpp
- platforms/common/uORB/uORBDeviceNode.cpp
- src/lib/cdev/CDev.cpp
- src/lib/cdev/CDev.hpp
- src/lib/cdev/CMakeLists.txt
This is a cherry-pick from the protected build PR. This fixes a problem in freeing allocated node name; in kernel it needs to be freed with kernel-specific function (kmm_free), as the strdup allocates it from kernel heap.
This also cleans up the managing of the node name in general. It seems unnecessary to transfer the memory allocation ownership from uORB to CDev. It is confusing and in general better practice to free the memory by the same entity who allocated it. In this case the memory allocation and de-allocation can be fully managed by uORBDeviceNode.
Allocate the copy of the node name in uORBDeviceNode constructor, when the CDev object is being created. The success of the allocation is checked later in …
> Remove memory allocation ownership transfer

- msg/vehicle_status.msg
- src/modules/commander/Arming/HealthFlags/HealthFlags.cpp
- src/modules/commander/Arming/HealthFlags/HealthFlags.h
- src/modules/commander/Commander.cpp
- src/modules/mavlink/streams/SYS_STATUS.hpp
MAVLINK ran out of sensor status bits in the SYS_STATUS message. Recently, the SYS_STATUS message was extended with another 32-bit bit field. https://github.com/mavlink/mavlink/pull/1751
This PR changes the PX4 internal `onboard_control_sensors_present` `onboard_control_sensors_enabled` and  `onboard_control_sensors_healthy` fields to 64-bit types, which are then mapped to the base and extended 32-bit fields of the mavlink message. Additionally, the first bit of the extended message is used for parachute status indication. 
I think longer term, we should refactor this and make the internal representation independent of mavlink.
Tested on PIXHAWK 4 and skynode
> Extend sensor status bits to 64-bit - set parachute status

- src/modules/ekf2/CMakeLists.txt
- src/modules/ekf2/EKF2Selector.cpp
- src/modules/ekf2/EKF2Selector.hpp
- require that an instance is healthy continuously for >= 1s before allowing it to be used
Accelerometer clipping is included as one of the estimator fault status flags. During periods of intermittent clipping across all IMUs (eg boards that only have 16G accels) this can result in rapid switching between estimators.
By adding a small hysteresis to the per instance healthy flag we can minimize this.
This has been tested, but not in the original failure case on a board with 2 IMUs that both have the same accel dynamic range and a frame with very bad vibration.
> ekf2: selector use hysteresis for healthy flag

- src/modules/commander/commander_params.c
- src/modules/ekf2/ekf2_params.c
Other than potentially increasing preflight warnings within ekf2 this will also have an impact on inhibiting mag use and resets. 
Is this a better default than having it off entirely?
> ekf2: enable mag check by default, but commander only warn

- src/lib/drivers/accelerometer/PX4Accelerometer.cpp
- src/lib/mathlib/math/Functions.hpp
- consider data clipped/saturated if it's INT16_MIN/INT16_MAX or within 1
- this accommodates rotated data (|INT16_MIN| = INT16_MAX + 1) and sensors that may re-use the lowest bit for other purposes (sync indicator, etc)
> drivers/accelerometer: adjust int16_t clipping threshold slightly

- src/modules/flight_mode_manager/FlightModeManager.cpp
- src/modules/mc_att_control/mc_att_control_main.cpp
- src/modules/mc_pos_control/MulticopterPositionControl.cpp
- the timestamp_sample is ultimately set by the primary IMU's data ready interrupt or via px4 hrt so it's more consistent and immune to most jitter that can impact per module scheduling
> multicopter: minimize dt jitter by using estimate timestamp_sample

- src/modules/mavlink/mavlink_receiver.cpp
In some cases we print also the mavlink commands that replied to be unsupported or temporarily unavailable. This is not an error to show in the log. For example if a trigger fails because the camera is not ready and then the retry succeeds then we don't need this to spam the log.
Mavlink error codes for reference: https://mavlink.io/en/messages/common.html#MAV_RESULT
Print only if the command fails and not for other conditions as before.
I cannot really think of an alternative other than leaving it as it is. This is also fine although it can spam the log in certain specific situations.
This has been in our internal branch for a few months now and we have …
> mavlink camera ack - print error only if the mavlink command fails

- src/drivers/px4io/CMakeLists.txt
This should fix the build with older cmake versions.
> px4io: remove unused cmake_policy

- src/modules/mavlink/CMakeLists.txt
- src/modules/mavlink/MavlinkStatustextHandler.cpp
- src/modules/mavlink/MavlinkStatustextHandler.hpp
- src/modules/mavlink/MavlinkStatustextHandlerTest.cpp
- src/modules/mavlink/mavlink_bridge_header.h
- src/modules/mavlink/mavlink_receiver.cpp
- src/modules/mavlink/mavlink_receiver.h
This adds support for mavlink statustext messages arriving in multiple chunks.
> mavlink: support receiving multi-chunk statustexts

- src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
- src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.hpp
- non-trivial perf counters (elapsed & interval) are relatively expensive
- if ESC and FFT notch filtering are enabled this reduces 6 updates (2 per axis) to 1
> sensors/vehicle_angular_velocity: replace ESC/FFT perf counters with single cycle perf counter

- platforms/common/px4_work_queue/WorkQueueManager.cpp
- src/modules/mavlink/streams/ACTUATOR_CONTROL_TARGET.hpp
- src/modules/mavlink/streams/SERVO_OUTPUT_RAW.hpp
- fixes a compiler error on GCC 11.2.1: `error: no matching function for call to ‘max(long int, int)’`
- mavlink streams: add return in all cases
> WorkQueueManager: explicitly convert PTHREAD_STACK_MIN to int 

- msg/vehicle_status_flags.msg
- src/modules/commander/Commander.cpp
Before https://github.com/PX4/PX4-Autopilot/pull/17404 special handling of RC actions namely arming, modes switching and override during RC calibration was done through the `ManualControl::setRCAllowed()` in the class within commander. Listening to the `vehicle_status_flags.rc_input_blocked` flag was kept intact for the override but not for arming and mode switching.
I rename the flag `vehicle_status_flags.rc_input_blocked` to `rc_calibration_in_progress` to avoid any ambiguity and guard the execution of RC-initiated actions during RC calibration.
I bench tested this on a pixracer with TBS Crossfire SBUS concentrating on holding the already calibrated arm gesture for a long time and also …
> Commander: avoid RC actions during calibration

- platforms/nuttx/src/px4/stm/stm32_common/include/px4_arch/px4io_serial.h
- platforms/nuttx/src/px4/stm/stm32f4/px4io_serial/px4io_serial.cpp
- platforms/nuttx/src/px4/stm/stm32f7/px4io_serial/px4io_serial.cpp
- platforms/nuttx/src/px4/stm/stm32h7/px4io_serial/px4io_serial.cpp
- px4io_serial: always perform full abort DMA on error 
- enable DMA error perf count
- possible fix (or overreaction) to https://github.com/PX4/PX4-Autopilot/issues/18375 https://github.com/PX4/PX4-Autopilot/issues/18856
> px4io_serial: always perform full abort DMA on error

- .ci/Jenkinsfile-hardware
- nuttx in PX4/Firmware (d0ce5705359f8beeb9faf7fa0d12279e03bb7ac7): https://github.com/PX4/NuttX/commit/d4c06e9dfb7bb14d0f19ef47b94d838b1caf50f3
- nuttx current upstream: https://github.com/PX4/NuttX/commit/378032a44ba1ec0e7e3df16a23d21a6e77a2d816
- Changes: https://github.com/PX4/NuttX/compare/d4c06e9dfb7bb14d0f19ef47b94d838b1caf50f3...378032a44ba1ec0e7e3df16a23d21a6e77a2d816
378032a44b 2021-12-15 David Sidrane - [BACKPORT] stm32f7:sdmmc invalidate before DMA to avoid eviction overwrite
> Update submodule nuttx to latest Thu Dec 23 18:11:37 UTC 2021

- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
- src/modules/commander/commander_params.c
- useful for testing and other edge cases where you don't want home for whatever reason
I'd actually prefer to consolidate most of the `home_position` handling rather than having it scattered across different helpers, but I'll consider that later.
> commander: add COM_HOME_EN parameter to enable/disable home position

- ROMFS/px4fmu_common/init.d/rcS
- Tools/HIL/test_airframes.sh
- src/lib/parameters/tinybson/tinybson.cpp
- this is mainly for debug comparison
Parameter import failure on the test rack. http://px4-jenkins.dagar.ca:8080/blue/organizations/jenkins/PX4-Autopilot/detail/pr-update_platforms%2Fnuttx%2FNuttX%2Fnuttx/15/pipeline/1951/
> ROMFS: rcS dump parameter backup contents before using

- src/lib/sensor_calibration/Accelerometer.cpp
- src/lib/sensor_calibration/Gyroscope.cpp
- src/lib/sensor_calibration/Magnetometer.cpp
The sensor priority parameters underlying default value is -1 to indicate uninitialized. When a sensor calibration is first created it's then set to an appropriate default for internal vs external. This default doesn't need to be immediately written out to parameters immediately unless the value was invalid. The param save after a regular sensor calibration is when the priority will be exported.
> lib/sensor_calibration: don't save uninitialized priority parameter immediately

- platforms/common/include/px4_platform_common/atomic_bitset.h
- src/include/containers/Bitset.hpp
- src/lib/parameters/flashparams/flashparams.cpp
- src/lib/parameters/flashparams/flashparams.h
- src/lib/parameters/param.h
- src/lib/parameters/parameters.cpp
- src/lib/parameters/tinybson/tinybson.cpp
- src/lib/parameters/tinybson/tinybson.h
- src/modules/commander/factory_calibration_storage.cpp
- src/systemcmds/param/param.cpp
- src/systemcmds/tests/test_bson.cpp
- src/systemcmds/tests/test_parameters.cpp
This is to avoid iterating the full parameter array on every param_value_unsaved() call, and minimize locking.
The way logger and mavlink use this unsaved mechanism to check for recently updated parameters seems a bit questionable (race condition), but I'll save that for later.
> parameters use bitset for mark_unsaved and minimize unnecessary locking where possible (param_get, etc)

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
When flying in the windy SITL world the loiter circle of a GoTo looks like this:
It's because the position setpoint of a GoTo has the loiter_radius field at 0, and in handle_setpoint_type(), where we decide if the TYPE should be LOITER or POSITION, we used it without checking. 
Check if pos_curr.loiter_radius is non-zero, otherwise use default loiter radius (the same logic is already used in control_auto_loiter().
Set the loiter_radius of GoTos to the default loiter radius - we could do this on top, but i think checking and adapting in FW Pos C is safer.
SITL tested.
> FW Position controller: make loiter switching logic robust against pos_sp with loiter_rad=0

- src/modules/landing_target_estimator/LandingTargetEstimator.cpp
- src/modules/landing_target_estimator/LandingTargetEstimator.h
- src/modules/landing_target_estimator/landing_target_estimator_params.c
Hello all, We are currently working on a drone delivery project where we are planning to use the IR-LOCK for fine tuning the cargo delivery. However, the current `landing_target_estimator` module works under the assumption that the IRLOCK's camera frame has a specific orientation and position relative to the body frame.
In our drone frame it will not be possible to position the camera like this, so it would be nice to specify the camera's orientation and position relative to the body frame as parameters (as mentioned in a "todo" comment on the aforementioned module). We thought this could be a useful feature for other users
We have defined four additional parameters:
- **LTEST_SENS_ROT**: The yaw of the camera …
> Custom irlock frame params

- src/lib/parameters/CMakeLists.txt
- src/lib/parameters/parameters.cpp
- src/lib/parameters/tinybson/tinybson.cpp
- src/systemcmds/param/param.cpp
- src/systemcmds/tests/test_parameters.cpp
- parameter export
- re-read exported bson to verify contents
- export empty bson document if all parameters are unset (prevent stale data, detect difference between mtd erased and no params, etc)
- parameter import
- if bson empty silently retry import as a precaution
This is a quick idea for a small parameter robustness improvement after witnessing another rare unexplained failure on the test rack (cube orange again).
> parameters: add simple param verification pass on BSON data

- platforms/nuttx/CMakeLists.txt
- possible fix for https://github.com/PX4/PX4-Autopilot/issues/18894
> cmake: NuttX use cygwin friendly path for linker script

- Tools/docker_run.sh
- src/modules/ekf2/test/CMakeLists.txt
Use px4io/px4-dev-simulation-bionic:2021-02-04 docker container to execute "make tests" failed.
The current docker image(px4-dev-simulation-bionic:2021-02-04) will cause "make tests" to fail: "kconfiglib is not installed or not in PATH", so update it's versions to 2021-12-11.
And the current basic image used by px4io/px4-dev-simulation-bionic is ubuntu18.04, the default version of cmake is 3.10, and the add_compile_definitions command is only available in cmake 3.12+(ubuntu 20.04), so use add_definitions instead of add_compile_definitions command.
> fix: use px4io/px4-dev-simulation-bionic:2021-02-04 docker container to execute "make tests" failed

- boards/cuav/x7pro/init/rc.board_sensors
- boards/px4/fmu-v4/init/rc.board_sensors
- boards/px4/fmu-v4pro/init/rc.board_sensors
- platforms/common/i2c_spi_buses.cpp
We need to get to the point where the failure of a known required sensor can't slip through.
> I2CSPIDriverBase: sensor start failure ERROR if internal, WARN if external

- src/lib/parameters/parameters.cpp
The BSON document size is the first int32 in the file. This needs to match the total number of bytes read until the end of the document to be valid.
Parameter import failure on the test rack px4_fmu-v4pro (these are rare, but do happen). http://px4-jenkins.dagar.ca:8080/blue/organizations/jenkins/PX4-Autopilot/detail/pr-update_src%2Fdrivers%2Fuavcan_v1%2Flibcanard/52/pipeline
- parameters were set (verified via param dump)
- `param save` issued
- after reboot the system has 0 parameters imported
- this could happen if reading from mtd_params returns nothing but zeros (0 document size (int32_t) followed by BSON EOO)
> parameters: require valid BSON document size

- src/systemcmds/tests/test_dataman.c
The index was not applied to all the semaphores.
> test_dataman:Set SEM_PRIO_NONE on all semaphores

- Tools/HIL/monitor_firmware_upload.py
- Tools/HIL/nsh_param_set.py
- Tools/HIL/reboot.py
- Tools/HIL/run_nsh_cmd.py
- Tools/HIL/run_tests.py
``` Console
$ ./Tools/HIL/run_nsh_cmd.py --cmd 'work_queue status'
Default USB UART port: ttyUSB0
device: /dev/ttyUSB0
description: "FT232R USB UART - FT232R USB UART"
hwid: USB VID:PID=0403:6001 SER=AC00CKKL LOCATION=1-2.4.1
manufacturer: FTDI
[2021-12-31T21:20:17.098]
Running command: 'work_queue status'
[2021-12-31T21:20:17.208]
[2021-12-31T21:20:17.209] Work Queue: 14 threads                          RATE        INTERVAL
[2021-12-31T21:20:17.209] |__ 1) wq:rate_ctrl
[2021-12-31T21:20:17.211] |   |__ 1) mc_rate_control                  804.7 Hz         1243 us
[2021-12-31T21:20:17.212] |   |__ 2) px4io                            398.7 Hz         2508 us
[2021-12-31T21:20:17.213] |   \__ 3) vehicle_angular_velocity         804.7 Hz         1243 us
[2021-12-31T21:20:17.214] |__ 2) …
```
> Tools/HIL: default to USB UART if available

- src/lib/parameters/flashparams/flashparams.cpp
- src/lib/parameters/param.h
- src/lib/parameters/parameters.cpp
- src/lib/parameters/tinybson/tinybson.cpp
- src/lib/parameters/tinybson/tinybson.h
- src/modules/commander/factory_calibration_storage.cpp
- src/modules/commander/factory_calibration_storage.h
- src/systemcmds/param/param.cpp
- src/systemcmds/tests/test_bson.cpp
- src/systemcmds/tests/test_parameters.cpp
In NuttX bchlib keeps a sector sized buffer that might not be written out to ramtron until the file is closed (depending on usage). This was also interfering with the recently add parameter verification functionality that was reading back after an export. Depending on the size of the parameters the verify read was only coming from the buffer rather than the underlying ramtron storage as intended.
As a result there can be final ramtron writes that happens outside of our px4 shutdown lock.
> parameters: fix export shutdown locking

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
Previously vehicles only supported position setpoints which were tracked using a L1 controller.
While this is sufficient to do waypoint navigation, it is hard do more advanced maneuvers using only a L1 position setpoint.
This PR adds support for offboard velocity setpoints for fixedwing type vehicles. The velocity can be commanded in the local frame and the vehicle will try to follow the velocity setpoints in 3D.
- The horizontal velocity `vx`, `vy` will be passed as the target groundspeed.
- The vertical velocity `vz` will be mapped to TECS height rate setpoints
Being able to command velocity setpoints in the local frame allows fixedwing vehicles to be used in more robotics oriented tasks such as trajectory …
> Fixedwing Add support for offboard velocity setpoints

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
Previously it was hard to interpret what the fw position controller was doing in term of tracking performance since the position setpoints were not logged in the local frame.
- It is hard to associate waypoints switching with the vehicle behavior, given that the fw pos control overrides the setpoints internally sometimes
- This is especially a problem when passing high bandwidth setpoints from offboard or for path tracking.
- For VTOLs the position setpoints just stops logging when the vehicle transitions to FW mode, since the local_position_setpoint is only published from the MC position controller module
This adds publication of the `vehicle_local_position_setpoint` so that it gets logged as a local setpoint. …
> Log vehicle local position setpoints for fixedwing position control

- src/modules/ekf2/EKF2.cpp
- src/modules/ekf2/EKF2Selector.cpp
- src/modules/ekf2/EKF2Selector.hpp
- use delayed IMU timestamp for the timestamp_sample in most EKF2 publications, except those from the output predictor (attitude, local_position, global_position).
This is a convenient way to more directly see the delayed time horizon.
``` Console
nsh> listener estimator_states
TOPIC: estimator_states 3 instances
Instance 0:
estimator_states
timestamp: 13760866 (0.009067 seconds ago)
timestamp_sample: 13648974 (111892 us before timestamp)
states: [0.9310, 0.0173, 0.0062, -0.3645, 0.0008, -0.0003, -0.1048, 0.0016, 0.0000, -0.2949, 0.0000, 0.0000, 0.0000, 0.0001, -0.0001, -0.0022, 0.0911, -0.0000, 0.2883, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]
covariances: [0.0000, 0.0001, 0.0001, 0.0002, 0.0060, 0.0060, 0.0937, 0.0038, 0.0038, 0.7124, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, …
```
> ekf2: use delayed IMU timestamp for publication's timestamp_sample

- src/modules/ekf2/EKF2.cpp
In https://github.com/PX4/PX4-Autopilot/pull/18001 we replaced the internal computation of the vibration metric that was done by the EKF to the metric computed in the IMU module directly. However, there is a scale issue due to the conversion between delta angles and angular velocity for the coning metric:
In the past, we were computing the vibration metric in the EKF:
```coning = lpf(d_theta[k] x d_theta[k-1])``` << note the cross product
now, it is computed on the integrated IMU data from angular velocities
```coning_vel = lpf(w[k] x w[k-1])```
and then sent to the EKF as `coning = coning_vel * dt`
however, since `d_theta = w * dt`,
```coning = lpf(w[k]*dt x w[k-1]*dt)```
or
```coning = coning_vel * dt^2```
> Fix delta angle coning metric

- src/modules/ekf2/EKF/common.h
- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF2.cpp
- src/modules/ekf2/EKF2.hpp
- src/modules/sensors/vehicle_imu/VehicleIMU.cpp
The ekf2 accel "calibration" (stable estimated bias) was initially based on the mag criteria (in flight + no faults + 3d mag fusion), but there's no accel equivalent to mag_3D.
This PR attempts to collect all relevant factors to the estimated accel bias being acceptable and require that they're all satisfied continuously for 30 seconds before declaring it's stable (acceptable to update calibration). This is just a first pass of what seemed appropriate, @bresch please update accordingly.
- vehicle not at rest
- valid height mode
- preflight no height failure
- no height sensor timeout
- no invalid_accel_bias_cov_reset
- no vertical velocity or position fusion rejections
- bias variance within valid min/max range continuously for entire period (not just when calibration is retrieved)
> ekf2: expand accel bias stability criteria

- src/modules/commander/failure_detector/FailureDetector.hpp
This prevents a memory sanitizer/valgrind warning:
```
Conditional jump or move depends on uninitialised value(s)
at 0x2DA536: __sanitizer_cov_trace_cmp4 (in build/px4_sitl_default-clang/bin/px4)
by 0x6590D8: FailureDetector::update(vehicle_status_s const&, vehicle_control_mode_s const&) (src/modules/commander/failure_detector/FailureDetector.cpp:76) by 0x3817DF: Commander::run() (src/modules/commander/Commander.cpp:2605)
by 0x38B10B: ModuleBase<Commander>::run_trampoline(int, char**) (platforms/common/include/px4_platform_common/module.h:180)
```
> commander: prevent uninitialized warning

- ROMFS/px4fmu_common/init.d/airframes/13013_deltaquad
- msg/vehicle_land_detected.msg
- src/modules/flight_mode_manager/FlightModeManager.cpp
- src/modules/flight_mode_manager/FlightModeManager.hpp
- src/modules/land_detector/LandDetector.cpp
- src/modules/land_detector/LandDetector.h
- src/modules/land_detector/MulticopterLandDetector.cpp
- src/modules/land_detector/MulticopterLandDetector.h
- src/modules/mc_pos_control/MulticopterPositionControl.hpp
- src/modules/navigator/mission_block.cpp
- src/modules/navigator/navigator.h
After https://github.com/PX4/PX4-Autopilot/pull/15020 the land detector is just copying the maximum altitude parameter to the uORB message and publishing it regularly with the `vehicle_land_detected` topic.
I'm using the parameter directly in the two places that access it namely the multicopter position controller and the mission block in navigator. This is just one iteration and the parameter should probably be consolidated with `GF_MAX_VER_DIST` like it's description writes.
I did not test this yet.
> Remove relaying of maximum altitude through land detector

- src/lib/sensor_calibration/Accelerometer.cpp
- src/lib/sensor_calibration/Accelerometer.hpp
- src/lib/sensor_calibration/Gyroscope.cpp
- src/lib/sensor_calibration/Gyroscope.hpp
- src/lib/sensor_calibration/Magnetometer.cpp
- src/lib/sensor_calibration/Magnetometer.hpp
- src/modules/sensors/vehicle_imu/VehicleIMU.cpp
- src/modules/sensors/vehicle_imu/VehicleIMU.hpp
These are the uncontroversial/mundane changes from https://github.com/PX4/PX4-Autopilot/pull/18950.
- sensors/vehicle_imu: reset learned cal on any calibration change during parameter update
- sensors/vehicle_imu: cleanup logic estimated bias -> calibration offset saving
- don't invalidate saved calibration (the point is to keep the last valid)
- remove old debug code, etc
- sensors/vehicle_imu: notify parameter changes if accel or gyro calibration has changed
- lib/sensor_calibration: add calibrated() and calibration_index() getters, keep Accelerometer/Gyroscope/Magnetometer in sync
> sensors: minor IMU bias saving updates

- .clusterfuzzlite/Dockerfile
- .clusterfuzzlite/build.sh
- .clusterfuzzlite/project.yaml
- .github/workflows/cflite_batch.yml
- .github/workflows/cflite_pr.yml
- Makefile
- boards/px4/sitl/sitl.cmake
- cmake/px4_add_common_flags.cmake
- cmake/sanitizers.cmake
- platforms/posix/CMakeLists.txt
- platforms/posix/src/px4/common/main_fuzztesting.cpp
This adds the env option PX4_FUZZ which runs the LLVM libFuzzer which throws random bytes at mavlink_receiver using MAVLink messages over UDP.
The MAVLink messages that are being sent are valid, so the CRC is calculated but the payload and msgid, etc. are generally garbage, unless the fuzzing gets a msgid right by chance.
As I understand it, libFuzzer watches the test coverage and will try to execute as much of the code as possible.
To run this, do:
```
PX4_FUZZ=1 make px4_sitl_default-clang && (cd build/px4_sitl_default-clang/tmp/rootfs && mkdir CORPUS -p && ../../bin/px4 -detect_leaks=1 CORPUS/)
```
To stop it (if it never crashes): `killall px4`, or Ctrl+C.
So far I've been running this multiple days on a desktop computer but have not found anything.
> posix: add fuzz testing using MAVLink messages

- src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
- src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.hpp
When sending consecutive reposition commands to a multicopter that contain different altitudes and not waiting until the previous target position was reached there's very strange behavior.
This solves one of the issues when switching goto target mid-flight where the altitude overshoots. Only the horizontal path between waypoints was considered in the "off-track" calculations. I'm using the exact same calculations just in 3D to also consider the altitude.
Further improvements with unexpected waypoint changes require architecture changes to solve properly and are work in progress with the new mode architecture.
I tested this in SITL and SIH and the …
> FlightTaskAuto: Respect altitude with offtrack state

- src/modules/commander/Commander.cpp
- VEHICLE_CMD_COMPONENT_ARM_DISARM is yet another path that calls set_home_position()
There are quite a few paths through commander that set and update home_position.
> commander: fix COM_HOME_EN missing case

- src/modules/sensors/vehicle_imu/VehicleIMU.cpp
- src/modules/sensors/vehicle_imu/VehicleIMU.hpp
- src/modules/sensors/vehicle_imu/imu_parameters.c
Similar to https://github.com/PX4/PX4-Autopilot/pull/18421 for magnetometer this change will use an available stable estimated bias to set initial accel and gyro calibrations if the sensors are completely uncalibrated.
At the moment this is fairly conservative for accel.
- can be enabled via SENS_IMU_AUTOCAL parameter
- this parameter also controls saving the learned EKF2 IMU biases back to calibration parameters
> sensors: automatically set initial accel/gyro calibration if stable bias available

- src/lib/mathlib/math/filter/NotchFilter.hpp
- src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
- src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.hpp
- this simplifies the reset by allowing a notch filter to reset as needed
- improves cascade initialization, on reset each filter will reset properly from the output of the previous
- reset conditions can be handled more intelligently internally (eg decide to reset if only the notch frequency moves sufficiently)
TODO:
> NotchFilter push initialization/reset into filter

- src/lib/sensor_calibration/Accelerometer.cpp
- src/lib/sensor_calibration/Accelerometer.hpp
- src/lib/sensor_calibration/Gyroscope.cpp
- src/lib/sensor_calibration/Gyroscope.hpp
- src/lib/sensor_calibration/Magnetometer.cpp
- src/lib/sensor_calibration/Magnetometer.hpp
- src/modules/sensors/sensors.cpp
This is a small bug that slipped in at some point and only matters if your sensors move around (instance numbering) between full manual recalibrations.
When performing a full (re-)calibration the accel/gyro/mag calibration parameters are written out in the current sensor topic order. Downstream consumers (eg sensors/vehicle_imu) need to handle the case where the calibration slot (eg CAL_ACCx) has changed.
> lib/sensor_calibration: handle calibration slot change on parameter update

- .ci/Jenkinsfile-hardware
- src/modules/sensors/vehicle_imu/VehicleIMU.cpp
- on cycles that don't check for updated calibration (estimated bias) we check if there's anything valid to save (when disarmed)
> sensors/vehicle_imu: fix SENS_IMU_AUTOCAL saving logic

- boards/freefly/can-rtk-gps/init/rc.board_defaults
- src/drivers/uavcannode/UavcanNode.cpp
- src/drivers/uavcannode/uavcannode_params.c
This PR adds a param to cannodes in order to turn on/off publishing/subscribing to RTCM data. It is set to off by default and for the ARK RTK GPS and Freefly GPS, it is set to on by default.
> Add CANNODE_GPS_RTCM

- src/lib/sensor_calibration/Accelerometer.cpp
- src/lib/sensor_calibration/Accelerometer.hpp
- src/lib/sensor_calibration/Gyroscope.cpp
- src/lib/sensor_calibration/Gyroscope.hpp
- src/lib/sensor_calibration/Magnetometer.cpp
- src/lib/sensor_calibration/Magnetometer.hpp
- src/lib/sensor_calibration/Utilities.cpp
- src/lib/sensor_calibration/Utilities.hpp
- src/modules/commander/Arming/PreFlightCheck/checks/accelerometerCheck.cpp
- src/modules/commander/Arming/PreFlightCheck/checks/gyroCheck.cpp
- src/modules/commander/Arming/PreFlightCheck/checks/magnetometerCheck.cpp
- src/modules/commander/accelerometer_calibration.cpp
- src/modules/commander/gyro_calibration.cpp
- src/modules/commander/mag_calibration.cpp
- src/modules/gyro_calibration/GyroCalibration.cpp
- src/modules/sensors/vehicle_imu/VehicleIMU.cpp
- src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
- src/modules/sensors/voted_sensors_update.cpp
- centralize logic for selecting a preferred calibration slot
- automatically use existing calibration slot if it exists, otherwise find first available slot, with a preference for a requested index
- existing commander calibration methods rewrite all calibration slots to match current sensor ordering
> sensor_calibration: refactor and centralize calibration slot logic

- msg/battery_status.msg
- msg/esc_report.msg
- src/lib/events/enums.json
- src/lib/mathlib/math/Functions.hpp
- src/lib/mathlib/math/FunctionsTest.cpp
- src/modules/commander/Arming/PreFlightCheck/checks/powerCheck.cpp
- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
- src/modules/mavlink/streams/BATTERY_STATUS.hpp
With Smart batteries being more widely available in the industry the need of better handling for battery faults has increased also here in PX4. 
This PR extends the checks performed in commander to handle in-flight battery disconnection and/or faults by extending the checks with the BATTERY_FAULT and BATTERY_MODE described in mavlink https://mavlink.io/en/messages/common.html#BATTERY_STATUS.
For the batteries a new field `is_required` has been introduced in the uORB message. The goal of this field is to allow Drone manufacturers to specify the minimum number of …
> Commander: Extend battery status checks and rework ESC checks

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
- src/modules/navigator/mission_block.cpp
Waypoint item reached criteria for fixed-wing behaviors currently span the navigator, fixed-wing position controller, and L1 guidance library. Each location having slightly varying handling. For the case of waypoints in sequence, current handling strategies include:
- in navigator: check on horizontal acceptance radius + acceptance altitude (```NAV_FW_ALT_RAD```)
- in fw_pos_ctrl_l1: (for the case of loitering up to alt at the terminal waypoint) check on acceptance altitude (```2 * _param_fw_clmbout_diff```)
- in ECL_L1_Pos_Controller: once the aircraft is beyond the terminal waypoint and within some cone, guidance is switched to flying back to the terminal waypoint.
https://github.com/PX4/PX4-Autopilot/blob/463513f31fedad64cfad6d2ede19ef66c …
> handle line segment termination in navigator

- src/modules/fw_att_control/fw_att_control_params.c
- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c
In position and altitude control the roll angle was constrained using the same limits as for stabilized mode.
Additionally, the parameter description of both manual and autonomous limits was not very clear I found.
People might have different opinions on this, please raise concerns if you have any.
Use the same roll constraints as for autonomous modes. Even thought the roll angle is directly controlled by the user, in the context of the modes it makes sense to consistently use the same roll limit. E.g. in altitude and position control altitude and airspeed are both regulated by the controller and excessive roll angle setpoints by the user can cause bad performance and in the worst case a stall.
**Describe possible …
> Constently use same roll/pitch limits in Fixed Wing Position Controller

- Tools/setup/arch.sh
- Tools/setup/ubuntu.sh
I don't think the PX4 setup script should decide whether a user is to use ccache or not. Anecdotally, I've heard from some in the dev team that they are not using it themselves, so I don't think there is a good basis to push it onto others.
That being said, we can of course still use ccache as part of the CI builds nevertheless.
> setup: don't install ccache

- src/drivers/dshot/DShot.h
- src/drivers/uavcan/actuators/esc.cpp
- src/drivers/uavcan/actuators/esc.hpp
UAVCAN esc_status was publishing even with no ESCs attached. Additionally dshot was only publishing to the first esc_status instance.
> fix UAVCAN esc_status publish conflict

- Tools/module_config/generate_actuators_metadata.py
- Tools/module_config/generate_params.py
- src/drivers/linux_pwm_out/module.yaml
- src/drivers/pwm_out/module.yaml
- src/drivers/pwm_out_sim/module_hil.yaml
- src/drivers/pwm_out_sim/module_sim.yaml
- src/drivers/px4io/module.yaml
- src/drivers/uavcan/module.yaml
- src/drivers/uavcan_v1/module.yaml
- src/lib/mixer_module/mixer_module.cpp
- src/modules/control_allocator/module.yaml
- validation/module_schema.yaml
and remove the possibility to set min > max to reverse.
Initially the idea was to add the checkbox on the UI side, to avoid adding
another param, but I don't think I'll go through the extra effort on the
QGC side.
> actuator outputs: always add reverse range param 

- src/lib/wind_estimator/WindEstimator.cpp
- src/lib/wind_estimator/WindEstimator.hpp
- src/modules/airspeed_selector/AirspeedValidator.cpp
- src/modules/airspeed_selector/AirspeedValidator.hpp
Replaces https://github.com/PX4/PX4-Autopilot/pull/19011
Currently the ground course is used to map the airspeed measurement to a airspeed vector during the wind speed initialization (wind = ground - airspeed), as the airspeed sensor always points into the direction of the vehicle.
Use vehicle heading. 
SITL
New:
Old:
> Wind Estimator: use vehicle heading instead of course for initialisation

- src/lib/wind_estimator/WindEstimator.cpp
- src/lib/wind_estimator/WindEstimator.hpp
Trivial clang-tidy complaint introduced in https://github.com/PX4/PX4-Autopilot/pull/19013. 
FYI @sfuhrer
> lib/wind_estimator: pass q_att as const reference

- platforms/posix/cmake/sitl_target.cmake
If we use -j 0, ninja fails with invalid argument.
Closes #18738.
> cmake: use at least 1 core to build simulator

- src/drivers/uavcan/beep.cpp
- src/drivers/uavcan/beep.hpp
- src/drivers/uavcan/uavcan_main.cpp
- src/drivers/uavcan/uavcan_main.hpp
This PR starts the UAVCAN beep publication. The fw server merge missed starting this. I have also changed the beep class name to match the other Controller publishers naming convention.
> Fix UAVCAN beep not started

- .ci/Jenkinsfile-hardware
- Tools/HIL/test_airframes.sh
- src/lib/parameters/parameters.cpp
- on NuttX with MTD storage this is to ensure we are verifying what's actually stored on ramtron or eeprom, not just what's cached by bchlib
> parameters: perform verification pass twice

- src/modules/commander/failure_detector/FailureDetector.cpp
The existing metric is nonlinear and has the consequence that the test is more sensitive with higher overall vibration levels.
Use standard deviations instead of variance to create a linear metric.
Also fix the dt computation.
Many test flights on our internal branch. The check produces much less false positives.
> Failure detector: improve imbalanced propeller metric

- platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp
- platforms/common/px4_work_queue/WorkQueueManager.cpp
Naming these wq:UARTx is unnecessarily confusing because it usually doesn't match up with the actual hardware.
> px4_work_queue: rename serial port WQs

- src/modules/sensors/data_validator/DataValidator.cpp
- src/modules/sensors/vehicle_air_data/VehicleAirData.cpp
- src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
- src/modules/sensors/voted_sensors_update.cpp
This is a quick attempt to minimize sensor timeout false positives as a result of things like parameter updates, etc. Use single time stamp from beginning of cycle run rather than the current time stamp at each point. Data validator sensor timestamp use publication time rather than sample timestamp.
> sensors: simplify timestamp data validator handling

- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTiltrotorVTOL.cpp
- src/modules/control_allocator/ControlAllocation/ControlAllocation.cpp
- src/modules/control_allocator/ControlAllocation/ControlAllocation.hpp
- src/modules/control_allocator/ControlAllocation/ControlAllocationPseudoInverse.cpp
- src/modules/control_allocator/ControlAllocation/ControlAllocationPseudoInverse.hpp
- src/modules/control_allocator/ControlAllocation/ControlAllocationPseudoInverseTest.cpp
- src/modules/control_allocator/ControlAllocator.cpp
2 Issues:
1) The scale for the normalization should not be updated when the tilt of the motor changes in air (or if an actuator is switched off in air due to a detected failure in the future), but only when the configuration changes before flying. 
2) For tiltrotor the calculation of the average roll/pitch effect was wrong, as using the /`_num_actuators` is wrong in this case because e.g. actuators 5-8 are tilts that don't have an entry in the roll or pitch column.
1) The `forced` flag is used to distinguish when the matrix is updated because the user changes the configuration (only enabled when disarmed), and when the matrix is updated because the geometry changes due to motors being tilted.
In the future another …
> ControlAllocation: mixer matrix normalization fixes

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
- src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c
Currently moving the throttle stick in manual Altitude and Position flights changes the airspeed setpoint. I think for most users it would be easier to be able to set the speed in the UI of QGC, like I'm pushing for with https://github.com/PX4/PX4-Autopilot/pull/18834. And especially for setups with spring loaded sticks the UX for airspeed setting via sticks is particularly bad. 
Rename FW_POSCTL_INV_ST to FW_POS_STK_CONF and make bitmask out of it:
- bit 0: alternative mapping (height rate on throttle stick, airspeed on pitch)
- bit 1: enable/disable airspeed setpoints via stick
Flight tested on various platforms.
> FW Pos C: add option to disable airspeed setpoint via stick input

- src/modules/mc_pos_control/MulticopterPositionControl.cpp
- src/modules/mc_pos_control/PositionControl/PositionControl.cpp
- src/modules/mc_pos_control/PositionControl/PositionControl.hpp
- src/modules/mc_pos_control/PositionControl/PositionControlTest.cpp
Settings a specific combination of invalid `trajectory_setpoint` can lead to a flyaway.
This was found during simulation debugging for #18988 
I found that depending on the setpoint combination the velocity integrator can wind up because the calculations are ran with the invalid setpoint. Even though the results of the "invalid calculation" are not use the integrator state inside the controller is updated and leads to the problem.
1. I added a minimal unit test to reproduce the error case.
2.  I made the checks for valid inputs and combinations very explicit at the beginning and don't run any calculations if they do not pass the check.
3. The existing tests and the new one pass.
Added unit …
> Multicopter position control: Invalid setpoint can windup integrator

- src/lib/npfg/npfg.cpp
Spotted an accidental instance of indexing a `Vector2f` with floats.. fixed that.
> npfg: fix typo in Vector2f indexing

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
Previously, the orbit status was published only when the mission item was a loiter waypoint.
However, the fixedwing position controller goes into a loiter not only when the waypoint is a loiter, but also when other conditions are met as shown below.
https://github.com/PX4/PX4-Autopilot/blob/632dfa55e6f231f1b62fb2e9bfb048d391ebafc9/src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp#L1077-L1082
Therefore when the fixedwing position controller internally switches waypoint types, there is no feedback to the user other than the vehicle deviating off course. From experience, this can be very dangerous when flying a survey mission on steep terrain, while the vehicle does not give any feedback.
This PR makes the …
> Only publish orbit status when vehicle is in loiter

- platforms/nuttx/src/px4/stm/stm32f4/px4io_serial/px4io_serial.cpp
- platforms/nuttx/src/px4/stm/stm32f7/px4io_serial/px4io_serial.cpp
- platforms/nuttx/src/px4/stm/stm32h7/px4io_serial/px4io_serial.cpp
- this really shouldn't be necessary, but worst case it's harmless and much better than potentially falling out of the sky
https://github.com/PX4/PX4-Autopilot/pull/18893
@JohnSnowball
> platforms/nuttx: px4io_serial always cleanup DMA before next bus exchange

- src/modules/ekf2/EKF/control.cpp
- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/gps_control.cpp
The existing logic using the angle between velocity vectors failed to determine a yaw failure in practice because the state velocity is often too small compared to its uncertainty to be used. In all the failures reported, the yaw emergency estimator converged properly and yaw reset would have fixed the issue.
A much simpler check using the yaw difference between the main EKF and the emergency estimator is now used to tell if the vel/pos update failure is most likely caused by a wrong heading.
SITL tested with faulty mag data
> ekf2: replace yaw failure detection criteria

- platforms/common/uORB/uORB.cpp
Could have led to invalid memory access.
> uORB: fix copy-paste mistake in orb_print_message_internal

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
In https://github.com/PX4/PX4-Autopilot/pull/19042 the orbit status message publishing had been removed when the position controller was considering loiter type waypoints as a position setpoint. This PR retains this back to the current state. 
Publish orbit status also when the waypoint is a loiter waypoint
```
make px4_sitl gazebo_plane
```
- This is a follow up PR of https://github.com/PX4/PX4-Autopilot/pull/19042
> Publish orbit status also when the waypoint is a loiter waypoint

- src/drivers/magnetometer/bosch/bmm150/BMM150.cpp
- src/drivers/magnetometer/bosch/bmm150/BMM150.hpp
- src/drivers/magnetometer/bosch/bmm150/Bosch_BMM150_registers.hpp
- src/drivers/magnetometer/bosch/bmm150/bmm150_main.cpp
Anecdotal report of a Bosch BMM150 magnetometer not starting consistently. Retrying the probe multiple times is harmless.
> bmm150: retry probe up to 3 times

- src/drivers/uavcan/CMakeLists.txt
- src/drivers/uavcan/logmessage.hpp
- src/drivers/uavcan/uavcan_main.cpp
- src/drivers/uavcan/uavcan_main.hpp
- src/drivers/uavcannode/UavcanNode.cpp
- src/drivers/uavcannode/UavcanNode.hpp
On a CAN node this publishes PX4_INFO/PX4_WARN/PX4_DEBUG messages as UAVCAN LogMessage.
On regular PX4 it sends received UAVCAN LogMessages through the regular log infrastructure (px4_log_modulename). The log output is showing with `[uavcan:NODE_ID:MODULE_NAME]` as the module name.
> uavcan/uavcannode: bridge LogMessage and PX4 ORB_ID(log_message_s)

- Tools/gazebo_sitl_multiple_run.sh
It was reported(https://discuss.px4.io/t/multi-standard-vtol-are-unstable-in-gazebo/25850) that the mutlivehicle script(`Tools/gazebo_sitl_multiple_run.sh) fails for the `standard_vtol`
This commit fixes the spawn location of the multivehicle gazebo sitl script. This is consistent with the default sitl script: https://github.com/PX4/PX4-Autopilot/blob/ed28b216c7f904c2e2f95cd494fa1b0c82e6f4e0/Tools/sitl_run.sh#L169
Tested with
```
Tools/gazebo_sitl_multiple_run.sh -m standard_vtol
```
> Spawn at different height for multivehicle simulation

- src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
- src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.hpp
- src/modules/sensors/vehicle_angular_velocity/imu_gyro_parameters.c
Some vehicles need more than 3 harmonics of the ESC frequency to effectively filter.
To filter out the remaining high frequency noise we need to increase from 3 to 6 (or 7) harmonics.
> sensors/vehicle_angular_velocity: add IMU_GYRO_DNF_HMC to configure number of ESC RPM notch filter harmonics

- src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
- src/modules/flight_mode_manager/tasks/ManualAltitudeSmoothVel/FlightTaskManualAltitudeSmoothVel.hpp
- src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
- src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.hpp
It's possible to have steps when entering and exiting the circle approach:
1. @ThomasDebrunner removed switching to a circle approach if the radius is just slightly adjusted using the stick.
2. I found a typo and did some variable name improvement refactoring.
3. I checked how the position smoothing is initialized and made sure it's using the previous setpoint rather than the current vehicle state. This should give better results because the resulting error should then be continuous while if the setpoint jumps to the current vehicle state the error jumps to zero.
We should further improve the interface for using the jerk trajectory library to make it easier to reuse.
**Test data …
> Orbit approach transition improvements

- src/modules/ekf2/EKF/control.cpp
Following up #19031. If magnetometer is disabled, optical flow data was not fused and the local position couldn't initialize.
Tested on a Pixracer-compatible board.
> ekf2: fuse optical flow when magnetometer is disabled

- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/mag_control.cpp
The mag field disturbed preflight check was triggering even with EKF2_MAG_TYPE to set none.
- requires valid mag data (_mag_data_ready)
- respect mag_fusion_type (including MAG_FUSE_TYPE_INDOOR)
> ekf2: mag field strength check respect requirements

- src/modules/ekf2/EKF/control.cpp
- src/modules/ekf2/EKF/covariance.cpp
In ekf2 if there's any accel clipping at all we set `_fault_status.flags.bad_acc_clipping`. In practice this is way too sensitive as it results in unnecessary estimator switching during mundane events like setting a board with a hard mounted IMU on a table. It can also be too aggressive when there's real frequent clipping across multiple IMUs because the selector sees clipping on the current primary instance and then switches immediately to the next available instance only to see clipping on the next update.
I'm not sure if this change might be moving too far in the other direction, but it now exposes more internal state (_fault_status.flags.bad_acc_clipping = is_clipping_frequently) that we can monitor and adjust as needed.
> ekf2: only set fault status bad_acc_clipping if clipping frequently

- src/modules/logger/log_writer_file.cpp
If the board supports encrypting logfiles, but the parameter SDCARD_ALGORITHM is set to NONE,
the log should be written to the sdcard in plaintext format. This fixes a bug which caused
logger to hang in mutex instead.
> Fix sdcard logging when crypto is used but algorithm is set to NONE

- src/lib/drivers/device/CMakeLists.txt
- src/lib/rc/CMakeLists.txt
- src/modules/px4iofirmware/CMakeLists.txt
This were a few unnoticed mistakes in PR #19080
Something picked up erroneously when re-basing commits
- The one line in drivers__device CMakeLists.txt didn't make sense
- Building px4_io-v2 broke
This fixes those issues
> Fix errors from PR 19080

- src/drivers/distance_sensor/tfmini/tfmini_parser.cpp
When TFmini is Strength<20, it returns a value of 65535.
SPEC
Dist: Represents the output of the distance value detected by TFmini, with the unit in cm by default. This
value is interpreted into the decimal value in the range of 0-1200.In the practice, if the signal strength valueStrength<20 (which is settable), the value of Dist will be deemed as unreliable and FFFF will be output by
default (-1 in case of Pixhawk data format). If Strength≥20 and actual distance >12m, the default output
value of Dist will be 1,200(cm).
I did not set the …
> tfmini: If the distance is 0xFFFF, a negative value is returned

- msg/vehicle_odometry.msg
- src/modules/ekf2/EKF/common.h
- src/modules/ekf2/EKF/control.cpp
- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/ekf_helper.cpp
- src/modules/ekf2/EKF/estimator_interface.h
- src/modules/ekf2/EKF2.cpp
- src/modules/ekf2/EKF2Selector.cpp
- src/modules/ekf2/EKF2Selector.hpp
- src/modules/mavlink/mavlink_receiver.cpp
- src/modules/mavlink/streams/ODOMETRY.hpp
- src/modules/simulator/simulator_mavlink.cpp
- respect Mavlink ODOMETRY reset_counter http://mavlink.io/en/messages/common.html#ODOMETRY
- copy all odometry reset counts through (mavlink, ekf2, estimator selector)
- ekf2 reset velocity, position, yaw on reset count change if relevant control modes are active
> add odometry reset counter (ekf2, mavlink, etc)

- src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp
- src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.hpp
- src/modules/commander/Arming/PreFlightCheck/checks/preArmCheck.cpp
- src/modules/commander/Commander.cpp
- src/modules/commander/commander_tests/state_machine_helper_test.cpp
- src/modules/commander/state_machine_helper.cpp
- src/modules/commander/state_machine_helper.h
- handles a few edge cases at arming time that might slip through on a degraded system
- preflight tolerate ekf2 warnings if not in an attitude/velocity/position mode (eg manual or acro)
> commander: respect control mode for prearm requirements

- src/modules/ekf2/EKF/control.cpp
- src/modules/ekf2/EKF/ekf.cpp
- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/ekf_helper.cpp
- src/modules/ekf2/EKF/estimator_interface.h
- src/modules/ekf2/EKF/gps_control.cpp
- src/modules/ekf2/EKF/mag_control.cpp
- src/modules/ekf2/EKF/mag_fusion.cpp
- remove class _mag_sample_delayed
- update mag fusion call graph to use mag sample delayed functionally
- Ekf::resetMagHeading()
- use low pass mag directly, but check if valid (magnitude)
- MAG_FUSE_TYPE_INDOOR treat like auto if heading required
> ekf2: refactor mag control

- boards/px4/fmu-v5/nuttx-config/scripts/kernel-space.ld
- boards/px4/fmu-v5/nuttx-config/scripts/memory.ld
- boards/px4/fmu-v5/nuttx-config/scripts/user-space.ld
- platforms/nuttx/CMakeLists.txt
- platforms/nuttx/src/px4/common/CMakeLists.txt
- platforms/nuttx/src/px4/common/console_buffer_usr.cpp
- platforms/nuttx/src/px4/common/px4_layer.cmake
- platforms/nuttx/src/px4/common/px4_protected_layers.cmake
- platforms/nuttx/src/px4/common/usr_mcu_version.cpp
This PR adds the following in preparation for running PX4 in NuttX "protected build" configuration
- Linker scripts for building separate kernel and userspace blobs
- Cmake file change for building the two separate blobs and combining them into one for flashing
- px4_layer split into two: The OS specific part for kernel side linkage and the OS specific part for the user side linkage.
The px4_layer for user space contains a few stubs: 
- console_buffer_usr.cpp: we could avoid having this at all if we'd just define that the "protected" build doesn't support console buffer at all (this can be flagged in the board definition). I initially added a stub for it, so that we could have an implementation for it there in the future
- usr_mcu_version.cpp: Just give a version info of 00000 for now, as …
> Protected build linker scripts and px4 layer

- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
- src/modules/commander/commander_params.c
- src/modules/commander/state_machine_helper.cpp
- src/modules/commander/state_machine_helper.h
- src/modules/simulator/battery_simulator/BatterySimulator.cpp
If the low battery action is enabled (see [COM_LOW_BAT_ACT](https://docs.px4.io/master/en/advanced_config/parameter_reference.html#COM_LOW_BAT_ACT)) and the battery gets over the threshold the drone immediately does the action without any warning or time for the user to react. There were multiple cases where the unexpected ascend of the RTL which usually is the first action led to crashes because of an obstacle above the vehicle or a panic reaction. Often the pilot is already landing manually and is unpleasantly surprised about the sudden upwards acceleration.
- Refactor battery failsafe to be able to separately warn the user and get the battery failsafe action
- Introduce a delay of by default 10s between low …
> Battery failsafe delay

- msg/geofence_result.msg
- src/modules/navigator/geofence.cpp
- src/modules/navigator/geofence.h
This PR is some minor housekeeping in the Geofence Class. Some whitespace formatting is performed, a few variable initializations are added, and a cut/paste of one checkall() method overload to group it next to the other overloads is accomplished in geofence.cpp  The `getAltitudeMode()` getter is replaced with `_param_gf_altmode.get()` as the method is unused outside of the class.  Similar whitespace formatting/housekeeping is acccomplished in geofence.h
SITL tested with jmavsim, no functional changes are contained in this PR.
Let me know if you have any questions on this PR.  Thanks!
> Minor whitespace formatting and group checkAll() methods in the geofence class

- src/drivers/gps/params.c
The doc referred to first and second antennas. The change modifies the terminology to properly identify the antenna as rover and moving base.
Comes from https://github.com/PX4/PX4-user_guide/pull/1740
> GPS_YAW_OFFSET param docs: use rover and moving base terminology

- src/modules/ekf2/EKF/ekf.h
I don't see why these should be inlined, they aren't called at high rate.
Saves about 1.8 kB of flash.
> ekf2: remove unnecessary inlines

- ROMFS/px4fmu_common/init.d-posix/airframes/1037_believer
- src/lib/npfg/npfg.cpp
- src/lib/npfg/npfg.hpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
Fixedwing vehicles have mainly been controlled using waypoints. However, this makes it challenging to operate fixedwing vehicles close to obstacles/terrain since it is hard to predict the trajectory of the vehicle without executing the mission. 
Given that Fixedwing vehicles are more influenced by wind compared to multirotors, it is better for the vehicle to track a given **path** rather than a time stamped **trajectory**. With NPFG available in PX4, we can now precisely track arbitrary paths.
This PR adds a path tracking interface using offboard mode for fixedwing vehicles. The vehicle can follow arbitrary paths by passing a. a position setpoint, which should be the closest point on the path b. a velocity vector, …
> Add offboard path tracking for fixedwing vehicles using NPFG

- cmake/kconfig.cmake
- platforms/common/include/px4_platform_common/px4_config.h
Generate C/C++ header to expose px4board kconfig symbols to the preprocessor.
This allows to use #ifdef to check whenever a module/systemcd/driver is enabled.
> Generate C/C++ header to expose px4board kconfig symbols

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
For Go To waypoints, the loiter radius of the position setpoint is zero, and therefore orbit status was publishing zero radius. 
This resulted in the orbit status being displayed as a point on QGC. However, the goto waypoints are handled using a default loiter radius defined by the parameter when navigating through goto waypoints
This commit corrects this by passing the default loiter radius as the guidance logic was using
```
make px4_sitl gazebo_plane
```
- Before PR
- After PR
> Handle orbit status messages for go to waypoints

- src/modules/commander/state_machine_helper.cpp
Currently Quadchutes are handled differently for Mission and non-mission flight modes. In Mission it RTLs, in the other Auto modes it goes to the currently active wp (e.g. center of loiter) and just waits there.
It also triggers RTL in Loiter and VTOL_Takeoff modes.
Add option to customize action after quadchute.
SITL tested.
> Commander: VTOL quadchuate also triggers a RTL in Loiter and VTOL_Takeoff modes, not just in Mission

- src/drivers/protocol_splitter/protocol_splitter.cpp
This also guarantees that i is increased in every loop iteration.
Before it was possible to enter a busy loop.
Properly increase the `i` counter.
> Protocol_splitter: Increment i properly in scan_for_packets

- src/drivers/magnetometer/bosch/bmm150/BMM150.cpp
- src/drivers/magnetometer/bosch/bmm150/BMM150.hpp
- src/drivers/magnetometer/bosch/bmm150/Bosch_BMM150_registers.hpp
I noticed some weird data output on a Bosch BMM150 mag so I did a paranoid review of the PX4 driver vs the Bosch reference code (https://github.com/BoschSensortec/BMM150-Sensor-API/).
The only differences I found were in the least significant bit of our XY data (shouldn't matter), and a few checks around RHALL usage and trim data values. I'm not sure if this accounts for the bogus data I saw, but it also shouldn't hurt.
> bmm150: minor changes to match reference driver

- src/modules/ekf2/EKF/fake_pos_control.cpp
- src/modules/ekf2/test/test_EKF_externalVision.cpp
Given how sensitive the vehicle at rest detection is (you can't even touch a board without triggering) can we further reduce the ekf2 fake position observation variance so that tilt align completes even faster?
With current master on px4_fmu-v5x EKF alignment takes about 6 seconds (time from boot). This change reduces it to about 3.5 seconds.
> ekf2: lower fake position observation variance when at rest

- src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
- src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.hpp
- src/modules/land_detector/MulticopterLandDetector.cpp
- src/modules/land_detector/MulticopterLandDetector.h
- src/modules/mc_pos_control/mc_pos_control_params.c
Multirotors hit the ground vertically with land speed `MPC_LAND_SPEED` during autonomous landing. This speed should ensure there's no damage caused upon touch down but is high enough to not unnecessarily prolong the landing procedure. The user expereince of the vehicle hitting the ground at land speed is not necessarily nice. Since it might see the ground approaching using a distance sensor it could slow down further just for touch down.
**Describe @ThomasDebrunner 's solution**
This PR adds params for crawl speed and landing altitude 3. In case distance sensor measurements are available, the vehicle slows down to crawl speed at landing altitude 3, for an extra smooth landing. In case no LIDAR data is available, the behavior doesn't change. …
> Three stage atuonomous multicopter landing

- src/modules/micrortps_bridge/micrortps_client/microRTPS_client_main.cpp
- src/modules/micrortps_bridge/micrortps_client/module.yaml
It doesn't take too many RTPS topics to exceed the bandwidth of a serial connection. In my case RTPS data was using >70 KB/s on a 921600 baud connection, and the connected computer could not reliably establish an RTPS connection.
This parameter allows an easy way for users to specify the appropriate data rate. It defaults to unlimited data.
After configuring RTPS, I verified that `micrortps_client status` correctly reports back the transmit limit.
> Add configurable RTPS rate parameter

- boards/px4/fmu-v4/init/rc.board_sensors
Hello!
We're producing and shipping a Pixracer compatible flight controller — [COEX Pix](https://clover.coex.tech/en/coex_pix.html). For now, we have shipped more then 2K of items. This flight controller has fewer sensors, in particular, it doesn't have the HMC5883 magnetometer.
The problem is that `fmu-v4` startup scripts doesn't start the MPU9250's magnetometer for some reason. I don't know if this intended. But in our case this results in that there no magnetometer working at all.
There might be several solutions for this, but here is a solution I came up with: if none of the separated internal magnetometers (HMC5883 or LIS3MDL) has started successfully, then use the MPU9250's magnetometer.
> Enable mpu9250 mag if other mags don’t start

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/navigator/land.cpp
- src/modules/navigator/mission_block.cpp
**Describe problem solved by this pull request and how I solved it**
Two partly related things:
- when triggering LAND, the VTOL started the transition immediately and was then tracking a point slightly behind the vehicle, causing it to turn during the backtransition (instead of flying straight). Instead it should be tracking a point slightly in front of the vehicle (I set it to 1m for now)
- the position setpoint during transition was set to Loiter, and that caused it to display the Orbit status circle. Setting it to Position type looks more correct to me.
current:
https://user-images.githubusercontent.com/26798987/153183183-3cb4c589-cfc7-4be2-b42e-92a020d9e741.mp4
with the fixes:
https://user-images.githubusercontent.com/26798987/153183417-93c42a56-092e-4e32-a446-73e86413dc4b.mp4 …
> VTOL backtransition tracking improvements

- src/modules/sensors/vehicle_air_data/VehicleAirData.cpp
- src/modules/sensors/vehicle_air_data/VehicleAirData.hpp
- src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
- src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.hpp
- src/modules/sensors/voted_sensors_update.cpp
- src/modules/sensors/voted_sensors_update.h
Parameter changes can be relatively expensive to the point where they can trigger false positives in sensor timeouts on older boards. In the `sensors` module during a cycle where the parameters update we can temporarily bypass the voting re-selection to avoid false positives. These modules throttle parameter updates (1 Hz), so worst case the detection of a perfectly timed legitimate failure would only be delayed until the next iteration (eg 5 ms later for an IMU).
> sensors: skip selection and failover checks during parameter update

- src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
When on a goto action, changing the altitude creates a strange behavior: the vehicle stops, flies a couple of meters backwards and yaws while changing the altitude and then continues towards the goto point.
The current implementation checks for "offtrack" condition when the vehicle is too far from the expected path. Since the target altitude changed, the drone isn't on the "prev-to-next-wp" line and goes into that mode. When in offtrack, the autopilots guides the vehicle to the closest point on the line. That works well in the XY-plane, but when including Z, it generates an unwanted "backwards" motion (see drawing below).
I first considered the "other option" (depicted below) but then decided to go for the more …
> Fix unexpected yaw during GOTO when altitude changes

- msg/estimator_status.msg
- msg/estimator_status_flags.msg
- src/modules/ekf2/EKF/common.h
- src/modules/ekf2/EKF/control.cpp
- src/modules/ekf2/EKF/ekf.cpp
- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/sensor_range_finder.cpp
- src/modules/ekf2/EKF/sensor_range_finder.hpp
- src/modules/ekf2/EKF/terrain_estimator.cpp
- src/modules/ekf2/EKF2.cpp
- src/modules/ekf2/test/test_EKF_terrain_estimator.cpp
Mostly a pure refactoring.
- The terrain estimator checks if the aiding source (range and flow) can be used instead of having `control.cpp` doing it at various places
- Range terrain aiding has priority over flow terrain
- Flow terrain cannot start when flow is fused into the main EKF for velocity aiding
Added a range finder failure detection when the measurement has been rejected for some time and that the measured distance is smalle (< 2x the minimum distance from sensor to terrain). This is mostly to detect when the range finder is looking at some payload under the drone instead of the terrain.
- Thing to fix later: when using range aid, the range sensor is also used in the terrain estimator because fusing optical flow into the main EKF requires a valid terrain estimate...
> Ekf terrain estimator refactoring

- src/modules/mc_hover_thrust_estimator/MulticopterHoverThrustEstimator.cpp
- src/modules/mc_hover_thrust_estimator/MulticopterHoverThrustEstimator.hpp
- src/modules/mc_hover_thrust_estimator/hover_thrust_estimator_params.c
- src/modules/mc_hover_thrust_estimator/zero_order_hover_thrust_ekf.cpp
- src/modules/mc_hover_thrust_estimator/zero_order_hover_thrust_ekf.hpp
We had issues with VTOLs that have completely different thrust requirements when hovering in high winds. If facing the wind, the thrust usually is very low, as the wings provide most of the lift, but if the vehicle is not facing the wind then the thrust demand increases rapidly. As currently the range for the thrust estimate is [0.1, 0.9], it can lead to dangerous situations where the vehicle is close to the ground as experiences a sudden drop in aerodynamic lift, that the HTE is not fast enough to make up for. 
Instead of constraining the range to [0.1, 0.9], parametrize the range with new param `HTE_THR_RANGE`, that indicates how far the hover thrust estimate is allowed to deviate from `MPC_THR_HOVER`. The …
> HTE: parametrize range of hover thrust estimate

- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectiveness.hpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessControlSurfaces.cpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessControlSurfaces.hpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessCustom.hpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessFixedWing.cpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessFixedWing.hpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessMCTilt.cpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessMCTilt.hpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessMultirotor.cpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessMultirotor.hpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessRotors.cpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessRotors.hpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessRoverAckermann.cpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessRoverAckermann.hpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessRoverDifferential.cpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessRoverDifferential.hpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessStandardVTOL.cpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessStandardVTOL.hpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTailsitterVTOL.cpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTailsitterVTOL.hpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTiltrotorVTOL.cpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTilts.cpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTilts.hpp
- src/modules/control_allocator/ActuatorEffectiveness/CMakeLists.txt
- src/modules/control_allocator/ControlAllocator.cpp
- src/modules/control_allocator/ControlAllocator.hpp
This is mainly a refactoring of how we tell the effectiveness classes to update it's effectiveness matrices. This is required to enable motor failure handling and dynamic on/off switching of actuators in flight inside the control allocation. 
The "force" flag is replaced by an enum that relays the reason for the matrix update to the effectiveness:
```
enum class EffectivenessUpdateReason {
NO_EXTERNAL_UPDATE = 0,
CONFIGURATION_UPDATE = 1,
MOTOR_ACTIVATION_UPDATE = 2 (either motor failure or motor stopped in FW)
};
```
Then the Effectiveness knows when a matrix update is required (`!NO_EXTERNAL_UPDATE`) and if additionally the normalization scale needs an update (`CONFIGURATION_UPDATE`).
Note: the 4th reason for a matrix update, the change of combined tilt for …
> CA: refactor logic for matrix updating

- src/modules/navigator/rtl.cpp
Vehicle would never accept climb for RTL altitude, and just keep loitering for ever, because the _mission_item.loiter_radius field was not set (thus at 0m).
> RTL FW/VTOL doesn't accept climb for RTL altitude

- src/modules/airspeed_selector/airspeed_selector_main.cpp
Current behavior: If airspeed has been valid and gets invalid prior to arming, a warning will be spawned advising the user to RTL. This message is meant to be issued while flying. A quick investigation showed that the condition is broken.
Fix the condition and use an armed boolean instead of the landed flag.
> Airspeed selector: fix condition for messaging

- boards/matek/h743-slim/nuttx-config/include/board.h
Addresses the reliability issues seen on the Matek H743 Slim board when using a Sandisk 4, 16, and 32GB Class-10 U1 A1 SD cards, as described in: https://github.com/PX4/PX4-Autopilot/issues/19155
The main approach here is to drop the max SDIO clock speed from 25MHz to 20MHz, which appears to have generally solved the problem, at least on the Matek H743 Slim (monitored over a few days of heavy SD card testing with sd_stress, sd_bench, and general parameter-based operations).
This may not be strictly necessary on all boards, and may be a function of things like temperature, the onboard oscillator components used on each physical board, or other factors. That said, a similar PR was introduced in Ardupilot which drops the clock speed to an even more conservative speed of 12.5MHz: …
> Changes SDIO clock speed to 20MHz for Matek H743 Slim board

- src/modules/navigator/mission.cpp
- src/modules/navigator/navigator_main.cpp
- src/modules/navigator/rtl.cpp
Replaces https://github.com/PX4/PX4-Autopilot/pull/18605.
- no interface to change speed setpoint in auto flight if not in mission
- ~~flying in high wind with an airspeed setpoint close to stall is dangerous due to increased external disturbances, so the airspeed setpoint should ideally be increased in these situations~~
*Speed setpoint slider:*
(Note: no PR yet for QGC side) Introduce a slider in the flyview of QGC to change the current speed setpoint. For MC this would be groundspeed, for FW/VTOLs in FW mode airspeed. After confirming the set value of the slider, QGC sends the MAVLink command [DO_CHANGE_SPEED](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_CHANGE_SPEED). Navigator stores the received …
> Enable DO_SET_SPEED commands outside of missions in other AUTO modes

- platforms/common/uORB/uORBManager.cpp
- platforms/common/uORB/uORBManager.hpp
- platforms/nuttx/src/px4/common/board_ctrl.c
- platforms/nuttx/src/px4/common/include/px4_platform/board_ctrl.h
- platforms/nuttx/src/px4/common/px4_init.cpp
- platforms/nuttx/src/px4/common/px4_protected_layers.cmake
This adds an ioctl interface for NuttX protected build, allowing
system calls from user space to kernel for uORB, HRT and crypto
> Add an ioctl interface for userspace to kernel calls

- src/modules/gyro_calibration/GyroCalibration.cpp
- this is an edge case that can slip through if sensors are running normally but then stop publishing valid data
> gyro_calibration: add additional validity check before finalizing calibrations

- Tools/sitl_run.sh
Otherwise it can 
The ignition plugins are built for ignition edifice. If a newer version of ignition is installed alongside ignition edifice (e.g. fortress) the sitl run will use the newest version which ends up throwing a protobuf error and fails to run.
Full error [here](https://github.com/Auterion/px4-simulation-ignition/issues/21#issue-1133600298).
This forces ignition to use version 5, which is the version it was built for. This makes sure ignition starts with edifice even if a newer version is installed. 
**Describe possible …
> Force ignition to use version 5 (edifice) in sitl run

- src/modules/gimbal/gimbal.cpp
- src/modules/gimbal/gimbal_params.c
- src/modules/gimbal/gimbal_params.h
- src/modules/gimbal/output.cpp
- src/modules/gimbal/output.h
This adds a simple gimbal pitch constraint when landed for vehicles that might have a physical limitation.
A full solution probably involves factoring in distance to ground (if available) or potentially monitoring takeoff/landing status otherwise, but this is a simple start.
> gimbal: new pitch limits [MNT_LND_P_MIN, MNT_LND_P_MAX] when landed

- src/modules/gimbal/gimbal.cpp
Once we have valid input we should use that and not overwrite our update_result with the result from other inputs, otherwise the automatic selection does not actually work.
This behavior means that only the first update will be used if there are several sources updating in the same cycle.
> gimbal: fix input selection

- src/modules/airspeed_selector/airspeed_selector_main.cpp
#19173  introduced a new warning for a sensor failure while disarmed. However, a mistake in the condition for executing that caused it to never happen but still deploying the wrong message. Here's the fix.
> AirspeedSelector: fix condition for warning if not armed

- .ci/Jenkinsfile-hardware
- msg/CMakeLists.txt
- msg/ekf_gps_drift.msg
- msg/estimator_gps_status.msg
- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/ekf_helper.cpp
- src/modules/ekf2/EKF/estimator_interface.h
- src/modules/ekf2/EKF/gps_checks.cpp
- src/modules/ekf2/EKF2.cpp
- src/modules/ekf2/EKF2.hpp
- src/modules/logger/logged_topics.cpp
This is another new verbose estimator status output message to make our lives slightly easier when casually inspecting a system or reviewing logs. It combines the estimator status gps check fail bits and `ekf_gps_drift` into a new `estimator_gps_status` message that publishes with each new GPS sample.
``` Console
nsh> listener estimator_gps_status
TOPIC: estimator_gps_status 3 instances
Instance 0:
estimator_gps_status
timestamp: 61888757 (0.003161 seconds ago)
timestamp_sample: 61755344 (133413 us before timestamp)
position_drift_rate_horizontal_m_s: 0.1182
position_drift_rate_vertical_m_s: 0.1864
filtered_horizontal_speed_m_s: 0.0098
checks_passed: True
check_fail_gps_fix: False
check_fail_min_sat_count: False
check_fail_max_pdop: False
check_fail_max_horz_err: False …
```
> ekf2: add new estimator_gps_status.msg

- src/modules/control_allocator/ControlAllocator.cpp
- use max(fabsf(val)) instead of max(val)
- use correct actuator count & index
Bug introduced with #19201.
Fixes #19233 (@Jaeyoung-Lim)
> control_allocator: fix weak authority matrix check & update

- src/drivers/magnetometer/rm3100/rm3100.cpp
- src/drivers/magnetometer/rm3100/rm3100.h
We have been experiencing intermittent failures with RM3100 initialization, wherein the BIST sometimes fails due to the STATUS register's DRDY bit not being set after firing off the POLL command. In this event, the current code fails the BIST outright. Beyond that, after reading through the BIST section of the datasheet, there are a few additional checks/actions that need to be taken to ensure that the results of the self-test are valid and that the BIST mode is exited upon completion.
This PR addresses these issues in the following ways:
1. Adding some basic retry logic in the event that the DRDY bit was not upon checking the first time.
2. The results of the test are only valid if STE is set in the results, so …
> RM3100 self-test procedure revision

- ROMFS/px4fmu_common/init.d/rc.sensors
- src/drivers/rpm/pcf8583/PCF8583.cpp
- src/drivers/rpm/pcf8583/PCF8583.hpp
- src/drivers/rpm/pcf8583/parameters.c
- src/drivers/rpm/pcf8583/pcf8583_main.cpp
- src/modules/logger/logged_topics.cpp
- src/modules/mavlink/streams/RAW_RPM.hpp
A common requirement of PX4 users is to be able to connect multiple revolution sensors (counters, eg. PCF8583 used in TFRPM) to one autopilot. This PR tries to solve it. 
This modification extends the existing counter driver to support multiple instances at the same time. And produce multi-instance RPM uORB message. 
PR includes increased robustness to sensor failures and better recognition of the connected sensor.
The sensor driver is started by the parameter.
> Extend the PCF8583 driver to support multiple instances 

- src/modules/navigator/loiter.cpp
- src/modules/navigator/mission_block.cpp
- src/modules/navigator/mission_block.h
- src/modules/navigator/navigator.h
- src/modules/navigator/navigator_main.cpp
This PR re-uses the breaking logic which is used when we switch from mission to Goto/reposition mode but when entering hold/loiter mode.
> Use braking logic from mission to hold mode

- platforms/common/uORB/Subscription.hpp
- platforms/common/uORB/uORBManager.cpp
- platforms/common/uORB/uORBManager.hpp
- platforms/common/uORB/uORBManagerUsr.cpp
Move some logic from Subscriber into uORBManager. This reduces calls from the
modules to the uORB manager, improving performance in protected build.
On flat builds, the performance impact is less significant, but it still saves ~4-5 KB of flash and some 0.5% of CPU on fmu-v5 target.
> uORB performance updates

- src/drivers/dshot/DShot.cpp
- src/modules/control_allocator/ControlAllocator.cpp
- src/modules/control_allocator/ControlAllocator.hpp
- src/systemcmds/actuator_test/actuator_test.cpp
This PR addresses the issues described here:
https://github.com/PX4/PX4-Autopilot/issues/19190#issuecomment-1044276295
In summary, this PR addresses three problems:
1. The `actuator_test` system command does not accept the type and range of values it's usage statement describes
2. The DShot driver does not trigger commands unless the vehicle is armed and ControlAllocator is receiving torque/thrust setpoints. Because of this, the actuator_test commands have no effect.
3. Because `control_allocator` does not publish `actuator_motors` when disarmed, the FunctionMotors subscription never gets a sample containing information like the reversibility mask, which would cause issues in the interpretation of `actuator_test` commands if they did happen …
> Fix Dshot actuator test issues

- platforms/nuttx/src/px4/common/px4_protected_layers.cmake
- platforms/nuttx/src/px4/common/usr_hrt.cpp
- platforms/nuttx/src/px4/nxp/imxrt/hrt/hrt.c
- platforms/nuttx/src/px4/nxp/kinetis/hrt/hrt.c
- platforms/nuttx/src/px4/nxp/s32k1xx/hrt/hrt.c
- platforms/nuttx/src/px4/rpi/rpi_common/hrt/hrt.c
- platforms/nuttx/src/px4/stm/stm32_common/hrt/hrt.c
- platforms/posix/src/px4/common/drv_hrt.cpp
- src/drivers/drv_hrt.h
This adds a nuttx userspace interface for hrt driver, communicating with
the actual px4 hrt driver via BOARDCTL IOCTLs
The purpose of this is to enable the same interfaces for all the user-side modules, which are available on kernel side, to make it possible to freely place modules on either side of the memory barrier. The HRT timer implementetion in PX4 is basically a driver accessing directly STM registers and making callbacks directly from an interrupt, so it is not available in user side in memory protected build.
Specifically this adds the following for protected build user side:
- Basic time calculation functions (abstime to ts etc.)
- Latency counters for user side
- Basic hrt_absolute_time()
- The callbacks (hrt_call_after, hrt_call_every...). Whereas in the kernel side the …
> Add a generic hrt driver userspace interface

- src/modules/navigator/mission_block.cpp
The mission item parameter handling and interpretation is a mess.
One of the nasty extra cases is the `CMD_DO_SET_ROI_LOCATION` which:
- Comes from outside as either [MISSION_ITEM](https://mavlink.io/en/messages/common.html#MISSION_ITEM) or [MISSION_ITEM_INT](https://mavlink.io/en/messages/common.html#MISSION_ITEM_INT) with either double or single precision latitude, longitude (or even a different coordinate frame).
- Is parsed into an internal mission item which only has single precision parameters 5,6. But contains double-precision lat, lon fields.
- Needs to be sent out again to either vmount or and external gimbal/payload manager via vehicle command and possibly the correct MAVLink command.
Improved handling for this case was added by …
> mission_block: handle SET_ROI_LOCATION with absolute altitude correctly

- src/drivers/uavcan/actuators/esc.hpp
- this should run synchronized with the rate controller and can be limited by IMU_GYRO_RATEMAX
> uavcan: increase ESC max rate 200->400 Hz

- src/lib/matrix/matrix/Quaternion.hpp
- src/lib/matrix/test/attitude.cpp
- src/lib/matrix/test/dual.cpp
- src/modules/attitude_estimator_q/attitude_estimator_q_main.cpp
- src/modules/commander/accelerometer_calibration.cpp
- src/modules/uuv_pos_control/uuv_pos_control.cpp
- src/systemcmds/tests/test_mathlib.cpp
The naming of the function to rotate a vector with a unit quaternion is misleading. I found that to be the case myself when I started out and since I realized I'm not the only one I suggest changing it.
Fixes https://github.com/PX4/PX4-Autopilot/issues/19282
The description of the function starts with "Rotates vector" so what better name than `rotateVector()`? I made it camel case since that's the function naming convention we're targeting.
Tests still run through.
> Quaternion: rename function to rotate vectors

- src/lib/matrix/matrix/helper_functions.hpp
- src/lib/matrix/test/CMakeLists.txt
- src/lib/matrix/test/unwrap.cpp
Angles occasionally need to not only be wrapped.. but also unwrapped. But there's no common library method for this yet on PX4. This PR adds one.
The function currently only considers angles.. and specifically in [-pi,pi], could be possible to generalize it for any unwrapping bounds. Open to suggestions.
Another point I briefly discussed with @bresch was that `matrix` lib seems like a strange place to have all these wrapping functions. I added this one here only to keep it grouped with the existing ones. Not sure how tedious it would be to move them to their own library.. or to e.g. `mathlib`.
Unit tests.
Will likely be used in #18026. Very likely that there …
> Angle unwrapping method

- src/modules/ekf2/EKF2.cpp
Based on the context, `_estimator_visual_odometry_aligned_pub` should call `advertise` API here, NOT `advertised`.
https://github.com/PX4/PX4-Autopilot/blob/3e21efb72147b349d5c3a389bbe70b705ccfd20d/src/modules/ekf2/EKF2.cpp#L204-L206
API `advertise` will generate a handle for the instance, thus ensure the consistentency of uORB instance number:
https://github.com/PX4/PX4-Autopilot/blob/5dbbddb13f1730d51c33c5a90d1042ba0a714241/platforms/common/uORB/PublicationMulti.hpp#L72-L80
While `advertised` only check whether the handle is null, without generate the handle:
https://github.com/PX4/PX4-Autopilot/blob/5dbbddb13f1730d51c33c5a90d1042ba0a714241/platforms/common/uORB/Publication.hpp#L73
Replace `advertised` with …
> Typo Fix: pub.advertised() -> pub.advertise()

- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
- src/modules/commander/commander_params.c
Immediate rearming after landing should not bypass all checks in normal operation. For example, the drone should not rearm if the user landed after a yaw emergency reset or a loss of navigation.
The grace period introduced in https://github.com/PX4/PX4-Autopilot/pull/9622/files is intended to allow the user to rearm the drone in air in case of an unintentional disarming using the arm switch.
Use a grace period of 5s after disarm only if the drone is armed through the arm switch.
SITL tested
> commander: allow rearming grace period for arming switch only

- src/modules/vtol_att_control/standard.cpp
- src/modules/vtol_att_control/tiltrotor.cpp
- src/modules/vtol_att_control/vtol_att_control_main.cpp
- src/modules/vtol_att_control/vtol_att_control_main.h
- src/modules/vtol_att_control/vtol_type.cpp
- src/modules/vtol_att_control/vtol_type.h
As air density decreases the transiton time from MC to FW increases. This is an attempt to compensate for this given air density estimate we have. This is less important for vehicles using an airspeed sensor.
Calculate a scale factor based on air density.
Maybe there are more accurate calculations. It would be good to gather some test data from different altitudes to verify and/or correct the compensation model. 
At this point only in SITL, flight tests will follow. …
> Compensate VTOL transition time for air density

- src/drivers/imu/analog_devices/adis16470/ADIS16470.cpp
This slipped through on the CUAV X7 pro because it's only obvious with movement and multi-ekf automatically switches the primary IMU.
> adis16470: fix gyro scaling

- src/modules/mavlink/module.yaml
This PR adds a parameter to force flow control on or off in the mavlink config. I have run into issues with the auto detection failing to turn off flow control. This defaults to auto and will not change the current functionality unless a user changes the param to 0 or 1.
There were some extra spaces on the other lines that VScode automatically wants to remove.
> Add mavlink flow control parameter

- src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
Problem: Weather vane and nuding are both publishing a yawspeed_setpoint. The one from nudging overrides the one from WV.
Proposed fix: Only allow yawing inputs if weather vane is not active or the yaw stick is out of a 10% dead-zone
Disable yaw lock when weather vane is active.
SITL tested.
> FlightTaskAuto: Nudging: only set yawrate_sp if WV is disabled or stick is out of dead zone

- msg/tune_control.msg
Currently, all devices using [TAP_ESC driver](https://github.com/PX4/PX4-Autopilot/tree/master/src/drivers/tap_esc) is too loud (e.g. Mantis drone when it starts up, it's so loud that everyone in the room stops what they are doing :flushed:), with the default volume 40.
**This PR sets the default volume to 20, and this only affects TAP_ESC driver using devices, because on other buzzer drivers, they do not take the volume element in the "tune_control" message into account.** So it only affects the devices with the TAP_ESC, and they are all too loud due to this volume setting.
We could add a 'System wide Volume' parameter, but that would be meaningless because the only use case for …
> Reduce Beeepr Default volume since it's too loud in TAP_ESC devices

- src/modules/navigator/navigator_main.cpp
- src/modules/navigator/rtl.cpp
- src/modules/navigator/rtl.h
RTL in hover mode if mission landing is available would go to the mission landing point but then it would navigate to the mission loiter point and get stuck there.
The reason was that navigator switched into mission mode as soon as the return segment was completed. This should only be done for fixed wing vehicles but not when RTL is triggered during hover.
When RTL is triggered, figure out if mission landing is needed.
SITL
> rtl: don't fly mission landing if we trigger rtl in hover

- src/modules/sensors/vehicle_imu/VehicleIMU.cpp
A caveat in `VehicleIMU.cpp` that allows `IMU_INTEG_RATE > IMU_GYRO_RATEMAX`.
https://github.com/PX4/PX4-Autopilot/blob/58a4c38519498888679e3d81c7e6c85ae860dfa8/src/modules/sensors/vehicle_imu/VehicleIMU.cpp#L148-L150
Even we allow that happen, it's function still inconsistent with the comment if `IMU_GYRO_RATEMAX` is set to 2000 Hz.
(Here is a [ref](https://github.com/PX4/PX4-Autopilot/blob/5ded1aedcb0d429cce55fa9138c6acabcaa37ed7/src/modules/sensors/vehicle_angular_velocity/imu_gyro_parameters.c#L85-L105) for 'IMU_GYRO_RATEMAX')
And the line would become:
```
// constrain IMU integration time 1-20 milliseconds (50-1000 Hz)
int32_t imu_integration_rate_hz = constrain(_param_imu_integ_rate.get(), (int32_t)50, (int32_t) 2000);
```
This PR is …
> Bug Fix: IMU_INTEG_RATE can greater than IMU_GYRO_RATEMAX

- src/lib/sensor_calibration/Accelerometer.cpp
- src/lib/sensor_calibration/Accelerometer.hpp
- src/lib/sensor_calibration/Gyroscope.cpp
- src/lib/sensor_calibration/Gyroscope.hpp
- src/lib/sensor_calibration/Magnetometer.cpp
- src/lib/sensor_calibration/Magnetometer.hpp
- src/lib/sensor_calibration/Utilities.cpp
- src/lib/sensor_calibration/Utilities.hpp
- src/modules/commander/accelerometer_calibration.cpp
- src/modules/commander/gyro_calibration.cpp
- src/modules/commander/mag_calibration.cpp
- src/modules/gyro_calibration/GyroCalibration.cpp
- src/modules/sensors/module.yaml
- src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
- src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.hpp
- this was an experiment to casually monitor sensor offsets relative to temperature, but now that all calibration offsets can be adjusted post-flight the stored temperature can be misleading
- deleting to save a little bit of flash
> sensor calibration delete temperature (CAL_ACCx_TEMP, CAL_GYROx_TEMP, CAL_MAGx_TEMP)

- src/modules/commander/Arming/PreFlightCheck/CMakeLists.txt
- src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp
- src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.hpp
- src/modules/commander/Arming/PreFlightCheck/checks/modeCheck.cpp
It is possible to arm in any mode e.g. by sending an arm command. This happens to not be a big issue in a lot of cases where e.g. the drone just landed and if you arm it again in land mode at the same spot it will auto disarm again. But apart from not making sense for a user experience perspective it can be dangerous to arm in any mode e.g. when arming in Orbit or similar.
This pr is a direct reaction to a case where a VTOL in RTL took off again when arming by command.
I'm adding a check and only explicitly allow arming in modes suitable for takeoff. Please check the list and raise any concerns.
I tested this in simulation with multiple cases where arming should be allowed or denied e.g. …
> PreFlightCheck: only allow modes suitable for takeoff

- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/ekf_helper.cpp
- the estimated mag bias was requiring > 30 seconds of continuous 3d
mag fusion to be reported stable (and saved back to mag cal), this
restores the original intent requiring 30 seconds of accumulated valid
3d mag fusion
> ekf2: return saved mag bias variance when not in 3d magnetometer fusion

- ROMFS/px4fmu_common/mixers/quad_x_vtol.main.mix
- src/lib/systemlib/system_params.c
- src/modules/commander/Arming/PreFlightCheck/CMakeLists.txt
- src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp
- src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.hpp
- src/modules/commander/Arming/PreFlightCheck/checks/distanceSensorChecks.cpp
Adding a preflight check for the distance sensors.to check, if the sensor exists and publishes data. warn the user if the vehicle is armed without proper distance sensor.
Added a new parameter, describing the number of distance sensors which should be present for the vehicle.
Added preflight check:
- Check if a uORB topic exists for all the defined distance sensor instances.
- Check if the timestamp of the last published data is not older than 1s.
- If the check does not pass, a mavlink error is sent, but arming is still allowed.
Tested on the ground with a vehicle with distance sensor. After startup, disconnected the distance sensor and then tried to arm.
> preflight checks: add check for distance sensor (via parameter)

- platforms/common/include/px4_platform_common/px4_work_queue/WorkItem.hpp
- src/drivers/pca9685_pwm_out/main.cpp
- src/lib/mixer_module/mixer_module.cpp
A minor typo fix that change 'WorkItem::ChangeWorkQeue' to 'WorkItem::ChangeWorkQueue'.
Tested@release/1.12 branch with `make px4_sitl none` under `Ubuntu 18.04`, passed.
> Typo Fix: WorkItem::ChangeWorkQeue -> WorkItem::ChangeWorkQueue

- src/modules/micrortps_bridge/CMakeLists.txt
Hi,
I found some compile error when building the px4_fmu-v5x_rtps like #19323.
```
[  1%] Built target parameters_xml
make[3]: *** No rule to make target 'src/modules/micrortps_bridge/topics_microcdr_sources/collision_constraints.cpp', needed by 'events/px4.json'.  Stop.
make[2]: *** [CMakeFiles/Makefile2:17874: src/lib/events/CMakeFiles/events_json.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[  1%] Built target git_nuttx
```
To solve this problem, I fix the cmake file  by adding the add_custom_target  for uorb_sources_microcdr_gen.
Please check the modified cmake file.
Thanks in advance.
> add custom target for uorb_sources_microcdr_gen

- src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp
- src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.hpp
- src/modules/commander/Arming/PreFlightCheck/checks/accelerometerCheck.cpp
- src/modules/commander/Arming/PreFlightCheck/checks/baroCheck.cpp
- src/modules/commander/Arming/PreFlightCheck/checks/distanceSensorChecks.cpp
- src/modules/commander/Arming/PreFlightCheck/checks/gyroCheck.cpp
- src/modules/commander/Arming/PreFlightCheck/checks/magnetometerCheck.cpp
requires https://github.com/PX4/PX4-Autopilot/pull/19313
Until now, only the first sensor instance was considered mandatory. For example, an issue with the external mag (instance 1, the primary one used by EKF2) did not trigger a pre-flight check failure.
With this PR, all the sensors used by all the EKF2 instances are considered mandatory and would prevent arming in case of a pre-flight failure. In addition to this, the first instance is always mandatory.
Additional changes:
- the pre-flight check also fails if the sensor was disconnected after boot by checking the freshness of the measurement (1s data timeout)
- remove `maximum_optional_...` that are all the same and hardcode the number in the loop to reduce the …
> Consider all sensors used by EKF in pre-flight checks

- platforms/posix/src/px4/common/print_load.cpp
On newer macOS (12.2+) the clang version that is shipped with the OS is more strict in detecting unused variables. This triggers 
```
/Users/thomas/auterion/PX4/platforms/posix/src/px4/common/print_load.cpp:119:11: fatal error: variable 'stat_thread' set but not used [-Wunused-but-set-variable]
uint32_t stat_thread = 0;
```
This variable is indeed only set and never read. 
This PR removes that variable.
`top` on POSIX sitl target is not available anyways, is this code even still used?
> print_load: Removed unused variable to fix compilation on macos

- src/modules/navigator/geofence.h
- src/modules/navigator/geofence_params.c
- src/modules/navigator/navigator_main.cpp
PR #16400 added a new prediction algorithm that cannot be disabled.
This PR adds the GF_PREDICT parameter to fall back to the old method of triggering geofence on current location.
GF_PREDICT is enabled by default to keep the current predictive behavior.
This fixes #17605 
Tested geofence using quadcopter in jmavsim with GF_PREDICT enabled and disabled.
> Add geofence predict param

- src/lib/matrix/test/MatrixHelperTest.cpp
A couple tests are failing after #19250. @dagar I'm wondering how this got past CI?
Fixed two float compares -- just had wrong compare value for the wrapping functions, methods were calculating correctly.
TODO:
https://github.com/PX4/PX4-Autopilot/blob/92b93811e3e67abff277491760887e155ff9935e/src/lib/matrix/test/MatrixHelperTest.cpp#L51-L52
```
[ RUN      ] MatrixHelperTest.Helper
../../src/lib/matrix/test/MatrixHelperTest.cpp:52: Failure
Expected equality of these values:
wrap(0. + 1.19209289550781250000000000000000000e-7F, 0., 360.)
Which is: 1.1920929e-07
0.
Which is: 0
../../src/lib/matrix/test/MatrixHelperTest.cpp:55: Failure
Expected equality of these values:
wrap(360. + …
```
> MatrixHelperTest: correct wrap compare values

- posix-configs/SITL/init/test/test_imu_filtering
- src/modules/gyro_fft/CMakeLists.txt
- src/modules/gyro_fft/GyroFFT.cpp
- src/modules/gyro_fft/GyroFFT.hpp
- when estimating the peak frequency the magnitude of side buckets will
be factored in, so it doesn't make sense to potentially treat them as separately detected peaks
> gyro_fft: peak detection exclude side FFT buckets

- posix-configs/SITL/init/test/test_imu_filtering
- src/lib/parameters/param_translation.cpp
- src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
- src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.hpp
- src/modules/sensors/vehicle_angular_velocity/imu_gyro_parameters.c
- new static notch filter configured via IMU_GYRO_NF1_FRQ and IMU_GYRO_NF1_BW
- existing notch parameters IMU_GYRO_NF_FREQ and IMU_GYRO_NF_BW become IMU_GYRO_NF0_FRQ and IMU_GYRO_NF0_BW
> sensors: add 2nd static notch and migrate existing parameters

- src/modules/vtol_att_control/standard.cpp
- src/modules/vtol_att_control/tailsitter.cpp
- src/modules/vtol_att_control/tiltrotor.cpp
For the standard VTOL configuration, put the landing gear down when trying to land, and retract them when flying in mission mode as well as in other manual modes.
The current implementation set the landing gear down, if the VTOL is in hover mode and sets the landing gear up in all other modes. This way, the landing gear is always down when trying to land in hover for all flight modes.
Other alternatives would consists of using the MC logic and adapt it for the fixed wing/VTOL cases as well or to have a landing gear module setting the landing gear down if the vehicle is close to the ground.
This PR was tested using the gazebo_standard_vtol simulation and …
> Set up landing gear logic for standard VTOL

- src/modules/navigator/navigator_main.cpp
- src/modules/navigator/vtol_takeoff.cpp
VTOL takeoff navigation mode was broken. Once the vehicle was loitering and switched to loiter, it would fly back to home and loiter there.
Don't reset cruise speed and throttle after a vtol transition as part of the VTOL takeoff navigation mode.
None
SITL
> Fix VTOL takeoff loitering around home instead of loiter point

- src/lib/matrix/matrix/helper_functions.hpp
- src/lib/matrix/test/MatrixHelperTest.cpp
Fixes #19361 thanks to @tstastny !
- The sign function has no documentation
- There are no unit tests for the sign function
- The sign function has a bug where unexpectedly sign(0) = -1 and sign(FLT_EPSILON) = 0
Add documentation and unit tests.
For the bug, I'm really not sure why the putative deadzone was added here: https://github.com/PX4/PX4-Autopilot/pull/12905/files#diff-b76fc4ece0dac2e83a0e972fbea85372175487ed12f9146ee211252e51da3494R51
It never worked before. It would need to be `(T(FLT_EPSILON) < val) - (val < -T(FLT_EPSILON))`.
We could add another sign function that has a configurable deadzone with a default parameter value if there's the need. Also we should move it …
> Test and fix sign function

- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
- src/modules/land_detector/MulticopterLandDetector.cpp
- src/modules/mavlink/mavlink_receiver.h
The remaining battery time based RTL is triggered also when already landed (in another mode then RTL or Land).
Instead of just checking for being armed I also check if the vehicle is already in any landed stage
`!_vehicle_land_detected.ground_contact // not in any landing stage`
On the way I:
- refactored the naming of the land detection subscription in commander
- updated a comment about land detection triggering time 
- removed an unused publication of landed state in the MAVLink module
I tested this in SITL by making the battery simulator publish a current and configuring a battery capacity.
I think we should enable optional testing of battery current and capacity in SITL in general in …
> No battery time based RTL when already landed

- src/lib/mathlib/math/Functions.hpp
- src/lib/mathlib/math/FunctionsTest.cpp
- src/lib/matrix/matrix/helper_functions.hpp
- src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
- src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.hpp
When flying an orbit with the yaw behavior `ORBIT_YAW_BEHAVIOUR_HOLD_FRONT_TANGENT_TO_CIRCLE` where the vehicle is facing tangential to the circle and hence facing the direction of travel it's unintuitive to change the radius and velocity of the orbit with the usual stick mapping. This is because usually the stick input is mapped in the body yaw frame.
I changed the stick input to also act 90° offset compared to when flying with the vehicle facing the center of the circle. Such that's intuitively in body yaw frame.
Doing that I found the direction of where the vehicle is facing and hence also how the stick input is mapped would change 180° when switching rotation direction. This makes direction switches by stick …
> Remap orbit stick input when vehicle faces tangential

- src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
- src/modules/flight_mode_manager/tasks/ManualAltitude/FlightTaskManualAltitude.cpp
- src/modules/flight_mode_manager/tasks/Utility/Sticks.cpp
- src/modules/flight_mode_manager/tasks/Utility/Sticks.hpp
'Sticks' utility library is used by Flight Tasks. While implementing a Follow-Target feature (#19260) with RC-controllable behavior, I found that **it is unclear as to which 'user input' each input vector corresponds to.**
Added functions each returning user input values in a clear, intuitive naming.
+ Also renamed the 'checkAndSetStickInputs' function name to 'checkAndUpdateStickInputs', since 'set' doesn't imply that the stick values are update, which is the most important aspect of this function, thus avoiding possible confusions ;)
> Sticks : Add utility functions to get pitch, roll, throttle and yaw values more intuitively

- src/lib/l1/ECL_L1_Pos_Controller.cpp
- src/lib/l1/ECL_L1_Pos_Controller.hpp
- src/lib/npfg/npfg.cpp
- src/lib/npfg/npfg.hpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/rover_pos_control/RoverPositionControl.cpp
Previously the L1 guidance for Fixedwing/VTOL vehicles have been using global coordinates.
- None of the other controllers that are used by multicopters work directly on global coordinates.
- When passing position setpoints with offboard, the setpoints were converted into global coordinates just so that it can be used by L1. This results in redundant conversions(local->global->local) internally in the controller
- This prevents from using the L1 controller without the global position being initialized, such as using external vision based position estimation. Such use case is particularly useful for rovers that operate indoors
This PR changes the input of the ECL_L1_PosController and NPFG to use local coordinates …
> Use local coordinates for Fixedwing/Rover L1/NPFG controller

- msg/vehicle_status_flags.msg
- src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp
- src/modules/commander/Arming/PreFlightCheck/checks/preArmCheck.cpp
- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
- src/modules/commander/commander_tests/state_machine_helper_test.cpp
- src/modules/commander/state_machine_helper.cpp
- src/modules/events/set_leds.cpp
- src/modules/gyro_calibration/GyroCalibration.cpp
- src/modules/mag_bias_estimator/MagBiasEstimator.cpp
- src/modules/mavlink/streams/HEARTBEAT.hpp
- src/modules/mavlink/streams/HIGH_LATENCY2.hpp
Issue: `WARN [logger] skip topic vehicle_status_flags, format string is too large: 1650 (max is 1500)`
Why?: because we have a couple of custom status flags in a custom firmware that cause the overflow. Even without the customization the topic is very close to the max size.
Proposed solution: Reduce the `vehicle_status_flags` message by removing the `condition_` prefix where possible. That saves us 15x10 = 150 characters. Plus I noticed that `condition_system_returned_to_home` doesn't seems to be used anywhere, so I removed that completely. 
I think it's also more readable without the condition_ prefix.
>  vehicle_status_flags: remove condition_ prefix

- ROMFS/px4fmu_common/init.d/rc.fw_defaults
- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
- src/modules/commander/commander_params.c
If a multicopter looses GPS position for 10 seconds it needs to have GPS position passing all accuracy checks for over 100 seconds such that the estimate gets accepted as usable again by Commander even though the EKF is already fusing it for a long time. This results in perfectly accurate and used position information with the user not being able to switch to any position controlled mode or position controlled failsafe to be possible.
I'm investigating on this **test branch** what impact it has if we omit this to me confusing and unexpected logic and have a fixed configurable probation period for accepting valid position information.
I discussed with @dagar today that it would be …
> Commander: Remove dynamic position velocity probation period

- ROMFS/px4fmu_common/init.d-posix/rcS
- ROMFS/px4fmu_common/init.d/rcS
- src/drivers/heater/heater.cpp
- src/lib/mixer_module/mixer_module.cpp
- src/modules/airspeed_selector/airspeed_selector_main.cpp
- src/modules/control_allocator/ControlAllocator.cpp
- src/modules/ekf2/CMakeLists.txt
- src/modules/ekf2/EKF2.cpp
- src/modules/ekf2/EKF2.hpp
- src/modules/ekf2/EKF2Selector.cpp
- src/modules/ekf2/EKF2Selector.hpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/logger/logged_topics.cpp
- src/modules/sensors/sensors.cpp
- src/modules/sensors/vehicle_acceleration/VehicleAcceleration.cpp
- src/modules/sensors/vehicle_air_data/VehicleAirData.cpp
- src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
- src/modules/sensors/vehicle_gps_position/VehicleGPSPosition.cpp
- src/modules/sensors/vehicle_imu/VehicleIMU.cpp
- src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
- src/modules/sensors/voted_sensors_update.cpp
- src/modules/sensors/voted_sensors_update.h
- multi-EKF create each instance as soon as IMU & mag are advertised (before device id populated)
- ekf2 main run at slightly higher priority, and minimize sleeping between scanning for new sensors
- rcS move rc.vehicle_setup slightly earlier in init (to start ekf2 sooner)
- ekf2 event_status_flags publish periodically (to ensure it's captured by logging)
> init adjustments to ensure used topics are advertised early (primarily for logging)

- platforms/common/uORB/uORBManager.hpp
Possible doxygen error for orb_advertise_multi
orb_advertise says it returns nullptr and that it calls orb_advertise_multi. orb_advertise_multi says it returns -1, but code looks like it returns nullptr.
> orb_advertise_multi seems to return nullptr

- src/modules/rover_pos_control/RoverPositionControl.cpp
The L1 controller now uses local coordinates after https://github.com/PX4/PX4-Autopilot/pull/19347, but for rovers the projection operator was not initialized for rovers if the rover was not in offboard mode
The mavros mission tests on rover caught the problem: 
This commit initializes the global and local projection for rovers
- This fixes a regression introduced by https://github.com/PX4/PX4-Autopilot/pull/19347
> Initialize global local  projection for rovers

- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
- things like arming requests can be dependent on current nav state
that might requested by a previous command, but the state machine
transition will only happen after command processing
> commander: only process one vehicle_command/action_request per cycle

- src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
- src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.hpp
For certain use cases the limit is just too low and if the limit is exceeded currently there a bug where the radius is just pruned instead of not executing the out of range orbit command.
Note: Not rejecting out of range radiuses is a regression:
https://github.com/PX4/PX4-Autopilot/commit/9bd46be1242535d5ec3da04c11d274aa22a2f805#diff-89127f427c1fc4e2fb02b97822ec75dc1bc7a4690ae4cd3aba8bc4f811250717L61
- > the orbit radius is limited to 100m. If flying in open areas this limit is too strict.
Makes it configurable by parameter. I'm open to suggestions for the default.
- > When commanding a larger radius in AMC, it gets resized to 100m.
Fixes the bug by not acknowledging the command and stopping instead of executing …
> Increase orbit radius limit & reject out of range radius commands

- src/modules/flight_mode_manager/FlightModeManager.cpp
- src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
- src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.hpp
This is a follow-up to https://github.com/PX4/PX4-Autopilot/pull/19362 fixing an already previoulsly existing bug. Thanks to @mrivi for finding it!
When commanding a too large Orbit she got invalid setpoints. I figured out that’s because since the introduction the command handling for flight tasks (which is only used for orbit yet) switches to the most basic position mode flight task upon command parameter rejection.
- Switch to the failsafe flight task when command parameters were not accepted.
- This makes the drone just stop and wait for further actions.
- This solves getting invalid setpoint messages when no RC is connected.
- This also solves ending up in an "aggressive" position mode unexpectedly.
- Report …
> Fix reaction to rejected orbit command

- src/modules/mavlink/streams/BATTERY_STATUS.hpp
This makes more sense as the battery percentage is supposed to go from 0 to 100.
> mavlink: Use round instead of ceil on BATTERY_STATUS percentage

- src/modules/commander/commander_params.c
In the parameter metadata it's not possible to map precision landing to the mode switch. It came up before why it cannot be mapped e.g. for testing purposes and I think it's the case because of how it was originally integrated but it's being revised now in https://github.com/PX4/PX4-Autopilot/pull/18973
Adding the option in the parameter metadata such that when it's generated for QGC the option is available in the drop down menu.
Setting the value manually works so it's just a matter of adding it to the metadata.
> Add precision land option for mode switch

- ROMFS/px4fmu_common/init.d-posix/airframes/1011_iris_irlock
For testing precision landing, we can use the simulated world with an IR beacon
```
make px4_sitl gazebo_iris_irlock
```
Precision landing can either be done by switching into the precland flight mode, or by switching to RTL with the parameter `RTL_PLD_MD` set to either 1 (opportunistic) or 2 (required). For the IRlock simulation it makes sense to have `RTL_PLD_MD` enabled.
@julianoes you suggested elsewhere, that we start the `landing_target_estimator` when `RTL_PLD_MD != 0`. I'm not sure if this is enough, or of precision landing also works with `RTL_PLD_MD=0` when switching to the precision landing flight mode rather than using RTL. I have not yet dug into how the flight mode works, but wanted to drop this message before forgetting about it.
> 1011_iris_irlock: require precland

- cmake/metadata.cmake
@hamishwillee this adds the ethernet params (`MAV_${i}_BROADCAST` etc) to the docs.
At some point we'll need handle this per-board, but this still works for now.
> metadata.cmake: enable ethernet parameters

- src/lib/battery/battery.cpp
- src/lib/battery/battery.h
- src/lib/battery/battery_params_common.c
The filter for average current (which is part of the calculation for remaining flight time and thus RTL triggering logic) was always initialized to 15A, not strongly filtered and also updated if on the ground (if the current draw was higher than 1A), resp. not updated in air if the current drawn was below 1A. 
- introduce BAT_AVRG_CURRENT param that is used for init of average current estimate
- increase filtering of average current estimation
- only update average current filter when armed
- store estimated value in parameter after landing (update BAT_AVRG_CURRENT)
- for VTOL: only update average filter if in FW mode
SITL and partially flight tested. …
> battery: improve flight time remaining improvements

- boards/holybro/kakuteh7/src/hw_config.h
The BL was reporting a flash size of 1703936, whereas it should be 1835008.
> holybro/kakuteh7: fix BOARD_FLASH_SIZE

- msg/CMakeLists.txt
- msg/button_event.msg
- src/drivers/px4io/CMakeLists.txt
- src/drivers/px4io/px4io.cpp
- src/drivers/safety_button/CMakeLists.txt
- src/drivers/safety_button/SafetyButton.cpp
- src/drivers/uavcan/CMakeLists.txt
- src/drivers/uavcan/sensors/safety_button.cpp
- src/drivers/uavcan/sensors/safety_button.hpp
- src/drivers/uavcan/sensors/sensor_bridge.cpp
- src/drivers/uavcan/uavcan_params.c
- src/lib/button/ButtonPublisher.cpp
- src/lib/button/ButtonPublisher.hpp
- src/lib/button/CMakeLists.txt
- src/modules/commander/CMakeLists.txt
- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
- src/modules/commander/Safety.cpp
- src/modules/commander/Safety.hpp
- src/modules/commander/commander_params.c
This is the new architectural approach for **button** usage as a **safety button** and **pairing button**. 
This is a continuation of the work from this  PR: https://github.com/PX4/PX4-Autopilot/pull/19255
**What is new?**
- added new `button_event.msg` with TOPIC: `safety_button`.
- added new library `ButtonPublisher`. The library is used at SafetyButton Driver, PX4IO, and UAVCAN. 
- ButtonPublisher for now has two functionality: 
1) publish the SafetyButton event if the button is pressed for 1 second
2) publish the PairingButton event if the button is pressed 3 times in a row under 2 second period. 
The logic of detecting what event was triggered must be done in the driver part as it currently is for **Gpio SafetyButton** and for **UAVCAN SafetyButton**. 
The library could also be …
> Safety and button usage refactoring

- src/lib/mathlib/CMakeLists.txt
- src/lib/mathlib/math/filter/second_order_reference_model.hpp
- src/lib/mathlib/math/test/second_order_reference_model_test.cpp
Reference models can be used as filters which exhibit a particular, chosen (reference) dynamic behavior. This PR implements a simple second order transfer function which can be used as such a reference model, additionally with rate feedback. The system is parameterized by explicitly set natural frequency and damping ratio. Another nice feature is that the output state and rate are kinematically consistent.
This PR doesn't use this filter in an application just yet.. but there are some future PR's in the pipeline which will benefit from this filter formulation. Example applications: Input filter for attitude / rate commands before reaching the attitude / rate controllers, respectively. Smoothing out airspeed estimates with aid from …
> second order reference model filter with optional rate feedback

- ROMFS/px4fmu_common/init.d/rc.vtol_defaults
- src/modules/commander/commander_helper.cpp
- src/modules/mavlink/mavlink_main.cpp
- src/modules/mavlink/mavlink_params.c
- src/modules/mavlink/mavlink_receiver.cpp
- src/modules/mavlink/streams/HIL_ACTUATOR_CONTROLS.hpp
- src/modules/simulator/simulator_mavlink.cpp
PX4 supports int32 parameter types by interpreting the 32 bits in the float field as an int32 field. To signal this behaviour, it should set the bit which is described as PARAM_ENCODE_BYTEWISE.
PX4 had always handled parameters this way but never actually sent the capability (which back then was called PARAM_UNION), however, it should have. This came up recently in the MAVLink devcall when these flags were discussed. The takeaway was to remove the flags to make it clearer and to make sure the projects (like PX4) send them out correctly.
Also see:
https://github.com/mavlink/mavlink/pull/1814
> mavlink: set correct param capability

- src/modules/rc_update/rc_update.cpp
- src/modules/rc_update/rc_update.h
- any real RC data input will be much faster than 10 Hz, so this is an easy way to minimize bogus decoded data from propagating
> rc_update: further tighten timing requirements for valid data

- src/modules/commander/Arming/PreFlightCheck/checks/modeCheck.cpp
As stated by @julianoes in https://github.com/PX4/PX4-Autopilot/pull/19291#issuecomment-1076694121 the linked pr breaks compatibility to some MAVSDK tests and examples.
To fix that I'm allowing arming in land mode even though it was the purpose of #19291 .
The suggested solution was to automatically change to a suitable mode to take off again after disarming. Until that's hashed out and implemented I suggest this in-between fix to make sure MAVSDK is unblocked.
I did not test this separately, please review.
> Preflight checks: allow arming in land mode for MAVSDK compatibility

- boards/matek/gnss-m9n-f4/init/rc.board_sensors
The icm20602 IMU needs to be rolled 180º and yaw 90º for this board.
> Matek M9N-CAN IMU orientation update

- boards/matek/gnss-m9n-f4/init/rc.board_sensors
The RM3100 needs to be pitched 180º for the correct orientation on this board.
> Matek M9N CAN- RM3100 orientation fix

- src/modules/commander/state_machine_helper.cpp
In this case, no action is configured for datalink lost and an action is configured for RC lost.
In case of no data link and no RC, failsafe is enabled but reporting a "no_datalink" reason. "no_rc_and_no_datalink" seems more explicit.
In my case, the issue was that I wanted to fly without RC and without datalink (controlled by an onboard computer) but when I tried to take off, failsafe is enabled for no datalink reason. As I did not have any datalink lost action configured I had to look into the code to understand that I had to change RC loss exceptions.
Using "no_rc_and_no_datalink" reason is more accurate and can help to understand what to do.
> enable_failsafe reason

- ROMFS/px4fmu_common/init.d-posix/airframes/1040_standard_vtol
- ROMFS/px4fmu_common/init.d-posix/airframes/1041_tailsitter
- ROMFS/px4fmu_common/init.d-posix/airframes/1042_tiltrotor
- ROMFS/px4fmu_common/init.d-posix/airframes/1043_standard_vtol_drop
- ROMFS/px4fmu_common/init.d/airframes/1002_standard_vtol.hil
- src/modules/navigator/navigator_params.c
- src/modules/navigator/rtl_params.c
For many VTOLs/fixed-wing drones a 50m loiter radius is too tight, and
going to 80m is a better and safer default.
> Increase NAV_LOITER_RAD and RTL_LOITER_RAD to 80m each

- Tools/ecl_ekf/drag_fusion_tuning/drag_fusion_symbolic.py
- Tools/ecl_ekf/drag_fusion_tuning/drag_replay.py
- Tools/ecl_ekf/drag_fusion_tuning/readme.md
- Tools/ecl_ekf/drag_fusion_tuning/requirements.txt
This python script can be used on a `.ulg` log file in order to estimate the appropriate coefficients for multicopter wind estimation (through drag fusion).
Port of https://github.com/Auterion/Flight_Control_Prototyping_Scripts/tree/master/drag_fusion_tuning
> Tools: add drag fusion tuning script

- msg/sensor_combined.msg
- src/modules/ekf2/EKF2.cpp
- src/modules/sensors/voted_sensors_update.cpp
- this was working in the multi-EKF case using vehicle_imu, but missing in sensor_combined
> ekf2: properly reset IMU biases on calibration change (non-multi-EKF)

- src/modules/mc_pos_control/MulticopterPositionControl.cpp
- src/modules/mc_pos_control/MulticopterPositionControl.hpp
Just randomly saw this unused return value.
Remove it.
Compiles.
> MulticopterPositionControl: remove unused return value parameters_update()

- msg/templates/uorb/uORBTopics.cpp.em
- msg/templates/uorb/uORBTopics.hpp.em
- msg/templates/uorb_microcdr/dds_topics.h.em
- msg/templates/uorb_microcdr/microRTPS_client.cpp.em
- msg/tools/px_generate_uorb_topic_files.py
Let's say you had an uORB message definition in "pasta_information.msg", and you didn't include the message name (pasta_information) in the multi topics comment section for registering custom topics (pasta_cook, pasta_order)
The message name wouldn't be included in the uorb declaration in the message source file, which is **expected since if you specify a custom topic it means that you want to specify which topics to declare.**
**However, the message name was always added as a default topic name in uORBTopics source file by default**
Which was causing an build error since that uorb topic isn't declared from message source, but is used in the list of uORBTopics.
This PR refactors the handling of the multi topics …
> uORB : Don't add message name as default in topics list if not specified

- Tools/ecl_ekf/analysis/checks.py
- Tools/ecl_ekf/analysis/metrics.py
- Tools/ecl_ekf/batch_process_metadata_ekf.py
- Tools/ecl_ekf/check_level_dict.csv
- Tools/ecl_ekf/check_table.csv
- Tools/ecl_ekf/plotting/pdf_report.py
- msg/vehicle_imu_status.msg
- src/modules/mavlink/streams/VIBRATION.hpp
- src/modules/sensors/vehicle_imu/Integrator.hpp
- src/modules/sensors/vehicle_imu/VehicleIMU.cpp
- src/modules/sensors/vehicle_imu/VehicleIMU.hpp
This broke when vibe metrics were removed from estimator_status. It's now handled per IMU instance in vehicle_imu_status.
> Tools/ecl_ekf: fix vibe_metrics usage (moved to vehicle_imu_status instances)

- src/drivers/uavcan/beep.cpp
- src/drivers/uavcan/beep.hpp
After the last bugfix https://github.com/PX4/PX4-Autopilot/pull/18840 there is now a leftover variable that's not really needed anymore.
`_play_tone` can be removed. It's initialized as False, then set to True once, and then it stays True forever.
A similar fix was done in tap_esc.cpp where the same variable was also removed: https://github.com/PX4/PX4-Autopilot/commit/76920171c771539d5bb6a03593d4cfbcbea342b6
Bench-tested with a UAVCAN GPS module
> dronecan beeper: remove unneded var

- src/modules/commander/Commander.cpp
- src/modules/commander/worker_thread.cpp
- src/modules/commander/worker_thread.hpp
Some external tools require the flight uuid and autopilot uuid combination to be unique. If a vehicle is reset from the GCS with the reset command, the uuid and flight time get reset as well, which causes "duplicate" flights. Also, the total flight time is no longer truthful.
This PR changes the default reset behaviour to exclude these params, while also introducing a way to still reset all by setting the PREFLIGHT_STORAGE message param1 to 4. Idea is that from GCS, user generally only wants to wipe config, but not "lifetime reporting" things, such as the total flight time. 
Tested on Pixhawk 4
I'll also do a PR to mavlink to clarify the param usage + include value 4 …
> Preflight storage: Do not reset flight UUID and total flight time on request from GCS

- src/modules/commander/Safety.cpp
This solves prearm check issue introduced after the safety_button refactoring https://github.com/PX4/PX4-Autopilot/pull/19413
The commander should be first able to know if the safety button exists before it is pressed. 
If a safety button is advertised it means that driver that handles the safety button exists.
> commander/safety: set early safety_button_available

- src/lib/component_information/generate_crc.py
- src/modules/mavlink/mavlink_messages.cpp
- src/modules/mavlink/streams/COMPONENT_METADATA.hpp
And still support the previous message COMPONENT_INFORMATION for now.
From https://github.com/mavlink/mavlink/pull/1823
> mavlink: add COMPONENT_METADATA message

- src/drivers/dshot/DShot.cpp
- src/drivers/linux_pwm_out/linux_pwm_out.cpp
- src/drivers/pca9685_pwm_out/PCA9685.cpp
- src/drivers/pca9685_pwm_out/main.cpp
- src/drivers/pwm_out/PWMOut.cpp
- src/drivers/pwm_out_sim/PWMSim.cpp
- src/drivers/px4io/px4io.cpp
- src/drivers/tap_esc/TAP_ESC.cpp
- src/drivers/uavcan/uavcan_main.cpp
- src/lib/mixer_module/mixer_module.cpp
- src/lib/mixer_module/mixer_module.hpp
- fixes the deadlock in px4io ioctl mixer reset 
- px4io Run() locks (CDev semaphore)
- mixer load goes through px4io ioctl MIXERIOCRESET which calls MixingOutput::resetMixerThreadSafe()
- MixingOutput::resetMixerThreadSafe() stores a Command::Type::resetMixer command in an atomic variable, schedules a work queue cycle, then sleep spins until the command is cleared
- the execution of the cycle eventually calls back into PX4IO::updateOutputs(), which tries to lock (and waits forever)
The fix is to make the output module locking simpler, always locking the full Run() and ioctl() call. This can be removed once the old mixers are purged post v1.13.
> output modules simplify locking for mixer reset and load

- src/modules/navigator/mission_block.cpp
Addresses #18595
Loiter exit for fixed-wing landing was incorrectly calculated on counter clockwise loiters causing the aircraft to fly an offset approach vector.
Loiter radius was signed in mission item, which means we need to take it's absolute value before doing trig operations (as they were currently implemented).
SITL with CCW landing. Aborted and let it go around one more time just for good measure.
And in CW direction just to make sure nothing else changed.
@ryanjAA @thomasteisberg
> mission block: fix incorrectly calculated ccw loiter exit

- src/modules/navigator/mission_block.cpp
The calculation of the boolean **exit_heading_reached** was using the default loiter radius and not the loiter radius of the current waypoint. This resulted in the logic breaking down when the two values where different.
Fixed and simplified the logic. …
> Fix vehicle not exiting loiter

- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
- src/modules/commander/commander_params.c
- src/modules/navigator/geofence.cpp
- src/modules/navigator/geofence.h
- src/modules/navigator/mission.cpp
- src/modules/navigator/mission_feasibility_checker.cpp
- src/modules/navigator/navigator.h
- src/modules/navigator/navigator_main.cpp
- src/modules/navigator/rtl.cpp
- src/modules/navigator/takeoff.cpp
- src/modules/navigator/vtol_takeoff.cpp
- always try to set local or global home position when possible
- set global home with GNSS position if global pos from EKF isn't
available
- reset home when significantly moved from home before takeoff (checking
lpos or gpos or GNSS)
- reset home on takeoff transition
- reset home on mavlink arm command
- remove "home required accuracy" parameters, rely on validity flags
- when allowed, use all possible data to set local and global home position in air (back-computation) 24d9254f11da07c2d8b30440103cc16388c2b2e9
> commander: refactor home position setter

- ROMFS/px4fmu_common/init.d/airframes/13004_quad+_tailsitter
Fixes https://github.com/PX4/PX4-user_guide/issues/1849
Essentially the airframe uses `R: 4+` or `R: 4x` mixers, and the motors are assigned sequentially to the next free bus slots. So it should not be possible for these to be out of order. 
This has been wrong for more than 5 years according to the docs.
Note, I don't have merge rights, so if you approve this, please also merge it.
> 13004_quad+_tailsitter - outputs mixed up

- ROMFS/cannode/init.d/rcS
- ROMFS/px4fmu_common/init.d/rc.sensors
- ROMFS/px4fmu_common/init.d/rcS
- src/drivers/optical_flow/px4flow/px4flow.cpp
On px4_fmu-v5x the peripheral power is cycled at init and things like the px4flow need more time to be available and successfully probe.
This is a bit ugly, but works for now.
> px4flow allow delayed background startup

- src/modules/navigator/mission.cpp
When using MAV_CMD_MISSION_START to start a Mission on the ground, one gets the following sequence (including printfs here for context):
```
INFO  [commander] Armed by mission start	
_navigator->get_mission_result()->valid: 1
index: 0, _current_mission_index: 0, _mission.count: 11
WARN  [navigator] CMD_MISSION_START failed
INFO  [navigator] Takeoff to 20.0 meters above home
```
So it complains about that the mission start failed, but then it takes off still and flies perfectly fine.
Don't do anything in set_current_mission_index() when index=current already, and return true.
SITL - with a groundstation that sends CMD_MISSION_START when starting the Mission while still disarmed.
> Mission: don't do anything in set_current_mission_index() when index=current already

- ROMFS/px4fmu_common/init.d/airframes/13010_claire
- ROMFS/px4fmu_common/init.d/airframes/13012_convergence
Caused the MAV_TYPE to not be set correctly (I noticed though only by chance when doing `dmesg` on a Convergence).
> ROMFS: fix typo in convergence and claire configs

- src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
When weather vane is enabled, we don't want to set any heading setpoint during Land, only yawspeed. Unless land help (nudging) is enabled and the yaw stick deflected, then both the yawspeed and yaw setpoint are set by that.
This functionality was already working correctly and acting on the `_yawspeed_setpoint`, but not yet on the `_yaw_setpoint`, as that one got overwritten by the `_land_heading`, that in turn was set during the init and only overwritten by the nudging (but not WV). 
~Remove `_land_heading` and instead set `_yaw_setpoint` directly.~
EDIT:  Weather vane should only set a yawrate setpoint, but no yaw setpoint. Setting it to NAN when WV is active makes sure that whatever _yaw_setpoint is set …
> FlightTaskAuto: remove _land_heading and instead directly set _yaw_setpoint (fixes weather vane landings)

- src/modules/commander/Commander.cpp
Power Off volume was set to default volume - 20, which is almost inaudible for variable-volume beeper ESCs, like ATL Mantis Edu. So whenever powering down the ATL Mantis Edu, user couldn't know if it was turning off or not!
Restore default volume as the volume commanded
> Set Tune's Volume for Power-Off in Commander to default volume

- src/modules/mavlink/mavlink_main.cpp
- src/modules/mavlink/mavlink_shell.cpp
On some H7 boards (cuav x7pro tested)  there's an occasional hard fault when starting the mavlink shell. It stopped reproducing when I expanded the locking slightly, but I haven't identified the root cause.
> mavlink: shell expand locking

- msg/vehicle_status_flags.msg
- src/modules/commander/Arming/PreFlightCheck/checks/preArmCheck.cpp
- src/modules/commander/Commander.cpp
This adds a pre-arm check that prevents arming after a flight termination. This probably requires some discussion as it is related to the ongoing discussion in #19198.
> commander: Add prearm check for flight termination

- src/modules/mavlink/mavlink_main.cpp
- src/modules/mavlink/mavlink_main.h
Small bug discovered during https://github.com/PX4/PX4-Autopilot/pull/19529. If there's an error in `Mavlink::task_main()` and it exits early the mavlink instance isn't deleted.
The entire mavlink module lifecycle management could use a bit of an overhaul, but this should be an acceptable short term fix for v1.13.
> mavlink: delete Mavlink instance if early startup fails

- src/modules/commander/mag_calibration.cpp
Note this only works if the mag already has a calibration (CAL_MAGx_ID, etc) so that it was able to be disabled (CAL_MAGx_PRIO 0). 
This could ultimately be good in combination with https://github.com/PX4/PX4-Autopilot/pull/18421 where the mag cal slots can be filled initially from the on ground bias estimate. From that point a user can explicitly disable a mag.
> commander: mag calibration tolerate fit failure if sensor disabled

- src/modules/mc_att_control/AttitudeControl/AttitudeControl.hpp
- src/modules/mc_att_control/mc_att_control.hpp
- src/modules/mc_att_control/mc_att_control_main.cpp
I came across a log with a brief spike in the yaw rate setpoint corresponding to a heading reset.
Generally this shouldn't be an issue with the attitude controller running immediately on every vehicle_attitude publication (before the position controller), but in this particular log I don't see how this could be possible unless the position controller ran and published before the attitude controller. This might be possible if the scheduling is disrupted, but I'm still trying to reproduce.
> mc_att_control: only apply quat reset if estimate is newer than setpoint

- src/modules/mc_pos_control/MulticopterPositionControl.cpp
This is a minimal fix to silence the "invalid setpoints" warning that can appear the first time a valid position estimate is published.
> mc_pos_control: silence invalid setpoint warning when disarmed

- src/drivers/rc_input/RCInput.cpp
- src/drivers/rc_input/RCInput.hpp
- src/drivers/rc_input/module.yaml
This is a minimal version of https://github.com/PX4/PX4-Autopilot/pull/19285 that fixes the `drivers/rc_input` problem where CRSF and GHST protocols can be falsely detected due to a nearly identical wire format. Following the next release the common `drivers/rc_input` module will be split into dedicated drivers per protocol.
By default the existing `drivers/rc_input` behavior is maintained, but with a new parameter`RC_INPUT_PROTO` that always manually specifying the protocol. Additionally the parameter is set to the RC protocol on the first successful decode, so future sessions will skip the scanning entirely.
Co-authored-by: chris1seto <chris12892@gmail.com>
> drivers/rc_input: RC_INPUT_PROTO parameter minimal implementation

- src/drivers/dshot/DShot.cpp
Fixes a regression from c1e5e666f083f08ddca218aef86a22338c8020cd, where with static mixers the dshot outputs would go to max instead of 0 in a failsafe case.
> fix dshot: remove setAllFailsafeValues

- src/modules/logger/logger.cpp
- src/modules/logger/watchdog.cpp
- src/modules/logger/watchdog.h
There was a time window where if a task with higher priority than the main
logger thread would busy-loop, it would block both logging threads and the
watchdog would not trigger if the writer was in idle state.
This can happen for fast SD card writes.
> logger watchdog: also check main thread

- src/modules/ekf2/EKF/EKFGSF_yaw.cpp
- src/modules/ekf2/EKF/airspeed_fusion.cpp
- src/modules/ekf2/EKF/covariance.cpp
- src/modules/ekf2/EKF/drag_fusion.cpp
- src/modules/ekf2/EKF/gps_yaw_fusion.cpp
- src/modules/ekf2/EKF/mag_fusion.cpp
- src/modules/ekf2/EKF/sideslip_fusion.cpp
References aren't cheaper than using the float directly.
> ekf2: remove unnecessary const references

- src/drivers/dshot/DShot.cpp
I remembered why I added `setAllFailsafeValues` in the first place - to avoid using pwm params.
Follow-up to https://github.com/PX4/PX4-Autopilot/pull/19553.
> dshot: avoid using pwm failsafe params when dynamic mixing is enabled

- src/lib/l1/ECL_L1_Pos_Controller.cpp
The l1 control library has an approach angle limitation when navigating to a line defined by two points. This can lead to undesired behavior in the case that the vehicle is further away than the l1 distance from the line while being close to the end point. In this case, the vehicle will fly past the endpoint without going close to it.
Removed the 45° approach angle restriction. What was the reason for the limitation in the first place?
Tested with SITL simulation
> l1 control: Removed approach angle limitation

- src/lib/wind_estimator/WindEstimator.cpp
- src/lib/wind_estimator/python/wind_est_derivation.py
I was surprised by the complexity of the process covariance prediction given that the model is composed by 3 interdependent stationary processes driven by uncorrelated noise. 
The covariance prediction should then be trivial: `P[k+1] = P[k] + Qk` where `Qk` is the discrete-time process noise -diagonal- matrix `diag((wind_noise * dt)^2, (wind_noise * dt)^2, (scale_noise * dt)^2)`
SITL tested with and without wind with a wind input scaled down by 0.9.
No wind (`make px4_sitl gazebo_plane`):
Master:
This PR:
Wind (`make px4_sitl gazebo_plane__windy`):
Master:
This PR:
> Wind estimator state covariance prediction fix

- src/modules/ekf2/EKF/common.h
Hello,
EKF/common.h struct variable initialization is somewhat haphazard and nonuniform.  This PR applies C++ style initialization to struct member variables and standardizes formatting within the file for readability as well as better alignment with the Google style guide. This PR introduces no functional changes to the code.
This PR introduces no functional changes, so if the line-by-line thrash is undesirable simply to standardize formatting and add uniform initialization we can simply leave the file remain as-is.
Flight tested: https://review.px4.io/plot_app?log=5d922789-065a-4350-84e0-41ad3f663020
@dagar, feel free to push any enum changes into this PR …
> EKF/common.h C++ style initialization and Google style whitespace cleanup

- ROMFS/px4fmu_common/init.d-posix/airframes/1030_plane
Currently the ailerons are deflected 80% up during landing to simulate extra breaking. This seems to be enough, as with that high setting the roll tracking gets so worse that it effects lateral guidance. 
Came in as part of https://github.com/PX4/PX4-Autopilot/pull/19329. 
I think it is still good to have in the SITL Plane the ailerons deflect a bit during landing, just to have it as an example of what's possible. 
Propose setting them to 40% deflection.
> ROMFS: SITL Plane: reduce FW_SPOILERS_LND to 0.4 to leave ailerons enough control authority

- src/modules/commander/state_machine_helper.cpp
If both local position and altitude were not valid, then both RC loss and
datalink loss would not trigger any failsafe at all, independently from
the configured action.
> commander: fix incorrect return in set_link_loss_nav_state()

- src/modules/commander/Commander.cpp
Upon battery disconnect, the error message is spammed instead of only being sent once like it was intended.
Reported by @dagar over Slack.
FYI @cmic0 
Make sure the corresponding bit for the battery in the bit field `_last_connected_batteries` is updated when the battery gets disconnected and not just when it's connected.
Bug must have been introduced here: https://github.com/PX4/PX4-Autopilot/pull/18919/files#diff-e4b611e75eba3844661619867ee06befbcf230aced354a14f167f7d0ebbca8e0R3783
I could do a bitfield class that does this such that set/reset don't have to be repeated everywhere.
Untested, issue was found in code inspection after the report. Please …
> Commander: ensure diconnected battery is cleared from bit field

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
Takeoff and landing modes were separated from the `control_auto()` umbrella in #19495 in an effort to start untangling the fixed-wing position control module before some more significant refactoring to come. However, some of the internal state resets  and position setpoint handling logic was not exactly translated in a way that reproduced the previous behavior. Sorry - I missed them as well in the PR review.
Example: takeoff mode would be overridden from this logic:
https://github.com/PX4/PX4-Autopilot/blob/14a2fdfe551435638e22864437e75030abbf28eb/src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp#L760-L766
And some TECS states and other attitude integral resets were not initialized in takeoff and landing modes as they were before. …
> fw pos ctrl: fix state switching logic for takeoff and landing

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
Cherry-picking #19589, as it fixes a bug caused very recently by #19495. This cherry pick has only a few extra flap definitions compared to the original commits, because #19329 is not in the release, and had not already added these.
> Fix fw takeoff landing handling

- msg/failure_detector_status.msg
- msg/vehicle_status.msg
- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
- src/modules/commander/commander_params.c
- src/modules/commander/failure_detector/FailureDetector.hpp
- no option atm for flight time restriction (it's a legal requirement in some countries to restrict the flight time of a drone)
- no option to abort the flight if the current wind speeds (estimated on board) are above the vehicle thresholds. 
Add the above two features to Commander. Combine the Wind abort with the wind warning that already existed. 
Further I removed the high_wind state from the failure detector. At some point it was planned to add the high wind abort through it, but as it actually isn't a system failure it should be separated. 
SITL tested.
> Commander: add options for max-wind and max-flight-time RTL

- platforms/nuttx/CMakeLists.txt
This is a mistake I've seen a few times that occurs due to most boards starting life copied from an existing similar board.
> cmake: NuttX check that CONFIG_ARCH_BOARD_CUSTOM_DIR is in PX4_BOARD_DIR

- src/modules/navigator/geofence_params.c
The flight termination action on geofence violation is described as only trigger, when the corresponding circuit breaker is not disabled. However, the description of the circuit breaker states, that the geofence action is not depedning on this circuit breaker. The implementation follows the description of the circuit breaker.
The GF_ACTION description is adapted. From my perspective, it is fine to have the geofence flight termination not dependent on the circuit breaker, as it has to be explicitly selected.
Make geofence flight termination dependent on the circuit breaker, and adapt the description on the circuit breaker.
No code was changes, only …
> Remove contradicting geofence parameter description

- msg/follow_target_status.msg
- src/modules/commander/Commander.cpp
- src/modules/flight_mode_manager/tasks/AutoFollowTarget/FlightTaskAutoFollowTarget.cpp
- src/modules/flight_mode_manager/tasks/AutoFollowTarget/FlightTaskAutoFollowTarget.hpp
- src/modules/flight_mode_manager/tasks/AutoFollowTarget/follow_target_estimator/TargetEstimator.cpp
- src/modules/flight_mode_manager/tasks/AutoFollowTarget/follow_target_estimator/TargetEstimator.hpp
- src/modules/flight_mode_manager/tasks/AutoFollowTarget/follow_target_params.c
- src/modules/flight_mode_manager/tasks/Utility/Sticks.hpp
- src/modules/logger/logged_topics.cpp
Refer to the document : https://docs.google.com/document/d/1E04Rn6sxYNqKve4-KZYdC2-9LExKmHKuYjWZlwf61rA/edit
This change log : https://logs.px4.io/plot_app?log=6561ce69-e2e3-46c3-9e13-e29f2dbc11c7
Alessandro PR log : https://logs.px4.io/plot_app?log=fa76985d-87c6-4c4f-9164-fa2f2c15338b
* This PR is to be merged to a pre-existing PR : #18026 
* Depends on  library added from #19246 and #19249.
* Proposal brainstorming issue : #19251 
* User Doc Update PR : https://github.com/PX4/PX4-user_guide/pull/1810
* Scripts I used for testing the algorithm : …
> Follow Me mode Second order filter & improvements

- ROMFS/px4fmu_common/init.d-posix/airframes/1042_tiltrotor
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessMCTilt.cpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessRotors.cpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessRotors.hpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTailsitterVTOL.cpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTiltrotorVTOL.cpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTiltrotorVTOL.hpp
- src/modules/vtol_att_control/tiltrotor.cpp
1) Input of dependent values into allocation
Currently the tiltrotor allocation receives the "normal" allocation inputs (3D torque and 3D thrust), plus additionally collective thrust (through actuator_controls_1[8]). This can result in infeasible inputs, as collective tilt and possible Fx/Fz ratio is closely linked. 
2) Non-zero yaw effectiveness for tiltrotor VTOLs with tilt as their primary yawing actuation
We currently set the torque coefficient to 0 in case of yaw-by-tilt, but when there is some collective tilt then also the thrust coefficient has an influence on the yaw effectiveness. The current way we handle yaw control on tiltrotors (basically simplifying the yaw effectivness of a tilt to "1" or "-1") though only works when the yaw …
> Control Allocation: Tiltrotor improvements

- src/drivers/rc_input/RCInput.cpp
- src/drivers/rc_input/RCInput.hpp
- this allows jumping straight to a non-SBUS RC protocol
- minimal v1.13 bug fix for non-SBUS RC on a pixracer (https://github.com/PX4/PX4-Autopilot/pull/19564)
- increased the scan time per protocol 300->500 ms, which the newer DSM parser seems to need in some cases.
- only set RC_INPUT_PROTO if we've had a successful RC lock for > 3 seconds
> drivers/rc_input: ensure RC inversion is disabled initially

- src/drivers/uavcan/sensors/battery.cpp
- src/drivers/uavcan/sensors/battery.hpp
This PR fixes a standard dronecan battery without the ardupilot aux message causing an immediate RTL due to time remaining low.
Fixes issue https://github.com/PX4/PX4-Autopilot/issues/19642
This PR
https://review.px4.io/plot_app?log=5b4122a9-8a57-48cc-8d0e-d8cdc8945d30
v1.13.0-beta1
https://review.px4.io/plot_app?log=761b3a20-94ae-43d9-aba3-1205751f58ce
https://review.px4.io/plot_app?log=25386252-9972-4f8f-bac0-716c54559f68
> Fix uavcan battery causing immediate RTL time remaining low

- src/systemcmds/pwm/pwm.cpp
`test` was removed as a command in https://github.com/PX4/PX4-Autopilot/pull/18944 (see https://github.com/PX4/PX4-Autopilot/pull/18944/files#diff-90857310600e7e305702c6b43a375b216ef7ead634a4c0b6f690a8289e6b746cL135) but is still used as a usage example in the docs.
This removes the command.
PLEASE check that the command I have replaced it with `$ pwm arm -c 13 -p 1200` is valid!
> pwm.cpp: remove the test example

- src/drivers/dshot/DShot.cpp
- src/drivers/linux_pwm_out/linux_pwm_out.cpp
- src/drivers/pca9685_pwm_out/main.cpp
- src/drivers/pwm_out/PWMOut.cpp
- src/drivers/pwm_out_sim/PWMSim.cpp
- src/drivers/px4io/px4io.cpp
- src/drivers/tap_esc/TAP_ESC.cpp
This fixes an invalid memory access (regression from https://github.com/PX4/PX4-Autopilot/pull/19490) when exiting the module:
exit_and_cleanup destroys the object, but lock_guard is destructed after and accesses the lock.
> output drivers: init SmartLock after exit_and_cleanup

- src/drivers/dshot/DShot.cpp
- src/drivers/dshot/DShot.h
Also ensures there's no deadband if dead_l == dead_h (the default).
> dshot: handle DSHOT_MIN for reversible outputs

- src/modules/flight_mode_manager/tasks/Utility/Sticks.hpp
Adds a verbose function to return Expo() values of the RC stick commands, to intuitively get Roll, Pitch Yaw and Throttle stick inputs.
Add get*Expo() functions
Discussion happened in the #19260, where I had put arbitrary dead-zone threshold to the User RC adjustment for the Follow Angle, Height and Distance to make sure slight movements on the stick wouldn't affect the follow target behaviors (Since it's easy to move the stick right while moving it up, etc. which would bring undesirable effect of changing two parameters at once, when user only wants to change one) …
> Add get*Expo() functions to the Sticks library

- src/modules/mavlink/mavlink_mission.cpp
We had a one-off mission read error and have no idea why. It would have been helpful to at least know the error from the message but it only said "Mission storage: Unable to read from microSD"
@Igor-Misic suggested adding more instrumentation to see what the error was and I agree. This would be my take on adding this directly to the error message.
Probably a general way of reporting such errors would make sense because otherwise, we might start to add such functionality to every possible read that can fail.
Not tested. What do you think @Igor-Misic ?
> mavlink_mission: more specific read storage error message

- boards/nxp/ucans32k146/src/bringup.c
For CAN1 STB wasn't set hence CAN1 wasn't working
This PR adds GPIO for STB pin
> UCANS32K146 Fix CAN1 STB pin

- ROMFS/px4fmu_common/init.d/airframes/13013_deltaquad
- msg/vehicle_status.msg
- msg/vtol_vehicle_status.msg
- src/lib/parameters/param_translation.cpp
- src/modules/airspeed_selector/airspeed_selector_main.cpp
- src/modules/commander/Commander.cpp
- src/modules/fw_att_control/FixedwingAttitudeControl.cpp
- src/modules/fw_att_control/FixedwingAttitudeControl.hpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
- src/modules/mc_att_control/mc_att_control.hpp
- src/modules/mc_att_control/mc_att_control_main.cpp
- src/modules/vtol_att_control/standard.cpp
- src/modules/vtol_att_control/standard.h
- src/modules/vtol_att_control/tailsitter.cpp
- src/modules/vtol_att_control/tailsitter.h
- src/modules/vtol_att_control/tiltrotor.cpp
- src/modules/vtol_att_control/tiltrotor.h
- src/modules/vtol_att_control/vtol_att_control_main.cpp
- src/modules/vtol_att_control/vtol_att_control_main.h
- src/modules/vtol_att_control/vtol_att_control_params.c
- src/modules/vtol_att_control/vtol_type.cpp
- src/modules/vtol_att_control/vtol_type.h
Commit by commit:
- move VTOL module to px4::params
- set tailsitter flag through vehicle_status.is_tailsitter instead of VT_TYPE param, thus removing the dependency of some modules on vtol_type.h
- Commander/VTOL: move VT_FW_PERM_STAB param to commander and not pass it through as flag (less complexity, plus it actually can just as much be a fixed-wing param, not only VTOL)
- vtol_vehicle_status: replace several status bools by single vehicle_vtol_state --> it anyway can always only be in either MC, trans to FW, FW, trans to MC, so it makes it cleaner
- VTOL: remove some unsued variables (e.g. the mc weights were always set to 1 for the tailsitter, one can just as well remove them)
- Commander: remove permanent stabilization option for fixed-wing flight …
> VTOL: move to cpp params API and some refactor

- msg/sensor_combined.msg
- msg/sensor_gyro.msg
- msg/vehicle_attitude.msg
- msg/vehicle_imu.msg
- msg/vehicle_imu_status.msg
- src/lib/drivers/gyroscope/PX4Gyroscope.cpp
- src/lib/drivers/gyroscope/PX4Gyroscope.hpp
- src/modules/sensors/vehicle_imu/VehicleIMU.cpp
- src/modules/sensors/vehicle_imu/VehicleIMU.hpp
- src/modules/sensors/voted_sensors_update.cpp
Some of the hard mounted IMUs I have flown in the past have demonstrated accel clipping but I only recently became aware of the reason I have never seen any instances of gyro clipping.  This PR adds gyro clipping counters/messages mirroring that of the accelerometer clipping monitors.
The accel clipping framework is now simply duplicated for the gyro instances.
Flight tested on a pixhawk4 mini and generic quad 250 racer, however even with a hardmounted pixhawk4 mini, I have been unable to capture a clipping event in flight to this point.  Here are a series of logs flying this PR code, followed by a log on the bench with an artificially lowered clipping threshold:
Functional code flight …
> Add gyro clipping to mirror accel clipping monitoring instances.

- src/modules/commander/commander_params.c
I got multiple times the feedback now that a consistent delay is helpful and makes sense but the default delay is too long for low battery action where you're trying to come back in time and possibly the emergency reaction kicks in while the critical action is executing which leads to a longer accumulated delay.
5 seconds are enough to understand what's going on and react if necessary. Otherwise this delay can be configured longer for specific use cases.
Original introduction of the feature: https://github.com/PX4/PX4-Autopilot/pull/19033
> commander_params: shorten low battery action delay

- Tools/setup/ubuntu.sh
Fixes gazebo and openjdk versions in installation script for ubuntu 22.04.
On Ubuntu 22.04 the packages `gazebo11` and `libgazebo11-dev` do not exist. The packages `gazebo` and `libgazebo-dev` (without a version number) seem to be at the correct version though:
```
apt show gazebo
Package: gazebo
Version: 11.10.2+dfsg-1
...
```
```
apt show libgazebo-dev
Package: libgazebo-dev
Version: 11.10.2+dfsg-1
```
I verified the installation with 
```
make px4_sitl gaebo
```
It compiles fine and the drone is flying :sweat_smile: 
As for openJDK, Ubuntu 22.04 dropped openjdk13 specifically. Using openjdk17 doesn't work with jMAVSim, so I opted for the older openjdk11 that is still available and also used on 18.04. Alternatively we could download openjdk13 from https://download.java.net/openjdk/, but …
> ubuntu.sh: new gazebo package in 22.04

- msg/vehicle_status.msg
- src/modules/commander/Arming/ArmStateMachine/ArmStateMachine.cpp
- src/modules/commander/Arming/ArmStateMachine/ArmStateMachine.hpp
- src/modules/commander/Arming/ArmStateMachine/ArmStateMachineTest.cpp
- src/modules/commander/Commander.cpp
- src/modules/commander/state_machine_helper.h
The state machine is pretty entangled with distributed states which are hard to understand, enforce scope on and unit test.
This is the second step of pure refactoring with a focus on having one source of truth for the current arm state within commander. This is just the second step to make it easy to review and avoid conflicts on the way.
- Behavioral change: Messages are not ALL_CAPITAL anymore. e.g. `Transition denied: Shutdown to Standby` instead of `Transition denied: SHUTDOWN to STANDBY`
The unit tests still pass and the only thing that changes in commander is that until `vehicle_status.arming_state` and `actuator_armed.armed` get published they are not updated but the internal …
> Commander Arming State Machine Refactor Part 2

- src/modules/commander/Commander.cpp
When starting vmount with MAVLink gimbal v2 as the output, the blue LED on the FMU blinks irregularly, because vmount publishes a MAV_CMD_DO_REQUEST_MESSAGE, which isn't known to commander.
This commit adds the MAV_CMD_REQUEST_MESSAGE to the list of vehicle
commands which are ignored without generating a warning sound.
I'm open to inputs, but I think this is how it's done
On my bench, it no longer triggers the "Command unsupported" beep & blink when starting vmount.
> Commander: ignore MAV_CMD_REQUEST_MSG

- src/modules/commander/Commander.cpp
We use lockdown to prevent outputs like motors and servos from being active in HITL simulation. This means that we can't treat the lockdown flag as a flight_terminated, otherwise we can't arm in HITL at all.
I suggest to merge this for now and then revisit the termination and lockdown topic another time.
Related to: https://github.com/PX4/PX4-Autopilot/pull/19419.
> commander: lockdown is not termination

- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
- src/modules/manual_control/ManualControlSelector.cpp
If the `manual_control` module stops publishing for whatever reason we still need to catch the timeout in commander to handle the loss of manual control.
> commander: handle RC loss timeout if manual_control_setpoint stops publishing

- .github/ISSUE_TEMPLATE/1_Bug_report.md
- .github/ISSUE_TEMPLATE/2_Feature_request.md
- .github/ISSUE_TEMPLATE/3_Support_question.md
- .github/ISSUE_TEMPLATE/4_Documentation_issue.md
- .github/PULL_REQUEST_TEMPLATE.md
Current Templates for Issue and PRs can be improved!
1. Change the paragraph headings to proper Markdown headings (easier to link / structure the Markdown)
2. Move PULL_REQUEST_TEMPLATE into .github folder
3. Change description in Issue template and remove outdated DevGuide Repository information
4. Add a bug emoji to bug report isue template
6. Support automatically adding labels 'bug-report' and 'feature-request' to easily sort / filter appropriate issues in Github
> Update Issue and Pull Request Templates

- src/modules/airship_att_control/airship_att_control.hpp
- src/modules/airship_att_control/airship_att_control_main.cpp
- src/modules/fw_att_control/FixedwingAttitudeControl.cpp
- src/modules/fw_att_control/FixedwingAttitudeControl.hpp
- src/modules/mc_att_control/mc_att_control.hpp
- src/modules/mc_att_control/mc_att_control_main.cpp
- src/modules/mc_rate_control/MulticopterRateControl.cpp
- src/modules/mc_rate_control/MulticopterRateControl.hpp
- src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
- src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.hpp
- src/modules/vtol_att_control/vtol_att_control_main.cpp
- src/modules/vtol_att_control/vtol_att_control_main.h
This PR standardizes variable names and formats whitespace across the various vehicle attitude controller files.  This PR facilitates what will become a subsequent PR to limit rate controller commands to within the IMU gyro dynamic ranges. This PR is submitted to allow an easier diff for the follow-on work, but while working in the files it seemed appropriate to clean things up for readability.
Variable names follow a standard convention and whitespace formatting allows for easier reading.
Flight tested on a generic 250 quad: https://review.px4.io/plot_app?log=38dd7cb8-d252-4856-921e-5fa5997f8477
This PR contains no functional logic changes, just simplifies reading …
> Standardize variable naming and formatting across vehicle attitude controller files.

- ROMFS/px4fmu_common/init.d/airframes/1000_rc_fw_easystar.hil
- ROMFS/px4fmu_common/init.d/airframes/1001_rc_quad_x.hil
- ROMFS/px4fmu_common/init.d/airframes/1002_standard_vtol.hil
Without this, uavcan creates MixingOutput classes which then create empty actuator_outputs publications. This then prevents the motor output in HITL to be forwarded to the simulator via mavlink.
As suggested by @NicolasM0 in https://github.com/PX4/PX4-Autopilot/issues/18668
Closes https://github.com/PX4/PX4-Autopilot/issues/19667.
> ROMFS: disable UAVCAN in HITL

- src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
Signed-off-by: Serhat Aksun <serhat.aksun@maxwell-innovations.com>
In VehicleMagnetometer, multi mode for magnetometers are enabled when sens_mag_mode parameter is set to 1 which is not correct.
multi mode for magnetometers are enabled when sens_mag_mode parameter is set to 0. This pr fixes the multi_mode check in VehicleMagnetometer
> sensors/vehicle_magnetometer: fix multi_mode check

- src/modules/ekf2/EKF/mag_fusion.cpp
- src/modules/ekf2/EKF/optflow_fusion.cpp
This prevents bitmask mismatch when a new flag is inserted
Offsets of 3 for mag and 10 for flow was in the "old" bitmask; now it's 4 and 11 but it's even better to use the name directly.
> ekf2: use explicit flags instead of bitmask position

- src/drivers/imu/invensense/icm42688p/ICM42688P.cpp
The drivers periodically verify that they're configured as intended by walking through all configured registers periodically or on any failure. The icm42688p was incorrectly doing this every iteration.
On a px4_fmu-v5x it saves about 1.2% cpu at default IMU_GYRO_RATEMAX 800 Hz.
> icm42688p: only check configured registers periodically (as intended)

- ROMFS/px4fmu_common/init.d-posix/rcS
- ROMFS/px4fmu_common/init.d/rcS
**UPDATED** In the current master branch, setting the param SYS_AUTOCONFIG to 1 resets the mag calibration.  This PR excludes the mag calibration from being reset along with the other IMU sensor calibrations.
Bench tested on a pixhawk 4 mini.  Behavior is as the comment indicates is intended.
Please let me know if there is interest in continuing to reset mag calibrations or if you have any questions on this PR.  Thanks!
> Keep Mag Cal with AUTOCONFIG param reset in rcS, deprecate rcS AUTOCNF param

- src/lib/battery/battery_params_deprecated.c
- src/lib/battery/module.yaml
Based on multiple reports the battery is used down too low with the default parameters. I analyzed logs and observed this happens consistently when the cell voltage is properly load compensated using the current measurement. The default load compensation before #19429 was very inaccurate and resulted in an unpredictable estimate. After that pr enabling current based load compensation by default if there is a usable current measurement and the battery is within expected tolerances of the default internal resistance the compensation is pretty good and 3.5V is clearly too low for an empty compensated cell voltage (the value is good for an uncompensated empty voltage under load). That was seen in various logs where the compensated cell voltage was already dropping fast after 3.6V.
Example: …
> battery_params: increase default empty cellvoltage to 3.6v

- src/modules/commander/Commander.cpp
- src/modules/navigator/mission_block.cpp
Goal: As part of one mission without user intervention land at a waypoint, wait a specified time without disarming and then takeoff again and continue with other mission items.
I had these problems on the radar:
1. No easy way to plan such a mission.
No blocking issue. In QGC I can plan a land waypoint (to zero meters above ground whatever effect that has, violates terrain collision) a "Delay until" waypoint with a specified delay time and then further waypoints.
1. Landing would not get accepted and it would not continue to the next item.
No issue, worked out of the box. Land item is accepted upon land detection:
https://github.com/PX4/PX4-Autopilot/blob/3fe4c6e3f56d68417918454188a3f968c1e5ccd6/src/modules/navigat …
> Land amid mission

- src/modules/mc_rate_control/MulticopterRateControl.cpp
Regression from fbc109436f00a815eb6130c6d177086e6b1ae80a
> MulticopterRateControl: fix thrust sign for acro

- src/modules/simulator/simulator_mavlink.cpp
This type (23) doesn't specify a motor number, so it can't be properly handled. For sure not with 3 motors. This came in when we renamed some VTOL_RESERVED types in https://github.com/mavlink/mavlink/pull/1818.
There are duo (19) and quad (20) tailsitter types that still work in simulation.
Note: as soon as we switch to the new allocation architecture we don't need MAV_TYPE for the motor simulation anymore.
> simulator_mavlink: remove MAV_TYPE_VTOL_TAILSITTER case

- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
I renamed the uORB related variable names in Commander to match the respective uORB message name. There is no reason for things like referring to "commander_state" as "internal_state", except to confuse new developers. Another example is that there are 634 hits for the term "search" in Commander.cpp. I'd like to provide the 1:1 uORB message names to the variable names like we do in most other modules as well.
> Match uORB var names to message names

- src/modules/commander/Commander.cpp
After https://github.com/PX4/PX4-Autopilot/pull/19707 was merged CI failed on master because of some rebase naming issue.
Fix the build.
Normal simulation build works again, let's check CI.
> Commander: fix overlooked rebase naming error

- boards/cuav/nora/nuttx-config/scripts/script.ld
- boards/cuav/x7pro/nuttx-config/scripts/script.ld
- boards/cubepilot/cubeorange/nuttx-config/scripts/script.ld
- boards/holybro/durandal-v1/nuttx-config/scripts/script.ld
- boards/holybro/kakuteh7/nuttx-config/scripts/script.ld
- boards/matek/h743-mini/nuttx-config/scripts/script.ld
- boards/matek/h743-slim/nuttx-config/scripts/script.ld
- boards/matek/h743/nuttx-config/scripts/script.ld
- boards/modalai/fc-v2/nuttx-config/scripts/script.ld
- boards/mro/ctrl-zero-classic/nuttx-config/scripts/script.ld
- boards/mro/ctrl-zero-h7-oem/nuttx-config/scripts/script.ld
- boards/mro/ctrl-zero-h7/nuttx-config/scripts/script.ld
- boards/mro/pixracerpro/nuttx-config/scripts/script.ld
- boards/px4/fmu-v6c/nuttx-config/scripts/script.ld
- boards/px4/fmu-v6u/nuttx-config/scripts/script.ld
- boards/px4/fmu-v6x/nuttx-config/scripts/script.ld
- boards/spracing/h7extreme/nuttx-config/scripts/script.ld
To address issue noted in https://github.com/PX4/PX4-Autopilot/pull/19690 at the bin file level to remove tools dependency. I.E. https://github.com/PX4/PX4-Autopilot/pull/19690 does not solve the problem for QGC etc.
> boards:STM32H7 pad to 256 bit - 32 bytes

- .vscode/settings.json
These terminal settings are a matter of personal preference and should not be part of the project configuration.
> vscode: remove terminal settings

- src/modules/control_allocator/ControlAllocator.cpp
The backup schedule triggers updates too early and leads to simulator errors:
```
ERROR [simulator] poll timeout 0, 22
```
Fixes https://github.com/PX4/PX4-Autopilot/issues/19668
@hamishwillee @Jaeyoung-Lim fyi
> control_allocator: disable backup schedule with lockstep

- src/modules/commander/Arming/PreFlightCheck/checks/modeCheck.cpp
- src/modules/commander/Commander.cpp
1. There can be seemingly random switches to Hold mode when the vehicle has an RC loss while sitting on the ground, disarmed, in Manual mode.
2. After an RTL the vehicle stays in Return mode even though it's already done and it's not possible to take off again in that mode. Users get annoyed by this and there are corner cases with using the takeoff button in the ground station.
3. There are still MAVSDK use cases which will fail arming even after arming in Land mode was temporarily allowed again in https://github.com/PX4/PX4-Autopilot/pull/19449
1. Only automatic switch to Hold mode for a connected tablet and no stick input on initialization and not later on when having RC loss.
2. After landing in an autonomous mode (most of the time RTL, Land, Mission) switch back to Hold mode upon …
> Switch mode after autonomous disarm

- src/modules/flight_mode_manager/FlightModeManager.cpp
When flying a VTOL in fixed-wing operation and sending an Orbit command with a large radius the user gets an error that the limit is exceeded even though for fixed-wing there is apparently no limit.
The issue is that for VTOLs in fixed-wing all flight tasks are stopped as part of the loop but an incoming command can still get processed and start a task that checks the parameters just to get stopped again. I'm only allowing task switching commands while the vehicle is a multicopter.
Later on we need to dispatch the different modes depending on vehicle type. That's also why I just solved it this way and didn't just prohibit running any flight mode manager activity when the vehicle type is different from a multicopter.
I verified in simulation that the problem is solved.
> FlightModeManager: only execute flight task commands when multicopter

- boards/mro/pixracerpro/src/board_config.h
The board definition for the Pixracer Pro's brick power valid signal has the wrong polarity.
This PR corrects the polarity for the signal allowing the battery to be used.
Tested using the analog power input socket on a Pixracer Pro and an Mro ACSP4 power module. Verified that the battery is now properly detected, and that the voltage and current readouts can now be correctly calibrated and displayed.
Essentially the same fix as https://github.com/PX4/PX4-Autopilot/pull/16590
> boards/mro/pixracerpro: fix voltage/current monitoring

- src/drivers/dshot/DShot.cpp
Fixes #19756 - where motor direction command is incorrect (temporary direction change instead of saveable direction change)
Replaced temporary direction change DShot commands with saveable DShot commands
N/A
Tested on custom flight controller board connected to AM32 ESC
See original issue
> Corrected DShot motor spin direction command - fixes #19756

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/navigator/mission_block.cpp
We have a function doing what is used in a lot of places even though it's not complicated.
Use the existing unit tested function. I know that 0 is now considered positive while before it was negative but a zero loiter radius does not produce any movement and is in my eyes not supported. And even if it was a positive turn direction would not make any difference.
I did not test this other than comparing the function interface to what the code did before.
> Use signNoZero() where possible

- src/modules/ekf2/EKF/terrain_estimator.cpp
Clear the hagl fusion-related fields when aiding stops
> terrain est: clear innovation/var/test ration when aiding stops

- ROMFS/px4fmu_common/init.d-posix/airframes/10019_omnicopter
- ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt
- ROMFS/px4fmu_common/init.d-posix/rcS
- platforms/posix/cmake/sitl_target.cmake
- src/modules/commander/failure_detector/FailureDetector.cpp
- src/modules/commander/failure_detector/FailureDetector.hpp
- src/modules/commander/failure_detector/failure_detector_params.c
- src/modules/control_allocator/module.yaml
- src/modules/mc_rate_control/MulticopterRateControl.cpp
- src/modules/mc_rate_control/MulticopterRateControl.hpp
- src/systemcmds/failure/failure.cpp
- test/mavsdk_tests/autopilot_tester.h
- test/mavsdk_tests/test_multicopter_failure_injection.cpp
This PR adds a 6dof omnicopter model for SITL Gazebo simulations using the control allocation
This is a demonstration of how control allocation can be used for multicopters with arbitrary geometries
The model geometry is based on the Omnicopter presented in the following paper:
***Brescianini, Dario, and Raffaello D'Andrea. "Design, modeling and control of an omni-directional aerial vehicle." 2016 IEEE international conference on robotics and automation (ICRA). IEEE, 2016.*** (Video: https://youtu.be/sIi80LMLJSY)
The model can be tested using the following sitl target
```
make px4_sitl gazebo_omnicopter
```
Flight log: https://review.px4.io/plot_app?log=954dda59-c163-4a34-98d0-f97d8f7fbcc6
Video:
[![IMAGE ALT TEXT …
> Add 6Dof Omnicopter model for sitl_gazebo

- src/modules/mc_rate_control/MulticopterRateControl.cpp
Just a tiny suggestion on top of https://github.com/PX4/PX4-Autopilot/pull/19557
Using the Vecto3f constructor that takes a float[3] array instead of assigning each element.
Not specifically tested.
> MulticopterRateControl: use constructor to copy thrust setpoint array

- msg/vehicle_status.msg
- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
- src/modules/commander/Safety.cpp
- src/modules/commander/Safety.hpp
- src/modules/manual_control/manual_control_params.c
It was reported that the startup tune doesn't play fully anymore on master. It was reproducible all the time on my setup. I found the breaking commit to be https://github.com/PX4/PX4-Autopilot/commit/08dcc72e1fea75d2609234cecd7588ecb37492d1. Looking into more detail the safety handling can be and is by default disabled by circuit breaker parameter `CBRK_IO_SAFETY`. In that case the safety status changes once at boot and for that change with mentioned commit there is a tune output for the user that interrupts the startup tune.  
I don't output any tunes for safety if it's disabled (3rd commit [1310dde](https://github.com/PX4/PX4-Autopilot/pull/19777/commits/1310dde035d4196ec5844992ede6b1260f5231fe)) the rest is just refactoring.
I tested that the startup tune is not interrupted anymore and …
> Safety disabled startup tune

- src/modules/navigator/navigator_main.cpp
A reposition setpoint is currently only handled when armed (https://github.com/PX4/PX4-Autopilot/blob/5df266cedcefea01404c6c31354c73104b3ca311/src/modules/navigator/loiter.cpp#L84). When disarmed the reposition_tripplet is though still updated, and then executed when next time switched to LOITER. So e.g. if one sends a DO_REPOSITION when disarmed and then takes off, the vehicle will go to the reposition setpoint once the takeoff is finished. I don't think this is desired. 
I propose to still let it switch to MAIN_STATE_AUTO_LOITER when the DO_REPOSITION is received when not armed, but not to update the reposition_triplet. The alternative (see below) would maybe even be cleaner, though may also have consequences I don't yet foresee. 
Reject the DO_REPOSITION command when not armed. 
SITL …
> navigator_main: DO_REPOSITION: only trigger reposition setpoint update if vehicle is armed

- src/modules/airspeed_selector/airspeed_selector_params.c
The airspeed scale estimator is a nice tool and has proven reliability in many cases already. We should have it apply the estimated scale in air by default.  
Tested on many different VTOL platforms.
> Airspeed params: change default for ASPD_SCALE_APPLY to 2

- src/drivers/uavcan/uavcan_main.cpp
Users who have a `UAVCAN_ENABLE` parameter set different than Disabled and don't have any UAVCAN device connected, will get the following error:
`[uavcan] couldn't start parameter count`
To reproduce start QGC and check the parameters. 
Function `param_count` is getting ErrInvalidParam from call `_param_getset_client.call(node_id, req);  ` when there is no UAVCAN device connected on the CAN bus. 
My suggestion is to inform the user that there is no UAVCAN device connected instead of giving back the error.
If anyone has a better idea of how to solve it, please use this just as a pointer to the error and how to reproduce it.
> uavcan: print info instead of error when no UAVCAN device  is detected

- msg/vehicle_status_flags.msg
- src/modules/commander/Arming/ArmStateMachine/ArmStateMachine.cpp
- src/modules/commander/Arming/ArmStateMachine/ArmStateMachine.hpp
- src/modules/commander/Arming/ArmStateMachine/ArmStateMachineTest.cpp
- src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp
- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
Next part after https://github.com/PX4/PX4-Autopilot/pull/19664
Trying to simplify I found that `system_sensors_initialized` and `system_hotplug_timeout` were out of use for over 2 years.
I simplified and the logic by removing them and control the LED with preflight check results instead.
I'm working on more follow-ups.
I tested the LED blinks when preflight checks are failing and am pretty sure no functionality is lost. Please review.
> Commander Arming State Machine Refactor Part 3

- src/modules/commander/Arming/ArmStateMachine/ArmStateMachine.cpp
- src/modules/commander/Arming/ArmStateMachine/ArmStateMachine.hpp
- src/modules/commander/Arming/ArmStateMachine/ArmStateMachineTest.cpp
- src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp
- src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.hpp
- src/modules/commander/Arming/PreFlightCheck/checks/airspeedCheck.cpp
- src/modules/commander/Arming/PreFlightCheck/checks/failureDetectorCheck.cpp
- src/modules/commander/Arming/PreFlightCheck/checks/powerCheck.cpp
- src/modules/commander/Arming/PreFlightCheck/checks/preArmCheck.cpp
- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
It's super confusing under what conditions what preflight/arm checks are actually called in the arm state machine.
I simplified the conditions to cover mostly how it was. It's not an exact refactor but I'm pretty sure it covers all the conditions we care about. The rest was in my eyes just complexity built from historic patches.
I quickly tested that generally preflight checks still work as expected in simulation.
Builds on #19764, please review that one first.
> Preflight check call simplifications

- src/modules/fw_att_control/fw_att_control_params.c
The current fixed wing tuning guide recommends zeroing P/I scalers during tuning. Previously, the limits for these params were set to a larger than zero lower bound. This PR re-aligns the limits to the documentation. This is arithmetically, not an issue.
> Re-set param limits for fw tuning values to align with fw tuning guide

- src/modules/mavlink/mavlink_main.cpp
- src/modules/mavlink/mavlink_receiver.cpp
- src/modules/mavlink/mavlink_shell.h
These got added in https://github.com/mavlink/mavlink/pull/1725 and need to be set for correct routing.
> mavlink_shell: set target system and component id

- src/modules/esc_battery/EscBattery.cpp
Previously we were only estimating voltage if all the Escs were connected. this caused me some issues during development as i only had 1 Motor connected but still wanted to see the voltage estimation working.
This fix makes the Estimation account for the online Esc.
> EscBattery: account for online ESCs when averaging voltage

- src/lib/weather_vane/WeatherVane.cpp
- src/lib/weather_vane/WeatherVane.hpp
- src/modules/flight_mode_manager/FlightModeManager.cpp
- src/modules/flight_mode_manager/FlightModeManager.hpp
- src/modules/flight_mode_manager/tasks/Auto/CMakeLists.txt
- src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
- src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.hpp
- src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.hpp
- src/modules/flight_mode_manager/tasks/ManualAcceleration/CMakeLists.txt
- src/modules/flight_mode_manager/tasks/ManualAcceleration/FlightTaskManualAcceleration.cpp
- src/modules/flight_mode_manager/tasks/ManualAcceleration/FlightTaskManualAcceleration.hpp
- src/modules/flight_mode_manager/tasks/ManualPosition/CMakeLists.txt
- src/modules/flight_mode_manager/tasks/ManualPosition/FlightTaskManualPosition.cpp
- src/modules/flight_mode_manager/tasks/ManualPosition/FlightTaskManualPosition.hpp
- src/modules/flight_mode_manager/tasks/ManualPositionSmoothVel/FlightTaskManualPositionSmoothVel.hpp
There is a construct for external yaw handlers in flight tasks that was solely added and used for the weather vane library. The problem with it is unnecessary complexity from dynamic memory allocation over pointer passing to external logic passing in data from different locations. I do not see any advantage in maintaining this complexity so I suggest removing it.
- Remove the entire external yaw handler, dynamic memory allocation, pointer passing logic.
- Directly instanciate the weather vane instance in the flight tasks that support it.
- Get uORB and parameter data in weather vane class directly instead of subscribing outside and passing it in.
- Use header initializer to pass the "this"-pointer as parent to ModuleParams children.
- Make `WeatherVane` method names camel case.
This is …
> FlightTask: Weather vane cleanup

- boards/cuav/nora/src/board_config.h
CUAVnora: changed brick to compatible with cuav noraplus. So we can see voltage report with HVPM in QGC.
> cuav-nora: changed brick to compatible with cuav noraplus

- src/examples/fake_gyro/Kconfig
- src/examples/fixedwing_control/main.cpp
- src/modules/fw_att_control/FixedwingAttitudeControl.hpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
- src/modules/uuv_att_control/uuv_att_control.hpp
- src/modules/uuv_pos_control/uuv_pos_control.cpp
- src/modules/uuv_pos_control/uuv_pos_control.hpp
I found these while rebasing #15949 and wanted to make a separate pr.
Commit messages describe the cleanup steps.
No tests. It's pure refactoring. The fake gyro example is empty and the manual control subscription in the UUV position controller is a stub and unused.
> Clean up uORB subscription declarations

- ROMFS/px4fmu_common/init.d/airframes/13014_vtol_babyshark
- src/lib/parameters/param_translation.cpp
- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
- src/modules/commander/commander_params.c
- src/modules/commander/failure_detector/FailureDetector.cpp
- src/modules/mc_pos_control/MulticopterPositionControl.cpp
- src/modules/mc_pos_control/MulticopterPositionControl.hpp
- src/modules/mc_pos_control/Takeoff/Takeoff.hpp
- src/modules/mc_pos_control/mc_pos_control_params.c
It's about the case where the ESC reports an error for not being able to spool up the motor because it's not connected, faulty, stuck or detects that there is no propeller attached. In that case, there's currently the same handling as in the air.
This pr makes sure that if the ESC reports an error during the spool-up time so before taking off then it disarms again to prevent the takeoff. The spool-up time has to be available in commander for this to be possible.
As discussed before we should extend the arming state machine to take care of the spool-up state and have other parts of the system like the takeoff tie into that arming state such that there's only one single point of …
> Make spoolup time a gloabal delay/timeout for checks after arming before navigation

- src/drivers/uavcannode/UavcanNode.cpp
- src/drivers/uavcannode/UavcanNode.hpp
- this is a precaution to minimize log message latency and potential lost messages
> uavcannode: schedule to run on log_message publications

- src/modules/angular_velocity_controller/AngularVelocityControl/AngularVelocityControl.hpp
- src/modules/mc_rate_control/RateControl/RateControl.hpp
I noticed that the MultirotorMixer is included from the ratecontrol library, but is actually not being used
Remove the library and use the mathlib instead!
Tested in SITL
```
make px4_sitl gazebo
```
builds correctly :smile:
> Remove MultirotorMixer from MC Ratecontrol

- src/drivers/drv_pwm_output.h
- src/drivers/linux_pwm_out/linux_pwm_out.cpp
- src/drivers/pwm_out/PWMOut.cpp
- src/drivers/px4io/px4io.cpp
Before https://github.com/PX4/PX4-Autopilot/pull/19805 failsafe values stayed 0 which resulted in PWM signal being lost completely upon vehicle termination if not configured explicitly different per channel. The pr introduced default failsafe values of 900 for channels configured as ESCs and 1500 for servos. While this solved most cases there remain some unsafe ones where the output is not correctly masked as ESC, mistaken for a servo and even though the disarmed value is 0 or even set to 900 and the motor not turning when disarmed it can spool up upon vehicle termination. Also, it could be that an ESCs and servos are calibrated/set up for a different idle values than 900 and 1500 in which case the failsafe value is out of sync with the disarmed one and has to be set separately.
E.g. …
> PWM: Use disarmed value as default failsafe value

- src/modules/ekf2/ekf2_params.c
I could be wrong, but I suspect `EKF2_EV_DELAY 0` is a better default for most people because MAVROS and ModalAI VOXL vision are handling the timesync by default.
- using ROVIO and with the default EKF2_EV_DELAY 175 it was exceeding the EKF internal timeouts https://github.com/PX4/PX4-Autopilot/issues/19859 
- modal AI EV defaults https://gitlab.com/voxl-public/flight-core-px4/px4-parameters/-/blob/master/platforms/v1.12/Starling/Starling_V2_param_rev_C.params#L54
> ekf2: update EKF2_EV_DELAY default to 0

- ROMFS/px4fmu_common/init.d-posix/airframes/1042_tiltrotor
I originally wanted to only tilt the front motors of the SITL tiltrotor, as this is more realistic (in the model the props are mounted all on the top side of the motor which would cause collisions when tilting..). This could be done by not assigning a motor to the tilt, then it would always stay vertical and not tilt for FW. Kind of a hack that we possibly should prevent in the future, and maybe replace with exposing a setting for which motors to tilt for FW.
Forgot to set CA_SV_TL0_CT and CA_SV_TL2_CT to 1 though, so the current model is broken.
And while reconsidering it decided to for now have all 4 motors tiltable, and control yaw in hove through differential thrust and not tilt.
Let's remove the rear tilts from the simulation model and then change the config again to resemble it to …
> ROMFS: assign all 4 tilts to motors to have them all tilt

- src/drivers/gps/gps.cpp
On some branches, my GCC started complaining this this `snprintf` call may truncate. Looks like increasing the buffer by 1 byte silences the warning. This is also in line with the maximum param name length of 16 (+1 null terminator), and is used like this in other places.
```
/projects/PX4/src/drivers/gps/gps.cpp:329:78: error: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Werror=format-truncation=]
329 |   snprintf(protocol_param_name, sizeof(protocol_param_name), "GPS_%i_PROTOCOL", (int)_instance + 1);
|                                                                              ^
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
```
Increase the buffer by 1 byte.
Check snprintf return value, and do other …
> GPS: Increase param name buffer to address warning in newer gccs

- src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
The auto flight tasks supports retracting the landing gear when it considers to be "high enough above the ground".
However, during the entire takeoff navigation state (which usually persists until you reach the desired takeoff altitude) the landing gear was hardcoded to be extended and thus the mechanism described above did not work anymore.
Remove the hardcoded extension of landing gear during takeoff.
> FlightTaskAuto: don't override landing gear state for takeoff

- ROMFS/CMakeLists.txt
- platforms/nuttx/src/px4/common/gpio/mcp23009/CMakeLists.txt
Fixes the error:
`Aborting due to missing @type tag in file: 'build/px4_fmu-v5_test/etc/init.d/airframes/11001_hexa_cox'`
This can happen due to a change to e.g. board_serial_ports, which changes
the CLI command and triggers a re-execution of the airframe processing.
> ROMFS: fix incremental build for airframe processing

- src/modules/vtol_att_control/standard.cpp
Pusher assist was broken for standard vtol. The signal going to the pusher motor would alternate between the desired value an 0.
> Fixed pusher assist for standard vtol

- src/modules/commander/Commander.cpp
The Battery cell count parameter of the Mantis has been changed from 3 to 4 (which triggers the Battery emergency warning), and was rebooted. **The vehicle would power up (start-up tune plays for 300 ms), and then shut down immediately.**
This leaves the user puzzled as to what's happening (I thought it was bricked), and doesn't give enough time to assess the situation and modify the necessary changes (e.g. changing the battery cell count parameter for my example).
I**ncrease Battery level emergency shutdown time delay from 300 ms to 60 seconds**, to give enough time for the user to configure the vehicle in the mean time. 60 second window is intended to be a reasonable time that will allow the user to figure out …
> Increase Battery level emergency shutdown time delay

- msg/estimator_aid_source_1d.msg
- src/modules/ekf2/EKF/airspeed_fusion.cpp
- src/modules/ekf2/EKF/control.cpp
- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/ekf_helper.cpp
- src/modules/ekf2/EKF/estimator_interface.h
- src/modules/ekf2/EKF/python/ekf_derivation/generated/3Dmag_generated.cpp
- src/modules/ekf2/EKF/python/ekf_derivation/generated/acc_bf_generated.cpp
- src/modules/ekf2/EKF/python/ekf_derivation/generated/beta_generated.cpp
- src/modules/ekf2/EKF/python/ekf_derivation/generated/flow_generated.cpp
- src/modules/ekf2/EKF/python/ekf_derivation/generated/gps_yaw_generated.cpp
- src/modules/ekf2/EKF/python/ekf_derivation/generated/mag_decl_generated.cpp
- src/modules/ekf2/EKF/python/ekf_derivation/generated/tas_generated.cpp
- src/modules/ekf2/EKF/python/ekf_derivation/generated/tas_hk_generated.cpp
- src/modules/ekf2/EKF/python/ekf_derivation/generated/tas_var_generated.cpp
- src/modules/ekf2/EKF/python/ekf_derivation/main.py
- src/modules/ekf2/EKF2.cpp
- src/modules/ekf2/EKF2.hpp
Follows https://github.com/PX4/PX4-Autopilot/pull/19702, requires https://github.com/PX4/PX4-Autopilot/pull/19867
Since this isn't a direct observation of a state, the innovation variance and the KH computation need to be split-up in the python derivation directly.
@dagar This is required to be able to check the test ratio before trying to start the fusion.
SITL tested
> ekf2: estimator aid source status (airspeed)

- msg/vehicle_command.msg
- msg/vehicle_command_ack.msg
- src/drivers/camera_capture/camera_capture.cpp
- src/drivers/camera_trigger/camera_trigger.cpp
- src/drivers/dshot/DShot.cpp
- src/drivers/px4io/px4io.cpp
- src/drivers/rc_input/RCInput.cpp
- src/drivers/uavcan/uavcan_main.cpp
- src/modules/commander/Arming/ArmAuthorization/ArmAuthorization.cpp
- src/modules/commander/Arming/PreFlightCheck/checks/preArmCheck.cpp
- src/modules/commander/Commander.cpp
- src/modules/commander/calibration_routines.cpp
- src/modules/commander/failure_detector/FailureDetector.cpp
- src/modules/flight_mode_manager/FlightModeManager.cpp
- src/modules/gimbal/input_mavlink.cpp
- src/modules/logger/logger.cpp
- src/modules/mavlink/mavlink_main.cpp
- src/modules/mavlink/mavlink_receiver.cpp
- src/modules/navigator/navigator_main.cpp
- src/modules/simulator/simulator_mavlink.cpp
- src/modules/temperature_compensation/TemperatureCompensationModule.cpp
- src/modules/vtol_att_control/vtol_att_control_main.cpp
- src/systemcmds/failure/failure.cpp
Currently, `vehicle_command` uORB message definition has a manually copied over the `VEHICLE_CMD_RESULT*` enums from `vehicle_command_ack` definition, and was using it interchangeably in the code.
This is confusing as the `Command Result` enums are only used by the `vehicle_command_ack` messages, and hence it's unnecessary to have it both in both uORB messages.
More detailed reason:
- As it is always only used for the vehicle command ack message
- It was a duplicate, hence making it error prone for maintainment
- The uORB message comments were updated to make the relationship with
the MAVLink message / enum definitions clear
Move `VEHICLE_CMD_RESULT*` enums to `vehicle_cmd_ack` message file
> Move Vehicle Command Result Enum defs to Vehicle Command Ack message file

- src/modules/ekf2/EKF/control.cpp
requires https://github.com/PX4/PX4-Autopilot/pull/19868
When wind is already estimated, we don't reset the states using airspeed data, so it could be that the fusion fails if the airspeed isn't consistent with the filter (test ratio > 1). At the moment, this makes the airspeed control logic start and stop the fusion at every loop.
If the wind states are already estimated, don't start the fusion if the test ratio would fail.
When wind isn't already estimated, the wind states are reset using airspeed so the fusion can start regardless of the current test ratio.
SITL using `make px4_sitl gazebo_standard_vtol__windy`
With an artificial high constant value in the airspeed data.
> ekf2: start airspeed fusion when test ratio is passing only

- src/drivers/pwm_out/module.yaml
- src/drivers/px4io/module.yaml
This is a Autopilot side PR for the ongoing control allocation user experience improvement (#19444).
1. Clarify the PWM 50, 100, 200, ... setting values by adding 'Hz' in the end to avoid misunderstanding
2.
> Control Allocation User Experience Improvement

- src/drivers/uavcan/sensors/battery.cpp
- src/drivers/uavcan/sensors/battery.hpp
- src/drivers/uavcan/uavcan_params.c
Some of the power modules (non-Smart battery UAVCAN batt devices) don't have an algorithm that is handling estimation like voltage drop or remaining time. 
In that case, if the user drow a lot of currents and the battery have high internal resistance user can experience low remaining flight time or voltage drop under the allowed value that can trigger a false failsafe. 
This solution is integrating internal Battery Library (src/lib/battery) for calculating all filtered voltage, like it is done at other places (ina226, voxlpm drivers, [analog battery](https://github.com/PX4/PX4-Autopilot/blob/f9d8c613b048f58eb3110e9af13cb3a89c4c866f/src/modules/battery_status/analog_battery.h#L39), [esc battery](https://github.com/PX4/PX4-Autopilot/blob/f9d8c613b048f58eb3110e9af13cb3a89c4c866f/src/modules/e …
> Add option for UAVCAN battery to use Battery Library for filtering

- src/lib/tunes/tune_definition.desc
- src/modules/commander/Commander.cpp
- src/modules/commander/commander_helper.cpp
- src/modules/commander/commander_helper.h
Currently when you have a low battery warning, pressing down the power button (e.g. on ATL Mantis Edu) doesn't play the power-off tune, because it gets overridden by the low battery warning tune request published by the Commander
1. Commander was sending the "low battery warning" tune request on every single loop, thus filling up the uORB queue of the `tune_control` message.
1. Fix the commander's `set_tune` function to only allow transmitting the tune_control uORB message request for a tune only after it has finished playing, so that it wouldn't fill up the queue excessively
2. Allow 'override' when requesting the Power button down tune in Commander
I think that a 'priority' …
> Make power off tune uninterruptable

- ROMFS/px4fmu_common/init.d-posix/airframes/1030_plane
- ROMFS/px4fmu_common/init.d-posix/airframes/1037_believer
- ROMFS/px4fmu_common/init.d-posix/airframes/1038_glider
- ROMFS/px4fmu_common/init.d-posix/airframes/1040_standard_vtol
- ROMFS/px4fmu_common/init.d-posix/airframes/1041_tailsitter
- ROMFS/px4fmu_common/init.d-posix/airframes/1042_tiltrotor
- ROMFS/px4fmu_common/init.d-posix/airframes/1043_standard_vtol_drop
- ROMFS/px4fmu_common/init.d-posix/airframes/17001_tf-g1
- ROMFS/px4fmu_common/init.d/airframes/13005_vtol_AAERT_quad
- ROMFS/px4fmu_common/init.d/airframes/13008_QuadRanger
- ROMFS/px4fmu_common/init.d/airframes/13013_deltaquad
- ROMFS/px4fmu_common/init.d/airframes/13014_vtol_babyshark
- ROMFS/px4fmu_common/init.d/airframes/17002_TF-AutoG2
- ROMFS/px4fmu_common/init.d/airframes/17003_TF-G2
- ROMFS/px4fmu_common/init.d/airframes/3100_tbs_caipirinha
- msg/position_setpoint.msg
- msg/tecs_status.msg
- src/lib/parameters/param_translation.cpp
- src/lib/tecs/TECS.cpp
- src/lib/tecs/TECS.hpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
- src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c
- src/modules/navigator/mission_block.cpp
- src/modules/navigator/navigator_main.cpp
1) Introduced trim throttle compensation based on vehicle weight. Weight can be specified via WEIGHT_BASE and WEIGHT_GROSS parameters.
2) Cleaned up trim throttle compensation based on air density.
3) Get rid of trim throttle update via position setpoint triplet. Navigator can command speed setpoints which will take effect if an airspeed estimate is available. Airspeed can either be measured by an airspeed sensor or obtained as a synthetic airspeed measurements (see ASPD_PRIMARY parameter).
**Weight compensation**
Introduce WEIGHT_BASE and WEIGHT_GROSS parameters which are the nominal weight (weight at which the vehicle was tuned) and the actual weight of the vehicle. The two parameters define a weight ratio which are used to adjust the minimum equivalent stall speed based on the relation …
> Improve fixed wing trim throttle compensation & geneal refactoring

- msg/vehicle_status.msg
I was bothered by the readability of the message definition and decided to improve it instead of just skipping over.
- Enums definitions far from the actual variable
- Description of the message somewhere in the middle
- comments repeating only parts of the enums
- useless repetitive comments
- inconsistent spacing tabs and spaces in the same gap
Improved readability in my perspective. No functional changes.
No functional change. Feedback welcome.
> Address vehicle_status message readability

- src/modules/ekf2/EKF/control.cpp
As they are always moving horizontally, the check doesn't make sense for fixed-wings.
Also don't run the check while on ground to prevent getting a failed check during pre-takeoff manipulation.
> ekf2: do not run range finder kinematic consistency check for fixed-wings

- src/modules/commander/commander_params.c
The comment for `COM_RC_IN_MODE` does not match the current value options. 
I have removed the invalid part, but we need to update with information about the new options.
I can't do that yet because I don't know for each case what protections are enabled/disabled. 
@MaEtUgR can you clarify?
Options with questions/comments about behaviour as bullets. 
`@value 0` RC Transmitter only
* Is it true that this requires valid transmitter setup and will failsafe (unless circuit breaker) if transmitter data is lost?
* No requirements for Joystick and it will be ignored.
`@value 1` Joystick only
- Joystick is enabled and RC is disabled. 
- All the RC checks are disabled - so you don't have to set a circuit breaker on them or anything.
- Joystick checks are enabled - so either you will have to have a …
> commander_params: COM_RC_IN_MODE - comment out of date

- msg/gps_inject_data.msg
RTCM data message length was increased to 300 bytes without changing data type of integer holding the length.
This caused an overflow which lead to a busy loop in the gps driver.
Use a uint16.
> Fix busy loop in gps module when using RTCM

- src/drivers/magnetometer/rm3100/rm3100.cpp
The latest changes to the rm3100 driver introduced a bug in self-test.  On fast processors, like the QRB5165, the rm3100 occasionally fails self-test due to incorrect registers configuration.  Further, failed devices return successful if any one of the oscillators passed BIST.  If any of the x, y, or z LR oscillators is malfunctioning then self-test should fail.
Fixed the bug according to the RM3100 datasheet.
This was tested on multiple good RM3100 devices as well as a failed RM3100 (missing z coil).
> Fixed rm3100 self-test bug

- src/drivers/transponder/sagetech_mxs/module.yaml
I noticed the sagetech mxs was running by default in https://github.com/PX4/PX4-Autopilot/issues/19831#issuecomment-1183327062.
FYI @faberc
> sagetech_mxs: don't run by default

- src/modules/sensors/vehicle_gps_position/params.c
When using multiple GPS without blending enabled, the sensors module will select one GPS to use. This can result in vehicle_gps having discontinuities if the data from each GPS isn't similar.
When using Moving Baseline using CAN RTK GPS, such as the ARK RTK GPS, this can result in the second uorb instance being the Rover that is outputting the heading. When the selected GPS is the Moving Base, the heading output from the Rover isn't used. With blending enabled, the heading is always used.
Here is an example where the selected GPS changed back and forth causing an EKF altitude error.
With GPS blending enabled, the blended output results in improved flight performance. 
Does anyone have thoughts on the default of using speed, hpos, and vpos?
> Enable GPS Blending by default

- boards/px4/fmu-v5x/init/rc.board_sensors
- src/drivers/adc/board_adc/ADC.cpp
- src/drivers/adc/board_adc/ADC.hpp
ADS1115 wasn't working as a power monitor for the FMU
This commit starts both the ADS1115 and the internal ADC so that both battery_status and system_power topics are published.
This is how to enable the ADS1115 as power monitor:
BAT1_SOURCE = Power Module (default)
ADC_ADS1115_EN = 1
reboot (and restart AMC or QGC to reload the parameters list)
BAT1_I_CHANNEL = The channel where you connected the analog current reference (either 0 or 1)
BAT1_V_CHANNEL = The channel where you connected the analog voltage reference (either 1 or 0)
BAT1_V_DIV = Given by the manufacturer of the power module
BAT1_A_PER_V = Given by the manufacturer of the power module
Not tested yet. I'll add more context once it's tested
> ADS1115 ADC: start internal ADC as well

- msg/gps_inject_data.msg
- msg/sensor_gps.msg
- src/drivers/gps/gps.cpp
- src/modules/mavlink/mavlink_receiver.cpp
- src/modules/mavlink/mavlink_receiver.h
This PR attempts to support transmission of RTCM corrections over redundant mavlink streams. For example, the corrections are sent through the IP radio and a backup with a serial telemetry radio. 
Previously, if this setup was attempted, both corrections would get published to the same uorb instance. This can cause the RTK GPS to fail from injection of garbage data.
> Support two RTCM links with the same corrections

- src/modules/ekf2/EKF/common.h
Got accidentally removed in https://github.com/PX4/PX4-Autopilot/commit/ea10eacb997d6ad9e91b0ba8777b1454fd9bf54e#diff-a2d8d24867c9fe8a41c8277913b3fba8469e69338097db46ab315e4fa65f21a6L211 , creating an enum mismatch between PX4 and the EKF backend.
> ekf2: add missing mag fuse type in enum

- ROMFS/px4fmu_common/init.d-posix/airframes/1033_rascal
- ROMFS/px4fmu_common/init.d-posix/airframes/1034_rascal-electric
- ROMFS/px4fmu_common/init.d-posix/airframes/1036_malolo
- msg/vehicle_rates_setpoint.msg
- src/lib/tecs/TECS.cpp
- src/lib/tecs/TECS.hpp
- src/modules/fw_att_control/FixedwingAttitudeControl.cpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
- src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c
- src/modules/fw_pos_control_l1/runway_takeoff/RunwayTakeoff.cpp
- src/modules/fw_pos_control_l1/runway_takeoff/RunwayTakeoff.h
- src/modules/fw_pos_control_l1/runway_takeoff/runway_takeoff_params.c
- src/modules/navigator/mission_block.cpp
Issues:
- takeoff is currently defined by a waypoint, but should really be seen as an action or procedure
- many entanglements with TECS and other fixed-wing modes
- many hardcoded limits (magic numbers!) and open-loop behaviors
- takeoff behavior now defined by a **course** (ground-relative direction) to takeoff in, and **clearance altitude** to "clear" before proceeding with the mission.
- takeoff mainly just concerns getting to a specific airspeed and altitude, let TECS control this (in a constrained manner)
- some incremental work on disentangling things
- NOTE: this is mainly a runway takeoff refactor, so the launch detection method is untouched, except for also adhering to the new course-based takeoff logic.
[fw pos ctrl: handle takeoff detection when switching to takeoff mode while …
> Fw takeoff refactor

- src/modules/ekf2/EKF2.cpp
- this is necessary to use distance_sensor data in replay
Backport for v1.13.1
> ekf2: update range sample fix ekf2_timestamps

- ROMFS/px4fmu_common/init.d-posix/airframes/17002_tf-g2
- ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt
- platforms/posix/cmake/sitl_target.cmake
- src/modules/simulator/simulator.h
- src/modules/simulator/simulator_mavlink.cpp
Hello, 
After the devcal last week (26.1.2022), we agreed to prepare a functional Flight-gear simulator with the [TF-G2](https://github.com/ThunderFly-aerospace/TF-G2/) autogyro model, where an automatic takeoff (https://github.com/PX4/PX4-Autopilot/pull/18582) should work.
This PR contains several changes: 
* Update submodule of [flight-gear bridge](https://github.com/PX4/PX4-FlightGear-Bridge), that contains TF-G2 model
* Create TF-G2 SITL airframe, and target
* Added translation of RPM messages from FG to PX4 
Before accepting this PR, it would be good to accept https://github.com/PX4/PX4-FlightGear-Bridge/pull/6 and update it to the latest fg-bridge master version.
> Update Flight-gear bridge, Add support of TF-G2 autogyro flight-gear model 

- src/modules/mavlink/mavlink_main.cpp
- src/modules/mavlink/mavlink_messages.cpp
QGroundControl is capable of rendering temperature data by up to three separate sources (available through mavlink messages SCALED_PRESSURE/2/3), however that data was missing since px4 doesn't send it.
This PR fixes some internal issues around enabling the messages in the first place, then turns them on by default in every place it would otherwise be appropriate to send hygrometer data.
Verified with a custom boat that uses the BMP280 sensor as a means of determining overheating internal components (since the barometer is located in a water proof chamber along with the main board).
> Make barometer temperature data available to QGroundControl

- src/modules/fw_att_control/FixedwingAttitudeControl.cpp
- src/modules/fw_att_control/FixedwingAttitudeControl.hpp
This adds simple backup scheduling to the FW attitude controller so that it continues to run if the `vehicle_attitude` isn't available (or stops midflight). The changes are intended to be a minimal quick fix, but later I'd like to do a larger refactor with separation of the attitude and rate controller that only run if/when the relevant input data is available. It would also be nice to fully remove FW manual mode handling from the attitude controller into a future FlightTask (soon to be standalone flight mode).
> fw_att_control: add simple backup scheduling if vehicle_attitude unavailable (or stops)

- msg/templates/uorb_microcdr/microRTPS_client.cpp.em
- msg/templates/urtps/microRTPS_agent.cpp.em
- msg/templates/urtps/microRTPS_transport.cpp
- msg/templates/urtps/microRTPS_transport.h
We had problems with the RTPS bridge when used over UART. Electrical noise might introduce a spurious character into the data stream from time to time. The existing implementation would accumulate those errors in the parsing buffer. Once the buffer is full only CRC errors would be generated and no message would be parsed successfully.
Two parts:
- Decouple the reading of the transport buffers from the parsing. The old implementation could only parse a single message per transport buffer read. However, a single read might push multiple message into the buffer leading to dropped message, if data is ingested too fast, or if corrupted messages (bad CRC) would accumulate in the buffer.
- Refactor the message detection on the stream buffer.
No alternatives have been explored.
Tested on a single …
> Robustify RTPS bridge stream parsing.

- src/drivers/px4io/px4io.cpp
- even if there's no configured output we still need to run to grab RC data
> px4io: minimal backup scheduling regardless of dynamic mixing

- src/modules/ekf2/EKF2.cpp
- this prevents potential misconfiguration if trying to disable ekf2 multi mag
> ekf2: if multi-mag disabled (EKF2_MULTI_MAG <= 1) properly re-enable sensors hub selection (SENS_MAG_MODE)

- src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
- if using multi-EKF across all magnetometers then an instance of vehicle_magnetometer is advertised immediately for every sensor_mag instance
- this can become problematic if EKF2 multi-mag is enabled, but with only 1 IMU (EKF2_MULTI_MAG) because you will be stuck with no magnetometer data
> sensors/vehicle_magnetometer: don't advertise vehicle_magnetometer instance if mag has been disable

- platforms/nuttx/src/px4/common/nuttx_random.c
- src/drivers/stub_keystore/Kconfig
These are small fixes from the TII master branch;
- It is not necessary to give a compilation error on missing CONFIG_CRYPTO_RANDOM_POOL. Some want's to define their own px4_secure_random function without using NuttX crypto support.
- Allow using stub_keystore with also other crypto backend drivers than sw_crypto
> Small crypto cleanups

- ROMFS/px4fmu_common/init.d/airframes/13000_generic_vtol_standard
- ROMFS/px4fmu_common/init.d/airframes/13100_generic_vtol_tiltrotor
- ROMFS/px4fmu_common/init.d/airframes/13200_generic_vtol_tailsitter
- ROMFS/px4fmu_common/init.d/airframes/2100_standard_plane
- ROMFS/px4fmu_common/init.d/airframes/3000_generic_wing
- ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt
Following up on https://github.com/PX4/PX4-Autopilot/pull/19596#issuecomment-1119658490, I created a "Generic Tiltrotor VTOL" airframe config. The purpose of it is that users with custom airframes (=not RTF models basically) can select this airframe, it sets the needed system variables that tell the system that we're dealing with a VTOL tiltrotor (yes, we should try to reduce their number, they're quite redundant) and then the user configures the actuators through the control allocation UI. 
We already have generic airframes for tailsitters(13200) and standard VTOLs (13000), though they also contain specific actuator settings that we maybe want to remove after dropping support for the legacy mixing system. IMO VTOLs (and FW btw) are too diverse to split them further up than "standard …
> ROMFS: add 13100_generic_tiltrotor config and remove actuator assignments from other generic vehicles

- src/modules/navigator/navigator_main.cpp
- src/modules/navigator/rtl.cpp
- src/modules/navigator/rtl.h
Slight clean up after #19928, realized there is no reason to have special getters for the RTL states.. we can just expose it and compare the current state to the relevant enums.
Exposed the RTL state.
> RTL: expose RTL state

- src/lib/parameters/flashparams/CMakeLists.txt
- src/lib/parameters/flashparams/flashfs32.c
As per the discussion in #15331, fixed issue where stm32h7 chips
use hardware ECC bits in program memory that disallow overwriting
32-byte flash line that has already been written. As such,
this change allows for a variant implementation of the flashfs system
that uses more space in the flash entry header in order to
allow an entire line to be reserved for erasing an entry.
Signed-off-by: Taylor Nelms <tnelms@roboticresearch.com>
Fixed #15331 allowing for onboard-flash parameter storage on STM32H7 chips
I added padding to the flash entry structure such that "erasing" an entry could be done by writing an entire flash line, avoiding the issue with hardware ECC bits causing issues in overwriting the flag on each entry.
I looked into other flash filesystems as potential drop-in alternatives, …
> Component: flash parameter storage on stm32h7. Fixes #15331.

- src/systemcmds/serial_test/serial_test.c
Two bugs are fixed:
1) Proper solution for infinity loop when DMA is used
2) Fix the value for the next write that was causing errors. That was working if a number of bytes for send was a module of 256 because data repeated itself and the empty value was 0.
reproducible with `serial_test -e -b 57600 -p /dev/ttyS6 -w 10`
1) When using DMA with a buffer larger than bytes that are written `write` function will return the given size. Fixed with including the max size of given data. 
2) Calculating the next value before loop exit. 
For better handling when data was really written, DMA tx interrupt could be implemented. 
If the test is used by TX and RX pin connected together with DMA enabled, take care that the TX buffer is not larger than RX buffer. If this is the case it will override the …
> serial_test fix when DMA use large buffer

- src/modules/navigator/vtol_takeoff.cpp
VTOL loiters above home after VTOL Takeoff. This issue can be reproduced when doing a VTOL takeoff after having landed as part of RTL mode. During the backtransition in RTL mode we publish a reposition triplet in order to reset cruise speed and throttle. This triplet is never handled anywhere and remains valid. When the VTOL takeoff completes, commander switches to loiter mode which uses this reposition triplet as setpoint.
Invalidate reposition triplet once VTOL takeoff navigation mode completes
> vtol_takeoff: reset reposition triplet before handing over to loiter mode

- src/modules/airspeed_selector/AirspeedValidator.cpp
Currently the scale factor_validated (which is used to scale the raw airspeed data to airspeed_validated.CAS and TAS) is only allowed to increase by 1% per full circle flown. 
Increase the max step size to 5%. This should still be small enough to not create dangerous steps of the airspeed fed back into controllers.
SITL tested. As expected leads to a 5x faster convergence of the validated scale to the raw scale.
I btw don't understand why the valdiated scale doesn't fully converge to the raw one in SITL, on real places I have never seen that large offset (of 5% here). Example of a real flight:
FYI @RomanBapst @tstastny
> AirspeedValidator: increase max update step size of tas_scale_validated from 1% to 5%

- msg/tools/generate_microRTPS_bridge.py
humble added to the microRTPS bridge generation to add the support in px4_ros_com
> generate_microRTPS_bridge.py updated to support ROS2 humble

- msg/estimator_aid_source_1d.msg
- msg/estimator_aid_source_3d.msg
- msg/estimator_status_flags.msg
- src/modules/ekf2/EKF/control.cpp
- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/ekf_helper.cpp
- src/modules/ekf2/EKF/estimator_interface.h
- src/modules/ekf2/EKF/gps_control.cpp
- src/modules/ekf2/EKF/gps_fusion.cpp
- src/modules/ekf2/EKF/gps_yaw_fusion.cpp
- src/modules/ekf2/EKF/mag_control.cpp
- src/modules/ekf2/EKF/mag_fusion.cpp
- src/modules/ekf2/EKF/zero_innovation_heading_update.cpp
- src/modules/ekf2/EKF2.cpp
- src/modules/ekf2/EKF2.hpp
- src/modules/logger/logged_topics.cpp
This adds initial support for partially populating and publishing estimator_aid_source for all heading sources (mag, gnss, yaw). Slightly larger restructuring will be necessary to fully populate everything when the heading source isn't active.
> ekf2: use estimator_aid_src for all yaw sources (mag, gnss, ev)

- boards/av/x-v1/src/CMakeLists.txt
- boards/cuav/nora/src/CMakeLists.txt
- boards/cuav/x7pro/src/CMakeLists.txt
- boards/cubepilot/cubeorange/src/CMakeLists.txt
- boards/cubepilot/cubeyellow/src/CMakeLists.txt
- boards/holybro/durandal-v1/src/CMakeLists.txt
- boards/holybro/kakutef7/src/CMakeLists.txt
- boards/holybro/kakuteh7/src/CMakeLists.txt
- boards/holybro/pix32v5/src/CMakeLists.txt
- boards/matek/h743-mini/src/CMakeLists.txt
- boards/matek/h743-slim/src/CMakeLists.txt
- boards/matek/h743/src/CMakeLists.txt
- boards/modalai/fc-v1/src/CMakeLists.txt
- boards/modalai/fc-v2/src/CMakeLists.txt
- boards/mro/ctrl-zero-f7-oem/src/CMakeLists.txt
- boards/mro/ctrl-zero-f7/src/CMakeLists.txt
- boards/mro/ctrl-zero-h7-oem/src/CMakeLists.txt
- boards/mro/ctrl-zero-h7/src/CMakeLists.txt
- boards/mro/pixracerpro/src/CMakeLists.txt
- boards/nxp/fmuk66-e/src/CMakeLists.txt
- boards/nxp/fmuk66-v3/src/CMakeLists.txt
- boards/px4/fmu-v5/src/CMakeLists.txt
- boards/px4/fmu-v6u/src/CMakeLists.txt
- boards/px4/fmu-v6x/src/CMakeLists.txt
- boards/spracing/h7extreme/src/CMakeLists.txt
Linking issue for PX4 minimal build (reduced .px4board, useful for board recovery variant)  
`/GIT/PX4/Firmware/build/px4_fmu-v6x_recovery/../../boards/px4/fmu-v6x/src/init.c:144: undefined reference to 'io_timer_channel_get_as_pwm_input'`
To reproduce remove all modules that contain **arch_io_pins** px4board config 
Add missing link to **arch_io_pins** lib for `boards/init.c` where `io_timer_channel_get_as_pwm_input` is used. 
```
> grep -nr io_timer_channel_get_as_pwm_input boards
boards/holybro/durandal-v1/src/init.c:144:              px4_arch_configgpio(PX4_MAKE_GPIO_INPUT(io_timer_channel_get_as_pwm_input(i)));
boards/holybro/kakuteh7/src/init.c:129:         px4_arch_configgpio(PX4_MAKE_GPIO_INPUT(io_timer_channel_get_as_pwm_input(i)));
boards/holybro/pix32v5/src/init.c:143: …
```
> boards: link missing arch_io_pins lib

- src/drivers/pwm_out/PWMOut.cpp
- src/drivers/pwm_out/PWMOut.hpp
- src/drivers/px4io/px4io.cpp
- src/lib/mixer_module/mixer_module.hpp
This should simplify the setup a bit.
@jstrebel this adds the logic to set the PWM rate to 50 Hz and disarmed value to 1500 when first setting a servo to one of the PWM outputs.
Fixes #19866
> px4io+pwm_out: set the PWM rate and disarmed value when a channel is first set to a servo

- platforms/nuttx/src/px4/nxp/s32k1xx/watchdog/CMakeLists.txt
- platforms/nuttx/src/px4/nxp/s32k1xx/watchdog/iwdg.c
#19924 Needed this dummy iwdg driver since uavcannode needs this.
Since this patch da675372911b446460ab08b53b98c5c9f336520d
@davids5 what does this watchdog do, and is there a way to make this platform agnostic in the future?
> S32K1XX add dummy iwdg driver

- src/modules/navigator/mission.cpp
- src/modules/navigator/mission_block.cpp
When updating a mission while the vehicle is already flying in fixed wing mode the mission index is reset. If the mission contains a VTOL_TAKEOFF item then the vehicle will navigate to it. This does not make sense as the vehicle has already transitioned.
Skip VTOL_TAKEOFF item when already in fixed wing mode.
> Skip VTOL_TAKEOFF mission item when in fixed wing mode

- Jenkinsfile
CI does not appear to be working at all, and hasn't AFAIK since update to use main rather than master. As evidence I point to the jenkins page, which indicates nothing has run, and is idle (except main), which I kicked off. Also that no stuff from docs has been build for a month or so - though that co-incided with me changing docs to main, so could be multiple things going on.
I think there was no update to CI following moving to using main branch. 
As @dagar is on holiday, this change just updates jenkins to build for main as well as master. It shouldn't break anything because it is an "as well" build. Let's see if this does something useful.
> CI - build on main as well

- src/drivers/rc_input/ghst_telemetry.cpp
- src/drivers/rc_input/ghst_telemetry.hpp
- src/lib/rc/ghst.cpp
- src/lib/rc/ghst.hpp
Add support for the basic GPS telemetry values when using the GHST protocol.
Initial GHST driver handled battery status telemetry, but not GPS telemetry. This PR contains a relatively simple (safe) change which adds pass-through of PX4's GPS position to the Ghost receiver. 
Tested on a H743-SLIM (which requires #define RC_SERIAL_SINGLEWIRE in board_config.h to enable telemetry). 
Reviewers... should this #define be added to the H743-SLIM board definition? it does mean (I believe) that anyone running this board with the Ghost receiver hooked to a UART Rx pin would need to rewire it to a Tx pin (as is the case for Betaflight, iNav, etc. )
> GHST: Add support for GPS Telemetry

- boards/px4/fmu-v6c/init/rc.board_defaults
On the boot the Ethernet params are being initiated which are non-sense on 6C
Cleaned up the init file.
> Pixhawk 6C Ethernet init stuff clean up. 

- src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
Navigator sets the cruise_speed to -1 if the controller shouldn't listen to it and instead use the default speed (for MC: MPC_XY_CRUISE). This is for example for RTL the case, where we want to return at the default speed, independently of what the mission speed before was.
For FW the check for <0 was never there, it only checks isfinite() (like the MC controller now). 
Also added a minor cosmetic change in changing a `<0.0f` to `<FLT_EPSILON` as float comparisons against 0.0f are not recommended.
> FlightTaskAuto: apply cruise speed from position triplet also when negative to have default speed in RTL

- src/modules/ekf2/EKF/ekf_helper.cpp
- src/modules/ekf2/test/test_EKF_basics.cpp
1. the test wasn't running properly because if the ekf doesn't run, the test ratio isn't populated, so the test ratio is 0
1. the maximum size of the local position origin is a cube of 1e6m. If the origin is moved further than this, the state is clipped to that maximum value. 
1. baro and range height offsets are "positive up" while `posD_change` is "positive down" so we need to add the `posD_change`
> setEkfGlobalOrigin fixes

- src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
- src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.hpp
- src/modules/flight_mode_manager/tasks/Orbit/flight_task_orbit_params.c
For safety/dummy proofing reasons the radius of a multicopter orbit is limited. There were use cases recently that required more than 100m orbit radius limit and that's why I increased the hardcoded limit in https://github.com/PX4/PX4-Autopilot/pull/19362 The ground station does not know what the limit is but allows the user to plan an arbitrary radius which then gets rejected by the autopilot.
For these reasons, I made the maximum radius configurable.
Alternatively we could remove the maximum radius limit altogether.
\- That would allow an infinite unreasonable radius
\+ For dummy proofing 1 km radius is already quite large
\+ Slightly less complexity and code
This was simulation tested separately and together with client ground station code to limit the radius correctly.
> FlightTaskOrbit: parameterize hardcoded maximum radius

- ROMFS/px4fmu_common/init.d-posix/airframes/1030_plane
- ROMFS/px4fmu_common/init.d-posix/airframes/1037_believer
- ROMFS/px4fmu_common/init.d-posix/airframes/1040_standard_vtol
- ROMFS/px4fmu_common/init.d-posix/airframes/1041_tailsitter
- ROMFS/px4fmu_common/init.d-posix/airframes/1042_tiltrotor
- ROMFS/px4fmu_common/init.d-posix/airframes/1043_standard_vtol_drop
- ROMFS/px4fmu_common/init.d-posix/airframes/17001_tf-g1
- ROMFS/px4fmu_common/init.d-posix/airframes/17002_tf-g2
- ROMFS/px4fmu_common/init.d/airframes/1002_standard_vtol.hil
- ROMFS/px4fmu_common/init.d/airframes/13008_QuadRanger
- ROMFS/px4fmu_common/init.d/airframes/13012_convergence
- ROMFS/px4fmu_common/init.d/airframes/13013_deltaquad
- ROMFS/px4fmu_common/init.d/airframes/13014_vtol_babyshark
- ROMFS/px4fmu_common/init.d/airframes/3100_tbs_caipirinha
- ROMFS/px4fmu_common/init.d/rc.vtol_defaults
- src/modules/fw_att_control/fw_att_control_params.c
- src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c
- src/modules/mc_pos_control/mc_pos_control_params.c
With this PR I try to improve the setup UX though:
- set more reasonable parameter defaults where the case is valid for all vehicle types that use it
- change/add params in the vehicle defaults (only in vtol_default in this case)
- improve parameter meta data 
Most of the param defaults that I touch are params that I change on every single VTOL that I set up, and the annoyance of having to do that was the largest motivation for this PR.
See commit messages for details. I expect the biggest controversy around https://github.com/PX4/PX4-Autopilot/commit/d16270ffb4046fdb6dc9fd7b7430499608c6a422 (@bresch @MaEtUgR ). For MC we had a default of 1m/s descend speed, for VTOL 1.5. My proposal is to globally have it at 1.5m/s.
> Various parameter default/vehicle default/meta-data changes 

- cmake/gtest/CMakeLists.txt.in
Fixes the error
```
googletest-src/googletest/src/gtest-death-test.cc:1283:24: error: ‘dummy’ may be used uninitialized [-Werror=maybe-uninitialized]
```
with GCC 11
> gtest: update to version 1.12.1

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
Nudge rate on landing was a bit slow. And post flaring, not so effect when rolling out on ground (still moving the path and not directly acting with the wheel).
- Bumped the landing nudge rate.
- Once the flare has engaged, fixed the landing touchdown offset, and feed the yaw stick directly to the wheel (like in takeoff nudging) to allow direct nudging on wheels after touchdown.
Flight test https://review.px4.io/plot_app?log=7cfc1746-df6b-4824-ab9e-ac6c2e7962bd
> Fixed-wing landing nudge modifications

- src/drivers/distance_sensor/lightware_laser_i2c/lightware_laser_i2c.cpp
- src/drivers/distance_sensor/lightware_laser_serial/lightware_laser_serial.cpp
SF11: https://www.documents.lightware.co.za/SF11%20-%20Laser%20Altimeter%20Manual%20-%20Rev%209.pdf
SF/LW20: https://www.documents.lightware.co.za/SF11%20-%20Laser%20Altimeter%20Manual%20-%20Rev%209.pdf
> lightware dist sensor: set min range based on datasheet

- cmake/px4_add_module.cmake
We are running PX4&NuttX on 64-bit RISC-V targets. The need for stack is larger on 64 bits, and this is taken care in many places already with PX4_STACK_ADJUSTED() macro.
However, with built-in modules "main" functions this is not yet handled. The stack size comes from STACK_MAIN CMake variable, which has got either a default value, or it can be set per-module.
Just recently I figured out that we are getting some instability & random crashes due to some of these modules crashing / corrupting memory at startup (especially sensors module, maybe some others as well). This was due to stack overflows.
Just adjust the STACK_MAIN directly in px4_add_module, using the same mechanism as what PX4_STACK_ADJUSTED macro does. Since STACK_MAX is …
> Double the allocated stack size of 64-bit NuttX built-in modules

- ROMFS/px4fmu_common/init.d-posix/airframes/1042_tiltrotor
The tiltrotor model had all four motors tilting. However the most common quad tiltrotor configuration is the front two motors rotating, and the two rear motors fixed.
This PR modifies the current tiltrotor model to have only the front motors rotate in fixed wing mode
Flight log: https://review.px4.io/plot_app?log=80077dd9-fb35-498e-8f5e-3d6711ac0add
[![Hovering drone](https://img.youtube.com/vi/Q9iYKR3eimo/0.jpg)](https://youtu.be/Q9iYKR3eimo)
- Submodule PR: https://github.com/PX4/PX4-SITL_gazebo/pull/890
> Disable rear motors tilt

- src/modules/mavlink/mavlink_main.cpp
- src/modules/mavlink/mavlink_messages.cpp
- src/modules/mavlink/streams/TIME_ESTIMATE_TO_TARGET.hpp
Time to safe return (time to RTL) is calculated by PX4 and published to uOrb, but it is not sent through MAVLink. This PR populates the `TIME_ESTIMATE_TO_TARGET` message with the time to RTL field and sends it with a maximum frequency of 1Hz. This can be used to display the time for safe return on the ground station.
Created a MAVLink stream that subscribes to the `rtl_time_estimate` uOrb topic, constructs the MAVLink message and sends it.
Tested using gazebo simulator and QGC MAVLink inspector.
> Fill estimate time to target message with time to RTL 

- src/modules/ekf2/EKF2.cpp
Using the control status flags isn't robust as this part of the code runs at the EKF update rate while the in_air transition is don at the prediction rate; it was then likely to miss the transition
> ekf2: reset ekf preflight checks on takeoff correctly

- src/modules/mavlink/streams/TIME_ESTIMATE_TO_TARGET.hpp
The [MAVLink message definition](https://mavlink.io/en/messages/common.html#TIME_ESTIMATE_TO_TARGET) says "-1 means no time estimate available." Since the original implementation from https://github.com/PX4/PX4-Autopilot/pull/20029 initializes all fields with zero they are in principle valid and available.
FYI @marcirsch
Fill unsupported fields with -1.
Also I made the cast of the estimated time for the RTL in seconds float in uORB to int32 in MAVLink explicit.
Untested. This is purely based on code review.
> TIME_ESTIMATE_TO_TARGET: clarify unsupported message fields

- src/modules/mc_att_control/mc_att_control_main.cpp
https://github.com/PX4/PX4-Autopilot/pull/12542 made the lowest possible throttle value commanded by stick in Stabilized mode before taking off 0. The real world problem with this is that when takeoff is detected then the entire throttle scaling range jumps from
[0, MPC_MANTHR_MIN] to [MPC_MANTHR_MIN, MPC_MANTHR_MIN].
As a result whenever MPC_MANTHR_MIN is not set to 0 there is a thrust jump on every takeoff just at the moment takeoff is detected even when the stick is moved continuously.
Because of this, I suggest reverting to having a higher throttle value from the beginning on because it's less complicated and there's no obvious value in starting out with zero thrust if it's anyways not possible to go back to zero for safety once takeoff is detected.
I tested this in simulation:
I …
> Fix multicopter stabilized mode throttle scale jump during takeoff

- src/modules/mavlink/mavlink_ftp.cpp
Clear any not used payload data to correctly trim mavlink ftp message reply to avoid sending long ACK and NACK messages.
File upload before patch:
Full size 308 bytes acknowledgments that replicate requested packet disregarding that `payload->size` is set for 4 bytes (bytes written).
After patch:
Correctly trimmed acknowledgments.
I supposed same thing have to be done in QGC.
It would be more efficient instead of `memset` to pass somehow payload size to `mavlink_msg_file_transfer_protocol_send_struct()` but as I understand it is not convenient by mavlink architecture.
I've tested this with file upload and a little with file download with custom board and custom fork based on older px4. Please feel free to edit if needed.
This should speed up mavlink ftp transfer a little especially if …
> mavlink_ftp: fix to correctly trim reply messages

- src/drivers/imu/analog_devices/adis16470/ADIS16470.cpp
Accel scaling was equivalent, but this shows how it's directly derived from the datasheet. Gyro scaling was wrong (and being overwritten).
> adis16470: fix accel and gyro scaling

- src/lib/battery/battery.cpp
- src/lib/mathlib/math/Functions.hpp
- src/lib/mathlib/math/FunctionsTest.cpp
- src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
- src/modules/flight_mode_manager/tasks/ManualAltitude/FlightTaskManualAltitude.cpp
- src/modules/fw_att_control/FixedwingAttitudeControl.cpp
- src/modules/mc_att_control/mc_att_control_main.cpp
- src/modules/simulator/battery_simulator/BatterySimulator.cpp
The method math::gradual in the mathlib is a good linear interpolation routine.
A linear interpolation routine deserves to be recognized as such. :)  https://en.wikipedia.org/wiki/Linear_interpolation
Although I have no idea how it is not clobbering things in the case of divide by zero, that case, as well the types I've tested in the unit tests, (not included in this PR to save extra code), have all passed. 
I am an advocate of templating, even though it can increase binary size.  If we template more math routines as is in the case of the methods in some of the math namespace, we could consider migrating toward leveraging the Eigen library... although that comes at a cost as well.
Additional unit tests were added to ensure undefined behavior was not taking place.
> Rename math::gradual() to math::interpolate() and add unit tests to cover additional corner cases.

- src/modules/mc_pos_control/PositionControl/PositionControl.cpp
Since the horizontal and vertical velocity controllers are now decoupled, it can be that the horizontal acceleration produced by the controller is actually greater than the desired one (by design). This condition would actually make the ARW run "backwards", degrading the controller performance.
Current state of PX4:
We can see below that the integrator continues to increase even when the velocity overshoots the setpoint because  the anti-reset windup loop works in reverse when the produced acceleration is larger than the desired one (this was never possible in the past, with the coupled XY and Z axes).
With this PR:
The integrator now works properly; there is also less overshoot in general
> MCPosControl: fix horizontal anti-reset windup algorithm

- platforms/nuttx/src/px4/stm/stm32f4/px4io_serial/px4io_serial.cpp
- platforms/nuttx/src/px4/stm/stm32f7/px4io_serial/px4io_serial.cpp
- platforms/nuttx/src/px4/stm/stm32h7/px4io_serial/px4io_serial.cpp
- src/drivers/px4io/px4io.cpp
There seems to be a potential race condition within the px4io serial driver, that leads to double posting of the `_completion_semaphore`. This semaphore is posted from the UART or DMA interrupts. If the `sem_timedwait` times out waiting for the semaphore, it aborts the DMA and UART transfer, which also disables those interrupts. However, there is a race. The interrupt could happen before the interrupts are disabled or the `_rx_dma_status` gets set to `_dma_status_inactive`. Then the sempahore gets posted, without anyone waiting for it. In the next transfer, the code can then immediately obtain the semaphore and thus no longer waits for the semaphore to complete.
This then usually leads to CRC errors. Now:
- In the worst case, the CRC happens to match by accident, the data is treated as …
> Fix race condition in px4io serial driver

- src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
The roll one is since https://github.com/PX4/PX4-Autopilot/pull/18989 not used anymore, how pitch was ever used I don't know.
> FW Position Control: remove unnsed params

- src/lib/mixer_module/CMakeLists.txt
The module has a hard dependency on mixer library, so link them together
Fixes build error when mixer_module cannot find definitions for Mixer::Xxx()
The mixer module has a hard dependency on mixer, so they should be linked together
Find every module / library that depends on mixer_module and add the linkage with mixer there
fmu-v5 protected mode
> mixer_module: Fix linking of mixer_module

- platforms/nuttx/NuttX/CMakeLists.txt
Use CONFIG_ARCH instead of arm
Solves a minor issue with library pathing for protected mode karch library
Build succeeds / fmu-v5 protected mode works
> platforms/nuttx: Fix hard coded path for karch library

- src/lib/motion_planning/VelocitySmoothingTest.cpp
Bug fix on compilation error when running functional tests. Specifically, the test failing was in the velocity smoothing. Root cause was in line 171 of VelocitySmoothingTest.cpp, which was using `ceil`. The compiler threw a fatal error for implicit casting as the ceil function accepts arguments of the double type. 
Minor amendment to use `ceilf` which accepts floating point arguments. 
Casting arguments to double in `ceil`. 
Ran `make tests TESTFILTER=function` with all tests passing.
> Fix velocity smoothing functional test

- src/drivers/adc/board_adc/ADC.cpp
Print sizeof type with %zu to be compatible with 64 bit targets, where it is unsigned long
> board_adc: Small fix for printf formatter

- platforms/nuttx/CMakeLists.txt
The comment is right, it is not needed -> get rid of it
Remove unnecessary library from the kernel side link command
> Remove px4_work_queue from the kernel side LD command

- src/modules/commander/Commander.cpp
The Level Horizon button in QGC was no starting the level calibration routine after this commit: https://github.com/PX4/PX4-Autopilot/pull/19729
See issue discussion here: https://github.com/PX4/PX4-Autopilot/issues/19998
Restored else if statement that was accidentally deleted in the commit mentioned above.  
Tested on a Pixhawk 4 that Level Horizon initiated the level calibration, and properly populated SENS_BOARD_X_OFF and SENS_BOARD_Y_OFF as expected.
> Reverted changes that broke Level Horizon calibration

- platforms/common/include/px4_platform_common/crypto.h
- platforms/common/include/px4_platform_common/crypto_backend.h
- platforms/nuttx/src/px4/common/px4_protected_layers.cmake
- platforms/nuttx/src/px4/common/px4_usr_crypto.cpp
This adds kernel-userspace interfaces to crypto layer
Crypto interfaces are not usable in protected build, unless there is an interface to use it also from the user-side modules. This patch adds the necessary IOCTL:s to use the crypto api also in protected build.
This has been tested on fmu-v5 (pixhawk4) platform as well as one one custom HW.
> Add call-gates to px4_crypto for protected build

- src/modules/ekf2/CMakeLists.txt
- src/modules/ekf2/EKF/estimator_interface.cpp
- this prevents unsigned integer underflow if the timestamp is smaller than the configured delay (mostly a simulation edge case)
- discovered when testing https://github.com/PX4/PX4-Autopilot/pull/20137
> ekf2: estimator interface handle sample time with signed integers

- platforms/posix/src/px4/common/drv_hrt.cpp
- src/drivers/drv_hrt.h
- src/modules/simulation/simulator_mavlink/SimulatorMavlink.cpp
Do we need the HRT offset time for anything? Dropping it makes things a bit simpler with the sim time and HRT time exactly the same.
> posix lockstep remove HRT offset and use full sim time

- platforms/posix/Debug/launch_sitl_ignition.json.in
- platforms/posix/src/px4/common/drv_hrt.cpp
- src/drivers/drv_hrt.h
- src/modules/simulation/simulator_ignition_bridge/CMakeLists.txt
- src/modules/simulation/simulator_ignition_bridge/SimulatorIgnitionBridge.cpp
- src/modules/simulation/simulator_ignition_bridge/SimulatorIgnitionBridge.hpp
- src/modules/simulation/simulator_mavlink/SimulatorMavlink.cpp
- requires HRT lockstep changes to eliminate offset (PR #20146)
> simulation: ignition bridge allow IMU or pose callbacks to update system time if newer than clock

- src/modules/ekf2/EKF/ekf.cpp
- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/ekf_helper.cpp
- src/modules/ekf2/EKF/gps_yaw_fusion.cpp
- most of resetQuatStateYaw doesn't apply to initial heading init, so removing the special case keeps it simple
- avoid incrementing the quat reset counter and delta initially (no one even has the attitude yet)
> ekf2: initialiseFilter() simplify mag heading init and resetQuatStateYaw

- boards/px4/fmu-v5/src/board_config.h
- platforms/common/CMakeLists.txt
- platforms/common/board_common.c
- platforms/common/include/px4_platform_common/board_common.h
- platforms/nuttx/src/px4/common/board_ioctl.c
- platforms/nuttx/src/px4/common/include/px4_platform/board_ctrl.h
- platforms/nuttx/src/px4/common/px4_layer.cmake
- platforms/nuttx/src/px4/common/px4_protected_layers.cmake
- platforms/nuttx/src/px4/common/usr_board_ctrl.c
Move logic implemented in the header files to source files, this way it will be simpler to define which is compiled to kernel space and which to user space in CONFIG_BUILD_PROTECTED target
Also allows to remove some headers that pull in half the universe from the board definitions (which should just be pin definitions and no functionality)
Splits the VBUS and nARMED pin handling into two separate implementations, for user- and kernelspace
> board_ctrl: Clean up usage of VBUS, nARMED from user/kernelspace

- src/modules/ekf2/EKF/control.cpp
- src/modules/ekf2/EKF/covariance.cpp
- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/ekf_helper.cpp
- src/modules/ekf2/EKF/gnss_height_control.cpp
- src/modules/ekf2/EKF/gps_control.cpp
- src/modules/ekf2/EKF/gps_fusion.cpp
- src/modules/ekf2/EKF/gps_yaw_fusion.cpp
- src/modules/ekf2/EKF/height_control.cpp
- this minimizes potential misuse accessing _gps_sample_delayed and makes the dependency clear
> ekf2: pass gpsSample around where required

- src/modules/ekf2/EKF/zero_velocity_update.cpp
- src/modules/ekf2/test/test_EKF_accelerometer.cpp
- src/modules/ekf2/test/test_EKF_gps.cpp
After boot, the GPS checks are sometimes passing quite early, before the GNSS solution fully converged. The EKF needs to follow the altitude variation (re-converge), but it takes a lot of time because the "Zero Velocity Update (ZVU)" almost paralyzes the vertical velocity and position estimates.
- ~enable PDOP and EPV checks for starting GNSS fusion (GNSS height fusion is now enabled by default)~ will be in a follow-up PR
- increase the measurement noise of VZU (equivalent to a good GNSS velocity aiding) after the global position has been initialized
Move the EKF global origin: the issue by doing this is that it requires more changes and is likely to create new bugs and race conditions.
> EKF2: Improve height convergence during startup

- Tools/setup/macos.sh
Somehow the wheel install of pymavlink fails without future, let's try to work around that.
> setup: attempt to fix macOS CI

- msg/geofence_result.msg
- msg/vehicle_status_flags.msg
- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
- src/modules/commander/HealthAndArmingChecks/checks/geofenceCheck.cpp
- src/modules/commander/failsafe/failsafe.cpp
- src/modules/mavlink/streams/HIGH_LATENCY2.hpp
- src/modules/navigator/navigator_main.cpp
- src/systemcmds/microbench/test_microbench_uorb.cpp
Hi @bkueng ,
This PR replaces work done in #20164 to capture google style changes and formatting.  It also renames `geofence_violated` -> `primary_geofence_breached` to lay groundwork for #20055.  It also fixes up the current failing CI test in #20172
Flight tested on a pixhawk4 mini: https://review.px4.io/plot_app?log=3fa509c3-c1c2-45f9-b9fd-c183d92ed23b
Basic geofence and mode sqitching all checks out fine.
Feel free to simply grab these changes, commit into your existing branch, and close this PR.
Let me know if you have any questions on this PR.
Thanks!
> Apply Google Style to Commander Private methods, rename geofence message geofence_violation to primary_geofence_breached.

- src/modules/dataman/dataman.cpp
Fixes:
WARN  [load_mon] dataman low on stack! (276 bytes left)
Seen on px4_fmu-v5_protected target.
Increase the dataman stack size slightly. I assume the warning threshold is reached if a trap is taken when dataman is in execution (trap entry requires quite a large stack frame). With protected mode every syscall traps via SVC so seeing higher stack utilization with this target is more common.
px4_fmu-v5_protected
> modules/dataman: Increase stack size by 100B

- .github/workflows/checks.yml
- .github/workflows/clang-tidy.yml
- .github/workflows/compile_linux.yml
- .github/workflows/compile_linux_arm64.yml
- .github/workflows/compile_macos.yml
- .github/workflows/compile_nuttx.yml
- .github/workflows/deploy_all.yml
- .github/workflows/mavros_mission_tests.yml
- .github/workflows/mavros_offboard_tests.yml
- .github/workflows/metadata.yml
- .github/workflows/python_checks.yml
- .github/workflows/sitl_tests.yml
- .travis.yml
- Jenkinsfile
Some of the CI files still point to the `master` branch instead of the up-to-date `main` branch. This points the CI to the correct `main` branch. This also fixes the issues where the update to `px4_msgs` was still using the old `master` branch instead of the current `main` branch.
Replace `master` branch with `main` where appropriate.
> Update CI files to use the main branches.

- platforms/nuttx/src/px4/common/px4_userspace_init.cpp
For targets that define the SPI buses via px4_spi_buses_all_hw, a call to px4_set_spi_buses_from_hw_version() is needed. Otherwise a NULL de-reference will occur when trying to access px4_spi_buses.
Fixes a system crash in px4_fmu-v5_protected:
up_assert: Assertion failed at file:armv7-m/arm_memfault.c line: 101 task: wq:lp_default
px4_fmu-v5_protected
> px4_userspace_init: Fix NULL dereference for px4_spi_buses in user space

- src/modules/navigator/mission_block.cpp
VTOL takeoff depending on how the vehicle was landed before would not work properly. The tricky part is that even though the issue showed up pretty often after an update on one of our models used in its typical workflow I was never able to reproduce the root cause SITL. Also, the Symptom is flaky but most of the time it would not take off at all, get stuck during the initial ascent or even descend again somewhere in the middle of the ascent.
I was able to find the combination of all the in-between problems and two of them I'm fixing in this pr. That doesn't give us a guarantee for any related problem ever occurring again but I'm fairly confident it increases robustness.
- The global field `_mission_item.acceptance_radius` in navigator in some way got a value close to zero but just not …
> VTOL takeoff problem hotfix

- msg/tools/generate_microRTPS_bridge.py
When ROS2 is built from sources and dpkg is unable to check the package version, system-wide version of fastrtps is used.
> Fixed fastrtps version reading in microRTPS generation for ROS2 built from sources

- platforms/common/include/px4_platform_common/time.h
- platforms/posix/cmake/px4_impl_os.cmake
- platforms/posix/src/px4/common/drv_hrt.cpp
I believe since Sierra CLOCK_MONOTONIC has been available, but I'll verify.
> platforms/posix: cleanup obsolete MacOS legacy

- boards/ark/can-rtk-gps/init/rc.board_defaults
- src/drivers/uavcan/sensors/gnss.cpp
- src/drivers/uavcannode/Subscribers/RTCMStream.hpp
- src/drivers/uavcannode/UavcanNode.cpp
- src/drivers/uavcannode/uavcannode_params.c
This PR adds an option to subscribe to RTCMStream messages on cannode GPS. Ardupilot publishes RTCMStream when using a fixed base but uses MoveBaselineData when using a moving base.
> Add cannode RTCMStream subscriber and fix RTCMStream Publisher

- src/drivers/imu/invensense/icm42688p/ICM42688P.cpp
- src/drivers/imu/invensense/icm42688p/ICM42688P.hpp
In roughly 5% of ICM-42688-P we have seen the issue `bad transfer: 1 events` after PX4 reboot. 
After investigating it is discovered that bits **HEADER_ODR_ACCEL** and **HEADER_ODR_GYRO** in the first FIFO Header are set to value 1. 
In the image, it can be seen the value of the first FIFO header is **0x7B** while the second one is 0x78
0x7B -> first 2 bits are set to 1 (HEADER_ODR_ACCEL and HEADER_ODR_GYRO)
0x78 -> first 2 bits are set to 0 (HEADER_ODR_ACCEL and HEADER_ODR_GYRO)
After adding sleep before `FifoReset()` result was `FIFO empty: 1 events` 
That means FIFO was actually getting restarted but didn't have enough time to finish it, so another sleep was needed for `FifoRestart()`.
The conclusion is that about 5% of IMUs are not fast enough to immediately do config and FIFO flush. …
> invensense/icm42688p: add extra time for between FIFO Reset command

- ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator
- ROMFS/px4fmu_common/init.d-posix/rcS
- ROMFS/px4fmu_common/init.d/rcS
- Tools/px4airframes/rcout.py
- src/lib/parameters/parameters.cpp
- src/lib/parameters/tinybson/tinybson.cpp
- rcS parameter backup try to directly restore param (FRAM) from backup (in case SD card is removed before successful export)
- rcS parameter backup logging rearrange to capture more logging output (param_import_fail.txt)
- posix rcS try to keep param backup and restore roughly in sync with NuttX rcS
- tinybson fix debug printf format
- param_export_internal ensure file descriptor positioned at 0 (precaution)
> parameters: open export files O_TRUNC to discard previous data

- msg/tools/urtps_bridge_topics.yaml
`attitude` and `body rate` control in offboard mode was previously not possible with Fast-RTPS.
Generate the corresponding RTPS message for those two channels. The PX4 build bot should automatically update the [px4_ros_com](https://github.com/PX4/px4_ros_com) repo right?
None
Does not affect the flight controller
None
> Add attitude and bodyrate control to RTPS

- src/drivers/gps/gps.cpp
- src/drivers/gps/params.c
When using the U-blox ZED-F9P GPS module, users may want to use the GPS module's UART2 port to send or receive RTCM corrections using a Telemetry Radio, rather than hard wiring this port to another module. These radios commonly operate at 57600 baud out of the box. But the UART2 baudrate is hard coded to 230400 baud. This PR allows us to configure the Baud Rate of the ZED-F9P's UART2 port through a QGC param.
Additionally, the existing modes that the **GPS_UBX_MODE** param covers misses one potential mode -- when a user is sending RTCM corrections from a _static_ base, or other _static_ correction source, directly to UART2. The wording and documentation of the existing modes that enable UART2 assume a moving base configuration. I've called this new mode **Rover With Static Base on …
> ZED-F9P UART2 Baudrate Configurability and New UBX Mode.

- src/drivers/distance_sensor/broadcom/afbrs50/AFBRS50.cpp
- src/drivers/distance_sensor/broadcom/afbrs50/API/Src/irq.c
This PR changes the AFBR distance sensor driver to use the trigger measurement function instead of the API's built in measurement timer.
https://review.px4.io/plot_app?log=0eb19c71-da95-4341-84da-d547436b4039
> Switch to async AFBR measurement calls and use schedule.

- boards/px4/fmu-v6c/src/i2c.cpp
Reverts PX4/PX4-Autopilot#19949
This is causing issues with the internal mag marked as external. For not it is better to fail starting devices on the connector marked I2C
FYI: @dagar @julianoes @vincentpoont2
> Revert "px4_fmu-v6c Move I2C 4 to External"

- src/drivers/distance_sensor/ll40ls/LidarLiteI2C.h
The data from the Lidar Lite v3 sensor (read through the pixhawk) is coming only on 20Hz. The [datasheet](http://static.garmin.com/pumac/LIDAR_Lite_v3_Operation_Manual_and_Technical_Specifications.pdf
) states that the sensor does measurement typically on 270 Hz.
> Lidar Lite v3 distance sensor: Increase rate of the driver over I2C to 100Hz

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/navigator/mission_block.cpp
If the current yaw setpoint is valid we should use it to make the transition in this direction. For a VTOL_TAKEOFF the yaw_setpoint is used to specify the transition direction (the vehicle is aligned towards it and then transition is started). The current yaw can be a bit off (e.g. because `MIS_YAW_ERR` is large), and it is better to track the actual setpoint.
Ugly front transition when initial yaw error was large and MIS_YAW_ERR is large as well, as then the vehicle starts the transition e.g. 30° off to the desired transition direction while still yawing to achieve it, and then yaws back to track a heading 30° off to the actual desired transition direction. 
See above.
SITL tested.
> Navigator/FW Position Control: VTOL front towards specified transition heading if available

- src/modules/simulation/simulator_mavlink/SimulatorMavlink.cpp
- src/modules/simulation/simulator_mavlink/SimulatorMavlink.hpp
A simulation should e able to simulate multiple sensors of the same kind. This is implemented for the gps sensors, however, only one imu and magnetometer can be simulated. They are duplicated on the PX4 side.
This PR is coupled to the PR in [sitl_gazebo](https://github.com/PX4/PX4-SITL_gazebo/pull/905), where it is now possible to add multiple imu and magnetometer links. On the PX4 side the handling of the hil_sensor message is updated, where the sensor id in the hil_sensor message is used to determine which imu should currently be updated.
Tested with standard_vtol sitl simulation. Needs more testing.
> Enable multiple simulated imu and magnetometers in gazebo

- src/modules/navigator/mission_block.cpp
- src/modules/navigator/mission_block.h
Loiter exit condition is linked to MIS_YAW_ERR parameter. Beside the fact that loiter exit isn't based on yaw but course, I don't see the necessity to have it based on a parameter (and have it linked to one that does something entirely different, MC waypoint yaw acceptance) is even worse. And by default the value is currently 12°, meaning that the vehicle will leave a loiter 12° too early. Rather a bit high, see examples for center line tracking below. 
So let's make it a constant!
Make the course error for loiter exit condition a constant. Set it to 5°, as a trade off for good tracking of a tangential exit path (if it's too small then the vehicle will overshoot the exit course and needs to come back), and center line tracking (if it's too large then it will quite aggressively turn in to …
> MissionBlock: base loiter course exit condition on a constant value instead of MIS_YAW_ERR

- platforms/common/CMakeLists.txt
- platforms/common/board_identity.c
- platforms/common/board_identity_test.cpp
- platforms/common/include/px4_platform_common/board_common.h
- platforms/nuttx/src/px4/nxp/imxrt/version/board_identity.c
- platforms/nuttx/src/px4/nxp/kinetis/version/board_identity.c
- platforms/nuttx/src/px4/nxp/s32k1xx/version/board_identity.c
- platforms/nuttx/src/px4/rpi/rpi_common/version/board_identity.c
- platforms/nuttx/src/px4/stm/stm32_common/version/board_identity.c
From #20036, it utilizes the `board_get_px4_guid_formated` function for filling in `uas_id` for OPEN DRONE ID MAVLink message, like [here](https://github.com/PX4/PX4-Autopilot/pull/20036/files#diff-9df698b07008acc1a7b23a558fb96d819a88ac3e378bf34602fe5f23a3efe809R163).
This led to the ['Standard VTOL w/ build type AddressSanitizer'](https://github.com/PX4/PX4-Autopilot/blob/main/.github/workflows/sitl_tests.yml#L19) SITL test to fail with Stack Buffer Overflow, as shown below in 'Cause' section.
You can reproduce this bug via:
1. Checkout your branch to the one in #20036 
2. Build SITL with AddressSanitizer enabled: `PX4_ASAN=1 make px4_sitl gazebo HEADLESS=1`
3. The stack overflow error will occur shortly after the SITL starts
`board_get_uuid32_formated` function didn't respect the `size` …
> Board UUID format function wrong memory access bug fix

- src/modules/vtol_att_control/standard.cpp
Port of https://github.com/PX4/PX4-Autopilot/pull/19865 to v1.13
Got noticed about it being broken on 1.13 through https://discuss.px4.io/t/pusher-throttle-pulsing-with-vt-fwd-thrust-en/28994
> standard: fixed pusher assist in hover

- src/drivers/px4io/px4io.cpp
- src/drivers/px4io/px4io.hpp
This PR breaks out a header file from px4io.cpp to improve readability and maintainability.
Bench tested, results are the same as the pr-px4io_dumb_output_module branch
Let me know if you have questions about this PR.
Thanks!
-Mark
> Breakout px4io.hpp and delete unneeded #includes.

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/navigator/mission.cpp
- src/modules/navigator/mission.h
- src/modules/navigator/navigator.h
- src/modules/navigator/rtl.cpp
- src/modules/navigator/rtl.h
- loiter radius and direction of the loiter down in a RTL during a mission landing could differate from loiter radius and direction before mission landing was engaged. 
- loiter (orbits) with negative loiter directions (CCW) were not correctly displayed on the GS
- Orbit status of loiter before landing was not shown until on loiter (as WP wasn't of type Loiter) and vehicle flew through center of loiter down instead of joining it smoothly:
- if RTL is of type RTL_DESTINATION_MISSION_LANDING, then set loiter radius and direction of Descend loiter (where it will descend to RTL_DESCEND_ALT and wait there for RTL_DELAY seconds) to what was set in the mission.
- uint8_t -->int8_t
- for FW flight: already set WP type to LOITER_TO_ALT for state RTL_STATE_RETURN.
SITL (standard VTOL and Plane)
> RTL: some small fixes for fixed-wing/VTOL

- platforms/nuttx/src/bootloader/common/image_toc.c
As the first entry is used to sign / authenticate the ToC, make sure the ToC is actually in the first entry.
Fix a security hole, without this fix the ToC can be manipulated to load malicious code.
Check that the ToC actually is within the signed entry (authenticated).
None
> image_toc.c: Check that the ToC actually lies within the first entry

- ROMFS/px4fmu_common/init.d/airframes/4020_holybro_px4vision_v1_5
- ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt
Add Holybro PX4 vision v1.5 Airframe so user can select it in QGC.
Holybro PX4 Vision v1.5 has some differences from the v1 would require different parameter.
[More info regarding PX4 Vision v1.5 ](https://shop.holybro.com/px4-vision-dev-kit-v15_p1342.html)
> Add Holybro PX4 vision v1.5 Airframe

- msg/tools/generate_microRTPS_bridge.py
If ROS2 is built from source and no system-wise version of `fastrtps` is installed, then the microRTPS generation fails.
In the above situation, `LD_LIBRARY_PATH` is used to search for the version provided by ROS2.
First the exact location of the library is retrieved, then its version is extracted.
Would it make sense to look first for the version provided by ROS2 and only if it fails then to look for the system-wise version?
Tested on Ubuntu 20.04, ROS2 foxy source installed and no other versions of fastrtps available
This method requires the ROS2 environment to be sourced before compiling.
> Fixed fastrtps version reading in microRTPS generation

- platforms/common/include/px4_platform_common/log.h
- platforms/common/include/px4_platform_common/log_history.h
- platforms/common/px4_log.cpp
- platforms/common/px4_log_history.cpp
- src/systemcmds/hist/CMakeLists.txt
- src/systemcmds/hist/Kconfig
- src/systemcmds/hist/hist.cpp
Added a log history to allow the ability to display the px4 log messages through a new "hist" command for posix targets.  Initial version looking for feedback.  
A console_buffer could achieve the same functionality.
Tested on SITL and a posix based flight controller.  Some status and error messages throughout the code base use the printf()s and are not captured in this log history implementation.
This was a follow-up to pr #19851.
> Initial version of log history support.

- platforms/nuttx/src/px4/common/hrt_ioctl.c
- platforms/nuttx/src/px4/common/px4_init.cpp
- platforms/nuttx/src/px4/common/px4_protected_layers.cmake
- platforms/nuttx/src/px4/stm/stm32_common/hrt/hrt.c
- src/drivers/drv_hrt.h
The HRT ioctl is common code, so move it out of chip specific code. Allows other targets to utilize the same ioctl code as ARM / STM32 does.
Move the common code from stm32/xx/hrt.c to a common place.
Copy&paste the same code to every platform
fmuv5 and unpublished Microchip mpfs target
> hrt_ioctl: Move common code under /common folder

- src/modules/navigator/mission.cpp
- src/modules/navigator/navigator.h
- src/modules/navigator/navigator_main.cpp
This brings in a few fixes:
- If a survey was interrupted with an RTL, the drone would have kept doing the pictures doing the RTL. As per @julianoes comment at the time we discussed it: "_When a mission starts capturing images using the MAV_CMD_IMAGE_START_CAPTURE command, it should also stop it again, in case it is stopped early, e.g. with RTL_"
- According to MAVLink specs, when triggering a single photo the Capture ID needs to be incremented the to prevent double captures when a command is re-transmitted (https://mavlink.io/en/messages/common.html#MAV_CMD_IMAGE_START_CAPTURE).
This was not happening for "Hover and capture" waypoints and in general when using TakePhoto with MAVSDK.
A clear and concise description of …
> Navigator: Various fixes for camera trigger interactions

- src/lib/drivers/device/nuttx/I2C.cpp
With drivers like the INA226 running in the background in case of late connect we were issuing I2C_RESET constantly.
> drivers/device/nuttx/I2C: only issue I2C_RESET() if retrying, and only before the next retry

- src/modules/mavlink/CMakeLists.txt
- src/modules/mavlink/mavlink_bridge_header.h
From v1.13.0 PX4 stopped building from a Catkin workspace (with `catkin_make px4`). And we are using such a setup for our simulation environment.
The error:
```
In file included from /home/oleg/catkin_ws/src/PX4-Autopilot/src/modules/mavlink/mavlink.c:46:
/home/oleg/catkin_ws/src/PX4-Autopilot/src/modules/mavlink/mavlink_bridge_header.h:64:10: fatal error: mavlink/mavlink_types.h: No such file or directory
64 | #include <mavlink/mavlink_types.h>
|          ^~~~~~~~~~~~~~~~~~~~~~~~~
```
Seemingly, the include directory is already `~/catkin_ws/build/mavlink`, so `mavlink/` prefix is not needed. And all the other `mavlink_types.h` inclusions in other modules don't prefix it with `mavlink/` directory.
This patch fixes building in a Catkin workspace and doesn't break the normal building (with …
> mavlink: fix path for mavlink_types.h include

- boards/px4/fmu-v6x/src/CMakeLists.txt
- boards/px4/fmu-v6x/src/bootloader_main.c
- boards/px4/fmu-v6x/src/init.c
The PR ensures the PWM pins stay low from power on (in bootloader) until driven
N.B. the PX4IO has a 880 ns pulse on it.
Channels are PX4IO 0-7, FMU 8-15
Master
From power on battery
From power on USB
This PR
From power on battery
From power on USB
> px4_fmu-v6x_bootloader:Ensure PWM pins are low from boot

- src/modules/mavlink/mavlink_main.cpp
Tailsitters need Mavlink message ATTITUDE_QUATERNION  to display properly the horizon in FW mode.
Artificial horizon not pitching down 90º in FW mode because ATTITUDE_QUATERNION message is not being send in Mavlink normal mode.
Add this message to the normal mode at 10Hz
> Tailsitters need ATTITUDE_QUATERNION  to display properly the horizon

- platforms/common/include/px4_platform_common/atomic.h
fetch_add/sub were really inc/dec for the __atomic_always_lock_free == true branch. This fixes them so that the arg "num" is actually used.
Fix the add/sub methods (what they really did was increment/decrement). Don't know if this is a real issue, just noticed that they
do not do what the name implies.
> px4_platform_common/atomic.h: fetch_add/sub were really fetch_inc/dec

- src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.cpp
Attempted fix for small oscillations that occur with `FlightTaskManualAcceleration` when you start or stop moving the sticks and the velocity setpoint is nearly zero.
> flight_mode_manager: StickAccelerationXY minimize setpoint oscillations around zero

- src/modules/simulation/simulator_ignition_bridge/SimulatorIgnitionBridge.cpp
- src/modules/simulation/simulator_ignition_bridge/SimulatorIgnitionBridge.hpp
- ideally we'd get this from the actual joint velocity, but this is good enough to start
> simulator_ignition_bridge: add simple esc_status publication

- boards/px4/fmu-v6c/init/rc.board_sensors
- boards/px4/fmu-v6c/src/board_config.h
- boards/px4/fmu-v6c/src/i2c.cpp
- platforms/common/i2c.cpp
- platforms/common/include/px4_platform_common/i2c.h
- src/lib/drivers/device/nuttx/I2C.hpp
- src/lib/drivers/device/posix/I2C.hpp
- src/lib/sensor_calibration/Utilities.cpp
**This contains two changes:**
1. This swaps the internal baro and mag back to the bus which is both internal an external but configured as external for this case, in the same way as #20151.
2. Also, it adds a hack for fmu-v6c regarding mag calibration: In order for the mag calibration to treat the mag as an internal one, as well as sensors_status_mag and sensors_status_baro to be correct, we need to insert this override to change these two sensors specifically to internal.
FYI @vincentpoont2 
**Tests:**
Mag calibration:
```
...
MAG 396321 EN: 1, offset: [-0.039 -0.009 -0.025], scale: [0.991 1.069 0.981], Internal
```
sensor status topics:
```
nsh> listener sensors_status_mag
TOPIC: sensors_status_mag
sensors_status_mag
timestamp: 233004294 (0.008210 seconds ago)
device_id_primary: 396321 …
```
> Pixhawk 6C external I2C bus hack

- src/modules/control_allocator/ControlAllocator.cpp
Otherwise the 2. setpoint is equal to the first one. This is only an issue if the 2. instance isn't advertised.
This isn't an issue on any of the existing configs.
> fix control_allocator: check if 2. thrust and torque sp topic is valid

- src/modules/vtol_att_control/standard.cpp
- src/modules/vtol_att_control/tailsitter.cpp
- src/modules/vtol_att_control/tailsitter.h
- src/modules/vtol_att_control/tiltrotor.cpp
- src/modules/vtol_att_control/tiltrotor.h
- src/modules/vtol_att_control/vtol_type.cpp
- src/modules/vtol_att_control/vtol_type.h
Just a couple of leftovers that escaped their doom with [the old mixer purging](https://github.com/PX4/PX4-Autopilot/pull/20108).
Plus I noticed that _flag_was_in_trans_mode is defined for all vtol types, but only used for tailsitter, so made it a tailsitter-only member.
> VTOL: remove some remaining pwm stuff

- Tools/px4events/srcparser.py
- Tools/px4events/srcscanner.py
- src/modules/commander/HealthAndArmingChecks/HealthAndArmingChecksTest.cpp
And skip [HealthAndArmingChecksTest.cpp](https://github.com/PX4/PX4-Autopilot/compare/main...pr-cmake_metadata_extract_events_skip_file?expand=1#diff-0acaeaa062a8d2fb0616f25ecceb05995fb02cbc9bec0fd06231115b980911cf) to fix metadata deployment.
Replacement for https://github.com/PX4/PX4-Autopilot/pull/20189
> px4events: add @skip-file tag

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
- src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c
High winds usually come with more turbulence, that make flying in higher winds tricky/the vehicles more prone to stall, especially for vehicles with a low airspeed.
Add option to increase the minimally allowed airspeed setpoint in AUTO flight based on wind speed magnitude. The new parameter is `FW_WIND_ARSP_SC`, and effects the min airspeed like this:
`airspeed_min_adjusted = FW_AIRSPD_MIN + FW_WIND_ARSP_SC * wind.length()`
We should probably have the same logic also running in manual flight modes. I noticed that currently none of the airspeed limit adjustments (for minimal groundspeed, load factor and wind speed) are run in `get_manual_airspeed_setpoint()`. Wonder if we at all need different handling of airspeed, meaning if we need to support still the airspeed setpoint through stick …
> FW Position control: add option to scale min airspeed wtih wind magnitude

- src/modules/navigator/mission_block.cpp
- src/modules/navigator/navigator.h
- src/modules/navigator/navigator_main.cpp
VTOLs use NAV_FW_ALTL_RAD instead of NAV_FW_ALT_RAD to accept backtransititon altitude before a landing.
Only use NAV_FW_ALTL_RAD when not a VTOL or a VTOL without force_vt on.
Also containst a mini refactor by removing the unnecessary function get_default_altitude_acceptance_radius().
> Navigator: use NAV_FW_ALTL_RAD only for FW landings, not VTOL landings

- src/modules/fw_att_control/FixedwingAttitudeControl.cpp
- src/modules/fw_att_control/FixedwingAttitudeControl.hpp
vehicle_rates_setpoint_poll() rotated the rate setpoint for tailsitters from hover to fixes-wing orientation. That is though not correct, as the actual rate estimates get rotated and thus the setpoints shouldn't be touched.
Fixes https://github.com/PX4/PX4-Autopilot/issues/20279
Issue arose with https://github.com/PX4/PX4-Autopilot/pull/20080. Acro was though also broken before it seems, as that one used vehicle_rates_setpoint_poll() already.
> FW Attitude Controller: fix polling of rate setpoint for tailsitter

- src/modules/payload_deliverer/gripper.cpp
- src/modules/payload_deliverer/gripper.h
- src/modules/payload_deliverer/payload_deliverer.cpp
- src/modules/payload_deliverer/payload_deliverer.h
**Bug**: When the payload_deliverer's gripper wasn't configured correctly, the error message was spammed to the user for *any vehicle command received.
**Room for Improvement**: Also, it was hard to check what the status of the payload_deliverer module was (especially the gripper instance)
1. First commit splits out the gripper state update function and only prints out info message when we did indeed receive the `DO_GRIPPER` vehicle command
2. Second commit adds a status output function to show gripper state
Here, with the changes in this PR, the spamming doesn't occur anymore unless an actual DO_GRIPPER command is received, and the status output through the px4 shell gives a verbose status of the gripper, which is very useful for the operator!
> Payload Deliverer bug fix + status output improvements

- boards/px4/fmu-v2/src/i2c.cpp
- boards/px4/fmu-v3/src/i2c.cpp
- platforms/common/i2c.cpp
- platforms/common/include/px4_platform_common/i2c.h
This removes the odd px4_i2c_bus_external override which was confusing me and lead to odd and inconsistent results.
The function is now only available with an int as the argument.
> boards/platform: remove confusing override

- src/modules/ekf2/EKF2.cpp
Don't use synthetic measurements to prevent circular dependency.
https://github.com/PX4/PX4-Autopilot/blob/8080ca966a8a435ba550f4bc8dda39eab20af2fb/msg/airspeed_validated.msg#L12
> ekf2: use validated airspeed from airspeed sensor only

- src/drivers/uavcan/rgbled.cpp
The HERE 3 LEDs are brighter on some colors (yellow purple cyan white).
When connecting two HERE 3 GPS on the same CAN bus, current can be very high (> 500mA), potentially blowing fuses on the power provided on the JST CAN ports on some boards.
This balances the intensities of the different colors. This also reduces power consumption
> uavcan rgbled: Scale brightness for constant illumination

- cmake/px4_parse_function_args.cmake
Better to have this enabled and catch any typos.
> cmake: px4_parse_function_args re-enable failure on unparsed (invalid) arguments

- src/drivers/rc/crsf_rc/CrsfParser.cpp
- src/drivers/rc/crsf_rc/CrsfParser.hpp
- src/drivers/rc/crsf_rc/CrsfRc.cpp
An issue existed in the CSRF driver, where invalid serial data could result in the parser attempting to parse a packet of unknown type, with a length which is larger than the circular buffer itself. This would mean the parser would be stalled waiting for a packet larger than could ever be encountered. This PR fixes this bug to cap the possible unknown packet type size to the maximum size of a CRSF packet.
> CRSF: Validate unknown packet sizes to be smaller than max packet size

- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/ekf_helper.cpp
- src/modules/ekf2/EKF/ev_height_control.cpp
EV odometry handling in the EKF is not considering the reset_counter field for EV height fusion, only horizontal position, velocity, and yaw.
This PR adds the same reset logic from the other estimates to the EV height fusion controller so that the vertical position and velocity estimates are reset upon change in the EV odom message's reset_counter field.
> Adds missing reset counter logic to EV height fusion

- src/modules/navigator/rtl_params.c
It's completely valid to have a RTL_RETURN_ALT of much higher than the current 150m, so I increased it to 1000 here. E.g. for a vehicle flying in hilly/mountainous terrain you would want to set RTL_RETURN_ALT above the highest terrain in the flight area (relative to Home or the safe landing spot defined).
> RTL params: increase max of RTL_RETURN_ALT and improve description

- platforms/common/uORB/ORBSet.hpp
- platforms/common/uORB/uORBManager.cpp
- platforms/common/uORB/uORBManager.hpp
In the recently merged initial VOXL2 support (https://github.com/PX4/PX4-Autopilot/pull/20274) `uORB::Manager::orb_exists()` needed to non-static so that it can check the remote subscribers. This broke the px4_fmu-v5_protected build which has a static orb_ioctl() method kernel side (https://github.com/PX4/PX4-Autopilot/commit/0b9505453d03cb586c2d6e8a927e0b5b5e1761b3).
This PR keeps orb_exists() non-static for VOXL2, but updates orb_ioctl() to call orb_exists() on the uORB::Manager instance (if available). I also updated ORBSet so it's used everywhere, rather than just being a typedef for std::string on Linux. We may want to optimize it later, but for now I think it would be better to keep it together.
> uORB: fix static orb_exists call for protected build

- boards/px4/fmu-v3/init/rc.board_sensors
- boards/px4/fmu-v5x/init/rc.board_sensors
- boards/px4/fmu-v5x/src/board_config.h
- boards/px4/fmu-v5x/src/manifest.c
- boards/px4/fmu-v5x/src/spi.cpp
- boards/px4/fmu-v6x/init/rc.board_sensors
- boards/px4/fmu-v6x/src/board_config.h
- boards/px4/fmu-v6x/src/manifest.c
- boards/px4/fmu-v6x/src/spi.cpp
- platforms/common/include/px4_platform_common/spi.h
> [BACKPORT v1.13] Add Holybro Pixhawk Pi CM4 Baseboard Support

- src/drivers/osd/msp_osd/uorb_to_msp.cpp
When building the ignition SITL on Ubuntu 22.04, the following error occurs:
```
uorb_to_msp.cpp:347:58: error: comparing floating-point with ‘==’ or ‘!=’ is unsafe [-Werror=float-equal]
```
Use `std::isnan` instead.
Local SITL build is now successful:
```make px4_sitl ign_x500```
> Fix uorb_to_msg isnan floating-point check

- ROMFS/px4fmu_common/init.d-posix/airframes/1039_advanced_plane
- ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt
- src/modules/simulation/simulator_ignition_bridge/SimulatorIgnitionBridge.cpp
- src/modules/simulation/simulator_mavlink/sitl_targets_gazebo.cmake
The Advanced Lift Drag plugin (https://github.com/PX4/PX4-SITL_gazebo/pull/901) needs an associated airframe to test it with. While there is a model in that pull request, PX4 does not "see" it by default, and will not compile it. 
@Jaeyoung-Lim has previously opened a pull request for this [here](https://github.com/PX4/PX4-Autopilot/pull/20136), and this pull request is quite similar to that one; the changes between the two are the different parameters for the advanced plane airframe, and the change I made to one of the simulation plugins to make sure it compiles.
This pull request links the model in the …
> Advanced Plane Airframe for SITL Advanced Lift-Drag Plugin

- src/drivers/uavcan/sensors/gnss.cpp
Before this fix, this function would stall and somehow never return.
This makes RTK data sent from QGC work on top of v1.13 for me.
> [v1.13] Fix RTK

- src/lib/hysteresis/hysteresis.cpp
- avoid potential errors with timestamp passed in from different sources
- this wasn't a potential issue originally when hrt_absolute_time() was handled internally
> hysteresis: avoid subtracting unsigned integers

- msg/position_setpoint.msg
- src/lib/l1/ECL_L1_Pos_Controller.cpp
- src/lib/l1/ECL_L1_Pos_Controller.hpp
- src/lib/npfg/npfg.cpp
- src/lib/npfg/npfg.hpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/navigator/mission.cpp
- src/modules/navigator/mission_block.cpp
- src/modules/navigator/navigator_main.cpp
The loiter direction specified in a position setpoint was parametrized using an integer and used directly in calculations which relied on the value being limited to the set  {-1, 1}. This approach is very prone to errors as e..g. a value of 0 would screw up the guidance law completely (If you've ever seen a fixed wing loitering and producing the shape similar to a flower, then you've hit this case).
We now parametrize the loiter direction using a boolean, which avoids unspecified behavior as there are only two options.
Use an enum but I don't see the benefit of doing so as we really don't need more than two options.
> position_setpoint: replaced loiter_direction integer by boolean

- ROMFS/px4fmu_common/init.d-posix/airframes/1040_standard_vtol
- ROMFS/px4fmu_common/init.d-posix/airframes/1041_tailsitter
- ROMFS/px4fmu_common/init.d-posix/airframes/1042_tiltrotor
- src/modules/vtol_att_control/standard.cpp
- src/modules/vtol_att_control/standard_params.c
- src/modules/vtol_att_control/tailsitter.cpp
- src/modules/vtol_att_control/tiltrotor.cpp
- src/modules/vtol_att_control/vtol_att_control_main.cpp
VTOL transition broken in Stabilized for Tiltrotor since https://github.com/PX4/PX4-Autopilot/pull/20257. Reason: In Stabilized mode only the FW attitude controller was running during transitions, and thus there was no virtual mc attitude setpoint recently published. 
~MC Attitude controller: run and publish if vehicle is a MC or a VTOL in MC mode (which includes transitions). Before it was only run in full MC for Tiltrotor and Standard VTOL. The VTOL module does the selection on which virtual setpoint to use in the end (no changes there).~
EDIT: the above proposed doesn't work because it means that both the mc and fw attitude constantly publish rate setpoints, while it should be always only once of them.
New proposal pushed: move "is-recent" check inside the update_transition_state() …
> VTOL: fix transitions in Stabilized

- src/modules/mc_pos_control/MulticopterPositionControl.cpp
- trajectory_setpoint and vehicle_local_position_setpoint used to be the same data type
- we got extremely lucky here that this didn't cause any issues due to all the fields still aligning
> mc_pos_control: fix trajectory setpoint copy

- msg/actuator_controls.msg
The counter wasn't increased when the tilt index was added in https://github.com/PX4/PX4-Autopilot/pull/19329/commits/938c4c6da1d491e1e54b2d8f35ccda22c469fd89. 
Note: the actuator_controls.msg will be replaced by dedicated topics for thrust, torque and special commands (like flaps) very soon.
> actuator_controls.msg: fix NUM_ACTUATOR_CONTROLS (9)

- src/modules/fw_att_control/FixedwingAttitudeControl.cpp
Something we didn't consider in https://github.com/PX4/PX4-Autopilot/pull/20080: In Acro the` att_sp.thrust_body `obviously isn't updated, but is still listened to for filling `_actuator_controls` with.
Fill `_actuator_controls` always with rate_sp.throttle_body, which in turn is set to` att_sp.thrust_body` if in a mode with an attitude setpoint. 
SITL tested.
> FW Attitdue controller: fix throttle in acro (use _rate_sp.throttle_body)

- boards/px4/fmu-v2/init/rc.board_sensors
- boards/px4/fmu-v3/init/rc.board_sensors
> boards: px4_fmu-v2/v3 allow optional mpu9250 probe to fail without error

- src/modules/control_allocator/ControlAllocation/ControlAllocation.hpp
Setting a non-zero control surface trim on vehicles with control allocation leads to non-working Integral part of the PID controller of the FW rate controller.
Reason: the fed back "allocated_torque" contains the torque generated by the trim as well, which means that "unallocated torque" is never 0, which then prevents the I-part from growing (in the corresponding direction, so either + or -).
Only happens since https://github.com/PX4/PX4-Autopilot/pull/19912 is in, as from then on we listen to the unallocated torque info for disabling the integrator to avoid integrator windup due to actuator saturation.  
Subtract the trim value from the actuator setpoint to get to the "net" actuator setpoint. 
Can we move the trim setting from the allocation to the output part? So e.g. for PWM servos …
> ControlAllocation: remove actuator trim value from actuator_sp to calculate allocated control

- src/modules/vtol_att_control/standard.cpp
So that the sum of the control is always 1.
> vtol_att_control: standard: also do blending for FW controls

- src/drivers/barometer/ms5611/ms5611.cpp
This prevents publishing a negative pressure which leads to a NAN altitude estimate further down the line.
This was discovered on the Holybro Pixhawk 6C where the ms5611 is connected via I2C, and using the release/1.13 branch.
I suspect the measuring and collecting is a bit out of whack initially which leads to this from what I can see in the console right after startup:
```
ms5611 #0 on I2C bus 4 (external) address 0x77
486836: measure(), phase: 0
ist8310 #0 on I2C bus 4 (external) address 0xC
WARN  [SPI_I2C] ist8310: no instance started (no device on bus?)
507538: collect(), phase: 0
nsh: icm20948_i2c_passthrough: command not found
522745: measure(), phase: 1
546096: collect(), phase: 1
failed
551336: collect(), phase: 1
failed
557794: collect(), phase: 1
failed
565867: collect(), …
```
> ms5611: ignore reading 0

- msg/telemetry_status.msg
- msg/vehicle_status.msg
- src/modules/commander/Commander.cpp
- src/modules/commander/Commander.hpp
- src/modules/mavlink/mavlink_main.cpp
- src/modules/mavlink/mavlink_messages.cpp
- src/modules/mavlink/mavlink_receiver.cpp
- src/modules/mavlink/mavlink_receiver.h
- src/modules/mavlink/streams/OPEN_DRONE_ID_BASIC_ID.hpp
- src/modules/mavlink/streams/OPEN_DRONE_ID_LOCATION.hpp
Minimal Mavlink support for OPEN_DRONE_ID_BASIC_ID and OPEN_DRONE_ID_LOCATION continued from https://github.com/PX4/PX4-Autopilot/pull/20036.
I'd like to get this in immediately to enable wider testing. I ended up rewriting most of OPEN_DRONE_ID_LOCATION to use vehicle_gps_position directly, which seemed more appropriate in this particular context.
For the normal Mavlink mode I kept the rate quite minimal to not interfere, but we can raise it later if needed.
FYI @ThomasDebrunner @Igor-Misic @BluemarkInnovations
> mavlink: initial OPEN_DRONE_ID_BASIC_ID/OPEN_DRONE_ID_LOCATION support

- src/drivers/actuators/modalai_esc/modalai_esc.cpp
Per usage feedback in the field, use the "turtle mode dead band" value instead of converting it to RPM
> modalai_esc - directly using deadband param value instead of converting it to RPM

- src/modules/commander/Commander.cpp
- src/modules/commander/commander_helper.cpp
- src/modules/commander/commander_helper.h
Reported via Discord by @PierceNichols:
> So, an issue I have been having with my project is that the commander module never shows a boat as landed. Therefore, it refuses to disarm in response to the arming switch mapped from the RC controller and can only be disarmed through QGC. 
> For my own project, I made a one-line change to the is_ground_rover() function in src/modules/commander/commander_helper.cpp so that it returns true for both ground rovers and boats instead of just ground rovers. Would this be an acceptable patch to submit?
https://discordapp.com/channels/1022170275984457759/1026905600241696819/1026966402378248224
I extend this hack to boats: https://github.com/PX4/PX4-Autopilot/commit/98dfa30838f78dfe74f903e26be9e0050578ee4a
We need to fix land detection and its dependencies …
> Commander: allow disarmin not-landed boat like rover

- src/modules/sensors/vehicle_gps_position/gps_blending.cpp
- src/modules/sensors/vehicle_gps_position/gps_blending_test.cpp
- output GPS publication defaults to best input instance (so we capture all misc fields like jamming state, etc)
- blended states are explicitly cleared and then populated with weighted blend
> gps_blending: fix blending init to best instance

- src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
I am seeing the auto mag cal not updating ever. Examine the logs, it appears that the Z bias variance is always much higher than X and Y, which will cause the valid check to fail.
Increasing the max variance to 500 allows most of these flights to be in the valid range after about 4 minutes of flying. 
Maybe we need to have different limits for XY and Z.
> Increase mag calibration max_var_allowed

- src/modules/commander/commander_params.c
This might be controversial, but this preflight check often reports false positives that aren't actually going to be problematic in real operation.
In my mind this check is mainly for catching blatant setup problems like a magnetometer that's mounted 90 or 180 degrees off.
> commander: relax COM_ARM_MAG_ANG default to minimize false positives

- src/modules/mavlink/streams/LOCAL_POSITION_NED.hpp
There is no mavlink message `LOCAL_POSITION_NED` published when v_xy or xy of the local_position get invalid. E.g. after a GNSS failure. The vertical states (vz and z) can though still be fairly well estimated (baro), so not the whole message should be stopped from being published. 
This message can e.g. be used by the groundstation to display the current relative altitude. 
Remove validity checks, always publish the message.
- Granular checks for xy, z, v_xy, v_z and only fill valid fields. Set others to NaN?
- use other mavlink message for relative altitude. E.g. could be added to VFR_HUD (currently only has AMSL). Or be calculated using AMSL-Home.alt (though what to display then when Home is not valid..)
> mavlink local_position_ned: always publish on update, not just when xy and v_xy valid

- Tools/module_config/output_groups_from_timer_config.py
- boards/nxp/fmurt1062-v1/src/board_config.h
- boards/nxp/fmurt1062-v1/src/timer_config.cpp
- platforms/nuttx/src/px4/nxp/imxrt/include/px4_arch/io_timer.h
- platforms/nuttx/src/px4/nxp/imxrt/include/px4_arch/io_timer_hw_description.h
- platforms/nuttx/src/px4/nxp/imxrt/io_pins/io_timer.c
This pulls in https://github.com/PX4/PX4-Autopilot/pull/20387 and changes the IMX code to work with Control allocation
This treats each channel as a group and therefore can set the rates per channel
> NXP IMXRT nxp_fmurt1062-v1 Support 1 channel per Timer (Group)

- src/modules/fw_att_control/fw_att_control_params.c
The trigger for this PR was looking at the [this flight](https://review.px4.io/plot_app?log=1bc95f58-ae0a-4267-a34b-20ecfba43a73), where the yaw integrator is very often at the limit. Further, I had it now a couple of times that I had to "force save" tuning parameters because they were slightly outside of the (seemingly quite random and rather tight) constraints. So I propose to loosen the constraints a bit.
See commits.
FYI @chris1seto
> FW rate controller gains: open up constraints and change defaults for IMAX

- src/modules/logger/logged_topics.cpp
- src/modules/sensors/vehicle_optical_flow/VehicleOpticalFlow.cpp
- src/modules/sensors/vehicle_optical_flow/VehicleOpticalFlow.hpp
We also should maybe allow a few messages to slip when the gyro is running at a high rate compared to the sensors optical flow module.
> Only get gyro if delta angle not available

- src/modules/sensors/vehicle_optical_flow/VehicleOpticalFlow.cpp
- in the worst case scenario printing the error message can take longer than the next gyro publication, so combined with an infinite loop you could get stuck here
> sensors/vehicle_optical_flow: limit gyro updates and generation lost error per cycle

- src/modules/mavlink/mavlink_main.cpp
- src/modules/mavlink/streams/COMMAND_LONG.hpp
- src/modules/navigator/navigator_main.cpp
- src/modules/temperature_compensation/TemperatureCompensationModule.cpp
- this is a precaution to eliminate the possibility of getting stuck in a loop trying to keep up with a high rate publication that could be coming from a higher priority task
> limit vehicle_command subscription updates per cycle

- msg/position_setpoint.msg
- src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
- src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.hpp
- src/modules/navigator/loiter.cpp
- src/modules/navigator/mission.cpp
- src/modules/navigator/navigator_main.cpp
Remove some unused fields from the position_setpoint message, plus delete _getTargetVelocityXY() that relied on some of them, but wasn't used anywhere. 
Once we clean up the offboard interface for FW a bit, also the vx, vy, vz can go I hope, as they're anyway [just copied now from the trajectory_setpoint input](https://github.com/PX4/PX4-Autopilot/blob/8545164869479486ec68e78a1ae887a10babd7fb/src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp#L2124-L2171).
> position_setpoint.msg: remove some unused fields

- src/modules/flight_mode_manager/FlightModeManager.cpp
- src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.cpp
- src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.hpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/land_detector/MulticopterLandDetector.cpp
- src/modules/land_detector/MulticopterLandDetector.h
- src/modules/mavlink/mavlink_receiver.h
- src/modules/mc_pos_control/MulticopterPositionControl.cpp
- src/modules/mc_pos_control/MulticopterPositionControl.hpp
- src/modules/mc_pos_control/PositionControl/PositionControl.cpp
- src/modules/mc_pos_control/PositionControl/PositionControl.hpp
- src/modules/mc_pos_control/PositionControl/PositionControlTest.cpp
- src/modules/mc_pos_control/Takeoff/Takeoff.hpp
In https://github.com/PX4/PX4-Autopilot/pull/19622 I separated out the `trajectory_setpoint` to being a completely different uORB message instead of the same message like `vehicle_local_position_setpoint` but just a different topic. The issue is that I did not do it cleanly and it only went "well" because the two messages align in memory.
@dagar found one instance where it was done incorrectly here: https://github.com/PX4/PX4-Autopilot/pull/20324
@sfuhrer asked me about another instance in the land detector
I went through the code with a full-text search and made sure there is never a copy or update into a `vehicle_local_position_setpoint_s` from a `trajectory_setpoint` topic. While I was at it I properly switched the position controller to use `trajectory_setpoint_s` as input and …
> Fix confusion between trajectory_setpoint and vehicle_local_postion_setpoint

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
Offboard position setpoints (`local_ned_position_target`) allows you to send feedforward acceleration messages. For fixedwing vehicles, this gets translated into curvature (or loiter radius of position_setpoint_triplet)
Previously when acceleration feedforward inputs were sent, negative curvature accelerations were always being considered as positive curvature (loiter radius > 0.0). Therefore the tracking performance was bad when the curvature was negative.
This Fixes the loiter radius computation to also include negative radius
> Fix feedforward acceleration setpoints for fixedwing offboard position

- src/modules/airspeed_selector/airspeed_selector_main.cpp
Thanks for raising @bresch 
No wind sideslip-only-wind estimate on planes.
`_vehicle_status.vehicle_type == vehicle_status_s::VEHICLE_TYPE_FIXED_WING` instead of `vtol_status`. 
While on it I also removed a redundant check for armed (check for landed is enough) and in another check swapped the check for if(armed) to if(!landed). 
I briefly tried to further clean up/simplify the current if(landed), if(fixed-wing-flight), if(in-takeoff-condition) mess, but it's not that easy. I feel like most efficiently we should try to improve the fixed-wing land detector. If we centrally are good in land detection we can use it system wide without all these extra checks. Currently it though detects takeoff way too early and landing too late. Maybe we could use the "groundcontact" flag (isn't implemented …
> airspeed_selector: update wind estimator (w/o airspeed fusion) always if in FW mode

- boards/px4/fmu-v6c/src/board_config.h
- boards/px4/fmu-v6c/src/manifest.c
The I2C connector has been moved to I2C2 on Rev 1 of the px4_fmu-v6C
> px4_fmu-v6C:Add Revision 1 to manifest to note I2C4 is only internal

- src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.cpp
Some of this can be more flexible in the future, but for now let's at least minimize the distraction.
> commander: limit some estimator checks to prearm

- src/modules/commander/Commander.cpp
- src/modules/commander/HealthAndArmingChecks/Common.cpp
- src/modules/commander/HealthAndArmingChecks/HealthAndArmingChecks.cpp
- src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.cpp
- avoid the possibility of unsigned underflow from subtracting 2 HRT timestamps (uint64_t)
- most of these aren't problematic, but people tend to replicate the pattern, so it's better to be safe
- likely wasn't a problem when people were using hrt_absolute_time() in place, but if using an existing timestamp there's the possibility it's older than a more recent topic update
> commander: elapsed time checks avoid subtracting unsigned integers

- cmake/px4_add_common_flags.cmake
- platforms/nuttx/cmake/px4_impl_os.cmake
- platforms/posix/cmake/px4_impl_os.cmake
Fix for build failures on the Qurt platform.
Moved the bad-function-cast compiler warning option out of the common options and into the nuttx and posix specific options files since this option cannot be used with the qurt platform. There are header files in the hexagon sdk that fail this check.
> Moved the bad-function-cast compiler warning option out of the common options

- src/lib/wind_estimator/WindEstimator.cpp
- src/lib/wind_estimator/WindEstimator.hpp
We had a wind estimator filter reset on a VTOL with low yaw stability (causing it to side-slip quite often) that then a bit later in the flight triggered an airspeed failure because the wind estimate was then re-initialized to very wrong values (due to a high slip angle during initialization). 
The reset happened during a very dynamic flight phase where the side slip angle was high (looking at COG and yaw and the previously estimated wind), and was triggered as the beta_innovations were not fused for more than 5s (threshold for beta fusion, with gate=1 and innov_variance=0.09 is 0.3). 
Remove the filter re-init after 5s not fusing beta. I'm yet to see a case where the wind estimator got so out of hands that it needs to be reset because even in normal flight conditions (without a lot of …
> Wind Estimator: remove filter reset due to beta fusion timeout

- msg/Gripper.msg
- src/modules/fw_att_control/fw_att_control_params.c
- src/modules/simulation/simulator_sih/sih.cpp
There are params and uorb topics that refer to mixer or mixer/or allocation. I'm trying to update our docs to refer to control allocation wherever this is "no worse" in order to create a cleaner break between mixer and control allocation documentation.
> params/uorb dos - mixer to control allocation

- src/modules/navigator/rtl.cpp
- src/modules/vtol_att_control/vtol_att_control_main.cpp
- src/modules/vtol_att_control/vtol_att_control_main.h
When experimenting on an improved front transition tracking (for which I hope to be able to present a PR soon), I realised that it would make more sense to abort the front transition when an RTL is triggered during the transition. Like this you switch back to MC mode immediately and fly back to the RTL point directly instead of finishing the transition then U-turning to finally do the back transition again before landing.
Send a back transition command if RTL is activated during a front transition.
\-
SITL gazebo_standard_vtol: https://logs.px4.io/plot_app?log=5126b6cf-6e74-4e82-ae1e-74513e057027
To compare, this is how it behaves on current main: https://logs.px4.io/plot_app?log=cd083ce8-4b1e-4bde-b4a8-91d87266ec83
I also modified slightly how the return altitude is calculated. If the …
> [VTOL] Abort front transition if RTL is activated during transition

- src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.cpp
- otherwise these are awkwardly split in mavlink
> commander: estimator check shorten messages

- platforms/qurt/include/qurt_log.h
- src/modules/muorb/slpi/uORBProtobufChannel.cpp
This PR is meant to allow for PX4_INFO and other logging functions (err, warn, etc.) to be used by qurt and to be outputted onto mini-dm -- FUTURE will require string being passed into PX4_INFO to be sent over to apps side to be printed out by px4 shell.
Implemented a qurt_logger that leverages a hex function called HAP_debug - this function is in charge of printing out strings on mini-dm. This was then abstracted out to a function called qurt_log which was then leveraged in log.h.
Currently this is the best possible route. Only other implementation that needs to happen is for these strings to be sent over to the apps side via a uorb communicator which would then be printed out on PX4 shell.
This was tested using mini-dm and the muorb protobuf code base that runs on the slpi.
> Qurt Logger Implementation

- Jenkinsfile
Fixes the error:
```
Error: tar (child): xz: Cannot exec: No such file or directory
```
> Jenskinsfile: use nuttx container as emscripten requires xz to be installed

- src/modules/payload_deliverer/gripper.cpp
- src/modules/payload_deliverer/gripper.h
- src/modules/payload_deliverer/module.yaml
- src/modules/payload_deliverer/payload_deliverer.cpp
- src/modules/payload_deliverer/payload_deliverer.h
This fixes multiple problems found when integrating the interface with the Ground Control Station (abbreviated below as **GCS**) on directly commanding the gripper via [Joysticks](https://docs.qgroundcontrol.com/master/en/SetupView/Joystick.html) Button assignment.
- [GRIPPER_ACTION](https://mavlink.io/en/messages/common.html#GRIPPER_ACTIONS) Enum being sent by GCS was being encoded in the `param2` in `MAV_CMD` in floating point, so the value `1` (ACTION_GRAB) was not being converted correctly into the `int32_t` type
- Gripper instance was publishing `gripper` message every-time user was commanding Gripper command via GCS, this was spamming the Gripper Control Allocator
- Payload deliverer was not sending the 'IN_PROGRESS' ack to GCS, so GCS was detecting a link failure in vehicle …
> Payload deliverer improvements: Gripper intermediate state & Vehicle command Ack & Parameter Updates

- src/modules/navigator/mission.cpp
- src/modules/navigator/mission_block.cpp
- src/modules/navigator/mission_block.h
- src/modules/navigator/navigator_main.cpp
- src/modules/navigator/navigator_mode.h
This is to address what was reported here: https://github.com/PX4/PX4-Autopilot/pull/19928#issuecomment-1277934841
What I think was going on:
- RTL triggered a couple of times, and each time it was above the return altitude, so didn’t have to climb. In the v1.13 RTL logic, as pointed out [here](https://github.com/PX4/PX4-Autopilot/pull/19928#issuecomment-1284454859), the mission_item.loiter_radius field wasn't filled, and it just kept using it as initialized. 
- The initialization happens in the constructor, and it initializes it to `_navigator->get_loiter_radius()`, which itself just gets the value of `_param_nav_loiter_rad`. At this moment, the params are though not yet fetched (happens [here](https://github.com/PX4/PX4-Autopilot/blob/c267cf71c3aa57fbbe544d02f3b25650f029384d/src/modules/ …
> Navigator: fix init of _mission_item, plus add guards for using mision_item.loiter_radius

- src/modules/navigator/navigator_main.cpp
Fixes https://github.com/PX4/PX4-Autopilot/issues/20477
See https://github.com/PX4/PX4-Autopilot/issues/20477
Remove reposition hacks from logic handling of DO_TRANSITION. This was previously required to reset the flight speed after a VTOL transition, but is now no longer required as the DO_CHANGE_SPEED commands are handles directly in the controllers.
SITL testing (standard vtol)
Originally introduced here: https://github.com/PX4/PX4-Autopilot/pull/18834#issuecomment-996595040, then the DO_CHANGE_SPEED handling was changed with https://github.com/PX4/PX4-Autopilot/pull/19407 but it looks to me like this specific part was overseen and is not required anymore.
BTW I think DO_SPEED_CHANGE is currently broken for MC in AUTO modes (at least for Goto). For FW it works. FYI @MaEtUgR 
FYI …
> Navigator: remove update of reposition setpoint at Transition command

- src/modules/navigator/mission_block.cpp
- src/modules/navigator/mission_block.h
- src/modules/navigator/navigator_main.cpp
- src/modules/navigator/navigator_mode.h
Backport of first commit of https://github.com/PX4/PX4-Autopilot/pull/20464.
> [Release port 1.13] Navigator: fix init of _mission_item

- src/modules/fw_att_control/FixedwingAttitudeControl.cpp
There is a corner case where, if in an auto mode that sets a reset command on the attitude setpoint message (e.g. auto takeoff), if the mode was then switched stabilized, this reset bool would never be changed back to false and the integrators would reset every cycle.
this commit initializes them to false on the manual setpoint poll where they otherwise weren't explicitly set
> fw rate control: initialize rate control resets to false in stabilized mode

- src/drivers/imu/invensense/icm20649/InvenSense_ICM20649_registers.hpp
- src/drivers/imu/invensense/icm42670p/InvenSense_ICM42670P_registers.hpp
This fixes two errors where CLion complains:
```
error: 'size_t' does not name a type
```
> drivers: fix two includes for CLion

- src/modules/commander/Commander.cpp
- src/modules/commander/commander_helper.cpp
- src/modules/commander/commander_helper.h
Waypoints were not getting accepted since the altitude of the vehicle was being considered for accepting a waypoint.
However, boats are ground vehicles where an altitude of a waypoint is not used.
This corrects the waypoint handling logic to consider boat type vehicles as ground vehicles.
Tested in SITL with https://github.com/PX4/PX4-Autopilot/pull/20082
- This PR is a follow up of https://github.com/PX4/PX4-Autopilot/pull/20363
- Fixes https://github.com/PX4/PX4-Autopilot/issues/19045
> Handle waypoint altitude acceptance radius correctly for boats

- src/systemcmds/hardfault_log/hardfault_log.c
I believe the addresses in the stack dump of the hardfault logs are wrong.
```
...
0x2003f129 0x403c5ab6
0x2003f128 0xa619da9c
0x2003f127 0x3a83126f
...
```
The addresses increment by 1, but we print a full word on each line. This is impossible, since arm is byte-addressed and the values are non-repeating. 
The addresses are generated in the `hardfault_log` code, anchored at the `sp` locations. So the line annotated with `<-- User sp` and `<-- Interrupt sp` are correct, all the other addresses wrong. 
This makes the function use an increment of 4 isntead of 1. This should fix the addresses
Tested on pixhawk 4 
This bug had the effect that the `<-- Interrupt sp top` etc annotations were wrong. After the fix, they nicely align with what you'd expect:
```
...
0x200210cc 0x00000000
0x200210c8 …
```
> hardfault_log: Correctly annotate stack addresses

- platforms/qurt/cmake/px4_impl_os.cmake
- platforms/qurt/include/px4_arch/micro_hal.h
- platforms/qurt/include/qurt_reqs.h
- platforms/qurt/include/sys/ioctl.h
- platforms/qurt/src/px4/CMakeLists.txt
This PR is meant to tie in Work Queue into the qurt environment.
Firstly we created a micro_hal place holder to remove the dependency associated to it. Secondly, this usleep is not defined in the unistd.h file within the Hexagon SDK, we created a qurt_reqs file with the declarations and then made them included headers in every file during compilation via the cmake edit.
There are no other alternative implementations, only thing is that as we move further in the implementation of other things, micro_hal will have to be converted from a placeholder to legitimate code.
Tested via the muorb module with some usleeps and work_queue code to ensure proper running
> Qurt work_queue Implementation

- msg/CMakeLists.txt
- msg/LandingGearWheel.msg
- msg/VehicleAttitudeSetpoint.msg
- src/lib/mixer_module/functions/FunctionLandingGearWheel.hpp
- src/lib/mixer_module/mixer_module.cpp
- src/lib/mixer_module/mixer_module.hpp
- src/lib/mixer_module/output_functions.yaml
- src/modules/fw_att_control/FixedwingAttitudeControl.cpp
- src/modules/fw_att_control/FixedwingAttitudeControl.hpp
- src/modules/fw_att_control/fw_att_control_params.c
- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/logger/logged_topics.cpp
- src/modules/mc_pos_control/PositionControl/PositionControlTest.cpp
Adds a new message for ferrying steering wheel control from FW attitude controller to Allocation, and a new function to add it there to an output. 
SITL and bench tested briefly. Couldn't properly test the wheel controller though, as SITL isn't accurate enough for it.
> Fixed-wing steering wheel control rework

- msg/VehicleAttitudeSetpoint.msg
- msg/VehicleRatesSetpoint.msg
- src/modules/fw_att_control/FixedwingAttitudeControl.cpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/mc_pos_control/PositionControl/PositionControlTest.cpp
Attitude setpoints contains a `reset_rate_integrals` field, meaning that the attitude setpoint includes flags for the rate controller. This was fine since the `fw_att_controller` module contained both attitude and rate control functionalities. 
However, with https://github.com/PX4/PX4-Autopilot/pull/20237, we want to separate rate control and attitude control for fixed wings, and therefore the integral reset information needs to be propagated through a message.
Add a `reset_integral` message was added on both `vehicle_attitude_setpoints` and `vehicle_rate_setpoints` in order to make the interface between the attitude and rate controller cleaner
We could make the `reset_integrals` message a 3-dimensional field so that we can reset each axis of the integrator individually
Tested in SITL
``` …
```
> FW separate reset integrals for attitude and rate setpoint messages

- src/systemcmds/ver/ver.cpp
It might not be completely clear what FW is. PX4 is unmistakable.
> ver command: clarify PX4 version instead of FW version

- Tools/px_uploader.py
This changes allows for the px_uploader script to take multiple binaries and chose the correct one to flash among them. E.g. a v5x and a v6x binary can be provided and px_uploader verifies through the bootloader which one to flash.
> px_uploader: Allow for multiple firmware files

- msg/VehicleLandDetected.msg
- src/modules/land_detector/LandDetector.cpp
- src/modules/land_detector/LandDetector.h
- src/modules/land_detector/MulticopterLandDetector.cpp
- src/modules/land_detector/MulticopterLandDetector.h
- src/modules/land_detector/land_detector_params_mc.c
- src/modules/mc_pos_control/mc_pos_control_params.c
1) vertical speed threshold for land detection very low, plus complex to tune. The threshold is currently:
`min(0.9 * max (MPC_LAND_CRWL, 0.1) * 0.5, LNDMC_Z_VEL_MAX)`, which with the default values is 0.9x0.5x0.3m/s = 0.135m/s, so about 4 times lower than `LNDMC_Z_VEL_MAX and means that `LNDMC_Z_VEL_MAX` is not at all considered (breaking [the documentation of the land detector](https://docs.px4.io/main/en/advanced_config/land_detector.html#ground-contact) .
2) rotational movement (that is checked for land detection) not logged
3) pre-emptive "takeoff" detection during auto takeoff due to motor spool up triggering rotational movement to be above threshold
1) MC LandDetector: remove dependency on `MPC_LAND_SPEED` and `MPC_LAND_CRWL`
Don't consider these params for vertical speed …
> MC Land Detector: try to make simpler to tune and less likely to detect early takeoffs, plus improve logging

- msg/ControlAllocatorStatus.msg
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectiveness.hpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessHelicopter.cpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessHelicopter.hpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessRotors.cpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTiltrotorVTOL.cpp
- src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTiltrotorVTOL.hpp
- src/modules/control_allocator/ControlAllocator.cpp
Addresses https://github.com/PX4/PX4-Autopilot/issues/20395
There is very often some left over (unallocated) yaw torque, even though the tilts are not saturating. Reason is that when the tilts are used for yaw control, they are meant to move symmetrically to the front and back, but back is limited and thus there is some leftover torque not allocated. 
- in `ControlAllocator::publish_control_allocator_status()` always fill allocated/unallocated torque from matrix, then allow them to be overwritten by custom `getAllocatedAndUnallocatedControl() `implementation (specific for effectiveness type)
- add `actuatorEffectivenessTiltrotorVTOL::getAllocatedAndUnallocatedControl()` that only affects the yaw unallocated torque of matrix 0 (titls). Set `unallocated_torque[2] `corresponding to if the …
> ControlAllocation: implement custom saturation logic for tilt-for-yaw actuation

- ROMFS/px4fmu_common/init.d/airframes/4020_holybro_px4vision_v1_5
This is required in v1.13. As found by @vincentpoont2 in https://github.com/PX4/PX4-Autopilot/pull/20244#issuecomment-1281766937.
> [Release 1.13 fixup] Holybro PX4Vision: Don't use IO

- boards/px4/fmu-v6c/src/board_config.h
- boards/px4/fmu-v6c/src/manifest.c
> [BACKPORT v1.13] px4_fmu-v6:Add Revision 1 to manifest to note I2C4 is only internal

- ROMFS/px4fmu_common/init.d-posix/airframes/10042_xvert
- ROMFS/px4fmu_common/init.d-posix/airframes/1041_tailsitter
- ROMFS/px4fmu_common/init.d/airframes/1102_tailsitter_duo_sih.hil
- src/lib/parameters/param_translation.cpp
- src/modules/vtol_att_control/tailsitter.cpp
- src/modules/vtol_att_control/tiltrotor.cpp
- src/modules/vtol_att_control/vtol_att_control_params.c
- src/modules/vtol_att_control/vtol_type.h
For tailsitter VTOLs, motors are not used for attitude control in fixedwing mode. This is because of the distinction between control surfaces and motor controls being enabled / disabled depending on whether the vehicle is in fixed wing or multicopter mode.
This commit enables motor controls in fixed-wing mode for tailsitters. This is enabled when `VT_FW_DIFTHR_EN` is enabled on a tailsitter. This is needed for enabling control surface-less quad tailsitters (https://github.com/PX4/PX4-Autopilot/issues/19747)
This feels like a hack and would be great if we can discuss how bad this hack is :sweat_smile:  @sfuhrer @tstastny 
IMHO, it would be better if this comes implicitly from the geometry of the control allocation framework. However, vehicle geomtetry doesnt seem to propagate back to …
> Enable motor controls for tailsitter VTOLs in fixed wing mode (enable Quad Tailsitters)

- src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
The preflight mag bias estimate is in the vehicle body frame and removed from the raw mag data after it's rotated, calibrated, etc.
The in flight mag bias (from ekf2) is in the vehicle body frame, but stored as a sensor frame offset immediately.
> vehicle_magnetometer: fix standalone mag bias est factored into in flight mag cal

- test/mavsdk_tests/autopilot_tester.cpp
- test/mavsdk_tests/autopilot_tester.h
Previously, due to the way MAVSDK's `health_all_ok` was implemented, vehicle often didn't have a valid global position estimate (although function returned true), and it wouldn't arm, and the SITL would fail. This was originally reported here: https://github.com/mavlink/MAVSDK/issues/1852#issue-1302090147
Also sometimes as vehicle didn't have manual control, it entered weird states where it wasn't able to arm as well.
In `wait_until_ready()`, wait until we are able to arm, after checking system health. This ensures that `tester.arm()` in mavsdk tests will succeed, since we know we will be able to arm, and SITL tests will not fail just because it can't arm.
Standard VTOL mavsdk tests succeeded in local environment (wow it is slow when we don't have time factor!).
Related: …
> Mavsdk test: Make `wait_until_ready` also wait until vehicle can arm

- src/drivers/osd/msp_osd/msp_osd.cpp
@hamishwillee mentioned the msp_osd documentation needed a bit of work. In preparation for that, I wanted to clean up the previously nondescriptive help strings in the msp_mosd module.
> Clean msp_osd help string and debug message

- platforms/common/spi.cpp
This was temporarily broken as the HW_VER_REV changed from 8  to 16 bit. To avoid such issues if the function is ever changed again, we should use the actual function here instead of hardcoding it.
> SPI: use official HW_VER_REV function

- src/modules/commander/HealthAndArmingChecks/checks/rcAndDataLinkCheck.cpp
A small fix to avoid GCS connexion errors sent through Mavlink log publisher when it is not required.
> fix warning (mavlink): connection to gcs

- src/modules/land_detector/MulticopterLandDetector.cpp
- src/modules/land_detector/MulticopterLandDetector.h
Follow-up to https://github.com/PX4/PX4-Autopilot/pull/20425#discussion_r1006948037
Logged `vehicle_land_detected.rotational_movement` is not always correct because of the early returns. Early returns are in my eyes toxic for the readability of such kind of logic anyways.
Refactor removing all early returns. I find it more readable now and am convinced it's easier to improve further.
I did a quick SITL test. Please review thoroughly. I'm happy to walk any volunteer through it in detail.
> MulticopterLandDetector: refactor maybe_landed condition

- src/lib/avoidance/ObstacleAvoidance.cpp
- src/lib/avoidance/ObstacleAvoidance.hpp
1. If the obstacle avoidance input _from the mission computer_ switches from waypoints to bezier points, `if (avoidance_point_valid)` stays true and the interface _in PX4_ never switches to bezier points.
2. The OA interface is set to fail if it does not receive a waypoint message for more than 500ms. This means it fails _as soon as the flight mode changes_ from a manual mode to an auto mode. In this case it would arm, but then switch to Loiter and out of the desired auto mode (e.g. Mission or Take-off).
1. The interface switches to handling bezier points of the waypoint stream times out.
2. The interface can only fail if there's a timeout _and_ it has already received at least one waypoint message. It will be in a 'waiting' state until the first message is received.
Tested in simulation …
> Avoidance interface: timeout and initialisation fixes

- src/modules/ekf2/EKF/estimator_interface.cpp
- buffer at least 2 samples for the IMU (and output predictor buffers) and observation buffers
- dropping below 2 becomes problematic for the minimum observation interval calculation and the vertical output buffer trapezoidal integration
Arguably the real (potential) issue here is that the EKF delayed time horizon configuration isn't factoring in the difference between the timestamp and timestamp_sample in many of the incoming data sources. So for now we'll at least have this minimal protection.
The longer term solution will be monitoring incoming data sources and determining an appropriate delay for each that factors in the timestamp_sample delay initially.
> ekf2: ensure minimum output buffer sizing

- src/modules/mc_pos_control/MulticopterPositionControl.cpp
MulticopterPositionControl: fix amending existing idle setpoint from before takeoff once the rampup starts. The rampup requires a valid vertical velocity setpoint.
The corner case is:
- We are before takeoff and amending the setpoint to be 0,0,100 acceleration in order to idle
- The rampup starts BUT the setpoint is not yet overwritten by the trajectory setpoint topic
- The idle setpoint gets amended to not contain a feed-forward vertical acceleration because the rampup is velocity based
- The result is a brief invalid 0,0,NAN acceleration setpoint
- That invalid setpoint gets overridden by a failsafe that holds zero velocity
- Zero velocity leads to applying ~hover thrust briefly
I check if there's a valid vertical velocity setpoint which is required for the takeoff ramp and only then …
> Fix invalid setpoint in most takeoffs

- Tools/px4airframes/markdownout.py
- Tools/px4airframes/rcout.py
- Tools/px4airframes/srcparser.py
- Tools/px4airframes/xmlout.py
- Tools/px_process_airframes.py
As discussed in the Actuators Document Improvement PR in User Guide: https://github.com/PX4/PX4-user_guide/pull/1858#discussion_r876554728, **the current airframe reference document doesn't separate out the airframes accurately.**
For example, the 'VTOL Tiltrotor' [Airframe Reference](http://docs.px4.io/master/en/airframes/airframe_reference.html#vtol-tiltrotor) has a **6-rotor VTOL diagram that doesn't match with the E-Flite Convergence, that is currently under the same "type" in the doc.**
1. Add more @type categories to the [Airframe files](https://github.com/PX4/PX4-Autopilot/tree/master/ROMFS/px4fmu_common/init.d/airframes) to specify the Airframes that is currently in the wrong 'type'
2. Add the SVG diagrams …
> More specific Airframe type support for better Airframe Reference

- boards/ark/fmu-v6x/src/mtd.cpp
- boards/px4/fmu-v5x/src/mtd.cpp
- boards/px4/fmu-v6c/src/mtd.cpp
- boards/px4/fmu-v6x/src/mtd.cpp
- boards/sky-drones/smartap-airlink/src/mtd.cpp
- platforms/common/include/px4_platform_common/mtd_manifest.h
- platforms/nuttx/src/px4/common/include/px4_platform/board_hw_eeprom_rev_ver.h
- platforms/nuttx/src/px4/stm/stm32_common/board_hw_info/board_hw_rev_ver.c
This PR adds support that Manifest (MFT) could be read out from FMUM's IMU's EEPROM. Inside MFT is `hw_extended_id` that carries HW Revision. 
Some background:
Credits for architecture and requirements go to @davids5  
In this solution, it is added additional partition at `imu_eeprom ` that will serve to store data for MTD_MFT_REV. 
It is tested with fmu-v5x and fmu-v6x.
> mtd: add support for extended HW revision

- src/modules/commander/Commander.cpp
Sets the vehicle to hold after a mission is finished (or cleared). -- before would stay in mission.
leave it in mission.. with no mission item, however, this is somewhat uncommanded behavior.
https://user-images.githubusercontent.com/8026163/200412752-d9db89ff-4781-4f92-abe9-e5b2565eb861.mp4
> commander: hold after mission clear

- src/modules/commander/Commander.cpp
In https://github.com/PX4/PX4-Autopilot/pull/20564, the change in logic to hold after mission clear also broke RTL, as non-mission takeoff still published a mission result which allowed entering the mission finished condition and always changing state to loiter (ignoring rtl). New logic only switches navigation states if mission is finish and the nav state is explicitly in takeoff state, or in mission state.
I checked the following cases work as intended in SITL:
- takeoff command, RTL command .. RTL actually is able to finish
- takeoff command, `COM_TAKEOFF_ACT=0`, vehicle holds once done taking off
- takeoff command, `COM_TAKEOFF_ACT=1`, vehicle enters the mission once done taking off
- start mission, clear mission while it's running, vehicle holds
> commander: fix hold after mission logic

- src/modules/navigator/mission_block.cpp
@OfficerJannis reported that the problem I fixed in https://github.com/PX4/PX4-Autopilot/pull/20171 also happened to him on  the release 1.13. Also I got basically the same report a second time on Discord from SZ#6337 sadly in private (will not accept that in the future anymore).
So I'm following @julianoes 's valid request here https://github.com/PX4/PX4-Autopilot/pull/20171#issuecomment-1301359524 and backport the fix to 1.13.
FYI @OfficerJannis
See https://github.com/PX4/PX4-Autopilot/pull/20171
This was tested by many people by now on `main` and reportedly also backported to older versions to fix the original issue.
> [1.13] VTOL takeoff problem hotfix

- src/modules/sensors/module.yaml
Please use [PX4 Discuss](http://discuss.px4.io/) or [Discord](https://discord.gg/dronecode) to align on pull requests if necessary. You can then open draft pull requests to get early feedback.
The vehicle parameters CAL_ACC[012]* were lacking the 'decimal' field in the yaml description
The field decimal field is now added
NA
The changes were tested with QGC and SITL. Before the changes the parameters appear as integers which is NOK and after the changes they appear as floats which is correct.
> Decimal added for the CAL_ACC[012]* parameters

- src/modules/simulation/simulator_mavlink/SimulatorMavlink.cpp
- src/modules/simulation/simulator_mavlink/SimulatorMavlink.hpp
`simulator_mavlink` didn't support vio failure injection.
Adds a `FAILURE_UNIT_SENSOR_VIO` case to `SimulatorMavlink::check_failure_injections()`, supporting the "off" failure type. 
Tested with `make px4_sitl gazebo_iris_vision`, and using the `failure` command.
Drone swaps to altitude mode after `failure gps off` & `failure vio off`, goes back to position after `failure vio ok`
Logs: https://review.px4.io/plot_app?log=bb544f7f-6da4-490a-b5e5-d4fbb9c7c650
> simulator_mavlink: Add basic vio failure injection

- src/modules/commander/HealthAndArmingChecks/HealthAndArmingChecks.cpp
- src/modules/commander/HealthAndArmingChecks/HealthAndArmingChecks.hpp
In this case it did not cause any problems.
Fixes a compiler warning:
```
/src/modules/commander/HealthAndArmingChecks/HealthAndArmingChecks.cpp:39:21: error: member ‘HealthAndArmingChecks::_failsafe_flags’ is used uninitialized [-Werror=uninitialized]
39 |           _reporter(_failsafe_flags)
|                     ^~~~~~~~~~~~~~~
```
> commander: fix initialization order of _failsafe_flags

- msg/CameraCapture.msg
- src/modules/camera_feedback/CameraFeedback.cpp
- src/modules/camera_feedback/CameraFeedback.hpp
- src/modules/mavlink/mavlink_receiver.cpp
The CameraFeedback module uses only the vehicle attitude for the camera orientation which is not necessarily correct when the camera is mounted to a gimbal.
With this change, the `gimbal_device_attitude_status` is used to compute the global camera orientation when available. It handles the two cases where `DEVICE_FLAGS_YAW_LOCK` is set or not but assumes that roll and pitch are locked and thus already relative to the NED earth-fixed frame.
The comment for the camera attitude in the `CameraCapture` message said it is relative to the front of the vehicle but since the location in lat and lon coordinates are global, it would be more consistent to reference the earth frame for the attitude as well. Moreover, the previous logic just copied the vehicle attitude which is not consistent with that …
> Use gimbal device attitude for the camera feedback when available

- ROMFS/px4fmu_common/init.d/rcS
This PR moves the uavcan startup to the end of the rcS script. I have been seeing an issue on and off on different autopilots where when on battery power, uavcannodes sometimes won't boot. It looks like it is caused by the uavcan firmware server spinning on the sd card firmware read. When this occurs, no other task can read the SD.
Moving the uavcan start call to the end of the rcS script appears to solve the problem. Could be related to logger start timing.
> Move uavcan start to end of rcS to prevent sd card read lock

- src/lib/parameters/param_translation.cpp
- src/modules/vtol_att_control/standard.cpp
- src/modules/vtol_att_control/standard.h
- src/modules/vtol_att_control/standard_params.c
Before, for standard VTOLs, no matter what pusher throttle was used before, it was reset to zero at the beginning of a front transition and then linearly increased to reach the desired value for fixed wing mode: it was useless, slower and resulted in a waste of energy. 
The solution that we implemented is just to make the ramp up start at the previous value assigned to the pusher instead of resetting it to zero, while keeping the same rate of increase: that way, the drone can just accelerate to get to fixed wing mode without having to slow down before.
What we implemented was an easy and simple way to improve the behavior of the drone, so we didn't really consider any other solution. There could be smarter ways to do it, maybe using a nonlinear ramp up but we didn't take the time to focus …
> Smarter pusher ramp up during front transtitions for standard VTOLS

- src/modules/ekf2/EKF/common.h
- src/modules/ekf2/EKF/control.cpp
- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/ekf_helper.cpp
- src/modules/ekf2/EKF/gnss_height_control.cpp
- src/modules/ekf2/EKF/gps_control.cpp
- src/modules/ekf2/EKF/mag_control.cpp
When a GNSS fusion due to a bad yaw (e.g.: sudden reset) occurs later than 30s after takeoff (i.e.: when the quick trigger is inactive), the loss of local position (5s) occurs before even trying a reset (7s).
- ~Try a yaw  (if needed) and local position reset just before (at 4.5s) a potential loss of navigation. Consecutive resets are still separated by a 7s interval.~
- Reset to the yaw emergency estimator more aggressively: "is the difference between the yaw from EKF2 and the yaw estimator is >25deg and that the GNSS velocity fusion is failing for more than 1s, then reset". We've seen in the last couple of years that almost all loss of navigation are caused by a bad magnetometer pulling the yaw estimate away and that in all those issues, the yaw estimator was correct and would have …
> Allow for emergency yaw reset before stopping navigation

- src/modules/flight_mode_manager/CMakeLists.txt
- src/modules/flight_mode_manager/FlightModeManager.cpp
- src/modules/flight_mode_manager/FlightModeManager.hpp
- src/modules/flight_mode_manager/Templates/FlightTasks_generated.cpp.em
- src/modules/flight_mode_manager/generate_flight_tasks.py
- src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.hpp
- src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
- src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.hpp
This fixes a few problems for orbit:
remove command ack for VEHICLE_CMD_DO_ORBIT. Already acked in commander
Fixes a regression from https://github.com/PX4/PX4-Autopilot/commit/8bae4e5c0e29f70d5d1d2427ffdef97092be939c, where
the orbit flight task wasn't an extra task (flight_tasks_to_add) anymore
and therefore the command handling wasn't generated.
There was a race condition that could cause several outcomes. The most severe
was that flight_mode_manager gets the command, switches to orbit and then
in the next iteration switches back because commander did not change
nav_state yet. When commander then switches, flight_mode_manager would still
be in the old mode.
This is prevented by storing the command (allowing it to arrive before or
after mode switch), and then apply it after the switch …
> Orbit fixes for MC

- src/modules/ekf2/EKF/common.h
- src/modules/ekf2/EKF/control.cpp
- src/modules/ekf2/EKF/estimator_interface.cpp
- src/modules/ekf2/EKF/estimator_interface.h
- src/modules/ekf2/EKF2.cpp
- src/modules/ekf2/EKF2.hpp
- in a lot of cases this won't really matter, although you can see it in logs (especially with things like vehicle_at_rest), but it's something we might as well do properly
- occasionally I do come across logs where the external VIO, optical flow, mocap, etc is fairly significantly delayed ( > 500 ms)
> ekf2: update flags (in_air, at_rest, etc) on delayed time horizon

- src/modules/ekf2/EKF/zero_velocity_update.cpp
Some people are still seeing annoying "height estimate not stable" messages primarily because the GNSS altitude drifted by a couple of meters after initializing the EKF origin. The problem is that with Zero Velocity Updates in addition to GNSS velocity fusion, the variance of the velocity estimate becomes really small and makes the position estimate too rigid and it can take several tens of seconds to move by a couple of meters.
1. Do not fuse zero velocity fake measurements if another velocity aiding source is active (GNSS or VIO)
2. Use "extremely high accuracy" during fine alignment and "good accuracy" otherwise (this is to decouple from `_NED_origin_initialised` that relates to GNSS directly)
Unit tests, SITL
> ekf2: do not fuse ZVU if other velocity source is active

- src/modules/ekf2/EKF/estimator_interface.cpp
- src/modules/ekf2/EKF/estimator_interface.h
- src/modules/ekf2/EKF/zero_velocity_update.cpp
Add some recent improvements to prevent excessive "height estimate not stable" issues.
see https://github.com/PX4/PX4-Autopilot/pull/20611
and https://github.com/PX4/PX4-Autopilot/commit/a2a50938815026ac26ef25136f3aac75cbbc979c
> [RELEASE/1.13] EKF2: ZVU improvements

- src/modules/ekf2/EKF/control.cpp
- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/ekf_helper.cpp
- src/modules/ekf2/EKF2.cpp
- if in a single EKF update there are multiple resets we need to track the accumulated delta so the reset consumed by the controllers is correct
> ekf2: accumulate multiple vel/pos/orientation reset deltas per update

- src/modules/commander/commander_params.c
@Curry reported on Discord some results of running static analysis and to my surprise `COM_RCL_ACT_T` was in the list of unused parameters: https://discord.com/channels/1022170275984457759/1040487659560239184/1040487670377349150
And duplicate here: fixes #20593
I remove the definition of `COM_RCL_ACT_T` because https://github.com/PX4/PX4-Autopilot/commit/455b885f86754985fb07726b7975f0f028537204 deprecated the parameter and failsafe delays got consolidated to `COM_FAIL_ACT_T`.
This parameter was originally introduced in: https://github.com/PX4/PX4-Autopilot/pull/16406
> commander_params: remove deprecated COM_RCL_ACT_T

- src/modules/navigator/navigator_params.c
@bigworldsmall statically analyzed parameter use in PX4 and found quite some unused parameter definitions.
I'm removing deprecated or otherwise needless parameters. See the table in:
closes #20593
> Remove needless parameter definitions

- .github/PULL_REQUEST_TEMPLATE.md
I see lots of newcomers straight ignoring the pull request template.
Many times the whole
> Please use [PX4 Discuss](http://discuss.px4.io/) or [Discord](https://discord.gg/dronecode) to align on pull requests if necessary. You can then open draft pull requests to get early feedback.
is still in and probably nothing was read.
I suggest keeping it short, no full text, the top part commented.
> Suggestion to make the pull request template more "concise"

- src/modules/land_detector/MulticopterLandDetector.cpp
- src/modules/land_detector/MulticopterLandDetector.h
- src/modules/land_detector/land_detector_params_mc.c
Otherwise the _in_descend flag doesn't get set correctly during the last part of the landing, where the descend speed is at MPC_LAND_CRWL/MPC_LAND_SPEED. The _in_descend flag is set it the velocity setpoint is >1.1*LNDMC_Z_VEL_MAX, so I added a 1.2 factor to be on the safe side.
There was a very similar check that I removed recently: https://github.com/PX4/PX4-Autopilot/pull/20425/files#diff-ccf6ef052db2503b2701a1211d31f99d45cf581db98e056ca8b4da725a805b7dL125-L131.
I think I removed it because A) it anyway didn’t check the right param (MCP_LAND_SPEED instead of CRWL), and B) because I thought it may be confusing to have it enforced to lower than CRWL even if CRWL is never used (bc no distance sensor is present). Thinking about it again I think the advantages overweight the disadvantages …
> LandDetectorMC: enforce that LNDMC_Z_VEL_MAX is larger than MPC_LAND_CRWL/MPC_LAND_SPEED

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- While flight testing I found that the airspeed setpoint increase due to bank angle is wrong.
- the 0.9 factor margin between stall vs min airspeed isn't actually necessary, it's enough to warn the user if stall>min.
- remove the sqrt() from the load factor calculation. There is still a sqrt(load_factor) for the airspeed calculation based on load factor.
- remove the 0.9 factor
> Pr fw pos c fix load factor airspeed main

- src/drivers/drv_hrt.h
I found that abstime_to_ts doesn't work at all, it overflows on two lines. Caused many mysterious bugs in my own development branches. Added separate comments explaining the needed changes
Fix the typecasts
N/A
Desk-tested by printing out the calculated values
> Fix overflows in abstime_to_ts

- src/drivers/gps/gps.cpp
- src/drivers/uavcannode/UavcanNode.cpp
Fixes a typo in my last PR for CANNODE_SUB_MBD. Increase the allowed RTK injections to match the uorb queue depth. Update GPS submodule with fixed UBX_MODE enum.
> Fix CANNODE_SUB_MBD typo and broken GPS_UBX_MODE param. Update GPS Submodule. Increase allowed RTK injections.

- src/modules/fw_att_control/FixedwingAttitudeControl.cpp
- src/modules/fw_att_control/FixedwingAttitudeControl.hpp
This is to make it again in line with the parameter description and docs
> FW Attidue Controller: use FW_AIRSPD_MIN for DTRIM instead of STALL

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
- src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c
Two separate issues related to accelerated stall (load factor dependent stall speed):
- the check was only in Auto modes, not in manual Position or Altitude
- it was using FW_AIRSPD_STALL, which, when set correctly, didn't leave the controller any room for error
- also do it in Position and Altitude
- clearly define FW_AIRSPD_MIN as stall+margin, and use that (adjusted to the load factor), as the min airspeed setpoint into the controller
SITL
> FW Position Controller: improve accelerated stall protection

- src/modules/microdds_client/utilities.hpp
This corresponds to the ROS2 default. Using reader=TRANSIENT_LOCAL and writer=VOLATILE (=default) is incompatible according to https://docs.ros.org/en/rolling/Concepts/About-Quality-of-Service-Settings.html
@dagar did you use non-default QOS in your testing?
> microdds: use UXR_DURABILITY_VOLATILE for data reader

- src/modules/mavlink/mavlink_main.cpp
The AT commands were formatted incorrectly
PR by @amikhalev.
> mavlink: Fix setting MAV_SIK_RADIO_ID

- src/modules/fw_att_control/FixedwingAttitudeControl.cpp
- src/modules/fw_att_control/FixedwingAttitudeControl.hpp
- src/modules/fw_att_control/fw_att_control_params.c
- yaw stick still maps directly to actuator_controls[YAW] (seems to have been an oversight in https://github.com/PX4/PX4-Autopilot/pull/19912/commits/8372a78507f70a47ced64404250075f806c5aa22)
- not possible to disable manual yawing if not desired
- remove direct stick-->controls, only change body_rates_setpoint(2) which is then fed into the controller. Note: body_rates_setpoint(2) is previously calculated by the attitude controller for turn coordination. 
- introduce FW_YR_MAX_ADD param and use instead of FW_Y_RMAX to set the effect of the stick to the rate setpoint. If no effect is desired, it can be set to 0. 
We could also completely disable it in any attitude controlled mode?
SITL tested.
> fixed-wing attitude control: add option to disable manual yaw

- src/lib/npfg/npfg.cpp
- src/lib/npfg/npfg.hpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
For fixedwing position control, waypoint coordinates projected on to the local frame are logged as local position setpoints. While this makes sense for waypoints, NPFG is capable of tracking paths, and logging what position reference the vehicle is trying to track would be much more informative. For example, when the vehicle is flying on a loiter path, we want to know how close the vehicle is to the closest point on the circle, rather than the center of the loiter circle.
This commit adds a state in the NPFG library which keeps the position setpoint reference so that it can be published as part of the `vehicle_local_position_setpoint` message.
When passing arbitrary references with a path in offboard mode, comparing the position reference and the current position provides better insights …
> Log local position setpoint reference for fixedwings when running NPFG

- boards/px4/fmu-v2/init/rc.board_sensors
As requested in https://github.com/PX4/PX4-Autopilot/pull/20262. Sorry for the delay.
> fmu-v2: make optional sensor startup quiet

- src/modules/gimbal/gimbal.cpp
The [update function of InputMavlinkGimbalV2](https://github.com/PX4/PX4-Autopilot/blob/main/src/modules/gimbal/input_mavlink.cpp#L491) returns `UpdatedNotActive` when receiving control commands from a system or component that doesn't match the primary control. This can happen if a component just sends commands without being in control or when transitioning to a different primary control. If the input is marked as `already_active`, it will [reset last_input_active](https://github.com/PX4/PX4-Autopilot/blob/main/src/modules/gimbal/gimbal.cpp#L252) which in turn [resets the primary control](https://github.com/PX4/PX4-Autopilot/blob/main/src/modules/gimbal/gimbal.cpp#L209) in the next iteration. According to the MAVLink gimbal protocol v2, a component needs to send …
> Preserve gimbal control when receiving updates from an input that is not active

- src/modules/mc_pos_control/MulticopterPositionControl.cpp
- src/modules/mc_pos_control/MulticopterPositionControl.hpp
Right now on main there's a high chance that if you switch from a non altitude controlled mode e.g. stabilized to an altitude controlled one e.g. altitude that you get a message for invalid setpoint. This is because https://github.com/PX4/PX4-Autopilot/pull/19162 solved the issue where no valid setpoint is present yet by just generating a failsafe setpoint. And I think originally it was supposed to not show the message but now it does.
I just don't show the message when the failsafe setpoint is generated to bridge the mode switch.
I plan to change the logic as part of simplifying the entire wrapping logic for takeoff and landing but in the meantime we need a fix for the user experience on main.
I tested this in SITL. The message doesn't show up anymore.
> Avoid invalid setpoint message when switching to altitude controlled mode

- src/modules/simulation/gz_bridge/GZBridge.cpp
When using ignition SITL simulation with NO_LOCKSTEP, the SITL PX4 fails to update the IUM data from Ignition Gazebo.
The timestamp for the IMU data is taken from the ignition message:
- In LOCKSTEP mode the clock from the ignition simulation and the one from PX4 SITL are synchronized, hence everything works fine
- In NO_LOCKSTEP mode, those clocks are not synchronized anymore, so the timestamp for the IMU data should not be the one from Ignition but the current time in PX4 SITL when receiving the message.
An alternative would be to have a clock synchronization process between ignition and PX4_SITL when we are in NO_LOCKSTEP mode, but since it is a SITL simulation, it is a bit overkill.
A good option would be to work always using LOCKSTEP for simulation. But using the DDS bridge and ROS2 …
> fix: ignition with no lockstep

- src/drivers/pwm_out/PWMOut.cpp
- src/drivers/pwm_out/PWMOut.hpp
- src/drivers/px4io/px4io.cpp
- src/drivers/tap_esc/TAP_ESC.cpp
- src/lib/mixer_module/mixer_module.cpp
- src/lib/mixer_module/mixer_module.hpp
Before, the logic to update disarm and rate values also triggered during
bootup on the px4io, because the output functions are only set in
updateSubscriptions().
Therefore change the check to prevent updating during the first cycle.
@sfuhrer @ryanjAA
> fix pwm_out, px4io: prevent disarm and rate param updates during boot 

- src/modules/gyro_calibration/GyroCalibration.cpp
- src/modules/temperature_compensation/temperature_calibration/accel.cpp
- src/modules/temperature_compensation/temperature_calibration/baro.cpp
- src/modules/temperature_compensation/temperature_calibration/gyro.cpp
When temperature compensation is active, it happened that the sensor offset was compensated twice because the `GyroCalibration` "auto-calibration" was not considering the new thermal offset when updating the calibration.
Also reset the offset and scale parameters as the thermal calibration does not consider those values when gathering data.
bench tests on Pixhawk5
> GyroCalibration: consider updated temperature compensation offset

- .gitignore
- Makefile
Adds make jlink-nuttx command that builds GDB Segger jlink-nuttx.so plugin for task-aware debugging.
To enable multi-task debugging you've enable `CONFIG_DEBUG_TCBINFO` in your NuttX config to expose the TCB offsets.
To enable multi-task debugging in your segger debugger you've add the following line to the SEGGER GDB commandline options
`-rtos /home/peter/src/Firmware/Tools/jlink-nuttx.so`
> Add jlink-nuttx build command for gdb helper for multi-task debugging

- msg/ManualControlSetpoint.msg
- src/drivers/actuators/modalai_esc/modalai_esc.cpp
- src/lib/mixer_module/functions/FunctionManualRC.hpp
- src/modules/airship_att_control/airship_att_control.hpp
- src/modules/airship_att_control/airship_att_control_main.cpp
- src/modules/commander/Commander.cpp
- src/modules/commander/rc_calibration.cpp
- src/modules/flight_mode_manager/tasks/Utility/Sticks.cpp
- src/modules/fw_att_control/FixedwingAttitudeControl.cpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
- src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
- src/modules/local_position_estimator/BlockLocalPositionEstimator.hpp
- src/modules/manual_control/ManualControl.cpp
- src/modules/manual_control/ManualControl.hpp
- src/modules/mavlink/mavlink_receiver.cpp
- src/modules/mavlink/streams/MANUAL_CONTROL.hpp
- src/modules/mc_att_control/mc_att_control.hpp
- src/modules/mc_att_control/mc_att_control_main.cpp
- src/modules/mc_autotune_attitude_control/mc_autotune_attitude_control.cpp
- src/modules/mc_rate_control/MulticopterRateControl.cpp
- src/modules/rc_update/params.c
- src/modules/rc_update/rc_update.cpp
- src/modules/rover_pos_control/RoverPositionControl.cpp
- src/modules/uuv_att_control/uuv_att_control.cpp
Fixes #9331 and works towards a solution for part of https://github.com/PX4/Firmware/issues/15874
Rescale `manual_control_setpoint.z` which represents the throttle stick value from a range of [0,1] to [-1,1].
I think for nicer usage in all the different modules it would be helpful to extend the `Sticks` class to provide the common scaling and gestures (is stick below minimum) from one single place.
Not yet tested.
This is also useful to be able to convert between RC modes (https://www.rc-airplane-world.com/rc-transmitter-modes.html) on the fly without having to recalibrate everything.
> Scale manual control setpoint up/down stick -1 to 1

- src/lib/battery/battery.cpp
- src/lib/battery/battery.h
When implementing a smart battery driver I found that just overwriting the state of charge in the battery message doesn't update the battery class so if I want to use that class and benefit from not duplicating things there needs to be an explicit way to externally inject the known state of charge from the smart battery.
- Add possiblity to inject a known state of charge without interfering with the battery class internal calculations but leveraging e.g. existing battery warnings.
This was tested with a very custom smart battery driver to work as expected.
This should also be used for UAVCAN power module and smart battery support 👀
> battery: allow for external state of charge injection

- src/modules/fw_att_control/FixedwingAttitudeControl.cpp
There was a bug introduced with https://github.com/PX4/PX4-Autopilot/pull/20502, where _rates_sp.reset_integral would never be set to false again once it was set to true.
> FW Attitude Control: fix integral resetting

- src/modules/ekf2/EKF/estimator_interface.cpp
- src/modules/ekf2/EKF/estimator_interface.h
EKF2 never gives up on fusing GNSS data once the fusion started if there is no other horizontal aiding source available. The issue is that even if the receiver reports an invalid fix, the data is still used and the vehicle never goes into failsafe.
Do not add an invalid GNSS sample to the buffer.
Store this flag in the buffer and add it to the mandatory conditions in GPS_control
In SIH, when the GNSS fails, the eph and epv are increased, and the `vel_ned_valid` flag is set to `false` but the drone continues to fly in position or auto mode and drifts away.
> ekf2: don't add invalid GNSS samples to the buffer

- src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
This commit fixes a regression that caused problems when trying to use offboard control with fixedwings (or VTOLs in fixedwing mode)
The problem was that all offboard setpoints were considered invalid in offboard mode:
This was a regression introduced by https://github.com/PX4/PX4-Autopilot/pull/19942, where the valid flag in position_setpoint_triplet was no longer being used and the offboard logic was left out.
Tested in SITL Gazebo and publishing offboard setpoints
- Flight logs before PR: https://review.px4.io/plot_app?log=b46b490c-69f8-4fe1-a47f-b16fc6ab8b54
- Flight logs after PR: https://review.px4.io/plot_app?log=ced912ac-1b8d-427e-8829-90337d208482
> Fix invalid offboard setpoints for fw pos control

- src/modules/ekf2/EKF/estimator_interface.cpp
https://github.com/PX4/PX4-Autopilot/pull/20679 wasn't enough so this PR prevents from pushing a gnss sample to the buffer when there is no fix at all.
> ekf2: do not use gnss data when no fix

- src/modules/commander/failure_detector/FailureDetector.cpp
Imbalanced prop metric was spitting out nans on occasion, resulting in the imbalanced prop detection not working.
Root cause - the raw accelerometer component variances were getting rotated into body frame as a vector (not covariance), giving negative numbers when the calibration rotation was not very small. This is fixed already in #20676 - thanks @dagar 
However, while looking into it, I also found that the time interval calculation in failure detector had an error which maxed out the dt on the metric filter at all times.
- fix the time interval calculation error
- bonus: guard the square root functions as extra protection against any floating point errors so nans cannot appear
> Imbalanced prop detection fixes

- src/modules/sensors/data_validator/DataValidatorGroup.cpp
A single error makes the selector switch from the primary mag to a secondary one because it is on instance 1 while the internal one is on instance 0.
This is because currently, the the best instance is selected but it is harder for an instance with a higher number to be selected because they need to be strictly better than the instance with a lower number.
IMO, the initial intent was to keep the currently selected instance until a problem is detected or if a good instance with a higher priority is available.
Instead of always starting with instance 0 (potentially an internal mag), first take the current sensor as reference to
compare the other ones against it.
tested on v5 by hacking a change of confidence when a sensor is disconnected instead of triggering a timeout
FYI: @bkueng
> DataValidator: fix unexpected fail-over

- src/modules/vtol_att_control/vtol_att_control_main.cpp
- src/modules/vtol_att_control/vtol_att_control_main.h
- src/modules/vtol_att_control/vtol_type.cpp
- src/modules/vtol_att_control/vtol_type.h
Pusher assist altitude-based activation/deactivation is wrong when the vehicle doesn't take off from 0 local_position.z in case there is no valid distance sensor data.
Subtract the home position altitude from the local position altitude.
SITL tested.
Uses now same logic as FlightTask: https://github.com/PX4/PX4-Autopilot/blob/65577a4f89cc75e573deb3d1b6313c1857f68a72/src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.cpp#L176-L189
Maybe we could even add a field in local_position called distance_to_home_vertical or so?
> VTOL: take home_position into account for ground clearance

- Tools/simulation/jmavsim/jmavsim_run.sh
With openjdk 17.0.5 2022-10-18, jmavsim fails to start due to missing exports. This was previously a warning and turned into an error now.
```
Caught AppContextInfo(Bug 1004) InaccessibleObjectException: Unable to make public static sun.awt.AppContext sun.awt.AppContext.getAppContext() accessible: module java.desktop does not "exports sun.awt" to unnamed module @2c767a52 on thread J3D-Renderer-1
[0]: java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
[1]: java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[2]: java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
[3]: java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
[4]: …
```
> jmavsim_run.sh: add module exports to avoid access errors

- ROMFS/px4fmu_common/init.d-posix/rcS
- src/modules/microdds_client/microdds_client.cpp
- src/modules/microdds_client/microdds_client.h
- src/modules/microdds_client/module.yaml
1. The `microdds_client` did not add the namespace to the participant name. As a result when working with multiple vehicles and ROS2 all microdds_agent had the same name.
2. in `sitl` the `microdds_client` was automatically started on `udp` and port `8888`. With multiple vehicles this caused having all the clients connected to the same agent with the same key identifier, breaking the bridge regardless the presence of the namespace.
1. The `participant_xml` is created taking into account the desired namespace.
2. The parameter `XRCE_DDS_KEY` is added and used to specify the session key.
3. In `sitl` the `microdds_client` is automatically started on `udp`. ~~Depending on the `px4_instance` variable the port and the namespace are selected:
`microdds_client start -t udp -p …
> microdds_client: add namespace to partecipant name

- platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp
On the ARKV6X, load mon is warning that SPI2 is low on stack running just the icm42688p driver. It appears to be due to the icm42688p on SPI2 using rotation ROTATION_ROLL_180_YAW_45 compared to the icm42688p on SPI3 using ROTATION_YAW_270.
It also appears that this is causing SPI2 to use twice the CPU as the same driver on SPI3 with a more simple rotation.
```
489 wq:SPI2                       101  5.781  2012/ 2328 252 (252)  w:sem  4
504 wq:SPI3                        41  2.382  1848/ 2328 251 (251)  w:sem  4
```
> Increase SPI stacks by 16 bytes

- boards/beaglebone/blue/cmake/init.cmake
Fixes PRU path issues found in old versions of the library by upgrading to 1.0.5
> Point to a newer version of librobotcontrol

- src/drivers/uavcannode/Publishers/HygrometerMeasurement.hpp
- src/drivers/uavcannode/UavcanNode.cpp
Signed-off-by: dirksavage88 <dirksavage88@gmail.com>
Uavcannode support for hygrometer sensor
Tested on sht3x hygrometer, was able to read temp and humidity over the bus using the dronecan gui tool.
Since dronecan dsdl includes hygrometer sensors, including this in Uavcannode drivers as a publisher is trivial.
> Uavcannode hygrometer support

- boards/nxp/ucans32k146/src/board_config.h
@PetervdPerk-NXP  bit by the non-auto sizing table bug again!
Symptom: Hard fault on Port E config (CAN0)
> Hard fault on Port E config (CAN0) due to not sizing the table correctly

- src/modules/ekf2/EKF/common.h
- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/ekf_helper.cpp
- src/modules/ekf2/EKF/mag_control.cpp
- src/modules/ekf2/EKF2.cpp
- not a verified bug, but depending on configuration and timing this potentially could have resulted in a mag calibration change causing EKF2 to reset mag states, but immediately performing the reset on previous mag data (without the new calibration)
> ekf2: push mag cal reset to delayed time horizon

- src/modules/ekf2/EKF/bias_estimator.hpp
- src/modules/ekf2/EKF/common.h
- src/modules/ekf2/EKF/control.cpp
- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/ekf_helper.cpp
- src/modules/ekf2/EKF/estimator_interface.cpp
- src/modules/ekf2/EKF/ev_height_control.cpp
- src/modules/ekf2/EKF/ev_vel_control.cpp
- src/modules/ekf2/EKF/height_control.cpp
- src/modules/ekf2/EKF2.cpp
- src/modules/ekf2/EKF2.hpp
- src/modules/ekf2/test/sensor_simulator/ekf_wrapper.cpp
- respect new EKF2_EV_CTRL parameter for VPOS usage
- EV hgt rotate EV position before usage (there's often a small offset in frames)
- EV hgt reset use proper EV velocity body frame
- try to keep EV hgt and EV vel state machines consistent
- small incremental piece of https://github.com/PX4/PX4-Autopilot/pull/19128
- requires https://github.com/PX4/PX4-Autopilot/pull/20497 to come in first
> ekf2: update EV height state machine (small piece of EV overhaul)

- src/modules/mavlink/mavlink_main.cpp
- src/modules/mavlink/mavlink_messages.cpp
- src/modules/mavlink/streams/OPEN_DRONE_ID_LOCATION.hpp
- src/modules/mavlink/streams/OPEN_DRONE_ID_SYSTEM.hpp
> mavlink: add initial mavlink OPEN_DRONE_ID_SYSTEM stream

- src/modules/mavlink/streams/GPS2_RAW.hpp
- src/modules/mavlink/streams/GPS_RAW_INT.hpp
If the gps process dies, the ground control will keep showing the values from the last GPS_RAW_INT message and will not detect an unhealthy state of the GPS.
Keep sending GPS_RAW_INT message on 1Hz, with no gps available state and default values when the GPS_RAW_INT message wasn't sent for 1s. This allows the ground control to visualise that no GPS is available.
Tested by stopping the gps process using `gps stop` in the MAVLink Console.
> Keep sending GPS_RAW_INT on gps failure

- src/modules/vtol_att_control/vtol_att_control_params.c
- src/modules/vtol_att_control/vtol_type.cpp
- src/modules/vtol_att_control/vtol_type.h
Triggering a quadchute high up above the ground can be dangerous as batteries deplete fast in  hover.
Add a parameter to specify a maximum height above ground/home/origin.
> Quadchute: Specifiy a maximum height

- src/modules/fw_att_control/FixedwingAttitudeControl.cpp
- src/modules/fw_att_control/FixedwingAttitudeControl.hpp
- src/modules/fw_att_control/ecl_controller.cpp
- src/modules/fw_att_control/ecl_controller.h
- src/modules/fw_att_control/ecl_pitch_controller.cpp
- src/modules/fw_att_control/ecl_yaw_controller.cpp
- src/modules/fw_rate_control/FixedwingRateControl.cpp
- src/modules/fw_rate_control/FixedwingRateControl.hpp
Follow up on @Jaeyoung-Lim 's PR https://github.com/PX4/PX4-Autopilot/pull/20237, where he split out the FW rate controller into a new module. 
I here remove logic that was not no longer needed (both in the Attitude and Rate module), fixed some issues where I saw them and also couldn't hold back with some smaller refactors.
Quickly flew it in SITL on all VTOL types plus plane, looked fine so far - would say we bring this into the main PR and proceed discussion/reviewing/testing there, unless you see something you don't like here @Jaeyoung-Lim , then I would address it prior merging.
> FW Rate Controller Followup

- src/lib/mixer_module/mixer_module.cpp
Avoids extra empty topic instances, e.g. with uavcan enabled but not used for outputs.
Fixes https://github.com/PX4/PX4-Autopilot/issues/20747
> [1.13] mixer_module: only advertise actuator_outputs when mixer is loaded

- src/modules/vtol_att_control/standard.cpp
- src/modules/vtol_att_control/tailsitter.cpp
- src/modules/vtol_att_control/tiltrotor.cpp
- src/modules/vtol_att_control/vtol_type.h
The transition timer state was only updated in the `VtolType::update_vtol_state` method. However, the timer value was being used in methods which were called prior to that. Thus it could happen that a backtransition was accepted immediately  due to the timer not having been reset.
> Fixed transition timer not being reset

- src/modules/muorb/aggregator/mUORBAggregator.cpp
- src/modules/muorb/aggregator/mUORBAggregator.hpp
- src/modules/muorb/apps/CMakeLists.txt
- src/modules/muorb/apps/uORBAppsProtobufChannel.cpp
- src/modules/muorb/apps/uORBAppsProtobufChannel.hpp
- src/modules/muorb/slpi/CMakeLists.txt
- src/modules/muorb/slpi/uORBProtobufChannel.cpp
- src/modules/muorb/slpi/uORBProtobufChannel.hpp
Sending lot's of single uorb topics from the DSP (Qurt) up to the Apps side at high frequency is very inefficient. It is much more efficient to aggregate a few topic messages together and then send up that one larger message.
> Qurt platform muorb aggregator

- src/drivers/gps/gps.cpp
- src/drivers/gps/params.c
I2C port In/Out configuration issue https://github.com/PX4/PX4-Autopilot/issues/20599
This solution will give support for enabling protocols at the I2C interface with the **GPS_UBX_CFG_INTF** parameter. 
In the future parameter can be extended for enabling/disabling protocols at other interfaces (UART1, UART2, USB, SPI).
Needed protocols could be enabled with the check box:
> drivers/gps: add param for enabling protocols at i2c interface

- src/modules/airspeed_selector/AirspeedValidator.cpp
- src/modules/airspeed_selector/AirspeedValidator.hpp
- src/modules/airspeed_selector/airspeed_selector_main.cpp
- src/modules/airspeed_selector/airspeed_selector_params.c
By default disable the "data stuck" and "data variation after boot" checks. Those checks were introduced to catch the (unlikely) case of the driver publishing a stale value that is not actually from a current measurement. This was done by declaring it invalid if either there is no update in the data for 2s or no update within the first 10s after boot.
Practice though has shown that around 0, many airspeed sensors have such a low resolution that the reported airspeed value is often at the exact same value for longer periods of time on totally healthy sensors, and thus we trigger some false positive failure detections.
Given that this failure mode (driver publishing stale data) is quite rare (if it doesn't receive new data it should stop publishing), I disable this checks here by default. …
> AirspeedValidator: change default of ASPD_DO_CHECKS

- src/lib/adsb/parameters.c
- src/modules/mavlink/streams/UAVIONIX_ADSB_OUT_CFG.hpp
Added support for Callsign for uAvionix transmitters
On request added 2 x int32 parameters to be used for storing 8-byte callsign. This is a temporary solution until the string is supported for parameters.
> adsb: add support for callsign

- src/lib/airspeed/airspeed.cpp
- src/lib/airspeed/airspeed.h
- src/modules/airspeed_selector/airspeed_selector_main.cpp
- to calculate CAS from TAS for the synthetic airspeed instance (ground-windspeed), the baro temperature is used. Due to the baro usually being inside a flight controller, this estimate is less accurate then using the temperature measured at the airspeed sensor.
- the learned airspeed scale is written to the param also if the airspeed was declared invalid
- use air_data.rho for density, which relies on airspeed sensor temperature if available
- only safe scale to param if the airspeed instance is valid
While flying in damp, cold conditions we had a case of a clogged pitot due to ice building inside it. The airspeed validator correctly triggered and declared the data invalid, but then saved the estimated value to the param after disarm, which then caused issues in the next flight. On the …
> Airspeed Selector: use better density source and only save scale parameter if valid

- src/drivers/optical_flow/paa3905/PAA3905.cpp
- src/drivers/optical_flow/paa3905/PAA3905.hpp
- src/drivers/optical_flow/paw3902/PAW3902.cpp
- src/drivers/optical_flow/paw3902/PAW3902.hpp
Ardupilot requires the optical flow data to be published at least once every 200ms. Decrease the backup schedule from 1 second to 200ms. 
https://review.px4.io/plot_app?log=d0f3ed77-24bc-4a40-af77-2cf56eca375f
> Decrease PAW3902 and PAA3905 backup schedule to 200ms

- src/modules/mavlink/mavlink_shell.cpp
On CubeOrange where no console is configured by default, starting MAVLink shell just stalls, and doesn't work.
Also, logfile download has been reported not to work, and again, seems to work with this change.
@bkueng does this make any sense to you? Why are the `fflush`s required? 
Related to #19831.
> mavlink_shell: fix stall on CubeOrange

- src/lib/battery/battery.cpp
- src/lib/battery/battery.h
@sanderux found during testing with v5x and INA238 that the computed state of charge can be off (e. g. 50%) even though the voltage seems to be measured correctly. It turned out that the issue is caused by the usage of anti-spark connectors; the pre-resistor causes a lowered initial voltage reading. This combined with bad timing (essentially how fast you're plugging the connector) causes a faulty initialization of the state of charge.
- adding a delay of 2 seconds before initializing the state of charge solves the given issue
The alternative would be to adjust the weight factor for faster convergence and make it independent of the charge level of the battery: https://github.com/PX4/PX4-Autopilot/blob/cfb670fbb37b18e1d145d86caa9244cfa7373869/src/lib/battery/battery.cpp#L233
However, this …
> Battery: delay initialization of SoC

- platforms/nuttx/src/px4/nxp/s32k3xx/board_reset/board_reset.cpp
The reboot didn't work on the MR-CANHUBK3
Since it seems that up_systemreset doesn't work on the S32K3XX MCU.
This patch just calls the board_functional_reset regardless of the board_reset() arguments.
> S32K3XX call functional reset on board_reset

- Tools/setup/ubuntu.sh
Fixes ubuntu installation script for 22.04 to only install gazebo.
Makes correct gazebo the only target for default install with --sim_jammy option.
> Fixes install for 22.04 gazebo

- src/modules/ekf2/EKF/common.h
- src/modules/ekf2/EKF/control.cpp
- src/modules/ekf2/EKF/ekf.h
- src/modules/ekf2/EKF/mag_control.cpp
- src/modules/ekf2/EKF/mag_fusion.cpp
- src/modules/ekf2/EKF/zero_innovation_heading_update.cpp
- src/modules/ekf2/test/CMakeLists.txt
- src/modules/ekf2/test/sensor_simulator/ekf_wrapper.cpp
- src/modules/ekf2/test/sensor_simulator/ekf_wrapper.h
- src/modules/ekf2/test/test_EKF_mag.cpp
When not using a mag (e.g.: after yaw emergency or mag type "none"), a yaw error isn't properly corrected even in presence of a large acceleration an a GNSS observation.
Constantly fusing a zero yaw innovation makes the filter too confident about its yaw estimate and doesn't correct itself anymore. The proposed solution is to only fuse a fake yaw measurement when the yaw variance of the estimator is too large (i.e.: larger than its initialization value).
Other changes:
- do not run the mag selection/reset/fusion logic when the mag is inhibited
- stop the mag fusion when the mag is constantly inhibited, this prevents having the mag fusion flag set while the fusion is not occurring for a long time.
SITL test: mag type none, takeoff in alt mode, move to init yaw. After a couple of seconds, …
> EKF2: Only fuse fake yaw when really needed

- Kconfig
- platforms/common/uORB/Kconfig
- src/drivers/qshell/Kconfig
- src/drivers/qshell/posix/Kconfig
- src/drivers/qshell/qurt/Kconfig
- src/modules/muorb/Kconfig
- src/modules/muorb/apps/Kconfig
- src/modules/muorb/slpi/Kconfig
Hides MUORB and QSHELL qurt and qshell modules for non-QURT platforms in boardconfig
By adding dependencies for these kconfig symbols
> PX4Board kconfig add dependency chain for QURT & POSIX modules

- src/modules/mavlink/mavlink_shell.cpp
> [BACKPORT v1.13] mavlink_shell: fix stall on CubeOrange

- src/modules/sensors/sensors.cpp
This fixes the case where vehicle_angular_rate is no longer started when airspeed is not enabled.
Signed-off-by: Julian Oes <julian@oes.ch>
> sensors: fix overlapping ifdef

- src/modules/navigator/mission_params.c
The MIS_TKO_LAND_REQ value 4 description was hard to read.
> MIS_TKO_LAND_REQ - improve English for value 4

- src/modules/commander/failsafe/failsafe.cpp
- src/modules/commander/failsafe/failsafe.h
None
A magic number is being used.
Definition names would be easier to understand.
I checked the meaning of the numbers at the following URL
https://docs.px4.io/main/en/advanced_config/parameter_reference.html
None
None
None
> failsafe: Define offboard loss failsafe mode

- Tools/setup/ubuntu.sh
Gazebo simulation on ubuntu 22.04
- Fall back to gazebo in version 11 (Package named gazebo) as it works on ubuntu 22.04 
- Left ignition gazebo for potential future use case
- Tested on ubuntu 22.04
> setup ubuntu.sh; fix legacy gazebo for Ubuntu 22.04

- src/modules/mavlink/mavlink_main.cpp
When we receive a command_long or command_int message to answer, it arrives with a source sysid/compid, so this means we can send the command_ack back on the appropriate MAVLink instances instead of all of them.
This commit filters outgoing command_ack messages, so they are only sent on the MAVLink instances where the sysid/compid has been seen in the past.
This means that a command_ack is likely still sent on multiple links for a setup with redundant links.
This should also prevent command_acks from being blasted on Iridium links when it's not required.
> mavlink: filter command_acks by target

- src/modules/simulation/gz_bridge/CMakeLists.txt
`px4-rc.simulator` uses `PX4_GZ_WORLD` to define the world file when Gazebo (not Gazebo Classic) is used.
> gz_bridge: fix world selector environment variable

- src/modules/commander/Commander.cpp
In Commander, the local copies of PX4 parameters are only updated if disarmed, and not if armed. This makes it impossible to change any COM_* parameter if in air (well, you can change it but it doesn't have any effect until you land and takeoff again). The user is not notified about params not having an effect immediately (as opposed to the ones that require a reboot).
Remove check for if (disarmed). 
Are you aware of any COM_* params that really should not be updated in air?
> Commander: always update parameters, not just if disarmed

- src/modules/replay/Replay.cpp
@dagar When using replays, I found that several topics were not published at all. Digging deep I found that this happened for all uORB topics with a msg_id larger than 128. The old formula behaved weird when casting (signed) char to unsigned int16, so I made the calculation a bit more straightforward.
Before:
```
INFO  [replay] Topic estimator_optical_flow_vel got msg id 125
ERROR [replay] estimator_optical_flow_vel nextDataMessage 96242
INFO  [replay] Topic estimator_optical_flow_vel got msg id 126
ERROR [replay] estimator_optical_flow_vel nextDataMessage 96274
INFO  [replay] Topic estimator_optical_flow_vel got msg id 127
ERROR [replay] estimator_optical_flow_vel nextDataMessage 96306
INFO  [replay] Topic estimator_optical_flow_vel got msg id 65408
ERROR [replay] …
```
> fix replay msg ids larger than 128
