ROMFS/px4fmu_common/init.d/rc.sensors
src/drivers/distance_sensor/vl53l0x/params.c

It turns out there was no param to enable starting the VL53L0X at startup.
Untested, based on a private report on discuss.px4.io.

sensors: Add param for VL53L0X to startup

---

src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.cpp

When @bresch analyzed a log in which the pilot switched from Altitude mode to Position mode at high speed he found that upon FlightTaskAcceleration initialization the drag calculation can produce a big step in the acceleration setpoint and hence attitude.
We discussed many possibilities to initialize with the exact right value e.g. by back calculating and so on but applying the jerk limit after the drag already solves the issue, makes the solution less complex and brittle and if there are no negative side effects for stick feeling and brake behavior in normal use nothing speaks against that.
I thought there is a reason for this order but can't remember or find any clue for that anymore so we should just test if we found any problem with this.
- I did not test this on a real vehicle. It …

StickAccelerationXY: apply jerk limit after drag

---

src/modules/commander/factory_calibration_storage.cpp
src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp

Follow-up on https://github.com/PX4/PX4-Autopilot/pull/20723
Since I had to re-add `CAL_MAG_SIDES` for QGC purposes, it's still saved in the factory calibration.
Also, if it was already saved the warning message at every boot is just annoying.
- Add `CAL_MAG_SIDES` to the factory cal filter to exclude it
- Remove the warning on `CAL_MAG_SIDES` change (silently override it).
Filter the param loading, but thin involves more changes.

Don't save `CAL_MAG_SIDES` in factory calibration

---

msg/FailsafeFlags.msg
msg/VtolVehicleStatus.msg
src/modules/commander/HealthAndArmingChecks/checks/vtolCheck.cpp
src/modules/commander/failsafe/failsafe.cpp
src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/tailsitter.cpp
src/modules/vtol_att_control/tiltrotor.cpp
src/modules/vtol_att_control/vtol_att_control_main.cpp
src/modules/vtol_att_control/vtol_att_control_params.c
src/modules/vtol_att_control/vtol_type.cpp

Many people complained that it is not possible for them to transition back to FW after a quad-chute. Depending on how far away from Home the QC happened, transitioning to FW is the only way to get the vehicle back home and land it safely. As the trigger of a quad-chute is not a reliable source to determine the system health (is real hardware failure or did a large external disturbance cause the QC?), I find it better to give the operator the responsibility to judge the situation and trigger a transition to FW if deemed safe.
Reset the failure flag (`fixed_wing_system_failure`) on re-triggering of transition to FW, which then in turn allows the transition to happen int he first place. Before was only possible to reset it with a commanded transition to MC, which many ground station …

VTOL Quad-chute: reset failure state once operator triggeres transition to FW again

---

src/modules/fw_att_control/FixedwingAttitudeControl.cpp
src/modules/fw_rate_control/FixedwingRateControl.cpp
src/modules/vtol_att_control/tailsitter.cpp

Tailsitters that require control surfaces are currently broken on main since https://github.com/PX4/PX4-Autopilot/pull/20237, as we there forgot to do a couple of required tailsitter axes transformations. We didn't notice in SITL testing because the model there has 4 motors that it uses for hover control, without the need of control surfaces and thus the FW rate controller. 
Problem found by @Jaeyoung-Lim while working on https://github.com/PX4/PX4-Autopilot/pull/20859.
Strictly follow the following convention for tailsitter: FW Attitude and FW rate controller always operate in the FW frame, meaning that roll is roll in FW, which for tailsitter means around the yaw axis in the body frame. The interfaces between modules is though always in body frame.
That enables us to do the axis …

FW Att and Rate Controller, Tailsitter: fix tailsitter frame transformations

---

Tools/simulation/jsbsim/sitl_run.sh

This is just to match the docs.
https://docs.px4.io/main/en/simulation/flightgear.html#usage-configuration-options

jsbsim: take FG_BINARY env var into account

---

src/modules/rover_pos_control/RoverPositionControl.cpp

Log file: [link](https://review.px4.io/plot_app?log=79884cfc-ef61-4605-b31b-7f78004fd226)
So, i checked out how Multi-copters were reading inputs and they are adjusting the manual_control_setpoint
`(_manual_control_setpoint.throttle + 1.f) * .5f;`
Implemented that for rover, and it seemed to fix the rover in SITL. Have not tested in real world
I noticed that when running the differential rover in sitl: `make px4_sitl gazebo_r1_rover` in manual mode, the rover immediately starts to travel backwards. 
#20886 
added
(_manual_control_setpoint.throttle + 1.f) * .5f; for thrust
not sure tbh
before: [link](https://review.px4.io/plot_app?log=79884cfc-ef61-4605-b31b-7f78004fd226)
after: [link](https://review.px4.io/plot_app?log=18069f38-872b-463a-9367-22e1aa35794f)
Related …

thrust normalization for joystick input

---

src/modules/ekf2/EKF/common.h
src/modules/ekf2/EKF/ekf.h
src/modules/ekf2/EKF2.cpp
src/modules/ekf2/EKF2.hpp
src/modules/ekf2/ekf2_params.c

- default is now a more conservative 0.15 rad/s (~8.6 deg/s) instead of the previous hard coded 20 deg/s

ekf2: new gyro bias limit parameter EKF2_GYR_B_LIM

---

msg/ActuatorTest.msg

The actuator test is published for each motor in a row. If the orb queue size is too small, messages are lost and not received in mixer_module.
ESC calibration didn't work any more on upstream PX4 main

esc_calibration: Publish actuator_test with large enough queue size

---

ROMFS/px4fmu_common/init.d/rc.sensors
src/drivers/distance_sensor/Kconfig
src/drivers/distance_sensor/tf02pro/CMakeLists.txt
src/drivers/distance_sensor/tf02pro/Kconfig
src/drivers/distance_sensor/tf02pro/TF02PRO.cpp
src/drivers/distance_sensor/tf02pro/TF02PRO.hpp
src/drivers/distance_sensor/tf02pro/parameters.c
src/drivers/distance_sensor/tf02pro/tf02pro_main.cpp
src/drivers/drv_sensor.h

None.
Benewake TF02 Pro I2C is a communication device using I2C.
TFmini driver is a communication device using UART.
I will add I2C driver for TF02 Pro.
None.
PLOTJUGGER
QGC
None.

distance_sensor: Add TF02 Pro I2C

---

src/modules/ekf2/Utility/PreFlightChecker.hpp

This is an attempt to solve preflight check errors when using optical flow sensors very close to the ground before arming. This is currently untested.
https://github.com/PX4/PX4-Autopilot/issues/20929

Increase flow preflight check innovation limit

---

src/modules/microdds_client/dds_topics.h.em
src/modules/microdds_client/microdds_client.cpp

If the DDS session is closed without stooping the client (i.e. by the Agent or due to a connection issue) the `_subs` structure is not de-initialized (`data_writer.id = UXR_DATAWRITER_ID`) and therefore when a new session is established the `*_data_writers` are not recreated. 
https://github.com/PX4/PX4-Autopilot/blob/00bfd5436a6f743fe79d6c300ab37982fcf2987f/src/modules/microdds_client/dds_topics.h.em#L52-L55
Right now the only solution is to stop and restart the client.
Fixes https://github.com/PX4/px4_ros_com/issues/175
- Added the `reset()` method to `SendTopicsSubs` which clear the structure.
- `_subs->reset()` is called right after the DDS session is deleted.
The entire `_subs` struct could be deleted and then recreated in the following cycle.

microdds_client: add _subs reset method to allow reconnections

---

src/lib/perf/perf_counter.cpp

From what address sanitizer tells me, we need to tell delete what type it is deleting.

perf: avoid leaks in dtor

---

ROMFS/px4fmu_common/init.d/rc.logging
src/modules/logger/logger.cpp
src/modules/logger/logger.h
src/modules/logger/params.c

None
I would like to automatically create a flight logbook by getting the flight time, flight start time, flight end time, flight start location, etc. from ULOG.
I want one ULOG file from first arm to power off.
I live in Japan.
The flight time of the drone in Japan country is assumed to be from "first takeoff to power off".
The drone in Japan country may move without turning off the power in the state of arm release.
PX4-Autopilot logs from boot to power off.
I may only power on and not arm.
I can create a valid ULOG file.
None
None
Logger menu
Command start
Description
Parameter selection
ULOG: start Armed!! and meny armed, disarmed..

logger: Add 1st arm to shutdown

---

src/drivers/imu/invensense/icm42688p/ICM42688P.cpp
src/drivers/imu/invensense/icm42688p/ICM42688P.hpp
src/drivers/imu/invensense/icm42688p/InvenSense_ICM42688P_registers.hpp

Looks like we got away with this because the defaults for registers in bank 1 and bank 2 were mostly acceptable.

icm42688p: fix register bank selection

---

boards/ark/fmu-v6x/init/rc.board_sensors
boards/ark/fmu-v6x/src/CMakeLists.txt
boards/ark/fmu-v6x/src/board_config.h
boards/ark/fmu-v6x/src/init.c
boards/ark/fmu-v6x/src/spix_sync.c
boards/ark/fmu-v6x/src/spix_sync.h
boards/ark/fmu-v6x/src/timer_config.cpp
platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp
platforms/nuttx/src/px4/stm/stm32_common/include/px4_arch/io_timer.h
src/drivers/imu/invensense/icm42688p/CMakeLists.txt
src/drivers/imu/invensense/icm42688p/ICM42688P.cpp
src/drivers/imu/invensense/icm42688p/ICM42688P.hpp
src/drivers/imu/invensense/icm42688p/InvenSense_ICM42688P_registers.hpp
src/drivers/imu/invensense/iim42652/CMakeLists.txt
src/drivers/imu/invensense/iim42652/IIM42652.cpp
src/drivers/imu/invensense/iim42652/IIM42652.hpp
src/drivers/imu/invensense/iim42652/InvenSense_IIM42652_registers.hpp
src/drivers/imu/invensense/iim42652/iim42652_main.cpp

The ARKV6X has two ICM42688P's and the industrial version of the same IMU the IIM42652. These IMUs support a clock input which improves performance and allows the three IMUs to be synchronized. 
https://review.px4.io/plot_app?log=8a2a2011-8b1c-47e3-bf9c-193da6f3b190
https://review.px4.io/plot_app?log=5b9e35da-24b0-4b82-b2bb-165922394e9c
https://review.px4.io/plot_app?log=ebe04309-0510-4342-a83a-01bda4013b4e
https://review.px4.io/plot_app?log=0afe68b4-721d-4827-bf18-57c8f267592d
https://review.px4.io/plot_app?log=03c524bd-bcaa-4025-b140-970f9dda5ca1
```
The IIM-42652 has a flexible clocking scheme, allowing the following internal clock sources to be used for the internal
synchronous circuitry. This synchronous circuitry includes signal conditioning, ADCs, and various control circuits and …
```

ARKV6X Enable SPIX SYNC and Enable ICM42688P IIM42652 CLKIN

---

src/drivers/distance_sensor/lightware_laser_i2c/lightware_laser_i2c.cpp

In rare occasions asking for the protocol values after setting it returned [0, 0]. I did not see any documentation for having to wait, but adding a short wait period fixes it.

lightware_laser_i2c: fix unreliable startup detection

---

src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/tailsitter.cpp
src/modules/vtol_att_control/tiltrotor.cpp
src/modules/vtol_att_control/vtol_att_control_main.cpp
src/modules/vtol_att_control/vtol_att_control_params.c
src/modules/vtol_att_control/vtol_type.cpp
src/modules/vtol_att_control/vtol_type.h

Based on https://github.com/PX4/PX4-Autopilot/pull/20913 (but basically separate). 
Previously the condition was based on hard coded height rate estimate and setpoint values and an altitude error threshold. That showed to be leading to false positives when the vehicle doesn't tightly follow the altitude ramp given by TECS to achieve a new altitude setpoint, and has become completely infeasible with the latest TECS rework that leads to non-ramped altitude setpoint changes in the tecs_status message.
For example this flight triggered a quadchute due to altitude loss (VT_FW_ALT_ERR was set to 15m, and vehicle was not able to follow TECS altitude ramp and then briefly had an uncommanded descent due to strong crosswind). 
An additional issue was that during a front transition the VT_FW_ALT_ERR …

VTOL: Rework altitude-loss quad-chute

---

src/modules/commander/HealthAndArmingChecks/checks/offboardCheck.cpp
src/modules/commander/failsafe/failsafe.cpp

- 64 bit time in microseconds stored in a 32 bit float quickly becomes problematic
- fixes https://github.com/PX4/PX4-Autopilot/issues/20944
@ecmnet

commander: avoid timestamp implicit float conversions

---

ROMFS/px4fmu_common/init.d-posix/airframes/4001_gz_x500
ROMFS/px4fmu_common/init.d-posix/airframes/4002_gz_x500_depth
ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator
src/modules/simulation/gz_bridge/CMakeLists.txt
src/modules/simulation/gz_bridge/GZBridge.cpp
src/modules/simulation/gz_bridge/GZBridge.hpp
src/modules/simulation/gz_bridge/GZMixingInterfaceESC.cpp
src/modules/simulation/gz_bridge/GZMixingInterfaceESC.hpp
src/modules/simulation/gz_bridge/GZMixingInterfaceServo.cpp
src/modules/simulation/gz_bridge/GZMixingInterfaceServo.hpp
src/modules/simulation/gz_bridge/module.yaml

- existing SIM_GZ outputs -> SIM_GZ_EC (ESCs)
- new SIM_GZ_SV for servos (not yet fully implemented)

simulator/gz_bridge: split actuator outputs for ESCs and servos

---

src/modules/mavlink/CMakeLists.txt

This is primarily noise that makes it more likely people will ignore the rest of the output. Any errors will still be printed, otherwise regular STDOUT is logged to a file in the build directory.

mavlink: generate mavlink quiet by default (stdout redirected to log file)

---

src/drivers/uavcan/CMakeLists.txt
src/drivers/uavcannode/CMakeLists.txt
src/drivers/uavcannode/uavcan_driver.hpp

- keep drivers/uavcannode cmake in sync with drivers/uavcan
Silence this noise for now, it's not that hard to fix properly when the time comes, but will require a submodule update.

drivers/uavcan: silence cmake deprecation warning for now

---

msg/tools/generate_microRTPS_bridge.py

ROS2 Humble was not supported when using the mircoRTPS bridge to do offboard control
- As @TSC21 has done a while ago for galactic: https://github.com/PX4/PX4-Autopilot/commit/f9fe0e3746d9df16b521b80b414da8b4cffd7d3c

Add support for ROS2 Humble for the microRTPS bridge

---

Tools/simulation/gz/models/rc_cessna/model.sdf
src/modules/simulation/gz_bridge/GZMixingInterfaceServo.cpp

Makes models work for everyone, allowing them to go into fuel as a common resource.

Remove proceeding px4_ from servos in gazebo model

---

src/lib/tecs/TECS.cpp

We want to avoid going into stall, when a FW is changed from airspeed to airspeedless altitude mode. In this case, we want to avoid reducing the throttle kcommand. However, when switching into the airspeedless mode, the throttle integrator term in TECS is discarded. This could reduce the throttle command, when switching into airspeedless mode.
If in airspeedless mode, add the throttle integrator term to the throttle setpoint, if the integrator term is positive. This should avoid reducing airspeed when switching to airspeedless mode.

TECS airspeedless throttle improvement.

---

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp

Sudden altitude increase due to vehicle switching out of first-order-hold (FOH) climb. 
Eg reported here: 
https://discord.com/channels/1022170275984457759/1064965130472927294/1065009827228700733
Remove factor of 2.0 to determine distance to a POSITION WP where FOH is deactivated and the vehicle achieves altitude through LOITER mode. Instead check if the switch from POSITION to LOITER has already happened, and in that case never again switch out of LOITER until altitude is reached (at which point Navigator anyway accepts the WP). 
Keep some factor, but maybe reduce it. Here is how it could look (with the SITL standard VTOL), for factors of 1, 1,2  and 1.5:
The 1.5 factor has the nicest looking outcome, but with the downside of increasing the chance to of switching out of the …

FWPositionController: remove factor of 2 for switching to LOITER to achieve altitude setpoint

---

platforms/posix/src/px4/common/drv_hrt.cpp
platforms/posix/src/px4/common/lockstep_scheduler/include/lockstep_scheduler/lockstep_components.h
platforms/posix/src/px4/common/lockstep_scheduler/include/lockstep_scheduler/lockstep_scheduler.h
platforms/posix/src/px4/common/lockstep_scheduler/src/lockstep_components.cpp

The static object is destroyed on at_exit while threads might still be inside a CS. This can lead to a hanging process.
Cleaner would be to gracefully stop the threads.
According to https://linux.die.net/man/3/pthread_cond_destroy: Attempting to destroy a condition variable upon which other threads are currently blocked results in undefined behavior.

lockstep_scheduler: avoid pthread_cond_destroy on at_exit

---

src/modules/mavlink/mavlink_main.cpp

This replaces #20622.
With this PR, we always forward MAVLink traffic to/from USB.
FYI @DonLakeFlyer

mavlink: always forward messages on USB

---

msg/FailsafeFlags.msg
src/modules/commander/Commander.cpp
src/modules/commander/HealthAndArmingChecks/checks/flightTimeCheck.cpp
src/modules/commander/HealthAndArmingChecks/checks/flightTimeCheck.hpp
src/modules/commander/HealthAndArmingChecks/checks/modeCheck.cpp
src/modules/commander/ModeUtil/mode_requirements.cpp
src/modules/commander/UserModeIntention.cpp
src/modules/commander/commander_params.c
src/modules/commander/failsafe/emscripten_template.html
src/modules/commander/failsafe/failsafe.cpp
src/modules/commander/failsafe/framework.cpp

This is a follow up to https://github.com/PX4/PX4-Autopilot/pull/19578, where the max wind speed and flight time exceeded RTLs were introduced. 
What changed:
- improve parameter description
- add warning when approaching max flight time (every 1 min starting from 90% of the max flight time, or then if <60s)
- allow switching out of high wind or flight time exceeded RTL, but only into a manual mode. Do this by adding an extra requirement to Mission, Loiter, FollowMe and Orbit (`mode_req_wind_and_flight_time_compliance`).
It also incorporates a couple of Commander fixes by @bkueng that enable these extended checks.

Commander: UX improvements on max wind and max flight time RTL

---

ROMFS/px4fmu_common/init.d/rc.fw_defaults
ROMFS/px4fmu_common/init.d/rc.vtol_defaults
msg/FailsafeFlags.msg
src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.cpp
src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.hpp
src/modules/commander/commander_params.c
src/modules/commander/failsafe/failsafe.cpp

Replaces https://github.com/PX4/PX4-Autopilot/pull/18787 and https://github.com/PX4/PX4-Autopilot/pull/19897.
- Bad operator notification when flying in GPS-denied areas with vehicle that is capable of keeping a valid position estimate for some time. The user just gets a "GPS invalid" warning, but then nothing anymore until the system switches into position-loss failsafe
- as the GPS-denied areas are rather local, it can be beneficial to start a RTL if the position is still valid but in-accurate to fly out of this area. Also, if the vehicle then loses position completely, the vehicle already started to fly towards home and it should be simpler to manually proceed in this direction
- improve param description of COM_POS_FS_EPH and set it to 50 for VTOL and FW
- add local position low …

Commander: add GPS-denied low position accuracy warning and RTL

---

.vscode/cmake-variants.yaml

- Fixes typo in Cube Orange build target config
Fixes #17745

vscode: change cubeorange build target

---

src/modules/commander/HealthAndArmingChecks/checks/airspeedCheck.cpp
src/modules/commander/HealthAndArmingChecks/checks/airspeedCheck.hpp

@dagar @ryanjAA as discussed yesterday. 
Also improved the messaging a bit.

Commander: use FW_AIRSPD_MAX as threshold for airspeed preflight checks

---

src/modules/fw_autotune_attitude_control/fw_autotune_attitude_control_params.c

The name "Aux input" is opaque unless you know what it is. I've tried to make it clear that this is a map to a channel defined in RC_MAP_AUXn
Relates to #2163

FW_AT_MAN_AUX - define what an Aux input is

---

.ci/Jenkinsfile-compile

Adds Holybro kakuteh7v2 & Kakuteh7mini to Travis CI for building and deployment to S3 for QGC
Both Board ID was added in QGC here: https://github.com/mavlink/qgroundcontrol/pull/10554

ci: build and deploy kakuteh7v2 & Kakuteh7mini

---

src/modules/ekf2/EKF/common.h
src/modules/ekf2/EKF/covariance.cpp
src/modules/ekf2/EKF/ekf.h
src/modules/ekf2/EKF/vel_pos_fusion.cpp
src/modules/ekf2/EKF2.cpp
src/modules/ekf2/EKF2.hpp
src/modules/ekf2/ekf2_params.c

- EKF2_AID_MASK accel bias inhibit moves to EKF2_IMU_CTRL
- gyro bias can now also be inhibited (currently only via EKF2_IMU_CTRL, but more criteria could be added)

ekf2: new EKF2_IMU_CTRL parameter and gyro bias inhibit mechanism

---

ROMFS/px4fmu_common/init.d-posix/airframes/10042_sihsim_xvert
ROMFS/px4fmu_common/init.d-posix/airframes/1041_gazebo-classic_tailsitter

The CA params for the geometry are wrong (frames are symmetric). 
Used to be part of https://github.com/PX4/PX4-Autopilot/pull/20558, but better keep unrelated stuff separated.
Tested the SITL, flies alright.

ROMFS: tailsitter SITL and SIH: fix motor allocation geometry

---

src/lib/sensor_calibration/Accelerometer.hpp
src/lib/sensor_calibration/Gyroscope.hpp
src/lib/sensor_calibration/Magnetometer.hpp

- the thermal offsets are an optional correction applied to the raw data, so when updating an existing calibration offset with new learned bias we don't want this incorporated
Only a problem if you're using factory temperature calibration (majority of users aren't) and `SENS_IMU_AUTOCAL = 1`.

lib/sensor_calibration: BiasCorrectedSensorOffset() don't incorporate thermal offsets

---

.vscode/settings.json

The custom vscode settings in the repo overrule the  user's settings.
Fixes #21062 
Remove some of the settings that are not related to building the project or code formatting.

remove some vscode settings

---

platforms/nuttx/src/px4/stm/stm32f1/CMakeLists.txt

The `arch_spi` library is missing for the STM32 F1 targets.
Fix linking error for STM32 F1 targets.

add SPI to stm32f1

---

src/modules/commander/Commander.cpp

We have had problems with status leds not properly updating when pre-arm checks are done. Basically, the blinking status leds often show some wrong/previous value (e.g. fast blinking red light even if the previous preflight checks passed).
Always update the status leds when the result from prearm checks change; set "_status_changed = true;", which is then later passed to rgbled_set_color_and_mode
Tested on Pixhawk 5x

Update status leds every time when prearm check status changes

---

src/modules/ekf2/ekf2_params.c

This should be disabled by default until we have more real world testing and can tune EKF2_GRAV_NOISE.

ekf2: disable new gravity fusion by default

---

src/drivers/qshell/posix/qshell.cpp
src/drivers/qshell/posix/qshell.h

Qshell instantiates a new instance for each command with a new subscription to the return value topic. This will cause it to see any old topic data until the new one comes in. This PR changes the subscription to be static so that it will not see the old topic data and only see new updated topic information.

Qshell static subscription

---

platforms/common/include/px4_platform_common/log.h
platforms/qurt/include/qurt_log.h

Qurt drops PX4_INFO_RAW logs currently. This PR sends them over to the Linux side for display.

Qurt px4_info_raw send to apps for display

---

boards/px4/fmu-v6x/nuttx-config/include/board.h

Backport of https://github.com/PX4/PX4-Autopilot/pull/20974.

[BACKPORT v1.13] boards: px4_fmu-v6x add pulldowns to GPIO pins UART7 RTS and UART7 CTS

---

src/lib/npfg/npfg.cpp
src/lib/npfg/npfg.hpp
src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp

Rearranged the interaction between the FwPosController and npfg. the guidance logic should not be concerned with the waypoint triplets directly. The FwPosController converts the triplets into a path setpoint which is fed into the npfg navigation logic. This is part of separating the npfg into smaller controllers with cleaner API.
- Move the navigateXX function into the FwPosController. They are responsible to convert the setpoint triplets into a path setpoint.
- Update the npfg to only rely on one single navigatePath input function, which is used to navigate to the desired path.
- Tested in SImulation using the standard_vtol gazebo simulation.

Rearrange npfg use path input

---

src/modules/mavlink/mavlink_log_handler.cpp
src/modules/mavlink/mavlink_main.cpp

When upgrading a cube orange to 1.13 we found log download by USB to not work when there was 50 or more logs on the target. In addition for less than 50 logs, it is necessary to request the list of logs two times for it to be generated. This is assuming we use QGroundControl (which requests 50 entries at a time with LOG_REQUEST_LIST), and USB connection.
There is two issues that cases this:
- When opening the mavlink module by USB auto-start (from https://github.com/PX4/PX4-Autopilot/pull/16180) stdout and stderr is not open (unsure if stderr is a problem). This would cause file descriptor 1 to be reused when generating the log list, and the log list would be corrupted by an other part of the module erroneously writing to stdout. I could not replicate this in main, but I believe this is …

Mavlink log download by USB fix (cube orange, possible others)

---

src/modules/navigator/rtl.cpp

**Update 2023-02-01**
This PR does not longer include the original MC descend alterations in RTL, but instead just fixes the addtional issues found int the process. This PR now:
- Fixes VTOL FW landing bug
- RTL_STATE_HEAD_TO_CENTER is not longer dependent on whether loiter is used or not.
- MC will use descend state, independent of whether loiter is used or not.
- Fix acceptance radius for mission item prior to VTOL transition by setting _mission_item.vtol_back_transition
The main problem I set out to solve was that a VTOL RTL is too slow/consumes to much battery when landing at rally points with altitude different than home altitude. This is because MPC_LAND_ALT1/MPC_LAND_ALT2 do not consider rally point altitude, and it is therefor not …

RTL fixes and improvements for VTOL vehicles

---

src/lib/battery/battery.cpp
src/lib/battery/battery.h

When looking back at https://github.com/PX4/PX4-Autopilot/pull/20729 I found that there were some additional comments:
- use a constant instead of a magic number
addresses https://github.com/PX4/PX4-Autopilot/pull/20729#discussion_r1057367977
- fix code comment typo
addresses https://github.com/PX4/PX4-Autopilot/pull/20729#discussion_r1057368047
Should not change functionality.

Battery: address two comments from #2242

---

ROMFS/px4fmu_common/init.d-posix/airframes/1013_gazebo-classic_iris_vision

- `ROMFS/px4fmu_common/init.d-posix/airframes/1013_gazebo-classic_iris_vision` was wrongly loading the base iris model.
- The GPS is the default source for altitude estimation (`EKF2_HGT_REF=1`) therefore `EKF2_GPS_CTRL` was never set to 0 but remained 7.
- Fix the base iris airframe name.
- Set `EKF2_HGT_REF=3` as default values in order to use vision for altitude estimation. `EKF2_GPS_CTRL`  is now correctly set to 0.

gazebo-classic_iris_vision: fix airframe include and default parameters

---

src/drivers/imu/bosch/bmi088/BMI088.hpp
src/drivers/imu/bosch/bmi088/BMI088_Accelerometer.cpp
src/drivers/imu/bosch/bmi088/BMI088_Gyroscope.cpp

- new FIFO_RESET state used to give the sensor more time after successful configuration before sampling begins

drivers/imu/bosch/bmi088: add more time between configure and FIFO_READ

---

ROMFS/px4fmu_common/init.d-posix/airframes/4003_gz_rc_cessna
ROMFS/px4fmu_common/init.d-posix/airframes/4004_gz_standard_vtol
ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator
src/modules/simulation/sensor_airspeed_sim/SensorAirspeedSim.cpp
src/modules/simulation/sensor_airspeed_sim/SensorAirspeedSim.hpp
src/modules/simulation/sensor_airspeed_sim/parameters.c

This is a follow-up PR of https://github.com/PX4/PX4-Autopilot/pull/21114, where the airspeed sensor was enabled for all vehicles in gz.
This PR adds a parameter to optionally enable the module and dynamically turn on and off the sensor publishing
- `SENS_EN_ARSPDSIM`: Enable/disable the simulated airspeed sensor module
- `SIM_ARSPD_FAIL`: Inject failure to the simulated airspeed sensor on runtime
The sensor is now only enabled for `rc_cessna` and `standard_vtol`
As discussed with @dagar, we could always run the module and check whether `SENS_EN_ARSPDSIM` is true to publish the sensor data. However, I think separating the two use cases explicitly makes a more clear separation of the two use cases.
Tested with the `standard_vtol`
```
make px4_sitl gz_standard_vtol
```
- This is a follow-up …

Optionally enable airspeed sim and inject failure

---

src/drivers/linux_pwm_out/CMakeLists.txt

When compiling `linux_pwm_out` I got linking errors related to `MixingOutput`:
```
../../src/drivers/linux_pwm_out/linux_pwm_out.cpp:348: error: undefined reference to 'MixingOutput::printStatus() const'
../../src/drivers/linux_pwm_out/linux_pwm_out.cpp:47: error: undefined reference to 'MixingOutput::MixingOutput(char const*, unsigned char, OutputModuleInterface&, MixingOutput::SchedulingPolicy, bool, bool)'
../../src/drivers/linux_pwm_out/linux_pwm_out.cpp:50: error: undefined reference to 'MixingOutput::setAllMinValues(unsigned short)'
../../src/drivers/linux_pwm_out/linux_pwm_out.cpp:51: error: undefined reference to 'MixingOutput::setAllMaxValues(unsigned short)'
../../src/drivers/linux_pwm_out/linux_pwm_out.cpp:322: error: undefined reference to 'MixingOutput::loadMixer(char const*, …
```

linux_pwm_out must link mixer_module

---

src/modules/ekf2/EKF/common.h
src/modules/ekf2/EKF/mag_control.cpp

When mag data stops in air, EKF2 never sets the fusion to inactive. This is problematic as other parts of the system are generally relying on those status flags to change their behavior.
As for the other sources, stop the fusion (and clear the status flags) when there is no new data for some time (1s timeout).
SITL 
Note that the "good for control" flag goes to `true` because there is no criterion defining it if there is no mag aiding.

ekf2: stop mag fusion when there is no data anymore

---

src/modules/navigator/mission.cpp
src/modules/navigator/navigator_main.cpp

At the start of a RTL using a mission landing, `position setpoint.type` is IDLE, and valid=false, thus FW position controller switch to `FW_POSCTRL_MODE_OTHER` which sets `_tecs.reset_state()`;
_land_start_index is used to to start the mission from this item index, and to avoid to publish a triplet.current.type=IDLE, we need to fill it with the actual position setpoint that the vehicle should go to at the start of a mission landing.
This was like this ever, but it only surfaced not because previously we didn't do a TECS reset on receiving IDLE setpoints in the FW Position Controller.

Navigator: set _land_start_index to first item with a position after the marker

---

src/modules/fw_path_navigation/FixedwingPositionControl.cpp
src/modules/fw_path_navigation/FixedwingPositionControl.hpp
src/modules/fw_path_navigation/fw_path_navigation_params.c
src/modules/fw_path_navigation/runway_takeoff/RunwayTakeoff.cpp
src/modules/navigator/land.cpp
src/modules/navigator/mission_block.cpp
src/modules/navigator/mission_block.h

When triggering a land outside of a mission (e.g. by switching to Land mode, sending DO_LAND command or typing `commander land` in shell), vehicle does a fly away. Instead if should come down at current location and "land" more or less smoothly. 
- rename existing landing method `control_auto_landing` to `control_auto_landing_straight()`
- add new landing method `control_auto_landing_circular()`
--> `control_auto_landing_circular()` is used if `_position_setpoint_previous_valid=false`, which is the case for landings outside of missions. At some point we could add a flag to [CMD_NAV_LAND](https://mavlink.io/en/messages/common.html#MAV_CMD_NAV_LAND) to be able to distinguish straight and circular landings this way (there may be valid use cases where circular mission landings are preferred …

FW: support Land command outside of a mission

---

src/modules/fw_path_navigation/FixedwingPositionControl.cpp

Possible replacement for https://github.com/PX4/PX4-Autopilot/pull/20992, and follow up to https://github.com/PX4/PX4-Autopilot/pull/21012.
Controller sometimes switches to loiter even though the altitude of a waypoint could also have been reached by just proceeding fling straight towards waypoint (while climbing). 
https://github.com/PX4/PX4-Autopilot/pull/21012#discussion_r1097682996
Remove the loiter_radius from the logic, only consider acceptance radius. That normally means that the vehicle turns in later for the loiter to achieve altitude.

FWPositionControllre: only check acceptance radius to swich to loiter to achieve altitude

---

boards/mro/pixracerpro/src/init.c

Fixes non-working FRAM module - now you will be able to save parameters even if not inserting an SD card.
Compared folder to CZ OEM and found out a config function was missing at init.c
Tested with current revision D, however I would appreciate if you help me verify.

Fix reported FRAM issue

---

boards/mro/pixracerpro/src/init.c

Corresponding PR to v1.13.x branch
Enable FRAM for mRo PixracerPro.

Configure FRAM for PixracerPro

---

ROMFS/px4fmu_common/init.d-posix/airframes/10040_sihsim_quadx
ROMFS/px4fmu_common/init.d-posix/airframes/10041_sihsim_airplane
ROMFS/px4fmu_common/init.d-posix/airframes/10042_sihsim_xvert
ROMFS/px4fmu_common/init.d-posix/airframes/4001_gz_x500
ROMFS/px4fmu_common/init.d-posix/airframes/4002_gz_x500_depth
ROMFS/px4fmu_common/init.d-posix/airframes/4003_gz_rc_cessna
ROMFS/px4fmu_common/init.d-posix/airframes/4004_gz_standard_vtol
ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator
src/modules/simulation/sensor_baro_sim/parameters.c
src/modules/simulation/sensor_gps_sim/parameters.c
src/modules/simulation/sensor_mag_sim/parameters.c

Simulated sensor instances were being run in the background when simulations such as SIH, Gazebo is being run.
Since https://github.com/PX4/PX4-Autopilot/pull/21126, we have a sensor instance that is optionally enabled for just `plane` and `standard_vtol` models.
This PR propagates this change to other sensors and makes enabling/disabling simulated sensor instances more explicit
Added parameters are
- `SENS_EN_MAGSIM`: Enable simulated magnetometers
- `SENS_EN_GPSSIM`: Enable simulated GPS
- `SENS_EN_BAROSIM`: Enable simulated barometer
- Tested in Gazebo
```
make px4_sitl gz_standard_vtol
```
- @bperseghetti @ahcorde I noticed that the Gazebo models are still missing GPS, Baro and Magnetometers in the model. I think we would probably want to disable the simulated instances and simulate …

Optionally enable sensor simulations

---

platforms/common/include/px4_platform_common/tasks.h
src/modules/logger/log_writer.h
src/modules/logger/log_writer_file.cpp
src/modules/logger/log_writer_file.h
src/modules/logger/logger.cpp
src/modules/logger/logger.h
src/modules/logger/watchdog.cpp
src/modules/logger/watchdog.h

- log_writer_file: do not call close() with mutex held 
- reduce boost priority to PX4_WQ_HP_BASE - 6. @dagar we can adjust this after your prio changes.
- add cli command 'trigger_watchdog' to manually trigger watchdog
- add perf counters when triggering watchdog
- reduce top measurement to 300ms
- restore priorities after 1.5s
There are precautions in case the SD card code itself has a busy-loop.

Logger: watchdog updates

---

src/modules/mc_att_control/mc_att_control.hpp
src/modules/mc_att_control/mc_att_control_main.cpp

No manual yaw control when landed. This e.g. makes preflight checks for yaw actuators impossible in any attitude-controlled mode (for hovering vehicles with yaw control not through differential thrust like tiltrotors or tailsitters). It's also quite confusing to have actuation of roll/pitch but not yaw.
Remove _landed check for _reset_yaw_sp. 
Note that the integrals still get reset independently in the rate controller (for all axes). 
I wonder if we the other two conditions (attitude_setpoint_generated and vtol_in_transition_mode) are really required as well. Why do you only want to reset yaw if (!attitude_setpoint_generated), and is the yaw reset during VTOL transition not only required for tailsitters, and there handled in the tailsitter.cpp (as the comment hints as well)? 
Minimal …

MCAttitudeController: remove reset of yaw_sp when landed

---

Tools/msg/generate_msg_docs.py

uOrb topics documentation haven't build since at least September last year. I think the path to messages must have changed, or to the tool.
In either case, this should fix it.
FYI all the names have changed from snake to camel case, so will have to delete some of the removed docs. Might be some related docs updates needed to.

generate_msg_docs.py - fix path to messages

---

src/modules/microdds_client/microdds_client.cpp
src/modules/microdds_client/microdds_client.h

Allows to use a custom FastDDS configuration on the Agent side.

microdds_client: fix -l flag and add -c for custom participant configuration

---

src/modules/sensors/sensors.cpp

All uORB topics changed case at some point recently. Fixed this one as it appears in docs.

Sensors.cpp - case the uorb topics like SensorGyro

---

src/modules/payload_deliverer/module.yaml

Fixing typos in uorb names, as I find them

VehicleCommandAck typo on module docs

---

Tools/setup/ubuntu.sh

When looking into https://github.com/PX4/PX4-Autopilot/issues/21130 I realized this duplication in the script.
Only add the gazebo binary source once.
I successfully ran this exact script on a fresh Ubuntu 22.04.1 VM with `sudo apt-get upgrade` before to not run into https://github.com/PX4/PX4-Autopilot/issues/21130.

ubuntu.sh: only add gazebo source once on 22.04

---

ROMFS/px4fmu_common/init.d/rc.fw_defaults
msg/FailsafeFlags.msg
src/modules/commander/HealthAndArmingChecks/HealthAndArmingChecks.cpp
src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.cpp
src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.hpp
src/modules/commander/HomePosition.cpp
src/modules/commander/HomePosition.hpp
src/modules/commander/commander_params.c
src/modules/mavlink/streams/HIGH_LATENCY2.hpp

- checks for GPS validity in Commander (used for setting Home and for triggering warning if GPS data is bad) are linked to failsafe thresholds (eg. COM_POS_FS_EPH), so don't reflect if the GPS is currently used or not by the estimator
- decouple GPS checks for Home position setting (with hard coded thresholds)
- change "GPS invalid" warning to "GPS stopped being fused warning", that acts on real estimator feedback not separate thresholds
Previously failsafe_flags.gps_position_invalid was used for both. Beside it being two different things that really shouldn't have the same thresholds, it for me also doesn't belong into the failsafe flags as it doesn't trigger any failsafe (only losing global/local position does). 
One diff in the Home position setting is that I dropped (for now) the …

Commander: rework GPS quality thresholds for Home position setting and GPS invalid warning

---

src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/tailsitter.cpp
src/modules/vtol_att_control/tailsitter.h
src/modules/vtol_att_control/tiltrotor.cpp
src/modules/vtol_att_control/tiltrotor.h
src/modules/vtol_att_control/vtol_type.cpp
src/modules/vtol_att_control/vtol_type.h

1. The front transition logic for standard vtol used the minimum transition time for completing a front transition in case airspeed was not valid. It makes more sense to use the open loop transition time.
2. The 3 VTOL types shared a lot of common logic regarding the transition completion and this can be consolidated.
Fix 1) and consolidate logic.

vtol_att_control: Consolidate logic for front transiton completion

---

src/lib/tecs/TECS.cpp
src/lib/tecs/TECS.hpp
src/modules/fw_path_navigation/FixedwingPositionControl.cpp

`FW_T_SINK_MIN` is not used anymore, and instead `FW_T_SINK_MAX` is used for determine `STE_rate_min`. In my eyes this is wrong, as eg the predicted throttle should already be at 0 when the `STE_rate.setpoint` is at the rate achieved at `FW_T_SINK_MIN`, and not only when it's at `FW_T_SINK_MAX`. 
https://github.com/PX4/PX4-Autopilot/blob/be6bba68b0f5abc905c02bd11a376c21990cf187/src/lib/tecs/TECS.cpp#L585-L586
Came in with https://github.com/PX4/PX4-Autopilot/pull/20443, before that change it was as proposed again through this PR (https://github.com/PX4/PX4-Autopilot/blob/4bcbfec6cb2c810e8df30ef74cea16db2fffb84a/src/lib/tecs/TECS.cpp#L551).
Use FW_T_SINK_MIN to determine STE_rate_min.
For calculating `min_tas_rate_sp` we could maybe keep using `FW_T_SINK_MAX`, though it doesn't have a …

tecs: use FW_T_SINK_MIN for STE_rate_min

---

boards/px4/fmu-v6x/init/rc.board_sensors

When I was flying V6X on Skynode I found that the values from the MAG0 were not correlated with MAG1. Only z-axis was correct. y-axis and x-axis were inverted.
set orientation of bmm150 to zero.
- Tested on Skynode. Multiple test flights were performed.
before: x-axis of mag0 correlated with y-axis of mag1
after set rotation to zero: x-axis of mag0 correlates now with x-axis of mag1

Fixed Skynode orientation

---

README.md

Previously the Maintainer, Board compatibility & Roadmap were outdated
1. Reorganize the maintainer list (need confirmation from individuals)
2. Update supported hardware list (mostly in sync with docs & checked link access)
3. Added note on outdated Roadmap
This is the first step after the community coordination call from January 30th: [Document Link](https://docs.google.com/document/d/1dnEmOeciJ4fdhNqPT9SZv9-5on6P-9ajKDf-wVV0B-A/edit?usp=sharing)

Update README: Maintainers, Boards, Roadmap

---

src/modules/commander/HealthAndArmingChecks/checks/magnetometerCheck.cpp

When running in HIL simulation, the number of valid magnetometers is always 0 because of the `num_enabled_and_valid_calibration` variable in `commander/HealthAndArmingChecks/checks/magnetometerCheck.cpp`.
The root cause is that we do not increment `num_enabled_and_valid_calibration` if we are in HIL mode.
Increment `num_enabled_and_valid_calibration` in `magnetometerCheck.cpp`/`checkAndReport` if we are in HIL mode:
```cpp
if (context.status().hil_state == vehicle_status_s::HIL_STATE_ON) {
is_calibration_valid = true;
num_enabled_and_valid_calibration++;
}
```
By incrementing `num_enabled_and_valid_calibration` it allows the check to pass and not throw a false positive:
```cpp
if (!had_failure && !context.isArmed()) {
consistencyCheck(context, reporter);
if …
```

commander: fixes valid mag count in HIL

---

src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/streams/GPS_GLOBAL_ORIGIN.hpp

When requesting a message from a stream that is not active we start the
stream with interval=0 and call the request method once. For all streams
this works fine except the gps_global_origin. For this one the request method
is actually overidden to throttle down the rate and not just send out the message.
This will cause this message to never being sent on request if the stream
is not active by default.
@DanielePettenuzzo fyi

Fix gps global origin stream

---

boards/px4/fmu-v6x/init/rc.board_sensors

Reverts part of 3c10e34a49d964f85eacf186153097d102fd2578 not applicable to V1.13 VER/REV system.
```
[boot] Rev 0x1 : Ver 0x2 V6X21
reset done, 10 ms
[boot] Fault Log info File No 4 Length 3177 flags:0x01 state:1
[boot] Fault Log is Armed
sercon: Registering CDC/ACM serial driver
sercon: Successfully registered the CDC/ACM serial driver
HW arch: PX4_FMU_V6X
HW type: V6X21
HW version: 0x00000002
HW revision: 0x00000001
FW git-hash: 3cb529184ec9c715367ac1ce48cec29b17bab1b5
FW version: 1.13.2 0 (17629696)
FW git-branch: release/1.13-pr-cuav-fix
OS: NuttX
OS version: Release 12.0.0 (201326847)
OS git-hash: 78abbf36c057f2a62011d7d208134d50e95d9916
Build datetime: Mar  1 2023 06:02:10
Build uri: localhost
Build variant: default
Toolchain: GNU GCC, 9.3.1 20200408 (release)
PX4GUID: …
```

CUAV Pixhawk V6X Baro & Mag won't start on stable | px4_fmu-v6x:Fix CUAV Sensor Set startup

---

src/drivers/distance_sensor/lightware_sf45_serial/CMakeLists.txt
src/drivers/distance_sensor/lightware_sf45_serial/Kconfig
src/drivers/distance_sensor/lightware_sf45_serial/lightware_sf45_serial.cpp
src/drivers/distance_sensor/lightware_sf45_serial/lightware_sf45_serial.hpp
src/drivers/distance_sensor/lightware_sf45_serial/lightware_sf45_serial_main.cpp
src/drivers/distance_sensor/lightware_sf45_serial/module.yaml
src/drivers/distance_sensor/lightware_sf45_serial/sf45_commands.h

Lightware SF45/B rotating distance sensor driver that publishes distance and yaw angle (through the obstacle distance sensor message). Preliminary testing I show the sensor is able to detect obstacles:
I am able to publish to obstacle distance msg and I see valid distance values moving through the bins. It is also stopping before collision with an obstacle if within CP distance defined in the parameters (tested using 3m).
Ardupilot has a working driver that can be used as a reference [here](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Proximity/AP_Proximity_LightWareSF45B.cpp)
Additionally, Lightware has a sample cpp library on their github. 
Serial driver defaults to TEL1 due to the power requirements of the sensor which is documented …

LightwareLidar SF45/B rotating sensor serial driver

---

Tools/setup/ubuntu.sh

- Ingition Fortress was installed instead of Gazebo Garden.
- Deprecated `apt-key` was used in Ubuntu 22.04
Fixes #21163
- On Ubuntu 22.04, install only Gazebo Garden
- Key is stored in `/usr/share/keyrings/`

setup/ubuntu.sh: Only install Gazebo Garden for Ubuntu 22.04

---

src/modules/navigator/rtl.cpp
src/modules/navigator/rtl.h

Wrong RTL time calculation when global position is invalid (never published) but home position is set.
Home position can also be set with the raw gps lat/lon before EKF publishes a global_position estimate.
Check if global_position estimate has been updated recently (<10s) before running the functions in `rtl::on_inactive()` (`calc_and_pub_rtl_time_estimate` and `find_RTL_destination()`). 
Running `find_RTL_destination()` even without valid global position didn't show any problems but I included it here as it seems correct to me.
Use some other flag for global_position validity?

RTL: only do calculations in is-inactive if global position is recent

---

Tools/msg/templates/ucdr/msg.h.em

This adds a few protections on the timestamps for incoming data through microdds (typically from ROS 2). We're at the mercy of these timestamps being manually populated correctly, so I think a few simple protections will save us some headaches.
- if timestamp (or timestamp_sample) unpopulated fill it with current hrt_absolute_time()
- if using provided timestamp don't allow it to exceed current hrt_absolute_time()

ucdr msg template add timestamp protections

---

src/modules/commander/failsafe/framework.h

There needs to be a default statement for the compiler to work when this function is called. Apparently it is never called in the codebase.

Fix missing return in actionStr function

---

ROMFS/px4fmu_common/init.d-posix/airframes/4005_gz_x500_vision
ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt
Tools/simulation/gz/models/x500_vision/model.config
Tools/simulation/gz/models/x500_vision/model.sdf
src/modules/simulation/gz_bridge/GZBridge.cpp
src/modules/simulation/gz_bridge/GZBridge.hpp

This PR adds a model to simulate visual odometry in Gazebo
- Added the `x500_vision` model with the `odometry_publisher` included
- Added a subscription to the `gz_bridge` to consume odometry with covariance messages
@ahcorde FYI
```
make px4_sitl gz_x500_vision
```
- This includes https://github.com/PX4/PX4-Autopilot/pull/21136

Add visual odometry support for Gazebo

---

.vscode/tasks.json
platforms/posix/Debug/launch_sitl.json.in

Since posix airframe are simulator specific, `PX4_SIM_MODEL` and `GZ_SIM_MODEL` are not the same: `PX4_SIM_MODEL=gz_${GZ_SIM_MODEL}`.
`PX4_SIM_MODEL` has two different usages during the startup of the simulation:
1. It is used to look for the right airframe unless `PX4_SYS_AUTOSTART` is defined. In this scenario `PX4_SIM_MODEL` **must** contain the `gz_` prefix.
2. It is used to look for the right gz model unless `GZ_SIM_MODEL` or `GZ_SIM_MODEL_NAME` are defined. In this scenario the prefix is not needed: if it is present it is automatically removed.
In `launch_sitl.json` the prefix was missing and no `PX4_SYS_AUTOSTART` was defined.
- Add prefix
The post debug task was referencing to Ignition Fortress syntax
- Update to Gazebo Garden syntax

VScode: fix tasks.json and launch_sitl.json after ign -> gazebo renaming

---

msg/FailsafeFlags.msg
src/modules/commander/HealthAndArmingChecks/Common.hpp
src/modules/commander/HealthAndArmingChecks/checks/modeCheck.cpp
src/modules/commander/HealthAndArmingChecks/checks/modeCheck.hpp
src/modules/commander/HealthAndArmingChecks/checks/rcAndDataLinkCheck.cpp
src/modules/commander/HealthAndArmingChecks/checks/rcAndDataLinkCheck.hpp
src/modules/commander/ModeUtil/mode_requirements.cpp
src/modules/commander/failsafe/framework.cpp

When switching to a manual mode (Manual, Acro, Stabilized, Altitude, Position) without a stick input source it is currently possible to arm and stay in the mode.
Fixes https://github.com/PX4/PX4-Autopilot/pull/20172#discussion_r988214569
1. **[untouched]** Stick input disabled and not required -> Nothing
2. **[untouched]** Stick input present but lost in flight -> Failsafe NAV_RCL_ACT (tested with RTL only!)
3. **[mandatory]** Manual mode (Manual, Acro, Stabilized, Altitude, Position) and disabled or unavailable stick input -> Error
4. **[nice to have]** Stick input enabled but not present when not required -> Warning
|  | RC required | RC not required |
|---|---|---|
| RC disabled | Error 3. | OK 1. |
| RC enabled not present | Error 3. | Warn 4. |
| RC enabled and present | OK | OK |
- …

Manual control mode requirement for manual modes

---

boards/holybro/kakuteh7mini/init/rc.board_defaults
boards/holybro/kakuteh7v2/init/rc.board_defaults

This switches from attitude_estimator_q to EKF2 which should now work without mag when the params are set to SYS_HAS_MAG = 0 and EKF2_IMU_CTRL = 7 to enable gravity fusion.
As suggested by @bresch.
@bkueng should I do the same for KakuteH7 v1 and KakuteF7?
FYI @vincentpoont2.

kakuteh7v2/mini: use EKF2 without mag by default 

---

ROMFS/px4fmu_common/init.d-posix/airframes/6011_gazebo-classic_typhoon_h480.post

When was running the autopilot in headless mode in docker. I found that I was receiving an error on the startup script: 
```
WARN  [mavlink] mavlink for network on port 18570 is not running
ERROR [px4] Startup script returned with return value: 256
```
Seeing that @julianoes already removed it from other vehicles and @TSC21 told me that it was very probably deprecated, maybe it makes sense to remove it ?
I have to admit that I don t fully understand what I' m doing and I would be happy to get explained why we send this message to the "Ground Control Station" ?

removing MOUNT_ORIENTATION on udp_gcs_port_local from typhoon

---

src/modules/ekf2/EKF/common.h
src/modules/ekf2/ekf2_params.c

Currently in ekf2 starting mag_3d requires mag_aligned_in_flight and either the yaw > EKF2_MAG_YAWLIM or horizontal acceleration (filtered) > EKF2_MAG_ACCLIM. 
I think the default yaw rate gate (EKF2_MAG_YAWLIM) could be lowered a bit to get the mag states initialized earlier on.

ekf2: decrease EKF2_MAG_YAWLIM default 0.25 -> 0.2 rad/s 

---

ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator

Allows a user to specify a starting location for `sihsim` via environment variables like the `PX4_SIMULATOR` environment variable required for `sihsim`.
- Checks to see if `PX4_HOME_LAT` and `PX4_HOME_LON` are set and then calls `param set` on `SIH_LOC_LAT0` and `SIH_LOC_LON0`, respectively.
- `param set-default` might be a better option?
- we could also add an environment variable for `SIH_LOC_H0`

init.d-posix/px4-rc.simulator: adds non-default LAT and LON as optional environment variables

---

src/modules/flight_mode_manager/tasks/ManualAltitude/FlightTaskManualAltitude.hpp
src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.hpp

I found this while looking into tilt, yaw limits.
- Compiles without these lines

FlightTask: don't instaniate unused parameters

---

ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator

It looks like this PR introduced a shellcheck failure
https://github.com/PX4/PX4-Autopilot/pull/21253
changing string condition from -z to -n as spellcheck recommended 

fix shellcheck error

---

src/modules/landing_target_estimator/LandingTargetEstimator.cpp

Reduce severity of precision landing related messages, and rephrase one of the messages to be more operator friendly, rather than geared towards developers.

Reduce warnings in logs and reword messages

---

boards/cubepilot/cubeorangeplus/src/board_config.h

If NuttX is built without support for SMPS it can brick the hardware. Therefore, I suggest that we add this additional compile-time check.
FYI @bugobliterator

CubeOrange+: add check for SMPS support

---

msg/SensorGps.msg
src/drivers/gps/CMakeLists.txt
src/drivers/gps/gps.cpp
src/examples/fake_gps/FakeGps.cpp
src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.cpp
src/modules/mavlink/mavlink_receiver.cpp
src/modules/simulation/sensor_gps_sim/SensorGpsSim.cpp
src/modules/simulation/simulator_mavlink/SimulatorMavlink.cpp

This PR adds spoofing state to the ublox driver.
Requires https://github.com/PX4/PX4-GPSDrivers/pull/124 and https://github.com/PX4/PX4-GPSDrivers/pull/125
While I was attempting to get it to detect spoofing, I got it to detect jamming.
If you run the GPS spoofer long enough, it goes back to reporting spoofing state unknown.
```
WARN  [gps] GPS spoofing detected! (state: 3)
WARN  [gps] GPS spoofing detected! (state: 2)
WARN  [gps] GPS spoofing detected! (state: 3)
WARN  [gps] GPS spoofing detected! (state: 2)
nsh> WARN  [gps] GPS jamming detected! (state: 2)
nsh> WARN  [gps] GPS jamming detected! (state: 3)
```

Add GPS spoofing state

---

src/modules/ekf2/EKF/gps_yaw_fusion.cpp

- otherwise external test ratio monitoring could trigger a false positive

ekf2: GNSS yaw only reset test ratio for new samples

---

src/drivers/gps/CMakeLists.txt
src/drivers/gps/params.c

This adds a parser for Unicore sentences sent in-between NMEA sentences which brings support for the Unicore UM982 module which publishes heading information based on the two antennas.
Stack is raised because we allocate 200 bytes for the Unicore parser.
The assumption is that the "rover antenna" is considered to be the primary one and would match the Unicore master antenna.
FYI @vincentpoont2

gps: Support for Unicore HEADINGA sentence in NMEA

---

src/drivers/distance_sensor/lightware_sf45_serial/lightware_sf45_serial.cpp

The PR was made a while back before the crc.h file was moved out of systemlib. I believe the CI did not catch it due to the module not being enabled on any default firmware.

Lightware SF45 Fix path to crc lib (no longer in systemlib)

---

src/modules/vtol_att_control/vtol_att_control_main.cpp

The update of virtual thrust setpoint would not happen if the torque one already was updated. 
That slipped in with https://github.com/PX4/PX4-Autopilot/pull/20837 and interestingly wasn't noticeable in SITL.

VTOL: make sure that all virtual topics are updated

---

src/drivers/gps/gps.cpp

It appears that the F9P GPS ends up reporting JAMMING_STATE_WARNING more often than not. This updates the warning to only report when the jamming state is critical.
https://github.com/PX4/PX4-Autopilot/pull/21244#issuecomment-1474269102

GPS only warn if jamming state is critical

---

src/drivers/distance_sensor/leddar_one/LeddarOne.cpp

added missing "~"
I found that missing char when i was investigating the code for something else. I am not very familiar with serial port reading but if i am not mistaken that line is useless if that char is missing. Similiar line also had that char. 
I have not actually tested the code, so maybe the correct thing to do is removing the line altogether

fix typo in LeddarOne.cpp

---

Tools/simulation/gazebo-classic/sitl_multiple_run.sh

It was getting extremely difficult to modify or even read the default jinja-gen call due to the amount of parameter.
using ${@} allows us to set all the different parameters on a different line
Later I plan to use https://github.com/PX4/PX4-SITL_gazebo-classic/pull/965 to allow myself to remove all the custom parameters I previously introduced

refactoring jinja-gen call in a cleaner way

---

src/modules/mavlink/mavlink_ulog.cpp
src/modules/mavlink/mavlink_ulog.h

The float inaccuracy was leading to problems on SITL with large timestamps.

fix mavlink_ulog: use hrt_abstime instead of float

---

Tools/px4events/jsonout.py
src/lib/component_information/CMakeLists.txt
src/lib/events/enums.json
src/lib/parameters/px4params/jsonout.py

This adds the metadata translation url's pointing to https://github.com/PX4/PX4-Metadata-Translations.
@hamishwillee fyi
QGC PR: https://github.com/mavlink/qgroundcontrol/pull/10522
MAVLink: https://github.com/mavlink/mavlink/pull/1934

component information: add translation support

---

boards/px4/fmu-v6c/src/board_config.h
boards/px4/fmu-v6c/src/manifest.c
boards/px4/fmu-v6c/src/spi.cpp

Add 6C Mini and fixes rev1 sensor selection. 
The entry was wrong but the fact that all the sensor sets are the same the "fall back" cod in spi.cpp mapped it back to V6C00.
It could be used as a neat trick to same some FLASH, but it will cause an issue if the sensor set is changed.

px4_fmu-v6c:Add Mini & fix Rev 1

---

src/modules/mc_att_control/AttitudeControl/AttitudeControlMath.hpp
src/modules/mc_att_control/AttitudeControl/AttitudeControlMathTest.cpp
src/modules/mc_att_control/AttitudeControl/CMakeLists.txt
src/modules/mc_att_control/mc_att_control_main.cpp

Passing by Euler angles to adjust roll/pitch and yaw independently produces unwanted artifacts and is generally not an attitude representation we would like to use in the autopilot.
TODO:
Generate manual attitude setpoints with quaternions.
We could also use rotation matrices .
- sitl tests with large yaw error and `if (_vtol)` forced to true. Both implementations "feel" the same: the tilt is always aligned with the body frame 
main:
PR:
Also tested at pitch = 90 deg, for the VTOL case, unlike before, applying a yaw stick input creates a pure roll rate

mc att: do not pass by euler angles to generate att sp from sticks

---

ROMFS/px4fmu_common/init.d-posix/airframes/10042_sihsim_xvert
ROMFS/px4fmu_common/init.d-posix/airframes/1041_gazebo-classic_tailsitter
ROMFS/px4fmu_common/init.d/airframes/1102_tailsitter_duo_sih.hil
ROMFS/px4fmu_common/init.d/airframes/13200_generic_vtol_tailsitter
src/modules/airspeed_selector/AirspeedValidator.cpp
src/modules/airspeed_selector/AirspeedValidator.hpp
src/modules/airspeed_selector/airspeed_selector_main.cpp
src/modules/commander/failure_detector/FailureDetector.cpp
src/modules/commander/failure_detector/FailureDetector.hpp
src/modules/ekf2/EKF2.cpp
src/modules/ekf2/ekf2_params.c

https://github.com/PX4/PX4-Autopilot/issues/21229
Rotate attitude 90° in airspeed selector and failure detector.
Still have some `WARN  [ekf2] primary EKF changed 0 (filter fault) -> 3` that I'm looking into, which may have been the root issue for https://github.com/PX4/PX4-Autopilot/issues/21229.
It seems to be a EKF side slip fusion failure 
`# 6 - true if fusion of the synthetic sideslip constraint has encountered a numerical error`

AirspeedSelector, FailureDetector: Tailsitter attitude fixes

---

msg/GimbalControls.msg
src/modules/gimbal/common.h
src/modules/gimbal/gimbal.cpp
src/modules/gimbal/gimbal_params.c
src/modules/gimbal/gimbal_params.h
src/modules/gimbal/input_mavlink.cpp
src/modules/gimbal/input_rc.cpp
src/modules/gimbal/input_test.cpp
src/modules/gimbal/output_rc.cpp
src/modules/gimbal/output_rc.h

The logic around automatically retract/deploy a gimbal resp. a camera shutter is currently broken (as it's not handled in the new control allocation). It's currently only possible to manually control retraction via MAVLink commands (DO_SET_ACTAUTOR or DO_SET_SERVO). 
Previously it used to work like that if I understand it correctly:
- at the beginning/by default, it would be  `gimbal_retract = false`
- if could be retracted by sending the MAVLink message [VEHICLE_CMD_DO_MOUNT_CONTROL](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_MOUNT_CONTROL) with the last field set to VEHICLE_MOUNT_MODE_RETRACT (0), so `gimbal_retract = true` Note: VEHICLE_CMD_DO_MOUNT_CONTROL is deprecated and thus shouldn't be used anymore I guess
- if would be automatically deployed when a ROI is commanded, …

Gimbal: remove shutter and retraction handling

---

README.md

This adds the Cube Orange+ to the list, and also changes the Hex naming to CubePilot as that is how it is sold/marketed now.

README: add Cube Orange+

---

src/modules/navigator/mission.cpp
src/modules/navigator/mission.h

WORK_ITEM_TYPE_TRANSITON_AFTER_TAKEOFF has a typo error
- Rename `WORK_ITEM_TYPE_TRANSITON_AFTER_TAKEOFF`  -> `WORK_ITEM_TYPE_TRANSITION_AFTER_TAKEOFF`

Fix typo in WORK_ITEM_TYPE

---

Tools/simulation/gazebo-classic/sitl_multiple_run.sh

Complementary to #21091.
The microDDS namespace logic remains unchanged. Single vehicle simulations have no additional prefix in the namespace and are adopted when `-i 0` is given to the startup script (the default value). Multi vehicle simulations are instead adopted for `-i 1` and greater.
This allows to keep the same namespace convention for single vehicle simulations and single real drone scenarios.
This PR forces `Tools/simulation/gazebo-classic/sitl_multiple_run.sh` to start assigning instance ids from index 1 fixing the previous collision.
Fixes #21085, #21069.

gazebo-classic/sitl_mutliple_run.sh: start spawning drones from index 1

---

src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessHelicopter.cpp
src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessHelicopter.hpp
src/modules/control_allocator/module.yaml

When tuning the yaw torque compensation I found that it can easily happen that the main rotor produces the least torque with a non-zero collective pitch. In that case it's essential to configure that offset otherwise the yaw compensation will always be off.
- Add a parameter `CA_HELI_YAW_CP_O` to allow configuring at which collective pitch the main rotor produces the least amount of torque.
With that particular vehicle, I found that `CA_HELI_YAW_TH_S` (throttle based torque compensation) gets negligible when the collective pitch-based compensation is tuned correctly including this new offset. I want to see if that's also the case for other models. It might be that we can remove `CA_HELI_YAW_TH_S` altogether because it has no benefit.
- This is in use on a large vehicle and clearly …

Helicopter: add offset for yaw compensation based on collective pitch

---

src/modules/vtol_att_control/vtol_att_control_params.c

Stumbled on some inconsistencies and wrong/bad param descriptions for the quad-chute params while doing https://github.com/PX4/PX4-user_guide/pull/2364.
Further I propose here to increase the default of VT_QC_T_ALT_LOSS to 20m, as 10m has shown to be quite tight.

VTOL: Quad-chute param corrections/improvements

---

test/mavsdk_tests/mavsdk_test_runner.py

- This was a nasty bug where starting PX4 instance first, then starting Gazebo server was causing PX4 instance' EKF to freak out, probably because it doesn't like getting data a while after it is started
- This now guarantees that such edge case won't occur and MAVSDK test will run as it should
For detailed troubleshooting log, please read: https://github.com/PX4/PX4-Autopilot/issues/21229
Fixes https://github.com/PX4/PX4-Autopilot/issues/21229
Start PX4 instance AFTER Gazebo server is started
We could also make px4 itself robust so that it doesn't freak out when a simulated sensor data starts flowing in after it is instantiated for a while, but that's up for a discussion.
All 3 out of 4 tests now always pass consistently:
NOTE: VTOL Mission Test (4/4) failure isn't related to MAVSDK Test …

Fix SITL Test failure: Place PX4 instance runner after Gazebo server runner

---

ROMFS/px4fmu_common/init.d-posix/airframes/1033_jsbsim_rascal
ROMFS/px4fmu_common/init.d-posix/airframes/1034_flightgear_rascal-electric
ROMFS/px4fmu_common/init.d-posix/airframes/1036_jsbsim_malolo
ROMFS/px4fmu_common/init.d-posix/airframes/1039_flightgear_rascal
ROMFS/px4fmu_common/init.d/airframes/13013_deltaquad
ROMFS/px4fmu_common/init.d/rc.fw_defaults
ROMFS/px4fmu_common/init.d/rc.vtol_defaults
src/modules/navigator/MissionFeasibility/FeasibilityChecker.cpp
src/modules/navigator/MissionFeasibility/FeasibilityChecker.hpp
src/modules/navigator/MissionFeasibility/FeasibilityCheckerTest.cpp
src/modules/navigator/mission.h
src/modules/navigator/mission_params.c

- annoying parameter MIS_DIST_WPS with questionable use
- first waypoint check (around MIS_DIST_1WP) only checks distance to Home, and thus prevents uploading a mission that is some distance from home (typically because vehicle is already in air). 
- remove MIS_DIST_WPS check completely
- rework MIS_DIST_1WP check to always take min() of Home and current position distance
That way we still catch the most important misconfiguration: starting a mission that actually is from another day of flying and thus very far away. I would argue that there is no other check then that required. Eg [estimator issues during too long straight](https://github.com/PX4/PX4-Autopilot/pull/16550#issuecomment-759831054) legs is something that no longer is a valid reason to prevent waypoints far apart. 
- use Home …

Navigator::MissionFeasibilityChecks: rework min distance checks

---

src/modules/microdds_client/microdds_client.cpp

When starting the `microdds_client` with the `-l` flag, it gave an error that the client namespace was too long, even when no namespace was given.
This was because the length of the resulting participant XML was being compared to the incorrect variable and thus always appeared too long.
Compare XML length to `PARTICIPANT_XML_SIZE`.
We could also directly query the allocated size of `participant_xml` and compare `ret` to that.
Tested on a v5x device and successfully started the client with the `-l` flag.
N/A

microdds_client: Fix check for length of participant XML

---

ROMFS/px4fmu_common/init.d-posix/rcS
Tools/convert_ip.py
src/modules/microdds_client/microdds_client.cpp
src/modules/microdds_client/microdds_client.h
src/modules/microdds_client/module.yaml

1. Removed incomplete multi instance capability for microdds_client.
2. Added new parameter `XRCE_DDS_AG_IP` that encodes the micro XRCE-DDS Agent IP. Its default value corresponds to `127.0.0.1`.
3. When the client is started without specifying the udp port (missing `-p` argument) then the parameter `XRCE_DDS_PRT` is used.
4. When the client is started without specifying the Agent IP (missing `-h` argument) then the parameter `XRCE_DDS_AG_IP` is used.
5. Increased verbosity of `microdds_client status`.
6. To make the conversion from IP addresses in decimal-dot notation to int32 and vice-versa `Tools/convert_ip.py` is added.
Fixes #21179
Taking the IP address in decimal-dot notation, converting it in HEX dot notation and the stacking together the 4 bytes is not enough. The parameters in …

microdds_client: support Agent IP address as PX4 parameter

---

Tools/simulation/jmavsim/jmavsim_run.sh

I found that the wrong flags expressions when using getopt function.
I update the expression,  
```
":b:d:u:p:qsr:f:i:loat" => "b:d:ui:p:qsr:loat" 
```

fix the wrong flags expression in getopt

---

src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.hpp

Allow the operator of a multirotor to yaw the vehicle in hold mode without switching to position mode if RC help is active and RC override is disabled.
SITL jmavsim

Allow yawing during hold

---

ROMFS/px4fmu_common/init.d-posix/airframes/4002_gz_x500_depth
ROMFS/px4fmu_common/init.d-posix/airframes/4003_gz_rc_cessna
ROMFS/px4fmu_common/init.d-posix/airframes/4004_gz_standard_vtol
ROMFS/px4fmu_common/init.d-posix/airframes/4005_gz_x500_vision
Tools/simulation/gz/models/x500_depth/model.sdf

1. The Gazebo model `x500_depth` uses `https://fuel.gazebosim.org/1.0/RudisLaboratories/models/x500-Base` as base model and attaches to it the depth camera.
1. This is not consisten with #21285.
2. More importantly, that base model does not include the `air_pressure` sensor which leads to `Preflight Fail: barometer 0 missing` warnings.
2. The sitl airframe `4002_gz_x500_depth` is entirely coping `4001_gz_x500` with just `PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_depth}` (the SIM_MODEL name) as difference.
3. The sitl airframe `4005_gz_x500_vision` first includes `4001_gz_x500` and then set (only if they are not already set) the simulator/model specific environment variables:
```sh
PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default} …
```

gazebo airframes: cleanup and fix missing parameters

---

boards/px4/fmu-v2/src/init.c
boards/px4/fmu-v3/src/init.c
platforms/nuttx/src/px4/nxp/imxrt/board_hw_info/board_hw_rev_ver.c
platforms/nuttx/src/px4/stm/stm32_common/board_hw_info/board_hw_rev_ver.c

This fixes the case where the hardware detection fails on CubeBlack when a CAN device is connected to CAN1 and talking, and therefore preventing the check from getting a clear result.
I suggest to review commit by commit as the first commit is just a refactor.
Tested on CubeBlack.
Fixes #21102.
Probably needs duplicating/copying to fmu-v2.

CubeBlack: fix hardware detection

---

ROMFS/px4fmu_common/init.d/airframes/4052_holybro_qav250

`PWM_MAIN_TIM0 = 0` is an invalid value:
Remove that line and so that the default value `400` is used.

Holibro qav250 airframe: fix PWM_MAIN_TIM0 value

---

src/modules/commander/failsafe/framework.cpp

Otherwise the additional mode check triggers an RTL which takes precedence over Hold.
Introduced in 132e9d243966586d7aaf21d9600d9413993e5cc8

fix failsafe: correctly handle Hold RC loss action

---

src/drivers/gps/gps.cpp

When GPS_DUMP is used, more stuff is streamed, and the gps driver reports low on stack. Actually had stack at 1940 on a private repo and still saw the low on stack warning, hence bumping to 1990 here.
Increase the stack.

drivers/gps: increase stack

---

src/drivers/uavcan/uavcan_main.cpp

Error message for "UavcanServers init" should return error code from UavcanServers->init instead of _sensor_bridges->init.

minor fix regarding console output

---

src/modules/navigator/mission.cpp
src/modules/navigator/mission.h
src/modules/navigator/navigator.h
src/modules/navigator/navigator_main.cpp
src/modules/navigator/rtl.cpp

Vehicle climbs and follows RTL sequence when already on mission landing (on loiter down).
Improve function` Mission::landing() `--> To find out if we're currently on a mission landing, check if we either are past the land start marker OR currently land start marker is current WP ~and vehicle is already in LOITER mode.~, type is LOITER_TO_ALT and vehicle is inside loiter circle. Then it seems to me like we don't need to additional function `Navigator::getMissionLandingInProgress() `anymore, so I removed that. 
https://github.com/PX4/PX4-Autopilot/pull/20903 will hopefully help us to once and for all make the RTL behavior deterministic and predictable. 
Tested triggering RTL on a VTOL in SITL in all flight phases of the Mission, and it now only does the whole RTL sequence when outside of …

Navigator: fix logic around when to switch to mission landing for RTL

---

src/lib/tecs/TECS.cpp
src/lib/tecs/TECS.hpp
src/modules/fw_path_navigation/FixedwingPositionControl.cpp
src/modules/fw_path_navigation/FixedwingPositionControl.hpp
src/modules/fw_path_navigation/fw_path_navigation_params.c

1) TECS doesn't cleanly support handling varying airspeed. 
Flying at different airspeed requires some sort of drag modelling, as the trim throttle strongly depends on current airspeed. The controller is able to compensate for some small airspeed changes manly through the throttle integrator, but this is not optimal especially if the airspeeds varies strongly within the same flight, as then the quality of the airspeed tracking on airspeed changes is directly dependent on how fast the integrator converges. 
~2) Inconsistent handling of load factor increase due to vehicle weight vs load factor increase due to banking.
The load factor determines how much lift the vehicle currently has, and that in turn how much induced drag it experiences, that then has to be taken into account for the …

FWPositionControl: trim throttle prediction improvements

---

msg/TecsStatus.msg
src/lib/tecs/TECS.cpp
src/lib/tecs/TECS.hpp
src/modules/fw_path_navigation/FixedwingPositionControl.cpp

https://github.com/PX4/PX4-Autopilot/pull/21189#issuecomment-1487220075
This reverts the logic to how it was before the TECS refactoring. Not saying it has to stay that way.

TECS: if height_rate_setpoint is set, only use that one to update altitude reference

---

src/modules/ekf2/EKF/airspeed_fusion.cpp
src/modules/ekf2/test/sensor_simulator/ekf_wrapper.cpp
src/modules/ekf2/test/sensor_simulator/ekf_wrapper.h
src/modules/ekf2/test/test_EKF_airspeed.cpp

Tests showed that sideslip fusion often starts just before airspeed fusion, resetting the wind states to 0 instead of using the airspeed data.
A quick look at the wind uncertainty allows to know if the current wind estimate is meaningful or if we should rather reset it using the airspeed data.
- added unit test that covers that case

ekf2: robustify wind init using airspeed

---

src/drivers/ins/vectornav/libvnc/src/vn/sensors.c

Fixed incorrect string-from-error function usage causing build failure
```
/home/jake/code/jake/PX4-Autopilot/src/drivers/ins/vectornav/libvnc/src/vn/sensors.c:2692:30: error: implicit conversion from 'VnError' to 'SensorError' [-Werror=enum-conversion]
2692 |   strFromSensorError(buffer, error);
```

vectornav: fix incorrect string-from-error function usage

---

src/modules/microdds_client/microdds_client.h

The protocol source for timesync status was not properly set for DDS protocol

fix timesync source for DDS protocol

---

src/modules/simulation/gz_bridge/GZBridge.cpp
src/modules/simulation/gz_bridge/GZBridge.hpp

- When converting from `gz::msgs::OdometryWithCovariance` to `vehicle_odometry_s` no quaternion was provided.
- Linear and angular velocities and covariance matrices were converted in the wrong frames.
- Covariance matrices are not in pupper triangle format.
- added static method to covert quaternions from ROS to PX4 convention.
- Fixed velocities and covariance matrices frames (they are in body FRD now).

gz_bridge: fix missing orientation and frames in odometryCallback

---

src/modules/microdds_client/dds_topics.yaml

When trying to integrate an offboard process such as an obstacle avoidance algorithm in ROS2, there was no information of the vehicle's mission or waypoints being published
This commit adds the position_sp_triplet to the dds topic list.
This lets you at least figure out where the vehicle is "trying" to go next for auto modes
We can try to find a better way to communicate mission waypoints as a dds topic, or provide a service interface, where the offboard process can request what the mission of the vehicle should be.
- Related to https://github.com/PX4/PX4-Autopilot/issues/20981

Add position_sp_triplet to the dds topics

---

src/modules/flight_mode_manager/FlightModeManager.cpp
src/modules/flight_mode_manager/FlightModeManager.hpp

When starting SITL e.g. using `make px4_sitl sihsim_quadx` and don't have any ground station that immediately sends joystick data there's an error message `ERROR [flight_mode_manager] Failsafe task activated`
This translates to the real vehicle boot without position estimate and RC signal.
Fixes #21370
My suggestion for 1.14 is to add the descend task to the flight mode manager fallback which I did in this pr. It's a minimal change that solves the problem like it was after merging #20172 before making the checks to run all stick dependent tasks including altitude more strict in https://github.com/PX4/PX4-Autopilot/commit/da4644c20adce8aeedd5be432fc88b1b115d7eb9#diff-a65eff8fc6362bb2a8c4c7495f56778e1896809f6251a9403e57ff18f754076aR66
I would like to rework this logic. We still don't have a …

Add descend task to failsafe fallback to avoid "Failsafe task activated"

---

.github/PULL_REQUEST_TEMPLATE.md

In the maintainer call of 04.04.2023 we discussed that it would help anyone doing release notes if the pull requests contain changelog entries that just need to be filtered and concatenated. E.g. @mrpollo and @tstastny know the pain of finding the all important changes and writing a concise description for them.
We could add a title and make sure there is a useful changelog entry for every pull request before merging it. For very small prs the description could consist of only the changelog entry to not convolute the description unnecessarily.
We could carry the changelog in tree but it would likely lead to many versioning conflicts.
We could also do further changes to the template to make it slimmer.

Pull request template: add changelog entry

---

src/lib/matrix/matrix/Dcm2.hpp
src/lib/matrix/matrix/math.hpp
src/lib/matrix/test/CMakeLists.txt
src/lib/matrix/test/MatrixDcm2Test.cpp
src/modules/flight_mode_manager/tasks/ManualAltitude/FlightTaskManualAltitude.cpp
src/modules/flight_mode_manager/tasks/ManualAltitude/FlightTaskManualAltitude.hpp
src/modules/flight_mode_manager/tasks/ManualPosition/FlightTaskManualPosition.cpp
src/modules/flight_mode_manager/tasks/Transition/FlightTaskTransition.cpp
src/modules/flight_mode_manager/tasks/Utility/Sticks.cpp
src/modules/mc_att_control/AttitudeControl/AttitudeControl.cpp

For horizontal flight patterns, it's useful to be able to rotate a 2D vector.
- Add a 2-dimensional rotation matrix class.
We could also call the 3D rotation implementation with only a yaw rotation but I doubt that's any better.
- I added unit tests to compare a rotation matrix to the 3D case and rotate a vector.
This is in preparation to enable a figure eight pattern.

Matrix: 2D rotation

---

src/modules/navigator/navigator_main.cpp

`rep->current.cruising_speed = get_cruising_speed();` was missing on entry of a FW Orbit, thus always resetting the speed to the vehicle default.

navigator_main: orbit in FW: get_cruising_speed()

---

src/drivers/gps/gps.cpp

GPS driver is out of stack again when using dump config for PPK.
Increase stack 50 more bytes.
Likely not interesting for release notes.
Stack warnings were a bit sporadic, but will update from flight tests in next couple days if still not enough. Really should handle it now after this second increase.

drivers/gps: increase stack to handle gps dump config for RTCM output (PPK)

---

boards/modalai/voxl2-slpi/src/CMakeLists.txt
boards/modalai/voxl2-slpi/src/drivers/spektrum_rc/CMakeLists.txt
boards/modalai/voxl2-slpi/src/drivers/spektrum_rc/drv_rc_input.h
boards/modalai/voxl2-slpi/src/drivers/spektrum_rc/spektrum_rc.cpp
src/drivers/spektrum_rc/Kconfig

The outdated and obsolete snapdragon_spektrum_rc driver (and empty spektrum_rc driver) were removed and replaced with a VOXL2 board specific spektrum_rc driver. This will eventually get replaced as well once the UART API changes to the standard rc drivers are resolved so that they can be used directly on VOXL2.

Snapdragon spektrum rc refactor

---

src/modules/navigator/mission.cpp

When landing with a mission stored on the vehicle, that has not been updated since power cycling, these errors appear:
```
ERROR [navigator] mission update failed
WARN  [mavlink] ERROR: wp index out of bounds
```
The errors come from the fact that when the mission is not updated, the [_mission_sub.copy(_mission) ](https://github.com/PX4/PX4-Autopilot/blob/202e2770da50caff0ed00c06a574e3c39933df52/src/modules/navigator/mission.cpp#L524)returns false, and thus the code below is not run, which would [reset _current_mission_index to 0 over current_seq](https://github.com/PX4/PX4-Autopilot/blob/202e2770da50caff0ed00c06a574e3c39933df52/src/modules/navigator/mission.cpp#L527), that was previously set to 0 in reset_mission. 
I thus here propose to only run `update_mission()` when the mission was …

mission: only run update_mission() if mission is updated, not when reset due to landing

---

Makefile

`validate_module_configs` target is checking against unrelated yaml file
```sh
(venv) salimterryli@stl-laptop:/media/dev-linux/px4/Firmware$ make validate_module_configs
Validation Errors:
{'body': ['unknown field'], 'description': ['unknown field'], 'labels': ['unknown field'], 'module_name': ['required field'], 'name': ['unknown field']}
Traceback (most recent call last):
File "/media/dev-linux/px4/Firmware/Tools/validate_yaml.py", line 67, in <module>
raise Exception("Validation of {:} failed".format(yaml_file))
Exception: Validation of /media/dev-linux/px4/Firmware/src/lib/events/libevents/libs/cpp/parse/nlohmann_json/.github/ISSUE_TEMPLATE/bug.yaml failed
make: *** [Makefile:484: validate_module_configs] Error 123
```

Makefile: validate_module_configs skips src/lib/events/libevents/*

---

src/drivers/osd/msp_osd/module.yaml
src/drivers/osd/msp_osd/msp_osd.cpp
src/drivers/osd/msp_osd/msp_osd.hpp

Simply adds crosshairs to the OSD display, optionally

Added crosshairs to MSP OSD driver

---

src/modules/vtol_att_control/vtol_type.cpp
src/modules/vtol_att_control/vtol_type.h

VT_TRANS_MIN_TM and VT_F_TR_OL_TM are scaled with density altitude. This was not yet the case for the timeout, but should be done here as well.

vtol_type: scale VT_TRANS_TIMEOUT with air density

---

src/modules/navigator/land.cpp
src/modules/navigator/loiter.cpp
src/modules/navigator/mission.cpp
src/modules/navigator/precland.cpp
src/modules/navigator/rtl.cpp
src/modules/navigator/takeoff.cpp

When I issued a DO_CHANGE_SPEED, and then changed flight modes, that speed continued over to the new flight mode. 
For example, if I issue a DO_CHANGE_SPEED in mission mode for 1 m/s, and then switch to Loiter mode, I am still restricted to 1 m/s.
From the conversations that I have had with maintainers, this is not the behavior we want to have
The only flight mode that this **does not** happen for is RTL, which has the following line
`_navigator->reset_cruising_speed();`
I reset the cruising speed upon entering a new navigation mode.
We could also create a new module that keeps track of what mode we are in and changes speed limits from there
- Create a waypoint mission with a change speed waypoint item at 1 m/s. Mid-mission flip to HOLD mode and issue a do_relocate. 
Before the change: …

Speed reset when switching flight modes

---

ROMFS/px4fmu_common/init.d-posix/airframes/1010_gazebo-classic_iris_opt_flow
ROMFS/px4fmu_common/init.d-posix/airframes/1017_gazebo-classic_iris_opt_flow_mockup
ROMFS/px4fmu_common/init.d-posix/airframes/4006_gz_px4vision
ROMFS/px4fmu_common/init.d/airframes/4016_holybro_px4vision
ROMFS/px4fmu_common/init.d/airframes/4020_holybro_px4vision_v1_5
ROMFS/px4fmu_common/init.d/airframes/4061_atl_mantis_edu
ROMFS/px4fmu_common/init.d/airframes/4073_ifo-s
ROMFS/px4fmu_common/init.d/airframes/4900_crazyflie
ROMFS/px4fmu_common/init.d/airframes/4901_crazyflie21
boards/modalai/voxl2/target/voxl-px4-set-default-parameters.config
src/modules/ekf2/EKF/airspeed_fusion.cpp
src/modules/ekf2/EKF/common.h
src/modules/ekf2/EKF/drag_fusion.cpp
src/modules/ekf2/EKF/estimator_interface.cpp
src/modules/ekf2/EKF/optical_flow_control.cpp
src/modules/ekf2/EKF2.cpp
src/modules/ekf2/EKF2.hpp
src/modules/ekf2/ekf2_params.c
src/modules/ekf2/test/sensor_simulator/ekf_wrapper.cpp

The last bits used in the aid mask were to select optical flow and drag fusion; we should have them removed for 1.14 to be consistent and be able to remove `EKF2_AID_MASK` completely just after the release.
Create:
- `EKF2_OF_CTRL`: en-/disable optical flow
- `EKF2_DRAG_CTRL`: en-/disable wind estimation using drag fusion
```
Migrate EKF2_AID_MASK
New parameter: EKF2_OF_CTRL, EKF2_DRAG_CTRL
Documentation:
```
https://github.com/PX4/PX4-user_guide/pull/2459
Param migration tested in SITL

EKF2: deprecate aid mask

---

src/drivers/imu/bosch/bmi088/BMI088_Gyroscope.cpp
src/drivers/imu/bosch/bmi088_i2c/BMI088_Gyroscope.cpp

We discovered that ArduPilot gets incorrect values from the BMI088.
ArduPilot added a process that does not use illegal values (X, Y, Z values of -1).
Add this process to PX4-AutoPilot.
None
None
None
ArduPilot PR
https://github.com/ArduPilot/ardupilot/pull/22710
https://github.com/ArduPilot/ardupilot/pull/23033

bmi088: Do not use invalid values

---

src/modules/gimbal/common.h
src/modules/gimbal/gimbal.cpp
src/modules/gimbal/input_mavlink.cpp
src/modules/gimbal/input_mavlink.h
src/modules/gimbal/output.h
src/modules/gimbal/output_mavlink.cpp
src/modules/gimbal/output_mavlink.h
src/modules/gimbal/output_rc.cpp
src/modules/gimbal/output_rc.h
src/modules/mavlink/streams/GIMBAL_MANAGER_INFORMATION.hpp

It turns out that I had omitted implementing the gimbal_device_id which is the component ID of the gimbal device that the gimbal manager (in this case PX4) is responsible for.
This should probably go into v1.14, otherwise it won't be compatible with the upcoming QGC changes.

gimbal: implement gimbal_device_id

---

Tools/module_config/generate_actuators_metadata.py
validation/module_schema.yaml

I'm now doing the rewrite of `pca9685_pwm_out` driver and want to make it able to output duty cycle information(aka PWM mode) instead of typical 1ms~2ms pulse signal.
This PR will let actuator drivers be able to do runtime configuration of its output, based on Dynamic Allocator in a more flexible way than before.
Both param and meta generator are affected. 
This is the part of my current `module.yml`:
```
output_groups:
- param_prefix: PCA9685
group_label: 'PCA9685'
channel_label: 'Channel'
standard_params:
disarmed: { min: 0, max: 4095, default: 900 }
min: { min: 0, max: 4095, default: 1000 }
max: { min: 0, max: 4095, default: 2000 }
failsafe: { min: 0, max: 4095 }
custom_params:
pwm:
label: PWM Mode
prefix: PWM
description: |
Enable PWM mode will make PCA9685 output duty cycle instead …
```

Support custom per-channel parameters in actuator driver

---

src/drivers/gps/gps.cpp

This fixes 3 small issues in the RTCM injection instance failover logic:
- Properly reset and thus log RTCM instance.
- Check instances all the time instead of every 5s when the current instance stopped publishing.
- Don't swallow one instance right after instance switching.
More info is in the commit messages.
This work is sponsored by [Firefly Drone Shows](https://www.fireflydroneshows.com/).

RTCM injection fixes

---

boards/px4/fmu-v6c/nuttx-config/include/board.h

When flow control is used together with DMA, we need to add a pulldown to ~RTS and~ CTS. Without it, it assumes flow control and gets stuck when ~RTS and~ CTS ~are~ is not connected.
Same as #20974 but for 6C.

fmu-v6c: fix Telem1, Telem2 without flow control

---

boards/px4/fmu-v6x/nuttx-config/include/board.h

On CTS with DMA, we need the pulldown but not on RTS.

fmu-v6x: pulldown on RTS not required

---

src/modules/navigator/navigator_main.cpp

Follow up on https://github.com/PX4/PX4-Autopilot/pull/21414.
The resets in the modes (eg Loiter mode) are not active yet, so manually set rep->current.cruising_speed = -1.f if not already in the same flight mode.
SITL and flight tested on VTOLs.

Navigator: set cruise_speed to default on entering new mode

---

src/drivers/gps/gps.cpp

The "already_copied = false;" is repeatedly executed in the do whie process.
Make the value of the ALREADY_COPIED variable the initial value of the UPDATED variable.
Refactoring
None
None
None

gps: Improve the FALSE setting of the ALREADY_COPIED variable

---

src/drivers/adc/ads1115/ADS1115.cpp
src/drivers/adc/ads1115/ADS1115.h
src/drivers/adc/ads1115/ads1115_main.cpp

This improves the ADS1115 adc driver with the following:
- Adds a `probe` function to check for the config register default value. This prevents the driver to accidentally recognize another device with the same address on the bus. For example, the SE050 chip on FMUv5X can have the same basic address of `0x48`.
- Prevent printing an error on init failure when just probe fails
- Prevent spamming of console when the device is lost
The random probing of I2C buses is not nice. Also, this chip has no chip ID register, so probing for the config register default value is the best we can do.

ads1115: Driver improvements

---

src/modules/airspeed_selector/AirspeedValidator.cpp
src/modules/airspeed_selector/AirspeedValidator.hpp

The airspeed innovation checks were also run when the local position was invalidated, as we so far only checked for the estimator velocity test ratio < 1 to run it. And the test ratio with a invalid position estimate seems to be NAN.
Can be reproduced by simulating a VTOL, then faking a GPS failure (failure gps off), then transition to hover, then switching to Altitude, then transitioning again --> airspeed gets invalidated. 
Add additional check for lpos validity. 
```
Bugfix AirspeedValidator in GPS-denied environment
```

AirspeedValidator: disable innovation checks if lpos invalid

---

src/modules/ekf2/EKF2.cpp

- sanity check against potential timestamp issues with incoming distance_sensor data

ekf2: last range sensor simple timestamp protection

---

ROMFS/px4fmu_common/init.d-posix/airframes/1030_gazebo-classic_plane
ROMFS/px4fmu_common/init.d-posix/airframes/1031_gazebo-classic_plane_cam
ROMFS/px4fmu_common/init.d-posix/airframes/1032_gazebo-classic_plane_catapult
ROMFS/px4fmu_common/init.d-posix/airframes/1035_gazebo-classic_techpod
ROMFS/px4fmu_common/init.d-posix/airframes/1037_gazebo-classic_believer
ROMFS/px4fmu_common/init.d-posix/airframes/1038_gazebo-classic_glider
ROMFS/px4fmu_common/init.d-posix/airframes/1039_flightgear_rascal
ROMFS/px4fmu_common/init.d-posix/airframes/1039_gazebo-classic_advanced_plane
ROMFS/px4fmu_common/init.d-posix/airframes/1044_gazebo-classic_plane_lidar
ROMFS/px4fmu_common/init.d-posix/airframes/17002_flightgear_tf-g2
ROMFS/px4fmu_common/init.d-posix/airframes/4003_gz_rc_cessna
src/modules/fw_pos_control/FixedwingPositionControl.cpp

Fixes https://github.com/PX4/PX4-Autopilot/issues/21567
Use FW_TKO_PITCH_MIN in takeoff phase instead of global min pitch. That prevents the system from diving after the throw to gain airspeed. 
Further we could filter the airspeed in TECS less, eg by increasing FW_T_SPD_DEV_STD (as we anyway fix the airspeed rate input into TECS to 0 currently, see https://github.com/PX4/PX4-Autopilot/pull/21317).
I also fixed the simulation along the way (see attached screen recording).
```
Bugfix Plane catapult use FW_TKO_PITCH_MIN
```
Would be cool!
How to simulate:
`make px4_sitl_default gazebo_plane_catapult`
Plan mission with takeoff, arm vehicle.
https://github.com/PX4/PX4-Autopilot/assets/26798987/1b953c42-07d6-4110-b222-3f5543d949da

FW Position Controller: use FW_TKO_PITCH_MIN to not dive into ground

---

src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp

A VTOL plane in MC mode has no yaw setpoint during takeoff because of weather-vane. To align for the front transition, the yaw target jumps and caused a step in the controller, making it reach saturation.
With this commit, the previous yaw setpoint is set to the current yaw when no yaw setpoint is sent in order to create a smooth yaw trajectory starting at the current orientation when yaw target is suddenly finite.
The yawspeed filter also now contains the yaw speed instead of dyaw in order to prevent chattering due to dt jitter.
```
Fix high yaw rate before front-transition
```
SITL gazebo vtol standard
before:
after:

Fix high yaw rate before front-transition

---

ROMFS/px4fmu_common/init.d-posix/airframes/1045_gazebo-classic_quadtailsitter
src/modules/fw_att_control/fw_att_control_params.c
src/modules/fw_rate_control/FixedwingRateControl.hpp
src/modules/fw_rate_control/fw_rate_control_params.c

A couple of tuning proposals for https://github.com/PX4/PX4-Autopilot/pull/20558 (PR against PR). 
- keep as many params at default as possible to reduce maintenance load
- make pitch loop tighter
- reduce aggressiveness on yaw controller as not as important as pitch/roll, and it had negative side effects on pitch/roll
- adapt TECS params
And https://github.com/PX4/PX4-Autopilot/commit/377034d43337904d1e30061b9458f74642a45154 is acutally unrelated to the PR, but looked wrong to me.

Quad Tailsitter SITL tuning proposal

---

src/lib/tecs/TECS.cpp

The manual trajectory generator was never initialized, and then if you did a VTOL transition in Altitude or Position mode, it's position was at 0 instead of the current altitude, resulting in a big height rate down setpoint. 
It was then correctly reset once the sticks are moved ([here](https://github.com/PX4/PX4-Autopilot/blob/cf74d5ff5aa6b0461bb209a845a9f4f75c0d238b/src/lib/tecs/TECS.cpp#L172)), but if you never moved your sticks the vehicle would have crashed.  
Reset _velocity_control_traj_generator when also _alt_control_traj_generator is reset.

TECS: init _velocity_control_traj_generator properly

---

src/modules/fw_pos_control/fw_path_navigation_params.c

We currently fuse 0 as airspeed rate measurement, and thus simply low-pass filter the airspeed measurements. Testing has shown that the current default on the airspeed rate measurement noise is set to low, and thus the airspeed measurement is filtered too much.
Fixes https://github.com/PX4/PX4-Autopilot/issues/21567 (beside other PRs)
Increase default to 0.2
Tested on different FW and VTOLs. E.g.
https://review.px4.io/plot_app?log=f1a4a437-b99f-4b22-b711-c5674c4b2b62
The cursor is at the moment where the value of FW_T_SPD_DEV_STD was changed from 0.05 to 0.2. Note how the filtered airspeed value then follows the measurement closer, and the raw airspeed oscillations are reduced as the controller is able to react earlier to disturbances. 
It also has a positive effect on …

FW Position Controller: increase default of FW_T_SPD_DEV_STD to 0.2

---

src/modules/vtol_att_control/tailsitter.cpp
src/modules/vtol_att_control/tailsitter.h

Transitions in Stabilized mode are done manually, the pilot controls the pitch angle and if it's above the threshold the transition is declared finished (plus airspeed check for front transition). Thus we can't have fixed thresholds but need to link them to the actual max pitch angle in Stabilized mode.
With default gains not possible to perform transition to FW in Stabilized.
Link pitch thresholds to max manual angle (MPC_MAN_TILT_MAX).
SITL testing.

Tailsitter: make pitch angle thresholds for transition in Stabilized depending on max manual pitch

---

src/systemcmds/hardfault_log/hardfault_log.c

When using progmem backend and `hardfault_log rearm` previous fault didn't got cleared
Always clear on rearm when using progmem backend
Tested on MR-CANHUBK344

Hardfault_log progmem always clear when re-arming

---

ROMFS/px4fmu_common/init.d-posix/airframes/1041_gazebo-classic_tailsitter
ROMFS/px4fmu_common/init.d-posix/rcS
boards/atl/mantis-edu/init/rc.board_defaults
boards/px4/fmu-v5/init/rc.board_defaults
platforms/nuttx/init/kinetis/rc.board_arch_defaults
platforms/nuttx/init/stm32/rc.board_arch_defaults
platforms/nuttx/init/stm32f7/rc.board_arch_defaults
platforms/nuttx/init/stm32h7/rc.board_arch_defaults

- re-enable once the estimator selector respects configured mag priority (at least initially) or is otherwise able to automatically prefer an external mag over internal
- for SITL disabled because the full matrix of estimator instances (IMUs X mags) is too many topics for logger currently
FYI @bresch @AlexKlimaj @julianoes

ekf2: disable multi-EKF across mags by default (H7 & SITL) for now

---

platforms/common/px4_log.cpp
platforms/common/uORB/uORB_tests/uORBTest_UnitTest.cpp
src/lib/sensor_calibration/Utilities.cpp
src/lib/sensor_calibration/Utilities.hpp
src/modules/commander/HealthAndArmingChecks/checks/rcCalibrationCheck.cpp
src/modules/mavlink/mavlink_shell.cpp
src/modules/rc_update/rc_update.cpp
src/modules/temperature_compensation/TemperatureCompensation.cpp
src/modules/temperature_compensation/temperature_calibration/accel.cpp
src/modules/temperature_compensation/temperature_calibration/baro.cpp
src/modules/temperature_compensation/temperature_calibration/common.h
src/modules/temperature_compensation/temperature_calibration/gyro.cpp
src/systemcmds/tests/test_float.cpp

The `sprintf` is deprecated and has been replaced with `snprintf`, a warning shows when using "Apple clang version 14.0.0 (clang-1400.0.29.202)". 
Allow compiling `px4_sitl` under M1 with MacOS 13.2

Use snprintf over sprintf

---

src/drivers/px4io/px4io.cpp
src/drivers/rc_input/RCInput.cpp
src/drivers/rc_input/RCInput.hpp
src/modules/manual_control/ManualControlSelector.cpp
src/modules/manual_control/ManualControlSelectorTest.cpp
src/modules/mavlink/mavlink_receiver.cpp
src/modules/rc_update/rc_update.cpp
src/modules/rc_update/rc_update.h

When testing for https://github.com/PX4/PX4-Autopilot/issues/21506 I often reset all parameters to go through a fresh setup and found that my RC input data from a crossfire receiver was used even though I didn't calibrate it yet. The values were all static zero because it was uncalibrated but still assuming to have pilot input even though there is none is a safety concern.
- (Refactor topic object naming in RCInput.)
- Start using the `valid` flag in the `manual_control_input` topic to signal that the input is not actually calibrated and shouldn't be considered valid and used. The RC is considered calibrated if the channel count parameter `RC_CHAN_CNT` is set and at least one of the stick axes roll, pitch, yaw or throttle is mapped to an RC channel. Further the input is only considered …

Fix uncalibrated RC input being used

---

src/modules/mavlink/mavlink_receiver.cpp
src/modules/mavlink/mavlink_receiver.h

When a mavlink stream is closed, the uorb multi pubs need to be unadvertised. Otherwise when the stream comes back, a second instance can be created in uorb.

Mavlink receiver unadvertise all uorb multi topics

---

src/modules/mavlink/mavlink_messages.cpp

Trying to get the SYSTEM_TIME mavlink stream to work 
```
WARN  [mavlink] stream SYSTEM_TIME not found
ERROR [mavlink] configure_streams_to_default() failed
```
Simply add the stream corresponding to the right header preprocessor directives
Bugfix: SYSTEM_TIME stream not found
-
- add stream to desired mode
- SITL starts without complaining
-

[mavlink_messages] Missmatch between header macros and class used

---

.github/workflows/stale.yml

Bring back stale bot as described in: https://discuss.px4.io/t/px4-maintainers-call-may-23-2023/32245#stale-bot-bringup-10
Referenced https://github.com/marketplace/actions/close-stale-issues for setting up the action.
We can customize the messages as ramon said, but for now I kept it simple for testing.
Also, `debug-only` being set to `true` for now will prevent the stale bot from taking any actions, Adding this to prevent irreversible actions in case it isn't behaving as we want!

Create stale bot (Github actions)

---

src/drivers/uavcannode/Publishers/GnssAuxiliary.hpp
src/drivers/uavcannode/UavcanNode.cpp

This PR adds a gnss auxiliary publisher to the cannode in order to transmit the actual hdop and vdop instead of relying on pdop.

Cannode add Gnss Auxiliary publisher

---

src/modules/fw_pos_control/FixedwingPositionControl.cpp

Fixes https://github.com/PX4/PX4-Autopilot/issues/21327
Vehicle fly away when the currently active WP is the current vehicle position, relative to the line from previous to next waypoint. That happens e.g. when the vehicle loitered to achieve altitude and is then "passed" the current WP when the altitude is accepted. 
There was already logic in place that handled the case of the vehicle being behind the previous WP, but no one where the vehicle is ahead of the current WP. I added that now. The logic changes the guidance from tracking a path between two WP to fly directly to the active WP.
~Further, in the second commit I removed the check for "if further than acceptance from waypoint" to apply the special handling. It seems dangerous to me to keep it, what happens if Navigator doesn't …

FW Position Controller: navigateWaypoint(): fix corner case of vehicle not turning back to waypoint

---

src/modules/ekf2/EKF/mag_fusion.cpp

- handle synthetic z special case

ekf2: fuse mag update last heading fuse time if updating all states

---

ROMFS/px4fmu_common/init.d-posix/airframes/10042_sihsim_xvert
ROMFS/px4fmu_common/init.d-posix/airframes/1041_gazebo-classic_tailsitter
ROMFS/px4fmu_common/init.d-posix/airframes/1045_gazebo-classic_quadtailsitter
ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt
ROMFS/px4fmu_common/init.d/airframes/1102_tailsitter_duo_sih.hil
ROMFS/px4fmu_common/init.d/airframes/13200_generic_vtol_tailsitter
src/modules/simulation/simulator_mavlink/sitl_targets_gazebo-classic.cmake

The current tailsitter model has control surfaces, and a control surface-less tailsitter was not available for testing in simulation
This PR adds support for a quadtailsitter, which models the HEQ SWAN K1.
The 3D mesh was provided by Holybro
```
make px4_sitl gazebo_quadtailsitter
```
- Depends on https://github.com/PX4/PX4-Autopilot/pull/20511

Add support for quadtailsitter in SITL Gazebo

---

src/drivers/uavcan/arming_status.cpp
src/drivers/uavcannode/Subscribers/ArmingStatus.hpp

Previously, the DroneCAN message `uavcan::equipment::safety::ArmingStatus::status` was set to STATUS_FULLY_ARMED if we were prearmed or armed. This would result in actuators being able to actuate such as ESC's  even if the arm switch on the transmitter were on the disarm position, because the FMU entered prearmed.
This change sets `uavcan::equipment::safety::ArmingStatus::status` to STATUS_FULLY_ARMED if actuator_armed::armed is true.
On the cannode side, we hardcode prearm to true on receiving the uavcan::equipment::safety::ArmingStatus message, to allow servos/lights and other devices to be controlled in a disarmed state.

ArmingStatus set to Armed based on actuator_armed.armed

---

src/modules/vtol_att_control/vtol_att_control_params.c
src/modules/vtol_att_control/vtol_type.cpp
src/modules/vtol_att_control/vtol_type.h

The current implementation of the uncommanded descend quadchute revealed two issues:
1) It was possible for a vehicle to enter a limit cycle in which it would stall, loose a lot of altitude, recover, slightly climb up, stall, ...
This behavior has been observed on a vehicle that suffered an airspeed sensor failure and was flying with a too low trim throttle value. In the phases during which the vehicle climbed again after recovering from the stall, the quadchute height rate error integral (current implementation) was reset to 0 and therefore quadchute never triggered, although the vehicle lost close to 100m altitude.
2) Users found it difficult to tune the quadchute as there was no one to one relation between the parameter value and the actual altitude error at which quadchute would …

Refactor uncommanded descend Quad-Chute

---

src/lib/events/enums.json
src/modules/commander/HealthAndArmingChecks/CMakeLists.txt
src/modules/commander/HealthAndArmingChecks/HealthAndArmingChecks.hpp
src/modules/commander/HealthAndArmingChecks/checks/openDroneIDCheck.cpp
src/modules/commander/HealthAndArmingChecks/checks/openDroneIDCheck.hpp
src/modules/commander/commander_params.c

The Open Drone ID system (aka Remote ID) should be present and healthy before the system can arm. There was no check for this so it has been added. A convenience parameter has also been added to change it to a warning but still allow arming or to disable the check completely.

Add Open Drone ID arming check

---

src/modules/navigator/mission.cpp
src/modules/navigator/rtl.cpp
src/modules/navigator/vtol_takeoff.cpp

`
mission_block::set_vtol_transition_item` sets the params of the mission item directly to values that make sense for NAV_CMD_DO_VTOL_TRANSITION, but don't for other NAV_CMDs. So make sure that whenever we use it, we then in the next step reset the touched mission_item fields.
acceptance radius and/or time_inside fields of mision_item can be wrong after a VTOL transition. 
Make sure to at least always fill the fields touched by set_vtol_transition_item, which are fields 0 (another union with eg time_inside), and acceptance_radius. 
Change the way of how `set_vtol_transition_item` works? Does it have to manually adapt the fields of _mission_item?
Some SITL testing.

Navigator: make sure to reset mission.item fields touched by set_vtol_transition_item

---

src/modules/navigator/mission.cpp
src/modules/navigator/rtl.cpp
src/modules/navigator/vtol_takeoff.cpp
src/modules/vtol_att_control/vtol_att_control_params.c
src/modules/vtol_att_control/vtol_type.cpp
src/modules/vtol_att_control/vtol_type.h

Port of https://github.com/PX4/PX4-Autopilot/pull/21641 and https://github.com/PX4/PX4-Autopilot/pull/21598 to 1.14

Port VTOL mission item resets and QC rework

---

src/modules/commander/commander_params.c
src/modules/fw_att_control/fw_att_control_params.c
src/modules/fw_pos_control/fw_path_navigation_params.c
src/modules/fw_rate_control/fw_rate_control_params.c
src/modules/vtol_att_control/standard_params.c
src/modules/vtol_att_control/tiltrotor_params.c

While setting up planes lately I noticed that a couple of parameter min/max constraints don't make sense or that some param meta data is missing. 
Further I reduce the default of FW_T_I_GAIN_THR further, as testing on a wide variety of vehicles showed that 0.05 is a more appropriate value. Follow up on https://github.com/PX4/PX4-Autopilot/pull/21360.
I also change the default of VT_TILT_TRANS to the more appropriate 0.4 (0.3 is usually too low to accelerate enough for the transition to complete).

FW/VTOL: open up a couple of param constraints

---

src/modules/commander/commander_params.c
src/modules/fw_att_control/fw_att_control_params.c
src/modules/fw_pos_control/fw_path_navigation_params.c
src/modules/fw_rate_control/fw_rate_control_params.c
src/modules/vtol_att_control/standard_params.c
src/modules/vtol_att_control/tiltrotor_params.c

Port of https://github.com/PX4/PX4-Autopilot/pull/21597 to 1.14. I think it makes sense to port these over, as I found them all while doing testing on 1.14.

[Port 1.14] FW/VTOL: open up a couple of param constraints

---

src/systemcmds/netman/netman.cpp

clarifies a few key aspects of the module for our docs here https://docs.px4.io/main/en/modules/modules_system.html#netman
Hey @davids5 it would be good to get your eyes on this one I want to make sure I captured the details correctly, I think the added info will help users.

netman: update module description

---

src/lib/version/px_update_git_header.py
src/lib/version/version.c
src/lib/version/version.h
src/modules/logger/logger.cpp

Since 'ecl' is nomore a git submodule, code lines related to 'ECL_LIB_GIT_VERSION' could be deleted
I found that in src/lib/version/px_update_git_header.py (line 123) :
~~~
if (os.path.exists('src/lib/ecl/.git')):
~~~
where 'ecl' used to be a submodule but now does not exist anymore, and  the macro definition 'ECL_LIB_GIT_VERSION' is not referenced by any code, so it could be deleted.
- delete unused code
- tested in sitl

delete unused ECL_LIB_GIT_VERSION

---

src/drivers/adc/ads1115/ads1115_main.cpp

This updates the docs for the ADC1115 ADC in order to make it clear:
- whether the driver is installed by default, and if not where.
- how the driver is enabled and whether/where it is enabled by default.
- if it is enabled, having a link to the parameter.
- What the ADC1115 actually is, with a link to the manufacturer.
It is a test case for similar changes I hope to make across the docs, and to explore what might be automated. I'll add that discussion in a separate comment.

ADS1115 Update docs - for discussion

---

src/modules/logger/log_writer.cpp
src/modules/logger/log_writer.h
src/modules/logger/log_writer_file.cpp
src/modules/logger/log_writer_file.h
src/modules/logger/logger.cpp
src/modules/logger/logger.h

This can also happen if the maximum file size is reached.

logger: restart on file write error

---

msg/SensorGps.msg
src/drivers/gps/gps.cpp
src/drivers/uavcan/sensors/gnss.cpp
src/drivers/uavcan/sensors/gnss.hpp

This PR adds support for the UBX-RXM-RTCM message which gives feedback on whether the ublox module is using the RTCM data that is being sent to it.
Requires https://github.com/PX4/PX4-GPSDrivers/pull/130
I also discovered a bug in the uavcan rtcm publisher. When the mavlink stream goes down there is a chance that a second instance of the gps_inject_data topic is created. When that happens the uavcan publisher isn't setup to handle switching streams. 
I mirrored the gps driver instance switching logic but discovered it will get stuck on a non existing gps_inject_data instance. 
@julianoes Can you take a look? 
```
nsh> gps status
INFO  [gps] Main GPS
INFO  [gps] protocol: UBX
INFO  [gps] status: OK, port: /dev/ttyS0, baudrate: 921600
INFO  [gps] sat info: disabled
INFO  [gps] rate reading: …
```

Ublox add UBX-RXM-RTCM for RTCM input status

---

src/modules/ekf2/ekf2_params.c

The description of EKF2_HDG_GATE made me assume this parameter was irrelevant for a vehicle that doesn't use a magnetometer:
I'm working on a multicopter with external odometry input (via mavlink ODOMETRY type VISION). I want the external odometry system's heading to always be trusted, so I had set EKF2_HDG_GATE very high. Later, having forgotten about the original reason for setting EKF2_HDG_GATE, I found that the docs for this parameter say "Gate size for magnetic heading fusion". Since I do not use a magnetometer, this made me think I'd set this parameter by mistake, so I reset it to the default value. When flying, it became clear that it does indeed also affect yaw estimation with only external vision/odometry yaw, but the parameter description is a bit misleading.
The simplest fix is …

ekf2: Fix description of EKF2_HDG_GATE

---

src/modules/mavlink/streams/CAMERA_TRIGGER.hpp

The camera triggering logic is currently "random" when more than one camera sending a mavlink heartbeat is connected to PX4. The trigger logic in PX4 currently stores the last camera mavlink component ID it saw a heartbeat from, and then sends trigger commands to that camera. If there are multiple cameras sending heartbeats, it is more or less random which camera gets triggered when a capture command is sent to PX4. This includes missions that have capture waypoints, or surveys that capture a photo periodically.
This PR changes the behaviour such that always all mavlink cameras are triggered, making the photo capture process deterministic, which is the main improvement.
This changes nothing for systems that have only one camera, as it will still trigger this one camera.
The only scenario …

Always trigger all cameras

---

src/lib/mixer_module/mixer_module.cpp
src/lib/mixer_module/mixer_module.hpp

When integrating a product with PWM ESCs I found that the current PWM is suboptimal:
Excpected: When the mixed motor command is exactly the minimum during the ramp time it ramps from the disarmed PWM value to the minimum PWM value.
Unexpected: When the mixed motor command is even just slightly higher than the minimum the ramp jumps up to a higher value than the disarmed PWM value and then ramps from there to the commanded throttle scaled between minimum PWM and maximum PWM. Additionally the first time a vehicle is armed after boot there is a 50 millisecond delay until the ramp actually starts.
- Replace the complicated ramp calculation with a simpler one that fades the current motor command in with a scale ramping from 0 to 1.
- Remove the ancient init state of the ramp state machine that …

Motor output ramp consistent for higher than minimum initial motor command

---

src/drivers/actuators/modal_io/modal_io.cpp
src/drivers/actuators/modal_io/modal_io.hpp
src/drivers/dshot/DShot.h
src/lib/mixer_module/actuator_test.cpp
src/lib/mixer_module/mixer_module.cpp
src/modules/commander/esc_calibration.cpp

When testing https://github.com/PX4/PX4-Autopilot/pull/21513 I found (again) that PWM calibration does not do what I expect and leads to it almost being impossible to configure PWM outputs consistently once a calibration was performed. That's why I opened #21634 and want to fix that first.
Fixes #21634 
- Make PWM calibration range consistent 1000-2000us (which maps to 125-250us for Oneshot) independent of minimum and maximum PWM configuration. These parameters represent the PWM value where the motors start spinning and stops going faster and producing more thrust. These definitions are separate from the calibration and do not match the same values for any ESC I've ever used. This was also discussed for example here: https://github.com/PX4/PX4-Autopilot/pull/11663#issuecomment-473406492
- …

Fix PWM/Oneshot calibration

---

src/modules/mavlink/streams/HEARTBEAT.hpp

When performing a HITL simulation, the PX4 heartbeat always sends the system_status FLIGHT_TERMINATION, although the simulation works just fine and the simulated vehicle reacts to the commands. This is due to the fact, that in HITL the actuators are always locked. This flag is mapped to the system status flight termination.
- In the mavlink Heartbeat stream only consider the armed.lockdown flag, if the system is not configured as HITL.
```
Bugfix Mavlink heartbeat stream: Fix system status always reporting FLIGHT_TERMINATION in HITL
```
- SIH simulation, check mavlink inspector in AMC.

mavlink heartbeat stream: Fix system status always reporting FLIGHT_TERMINATION in HITL

---

src/drivers/actuators/modal_io/modal_io.cpp
src/drivers/actuators/modal_io/modal_io.hpp
src/drivers/dshot/DShot.h
src/lib/mixer_module/actuator_test.cpp
src/lib/mixer_module/mixer_module.cpp
src/modules/commander/esc_calibration.cpp

1.14 port of https://github.com/PX4/PX4-Autopilot/pull/21711
Applied cleanly. Not much difference between the main and 1.14 branches yet.
```
Bugfix: Fix PWM/Oneshot calibration to consistent range
Documentation: Need to clarify https://docs.px4.io/main/en/advanced_config/esc_calibration.html#esc-calibration
```

[1.14] Fix PWM/Oneshot calibration

---

src/modules/mc_pos_control/MulticopterPositionControl.cpp
src/modules/mc_pos_control/PositionControl/PositionControl.cpp
src/modules/mc_pos_control/PositionControl/PositionControl.hpp

See https://github.com/PX4/PX4-Autopilot/issues/20275#issuecomment-1539704155
Port of https://github.com/PX4/PX4-Autopilot/pull/21512
```
Bugfix: Prevent out-of-range hover thrust from screwing the position controller up
```
- Not tested on 1.13 specifically but I'm assuming the original author @hendjoshsr71 used an equivalent change on 1.13 before.
Original prs:
https://github.com/PX4/PX4-Autopilot/pull/21372
https://github.com/PX4/PX4-Autopilot/pull/21380

[1.13] Fix MC thrust spike

---

src/modules/commander/failsafe/failsafe.cpp
src/modules/commander/failsafe/failsafe.h

`_param_com_rc_in_mode.get()` was compared with the wrong enum. 
- Add enum `RcInMode` to improve code readability
none necessary

Fix enum for COM_RC_IN_MODE in failsafe

---

src/lib/rate_control/rate_control.cpp
src/lib/rate_control/rate_control.hpp
src/modules/fw_rate_control/FixedwingRateControl.cpp
src/modules/fw_rate_control/FixedwingRateControl.hpp

Context: https://github.com/PX4/PX4-Autopilot/issues/21501#issuecomment-1584754445
Actuator saturation logic in the FW rate controller was not working as intended if the actuators for a certain axis aren't in the matrix 1 (servo matrix) for VTOL. That led to the rate controller being very often disabled as the controller thought it the axis was saturated. That in turn leads to very bad rate tracking. 
It is most prominent when flying a Quad tailsitter without control surfaces, as in this case all 3 axis are affected. 
Add logic for when to use which allocation matrix.
```
Bugfix: fix actuator saturation handling for VTOLs with differential thrust in fixed-wing flight
```
We need to work towards keeping this customization per vehicle in the allocation.
SITL tested. 
I …

FW Rate Controller: fix saturation logic for VTOLs with differential thrust enabled

---

src/lib/parameters/autosave.cpp
src/lib/parameters/autosave.h
src/lib/parameters/param.h
src/lib/parameters/parameters.cpp
src/lib/parameters/parameters_ioctl.cpp
src/lib/parameters/parameters_ioctl.h
src/lib/parameters/usr_parameters_if.cpp
src/modules/commander/airspeed_calibration.cpp
src/modules/commander/worker_thread.cpp
src/modules/temperature_compensation/temperature_calibration/task.cpp
src/systemcmds/param/param.cpp
src/systemcmds/tests/test_parameters.cpp

After the latest param rework, the file lock in `param_save_default` was changed to a `trylock`, to prevent any blocking in the param system. This makes `param_save_default` occasionally fail, if it is called from multiple threads at the same time. This is correct, but unexpected especially when used from the shell.
This changes the `param_save_default` function to have be either blocking or non-blocking.
From the shell and from modules that expect a synchronous API, the blocking version is called. From the work queue, the non blocking version is called. 
This also modifies the autosave worker, to re-schedule writing up to three times, in case writes fail.
- Bugfix: Blocking API for param save
As an alternative, we could disable the autosave worker in the CI tests. This …

param save: Add a blocking API for param saves to be used from shell.

---

src/drivers/distance_sensor/lightware_laser_serial/lightware_laser_serial.cpp

When trying to fix https://github.com/PX4/PX4-Autopilot/pull/21737#pullrequestreview-1489844308 and compiling `make beaglebone_blue` locally with `arm-linux-gnueabihf-gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0` I got a compile warning -> error:
```
PX4-Autopilot/src/drivers/distance_sensor/lightware_laser_serial/lightware_laser_serial.cpp: In member function ‘virtual void LightwareLaserSerial::Run()’:
PX4-Autopilot/src/drivers/distance_sensor/lightware_laser_serial/lightware_laser_serial.cpp:311:39: error: ‘ssize_t write(int, const void*, size_t)’ reading 5 bytes from a region of size 4 [-Werror=stringop-overread]
311 |                         (void)!::write(_fd, &data, strlen(data));
|                                ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to …
```

lightware_laser_serial: fix pointer for enabling serial mode

---

ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt

This just reserves the airframe numbers for custom simulation models to avoid collisions with master.  The range was set such that it matches the custom range for actual airframes.

ROMFS : POSIX Airframes reserve space for custom models

---

Tools/ecl_ekf/analysis/checks.py
Tools/ecl_ekf/analysis/metrics.py
Tools/ecl_ekf/plotting/pdf_report.py

Replace reject_mag* with fs_bad_mag*
Apply the fix from #21429
Should also fix #21686

Fix reject_mag* and imu_coning* key errors

---

src/modules/commander/HealthAndArmingChecks/CMakeLists.txt
src/modules/commander/HealthAndArmingChecks/HealthAndArmingChecks.hpp
src/modules/commander/HealthAndArmingChecks/checks/armPermissionCheck.cpp
src/modules/commander/HealthAndArmingChecks/checks/armPermissionCheck.hpp
src/modules/commander/commander_params.c

The carrier is maintaining or showcasing the vehicle powered but not armed and wants to make sure it's not accidentally armed.
- Add parameter `COM_ARMABLE` defaulting to allow arming which can be set to false to disallow arming
```
Feature: New parameter: COM_ARMABLE if set to 0 arming is disallowed
```
Documentation: Parameter reference is automatically updated. Safety chapter does not specifically exist or does it?
- I tested this in Simulation. Like expected it does prevent arming when disallowed but does not failsafe when the parameter is set in air.

ArmingChecks: disallow arming via parameter

---

boards/px4/fmu-v5x/init/rc.board_mavlink
src/modules/commander/ModeManagement.cpp
src/modules/commander/ModeManagement.hpp
src/modules/commander/ModeUtil/ui.hpp

- All available flight modes showed up in the selector, not just the ones we want to be able to select.
- Missing `ATTITUDE_QUATERNION` which was needed by the external mode.
- Define user-selectable flight modes separately from valid flight modes.
- Add `ATTITUDE_QUATERNION` MAVLink stream
N/A
N/A
Flight tests
N/A

Fix selectable flight modes

---

src/drivers/barometer/invensense/icp201xx/ICP201XX.cpp

Fixes wrong altitude reporting trough barometer on CUAV FMUv6X hardware with the ICP201XX sensor by InvenSense. The issue was first reported here https://github.com/PX4/PX4-Autopilot/pull/19819#issuecomment-1338700102
Log with issue
https://logs.px4.io/plot_app?log=a3e68174-e2e7-4b81-b47f-87e03cbc2d69
Log with fix
https://logs.px4.io/plot_app?log=921154ae-a088-4334-b899-debdc04075d5

icp201: increase startup delay (FMUv6X)

---

src/modules/vtol_att_control/tiltrotor.cpp
src/modules/vtol_att_control/tiltrotor.h
src/modules/vtol_att_control/tiltrotor_params.c

This affects how soon after a backtransition the vehicle has the full hover controller running again. Specifically it reduces the duration of the ramp down of the motors prior to tilting them.
The backtransition logic is split into 4 parts:
- ramp down motors
- tilt motors
- ramp up motors
- wait till transition exit conditions are met (groundspeed and time)
The ramp down and the ramp are currently hard-coded to 1s each, as well as the tilting duration. That means that it currently takes 3s from starting the transition to having full MC controller effectiveness. During the first 2s of them purely the FW controller is running and working on stabilizing the system, and then for 1s the MC controller is running but not fully yet. If the vehicle decelerates very fast it can happen that the …

Tiltrotor: VTOL back-transition: expose tilting time as parameter and reduce overall duration

---

ROMFS/px4fmu_common/init.d-posix/airframes/10042_sihsim_xvert
ROMFS/px4fmu_common/init.d-posix/airframes/1041_gazebo-classic_tailsitter
ROMFS/px4fmu_common/init.d-posix/airframes/1045_gazebo-classic_quadtailsitter
ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt
ROMFS/px4fmu_common/init.d/airframes/1102_tailsitter_duo_sih.hil
ROMFS/px4fmu_common/init.d/airframes/13200_generic_vtol_tailsitter
src/modules/simulation/simulator_mavlink/sitl_targets_gazebo-classic.cmake

Port of https://github.com/PX4/PX4-Autopilot/pull/20558 to 1.14.
I realized that we have these tailsitter SITL fixes not yet in 1.14. Without it the normal tailsitter (`make px4_sitl_default gazebo_tailsitter`) has a ton of oscillation in Hover and the control surface less quadtailsitter target doesn't exist yet (`make px4_sitl_default gazebo_quadtailsitter`).

SITL Tailsitter tuning fixes and add quadtailsitter 

---

src/modules/navigator/loiter.cpp
src/modules/navigator/loiter.h

While working on https://github.com/PX4/PX4-Autopilot/pull/21775 I noticed this seemingly unnecessary class variable `_loiter_pos_set`, that was set to false in `on_inactive()` or in `on_active`, and then though only ever checked in `on_activation` (through `set_loiter_position()`). I don't see how it could be false when entering on_activation(), and thus can just be removed, or am I missing something?
Remove it!
```
Refactor: remove unnecessary variable
```
Bit of SITL testing.

Navigator: loiter: remove unnecessary _loiter_pos_set

---

.github/workflows/stale.yml

Having newline between I think didn't apply the PR stale days setting of 30 properly (it was using 45), so removed newline.
And it seemd that unless I set the days-before-close to -1 intentionally, it would still close the Issue/PRs, as the default value
is 7 already. So set the days to -1 to disable closing action.
Also updated version of the stale action to v8, cuz why not.
Debug is now removed, and will actually apply the action!

Stale bot configure

---

src/modules/flight_mode_manager/tasks/ManualAcceleration/FlightTaskManualAcceleration.cpp
src/modules/flight_mode_manager/tasks/ManualAcceleration/FlightTaskManualAcceleration.hpp
src/modules/flight_mode_manager/tasks/ManualAltitude/FlightTaskManualAltitude.cpp
src/modules/flight_mode_manager/tasks/ManualAltitude/FlightTaskManualAltitude.hpp
src/modules/mc_pos_control/multicopter_altitude_mode_params.c
src/modules/mc_pos_control/multicopter_position_control_params.c
src/modules/mc_pos_control/multicopter_stabilized_mode_params.c

When helping @marcinolokk with a new slower Position mode input feature I realized that there is quite some duplication in yaw handling over `FlightTaskManualAltitude` and `FlightTaskManualAcceleration`.
I had unified the handling in the `StickYaw` class in https://github.com/PX4/PX4-Autopilot/pull/21192 but apparently did not follow through and only use it once for all cases.
- Remove forgotten parameter metadata trailing zeroes from https://github.com/PX4/PX4-Autopilot/pull/21729 (FYI @sfuhrer)
- Remove duplicate instantiation and call to the `StickYaw` class in `FlightTaskManaulAcceleration`. It inherits the instance from `FlightTaskManualAltitude` and also calls the update by running `FlightTaskManualAltitude`'s update already.
- Remove all the legacy yaw handling from …

Do not handle yaw stick multiple times in Altitude and Position mode

---

platforms/nuttx/init/kinetis/rc.board_arch_defaults
platforms/nuttx/init/stm32/rc.board_arch_defaults
platforms/nuttx/init/stm32f7/rc.board_arch_defaults
platforms/nuttx/init/stm32h7/rc.board_arch_defaults

Not all boards (kakutef7, omnibus) have EKF2 enabled so adding silent flag

rc.board_arch_defaults: add the silent flag for EKF2_MULTI_IMU

---

src/modules/mavlink/mavlink_log_handler.cpp

When you send a LOG_REQUEST_LIST message with the `start` log id > the `end` log id, PX4 responds with LOG_ENTRY messages for every single log ID up until, I assume, `_next_entry` overflows and finally `== _last_entry` at some point.
This change results in just a single LOG_ENTRY being sent for the `start` log id if `end > start`. I think this is a little better than sending up to u32 max value LOG_ENTRY messages.
I really only tested this manually, but happy to perform other testing if necessary.

Handle illogical LOG_REQUEST_LIST messages more gracefully

---

boards/px4/fmu-v6x/init/rc.board_mavlink

v6x: start mavlink on TELEM2 for skynode

---

src/drivers/distance_sensor/vl53l1x/vl53l1x.cpp

The VL53L1X sensor was updating at a very high rate and taking up considerable CPU resources. The realistic update rate in long range mode (4 meters) is 200ms. The sensor should only be run at 5hz in this mode, instead it was running at a much higher update rate.

VL53L1X: Reduce CPU usage

---

src/modules/ekf2/EKF/ekf.h
src/modules/ekf2/EKF/ev_control.cpp
src/modules/ekf2/EKF/ev_height_control.cpp
src/modules/ekf2/EKF/ev_pos_control.cpp
src/modules/ekf2/EKF/ev_vel_control.cpp

When the vision frame is not NED, we need to rotate the EV data by the attitude difference between the two frames. The issue is that any noise in that difference will be transferred on the EV position and velocity measurements.
This can in some extreme case cause a constant reset of the estimator as the data can often fail the innovation check.
Since the attitude error is almost constant (really slow drift), it can be heavily low-passed to remove most of the noise.
```
Add vision attitude error filter
```
estimate the attitude error
unit and sitl tests

EKF2: vision attitude error filter

---

src/modules/navigator/loiter.cpp

https://github.com/PX4/PX4-Autopilot/issues/21702
Vehicle keeps flying towards Loiter waypoint if Hold mode is selected. In the past we within Navigator set the type to POSITION when far away from a Loiter waypoint, and then only to LOITER when really on established loiter, but this distinction is now no longer part of Navigator and the FW position controller handles it.
When switching into Hold mode establish a Loiter around current position, even if we were before already loitering (eg in Mission mode). This results in the same behavior when switching into Hold/Loiter mode directly (either through RC switch or in the flight mode selection in QGC) or through the "Hold" button in QGC (which sends a DO_REPOSITION with the fields at the current position). 
In this screen recording you see …

Navigator: Loiter: always establish new Loiter with center at current position

---

src/modules/navigator/rtl.cpp

RTL::find_RTL_destination() is called also when the RTL has already started, and can override the set _destination etc. I don't think that's desired.
This was introduced through a refactor commit: https://github.com/PX4/PX4-Autopilot/pull/21208/commits/2bff49475b504b29eba8fb5cf1cb65400ea80482
Remove it again.
```
Bugfix: RTL: do not edit RTL destination once RTL is started
```

Navigator RTL: run find_RTL_destination() only on_inactive

---

ROMFS/px4fmu_common/init.d/rcS

This is required to auto-start the is31fl3195 driver if connected.
@vincentpoont2 
Needs to also go into v1.14.

ROMFS: auto try RGBLED is31fl3195

---

ROMFS/px4fmu_common/init.d/rcS

Backport of https://github.com/PX4/PX4-Autopilot/pull/21718.

[BACKPORT v1.4] ROMFS: auto try RGBLED is31fl3195

---

platforms/posix/src/px4/common/px4_daemon/pxh.cpp
src/lib/matrix/matrix/SquareMatrix.hpp

px4:
```
/home/patrick/git/blue/PX4-Autopilot/platforms/posix/src/px4/common/px4_daemon/pxh.cpp: In member function ‘void px4_daemon::Pxh::run_remote_pxh(int, int)’:                                                                   
/home/patrick/git/blue/PX4-Autopilot/platforms/posix/src/px4/common/px4_daemon/pxh.cpp:208:25: error: ‘uint8_t’ was not declared in this scope                                                                                 
208 |                         uint8_t buffer[512];    
```
SquareMatrix:
```
In file included from /home/patrick/git/blue/PX4-Autopilot/src/lib/matrix/matrix/math.hpp:8,                                                                                                                                   
from …
```

Random fixes for GCC 13

---

src/modules/ekf2/EKF2.cpp

I found that EKF2.cpp file used hard-coded values to check that the *EKF2_MULTI_IMU* and *EKF2_MULTI_MAG* values matched the maximum allowed value.
- Use the already existing constants (defines) instead of hard-coded values. This defines were already available in EKF2.hpp

EKF2 cleanup. Use MAX_NUM_x constants instead of hard-coded numbers

---

src/modules/navigator/navigator_main.cpp

When asking for an altitude change only, the lat/lon is NAN and that makes the geofence check pass regardless of the change in altitude, allowing the drone to climb above the fence.
Set the lat/lon to the current position if NAN
```
Fix geofence when changing altitude through reposition.
```
SITL tests

geofence: fix altitude change fence check

---

src/systemcmds/netman/netman.cpp

Backport of https://github.com/PX4/PX4-Autopilot/pull/21680, to fix the Module documentation CI broken in `release/1.14` branch, caused by https://github.com/PX4/PX4-Autopilot/pull/21673.
Example CI run where the module documentation was not getting built: https://github.com/PX4/PX4-Autopilot/actions/runs/5510837000/jobs/10045596294#step:4:46

[v1.14 backport] netman line too long

---

src/modules/ekf2/EKF2.cpp

The timestamps of estimator_ev_pos_bias are broken in EKF replay.
Fill timestamp field with what was passed into PublishEvPosBias() as an argument instead of calling hrt_absolute_time().

EKF2: use timestamp from argument of PublishEvPosBias()

---

src/modules/rc_update/RCUpdateTest.cpp
src/modules/rc_update/rc_update.cpp
src/modules/rc_update/rc_update.h

When reviewing #21763 I wasn't exactly sure why the fix is needed at all see https://github.com/PX4/PX4-Autopilot/pull/21763#issuecomment-1614360730. I tested on hardware and realized it's actually broken and I still don't know why it broke. But I was sure I wanted it to not break the same way again and the function to be more readable. So I added unit testing and fixed it by simplifying the function rather than adding to it.
Fixes #19809
Closes #21763
- Improve unit testing of the RCUpdate class I added in #19579
- adding protected scope again
- setting parameters from outside the class
- Add unit tests for the return switch
- Positive threshold cases
- Corner cases
- Negative threshold cases that failed
- Fix negative threshold cases
```
Bugfix: Negative RC switch thresholds
```
Unit …

rc_update: fix on-off-switch with negative threshold values

---

src/modules/rc_update/rc_update.cpp
src/modules/rc_update/rc_update.h

Port of the minimal fix from: https://github.com/PX4/PX4-Autopilot/pull/21796
The logic was tested as part of the original pr.
```
Bugfix: Negative RC switch thresholds
```

[1.14] rc_update: fix on-off-switch with negative threshold values

---

src/modules/ekf2/EKF/common.h
src/modules/ekf2/EKF/optflow_fusion.cpp
src/modules/ekf2/EKF/optical_flow_control.cpp
src/modules/ekf2/EKF2.cpp
src/modules/ekf2/EKF2.hpp
src/modules/ekf2/ekf2_params.c

This PR brings in @katzfey changes from https://github.com/PX4/PX4-Autopilot/pull/21436 and adds a new parameter EKF2_OF_QMIN_GND to set the minimum optical flow quality when on the ground. Solves https://github.com/PX4/PX4-Autopilot/issues/20929
When the optical flow sensor is sitting in tall grass, it will output a 0 quality and is_quality_good is become false. 
This will need to be backported into the 1.14 release branch.
Optical Flow fusion with GPS fusion on
https://review.px4.io/plot_app?log=d6a23cd7-a292-49c5-a543-cc483856d019
On a different 250 - https://review.px4.io/plot_app?log=2e87a149-4992-47d1-84fe-693675a0221c
https://review.px4.io/plot_app?log=f353442a-f324-4b15-b4cb-109403e36ebe
Optical Flow fusion with GPS fusion off …

Optical Flow Fixes

---

src/modules/ekf2/EKF/ekf_helper.cpp
src/modules/ekf2/EKF/terrain_estimator.cpp
src/modules/ekf2/EKF2.cpp
src/modules/ekf2/Utility/PreFlightChecker.cpp
src/modules/ekf2/Utility/PreFlightChecker.hpp

While checking logs from https://github.com/PX4/PX4-Autopilot/pull/21769 I saw that there were still some pre-flight failure problems due to large opt flow innovations
This is due to the predicted optical flow with a really low distance to the ground: `flow = vel / range`
Scale the innovation check with range. That way, the check is more meaningful as it requires to have a low velocity innovation.
In addition to that the dist bottom wasn't reported when the range finder code isn't built. This was incorrect as the terrain height can be estimated using optical flow data.
```
Fix false flow innovation pre-flight failure
```
Gazebo-classic iris opt flow

Optical flow: pre-flight check improvements

---

src/modules/rover_pos_control/RoverPositionControl.cpp

Backport of https://github.com/PX4/PX4-Autopilot/pull/21271 to 1.14 release

Release 1.14 Backport. Fix Rover Thrust Normalization

---

src/lib/sensor_calibration/Magnetometer.cpp
src/modules/ekf2/EKF2.cpp
src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp

I realized that the estimated mag bias was never applied back to the calibration. I found the following bugs:
1. since last_us is set to 0 every time the bias is not observable, the total time was also reset -> needed 30 consecutive seconds in mag 3D to be declared "stable"
2. after landing, the mag_aligned_in_flight flag is reset. Using this for bias validity makes it invalid before we have a chance to save it to the calibration.
3. the change in parameter is (at least in sim) < 0.01gs when the parameter is wrong by 0.1 gs, making it being rejected in `set_offset`
Fix 1.; now it's truly a period of accumulated time, no need to be consecutive anymore
Remove check for mag_aligned_in_flight; we anyway don't enter mag 3D before that
Reduce the minimum mag offset param change to 0.001gs …

Fix mag offset correction from estimated bias

---

.ci/Jenkinsfile-compile
Tools/docker_run.sh

It's a follow up to https://github.com/PX4/PX4-Autopilot/pull/21749 since I see Jenkins and metadata builds failing on the main branch still with the same error that was solved on the normal linux target GitHub Actions before.
I wasn't aware that there are multiple different container versions used for almost the same build.
Of course they need to use the updated container.
I'm assuming the update metadata uses what's specified in `Tools/docker_run.sh` and Jenkins uses `.ci/Jenkinsfile-compile`.
```
- Fix remaining CI by updating to Debian 11 for linux targets and have the required cmake version
```
- Not tested locally. I'm assuming these other jobs will run fine with the updated container since their current error was solved before the same way.

Other CI: Use Debian 11 for linux targets and have the required cmake version

---

msg/VehicleStatus.msg
src/lib/avoidance/ObstacleAvoidanceTest.cpp
src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.hpp
src/modules/manual_control/CMakeLists.txt
src/modules/manual_control/ManualControl.cpp
src/modules/manual_control/ManualControl.hpp
src/modules/manual_control/ManualControlSelector.cpp
src/modules/manual_control/ManualControlTest.cpp
src/modules/rc_update/RCUpdateTest.cpp

- 1 Unexpected action regaining RC
- Valid RC with switch in position A
- RC signal lost (or RC is turned off)
- Switch is moved to position B
- RC regained after a few minutes
- trigger for switch position B is immediately executed
- 2 Unexpected action first time RC
- Vehicle flying autonomously without RC input
- RC is turned on with mode switch in e.g. Acro position
- Vehicle switches to Acro mode and crashes because pilot is not prepared
- 3 Unexpected action RC as safety fallback (similar to previous)
- Vehicle flying in any mode with joystick as stick input and RC configured as fallback
- Joystick signal is lost because of link or ground station application outage
- Vehicle falls back to RC stick input for safety but also switches mode to the mode switch position
- Make …

RC switch improvement for mid air (re)gain/fallback

---

ROMFS/px4fmu_common/init.d/rc.interface

Credits to @eyeam3 for pointing out to me that these ifs do not help because the ESC mask should always be saved.
If the environmental variable is any string in this case "none", then the integer parameter gets set to 0 which is exactly what we want.
Admittedly I did not find any real case in which the variables are none it could in principle still happen and in that case the mask is wrongly set after switching airframe/output configuration.
I removed the ifs again that were in my understanding experimentally added in https://github.com/PX4/PX4-Autopilot/commit/7c0165ea0c4f783c1d49a9446d5559248c0cc171 from https://github.com/PX4/PX4-Autopilot/pull/18769 to work against some CI issues.
See screenshot of what the command does with none.
Related to …

rc.interface: also save empty ESC mask (none)

---

src/modules/commander/HealthAndArmingChecks/checks/airspeedCheck.cpp
src/modules/commander/HealthAndArmingChecks/checks/airspeedCheck.hpp
src/modules/commander/commander_params.c
src/modules/navigator/navigator_params.c
src/modules/vtol_att_control/vtol_att_control_params.c
src/modules/vtol_att_control/vtol_type.cpp
src/modules/vtol_att_control/vtol_type.h

Safes a bit of flash and reduces entropy by removing two params that aren't really required anymore. 
```
Remove COM_ARM_ARSP_EN and VT_B_DEC_FF params, plus shorten parameter descriptions
```

Some parameter cleanup

---

src/modules/ekf2/EKF/common.h
src/modules/ekf2/EKF/ekf_helper.cpp
src/modules/ekf2/EKF/optflow_fusion.cpp
src/modules/ekf2/EKF/optical_flow_control.cpp
src/modules/ekf2/EKF/terrain_estimator.cpp
src/modules/ekf2/EKF2.cpp
src/modules/ekf2/EKF2.hpp
src/modules/ekf2/Utility/PreFlightChecker.cpp
src/modules/ekf2/Utility/PreFlightChecker.hpp
src/modules/ekf2/ekf2_params.c

backport of 
https://github.com/PX4/PX4-Autopilot/pull/21769 and
https://github.com/PX4/PX4-Autopilot/pull/21789

[RELEASE/1.14] Opt flow fixes

---

src/drivers/actuators/modal_io/modal_io.cpp
src/drivers/tap_esc/TAP_ESC.cpp
src/drivers/uavcan/actuators/esc.cpp
src/modules/simulation/gz_bridge/GZMixingInterfaceESC.cpp
src/modules/simulation/simulator_mavlink/SimulatorMavlink.cpp

- esc_status is an optional logging topic resulting in it not being logged if it doesn't get advertise -> Add advertise where applicable.
- Main application was to get feedback from dronecan esc, but added it to other instances,

advertise esc_status uorb message where it publishes

---

src/lib/sensor_calibration/Magnetometer.cpp
src/modules/ekf2/EKF2.cpp
src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp

Minimal cherry-pick of https://github.com/PX4/PX4-Autopilot/pull/21812 for v1.14.
@bresch

[v1.14 backport] mag_cal: fix mag bias estimate to mag cal

---

.github/workflows/compile_macos.yml

The MacOS workflow for CI was set for macOS-10.5, which isn't available anymore at GitHub, causing macOS builds to fail when they couldn't find a runner.
```
CI: Bump macOS Runner OS to the latest
```
**[For context here's github runners page](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)**

ci: update macos runner

---

src/modules/flight_mode_manager/FlightModeManager.cpp

Concurrent internal task sending setpoint at the same time as external mode when testing https://github.com/PX4/PX4-Autopilot/pull/20707:
- Add exclusion for external modes when starting internal flight tasks.
A direct mapping from the navigation state to flight task would be even more desired. I should look into this.
This was reported to fix the issue as expected.

FlightModeManager: avoid internal flight task running concurrently with external mode

---

.ci/Jenkinsfile-hardware
.devcontainer/devcontainer.json
.github/workflows/checks.yml
.github/workflows/compile_linux_arm64.yml
.github/workflows/compile_nuttx.yml
.github/workflows/deploy_all.yml
.github/workflows/failsafe_sim.yml
.github/workflows/metadata.yml
Jenkinsfile
Tools/docker_run.sh
Tools/generate_board_targets_json.py

I realized I did not catch all the container version strings in #21831 
In today's maintainer call it was all about CI and one of the topics was the still failing metadata deployment target on all the builds on main see e.g. https://github.com/PX4/PX4-Autopilot/actions/runs/5584519814/jobs/10206077634. The error is still what I originally solved in #21749 so I did just not understand all the places different container versions are used.
- I changed the `generate_board_targets_json.py` script to
- not just infer the container name from the platform name (isn't that better error handling?)
- explicitly output the full container tag for each platform and toolchain
- This is my (hopefully last) take at unifying all the versions of containers in use in CI.
```
CI: unify all container versions …
```

CI: Fix metadata deployment, unify all container versions in use

---

.github/workflows/deploy_all.yml

`Deploy metadata for all targets / build beaglebone` still failing now with the new error:
`fatal: detected dubious ownership in repository at '/__w/PX4-Autopilot/PX4-Autopilot'`
Port the workaround from https://github.com/PX4/PX4-Autopilot/pull/21749 namely commit a6d2c2cf5e21ecdad8d737c31de81fab128898c5 to the metadata deployment. I double-checked that if you have an older version of git this setting gets added without failing.
It builds locally, I cannot reproduce the permission setup that GitHub Actions creates with the checkout plugin but the same fix worked on the other ci pipelines that use this container and failed with the same error.

CI: deploy_all: add git ownership workaround

---

.github/workflows/compile_linux.yml
.github/workflows/compile_linux_arm64.yml
.github/workflows/compile_nuttx.yml

As discussed in [maintainer's call](https://discuss.px4.io/t/px4-maintainers-call-july-18-2023/33189#ci-improvements-6), this adds `stable`, `beta`, and `release/*` branches to the triggering conditions for target compile actions.
Now we will be able to confirm whether the release branches (as well as manually controlled stable and beta branches) have any target compilation issues constantly.

Enable Target Compile Github Actions also on stable, beta, release branches

---

src/modules/temperature_compensation/temperature_calibration/mag.cpp

MacOS CI failing with:
```
'sprintf' is deprecated: This function is provided for compatibility reasons only. Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.
```
Use snprintf with the buffer limit since it's better practise and hopefully will fix MacOS CI.
```
Refactor: thermal calibration cstring better practise
```
There are many more sprintfs mostly in the xrce log functionality (submodule) but apparently that's not compiled by default for SITL.
Builds locally on Ubuntu, let's see what MacOS CI does.
Example failed build: https://github.com/PX4/PX4-Autopilot/actions/runs/5602138930/jobs/10246984717

temperature_compensation: use snprintf instead of sprintf

---

platforms/nuttx/src/px4/common/px4_init.cpp

This is a small issue found in code inspection;  failure of mounting procfs goes unnoticed while the return value is not correctly checked

px4_init.cpp: Properly check the return value of mounting procfs

---

src/modules/ekf2/EKF/estimator_interface.cpp
src/modules/ekf2/test/test_EKF_gps.cpp

fixes https://github.com/PX4/PX4-Autopilot/issues/21828
Already fixed on 1.14 (https://github.com/PX4/PX4-Autopilot/pull/20686) but this was a regression from 1.12 that could lead to a crash
Added unit test for this exact condition.

[RELEASE/1.13] Stop GNSS fusion when fix is loss

---

ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator

In simulation, with env. var. `GZ_VERBOSE=1` and a Gazebo world is already running, GZBridge fails to start because it gets the wrong name for the running world. This is because the `grep` command used retrieve only the first occurrence of "/world/.*/clock" and thus, it gets `Topic: [@/theotime-Precision-5570:theotime@/world/multicopter/clock]` instead of the real name of the topic `/world/multicopter/clock`.
Fixes #{21727}
- Grep only the lines that **start** with `/world/.*/clock`, which is the case 
no need
Gazebo's API has a "Name" endpoint for worlds, admittedly it could be cleaner to exploit that. The grep tech could create more issues in the future.
- tested on my machine. Works with GZ_VERBOSE=0 and 1. The name of world is correctly found.
N/A

Fix gz_bridge gets wrong world name when GZ_VERBOSE=1

---

Tools/simulation/gz/worlds/default.sdf

This can be useful for apply arbitrary forces like simulating hand launching a vehicle (throwing it in the air).
Example
``` Bash
$ gz topic -t /world/default/wrench -m gz.msgs.EntityWrench -p '
entity {
name: "x500_0"
type: 2
}
wrench {
force {x:100, y:200, z:5000}
torque {x:5, y:6, z:7}    
}
'
```

Tools/simulation/gz: load ApplyLinkWrench plugin by default

---

msg/EstimatorStatus.msg
src/modules/ekf2/EKF/common.h
src/modules/ekf2/EKF/ekf.h
src/modules/ekf2/EKF/estimator_interface.h
src/modules/ekf2/EKF/mag_control.cpp
src/modules/ekf2/EKF2.cpp
src/modules/ekf2/EKF2.hpp
src/modules/ekf2/ekf2_params.c
src/modules/ekf2/test/sensor_simulator/ekf_wrapper.cpp
src/modules/ekf2/test/sensor_simulator/ekf_wrapper.h
src/modules/ekf2/test/test_EKF_mag.cpp

requires (implemented on top of) #21305 
A mag sample can be incorrect but have the expected strength but it's quite unlikely to have the correct inclination too.
Adding a check for the inclination makes a bad sample less likely to be accepted.
Additionally:
- refactor the mag strength check
- add an option to force the ekf to wait for the World Magnetic Model before accepting mag samples (this makes sure we have the correct strength and inclination references)
- parameterize the strength and inclination tolerances
- log the expected and measured mag strength and references
```
Add mag inclination check
New parameter: `EKF2_MAG_CHK_STR`, `EKF2_MAG_CHK_INC`. Modified `EKF2_MAG_CHECK` (was boolean, now bitmask)
Documentation: Need to add doc to mention those options
```
- …

Add mag inclination check

---

src/modules/navigator/geofence_params.c

As discussed in https://discuss.px4.io/t/px4-maintainers-call-may-30-2023/32372#v114-new-beta-release-5, Geofence predictor feature was not well tested / maintained, hence was agreed upon to be disabled for the 1.14 release. And this was merged with the PR: https://github.com/PX4/PX4-Autopilot/pull/21657
Although we didn't discuss how to proceed with this feature in `main`, since it isn't actively maintained, I think it makes sense to backport this back to `main`.

Geofence: Disable pre-emptive geofence predictor by default

---

src/modules/ekf2/EKF/ekf_helper.cpp
src/modules/ekf2/EKF/ev_control.cpp

- set vision attitude error filter uninitalized if vision data stops

ekf2: apply yaw reset to vision attitude error filter

---

src/modules/ekf2/EKF/ekf.h
src/modules/ekf2/EKF/ev_yaw_control.cpp
src/modules/ekf2/EKF/mag_control.cpp
src/modules/ekf2/EKF/mag_fusion.cpp
src/modules/ekf2/EKF/zero_innovation_heading_update.cpp

- make it safe to call for other aid sources, no EKF state is changed unless fusion_enabled

ekf2: simplify fuseYaw() signature and use consistently

---

src/modules/ekf2/EKF/ekf.h
src/modules/ekf2/EKF/ekf_helper.cpp
src/modules/ekf2/EKF/gps_control.cpp
src/modules/ekf2/test/test_EKF_yaw_estimator.cpp

- yaw estimator yaw reset only flags mag_fault if the result of yaw failure
This can be useful if using a full EV + GNSS setup and you start indoors, then fly outside. Once GPS is good and the only missing requirement is yaw alignment the yaw estimator reset is performed and EV yaw will automatically stop itself.
Current `main` can already do this if mag is fully disabled (EKF2_MAG_TYPE none), but the logic is a bit questionable because it will reset velocity and position to GPS without actually starting GPS (control_status.flags.gps) and the logic isn't exactly the same for starting GPS on the next update.
https://github.com/PX4/PX4-Autopilot/blob/fd33e60f788695702d252bd4f8c15b8920bb3c1f/src/modules/ekf2/EKF/gps_control.cpp#L232-L247

ekf2: allow yaw estimator to perform yaw alignment

---

src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.cpp
src/modules/ekf2/ekf2_params.c

It's hard to tune the mag strength and inclination thresholds if the user can't see the current and reference values.
Add the measured and expected mag strength and inclination + tolerance parameters

Mag check: report strength and inclination values in case of preflight failure

---

src/modules/uxrce_dds_client/module.yaml
src/modules/uxrce_dds_client/uxrce_dds_client.cpp
src/modules/uxrce_dds_client/uxrce_dds_client.h

micro XRCE-DDS synchronizes the messages timestamp based on the Agent _wall clock_ and the client clock. This is the desired behavior in real applications, but it falls short in simulation.
During Gazebo (Garden) simulations, PX4 gets it time from the Gazebo `/clock` topic which:
- start from zero when the simulation starts.
- Can be faster or slower than the OS wall clock.
It makes sense for a ROS developer to use the same clock source for its nodes. In this scenario the time synchronization is managed by Gazebo itself.
However, by doing so, the micro XRCE-DDS bridge will apply the wrong time offset as it always assumes that the Agent side is using the _wall clock_.
With client side and agent side (the ROS applications) synchronized by Gazebo, there is no need to use the micro XRCE-DDS …

[uxrce-dds-client]: add parameter to disable time synchronization between Agent and Client.

---

src/modules/simulation/sensor_gps_sim/SensorGpsSim.cpp

- for a multicopter EKF2 default required GPS speed accuracy is 0.5 m/s

simulation/sensor_gps_sim: lower GPS velocity variance

---

src/modules/mavlink/mavlink_mission.cpp
src/modules/navigator/mission.cpp

I found two issues with mission uploading in the newest main. 
1. Mission module per default assumed the mission was not valid when the mission uorb topic changed. Only when the mission counter is updated, it actually checks the validity of the mission. But since the mission topic gets updated as well when the geofence or safepoints changed, this would lead to wrongly failed missions in the mission module where the mission would be reset.
2. The mission counter in mavlink_mission module was always set to 0 on startup. When on the last powercycle, exactly one mission was loaded, the mission counter in the dataman was set to one. On the next powerccle and the first mission upload, the mavlink_mission would report again a mission counter of 1. This would lead in the mission module to …

Fix mission failed bug

---

msg/FailsafeFlags.msg
src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.cpp
src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.hpp

Some system are able to dead-reckon for a while after losing GPS or other sources providing positional feedback. If the estimated position error grows above the failsafe threshold, the system enters a failsafe mode. As the position error estimate is growing linearly over time, and it is recommended to take action before entering the failsafe, we here warn the user about the imminent failsafe and propose to take manual control.
Warn the user when the position error estimate (eph) is either 90% of threshold (COM_POS_FS_EPH) or less than 10m below it (which ever is reached later). 
```
Feature: warn user when navigation failure is imminent 
```
As this is a purely a notification thing, it could also happen exclusively on the ground station. The envisioned mechanism would …

Commander: add warning for imminent navigation failure

---

boards/ark/can-rtk-gps/init/rc.board_sensors

This PR adds support for running the barometer on the ARK RTK GPS on bus 1 instead of 2.

ARK RTK GPS support baro on I2C bus 1 instead of 2

---

src/drivers/pca9685_pwm_out/main.cpp
src/drivers/pca9685_pwm_out/module.yaml

Fixes https://github.com/PX4/PX4-Autopilot/issues/21929 for `beta` branch.
Fixes #21929
Add parameter `PCA9685_RATE` again to set `_targetFreq`.
```
Feature/Bugfix add parameter PCA9685_RATE as a replacement for removed PWM_MAIN_RATE again
New parameter: PCA9685_RATE
```
Tested with PCA9685 breakout board.

add pca9685 parameter again

---

Tools/msg/templates/uorb/msg.cpp.em
Tools/msg/templates/uorb/uORBTopics.cpp.em
Tools/msg/templates/uorb/uORBTopics.hpp.em
platforms/common/uORB/uORB.h
platforms/common/uORB/uORBDeviceMaster.cpp
platforms/common/uORB/uORBDeviceMaster.hpp
src/modules/logger/logged_topics.h
src/modules/logger/logger.h
src/modules/uxrce_dds_client/dds_topics.h.em
src/modules/uxrce_dds_client/utilities.hpp

Replaces https://github.com/PX4/PX4-Autopilot/pull/20637
@hskrieg thanks for your efforts, I'm continuing your PR here. I had to adjust the DDS code a bit (see 2. commit).
I also dropped some of the logger changes as they're not necessary.
Resource usage stays the same (flash, RAM and CPU load).

uorb: allow for more than 255 uORB messages

---

src/modules/navigator/mission.cpp
src/modules/navigator/mission.h
src/modules/navigator/navigator.h
src/modules/navigator/navigator_main.cpp

Based on https://github.com/PX4/PX4-Autopilot/pull/21710
On resuming a mission, the flight speed was reset to the vehicle default. Especially for surveys this is not acceptable. 
Further extend the ideas from https://github.com/PX4/PX4-Autopilot/pull/21710: some mission items contain not momentary setpoints (like go to point A), but instead contain settings that are then relevant for the whole mission (or until over-turned by a negating command). 
DO_CHANGE_SPEED items belong to the same category as eg camera settings: you want to re-apply them when resuming a mission. 
I've further removed the separated mc/fw stored flight speeds, as it's only ever needed to store the speed of the current mode we're in, and we reset it during VTOL transitions. 
```
Feature: Resume mission with flight …
```

Navigator: Resume mission with last flight speed

---

src/lib/sensor_calibration/Utilities.cpp

This is a minor issue found in static code analysis:
Fix a memory overflow in case SENS_BOARD_ROT is set to Rotation::ROTATION_MAX (41) which is not a valid value

Fix maximum rotation value in GetBoardRotation()

---

src/include/containers/BlockingQueue.hpp

sem_wait() can be interrupted if the process receives a signal, however the queue implementation assumes the caller blocks on the barrier until something is posted in the queue, which means the call to px4_sem_wait() should loop until the return value is OK (not -EINTR).
Work queue manager is affected, when this happens multiple instances of the same work queue are started.
Fix the simple bug
Verify the issue does not happen any more

blockingqueue.hpp: Fix sem_wait not blocking if task is signaled

---

boards/px4/raspberrypi/cmake/upload.cmake

Backport of https://github.com/PX4/PX4-Autopilot/pull/21940/commits/a527a94f7c86b335987bff20dc2d6765b57c27a5 to 1.14.

skip SSH key check for simpler builds in the Docker container

---

src/drivers/heater/heater.cpp
src/drivers/telemetry/hott/messages.cpp
src/modules/navigator/GeofenceBreachAvoidance/geofence_breach_avoidance.cpp

Resolves https://github.com/PX4/PX4-Autopilot/issues/21924
Solves incorrect usage of abs. See https://github.com/PX4/PX4-Autopilot/issues/21924 for details
```
Documentation: Solves incorrect usage of abs
```
N/A
- Unit/integration test: All tests still pass
- Simulation/hardware testing logs: None
I realized that using abs() on float values casts them to int, which caused problems in some code I was working on. While searching through the code I realized that there were 3 places abs is currently being used on float values which can cause problems/inaccuracies.  I don't have a setup to test these changes, so I have not tested it beyond verifying that no tests fail.

multiple: Fix abs(int) usage on float values

---

.gitmodules

This is the same jump off point as main and release/1.14 with several NXP arch backports, 2 Commits fixing bad DEBUGASSERT
logic and a  Socket CAN change.
DEBUGASSERT
23b72dffe [BACKPORT] sched/semaphore: Remove restriction to use nxsem_trywait from ISR
00a68b7668 [BACKPORT] fs/cromfs: Fix faulty DEBUGASSERT() check
Arch changes:
fd47cd20a2 [BACKPORT] imxrt:Serial Preserve all but W1C bit in SR
c55f0fd3ac [BACKPORT] imxrt: lpspi dma invalidate cache after exchange
198c7caecb [BACKPORT] imxrt:lpi2c fix status handeling & race
cbd2e44c10 [BACKPORT] s32k3xx: lpspi dma invalidate cache after exchange
e71618d60e [BACKPORT] s32k3xx:lpi2c fix status handeling & race
6f59cc3659 [BACKPORT] s32k1xx:lpi2c fix status handeling & race
1e316d7e32 [BACKPORT] imxrt: flexcan use hpwork for receiving …

NuttX with NXP Backports & DEBUGASSERT & Soket CAN fix

---

src/modules/mavlink/mavlink_receiver.cpp

In the mavlink_receiver code, after a while it will try to resend some parameter update through the MAVLink instance. But for Iridium links those are not a good idea. So this adds a condition that prevent the sending if the MAVLink instance is in Iridium mode.
Related to issue #21496
I found that adding a condition for the MAVLink mode of the instance the MAVLink receiver is in prevent the sending of PARAM_VALUE message on the interface.
Fixes #21496 [Sporadic PARAM_VALUE message being sent through an Iridium interface
](https://github.com/PX4/PX4-Autopilot/issues/21496)
- Add simply to add an if condition around the `_parameters_manager.send();` function in the `mavlink_receiver.cpp` file. 
- Tested it only manually on my setup, and I wasn't able to reproduce the bug with this fix.
Most …

Add condition for Iridium mode to not send params change after a timeout

---

src/modules/fw_autotune_attitude_control/fw_autotune_attitude_control.cpp
src/modules/fw_autotune_attitude_control/fw_autotune_attitude_control.hpp

see https://github.com/PX4/PX4-Autopilot/issues/21358#issuecomment-1683620913
- limit maximum test signal based on max rate parameter
- scale down rule generating the P attitude gain and constrain it to the parameter's limits
```
FW autotune: reduce generated attitude gain
```

FW autotune small adjustments

---

Tools/auterion/remote_update_fmu.sh
Tools/auterion/upload_skynode.sh
boards/px4/fmu-v5x/cmake/upload.cmake
boards/px4/fmu-v6x/cmake/upload.cmake

When building firmware for Auterion Skynode with `make px4_fmu-v5x` there is no upload script to directly flash it but the user has to manually flash the binary.
- Add scripts to simplify flashing Skynode over either USB or Wifi.
```
Tools: Skynode flash scripts
Documentation: Still needs to be added to the documentation
```
Instead of `make px4_fmu-v5x upload_usb` it could be either a more specific upload target `make px4_fmu-v5x upload_skynode_usb` or a completely different build target `make auterion_skynode upload`. I'd need to check how the latter can be achieved without duplicating anything from the v5x target.
- I did not test this pr but am using the same exact rebased scripts a lot. I can quickly double-check.
See example output in …

Auterion Skynode upload scripts

---

src/modules/commander/commander_params.c

Found thanks to @sfuhrer 's question:
> In the param description is says "During that time the user cannot take over control." I guess that refers to "not able to manually override using the sticks"? But taking over control by switching the flight mode is completely fine, right? Can we adapt the param description if that's the case?
Be more clear that the override by stick is not possible during the failsafe action delay. The mode RC switch and mode siwtch commands allow any other kind of takeover.
```
Documentation: Clarify COM_FAIL_ACT_T description
```

commander_params: more precise COM_FAIL_ACT_T description

---

src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTiltrotorVTOL.cpp
src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTiltrotorVTOL.hpp
src/modules/vtol_att_control/tiltrotor.cpp
src/modules/vtol_att_control/tiltrotor.h
src/modules/vtol_att_control/tiltrotor_params.c

This removes the [functionality around specifying a spin up tilt thorough the param VT_TILT_SPINUP in the VTOL module ](https://github.com/PX4/PX4-Autopilot/pull/14330), and instead adds the functionality in slightly altered fashion in the control allocation for tiltrotor VTOLs. How it works now:
- set the tilt outputs to NAN if in hover mode and disarmed
- NAN in the outputs corresponds by definition to "set this actuator to the disarmed state"
- allow the tilts to go to normal operation once spool up is completed (tunable through COM_SPOOLUP_TIME)
```
Feature: VTOL tiltrotor: remove VT_TILT_SPINUP and instead have tilts at the disarmed value during the spoolup (COM_SPOOLUP_TIME)
```
It would be nice if the specified slew rate limiting on the tilts is also active …

Tiltrotor: move spin up tilt to control allocation

---

src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessMCTilt.cpp
src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessMCTilt.hpp
src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTiltrotorVTOL.cpp
src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTilts.hpp

VTOL Tiltrotors require a special yaw saturation detection. Simply looking at whether there is unallocated yaw torque leads to almost constant saturation reporting, as often one of the tilts is saturated (they usually can't tilt backwards). I patched this previously in https://github.com/PX4/PX4-Autopilot/pull/20518, where I simply declared the yaw saturated if the torque setpoint was saturated. Given that there is also a  collective tilt this assumption is quite rough. 
While flying a tricopter with sideways tiltable tail I further noticed that there the reported unallocated yaw was never 0, while the tilt servo clearly never reached saturation:
I didn't investigate further why the unallocated torque calculation is so wrong, but given that MC tilt vehicles would anyway have the same …

Control Allocation: fixes in yaw saturation detection for vehicles with tilt-for-yaw

---

src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessTiltrotorVTOL.cpp

Two related issues and fixes:
- During transition to FW, only allow update thrust axis up to 45° as with a high tilt angle the effectiveness of the thrust axis in z is approaching 0, and by that is increasing the motor output to max. As the vehicle picks up airspeed during the transition and with that the wings start to generate lift, it is not required to produce the same about of vertical thrust as in pure hover.
- Transition to HF: disable thrust axis tilting, and assume motors are vertical. This is to avoid a thrust spike when the transition is initiated (as then the tilt is fully forward). 
Before this PR (notice the thrust spikes when the vehicle is still in transition phases with the collective tilt being almost at horizontal):
After this PR (note how the thrust spikes during front …

TiltrotorEffectiveness: limit thrust axis tilt to z effectiveness scaling

---

src/modules/ekf2/EKF/ekf_helper.cpp
src/modules/ekf2/EKF/estimator_interface.h
src/modules/ekf2/EKF/gps_checks.cpp
src/modules/ekf2/test/test_EKF_basics.cpp
src/modules/ekf2/test/test_EKF_fusionLogic.cpp

Fixes https://github.com/PX4/PX4-Autopilot/issues/17249
Even if the aiding is local only, a valid global estimate can be sent as long as we know the EKF's origin.
```
Allow auto modes with local position estimate if global origin is set manually
Documentation: see https://github.com/PX4/PX4-user_guide/pull/2689
```
- unit tests

Allow auto modes with local position estimate if global origin is set manually

---

src/drivers/drv_hrt.h

Fixes the clang error:
```
/__w/PX4-Autopilot/PX4-Autopilot/src/drivers/drv_hrt.h:297:35: fatal error: identifier '_s' preceded by whitespace in a literal operator declaration is deprecated [-Wdeprecated-literal-operator]
297 | constexpr hrt_abstime operator "" _s(unsigned long long seconds)
```
Let's see if CI passes.

drv_hrt: remove whitespace for operator ""

---

boards/ark/can-flow/src/boot_config.h
boards/ark/can-flow/uavcan_board_identity
boards/ark/can-gps/src/boot_config.h
boards/ark/can-gps/uavcan_board_identity
boards/ark/can-rtk-gps/src/boot_config.h
boards/ark/can-rtk-gps/uavcan_board_identity
boards/ark/cannode/src/boot_config.h
boards/ark/cannode/uavcan_board_identity
boards/cuav/can-gps-v1/uavcan_board_identity
boards/freefly/can-rtk-gps/uavcan_board_identity
boards/holybro/can-gps-v1/uavcan_board_identity
boards/matek/gnss-m9n-f4/uavcan_board_identity
boards/nxp/ucans32k146/uavcan_board_identity
boards/px4/fmu-v4/uavcan_board_identity
src/drivers/uavcannode/UavcanNode.cpp
src/drivers/uavcannode/UavcanNode.hpp
src/drivers/uavcannode/uavcannode_params.c

This PR adds the ability for cannodes to get a node ID after booting if they did not receive on in the bootloader. CANNODE_NODE_ID is removed since it was never used and complicates the entire node ID logic.

Cannode boot immediatly and get node ID later

---

src/lib/mixer_module/functions/FunctionMotors.hpp
src/modules/mc_pos_control/PositionControl/PositionControl.cpp

1. When checking the multicopter position controller I found that https://github.com/PX4/PX4-Autopilot/pull/16030/files#diff-4a755e9af489c034497b67e34c4217b79dbd151a029f622e8cb3fe645efdc87fR168 used integer literals that get implicitly casted to float.
2. When including `FunctionMotors.hpp` I realized I had to include `actuator_motors.h` just before for it to compile. That brought me to assume it's a copy-paste error from https://github.com/PX4/PX4-Autopilot/commit/9ed861e0a3060de84df3eb46759c86eac6a64e45#diff-907d7c7904906f82013983fc380e1918a46bb1f1b381b3f0d57ae3c941e3eb3cR38
1. I made it explicit.
2. include the motors header instead of the servos one
Small code cleanup nothing user-facing
- Still compiles

Cleanup: include problem, float literals

---

src/modules/control_allocator/module.yaml

I'm assuming that the rotor positions are given relative to the center of gravity (CG).
Is that correct?

control_allocator: Clarify position description

---

boards/cubepilot/cubeorangeplus/init/rc.board_sensors

This adds support for the 4. hardware variant of the CubeOrange+ featuring 3 ICM45686.
Please check @bugobliterator

cubepilot: Add support for 4. variant of Orange+

---

src/drivers/adc/ads1115/ADS1115.h

We have a design with several ads1115 sensors on the i2c bus; this changes the publishing of the data to separate adc_report instances.

Ads1115 multi support

---

boards/ark/cannode/src/boot_config.h

On the ARK CANnode, switching to OPT_WAIT_FOR_GETNODEINFO_JUMPER_GPIO_INVERT caused the OPT_WAIT_FOR_GETNODEINFO_JUMPER_GPIO logic in the bootloader to not work.

ARK CANnode disable OPT_WAIT_FOR_GETNODEINFO_JUMPER_GPIO

---

src/lib/systemlib/system_params.c

When helping @marcinolokk I found that the description of the parameter for the distance sensor preflight check is not entirely clear to either me or him so I went ahead to suggest an improvement.
- Different wording, please check if it makes sense
- I checked in simulation and no reboot is required, it applies immediately.
```
Documentation: Improve parameter description for distance sensor preflight check
```

system_params: improve distance sensor check description

---

platforms/common/uORB/uORBDeviceNode.cpp

When running out-of-memory, the malloc returns NULL and the memset then tries to write to address 0 which results in a hardfault.
I mean… just™ don't write to address 0.
```
Bugfix: Fix hardfault in uORB DeviceNode::write when OOM
```
We could also… not use dynamic memory. LOL.
Forced by automatic GDB scripting.
A [longer analysis of additional hardfault sources in OOM conditions is available here](https://gist.github.com/niklaut/a438bf711d5890099c2d3457b48707a0).
(There'll be more fixes coming).

Fix hardfault in uORB calloc implementation

---

src/lib/npfg/npfg.cpp
src/lib/tecs/TECS.cpp
src/modules/fw_pos_control/FixedwingPositionControl.cpp
src/modules/fw_pos_control/FixedwingPositionControl.hpp

https://github.com/PX4/PX4-Autopilot/issues/21358#issuecomment-1683501042 (from #21358) reported turn around behavior after passing the land point during a fixed-wing autolanding. Sure enough - the vehicle was indeed hard turning just past the land point. this is dangerous behavior, and should not happen.
Turns out to be a regression made after merging #21635. The intent of #21635 was to safe guard waypoint navigation logic from vehicle runaways once past the target waypoint (caused in rare cases by race conditions with the Navigator module). The solution was to add logic to turn back to the target waypoint once past, with the nominal behavior being that this condition is never entered due to acceptance radius based switching logic triggering in the Navigator before the condition was ever …

FixedwingPositionControl: refine / refactor waypoint navigation methods

---

src/modules/dataman/dataman.cpp

On NuttX if the SD card was just cleared (quick format) it's possible for the newly created dataman file to still have the same compatibility key. If the file was created we should always init.

dataman: explicitly check file existance to init

---

integrationtests/python_src/px4_it/mavros/mission_test.py

integrationtests: MAVROS mission_test.py relax yaw estimator mean check for now
- ekf2 heading first initializes to 0 degrees, then immediately resets to mag heading once a few samples are accumulated
- the yaw error mean check should be adjusted to exclude this brief (<1s) initial period

MAVROS mission test temporarily relax estimator yaw mean error check

---

src/drivers/uavcan/uavcan_drivers/stm32h7/driver/src/uc_stm32h7_can.cpp

While testing the reception of the feedback from KDECAN ESCs in the following public branch (https://github.com/duartecdias/PX4-Autopilot/tree/pr/uavcan/kdecanProtocol), it was noted that while using standard ids, some messages were not being received from the ESCs in a random fashion for different power cycles.
Problem was tracked down to the initialization of the filters (probably they are being initialized randomly at each power cycle). After proper memset of the respective filter areas the problem went away.
Also adjusted the number of maximum filters for extended IDs to 64, according to the h7 chip datasheet.

stm32h7_can: fix filter memory initialization bug.

---

boards/px4/fmu-v6x/init/rc.board_sensors

From looking at the history the BMM150 rotation was initially 0. Then, this was changed to 6 when the intent was to only change it for Skynode.
A bit later, the rotation was changed back to 0, but only for Skynode.
This tells me that rotation 0 was correct for all 6X including Skynode all along.
Tested on my Holybro 6X and 6X mini.
Fixes #22004.
Needs backporting to v1.14.
FYI @baumanta and @marcoraeth.

6x: fix internal mag rotation

---

src/modules/ekf2/test/sensor_simulator/convertULogToSensorData.py
src/modules/logger/logged_topics.cpp

Optical flow data isn't logged at full rate when ekf replay logging is selected
optical_flow got replaced by sensor_optical_flow and vehicle_optical_flow in https://github.com/PX4/PX4-Autopilot/pull/19714 but we forgot to also rename it in two places
```
Fix vehicle_optical_flow logging for EKF2 replay
```
bench tested

Fix opt flow logging for EKF2 replay

---

src/lib/npfg/npfg.cpp
src/lib/tecs/TECS.cpp
src/modules/fw_pos_control/FixedwingPositionControl.cpp
src/modules/fw_pos_control/FixedwingPositionControl.hpp

Backport #21988
```
Bugfix FixedwingPositionControl: Fixes landing regression where the vehicle could turn back towards the landing point after passing it.
Documentation: Should update docs.px4.io/ with waypoint logic description and perhaps the figure included above.
```

[BACKPORT] FixedwingPositionControl: refine / refactor waypoint navigation methods

---

ROMFS/px4fmu_common/init.d-posix/airframes/1032_gazebo-classic_plane_catapult
src/modules/fw_pos_control/FixedwingPositionControl.cpp
src/modules/fw_pos_control/FixedwingPositionControl.hpp

Airspeed setpoint at beginning of FW takeoff is set to AIRSPD_TRIM, and then slowly ramped down to TKO_AIRSPD. 
Fixes https://github.com/PX4/PX4-Autopilot/issues/21567 (beside other PRs)
Add argument in_takeoff_situation to adapt_airspeed_setpoint(), and do not run airspeed setpoint slew rate limiting then. Also disable some other logic, and only keep the load factor to airspeed setpoint logic while in takeoff.
SITL tested.
Prior this PR:
After this PR:
Now the airspeed setpoint is at the set 12m/s when the takeoff starts, and not at the TRIM airspeed (15).

FW Pos Control: add in_takeoff_situation argument to adapt_airspeed_setpoint()

---

src/drivers/camera_capture/camera_capture.cpp

When receiving a camera trigger in hardware after calling `camera_capture stop`, the FMU hardfaults.
```
Program received signal SIGTRAP, Trace/breakpoint trap.
exception_common () at platforms/nuttx/NuttX/nuttx/arch/arm/src/armv7-m/gnu/arm_exception.S:144
144		mrs		r0, ipsr				/* R0=exception number */
=> 0x08008244 <exception_common+0>:	ef f3 05 80	mrs	r0, IPSR
(gdb) backtrace
#0  exception_common () at platforms/nuttx/NuttX/nuttx/arch/arm/src/armv7-m/gnu/arm_exception.S:144
#1  <signal handler called>
#2  0x0802783c in CameraCapture::capture_callback (this=0x0, chan_index=6, edge_time=176203508, edge_state=0, overflow=0) at src/drivers/camera_capture/camera_capture.cpp:110
#3  0x0815459a in io_timer_handler (timer_index=<optimized out>) at …
```

Disable timer callback in CameraCapture::stop()

---

src/modules/commander/failsafe/failsafe.cpp

When flying with a low battery, the remaining rtl flight time estimate can be triggered, performing an RTL. But while performing an RTL and getting closer to the landing position, it can happen the the "battery_low_remaining_time" flag is toggled, because the estimate is lower when approaching the land position. Thus it can happen, that the failsafe is completed and retriggered several times.
- Only allow to clear the Low battery based on remaining flight time failsafe, when the user changes the mode or the vehicle is disarmed.
```
Bugfix: Only allow to clear the Low battery based on remaining flight time failsafe, when the user changes the mode or the vehicle is disarmed.
```
- Tested using the failsafe web simulation while toggling the "Low battery based on remaining …

failsafe: rtl_time_estimate failsafe disable only on mode change/disarm

---

ROMFS/px4fmu_common/init.d-posix/airframes/1032_gazebo-classic_plane_catapult
src/modules/fw_pos_control/FixedwingPositionControl.cpp
src/modules/fw_pos_control/FixedwingPositionControl.hpp

Backport of https://github.com/PX4/PX4-Autopilot/pull/21581
```
Bugfix: initialize fixed-wing takeoff airspeed at correct value, disable airspeed increments except load factor during takeoff
```

[BACKPORT] FW Pos Control: add in_takeoff_situation argument to adapt_airspeed_setpoint()

---

ROMFS/px4fmu_common/init.d/rc.fw_defaults

- for FW the primary range finder usage is estimating the distance to the ground (terrain estimate) to guide the landing approach and initiate flare
- increase EKF2_RNG_QLTY_T default 1->3 seconds
FYI @ryanjAA 
I wouldn't necessarily claim this is a fix, but is there any real current usage where being more conservative with range finder validity (requiring 3 seconds of consistently good data) would be problematic?

ROMFS: rc.fw_defaults set more conservative range finder requirements

---

src/modules/commander/Commander.cpp
src/modules/navigator/loiter.cpp

1. Geofence reposition lifetime: when in RTL, the geofence reposition setpoint is ignored (ok, fine) - however, the reposition struct that holds that geofence position is stored until the next flight. If a manual control loss then engages a hold (during RTL delay time), the reposition setpoint is taken for the hold, which may be anywhere else other than the vehicle's current position.. which would be the desired hold position.
2. External reposition commands without a requested mode switch (flag) are silently accepted and can cause unexpected positioning when hold is engaged.
1. In the loiter activation methods, check the reposition setpoint's timestamp in addition to validity.
3. Don't allow reposition commands without a requested mode switch.
```
Bugfix: Don't allow …
```

Avoid unexpected repositions

---

src/modules/fw_pos_control/FixedwingPositionControl.cpp

The airspeed slew rate controller in the fixed wing position controller is only explicitly intialized in takeoff modes - but otherwise defaults to zero.. which then gets bounded to min airspeed on first pass to the airspeed handling logic.. which then requires a slewed ramp in of whatever actual setpoint the mode demands. Undesireable.
Initialize the slew rate to trim airspeed in the constructor. This way no matter what mode enters the slewing logic first.. the starting point is a reasonable one. And takeoff modes still initialize to takeoff speed explicitly.
Additionally move the slew constraint checks to end of adapt airspeed method to make sure setpoint and constraints are decoupled.
```
Bugfix: initialize airspeed setpoint by default at at …
```

FixedwingPositionControl: initialize airspeed slew controller in constructor

---

ROMFS/px4fmu_common/init.d/airframes/4900_crazyflie
ROMFS/px4fmu_common/init.d/airframes/4901_crazyflie21

When browsing through the maximum thrust settings of different airframes I found that the Crazyflies config sets the default to the same value as the default which is 100% thrust.
Since https://github.com/PX4/PX4-Autopilot/pull/9359 the default is 100% thrust and when the parameter for the Crazyflie was commited that was already there: https://github.com/PX4/PX4-Autopilot/commit/28f616b1c170dd3f416ddd60c3ca2947208b357d#diff-0c848f9e92ff14731d314da17e247ea2312673f6c8018c94c9a22153419e79d9R41
Don't set the global default as airframe default with no apparent reason.
```
Cleanup: Crazyflie airframe sets global default again
```
I'm certain the value stays the same.

Craziflie configs: remove default 100% thrust parameter

---

src/modules/replay/Replay.cpp
src/modules/replay/Replay.hpp

It is possible to override parameters when replaying a log, but these are then fixed for the entire replay.
This means the replay can't be used to assess the effects of parameter changes.
Allow scheduling changes to "dynamic parameters" at specific flight times during the replay in `replay_params_dynamic.txt`.
- All parameters are initialised as before - either from `replay_params.txt` or the values in the log.
- At each time step:
- Check for scheduled changes that should have occurred since the last step and apply them.
- If a dynamic parameter was changed _in the log_, do not apply the change.
`replay_params_dynamic.txt` should be created in the same location as `replay_params.txt`. That is, in `build/px4_[target]_replay/rootfs/`. See …

Allow changing parameters during replay

---

src/modules/landing_target_estimator/landing_target_estimator_params.c

`target` -> `Target`. Useful to users of machine-readable documentation.
When using the automatically generated documentation (in JSON format) in my application, I found two "Landing Target Estimator" param groups, with difference in "target" casing.
- Change `target` to `Target` for consistency reasons.
Handling this on documentation user side is of course an option.
N/A
N/A

Landing Target Estimator: fix param group casing consistency

---

ROMFS/px4fmu_common/init.d-posix/airframes/1010_gazebo-classic_iris_opt_flow
src/modules/navigator/land.cpp
src/modules/navigator/loiter.cpp
src/modules/navigator/mission.cpp
src/modules/navigator/mission.h
src/modules/navigator/mission_params.c
src/modules/navigator/navigator.h
src/modules/navigator/navigator_main.cpp
src/modules/navigator/rtl.cpp
src/modules/navigator/takeoff.cpp

Only base decision on whether a takeoff is required prior to starting a mission on landed state and altitude below min altitude/mission altitude.
`get_can_loiter_at_sp()` was only needed for setting `_need_takeoff` (the comment says "require takeoff after non-loiter or landing"). The landing part is covered in `Mission::do_need_vertical_takeoff()` already, and I don't get how this should be linked to whether the type is loiter or not.
I originally wanted to work on syncing the behavior of what the vehicles do when starting a mission with the current WP being a takeoff while already in-air, but then instead only ended up doing this mini clean up. If somebody has an idea how to cleanly not look at Takeoff WP once already in flight let me know, but it's not necessarily linked to the changes …

Navigator: remove _can_loiter_at_sp and _need_takeoff

---

src/modules/navigator/vtol_takeoff.cpp

When the vehicle home position does not coincide with the takeoff position the vehicle drifts off towards the home position during takeoff which is not the expected behavior.
- Use global position for takeoff instead of home position.
```
Bugfix: 
Prevent VTOL Takeoff from drifting during takeoff ascent when home position does not coincide with takeoff position.
```

VTOL Takeoff: Use global position instead of home for takoeff

---

src/modules/fw_pos_control/FixedwingPositionControl.cpp

backport of https://github.com/PX4/PX4-Autopilot/pull/22077
```
Bugfix: initialize airspeed setpoint by default at at trim speed
```

[BACKPORT] FixedwingPositionControl: initialize the airspeed slew rate controller with trim airspeed in the constructor

---

src/modules/commander/Commander.cpp
src/modules/navigator/loiter.cpp

backport of https://github.com/PX4/PX4-Autopilot/pull/22078
```
Bugfix: Don't allow external reposition commands without a mode switch, and ensure old reposition commands are not erroneously set.
```

[BACKPORT] Avoid unexpected repositions

---

src/modules/fw_pos_control/FixedwingPositionControl.cpp
src/modules/fw_pos_control/FixedwingPositionControl.hpp

Fixes this comment: https://github.com/PX4/PX4-Autopilot/issues/21358#issuecomment-1725804676
I've also added patches for lat/lon, even though there no issue was reported so far (only affects offboard mode).
Same approach as in [MC flight task auto](https://github.com/PX4/PX4-Autopilot/blob/dac337efc4c3cc532509617c72bb6ec9777052d8/src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp#L604-L610): set reference to 0 if not provided as a finite number in the local_position. 
```
Bugfix: FW Position Controller: only use reference from local_position if valid, otherwise assume (0,0,0)
```
Needs to be ported to 1.14.

FW Positon Controller: set references to 0 if not provided by local_position

---

src/modules/mc_rate_control/mc_acro_params.c
src/modules/mc_rate_control/mc_rate_control_params.c

When discussing with @sfuhrer I found that most people lower these parameters to tune their vehicles and some even put that in the airframe because forgetting to lower them can lead to accidental flipping the drone.
- Move acro mode parameters to separate file and parameter group
- Improve parameter description
- Lower the default rates to 100°/s and disable expo
This is useless for acro flying but good for rate control tuning and avoids the danger of a beginner or someone tuning who forgot to lower the parameters from flipping the drone immediately.
```
Much lower Multicopter Acro mode default rates
```
Documentation: Need to adjust [tuning guide](https://docs.px4.io/main/en/config_mc/pid_tuning_guide_multicopter.html#rate-pid-tuning) and  [Acro …

Beginner/control tuning friendly Acro mode defaults

---

src/modules/ekf2/EKF/airspeed_fusion.cpp
src/modules/ekf2/EKF/covariance.cpp
src/modules/ekf2/EKF/drag_fusion.cpp
src/modules/ekf2/EKF/ekf.h
src/modules/ekf2/EKF/ekf_helper.cpp
src/modules/ekf2/EKF/gps_yaw_fusion.cpp
src/modules/ekf2/EKF/gravity_fusion.cpp
src/modules/ekf2/EKF/mag_fusion.cpp
src/modules/ekf2/EKF/mag_heading_control.cpp
src/modules/ekf2/EKF/optflow_fusion.cpp
src/modules/ekf2/EKF/sideslip_fusion.cpp
src/modules/ekf2/EKF/vel_pos_fusion.cpp
src/modules/ekf2/EKF/yaw_fusion.cpp
src/modules/ekf2/EKF/zero_gyro_update.cpp
src/modules/ekf2/EKF/zero_innovation_heading_update.cpp

State vector type contains the number of elements in its name, this would cause to rename everything is its size changes.
rename
`Vector24f -> VectorState`
`SquareMatrix24f -> SquareMatrixState`
`SparseMatrix24f -> SparseMatrixState`
Additional changes: used auto-generated `State` constants instead of more hardcoded indexes
Note: missing is still the airspeed reset
unit tests

Ekf2: Vector24f -> VectorState

---

src/lib/slew_rate/SlewRate.hpp
src/modules/mc_att_control/mc_att_control.hpp
src/modules/mc_att_control/mc_att_control_main.cpp

1. We had a crash because:
- The spoolup time is a phase after arming where ESC/Motor checks are done e.g. is the rotor stuck?
- Commander / failure detector is allowed to disarm immediately again if such a check fails sich that the vehicle doesn't even take off
- Climb rate controlled modes don't allow the vehicle taking off in this phase
- Stabilized mode did not prohibit that
- If the spoolup time is long enough e.g. many seconds and the ESC reports a failure only after a certain time the vehicle can drop again
2. Certain very specific setups require the spoolup throttle to be zero (purely idle). This is the case in climb rate controlled modes thanks to https://github.com/PX4/PX4-Autopilot/blob/23b31cc5fdc33fe1f43dcf12bb6fe4a5afbbc24d/src/modules/mc_pos_control/MulticopterPositionContro …

Spoolup in Stabilized/Manual Mode

---

src/modules/fw_pos_control/FixedwingPositionControl.cpp

Fixes https://github.com/PX4/PX4-Autopilot/issues/22072
A setpoint of type IDLE can be published by Navigator without a valid position, and should be handled in the auto function in `FW_POSCTRL_MODE_AUTO`. If it wouldn't be handled there the controller would switch to mode `FW_POSCTRL_MODE_OTHER`, in which case no attitude setpoint is published and the lower controllers would be stuck with the last published value (incl. thrust).
```
Bugfix: FW Position Controller: handle IDLE waypoints in FW_POSCTRL_MODE_AUTO
```
- prevent arming in case of invalid mission
- also publish an attitude setpoint if in `FW_POSCTRL_MODE_OTHER`? With thrust set to 0 like when in `FW_POSCTRL_MODE_AUTO` and `SETPOINT_TYPE_IDLE`?
SITL tested.
This falls into the context of interfaces cleanup. …

FW Position Controller: handle IDLE waypoints in FW_POSCTRL_MODE_AUTO also with NAN setpoints

---

ROMFS/px4fmu_common/init.d/airframes/4019_x500_v2

Currently, in master & 1.14.0 RC1, the X500v2 Airframe defaults Main 1-2 output protocol to `Unknown: -4` 
It was found that this PR https://github.com/PX4/PX4-Autopilot/pull/21841 changed the default output protocol of X500v2 airframe from Aux to Main but forgot to remove the line that set it to DShot `param set-default PWM_AUX_TIM0`, DShot is not available in Main output (IO PWM) , only Aux (FMU PWM) does. 
Removing this line should make default output protocol back to `PWM 400 Hz`

Fix Default Output Protocol - Airframe 4019_x500_v2

---

src/modules/ekf2/EKF/covariance.cpp
src/modules/ekf2/EKF/ekf.h
src/modules/ekf2/EKF/ekf_helper.cpp
src/modules/ekf2/EKF/ev_pos_control.cpp
src/modules/ekf2/EKF/mag_3d_control.cpp
src/modules/ekf2/EKF/zero_velocity_update.cpp
src/modules/ekf2/EKF2.cpp
src/modules/ekf2/test/sensor_simulator/ekf_wrapper.cpp
src/modules/ekf2/test/sensor_simulator/ekf_wrapper.h
src/modules/ekf2/test/test_EKF_gps_yaw.cpp
src/modules/ekf2/test/test_EKF_initialization.cpp

Non-functional, reduces line length and probability of doing a mistake.
main:
```FLASH_AXIM:     2043457 B      2016 KB     98.99%```
pr:
```FLASH_AXIM:     2043345 B      2016 KB     98.98%```

EKF2: access state covariance using helper functions

---

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp

In my earlier testing of https://github.com/PX4/PX4-Autopilot/pull/21432 I didn't notice any hardfaults. I just did another build of units and started noticing random hardfaults on boot. I traced it back to the AFBR 1.4.4 library update. Sometimes on boot it uses more stack than is allocated in hp_default.
Before increasing the total stack allowed for the task. Non hardfault case.
``` 
0 Idle Task                   34313 48.250   260/  768   0 (  0)  READY  3
1 hpwork                        318  2.668  1324/ 2944 254 (254)  w:sem  3
2 lpwork                          0  0.000   284/ 1576  50 ( 50)  w:sem  3
3 nsh_main                        0  0.000  1548/ 2576 100 (100)  w:sem  3
4 wq:manager …
```

workqueue: increase hp_default stack

---

src/lib/battery/module.yaml

When switching back and forth between power modules on I2C1 and 2 resulting in using different driver instances that publish as batteries 1 or 2 I found that it's not possible with the current parameter metadata to restore the unknown cell count which the configuration starts with. I think we should not hide this since it can life in a corner case unnecessary complicated.
Add metadata for the default value such that it shows up in the drop down.
```
Bugfix: allow choosing unknown battery cell count from the dropdown
```
Tested in simulation to work as expected:

battery: show unknown cell count

---

src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessHelicopter.cpp

This became necessary otherwise
the allocation reports saturation all
the time and the rate integrator doesn't work.
When using a helicopter on the latest version I found that the integrator doesn't have any effect. The issue seems to be the same as was fixed for tiltrotors in https://github.com/PX4/PX4-Autopilot/pull/21994 I'm looking for the original change that made this necessary.
Handle the unsaturated case explicitly and report 0 unallocated torque in that case.
```
Bugfix: Helicopter saturation logic leads to rate control integrator not working
```
After this change it was working like expected again, tested on a real helicopter.
Before
After

Fix Helicopter saturation logic

---

src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessHelicopter.cpp
src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessHelicopterCoaxial.cpp
src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessHelicopterCoaxial.hpp
src/modules/control_allocator/ActuatorEffectiveness/CMakeLists.txt
src/modules/control_allocator/ControlAllocator.cpp
src/modules/control_allocator/ControlAllocator.hpp
src/modules/control_allocator/module.yaml

When working on a coaxial fixed collective pitch helicopter project I added back support in control allocation.
- Add control allocation airframe (`CA_AIRFRAME`) 12 for coaxial helicopters.
- Allow configuring 2 swash plate servos which is not enough for a normal helicopter with collective pitch but necessary to support the fixed collective pitch coaxial helicopters.
- Adjust a copy of the helicopter allocation for the coaxial use case. These are separate commits to simplify the review of the history.
- Refactor some spacing in the original helicopter allocation.
```
Feature: Add back support for coaxial helicopters with the new actuator allocation
Documentation: Need to add at least a paragraph to https://docs.px4.io/main/en/frames_helicopter/
``` …

Coaxial Helicopter Support

---

src/modules/ekf2/EKF/gps_checks.cpp

This should have been if any of the stored WMM fields are NAN to allow them to be set immediately. In typical usage this is redundant with the time check (_wmm_gps_time_last_set).

ekf2: fix WMM NAN checks

---

ROMFS/px4fmu_common/init.d-posix/airframes/1039_gazebo-classic_advanced_plane
src/modules/navigator/mission_base.cpp

Fixes issue raised [here](https://discord.com/channels/1022170275984457759/1022186266957201480/1156841185160204329) about weird FW takeoff path. 
Issue was introduced with https://github.com/PX4/PX4-Autopilot/pull/20908. There was a missing customization for FW, where we don't want to do the same as for MC/VTOLs in hover when starting a mission (go directly to first WP and not first climb to altitude).
I also removed some outdated config in the advanced_plane config. 
```
Bugfix: FW Mission start with Takeoff item: by-pass climbing-first logic and go straight to the Takeoff item.
```

mission_base: if FW and Takeoff do not enter climb before mission start

---

src/modules/ekf2/EKF/ekf.h
src/modules/ekf2/EKF/gps_yaw_fusion.cpp
src/modules/ekf2/EKF/mag_fusion.cpp
src/modules/ekf2/EKF/optflow_fusion.cpp

The sparse vector template requires to know which states are non-zero in the observation jacobian. This complicates the modularity of the code when the state vector or the derivation is changed. The risk of forgetting to update the list of non-zero states is also high and since it's only used for a couple of matrix-vector multiplications, the reduced CPU load is very minimal (on fmu-v5, removing the optimization on the mag 3D fusion doesn't show any change in CPU usage).
Use dense vectors. The computation cost difference is almost negligible for this size.
```
-
```
I tried to directly compute the Kalman gain in the SymForce derivation. This could make the code faster but increases flash space. Since we're short on flash space but not …

EKF2: remove sparse vector optimization

---

src/drivers/rc/crsf_rc/CrsfParser.cpp

The length check for unknown packets did not include PACKET_SIZE_TYPE_SIZE and CRC_SIZE, and hence working_index could overflow CRSF_MAX_PACKET_LEN, triggering invalid memory access further down in QueueBuffer_PeekBuffer.
Also the working_segment_size was wrong for unknown packets.
Credits for finding this go to @Pwn9uin.
I did not test this, as I currrently don't have hw.

fix crsf_rc: prevent potential buffer overflow for unknown packets

---

boards/px4/fmu-v5x/init/rc.board_defaults
boards/px4/fmu-v6x/init/rc.board_defaults
src/modules/uxrce_dds_client/module.yaml
src/modules/uxrce_dds_client/uxrce_dds_client.cpp

The `uxrce_dds_client` can be started with flags to enable using a custom participant (`-c`) or localhost-only on the agent side (`-l`), but these were only available when starting the client by hand in the console.
Remove the CLI flags and instead a parameter for selecting the participant configuration, `UXRCE_DDS_PTCFG`.
This allows for selecting either the custom participant or localhost-only configuration, or neither (the default).
- Improve other parameter descriptions for the `uxrce_dds_client`.
- Improve formatting of `uxrce_dds_client status`. For example:
```bash
INFO  [uxrce_dds_client] Running, connected
INFO  [uxrce_dds_client] Using transport:    udp
INFO  [uxrce_dds_client] Agent IP:           192.168.0.5
INFO  [uxrce_dds_client] Agent port:         8888
INFO …
```

uXRCE-DDS Client: Expose custom participant and localhost-only flags

---

msg/VehicleOpticalFlowVel.msg
src/drivers/uavcan/sensors/flow.cpp
src/modules/ekf2/EKF/ekf.h
src/modules/ekf2/EKF/optflow_fusion.cpp
src/modules/ekf2/EKF2.cpp
src/modules/sensors/vehicle_optical_flow/VehicleOpticalFlow.cpp

Position oscillations with ArkFlow
- fix sign in flow gyro bias estimation
- avoid possibility to remove gyro bias multiple times
- add Z gyro in flow gyro data to compensate for apparent flow while doing yaw rotations (when the sensor has an X or Y offset)
```
Improve estimation performance when using ArkFlow
```

Fix flow gyro bias corrections

---

src/lib/events/CMakeLists.txt

fix events: use px4_add_library instead of add_library

---

src/modules/simulation/gz_bridge/GZBridge.cpp

`gz_bridge` does not allow Gazebo to start and triggers the timeout.
Increased the timeout value to 10s.
None

[gz-bridge] fix GZ timeout for slow starting simulations

---

src/modules/commander/commander_params.c

The COM_RC_LOSS_T param reflects manual control loss, not just RC loss as implied by the docs and name. This updates the text.
It would be good to change the name of the parameter too but I suspect we don't have appetite for that - it is explicitly accessed in QGC for example.

Update commander_params.c - RC loss is manual control loss

---

src/modules/commander/HealthAndArmingChecks/checks/batteryCheck.cpp
src/modules/commander/HealthAndArmingChecks/checks/batteryCheck.hpp
src/modules/commander/commander_params.c

Currently the battery checks make sure that arming is not possible when the SOC is below the warning threshold (BAT_LOW_THR). BAT_LOW_THR is though in the first place thought to be the in-flight battery level warning. For systems that require a lot of energy during takeoff (eg VTOLs) it is beneficial to have a separate, higher threshold to prevent arming.
Add new battery threshold for arming (new parameter COM_ARM_BAT_MIN).
```
Feature: add additional battery level preflight check.
New parameter: COM_ARM_BAT_MIN
```

batteryCheck: add new battery threshold for arming (COM_ARM_BAT_MIN) 

---

src/drivers/distance_sensor/lightware_laser_serial/lightware_laser_serial.cpp

In the lightware_parser function, LW_PARSE_STATE2_GOT_DIGIT0 state can be repeated unexpectedly without proper parserbuf_index or state checking. This behavior will trigger a heap buffer overflow vulnerability by allowing to write some data. And the writable size is sizeof(unsigned).
We've discussed for this bug with @bkueng

fix lightware_laser_serial: prevent potential heap buffer overflow

---

src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/tiltrotor.cpp
src/modules/vtol_att_control/vtol_type.cpp
src/modules/vtol_att_control/vtol_type.h

Since the stall airspeed increases with vehicle weight, we want to make sure that the transition airspeed is at least as high as the minimum airspeed compensated for weight.

Limit transition airspeed using minimum airspeed compensated for weight

---

src/modules/mavlink/mavlink_main.cpp

After implementing the GPS Denied feature, GPS_RAW_INT can be used to display the vehicle position similar to GLOBAL_POSITION_INT. The position using the raw gps data is laggy in comparison to the global position.
Bump GPS_RAW_INT to same frequency as  GLOBAL_POSITION_INT.

Increase raw gps latency

---

src/modules/navigator/rtl.cpp
src/modules/navigator/rtl.h

When ... I found that ...
- Add ... for ...
- Refactor ...
```
```

Make some functions const

---

src/modules/mavlink/mavlink_main.cpp

This prevents a deadlock when calling mavlink status from the mavlink shell.
The coredump presents the following deadlock situation: Both mavlink transmit (`mavlink_if0`) and receive (`mavlink_rcv_if0`) tasks are waiting on the `mavlink_module_mutex`, which is held by the `mavlink` task executing the `mavlink status` command launched from task `mavlink_shell`.
```
(gdb) px4_tasks
╷                        ╷      ╷      ╷       ╷
│                        │      │      │       │
pid │ Task Name              │ Prio │ Base │ State │ Waiting For
══════╪════════════════════════╪══════╪══════╪═══════╪═══════════════════════════════════
1267 │ mavlink_if0            │  100 │  100 │ w:sem │ 0x20020ca0 -2 waiting: 1x mavlink
1268 │ mavlink_rcv_if0        │  175 │  175 │ w:sem │ 0x20020ca0 -2 …
```

[mavlink] Use separate mutex for event buffer to prevent deadlock

---

platforms/common/px4_work_queue/WorkItemSingleShot.cpp
src/include/containers/BlockingQueue.hpp

This disables priority inheritance for signaling semaphores. These two cause issues for me, although there might be other semaphores that require similar fixes.

nuttx/semaphore: Disable priority inheritance for signaling semaphores.

---

boards/modalai/voxl2-slpi/src/drivers/icm42688p/InvenSense_ICM42688P_registers.hpp
src/drivers/imu/invensense/icm42688p/ICM42688P.hpp
src/drivers/imu/invensense/icm42688p/InvenSense_ICM42688P_registers.hpp

This prevents accidental misconfiguration via I2C if there are multiple SPI devices on the same bus. The device may hear it's i2c address and write some register, while there is data transfer ongoing with another device.

Disable I2C interface in ICM42688P sensor when it is initialized

---

src/modules/navigator/mission.cpp
src/modules/navigator/mission_base.cpp
src/modules/navigator/mission_base.h

There is a bug when activating a mission for checking if a climb is required. The check is performed on the inactivation_index instead of the chosen mission index. The inactivation index should only be used when infering, if a mission was interrupted during a survey, instead the climb required check should always be performed on the mission item that comes first. In addition the inactivation index should be reset, when a misison is interrupted and the user changes the current sequence as well as when the mission is reset.
- Make sure to use the current mission index when performing the climb check.
- Reset inactivation index when user sets current sequence of the mission is reset.
```
Bugfix Make sure the climb check at the start of a mission is …
```

Check mission climb always on current mission item

---

boards/px4/fmu-v6x/init/rc.board_sensors

Prevent error messages:
```
ERROR [SPI_I2C] icm42688p: no instance started (no device on bus?)
ERROR [SPI_I2C] icm20649: no instance started (no device on bus?)
```
by not starting  starting icm42688p, icm42670p, icm2069, icm20602 on V6X with Rev 6 Sensors set

px4_fmu-v6x:Rev 6 Sensors omit starting icm42688p, icm42670p, icm2069, icm20602

---

platforms/common/uORB/Subscription.cpp

When using Subscription::ChangeInstance() I found that it was unexpectedly returning false, even when instances existed.
- Fix minor typo

uorb: fix Subscription::ChangeInstance() bug

---

src/modules/mavlink/mavlink_mission.cpp

Fixes #22069.
The mission_type was defaulted to 0 before which messed with transmitting geofence and rally items.
Needs to go into v1.14 as well.
Thanks to [av-jeroen](https://github.com/av-jeroen) for reporting the bug.

mavlink: properly set mission_type

---

platforms/nuttx/src/px4/stm/stm32_common/io_pins/io_timer.c

We provide a latency measurement in the input capture handler. However, since the timer was not enabled, none of the counter were running therefore all counters were zero, thus latency was also zero.
Since the HRT is used to provide a timestamp, the lack of the running timer was never noticed. After enabling the timer, latency now correctly shows 9-10 counts.
```
nsh> camera_capture status
INFO  [camera_capture] Capture enabled : YES
INFO  [camera_capture] Frame sequence : 148
INFO  [camera_capture] Last trigger timestamp : 131463420 (6236 ms ago)
INFO  [camera_capture] Number of overflows : 0
INFO  [camera_capture] Status chan: 6 edges: 159 last time: 131463420 last state: 1 overflows: 19 latency: 10
```
Watching the register file differences via the debugger during camera triggers after …

iotimer: Enable timer when configuring input capture

---

src/modules/ekf2/EKF2.cpp
src/modules/ekf2/EKF2.hpp

We should otherwise call this publication before the aid_src publisher that sets the timestamp. Having it separate avoids this ordering constraint.

ekf2: fix optical_flow_vel publication

---

platforms/common/px4_log.cpp
src/modules/commander/HealthAndArmingChecks/checks/sdcardCheck.cpp

Fix expected behavior points 2. and 3. from https://github.com/PX4/PX4-Autopilot/issues/22259
Shorten the message
It seems to cause multiple issues to have a long message:
- The full message doesn't show on the console because the buffer only has length of `log_message.text` which is 127.
- The additional text shows even if the event that replaces this message already exists. I honestly didn't find the mechanism that breaks there.
```
Bugfix: Show hard fault log availability message correctly
```
Ideally, longer messages would be supported correctly or there would be a compile error preventing developers from using them. Note that it's not that easy because e.g. the colorized console output uses up > 50 bytes for all the WARN, coloring and module name from the 127-byte buffer.
- Tested …

sdcardCheck: shorten hardfault log availability message

---

boards/nxp/ucans32k146/init/rc.board_defaults
boards/nxp/ucans32k146/src/boot.c
platforms/nuttx/src/canbootloader/arch/nxp/s32k14x/board_identity.c
platforms/nuttx/src/canbootloader/arch/nxp/s32k14x/drivers/can/driver.c
platforms/nuttx/src/px4/nxp/s32k14x/include/px4_arch/micro_hal.h
src/drivers/bootloaders/boot_app_shared.c
src/drivers/bootloaders/boot_app_shared.h
src/drivers/uavcannode/UavcanNode.cpp
src/drivers/uavcannode/UavcanNode.hpp

When only this device was on bus not ACK's would be sent and device could not autobaud.
[94ee6d3](https://github.com/PX4/PX4-Autopilot/pull/22247/commits/94ee6d304b6ce432a840946555abe6c345cf590b) Solves https://github.com/PX4/PX4-Autopilot/issues/22068
~~But there is still an issue with APP not taking the boot baudrate and Node ID. from the bootloader.~~
- The s32k bootloader was not actually writing the Node ID and bit rate.  
s32k14x:Make use of boot_app_shared shared_[un]lock] cc31daa3bbd77595840ae460af1391a84be7cf89 Solves this.
- Once the  Node ID and bit rate was written, the Nuttx SocketCAN driver was wiping out the values. 
This is solved with:
boot_app_shared:Add optional board_app_shared_read  f8fe64ba9135a851d624bf83af60dcb6615d4b39
UavcanNode:Support optional …

s32k14x canbootloader:Change autobaud to ACK and range high to low

---

boards/ark/fmu-v6x/src/board_config.h
boards/ark/fmu-v6x/src/spix_sync.c

In an attempt to get the SPIX_SYNC output frequency I wanted, I inadvertadntly caused the PWM output value calculation to be wrong by 25-50us. This fix separates the SPIX_SYNC from the BOARD_PWM_FREQ.
Will need to backport into 1.14.
@ryanjAA

boards: arkv6x fix wrong pwm output values

---

Tools/simulation/gz/models/omnicopter/model.sdf

When running the command line instructions found on the PX4 manual related to Gazebo, I found that vehicles would clip into the ground as their default pose was placed at 0,0,0,0,0,0. No fix is required except running a different command that uses an alias of `PX4_GZ_MODEL`. This is currently being updated in: https://github.com/PX4/PX4-user_guide/pull/2801. 
This PR addresses movign the default pose provided in the omniocopter's model.sdf file. It is set at 0,0,0,0,0,0 meaning that it will clip into the ground regardless of command. By moving the default pose, the omnicoper will sit on top of the ground rather than in it. 
Fixes #22214 
Move default pose of omnicopter in sdf file along z-axis by 20cm.

update default omnicopter pose in gazebo

---

src/modules/zenoh/CMakeLists.txt

Zenoh PR broke CI, we ignore stringop-truncation warnings specifically for zenoh-pico library.

zenoh: fix sitl ci compile warning

---

boards/ark/fmu-v6x/src/board_config.h
boards/ark/fmu-v6x/src/spix_sync.c

Backport of https://github.com/PX4/PX4-Autopilot/pull/22270
@ryanjAA

1.14 backport: boards: arkv6x fix wrong pwm output values

---

src/modules/ekf2/EKF/gnss_height_control.cpp
src/modules/ekf2/EKF/gps_control.cpp

There is no reason to keep an uncertainty on the origin as it is then already contained in the local position estimate when GNSS data is fused in the filter.

ekf2: reset globlal position uncertainty when GNSS is fused

---

src/modules/mavlink/mavlink_receiver.cpp

Minor change :smile: 
The value `current_filtered_a` is assigned twice. Once where I removed it, and once on the line after.

mavlink-receiver: remove double assignment of battery field

---

platforms/common/CMakeLists.txt
src/lib/parameters/CMakeLists.txt

Fixes the compilation with `CONFIG_PLATFORM_ROS2=y`.
Fix/workaround includes.

fix compiling on ros2 platform

---

src/modules/commander/HealthAndArmingChecks/checks/windCheck.cpp
src/modules/commander/HealthAndArmingChecks/checks/windCheck.hpp
src/modules/commander/commander_params.c
src/modules/commander/failsafe/failsafe.cpp
src/modules/commander/failsafe/failsafe.h

Currently the action after a "high wind speed detected" is hard coded to RTL. We would like to expose it to the user to easily switch on/off this failsafe, and doing that over the currently only interface COM_WIN_MAX (eg set to -1 to disable) is not as easy as setting a boolean. 
For some use cases, setting the action to Land instead of RTL is more appropriate, and even further options like Terminate could be added.
Add new param `COM_WIND_MAX_ACT` with fields:
- None (in that case COM_WIND_MAX is not looked at at all)
- Warning ( in that case, if the wind is above COM_WIND_MAX, it publishes a warning that replaces the one for COM_WIND_WARN)
- Hold
- Return
- Terminate
- Land
<del>The issue I have with this way of implementing it is that it is not possible to disable the failsafe action …

Commander: add COM_WIND_MAX_ACT param

---

src/modules/commander/HealthAndArmingChecks/checks/cpuResourceCheck.cpp
src/modules/commander/HealthAndArmingChecks/checks/cpuResourceCheck.hpp
src/modules/commander/commander_params.c

Momentary CPU spikes are not an issue and should not prevent arming or alarm the operator. 
This PR adds a 2 second hysteresis to the high CPU load preflight check.
```
Improvement: add 2s hysteresis to CPU load check to not trigger on load spikes.
```
Have high_cpu_load_start_time_us_ as as class member instead of a static variable? 
Tested on a PH4, with COM_CPU_MAX set to 60 and then doing some param changes. On main this then throws warnings, with this PR not anymore.

Commander: cpuResourcesCheck: add 2 seconds hysteresis to trigger failure

---

src/modules/ekf2/EKF/sensor_range_finder.cpp
src/modules/ekf2/EKF/sensor_range_finder.hpp
src/modules/ekf2/test/test_SensorRangeFinder.cpp

The stuck detector in the `sensor_range_finder` is not relevant for our sensor and causes a short delay before the sensor becomes healthy again after pointing at something it cannot detect for a while.
This PR makes the stuck detector optional by explicitly checking whether `_stuck_threshold` is 0 and then always setting _is_stuck = false.
With this PR the stuck detector can be disabled by setting `_stuck_threshold = 0.f`
https://github.com/scoutdi/PX4-PX4-Autopilot/blob/97ca7b9b215f55dd7d27463062cd1ec958f20cac/src/modules/ekf2/EKF/sensor_range_finder.hpp#L135
```
Make sensor_range_finder stuck detector optional
New parameter: N/A
Documentation: Set _stuck_threshold = 0.f to disable.
```
We could already disable it in practice by setting _stuck_treshold < 0, which would …

ekf2: Make sensor_range_finder stuck detector optional

---

src/modules/flight_mode_manager/tasks/ManualAltitude/FlightTaskManualAltitude.cpp
src/modules/flight_mode_manager/tasks/ManualAltitude/FlightTaskManualAltitude.hpp
src/modules/flight_mode_manager/tasks/ManualAltitudeSmoothVel/FlightTaskManualAltitudeSmoothVel.cpp
src/modules/flight_mode_manager/tasks/ManualAltitudeSmoothVel/FlightTaskManualAltitudeSmoothVel.hpp
src/modules/flight_mode_manager/tasks/ManualPositionSmoothVel/FlightTaskManualPositionSmoothVel.cpp
src/modules/flight_mode_manager/tasks/ManualPositionSmoothVel/FlightTaskManualPositionSmoothVel.hpp
src/modules/mc_pos_control/multicopter_altitude_mode_params.c

Continuation of https://github.com/PX4/PX4-Autopilot/pull/21885 and should fix https://github.com/PX4/PX4-Autopilot/issues/22221
Flew under the deck which caused the GNSS fusion to stop then flew back out.
https://review.px4.io/plot_app?log=d6be638f-4ca1-4ed9-ae6b-8969ea724a9a
On a 650
https://review.px4.io/plot_app?log=de32ab72-e175-4ea4-8d6b-a76fae956b7e

flight mode manager: fix terrain hold

---

msg/TecsStatus.msg
src/lib/tecs/TECS.cpp
src/lib/tecs/TECS.hpp
src/modules/fw_pos_control/FixedwingPositionControl.cpp

The underspeed logic inside TECS overwrites the incoming airspeed setpoint and sets that one to FW_AIRSPD_MIN. That way, in case an underspeed is detected, the airspeed setpoint it then applies may not even be enough to not stall (there is no bank angle or high wind compensation in that case). 
Remove the airspeed setpoint adaption in case of underspeed. 
It now does the following in the underspeed state:
- set the speed weight to 2 (foll prio on airpseed and not height rate error)
- set throttle to FW_THR_MAX (it is debatable if that is needed and beneficial or if simply setting the speed weight is enough)
Beside that I took the opportunity and changed the `TECS_MODE` enum into a boolean `underspeed_mode_enabled`. That's more descriptive and cleaner in my view.
``` …
```

TECS controller: do not adapt the airspeed setpoint in case of underspeed.

---

src/modules/ekf2/EKF/EKFGSF_yaw.cpp
src/modules/ekf2/EKF/EKFGSF_yaw.h
src/modules/ekf2/EKF/gps_control.cpp

- if not in air the accel noise is doubled
- if landed don't init unless GPS velocity is non-negligible (magnitude of GPS velocity exceeds reported accuracy)
- when inactive continue seeding with EKF gyro bias
- reset yaw estimator if GPS fusion is stopped

ekf2: EKFGSF always run

---

platforms/nuttx/NuttX/include/cxx/new

When adding a new third-party library to our project ([HFSM2](https://github.com/andrew-gresyk/HFSM2), FWIW), I found that there were compilation issues with **platforms/nuttx/NuttX/include/cxx/new**:
```
/home/robbie/px4/platforms/nuttx/NuttX/include/cxx/new:34:34: error: declaration of 'operator new' as non-function
34 | inline void* operator new  (std::size_t, void* ptr) { return ptr; }
|                                  ^~~~~~
```
Despite the warning from the compiler, the error in my IDE (VSCode) reported that "namespace 'std' has no member 'size_t'"
I found that the compilation error went away when I included the library header later in my code, suggesting that something in the include chain could fix the error
- Explicitly `#include <cstddef>` in …

nuttx: fix <new>

---

src/modules/commander/failsafe/failsafe.cpp

Some batteries issues can only be seen after arming. If a failure occurs between arming and takeoff, it's safer to disarm immediately.
```
Disarm if battery failure is detected during spool-up
```

Disarm if battery failure is detected during spool-up

---

src/lib/modes/standard_modes.hpp
src/lib/modes/ui.hpp
src/modules/mavlink/streams/AVAILABLE_MODES.hpp

adds the MAV_MODE_PROPERTY_ADVANCED property to any flight mode that is not Altitude, Position, or external

flightmodes: flag advanced modes accordingly

---

test/mavsdk_tests/test_vtol_rtl.cpp

- explicitly disable RTL_FORCE_APPROACH for RTL direct Home testcase

vtol_rtl_test: explicitly disable RTL_FORCE_APPROACH for RTL home test

---

ROMFS/px4fmu_common/init.d-posix/airframes/1040_gazebo-classic_standard_vtol
src/modules/airspeed_selector/airspeed_selector_params.c
src/modules/ekf2/EKF/sideslip_fusion.cpp
src/modules/ekf2/ekf2_params.c
src/modules/simulation/simulator_mavlink/SimulatorMavlink.cpp
src/modules/simulation/simulator_mavlink/SimulatorMavlink.hpp
src/modules/simulation/simulator_mavlink/sitl_targets_gazebo-classic.cmake
test/mavsdk_tests/CMakeLists.txt
test/mavsdk_tests/autopilot_tester.cpp
test/mavsdk_tests/autopilot_tester.h
test/mavsdk_tests/configs/sitl.json
test/mavsdk_tests/mavsdk_test_runner.py
test/mavsdk_tests/process_helper.py
test/mavsdk_tests/test_vtol_loiter_airspeed_failure_blockage.cpp
test/mavsdk_tests/test_vtol_mission_wind.cpp
test/mavsdk_tests/vtol_mission_straight_south.plan

We had an incident lately where a VTOL flew into a thunderstorm, which caused a couple of (linked) issues to surface.
Chain of events:
- wind increases by 15m/s within roughly 1min, from 8m/s to ~23m/s. In the steepest part of the wind increase it went up  1m/s in average (from 10.5 to 22m/s within 15s)
- airspeed is declared invalid shortly after hitting the wind wall (due to high airspeed innovation compared to the wind estimate by the validator)
- the EKF wind states reset to wrong values and in the following never recover again (reset because of fusion timeout, both by airspeed and beta fusion)
- NPFG (lateral FW guidance) assumes wind valid and keeps using it. As the states are obviously majorly wrong the vehicle drifts away while doing circles
Reproduced condition in SITL: constant …

Fixed-wing/VTOL: High wind hardening

---

src/modules/mavlink/mavlink_mission.cpp

Backport of https://github.com/PX4/PX4-Autopilot/pull/22248.

[BACKPORT v1.4] mavlink: properly set mission_type

---

ROMFS/px4fmu_common/init.d/rcS
boards/ark/fmu-v6x/init/rc.board_defaults
boards/cubepilot/cubeorange/init/rc.board_defaults
boards/cubepilot/cubeorangeplus/init/rc.board_defaults
boards/cubepilot/cubeyellow/init/rc.board_defaults
boards/holybro/durandal-v1/init/rc.board_defaults
boards/holybro/pix32v5/init/rc.board_defaults
boards/mro/x21-777/init/rc.board_defaults
boards/mro/x21/init/rc.board_defaults
boards/px4/fmu-v2/init/rc.board_defaults
boards/px4/fmu-v3/init/rc.board_defaults
boards/px4/fmu-v4pro/init/rc.board_defaults
boards/px4/fmu-v5/init/rc.board_defaults
boards/px4/fmu-v5x/init/rc.board_defaults
boards/px4/fmu-v6c/init/rc.board_defaults
boards/px4/fmu-v6x/init/rc.board_defaults
boards/siyi/n7/init/rc.board_defaults
boards/sky-drones/smartap-airlink/init/rc.board_defaults
boards/thepeach/k1/init/rc.board_defaults
boards/thepeach/r1/init/rc.board_defaults
src/drivers/px4io/px4io.cpp
src/drivers/px4io/px4io_params.c

The param is not really required anymore with the actuator configuration. Also, when it is set to 0, RC doesn't work for some boards which would be nice to avoid.
If you have alternative ways to fix #22206, that's fine with me, but as it is now, the param description is a lie and this is a major regression with v1.14.
Fixes https://github.com/PX4/PX4-Autopilot/issues/22206
Needs to go into v1.14.

Remove SYS_USE_IO param

---

src/lib/motion_planning/PositionSmoothing.cpp
src/lib/motion_planning/PositionSmoothing.hpp

We got multiple reports that the altitude profile between two waypoints is not a diagonal line but changes altitude much quicker when leaving the previous waypoint and getting much flatter after that.
During a round corner the L1 distance calculation
was only done in 2D and the z-axis coordinate
was directly coming from the next waypoint.
This lead to an unpredictable altitude profile
between two waypoints. Sometimes almost all
altitude difference was already covered during
the turn instead of going diagonally.
- Make the entire L1 distance and intersection calculation 3D
- Refactor ...
```
Bugfix: Multicopter altitude change sometimes not linear between two waypoints
```
Simulation testing procedure:
1. Command to test: `PX4_SIM_SPEED_FACTOR=100 make px4_sitl …

PositionSmoothing: fix corner altitude bug

---

src/lib/motion_planning/PositionSmoothing.cpp
src/lib/motion_planning/PositionSmoothing.hpp

https://github.com/PX4/PX4-Autopilot/pull/22331
```
Bugfix: Multicopter altitude change sometimes not linear between two waypoints
```
I verified specifically on 1.14 the bug exists the exact same way and is fixed with the change with the same simulation testing method described in the original pr.

[1.14] PositionSmoothing: fix corner altitude bug

---

ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator

~Two things that caught my eye. See commits.~
This fixes the error:
```etc/init.d-posix/rcS: 39: [: Illegal number:```

SITL: fix parse error on start

---

ROMFS/px4fmu_common/init.d-posix/airframes/4004_gz_standard_vtol

VTOL simulation was still using the L1 deprecated a warning message was displayed at startup.
Just removed the setting of the deprecated parameter in the configuration script for simulated VTOL.

fix: remove L1 deprecated parameter in VTOL simulation

---

src/modules/mavlink/mavlink_receiver.cpp

I can unify by matching the wording with other wording.
Change lowercase LANDING to uppercase Landing.
None
None
None
None

mavlink: Capitalize the first letter of Landing

---

src/lib/battery/battery.cpp

This triggers the undefined behavior fuzzer, so let's try to fix it.
https://github.com/PX4/PX4-Autopilot/runs/7315277790?check_suite_focus=true#step:5:51

battery: skip charge estimation if N cells is 0

---

src/modules/commander/Commander.cpp
src/modules/commander/Commander.hpp
src/modules/commander/MulticopterThrowLaunch/CMakeLists.txt
src/modules/commander/MulticopterThrowLaunch/MulticopterThrowLaunch.cpp
src/modules/commander/MulticopterThrowLaunch/MulticopterThrowLaunch.hpp
src/modules/commander/commander_params.c
src/modules/mc_pos_control/MulticopterPositionControl.cpp
src/modules/mc_pos_control/MulticopterPositionControl.hpp
src/modules/mc_pos_control/Takeoff/Takeoff.cpp
src/modules/mc_pos_control/Takeoff/TakeoffTest.cpp

This PR implements a throw-launch feature for multicopters: the ability to start the drone by throwing it into the air. The drone should not spin the propellers while held in hand and only do that when airborne.
It is based on the discussions here: https://discuss.px4.io/t/quadrotor-launch-control-throw-launches/212
Technically, the feature is realized by locking the motors (i.e., preventing them from spinning) after the drone is armed and releasing the lock only when a fall down is detected. Then, the drone stabilizes according to the mode it is in.
The feature was tested both in simulation and real flight, an example flight log is available here: 
https://logs.px4.io/plot_app?log=184b1c7f-e875-4937-a12d-c7dfca8e70aa (bad throw with lots of rolling, but the drone still recovers) …

throw launch

---

src/modules/navigator/loiter.cpp
src/modules/navigator/mission_block.cpp

When using a VTOL takeoff, a loiter location can be set. when the system reaches the takeoff altitude, it starts loitering at the current position instead of continuing at the loiter location defined in the VTOL takeoff. 
- Check in the loiter activation is the current position setpoint is a valid loiter point. If this is true and no reposition is active, set the loiter position to the loiter position item.
- Refactor ...
```
Bugfix VTOL takeoff: do not change loiter location after VTOL takeoff completed.
```
- Simulation tests: using gazebo-classic_standard_vtol.
- Check correct loiter location for vtol takeoff.
- Check correct functionality for hold when currently flying to an orbit/mission orbit

VTOL takeoff: do not change loiter location after VTOL takeoff completed

---

src/lib/parameters/px4params/markdownout.py

Some of the params have ">" characters, which break the HTML in the param reference. Browsers are pretty robust so this was rendering mostly OK most of the time, but I think it is the cause of some weird loading errors with the param ref page.
This escapes the values. Also used f-strings to improve the rendering, and tidied it up a little.

Escape param metadata to fix broken tags

---

boards/nxp/ucans32k146/src/clockconfig.c

As described in the S32K1XX reference manual table 27-1 SPLLDIV2 should be 40Mhz or less.

ucans32k1: SPLLDIV2 set to 40Mhz

---

ROMFS/px4fmu_common/init.d/rcS
boards/ark/fmu-v6x/init/rc.board_defaults
boards/cubepilot/cubeorange/init/rc.board_defaults
boards/cubepilot/cubeorangeplus/init/rc.board_defaults
boards/cubepilot/cubeyellow/init/rc.board_defaults
boards/holybro/durandal-v1/init/rc.board_defaults
boards/holybro/pix32v5/init/rc.board_defaults
boards/mro/x21-777/init/rc.board_defaults
boards/mro/x21/init/rc.board_defaults
boards/px4/fmu-v2/init/rc.board_defaults
boards/px4/fmu-v3/init/rc.board_defaults
boards/px4/fmu-v4pro/init/rc.board_defaults
boards/px4/fmu-v5/init/rc.board_defaults
boards/px4/fmu-v5x/init/rc.board_defaults
boards/px4/fmu-v6c/init/rc.board_defaults
boards/px4/fmu-v6x/init/rc.board_defaults
boards/sky-drones/smartap-airlink/init/rc.board_defaults
boards/thepeach/k1/init/rc.board_defaults
boards/thepeach/r1/init/rc.board_defaults
src/drivers/px4io/px4io.cpp
src/drivers/px4io/px4io_params.c

[BACKPORT v1.14] Remove SYS_USE_IO param

---

src/modules/fw_autotune_attitude_control/fw_autotune_attitude_control.cpp
src/modules/mc_autotune_attitude_control/mc_autotune_attitude_control.cpp

Autotune is sometimes stuck in the Init state because it waits for the filters to initialize but nothing happens because there is no need for a reset.
```
Autotune: fix state machine stuck in "Initializing"
```

Autotune: fix state machine stuck in "Initializing"

---

src/modules/commander/Commander.cpp
src/modules/commander/Commander.hpp
src/modules/commander/commander_params.c
src/modules/manual_control/ManualControl.cpp
src/modules/manual_control/ManualControl.hpp
src/modules/manual_control/manual_control_params.c

We received the requirement to not disarm in Manual/Stabilized mode when not landed but keep an accessible way to be able to kill the vehicle. After a local solution my goal was to find something future proof and I came up with this suggestion.
A rough solution:
- Kill if sticks are held "left stick lower left and right stick lower right" for 10 seconds
- Parameter to be able to disable disarming when not landed in manual thrust modes like Acro, Stabilized
I can confirm what Beat mentioned: We would not have this problem if the arm and disarm gesture would be using both sticks e.g. arm with left stick lower right, right stick lower left and disarming with left stick lower left …

Stick gesture to kill

---

.vscode/cmake-variants.yaml

There is currently no CMake variant for the Cube Orange Plus meaning that full VSCode development (including building through VSCode) for this target is not possible.
- Add new variant to the list of CMake variants
- Used the _test target (as used for standard Cube Orange) to allow hardware debugging by default (serial console)
```
Cube Orange Plus variant added to list of CMake variants
```
N/A
- Build is successful through VSCode
N/A

Add Cube Orange Plus to CMake variants

---

src/modules/uxrce_dds_client/dds_topics.yaml

@bradenwagstaff is working on controlling a rover through uxrce and manual_control_setpoint is needed.

uxrce add manual control setpoint subscriber and battery status publisher

---

src/modules/flight_mode_manager/FlightModeManager.cpp
src/modules/flight_mode_manager/FlightModeManager.hpp
src/modules/land_detector/land_detector_params_mc.c
src/modules/navigator/land.cpp
src/modules/navigator/loiter.cpp
src/modules/navigator/mission.cpp
src/modules/navigator/mission_base.cpp
src/modules/navigator/mission_block.cpp
src/modules/navigator/mission_block.h
src/modules/navigator/navigator.h
src/modules/navigator/rtl_direct.cpp
src/modules/navigator/rtl_direct_mission_land.cpp
src/modules/navigator/rtl_mission_fast.cpp
src/modules/navigator/rtl_mission_fast_reverse.cpp
src/modules/navigator/takeoff.cpp
src/modules/navigator/vtol_takeoff.cpp

When discussing with @sfuhrer about geofence improvements he mentioned again the overlap between `LNDMC_ALT_MAX` and `GF_MAX_VER_DIST`. I know @dagar was bringing this up many times.
I think now is the right time to remove it since I'm not aware who is using that functionality right now and @sfuhrer is working on geofence improvements which should allow us to forward users to using `GF_MAX_VER_DIST`.
Fixes #13345
I remove `LNDMC_ALT_MAX` completely.
It was introduced here: https://github.com/PX4/PX4-Autopilot/pull/6679
extended to shift down mission items here: https://github.com/PX4/PX4-Autopilot/pull/8048
```
Cleanup: Remove LNDMC_ALT_MAX, use GF_MAX_VER_DIST instead
```
We could use `GF_MAX_VER_DIST` in place of how `LNDMC_ALT_MAX` is currently used but:
- On multicopter it prevents …

Remove LNDMC_ALT_MAX

---

ROMFS/px4fmu_common/init.d/rcS
src/drivers/px4io/px4io.cpp

This PR adds a "supported" command to the px4io driver. If its not supported, then rcS won't attempt to update the IO MCU and start it.
Fixes https://github.com/PX4/PX4-Autopilot/issues/22356

drivers: px4io add 'support' command and update rcS logic

---

src/modules/ekf2/EKF/range_finder_consistency_check.cpp
src/modules/ekf2/EKF/range_finder_consistency_check.hpp
src/modules/ekf2/EKF/range_height_control.cpp
src/modules/ekf2/EKF/terrain_estimator.cpp

fixes: https://github.com/PX4/PX4-Autopilot/issues/22357
The issues was caused by the reset function setting `_time_last_healthy_rng_data` to 0, leading to an immediate timeout at the next loop run.
Issue got introduces in https://github.com/PX4/PX4-Autopilot/pull/21338
and fixed in https://github.com/PX4/PX4-Autopilot/pull/22030
I also decided to pull https://github.com/PX4/PX4-Autopilot/pull/22117 to reduce the likelihood of hitting another corner care that we fixed recently on the range finder kinematic consistency check.
Verified in replay using https://review.px4.io/plot_app?log=76f8ab88-738c-4a14-a9f7-dd87dd617366
Before:
After:

[1.14] Fix terrain estimator validity issue

---

src/modules/flight_mode_manager/tasks/ManualAltitude/FlightTaskManualAltitude.cpp
src/modules/flight_mode_manager/tasks/ManualAltitude/FlightTaskManualAltitude.hpp
src/modules/flight_mode_manager/tasks/ManualAltitudeSmoothVel/FlightTaskManualAltitudeSmoothVel.cpp
src/modules/flight_mode_manager/tasks/ManualAltitudeSmoothVel/FlightTaskManualAltitudeSmoothVel.hpp
src/modules/flight_mode_manager/tasks/ManualPositionSmoothVel/FlightTaskManualPositionSmoothVel.cpp
src/modules/flight_mode_manager/tasks/ManualPositionSmoothVel/FlightTaskManualPositionSmoothVel.hpp

Backport of https://github.com/PX4/PX4-Autopilot/pull/22294 without the default parameter change.

1.14 backport: flight mode manager: fix terrain hold

---

msg/VehicleOpticalFlowVel.msg
src/modules/ekf2/EKF/common.h
src/modules/ekf2/EKF/ekf.h
src/modules/ekf2/EKF/estimator_interface.h
src/modules/ekf2/EKF/optflow_fusion.cpp
src/modules/ekf2/EKF/optical_flow_control.cpp
src/modules/ekf2/EKF/terrain_estimator.cpp
src/modules/ekf2/EKF2.cpp
src/modules/ekf2/test/sensor_simulator/flow.cpp
src/modules/ekf2/test/sensor_simulator/sensor_simulator.cpp
src/modules/ekf2/test/test_EKF_flow.cpp
src/modules/ekf2/test/test_EKF_fusionLogic.cpp
src/modules/ekf2/test/test_EKF_gps.cpp
src/modules/ekf2/test/test_EKF_terrain_estimator.cpp
src/modules/logger/logged_topics.cpp
src/modules/replay/Replay.cpp
src/modules/sensors/vehicle_optical_flow/VehicleOpticalFlow.cpp

replaces https://github.com/PX4/PX4-Autopilot/pull/21005
The optical flow control logic is way too complicated to read, has a lot of strange behaviors due to the multiple possible paths in the code and several strange legacy checks.
Furthermore, it tries to compensate the flow due to angular motion by popping the data from the buffer early to be able to accumulate gyro data during the flow integration interval, which makes the code even more complicated. I also think that it wasn't working as expected and that most of the time, only 1 gyro sample is available between the start of the integration and the midpoint (where we want to fuse it), so IMO, there is no real benefit of doing it this way. Also note that this integration is also now done in `VehicleOpticalFlow`.
- convert to flow rate …

EKF2: optical flow refactoring

---

src/modules/uxrce_dds_client/dds_topics.h.em
src/modules/uxrce_dds_client/dds_topics.yaml
src/modules/uxrce_dds_client/generate_dds_topics.py

Currently we cannot have topics subscribed over DDS be republished via `uORB::PublicationMulti`.
Scenario: I want to test and compare two sources of `vehicle_optical_flow_vel`, one produced internally and one produced from an external app. I want to log both topics on the same mission for evaluation. Currently dds subscribing to `/fmu/in/vehicle_optical_flow_vel` will prevent from being able to view `vehicle_optical_flow_vel` published internally.
- Add `subscriptions_multi` field to `dds_topics.yaml`. This create a `uORB::PublicationMulti` for the specified topics.
```
Feature: Adds multi publication option for subscribed dds topics
```
After: logging multiple sources of a topic. internal and over DDS.
I can produce instructions to reproduce the results above if this …

dds_topics: Add multi publication for topics subscribed over dds

---

src/modules/logger/logged_topics.cpp

I propose to log GPS data at full rate instead of once a second because GPS data is usually only 10 Hz anyway, and for debugging every sample can be an important clue.
For instance, not all sensor_gps messages contain the heading, and so heading is completely missed and impossible to debug.
This came up when debugging https://discuss.px4.io/t/um982-isnt-providing-heading-data/35195.

logger: log all GPS data

---

.github/workflows/nuttx_env_config.yml
platforms/nuttx/NuttX/CMakeLists.txt
platforms/nuttx/cmake/init.cmake

Our use-case is to enable nsh password protection for release builds.
For example:
```
export PX4_EXTRA_NUTTX_CONFIG="CONFIG_NSH_LOGIN_PASSWORD=\"test\";CONFIG_NSH_CONSOLE_LOGIN=y"
make px4_fmu-v5x
```
```
Allow extra nuttx config options via PX4_EXTRA_NUTTX_CONFIG env var
```

Allow extra nuttx config options via PX4_EXTRA_NUTTX_CONFIG env var

---

src/drivers/ins/vectornav/VectorNav.cpp
src/drivers/ins/vectornav/VectorNav.hpp

This is a bit of a workaround for using the VectorNav INS in place of onboard ekf2. To continue using the airspeed selector without ekf2 it currently depends on estimator status mag_test_ratio (really heading) and vel_test_ratio for validity checks in order to use the velocity estimate.
Not yet verified on a real setup.

drivers/ins/vectornav: publish estimator_status (only in VN_MODE 1)

---

msg/FailsafeFlags.msg
msg/GeofenceResult.msg
src/lib/events/enums.json
src/modules/commander/HealthAndArmingChecks/checks/geofenceCheck.cpp
src/modules/commander/failsafe/failsafe.cpp
src/modules/mavlink/streams/HIGH_LATENCY2.hpp
src/modules/navigator/GeofenceBreachAvoidance/geofence_breach_avoidance.cpp
src/modules/navigator/GeofenceBreachAvoidance/geofence_breach_avoidance.h
src/modules/navigator/geofence.cpp
src/modules/navigator/geofence.h
src/modules/navigator/geofence_params.c
src/modules/navigator/mission_feasibility_checker.cpp
src/modules/navigator/mission_feasibility_checker.h
src/modules/navigator/navigator.h
src/modules/navigator/navigator_main.cpp

Fixes: 
1) listen to GF_SOURCE (fixes https://github.com/PX4/PX4-Autopilot/issues/20677)
2) do not constantly send new reposition waypoints when GF is breached as a fixed-wing
New features:
3) if armed, do not allow to upload GF that would immediately trigger
4) do not allow to upload GF if it doesn't contain Home (to not break RTL)
Functional changes (neither new features nor fixes):
5) has to be in all inclusion GF 
6) remove GF_ALTMODE (with the big baro offset usually present this is quite unusable)
7) remove GF_COUNT (don't see need, don't find it intuitive)
8) change messaging
9) some code cleanup
1) correctly listen to it.
2) if GF_ACTION is HOLD, and GF is breached: stay in the "GF breached mode" until the current loiter is changed (through new reposition or change of mode) --> …

Navigator: Geofence improvements

---

msg/OffboardControlMode.msg
src/modules/commander/HealthAndArmingChecks/checks/offboardCheck.cpp
src/modules/commander/ModeUtil/control_mode.cpp
src/modules/uxrce_dds_client/dds_topics.yaml

EDITED on 2023/11/18
- The `actuator` flag of the `offboard_control_mode` was referring to _thrust_ and _torque_ control, requesting `vehicle_thrust_setpoints` and `vehicle_torque_setpoint`.
- direct actuator control (bypassing the control allocator) was not possible.
- The current `actuator` flag of the `offboard_control_mode` is renamed `thrust_and_torque`.
- The new ~~`actuator`~~ `direct_actuator` flag disables the control allocator module. The offboard controller has then to provide `actuator_motors` and `actuator_servos` messages.
- New topics added to the uxrce_dds bridge (subscriptions). No additioal load is introduced as the topics are only used if published by the offboard controller.
- `vehicle_thrust_setpoints` and `vehicle_torque_setpoint`
- `actuator_motors` and …

[offboard control] allow for direct actuator control

---

msg/VehicleControlMode.msg
src/modules/commander/ModeManagement.hpp
src/modules/commander/ModeUtil/control_mode.cpp

When running an orbit in simulation I found that the vehicle immediately crashes upon the first command.
A quick bisect led me to https://github.com/PX4/PX4-Autopilot/pull/22222 which disabled the allocation for orbit mode so there is not even rate tracking anymore.
Add `flag_control_allocation_enabled` for Orbit mode.
The rest is reordering the flags according to the control cascade while going through them. None of the other modes is missing anything according to my inspection. I assume the allocation flag is useful only in the case where you're in `NAVIGATION_STATE_OFFBOARD` but none of the `offboard_control_mode` flags are set then the allocation is not running and the offboard thing can command the motors.
```
Critical bugfix: Multicopter orbit leads to crash only in main for a few …
```

Fix Orbit Crash

---

msg/HomePosition.msg
msg/MissionResult.msg
src/modules/commander/Commander.cpp
src/modules/commander/HealthAndArmingChecks/checks/missionCheck.cpp
src/modules/commander/HomePosition.cpp
src/modules/navigator/mission_base.cpp
src/modules/navigator/navigator.h

Misison feasibility was not checked again, if the home position or the geofence changed after it was checked once. Further, if the mission was invalid during upload (e.g. home position not valid yet) the mission is cleared.
- Remove clearing the mission when the mission is invalid during mission upload.
- Mission feasibility checks also checks if the geofence counter or the home position timestamp has changed since last check.
```
Bugfix: Do not clear invalid mission after upload
Bugfix: Mission feasibility checks also checks if the geofence counter or the home position timestamp has changed since last check
```
The mission feasibility checks should be moved to another location instead of being performed in the mission mode. They should be moved …

Mission feasibility checks with changing home

---

src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp

If the previous and current setpoint are set to the same, the logic in `FlightTaskAuto::_getCurrentState()` sets the state to offtrack, which then though doesn't get handled correctly as we don't have a track to follow in the first place.
Set state to None in that case.
```
Bugfix: FlightTaskAuto: harden line following logic (only do line following if previous and current setpoints are not equal).
```
It would also be nice to simply the whole (currently very convoluted) logic in `FlightTaskAuto` and `PositionSmoother`. Likely the desired behavior would be that on triggering Land, the vehicle breaks and then descends vertically where it came to reset, instead of going back to the point where the land was triggered as it does currently. 
SITL tests.
Some prints from the …

FlightTaskAuto: set state to None if previous and current setpoint are equal

---

src/lib/timesync/Timesync.hpp
src/modules/uxrce_dds_client/uxrce_dds_client.cpp

- `int64t` are `%lld` for Nuttx target and `%ld` for posix ones.
- The `uxrcs_dds_client` do not wait for the time synchronizet to settle. https://github.com/PX4/PX4-Autopilot/pull/22290#issuecomment-1823768267
- Use `PRId64`
- Wait for the time synchronizer to converge.

[uxrce_dds_client] Fix debug string format and wait for timesync to converge

---

boards/px4/fmu-v6xrt/init/rc.board_mavlink

Mavlink should only started on TELEM2 when on Skynode, replicates V6X behavior

px4_fmu-v6xrt: Fix TELEM2 always being used for mavlink

---

boards/ark/can-flow/init/rc.board_sensors
boards/ark/can-gps/init/rc.board_defaults
boards/ark/can-rtk-gps/init/rc.board_defaults
boards/ark/cannode/init/rc.board_defaults
src/modules/sensors/vehicle_imu/VehicleIMU.cpp
src/modules/sensors/vehicle_imu/VehicleIMU.hpp
src/modules/sensors/vehicle_imu/imu_parameters.c

On the ARK CAN sensors with the sensors module compiled in, various mounting locations can cause IMU clipping. These warnings get sent over the CAN bus and logged.

sensors: add parameter to silence imu clipping

---

msg/Mission.msg
msg/MissionResult.msg
src/modules/commander/Commander.cpp
src/modules/commander/HealthAndArmingChecks/checks/missionCheck.cpp
src/modules/dataman/dataman.cpp
src/modules/mavlink/mavlink_mission.cpp
src/modules/mavlink/mavlink_mission.h
src/modules/navigator/geofence.cpp
src/modules/navigator/geofence.h
src/modules/navigator/mission.cpp
src/modules/navigator/mission_base.cpp
src/modules/navigator/navigation.h
src/modules/navigator/navigator.h
src/modules/navigator/navigator_main.cpp
src/modules/navigator/rtl.cpp
src/modules/navigator/rtl.h
src/systemcmds/tests/test_dataman.cpp

This PR adds support for the Mavlink Mission opaque ID as defined in https://github.com/mavlink/mavlink/pull/2012. It is based on the earlier implementation for the mission checksum support in https://github.com/PX4/PX4-Autopilot/pull/18418, but the mission checksum in Mavlink will be deprecated in https://github.com/mavlink/mavlink/pull/2010.
- Add an opaque Id for the mission, geofence and rally points. The opaque id is based on a Crc32 checksum as in the implementation in https://github.com/PX4/PX4-Autopilot/pull/18418
- Opaque id is send from the System in the MISSION_COUNT on download. On upload, the opaque id is sent on the final MISSION_ACK
- The opaque Id is also streamed continuously in the MISSION_CURRENT message, such that a GCS can detect plan changes.
- The opaque id …

Support mavlink opaque ID

---

src/drivers/sw_crypto/crypto.c

The size input argument for monocypher crypto_xchacha20_ctr should be the plaintext message length.
The promise of the interface is, that the call to encrypt_data updates the ciphertext message length after the call succeeds.
Fix these issues; these have gone unnoticed for a long time since the interface has been only used by logger, and passing the same size for both in and out.

Fix buffer lengths for xchacha20 crypto

---

src/modules/navigator/land.cpp
src/modules/navigator/mission_base.cpp
src/modules/navigator/navigator.h
src/modules/navigator/navigator_main.cpp
src/modules/navigator/rtl.cpp

- cameras have higher chance to get damaged when pointing down (like they do while flying a survey)
- on Holding a survey mission, most users seem to prefer to have the camera pan upwards such that they can look at the surroundings
Introduce set_gimabl_neutral() method that sets `gimbal_manager_set_attitude_s::GIMBAL_MANAGER_FLAGS_NEUTRAL`. Call it on entering RTL and Land flight modes, as well as when in a mission and the next item is Land, or on pausing a mission.
```
Feature: set gimbal to neutral (horizontal) in Landing scenarios and on pausing a Mission
```
SITL tested.

Navigator: add set_gimbal_neutral() logic

---

src/modules/mavlink/mavlink_main.cpp

When looking through the `MAVLINK_MODE_ONBOARD_LOW_BANDWIDTH` MAVLink streams which we heavily rely on I found that some of them are different from other streams or don't meet certain MAVLink payload's requirements.
- Adapt `MAVLINK_MODE_ONBOARD_LOW_BANDWIDTH`
- Add the `MOUNT_ORIENTATION` stream to the normal profile. It's only sent out when the `gimbal` module publishes it and available in almost all other profiles.
```
Add missing MAVLink streams to the `MAVLINK_MODE_ONBOARD_LOW_BANDWIDTH` profile.
```
Ideally we shift towards components requesting the streams they need at the rate required. Until then these adjustments make PX4 more compatible.
- We successfully use this stream profile in many production setups with different payloads for a long time now.

Adapt onbaord low bandwidth MAVLink stream profile

---

src/lib/mixer_module/mixer_module.cpp
src/lib/mixer_module/mixer_module.hpp
src/lib/mixer_module/mixer_module_tests.cpp

When reviewing and testing #22402  I found that some input values to the mixer produce unexpected rounding errors on the out interface. Namely with symmetric differential rover wheel commands the rover would not go completely straight. I narrowed th issue down to the `output_limit_calc` in the mixer module which converts float to uint16_t (which we want to remove anyways). But I found that the issue comes from not very obvious rounding errors in this very old calculation.
I suggest to fix it by adding `0.5f` before letting the machine round down during the datatype cast.
Please review carefully and tell me if there's a preferred method.
```
Bugfix: Rounding error at the output of mixing
```
We'll move to floats for outputs completely which will allow also reverse outputs with negative …

mixer_module: round float value when casting to uint16_t

---

src/modules/navigator/mission_block.cpp

Attitude resets happening when switching to Mission mode with VTOL_Takeoff selected in-air.
Chain:
- Navigator sets the type to SETPOINT_TYPE_TAKEOFF for one sample
- FW position controller goes into _control_mode_current= FW_POSCTRL_MODE_AUTO_TAKEOFF
- FW position controller executes control_auto_takeoff() --> resets integrals [here](https://github.com/PX4/PX4-Autopilot/blob/main/src/modules/fw_pos_control/FixedwingPositionControl.cpp#L1552)
Navigator: Avoid attitude stepoint resets by not going into Takeoff mode if VTOL_Takeoff is selected in-air
```
Bugfix: Navigator: Avoid attitude stepoint resets by not going into Takeoff mode if VTOL_Takeoff is selected in-air.
```
SITL
Reproducible in SITL (start mission with VTOL_Takeoff, change mission in-air, re-upload, start …

Navigator: Avoid attitude stepoint resets by not going into Takeoff mode if VTOL_Takeoff is selected in-air

---

src/drivers/osd/msp_osd/uorb_to_msp.cpp

When having a first look at the OSD code I found that all the modes names are explicitly defined again. This is also done in the corssfire driver and analog OSD for a long time already. I might fix those when I have things ready to test next.
Reuse the existing mode utility `nav_state_names[]` string definitions.
This saves a bit of flash, keeps the mode names up to date and works like expected.
```
Improvement: MSP OSD mode names come from common list
```
I finally assembled the hardware to fly and test the digital FPV system. Here are potato pictures of me switching through the modes. It works great, still only shows the 3 first letters but we can improve that later once I understand all the limitations.

msp_osd: reuse existing mode name conversion

---

test/mavsdk_tests/test_vtol_figure_eight.cpp

When working on PRs I was going nuts about the figure eight test failing more often than not.
wait_until_altitude() checks for absolute altitude being close so checking for 1m below the setpoint can fail if the speedup results in no sample inside the altitude window being checked.
```
CI fix: Make figure-eight test pass consistently
```
Ideally the test could check if the takeoff is done directly instead of comparing altitudes in the first place.
I successfully ran the test 100 times with the altitude thershold 5 times narrower at 10cm instead of 50cm. Without the fix I had it fail locally basically every single time.

Fix Figure Eight CI Test

---

src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessHelicopter.cpp

Backport https://github.com/PX4/PX4-Autopilot/pull/22147 for the point release 1.14.1
```
Bugfix: Helicopter saturation logic leads to rate control integrator not working
```
I cannot test this specifically on 1.14 but it's a low-risk change because handling the extra case was even correct before it became necessary. On 1.14 it is necessary because this one was also necessary: https://github.com/PX4/PX4-Autopilot/pull/21994

[1.14] Fix Helicopter saturation logic

---

src/modules/uxrce_dds_client/dds_topics.yaml

Export estimator_status_flags to ROS 2.
Use case: PX4 ROS 2 navigation interface requires feedback from PX4 when requesting measurement updates.

dds_topics: export estimator_status_flags

---

ROMFS/px4fmu_common/init.d/rcS
src/drivers/px4io/px4io.cpp

Backport of https://github.com/PX4/PX4-Autopilot/pull/22368

1.14 backport - Pr ver px4io check backport

---

src/modules/mavlink/mavlink_receiver.cpp
src/modules/mavlink/mavlink_receiver.h

Implements [mavlink NAMED_VALUE_INT](https://mavlink.io/en/messages/common.html#NAMED_VALUE_INT)
- Tested in flight

mavlink: Handle NAMED_VALUE_INT

---

src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp

- This fixes the force call on SensorSelectionUpdate
- In contrary to the rest of the codebase, this method also takes a timestamp: When you call SensorSelectionUpdate(true), time_now_us is actually set to 1 and force stays false, as this is the default value for in the method.
- Add time_now_us always when calling SensorSelectionUpdate in VehicleAngularVelocity 
```
Feature/Bugfix Fix force SensorSelectionUpdate in VehicleAngularVelocity
New parameter:
Documentation:
```
-
-
-

VehicleAngularVelocity: Fix force SensorSelectionUpdate

---

src/drivers/distance_sensor/lightware_laser_i2c/lightware_laser_i2c.cpp
src/drivers/distance_sensor/lightware_laser_i2c/parameters.c

Adds a parameter `SF1XX_MODE` that controls if the SF1xx distance sensor will disable automatically in forward flight after a commander transition.
Tested in hardware via NSH commands `commander transition` and `param set`.
<details>
<summary>Example Behavior</summary>
```
nsh> lightware_laser_i2c start -X
lightware_laser_i2c #0 on I2C bus 1 (external) address 0x66 rotation 25
nsh> commander transition
INFO  [lightware_laser_i2c] Emission Control: disabling sensor!
nsh> commander transition
INFO  [lightware_laser_i2c] Emission Control: enabling sensor!
nsh> commander transition
INFO  [lightware_laser_i2c] Emission Control: disabling sensor!
nsh> param set SF1XX_MODE 1
+ SF1XX_MODE: curr: 2 -> new: 1
INFO  [lightware_laser_i2c] Emission Control: enabling sensor!
nsh> param set SF1XX_MODE 0 …
```

Optionally disable SF1xx sensor in forward flight

---

src/systemcmds/i2c_launcher/Kconfig

```
warning: the menuconfig symbol USER_I2C_LAUNCHER (defined at src/systemcmds/i2c_launcher/Kconfig:7) has no prompt
```

systemcmds/i2c_launcher: fix USER_I2C_LAUNCHER warning

---

src/lib/timesync/Timesync.cpp
src/lib/timesync/Timesync.hpp

- double required max consecutive counts
- don't continuously complain about round trip time (RTT) unless there's been at least one acceptable round trip (latency < 100 ms)

lib/timesync: relax warnings

---

src/modules/fw_pos_control/FixedwingPositionControl.cpp

This is the only if/else condition that didn't update _control_mode_current. Probably we should re-write this method to make it more robust.
It had no effect because we also set _pos_sp_triplet.current.type = position_setpoint_s::SETPOINT_TYPE_POSITION, which then made it enter another conditional.

FW Position Control: fix setting of _control_mode_current to AUTO in VTOL land

---

ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator

`SIM_GZ_HOME_ALT` was uncorrectly set.
Increase documentation of Gazebo simulation startup

[rc.simulator] fix PX4_HOME_ALT and cleanup

---

Tools/px_process_events.py

After merging https://github.com/PX4/PX4-Autopilot/pull/22551 I was informed by @dagar that the additional CI command `make extract_events` which only runs on the main branch fails 😬
I actually tested an empty base path but in between testing and pushing I changed the `base-path` parameter to a single string instead of a list, forgot to adjust the default and didn't test again. Sorry for that.
Adapt parameter to return an empty string instead of an empty string in a list after changing it to a single argument instead of multiple.
```
Bugfix: CI events generation base path mistake
```
I ran the command locally and verified the path was processed like before the change.

px_process_events: fix empty base path being a list

---

src/modules/sensors/vehicle_gps_position/gps_blending.cpp
src/modules/sensors/vehicle_gps_position/gps_blending.hpp
src/modules/sensors/vehicle_gps_position/gps_blending_test.cpp

The current implementation allows continuous instance switching based on the number of satellites as soon as the primary GNSS receiver had a timeout. A timeout could occur just after boot and it shouldn't allow switching once the primary receiver is regained.
Only allow switching while the primary GNSS receiver is unavailable. Otherwise, force back the selection.
In addition to that, I also took the opportunity to allow switching if the primary GNSS lost its 3D fix. I've seen several incidents where the antenna disconnected but no switch the the secondary GNSS occurred because we're solely relying on data timeout.
```
Fix continuous GNSS instance switch. Add fallback if fix is lost.
```
We should refactor the GNSS selector completely. …

Multi GNSS fallback improvements

---

src/modules/fw_autotune_attitude_control/fw_autotune_attitude_control.cpp
src/modules/mc_autotune_attitude_control/mc_autotune_attitude_control.cpp

Autotune cannot start if `xx_AT_START` is initially set to 1 (because there is no param change).
Reset parameter when module is started.
This is just a quick patch to fix the symptom, but the correct solution would be to handle the mavlink message directly in the autotune module instead of communicating via a parameter.
SITL tests

Autotune: reset param on start

---

platforms/common/include/px4_platform_common/shutdown.h
platforms/common/shutdown.cpp
platforms/nuttx/src/px4/common/cdc_acm_check.cpp
platforms/nuttx/src/px4/nxp/imxrt/board_reset/board_reset.cpp
platforms/nuttx/src/px4/nxp/kinetis/board_reset/board_reset.cpp
platforms/nuttx/src/px4/nxp/s32k1xx/board_reset/board_reset.cpp
platforms/nuttx/src/px4/nxp/s32k3xx/board_reset/board_reset.cpp
platforms/nuttx/src/px4/rpi/rpi_common/board_reset/board_reset.cpp
platforms/nuttx/src/px4/stm/stm32_common/board_reset/board_reset.cpp
src/modules/commander/Commander.cpp
src/modules/commander/worker_thread.cpp
src/systemcmds/netman/netman.cpp
src/systemcmds/reboot/reboot.cpp

Extend px4_reboot_request with enum to add REBOOT_TO_ISP request for devices with a bootrom to boot into the rom bootloader.

reboot: Add reboot to ISP option

---

boards/px4/fmu-v6xrt/init/rc.board_defaults

During a FAULT investigation of PIXHAWK 6X-RT, an error was found in DMESG.
Parameter "SYS_USE_IO" is missing.
nsh> dmesg
HW arch: PX4_FMU_V6XRT
HW type: V6XRT000000
HW version: 0x000
HW revision: 0x000
PX4 git-hash: 6be8cbe43966d57630e6743e163307c216444be7
PX4 version: 1.15.0 40 (17760320)
PX4 git-branch: main
OS: NuttX
OS version: Release 11.0.0 (184549631)
OS git-hash: 1e3aaefc60a18838dc696e8f0f335d8c989f35cc
Build datetime: Dec 22 2023 11:18:10
Build uri: localhost
Build variant: default
Toolchain: GNU GCC, 9.3.1 20200408 (release)
PX4GUID: 000900000000000000008292b37f2718600e
MCU: i.MX RT1170 rB0, rev. 0
INFO  [param] selected parameter default file /fs/mtd_params
INFO  [param] importing from '/fs/mtd_params'
INFO  [parameters] BSON document size 1288 bytes, decoded 1288 bytes …

fmu-v6xrt: Delete a parameter setting that does not exist

---

src/modules/mavlink/mavlink_main.cpp

While checking the operation of PIXHAWK 6X-RT, only one barometric pressure sensor was shown in the MAVLINK inspector.
Add a second barometric sensor message to the MAVLINK message transmission list.
None
None
1. No build errors.      RESULT: OK
2. No errors when running on FC.    RESULT: OK
AFTER
BEFORE

mavlink: Add a second barometric sensor message

---

boards/px4/fmu-v6xrt/src/board_config.h
platforms/nuttx/src/px4/nxp/imxrt/board_reset/CMakeLists.txt
platforms/nuttx/src/px4/nxp/imxrt/board_reset/board_reset.cpp

Add -i option to reboot command and reboot into the rom ISP 1st stage bootloader.
Allows to flash px4 bootloader from USB using ISP bootloader.

V6X-RT Add reboot into ISP (1st stage bootloader)

---

boards/px4/fmu-v6xrt/init/rc.board_sensors

During a FAULT investigation of PIXHAWK 6X-RT, the activation of the external barometric sensor was affected by a config parameter.
The external barometric pressure sensor of PIXHAWK 6X was not affected by the config parameter.
Make the configuration parameter determination unaffected.
None
None
1. Confirm that it is started by DMESG.     Result: OK
DMESG Output Result:
bmm150 #0 on I2C bus 3 address 0x10
ist8310 #0 on I2C bus 1 (external) address 0xE rotation 10
bmp388 #0 on I2C bus 3 address 0x77
bmp388 #1 on I2C bus 2 (external) address 0x76
WARN  [SPI_I2C] Already running on bus 1
WARN  [vehicle_angular_velocity] no gyro selected, using sensor_gyro_fifo:0 2949130
ekf2 [498:237]
Board mavlink: /etc/init.d/rc.board_mavlink
Starting Main GPS on /dev/ttyS1

fmu-v6xrt: Move external BMP388 outside of config parameter determination

---

src/modules/control_allocator/ControlAllocation/ControlAllocation.hpp

Just a small typo fix for the function description of `ControlAllocation::getControlSetPoint`.

[control_allocation] small typo fix in member function description

---

msg/ModeCompleted.msg

I added a little comment where a person can see the possible value of nav_state

Added comment in the ModeCompleted.msg

---

src/modules/uxrce_dds_client/dds_topics.yaml
test/ros_tests/config.json

This enables integration tests for the external navigation ros2 interface: https://github.com/Auterion/px4-ros2-interface-lib/pull/5
Adds `estimator_status_flags` to dds published topics, required for these integration tests.

Integration tests for external navigation interface

---

src/modules/sensors/vehicle_imu/VehicleIMU.cpp

The IMU topic is not zeroed, and the clipping information was not copied, so this field ended up being garbage.

sensors: fix gyro clipping publication

---

src/modules/fw_pos_control/FixedwingPositionControl.cpp
src/modules/fw_pos_control/FixedwingPositionControl.hpp

This PR adds an additional FW path navigation state, which uses position, tangent and optionally curvature to do path tracking.
Currently this was done by overriding `control_auto_position`, but since it is using more of the derivative setpoints, we thought it should be separated out as a separate mode
The behavior is as the following.
In offboard,
- When velocity setpoints are available set FW state as `FW_POSCTRL_MODE_AUTO_PATH`
- When only position setpoints are available, set FW state as `FW_POSCTRL_MODE_AUTO`, which would end up using `control_auto_position`
- Tested in SITL Gazebo
-  with normal mission mode
-  with offboard path tracking
- Offboard seems to be also completely broken, so fixed it along the way

Add Fixedwing path following as a separate controller state

---

msg/VehicleCommand.msg
src/modules/ekf2/EKF/common.h
src/modules/ekf2/EKF/ekf.cpp
src/modules/ekf2/EKF/ekf.h
src/modules/ekf2/EKF/ekf_helper.cpp
src/modules/ekf2/EKF2.cpp

Added support for [MAV_CMD_EXTERNAL_POSITION_ESTIMATE](https://mavlink.io/en/messages/common.html#MAV_CMD_EXTERNAL_POSITION_ESTIMATE)
Note: The transmission_time field which is part of the mavlink message is currently not used.
```
Support MAV_CMD_EXTERNAL_POSITION_ESTIMATE which can be used to reset the estimator position state to an external measurement, e.g. an operator using an FPV camera to detect landmarks.
```
Plot showing how the reset affects only horizontal position, but not the velocity states:

Added support to reset vehicle position based on external position

---

src/modules/vtol_att_control/vtol_type.cpp
src/modules/vtol_att_control/vtol_type.h

https://github.com/PX4/PX4-Autopilot/pull/22140 brought in the scaling of the transition airspeed with the currently set vehicle weight. It though did that by limiting the minimum transition airspeed to the minimum airspeed in fixed-wing mode, `FW_AIRSPD_MIN`, which can lead to transitions not happening because `FW_AIRSPD_MIN` is set considerably higher than `VT_ARSP_TRANS`, and  the transition is tuned for `VT_ARSP_TRANS`.
I don't see the need to check `FW_AIRSPD_MIN` in the transition logic, and here propose to remove it, and instead scale the `VT_ARSP_TRANS` with the weight factor.  
```
Bugfix: VTOL: change transition airspeed threshold: only look at VT_ARSP_TRANS, not  FW_AIRSPD_MIN
```

VTOL: change transition airspeed threshold: only look at VT_ARSP_TRANS, not FW_AIRSPD_MIN

---

src/modules/ekf2/EKF2.cpp
src/modules/ekf2/EKF2.hpp

- these served their purpose, but are no longer useful
- still worth keeping the IMU subscription missed perf count to catch scheduling issues

ekf2: remove sample subscription missed perf counters

---

ROMFS/px4fmu_common/init.d-posix/airframes/1041_gazebo-classic_tailsitter
src/modules/mc_att_control/mc_att_control_main.cpp
src/modules/vtol_att_control/tailsitter.cpp
src/modules/vtol_att_control/tailsitter.h

Fixes https://github.com/PX4/PX4-Autopilot/issues/22316
Tailsitter transitions in Stabilized are currently handed the following way:
- transition to FW: user has to manually pitch down until within 5° of the max tilt in hover, MPC_MAN_TILT_MAX
- transition to MC: the pitch setpoint immediately changes to the hover interpretation, meaning that if the user doesn't pitch down while doing the transition then the vehicle will immediately try to pitch up to 0° hover pitch (so a 90° step)
Do the same pitch ramp as in all altitude controlled modes also in Stabilized. 
```
Feature: VTOL Tailsitter: add automatic pitch ramps also in Stabilized mode
```
Flight tested. 
Screen recording of a SITL flight with the …

VTOL Tailsitter: add automatic pitch ramps also in Stabilized mode

---

src/modules/navigator/MissionFeasibility/FeasibilityChecker.cpp
src/modules/navigator/MissionFeasibility/FeasibilityChecker.hpp

This check gave a warning when one or more mission items were below the Home altitude. As it is a valid use case to plan missions below Home, those warnings were too often seen as a inconvenience and are thus removed here.
```
Feature: MissionFeasibilityChecker: remove below home check
```
fyi @cmic0

MissionFeasibilityChecker: remove below home check

---

src/modules/fw_pos_control/FixedwingPositionControl.cpp
src/modules/fw_pos_control/FixedwingPositionControl.hpp
src/modules/fw_pos_control/fw_path_navigation_params.c

Fixes https://github.com/PX4/PX4-Autopilot/issues/22540.
TL;DR: PX4 v1.12 and v1.13 contained a bug that resulted in FW_T_I_GAIN_THR and FW_T_THR_DAMP having a much lower effect. This bug is fixed now, resulting in these params to have much stronger effects on the controller, which can lead to controller instability. 
- reduce the defaults
- introduce mechanism to warn user if gains are high    
- The params `FW_T_I_GAIN_THR` and `FW_T_THR_DAMP` have a much stronger effect  in PX4 v1.14 then before, and therefore we warn the user if the current values are above normally reasonable values, unless they have acknowledged  knowing about the change by setting the new param `FW_T_CHNG_ACK`.
```
Feature: FW TECS: Warn if throttle gains (that have changed effect with this …
```

TECS throttle gains default reduction and transition values from previous PX4 version

---

src/lib/matrix/matrix/Matrix.hpp
src/modules/ekf2/CMakeLists.txt

Makes the ekf2 verbose debug print status a bit easier to see.

Matrix: adjust printing for symmetric P (lower triangular only)

---

boards/px4/fmu-v6xrt/init/rc.board_sensors

While investigating the cause of a FAULT on PIXHAWK 6X-RT, we discovered that the UART device name specification was different from WIKI.
Match the file description to the WIKI.
None
None
None
None

fmu-v6xrt: Change the description to the device name in the WIKI

---

boards/px4/fmu-v6xrt/firmware.prototype

When uploading PIXHAWK6X-RT, the write flash size percentage was different.
Change the flash size of PIXHAWK6X-RT to "4063232".
None
None
The percentage of flash size at build time and the percentage of flash at upload time should be the same.　　Result: OK
AFTER
BEFORE

fmu-v6xrt: Change image size

---

src/modules/fw_rate_control/FixedwingRateControl.cpp

Everything operation was duplicated for roll, pitch and yaw. Even if it might be slightly more efficient at runtime (most likely not noticeable), having it done using matrix operations is cleaner.
Group every operation in a Vector3f object.
SITL tests

FW rate control: make use of Vector3f more intensively

---

src/modules/vtol_att_control/vtol_type.cpp
src/modules/vtol_att_control/vtol_type.h

When an altitude reset happens a false bad descend quadchute event can happen since the quadchute reference altitude state does not take into account the reset.
Apply the delta altitude to the quadchute reference altitude.
```
Bugfix: 
Fix chance of a false bad descend quadchute event when there is an altitude reset.
```

Bad descend quadchute: Take altitude reset into account

---

src/modules/ekf2/EKF2.cpp

When GPS fusion is enabled, the ev_yaw_control disables yaw fusion if the ev_sample position frame is not in the LocalNED frame. But if the EV message doesn't contain a position component, the position frame isn't set properly which disables attitude fusion.
This now enables EV messages containing only an attitude to be fused.
Always convert external vision odometry position and velocity reference frame enums, regardless if position and velocity components are present.

ev_odom: fuse ev yaw regardless of ev position 

---

msg/SensorGnssRelative.msg
src/drivers/uavcan/CMakeLists.txt
src/drivers/uavcan/Kconfig
src/drivers/uavcan/sensors/gnss.cpp
src/drivers/uavcan/sensors/gnss.hpp
src/drivers/uavcan/sensors/gnss_relative.cpp
src/drivers/uavcan/sensors/gnss_relative.hpp
src/drivers/uavcan/sensors/sensor_bridge.cpp
src/drivers/uavcan/uavcan_params.c
src/drivers/uavcannode/Publishers/GnssFix2.hpp

This PR hacks noise, jamming, and spoofing data into the dronecan gps fix2 message. This has been a big complaint about CAN GPS not providing this info. We were already using ecef_position_velocity for heading over the past two years. 
ARK Jetson, ARKV6X, ARK GPS
https://review.px4.io/plot_app?log=4cd6e706-4e15-42ee-aedd-95f5792fa944
Moving base setup with heading.
https://review.px4.io/plot_app?log=dd1198a5-d0ef-48ce-a361-ca0dfe8edd9c - sensor_gnns_relative heading is in degrees
https://review.px4.io/plot_app?log=de32ab72-e175-4ea4-8d6b-a76fae956b7e

dronecan: gps add noise, jamming, and spoofing data

---

src/modules/navigator/navigator.h
src/modules/navigator/navigator_main.cpp

When handling multiple commands, it could happen that the first command updates _reposition_triplet. Normally this would then get handled after getting the mode change from commander through vehicle_status. But if the next command is handled before an update from commander, it could overwrite the triplet.
This patch ensures that navigator waits for an update from commander (and therefore process the _reposition_triplet) before handling the next command.
This happened specifically when pressing 'Pause' from QGC during a mission. QGC sends VEHICLE_CMD_DO_REPOSITION twice, first for pausing, then changing the altitude.
The result was that the vehicle would not stop at the current location but continue to the next mission waypoint and stop there.
Fixes …

fix navigator: prevent race condition when receiving multiple commands at once

---

msg/CMakeLists.txt
msg/SensorAirflow.msg
src/drivers/wind_sensor/Kconfig
src/drivers/wind_sensor/ft_technologies/CMakeLists.txt
src/drivers/wind_sensor/ft_technologies/Kconfig
src/drivers/wind_sensor/ft_technologies/ft7_technologies.cpp
src/drivers/wind_sensor/ft_technologies/ft7_technologies.hpp
src/drivers/wind_sensor/ft_technologies/ft7_technologies_main.cpp
src/drivers/wind_sensor/ft_technologies/module.yaml
src/modules/logger/logged_topics.cpp

This brings support to communicate with an ultrasonic wind sensor, produced by FT technologies: FT742. It provides measurements about the speed and direction of the airflow flowing through its cavity. Its generally used when stationary, and thus will measure the wind conditions, however, there are use cases for mounting on a multicopter to do inspection of the airflow produced by wind turbines. [Usecases](https://fttechnologies.com/case-studies/)
The sensor communicates over RS485, and thus a  RS485 to UART signal transfer module is needed to communicate with the sensor, as seen in the below image
Part of a larger plan to bring the measurements into the EKF to improved its wind estimates, and hence getting the sensor in Gazebo @dagar : 
https://github.com/gazebosim/gz-sim/pull/2256
The …

FT7 series Wind/Airflow sensor Driver

---

src/lib/battery/module.yaml

The ARK Jetson PAB Carrier allows for 3 power module inputs. I had already updated PX4 to allow for the three INA226 drivers to run, but I forgot to update the battery library to allow for 3 instances.

lib: battery allow for 3 instances

---

ROMFS/px4fmu_common/init.d/rc.thermal_cal
src/modules/temperature_compensation/temperature_calibration/mag.cpp

This fix if only `TC_M_ENABLE` is enabled but not any other parameter, temperature_compensation  will not start.
It also renames `TC_A_ENABLE` to `TC_M_ENABLE` inside `temperature_calibration/mag.cpp`
@mcsauder can you have a look if this makes sense?

Minor fixes in magnetometer temperature compensation

---

src/lib/parameters/px4params/srcparser.py
src/modules/ekf2/ekf2_params.c

QGC was converting the `g` to `oz` as `g` is also used for grams.

ekf2-grav: rename g-force unit to g0 to avoid confusion with grams

---

src/lib/system_identification/signal_generator.hpp

Ref: https://www.recordingblogs.com/wiki/sine-sweep
To be used in 
- https://github.com/PX4/PX4-Autopilot/pull/22666 (auto-tune Fixed-wing)
- https://github.com/PX4/PX4-Autopilot/pull/21857 (auto-tune MC)
Linear sweep:
Log sweep:

sys-id: implement linear and log sine sweeps

---

src/modules/control_allocator/ControlAllocation/CMakeLists.txt
src/modules/control_allocator/ControlAllocation/ControlAllocationSequentialDesaturationTest.cpp

Unit tests for ControlAllocationSequentialDesaturation. No code changes are made to any existing library, this only adds unit tests. The unit tests serve 2 purposes: 1) help ensure that expected functionality remains the same and 2) documents and demonstrates (through examples) the desaturation algorithm.

Control Allocation Sequential Desaturation unit tests

---

src/modules/temperature_compensation/TemperatureCompensationModule.cpp

If `set_sensor_id_mag` is not used for mag compensation, compensating messages will not be published.

temperature_compensation: use set_sensor_id_mag for Mag

---

src/modules/logger/logged_topics.cpp

For VTOLs the high rate logging isn't properly enabled on the FW topics. Here I propose to change that. Downside: the logs get very fast very big (seems to be around 7MB/min from a quick bench test), maybe we have to find a compromise.

Logging: high rate logging: add actuator_servos and log all instances of thrust/torque setpoint

---

src/drivers/barometer/invensense/icp201xx/ICP201XX.cpp

Fixes wrong altitude reporting trough barometer with the ICP201XX B2 version sensor by InvenSense.

ICP201: increase startup delay with B2 version

---

ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator

Hi! I am running simulations on the system which does not supports Ogre 2.x (actually it's Parallels over Apple Silicon which has a limited support for the newest OpengGL). This can be fixed by downgrading to earlier Ogre version [as described](https://gazebosim.org/docs/garden/troubleshooting#ubuntu) in Gazebo documentation.
We probably have to mention this workaround in documentation.
Allow running simulations on Gazebo Garden for systems which do not support Ogre 2.x.
In some scenarios (like co-simulation or custom rendering with Unreal/Unity as in my case) it is beneficial to have a simplified renderer at the machine with older OpenGL version running SITL+Gazebo.
Add `--render-engine` argument if `PX4_GZ_SIM_RENDER_ENGINE` environment variable is set.
For example:
```shell …
```

Allow user to specify Gazebo render engine in simulations

---

src/modules/dataman/dataman.cpp

Variable definitions are defined in front of processes that are not used.
Move the variable definition to a process that uses it.
None.
None.
The system was confirmed to work correctly in SIH.
None.

dataman: Move before using variable definitions

---

src/modules/commander/HealthAndArmingChecks/checks/flightTimeCheck.cpp

The order in which messages and events are issued is different from others
Change the order of messages and events.
None
None
Confirmed that messages and events are notified.
None

check: Changing the order of messages and events

---

msg/Mission.msg
src/modules/dataman/dataman.cpp
src/modules/dataman/dataman.h
src/modules/mavlink/mavlink_mission.cpp
src/modules/mavlink/mavlink_mission.h
src/modules/navigator/geofence.cpp
src/modules/navigator/geofence.h
src/modules/navigator/mission.cpp
src/modules/navigator/mission_base.cpp
src/modules/navigator/mission_feasibility_checker.cpp
src/modules/navigator/navigation.h
src/modules/navigator/rtl.cpp
src/modules/navigator/rtl_direct_mission_land.cpp
src/modules/navigator/rtl_mission_fast.cpp
src/modules/navigator/rtl_mission_fast_reverse.cpp
src/systemcmds/tests/test_dataman.cpp

If there is an error during uploading of the rally points or geofence, the old fence points get overwritten and are not accessible anymore.
- Extend dataman to have double storage for rally points and geofence the same way as is already done for missions
- On upload write the uploaded points t othe inactive slot and switch at the end when upload was successful.
```
Feature: Enable double storage slots for rally points and geofence
```
- Tested in SITL while observing the mission topic when uploading rally points and missions.

Double storage for rally points and geofence

---

src/drivers/power_monitor/ina238/ina238.cpp
src/drivers/power_monitor/ina238/ina238.h
src/drivers/power_monitor/ina238/ina238_registers.hpp

In several log files (about 3 to this point) we have seen what looks like the shunt calibration being lost by the current sensor.
The issue was apparent by the fact that the current reading did not make any sense for the specific vehicle and also we verified by doing the maths, that the reported current matches the case when the shunt calibration was reset to default value.
It's not quite clear yet what is actually causing the reset, investigations are still ongoing.
```
INA238: re-apply sensor shunt calibration if readback is not correct
```

ina238: set shunt calibration to desired value if readback is incorrect

---

src/lib/matrix/matrix/AxisAngle.hpp
src/lib/matrix/matrix/Dcm.hpp
src/lib/matrix/matrix/Dcm2.hpp
src/lib/matrix/matrix/Dual.hpp
src/lib/matrix/matrix/Euler.hpp
src/lib/matrix/matrix/LeastSquaresSolver.hpp
src/lib/matrix/matrix/Matrix.hpp
src/lib/matrix/matrix/PseudoInverse.hpp
src/lib/matrix/matrix/Quaternion.hpp
src/lib/matrix/matrix/Scalar.hpp
src/lib/matrix/matrix/Slice.hpp
src/lib/matrix/matrix/SparseVector.hpp
src/lib/matrix/matrix/SquareMatrix.hpp
src/lib/matrix/matrix/Vector.hpp
src/lib/matrix/matrix/Vector2.hpp
src/lib/matrix/matrix/Vector3.hpp
src/lib/matrix/matrix/Vector4.hpp
src/lib/matrix/matrix/filter.hpp
src/lib/matrix/matrix/helper_functions.hpp
src/lib/matrix/matrix/integration.hpp
src/lib/matrix/matrix/math.hpp
src/lib/matrix/test/MatrixDcm2Test.cpp
src/lib/matrix/test/MatrixFilterTest.cpp

When @jwidauer helped me investigating for #22574 he had many suggestions to improve the matrix library.
Here I sorted out some low-hanging fruits he added in the code and I did some small additions.
- Include chain, don't include "math.h" everywhere and generate circular dependencies
- Slice templated on Matrix const and non-const case -> `SliceT`, `ConstSlice`
- Some simplifications to not repeat the type of the return value, using Vector3 where it makes sense, ...
```
Cleanup: matrix library improvements
```
Build and unit tests still work

Matrix library improvements

---

src/modules/logger/logger.cpp

When the CPU load monitor is started while already running, then the idle thread last_times[0] is reset to the last 1 second, 
rather than since when the CPU load monitor was last started. This can happen if the calls to `cpuload_monitor_start()` and `cpuload_monitor_stop()` are unbalanced. In my test case, the cpuload monitor is never disabled.
This results in the idle thread having a much lower CPU load, with the remaining CPU time being wrongly attributed as scheduler load. The remaining threads are not impacted, since their last_times[i] is reset to zero for every sample init.
This causes the preflight and postflight cpuload measurements to wrongly show a >30% scheduler load, which raises alarms in our monitoring suite. 
See #22655.
Fix the unbalanced calls in `logger.cpp`.
~~The …

cpuload: Workaround for wrong idle thread load

---

boards/px4/fmu-v6x/nuttx-config/include/board.h

When flow control is used together with DMA, we need to add a pulldown to CTS. Without it, it assumes flow control and gets stuck when CTS is not connected.
Follow up to:
https://github.com/PX4/PX4-Autopilot/pull/20974
Same as:
https://github.com/PX4/PX4-Autopilot/pull/21540
Needs backporting to v.1.14.

fmu-6x: fix Telem2 without flow control

---

boards/px4/fmu-v6x/nuttx-config/include/board.h

Backport of #22670 
@dagar sadly this didn't make the cut for v1.14.1.

[BACKPORT v1.14] fmu-6x: fix Telem2 without flow control

---

src/lib/mixer_module/functions/FunctionActuatorSet.hpp
src/modules/commander/Commander.cpp

MAVLink spec: https://mavlink.io/en/messages/common.html#MAV_CMD_DO_SET_ACTUATOR
Previously, a command was overwriting all other indexes.

fix FunctionActuatorSet: if a param is set to NaN, it should be ignored

---

src/lib/mixer_module/functions/FunctionActuatorSet.hpp
src/modules/commander/Commander.cpp

From https://github.com/PX4/PX4-Autopilot/pull/22711

[BACKPORT 1.14] fix FunctionActuatorSet: if a param is set to NaN, it should be ignored

---

src/modules/simulation/gz_bridge/GZMixingInterfaceWheel.cpp

I realized that the joint state publisher [plugin](https://github.com/gazebosim/gz-sim/blob/gz-sim8/src/systems/joint_state_publisher/JointStatePublisher.cc) from GZ used in the following PR #22402 publishes in rad/s instead of RPM, which means I can remove the conversion from RPM to rad/s. 
https://github.com/gazebosim/gz-sim/blob/18c535f4bf360132bb8825321e3e8a2bc8ee1947/src/systems/joint_state_publisher/JointStatePublisher.cc#L263-L285

GZ Sim: Bugfix removed conversion from rpm to rad s

---

ROMFS/px4fmu_common/init.d-posix/rcS
src/modules/simulation/battery_simulator/battery_simulator_params.c

I would like to run a more complex battery simulation in a standalone application. This can currently be achieved by stopping PX4's internal battery simulator after a boot, and then sending [BATTERY_STATUS](https://mavlink.io/en/messages/common.html#BATTERY_STATUS) MAVLink messages.
This PR proposes a parameter that controls the startup of the internal battery simulator. When disabling the battery simulator, it removes the extra step necessary after each boot to stop the battery simulator. But it also produces consistent measurements for PX4, since there will then only be the battery messages coming in through MAVLink.
- New parameter `SIM_BAT_ENABLE` that defaults to 1, but when set to 0 it won't start the internal battery simulator
```
Feature Parameter for …
```

bat_sim: parameter for disabling battery simulator

---

src/drivers/uavcannode/Kconfig
src/drivers/uavcannode/Publishers/IndicatedAirspeed.hpp
src/drivers/uavcannode/UavcanNode.cpp

Signed-off-by: dirksavage88 <dirksavage88@gmail.com>
Add indicated airspeed in order to use dronecan airspeed sensors in uavcannode. 
Sensors by default only publish to raw air data (differential pressure, static press., static temp). Adding indicated airspeed and thus having the sensors module on a dronecan node allows distributed airspeed sensor measurements. 
Existing solutions: problematic i2c cable runs, comm errors plagued these sensors in the past: #6314 
Uavcannode support can help pave a path towards #12237
True airspeed, sideslip, and AoA can also be brought in as they are in the dsdl, however I'm not sure if they should be under separate publishers, as indicated AS publisher is required to calibrate and use the airspeed sensor at a minimum.

Add indicated airspeed to uavcannode

---

src/modules/mc_att_control/mc_att_control_main.cpp

Currently in the MC attitude controller, in Stabilized mode, the generated attitude setpoints are copied inside the module to where they are used (plus also published over uORB). 
Here I propose to remove this internal copying and only publish it to the uorb topic, which is subscribed to in the same module.
This "should" have no behavior change - unless we deem the passing of the attitude setpoint over uorb less stable and want to keep the internal copying of it through `setAttitudeSetpoint()`. I propose this change to be able to remove the "if(vtol_transition)" and keep the controller flows as consistent as possible. 
Context: https://github.com/PX4/PX4-Autopilot/pull/22584#discussion_r1453376530
FYI @MaEtUgR

mc_att_control: remove direct setting of att sp in Stabilized

---

src/lib/parameters/flashparams/flashparams.cpp
src/lib/parameters/param_translation.cpp
src/lib/parameters/param_translation.h
src/lib/parameters/param_translation_unit_tests.cpp
src/lib/parameters/parameters.cpp

`WARN  [parameters] ignoring unrecognised parameter XXX`  when we do param_set() in the param translation. 
Return early in param_import_callback() with 1 if we do a param_set in the param translation.
```
Improvement: Param translation: enable the use of param_set() in the translation
```

params: change return type of param_modify_on_import to enum

---

src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp

@RomanBapst reported that on a frame with brittle landing gear it's crucial to have zero speed at touch down. Since the frame is only ever influenced manually when nudging we discussed it could be made more idiot-proof in a way that the horizontal nudging is limited in speed when you get close to the ground.
If the ground distance estimate is valid then during nudging the speed gets limited the closer the vehicle flies to the ground.
The logic is to not allow horizontal nudging below 50cm altitude above ground and above that allow half the speed in m/s of the altitude in meters e.g.
|Altitude|Horizontal speed with full stick input|
|-|-|
|0m|0m/s|
|0.5m|0m/s|
|1.5m|0.5m/s|
|2.5m|1m/s|
|3.5m|1.5m/s|
|4.5m|2m/s|
```
Feature: Limit land nudging horizontal speed close to the ground
```
To …

FlightTaskAuto: Limit land nudging horizontal speed close to the ground

---

src/lib/parameters/param_translation.cpp

Currently the translation of RWTO_L1_PERIOD, FW_L1_R_SLEW_MAX and FW_L1_PERIOD is not applied as the function returns before that. Was an oversight in https://github.com/PX4/PX4-Autopilot/pull/19629.

param translation: fix too early return

---

boards/px4/fmu-v6x/init/rc.board_sensors

I noticed that the system_power topic was not published if the ADS1115 driver is running on a v6x board.

v6x board_sensors: publish system_power if ADC_ADS1115_EN is enabled

---

src/drivers/distance_sensor/cm8jl65/CM8JL65.cpp
src/drivers/pwm_out/PWMOut.cpp
src/drivers/px4io/px4io.cpp

1. When working with PWM configurations I found that the output of what gets changed with the automatic servo/motor configuration is interchanged:
2. The Lanbao distance sensor is according to shops and even our docs an infrared sensor but the type was set to a laser.
https://docs.px4.io/main/en/sensor/cm8jl65_ir_distance_sensor.html
1. I swapped the outputs and made the channel number 1 based to avoid confusion with the UI.
2. Declared it IR.
```
Maintenance: Correct automatic servo/motor PWM configuration console output
Fix: Report Lanbao distance sensor as infrared instead of laser
```

Correct automatic servo/motor PWM configuration console output

---

src/modules/ekf2/EKF/python/tuning_tools/baro_static_pressure_compensation/baro_static_pressure_compensation_tuning.py
src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp

1G is calculated at 9.81.
Floating values are valid to 7 decimal places.
I would prefer to use the most accurate value possible.
Make 9.81 the scientific calculated value of 9.80665.
None
None
Perform SIH on PIXHAWK6X-RT.
SIH confirmed that the flight can be flown on the flight plan.
NOT HARD FALUT.
None

Global: Change 1G to a more accurate value

---

src/modules/navigator/mission_block.cpp
src/modules/navigator/mission_block.h
src/modules/navigator/navigation.h
src/modules/navigator/rtl.cpp
src/modules/navigator/rtl.h
src/modules/navigator/rtl_direct.cpp
src/modules/navigator/rtl_direct.h
src/modules/navigator/rtl_params.c

VTOLs yawing to the home position heading when descending in hover during RTL instead of weather-vaning.
Continue with what was started in https://github.com/PX4/PX4-Autopilot/pull/22532: 
- remove `RTL_HDG_MD` (necessity of it hasn't been proven and it interferes with the here proposed solution)
- only set heading setpoint in `Navigator::RTL` once above landing point, or when RTL is triggered close to it
- never set a heading setpoint in the RTL if weather vane is enabled
```
Bugfix: Fix weather vane in RTL
Feature: Make RTL behavior more deterministic by removing the parameter RTL_HDG_MD.
```
SITL tested. 
This is how a normal RTL with a MC looks like (the behavior doesn't change with this PR):
- climb while keeping heading
- return over landing point without a …

RTL: change when to set a heading setpoint, generally leave it up to executer

---

ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator
src/modules/simulation/gz_bridge/GZBridge.cpp
src/modules/simulation/gz_bridge/GZBridge.hpp
src/modules/simulation/gz_bridge/parameters.c

This addition allows one to accurately position a vehicle based real life coordinates provided in a Gazebo world sdf file. It requires  the use of the `<spherical_coordinates> tag in world sdf files (as well as the navsat plugin) and the use of 
```
<sensor name="navsat_sensor" type="navsat">
<always_on>1</always_on>
<update_rate>30</update_rate>
</sensor>
```
as a sensor in the model sdf file. 
The screenshot below shows the center of Turin and the respective position of an x500 on QGC.

Enable navsat plugin for accurate positioning of real life maps in Gazebo

---

ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator
ROMFS/px4fmu_common/init.d-posix/rcS

- only the `simulator_mavlink` module fakes multiple IMUs, all the other simulators only have a single IMU
- there's no delay in simulated GPS data like the typical ublox navigation soluiton (> 100 ms)

ROMFS: rc.simulator EKF2 setup specific to gazebo classic

---

src/modules/fw_pos_control/FixedwingPositionControl.cpp
src/modules/fw_pos_control/FixedwingPositionControl.hpp

…
For VTOL UAVs it can happen that during transition, the user warning "Roll command reduced due to uncertain velocity/wind estimates!" appears multiple times. Also i appears often at least once during transition, since at the beginning, the wind is unknown, and the groundspeed is low.
- Condition must persist for at least 2s before a user notification is thrown.
```
Bugfix: Reduce "roll command reduced" warning for user
```

FixedwingPositionControl: Only warn user when roll is reduced for a longer period of time

---

src/modules/ekf2/EKF/gps_control.cpp

- minor logging improvement when plotting the position from the beginning

ekf2: only populate gnss pos aid src status if ref initialized

---

src/drivers/batt_smbus/batt_smbus.cpp
src/drivers/batt_smbus/batt_smbus.h

When BQ40Z80 is going out of Shutdown mode we can't retrieve some telemetry message.
When using a SMbus ManufacturerAccess command in the batt_smbus driver (for example lifetime_data_flush()) the BQ40Z80 is stretching the clock for more than 20 ms.
The timeout configured for STM32H7 based autopilot is 10 ms.
As soon as the BQ40Z80 is releasing the clock, the PX4 try to send the command again (address + command + 2 byte block) but BMS can't resolve it as it is expecting only a 2 byte command and it receive 4 byte.
The result is that all the telemetry using ManufacturerBlockAccess in batt_smbus driver can't be refreshed.
By adding a dummy ManufacturerAccess command before sending the first ManufacturerBlockAccess command (LifetimeDataFlush in the get_startup_info() function) and a 30 ms …

Fixing batt_smbus timeout problem with BQ40Z80 BMS.

---

msg/CMakeLists.txt
msg/RtlStatus.msg
src/modules/logger/logged_topics.cpp
src/modules/navigator/MissionFeasibility/FeasibilityChecker.cpp
src/modules/navigator/MissionFeasibility/FeasibilityChecker.hpp
src/modules/navigator/mission_params.c
src/modules/navigator/navigator_main.cpp
src/modules/navigator/rtl.cpp
src/modules/navigator/rtl.h

When a VTOL is flying in air, we want to make sure that a landing is defined either by VTOL land approaches on home/rally points or the mission. Thus when uploading a new mission in air, the mission should get rejected, when it does not define a landing and there are no landing approaches defined for the safe points.
Add a new mission check option in MIS_TKO_LAND_REQ. This option checks, if a landing is defined, when in air and no safe point approaches are defined. While on the ground, it will use the same logic as MIS_TKO_LAND_REQ=4
```
Feature: New Mission takeoff/landing required option to check for a valid landing (either mission landing or land approaches) when in air.
```
- Simulation/hardware testing logs: …

Add mission check land when no approach

---

src/modules/navigator/land.cpp

The setpoint.yaw can be NAN, and this made the calculated land point NAN as well. Looking at the current yaw is anyway a better way to approximate the course over ground that fundamentally should be used.
NB As we only need a rough idea of the current course over ground, I think it's not worth to calculate it by using the ground velocity, as then we'd have instabilities when approaching 0 ground speed.
```
Bugfix 
```

Navigator: fix VTOL land waypoint calculation

---

src/modules/flight_mode_manager/tasks/Utility/CMakeLists.txt
src/modules/flight_mode_manager/tasks/Utility/StickTiltXY.cpp
src/modules/flight_mode_manager/tasks/Utility/StickTiltXY.hpp
src/modules/flight_mode_manager/tasks/Utility/StickTiltXYTest.cpp
src/modules/flight_mode_manager/tasks/Utility/Sticks.hpp
src/modules/mc_pos_control/multicopter_stabilized_mode_params.c

Reported by @alistair-blueflite when `MPC_MAN_TILT_MAX` is set to close to or 90° the accelerations go insane and I even had it that the stick input reverses direction at 90°.
Fixes #22714
- Consider 1° - 70° the recommended useful range. This corresponds to a 3:1 thrust-to-weight ratio.
- If the pilot sets `MPC_MAN_TILT_MAX` higher, guard against the calculations leading to a hardly steerable drone.
Note: In stabilized mode `MPC_MAN_TILT_MAX` can be up to 180° and the controller will track it.
- Add unit tests.
```
Fix: Limit maximum tilt in Altitude mode such that close to 90° configuration doesn't cause issues
```
Having a multicopter tilt to 90° and expect it to hold altitude doesn't make sense, see also this comment: https://github.com/PX4/PX4-Autopilot/issues/22714#issuecomment-19222 …

StickTiltXY: Fix too high maximum tilt problem

---

src/modules/ekf2/EKF/ekf_helper.cpp

`attitude_valid()` returns `_control_status.flags.tilt_align`. This is enough to declare a valid attitude

ekf2: set attitude validity flag using centralized function

---

src/modules/ekf2/EKF/ev_control.cpp
src/modules/ekf2/EKF/ev_height_control.cpp

- needs to be called every iteration

ekf2: fix EV height bias predict call

---

test/mavsdk_tests/autopilot_tester.cpp
test/mavsdk_tests/test_multicopter_manual.cpp
test/mavsdk_tests/test_multicopter_offboard.cpp

This PR solves the issue of the CI SITL Tests failing for the iris, specifically when the **'Fly forward in position control'** test is run. 
To verify, run the following locally: 
`DONT_RUN=1 make px4_sitl gazebo-classic mavsdk_tests && test/mavsdk_tests/mavsdk_test_runner.py test/mavsdk_tests/configs/sitl.json --speed-factor 20 --model iris --iterations 100  --case 'Fly forward in position control'`
These tests are written with the assumption, that PX4 will not switch to Position mode if it's not allowed to fly it yet. But now you can switch to Position mode even if it's not flyable yet when the vehicle is still disarmed. PX4 will actually automatically switch to position mode when there's stick input but we don't want to rely on that in this test.
Order:
- Send stick input (manual …

CI fix 'Fly forward in position control' MAVSDK test

---

ROMFS/px4fmu_common/init.d-posix/airframes/4011_gz_lawnmower
ROMFS/px4fmu_common/init.d-posix/airframes/5005_gz_lawnmower
ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt

This PR contributes full-size Zero Turm Lawnmower model to existing collection of Gazebo Ignition models. While crude visually, it tries to simulate masses, inertia and friction of an actual full-size machine.
Used _Husqvarna Z254_ dimensions.
This model works fine with current Differential Drive Controller (https://github.com/PX4/PX4-Autopilot/pull/22402) and my own fork (https://github.com/slgrobotics/PX4-Autopilot). It can be driven manually.
Please see https://github.com/PX4/PX4-gazebo-models/pull/27  for actual SDF file
**Testing:**
```
mkdir src21
cd src21
git clone https://github.com/slgrobotics/PX4-Autopilot.git --single-branch --recursive -b gz-lawnmower
cd PX4-Autopilot/
ls -al Tools/simulation/gz/models/
git tag v1.15.0-alpha1
make px4_sitl gz_lawnmower
```
You may need to …

Added Zero Turn Lawnmower model

---

src/modules/gimbal/gimbal.cpp

Controlling the gimbal when the gimbal driver was configured to mavlink gimbal v2 input and AUX output was not working. PX4 would never send out the gimbal manager information when requested.
The actual issue I was chasing was that our GCS (based on QGC) would always switch to mavlink gimbal v1 when the gimbal configuration in PX4 was mavlink gimbal v2 as input and AUX (pwm) as output. This was then causing other side effects that are not relevant in this PR.
The main problem was that during initial negotiation the GCS would request the gimbal_manager_information as specified in the gimbal v2 discovery protocol: https://mavlink.io/en/services/gimbal_v2.html#discovery-of-gimbal-manager
If no response came back the GCS would assume we were using the v1 gimbal protocol, while if the message …

fix gimbal driver for mavlink gimbal v2 input and AUX output

---

.ci/Jenkinsfile-compile

@PerFrivik was asking me about the following CI issue:
A quick investigation showed it's probably due to a missing comma.
Introduced in:
#22675 (2c81c9fdea0f589f4021a549d86969dc317327fa)
Add comma
```
Cleanup: CI script typo
```
Let's see if Jenkins feels better 👀

Jenkinsfile: correct typo, missing comma

---

src/modules/ekf2/EKF/airspeed_fusion.cpp
src/modules/ekf2/EKF/ekf.h
src/modules/ekf2/test/sensor_simulator/ekf_wrapper.cpp
src/modules/ekf2/test/sensor_simulator/ekf_wrapper.h
src/modules/ekf2/test/test_EKF_airspeed.cpp

Wind dead-reckoning using sideslip and airspeed fusion isn't able to start if the airspeed data isn't consistent with the filter. Since the ekf is doing inertial dead-reckoning, the estimate is probably worse than the airspeed measurement and we should allow a velocity reset.
When doing inertial dead-reckoning, allow airspeed fusion to start and reset the velocity estimate using airspeed if the consistency check is failing.
```
Allow wind dead-reckoning after manual position reset
```

ekf2: allow wind dead-reckoning after manual position reset

---

src/modules/fw_att_control/FixedwingAttitudeControl.cpp
src/modules/fw_att_control/FixedwingAttitudeControl.hpp

FW_Y_RMAX and not FW_MAN_YR_MAX used for max manual yawing rate in Attitude controlled modes, thus not possible to disable manual yaw rate input without disabling yaw rate control completely. 
Use FW_MAN_YR_MAX.
```
Bugfix: FW Attitude Controller: fix manual yaw rate setpoint limit
Original PR of the "add option to disable manual yaw": https://github.com/PX4/PX4-Autopilot/pull/20647

FW Attitude Controller: fix manual yaw rate setpoint limit

---

src/drivers/barometer/bmp388/bmp388.cpp

The BMP388 Driver supports both BMP388 and BMP390 but doesn't show this on startup.
This patch changes the `_item_name` on startup when a BMP390 gets detected
For example a board with a BMP338 and BMP390 shows the following now.
```
bmp388 #0 on I2C bus 3 address 0x77
bmp390 #1 on I2C bus 2 (external) address 0x76
```

bmp388: Driver print BMP390 identifier when detected

---

boards/atl/mantis-edu/src/board_config.h

@lyraik found this duplicate define 🧹

mantis-edu: remove duplicate RC define

---

src/systemcmds/netman/netman.cpp

Allows netman config to be file instead of a mtd device.
ENOENT returns if the file doesn't exist yet, when using mtd the /fs/mtd_net always exist. 
On a filesystem you've to generate the file so if ENOENT returns we've to regenerate the default config as well.
Also updates apps to allow for delayed opening of ipcfg file by polling if the filesystem ha been mounted, this can be done by setting the retry KConfig symbol

netman fix usage on a filesystem

---

boards/px4/fmu-v5x/init/rc.board_defaults
boards/px4/fmu-v5x/init/rc.board_mavlink
boards/px4/fmu-v5x/init/rc.board_sensors
boards/px4/fmu-v6x/init/rc.board_defaults
boards/px4/fmu-v6x/init/rc.board_mavlink
boards/px4/fmu-v6x/init/rc.board_sensors
boards/px4/fmu-v6xrt/init/rc.board_mavlink
platforms/common/pab_manifest.c

Adds a new baseboard revision for a Skynode RC13 baseboard without PX4IO, CAN2, CAN3, PM2.
```
Feature: Add Skynode RC13 baseboard with many parts removed
```
Yes. SBUS input has been tested.

Add minimal Skynode RC13 config to the PAB manifest

---

src/modules/commander/mag_calibration.cpp

- The existing code erroneously converts a variable containing a radian value into radians again for output. This update converts the variable containing the radian value into degrees for output. 
- The log level has been changed from critical to info.
And I have many questions about quick calibration.
Could you please check this issue - https://discuss.px4.io/t/quick-accel-magnetometer-calibration/37078

mag calibration: minor cleanup

---

src/modules/ekf2/EKF/EKFGSF_yaw.h
src/modules/ekf2/EKF/gps_control.cpp

The yaw estimate from the yaw emergency estimator can drift on ground due to incorrect gyro bias calibration.
Example log where the yaw composite drifts after every landing:
The gyro bias estimate from EFK2 is really good when at rest and should be used by the yaw estimator to prevent heading drifts due to poor heading observability.
Same log replayed with the fix:
```
Fix yaw emergency estimate drift on ground
Documentation: No
```
- EKF2 replay

EKF2-yaw estimator: force set gyro bias when at rest

---

src/modules/mag_bias_estimator/MagBiasEstimator.cpp
src/modules/sensors/vehicle_acceleration/VehicleAcceleration.cpp
src/modules/sensors/vehicle_air_data/VehicleAirData.cpp
src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp
src/modules/sensors/vehicle_imu/VehicleIMU.cpp
src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp

In several places where sensor data is grabbed we have the update in a while loop so that if the data is being generated faster than the consumer runs we don't miss it. For additional safety I've put an upper bound on the number of iterations to prevent any timing issues resulting in these updates looping indefinitely.

sensors: update loop limit iterations

---

src/drivers/barometer/invensense/icp201xx/ICP201XX.cpp

Fixes wrong altitude reporting trough barometer with the ICP201XX sensor by InvenSense in external I2C.

ICP201: increase config delay

---

src/modules/vtol_att_control/standard_params.c
src/modules/vtol_att_control/vtol_type.cpp

In Descend mode (failsafe mode after position loss in hover auto modes), the pusher assist is not running. It is expected that it runs in Descend as it does in Land, as the implications of the descend mode are the same as for Land (vehicle needs to reduce altitude and is about to have ground contact, for which for some vehicles it is better to disable pusher assist). 
Treat Descend as Land.
```
Improvement: VTOL forward thrust assist: treat Descend as Land mode.
```
We could also keep it fully disabled in Descend as it is currently.

VTOL: treat Descend mode as Land

---

src/modules/fw_pos_control/FixedwingPositionControl.cpp

I got the warning quite often on the ground when in a NPFG controlled mode.

FW Pos Controller: do not publish roll angle constrained warning if landed

---

src/modules/navigator/navigator_main.cpp

We had a special handling for RTL triggered in vtol_takeoff state. The idea is to wait until the VTOL Takeoff is completed and only then switch to RTL. On a second thought this special handling isn't really necessary and for the sake of simplicity should be removed. This also removes the side effect of the indicated flight mode after RTL being set to VTOL_Takeoff again.
While testing it I found that currently RTL in the hover phase of the VTOL Takeoff is completely broken, it just stays hovering. This change here fixes that.
Downside of this change: when triggering RTL shortly after the transition to FW is compete, the vehicle will loiter around the current location to climb to RTL_RETURN_ALT instead of climbing at the defined loiter position, but for me that's an acceptable state.
For …

Navigator: remove vtol_takeoff special handling for RTL

---

msg/CMakeLists.txt
msg/GeofenceStatus.msg
msg/MissionResult.msg
src/modules/navigator/MissionFeasibility/FeasibilityChecker.cpp
src/modules/navigator/MissionFeasibility/FeasibilityCheckerTest.cpp
src/modules/navigator/geofence.cpp
src/modules/navigator/geofence.h
src/modules/navigator/mission_base.cpp
src/modules/navigator/mission_base.h

The mission feasibility checks could return a wrong result on startup for the loaded mission on the storage.
- Only run the mission feasibility check after the geofence has loaded all the data.
- Only run mission feasibility check after a global position topic has been published.
- Some Bugfixes
```
Bugfix Correclty check mission feasilbity on startup
```
We really should decouple the feasibility check from the mission execution.
- SITL test:
- Test case 1: Define a valid mission and store it on the vehicle. Stop the simulation. Start it again, with a different location far away.
- Test case 2: Define a mission and a geofence, where the mission violates the geofence. Stop the simulation. Start it again.
- Test results: Prior in both cases, the vehicle would arm then …

Fix mission check for init mission

---

src/modules/navigator/mission_base.h
src/modules/navigator/rtl.cpp

When flying and setting a mission with only a vtol land, it is not executed.
- Check for land_start_inex is wrong. only check if it is negative.

mission_base: land_start_item invalid only when negative.

---

src/modules/vtol_att_control/tiltrotor.cpp

Vehicle yawing strongly during final phase of front transition.
MC yaw control is faded out during the blending phase of a VTOL front transition. As there can be a quite high yawing torque acting on the system (eg due to asymmetric motor setup), and the fixed-wing yaw actuator is not fully effective yet (if it is existing at all), the vehicle yaws often to a side. 
The effect is specially noticeable on Tiltrotors because there the blending phase doesn't always end with the transition airspeed reached, as also the transition motor tilt has to be reached first. It can thus stay in a prolonged blending phase of multiple seconds.
I propose to remove the MC yaw fade out for Tiltrotor. For standard VTOLs I would keep it for now due to two reasons:
- blending phase can be precisely controlled …

Tiltrotor: disable MC yaw fade out during front transition blending

---

src/modules/navigator/rtl_direct_mission_land.cpp

Came in yesterday with https://github.com/PX4/PX4-Autopilot/pull/22742
Symptom: on every boot with an invalid mission the system gave warning "No valid mission available, refusing takeoff"

rtl_direct: fix on_inactive()

---

src/lib/events/enums.json
src/modules/commander/HealthAndArmingChecks/checks/batteryCheck.cpp
src/modules/commander/commander_params.c
src/modules/commander/failsafe/failsafe.cpp
src/modules/commander/failsafe/failsafe.h
src/modules/commander/failsafe/framework.cpp
src/modules/commander/failsafe/framework.h
src/modules/navigator/rtl.cpp
src/modules/navigator/rtl.h

Around remaining flight time low failsafe:
- not possible to disable
- not possible to switch out of RTL, as it keeps getting re-engaged
- new param `COM_FLTT_LOW_ACT`
- update rlt time estimate also in RTL, and use it to set the flight_time_low flag to false if it applies (e.g. because user has moved the RTL destination, see screen recording)
- add hysteresis to make instant re-triggering less likely
```
Improvement:  Commander: make low remaining flight time configurable and do not clear
```
Without the fix:
https://github.com/PX4/PX4-Autopilot/assets/26798987/ff9b6042-5dc7-4b8e-8714-36d39d1cec27
With the fix:
Uploading AMC_RTL_time_with_fix_2.mp4…

 Commander: make low remaining flight time configurable and fix clearing condition

---

src/modules/uxrce_dds_client/uxrce_dds_client.cpp
src/modules/uxrce_dds_client/uxrce_dds_client.h

- move init from UxrceddsClient to init() method so that retry is possible for both serial and UDP init
- init from main loop instead of constructor so we can retry indefinitely

uxrce_dds_client: refactor init to retry indefinitely

---

src/lib/dataman_client/DatamanClient.cpp
src/lib/dataman_client/DatamanClient.hpp

Dataman requests occasionally time out during boot. My suspicion is that its a combination of slow SDCard and unfortunate scheduling order during boot when the CPU is very busy. The timeout of 1s may be reached more quickly than expected. 
However, it is notoriously difficult to reproduce this issue under controlled and debuggable/traceable conditions. I was only able to catch it once and the `dataman: write` perf counter "only" recorded most=310ms. However, [on unrelated traces](https://github.com/niklaut/orbetto-support-files/raw/main/orbetto_pc.perfetto_trace.gz) I've seen scheduling latencies on the dataman thread in the hundreds of milliseconds, here 271ms:
This increases the dataman client timeout to 5s and logs the time it took to service the sync requests.
There are already two …

dataman: Add client sync perf counter and increase default timeout to 5s

---

src/modules/commander/failsafe/framework.h

`vehicle_status.failsafe `is set when action is only a warning (e.g. battery warning level reached). That further set `system_status` to `MAV_STATE_CRITICAL` in the hearbeat that's sent to the ground station. 
Do not set the failsafe flag for Action::Warn.
It's debatable if this flag also should be set if the action is only warning. For me personally a failsafe is only a failsafe if the system has actually changed it's behavior in response to the system check that failed (e.g. switched to RTL if battery empty). If the system has detected a critical issue but cannot act to safe it then it should send a "system state critical" or similar message. 
```
Improvement:  Commander: set vehicle_status.failsafe flag only if action for failed check is more than warning
```
I've …

Commander: set vehicle_status.failsafe flag only if action for faileded check is more than warning

---

src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.cpp

The "GNSS data stopped" warning is sent after the system is already in local position estimate invalid failsafe (at least for hovering systems without wind dead-reckoning). That warning then distracts from the real issue (that the vehicle switched into a failsafe mode). 
https://github.com/PX4/PX4-Autopilot/assets/26798987/ad1b0710-7aec-4bd3-8439-2a440985eada
Reduce the severity level of the message to INFO in case of invalid local position. 
https://github.com/PX4/PX4-Autopilot/assets/26798987/648e97f6-6753-4474-82da-b2ee43ff2410
```
Improvement: EstimatorCheck: GNSS data fusion stopped as INFO if local position is already invalid
```

EstimatorCheck: GNSS data fusion stopped as INFO if local position is already invalid

---

src/modules/commander/Commander.cpp

There is currently no warning/event sent by PX4 when arming is denied due to a preflight check failure (though the preflight field in the top bar is red). 
Add a warning message to make clear that 
1) there was an arming attempt (not that e.g. sticks are not working)
2) give hint to why arming failed
```
Feature: 
```

Commander: trigger warning when arming denied due to check failure

---

src/lib/events/enums.json
src/modules/commander/failsafe/framework.cpp

The failsafe event messages are a bit long.
Make them shorter.
That's how it would look like now:
https://github.com/PX4/PX4-Autopilot/assets/26798987/ece1ea4e-74de-473c-8458-a7c24d986d6e
```
Improvement: Commander: make failsafe warnings shorter
```

Commander check reporting improvements

---

src/modules/commander/failsafe/framework.cpp

Previously when triggering low battery RTL and then losing GPS, the fallback to Descend would still have low battery as cause.

failsafe: set cause to generic when fallback mode is activated

---

src/modules/ekf2/EKF/gps_control.cpp

I think yas estimate is a yaw estimate.
Change yas to yaw.
None
None
None
None

EKF: Change a typo

---

src/modules/mc_pos_control/MulticopterPositionControl.cpp
src/modules/mc_pos_control/MulticopterPositionControl.hpp
src/modules/mc_pos_control/PositionControl/PositionControl.cpp
src/modules/mc_pos_control/PositionControl/PositionControl.hpp
src/modules/mc_pos_control/multicopter_position_control_limits_params.c

To generate a thrust setpoint from the acceleration demand, we decided to decouple the horizontal and vertical components as having the exact geometric controller creates a worse behavior while accelerating downwards. This is great for the normal use cases, but for acrobatic automated flights, it is still preferred to have better tracking than a smooth behavior.
Add an option to en-/disable horizontal-vertical coupling in the acceleration controller.
```
Multirotor: add possibility to generate tilt using full 3D acceleration
New parameter: MPC_ACC_DECOUPLE
Documentation: TODO
```
SITL

MC acceleration control: add possibility to generate tilt using full 3D acceleration

---

src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/streams/BATTERY_INFO.hpp

#22724 is failing because SMART_BATTERY_INFO was renamed to BATTERY_INFO and aligned with UAVCAN in https://github.com/mavlink/mavlink/pull/2070/files
This was reasonable as there are no smart batteries, but breaks MAVLink import, because PX4 implements it. This includes the same MAVLink module commit, but also renames SMART_BATTERY_INFO to BATTERY_INFO.
I'm fairly sure I got it right (all builds) but I'm not a software engineer. NOTE, a bunch of these fields aren't implemented in PX4 uorb topic so can't be passed through to MAVLink.
You can see the changes in link above, but at high level:
- Unchanged fields: `id`, `battery_function`, `type`, cycle_count`, `weight`, `cells_in_series`, `cycle_count`
- Modified 
- `serial_number` - char[16] to [32]
- `capacity_full_specification` renamed …

SMART_BATTERY_INFO to BATTERY_INFO

---

src/systemcmds/sd_bench/sd_bench.cpp

Check everything to know the maximum write time max.
I judge a MICRO SD card as good or bad by knowing the max time.
Show the maximum value of the maximum write time.
None
None
None

sd_bench: Display maximum time for maximum write time

---

src/modules/navigator/mission_base.cpp
src/modules/navigator/mission_base.h

fix the bug which cause  drone can't finish mission after changing home altitude.Update mission after changing home position.
This state management bug will result in the drone being unable to reach the waypoint and thus continuing the mission.And continues to drift irregularly near the waypoints.
1. When the drone is executing a mission, PX4 calculates the distance between the drone and the current target waypoint, and checks if it has reached the vicinity.
Here calculates the distance.
https://github.com/PX4/PX4-Autopilot/blob/8b96cd5372c343ef2a3f8a8b805d5b39b47a8008/src/modules/navigator/mission_block.cpp#L197-L201
When mission altitude mode is **Relative to Launch** `mission_item_altitude_amsl=mission_item.altitude + home_alt`
And here checks whether it is less than the acceptable …

update mission after changing home position

---

src/modules/ekf2/test/test_EKF_gps_yaw.cpp

The heading wasn't following the GNSS yaw precisely. After investigation I found that the unit test was incorrectly designed.
Make the unit test work the same way a real driver does.
Reduce the tolerance threshold (it was too high to make the unit test pass).

EKF2: fix gnss yaw unit test

---

src/modules/mc_pos_control/PositionControl/PositionControl.hpp

The unit test assumes the position controller is in "decoupled" mode
Broke due to https://github.com/PX4/PX4-Autopilot/pull/22696#pullrequestreview-1946794903

MPC: fix PositionControl unit test

---

platforms/common/uORB/SubscriptionBlocking.hpp

SubscriptionBlocking tries to initialize the mutex with type PTHREAD_PRIO_NONE if it is available in the platform. It supposedly is defined in Qurt but the init fails when it is set so this PR avoids that init on Qurt platforms.

Get rid of SubscriptionBlocking mutex init error message on Qurt

---

platforms/common/uORB/uORBDeviceNode.cpp

In UORB communicator interface only latest topic data should be sent to the remote entity on a new subscription.

Fix for UORB communicator remote subscription processing

---

.editorconfig

EditorConfig is a well-known convention to share style settings across different editors. Adding one will make it easier for new contributors or people who like to use a different editor to contribute.
I've switched from using Visual Studio Code to Neovim because the language server works quite a lot better. Neovim has no way to tell how to indent lines or how to represent tabs. Having this file tells a lot of different editors some basic information like how many spaces a tab represents, whether to indent with spaces or tabs, what the maximum line length should be... It can also tell editors to use a certain encoding, add a newline at the end of files and some other QOL settings.
The developer documentation mentions that a lot of files do not yet follow the style guidelines. This file …

code: add `.editorconfig` for consistent code style across editors

---

src/drivers/gps/gps.cpp

This is a small fix because when I read through the code, the `_task_id` does not seem to be set correctly in `gps.cpp` in the GPS module. It's setting a local variable instead of the member variable which is supposed to be set to -1 on error (see documentation of `ModuleBase::task_spawn()`).
Fixes \/
- Change local variable to member variable
```
Bugfix Correctly set GPS module task id on failure
```
\/
\/
Found this while working on extracting a GPS driver in #22904

gps: fix incorrect task id in module startup

---

.editorconfig

Some file types were missing from the global `.editorconfig`.
- Added more EditorConfig style settings to the `.editorconfig` to support YAML, Kconfig and `CMakeLists.txt` files.
\/
\/
\/
I wanted to see whether a `.editorconfig` would be accepted before adding all the options. This will also be an ongoing effort as that's easier than adding all the options for all the files at once. People can add files that aren't displayed/edited correctly as they need it.
The options are decided both by looking at the developer documentation as well as by checking what most files use (e.g. for YAML where the style isn't documented anywhere).

code: add more style options in `.editorconfig`

---

boards/modalai/voxl2/target/voxl-px4-start

QGC will complain about missing SYS_AUTOSTART on voxl2 because it isn't used. This will cause arming to be denied. So added a simple param touch in the startup script to make QGC content.

Add SYS_AUTOSTART touch in voxl-px4-start

---

boards/holybro/kakuteh7/src/spi.cpp

The mass-produced kakuteH7 did not use ICM20689 IMU. 
It used MPU6000 or ICM42688P.

Fix KakuteH7 icm42688p imu issue

---

src/modules/ekf2/EKF/gps_control.cpp

YAW Failure decision is being made after the YAW Failure decision and before the During Takeoff decision.
YAW Failure Decision is effective by making the during-takeoff decision first.
None
None
None
None

EKF: IN_AIR is determined first

---

boards/diatone/mamba-f405-mk2/src/board_config.h
boards/matek/h743-mini/src/board_config.h
boards/matek/h743/src/board_config.h
boards/sky-drones/smartap-airlink/src/board_config.h
src/lib/battery/module.yaml

When helping @sfuhrer with battery configuration he hinted me towards the description not being accurate.
Feel free to add to this.
- Correct the fact that these voltages are ideally with the load completely compensated.
This requires an accurate current measurement and configured internal resistance.
- Clarify the text a bit.
```
Documentation: clarify empty, full battery voltage description
```

Battery parameters: clarify empty, full voltage description

---

platforms/common/Serial.cpp
platforms/common/include/px4_platform_common/Serial.hpp
platforms/nuttx/src/px4/common/SerialImpl.cpp
platforms/nuttx/src/px4/common/include/SerialImpl.hpp
platforms/posix/include/SerialImpl.hpp
platforms/posix/src/px4/common/SerialImpl.cpp
platforms/qurt/include/SerialImpl.hpp
platforms/qurt/src/px4/SerialImpl.cpp
src/drivers/gps/gps.cpp
src/lib/drivers/device/qurt/uart.c
src/lib/drivers/device/qurt/uart.h

Serial UART had to be created dynamically in order to set the port since it could only be set in the constructor. Added a new constructor and a setPort function so that the port can be set after the Serial object has been created. Added a static validatePort function. The new validatePort function will call the access function on Nuttx and Posix platforms to verify the port name in the file system. The Qurt platform does not have a file system so it does not call access. The GPS driver was modified to make use of these new functions. It no longer dynamically allocates the Serial driver. And it uses the new validatePort function instead of calling access. This allows the GPS driver to now work on the Qurt platform.

Additions to the Serial UART API

---

boards/modalai/voxl2-slpi/src/CMakeLists.txt
platforms/qurt/include/termios.h
platforms/qurt/unresolved_symbols.c

Added decoy termios support to Qurt so that ghst parser in RC library can be used. No termios is actually needed but has to be there for the parser to work. When the RC library is ported to the new Serial API this decoy termios support can be removed.

Qurt termios decoy

---

src/drivers/gps/gps.cpp

For Septententrino we seem to sometimes fill the buffer pretty full.
If we ask for too much, readAtLeast will fail completely and make the GPS discovery logic fall over. Therefore, let's not ask for too much and just read what we can given the available buffer.

gps: fix Septentrino serial read

---

src/modules/logger/logged_topics.cpp

`rtl_status` seems to not get logged atm because it's not advertised at init. My proposal is to change `add_optional_topic()` to `add_topic()` for it, as we e.g. also add `rtl_time_estimate` as not optional. Otherwise we can advertise `_rtl_status_pub` in the RTL constructor.
I've also reduced the logging interval of `rtl_status` a bit.

rtl_status.msg logging fixes

---

src/lib/battery/battery.cpp

When analyzing test vehicle crashes I found that it happens regularly that people set a "random" battery capacity and then still rely on the battery estimate which is in that case completely wrong.
This is a minimal change to make it harder to crash a vehicle with an empty battery if the capacity was set completely wrong.
```
Fix: Rely less on battery capacity based estimate when voltage is low
Documentation: Battery estimate configuration docs are too sparse in general.
```
We need better documentation and improvements to the estimation.
- Not tested yet. I'll see if there's a simple simulation test to verify.
FYI @jongell @Dani3L9H

battery: Rely less on battery capacity based estimate when voltage is low

---

boards/modalai/voxl2/target/voxl-px4-start

The start script for VOXL2 board needed the device to be specified for the gps start command

Added device specifier to gps start line

---

Jenkinsfile

I'm hoping to migrate docs from vuepress to vitepress ("vuepress 3") in the coming weeks. This is some prep work to export the uorb graphs and failsafe simulation files to the right place for use by vitepress.
Initially delivering to both places, so I will need to follow on with removal of the vuepress file versions later.

Jenkinsfile - dual-deploy uorb graph and failsafe to vitepress

---

src/drivers/px4io/Kconfig

#22957 has a typo in the dependencies thus PX4IO wasn't building.
This PR Fixes that

px4io: Fix dependency problem caused by #22957

---

src/modules/simulation/gz_bridge/GZBridge.cpp

Fixes https://github.com/PX4/PX4-Autopilot/issues/22839
with the addition of the navsat plugin in PR https://github.com/PX4/PX4-Autopilot/pull/22638, the callback would reassign the previous timestamp used in the calculations of the angular_velocity causing derivative type noise in the groundtruth measurements
Main https://github.com/PX4/PX4-Autopilot/tree/416b6a35a478482fe021b9261e15911338598d09

gz-bridge: use correct prev_timestamp for dt calc 

---

src/modules/navigator/MissionFeasibility/FeasibilityChecker.cpp
src/modules/navigator/mission_params.c
src/modules/navigator/navigator.h

With MIS_TKO_LAND_REQ=5, it required a takeoff and a land or neither also when in air and there was a valid home/safe point approach. This is wrong, and it only should require that when on the ground.
Fix logic, only handle hasMissionBothOrNeitherTakeoffAndLanding() if on ground if MIS_TKO_LAND_REQ=5, in air and without safe approach only check for landing.
```
Bugfix: FeasibilityChecks: MIS_TKO_LAND_REQ=5: only require both or neither TO/LND when landed
```

FeasibilityChecks: MIS_TKO_LAND_REQ=5: only require both or neither TO/LND when landed

---

Jenkinsfile
Tools/msg/generate_msg_docs.py

Vitepress is now in, so this is changes to remove changes needed only by vuepress, or to better suit vitepress.
(copying files to vuepress that are no longer needed + outputing an index.md rather than readme.md since vitepress doesn't auto convert the readme anymore.

Vuepress removal /changes for vitepress

---

boards/modalai/voxl2/target/voxl-px4-start

Voxl2 startup script was attempting to start old microdds client instead of new uxrce dds client. This PR moves it to the correct one.

Move Voxl from microdds client to uxrce dds client

---

src/drivers/distance_sensor/broadcom/afbrs50/AFBRS50.cpp
src/drivers/distance_sensor/broadcom/afbrs50/AFBRS50.hpp
src/drivers/distance_sensor/broadcom/afbrs50/parameters.c

This PR attempts to fix the broadcom AFBR reading false readings when very close to the ground. 
https://review.px4.io/plot_app?log=4da0db08-522e-488a-942e-369b6085f239#Nav-Distance-Sensor
https://review.px4.io/plot_app?log=10f570a2-89f7-4696-8ea5-bb79e320d72f#Nav-Distance-Sensor
https://review.px4.io/plot_app?log=290041ef-6abb-4e1f-b236-fd2363087bf5#Nav-Distance-Sensor
https://review.px4.io/plot_app?log=aaad65cd-3eff-4237-b918-b2fbaf7ffe9a#Nav-Distance-Sensor
https://review.px4.io/plot_app?log=8c5acf8d-e921-49fd-8dc2-dda2aa7444b3#Nav-Distance-Sensor
It still looks like it can get into a state when right next to the ground where it reads ~3cm.
https://review.px4.io/plot_app?log=8c5acf8d-e921-49fd-8dc2-dda2aa7444b3#Nav-Distance-Sensor

drivers: broadcom AFBR fix close to ground false readings

---

src/modules/navigator/mission_base.cpp
src/modules/navigator/mission_base.h

The UAV could make a fly away, if a mission could not be started but the mission was still declared valid.
- Make sure to properly set a loiter item or idle item, when a mission can't be started or the current mission item could not be loaded
```
Bugfix: Prevent flyaway when an in air mission could not be started and the mission item could not be properly loaded
```
- Simulation test: Tested on gazebo-classic_standard_vtol

mission_base: fix to set the end of mission item on error

---

src/lib/tecs/TECS.cpp
src/modules/fw_pos_control/FixedwingPositionControl.cpp

FW auto hand/catapult launch takeoff without takeoff detection is currently broken. 
We though claim to support it, see [description of FW_LAUN_DETCN_ON](https://docs.px4.io/main/en/flight_modes_fw/takeoff.html#parameters-launch-detector).
required 2 fixes, plus added one hardening:
- within takeoff logic, do not set throttle to MIN if landed is true but launch detection state is FLYING
- remove checks for param FW_LAUN_DETCN_ON set to true to execute takeoff logic. FW_LAUN_DETCN_ON should only be checked to set the launch detection states, and if set to false this state is already forced to FLYING
- TECS throttle integrator: only apply if finite. I had cases in SITL where it would be nan shortly after booting, and would then stay nan for the whole flight, resulting in the throttle output …

FW auto hand/catapult takeoff: fix case with disabeld takeoff detection

---

src/modules/navigator/mission_base.h
src/modules/navigator/rtl.cpp
src/modules/navigator/rtl.h

With `RTL_TYPE=0` and `RTL_APPR_FORCE=1`, the logic in [RTL::findRtlDestination()](https://github.com/PX4/PX4-Autopilot/blob/4d0a88fdf8745c02f19f4142f0e98765a0a47b02/src/modules/navigator/rtl.cpp#L402-L403) does not check if the mission is valid, only if the mission has a valid land item. If the mission is not valid, it will result in anyway switching into the Mission RTL, only to then find that the mission is invalid and loiter at place instead of returning. 
Instead of adding an additional check for the mission validity there, the proposal here is to not return `hasMissionLandStart()` as true.
```
Bugfix: RTL: fix corner case where vehicle loiters in place instead of doing the RTL to Home.
```
Add a check for mission validity in …

RTL: fix corner case where vehicle loiters in place instead of doing the RTL to Home

---

boards/modalai/voxl2-slpi/src/CMakeLists.txt
boards/modalai/voxl2-slpi/src/drivers/spektrum_rc/spektrum_rc.cpp
src/lib/rc/dsm.cpp
src/lib/rc/dsm.h

The RC library has UART configuration and protocol parsing mixed together. This PR allows use of the DSM protocol parser
without the need to configure / use a UART which is needed for the Voxl board specific DSM RC driver.

Update the DSM library to allow use of protocol parsing without UART interaction

---

src/modules/logger/logged_topics.cpp

Useful for logging RTT data of MAVLink and uxrce_dds instances.

logger: add timesync_status to default logged topics

---

src/modules/simulation/gz_bridge/CMakeLists.txt

Added _lawn_ world to the GZ Bridge make process to allow GZ SITL builds like "```make px4_sitl gz_r1_rover_lawn```"
This is a follow-up to https://github.com/PX4/PX4-gazebo-models/pull/35 - "_Adding lawn.sdf world to have sky and grassy ground plane for rovers_"
@Jaeyoung-Lim  @dagar  - please take a look.

Update GZ Bridge CMakeLists.txt to include lawn world in build process

---

src/lib/drivers/accelerometer/PX4Accelerometer.cpp
src/lib/drivers/gyroscope/PX4Gyroscope.cpp

The PX4Gyro and PX4Accel classes assume the raw sensor data is `int16_t`. The SCH16T IMU is `int32_t` and 1600bits per deg/s so this presents itself as a bug where the sensors module reports clipping as soon as the raw data exceeds INT16T_MAX.
This happens at 65535/1600 = ~41 deg/s as you can see in this log
https://review.px4.io/plot_app?log=080b77bf-2ef8-49fb-878a-e6873b9bb422
This will have to be revisited for the FIFO code once there is a 32bit IMU with a FIFO (the sch16t does not have a FIFO) since the FIFO code in PX4Gyro/PX4Accel also assumes 16bit raw data.

[bug] Remove Gyro/Accel INT16_MAX constraint on clip_limit

---

Tools/msg/generate_msg_docs.py
Tools/px4airframes/markdownout.py
Tools/px4moduledoc/markdownout.py
src/lib/parameters/px4params/markdownout.py

The new infrastructure uses a different notes format. This just updates from "note" to "info".

Fix up notes boxes for docs

---

src/modules/ekf2/EKF/common.h
src/modules/ekf2/EKF/estimator_interface.cpp
src/modules/ekf2/EKF2.cpp
src/modules/ekf2/EKF2.hpp
src/modules/ekf2/module.yaml

Requires:
1. It is quite common to enable/disable an aiding source after takeoff to test the robustness of the system. With the current way of calculating the delayed time horizon, booting with or without an aiding source enabled leads to different results (especially for GNSS as it usually has the highest delay).
2. VIO systems are time-synchronized, meaning that their delay parameter is set to 0 but the actual delay is usually much higher, a known workaround is to set the VIO delay in the auxvel delay to size the buffer correctly.
Add `EKF2_DELAY_MAX` parameter to define the delay between the current time and delayed-time horizon.
```
New parameter: EKF2_DELAY_MAX
Documentation: TBD
```
Todo:

EKF2: use dedicated time-delay parameter

---

src/lib/adsb/AdsbConflict.cpp
src/lib/adsb/AdsbConflict.h
src/lib/adsb/AdsbConflictTest.cpp
src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_messages.cpp
src/modules/mavlink/mavlink_receiver.cpp
src/modules/navigator/navigator_main.cpp

- warn about full traffic conflict buffer at 1/60hz.
- add conflict expiry for buffer.
- use only events for buffer full warning. mavlink_log_critical no longer needed.
- use icao address for conflict warnings id, stop using uas_id. UTM_GLOBAL_POSITION assumed deprecated.
- remove mavlink_log_critical warnings. Replaced with events.
- stop spamming when buffer is full. log using px4_info and px4_warn for ulog since events don't show up on flight review or plotjuggler.
- fix warning wording if buffer is full.
- fix missing {1}, {2} etc. from events
follow up on https://github.com/PX4/PX4-Autopilot/pull/21283

Adsb warnings fixes

---

src/drivers/barometer/bmp388/bmp388.cpp
src/drivers/barometer/bmp388/bmp388.h
src/drivers/barometer/bmp388/bmp388_i2c.cpp
src/drivers/barometer/bmp388/bmp388_spi.cpp

BMP388 sensor driver does not check the return value of I2C/SPI bus transfer function, when a single register is read. This could lead to the situation where the driver deactivates its temperature and pressure measurements.
`PWR_CTRL` register value is read in `BMP388::set_op_mode()`. If the read operation fails, the bus driver returns ‘0’ as register value. Then the function sets power mode bits and writes the value back to the register, which disables pressure and temperature sensors (bits 0 & 1).
Tested with custom risc-v based board.

BMP388: Check I2C/SPI bus transfer return code after register read

---

src/modules/ekf2/EKF/python/tuning_tools/baro_static_pressure_compensation/baro_static_pressure_compensation_tuning.py

High-pass filter on baro error was helpful in some cases to remove the steady-state offset but the cutoff frequency depends on the system.
Make a param to set adjust the cutoff frequency using the command line

baro comp: set hpf optional

---

src/drivers/power_monitor/pm_selector_auterion/PowerMonitorSelectorAuterion.cpp

PowerMonitorSelectorAuterion did not allow to set different INA226_SHUNT values. We recently have seen multiple instances where a different value was required though for  providing a correct current reading.
Since the default value for this param is already set to the one we by default expect as well, I deem it okay to just remove that part of the code.
- remove the param reset logic
- tested on a Skynode

PM Selector Auterion: remove INA226_SHUNT value reset (skynode only)

---

src/modules/commander/HealthAndArmingChecks/checks/imuConsistencyCheck.cpp

Accel/gyro consistency mavlink preflight failure triggers below threshold.
In the past we had 2 different failures (see [here](https://github.com/PX4/PX4-Autopilot/blob/437b6b98448ff6587a98a4396a02b1223552f325/src/modules/commander/Arming/PreFlightCheck/checks/imuConsistencyCheck.cpp#L69-L87)):
- \> 0.8 * threshold: "Preflight advice" (mavlink log info)
- \> threshold: "Preflight fail" (mavling log critical)
Now we have:
- \> 0.8 * threshold: "Preflight fail" (mavling log critical)
Have a simpler check:
- \> threshold: "Preflight fail" (mavling log critical)
No magic number. 
I don't think that the warning at 0.8 * threshold is worth it.

imu consistency: don't scale param threshold

---

src/drivers/distance_sensor/lightware_sf45_serial/lightware_sf45_serial.cpp

-Replace raw yaw values with scaled yaw (degrees) when the SF45 is facing left, right, or aft. 
-Removes unused collision prevention angle limit param as it is not used, resulting in missing param error seen here: https://github.com/PX4/PX4-Autopilot/pull/19891#issuecomment-2068973036

Lightware SF45 fix to orientation offsets for scaled yaw, removed unused param

---

src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.hpp
src/modules/mc_pos_control/multicopter_autonomous_params.c

re commit #20888 
Solved Problem
I am developing a multi-rotor machine for agricultural use.
This multirotor machine sprays pesticides.
The nose direction of this multirotor machine is fixed.
I specified "along trajectory" in MPC_YAW_MODE.
I set the Along trajectory to MPC_YAW_MODE.
I determined the direction of the YAW before starting the mission and started the mission.
Once I started the mission, the YAW rotated in the direction of the WP.
I found that I set NAN as a variable to enter the YAW operation.
I need a setting where the nose direction does not change until specified.
Solution
I will change the variable to not set a value to match the other process.
Alternatives
None
Test coverage
AFTER

Auto: No YAW operation

---

src/modules/fw_pos_control/FixedwingPositionControl.cpp

In case of no global position estimate, the local_position.ref_alt is nan, which is directly passed into TECS and results in the output being nan as well. 
One can for example end up in this situation when one switches into Altitude mode without having a GPS sensor installed. The outcome is having all attitude setpoints at nan.
Use `_current_altitude`, which in turn already has a check for valid reference. I don't know why that wasn't done in the first place (likely was just missed). 
```
Bugfix: Fixed-wing: fix Altitude mode without valid global z reference (e.g. no GPS)
```
We need to add protections against this kind of invalid inputs into TECS. At very lest it has to throw an error.
SITL tested (set EKF2_GPS_CTRL to 0, restart simulation, takeoff in Altitude mode, …

Fixed-wing: fix Altitude mode without valid global z reference (e.g. no GPS)

---

Tools/module_config/output_groups_from_timer_config.py
platforms/nuttx/src/px4/nxp/imxrt/io_pins/io_timer.c

Allows i.mxrt platform to use A/B channel for each PWM timer

imxrt: flexpwm remove 1:1 mapping requirement

---

msg/LogMessage.msg

The use of `{` in the descriptive string `PX4_{WARN,ERR,INFO}` looks like a macro to the generated docs, and since that macro is not defined, vitepress doesn't render the page.
The easiest fix is to just expand this out. If needed in future we could fix the docs generation.

LogMessage.msg - expand out descriptive string

---

src/modules/commander/Commander.cpp

The commander stack gets small on one of our 64-bit targets; using the PX4_STACK_ADJUSTED solves this without affecting any of the mainstream targets.

commander: Use PX4_STACK_ADJUSTED to increase stack for 64-bit targets

---

src/modules/ekf2/EKF/ekf.h
src/modules/ekf2/EKF/gps_control.cpp
src/modules/ekf2/test/test_EKF_gps_yaw.cpp

True heading is of primary importance for GNSS fusion in order to align the body and NED frames. Following a heading measurement isn't really important in the NE fusion doesn't report any issue and resetting to a heading measurement when not needed can create more issues than it solves.
Also, recent experiments showed that dual-antenna GNSS receivers are sometimes diverging and re-converging during operation. Since this can occur several times during the mission and isn't a true failure of the system, marking it as faulty for the rest of the flight is too restrictive.
When North-East aiding is active (e.g.: GNSS pos/vel) , the heading estimate is constrained and consistent with the vel/pos aiding. Reset to GNSS heading should only occur if no N-E aiding is active or if the filter is not …

ekf2: Only reset to GNSS heading if necessary

---

src/modules/sensors/vehicle_angular_velocity/VehicleAngularVelocity.cpp

- this warning was to catch any potential errors in sensor selection relative to what's actually available, we don't need to complain about initial selection before the EKF selector is available

sensors/vehicle_angular_velocity: silence gyro selection fallback warning (PX4_WARN -> PX4_DEBUG)

---

src/systemcmds/sd_bench/sd_bench.cpp

Using `malloc()` you could still get an aligned memory address, when using `aligned = false` make sure the block we're benchmarking/testing on is unaligned.

sd_bench: make sure that unaligned is really unaligned

---

src/drivers/imu/analog_devices/adis16507/ADIS16507.cpp

Found a sensor where the self test sometimes fails on boot. If the driver goes back through the rest sequence, it will pass.

drivers: adis16507 reschedule reset after failed self test

---

src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_main.h

Regression from https://github.com/PX4/PX4-Autopilot/pull/23043
Also avoids a race condition by making sure the command ack is handled before sending out the mavlink message (in case an external component reacts immediately to the mavlink message).

fix mavlink: cmd_logging_{start,stop}_acknowledgement flags were not reset

---

Tools/check_submodules.sh

Same as what's required for VSCode.

Tools: skip submodule check in CLion

---

src/modules/mavlink/mavlink_ftp.cpp
src/modules/mavlink/mavlink_ftp.h

By ensuring there's a '/' in between when concatenating the path with _root_dir.
It turns out there's a bug in GQC where a component metadata uri like `mftp://etc/extras/component_general.json.xz` is turned into an ftp request with path `/etc/extras/component_general.json.xz`, whereas it should be `etc/extras/component_general.json.xz`.

mavlink_ftp: handle relative paths correctly 

---

src/drivers/gps/gps.cpp

I am checking the same variable value with different decision values.
Change to SWITCH statement.
None
None
None
None

gps: Change the IF statement to a SWITCH statement

---

src/modules/vtol_att_control/vtol_type.cpp

Local position and quadchute reference altitude have opposite signs, so the delta local position needs to be subtracted rather than added.

Quadchute: Fixed sign for handling altitude resets

---

src/modules/uxrce_dds_client/uxrce_dds_client.cpp

The uxrce-dds bridge is close to the stack limit. When topics are added (sensor_uwb alone is enough) stack overflows occour.
To fix that increasing the stack size of the uxrce-dds-client prevents that issue.

increased uxrce-dds stack size to prevent overflow

---

src/drivers/gps/params.c

This notes the reference yaw angle for the Septentrio Mosaic-H.
It's unfortunately a bit tricky in that Unicore has the main antenna in front by default while Septentrio decided to put the aux antenna in front.
FYI @vincentpoont2

gps: add note to param

---

boards/modalai/voxl2/README.md

The README file in the ModalAI VOXL 2 boards directory had some outdated information that was cleaned up.

Minor updates to the VOXL 2 board README file

---

src/modules/uxrce_dds_client/dds_topics.h.em
src/modules/uxrce_dds_client/utilities.hpp

When enabling subscriptions for ros topics in dds_topics.yml, the ros topics subscribed will be in /fmu/in/NAME_OF_TOPIC even when in the dds_topics.yaml, the topics name was set  to something else.
- Use the complete topic name path from dds_topics.yml to subscribe to the ROS topics instead of forcing the topic to be in /fmu/in/TOPIC_NAME. 
```
Bugfix: use the specified topic namt/path as described in dds_topics.yml
```
- Bench tested on Skynode. Added a new topic and check in the companion that the Micro uxrce agent created a subscriber for the exact same topic name.

uxcre_dds_client: use topic path as defined in the dds_topics.yaml

---

src/drivers/ins/vectornav/VectorNav.cpp

The link in the driver docs was pointing to "master" rather than "main" branch where docs live.

VectorNav.cpp - fix docs link to usage guide

---

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp

Increase lp default stack for targets such as the mr-canhubk3
Existing lp default stack size:
With the increased stack size:

increase lp default stack to 2000

---

.editorconfig

The setting wasn't consistent with the one used in the Visual Studio Code settings, which caused different newline formatting depending on whether the user uses Visual Studio Code or another editor that uses EditorConfig.
Fixes \/
- Change newline ending setting in the EditorConfig file to be consistent with the Visual Studio Code setting
```
```
Maybe remove the formatting settings from the Visual Studio Code `.vscode/settings.json` configuration file as the EditorConfig extension is now in the recommended list and it can therefore use the settings from the `.editorconfig` file.
\/
The original EditorConfig was based on the style in most files. After using it …

style(editorconfig): update newline setting

---

boards/mro/ctrl-zero-classic/init/rc.board_defaults

While working with this board I encountered that defining GPS2 in the serial port map does not affect the generated params (`generated_params/serial_params.c`). This board needs such definition because the port is intended for said purpose by design. 
``` c
/**
* Serial Configuration for Secondary GPS
*
* Configure on which serial port to run Secondary GPS.
*
* 
*
* @value 0 Disabled
* @value 201 GPS 1
* @value 202 GPS 2
* @value 101 TELEM 1
* @value 102 TELEM 2
* @value 103 TELEM 3
* @value 104 TELEM/SERIAL 4
* @group GPS
* @reboot_required true
*/
PARAM_DEFINE_INT32(GPS_2_CONFIG, 0);
```
- Assigned GPS_2_CONFIG to GPS2 
We could also consider this as a temporary workaround and modify the generation of parameters that assigns `202` to `GPS_2_CONFIG` whenever `CONFIG_BOARD_SERIAL_GPS2` is …

mRo Control Zero Classic: Enable GPS2 port by default

---

src/modules/ekf2/EKF/python/ekf_derivation/generated/predict_covariance.h
src/modules/ekf2/EKF/python/ekf_derivation/utils/derivation_utils.py
src/modules/ekf2/EKF/yaw_estimator/EKFGSF_yaw.cpp
src/modules/ekf2/EKF/yaw_estimator/derivation/derivation_yaw_estimator.py
src/modules/ekf2/EKF/yaw_estimator/derivation/generated/yaw_est_compute_measurement_update.h
src/modules/ekf2/EKF/yaw_estimator/derivation/generated/yaw_est_predict_covariance.h

- increase symforce CppConfig zero_initialization_sparsity_threshold so that a Matrix setZero() call is performed instead of individually zeroing
This saves ~ 1500 bytes of flash on px4_fmu-v5.

ekf2: symforce zero more efficiently

---

src/drivers/uavcan/uavcan_drivers/socketcan/driver/src/socketcan.cpp

Before doing a memcpy to our can_frame check if the size of the payload isn't bigger.
This avoids potential memory corruption.

dronecan: SocketCAN driver check size before copying

---

src/systemcmds/hardfault_log/hardfault_log.c

Extends hardfault_log fault tests
- Jumping to address 0x0
- Writiing to address 0x0
~~Depends on #23151~~  - merged

hardfault_log: Add jump to 0x0 & write 0x0 faults

---

src/modules/commander/HomePosition.cpp
src/modules/commander/HomePosition.hpp

When the vehicle is not yet armed and on the ground, the home position is allowed to change when it is detected that the vehicle position has changed. When the EKF estimator is initialized the home position is changed if the local position change is higher than the estimated deviations in eph and epv. Those can be pretty small number ( <15cm in my tests) although the altitude might change more. This leads to a lot of new home position changes before taking off. However those changes are unnecessary, as the home position is set again when taking off. Changing the home position that often can negatively influence other modules depending on the home position (as the e.g. the mission validity).
- Add a minimum horizontal distance of 1m needed horizontally and 1.5m vertically before changing …

HomePosition: Home position only changes on ground after minimum horizontal and vertical displacement

---

boards/mro/ctrl-zero-classic/init/rc.board_defaults

This is a backport from `main` to modify the default parameter of GPS2 for mRo Control Zero Classic.
Already been tested on HW and working without issues.

[BACKPORT] mRo Control Zero Classic: Definition for GPS2 by default added

---

src/drivers/cdcacm_autostart/cdcacm_autostart.cpp

Fixes logic if USB does not have data lines, ie powering the flight controller with USB wall wart. The module will stay in the `connecting` state and `px4_open()` will fail silently.
Closes https://github.com/PX4/PX4-Autopilot/issues/23179

cdcacm_autostart: handle USB with no data lines

---

msg/RtlStatus.msg
src/modules/navigator/mission_base.h
src/modules/navigator/rtl_mission_fast.cpp
src/modules/navigator/rtl_mission_fast.h
src/modules/navigator/rtl_mission_fast_reverse.cpp
src/modules/navigator/rtl_mission_fast_reverse.h

On a system with RTL_TYPE=2, the current behavior is that it will always start the RTL from the closes WP, and not from the current active one. If by chance e.g. WP 5 is closer than the current WP 2, it will go to 5. If there's an obstacle between 2 and 5 there is no way to ensure it won't hit it.
Only start from closest WP if not in Mission when RTL is started. Otherwise, if in Mission, the proceed mission from currently active one (case where it follows mission to the Land), or start from the previous item (if mission doesn't include a landing and it thus does it in reverse).  
```
Feature: do not leave mission path with RTL_TYPE=2 when RTL triggered in Mission
```
Basic SITL testing.

Navigator: do not leave mission path with RTL_TYPE=2 when RTL triggered in Mission

---

src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_main.h

When looking through the MAVLink implementation I found this commented out code to set a member that wasn't used for 10+ years. See: https://github.com/PX4/PX4-Autopilot/commit/346ae5b9f4fc2da13e6d890521f48768b6b6e8c2#diff-6128b04d894d13fd44974cb4c71a674ccd1338cbeb7e25c464f931fd666b7721
Remove it

MAVLink: remove never used `_mavlink_link_termination_allowed`

---

src/modules/vtol_att_control/standard.cpp
src/modules/vtol_att_control/standard.h
src/modules/vtol_att_control/vtol_att_control_main.cpp
src/modules/vtol_att_control/vtol_att_control_main.h
src/modules/vtol_att_control/vtol_type.h

The pusher ramp up time is much longer than set in the pusher slew rate param (`VT_PSHER_SLEW`). Reason is that we pass the `dt` from the main loop of the VTOL Attitude Controller to the `update_transition_state()`, which though is only run if a new attitude setpoint is present and thus would require a bigger `dt` to have the slew rate working correctly. 
Calculate the dt at the spot of usage.
```
Bugfix Standard VTOL: fix pusher transition ramp up slew rate
```

Standard VTOL: fix pusher transition ramp up slew rate

---

src/modules/camera_feedback/CameraFeedback.cpp

When checking CI failures I found that https://github.com/PX4/PX4-Autopilot/pull/23103 broke the automatic documenation generator by exceeding the maximum line length of the parser.
This was flagged by CI also on the PR see https://github.com/PX4/PX4-Autopilot/actions/runs/9184141819/job/25255983514 but apparently ignored presumably because other checks are failing on main.
Shortening the lines.
I ran the documentation target locally to verify this change makes it run through.

CameraFeedback: shorten line length such that documentation parser works

---

msg/LoggerStatus.msg
src/modules/commander/HealthAndArmingChecks/CMakeLists.txt
src/modules/commander/HealthAndArmingChecks/HealthAndArmingChecks.hpp
src/modules/commander/HealthAndArmingChecks/checks/loggerCheck.cpp
src/modules/commander/HealthAndArmingChecks/checks/loggerCheck.hpp
src/modules/logger/logger.cpp
src/modules/mavlink/streams/SYS_STATUS.hpp

I have a piece of companion software that automatically downloads flight logs from the vehicle over mavlink and uploads them to a server. I need to know when the logger is running or not so that I don't try to download a log file which is being actively written to (results in a partial log download and repeated downloads).
The mavlink SYS_STATUS message can tell us if the logger is running or not. We just need to check the LoggerStatus in the health and arming checks and set the MAV_SYS_STATUS_LOGGING bit.

[HealthCheck] Logger (is_logging?)

---

.ci/Jenkinsfile-compile

In https://github.com/PX4/PX4-Autopilot/pull/22829 the Jenkins build for the new board was added here:
https://github.com/PX4/PX4-Autopilot/commit/528ad1e87d4aba286be9a5133ba775e922d2005b#diff-1b600ac63a07cb41bf62e2cf4c19fcd9cc6b4ff52b35acb181383e44b839db37R50
but the comma was forgotten, this makes Jenkins fail on main with a Syntax error:
Add the missing comma.
I can't test locally but I'm confident it will fix at least this error and show us the next one.

Jankinsfile-compile: add missing comma after `ark_pi6x_default`

---

integrationtests/python_src/px4_it/mavros/mission_test.py

When running the test for `yaw_error_std`, it was observed that the test was flaky with the threshold set at 13.0.
Similar issue from #22061
- Increased the threshold for `yaw_error_std` from 13.0 to 15.0 to address flakiness.
```
Bugfix: Increased yaw_error_std test threshold from 13.0 to 15.0.
```
We could also look into the root cause in [ulog.py](https://github.com/dronecrew/px4tools/blob/ff33b269c58691a6f2de9de006f73c5bdda60658/px4tools/ulog.py#L517).

Increase threshold for yaw_error_std

---

platforms/qurt/CMakeLists.txt
platforms/qurt/c++.cpp
platforms/qurt/new_delete.cpp

The qurt platform is using one of multiple heaps available that only has 700KB of space. This PR changes that heap to one
with 3MB and is not shared with any other services. This is important because the qurt platform will crash if a C++ new operator operation fails so it needs to have a nice safety margin in the heap size. In order to use the larger heap the new and delete operators had to be overridden. To avoid a crash when a new operation fails all of the PX4 code would need to move from "new" to "new (nothrow)" but that's a whole different discussion.

Increased the size of the memory heap available to qurt platform

---

test/mavsdk_tests/test_multicopter_offboard.cpp

MC Offboard CI test failing, e.g. https://logs.px4.io/plot_app?log=aedb8d55-be3f-44d4-b323-667e3dfa872b.
It's failing because it is drifting more than 1m away from the Home position during the offboard_land() (velocity controlled). 
Possible reasons as seen in log file:
- estimator keeps estimating a downward velocity, even after ground contact (see top right)
- estimator underestimates the vx drifting rate
It would be interesting to know if there indeed is an issue with the estimator, or if it's simulation related. 
The proposal as in this PR can be applied if no estimator fix can be done: increasing the acceptance radius for an offboard landing from 1 to 2m.
- fix simulation and/or estimation
- use land() instead of offboard_land() (then it stays in a position controlled mode, instead …

mavsdk_tests: increase acceptance radius for position check on offboard landing

---

src/modules/ekf2/EKF/aid_sources/gnss/gps_control.cpp

When fusing GNSS 3D velocity and not lat/lon, the control logic continuously resets the velocity state as the position fusion timeout triggers at every loop. This makes the flight task trajectory setpoint reset and results in a constant oscillation of the drone.
Ignore position timeout when GNSS lat/lon is disabled.
Split GNSS control flag (velocity and hpos)
Reproducible in SITL.
Main:
This PR:

Fix oscillations when using GNSS velocity fusion only

---

ROMFS/px4fmu_common/init.d-posix/airframes/1033_jsbsim_rascal
ROMFS/px4fmu_common/init.d-posix/airframes/1034_flightgear_rascal-electric
ROMFS/px4fmu_common/init.d-posix/airframes/1036_jsbsim_malolo
ROMFS/px4fmu_common/init.d-posix/airframes/1039_flightgear_rascal
ROMFS/px4fmu_common/init.d/airframes/13013_deltaquad
src/modules/navigator/mission_params.c

A too low value on this check is very annoying and not really necessary. It's main purpose is to prevent a mission plan that was not planned at the current flight location to be executed.
Increase default to 10km. 
I've also removed a custom setting of MIS_DIST_1WP from some aiframes that I think is not needed anymore. 
```
Improvement: Increase default of MIS_DIST_1WP to 10km
```
We could also remove the check around MIS_DIST_1WP completely?

Increase default of MIS_DIST_1WP to 10km

---

boards/hkust/nxt-dual/src/hw_config.h

To fix ”hjust_nxt-dual board_config: disable FLASH_BASED_PARAMS to fix CI”
closes #23197

board hkust_nxt-dual fix hw_config.h missing APP_RESERVATION_SIZE, which causes CI bug

---

ROMFS/px4fmu_common/init.d/rcS
src/systemcmds/bsondump/bsondump.cpp

```nsh> dmesg
ERROR [parameters] BSON document size (0) doesn't match bytes decoded (984)
ERROR [parameters] BSON document size (0) doesn't match bytes decoded (984)
ERROR [parameters] BSON document size (0) doesn't match bytes decoded (984)
ERROR [param] importing from '/fs/mtd_caldata' failed (-1)
INFO  [param] selected parameter default file /fs/mtd_params
INFO  [param] importing from '/fs/mtd_params'
INFO  [parameters] BSON document size 1052 bytes, decoded 1052 bytes (INT32:25, FLOAT:25)
INFO  [param] selected parameter backup file /fs/microsd/parameters_backup.bson
Board architecture defaults: /etc/init.d/rc.board_arch_defaults
...
INFO  [logger] Opened full log file: /fs/microsd/log/2024-05-02/08_49_46.ulg
...
nsh> bsondump /fs/mtd_caldata
[bsondump] reading from /fs/mtd_caldata …
```

check if bson document size is set to zero and set to decoded size

---

platforms/common/uORB/ORBSet.hpp
platforms/common/uORB/uORBManager.cpp

On VOXL 2 platform where CONFIG_ORB_COMMUNICATOR is used there was a small memory leak where a topic name was being added to an ORBSet even if it was already in there. This PR fixes that so it's only added if it isn't in there already.

Fixed a small memory leak in uORBManager.cpp

---

src/modules/commander/HealthAndArmingChecks/checks/magnetometerCheck.cpp

Previously, if a mag was not required (not index 0 and not used by ekf), it was not counted in num_enabled_and_valid_calibration. If a user set SYS_HAS_MAG to e.g. 3, it would then trigger a preflight failure, even if there were 3 calibrated and enabled mags.

fix commander: make sure to count all valid mags in preflight check

---

src/modules/ekf2/EKF/aid_sources/magnetometer/mag_control.cpp
src/modules/ekf2/EKF/common.h
src/modules/ekf2/EKF2.cpp
src/modules/ekf2/module.yaml

I've seen several users that would like to fly without the mag but also being able to takeoff in position/auto mode. This is currently not possible as INS/GNSS heading alignment requires motion.
Add a new mag type less restrictive than "NONE" that lets run the mag fusion (i.e.: `cs_mag`) that is only allowed to align yaw and update the mag states. The implementation is as simple as "not being one of the other modes".
```
Add mag type INIT
Documentation: TBD
```
SITL tests

ekf2: add mag type init

---

boards/px4/fmu-v6xrt/src/board_config.h

Updates IMXRT driver to support RC telemetry.
Also changes rc_input singlewire mode to pushpull for better signalling.
~~Pending on PX4/NuttX#307~~

fmu-v6xrt lpuart singlewire for RC telemetry

---

src/modules/differential_drive/DifferentialDrive.cpp

When calling "differential_drive stop" during a simulation involving a robot with differential drive like r1_rover, a missing return statement in DifferentialDrive.cpp was causing a segmentation fault due to access to already freed memory.
Fixes issue #22818
Adding a return statement after line 68 solves the issue.

Solving Segmentation Fault on "differential_drive stop" (Patch for issue #22818)

---

src/modules/control_allocator/ControlAllocator.cpp

In `src/modules/control_allocator/ControlAllocator.cpp`, there was an incorrect comparison between a float variable `dt` representing seconds and a `uint64_t` value representing 5 milliseconds (`5_ms` = 5000). As a result, `do_update` could never become true, even if the last torque setpoint had been received more than 5 milliseconds before. I didn't find any issue linked to this.
To solve this, the `5_ms` value has been converted to seconds (0.005f) for the comparison with `dt`.

Fix seconds vs milliseconds comparison in ControlAllocator.cpp

---

src/drivers/imu/murata/sch16t/Murata_SCH16T_registers.hpp
src/drivers/imu/murata/sch16t/SCH16T.cpp
src/drivers/imu/murata/sch16t/SCH16T.hpp
src/drivers/imu/murata/sch16t/parameters.c
src/drivers/imu/murata/sch16t/sch16t_main.cpp

- Added perf counters for the individual errors
- don't report saturation as an error (instead it's just reported as clipping)
- use only ACC2 (decimated 8G range)
- added parameters to configure gyro / accel filter and decimation ratio

driver: imu: sch16t: improvements

---

src/modules/mavlink/mavlink_ftp.cpp
src/modules/mavlink/mavlink_ftp.h
src/modules/mavlink/mavlink_log_handler.cpp
src/modules/mavlink/mavlink_log_handler.h
src/modules/mavlink/mavlink_main.cpp
src/modules/mavlink/mavlink_main.h
src/modules/mavlink/mavlink_mission.cpp
src/modules/mavlink/mavlink_mission.h
src/modules/mavlink/mavlink_parameters.cpp
src/modules/mavlink/mavlink_parameters.h
src/modules/mavlink/mavlink_receiver.cpp
src/modules/mavlink/mavlink_receiver.h
src/modules/mavlink/mavlink_tests/mavlink_ftp_test.cpp
src/modules/mavlink/mavlink_tests/mavlink_ftp_test.h
src/modules/mavlink/mavlink_timesync.cpp
src/modules/mavlink/mavlink_timesync.h

When working on limiting autopilot access from a MAVLink instance configured for gimbal use I found that:
- In MAVLink receiver there is no single function processing a message that could be diverted to achieve what I need.
- All client protocols (except events) that are called from MAVLink receiver hold a raw pointer to the main MAVLink instance they operate on without safely handling the null pointer case.
- I moved all subprotocol message handling into the `MavlinkReceiver::handle_message()` function so that it ends up processing all messages from all protocols.
This allows for limiting access depending on the MAVLink profile/mode. I can follow up with this functionality but I didn't want to blow up this pull request more.
- Refactor the MAVLink receiver and all client protocol classes …

MAVLink: refactor message handling in one function, reference instead of pointer to main instance

---

platforms/posix/src/px4/common/px4_daemon/server.cpp

When I try to run a startup script I found that the system() call for that startup script was triggering a daemon server error that shuts down the socket early. Looks like another developer had handled this case by trying to ignore the specific errno for that system() triggered error, but left the `break` of that socket while loop outside of that errno check. 
Moved `break` into the if errno check
- Fixed daemon server errno handling bug

Only close server when errno is not EINTR

---

boards/px4/fmu-v6xrt/nuttx-config/scripts/itcm_functions_includes.ld
src/modules/ekf2/EKF/aid_sources/magnetometer/mag_control.cpp
src/modules/ekf2/EKF/ekf.h

- the additional hysteresis logic for "yaw angle observable" was needed when it controlled time dependent mag_3d

ekf2: merge mag yaw angle observability into heading consistency

---

src/modules/ekf2/EKF/aid_sources/magnetometer/mag_control.cpp

- we also need to clear mag_aligned_in_flight

ekf2: stopMagFusion() reset yaw_align if mag heading was active

---

Tools/setup/requirements.txt

The argparse module has been builtin to Python since Python 3.2, released in 2011 (see
https://docs.python.org/3/whatsnew/3.2.html).  Further, the argparse pip module has not been released or updated since 2015, and lacks some of the features of the modern, built-in argparse.  Drop the pip installed version in favor of the built-in version.
It was reported to ROS 2 that it couldn't be properly run after installing PX4; see https://github.com/ament/ament_cmake/pull/500 .  However, we prefer not to put in a workaround, because that actually downgrades functionality.  Instead, I think it makes sense to drop this dependency from PX4, and use the built-in Python version.
Remove argparse from the requirements.txt.
```
Dropped argparse from requirements.txt, as it is built-in …
```

Remove argparse from the requirements.txt.

---

Tools/setup/arch.sh

Fix error of script failing with following error:
PX4-Autopilot/Tools/setup/arch.sh: line 99: syntax error near unexpected token `;'
When running the script it failed with following error:
`./Tools/setup/arch.sh: line 99: syntax error near unexpected token ';'`
- Added missing \ in the script
- Script worked after changes

arch.sh: Fix syntax error

---

src/lib/battery/battery.cpp
src/lib/battery/battery.h

VTOLs consume a lot more power in hover compared to fixed-wing flight. The remaining flight time thus should reset if one switches from MC to FW, as otherwise it takes several minutes until the estimate goes down.
```
Improvement: battery: reset current filter when transitioning to FW
```
Only update the filter in FW for VTOL. As VTOLs though also can have full hover flights this is for me the worse option.

battery: reset current filter when transitioning to FW

---

msg/VehicleAttitudeSetpoint.msg
src/modules/fw_pos_control/fw_path_navigation_params.c

Just two comment fixes that I was made aware of recently.

Specify which modes apply FW_PN_R_SLEW_MAX and fix comment for attitude_setpoint.thrust_body

---

src/modules/vtol_att_control/tailsitter.cpp
src/modules/vtol_att_control/tailsitter.h
src/modules/vtol_att_control/vtol_type.cpp
src/modules/vtol_att_control/vtol_type.h

Various throttle spikes and jumps during tailsitter transitions, see screenshot:
The spikes are caused by the VTOL module selecting the FW rate controller output even when it doesn't have anything published yet, resulting in a publication of 0. The same happens during the initial phase of the back transition, as there the MC rate controller hasn't published yet.
The jumps are coming form different thrust level outputs of the MC vs FW controllers.
- Fix the spikes by waiting 50ms until the new controller output is used.
- Add ramps similar to what we already do for tiltrotor and standard VTOL.
- also wait for differential throttle in FW until 50ms have passed
```
Improvement: Tailsitter: remove thrust spikes around entering/leaving transition modes. 
```
The transition …

Tailsitter: remove thrust spikes around entering/leaving transition modes
