platforms/nuttx/src/px4/common/SerialImpl.cpp
If you pass a value of zero as the baudrate the entire system hangs
=> platforms: nuttx: SerialImpl: fix hang if baudrate is 0

Tools/setup/ubuntu.sh
When I tried to go through PX4 tutorials installing on Linux Mint, I found that it had issues with the version and codename.
- Added support for detecting and handling Linux Mint 21.3 in the `ubuntu.sh` script.
- Ensured the correct JRE/JDK version is installed for Linux Mint 21.3.
- Updated package installation and configuration steps to include Linux Mint 21.3.
- Added repository and installation steps for Gazebo specific to Linux Mint 21.3.
=> Update ubuntu.sh with Linux Mint 21.3 version

boards/holybro/kakutef7/init/rc.board_defaults, boards/holybro/kakuteh7/init/rc.board_defaults, boards/holybro/kakuteh7mini/init/rc.board_defaults, boards/holybro/kakuteh7v2/init/rc.board_defaults
When checking the latest release 1.14.3, I found that the modification in #21961 is a good start.
But there is a typo of EKF2_IMU_CTRL (EKF2_IMU_CONTROL in the codes).
- Fix the param typos for kakute f7/h7/h7mini/h7v2
=> kakute f7/h7/h7mini/h7v2: fix EKF2_IMU_CTRL typo

src/modules/airspeed_selector/AirspeedValidator.hpp, src/modules/airspeed_selector/airspeed_selector_main.cpp, src/modules/airspeed_selector/airspeed_selector_params.c
Using integers for the airspeed selector start / stop delay parameters did not provide sufficient granularity in practice.
Also reduce the default hysteresis time for declaring airspeed invalid from 2 to 1.
Define those parameters as floats.
```
ASPD_FS_T_START and ASPD_FS_T_STOP can now be set to floating points values.
```
=> Define airspeed selector start stop params as floats

src/modules/gimbal/gimbal.cpp, src/modules/gimbal/input_mavlink.cpp, src/modules/gimbal/input_rc.cpp, src/modules/gimbal/output_rc.cpp, src/modules/mavlink/mavlink_main.cpp
Backport of https://github.com/PX4/PX4-Autopilot/pull/23236
=> [BACKPORT v1.15] gimbal: fix auto RC and MAVLink mode

src/modules/airspeed_selector/AirspeedValidator.cpp, src/modules/airspeed_selector/AirspeedValidator.hpp
The additional hardcoded delay of 1 second on the airspeed innovation check does not add any value as the check itself uses an integrator to trigger and just makes analyzing a failure in a log file more difficult.
There is a separate parameter to control the delay between a detecting a failure and declaring airspeed invalid.
Remove the additional delay.
```
Remove additional 1 second of delay from airspeed innovation check.
```
=> AirspeedValidator: Remove extra delay from airspeed innovation check

src/lib/matrix/matrix/Matrix.hpp
Follow up from https://github.com/PX4/PX4-Autopilot/pull/22629, found while working on https://github.com/PX4/PX4-Autopilot/pull/23245. It's quite hard to read a print of a matrix that omits some of the elements because they are symmetric at this very point, but not the full matrix is.
With current main:
After this PR:
=> Matrix: print full matrix already if only one element is not symmetric

src/modules/ekf2/EKF/aid_sources/optical_flow/optical_flow_control.cpp
A flow sensor should publish a maximum distance to the ground below which it's expected to work well.
If the distance to the ground exceeds this value the estimator should not fuse these samples.
In this particular case we were using the Ark flow sensor which happens to work reliably up to about 10m.
```
Feature: EKF: Don't fuse optical flow samples when distance to the ground exceeds maximum flow sensor distance.
```
=> Don't fuse optical flow samples when distance to ground is above sensor limits

ROMFS/px4fmu_common/init.d-posix/airframes/4004_gz_standard_vtol
Standard VTOL accelerates a lot during transition and gets unstable while trying to loiter.
Reduce VT_F_TRANS_THR from 0.75 to 0.3
We could also add some other parameters which were also used in the gazebo-classic model? Improve model itself?
with 0.75
with 0.3
=> reduce transition pusher throttle

.vscode/settings.json
Generally I'm trying to not be too opinionated with the default config, but it's quite important to see (and set) the current PX4 config or quite a lot won't resolve properly in the IDE.
=> vscode: cmake default status bar visibility

src/modules/airspeed_selector/AirspeedValidator.cpp, src/modules/airspeed_selector/AirspeedValidator.hpp, src/modules/airspeed_selector/airspeed_selector_main.cpp
Compared to GNSS, alternate position observation methods are less accurate and thus generally not good enough to do airspeed validation with. Airspeed validation is thus disabled if no GNSS fusion is happening.
```
Improvement: Only do airspeed scale estimation and airspeed validation with valid GNSS fusion
```
- Directly fuse GNSS into the airspeed validator (to then be used for wind estimate), instead of using local_position but only if GNSS is fused --> I think this is the way to go, but we then need to figure out how to do signal validation (is using `estimator_gps_status.checks_passed enough`?).
=> AirspeedSelector:  Only do airspeed scale estimation and airspeed validation with valid GNSS fusion

src/drivers/magnetometer/isentek/ist8310/IST8310.cpp
Apparently, the IST8310's WHOAMI register is writeable. Presumably, this can get corrupted by bus noise. It is only reset if powered off for 30s.
Therefore, we do a reset before doing the WHOAMI.
Credit goes to:
https://github.com/ArduPilot/ardupilot/pull/26929
Testing done: Verified that the sensor still works. I have not tried to reproduce the failure case.
=> ist8310: do reset before WHOAMI call

platforms/nuttx/src/px4/common/SerialImpl.cpp, platforms/posix/src/px4/common/SerialImpl.cpp
A microsecond time was being passed to `poll()`, which takes a millisecond timeout. Also if the elapsed time was already greater than the timeout an integer underflow would occur which causes poll to block forever.
- fix poll timeout
- fix integer underflow
=> platforms: nuttx: SerialImpl: fix poll timeout and integer underflow

.github/workflows/checks.yml
#22957 Introduced allyes config but CI wasn't compiling them.
This PR adds the px4_sitl_allyes to the CI workflows.
=> Add px4_sitl_allyes to CI target

msg/CMakeLists.txt, msg/FuelTankStatus.msg, src/drivers/uavcan/CMakeLists.txt, src/drivers/uavcan/Kconfig, src/drivers/uavcan/sensors/fuel_tank_status.cpp, src/drivers/uavcan/sensors/fuel_tank_status.hpp, src/drivers/uavcan/sensors/sensor_bridge.cpp, src/drivers/uavcan/uavcan_params.c, src/lib/parameters/px4params/srcparser.py, src/modules/logger/logged_topics.cpp, src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_messages.cpp, src/modules/mavlink/streams/FUEL_STATUS.hpp
Implemented support for fuel tank status reporting via MAVLink using the new `FUEL_STATUS` message.
- Added support to DroneCAN `FuelTankStatus` messages
- Added `fuel_tank_status` uORB message
- Added `FUEL_STATUS` MAVLink stream
- Added `UAVCAN_ECU_MAXF` parameter to define max fuel tank capacity
- Added `UAVCAN_ECU_FUELT` parameter to set the fuel type
Note that https://github.com/mavlink/mavlink/pull/2112 needs to be merged as well. This validated the implementation in https://github.com/mavlink/mavlink/pull/2107.
```
New Feature: Added support for fuel tank status reporting via MAVLink.
New parameter: UAVCAN_ECU_MAXF
New parameter: UAVCAN_ECU_FUELT
New paremeter: UAVCAN_SUB_FUEL
```
Data currently is fetched from DroneCAN, but can also be generated through an ECU …
=> Add fuel tank status support

src/drivers/magnetometer/isentek/ist8310/IST8310.cpp
Read WHOAMI and only reset/sleep if it fails to return the expected device ID. The datasheet specifies up to 50ms for reset so we try to read WHOAMI multiple times for up to 50ms before failing
=> drivers: magnetometer: ist8310: more effecient probe()

boards/px4/fmu-v6xrt/init/rc.board_sensors
=> fmu-v6xrt: Fix redundant 'fi'

src/modules/logger/logged_topics.cpp
Hi, 
for full system identification, the motor commands as well as the observed acceleration are required to be logged at high frequencies. We are working on a system identification utility that people can use to find accurate dynamics parameters for their quadrotors just based on about a minute of flying data. 
The utility is available at [https://sysid.tools](https://sysid.tools) and the only missing piece is that people have to modify PX4 and re-compile/flash to include high-frequency logging of `actuator_motors` and `vehicle_acceleration` to be able to use it. Hence we propose to include it in the "Topics for system identification" option of the `SDLOG_PROFILE` parameter. By default, this option is deactivated so it will not affect most users, and even for users that have it enabled …
=> Adding vehicle_acceleration and actuator_motors to the logged topics for system identification

ROMFS/px4fmu_common/init.d/rcS, src/lib/systemlib/system_params.c, src/modules/mavlink/mavlink_parameters.cpp
When working on multiple projects I found that many reintroduced a mechanism to allow automatically resetting the parameter configuration during a product update. This functionality was initially introduced in https://github.com/PX4/PX4-Autopilot/pull/11760 and removed again in https://github.com/PX4/PX4-Autopilot/pull/17279 because we (including me) thought that the `param set-default` mechanism of https://github.com/PX4/PX4-Autopilot/pull/16796 would solve all the cases. But the case where the airframe maintainer wants to enforce a reset to airframe defaults is not covered anymore with the `param set-default` mechanism. For products based on PX4 this is still required to ensure proper functionality after a major update.
I suggest to reintroduce what was removed in …
=> Reintroduce optional parameter versioning mechanism for airframe maintainers

src/lib/mathlib/math/Functions.hpp, src/modules/mc_pos_control/MulticopterPositionControl.cpp, src/modules/mc_pos_control/MulticopterPositionControl.hpp, src/modules/mc_pos_control/multicopter_position_control_params.c
In some situations vibration in accelerometer data can be sufficiently bad that it's visible in the velocity estimate, which then becomes even more problematic when the multicopter position controller differentiates that velocity.
This pull request adds new optional filtering mechanisms in the multicopter position controller.
- **MPC_VEL_LP**: new velocity first order low pass filter (off by default)
- **MPC_VEL_NF_FRQ**/**MPC_VEL_NF_BW**: new velocity notch filter (off by default)
- **MPC_VELD_LP**: existing velocity derivative low pass filter, but I've dropped the remaining controllib usage
=> mc_pos_control: new low pass (MPC_VEL_LP) and notch filter (MPC_VEL_NF_FRQ/MPC_VEL_NF_BW)

platforms/common/Serial.cpp, platforms/common/include/px4_platform_common/Serial.hpp, platforms/nuttx/src/px4/common/SerialImpl.cpp, platforms/posix/src/px4/common/SerialImpl.cpp, platforms/qurt/src/px4/SerialImpl.cpp
There are currently three users of the new Serial driver (Septentrio GNSS, CRSF, and GPS). They all assume that the timeout for the readAtLeast call is specified in milliseconds but it is actually specified in microseconds. On top of this there was a bug where the implementation was actually using the microsecond timeout as an argument to a function that needed milliseconds and that was fixed in PR #23248. But because users were expecting milliseconds the timeout was now way too short and it caused CPU utilization to spike as the read kept timing out. See issue #23289. This PR changes the timeout to milliseconds to align with what the users are expecting.
=> Changed Serial readAtLeast timeout from microseconds to milliseconds

src/modules/gimbal/input_mavlink.cpp
I debugged a case where the auto setting for `MNT_MODE_IN` would not work: The mavlink input just stayed active after being engaged once, adjusting primary control would not suffice to enable RC control.
Turns out that if the mavlink_input just once returned UpdatedActive, it would keep doing so until e. g. a `VEHICLE_CMD_DO_GIMBAL_MANAGER_PITCHYAW` is received (there, UpdatedActiveOnce is returned instead).
This corner case is a combination of the following issues:
- in the input object list, mavlink comes first: https://github.com/PX4/PX4-Autopilot/blob/9c83f842bee11e3942e578377245b6a3fc9b5a7d/src/modules/gimbal/gimbal.cpp#L116-L123. Therefore, if we receive an UpdatedActive from mavlink input, we will never check what the RC is doing: …
=> gimbal - input_mavlink: return NoUpdate by default

src/modules/gimbal/input_mavlink.cpp
Backport of https://github.com/PX4/PX4-Autopilot/pull/23288.
=> [BACKPORT v1.15] gimbal - input_mavlink: return NoUpdate by default

src/modules/mavlink/CMakeLists.txt
The mavlink generator command silently succeeds even though the logs could contain errors.
When working through a hard to debug error I found that the generation command for a dialect can silently fail and since the uavionix dialect is still included in most places the some builds succeed without the primary dialect included while other specific test builds that don't contain the uavionix dialect (mavlink FTP test) fail unexpectedly.
Use https://github.com/ArduPilot/pymavlink/pull/863 to flag the error. I'll propose to make that default in pymavlink.
It's much more developer friendly to fail early in case of an error. The log path is then also shown in the console output.
```
Bugfix: Fail build early if MAVLink generation has an error
```
I ran this locally while debugging and lo and …
=> Bugfix: Fail build early if MAVLink generation has an error

src/drivers/rc/crsf_rc/CrsfRc.cpp
When sending CRSF telemetry, the GPS message provided an incorrect value for altitude [m]. This is because the existing PX4 code assumed the altitude_msl_m in the SensorGPS uORB message was in units of mm, instead of m.  
Removed scaling of the altitude in the uORB message  by 1000. 
Bugfix for CRSF GPS telemetry
Tested with ELRS transmitter in the loop to confirm correct values.
=> Correct units of CRSF GPS altitude

src/modules/navigator/mission.cpp, src/modules/navigator/mission_base.cpp, src/modules/navigator/rtl_mission_fast.cpp
When a mission is planned including a vtol takeoff item while the VTOL is already in Air and converted to a fixed wing, the VTOL immediately accepts the takeoff item, but is using an altitude ramp to the next waypoint item. This is due to the fact that although the vtol takeoff item is accepted immediately, it is still set as the position setpoint previous item including the transition altitude specified. This results in the VTOL losing altitude up to the transition item when the current altitude is higher. It should completely ignore the vtol takeoff item when already airborne.
- For all mission modes, ignore the VTOL Takeoff item if the vehicle is already in Air and already transitioned to fixed wing.
```
Bugfix Ignore VTOL takeoff when …
```
=> mission: skip a vtol takoff mission item if already in air

src/modules/ekf2/module.yaml
For both logging (https://github.com/PX4/PX4-Autopilot/pull/23306), safety, and minor memory optimization I think EKF2_EV_CTRL and EKF2_AGP_CTRL should be off by default.
Arguably nearly everything (except IMU) would be off by default and enabled per board and per airframe, but at the moment I don't think that's worth the hassle.
=> ekf2: disable EKF2_EV_CTRL and EKF2_AGP_CTRL by default

src/drivers/uavcan/sensors/gnss.cpp
Certain CAN GPS without position covariance will result in the system time not being set.
=> can gps set system time based on fix_type instead of valid_pos_cov

src/modules/ekf2/EKF/ekf.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/height_control.cpp
I've seen examples where the clipping detection fault status triggers due to very brief clipping (that didn't actually damage the velocity estimate), but causes more harm due to rapid estimator selection switching.
Ideally we'd collect more logs with sufficient clipping that the velocity estimate was ruined, and then tune this appropriately.
Note we still have clipping projections that boost the accel process noise, pause bias estimation, and skip gravity fusion on a per sample basis. 
https://github.com/PX4/PX4-Autopilot/blob/408d8abe959d71d843d48843bd6c050d70973e31/src/modules/ekf2/EKF/covariance.cpp#L123-L125
=> ekf2: more conservative clipping checks before declaring bad_acc_clipping fault status

ROMFS/px4fmu_common/init.d/airframes/4601_droneblocks_dexi_5, msg/BatteryStatus.msg, src/lib/battery/battery.cpp, src/lib/battery/battery.h, src/lib/battery/int_res_est_replay.py, src/lib/battery/module.yaml, src/lib/matrix/matrix/SquareMatrix.hpp, src/modules/ekf2/EKF/ekf.h
The volt-based estimation of the state of charge (SoC) currently uses a standard value for the internal resistance (IR) of the battery to compensate drops in the measurement of the voltage due to current draw.
If a battery is used that does not conform to this standard value it can lead to over/-underestimation and fluctuations of the volt-based SoC.
This PR implements an algorithm for online estimation of the battery IR to improve the volt-based SoC estimation. 
The algorithm is based on an approximation of the battery dynamics with an equivalent circuit model (ECM) consisting of the open-circuit voltage (OCV) and the IR of the battery:
The open-circuit voltage is the "actual voltage" of the battery which is used for the volt-based SoC estimation.
The ECM leads to the following equation: …
=> Online battery internal resistance estimation

src/modules/mavlink/mavlink_receiver.cpp
Fix the stack-buffer overflow vulnerability in the mavlink_receiver.cpp
Here is the reference link：https://github.com/PX4/PX4-Autopilot/security/advisories/GHSA-55wq-2hgm-75m4
=> Fix buffer overflow in mavlink_receive.cpp

boards/modalai/voxl2-slpi/src/drivers/dsp_hitl/dsp_hitl.cpp, msg/BatteryStatus.msg, src/drivers/batt_smbus/batt_smbus.cpp, src/drivers/cyphal/Subscribers/legacy/LegacyBatteryInfo.hpp, src/drivers/osd/atxxxx/atxxxx.cpp, src/drivers/osd/atxxxx/atxxxx.h, src/drivers/rc/crsf_rc/CrsfRc.cpp, src/drivers/rc_input/crsf_telemetry.cpp, src/drivers/rc_input/ghst_telemetry.cpp, src/drivers/smart_battery/batmon/batmon.cpp, src/drivers/tattu_can/TattuCan.cpp, src/drivers/uavcan/sensors/battery.cpp, src/lib/battery/int_res_est_replay.py, src/lib/drivers/smbus_sbs/SBS.hpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/streams/BATTERY_STATUS.hpp, src/modules/mavlink/streams/SYS_STATUS.hpp
In https://github.com/PX4/PX4-Autopilot/pull/23205 we removed the filtering of voltage and current as it's not used anymore in the battery SOC estimate. We though didn't yet remove the fields in the battery_status message, which are instead just not filled.
Remove the "filtered" fields from the BatteryStatus message. I argue that it is better to publish only the directly measured value instead of the filtered one. Reason: the amount of filtering is arbitrary, and there is likely no "optimal" way, it always a tradeoff between smoothness and delay. If the consumer of the BatteryStatus wants to do filtering before it is sent further it can be done there, though I personally am not convinced that it is needed. I as a pilot would prefer to see the raw measurement in the telemetry instead of a …
=> BatteryStatus: remove filtered voltage/current fields

src/drivers/gnss/septentrio/module.h, src/drivers/gnss/septentrio/module.yaml, src/drivers/gnss/septentrio/sbf/messages.h, src/drivers/gnss/septentrio/septentrio.cpp, src/drivers/gnss/septentrio/septentrio.h
During further internal testing of the new Septentrio driver, a few usability problems and two bugs were discovered. I know it's better to create small dedicated PRs, but as there are so many small tweaks and the driver is still very new, I'm creating one big pull request to apply all these fixes at once.
We've also tested this PR internally and it solves all of the problems listed below and cleans up/documents the code a bit further where it made sense.
- Fix failure to configure by reordering configuration steps
- Fix broken heading (missing `== PX4_OK` in check)
- Fix for possible timeout while stopping the driver (split baud rate detection using state machine)
- Fix duplicate usage instruction when executing `septentrio reset`
- Add some error messages that are shown in the global …
=> gnss(septentrio): driver general usability and bug fixes

ROMFS/px4fmu_common/init.d/rcS, Tools/px4airframes/rcout.py
When updating a vehicle configuration I had the requirement to not change the startup ID (`SYS_AUTOSTART`) but want to move the airframe file from the SD card to ROMFS.
Of course I can just remove the logic to load any airframe from the SD card from that vehicle but that would make that part custom. While going through what prevents the current logic from achieving the goal I stumbled across the number partitioning of external airframes needing to have numbers > 1'000'000 which was already talked about here: https://github.com/PX4/PX4-Autopilot/pull/18459#discussion_r732107774 I talked with @ThomasDebrunner about why there's no fallback for looking for airframes in the currently available two locations ROMFS and SD card except for when the SD card is completely missing.
My proposal is to …
=> Autostart: load all airframes IDs with priority ROMFS -> SD card

src/drivers/cyphal/Actuators/EscClient.hpp, src/drivers/cyphal/Cyphal.cpp, src/drivers/cyphal/Cyphal.hpp, src/drivers/cyphal/ParamManager.cpp, src/drivers/cyphal/ParamManager.hpp, src/drivers/cyphal/PublicationManager.cpp, src/drivers/cyphal/PublicationManager.hpp, src/drivers/cyphal/SubscriptionManager.cpp, src/drivers/cyphal/SubscriptionManager.hpp, src/drivers/cyphal/parameters.c
This PR includes Cyphal ESC improvements and some fixes to simplify configuration with Yukon. It is based on notes mentioned [in the forum](https://discuss.px4.io/t/zubax-myxa-and-cyphal-integration/31404/1) and in the previous Cyphal PR. 
I've started with a draft PR, so you can track the progress and give a earlier feedback.
I will attach it when it is ready.
=> improve cyphal esc

msg/BatteryStatus.msg
All these fields in the battery message aren't filled or used anywhere in PX4, so I don't see why they should be in the mainline PX4. Seemed to been [introduced](https://github.com/PX4/PX4-Autopilot/pull/17104/files#diff-2b038c042562ed5e0c53f450b7f7c3f7ef695087496853759f964f9be107cd30) as they get published by some power module over UAVCAN. Do we need to have battery_status in sync with the UAVCAN message?
I find all these empty fields quite annoying when debugging battery stuff, as they distract form the important ones. And it's empty weight in the log files.
=> battery_status.msg: remove unused fields

boards/px4/fmu-v6xrt/src/mtd.cpp
MTD was only using 4KB of the 32KB available on the fram, increase block counts.
=> fmu-v6xrt: MTD use full FRAM (32KB)

src/lib/fw_performance_model/PerformanceModel.hpp, src/modules/fw_pos_control/FixedwingPositionControl.hpp, src/modules/fw_pos_control/fw_path_navigation_params.c
Mostly to save flash (664 bytes), but also to improve conciseness and readability.
=> FW Position control: clean up param descriptions

boards/px4/fmu-v6xrt/nuttx-config/include/board.h, boards/px4/fmu-v6xrt/src/imxrt_clockconfig.c, platforms/nuttx/src/px4/nxp/imxrt/dshot/dshot.c
Use a FLEXIO base clock of 108Mhz which allows TCMP without fractions and thus gives us exact 150KHz, 300KHz, 600KHz, 1200KHz dshot timings.
Also this improves sampling of BDSHOT telemetry.
FYI @jwwaite this pretty much eliminates the CRC errors for me, could you test as well?
=> imxrt dshot timing fix

ROMFS/px4fmu_common/init.d-posix/airframes/4012_gz_x500_lidar, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt, platforms/posix/Debug/launch_sitl.json.in, src/modules/simulation/gz_bridge/GZBridge.cpp, src/modules/simulation/gz_bridge/GZBridge.hpp
See https://github.com/PX4/PX4-Autopilot/pull/22418
Credit to [dakejahl](https://github.com/dakejahl)
=>  [gz-sim] x500_lidar for testing CollisionPrevention 

src/modules/ekf2/EKF/aid_sources/external_vision/ev_vel_control.cpp
- these are set by the NED fuseVelocity() helper, so also need to be set in the body frame velocity case
=> ekf2: EV vel (body) update last vel fuse timestamps

ROMFS/px4fmu_common/init.d/airframes/4017_nxp_hovergames, ROMFS/px4fmu_common/init.d/rc.rover_ackermann_apps, msg/CMakeLists.txt, msg/RoverAckermannGuidanceStatus.msg, msg/RoverAckermannStatus.msg, src/modules/logger/logged_topics.cpp, src/modules/rover_ackermann/CMakeLists.txt, src/modules/rover_ackermann/RoverAckermann.cpp, src/modules/rover_ackermann/RoverAckermann.hpp, src/modules/rover_ackermann/RoverAckermannGuidance/RoverAckermannGuidance.cpp, src/modules/rover_ackermann/RoverAckermannGuidance/RoverAckermannGuidance.hpp, src/modules/rover_ackermann/module.yaml
This PR adds new features and a bugfix on a logging issue to the ackerman rover module from #23024:
1. Adds support for the return to launch (RTL) functionality
2. Adds a slew rate for the actuators which can be set with:
| Parameter | Description | Unit |
|--------|--------|--------|
| RA_MAX_ACCEL | Maximum acceleration for the rover | $m/s^2$ |
| RA_MAX_STR_RATE | Maximum steering rate for the rover | $rad/s$ |
The slew rate for the acceleration is not based on acceleration measurements but rather on an assumed linear relation between the throttle and maximum rover speed. Therefor the maximum rover speed `RA_MAX_SPEED` needs to be set for this to work.
The slew rate for the steering rate is also based on a assumed linear relation between steering input and steering angle. Therefor the …
=> New features for the ackermann rover module

platforms/common/uORB/SubscriptionInterval.hpp
When debugging #23378 , the only instance where timestamps get negative/wrap the unsigned datatype was the case where `SubscriptionInterval`s are initialized less than the interval time (e.g. 1 second) after boot and hence the start of the microcontroller timer. This made the cases fail after invalid assumptions were made that this case would never normally happen without checking even once here: https://github.com/PX4/PX4-Autopilot/pull/22881/files#diff-5971d648b2b246dfb01ec5d5006b5258cfdbc41b73f50db1abe7dd5236f855e1R167-R172
The change producing a few timestamps after boot that wrap was introduced here:
https://github.com/PX4/PX4-Autopilot/pull/14181/files#diff-c82d12a48f93eeb820597a14504a6a2d58cb7c09ad86d2e7da6aa6b04e144628L124-R128
and it never resulted in any problem because even …
=> Bugfix: Timestamp wrapping when initializing SubscriptionInterval less than the interval time after boot

ROMFS/px4fmu_common/init.d-posix/airframes/4012_gz_rover_ackermann, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt
Added a SITL aiframe for the new ackermann rover model added in https://github.com/PX4/PX4-gazebo-models/pull/46.
=> Add SITL airframe for ackermann rover

src/modules/ekf2/EKF/aid_sources/auxvel/auxvel_fusion.cpp, src/modules/ekf2/EKF/aid_sources/barometer/baro_height_control.cpp, src/modules/ekf2/EKF/aid_sources/external_vision/ev_control.cpp, src/modules/ekf2/EKF/aid_sources/external_vision/ev_height_control.cpp, src/modules/ekf2/EKF/aid_sources/external_vision/ev_pos_control.cpp, src/modules/ekf2/EKF/aid_sources/external_vision/ev_vel_control.cpp, src/modules/ekf2/EKF/aid_sources/external_vision/ev_yaw_control.cpp, src/modules/ekf2/EKF/aid_sources/gnss/gps_control.cpp, src/modules/ekf2/EKF/aid_sources/magnetometer/mag_control.cpp, src/modules/ekf2/EKF/aid_sources/range_finder/range_height_control.cpp, src/modules/ekf2/EKF/control.cpp, src/modules/ekf2/EKF/covariance.cpp, src/modules/ekf2/EKF/ekf.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/estimator_interface.cpp, src/modules/ekf2/EKF/height_control.cpp
When correcting velocity for position offsets (eg GNSS antenna) we were using uncorrected gyro stored during state predict). This pull request updates it to use bias corrected gyro (angular velocity) computed in place with the delayed IMU sample passed around.
I would guess this largely goes unnoticed as the majority of setups don't bother setting GNSS antenna positions, and typically the gyro bias is minimal (especially with autocal).
=> ekf2: use bias corrected angular velocity

boards/px4/fmu-v6xrt/nuttx-config/include/board.h, boards/px4/fmu-v6xrt/src/imxrt_clockconfig.c, boards/px4/fmu-v6xrt/src/mtd.cpp, platforms/nuttx/src/px4/nxp/imxrt/dshot/dshot.c
- Increase core voltage for stability.
- DShot timing fix
- Increase mtd_param size
Also pulls in stm32h7x7xx and ethernet changes from NuttX.
=> FMU-V6XRT release/1.15 backports

src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
There was an existing problem that surveys on steep terrain had bad tracking behaviour, whereby the multicopter went far offtrack before continuing to the next waypoint.
I changed the state-logic to use 3D coordinates instead of 2d. whereby the main contributer to the problem was that the elevation of the closest point between previous and current waypoint was set to use the elevation of the current waypoint
`_closest_pt = Vector3f(closest_pt_xy(0), closest_pt_xy(1), _triplet_target(2));`
```
Bugfix of the survey offtrack behaviour
```
Tested in SITL
Before:
After:
=> Survey - fix of survey tracking problem on steep slopes

platforms/common/uORB/SubscriptionInterval.hpp
1:1 backport of https://github.com/PX4/PX4-Autopilot/pull/23384 after varifying the problem is present on the 1.15 release.
I also successfully checked the SITL test documented in https://github.com/PX4/PX4-Autopilot/issues/23378 and it works with the fix.
=> [1.15] Bugfix: Timestamp wrapping when initializing SubscriptionInterval less than the interval time after boot

platforms/common/uORB/CMakeLists.txt, platforms/common/uORB/SubscriptionInterval.cpp, platforms/common/uORB/SubscriptionInterval.hpp
When porting the fix from #23384 to 1.15 with #23392 I saw that it uses 2.5 kilobytes more flash which is totally unexpected.
Big thanks to @niklaut who decompiled the binary and found that the unexpected impact comes from inlining the functions everywhere.
Move `updated()`, `update()`, `copy()` from `SubscriptionInterval` into a separate cpp file such that they are not inlined everywhere.
Saves 17.3 kilobytes of flash :open_mouth:
```
Fix: Save flash memory by not inlining SubscriptionInterval::copy()
```
Disadvantage is probably slightly more run time but I'd assume it's not worth that much flash 👀 
I'm testing this now.
=> Fix: Save flash by not inlining SubscriptionInterval::copy()

src/lib/tecs/TECS.cpp
When fast descend is enable and prior to the descend the vehicle is climbing the airspeed can drop and could potentially stall. The reason is that on fast decend the throttle is set to minimum, but if we are still climbing it takes some time until the vehicle pitches down. in this phase the airspeed can drop. The underspeed prevention should kick in eventually as this has higher priority than the fat descend.
- Make sure to give a trim throttle in fast descend, as long as the vehicle is still climbing
```
Bugfix Still enable throttle at the beginning of the fast descend while still climbing
```
**There could potentially be an issue with thermals, when it is not sinking although it has already pitched down. In this case it would also activate the motors instead of …
=> Dont shut off throttle in fast descend while stil climbing

src/modules/ekf2/EKF/python/tuning_tools/mc_wind_estimator/requirements.txt
When installing the required packages through `requirements.txt` and running the script, an error message appears which states that the required "quaternion" package cannot be found, even though `quaternion==3.5.2.post4` is specified in `requirements.txt`
- Specify for the `numpy-quaternion 2023.0.4` package to be installed instead of the `Quaternion 3.5.2.post4 ` package.
```
```
=> mc_wind_estimator_tuning: Changed Quaternion package installed 

.ci/Jenkinsfile-compile, boards/spracing/h7extreme/src/rcc.c
When checking CI of the `release/1.15` branch I found that some backports are certainly missing:
https://github.com/PX4/PX4-Autopilot/pull/23198
https://github.com/PX4/PX4-Autopilot/pull/23265/commits/7a65a8f73cea666449ff74db35e19b058c524b43
```
Fix CI errors on 1.15 release branch
```
Let's see if that's everything for now.
=> Fix CI errors on 1.15 release branch

msg/VehicleGlobalPosition.msg, msg/VehicleLocalPosition.msg, src/modules/ekf2/EKF/aid_sources/optical_flow/optical_flow_control.cpp, src/modules/ekf2/EKF/aid_sources/range_finder/range_height_control.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/position_fusion.cpp, src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2Selector.cpp, src/modules/ekf2/EKF2Selector.hpp, src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.cpp, src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.hpp
TODO: apply reset delta to flight task usage (_dist_to_bottom, _dist_to_ground_lock, etc)
=> ekf2: add terrain/dist_bottom reset deltas (vehicle_local_position/vehicle_global_position)

src/modules/ekf2/EKF/aid_sources/barometer/baro_height_control.cpp, src/modules/ekf2/EKF/aid_sources/external_vision/ev_height_control.cpp, src/modules/ekf2/EKF/aid_sources/external_vision/ev_vel_control.cpp, src/modules/ekf2/EKF/aid_sources/gnss/gnss_height_control.cpp, src/modules/ekf2/EKF/aid_sources/gnss/gps_control.cpp, src/modules/ekf2/EKF/aid_sources/range_finder/range_height_control.cpp, src/modules/ekf2/test/test_EKF_terrain.cpp
- GNSS height control using the velocity sample directly is ignoring potential position offsets
=> ekf2: GNSS velocity control should own vertical velocity reset if height faiing

src/modules/ekf2/EKF/aid_sources/optical_flow/optical_flow_control.cpp
1. When the height above ground (hagl) is not directly observed and that the vehicle is close to the ground (e.g.: during touchdown), the height estimate can go below the terrain estimate. Fusing optical flow with a negative distance isn't safe and should be avoided.
2. When neither the hagl nor the horizontal velocity is currently estimated, starting the optical flow can be hazardous as the filter might struggle to make both values converge at the same time.
1. Allow flow fusion when hagl is between min and max flow distance
3. As the flow makes the link between range and horizontal velocity, only allow it to start if at least one of the two is known
```
``` …
=> ekf2-flow: only allow flow when in range

src/modules/ekf2/EKF/common.h, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/ekf_helper.cpp, src/modules/ekf2/EKF2.cpp
The EKF estimator_status.solution_status_flags is a legacy set of bits we carry from mavlink that hardly matters anymore, but as long as we carry it we should try to keep it consistent with the rest of our usage.
https://mavlink.io/en/messages/common.html#ESTIMATOR_STATUS_FLAGS
=> ekf2: cleanup legacy EKF solution_status_flags

ROMFS/px4fmu_common/init.d-posix/airframes/4013_gz_x500_lidar, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt, msg/ObstacleDistance.msg, platforms/posix/Debug/launch_sitl.json.in, src/modules/simulation/gz_bridge/GZBridge.cpp, src/modules/simulation/gz_bridge/GZBridge.hpp
Added another x500 model with a lidar attached.
https://app.gazebosim.org/OpenRobotics/fuel/models/Lidar%202d%20v2
Subscribes to gz::msgs::LaserScan and publishes to ObstacleDistance. 
**requires** https://github.com/PX4/PX4-gazebo-models/pull/41
=> [gz-sim] x500_lidar for testing CollisionPrevention

src/modules/ekf2/EKF/aid_sources/optical_flow/optical_flow_control.cpp, src/modules/ekf2/EKF/aid_sources/optical_flow/optical_flow_fusion.cpp, src/modules/ekf2/EKF/aid_sources/sideslip/sideslip_fusion.cpp
- in the symforce generated code there's a 1 / eps^2 term if the height and terrain estimates are the same
=> ekf2: optical flow adjust jacobian epsilon to avoid numerical issues

src/modules/mc_pos_control/PositionControl/PositionControl.cpp
it seems that there is none needed calculation of Anti-Reset Windup on the PositionControl::_velocityControl().
it also make it more readable to understand when the ARW is active or not
=> mc_position_control: avoid calculating arw if not needed

src/modules/ekf2/EKF/aid_sources/gnss/gps_checks.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/module.yaml
Various GNSS checks are implemented to avoid using incorrect data but a couple of them are disabled by default for some unknown reason.
Enable all GNSS checks by default. The thresholds are wide enough to no cause unnecessary pain to the user but adds a layer of protection against really bad data.
```
-
```
=> ekf2: enable all GNSS checks by default

src/lib/battery/battery.cpp
Due to the internal resistance estimator (https://github.com/PX4/PX4-Autopilot/pull/23205) there is now a variable with the load compensated voltage that can be used to simplify the battery scale calculation. This does not change any functionality.
=> battery: simplify battery scale calculation

src/modules/ekf2/EKF/aid_sources/airspeed/airspeed_fusion.cpp, src/modules/ekf2/EKF/aid_sources/fake_height_control.cpp, src/modules/ekf2/EKF/aid_sources/fake_pos_control.cpp, src/modules/ekf2/EKF/aid_sources/optical_flow/optical_flow_fusion.cpp
- fake_pos shouldn't update _time_last_hor_pos_fuse
=> ekf2: fake_pos don't use fuseHorizontalPosition helper

msg/RoverAckermannGuidanceStatus.msg, src/modules/rover_ackermann/CMakeLists.txt, src/modules/rover_ackermann/RoverAckermann.cpp, src/modules/rover_ackermann/RoverAckermannGuidance/RoverAckermannGuidance.cpp, src/modules/rover_ackermann/RoverAckermannGuidance/RoverAckermannGuidance.hpp
Implement the new pure pursuit library (https://github.com/PX4/PX4-Autopilot/pull/23387) in the ackermann rover module.
Also fixes naming inconsistencies in the module: Changing coordinate postfix from `local` to `ned` and renaming `purePursuit` function to `computeGuidance`.
- SITL tested
https://github.com/user-attachments/assets/7e316764-92c9-49b0-b897-fdf5a76adb3b
=> ackermann: implement pure pursuit library

src/modules/load_mon/LoadMon.cpp
Inconsistency in load monitoring for memory when running on a Linux based system. This bug does not always occur, but I found it when running in an Ubuntu 22.04 incus container.  See linked Github issue for more detail. 
#23361
Reset the file descriptor back to the beginning of the file, rather than to the end of the file, to continually get new updates. 
```
Bug fix of load monitoring inconsistency bug
```
- Tested fix in SITL in incus Ubuntu 22.04 container. 
Before console output: 
After console output:
=> Fix load monitoring inconsistency bug

src/modules/sensors/data_validator/DataValidatorGroup.cpp
When the the last mag fails and there is no mag left to switch to, the current implementation keeps sending warnings to the user every 3 seconds.
If the mag continues to fail, no new warning gets sent. It still works correctly for:
mag works -> mag fails (warns) -> mag fails -> mag works -> mag fails (warns)
=> only warn once when the last mag fails/gets disabled

src/modules/ekf2/EKF/covariance.cpp
The wind variance can be reset to a value larger than the wind init variance (e.g.: when the reset occurs when flying close to the N or E axis). Constraining the variance after a covariance initialization would artificially increase the correlation and could destabilize the filter.
To reproduce:
- In sitl with a standard vtol plane, takeoff and transition towards the East **without** GNSS fusion.
- After a couple of seconds the wind state are diverging and because the airspeed fusion is used to update the other states, the vel/pos states are also diverging
Do not constrain the wind variance but rather stop the process noise when the wind variance is large enough.
I also think that the process noise should continue to run even when the wind has been initialized manually as the uncertainty …
=> Fix wind covariance prediction

src/modules/navigator/navigator_main.cpp
We had several vehicles with `Navigator low on stack `warnings (usually only by <20 bytes).
=> Navigator: increase stack by 40 bytes

src/modules/ekf2/module.yaml
Changed default value of `EKF2_OF_CTRL` to `true`, resulting in Optical Flow being enabled by default. This change does not have an effect on vehicles that are not equipped with an OF sensor.
```
Feature Optical flow enabled by default (EKF2_OF_CTRL =  true)
```
=> ekf2: Optical flow enabled by default

src/modules/rover_ackermann/RoverAckermannGuidance/RoverAckermannGuidance.cpp, src/modules/rover_ackermann/RoverAckermannGuidance/RoverAckermannGuidance.hpp
The rover wasn't stopping at waypoint if there was a delay on it, and instead was looping around
- Stop the rover when it is in the acceptance radius of the waypoint
- SITL tested
Mission : 
Before :
https://github.com/user-attachments/assets/00bd1ac4-5260-4c51-824b-397e5b6fa3c2
After :
https://github.com/user-attachments/assets/72435e4f-ab17-4728-9f2c-e8a89d8ea696
=> ackermann: added delay comand support

src/lib/parameters/px4params/markdownout.py
This generates the markdown for parameter listing using markdown as a heading, description and a small table. This is slightly less compact, but has the benefit that parameters link properly because they use the heading link. It also allows us to process the text in descriptions as markdown, allowing more formatting options.
THIS IS FOR DISCUSSION - what do we think? Is it better, same, worse? If it is better or same, what could be made even better? 
> Previously we generated all params in a group as an HTML table like this:
=> Proposal: Params generated as markdown table

src/modules/ekf2/EKF/aid_sources/optical_flow/optical_flow_control.cpp, src/modules/ekf2/EKF/common.h, src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp, src/modules/ekf2/module.yaml
In some cases the vibration environment of the optical flow sensor is worse than near the autopilot.
Add a param that lets the user decide if he wants to use the gyro data from the optical flow message or the internal gyro.
```
New parameter: EKF2_OF_GYR_SRC
```
This should maybe directly be applied at the vehicle_optical_flow level
SITL
=> ekf2-flow: add param to force using internal gyro

src/modules/commander/UserModeIntention.cpp
Two kind of separate problems:
- when after the `VEHICLE_CMD_DO_FLIGHTTERMINATION` there was a `VEHICLE_CMD_COMPONENT_ARM_DISARM` (to disarm) command, the system reset the flight mode from Termination to whatever was there previously. This then e.g. allowed to re-arm.
- the user could switch out of the Termination mode (I don't think this is intended?)
- allow _nav_state_after_disarming to be set to Terminate
- disallow mode changes if the nav_state is Termination
```
Bugfix: Commander: Termination: do not switch out of mode on disarm and prevent user switching out of it
```
=> Commander: Termination: do not switch out of mode on disarm and prevent user switching out of it

src/modules/ekf2/EKF/ekf.cpp, src/modules/fw_pos_control/FixedwingPositionControl.cpp, src/modules/fw_pos_control/FixedwingPositionControl.hpp
In posiiton-mode, the controller tries to follow a straight line to keep consistent track and avoid lateral drift.
After a position reset, either by fusion or hard reset, the line was not updated. This resulted in a "correction" path. Since the position difference from the reset does not represent the truth, we would expect the vehicle to fly straight on in the same direction.
After a position reset, the switches to track-hold mode for 2 seconds. During those 2 seconds it does not correct for any later drift. A time-based approach is needed since the states do not converge immediately after a reset-by-fusion.
Screenshots: position-mode, flight from W to E. position reset in N direction.
old:
new:
=> FW Position Controller: reset position-mode line following after position reset

src/modules/fw_pos_control/fw_path_navigation_params.c
The TECS airspeed filter is setup with too much filtering, which causes high measurements delay, which in turn can lead to instability of the control loop.
Reduce the default of FW_T_SPD_STD (airspeed measurement standard deviation) to reduce filtering. 
Current main, with default TECS airspeed filtering: delay of filtered airspeed input is about 1s:
With the proposed change of FW_T_SPD_STD to 0.07: delay is about 0.7s
Old (previous to [TECS rework](https://github.com/PX4/PX4-Autopilot/pull/20443)): the delay was at about 0.5s:
```
Improvement: TECS: reduce default of FW_T_SPD_STD to reduce airspeed measurement delay
```
This was flown on different drones with much better results.
=> TECS: reduce default of FW_T_SPD_STD to reduce airspeed measurement delay

src/modules/ekf2/EKF/python/tuning_tools/baro_static_pressure_compensation/baro_static_pressure_compensation_tuning.py
This filter is often not needed. Setting the default value to -1 makes it optional.
=> baro tuning: make hpf argument optional

ROMFS/px4fmu_common/init.d-posix/airframes/4012_gz_rover_ackermann, src/lib/pure_pursuit/CMakeLists.txt, src/lib/pure_pursuit/PurePursuit.cpp, src/lib/pure_pursuit/PurePursuit.hpp, src/lib/pure_pursuit/PurePursuitTest.cpp, src/lib/pure_pursuit/module.yaml, src/modules/rover_ackermann/RoverAckermannGuidance/RoverAckermannGuidance.cpp, src/modules/rover_ackermann/RoverAckermannGuidance/RoverAckermannGuidance.hpp, src/modules/rover_ackermann/module.yaml
The pure pursuit library introduced in https://github.com/PX4/PX4-Autopilot/pull/23387 requires some parameters that are currently defined in the ackermann module.
Migrating them to the library itself avoids having to redifine the same parameters for every module that uses the pure pursuit library in the future.
This effects the following parameters:
| Parameter | Description | Unit |
|--------|--------|--------|
| RA_LOOKAHD_GAIN $\rightarrow$ PP_LOOKAHD_GAIN | Main tuning parameter | - |
| RA_LOOKAHD_MAX $\rightarrow$ PP_LOOKAHD_MAX | Maximum value for the look ahead radius | m |
| RA_LOOKAHD_MIN $\rightarrow$ PP_LOOKAHD_MIN | Minimum value for the look ahead radius | m |
=> purePursuit: migrate parameters to library

src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp
When looking through code to answer questions I found that some parameters don't follow the naming convention and as a result it's harder to find the places they are used by doing a full text search.
We agreed on the convention `_param_{lower case parameter name}` in https://github.com/PX4/PX4-Autopilot/pull/11686 the only thing missing is an automated check to preserve it consistently. Maybe we could add it to the style checks similar to https://github.com/PX4/PX4-Autopilot/pull/23166
I quickly fixed up the ones I saw in Commander.
```
Cleanup: internal member names for parameter in Commander
```
Compiles and I don't see any mistake. Do you?
Just as reminder why it's useful to have the naming: One full text search shows the parameter definition with metadata, all airframes that set it …
=> Commander: adhere to parameter naming convention

ROMFS/px4fmu_common/init.d-posix/airframes/1031_gazebo-classic_plane_cam, ROMFS/px4fmu_common/init.d-posix/airframes/1032_gazebo-classic_plane_catapult, ROMFS/px4fmu_common/init.d-posix/airframes/1038_gazebo-classic_glider, ROMFS/px4fmu_common/init.d-posix/airframes/1039_flightgear_rascal, ROMFS/px4fmu_common/init.d-posix/airframes/1044_gazebo-classic_plane_lidar, src/modules/navigator/mission_base.cpp, src/modules/navigator/mission_block.cpp, src/modules/navigator/mission_block.h, src/modules/navigator/navigator.h, src/modules/navigator/navigator_main.cpp, src/modules/navigator/navigator_params.c, src/modules/navigator/rtl_direct.cpp, src/modules/navigator/rtl_direct_mission_land.cpp
Alternative to https://github.com/PX4/PX4-Autopilot/pull/23396. Changes:
- do not exclusively apply terrain collision logic for VTOL in landing phase
- do not allow to increase the altitude setpoint above the current altitude
- implement user feedback
There are several reasons why during a landing approach (landing with a pattern) a VTOL might fly into terrain.
The baro bias estimate could not be correct (especially when flying GPS denied) or the user might have not planned the mission correctly.
Avoid flying into terrain using the distance sensor. Enable through the parameter `NAV_MIN_GND_DIST`.
Only active during commanded descents with vz>0 (to prevent climb-aways), excluding landing and VTOL transitions.
It changes the altitude setpoint in the triplet to maintain the current altitude …
=> Navigator: add terrain collision avoidance during descents

ROMFS/px4fmu_common/init.d/CMakeLists.txt, ROMFS/px4fmu_common/init.d/rc.sysinit
Every time we open the `nsh`, we receive the error: `nsh: sysinit: fopen failed: No such file or directory`.
- Add the missing default file `rc.sysinit` to the ROMFS.
```
Fix/NSH failed to open file error
Adding the missing default file which causes the NSH to report an error on each boot. 
```
We could also find a way to disable it from NuttX side but like `rcS`, `rc.sysinit` is an important file in normal NuttX setups.
The error is triggering on this `fopen()` (using gdb with stlink and `px4_fbreak fopen`)
```c
0x0802bd32 in nsh_script (vtbl=vtbl@entry=0x30020bc0,
cmd=cmd@entry=0x813c454 "sysinit",
path=path@entry=0x813c445 "/etc/init.d/rc.sysinit")
at /home/alexis/work/PX4-Autopilot/platforms/nuttx/NuttX/apps/nsh_script.c:109
```
The error is "polluting" logs when we are debugging the …
=> Add the missing rc.sysinit file in the ROMFS

src/modules/commander/HealthAndArmingChecks/checks/externalChecks.cpp, src/modules/commander/HealthAndArmingChecks/checks/externalChecks.hpp
We've come accross a case where a ROS node would consistently take something over 800 ms until the first arming check request subscription callback was triggered.
After the first sample, the callback always triggered within the expected timeframe.
Therefore this patch allows for more time right after registration until timing out.
=> commander: allow external modes more time for initial response

src/modules/rover_ackermann/RoverAckermannGuidance/RoverAckermannGuidance.cpp
Sometimes when three waypoints are aligned, the acceptance radius returned by `updateAcceptanceRadius` can be NaN due to a float precision problem.
in `updateAcceptanceRadius` we use `acosf` that accept only numbers in range of [-1.0;1.0] and sometimes the value we get from this formula can be sligthly outside of the range due to float precision :
`(curr_to_prev_wp_ned * curr_to_next_wp_ned) / (curr_to_prev_wp_ned.norm() * curr_to_next_wp_ned.norm())`
For the same mission, the problem doesn't happen always at the same waypoints, because the position of the rover seems have an influence on it.
Constrain the value between [-1;1] and use it for `acosf`
- SITL test
Before (NaN value at the end):
https://github.com/user-attachments/assets/557f01c5-32c9-418e-9c29-262f0b27ebbd
After (Correction …
=> ackermann: add protection against float precision problem in acceptance radius update

src/systemcmds/hardfault_log/hardfault_log.c
CI fails to `make module_documentation` on main after https://github.com/PX4/PX4-Autopilot/pull/23003/files#diff-7d9b8a304c07e253fd338d3cd6df043d5793f60183255ee302e6c144bf194fecR1276
- the module documentation parser can only resolve defines from the same file
- also it cannot deal with defines embeded in strings
- what board should it add for the general documentation anyways?
As a result of these issues I suggest to stay with the original hardcoded /fs/microsd for the documentation. It's still the most common path as far as I can see.
I built it locally and removing the define it works again.
=> hardfault_log: revert to explicit path to not trip the module documentation parser

platforms/nuttx/src/px4/common/SerialImpl.cpp, platforms/posix/src/px4/common/SerialImpl.cpp
The Septentrio GNSS driver requires certain baud rates to test all the supported baud rates of the receiver. Without these changes, certain "non-standard" ones would print an error to the MAVLink console when the driver was started through the console.
This is an alternative to #23374 with the change suggested by @julianoes.
Fixes #23374
- Add the required baud rates to `SerialImpl.cpp`
- Test on a Holybro Pixhawk 6C mini to make sure all of them work
```
Bugfix Add new baud rates required by Septentrio driver
```
See #23374 for alternatives.
- Manual testing of all the newly added baud rates with the Septentrio driver, making sure no more warnings are printed and the driver successfully discovers the receiver.
\/
=> gnss: update supported baud rates

cmake/metadata.cmake
=> fix metadata.cmake: add missing paths to json & xml parameter outputs

ROMFS/px4fmu_common/init.d/airframes/50000_generic_rover_differential, ROMFS/px4fmu_common/init.d/airframes/50001_aion_robotics_r1_rover, ROMFS/px4fmu_common/init.d/airframes/51000_generic_rover_ackermann, ROMFS/px4fmu_common/init.d/airframes/51001_axial_scx10_2_trail_honcho, ROMFS/px4fmu_common/init.d/airframes/59000_generic_ground_vehicle, ROMFS/px4fmu_common/init.d/airframes/59001_nxpcup_car_dfrobot_gpx, ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt, ROMFS/px4fmu_common/init.d/rc.rover_ackermann_apps, ROMFS/px4fmu_common/init.d/rc.rover_ackermann_defaults, ROMFS/px4fmu_common/init.d/rc.rover_differential_apps, ROMFS/px4fmu_common/init.d/rc.rover_differential_defaults
This PR aims to restructure the rover aiframes s.t. they are in line with the new differential and ackermann modules.
Rover airframes will be contained within the (50000 - 59999) series with the following structure that allows for further expansion with new hardware specific airframes aswell as new rover configurations:
- 50000_generic_rover_differential
- 50001 - 50999: Hardware specific differential rover airframes
- 51000_generic_rover_ackermann
- 51001 - 51999: Hardware specific ackermann rover airframes
- 52000 other rover type i.e. mecanum
- etc.
- 59000-59999: The airframes connected to the old rover position module. They are tagged with _deprecated_ to eliminate any confusion until the old module is completely removed.
Besides restructuring this PR introduces these 2 new …
=> rover: restructure airframes

src/modules/fw_pos_control/FixedwingPositionControl.cpp
Flaps support during takeoff currently only possible in runway takeoff, not in hand/catapult launch. Was raised here: https://discord.com/channels/1022170275984457759/1265569056237555734
Enable it also for hand/catapult launch (for as long as control_auto_takeoff() is running). 
```
Improvement: Fixed-wing auto takeoff: enable setting takeoff flaps for hand/catapult launch.
```
Untested yet. To test: Configure flaps and enable them during takeoff through FW_FLAPS_TO_SCL.
=> Fixed-wing auto takeoff: enable setting takeoff flaps for hand/catapult launch.

src/modules/simulation/gz_bridge/CMakeLists.txt
This PR adds the rover world introduced in https://github.com/PX4/PX4-gazebo-models/pull/46 to the gazebo bridge cmake such that vehicles can be spawend in it by using the _rover suffix.
=> gz_bridge: add rover world to cmake

src/modules/mavlink/mavlink_log_handler.cpp, src/modules/mavlink/mavlink_log_handler.h
Fixes https://github.com/PX4/PX4-Autopilot/issues/22998
The main reason for doing this is to fix the above issue where a LOG_REQUEST_LIST pegs the CPU at 100% for multiple seconds. If you look at the original code, as it is before this PR, you will see the primary culprit is the redundant calls to stat. I've improved the method of constructing the log list file so that it doesn't take multiple seconds. There's no longer any CPU load during the request_list.
Creating the logdata.txt file (with 28 entries)
```
mavlink: create file: 16 events, 1045295us elapsed, 65330.94us avg, min 59106us max 74291us 6038.570us rms
```
Listing the entries (28 of them)
```
mavlink: listing: 16 events, 110504us elapsed, 6906.50us avg, min 6102us max 8128us 989.786us rms
```
I started a log to record the CPU …
=> mavlink log handler rewrite for improved effeciency

boards/cubepilot/cubeorange/nuttx-config/include/board.h, boards/cubepilot/cubeorangeplus/nuttx-config/include/board.h, boards/px4/fmu-v6c/nuttx-config/include/board.h, boards/px4/fmu-v6x/nuttx-config/include/board.h
This resets the USARTs' clock source selection to the default, in case it has been changed by the bootloader.
This is required if booting from the ArduPilot bootloader which happens to reset the clock selection to PLL.
Without this fix, UARTs (including the console) is garbled, so presumably at an invalid baudrate. I suspect this will solve a lot of frustration where serials "just don't work".
I have added defines for Pixhawk 6C and 6X, as well as CubePilot Orange and Orange+. I assume we need to add this to a bunch more boards.
Depends on https://github.com/PX4/NuttX/pull/319.
Needs backporting to v1.14 and v1.15!
=> [Sponsored by CubePilot] stm32h7: Reset USART clock selection

src/lib/mixer_module/functions/FunctionManualRC.hpp
1. I got multiple reports that when an actuator is mapped directly to an RC passthrough e.g. the roll stick and the RC is not present on boot the actuator goes to its middle position instead of staying on the disarmed value.
2. When the RC input is lost the actuator would stay in the last position it had. I quickly discussed with @sfuhrer and this could be unexpected or even dangerous depending on the use case.
Note: 1. very likely broke when I started publishing one `manual_control_setpoint` which has the valid flag set to false on boot to inform the clients.
Reset the actuators mapped to RC passthrough to their disarmed value whenever no valid stick input is present (anymore).
```
Improvement: Reset RC passthrough functions to disarmed value when no stick input
```
I quickly tested this …
=> Improvement: Reset RC passthrough functions to disarmed value when no stick input

src/lib/button/ButtonPublisher.cpp
@jeremyzff enhanced the user experience for pairing via the safety button. Thanks for the contribution.
The LED now blinks white instead of just lighting up green.
```
Improvement: Pairing button triggers 20 rapid white LED flashes
```
As discussed ideally there would be feedback over MAVLink from the link which would allow to verify the pairing is in progress or finished.
=> Improvement: Pairing button triggers 20 rapid white LED flashes

msg/NavigatorMissionItem.msg, src/modules/navigator/mission_base.cpp, src/modules/navigator/navigator.h, src/modules/navigator/rtl_direct.cpp, src/modules/navigator/rtl_direct.h
Followup from https://github.com/PX4/PX4-Autopilot/pull/23429: When in RTLDirect the terrain avoidance check was only done when in Loiter down state. Once this state was passed the altitude setpoint was opened again and the vehicle proceeded descending.
- add publication of NavigatorMissionItem to RTLDirect for logging and easier trouble shooting
- run updateAltToAvoidTerrainCollisionAndRepublishTriplet() in entire RTLDirect except for when state is in IDLE (which is the case then the vehicle is vertically Landing)
=> RTL Direct: terrain collision avoidance fix

src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
@leonardosimovic reported that the ground station does not get any altitude telemetry while the altitude is changed by stick during a multicopter orbit.
Continue reporting the altitude setpoint that's sent to the controller when it's not NAN. Use the altitude state estimate when no setpoint is commanded, such as during stick-controlled altitude changes.
```
Bugfix: Always report multicopter orbit altitude via status telemetry
```
Untested. @leonardosimovic could you give it a spin and report? 😇
=> Bugfix: Always report multicopter orbit altitude via status telemetry

src/lib/battery/battery.cpp
If the battery is disconnected (voltage measurement below a hardcoded value of 2.1 V) even for just one sample it causes the SoC filter to reset with the current voltage measurement. This leads to the SoC dropping to 0 for one sample which triggers a battery failsafe.
Protect the state of charge filter from being reset when the battery is disconnected.
=> battery: only reset soc filter with valid voltage measurement

boards/cubepilot/cubeorange/nuttx-config/include/board.h, boards/cubepilot/cubeorangeplus/nuttx-config/include/board.h, boards/px4/fmu-v6c/nuttx-config/include/board.h, boards/px4/fmu-v6x/nuttx-config/include/board.h
=> [BACKPORT v1.15] stm32h7: Reset USART clock selection (#23498)

src/lib/parameters/px4params/markdownout.py
Fix/improve rendering
- Insert either check mark or non breaking space for reboot required (fixes table rendering if reboot not required)
- Remove short description of parameter from start of long description IFF it ends in a full stop. This removes duplicate short/long descriptions, and improves the long description if it starts with the short description as a sentence.
As spotted by @Claudio-Chies :-)
=> Parameter metadata - improve/fix rendering

src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/streams/MANUAL_CONTROL.hpp
When working on #22102 I realized there's no way to get auxiliary continuous inputs in over MAVLink. That's why we came up with the suggestion to support it in MAVLink https://github.com/mavlink/mavlink/pull/2031 and this pr brings the implementation to PX4.
- https://github.com/mavlink/mavlink/pull/2031
- Read `MANUAL_CONTROL` fields when it's an input
main use case
- Fill the fields when sending out `MANUAL_CONTROL` as telemetry
only done sent with the USB telemtry profile
```
Feature: Support MAVLink MANUAL_CONTROL.aux extension
```
Note that in uORB we don't currently know if the aux fields are specifically valid or not so we can also not set the corresponding bits in the field and vice versa. I'll propose to set the fields differently from just zero-initialized to indicate them being …
=> Support MAVLink MANUAL_CONTROL.aux extension

src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h
Connecting to the payload bus's UART allows full control over the autopilot, even when the MAVLink instance is configured for a gimbal/(camera) payload.
This adds explicit handling for the relevant services for a gimbal/camera payload for MAVLink instances in gimbal mode.
```
Feature: Restrict access on gimbal-specific MAVLink instances
```
A more general approach may involve defining MAVLink instance modes with specific capability groups.
Tested on hardware to ensure restricted access through the gimbal UART port when configured in gimbal mode.
=> mavlink_receiver: limit access through instances with gimbal mode

boards/mro/ctrl-zero-classic/nuttx-config/include/board.h, boards/mro/ctrl-zero-h7-oem/nuttx-config/include/board.h, boards/mro/ctrl-zero-h7/nuttx-config/include/board.h, boards/mro/pixracerpro/nuttx-config/include/board.h
This PR applies #23498 fix to mRo boards, which as boards that use Ardupilot BL, might end up with wrong values for clock selection to PLLs. I can confirm that this helped to configure GPS devices correctly. This PR possibly can fix #21242, #18968, and #18505.
I am willing to help find and mitigate these bugs and undesired behaviors for boards using AP BLs and PX4.
=> mRo boards: Fix for USART clock selection

ROMFS/px4fmu_common/init.d-posix/airframes/4011_gz_lawnmower, src/modules/rover_differential/module.yaml
When running '''make px4_sitl gz_lawnmower_lawn``` the vehicle completes the mission, but its movements aren't smooth.
To fix that, ```RD_*``` parameters must be adjusted in the airframe definition file.
Ammends #{[23430](https://github.com/PX4/PX4-Autopilot/pull/23430)}
Speed, accelerations and turn rate were adjusted.
also, it looks like with Units being *rad*, the upper limit for RD_TRANS_DRV_TRN and RD_TRANS_TRN_DRV parameters should be in radians too.
Running '''make px4_sitl gz_lawnmower_lawn``` produces smooth movements.
=> Reasonable defaults for Lawnmower SITL

src/modules/mavlink/streams/SYS_STATUS.hpp
In https://github.com/PX4/PX4-Autopilot/pull/23001 the correct health components are updated to reflect the system state. However, during testing, I found that this causes the wrong or unexpected [MAVLink system status flag](https://mavlink.io/en/messages/common.html#MAV_SYS_STATUS_SENSOR) to be set.
The AHRS flag should in my understanding indicate IMU and magnetometer health and be unrelated to position estimates. Since there are separate flags for gyroscope, accelerometer, and magnetometer, it seems the AHRS flag was meant to represent an estimator in ArduPilot (see https://github.com/mavlink/mavlink/commit/66c4190b4400e4168655a6135b5169967b2df2c6). To me, its definition is too unclear to map to any specific EKF2 estimator state.
1. Map `health_component_t::local_position_estimate` to …
=> SYS_STATUS: fill correct attitude, horizontal position flags

src/modules/ekf2/EKF/python/tuning_tools/gyro_integration.py
Python script that compares the attitude estimate with an attitude obtained by pure gyro integration.
This is useful to see whether the attitude is affected by mag 3D fusion for example.
=> ekf tools: compare gyro integral with attitude estimate

src/modules/navigator/geofence.cpp
MAVLINK message level and EVENT message level are different.
Match the EVENT message level to the MAVLINK message level.
None.
None.
None.
None.
=> navigator: Align MAVLINK message level with EVENT message level

src/modules/ekf2/EKF2.cpp
On ground the airspeed can sometimes be slightly negative. If no airspeed data is sent to the backend, it cannot know that wind dead-reckoning will be possible post-takeoff and the inertial dead-reckoning is set.
See: https://github.com/PX4/PX4-Autopilot/blob/db8781e5311c876cb948fc2e10c0ec6d0ff96372/src/modules/ekf2/EKF/ekf_helper.cpp#L757-L763
Send airspeed data to ekf2 backend as long as finite but ignore sign.
=> ekf2: send airspeed data to ekf backend regardless of sign

Makefile
When we type wrong argument in first argument, the error said:
```
"Make target $@ not found. It either does not exist or $@ cannot be the first argument. Use '$(MAKE) help|list_config_targets' to get a list of all possible [configuration] targets."
```
But when typing `make help|list_config_targets`, it still not work.
- The command has been changed to `$(MAKE) list_config_targets`, so I changed Makefile too.
=> fix: Fix error message when cannot find target board

src/modules/mc_pos_control/multicopter_position_control_limits_params.c
`MPC_ACC_DECOUPLE` description doesn't help readers understand when they should use it. 
This paraphrases text from @bresch in https://discuss.px4.io/t/px4-v1-15-public-changes-what-needs-docs/39850/12?u=hamishwillee
=> MPC_ACC_DECOUPLE - better description

src/modules/navigator/geofence.cpp
Clarify each decision value.
re pr #23065
Change the IF statement to a SWITCH statement.
None
None
None
None
=> navigator: Change IF statement to SWITCH statement

msg/CMakeLists.txt, msg/FailsafeFlags.msg, msg/NavigatorStatus.msg, src/modules/commander/HealthAndArmingChecks/CMakeLists.txt, src/modules/commander/HealthAndArmingChecks/HealthAndArmingChecks.hpp, src/modules/commander/HealthAndArmingChecks/checks/navigatorCheck.cpp, src/modules/commander/HealthAndArmingChecks/checks/navigatorCheck.hpp, src/modules/commander/failsafe/failsafe.cpp, src/modules/logger/logged_topics.cpp, src/modules/navigator/land.cpp, src/modules/navigator/loiter.cpp, src/modules/navigator/mission.cpp, src/modules/navigator/mission_base.cpp, src/modules/navigator/mission_base.h, src/modules/navigator/mission_block.cpp, src/modules/navigator/mission_block.h, src/modules/navigator/navigator.h, src/modules/navigator/navigator_main.cpp, src/modules/navigator/navigator_mode.cpp, src/modules/navigator/navigator_mode.h, src/modules/navigator/precland.cpp, src/modules/navigator/rtl.cpp, src/modules/navigator/rtl_base.h, src/modules/navigator/rtl_direct.cpp, src/modules/navigator/takeoff.cpp, src/modules/navigator/vtol_takeoff.cpp
When using a downward looking sensor for navigation (e.g.: optical flow), the EKF sends a height above ground limit that the vehicle shouldn't exceed to avoid a loss of navigation. Currently, commander/navigator are unaware of this and are allowed to trigger RTL with an altitude higher than the maximum value, leading to a descend. When below the max HAGL, the navigation re-starts and commander tries to RTL again. The vehicle is then stuck in a loop.
RTL shouldn't send the vehicle to an altitude above the mag HAGL. Sending the drone to the max HAGL and then to home is dangerous too, so the best option is to land instead.
New uORB topic: `navigator_status` is used to report when a navigator mode fails to execute.
Commander monitors this field and triggers a failsafe if the current navigator …
=> RTL: do not RTL if RTL alt is above max HAGL

.github/ISSUE_TEMPLATE/bug_report.yml
Eases the burden on requirements for bug reports by marking previously required fields as optional.
=> github: update bug report template

src/modules/commander/failsafe/framework.cpp
In a generic failsafe, the message "autopilot disengaged" is wrong. E.g. it now displays the following for a Land failsafe due to geofence breach:
Only keep the "autopilot disengaged" in case the autopilot is no longer controlling the vehicle's position. This is a bit arbitrary but I guess the best approximation to what  "autopilot disengaged" implies, as then without any user input the vehicle will likely crash - thus the extra warning with the implication that the pilot should take over control if possible. 
With this change the geofence breach failsafe notification would looks like this:
```
Improvement: Commander: only add *autopilot disengaged* to failsafe notifactions in special cases
```
This was originally added in …
=> Commander: only add *autopilot disengaged* to failsafe notifactions in special cases

src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.cpp
COM_POS_FS_EPH can be set to -1, in which case the actual failure eph is INFINITY.
Use the same threshold as for the failure trigger.
```
Feature/Bugfix: estimatorChecks: disable warning for imminent position failure if that is disabled (COM_POS_FS_EPH=-1).
```
=> estimatorChecks: disable warning for imminent position failure if that is disabled (COM_POS_FS_EPH=-1)

ROMFS/px4fmu_common/init.d-posix/airframes/1010_gazebo-classic_iris_opt_flow
With the current setting of 3m this model is not possible to fly for more than some seconds with optical flow. 15m seems more reasonable.
=> ROMFS gazebo iris opt flow: increase SENS_FLOW_MAXHGT to 15m

src/modules/commander/failsafe/framework.cpp, src/modules/navigator/mission_block.cpp, src/modules/navigator/mission_block.h, src/modules/navigator/navigator_mode.cpp, src/modules/navigator/navigator_mode.h, src/modules/navigator/rtl.cpp, src/modules/navigator/rtl_direct.cpp
The HAGL navigator failsafe I added in https://github.com/PX4/PX4-Autopilot/pull/23501 should be used in all navigator modes.
Centralize the check instead of adding it to each mode separately.
```
Add maximum height above ground (HAGL) check to all Navigator modes
```
- SITL tests
=> Add maximum height above ground (HAGL) check to all Navigator modes

Tools/upload.sh
When trying to upload firmware via `upload.sh` we get infinite wait time for the bootloader. Fixing typo, fixes the issue.
If possible, @AlexKlimaj , take a look.
=> Fixes upload.sh for arkv6x

src/modules/navigator/rtl.cpp
This is to prevent that a large NAV_ACC_RAD leads to very high return altitudes.
At some point we should reconsider the cone logic, seems unnecessary complicated. 
```
Bugfix: RTL: cone: never climb more than to RTL_RETURN_ALT
```
=> RTL: cone: never climb more than to RTL_RETURN_ALT

src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp, src/modules/navigator/land.cpp
There was a problem where triggering Land, while having a forward velocity, the landing algorithm didn't compensate it, meaning the vehicle remained drifting while getting closer to the ground , and in some cases jerking unsteadily
i set the target landing location based on the current velocity, maximum acceleration and jerk. this way the drone is able to compensate the velocity and land smoothly at the target location.
- changed the lat and long in the triplet generation process in the navigator to be at a location in front of the vehicle, dependent on its current state.
- set the previous setpoint triplet to be the same as the target one, this way we avoid getting into offtrack mode.
```
Bugfix: Unsteady landing with horizontal velocity
Documentation: the position set point for landing …
```
=> Landing horizontal velocity compensation / unsteady landing

ROMFS/px4fmu_common/init.d/rcS, platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp, platforms/nuttx/src/px4/common/px4_mtd.cpp, platforms/nuttx/src/px4/stm/stm32_common/board_hw_info/board_hw_rev_ver.c, src/modules/logger/Kconfig, src/modules/logger/logger.cpp, src/systemcmds/hardfault_log/CMakeLists.txt, src/systemcmds/param/CMakeLists.txt
We built a smol FMU without SD card only with FRAM as minimal file system. Also doesn't have the revision resistors only EEPROM.
1. LittleFS manages the FRAM as `/mnt/microsd` and mounts it as `/fs/microsd`. We chose to keep the paths the same for compatibility. The `rcS` needs minor updates to allow the hardfault handler to still work.
2. The FRAM can do 30MHz writes, but the RamTron only does 10MHz by default. Adding a new `BOARD_SPI_RAMTRON_SPEED_MHZ` define to make that configurable.
3. LittleFS requires more stack in a couple of tasks (this is probably not the best solution).
4. Our board does not have a resistor for revisions, it only stores it in the EEPROM. Adding a new `BOARD_HAS_ONLY_EEPROM_VERSIONING` define to enable that behavior.
```
Feature Allow using …
```
=> Adapt for FMU with only FRAM and EEPROM

Makefile
Ubuntu 22.04 uses make 4.3 which broke the current `make help` target Reference:
https://stackoverflow.com/a/26339924
Running `make help` on Ubuntu 22.04 (make 4.3) returned:
```
Usage: make <target>
Where <target> is one of:
make: *** [Makefile:559: help] Error 1
```
Update the `make help` target so that it compatible with make 4.3 as suggested in https://stackoverflow.com/a/26339924
For release notes: NONE
=> fix: `make help` target on Ubuntu 22.04

src/modules/navigator/MissionFeasibility/FeasibilityChecker.cpp, src/modules/navigator/MissionFeasibility/FeasibilityChecker.hpp, src/modules/navigator/MissionFeasibility/FeasibilityCheckerTest.cpp, src/modules/navigator/mission_feasibility_checker.cpp
In the mission feasibility, it is checked if the 1st waypoint is too far from the current position. This means that the mission feasibility can change during flight if moving further away from the first waypoint. The mission feasibility should not be able to change depending on the current position of the AV.  Especially when a long mission is flown and interrupted, the mission check should make a mission infeasible because the AV did fly away from the fist mission item.
Since the first waypoint mission check should indicate that potentially an old mission from another location is loaded in PX4 it should not be able to change the feasibility in flight 
- The 1st waypoint check only generates a warning in QGC, but does not invalidate a mission
- The 1st waypoint …
=> Rework 1st waypoint check

.github/workflows/build_all_targets.yml
Use the Dronecode AWS Infrastructure for CI workflow runs. This PR introduces access to a paid Dronecode/PX4 AWS account for workflows. Initially, we are only using it for the new "Build All targets" workflow. 
To use the Dronecode Infrastructure, you have to add a similar line ([runner types available](https://runs-on.com/features/custom-runners/)):
> runs-on: [runs-on,runner=8cpu-linux-x64,image=ubuntu22-full-x64,"run-id=${{ github.run_id }}"]
**Current Setup**
* CPU: 8 cores
* RAM: 32GB
* AWS EC2 Type: m7a.2xlarge
* Max Concurrent Servers: 60
**Debug Access**
* Any user with Github admin access and a valid SSH key configured in github.com
* Click on the "Set up job" step and access the runner details
**Build Time Comparison (additive)**
* Dronecode Infra: **2h 18m 42s**
* Github …
=> ci: try runs-on Dronecode Infra

src/modules/simulation/gz_bridge/GZBridge.cpp, src/modules/simulation/gz_bridge/GZBridge.hpp
When running the simulation in gz, the model is not being followed by default.
- Fixes https://github.com/PX4/PX4-Autopilot/issues/22659
@frede791 FYI
Start gz with a follow mode engaged to the model
```
Feature/Bugfix Gazebo gui follows model by default
```
We could also create a custom plugin to follow the model
```
make px4_sitl gz_x500
```
- Thanks for the pointers! @srmainwaring
- We probably need https://github.com/gazebosim/gz-gui/pull/515 to make the follow camera smoother
=> Follow model in gz GUI

ROMFS/px4fmu_common/init.d-posix/airframes/1045_gazebo-classic_quadtailsitter
When running the gazebo classic quadtailsitter, I noticed one of the params in the airframe folder had a typo. This fixes that.
Switch `parm` for `param`
```
Fixed a small param typo in the gazebo classic quadtailsitter
```
- This was run in simulation before and after the change. I didn't see any difference because the FailureDetector was never triggered with or without the fix.
=> Fix param typo in quadtailsitter airframe

src/modules/navigator/mission_base.cpp
make sure to ignore any mission item yaw angle for the landing. Currently only the yaw angle for the final land item is ignored, but not for the part where the AV is moving to the land position. This can result in the AV turning while moving to the land location.
- Force the yaw angle to NaN before the mission item is changed for the land sub state machine
```
Bugfix: Force the heading angle to NaN for each mission landing substate 
```
If the landing yaw needs to be considered, it should be another specific substate in the land state machine before the descend aligning the heading. Currently it is completely ignored.
- Simulation testing
=> Fix force heading to NaN on mission landing approach

src/modules/navigator/navigator_main.cpp
It previously didn't catch switches to Descend from a manual mode, as both modes have navigation_mode_new=nullptr.
=> Navigator: make sure VTOL transitions in Descend mode are always triggered

src/modules/commander/failsafe/failsafe.cpp
For many failsafes, it is possible to select RTL and Land as actions. In this commit I synchronize the clear condition for these two action options, to always only clear on Disarm or manual mode change. Reasoning is that for the user RTL and Land is a similar action and I would thus expect them to be as similar as possible. And I in general would rather not clear a failsafe state instead of too often clearing it.
Example: GF failsafe with action Land --> even if the drone is marginally within the GF again, I want it to proceed with the Landing unless I manually intervene.
```
Improvement: Commander: Failsafe: set clear condition for action Land like for RTL (OnModeChangeOrDisarm)
```
We can also discuss if for each failsafe and set the clear condition of Land …
=> Commander: Failsafe: set clear condition for action Land like for RTL (OnModeChangeOrDisarm)

src/modules/navigator/land.cpp
When triggering a Land on a VTOL, the horizontal speed might not be zero after the back transition, resulting in a weird flying back movement, which comes from the fact that the setpoint is only updated until the transition is done, and not until it has come to a stop.
I propose we adapt the target landing location location setpoint based on the current velocity, and possible acceleration and jerk in MC mode.
```
Bugfix: VTOL Landing Location
Documentation: Landing location for VTOL is where it came to an full halt, and not where backtransition was completed.
```
Tested in SITL & on [Hardware](https://review.px4.io/plot_app?log=629ef75e-c257-4a24-912b-527d2f9634e6)
=> Navigator: Land: Improve it for VTOL by taking breaking distance into account

.github/workflows/sitl_tests.yml
Update the MAVSDK SITL tests to a new runner, upgrade actions in steps, and clean some older stuff.
**Note:** Tests now run on Dronecode Infrastructure (AWS), see inline comments for details
**Before**
**After**
=> ci: upgrade sitl mavsdk tests workflow

Tools/setup/ubuntu.sh
The EOL is approaching for gz garden (Nov 2024)
https://gazebosim.org/docs/latest/releases/
Update release to a LTS release of Gz (harmonic)
```
Feature/Bugfix Bump default version of gz to harmonic
Documentation: Need to update the documentation to use gz harmonic
```
No alternatives
- Tested with gz
```
make px4_sitl gz_x500
```
- This might fix the airspeed sensor issue go away
=> Update gz version to harmonic

msg/EstimatorStatusFlags.msg, src/modules/ekf2/EKF/aid_sources/fake_pos_control.cpp, src/modules/ekf2/EKF/common.h, src/modules/ekf2/EKF/control.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/ekf_helper.cpp, src/modules/ekf2/EKF/estimator_interface.h, src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp, src/modules/ekf2/test/CMakeLists.txt, src/modules/ekf2/test/sensor_simulator/airspeed.cpp, src/modules/ekf2/test/test_EKF_airspeed.cpp, src/modules/ekf2/test/test_EKF_fake_pos.cpp
When on a catapult, the vehicle might need to throttle up before triggering the catapult. This makes the "at rest" flag false (and this is correct) and the ekf goes into inertial dead-reckoning if no other aiding source is active. 
Since we know that the vehicle doesn't move while on a catapult, tell the ekf that that the vehicle stays at a constant position. The EKF can then start a "valid" fake position fusion. Then, if a valid fake position is fused and that we expect to have airspeed fusion in air, the local position can remain valid too.
```
```
unit test
=> EKF2: constant position aiding

src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp
Only allow setting `MAV_SYS_ID` and `MAV_COMP_ID` when initializing commander, similar to the implementation in the mavlink module.
fixes #22542 
https://github.com/user-attachments/assets/147dd037-4317-4ac7-b9da-4ecb09c73171
=> Commander: lock down mav_sys_id and mav_comp_id

CMakeLists.txt, src/lib/version/CMakeLists.txt, src/lib/version/px_update_git_header.py
We've been kind of obnoxious trying to enforce our git tagging convention for versioning, but this causes problems for 3rd parties that might clone without tags or may want to do their own thing.
I've updated the PX4_GIT_TAG in cmake so that it defaults to v0.0.0 if it doesn't find a match, and to pass that same found tag into `src/lib/version/px_update_git_header.py` so we don't have multiple areas of the codebase independently doing the same thing.
- default to v0.0.0 if tag isn't available
- src/lib/px_update_git_header.py use same PX4_GIT_TAG as cmake
- update lingering `master` branch references to `main`
For reference this is the obscure build failure someone will see if they happen to not have the tags (or the wrong tags).
=> cmake: relax git tag requirements

src/modules/ekf2/EKF/ekf_helper.cpp
This is very unlikely to actually matter, but we might as well be consistent. The `_accel_magnitude_filt` is also used by gravity fusion.
=> ekf2: always use corrected accel/gyro for filtered metrics

src/modules/simulation/gz_bridge/GZBridge.cpp
When launching a world in gazebo ignition different from 'default', PX4 does not start up, instead waiting forever for GZ to become available.
This is due to a missing string substitution in https://github.com/PX4/PX4-Autopilot/blob/ebbb880e925628fbf9357a7c5f06cc3982d3f3d6/src/modules/simulation/gz_bridge/GZBridge.cpp#L157
Fixes #23612 
- Add the missing world string substitution
```
Bugfix: Worlds different from 'default' are now correctly working with GZ again
```
See issue #23612
=> gz: Fix endless wait for gazebo on different worlds

platforms/nuttx/init/stm32f7/rc.board_arch_defaults
With current main, VTOLs with UACAN enabled use close to maximum of the RAM  (around 97%) on F7 (tested on v5x).
Reduce the `LOGGER_BUF` if UAVCAN is enabled, similar to what is already done [here](https://github.com/PX4/PX4-Autopilot/blob/f32f821f0220d4c8c4391534fc71594bb454e239/platforms/nuttx/init/s32k1xx/rc.board_arch_defaults#L8). I for now reduce the logger buffer by 24, which is close to 5% RAM reduction on the F7 and pushes my specific setup below the 95% RAM limit (v5x, VTOL, UAVCAN enabled, 3 mavlink instances). 
```
Improvement: f7: reduce LOGGER_BUF to 40 if UAVCAN is enabled
```
Save RAM in other areas, especially in the UAVCAN driver.
=> f7: reduce LOGGER_BUF to 40 if UAVCAN is enabled

src/modules/logger/log_writer_file.cpp, src/modules/logger/log_writer_file.h
This updates logger to automatically limit the buffer size at the time of allocation to available free memory and a 1 kilobyte margin.
I don't love the platform ifdef dropped in the middle of log_writer_file, but this is better than accidentally missing logging and only finding out later.
=> logger: limit buffer size to available free memory (NuttX only) 

test/mavsdk_tests/test_vtol_rtl.cpp
Loosen landing position check on the VTOL RTL Mission Landing tests, they were constanly failing by a small margin in the  desired position and actual
https://github.com/PX4/PX4-Autopilot/actions/runs/10523210703/job/29157445168#step:19:1446
=> tests: loosen radius of vtol rtl landing pos check

src/modules/ekf2/EKF/ekf.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF2.cpp, src/modules/ekf2/test/CMakeLists.txt, src/modules/ekf2/test/test_EKF_airspeed.cpp
requires https://github.com/PX4/PX4-Autopilot/pull/23590
[MAV_CMD_EXTERNAL_POSITION_ESTIMATE](https://mavlink.io/en/messages/common.html#MAV_CMD_EXTERNAL_POSITION_ESTIMATE) contains an "Altitude" field but is currently not handled by the EKF
Add support for altitude external reset
```
```
added unit test
=> EKF2: Handle external altitude resets

src/lib/mixer_module/mixer_module.cpp, src/lib/mixer_module/mixer_module.hpp
I found that when instance start is set in an actuator output yaml to something besides 1 then the parameters don't match the expected from mixer_module.cpp. I submitted an issue here
Fixes #23615
- I added a const to the constructor of MixingOutput called instance_start that defaults to 1
- I added a const instance_start to initParamHandles
- When initParamHandles the const from the constructor is used and passed in
- In initParamHandles instead of adding 1 to each parameter name, the instance_start parameter is added
```
Feature/Bugfix: Correct param handles are now selected when instance_start is used in actuator output drivers
```
We could also remove the functionality that is already available in the metadata generator, but that seems silly as this is only adding …
=>  Allowing instance_start to be used properly with new actuator output types

src/modules/mavlink/streams/ESC_STATUS.hpp
The indexing was wrong for esc_status sending for ESCs 4->
AFAIK the ESC_STATUS mavlink stream is not used much, QGroundControl doesn't even show it in the mavlink inspector even if streamed from the drone.
Anyhow, it is probably better to fix this
=> mavlink: Fix ESC_STATUS sending for batches > 1

msg/SensorAirflow.msg
I found there was a smell typo in the airsim px4 msgs. This just makes a small spelling fix.
- Fix typo in SensorAirflow message
=> Fix spelling of airflow sensor msg comments

src/modules/ekf2/EKF/aid_sources/aux_global_position/aux_global_position.cpp, src/modules/ekf2/EKF/aid_sources/gnss/gps_checks.cpp, src/modules/ekf2/EKF/ekf.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/ekf_helper.cpp, src/modules/ekf2/EKF2.cpp, src/modules/ekf2/test/CMakeLists.txt, src/modules/ekf2/test/test_EKF_airspeed.cpp
We now have 2 options to set the origin of the local frame:
- set the origin given the lat/lon/alt of the origin
- set the origin given the current lat/lon/alt of the vehicle
=> EKF2: origin reset cleanup

src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.cpp, src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.hpp, src/modules/commander/commander_params.c
Despite having `COM_ARM_WO_GPS` set, the autopilot still sends a Warning message. This is sometimes annoying and there is no way to avoid it.
Extend `COM_ARM_WO_GPS` to either disable arming or just send a warning message, or disable the check (i.e.: allow arming and don't send any message).
SITL tested the 3 cases
=> Commander: extend COM_ARM_WO_GPS to disable warning

src/modules/commander/commander_params.c, src/modules/commander/failsafe/failsafe.cpp, src/modules/commander/failsafe/failsafe.h
Small clean up in Commander:
- make clear that with "Manual" we actually mean "Stabilized" flight mode (which are only the same thing for Hovering vehicles)
- improve description of `COM_POSCTL_NAVL`
- only have one decimal value for `COM_FAIL_ACT_T`, that should be enough and improves the readability of the param.
=> Commander: small clean up: Manual-->Stabilized rename, COM_POSCTL_NAVL better description

src/modules/rover_differential/RoverDifferential.cpp, src/modules/rover_differential/RoverDifferential.hpp, src/modules/rover_differential/RoverDifferentialControl/RoverDifferentialControl.cpp, src/modules/rover_differential/RoverDifferentialControl/RoverDifferentialControl.hpp
This PR adds a way for the differential rover module to handle disarm.
If the vehicle is disarmed it will reset the integrators of all PID controllers and publish zero setpoints for foward speed and steering. This ensures that all motor commands are set to zero before arming again, removing any undefined behaviour caused by "residual" setpoints or integrators.
Tested in SITL and with hardware.
=> differential: reset controllers and setpoints on disarm

msg/DistanceSensor.msg, src/drivers/distance_sensor/lightware_laser_i2c/lightware_laser_i2c.cpp, src/lib/drivers/rangefinder/PX4Rangefinder.cpp, src/lib/drivers/rangefinder/PX4Rangefinder.hpp, src/modules/commander/HealthAndArmingChecks/checks/distanceSensorChecks.cpp
We have to option for the lightware laser driver to disable the sensor when in VTOL fixed wing flight. However, if the sensor is mandatory, a health failure warning appears, since no sensor data is published.
- If a distance sensor is in VTOL mode, mark the sensor as valid even when no data has arrived.
```
Bugfix: Disable health failure reporting if the SFXX_MODE is set to 2
```
=> DistanceCheck: Disable health failure reporting if the SFXX_MODE is set to 2

src/modules/commander/Commander.cpp
The manual trigger of "Land" mode is often done in emergencies, when you want the vehicle to stop the current operation and land ("come down") at the current spot. As it is though an auto flight mode, the Land mode gets rejected when e.g. local position is invalid. In these scenarios the only option for the pilot is to land the vehicle manually, which is a more complex action than clicking on a single button. And for VTOL there comes additional complexity should the pilot have to land it manually, as in that case he/she has to also trigger the transition manually. If in Land/Descend mode the transition to Hover is automatically done.
For now hard-coded that the switching into Land does never get rejected. We maybe want to hide it behind a param or an extra field in the mavlink messages …
=> Commander: always allow to switch to LAND mode, also if requirements are not met

src/modules/commander/Commander.cpp
One ack from Commander (with VEHICLE_CMD_RESULT_UNSUPPORTED), and then one from EKF2 (with VEHICLE_CMD_RESULT_ACCEPTED). Gives you a warning in the GCS.
Add VEHICLE_CMD_EXTERNAL_POSITION_ESTIMATE to the list of commands that is not handled by Commander.
```
Bugfix: Commander: fix wrong ack reporting for VEHICLE_CMD_EXTERNAL_POSITION_ESTIMATE
```
=> Commander: fix wrong ack reporting for VEHICLE_CMD_EXTERNAL_POSITION_ESTIMATE

msg/BatteryStatus.msg, src/drivers/power_monitor/ina228/ina228.cpp, src/drivers/power_monitor/ina228/ina228.h, src/drivers/power_monitor/ina238/ina238.cpp, src/drivers/power_monitor/ina238/ina238.h, src/drivers/power_monitor/ina238/ina238_registers.hpp, src/lib/battery/battery.cpp, src/lib/battery/battery.h
The INA228 and INA238 sensors have packaged temperature sensors. With this PR it is possible to use the temperature readings from these sensors. They are published in the field "temperature" of "BatteryStatus"
- Extended the Battery abstraction to also include a temperature
- Read out the temperature values from the sensors via I2C
```
Feature Added INA228 / INA238 temperature sensor support
```
When we want to use the temperature measurements of those sensors there is no alternative.
- Was tested locally at the bench
=> Implemented temperature sensor support for INA228 / INA238

src/modules/vtol_att_control/standard.cpp
We noticed on a standard VTOL configuration that the vehicle would start spinning in yaw during the backtransition. Currently, we blend in the multicopter torque and blend out the fw torque. 
In practice it seems to make more sense to allow the fw control surfaces to generate torque, rather than just blending them out. We were able to solve the backtransition issue completely with this change.
I also verified, that the scaling was not present in older PX4 versions and explains why this issue only appear on newer PX4 version.s
```
Removed scaling on fixed wing torque setpoints for VTOL transitions.
```
=> Standard VTOL: Remove scaling of fw torque setpoint during transition

.ci/Jenkinsfile-compile, .vscode/cmake-variants.yaml, Makefile
Dear PX4-Autopilot Developers.
I am about to test v1.15.0-rc2 with VIO and upload my flight LOG. And then I found that the MicoAir743 board is missing compile settings. So I added them in this PR.
=> Add micoair h743 compile settings

src/modules/land_detector/RoverLandDetector.cpp, src/modules/land_detector/RoverLandDetector.h
The RTL sequence from the navigator requires the vehicle to land. Currently the rover gets stuck in the "land" phase of RTL because the rover land detector is never set to true.
This is now handled for rovers by setting its state to landed if it is within the acceptance radius of the home position when in return mode.
The automatic disarm can be avoided by setting the RTL_LAND_DELAY to -1, similar to USVs. In that case the rover does not detect landing and will stay armed and in **return** mode.
- Tested on hardware
=> rover: add rtl as a landed condition for rovers

src/modules/simulation/gz_bridge/CMakeLists.txt
Gazebo simulation did not run on 24.04 with the latest version of Gazebo Ionic.
- Add `gz-transport14` to the options of `gz-transport` libraries to find in the CMakeLists
- Refactor the find_package to be simpler and just use the NAMES instead of the clunkier if statement
```
Feature: Add support for Gazebo Ionic
```
- Ubuntu 24.04 with Gazebo Ionic - tested with the X500
- Ubuntu 22.04 with Gazebo Harmonic - tested with the X500
I didn't see any issues building or running the simulation for these two configurations.
=> Simplify gz bridge CMakeLists and add GZ Ionic

msg/PositionSetpoint.msg, src/modules/fw_pos_control/FixedwingPositionControl.cpp, src/modules/navigator/mission.cpp, src/modules/navigator/mission.h, src/modules/navigator/mission_base.cpp, src/modules/navigator/mission_base.h, src/modules/navigator/mission_block.cpp, src/modules/navigator/navigator.h, src/modules/navigator/navigator_main.cpp, src/modules/navigator/rtl_direct_mission_land.cpp, src/modules/navigator/rtl_mission_fast.cpp
When flying Fixed Wings in a space constrained area, it can be difficult to plan the usual orbit type mission landings.
There might simply not be enough space for the vehicle to orbit while it's descending in altitude.
Of course, one can just plan a mission with simple waypoints and add a VTOL LAND waypoint at the end. However, there is always the risk that the altitude difference between the waypoints is too big and the vehicle cannot follow the glide-slope, causing it to loiter at the next waypoint in order to reduce altitude further. This behavior is highly undesirable as part of a mission landing, as already explained above.
I propose a solution where all simple waypoints AFTER a land stark marker have their altitude acceptance radius set to INFINITY, which …
=> Support straight line mission landings

ROMFS/px4fmu_common/init.d-posix/airframes/4009_gz_r1_rover, ROMFS/px4fmu_common/init.d/airframes/50001_aion_robotics_r1_rover, msg/RoverDifferentialStatus.msg, src/modules/rover_differential/RoverDifferential.cpp, src/modules/rover_differential/RoverDifferential.hpp, src/modules/rover_differential/RoverDifferentialControl/RoverDifferentialControl.cpp, src/modules/rover_differential/RoverDifferentialControl/RoverDifferentialControl.hpp, src/modules/rover_differential/RoverDifferentialGuidance/RoverDifferentialGuidance.cpp, src/modules/rover_differential/RoverDifferentialGuidance/RoverDifferentialGuidance.hpp, src/modules/rover_differential/module.yaml
Currently closed loop yaw rate and speed control is disabled if the setpoints are zero. This leads to issues such as when driving in a straight line in acro mode (zero yaw rate setpoint) as it will not counteract disturbances.
Initially this was done to stop the rover from moving at stand still due to measurement noise. This is now fixed by adding minimum thresholds on the yaw rate and speed measurements.
This PR also adds an improvement for the tuning process for the closed loop control by adding individual parameters for tuning the feed forward part of both yaw rate and speed.
=> Differential: Improve closed loop yaw rate and speed control

src/modules/navigator/mission_block.cpp
Currently the terrain avoidance check in the mission is always run when the mission mode is activated. it is even run when the mission has ended and the mission mode sets the idle navigation item. 
- Do not make terrain avoidance check on idle mission item
```
Bugfix: Do not make terrain avoidance check on idle mission item
```
We could also check that we are landed and prevent the terrain avoidance check then or do not call the function on these conditions.
=> mission_base: do not make terrain avoidance check on idle

msg/TecsStatus.msg, src/lib/tecs/TECS.cpp, src/lib/tecs/TECS.hpp, src/modules/fw_pos_control/FixedwingPositionControl.cpp
When fast descend is enabled it checks if the vehicle is currently climbing. While it is still climbing, it will send the throttle_trim value as throttle command instead of the minimum throttle to prevent stalling. However in thermal conditions, we can climb in altitude while the nose is pointing downwards. This can lead to TECS toggling the throttle between throttle_trim and throttle_min.
- Instead of switching directly into the fast descend and use additional logic to counter stalling while still climbing, the fast descend is ramped up during 2s after it exceeds the threshold.
```
Bugfix Do not toggle throttle setpoint when trying to enter fast descend in thermal conditions
```
Another guard would be using a hysteresis to avoid toggling the throttle setpoint. The fix …
=> TECS: ramp up fast descend

ROMFS/px4fmu_common/init.d/airframes/1102_tailsitter_duo_sih.hil, src/modules/simulation/simulator_sih/sih.cpp
Fix airspeed reading and set some reasonable parameter to allow the transition to complete and the vehicle to fly.
```
```
=> Fix tailsitter SIH

src/modules/land_detector/RoverLandDetector.cpp
Currently the land detector for rover detects landing if the nav state is land, the same should happen in descend.
This was tested in SITL by disabling GPS during a mission which activates descend mode.
=> Rover: add descend navigation state to land detection

ROMFS/px4fmu_common/init.d-posix/airframes/4009_gz_r1_rover, ROMFS/px4fmu_common/init.d/airframes/50001_aion_robotics_r1_rover, src/lib/pure_pursuit/PurePursuit.cpp, src/lib/pure_pursuit/PurePursuit.hpp, src/modules/rover_differential/RoverDifferential.cpp, src/modules/rover_differential/RoverDifferential.hpp, src/modules/rover_differential/RoverDifferentialGuidance/RoverDifferentialGuidance.cpp, src/modules/rover_differential/RoverDifferentialGuidance/RoverDifferentialGuidance.hpp, src/modules/rover_differential/module.yaml
Implemented support for position and stabilized mode for differential rovers.
Addresses  [#23660](https://github.com/PX4/PX4-Autopilot/issues/23660)
**Stabilized mode**
This mode is one step up from acro mode. It also uses _closed loop yaw rate control_, but in addition to that it does _closed loop yaw control_ when the yaw rate setpoint (stick input for yaw rate) is zero.
This means that the rover will maintain the current heading if the user only gives throttle input, but no yaw rate input. 
Compared to acro, this mode is much better at driving in a straight line as it can more effectively reject disturbances.
The yaw is close loop controlled using a cascaded PID:
**Position mode**
This is the most advanced manual mode.
It uses _closed loop yaw rate control_, _closed loop speed control_ …
=> Differential: Add stabilized and position mode

src/lib/matrix/matrix/Slice.hpp, src/lib/matrix/matrix/SquareMatrix.hpp, src/lib/matrix/matrix/Vector2.hpp, src/lib/matrix/test/MatrixSliceTest.cpp, src/lib/matrix/test/MatrixVector3Test.cpp
The problem was that addition and subtraction with slices didnt work. 
calculation as such didnt work
```
pos_error = _position.xy() - _position_setpoint.xy()
```
Added Addition and Subtraction to the Matrix Slice class
```
Feature Added: added Addition and Subtraction to matrix slices
```
- Wrote Automatic Tests
=> Misc: Matrix: Added Addition and Subtraction to Slices

src/modules/simulation/gz_bridge/CMakeLists.txt
`src/modules/simulation/gz_bridge/CMakeLists.txt` contains a duplicate entry in the `gz_worlds` list, causing build errors due to conflicting target definitions.
- Removed the duplicate `aruco `entry from the `gz_worlds` list..
```
Bugfix: Fixed duplicate world entry in `gz_worlds` list causing build failure for simulation targets.
```
- make test
=> Fix duplicate entry in gz_worlds list

ROMFS/px4fmu_common/init.d-posix/airframes/4008_gz_advanced_plane
The default gains in the Advanced Plane airframe yields poor tracking performance in Gazebo Garden simulation
Tune the gains for the Advanced Plane simulation model and update the current default ones stored in the airframe
- SITL testing on Gazebo Garden
New tracking behaviour
=> GZ Advanced Plane: improved rate/TECS tuning

ROMFS/px4fmu_common/init.d-posix/airframes/10040_sihsim_quadx, ROMFS/px4fmu_common/init.d-posix/airframes/10041_sihsim_airplane, ROMFS/px4fmu_common/init.d-posix/airframes/10042_sihsim_xvert, ROMFS/px4fmu_common/init.d-posix/airframes/4006_gz_px4vision, ROMFS/px4fmu_common/init.d/airframes/1001_rc_quad_x.hil, ROMFS/px4fmu_common/init.d/airframes/1002_standard_vtol.hil, ROMFS/px4fmu_common/init.d/airframes/1100_rc_quad_x_sih.hil, ROMFS/px4fmu_common/init.d/airframes/1101_rc_plane_sih.hil, ROMFS/px4fmu_common/init.d/airframes/1102_tailsitter_duo_sih.hil, ROMFS/px4fmu_common/init.d/airframes/13013_deltaquad, ROMFS/px4fmu_common/init.d/airframes/18001_TF-B1, ROMFS/px4fmu_common/init.d/airframes/2507_cloudship, ROMFS/px4fmu_common/init.d/airframes/4016_holybro_px4vision, ROMFS/px4fmu_common/init.d/airframes/4020_holybro_px4vision_v1_5, ROMFS/px4fmu_common/init.d/airframes/60002_uuv_bluerov2_heavy, ROMFS/px4fmu_common/init.d/airframes/6002_draco_r, boards/diatone/mamba-f405-mk2/init/rc.board_defaults, boards/flywoo/gn-f405/init/rc.board_defaults, boards/omnibus/f4sd/init/rc.board_defaults, boards/raspberrypi/pico/init/rc.board_defaults, boards/sky-drones/smartap-airlink/init/rc.board_defaults
Since https://github.com/PX4/PX4-Autopilot/pull/16847, `CBRK_IO_SAFETY` is already enabled by default, but still was set in many airframes.
=> aiframes: remove setting of CBRK_IO_SAFETY to enabeld, as that's already the param default

src/modules/navigator/rtl_direct.cpp
When during the RTL loiter down, the terrain avoidance is triggered and the vehicle is kept on an altitude higher than the indented one, it will try to sink to the indented altitude again at the end of the loiter. This is due to the loiter hold after the loiter down enforcing the altitude again.
- The loiter hold should only track the altitude as best effort but accept any altitude error. it should only check on the loiter time.
- Also make sure that the loiter hold forces the heading if necessary. Not an issue per se but it was only implicitely set from the prior mission item
```
Bugfix After RTL terrain avoidance is triggered during the loiter down, make sure to not try to sink again before proceeding to the land destination
```
- SITL testing: Tested in sitl with …
=> rtl_direct: loiter hold should track altitude as best effort 

src/drivers/distance_sensor/lightware_sf45_serial/lightware_sf45_serial.cpp, src/drivers/distance_sensor/lightware_sf45_serial/lightware_sf45_serial.hpp
Fixes https://github.com/PX4/PX4-Autopilot/issues/23308 when the SF45 is on specific UARTS, the sensor never reports distance data due to being stuck in init. 
Also populates comms_errs if there are issues reading/writing data.
The serial uart data being read reports the start of packet invalid, payload length invalid, and CRC mismatch in the early sensor init state, so the SF_STREAM command never gets sent out. This PR restarts the state machine if there are too many consecutive  errors in the beginning that are the result of UART data mismatch on what the driver expects and what the sensor sends. For unknown reasons the sensor seems to work much better on TELEM1 and TELEM2
Tested on holybro 6x where TELEM 1 and TELEM2 worked fine with the original driver, but TELEM3 did not and the …
=> SF45 fixes to restart the state machine if sensor does not init correctly

src/lib/version/version.c
The version was specified using a GIT tag, but the QGC version was displayed as 0.0.0. Upon investigation, it was found that the version was being determined using an IF statement to check the string.
I will clarify the pattern by changing the IF statement to a SWITCH statement
none
none
No build errors occur, OK.
Test pattern: v11.45.99-1.2.3-alpha3-7-g7e282f57
=> version: Change this IF statement to a SWITCH statement

src/modules/sensors/vehicle_air_data/VehicleAirData.cpp
VehicleAirData is responsible for down sampling the baro (in my case MS5611 with default settings from ~100Hz to 20Hz).
I found that the `vehicle_air_data` topic was published at the expected average rate (20Hz) but with a high variation : publication period is going from 10ms to 90ms):
The result is a high apparent noise on the barometer as some samples are not the average of multiple real sensor measurements.
What happen is that the module takes some measurements during 90ms and publishes the average, then take 1 measurement and publishes it, then the average during 90ms again, then1 measurement, etc
I found that the publication was triggered using the average measurement timestamp. The default configuration give a publication period of 50ms. So to make the average timestamp to increase …
=> fix air data publication rate

src/modules/ekf2/EKF/aid_sources/range_finder/range_height_control.cpp, src/modules/ekf2/test/test_EKF_terrain.cpp
Range does not provide a direct terrain observation but a measurement relative to the height state. De-correlating those states during initialization brings false information to the filter about the terrain accuracy.
Build correlation between the height covariance and terrain by manipulating the Kalman gain (this is possible thanks to the Joseph stabilized covariance update).
By looking at the state covariance matrix after the reset, we can see that a correlation with the vertical velocity, vertical position and vertical accelerometer bias is created. Also, the terrain variance contains both vertical position and range uncertainties.
NOTE: we should do the same for all measurements that are not a direct state observation (e.g.: body vel, airspeed, flow)
unit tests
=> EKF2: consider height covariance for terrain reset to range

src/modules/ekf2/EKF/aid_sources/airspeed/airspeed_fusion.cpp, src/modules/ekf2/EKF/aid_sources/drag/drag_fusion.cpp, src/modules/ekf2/EKF/aid_sources/external_vision/ev_vel_control.cpp, src/modules/ekf2/EKF/aid_sources/fake_height_control.cpp, src/modules/ekf2/EKF/aid_sources/fake_pos_control.cpp, src/modules/ekf2/EKF/aid_sources/gnss/gnss_yaw_control.cpp, src/modules/ekf2/EKF/aid_sources/gravity/gravity_fusion.cpp, src/modules/ekf2/EKF/aid_sources/magnetometer/mag_fusion.cpp, src/modules/ekf2/EKF/aid_sources/optical_flow/optical_flow_fusion.cpp, src/modules/ekf2/EKF/aid_sources/sideslip/sideslip_fusion.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/ekf_helper.cpp, src/modules/ekf2/EKF/position_fusion.cpp, src/modules/ekf2/EKF/velocity_fusion.cpp, src/modules/ekf2/EKF/yaw_fusion.cpp
merge after https://github.com/PX4/PX4-Autopilot/pull/23577
`fuseDirectStateMeasurement` and `measurementUpdate` are always returning `true` so we have a ton of unnecessary code to handle the `return false` case.
Change those functions to `void` and always assume that the fusion worked (because it always do).
```
-
```
unit tests
=> EKF2: fusion always succeeds, do not return boolean

src/drivers/gnss/septentrio/module.yaml
Fixes assignment of GPS1 by default
https://github.com/PX4/PX4-Autopilot/issues/23714#issuecomment-2370671684
=> gnss: disable default assignment of GPS1

src/drivers/gnss/septentrio/module.yaml
backport of https://github.com/PX4/PX4-Autopilot/pull/23718
fixes https://github.com/PX4/PX4-Autopilot/issues/23714
=> [RELEASE/1.15] Septentrio: disable default assignment of GPS1

boards/px4/fmu-v5x/src/board_config.h, boards/px4/fmu-v6x/src/board_config.h
As far as I can see fmu v5x and fmu v6x are not designed to have rc_input as a single wire uart.
This PR disables this for both targets and fix my issue where RC works only through the px4io but not directly to the fmu.
```
Fix rc_input when connecting the RC receiver directly to the FMU (no px4io).
```
- Tested on Auterion Skynode with both FMU V5X and FMU V6X
=> Fix fmu rc_input on v5x and v6x

boards/ark/fmu-v6x/init/rc.board_sensors, boards/px4/fmu-v6xrt/init/rc.board_sensors
To solve https://github.com/PX4/PX4-Autopilot/issues/22474 it is required that the `board_adc` does always startup to publish the `system_power` message.
The PR solves the problem by always starting the `board_adc`. To avoid that both the `board_adc` and the `ads1115` report adc messages the `-n` flag is used to stop the `board_adc` from reporting it as described in the linked issue.
This solution is already used for some boards but was not rolled-out to each board. This PR adds it to the remaining boards.
=> Always start board_adc

src/modules/commander/failure_detector/FailureDetector.cpp, src/modules/commander/failure_detector/FailureDetector.hpp
Only check for motor failures on indexes that have had non zero current. 
Fixes https://github.com/PX4/PX4-Autopilot/issues/23734
=> Failure detector use per index esc current

src/drivers/cdcacm_autostart/cdcacm_autostart.cpp
The `fd` needs to be set to -1 after calling close(), otherwise a loss of VBUS will kick the module back into the `connecting` state but will immediately pass the `open()` check since `fd` is still valid.
=> [cdcacm_autostart] set file descriptor to -1 after close()

src/modules/commander/failure_detector/FailureDetector.cpp, src/modules/commander/failure_detector/FailureDetector.hpp
https://review.px4.io/plot_app?log=38b1f067-8ff5-4b06-afee-98012f36dfc9
=> backport: failure detector use per index esc current

src/modules/ekf2/EKF/aid_sources/gnss/gnss_height_control.cpp, src/modules/ekf2/EKF/aid_sources/gnss/gps_checks.cpp, src/modules/ekf2/EKF/aid_sources/gnss/gps_control.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/ekf_helper.cpp, src/modules/ekf2/EKF/estimator_interface.h
`_NED_origin_initialised` has the same meaning as `_pos_ref.isInitialized()`
=> EKF2: remove redundant ned_origin_initialised flag

src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp
I would like to change the ekf altitude datum from amsl to wgs84 but I didn't really like the current implementation of the conversion from amsl to wgs84.
Estimate the geoid height by using the filtered difference the GNSS alt and alt_ellipsoid values. Then use this geoid height to convert altitude between amsl and wgs84.
Convention is:
`ellipsoid_height = amsl_height + geoid_height` ([ref](https://www.ngs.noaa.gov/PUBS_LIB/gislis96.html#:~:text=It%20is%20a%20straightforward%20procedure,H%20%3D%20h%20%2D%20N%20.))
Tested in SITL with a geoid height of 29m
=> EKF2: rework amsl to ellipsoid altitude conversion

src/modules/mc_pos_control/MulticopterPositionControl.cpp, src/modules/mc_pos_control/PositionControl/PositionControl.hpp
In some cases the velocity integrator can be strongly loaded when switching out of position control (e.g.: switch during braking or strong wind). When resuming position control, the drone is disturbed by this pre-loaded integrator since the conditions changed.
Reproduced in SITL:
fly fast in altitude mode, briefly switch into position mode, then stop the drone and re-engage pos control
Reset all integrators when not in a position controlled mode (e.g.: stabilized)
Reset the xy integrators when in altitude mode
Tested using https://github.com/PX4/PX4-Autopilot/pull/19649 to see the integrators.
```
```
SITL
=> MPC: reset velocity integrators when not in use

src/modules/ekf2/EKF/control.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/terrain_control.cpp
- require valid fusion from a range finder or optical flow before considering terrain valid again
This partially addresses https://github.com/PX4/PX4-Autopilot/issues/23761 where the terrain estimate was considered valid based on the variance before valid range finder data was available.
=> ekf2: tighten terrain validity requirements

src/modules/time_persistor/CMakeLists.txt, src/modules/time_persistor/Kconfig, src/modules/time_persistor/TimePersistor.cpp, src/modules/time_persistor/TimePersistor.hpp
On boards that don't have a hardware RTC, but a software RTC, the date and time are reset to a default value on each boot. Because of that the date/time is not monotonic and several problems arise. One example is that it is hard to analyse log files as it is difficult to order the entries.
A new module called time_persistor is added. It cyclically writes the RTC time to a file and reloads this value on startup.
This allows monotonic time on systems that only have a software RTC (that is not battery powered).
Explicitly setting the time backwards (e.g. via system_time) is still possible.
```
Feature Added time persistor to store RTC in persistent storage (for date/time monotony on software RTC boards)
```
If a system has a hardware RTC, it is not necessary to enable the …
=> Implemented time persistor to save time to persistent storage

src/modules/ekf2/EKF/aid_sources/external_vision/ev_vel_control.cpp, src/modules/ekf2/EKF/aid_sources/gnss/gps_checks.cpp, src/modules/ekf2/EKF/common.h, src/modules/ekf2/EKF/ekf.cpp, src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp, src/modules/ekf2/module.yaml
- replace hardcoded 1000 m/s velocity state constraint with new EKF2_VEL_LIM parameter (default 100 m/s)
- new velocity limit also used for GPS checks and external vision velocity
=> ekf2: configurable velocity state constraint (EKF2_VEL_LIM)

src/modules/ekf2/EKF/aid_sources/gnss/gps_control.cpp
- in the special case of bad vertical acceleration detected (bad_acc_vertical) only allow overriding rejected GNSS 3D velocity if horizontal innovations are accepted
=> ekf2: stricter GNSS vel rejected innovation override

src/modules/ekf2/EKF/common.h
During the bad accel probation period height sources will accept otherwise rejected innovations.https://github.com/PX4/PX4-Autopilot/blob/652bb82603c5f54b611b8a705123bc1e526b07d1/src/modules/ekf2/EKF/aid_sources/gnss/gps_control.cpp#L205-L211
I'm not sure if I can justify this one way or the other, but a 10 second probation time feels way too long, especially if caused by brief periods of accel clipping.
=> ekf2: reduce bad accel probation time 10s->3s

src/drivers/osd/msp_osd/uorb_to_msp.cpp, src/lib/geo/geo.h, src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp, src/modules/flight_mode_manager/tasks/AutoFollowTarget/follow_target_estimator/TargetEstimator.cpp, src/modules/gimbal/output.cpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/navigator/geofence.cpp, src/modules/navigator/precland.cpp, src/modules/simulation/simulator_mavlink/SimulatorMavlink.cpp
@bresch asked me how to write a unit test for the geo library when it depends on the timing driver drv_hrt.
My answer to this is to simply remove the dependency. It's a minor convenience thing for clients such that they don't need to provide their timestamp.
```
Chore: free geo library from drv_hrt dependency to enable unit testing
```
Refactoring that builds SITL, let's see if there's any NuttX target driver that uses geo 👀
=> geo: remove dependency on drv_hrt time driver

src/modules/airspeed_selector/airspeed_selector_main.cpp
Airspeed sensor failures are crucial to catch early during catapult/hand launches, as otherwise the large airspeed error can lead to the vehicle diving (when switched out of Takeoff mode).
The `_in_takeoff_situation` flag, which tells the validator when to enable the checks, is already set to false when `!landed` and `launched`. For runway takeoffs the logic in unchanged. The `launch_detection_status` message is not present on them.
```
Improvement: AirspeedSelector: enable sensor checks right after catapult launch
```
=> AirspeedSelector: enable sensor checks right after catapult launch

src/modules/mavlink/mavlink_mission.cpp
While connected over a groundstation and e.g. using a separate instance like MAVSDK to also download a mission, there will be timeout warnings in the groundstation when trying to make operations in the mission like clearing it. 
This is due to the fact that PX4 currently stores the system and component ID of the last connection partner who uploaded or downloaded a mission. When a mission clear command is received by PX4 it sends the Ack to the last learnt connection partner and not to the partner who send the clear request.
- Make sure that the mavlink ack is actually sent to the right connection partner who requested it.
- Make sure that PX4 only accepts mission items from the connection partner who sent the mission upload request
- Make sure to only accept a mission request item from …
=> fix mission sysid for mission_ack

ROMFS/px4fmu_common/init.d-posix/rcS, src/modules/commander/HealthAndArmingChecks/checks/batteryCheck.cpp, src/modules/commander/HealthAndArmingChecks/checks/batteryCheck.hpp, src/modules/commander/commander_params.c, src/modules/commander/failsafe/failsafe.cpp, src/modules/commander/failsafe/failsafe.h
When trying to fullfil the requirement "vehicle needs to still be aramable with critical battery" I found that it's not as easy anymore to do that with the new checks and failsafe state machine.
PX4 historically allows arming with low battery state (first level) but not with critical or emergency battery state (2., 3. level). Previously changing this behavior was a one-line change and we left it at this.
1. `COM_ARM_BAT_MIN` introduced in https://github.com/PX4/PX4-Autopilot/pull/22175 can be set lower than the critical or emergency threshold percentage now and based on that it allows arming. If it's set to zero (previous default) it always allows arming and hence a negative value disables using this threshold. @sfuhrer I hope this slight change in definition and default is ok.
2. I …
=> Allow arming with critical battery by setting COM_ARM_BAT_MIN lower than BAT_CRIT_THR

src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h
MAVLink recently added additional params to allow specific instances of messages to be streamed with [MAV_CMD_SET_MESSAGE_INTERVAL](https://mavlink.io/en/messages/common.html#MAV_CMD_SET_MESSAGE_INTERVAL) following the same pattern as [MAV_CMD_REQUEST_MESSAGE](https://mavlink.io/en/messages/common.html#MAV_CMD_REQUEST_MESSAGE) in https://github.com/mavlink/mavlink/pull/2148
Specifically, this allows us to tell as specific camera attached to a flight stack that we want it to stream, but it can be used for any purpose.
This updates PX4 to reject the command if it has non-zero values for unused parameters.
A couple of notes:
1. Param 3 was being used to set overall data rates if the value was `> 0`. This is non-compliant with the spec and not documented anywhere (not even sure how it would …
=> MAV_CMD_SET_MESSAGE_INTERVAL reject non-zero values for unused params

src/modules/commander/HealthAndArmingChecks/checks/modeCheck.cpp, src/modules/commander/HealthAndArmingChecks/checks/systemCheck.cpp
The messaging in case of estimation failures (local and global position, altitude) is very minimalistic and not end-user friendly. 
- add "Navigation error" before failure message
- add description
This is how the notification would look like now:
Expanded event (with description):
This is the raw notification, that also pops up in yellow on screen:
```
Improvement: HealthAndArmingChecks: improve messaging for position estimate failure
```
=> HealthAndArmingChecks: improve messaging for position estimate failure

.github/workflows/python_checks.yml
Now that ubuntu-latest has been pushed to Ubuntu 24.04, we need to fix up the pip install.
While at it, we might as well pin to the ubuntu 24.04 version, so we don't have this happen to use out of the blue again.
=> CI: fix Python checks

src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h
This fixes the SITL tests that fail in CI because we catch NAN as non zero after cast to int. To fix this I've added the check whether they are finite at all.
The checks for param5 and param6 would be a bit trickier because they can be int or float, so I have omitted them for now.
=> mavlink: fix SET_MESSAGE_INTERVAL parsing

boards/px4/fmu-v6x/init/rc.board_sensors
It turns out that the airspeed sensor MS5525DSO (e.g. https://holybro.com/products/digital-air-speed-sensor-ms5525dso) uses the same I2C address as the ms5611 potentially connected on the external I2C 3 bus, and so the two conflict and don't work properly.
Fixes #23434.
The suggestion is to just disable the potential external ms5611 for 6X.
```
Disable external ms5611 on Pixhawk 6x to avoid conflicts with MS5525DSO.
```
We could also consider disabling it only if `SENS_EN_MS5525DS` is set to `1` but start it otherwise.
Bench tested.
FYI @vincentpoont2
=> fmu-v6x: disable external baro ms5611

src/lib/mixer_module/mixer_module.hpp, src/lib/mixer_module/motor_params.c
Parameter **MOT_SLEW_MAX** doesn't seems to be used anymore.
=> lib/mixer_module: remove unused param MOT_SLEW_MAX

platforms/nuttx/src/bootloader/common/bl.c
The bootloader can often get stuck parsing random MAVLink traffic, thinking it had seen a GET_SYNC.
Therefore, this commits adds a two step check which requires a GET_SYNC followed by a GET_DEVICE to make sure it's really an uploader script talking to it, and not just random data.
=> bootloader: robustify uploader detection

src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_main.h
[MAV_PROTOCOL_CAPABILITY_COMPONENT_IMPLEMENTS_GIMBAL_MANAGER](https://mavlink.io/en/messages/common.html#MAV_PROTOCOL_CAPABILITY_COMPONENT_IMPLEMENTS_GIMBAL_MANAGER) was added in https://github.com/mavlink/mavlink/pull/2144 to allow a GCS to query if an autopilot/component supports gimbal managers.
This sets the bit to be output.
Note, PX4 may not yet have updated MAVLink to get this bit (so may fail tests). Also may need more robust setting. This is so we don't forget.
=> AUTOPILOT.capabilities includes gimbal manager protocol bit

Tools/px_uploader.py
When the px_uploader.py is used scripted, so without an interactive shell, the progress bar doesn't update. Therefore, I suggest to print a new line instead of a carriage return for the non-interactive shell case.
=> Tools: improve uploader output in scripts

src/modules/commander/commander_params.c
This is a change to request clarification of the term "arm" as it is used in the slow throw mode.
The process to launch in throw mode is to arm the vehicle (send the arm command/switch), then throw the vehicle. The motors only spin when you exceed a speed and then enter free-fall. 
Now normally "arm" means "power the motors and they start spinning", but there it means like a prearm state - motors are powered but they don't spin. The problem is that in this param we use arm to mean start the motors spinning, but at this point we have already sent the arm command so the vehicle is "armed".
I'd like to be precise because the term confused a new user in  https://discord.com/channels/1022170275984457759/1022186188255285399/threads/1295828271186972742
@sfuhrer @MaEtUgR How does this work? My …
=> COM_THROW_SPEED - arm or start motors clarification

msg/VehicleGlobalPosition.msg, src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.cpp, src/modules/ekf2/EKF/aid_sources/barometer/baro_height_control.cpp, src/modules/ekf2/EKF/aid_sources/magnetometer/mag_control.cpp, src/modules/ekf2/EKF/ekf.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/ekf_helper.cpp, src/modules/ekf2/EKF2.cpp, src/modules/ekf2/test/test_EKF_airspeed.cpp, src/modules/ekf2/test/test_EKF_basics.cpp, src/modules/ekf2/test/test_EKF_externalVision.cpp, src/modules/ekf2/test/test_EKF_fake_pos.cpp, src/modules/ekf2/test/test_EKF_fusionLogic.cpp, src/modules/ekf2/test/test_EKF_gps.cpp, src/modules/ekf2/test/test_EKF_yaw_estimator.cpp, src/modules/mavlink/streams/GLOBAL_POSITION_INT.hpp
Follow up to https://github.com/PX4/PX4-Autopilot/pull/23776
This PR introduces validity flags to the global position message as suggested [here](https://github.com/PX4/PX4-Autopilot/pull/23474). Previously, the commander implicitly assumed that if the global position (gpos) was published, it was valid. With these changes, the commander now explicitly relies on the validity state of the global position, ensuring more robust decision-making (in theory one could also check if gpos is getting published and lpos is valid, but this could break at some point).
Instead of checking global position validity within each navigation mode, we leave it to the commander to determine which mode to run based on the best available estimate. While gpos may not always be fully accurate, it still provides the …
=> EKF2: add validity flags to global pos message

src/modules/navigator/land.cpp, src/modules/navigator/loiter.cpp, src/modules/navigator/mission_block.cpp, src/modules/navigator/mission_block.h, src/modules/navigator/navigator.h, src/modules/navigator/navigator_main.cpp
Fixes https://github.com/PX4/PX4-Autopilot/issues/21524
Fixes https://github.com/PX4/PX4-Autopilot/issues/23773
Proposes a partial alternative to https://github.com/PX4/PX4-Autopilot/pull/23839
Land without global position estimate (e.g. GNSS-denied without manually initialized position) was broken since https://github.com/PX4/PX4-Autopilot/pull/21036/commits/efc8c167acd57ca175b9f2eea795b750227263b3. Instead of landing at the current spot it flew to (0/0).
Set lat/lon fields of triplet to NAN if global position is not valid. Further I disable the [breaking distance calculation](https://github.com/PX4/PX4-Autopilot/pull/23546) in this case, as it's requiring global position. Will be anyway removed from Navigator with https://github.com/PX4/PX4-Autopilot/pull/23678.
``` …
```
=> Navigator: land: fix when flying without global position estimate

src/modules/commander/ModeUtil/mode_requirements.cpp, src/modules/flight_mode_manager/tasks/Descend/FlightTaskDescend.cpp, src/modules/fw_pos_control/FixedwingPositionControl.cpp
I recently crashed a VTOL vehicle  in FW after disabling both GPS and baro fusion in air, which made it switch from AUTO to TERMINATE mode.
- remove mode requirement for a valid altitude estimate from DESCEND
- similar to [what is done for MC](https://github.com/PX4/PX4-Autopilot/blob/e234b583b75b0500e1584ca4c2dbcceef15eb52e/src/modules/flight_mode_manager/tasks/Descend/FlightTaskDescend.cpp#L50-L59) handle invalid v/vz in the FW position controller. For FW we in case of invalid v/vz measurements would likely just want the thrust to be 0, such that the vehicle glides down to the ground while still tracking the loiter (assuming it doesn't stall).
```
Improvement: Remove mode_req_local_alt from Descend mode and handle it in FW position controller
```
Can be easily tested …
=> Remove mode_req_local_alt from Descend mode and handle it in FW position controller

src/modules/gimbal/common.h, src/modules/gimbal/gimbal.cpp, src/modules/gimbal/input.cpp, src/modules/gimbal/input.h, src/modules/gimbal/input_mavlink.cpp, src/modules/gimbal/input_mavlink.h, src/modules/gimbal/input_rc.cpp, src/modules/gimbal/input_test.cpp, src/modules/gimbal/output.cpp, src/modules/gimbal/output.h, src/modules/gimbal/output_mavlink.cpp, src/modules/gimbal/output_rc.cpp
When an angular velocity setpoint (`gimbal_manager_set_manual_control`) stops streaming while still commanding non-zero velocity, the gimbal continues turning indefinitely.
Context:
I found this when working with a gimbal that can be steered by a lever but also a "level out" button it's crucial to not constantly send the lever-based angular velocity setpoint (`gimbal_manager_set_manual_control`) because that overrides any button-based attitude setpoint (`gimbal_manager_set_attitude`) immediately again. Solution: only send angular velocity setpoints when the lever is actually deflected and stop sending them when they are zero. But what happens if you lose connection?
1. Little refactor (optional)
2. Save the timestamp of the last received setpoint for every single input case.
3. Implement …
=> Fix: Stop gimbal from spinning when an angular velocity setpoint stream times out

ROMFS/px4fmu_common/init.d-posix/px4-rc.mavlink, Tools/px4moduledoc/srcparser.py, src/modules/gimbal/gimbal.cpp, src/modules/gimbal/input_mavlink.cpp, src/modules/gimbal/input_test.cpp, src/modules/gimbal/input_test.h, src/modules/gimbal/output_rc.cpp
This adds a test to test angular rate input, not just angles.
Also, this fixes MAVLink angular rate input which is in degrees but needs conversion to radians.
At least this second part should probably be backported to v1.15.
Also, make sure to forward gimbal traffic in SITL as it is required for proper discovery of a MAVLink gimbal.
Tested in SITL using typhoon_h480 model
=> Gimbal: add angular rate test and fix deg/rad input

src/modules/fw_pos_control/FixedwingPositionControl.cpp
When the estimator declares local position invalid during a VTOL backtransition in an autonomous mode, the vehicle enters a fixed bank loiter. This is not desired during a backtransition, as the vehicle will start to turn.
Explicitly handle the case where we don't control position during the backtransition by setting the roll setpoint to zero.
```
Bugfix: Prevent fixed bank loiter during backtransition when we lose local position.
```
=> Handle loss of position during backtransition

ROMFS/px4fmu_common/init.d-posix/airframes/4012_gz_rover_ackermann, msg/CMakeLists.txt, msg/RoverAckermannGuidanceStatus.msg, msg/RoverAckermannSetpoint.msg, msg/RoverAckermannStatus.msg, src/modules/logger/logged_topics.cpp, src/modules/rover_ackermann/CMakeLists.txt, src/modules/rover_ackermann/RoverAckermann.cpp, src/modules/rover_ackermann/RoverAckermann.hpp, src/modules/rover_ackermann/RoverAckermannControl/CMakeLists.txt, src/modules/rover_ackermann/RoverAckermannControl/RoverAckermannControl.cpp, src/modules/rover_ackermann/RoverAckermannControl/RoverAckermannControl.hpp, src/modules/rover_ackermann/RoverAckermannGuidance/RoverAckermannGuidance.cpp, src/modules/rover_ackermann/RoverAckermannGuidance/RoverAckermannGuidance.hpp, src/modules/rover_ackermann/module.yaml
This PR implements the following features:
1. Bring the structure of the ackermann module in line with the other rover modules
2. Updates to the slew rate
3. Add a _lateral_acceleration_setpoint_
4. Add support for **Acro** mode
5. Add support for **Position** mode
6. Update **Auto** modes with the lateral acceleration setpoint which deprecates some parameters
1. The module now uses the same structure as the differential and mecanum module:
Note: **Offboard** mode is not yet implemented, but this structure already accounts for it.
2. The acceleration slew rate is no longer directly applied to the motor command. Instead it is applied to the _forward_speed_setpoint_/_forward_speed_setpoint_normalized_. This leads to better controller performance as the system tracks a feasible setpoint …
=> ackermann: update module structure, add acro/position mode and improve guidance

src/modules/navigator/mission_params.c
Param description outdated since https://github.com/PX4/PX4-Autopilot/pull/23568.
Make clear that it only warns but doesn't have effect on mission validity.
```
Improvement: Mission validity checks: make clear that MIS_DIST_1WP only warns, not invalidates
```
=> Mission validity checks: make clear that MIS_DIST_1WP only warns, not invalidates

src/drivers/uavcannode/Publishers/SafetyButton.hpp
Ardupilot checks for an exact 1s press_count. PX4 checks for 1s or greater. 
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_BoardConfig/AP_BoardConfig.cpp#L499
=> cannode: safety_button: fix compatibility with Ardupilot

Tools/ci/generate_board_targets_json.py
This PR solves actually 2 Problems:
1. There is a bug in the generate_board_targets that drops a few targets when grouping them
2. If someone want to clone and reuse the code, he might not want to build all available targets, only the ones specific for the boards he wants to maintain. Instead of writting his own CI he should be able to reuse most of the CI script and adapt it with specifying the boards
- Refactored the grouping code
- Adding an additional board filter input to the scripts. Thus in the CI script one can simply add with the additional filter inputs here https://github.com/PX4/PX4-Autopilot/blob/main/.github/workflows/build_all_targets.yml#L45
```
Bugfix: Make sure all board targets get used in CI for build checks
Feature: Allow the set a board filter for …
```
=> Add filter generate board

src/drivers/power_monitor/ina220/ina220.cpp
ina220 max current param names were incorrect and being ignored
- Use correct param names in driver INA220_CUR_BAT and INA220_CUR_REG
=> ina220 fix max current param name

src/modules/navigator/rtl.cpp, src/modules/navigator/rtl_mission_fast.cpp, src/modules/navigator/rtl_mission_fast.h, src/modules/navigator/rtl_mission_fast_reverse.cpp, src/modules/navigator/rtl_mission_fast_reverse.h
When uploading missions to be flown with RTL_TYPE=2 as a return path, PX4 sometimes claims there is no mission when RTL is triggered:
```
```
Turns out that when these specific RTL handlers are initialized, they don't initialize their mission member variable. Because of that the RTL handlers essentially work with an empty mission where the index is -1, hence the dataman error.
The solution is to load the existing mission after initializing the handlers. I decided to pass the variables via constructor to contain the logic of obtaining the mission from the uORB queue all in rtl.cpp. This way the information flow is more visible in my opinion.
```
switch (new_rtl_mission_type) {
case RtlType::RTL_DIRECT_MISSION_LAND:
_rtl_mission_type_handle = new RtlDirectMissionLand(_navigator); …
```
=> Reload mission for RTL_TYPE 2

src/modules/logger/params.c
Apparently the AES option to `SDLOG_ALGORITHM` parameter is a placeholder for a desirable implementation.
However there is no way to know that unless you know that ....
So this adds the words `(Not implemented)` after the parameter.
@jlaitine Can you confirm the statement and the solution here?
This fell out of https://github.com/PX4/PX4-user_guide/pull/3401
=> SDLOG_ALGORITHM - AES option not implemented

src/systemcmds/param/param.cpp
When using e.g. `param show -q SYS_AUTOSTART` on the NuttX shell I found that it actually doesn't output anything. After looking into the code it prints the same way as other `params show` variants but without any newline.
1. Adding a newline makes it work. So the assumption was that without a newline there's no flush to the output console until the task ends. @dagar confirmed that when we talked today and we tried to add `fflush(stdout);` instead of a newline which also works. But adding the newline should be ok since the standard says trailing newlines get stripped from shell substitutions so we stick with the newline.
2. While at it @dagar suggested removing the legacy `PARAM_PRINT` defines.
```
Fix output of param show -q XXX on NuttX shell
```
I tested on `fmu-v5x` and the parameters …
=> Fix output of param show -q XXX on NuttX shell

src/modules/simulation/simulator_mavlink/CMakeLists.txt
When configuring a custom MAVLink dialect in https://github.com/PX4/PX4-Autopilot/blob/0c451552c7c85bcc2dfe186e1659dd5ea1728a61/boards/px4/sitl/default.px4board#L37 I found that `simulator_mavlink` fails building because of some unknown definitions even if I don't use any custom message from that custom dialect in there.
Include the right header files from the configured dialect to have the proper dialect hierarchy is in use outside of the default configuration. This is consistent with the main MAVLink module, see https://github.com/PX4/PX4-Autopilot/blob/0c451552c7c85bcc2dfe186e1659dd5ea1728a61/src/modules/mavlink/CMakeLists.txt#L152-L153
```
Bugfix: Use custom MAVLink dialect also in simulator_mavlink
```
I tested this change first with a custom dialect that failed building before and …
=> Bugfix: Use custom MAVLink dialect also in simulator_mavlink

src/modules/mavlink/mavlink_ftp.cpp
When trying to list an empty directory, I found that the mavlink ftp implementation does not return EOF.
`payload->offset == 0` should be checked as well for EOF.
This also changes the behavior to return `kErrFailErrno` when retrieving a dir entry fails, instead of failing silently (while removing duplicated `payload->size` and `closedir` logic).
```
Bugfix mavlink ftp not returning EOF on empty directory list.
```
=> fix(ftp): List empty directory

test/mavsdk_tests/autopilot_tester.cpp
CI is often failing here, namely the VTOL altitude flight mode test
=> tests: increase timeout for armable check

boards/mro/ctrl-zero-classic/nuttx-config/include/board.h, boards/mro/ctrl-zero-h7-oem/nuttx-config/include/board.h, boards/mro/ctrl-zero-h7/nuttx-config/include/board.h, boards/mro/pixracerpro/nuttx-config/include/board.h
This is a backport for mRo boards #23524 from main
=> [BACKPORT]  mRo boards: Fix for USART clock selection (#23524)

src/modules/mavlink/mavlink_receiver.cpp
These two commits should prevent some of the warnings regarding acks lost that we sometimes see:
```
[mavlink] vehicle_command_ack lost, generation 10 -> 15
```
See commits for more detail.
=> mavlink: command ack fixes

.github/workflows/build_all_targets.yml
This change will allow the build all variants ci workflow to continue building other targets when a failure is detected, this is good so you can determine which target failed building instead of having to guess by looking into each one. This change is harmless and can be merged now.
=> ci: disable fail fast for build targets job

src/drivers/gnss/septentrio/septentrio.cpp, src/drivers/gnss/septentrio/septentrio.h
When the Septentrio GPS receiver does not receive time information it sets TOW and WNc to some default value. The current implementation does use those default values which will cause an unexpected time jump
In the `RxState` field of `ReceiverStatus` there are two bits (`WNSET` and `TOWSET`) which indicate the synchronization status of the receiver time. Those are checked before using the values of TOW and WNc
```
Bugfix Avoid Septentrio setting wrong time in case of not receiving data
```
- Tested on the bench with a Septentrio mosaic-go
=> Avoid Septentrio setting wrong time

src/modules/uxrce_dds_client/uxrce_dds_client.cpp, src/modules/uxrce_dds_client/uxrce_dds_client.h
When the uxrce_dds_client is not able to connect it cleans up the current session and retries the connection after a certain time. This works well in most cases, but in certain situations the connection fails even before a session is created. This will cause a nullptr access when trying to clean a session that is not yet created.
Only clean the session if it has been created.
```
Bugfix uxrce_dds_client - Fix nullptr access in certain cleanup situations
```
- Has been tested on the bench
=> uxrce_dds_client - Fix nullptr access in certain cleanup situations

ROMFS/px4fmu_common/init.d-posix/airframes/4009_gz_r1_rover, ROMFS/px4fmu_common/init.d-posix/airframes/4011_gz_lawnmower, ROMFS/px4fmu_common/init.d/airframes/50001_aion_robotics_r1_rover, msg/RoverDifferentialSetpoint.msg, msg/RoverDifferentialStatus.msg, src/modules/rover_differential/RoverDifferential.cpp, src/modules/rover_differential/RoverDifferential.hpp, src/modules/rover_differential/RoverDifferentialControl/RoverDifferentialControl.cpp, src/modules/rover_differential/RoverDifferentialControl/RoverDifferentialControl.hpp, src/modules/rover_differential/RoverDifferentialGuidance/RoverDifferentialGuidance.cpp, src/modules/rover_differential/RoverDifferentialGuidance/RoverDifferentialGuidance.hpp, src/modules/rover_differential/module.yaml
The yaw, yaw rate and speed setpoint that the differential module attempts to track are currently mostly step inputs.
This means there are often large errors between the setpoint and measured value leading to very aggresive behaviour and overshoots. It also ramps up any integrator in the control structure, because these setpoint trajectories are infeasible since they don't account for physical limitations of the system.
This PR additional deprectes the `RD_MAN_YAW_SCALE` parameter and updates the default parameter values for the `50001_aion_robotics_r1_rover` with newly added/removed parameters.
By adding slew rates to the setpoints that have to be tracked by the control system the trajectory can be smoothed and made feasible. Setting these slew rates to the physical limitations of the …
=> differential: add slew rates for speed, yaw and yaw rate setpoints

src/drivers/imu/bosch/bmi088/BMI088_Accelerometer.hpp, src/drivers/imu/bosch/bmi088/BMI088_Gyroscope.hpp, src/drivers/imu/bosch/bmi088/Bosch_BMI088_Accelerometer_Registers.hpp, src/drivers/imu/bosch/bmi088/Bosch_BMI088_Gyroscope_Registers.hpp, src/drivers/imu/bosch/bmi088/Kconfig
The BMI088 sensor has 4 interrupt pins. PIN 1 & 2 can be used for accelerometer interrupts and PIN 3 & 4 for gyroscope interrupts. Currently the driver only allows to use PIN 1 for accelerometer interrupts and PIN 3 for gyroscope interrupts.
The change adds a KConfig based selection of which pin to use for accelerometer interrupts and which pin to use for gyroscope interrupts (or don't use any pin at all)
```
Feature Added interrupt pin selection to BMI088
```
- Tested on the bench with a Skynode v5x
=> Added interrupt pin selection to BMI088

platforms/common/pab_manifest.c
This adds the baseboard ID for the Skynode S, so that the ID is reserved and not reused for other boards.
Tested on Skynode v6x to not interfere with other configs.
=> manifest: Add Skynode S baseboard

src/drivers/magnetometer/memsic/mmc5983ma/CMakeLists.txt, src/drivers/magnetometer/memsic/mmc5983ma/mmc5983ma.h, src/drivers/magnetometer/memsic/mmc5983ma/mmc5983ma_main.cpp, src/drivers/magnetometer/memsic/mmc5983ma/mmc5983ma_spi.cpp
There is no support to use MMC5983MA driver via SPI.
- Add SPI support for MMC5983MA driver.
```
Feature/Bugfix: Add SPI support for MMC5983MA driver.
```
Not applicable.
- Unit/integration test: Tested in real hardware ([Navigator](https://bluerobotics.com/store/comm-control-power/control/navigator/))
[MMC5983MA Datasheet](https://www.memsic.com/Public/Uploads/uploadfile/files/20220119/MMC5983MADatasheetRevA.pdf)
=> drivers: magnetometer: mmc5983ma: Add SPI support

src/modules/commander/Commander.cpp, src/modules/commander/HomePosition.cpp, src/modules/commander/gyro_calibration.cpp, src/modules/commander/mag_calibration.cpp, src/modules/mc_rate_control/MulticopterRateControl.cpp
When working on https://github.com/PX4/PX4-Autopilot/compare/main...pid-class I found some parts were unnecessarily cumbersome to read partly because of wrong naming and partly because of automatic type deduction for sometimes even just an integer. I would use that only for the convenient for loops and types that really clutter everything without improving readability.
- Change the multicopter torque setpoint's name from `att_control` to `torque_setpoint`
- Replace `auto` in Commander with the actual type in places that don't fit the above criteria.
```
Small refactor automatic type dedution and naming
```
It compiles, the refactor should only be able to cause a compilation error.
=> Refactor: reduce use of automatic type deduction for readability, torque setpoint naming

src/modules/replay/Replay.cpp, src/modules/replay/Replay.hpp
A couple of logs I received didn't start with the expected message and made the EKF2 replay immediately fail:
```
INFO  [replay] Replay in progress...
WARN  [replay] Topic /data-logger/internal/statistics not found internally. Will ignore it
INFO  [replay] Replay done (published 0 msgs, 0.000 s)
```
Continue to search for the first valid topic
```
-
```
=> Fix EKF2 replay on log with additional topics

.github/workflows/compile_ubuntu.yml, CMakeLists.txt, Tools/setup/ubuntu.sh
Tests the setup script for ubuntu under Ubuntu 22.04 by running a few checks defined in `make quick_checks`
* missing and updated dependencies
* fixes python support
* updates simulation dependencies
* removes jmavsim deps
* installs gazebo harmonic by default
* setup: install zeromq for ubuntu 24.04
* cleans up ubuntu script
=> ci: add test for Ubuntu 22.04

ROMFS/px4fmu_common/init.d-posix/airframes/4013_gz_x500_lidar_2d, ROMFS/px4fmu_common/init.d-posix/airframes/4016_gz_x500_lidar_down, ROMFS/px4fmu_common/init.d-posix/airframes/4017_gz_x500_lidar_front, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt, src/modules/simulation/gz_bridge/GZBridge.cpp, src/modules/simulation/gz_bridge/GZBridge.hpp
Partly Tracked in https://github.com/PX4/PX4-Autopilot/issues/23602
To be merged only when following PR is merged
**other relevant PR's**
This PR Adds two X500 models, one with a front facing rangefinder for collision prevention, and one down facing lidar for normal rangefinder use case testing.
I also renamed the x500_lidar to x500_lidar_2d, to better differentiate the three
**New Models:**
`x500_lidar_front`
`x500_lidar_front`
**Changes:**
`x500_lidar `--> `x500_lidar_2d`
```
Feature: Added front and downfacing MPC Models for SITL Testing
Documentation: read docs.px4.io/main/en/sim_gazebo_gz/vehicles.html
```
=> SIM: MPC: add two x500 lidar airframes

src/modules/sensors/sensor_params_flow.c, src/modules/sensors/vehicle_optical_flow/VehicleOpticalFlow.cpp, src/modules/sensors/vehicle_optical_flow/VehicleOpticalFlow.hpp
Earlier this year we were investigating position oscillations in flow-only operations and came up with a couple of improvements (e.g.: [terrain state](https://github.com/PX4/PX4-Autopilot/pull/23263)). This made the situation better but I've seen the issue resurrecting recently.
This was with a FW version containing the new terrain state. The plot below shows a flight with optical flow fused but without distance sensor (and without GNSS). The flight was perfectly fine (no oscillations) and we can see that the `dist_bottom` estimate is lower than the measurement from the distance sensor. Calculating the ratio of those two values gives us a guess about the optical flow scale factor (between 0.85 and 0.9 in our case). Note that the GNSS altitude also shows that the distance sensor is more …
=> Optical flow: add scale factor parameter

src/modules/sensors/vehicle_imu/VehicleIMU.cpp
A change of SENS_IMU_CLPNOTI required a reboot. I would expect it to have effect immediately (there is no @reboot required in the meta data).
Set _notify_clipping on parameter update and not in constructor.
```
Bugfix VehicleIMU: param change of SENS_IMU_CLPNOTI should have effect without reboot
=> VehicleIMU: param change of SENS_IMU_CLPNOTI should have effect without reboot

src/drivers/magnetometer/akm/ak09916/AK09916.cpp, src/drivers/magnetometer/akm/ak09916/AK09916.hpp, src/drivers/magnetometer/akm/ak09916/AKM_AK09916_registers.hpp
The only difference between the ak09915 and ak09916 is the communication method
There is no support to AK09915 
- Add AK09915 support
- Refactor the code to support AK09915, AK09916, AK09918
```
Feature/Bugfix: Add support to ak09915
```
Not add support to it `¯\_(ツ)_/¯`
- Unit/integration test: Tested in real hardware ([Navigator](https://bluerobotics.com/store/comm-control-power/control/navigator/))
[AK09915 Datasheet](https://bluerobotics.com/wp-content/uploads/2022/05/AK09915-DATASHEET.pdf)
[AK09916 Datasheet](https://www.y-ic.es/datasheet/78/SMDSW.020-2OZ.pdf)
=> drivers/magnetometer/ak09916: Add support to AK09915

src/lib/conversion/rotation.cpp, src/lib/conversion/rotation.h, src/lib/world_magnetic_model/geo_mag_declination.cpp
Flash usage is always high, we compile large parts of PX4 with `-O3` optimization level, which inlines functions aggressively. Often these functions can be un-inlined without changing CPU usage.
@alexcekay "un-inlined" some functions that appear safe. The changes and FLASH save is as follows:
**Original:**
```
Memory region         Used Size  Region Size  %age Used
FLASH_ITCM:           0 B      2016 KB      0.00%
FLASH_AXIM:     1956312 B      2016 KB     94.76%
ITCM_RAM:           0 B        16 KB      0.00%
DTCM_RAM:           0 B       128 KB      0.00%
SRAM1:       97988 B       368 KB     26.00%
SRAM2:           0 B        16 KB      0.00%
```
**With the un-inline**
```
Memory region         Used Size  Region Size  %age Used
FLASH_ITCM:           0 B      2016 KB      0.00% …
```
=> Non-Inline function to save 4kB Flash

.github/workflows/flash_analysis.yml
Increase awareness of the impact of a code change on FLASH size. Allow developers to see exactly how much and where their change will increase FLASH usage.
- In case of a PR:
- Compile the base revision
- Compile the current revision of the branch
- Diff the flash usage using bloaty
- In case of a commit on main:
- Compile the previous main revision
- Compile the current main revision
- Diff the flash usage using bloaty 
This is an initial working version that includes the following two boards:
- px4_fmu-v5x
- px4_fmu-v6x
If we want, we can easily add more boards in the future.
This version compiles 2 times for each board (1 compile before / 1 compile after) to create the diff. With two boards this results in 4 compiles, which is fast and only creates a small overhead. If we add many more …
=> Added GH Action to show FLASH diff using bloaty

src/lib/component_information/generate_component_general.py
Doing a build, I saw the following syntax warning:
```
PX4-Autopilot/src/lib/component_information/generate_component_general.py:23: SyntaxWarning: invalid escape sequence '\s'
version_search = re.search('PX4_GIT_TAG_OR_BRANCH_NAME\s+"(.+)"', line)
```
- This fixes the issue by making it a raw literal string so the `\` isn't treated as an escape character. 
- Building with this change removes the SyntaxWarning.
=> Fix generate component regex escape sequence

boards/hkust/nxt-dual/src/board_config.h
Fix HKUST_NXT dual version ADC channel mismatch with the hardware design.
Change ADC_BATTERY_CURRENT_CHANNEL from 5 to 8
=> hkust_nxt-dual: fix ADC_BATTERY_CURRENT channel mismatch

CMakeLists.txt
Unit test filtering doesn't work anymore on main since https://github.com/PX4/PX4-Autopilot/pull/23869/files#r1841024972
Seems that apparently the parameters cannot be assembled in a CMake string variable like that so I'll just explicitly add the `-r` argument in the separate already existing `TESTFILTERARG` variable.
```
Fix: Unit test filter
```
Works again like expected on 22.04. @mrpollo please check if it makes the error you described in https://github.com/PX4/PX4-Autopilot/pull/23869/files#r1841089807 reappear. I couldn't guess where you had it but it should still be fixed.
=> gtest cmake: fix unit test filter

platforms/nuttx/cmake/upload.cmake
**Problem**
I was trying to flash the ARK FPV 
```
make ark_fpv_default upload
```
and it was getting stuck not finding the device while it was in the bootloader.
**Solution**
The upload.cmake is fixed to use the `${vendor_str}_BL` as a serial port option.
=> make upload: fix bootloader device path

src/modules/commander/HealthAndArmingChecks/checks/batteryCheck.cpp
When having battery checks fail in a bench test I found that enabling the circuit breaker allowed following arm attempts but the vehicle would immediately failsafe and disarm again without reporting any reason.
Failing checks caused failsafe flags to stay true when enabling the circuit breaker but not rebooting.
This should have been part of https://github.com/PX4/PX4-Autopilot/pull/23431/files#diff-1f54f0a80d365c804b5828d657946655fd70a397a3adf52102015ea31fea7a7bR75-R79
Resetting the failsafe flags state when the circuit breaker is set resolves this issue.
```
Fix: Power circuit breaker immediately passes battery checks without reboot
```
We found this was the actual issue by running `listener failsafe_flags` and seeing `battery_unhealthy` still being true after just having set the …
=> batteryCheck: fix enabling circuit breaker still causing battery failsafes

src/modules/sensors/vehicle_air_data/VehicleAirData.cpp
When the barometer is not getting calibrated (IMO: not really common to do) one cannot disable it through the parameters. By setting the calibration parameter in the very beginning one can always disable or switch to a different barometer manually.
=> always allow disabling uncalibrated baro

src/modules/mavlink/mavlink_main.cpp
@dagar sent me this:
Turns out I missed the stream configuration of the `COLLISION` message in https://github.com/PX4/PX4-Autopilot/pull/23933 so I remove them now 🙈 
Should have been part of b5d18c613181f0935890aef91cbc1da4d06e00c3
Was this showing in pr CI? Then we should see the warnings vanish on this one.
=> mavlink: remove reference to COLLISION message I had missed

src/drivers/barometer/bmp280/BMP280.cpp
It looks like the BMP280 was heavily filtered, leading to a step response of around 3 seconds. Comparing it to baro logs of BMP388 and MS5611, it looks very slow.
I therefore suggest to disable the on device IIR filter which makes the log data look more like the other baros.
=> bmp280: disable device filter

.github/workflows/dev_container.yml
When this workflow triggered by a tag push event, then it tags the image in multiple ways eg:
"image.name": "ghcr.io/px4/px4-dev:v1.16.0-alpha1,ghcr.io/px4/px4-dev:latest"
Having multiple names messes up the execution of the next step in the chain since we depend on its name to complete the testing.
Error https://github.com/PX4/PX4-Autopilot/actions/runs/11943677314/job/33293165630#step:10:3
=> ci: fix container image name when multiple given

.github/workflows/dev_container.yml
for some reason docker hub api is failing today, we will bring this back to docker hub soon.
=> ci: disable docker hub access

platforms/common/spi.cpp
Depending on defines px4_spi_buses can be NULL but often it's not and in those cases the compiler correctly warns about it.
Reported in https://github.com/PX4/PX4-Autopilot/pull/23869#issuecomment-2474826808 and https://github.com/PX4/PX4-Autopilot/issues/23963#issuecomment-2484159058
Suppress the warning.
Locally built fmu-v4 on Ubuntu 24.04 with the packaged GCC 13.2.1
=> spi: Suppress null pointer warning

src/modules/commander/Commander.cpp
I got the report that users reference the system "Remote ID" and "OpenDroneID" might already be too technical, less understandable to some.
I suggest rewording.
```
UX: Reword user-facing messages to "Remote ID" instead of "OpenDroneID"
```
I haven't particularly tested this. I'm certain it works since it's merely a user-facing string change that's shorter than before.
=> UX: Reword user-facing messages to "Remote ID" instead of "OpenDroneID"

src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/commander/HealthAndArmingChecks/Common.cpp, src/modules/commander/HealthAndArmingChecks/Common.hpp, src/modules/commander/HealthAndArmingChecks/HealthAndArmingChecks.cpp, src/modules/commander/HealthAndArmingChecks/HealthAndArmingChecks.hpp, src/modules/commander/HealthAndArmingChecks/HealthAndArmingChecksTest.cpp, src/modules/commander/failsafe/framework.cpp, src/modules/commander/failsafe/framework.h
As the failsafe message can reference the health report, the health report needs to be sent out first. This is generally the case, except there is a rate limiter set to 2 seconds. So if the report changes quickly, it is sent out delayed (potentially after the failsafe report).
=> commander: ensure health report is always sent out before failsafe notificaation

src/systemcmds/topic_listener/listener_main.cpp
I suggest to clear the screen when using the listener with -n. This way the updates don't just scroll by which isn't legible but instead stay in place and update, similar to the top command.
=> listener: clear screen on multiple output

src/lib/mixer_module/mixer_module.hpp
Came across these two function definitions that don't seem to be used anywhere anymore.
=> mixer module: remove unused functions

.github/workflows/dev_container.yml
This updates the docker image tag for the px4-dev container, from `px4-dev:main` to `px4-dev:main-{{YYYYMMDD}}` so we can lock down per date instead of having a constantly updating container
=> ci: container tag pattern updates

.github/workflows/build_all_targets.yml
Fixes artifact upload to tag/release.
The "build all boards" workflow can upload artifacts to GitHub releases (tags), but it fails to upload the artifacts because of a path mismatch. See the error here: https://github.com/PX4/PX4-Autopilot/actions/runs/11943677312/job/33293603268#step:4:18
=> ci: build all upload to releases

.github/workflows/dev_container.yml
Publishes the px4-dev container to docker hub, and updates tags
Docker Hub
https://hub.docker.com/repository/docker/px4io/px4-dev/general
GitHub Registry
https://github.com/PX4/PX4-Autopilot/pkgs/container/px4-dev
Updated Tags:
- ghcr.io/px4/px4-dev:pr-24027
- ghcr.io/px4/px4-dev:sha-b1b98d1
- px4io/px4-dev:pr-24027
- px4io/px4-dev:sha-b1b98d1
=> ci: publish px4-dev container to docker hub

ROMFS/px4fmu_common/init.d-posix/airframes/10041_sihsim_airplane, src/modules/simulation/simulator_sih/sih.cpp
SIH plane (`make px4_sitl sihsim_airplane`) immediately crashes after arming due to 2 issues:
1. actuator mapping was reversed for roll and pitch (broken when transitioning from mixer files to control allocation module)
2. airspeed measurement reconstruction was rotated by 90 degrees to make the tailsitter sim work... (https://github.com/PX4/PX4-Autopilot/pull/23673)
Additionally, it was difficult to make the plane takeoff as its attitude is locked while on ground contact. It should be allowed to at least pitch, so I removed this constraint.
SIH tests (takeoff in auto and position modes)
=> SIH: fix airplane sim

.github/workflows/dev_container.yml
Docker hub is rate limiting our API access, as a result tests are failing for no apparent reason. This change will decrease the API calls by at least 80%
We have applied for an Open Source account with greater API limits, I will come back to this and update as necessary when and if they grant us access to their program.
This PR also introduces the PX4 git tags, as a tagging mechanism for images, eg:
```
px4-dev:v1.16.0-alpha2-27-g8e6e401972
```
=> ci: disable publishing PR images to docker hub

src/modules/uxrce_dds_client/CMakeLists.txt
@slgrobotics this is why the configure was failing. The submodule cmake requirements are out of our control so all we can do is respect them. 
https://github.com/PX4/Micro-XRCE-DDS-Client/blob/711aef423edd1820347b866d1e4164832df35d04/CMakeLists.txt#L18
=> uxrce_dds_client: update cmake requirements to match Micro-XRCE-DDS-Client submodule

boards/emlid/navio2/arm64.px4board
Raspberry Pi 4,5 support 64-bit OS (Ubuntu) and _"aarch64-linux-gnu"_ toolchain.
This PR adds a single file that optionally allows cross-builds for ARM64 target architecture.
- Using a Ubuntu 24.04 Intel or similar desktop machine for builds
- This PR adds file _boards/emlid/navio2/arm64.px4board_
- Install ARM64 toolchain: ```sudo apt install g++-aarch64-linux-gnu```
The 32-bit toolchain can be installed by ```sudo apt install g++-arm-linux-gnueabihf```
Now both 32-bit and 64-bit builds are available:
```
make emlid_navio2 upload
make emlid_navio2_arm64 upload
```
=> boards: emlid_navio - support 64-bit OS on Raspberry Pi 4,5

src/modules/navigator/mission_block.cpp, src/modules/navigator/mission_block.h, src/modules/navigator/mission_params.c, src/modules/navigator/navigator.h, src/modules/navigator/navigator_main.cpp
In a mission with a move gimbal item followed by a take picture item, the picture is taken while the gimbal is still moving
After a `CMD_DO_GIMBAL_MANAGER_PITCHYAW` wait for a timeout before resuming the mission to be sure that the gimbal reached the desired orientation. 
Since we already have `CMD_DO_WINCH` and `NAV_CMD_DO_GRIPPER` following a similar pattern, we defined a common timeout parameter (`MIS_COMMAND_TOUT`) for these 3 mission items. Furthermore, we unified the logic handling such mission items simplifying the navigator code.
```
Removed parameter: MIS_PD_TO (substituted by MIS_COMMAND_TOUT)
New parameter: MIS_COMMAND_TOUT
```
- SITL testing
=> Navigator: add optional delay after gimbal mission items

ROMFS/px4fmu_common/init.d-posix/airframes/4009_gz_r1_rover, ROMFS/px4fmu_common/init.d-posix/airframes/4011_gz_lawnmower, ROMFS/px4fmu_common/init.d/airframes/50001_aion_robotics_r1_rover, src/modules/rover_differential/RoverDifferentialControl/RoverDifferentialControl.cpp, src/modules/rover_differential/RoverDifferentialGuidance/RoverDifferentialGuidance.cpp, src/modules/rover_differential/RoverDifferentialGuidance/RoverDifferentialGuidance.hpp, src/modules/rover_differential/module.yaml
This PR adds these 2 updates to the differential rover module:
1. The controller prioritizes yaw rate over forward speed. A high yaw rate setpoint can therefor make the forward speed setpoint infeasible due to actuator limitations. This leads the integrator of the speed controller to build up. This problem is fixed in this PR by adjusting the speed setpoint based on the amount of control effort that is “occupied” by the yaw rate setpoint.
2. Adds a tunable slow down effect in mission mode. As the rover approaches a waypoint it will slow down with the following logic: If the angle between the prev-curr-wp and curr-next-wp lines is bigger than  `RD_TRANS_DRV_TRN` the rover will come to a full stop at the waypoint and then turn on the spot (this is not new). If this angle is lower then it …
=> differential: speed setpoint feasibility and slow down effect in mission mode

ROMFS/px4fmu_common/init.d-posix/airframes/4015_gz_r1_rover_mecanum, msg/RoverMecanumSetpoint.msg, msg/RoverMecanumStatus.msg, src/modules/rover_mecanum/RoverMecanum.cpp, src/modules/rover_mecanum/RoverMecanum.hpp, src/modules/rover_mecanum/RoverMecanumControl/RoverMecanumControl.cpp, src/modules/rover_mecanum/RoverMecanumControl/RoverMecanumControl.hpp, src/modules/rover_mecanum/RoverMecanumGuidance/RoverMecanumGuidance.cpp, src/modules/rover_mecanum/RoverMecanumGuidance/RoverMecanumGuidance.hpp, src/modules/rover_mecanum/module.yaml
This PR adds the following new features to the mecanum module:
1. Deprecate `RM_MISS_SPD_DEF`: This brings the module in line with the other 2 rover modules. The default mission speed is now simply the maximum speed `RM_MAX_SPEED` or specified with a speed waypoint.
2. Deprecate `RM_MAN_YAW_SCALE`: This is also to bring the module in line with the other rover modules. This parameter is removed and its functionality is instead provided by `RM_MAX_YAW_RATE` and `RM_MAX_THR_YAW_R` (which already existed).
3. Add slew rates for the yaw, yaw rate and speed setpoints. Same idea/implementation as with the differential module (https://github.com/PX4/PX4-Autopilot/pull/23812). Adds 2 new parameters `RM_MAX_DECEL` and `RM_MAX_YAW_ACCEL`.
4. Fix inverse kinematics: The yaw rate prioritization was …
=> mecanum: new features

Tools/px4airframes/markdownout.py
This makes very minor change to the generated output for the airframe markdown, replacing a section surrounded by `<p>` tags with a single preceding `<br>`.
Both are valid, but for some reason when the former round-trips through crowdin, we end up with an extra opening `p` element, which causes vitepress to crash.
The output from this works (tested).
=> airframes markdownout.py - br rather than p for generated code

src/lib/motion_planning/PositionSmoothing.cpp, src/lib/motion_planning/PositionSmoothingTest.cpp, src/lib/motion_planning/TrajectoryConstraints.hpp
When conducting a survey, the drone tended to slow down and accelerate again when covering large altitude changes, with terrain following enabled. 
Example Survey:
**Without Fix:**
This is best seen when looking at the velocity change in x and z direction in the plot above.
To solve this issue i added a turning radius for the vertical component, whereby I simplify the problem so that we consider the 2D case where the vertical component of the incoming vector is the norm of the xy component, and the z component. 
I also removed the requirement for the XY turning radius that the altitude between the current and next waypoint have to be the same. 
**With Fix:**
As we can see in the Plot above, the velocity changes close to the waypoints are gone. 
```
Bugfix: removed …
```
=> MPC: Survey: Added a turning radius to altitude changes in FlightModeAuto

ROMFS/px4fmu_common/init.d-posix/airframes/4018_gz_quadtailsitter, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt, src/modules/simulation/gz_bridge/GZBridge.cpp, src/modules/simulation/gz_bridge/GZBridge.hpp
Add the quadtailsitter and airspeed sensor to gz simulation
Fixes #23602
Allowing airspeed sensor in gz bridge, adding a config file for the quadtailsitter.
As Gazebo garden reaches EOL by Nov 2024 this solution only takes into account sensor msgs from gazebo harmonic (LTS)   
It was tested on Ubuntu 22.04 using QGroundControl and gazebo Harmonic.
related PR with results:
=> Add gz model for quadtailsitter

src/modules/ekf2/EKF/aid_sources/aux_global_position/aux_global_position.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/test/test_EKF_flow.cpp
mismatch between function declaration (standard deviation) and implementation (variance)
=> EKF2: reset global position using variance

ROMFS/px4fmu_common/init.d/rc.fw_defaults, src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.cpp, src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.hpp, src/modules/commander/commander_params.c
When answering a support question I found that currently `COM_POS_FS_DELAY` configures the timeout for the internal `vehicle_local_position` uORB message which is to my knowledge not expected to time out as long as the estimator is running since it gets published regularly also when the position (or altitude) is flagged invalid.
A user-configurable timeout for the internal `vehicle_local_position` seems confusing in my eyes. It's a different timeout for fixed-wing and multirotor which might have made sense earlier but not really anymore since the topic is constantly published by the estimator and not expected to time out on either vehicle type and the parameter description is also misleading because it's outdated.
I remove the parameter and hardcode the timeout for the …
=> Commander: remove `COM_POS_FS_DELAY`

.github/workflows/checks.yml, .github/workflows/clang-tidy.yml, .github/workflows/compile_macos.yml, .github/workflows/ekf_functional_change_indicator.yml, .github/workflows/ekf_update_change_indicator.yml, .github/workflows/failsafe_sim.yml, .github/workflows/mavros_mission_tests.yml, .github/workflows/mavros_offboard_tests.yml, .github/workflows/nuttx_env_config.yml, .github/workflows/python_checks.yml
Problem
GitHub deprecated older versions of the cache, and checkout actions which are now using an updated version of node which isnt' available on the older PX4 container images
Solution
Updated cache, and checkout deps to latest where possible, and switched to the newer [px4-dev](https://github.com/PX4/PX4-Autopilot/pkgs/container/px4-dev/310191526?tag=1.16.0-alpha2) container image with the updated base operating system environment
=> ci: update actions and images

src/lib/parameters/flashparams/flashfs32.c
**Problem**
When updating from Ardupilot to PX4 on a board that uses flash based params PX4 will fail to load params. It will continue to fail until the MCU is mass erased. This is because the params sector contains the Ardupilot param format. 
**Solution**
Erase parameter sector if `parameters_token` is not found. This essentially tells us that the sector is not in the proper format and therefore we assume it is generally "corrupted". This is what Ardupilot does and doesn't have this issue.
**Testing**
Tested on an ARK FPV.
=> params: flash: erase corrupt sector

Tools/decrypt_ulog.py, src/modules/logger/log_writer_file.cpp, src/modules/logger/logger.cpp
When downloading the encrypted log files with QGC, there is no robust way to know which symmetric key files and encrypted ulog data files are related ones. Only way currently is to look at consecutive log files and assume that the smaller file (around 300bytes) is the key and the related ulog file is the next immediate file after that. This makes it a bit difficult to automate the log gathering.
To improve the situation, the encrypted/wrapped symmetric key data could be combine with the encrypted ulog data into one single file. Then the key is always kept in the same place with corresponding encrypted ulog data, so it cannot be mixed with other keys.
```
Feature: Ulog encryption changed to combine the wrapped symmetric key and ulog data into one file (.ulge) …
```
=> Logger:  combined encrypted ulog&key file

ROMFS/px4fmu_common/init.d-posix/airframes/1031_gazebo-classic_plane_cam.post, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt
The images taken during a survey was not being saved in the designated directory.
This is due to the mavlink stream at the camera port (14530) not being streamed for the `plane_cam` model.
Fixes https://github.com/PX4/PX4-Autopilot/issues/24073, https://github.com/PX4/PX4-SITL_gazebo-classic/issues/1059
Add a mavlink stream to the simulated camera
Tested in SITL
```
make px4_sitl gazebo-classic_plane_cam
```
=> Add mavlink stream for plan_cam model

src/modules/navigator/mission_base.cpp
When flying patterns, photos are sometimes taken while the gimbal is pitching up or down.
To address this, we orient the gimbal before reaching the mission waypoint, allowing more time to complete the action. Additionally, we verify if the vehicle is climbing to avoid orienting the gimbal while on the ground.
Tested in SITL.
=> Mission: Replay gimbal cached items before reaching mission waypoint

Tools/ci/generate_board_targets_json.py
The following PR: https://github.com/PX4/PX4-Autopilot/pull/24072 added a new target called `flash-analysis.px4board`. This naming convention does not cause any problems with KConfig or Make, it does however break _generate_board_targets_json.py_ as it does not expect such a naming convention.
Adapted the contained regex to also consider targets that contain a `-`
=> Fix board target generation 

Tools/setup/ubuntu.sh
- gz garden reached EOL nov 2024, so it should no longer be supported: https://gazebosim.org/docs/latest/releases/
- gz-harmonic should be supported on Ubuntu Jammy https://gazebosim.org/docs/harmonic/getstarted/
- and finally Linux Mint version 21.3 is built on top of Ubuntu Jammy https://linuxmint.com/download_all.php 
- not yet tested
=> Draft: Remove gz-garden from Ubuntu Installation as it reached EOL

src/modules/ekf2/EKF/aid_sources/aux_global_position/aux_global_position.cpp, src/modules/ekf2/EKF/aid_sources/aux_global_position/aux_global_position.hpp
AGP was not waiting for the timeout to perform a reset when a sample wasn't passing the test ratio as the `time_last_fused` is always reset to 0 as `aid_src` is not a member variable but re-instantiated at every loop.
Make the aux global position "aid_src" structure a member variable to remember when the last fusion occurred.
=> ekf-agp: fix timeout

src/drivers/gps/gps.cpp
Backport of #24077.
Needs testing.
=> [BACKPORT v1.15] gps: heading fixes for NMEA/Unicore

src/modules/simulation/gz_bridge/CMakeLists.txt
removes garden from cmake, since build will fail due to airspeed message
=> sim: gz: remove Garden from cmake

src/lib/mixer_module/functions/FunctionMotors.hpp
Fixes https://github.com/PX4/PX4-Autopilot/issues/24083.
Leave NAN untouched, even if THR_MOD_FAC is set.
For release notes: Mixer:  leave NAN control values at NAN with non-zero THR_MDL_FAC to fix VTOL motors not turning off correctly.
```
Bugfix: 
```
Should the whole THR_MOD_FAC logic not live in the control allocation? Why is it handled by the mixer?
SITL tested.
=> Mixer: FunctionMotors: leave NAN control values at NAN with non-zero THR_MDL_FAC

src/drivers/distance_sensor/lightware_sf45_serial/lightware_sf45_serial.cpp, src/drivers/distance_sensor/lightware_sf45_serial/lightware_sf45_serial.hpp, src/drivers/distance_sensor/lightware_sf45_serial/lightware_sf45_serial_main.cpp, src/drivers/distance_sensor/lightware_sf45_serial/module.yaml, src/modules/logger/logged_topics.cpp
**Basic Structure**
We updated the internal logic as follows:
- If during a sweep of the sensor, a bin gets skipped, we assume the last measurement to be valid for that bin as well. 
- If multiple measurements have been made in a bin, the lowest one is selected.
- To avoid issues with the message processing structure in CollisionPrevention, the sensor publishes all bins he has measured in the past 0.1s. This is because the sensor is publishing messages at a faster rate than CollisionPrevention is reading them, which might cause lost readings. 
**Other notable changes:**
- greatly improved the Sampling Rate (tested up to 500hz)
- Fixed boot up issues
- Added Timeout functionality to measurements.
- removed the publishing to distance_sensor
**Important note**
During testing we came across …
=> SENS: SF45: Improved Datahandling and fixes

src/modules/fw_pos_control/FixedwingPositionControl.cpp, src/modules/fw_pos_control/FixedwingPositionControl.hpp, src/modules/fw_pos_control/fw_path_navigation_params.c
Previously, the method to control a transition to hover was handling both cases when position was available, and when it was not available.
It's cleaner to have the methods separates for once. Other than that, the method which controls the transition for the case when position is not available, now does heading hold, which is better than just demanded 0 roll, which was done previously.
Control heading during backtransition when local position is not available.
Currently tested in SITL, following up with plots from real tests.
The figure below is from a simulation, where the vehicle approaches the transition point with a 10m/s crosswind (see large difference between heading and track)
The heading of the vehicle is tracked as the initial heading when local position is lost (when the nav …
=> Fixed-wing Position Control: Split up control methods for VTOL backtransition

src/modules/fw_rate_control/FixedwingRateControl.cpp
For fw_rate control, the feedforward term was being computed outside the rate controller.
This is an aesthetic change that modifies the feedforward gain of the fixed-wing rate controller, rather than adding a separate feedforward computation outside the rate library.
IMHO, this makes it a little bit more clear how the feedforward gain is being computed.
(Saves one vector multiplication and one vector addition :P)
```
Feature/Bugfix Dynamically update feedforward gains, in the fw_rate_control instead of computing feedforward inline.
New parameter: None
Documentation: Dynamically update feedforward gains, in the fw_rate_control.
```
=> Dynamically update ff gain for fw rate control

src/modules/commander/accelerometer_calibration.cpp
- accel cal use Accelerometer calibration class to fully respect rotation (both internal and external sensors)
=> commander: accelerometer calibration respect rotation

src/modules/uxrce_dds_client/dds_topics.yaml
The current dds topics yaml file does not include input of distance sensor messages, leaving only obstacle distance.
Obstacle map messages are cumbersome for offboard point-lidar sensors. It would be better to pass in the distance sensor messages instead of trying to configure the obstacle distance array in the offboard code.
For non-point lidars (e.g. radar or rotating lidar) one could feed in the quaternion along with the distance data similar to this [branch](https://github.com/PX4/PX4-Autopilot/commit/b7a8b64a6e219b5c0f30e075a1c246db72bc1f40#diff-0e95f3c35895702b8f78bf4fe6849e1cc8aaf71236c4efa7c964511490210d61R653)
With [increasingly complex lidar sensors ](https://www.mouser.com/new/stmicroelectronics/stmicroelectronics-vl53lp-tof-modules/)whose drivers are too large or compute …
=> Include distance sensor in dds topics

.github/workflows/dev_container.yml
we supported uploading container builds for pull requests so users could download and test, but we are facing issues with the github api, and as a result we are having [CI failures](https://github.com/PX4/PX4-Autopilot/actions/runs/12283238253/job/34276255629#step:13:274)
Given we don't have users taking advantage of this feature, I decided to remove it.
https://github.com/PX4/PX4-Autopilot/pkgs/container/px4-dev
=> container: remove pr container push to registry

src/lib/modes/standard_modes.hpp, src/modules/commander/Commander.cpp, src/modules/mavlink/streams/AVAILABLE_MODES.hpp, src/modules/mavlink/streams/CURRENT_MODE.hpp
See https://mavlink.io/en/messages/development.html#MAV_STANDARD_MODE. The only standard mode that is not set is MAV_STANDARD_MODE_SAFE_RECOVERY, as PX4 uses RTL for that (with configuration parameters).
```
Implement vehicle-type specific MAVLink standard modes.
```
=> standard_modes: add vehicle-type specific standard modes

msg/GimbalDeviceAttitudeStatus.msg, msg/GimbalDeviceInformation.msg, src/modules/gimbal/output_mavlink.cpp, src/modules/gimbal/output_mavlink.h, src/modules/gimbal/output_rc.cpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/streams/GIMBAL_DEVICE_ATTITUDE_STATUS.hpp
When we use a gimbal connected via "RC", so PWM via the Aux channels, we need to set the gimbal_device_id to 1 as per the protocol.
This was missing for GIMBAL_DEVICE_ATTITUDE_STATUS, so I added that, and fixed the name of that variable while at it.
=> gimbal: correctly set gimbal_device_id

src/modules/ekf2/EKF/yaw_estimator/EKFGSF_yaw.cpp, src/modules/ekf2/EKF/yaw_estimator/EKFGSF_yaw.h
This is a pure refactoring, no functional changes expected.
The yaw estimator has its attitude stored as a rotation matrix. This requires to save 5 more floats than using a quaternion per EKF; since there are 5 EKFs per yaw estimator this gives 25 floats per EKF2 instance. Furthermore initializing, integrating and re-normalizing a quaternion is simpler than using a rotation matrix.
Store the attitude as a quaternion.
unit tests
=> Yaw Emergency estimator: store attitude as quaternion instead of DCM

ROMFS/px4fmu_common/init.d-posix/airframes/4019_gz_x500_gimbal, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt, src/modules/gimbal/gimbal.cpp, src/modules/gimbal/gimbal_params.h, src/modules/gimbal/input_mavlink.cpp, src/modules/gimbal/input_mavlink.h, src/modules/gimbal/input_rc.cpp, src/modules/gimbal/output.cpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/streams/GIMBAL_DEVICE_ATTITUDE_STATUS.hpp, src/modules/mavlink/streams/GIMBAL_DEVICE_INFORMATION.hpp, src/modules/simulation/gz_bridge/CMakeLists.txt, src/modules/simulation/gz_bridge/GZBridge.cpp, src/modules/simulation/gz_bridge/GZBridge.hpp, src/modules/simulation/gz_bridge/GZGimbal.cpp, src/modules/simulation/gz_bridge/GZGimbal.hpp
Gimbal device to be controlled in SITL environment when using gazebo simulator (gz-garden). The device can act as a Mavlink gimbal (following Mavlink gimbal protocol v2) or as a non-Mavlink gimbal (responding to gimbal_controls messages) depending on `MNT_MODE_OUT` PX4 parameter.
It supports both angle and angular rate commands, it doesn't support yet the [gimbal device flags](https://mavlink.io/en/messages/common.html#GIMBAL_DEVICE_FLAGS) (WIP).
It is meant to work with the gz_x500_gimbal model (https://github.com/PX4/PX4-gazebo-models/pull/47).
Tested with QGC 
The submodule Tools/simulation/gz is temporarily pointing to https://github.com/StefanoColli/PX4-gazebo-models waiting for 
https://github.com/PX4/PX4-gazebo-models/pull/47 to be merged into main. …
=> GZ: Add gimbal device 

src/modules/simulation/gz_bridge/GZGimbal.cpp
When I tested the gimbal device I notice the angular velocity data wasn't updated in the gimbal device attitude status.
Tested with QGC
The original PR with results and description: 
Below is the result of the gimbal in motion and corresponding angular velocities in the gimbal device attitude status.
[07112024pr-gz-gimbal-sim.webm](https://github.com/user-attachments/assets/e1c4269e-4c7b-4020-a22b-27597983ec47)
=> Adding gimbal rate in gz simulation

ROMFS/px4fmu_common/init.d/rcS, Tools/kconfig/allyesconfig.py, msg/Rpm.msg, platforms/nuttx/src/px4/nxp/imxrt/include/px4_arch/io_timer.h, platforms/nuttx/src/px4/nxp/kinetis/include/px4_arch/io_timer.h, platforms/nuttx/src/px4/nxp/rt106x/include/px4_arch/io_timer.h, platforms/nuttx/src/px4/nxp/s32k1xx/include/px4_arch/io_timer.h, platforms/nuttx/src/px4/nxp/s32k3xx/include/px4_arch/io_timer.h, platforms/nuttx/src/px4/rpi/rpi_common/include/px4_arch/io_timer.h, platforms/nuttx/src/px4/stm/stm32_common/include/px4_arch/io_timer.h, src/drivers/camera_capture/camera_capture.cpp, src/drivers/camera_capture/camera_capture.hpp, src/drivers/camera_trigger/interfaces/src/camera_interface.cpp, src/drivers/pps_capture/PPSCapture.cpp, src/drivers/rpm/pcf8583/PCF8583.cpp, src/drivers/rpm/rpm_simulator/rpm_simulator.cpp, src/drivers/rpm_capture/CMakeLists.txt, src/drivers/rpm_capture/Kconfig, src/drivers/rpm_capture/RPMCapture.cpp, src/drivers/rpm_capture/RPMCapture.hpp, src/drivers/rpm_capture/rpm_capture_params.c, src/lib/mixer_module/output_functions.yaml, src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/streams/RAW_RPM.hpp, src/modules/simulation/simulator_mavlink/SimulatorMavlink.cpp
When wokring on helicopter rpm control I found that RPM sensing is "easily" possible but requires work. @bkueng provided the nice configurable capture part for that effort and I used the output directly in the heli-specific controller. But now I think we should enable generic RPM capturing for use in control, log, UI reporting.
~As a draft, I added the hardcoded logic we used to process the RPM.
Note: This doesn't work well out of the box because it cannot detect a timeout if the interrupt is never called anymore.~
The solution in the meantime has:
- timeout
- outlier rejection
- pule per revolution configuration
Thanks for all the help from @oravla5, @sfuhrer and @bresch behind the scenes.
```
Feature: Easy to use RPM sensing from GPIO pulses
```
This logic was used on a heli to control …
=> RPM sensing from GPIO (PWM pin) pulses

posix-configs/SITL/init/test/cmd_template.in, posix-configs/SITL/init/test/test_mavlink
Mavlink unit-tests started publishing messages to the first available network, causing issues with devices which were hooked up to the same network.
@eyeam3
=> Mavlink: dont broadcast during unit-testing

src/lib/adsb/AdsbConflict.cpp, src/lib/adsb/AdsbConflict.h, src/lib/adsb/AdsbConflictTest.cpp
Some of the unit tests for ADSB failed in our fork of PX4. My best guess is that it has something to do with timing. I don't understand how it is working atm without passing the "current time" to the unit test when the ADSB functionality we're testing is depending on the exact timing of the incoming faked conflicts. 
In unit tests define time of reception of new/removed conflict input.
```
Improvement: ADSB: improve testability and small refactor
```
=> ADSB: improve testability and small refactor

ROMFS/px4fmu_common/init.d-posix/airframes/4011_gz_lawnmower, ROMFS/px4fmu_common/init.d-posix/airframes/4012_gz_rover_ackermann, ROMFS/px4fmu_common/init.d-posix/airframes/4020_gz_tiltrotor, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt, src/modules/simulation/gz_bridge/GZMixingInterfaceServo.cpp, src/modules/simulation/gz_bridge/GZMixingInterfaceServo.hpp, src/modules/simulation/gz_bridge/module.yaml
Moving the tiltrotor from gazebo classic to gz sim as gazebo garden will be depreciated by the end of nov 24
Adding an airframe and fixed the bug in gz-bridge. PX4 sends an output value from 0 to 1000 of the servo and the GZbridge normalized it to be within +-1. The problem was that gazebo needs a servo input of angles in radian which meant the currently servos only works in the range +-1 rad.
Tested with QGC
Before updating GZMixingInterfaceServo.cpp:
After updating GZMixingInterfaceServo.cpp:
=> Adding tiltrotor airframe for gazebo simulation 

src/modules/flight_mode_manager/tasks/Transition/FlightTaskTransition.cpp, src/modules/flight_mode_manager/tasks/Transition/FlightTaskTransition.hpp
Follow-up to https://github.com/PX4/PX4-Autopilot/pull/23731
When looking for flash savings I realized flight task transition now uses 1.5+ kilobytes of flash which is completely useless on flash-constrained boards that do not support VTOLs so I thought about removing the task from flash constrained builds but we don't have a mechanism to enforce that no one will ever build a target with VTOL support but no transition flight task then.
After investigating this I was wondering why the transition task is so big now and cleaned up the logic while going through it.
First commit should be refactor as in:
- the parameters do not update during a transition anymore
- the fixed-wing parameters not being available gets handled slightly different by the `param_get()` function
- parameter variables …
=> Clean up Transition Flighttask

src/modules/mc_pos_control/multicopter_altitude_mode_params.c, src/modules/mc_pos_control/multicopter_position_mode_params.c, src/modules/mc_pos_control/multicopter_stabilized_mode_params.c
When working on https://github.com/PX4/PX4-Autopilot/pull/24041 I found that Kakute F7 runs out of flash so @sfuhrer told me easiest is to save on some parameter description strings. But I think does are not included in flash-contained builds.
Even though there is no effect on that particular build I think cleaning up is worthwhile.
I shortened the texts to contain the essential information but avoid language decorations.
```
Improvement: Make multicopter position control parameter descriptions more concise
```
=> Make multicopter position control parameter descriptions more concise

src/modules/commander/HealthAndArmingChecks/checks/offboardCheck.cpp
When "ra1nyu" brought up https://discuss.px4.io/t/why-does-acceleration-control-in-offboard-mode-need-velocity-estimate/42512 in the developer call we found in the discussion that offboard pure acceleration control should not depend on a velocity estimate but only on vehicle attitude control.
Change requirement to pass check for acceleration setpoints when an attitude is available.
```
Fix: Allow offboard acceleration control with only attitude and no horizontal velocity estimate
```
I honestly did not go back in history to check why this dependency exists. I can still do that.
Not tested, I only made the pr while already looking at the code and discussing it.
=> Fix: Allow offboard acceleration control with only attitude and no horizontal velocity estimate

src/modules/navigator/mission.cpp, src/modules/navigator/navigator_main.cpp, src/modules/navigator/rtl_direct.cpp, src/modules/navigator/rtl_direct_mission_land.cpp, src/modules/navigator/rtl_mission_fast_reverse.cpp
After a VTOL backtransition the vehicle might not be close enough to the land point and thus needs to move horizontally.
It can happened that during this process the vehicle loses altitude and thus reaches the land point without being within the acceptance radius of the land point. In cases of strong wind or depleted batteries, it might not be possible for the vehicle to climb into the acceptance radius. However, this is also unnecessary, as the goal is eventually to descend.
Set the altitude acceptance radius to infinity when we are moving to the land point after the backtransition.
```
```
- Simulation/hardware …
=> Navigator: Set altitude acceptance radius to infinity when moving to land point after transition

src/drivers/uavcan/uavcan_params.c
- this is optional sensor metadata that can be set if actually needed
=> uavcan: relax UAVCAN_RNG_MIN/UAVCAN_RNG_MAX defaults

src/modules/ekf2/EKF/terrain_control.cpp, src/modules/ekf2/test/CMakeLists.txt, src/modules/ekf2/test/test_EKF_grounded.cpp
replaces #24161 
fixes https://github.com/PX4/PX4-Autopilot/issues/24160
Terrain was continuously reset using the current altitude estimate because the terrain state is not updated when EKF2_HGT_REF is set to range finder. Since the terrain state is used to update the height through range fusion, the height is not constrained and can freely drift away.
Do not run the "fake terrain fusion" (i.e.: reset terrain) if the terrain is the height reference is the range finder.
unit test
@dakejahl Could you please try this fix?
=> EKF2: fix range height altitude drift on ground

src/modules/fw_att_control/FixedwingAttitudeControl.cpp
wheel control got broken in https://github.com/PX4/PX4-Autopilot/pull/22472
Use angular rate for yaw rate (wheel) control instead of yaw euler angle.
SITL test
=> Fixedwing: fix wheel controller

src/modules/fw_att_control/FixedwingAttitudeControl.cpp
backport of https://github.com/PX4/PX4-Autopilot/pull/24167
=> [RELEASE/1.15] Fixedwing: fix wheel controller

src/modules/commander/Commander.hpp
It's been a while that blocks.hpp is not used by Commander, though it currently is still in the include list.
Since https://github.com/PX4/PX4-Autopilot/pull/23131 blocks.hpp is only used by the [LPE](https://github.com/PX4/PX4-Autopilot/blob/326d4863971e1b773aca2e94c79db748bbca25d7/src/modules/local_position_estimator/BlockLocalPositionEstimator.hpp#L7). And afaik only very specific methods of it. Should we go through https://github.com/PX4/PX4-Autopilot/blob/main/src/lib/controllib/blocks.hpp#L55 and remove the ones that are not used in the LPE?
=> Commander: remove not used include of blocks.hpp

src/modules/navigator/mission_base.h, src/modules/navigator/mission_block.cpp, src/modules/navigator/rtl_direct.cpp, src/modules/navigator/rtl_mission_fast_reverse.cpp, src/modules/navigator/rtl_mission_fast_reverse.h, src/modules/navigator/rtl_params.c
- Found by chance that precision landing is always started atm in RTL direct. It doesn't have any negative effect currently from why I see but still seems wrong.
- No precision landing possible in RTL_TYPE=2 and no mission landing planned (RtlMissionFastReverse)
- Check for the setting of `RTL_PLD_MD` and only `startPrecLand()` if precision landing is enabled, plus harden `startPrecLand()` to not do anything if not precision landing is not enabled.
- check `RTL_PLD_MD` in RtlMissionFastReverse and execute precision landing if set accordingly (similar logic as in RtlDirect)
```
Bugfix: Navigator: RTL_direct: onyl start precision land if param is set to enabled
Bugfix: Navigator: RTL: use precision landing if enabled in param RTL_PLD_MD also for reverse mission RTL
```
=> Navigator: RTL: Enable precision landing for all RTL types but only start if enabled

src/modules/land_detector/FixedwingLandDetector.cpp, src/modules/land_detector/FixedwingLandDetector.h, src/modules/land_detector/land_detector_params_fw.c, src/modules/land_detector/land_detector_params_mc.c
Horizontal velocity considered in land detector for fixed wings even when invalid. 
- Add condition to disregard horizontal velocity when vehicle_local_position.v_xy_valid is false. 
- Add additional rotational velocity condition for landed state.
```
Feature/Bugfix: Add condition to disregard horizontal velocity when vehicle_local_position.v_xy_valid is false in land detector for fixed wings. Add extra land condition based on rotational velocity. 
```
- Simulation/hardware testing logs: to be tested
=> FW LandDetector: disregard horizontal velocity if local_position.v_xy_valid is false

src/lib/systemlib/system_params.c
after answering the questions:
Ah, the value can be 2? Should I set the number of magnetometers the board has or include the external ones?
I tried to find a concise description that should cover the confusion. Please correct if it's not clear.
```
Clarify SYS_HAS_MAG parameter description
```
=> Clarify SYS_HAS_MAG parameter description

src/modules/logger/log_writer_file.cpp, src/modules/logger/log_writer_file.h
Open log file only once to avoid conflicts.
Fixes [#24155](https://github.com/PX4/PX4-Autopilot/issues/24155)
- The init_logfile_encryption() call is moved after the buffer's start_log() is called. This way file is opened only once and is already open when storing possible key data into the beginning of the file.
```
Bugfix: Fix logger file open when SDLOG_ALGORITHM is 0 (crypto disabled)
```
Could also add "append" parameter to start_log() function to select whether file needs to be opened as APPEND or CREATE flag. Another option is to store the keydata into temporary memory buffer and store it to file when opened in buffer's start_log() method.
- Unit/integration test: Logging functionality with encryption enabled and disabled verified with Pixhawk4 and …
=> logger: fix file open issue if crypto algorithm is disabled

src/drivers/distance_sensor/ulanding_radar/ulanding_radar_main.cpp
Stumbled upon this deprecated link.
=> drivers ulanding: fix link in description to user guide section

ROMFS/px4fmu_common/init.d/airframes/1002_standard_vtol.hil, ROMFS/px4fmu_common/init.d/airframes/1103_standard_vtol_sih.hil, ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt, src/modules/simulation/simulator_sih/sih.cpp, src/modules/simulation/simulator_sih/sih.hpp, src/modules/simulation/simulator_sih/sih_params.c
The standard VTOL airframe was previously not available for simulation-in-hardware (SIH). With these changes, it is. 
We add a new SIH specific SVTOL airframe file, ROMFS/px4fmu_common/init.d/airframes/1103_standard_vtol_sih.hil. In src/modules/simulation/simulator_sih/sih.cpp, we add the corresponding `SVTOL` vehicle type. These are changes from [this commit](https://github.com/PX4/PX4-Autopilot/commit/4d930bdec25c7e345476d0ab90e8485440e79847) (thanks @RomanBapst), applied to upstream/main. 
```
Feature: Support SIH for standard VTOL airframe. 
Documentation: Need to update on https://docs.px4.io/main/en/sim_sih/index.html
```
SIH test log: https://review.px4.io/plot_app?log=92dedeaf-78f7-4771-9556-fd8a0386d5b1
=> SIH: Add Standard VTOL Airframe

src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectiveness.cpp
... and actuator effectiveness
`ControlAllocation` lib depends on `ActuatorEffectivenss` lib. However, the base class of `ActuatorEffectiveness` was using an enum defined in `ControlAllocation`
Remove circular dependency 
```
Feature/Bugfix Removed circular dependency of ActuatorEffectiveness and ControlAllocation
```
We could also just look the other way. To make life more interesting, maybe we can chain multiple libraries to then form a longer circular dependency. This would be harder to spot.
SITL builds.
```
make px4_sitl gazebo-classic
```
=> Remove circular dependency if ControlAllocation and ActuatorEffectiveness

src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessFixedWing.cpp, src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessRoverAckermann.cpp, src/modules/control_allocator/ActuatorEffectiveness/ActuatorEffectivenessStandardVTOL.cpp
... and actuator effectiveness
`ControlAllocation` lib depends on `ActuatorEffectivenss` lib. However, some of the vehicle specific `ActuatorEffectiveness`  was including `ControlAllocation` while nothing was used.
Remove circular dependency 
```
Feature/Bugfix Removed circular dependency of ActuatorEffectiveness and ControlAllocation
```
We could also just look the other way. To make life more interesting, maybe we can chain multiple libraries to then form a longer circular dependency. This would be harder to spot.
SITL builds.
```
make px4_sitl gazebo-classic
```
- Follow up of https://github.com/PX4/PX4-Autopilot/pull/24195
=> Take 2: Cleanup circular dependencies ActuatorEffectiveness

src/modules/mc_att_control/mc_att_control.hpp, src/modules/mc_att_control/mc_att_control_main.cpp, src/modules/mc_hover_thrust_estimator/MulticopterHoverThrustEstimator.cpp, src/modules/mc_hover_thrust_estimator/MulticopterHoverThrustEstimator.hpp
Update the hover thrust estimator to use vehicle_thrust_setpoint (body frame) rather than vehicle_local_position_setpoint thrust (NED). This allows it to work in stabilized mode.
https://logs.px4.io/plot_app?log=6df3713e-f511-4e2e-854d-8fc7ab98ec65
TODO: 
- review usability and safety in stabilized mode
- battery scaling?
=> multicopter hover thrust estimator use vehicle_thrust_setpoint (work in stabilized/manual mode)

src/modules/logger/logged_topics.cpp
There's a caveat with `LoggedTopics::add_optional_topic`, it will fail to log topics that don't exist at the time of the logger instantiation. So any sensor that publishes later (CAN nodes for example) won't be logged. Namely the newish CanInterfaceStatus message, the status of the CAN interfaces is not logged since a CAN node will typically take longer to boot than the FC does.
=> logger: always log can_interface_status

boards/ark/fmu-v6x/init/rc.board_defaults, boards/ark/pi6x/init/rc.board_defaults
Multi EKF doesn't appear to have SITL CI testing and can have large divergence when not using GPS.
=> boards: disable multi ekf on all ark flight controllers

src/modules/ekf2/EKF/covariance.cpp
We cannot let the covariance of a temporarily unobservable state grow for ever due to numerical issues that will arise when the the matrix is getting ill-conditioned but the current method of clipping the variance  has a destabilizing effect as it increases the correlation between the states. (recall: `correlation = cov_xy / (sqrt(var_x) * sqrt(var_y)` so if `cov_xy` grows but `var_x` or `var_y` increases, `correlation` increases)
This can be observed on the position state when flying without GNSS (e.g.: navigating with optical flow or airspeed data). When the position variance reaches the limit of 1e6, clipping it causes the correlation with the velocity state to increase and when a single position observation is fused (here sent via a manual position update), the velocity variance …
=> EKF2: constrain max variance by zero innovation update

src/modules/control_allocator/Kconfig, src/modules/control_allocator/VehicleActuatorEffectiveness/ActuatorEffectivenessHelicopter.cpp, src/modules/control_allocator/VehicleActuatorEffectiveness/ActuatorEffectivenessHelicopter.hpp
After I merged https://github.com/PX4/PX4-Autopilot/pull/24096/ @bresch reminded me that v6x now overflows flash.
Make heli rpm control a separate optional build flag (for now).
The rpm capture driver is also disabled on default releases.
```
Save flash by removing helicopter rpm control from default builds
```
- Remove avoidance: https://github.com/PX4/PX4-Autopilot/pull/24172
- Switch to ARM GCC 13
- Split up the control allocation module into the last part of vehicle specific controllers
For me locally `make px4_fmu-v6x` comes down from `1744 bytes` to `304 bytes` overflowed 😬
so it doesn't free enough flash because it seems we were exactly at the limit before that pr or added more flash use since.
=> Control allocation: make heli rpm control an optional build flag disabled by default

src/modules/rc_update/params.c
When helping @Perrrewi with auxiliary channel mapping we found that the documentation is confusing because it's mentioning AUX1 is "Default function: Camera pitch". I think this is only there because there used to be static mixing of RC passthrough which was intended to be used for gimbal control. But this is obsolete now since the actuator functions can be mapped in any way and there's no default use for the AUX1 channel anymore.
Remove the confusing comment. I can't find any implementation anymore that would justify the comment.
```
Documentation: Remove comment about default use of AUX 1-3 input channels
```
This comment first occurred in 2012:
https://github.com/PX4/PX4-Autopilot/commit/f5bad08bd0f4e0f6506deeac9d369b2b9c2d9e32#diff-f3c9d446d29b39e4ce08d76016d215d513a14e19773d1972d093dc …
=> Documentation: Remove comment about default use of AUX 1-3 input channels

src/modules/mavlink/mavlink_main.cpp
With Tailsitter VTOL aircraft, the ground station display heading in forward flight is incorrect if `ATTITUDE_QUATERNION` is not streamed. The issue was fixed [here](https://github.com/mavlink/mavlink/pull/1247), but only if we use the quaternion attitude stream. Previously in mavlink mode `ONBOARD_LOW_BANDWIDTH` this was not done.
Stream `ATTITUDE_QUATERNION` too.
=> stream ATTITUDE_QUATERNION in low bandwidth mode

src/modules/ekf2/EKF/aid_sources/gnss/gps_control.cpp, src/modules/ekf2/EKF/yaw_estimator/EKFGSF_yaw.cpp
This tightens the yaw estimator validity requirements closing a potential hole. I don't think it's a real concern because it occured in an extreme case in simulation where the simulation was breaking down, but the additional checks could't hurt.
=> ekf2: yaw estimator additional validity checks

src/drivers/distance_sensor/lightware_sf45_serial/CMakeLists.txt, src/drivers/distance_sensor/lightware_sf45_serial/lightware_sf45_serial.cpp, src/drivers/distance_sensor/lightware_sf45_serial/lightware_sf45_serial.hpp, src/lib/collision_prevention/CMakeLists.txt, src/lib/collision_prevention/CollisionPrevention.cpp, src/lib/collision_prevention/CollisionPrevention.hpp, src/lib/collision_prevention/ObstacleMath.cpp, src/lib/collision_prevention/ObstacleMath.hpp, src/lib/collision_prevention/ObstacleMathTest.cpp
To prevent oscillations caused by the coupling of pitch and roll, which increase the sensor's measured distance, we account for these effects by introducing scaling based on pitch and roll into the measurements. This adjustment ensures accurate collision prevention.
Issue was solved inside of collision prevention by @mahimayoga in https://github.com/PX4/PX4-Autopilot/pull/24107, whereby this implementation is aequivalent. 
- Rough test on Hardware, should be flight tested before Merging.
=> SENS: SF45: Scale the measured distance with pitch and roll

msg/versioned/VehicleLocalPosition.msg, src/drivers/ins/vectornav/VectorNav.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/ekf_helper.cpp, src/modules/ekf2/EKF2.cpp, src/modules/flight_mode_manager/tasks/ManualAcceleration/FlightTaskManualAcceleration.cpp, src/modules/flight_mode_manager/tasks/ManualAcceleration/FlightTaskManualAcceleration.hpp, src/modules/flight_mode_manager/tasks/ManualAltitude/FlightTaskManualAltitude.cpp, src/modules/flight_mode_manager/tasks/ManualAltitude/FlightTaskManualAltitude.hpp, src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.cpp, src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.hpp, src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/navigator/mission_block.cpp, src/modules/simulation/simulator_mavlink/SimulatorMavlink.cpp
Currently, when flying with only optical flow in position mode, you can easily surpass the max HAGL by continuously pushing the throttle up. The vehicle decelerates until it eventually exceeds the limit. At that point, we immediately lose optical flow measurements (when above the max height), and consequently, the HAGL max parameter is no longer set.
I modified the controller to limit the altitude to 1 meter (or 10%) below the actual max height limit. This ensures that even after approaching the limit, optical flow remains active, and the controller tries to correct the altitude.
Previously, the HAGL max also influenced the controller in altitude mode, which was undesirable when using a range sensor or barometer. To resolve this, I split the HAGL max field of the local position message …
=> Fix max-hagl restriction to position/altitude control

ROMFS/px4fmu_common/init.d/rc.mc_defaults, src/modules/ekf2/params_range_finder.yaml
We encountered several instances where the fog detector did not get triggered during foggy conditions on VTOLs because the limit was not optimally set.
The initial default value was primarily based on multicopter flight logs. It also makes sense to maintain this value for MC since they are expected to fly over obstacles that are much closer compared to FW or VTOL.
=> Increase EKF2_RNG_FOG by default, keep reduced for MC

src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp
I got the feedback from @jongell that the feature I introduced in https://github.com/PX4/PX4-Autopilot/pull/22690 is not generally useful but necessary on a specific platform so I suggest to remove it again and only have the few lines on that platform.
This reverts commit 97cb933cff6d837e59dd55123804cd78abdca22a.
```
Remove feature: Limit land nudging horizontal speed close to the ground
```
I could leave it, make it configurable and disabled by default but in my eyes that's not worth it and just adds dead code complexity for everyone.
=> Revert "FLightTaskAuto: limit nudging speed based on distance sensor"

msg/VehicleImu.msg, src/modules/sensors/Integrator.hpp, src/modules/sensors/vehicle_optical_flow/VehicleOpticalFlow.cpp
I was using the integrator class for a sensor which published at 12 Hz, which equals a dt of roughly 80'000 us.
The integrator dt varialbe was using a uint16, which overflows at around 65'500.
Use an uint32 variable.
```
Improvement: Prevent overflow of dt variable in Integrator class for sensors with low sampling rates.
```
=> Prevent overflow of dt in Integrator class

src/modules/simulation/gz_bridge/GZBridge.cpp
=> gz: increase timeout for service request

src/modules/simulation/gz_bridge/GZBridge.cpp
The spawning of the model in the air is confusing in logs and right now is potentially impacting the EKF during initialization (specifically rangefinder alt source as primary). This was added in https://github.com/PX4/PX4-Autopilot/pull/22400 but IMO it would be better to fix the offending models on a case by case basis. In a perfect world the maintainer of a model/world would have the flexibility to spawn their model wherever they want.
=> gz: remove model spawn offset

src/drivers/uavcan/uavcan_main.cpp
- removed mutex from `print_status()` as this blocks the main loop and causes false positives for **HW errors**.
- check if any ESC or Servo output function is set and only print status if at least one is set
=> uavcan: improve status reporting

src/modules/ekf2/EKF/aid_sources/sideslip/sideslip_fusion.cpp, src/modules/ekf2/EKF2.hpp, src/modules/ekf2/params_sideslip.yaml
During front transition, the drone is still considered as a multirotor. Airspeed fusion can start when there is enough wind-relative velocity but sideslip fusion is still strictly relying on the fixed-wing flag. This causes race conditions in commander when the transition to fixedwing occurs as the ekf needs to receive the message before activating the sideslip fusion. 
The sideslip fusion parameter tells the EKF that this fusion type is possible on this vehicle. We know that it's only possible when airspeed is significant so we can let it start when the airspeed fusion starts as well (regardless of the vehicle type).
This also gives us a bit more flexibility as a multirotor with a vertical stabilizer and an airspeed sensor could also enable sideslip fusion.
-
=> EKF2: allow sideslip fusion to always start with airspeed fusion

src/modules/navigator/vtol_takeoff.cpp, src/modules/navigator/vtol_takeoff.h
The VTOL takeoff navigation mode was using the home altitude to calculate the climbout altitude. However, the vehicle does not necessarily need to be at the home point at the time it takes off and thus, the ground alatitude and the home altitude could be very different.
In fact, if the ground altitude at the home position is much lower than the ground altitude at the takeoff point, then the vehicle would fly into the ground after the transition.
Store the current altitude before takeoff and use that as reference for the climbout altitude.
```
```
SITL
=> VTOL Takeoff: use vehicle altitude instead of Home for altitude setpoint calculation

src/modules/navigator/MissionFeasibility/FeasibilityChecker.cpp, src/modules/navigator/MissionFeasibility/FeasibilityChecker.hpp
When someone adds a new check he might forget to add the flag to the `someChecksFailed` method.
Use a bitfield to make the method independent from individual booleans. 
SITL
=> Mission feasibility checks: make adding new check less error prone

src/drivers/power_monitor/ina238/ina238.cpp
Noticing some occasional dropouts of the data with the ARK 12s power modules. Same thing I found on the INA226 a couple of years ago. A single bad I2C read would cause the driver to publish 0's and not connected.
https://github.com/PX4/PX4-Autopilot/pull/19423
Needs to be tested on hardware.
Current behavior
=> ina238: retry if read fails

ROMFS/px4fmu_common/init.d/rc.fw_defaults
We want to align the default over all vehicle types for this param. There are still some thresholds that are increased for FW.
=> FW defaults: remove EKF2_GPS_CHECK custom FW setting

src/drivers/drv_dshot.h, src/drivers/dshot/DShot.cpp, src/drivers/dshot/DShot.h, src/drivers/pwm_out/module.yaml
Dshot 1200 was removed from betaflight in 2019.
```
DShot1200 is officially removed from Betaflight 4.1:
1. Dshot1200 is only needed for 32khz looptime, and 32khz looptime isn't supported any more in Betaflight. The highest looptime in Betaflight (in BF4.1) is 8KHz, and Dshot600 is enough for 8khz looptime
2. Dshot1200 was not stable when used with bidirectional DShot which is required for RPM filter, which has a higher priority than DShot1200
```
https://intofpv.com/t-dshot1200-removed-from-betaflight-4-1
https://github.com/betaflight/betaflight/issues/8967
=> dshot: remove dshot 1200

msg/Ekf2Timestamps.msg, src/modules/ekf2/EKF2.cpp, src/modules/logger/logged_topics.cpp, src/modules/replay/ReplayEkf2.cpp, src/modules/replay/ReplayEkf2.hpp
Airspeed data is not used in ekf replay as it often comes through the airspeed validator (`airspeed_validated`) and not from the driver directly (`airspeed`).
Include `airspeed_validated` in the list of topics used in replay.
tested in SITL:
```
INFO  [replay] Replay done (published 25032 msgs, 129.876 s)
INFO  [replay]
INFO  [replay] Topic, Num Published, Num Error (no timestamp match found):
INFO  [replay] airspeed_validated: 980, 0 <=====================================
INFO  [replay] sensor_combined: 24491, 5586
INFO  [replay] vehicle_air_data: 1387, 0
INFO  [replay] vehicle_magnetometer: 1373, 0
```
=> ekf-replay: fix airspeed replay

src/modules/control_allocator/module.yaml
When resolving my oversight here https://github.com/PX4/PX4-Autopilot/pull/23835#issuecomment-2432896248 I took over the parameter description I came up with.
```
Documentation: Add unit for actuator slew rate and reword description
```
=> Documentation: Add unit for actuator slew rate and reword description

ROMFS/px4fmu_common/init.d-posix/airframes/10041_sihsim_airplane, ROMFS/px4fmu_common/init.d/airframes/1101_rc_plane_sih.hil, ROMFS/px4fmu_common/init.d/airframes/1103_standard_vtol_sih.hil, src/modules/simulation/simulator_sih/sih.cpp
In PR https://github.com/PX4/PX4-Autopilot/pull/24175, I changed the control surface deflection signs in generate_fw_aerodynamics to make the 1103 airframe work correctly. However, this breaks the 1101 airframe, introducing sing errors there.
The change in generate_fw_aerodynamics is reverted to the state before PR #24175. Instead, the signs are set correctly by using the HIL_ACT_REV bitfield in the respective airframe config files.
Simulation logs. Stable forward flight, therefore correct signs for control surface outputs:
- With 1101 airframe (fixed wing): https://review.px4.io/plot_app?log=a6e02012-2eac-4d7e-92a2-17f3f24b62c7
- With 1103 airframe (standard VTOL): https://review.px4.io/plot_app?log=cfbccab7-a08e-4048-a101-755c1c1de0eb
=> SIH: clean up control surface configuration

boards/nxp/tropic-community/src/CMakeLists.txt, boards/nxp/tropic-community/src/imxrt_ocram_initialize.c, boards/nxp/tropic-community/src/init.c, boards/px4/fmu-v6xrt/src/CMakeLists.txt, boards/px4/fmu-v6xrt/src/imxrt_ocram_initialize.c, boards/px4/fmu-v6xrt/src/init.c
New GCC versions inline builtin functions like memcpy automatically.
On the fmu-v6xrt we can't call the functions inside init.c because the ram function still needs to be initialized. This commit adds a compile hint to not use builtins inside the init function.
This fixes the binaries being compiled with GCC 13.2 for the fmu-v6xrt
=> imxrt: Fix runtime error on new GCC

msg/EstimatorStatusFlags.msg, src/modules/ekf2/EKF/aid_sources/barometer/baro_height_control.cpp, src/modules/ekf2/EKF/common.h, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF2.cpp, src/modules/sensors/vehicle_air_data/VehicleAirData.cpp, src/modules/sensors/vehicle_air_data/VehicleAirData.hpp
When a baro gets labeled as faulty within the EKF, the system does not automatically switch to a possible alternative. This can lead to inaccurate altitude estimations despite still having a "spare sensor".
Example Scenario:
Tape was accidentally left on the external baro sensor, causing it to malfunction. Without a fallback mechanism, the EKF would simply stop fusing any baro data.
The `cs_baro_fault` flag has been added to the `estimator_status_flags` topic. This flag indicates if the currently selected sensor is labeled as faulty by the estimator. The baro handler (VehicleAirData) subscribes to this topic and adjusts the priority of the currently selected sensor to the minimum value where the sensor is still enabled (1).
`Add fallback method inn the baro-sensor-selection, based on the …
=> EKF2: add cs_baro_fault to switch to fallback baro if available

test/mavsdk_tests/vtol_mission_straight_south.plan
We should generally use VTOL_LAND instead of LAND to land a VTOL. Is more specific (first transition to hover, then land vertically). In our case we even enforce it with feasibility checks (not present in mainline PX4).
Do a VTOL_LAND instead of a LAND in the VTOL integration test.
```
Improvement: test: in VTOL integration test use VTOL_LAND
```
I've tested with the VTOL high wind integration test.
=> test: in VTOL integration test use VTOL_LAND

ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator, src/modules/commander/HealthAndArmingChecks/checks/externalChecks.hpp, src/modules/commander/ModeManagement.cpp, src/modules/commander/commander_params.c
A new parameter `COM_MODE_ARM_CHK` is defined to allow mode registrations while vehicle is armed. In the current implementation, by default, external mode registrations are only allowed while disarmed and therefore parameter default is set to reject mode registrations while armed. 
[`allow_update_while_armed`](https://github.com/PX4/PX4-Autopilot/blob/07e7c64e6035015dbad3559e715ceaeee1dac345/src/modules/commander/ModeManagement.cpp#L376) variable was previously hard-coded and disabled. To provide users the option to allow -external- mode registrations while vehicle is armed, this variable is parameterized as `COM_MODE_ARM_CHK`, a boolean PX4 parameter under commander group.   
```
Documentation: Need to …
```
=> Commander: COM_MODE_ARM_CHK parameter to allow mode registration while armed

ROMFS/px4fmu_common/init.d-posix/airframes/10043_sihsim_standard_vtol, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt, src/modules/simulation/simulator_sih/CMakeLists.txt, src/modules/simulation/simulator_sih/sih.hpp
We can now simulate all major airframes in [SIH-as-SITL](https://docs.px4.io/main/en/sim_sih/index.html#sih-as-sitl-no-fc) (meaning, both PX4 and PX4-internal sim running on PC). In the future this will allow for depreciation of gazebo in the context of automated tests, making them much faster and simpler. 
Add new airframe file, and add it to build system in relevant places. New make target: `make px4_sitl sihsim_svtol`.
```
Add standard VTOL airframe for SIH-as-SITL. 
```
=> SIH-as-SITL: add  Standard VTOL Airframe

src/modules/navigator/mission_block.cpp, src/modules/navigator/navigation.h
Not a specific problem, but noticed that in the Navigator we in two cases use 0.001 instead of FLT_EPSILON to compare a float to zero. 
Original contributions:
- [to compare the loiter radius setpoint to zero](https://github.com/PX4/PX4-Autopilot/commit/590f00f56089cf6afa62b7f4df07527c014da559)
- [acceptance radius comparison to zero](https://github.com/PX4/PX4-Autopilot/pull/20171)
Consistently use x > FLT_EPSILON for floating point comparisons against 0.
In there any risk in these fields somehow being e.g. 0.00001? Because then >FLT_EPSILON will now be true, while previously it was false.
=> Navigator: remove custom "FLT_EPSILONs"

ROMFS/px4fmu_common/init.d-posix/airframes/10040_sihsim_quadx, ROMFS/px4fmu_common/init.d-posix/airframes/10041_sihsim_airplane, ROMFS/px4fmu_common/init.d-posix/airframes/10042_sihsim_xvert, ROMFS/px4fmu_common/init.d-posix/airframes/10043_sihsim_standard_vtol, ROMFS/px4fmu_common/init.d/airframes/1103_standard_vtol_sih.hil
Removed unnecessary params in all sihsim airframe files, as well as standard VTOL for SIH on FC (1103).
=> SIH airframes: clean up config

src/modules/gimbal/output_mavlink.cpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/streams/GIMBAL_DEVICE_ATTITUDE_STATUS.hpp, src/modules/simulation/gz_bridge/GZGimbal.hpp
The current approach was wrong because the gimbal protocol now handles the case properly where the autopilot is in charge of a non-MAVLink gimbal.
This means that we don't need to send message "as if we were a gimbal device" and instead set thet gimbal_device_id to 1 (up to 6) to indicate we are in charge or a non-MAVLink gimbal.
Tested using `make px4_sitl gz_x500_gimbal` and still works.
=> gimbal: don't spoof gimbal device

src/drivers/distance_sensor/lightware_sf45_serial/lightware_sf45_serial.cpp, src/drivers/distance_sensor/lightware_sf45_serial/lightware_sf45_serial.hpp, src/lib/collision_prevention/ObstacleMath.cpp, src/lib/collision_prevention/ObstacleMath.hpp, src/lib/collision_prevention/ObstacleMathTest.cpp
When flying with the SF45 rotary lidar, the `_handle_missed_bins` function in `lightware_sf45_serial.cpp` can fill bins in the obstacle map that are outside the sensor's FOV.  This has negative consequences for the setpoint constraints that are set when flying with `CollisionPrevention`. (For example: losing ability to move in direction outside of FOV) 
Data being added to bins outside the FOV & consequenctly not being able to pitch-up (move backwards): 
When filling the missed bins, we loop thruough the indices always starting from the first bin within the FOV. (see figure). We loop through these indices, but fill the obstacle map at the original bin indices. 
This way we can handle cases in which the `current_bin` (in this illustration bin 6) and `previous_bin` (in this illustration bin …
=> SF45: Adjust  _handle_missed_bins() logic

platforms/nuttx/CMakeLists.txt
Newer toolchains don't ship with arm-none-eabi-gdb hence we should use gdb-multiarch instead.
This fixes vscode cortex-debug with ubuntu 24.04 on a clean install
=> cmake: for vscode launch fallback to gdb-multiarch

src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.cpp, src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.hpp
This needs careful review.
I'd like to remove the multicopter navigation test in commander because I think it's no longer needed and has the potential to do more harm than good latching on a false positive.
It's not that common anymore, but I've seen examples where we would have recovered (or were in the process of recovering), but this "nav test" triggers (latched) and you're done (velocity and position locked invalid).
The counter example I'm looking for is if this ever triggers and actually prevented a fallway that the EKF2 yaw estimator wouldn't have caught.
=> commander: remove multicopter nav test

src/modules/flight_mode_manager/FlightModeManager.cpp, src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.cpp, src/modules/flight_mode_manager/tasks/FlightTask/FlightTask.hpp
When switching from a flight mode that is not a flight task (e.g.: stabilized). In this case, the reset counters were initialized to 0 and deltas were applied to the first setpoints if the EKF had any of its reset counters different from 0.
In the plot below, we can see a “delta_heading” of 89 degrees. Adding 89 to the current heading of 70 gives the setpoint of 159 degrees.
Initialize the reset counters when starting the task instead of passing the ones of the previous task.
SITL tests
=> MC: Fix yaw jump when switching from stabilized to another mode

src/drivers/gps/gps.cpp
This reverts UBX changes that we don't want to backport into v1.15.
We now point to a release/1.15 branch within the PX4-GPSDrivers submodule.
=> [v1.15] gps: revert ubx changes, point to 1.15 branch

boards/modalai/voxl2/target/voxl-px4, boards/modalai/voxl2/target/voxl-px4-hitl-start, boards/modalai/voxl2/target/voxl-px4-start
The file _[voxl-px4-start](https://github.com/PX4/PX4-Autopilot/compare/pr-voxl-start-spacings?expand=1#diff-1130bb45ba164a9c8b4f5fa1cd9bafecf7ce8e6ca71c128aa96d3e9f595ef05f)_ currently uses both tabs/spaces which makes some conditions a bit hard to read.
Used spaces throughout the file, as this is what is also used in all the other voxl files in the target directory. This way the voxl scripts are consistent and the conditions are a bit easier to read.
=> voxl target: Remove trailing spaces, consistent tabs/spaces in files

src/modules/sensors/vehicle_air_data/VehicleAirData.cpp, src/modules/sensors/vehicle_air_data/VehicleAirData.hpp
Reacting to https://github.com/PX4/PX4-Autopilot/pull/24260#issuecomment-2626261008.
> A more immediate problem with this is the race condition with ekf2 declaring a baro fault, then sensors/vehicle_air_data changing the priority (likely causing a switch). 
We discussed first that we need to listen to the _baro_device_id_, published in the _control_status_. This could still be an issue since this id gets changed within the _VehicleAirData.cpp_ as well.
Only trigger the sensor fallback when the _baro_fault_ flag switches from 0 -> 1. This ensures that the sensor-reset has reached the EKF, which sets the flag to 0 in this case...
=> Baro fallback follow up, avoid consecutive triggers

src/drivers/distance_sensor/lightware_sf45_serial/lightware_sf45_serial.cpp, src/drivers/distance_sensor/lightware_sf45_serial/lightware_sf45_serial.hpp, src/lib/collision_prevention/CollisionPrevention.cpp, src/lib/collision_prevention/CollisionPrevention.hpp, src/lib/collision_prevention/ObstacleMath.cpp, src/lib/collision_prevention/ObstacleMath.hpp, src/lib/collision_prevention/ObstacleMathTest.cpp
No functional change, only refactoring.
Some repeated code across `CollisionPrevention.cpp` and `lightware_sf45_serial.cpp`. 
Move some repeated/static code to ObstacleMath library. 
Part of this was already done in the following pr's: 
1. https://github.com/PX4/PX4-Autopilot/pull/24142  
2. https://github.com/PX4/PX4-Autopilot/pull/24248
- Pure refactoring, no functional change. 
- In the long run the SF45 driver should no longer publish obstacle maps. rather just a distance measurement and an associated orientation. The map logic should be separated. The functions in the ObstacleMath library were created with this in mind.
=> ObstacleMath: move repeated/static code in SF45 & CollisionPrevention to ObstacleMath library

src/modules/uxrce_dds_client/dds_topics.yaml
This PR adds the `AirspeeValidated` msg under published dds topics in `dds_topics.yaml`. ROS2 applications with fixed-wing vehicles can with this change receive airspeed information. 
```
```
=> publish validated airspeed topic

Tools/astyle/files_to_check_code_style.sh
When going back and forth between older branches or releases, make format tried to reformat libuavcan.
=> make format: ignore libuavcan

src/modules/ekf2/EKF/aid_sources/range_finder/sensor_range_finder.cpp, src/modules/ekf2/EKF/aid_sources/range_finder/sensor_range_finder.hpp, src/modules/ekf2/test/test_SensorRangeFinder.cpp
If the range finder detected fog for more than 1 second, the range finder could never be declared valid anymore due to a deadlock.
Remove condition which requires data to have been valid for the last second from the fog checks. This is to make sure that the fog detection logic can reset itself.
I also fixed the unit tests.
```
```
=> Fix deadlock in fog detection logic and improved unit test

src/modules/esc_battery/EscBattery.cpp
User has requested to see ESC temperature in the QGC battery UI when using the ESC battery setting.
=> esc_battery: report ESC temperature as battery temperature.

.github/workflows/dev_container.yml
We are currently pushing a container build on every pull request commit, this is causing our API token to reach its limit very easily daily, and as a result we now have failures on CI actions.
This PR changes the behavior from pushing every commit on PR, to only when we push to main. Hopefully this eases the burden on the API token.
=> ci: fix dev container builds

Tools/px_uploader.py
This fixes an issue with flashing Ardupilot binaries for targets that use flash based params.
**Problem**
Ardupilot always uses 2 sectors for flash based params. PX4 only uses 1 sector. This means that in Ardupilot binaries the `image_maxsize` property will always be 128k smaller than the property in the PX4 binary.
**Alternate solutions**
I could instead use the `--force` flag, but that skips over the board type check as well which is not desirable.
=> tools: px_uploader.py: ardupilot compatibility

Tools/ci/check_msg_versioning.sh
These can be changed without version increment, the check was a bit too strict.
Follow-up to https://github.com/PX4/PX4-Autopilot/pull/24113
=> ci: ignore changes to comments or constants in versioned message check

boards/ark/can-gps/init/rc.board_defaults, boards/ark/can-rtk-gps/init/rc.board_defaults, boards/ark/cannode/init/rc.board_defaults, boards/ark/septentrio-gps/init/rc.board_defaults, boards/ark/teseo-gps/init/rc.board_defaults
We have been seeing some strange mag calibration results on cannode GPS recently. It looks to be caused or made worse by the mag bias estimator.
=> ARK Cannodes disable mag bias estimator by default

src/lib/parameters/CMakeLists.txt
VOXL 2 builds use DISABLE_PARAMS_MODULE_SCOPING for parameters. The new spacecraft module has duplicate symbols with the control_allocator module and so this kills the VOXL 2 build. This PR simply disallows the spacecraft parameters for VOXL 2 to fix the build. This means that VOXL 2 cannot use the spacecraft module until the underlying issue is addressed.
=> Don't allow spacecraft module parameters for VOXL 2 builds

src/drivers/gps/gps.cpp
It was observed, that a setup with a UBX ZED-F9P was not able to do RTCM injection of data received via MAVLINK. Debugging showed that the GPS module selected the RTCM instance data published by the ZED-F9P itself.
Don't select RTCM publications that originate from the device itself.
```
Bugfix Fix GPS RTCM instance selection
```
- Tested on the bench with a ZED-F9P and a RTK GPS receiver
=> Fix GPS RTCM instance selection

src/lib/sensor_calibration/Magnetometer.hpp, src/modules/commander/HealthAndArmingChecks/checks/magnetometerCheck.cpp, src/modules/commander/mag_calibration.cpp, src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
Magnetometers inside the autopilot are almost always highly affected by varying magnetic fields generated by the drone due to their location inside the drone.
The internal mag is useful for initial autopilot bench testing, before it gets integrated inside a drone, and when performing the calibration of the external one to automatically detect the rotation parameter. However, it then only causes issues as it often triggers false warnings (mag inconsistency) and in case of an in-air failure of the external mag, a fallback to the internal mag can lead to worse performance than not using a mag at all. 
Automatically disable all internal mags just after calibration if an external one is available.
```
Documentation: todo
```
Bench tested
=> Mag cal: automatically disable internal mags if external ones are available

src/modules/flight_mode_manager/tasks/ManualAltitude/FlightTaskManualAltitude.cpp
The multicopter flies in position mode, after the user gives throttle down input, the drone flew back up to the previous position without any input!
The issue is within the terrain_hold feature where the drone tries to hold its vertical position in respect to the `dist_to_bottom`. The `dist_to_ground_lock` gets set while the `dist_to_bottom` is still valid. Now the interesting thing happens. The `dist_to_bottom` gets invald, the user applies throttle input. After releasing the throttle the multicopter still has not stopped yet (still slowing down), therefore no new reference distance (`dist_to_ground_lock`) was set. Now the `dist_to_bottom` gets valid again and the `position_setpoint` gets reset to the `dist_to_ground_lock` which is out of date.
Always `dist_to_ground_lock` when the …
=> reset dist_to_ground_lock if dist_to_bottom is not valid

src/drivers/uavcannode/Publishers/RangeSensorMeasurement.hpp
Publishing reading too close will cause Ardupilot to deploy landing gear. The AFBR min range is set to 0. In the current case, publishing 0 range, even with a 0 quality, will cause the reading too close to be published. This should publish an undefined reading instead of too close.
=> uavcannode rangefinder: too far or too close, less than or greater than, not equal to

MAINTAINERS.md, README.md
* creates new maintainers file per oss best practices
* adds publicly available emails for those maintainers that have them public on their github profile
* adds Pedro as Space maintainer
=> readme: update maintainers information

src/modules/control_allocator/VehicleActuatorEffectiveness/ActuatorEffectivenessControlSurfaces.cpp, src/modules/control_allocator/VehicleActuatorEffectiveness/ActuatorEffectivenessControlSurfaces.hpp, src/modules/control_allocator/VehicleActuatorEffectiveness/ActuatorEffectivenessHelicopter.cpp, src/modules/control_allocator/VehicleActuatorEffectiveness/ActuatorEffectivenessHelicopter.hpp, src/modules/control_allocator/VehicleActuatorEffectiveness/ActuatorEffectivenessHelicopterCoaxial.cpp, src/modules/control_allocator/VehicleActuatorEffectiveness/ActuatorEffectivenessHelicopterCoaxial.hpp
- this is a harmless workaround for a GCC warning (-Wdangling-pointer) false positive
=> control_allocator: param update avoid temporary

src/drivers/voxl2_io/voxl2_io.cpp
fixes the currently failing `module_documentation` test
=> voxl: document enable_debug command

msg/Airspeed.msg, msg/VehicleAirData.msg, src/drivers/telemetry/hott/messages.cpp, src/drivers/uavcan/sensors/airspeed.cpp, src/modules/airspeed_selector/airspeed_selector_main.cpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/streams/HIGHRES_IMU.hpp, src/modules/mavlink/streams/HIGH_LATENCY2.hpp, src/modules/sensors/sensors.cpp, src/modules/sensors/sensors.hpp, src/modules/sensors/vehicle_air_data/VehicleAirData.cpp, src/modules/sensors/vehicle_air_data/VehicleAirData.hpp, src/modules/simulation/simulator_sih/sih.cpp
Currently, multiple temperature measurements are used across different functionalities to represent ambient temperature. This creates ambiguity regarding which temperature measurement should be designated as `vehicle_temperature`. We lack dedicated temperature sensors or topics to consistently rely on a single source.
Implement a prioritized selection of temperature sensors. When an external airspeed sensor is available, its temperature is used as the primary source. If an external barometer is present, its temperature serves as the secondary option. The temperature from the internal barometer is disregarded due to its unreliability, which is caused by inconsistent PCB heat dissipation across different flight controllers.
`
Create a distinct ambient_temperature field in the VehicleAirData …
=> Clean up temperature msg fields

msg/GimbalManagerSetAttitude.msg, src/modules/flight_mode_manager/tasks/ManualAccelerationSlow/FlightTaskManualAccelerationSlow.cpp, src/modules/flight_mode_manager/tasks/ManualAccelerationSlow/FlightTaskManualAccelerationSlow.hpp, src/modules/flight_mode_manager/tasks/ManualAccelerationSlow/flight_task_acceleration_slow_params.c, src/modules/flight_mode_manager/tasks/Utility/CMakeLists.txt, src/modules/flight_mode_manager/tasks/Utility/Gimbal.cpp, src/modules/flight_mode_manager/tasks/Utility/Gimbal.hpp, src/modules/gimbal/input_mavlink.cpp
The goal is to reduce latency in the position slow mode between the joystick input and what the user see. The idea is to add the yawstick on the gimbal setpoint and let the vehicle follow the gimbal attitude.
Originally after moving and releasing the joystick there was a residual motion in the image frame. With this solution, the residual motion is no longer present.
It has been tested in SIH and in flight on a multicopter using different camera lenses to see that the joystick inputs changes with the focal length.
Switching into position slow mode with the vehicles yaw setpoint follows the gimbal ones the device attitude status reports ROLL|PITCH|YAW LOCK. Then the feedback signal from vehicle yaw follow the new reference:
Moving the Yawstick changes the gimbals absolute yaw, and the …
=> MC Slowmode: Yawstick for gimbal control, vehicle yaw follows gimbal

src/lib/drivers/device/qurt/I2C.cpp, src/lib/drivers/device/qurt/I2C.hpp
The i2c driver for Qurt uses a single mutex for all buses. If a single bus has a long timeout it can hold up activity on the other buses needlessly. This PR changes the single mutex into a mutex for each bus to avoid that issue.
=> Move to per i2c bus mutex in Qurt i2c driver

src/drivers/imu/invensense/mpu6000/InvenSense_MPU6000_registers.hpp
CLion tends to find these somehow.
=> drivers: include fix for size_t

src/modules/fw_pos_control/FixedwingPositionControl.cpp
Alternative to https://github.com/PX4/PX4-Autopilot/pull/23795
Vehicle could stall during landing abort because flaps are currently instantly retracted.
Keep flaps in landing configuration until the abort altitude is cleared.
EDIT: if airspeed is valid, only keep flaps deployed until the airspeed is above FW_AIRSPD_MIN (which is the speed where the vehicle should be able to fly safely without any flap deployed).
```
Improvement: FW Position Control: keep flaps in landing config during abort
```
SITL tested
=> FW Position Control: keep flaps in landing config during abort

src/modules/internal_combustion_engine_control/InternalCombustionEngineControl.cpp
This follows on from #24055 proposing some docs corrections. Note that some of these might not be possible/might irritate the code formatter but they are "better markdown", and a few are necessary. I've added notes of explanation so we can work out where compromise is needed.
@Perrrewi I've also moved the images, and added the Actuator setup instructions, without which this is a little confusing. That information would _also_ appear in an ICE setup section. I moved the architecture down to the implementation section - most users don't need it.
Hope this all makes sense!
=> InternalCombustionEngineControl - doc corrections

.github/workflows/flash_analysis.yml
The `flash_analysis` workflow does not work with PRs from forks. I think this will fix it. Can't be sure until it's tested though.
@ramon can you merge this and then I can re-trigger a currently failing PR to see if it passes?
=> add write permissions for flash_analysis workflow

src/modules/control_allocator/VehicleActuatorEffectiveness/ActuatorEffectivenessHelicopter.cpp, src/modules/control_allocator/VehicleActuatorEffectiveness/ActuatorEffectivenessHelicopter.hpp, src/modules/control_allocator/module.yaml
When using a 4 servo swash plate, non-linearity due to the rotation of the servo arm can cause servo misalignment and binding, particularly at high collective + cyclic inputs. This results in higher loads on servos.
Add 2 parameters, `CA_LIN_SERVO` and `CA_MAX_SVO_THROW`, to account for the nonlinear output due to servo-arm rotation.
`CA_LIN_SERVO`: Enables the feature.
`CA_MAX_SVO_THROW`: Allows you to define the maximum throw of the servos in degrees. Set to 50 degrees by default.
The feature works as follows:
- Calculate the max linear movement of a servo arm of unit length based on the max servo throw. This corresponds to a PWM value of 1000/2000 (max/min control input). 
- Calculate the servo arm angle required to achieve desired linear output with arcsin(max_servo_height * input) …
=> control_allocator: Added linearization feature for 4 servo swash plates to prevent binding

src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp, src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.hpp
Nudging during landing (RC help) wasn't working correctly anymore due to https://github.com/PX4/PX4-Autopilot/pull/24172/commits/22fc4acfd63c02d6d8a84b5d97b752a055756a98 . In fact, the comment was misleading as this logic was also required for nudging.
Revert removal of isTargetModified as this is required when the target is changed by "RC help" (nudging) during landing.
Make it more explicit directly in the nudging logic
Tested in SITL
=> MC auto: fix land nudging

src/lib/systemlib/system_params.c, src/modules/commander/HealthAndArmingChecks/CMakeLists.txt, src/modules/commander/HealthAndArmingChecks/HealthAndArmingChecks.hpp, src/modules/commander/HealthAndArmingChecks/checks/opticalFlowCheck.cpp, src/modules/commander/HealthAndArmingChecks/checks/opticalFlowCheck.hpp
Currently an arming check for the optical flow sensor does not exist and I now added it. One can specify if the check should be included with the `SYS_HAS_NUM_OF` parameter. I already named it `SYS_HAS_NUM_OF` instead of `SYS_HAS_OF` to make the param future proof for having multiple OF-sensors at some point.
```
New parameter: SYS_HAS_NUM_OF ; New sensor requirement check for OF-sensor.
```
tested on hardware
=> PR: add optical flow arming check

src/modules/dataman/Kconfig, src/modules/dataman/dataman.cpp
Boards without (or with a very small) persistent storage will face unexpected problems, when a user configures dataman to use persistent storage. While such boards can set the parameter to a default value of _RAM for storage_ it is still possible to start dataman manually with the `-f` option on such boards and face problems.
Use KConfig to select if dataman should support persistent storage. It is kept by default on `y` so the behavior does not change for all existing boards
```
Feature Option to configure if dataman should support persistent storage
```
Tested both options on the bench.
Info: This option is set to `n` for a downstream board, that we did not upstream yet.
=> dataman KConfig for persistent storage

src/modules/vtol_att_control/vtol_type.cpp, src/modules/vtol_att_control/vtol_type.h
This functionality was moved to FlightTaskTransition and the variable was forgotten in https://github.com/PX4/PX4-Autopilot/pull/23731 (079b756f1b79866720c76417b8edd24547894703)
Remove the leftovers.
Still compiles `make px4_sitl` for me locally.
=> vtol_type: remove unused variable and function for deceleration pitch integral

msg/MavlinkTunnel.msg, src/drivers/actuators/voxl_esc/voxl_esc.cpp, src/drivers/actuators/voxl_esc/voxl_esc.hpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h
Added a new feature to the voxl_esc driver that allows custom packets to be sent through px4 via Mavlink tunnel messages with new payload type definition. Requires the updated mavlink submodule.
=> voxl_esc: Add Mavlink tunnel UART pass-through feature

src/modules/commander/HealthAndArmingChecks/checks/powerCheck.cpp, src/modules/commander/HealthAndArmingChecks/checks/powerCheck.hpp
We had a setup where the voltage was right at the threshold and the check toggled continuously.
With this change, it still triggers immediately, and then keeps for 15 seconds.
=> commander: add hysteresis for avionics power low/high check

msg/CMakeLists.txt, msg/FwLateralControlSetpoint.msg, msg/versioned/VehicleAttitudeSetpoint.msg, src/modules/fw_att_control/FixedwingAttitudeControl.cpp, src/modules/fw_lateral_longitudinal_control/FwLateralLongitudinalControl.cpp, src/modules/fw_pos_control/FixedwingPositionControl.cpp, src/modules/fw_pos_control/FixedwingPositionControl.hpp, src/modules/fw_pos_control/runway_takeoff/RunwayTakeoff.cpp, src/modules/fw_pos_control/runway_takeoff/RunwayTakeoff.h, src/modules/fw_pos_control/runway_takeoff/runway_takeoff_params.c, src/modules/mc_pos_control/PositionControl/PositionControlTest.cpp
This should be replaced with dedicated messages for wheel control (published by the takeoff handler and used in the FW attitude controller).
=> Remove wheel control related fields from main FW control topics

src/modules/commander/Commander.cpp
Previously, when requesting a mode switch to Position without a valid position estimate through an RC button, the mode change to Position mode was not rejected if `COM_POSCTL_NAVL` was set to 1 and instead the system switched to Altitude mode.
If the mode request instead came in through MAVLink it was rejected.
This PR aligns the two ways ([MAVLink](https://github.com/PX4/PX4-Autopilot/blob/ba31054992b00a5e59b73d1a1ce22b5b02efe312/src/modules/commander/Commander.cpp#L899), [RC](https://github.com/PX4/PX4-Autopilot/blob/ba31054992b00a5e59b73d1a1ce22b5b02efe312/src/modules/commander/Commander.cpp#L1699)) of changing a flight mode (passing `false` for the `allow_fallback` argument).
```
Bugfix: Fix flight mode Position not rejected correctly if change requested through RC …
```
=> Commander: handle mode change rejection the same for RC and MAVLink

ROMFS/px4fmu_common/init.d/rcS
When `CONFIG_DRIVERS_CDCACM_AUTOSTART` is disabled, the console tries to start mavlink on a non-existing port.
The cause is that `cdcacm_autostart start` will fail, since the app does not exist and then executes the branch:
```sh
if ! cdcacm_autostart start
then
sercon
echo "Starting MAVLink on /dev/ttyACM0"
mavlink start -d /dev/ttyACM0
fi
```
Example output of the issue:
```
nsh: cdcacm_autostart: command not found
nsh: sercon: command not found
Starting MAVLink on /dev/ttyACM0
ERROR [mavlink] Device /dev/ttyACM0 does not exist
Usage: mavlink <command> [arguments...]
Commands:
start         Start a new instance
[-d <val>]  Select Serial Device
values: <file:dev>, default: /dev/ttyS1
[-b <val>]  Baudrate (can also be p:<param_name>)
default: 57600
[-r <val>]  Maximum sending data rate in …
```
=> [rcS] Only start CDC/ACM when the module is enabled

src/drivers/distance_sensor/ulanding_radar/AerotennaULanding.cpp, src/drivers/distance_sensor/ulanding_radar/AerotennaULanding.hpp
We measured 50%-100% message drop, which could lead to repeated timeouts.
The issue was that the driver is written with the assumption that the entire message is received.
However the sensor sends a message every 10ms and when the driver samples every 10ms, only parts of the message will be received.
This workaround fixes this by setting the sample rate to 12ms, since 11ms still had single digit message drops.
The driver would have to be rewritten as a proper state machine to find the full message. For now this fix is sufficient.
- Tested in hardware
The sensor does not perform byte stuffing, thus the header must be searched together with the CRC.
=> Robustify Ulanding Radar

boards/bitcraze/crazyflie/syslink/syslink_main.h, msg/versioned/BatteryStatus.msg, src/drivers/actuators/voxl_esc/voxl_esc.cpp, src/drivers/batt_smbus/batt_smbus.cpp, src/drivers/power_monitor/ina220/ina220.cpp, src/drivers/power_monitor/ina226/ina226.cpp, src/drivers/power_monitor/ina228/ina228.cpp, src/drivers/power_monitor/ina238/ina238.cpp, src/drivers/power_monitor/voxlpm/voxlpm.cpp, src/drivers/smart_battery/batmon/batmon.cpp, src/drivers/uavcan/sensors/battery.cpp, src/drivers/uavcan/sensors/battery.hpp, src/lib/battery/battery.cpp, src/lib/battery/battery.h, src/modules/battery_status/battery_status.cpp, src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/commander/HealthAndArmingChecks/checks/batteryCheck.cpp, src/modules/commander/failsafe/failsafe.cpp, src/modules/esc_battery/EscBattery.cpp, src/modules/events/set_leds.cpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/streams/BATTERY_STATUS.hpp, src/modules/mavlink/streams/HIGH_LATENCY2.hpp, src/modules/simulation/battery_simulator/BatterySimulator.cpp
The battery-related enums (source and state) contain a leading 'BATTERY_' string in the enums's member names. The naming should to be clear enough without that string.
Remove the leading 'BATTERY_' string in the enums's member names.
Simplified battery-related enum naming
=> Simplify Battery-related Enum Naming

src/lib/parameters/flashparams/flashfs32.c
This fixes the initial sector erase on STM32H7 for params in flash.
The main bugfix is an off by one bug which prevents the last sector from being erased because a sanity check fails, see this line: https://github.com/PX4/NuttX/pull/329/files#diff-6255d0a0954ab8fb7180dd0dec85833fcbc76db90a92364f6a0a3b9cb3a7e4d1R376
This should fix issues we had seen with Kakute H7 (mini and v2) where a full erase was required to avoid random param issues.
Depends on https://github.com/PX4/NuttX/pull/329 to merged first.
=> [Sponsored by CubePilot] Params in flash erase fixes

src/modules/commander/Commander.cpp
Setting `lockdown` disables the actuators. In this mode, `force_failsafe` has no effect as the actuators are disabled, so the parachute is not getting released as it requires the output to change to its failsafe value.
Only set the `force_failsafe` (not `lockdown`) flag when in flight termination
We could change the priority in https://github.com/PX4/PX4-Autopilot/blob/01549a58326c47cf562dc190f7fa6eaf966516cc/src/lib/mixer_module/mixer_module.cpp#L477-L489 but I feel that this could be dangerous in HIL mode where switching to flight termination could trigger a physical parachute.
Tested on a Pixhawk4 with parachute configured on channel 4 with a failsafe value of 1234. The autopilot is then armed and tilted by 90 degrees to trigger the attitude failure detection.
main:
```
actuator_armed …
```
=> Commander: fix parachute trigger

ROMFS/px4fmu_common/init.d-posix/airframes/4001_gz_x500, ROMFS/px4fmu_common/init.d-posix/airframes/4003_gz_rc_cessna, ROMFS/px4fmu_common/init.d-posix/airframes/4004_gz_standard_vtol, ROMFS/px4fmu_common/init.d-posix/airframes/4006_gz_px4vision, ROMFS/px4fmu_common/init.d-posix/airframes/4008_gz_advanced_plane, ROMFS/px4fmu_common/init.d-posix/airframes/4009_gz_r1_rover, ROMFS/px4fmu_common/init.d-posix/airframes/4011_gz_lawnmower, ROMFS/px4fmu_common/init.d-posix/airframes/4012_gz_rover_ackermann, ROMFS/px4fmu_common/init.d-posix/airframes/4015_gz_r1_rover_mecanum, ROMFS/px4fmu_common/init.d-posix/airframes/4018_gz_quadtailsitter, ROMFS/px4fmu_common/init.d-posix/airframes/4020_gz_tiltrotor, ROMFS/px4fmu_common/init.d-posix/airframes/71002_gz_spacecraft_2d, ROMFS/px4fmu_common/init.d-posix/airframes/8011_gz_omnicopter, ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator, src/modules/simulation/gz_bridge/GZBridge.cpp, src/modules/simulation/gz_bridge/GZBridge.hpp, src/modules/simulation/gz_bridge/GZGimbal.cpp, src/modules/simulation/gz_bridge/GZGimbal.hpp, src/modules/simulation/gz_bridge/GZMixingInterfaceESC.cpp, src/modules/simulation/gz_bridge/GZMixingInterfaceESC.hpp, src/modules/simulation/gz_bridge/GZMixingInterfaceServo.cpp, src/modules/simulation/gz_bridge/GZMixingInterfaceServo.hpp, src/modules/simulation/gz_bridge/GZMixingInterfaceWheel.cpp, src/modules/simulation/gz_bridge/GZMixingInterfaceWheel.hpp
The GZBridge should only be a minimal interface between gz::transport and px4::uORB. I've refactored the module to remove all of the service calls. I've also cleaned up a lot of the code to ensure correctness.
- Added service calls to px4-rc.simulator
-- Model spawn (optional pose)
-- Follow camera with offset (optional)
-- Faster than real-time (PX4_SIM_SPEED_FACTOR)
- Added `sensor_gps` publishing to GZBridge in the NavSat callback (added noise)
=> gz: Refactor GZBridge and px4-rc.simulator

src/modules/sensors/vehicle_angular_velocity/imu_gyro_parameters.c
While performing filter tuning, QGC keeps notifying that the `IMU_GYRO_*` parameter requires reboot.
However, it is not nessary those parameter updates are applied immediately.
- Set `@reboot_required false` on the parameters
N/A
N/A
N/A
=> Remove reboot_required from IMU_GYRO_* parameters

src/modules/replay/Replay.cpp
=> Replay: avoid recursion when adding subscriptions

src/drivers/uavcannode/Publishers/RangeSensorMeasurement.hpp
Customer is still reporting that the ARK Flow is publishing reading too close and causing the landing gear to deploy.
=> uavcannode rangefinder: add tolerance to reading too close check

src/modules/simulation/gz_msgs/CMakeLists.txt
The gz_msgs CMakeLists just depends on Protobuf and does not have GZ dependencies. The CMakeList also depends on an environment variable and does not build properly for non-harmonic Gazebo versions if not set.
This changed highlighted that building with an older version of protobuf gives a warning. This suppresses the warning for older versions of protobuf to make the build successful. 
The bug has been fixed on newer versions of Protobuf in this Protobuf [PR](https://github.com/protocolbuffers/protobuf/pull/6000) in 2019. 
- Remove dependencies that are not required for gz_msgs to build properly. 
- Suppress the float equal warning on older protobuf versions. 
- Local build on Ubuntu 24.04 with GZ Ionic.
=> cleanup gz_msgs CMakeLists

src/drivers/adc/ads1115/ADS1115.cpp, src/drivers/adc/ads1115/ADS1115.h, src/drivers/adc/ads1115/ads1115_main.cpp
Two main problems: 
1. ADS1115 would not be recognized after a reboot, only after a power cycle.
2. ADS1115 would spam the console when there were I2C transmission issues due to motor EMI (specifically during takeoff and landing).
The driver code is also a bit too optimistic and doesn't log any comms errors.
I've refactored the driver to be more robust.
1. The ADS1115 lacks an ID register, so the driver checked the CONFIG register for default values. This only works once after a power cycle, since the driver reconfigures the CONFIG register and then after a reboot the values don't match any more. I'm now instead checking the threshold registers, since the driver does not touch them.
2. Debouncing via counter is done to detect if the device failed to prevent spam when a single I2C …
=> [adc] Refactor ADS1115 driver

src/drivers/px4io/px4io.cpp
I was getting compilation errors on some of TII's 64-bit px4 targets
Cast the printf argument to int, expected by %i
N/A
Tested that compilation passes in CI
=> src/drivers/px4io/px4io.cpp: Fix compilation errors from printf modifiers

src/lib/airspeed/CMakeLists.txt
I am experiencing a link error with airspeed library, which calls "getDensityFromPressureAndTemp" from "atmosphere", but there is no linking dependency to that library
Add "target_link_libraries" to add the link dependency
Tested that this change eliminates the linking issue in TII/SSRCs CI
=> src/lib/airspeed/CMakeLists.txt: Link to "atmosphere" library

src/modules/ekf2/EKF/python/ekf_derivation/derivation.py, src/modules/ekf2/EKF/python/ekf_derivation/generated/compute_flow_xy_innov_var_and_hx.h, src/modules/ekf2/EKF/python/ekf_derivation/generated/compute_flow_y_innov_var_and_h.h
The partial derivative of the flow observation with respect to the terrain and height states involve calculating the derivative of 1/x, which is -1/x^2. This function is even, making the estimate diverge in case x (the height above ground) is negative.
Below is an example where the terrain state starts above (more negative value) the height estimate. The optical flow is not able to correct this error as the jacobian is incorrect for negative distances.
The solution is to take the derivative of 1/|x|, which is -x/|x|^3 and is an odd function; preserving the sign of x. Note that for positive values of x, the expression reduces to -1/x^2.
Replaying the same log, we can see that the terrain state comes back below (more positive value) the height estimate.
Replay, SITL tests with flow only (no …
=> EKF2: fix flow derivation for negative HAGL

platforms/common/include/px4_platform_common/log.h, platforms/qurt/include/qurt_log.h, platforms/qurt/src/px4/SerialImpl.cpp, platforms/qurt/src/px4/drv_hrt.cpp, platforms/qurt/src/px4/main.cpp, platforms/qurt/src/px4/tasks.cpp, platforms/qurt/unresolved_symbols.c, src/drivers/qshell/qurt/qshell.cpp, src/modules/muorb/apps/uORBAppsProtobufChannel.cpp
Made general improvements to the QURT platform message logging so that module name is printed both in mini-dm and on apps side terminal. Also some QURT log formatting changes to get rid of extra newlines.
=> Improvements to the QURT platform message logging facility

src/lib/parameters/parameters.cpp
When switching to 1.15.3 based PX4 on some of TII's RISC-V based platforms, I found out that parameters crash on unaligned pointer access. This is due to some components, such as Logger, directly placing parameter values into a character buffer. The parameters component simply casts a non 32-bit aligned pointer value into float or int32, and accesses the value through that. As not all HW platforms support making such pointer dereferences, this crashes.
Previously in v1.14 these accesses were (correctly) done by memcpy, which handles the alignment. This PR changes those back to memcpy.
We could also change the interface to the parameter to be int32 *, or an union {int32, float] pointer, and hence pushing the alignment to the users of parameters interface.
Tested on a custom microchip …
=> src/lib/parameters/parameters.cpp: Remove conversion of unaligned pointers

src/modules/replay/Replay.cpp, src/modules/replay/Replay.hpp, src/modules/replay/ReplayEkf2.cpp, src/modules/replay/ReplayEkf2.hpp
When estimator replay is not enabled in `SDLOG_PROFILE`, the `ekf2_timestamps` topic is missing and the sensors are not logged at full rate. However, it could be still interesting to attempt a crude replay.
When `ekf2_timestamps` is not available to precisely align the data, schedule the replay on `sensor_combined` topic update and publish all other topics that got published between 2 updates.
- Replayable log (estimator replay enabled), Left: replay result of main; Right: replay result of PR 
- Non-replayable log (estimator replay disabled), Left: original; Right: replayed with this PR
=> Best effort EKF replay on non-replayable logs

src/modules/sensors/vehicle_air_data/VehicleAirData.cpp, src/modules/sensors/vehicle_air_data/VehicleAirData.hpp
Splitting up this https://github.com/PX4/PX4-Autopilot/pull/24220 into two parts.
The global calibration will get added within a different PR since we had some discussions about it's requirements and implementation.
This fix adds a calibration procedure for handling relative offsets between multiple baros, avoiding vertical position jumps when one switches between baros mid-flight.
The offset is now stored in the offset parameter since it's static and not a changing bias.
I checked various flight logs with durations of more than 3000s and could not observe non systematic drifts between baros. Therefore frequent recalibration does not make any sense.
`Always trigger automatic relative barometer calibration 1s after startup`
Tested on hardware.
=> Automatic relative baro calibration

src/modules/navigator/mission_base.cpp, src/modules/navigator/mission_base.h
This fixes an issue where the speed was not correctly set at the beginning of a survey (with first wp having a DO_CHANGE_SPEED attached) when the user paused and resumed the mission prior to reaching the first waypoint.
See following screen recording: mission is paused before reaching the survey, and on resume the survey speed is not applied.
https://github.com/user-attachments/assets/10b6ff69-2af9-4749-86a5-003cdd038ec9
Digging further down: when resuming the mission, the previous DO_CHANGE_SPEED are not immediately replayed but only once the next waypoint is reached. In the case here, this coincides with the next DO_CHANGE_SPEED (12) of the survey, which is thus overwritten by the previous DO_CHANGE_SPEED (5), and the survey is flown at 5m/s instead of 12.
Replay DO_CHANGE_SPEED …
=> MissionBase: replay change speed on resume immediately if not going to  previous

src/modules/commander/failsafe/failsafe.cpp
When `NAV_DLL_ACT` or `NAV_RCL_ACT` is set to "Hold" and the link is re-gained after losing it, it will currently automatically switch back to the previous mode (e.g. Manual Position mode). If the user isn't aware of that it can easily result in a crash. 
Like we already do for the other actions options (RTL, Land), stay in that mode if the link loss failsafe gets cleared, until the user actively takes over again.
```
Improvement:  Never clear link loss failsafe automatically, also not when action is Hold. Require user input to go back to original mode.
```
SITL tested.
=> Commander: Never clear link loss failsafe automatically, also not when action is Hold

src/drivers/magnetometer/isentek/ist8310/IST8310.cpp, src/drivers/magnetometer/isentek/ist8310/IST8310.hpp
Reading the WAI register is unreliable as the chip sometimes returns wrong values but functions otherwise correctly. In addition, the chip may not have read the chip select pins correctly and responds to 0x0C instead of 0x0E. These problems go away after a software reset.
IST8310 sensor inside the CUAV IST8 external compass would sometimes not be detected properly. 
In these cases the sensor had an I2C address of 0x0C, thus the software reset of 0x0E doesn't work.
Sending the reset command to all possible I2C addresses works in any case.
Not really.
Our suspicion is that the sensor powers up incorrectly through the pullup resistors of the I2C lines, which are powered for ~1s before the 5V rail is switched on. This might have caused the I2C address selection pins to be misread as both GND …
=> [IST8310] Probe all I2C addresses on startup

src/modules/navigator/takeoff.cpp
Loiter after takeoff is done around Home instead of at current location, unless the distance to Home is too high at this point, see [this condition](https://github.com/PX4/PX4-Autopilot/blob/0ee592f67c4f52cf8e7a0d9939e00e5f1a3348f6/src/modules/navigator/loiter.cpp#L104C4-L104C6).
We already [set loiter position in loiter.cpp](https://github.com/PX4/PX4-Autopilot/blob/0ee592f67c4f52cf8e7a0d9939e00e5f1a3348f6/src/modules/navigator/loiter.cpp#L108-L116), and thus I propose to remove it from the `takeoff::on_active()`. 
What we possibly drop with that [switch is to set IDLE](https://github.com/PX4/PX4-Autopilot/blob/0ee592f67c4f52cf8e7a0d9939e00e5f1a3348f6/src/modules/navigator/takeoff.cpp#L77) when the vehicle is landed after the takeoff is complete. But do we really need it? In [this …
=> Takeoff: loiter after takeoff is established where the takeoff mode is completed, not around Home

src/modules/commander/failsafe/failsafe.cpp, src/modules/commander/failsafe/failsafe.h
There is already another check for battery_unhealthy, so a separate state and ID are required.
Fixes the error:
ERROR [failsafe] BUG: duplicate check for caller_id 74
=> fix commander: separate state tracking for battery_unhealthy failsafe

.github/workflows/docs_crowdin_download.yml
Update the workflow to use PX4BUILTBOT_PERSONAL_ACCESS_TOKEN, which I have already defined.
=> docs_crowdin_download.yml - use secrets 

docs/crowdin.yml
This is to fix an error in the crowdin download of translations
=> crowdin.yml - fix ignore to be an array

src/modules/ekf2/EKF/estimator_interface.cpp
follows https://github.com/PX4/PX4-Autopilot/pull/24472
GNSS velocity was not considered in `getNumberOfActiveHorizontalVelocityAidingSources`
add it
=> EKF2: consider GNSS vel as horizontal velocity aiding

src/modules/replay/Replay.cpp, src/modules/replay/Replay.hpp, src/modules/replay/ReplayEkf2.cpp, src/modules/replay/ReplayEkf2.hpp
The INS part of the EKF relies on the `integral_dt` of the `sensors_combined` message to perform the integration. This doesn't cause issues in the real-time system as we don't miss any sample, but it causes issues in the "Best effort replay" where the data is not logged at full rate, accumulating a large time slip.
Adjust the integral_dt (gyro and accel) to match the time between 2 sensor_combined logged samples.
Left: main, right: this PR
We can see that the time slip creates navigation issues that can be resolved with this PR.
=> ReplayEKF: reduce effect of IMU time slip

src/modules/navigator/takeoff.cpp
Alternative to https://github.com/PX4/PX4-Autopilot/pull/24454, fixes https://github.com/PX4/PX4-Autopilot/issues/24496#issuecomment-2719544023
See https://github.com/PX4/PX4-Autopilot/pull/24454
Do a if(MC) check, and keep current logic only for MC, while for FW establish loiter always at current position. 
Reason for differentiation MC/FW: And MC takeoff is considered complete before reaching set altitude, while for [FW it has to achieve the altitude fully](https://github.com/PX4/PX4-Autopilot/blob/e0d15b7a8042cfb38dcba6a064eb8685646526c0/src/modules/navigator/mission_block.cpp#L205). 
```
Bugfix: fixed-wing: loiter after takeoff is established at current position, not around Home
```
- We could add a method `setLoiterItemFromCurrentAltitudeSetpoint()` which sets a …
=> Fixed-wing: loiter after takeoff is established at current position, not around Home

src/drivers/gps/gps.cpp
When testing with the following setup, consistent GPS timeouts were observed:
- F9P with reduced output rate (https://github.com/PX4/PX4-GPSDrivers/commit/bbdd5767a961cc17bdcc577c79b1c708d2a7999a)
- NTRIP RTCM3 injection (15Hz)
- RTK dumping
Looking through the code revealed multiple causes for this:
- The UBX parser could get stuck in an invalid state, due to a buffer overflow (https://github.com/PX4/PX4-GPSDrivers/commit/91e3dbb296d74b2a6d4f8f3c7f2fddd3c6705495)
- Due to RTK dumping, the GPS outputs both UBX + RTCM3 on the UART. In some cases the parser parsed an invalid RTCM3 length, which caused it to read a lot of data (> 900 byte) and afterwards dumping all of that data. As it read invalid data, the parser was out of sync and it took quite some time for it to find the next valid UBX …
=> GPS Dump timeout increase + GPS overflow fix

src/modules/simulation/gz_bridge/GZBridge.cpp, src/modules/simulation/gz_bridge/GZBridge.hpp
Fixed model spawning issue only to discover that the realtime was not being set. Adds a conditional to set realtime clock at system startup.
=> gz: set realtime clock at startup

src/drivers/uavcan/sensors/gnss.cpp
We need to wait for a valid UTC timestamp, otherwise we end up in 1970 with Here 4 which sends 0 for a bit even if there is already a fix.
=> [Sponsored by CubePilot] uavcan: ignore 0 UTC timestamps

src/modules/simulation/gz_bridge/CMakeLists.txt
When inspecting the network with Wireshark I found that gazebo sends out a gigantic amount of multicast messages to everyone on the network containing ASCII string information about computer name, topic names, values for all kinds of sensor samples, commands, UI interactions. The problem with this is that they influence other systems and if there are enough simulations running can even bring down network performance significantly.
Note: When running the gazebo simultion in WSL the multicast packets never get routed away from the machine but on Linux the messages are sent out to all networks.
Reproduce:
1. Run `make px4_sitl gz_x500`
2. Check with Wireshark any network adapter on the computer the simulation is running (or any other computer in the same network).
3. See tons of spam
I'm not …
=> Hotfix: stop gazebo simulation from spamming multicast packets on the network

src/modules/vtol_att_control/vtol_att_control_params.c, src/modules/vtol_att_control/vtol_type.cpp
When the airspeed sensor is blocked, a VTOL will remain in the front transition until the transition times out (duration defiend by parameter). During this time the vehicle can speed up considerably and the rate controller can go into a limit cycle since the airspeed scaling does not work properly anymore.
Furthermore, the airspeed validator does not check against airspeed failures during the transition.
If the vehicle uses airspeed, then we can be more strict on the transition timeout logic, by requiring that the airspeed should have reached at least the blending airspeed after the open loop transition time. The open loop transition time is usually set to the expected transition time and the airspeed blend parameter is usually well below the transition airspeed. Therefore, this condition …
=> Added VTOL check for airspeed increase during front transition

docs/en/power_module/holybro_pm02d.md
As per https://github.com/PX4/PX4-user_guide/pull/3640#issuecomment-2725420013 there is only one PM02D - a current one and a legacy one. They vary in configuration.
This fixes up the doc so it is centred around the current variant. The only difference is in the configuration, so I've added a warning for that case.
=> Holybro PRM02d - fix up to make it clear there is only one variant now

docs/crowdin_docs.yml
This adds back in the ignore option for the test sidebar. That gets created automatically from SUMMARY.md, so does not need to round-trip translate.
=> crowdin - add back in the ignore

.github/workflows/docs_crowdin_upload.yml
=> Run upload on workflow dispatch if we want.

docs/en/config/_autotune.md
Autotune is breaking the docs build because it is sensitive to translations. This removes a little bit of that sensitivity, by making sure that crowdin numbering matches source numbering.
=> Autotune tidy - hopefully improve translations

.github/workflows/docs_crowdin_upload.yml, .github/workflows/docs_deploy.yml
Deployment step once docs built is taking about three times longer on PX4-Autopilots than it was with PX4_user guide repo. The only difference in the deploy step for the old and new is that the older user guide version used ubuntu-latest while the new one runs on runs-on: `[runs-on,runner=2cpu-linux-x64,image=ubuntu24-full-x64,"run-id=${{ github.run_id }}",spot=false]` - the zip is the same and generates in the same time.
This increases the runner to 8cpu to see if that makes a difference.
Also updated docs_crowdin_upload.yml to only run when something goes into main
=> docs_deploy.yml - bigger deployment runner

src/modules/flight_mode_manager/tasks/ManualAltitude/FlightTaskManualAltitude.cpp
When switching from RTL to position mode while the drone was ascending, the distance lock was set while still moving vertically. This resulted in the drone stopping its vertical motion first and then descending again to the distance-lock height.
We only lock the distance as soon as the vertical velocity is small enough...
before:
after:
STIL
=> enable terrain_hold when not moving vertically

src/modules/uxrce_dds_client/dds_topics.yaml
So that external ROS flight modes can make use of it, e.g. for return-to-launch features, reasoning about line-of-sight, or similar. 
Tested in simulation, correct output with `ros2 topic echo /fmu/out/home_position`.
=> dds_topics: add home_position

boards/modalai/voxl2-slpi/src/drivers/spektrum_rc/spektrum_rc.cpp
The custom Spektrum RC driver for VOXL2 SLPI target has a protocol byte check in it that fails with certain Spektrum transmitters. Those transmitters work fine without the protocol byte check. The DSM library does not do this check. So, it was removed from the custom driver to make it compatible with more Spektrum receivers.
=> voxl2-slpi: Removed bogus protocol check in custom Spektrum RC driver

src/lib/rover_control/RoverControl.cpp, src/lib/rover_control/RoverControl.hpp, src/modules/rover_ackermann/AckermannPosVelControl/AckermannPosVelControl.cpp, src/modules/rover_ackermann/AckermannPosVelControl/AckermannPosVelControl.hpp, src/modules/rover_differential/DifferentialPosVelControl/DifferentialPosVelControl.cpp, src/modules/rover_differential/DifferentialPosVelControl/DifferentialPosVelControl.hpp, src/modules/rover_mecanum/MecanumPosVelControl/MecanumPosVelControl.cpp, src/modules/rover_mecanum/MecanumPosVelControl/MecanumPosVelControl.hpp
This PR introduces the following update for rover auto mode logic:
If the `positionSetpointTriplet.next` is invalid, it will no longer default to being set to the `homePosition`.
Whenever the `next` waypoint is invalid, the rover will now come to a smooth stop at the current waypoint.
In other words, the mission is expected to be finished at the `current` waypoint if the `next` waypoint is invalid.
This removes the need to explicitly check if the vehicle is in 'return' flight mode.
Additionally, the waypoint types `Idle` and `Land` are treated as stopping conditions to prevent the rover from loitering around the waypoint.
This PR also refactors the speed setpoint calculation in auto mode of the rover modules to bring them more in line with each other.
Tested in SITL
=> rover: auto mode stopping conditions

src/modules/fw_pos_control/FixedwingPositionControl.cpp, src/modules/fw_pos_control/FixedwingPositionControl.hpp
**Solved Problem**
FW position controller `Run()` function runs regardless of flight mode. As a consequence: 
- `fixed_wing_lateral_status` is [continuously published](https://github.com/PX4/PX4-Autopilot/blob/pr-fw_ctrl_api/src/modules/fw_pos_control/FixedwingPositionControl.cpp#L2292) (undesirable)
-  the lateral and longitudinal [control limits are (incorrectly) updated ](https://github.com/PX4/PX4-Autopilot/blob/pr-fw_ctrl_api/src/modules/fw_pos_control/FixedwingPositionControl.cpp#L2287)every second 
when we are not using the position controller. 
**Solution** 
Current fix checks that we are not in an external flight mode before running position controller (temporary fix) 
To consider:
- Still runs even when in stabilized/manual. But could add these nav states as well to the run …
=> [Against another PR] fw-pos-ctrl: check nav state before running

.github/workflows/flash_analysis.yml
I received multiple comments that people want back the flash analysis comment, as it was working just fine for them as long as one worked on a non-fork branch.
This re-enables the flash analysis comment for non-fork PRs (via: `github.event.pull_request.head.repo.full_name == github.repository`, as described here: https://github.com/orgs/community/discussions/25217). A solution for fork PRs requires a bigger re-work for the flash analysis job (need to use `pull_request_target` as described here: https://github.com/PX4/PX4-Autopilot/issues/24408). This way we have incremental progress, until the complete solution is available.
=> Enable flash analysis comments again for non-fork PRs

Tools/px4.py
this tool is mainly being used by homebrew, its been failing or giving bad output since we updated the repo name.
=> tools: fixes px4.py when run outside of root

src/modules/ekf2/EKF/aid_sources/magnetometer/mag_control.cpp, src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
The heading after a quick mag cal (large vehicle mag calibration) is sometimes off by up to 10-15 degrees, but correct after a reboot.
I found that the reset counter was not properly in sync with the data corrected by the new calibration. If fact, it's because part of the data in the down-sampler is corrected using the "old" calibration.
Clearing the buffer makes it work correctly:
Additionally, I changed the EKF to automatically perform a heading reset when the new calibration is applied.
tested in SITL, on v5 and v5x
=> Fix large vehicle mag calibration

docs/.vitepress/config.mjs
This fixes vitepress config so that the file to open in the front matter is respected when you open it locally (not just on github).
=> Open file locally respects frontmatter

.github/workflows/docs_crowdin_download.yml
The label is actually `Documentation%20📑`, not `Documentation`
=> docs_crowdin_download.yml - attempt to fix the label

src/modules/uxrce_dds_client/dds_topics.yaml, src/modules/vtol_att_control/vtol_att_control_main.cpp, src/modules/vtol_att_control/vtol_att_control_main.h
So that external ROS flight modes can more easily observe VTOL state of PX4. 
This is mostly available / inferrable from the main VehicleStatus -- using the separate message makes handling easier on the receiving end at the cost of extra bandwidth. 
Tested in simulation, correct output with `/fmu/out/vtol_vehicle_status`.
=> dds_topics: add vtol_vehicle_status

src/modules/fw_rate_control/FixedwingRateControl.cpp
The maximum airspeed parameter (FW_AIRSPD_MAX) is not a guarantee that the actual vehicle airspeed will not exceed it's value. Either a mechanical failure or a misconfiguration can cause such a situation and therefore it does not make sense to limit the airspeed for the actuator scaling to the maximum airspeed parameter.
This can cause structural damage to the vehicle caused by rate controller limit cycling.
Remove the parameter limit.
```
Removed FW_AIRSPD_MAX as upper airspeed limit for control surface scale calculation.
```
=> FW rate controller: Don't constrain airspeed for scaling to maximum airspeed

src/modules/navigator/rtl.cpp, src/modules/navigator/rtl.h, src/modules/navigator/rtl_params.c
This adds RTL_TYPE 4 which means continue the mission or reverse back to the takeoff location, whichever is closer in terms of mission items in-between.
This would be nicer to have on a distance rather than mission item count basis but that would require access to the dataman and make it more complex.
=> Add RTL_TYPE to continue or reverse

msg/CMakeLists.txt, msg/versioned/AirspeedValidated.msg
The airspeed_validated topic is an important topic to stream over to ROS, and we're doing that since https://github.com/PX4/PX4-Autopilot/pull/24302. To keep the interface stable and have the translation working, I would version it.
Version it.
```
Feature: AirspeedValidated: add MESSAGE_VERSION
```
=> AirspeedValidated: add MESSAGE_VERSION

src/modules/dataman/parameters.c
As discussed in https://github.com/PX4/PX4-Autopilot/pull/24412#issuecomment-2685210532 the `Default storage` option behaves differently depending on whether or not the board supports persistent storage. This can be confusing for users.
Explain the behavior in the parameter documentation. This will cost us some FLASH for the documentation (72 byte), but this way the behavior is explained where it can be configured, so users can directly see the impact this parameter has.
=> dataman: clarify default storage backend

src/modules/commander/commander_params.c, src/modules/commander/failsafe/failsafe.cpp, src/modules/commander/failsafe/failsafe.h
It's currently not possible to exclude specific navigation modes from the data link loss failsafe action.
Similarly to COM_RCL_EXCEPT, add COM_DLL_EXCEPT.
I also realized that for a datalink loss we generally added an exception for when navigation modes were either NAVIGATION_STATE_AUTO_LAND or NAVIGATION_STATE_AUTO_PRECLAND.
I did not see a reason why we should not add the same exception for RC loss.
```
New parameter: COM_DLL_EXCEPT, allow to specify exceptions for navigation modes for the data link loss failsafe action. 
```
?
?
?
=> Add COM_DLL_EXCEPT to specifiy exceptions for data link loss failsafe

src/modules/simulation/gz_plugins/CMakeLists.txt
Fixes https://github.com/PX4/PX4-Autopilot/issues/24631
This tries to build the plugins and breaks the SITL build if you have Gazebo garden installed even if you're not trying to simulate with Gazebo.
```
Fix SITL build when Gazebo garden is still installed
```
`make px4_sitl` works and
`make px4_sitl gz_x500` fails because I don't have the correct Gazebo version
=> Fix SITL build when Gazebo garden is still installed

src/modules/ekf2/EKF/aid_sources/optical_flow/optical_flow_fusion.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/test/test_EKF_flow_generated.cpp
Some EKF stability issues were occurring near the ground, where the optical flow measurement is near its singularity point (0 distance).
- Adjust the optical flow prediction model to exactly match the one used in the derivation
- Avoid unnecessary double division in flow measurement prediction
- Limit flow measurement prediction magnitude by limiting the minimum predicted distance to 1cm
- Re-calculate innovation test ratio after having fused the flow X axis. As we operate close to the singularity, fusing the Y axis without checking the new test ratio can lead to over-corrections as the innovation might be really large
I was able to trigger issue on a bench setup with high baro drift and by allowing the EKF to start the flow fusion without range finder. The flow fusion then starts with a …
=> EKF2: improve optical flow stability near the ground

docs/en/advanced/gimbal_control.md, docs/en/peripherals/mavlink_peripherals.md
This updates gimbal docs to reflect that 
- Gimbal should use mode of Gimbal, not normal
- setting the mav mode to gimbal automatically sets MAVLink forwarding
- FLow should be turned off normally.
Also updates generic MAVLink setup to include the current set of modes, and to link to specific mavlink setup for gimbal and camera.
This fell out of https://github.com/mavlink/mavlink/issues/2239#issuecomment-2753449926
=> [Docs] Gimbal - improvements to mavlink setup instructions

msg/px4_msgs_old/msg/VehicleAttitudeSetpointV0.msg, msg/translation_node/translations/all_translations.h, msg/translation_node/translations/translation_vehicle_attitude_setpoint_v1.h, src/modules/fw_pos_control/ControlLimitsHandler.hpp
Two commits: 
1. Clang tidy failure: redundant boolean in  `floatValueChanged` function in `ControlLimitsHandler.hpp` 
2. ROS translation node: bump msg version of `VehicleAttitudeSetpoint.msg` and add translation header. 
**Current base is main so the CI tests are against the correct branch.**
=> [Against another PR] Address CI Failures 

boards/modalai/voxl2/target/voxl-px4-start
The default value of EKF2_EV_CTRL was 15 pre v1.16.0. It is now 0. For folks changing from an older version to v1.16.x that were relying on that default on VOXL 2 it would cause problems so the default value for VOXL 2 is explicitly set to 15 with this PR. See https://github.com/PX4/PX4-Autopilot/issues/24439
=> Added setting default for EKF2_EV_CTRL to 15 for VOXL 2 boards

src/modules/mc_att_control/mc_att_control.hpp
When I looked at #19633 specifically the merged commit 28fa04438616d16363306878e6bfee0473c77afc which I didn't have the opportunity to review, I realized that a seemingly random subscription instance was added and I couldn't find why. 
This was probably mistakenly added so I suggest to remove again.
```
Cleanup: remove unnecessary subscription in multicopter attitude controller
```
I'ts not used anywhere and still compiles without.
=> Cleanup: remove unnecessary subscription in multicopter attitude controller

src/modules/simulation/gz_plugins/CMakeLists.txt, src/modules/simulation/gz_plugins/gstreamer/CMakeLists.txt
It was impossible to run a gazebo simulation without gstreamer being installed, even if the gstreamer plugin was not necessary.
- Remove the `REQUIRED` dependency of gstreamer and check if it is found.
- Don't built the gstreamer plugin if gstreamer is not installed issue a warning message.
- Simulation test on a machine without gstreamer and a machine with gstreamer. Both are able to run `make px4_sitl gz_x500` now without issues.
=> Reduce dependency of gstreamer for gz simulation

src/lib/npfg/CourseToAirspeedRefMapper.cpp, src/lib/npfg/NpfgTest.cpp
Add unit tests to NPFG library.  
- Extend NPFG unit tests. 
- CourseToAirspeedRefMapper: Add infeasible bearing check back into logic. 
Interaction between CourseToAirspeedRefMapper class and LatLong controller: 
\* we need to check for feasibility because: the `projectAirspOnBearing` returns zero when the cross wind is > airspeed. This results in a heading that aligns the aircraft against the wind, rather than trying to achieve the bearing/minimize drift. 
\** My understanding of the infeasibleAirVelRef function is as follows (could be wrong): 
The infeasible bearing heading is defined by two components: (1) Into the bearing & (2) Into the wind. The weight of the component into the bearing direction (1) is determined by the magnitude of excess windspeed w.r.t our airspeed_sp. This …
=> [Against another PR] Add NPFG unit tests 

src/drivers/barometer/bmp581/bmp581.cpp, src/drivers/barometer/bmp581/bmp581.h
In forced mode, the I2C interface requires longer intervals for proper data reading, whereas using extended intervals with the SPI interface may lead to altitude anomalies. This issue can be resolved by switching to normal mode for data acquisition.
=> BMP581: Collect data using normal mode

docs/en/dev_setup/building_px4.md, docs/en/dev_setup/dev_env_linux_ubuntu.md, docs/en/dev_setup/vscode.md, docs/en/sim_gazebo_classic/index.md
PX4 is now working to a model of supporting the current and previous Ubuntu LTS builds: Ubuntu 24.02 and 22.02. We're also working towards Gazebo feature parity with Gazebo-Classic, after which the Classic version will be dropped.
This updates the toolchain installation, build and Gazebo-Classic docs to refer to the new supported OS versions. The Gazebo-Classic is also "deprioritized" in a number of ways - specifically the instructions are "Gazebo first", and the Gazebo-Classic instructions are very much "if you want to do something special then-ish".
Comes out of discussion https://discord.com/channels/1022170275984457759/1357170977582088223
> [!NOTE]
> When Gazebo Classic support is dropped or about to drop a lot more will need to be done. Specifically Gazebo classic is used in a lot of …
=> Ubuntu Versions update and Gazebo Classic deprioritisation

msg/LongitudinalControlLimits.msg, src/lib/fw_performance_model/PerformanceModel.cpp, src/lib/fw_performance_model/PerformanceModel.hpp, src/lib/fw_performance_model/performance_model_params.c, src/lib/npfg/CMakeLists.txt, src/lib/npfg/CourseToAirspeedRefMapper.cpp, src/lib/npfg/CourseToAirspeedRefMapper.hpp, src/lib/npfg/NpfgTest.cpp, src/modules/fw_att_control/FixedwingAttitudeControl.hpp, src/modules/fw_lateral_longitudinal_control/FwLateralLongitudinalControl.cpp, src/modules/fw_lateral_longitudinal_control/FwLateralLongitudinalControl.hpp, src/modules/fw_pos_control/ControlLimitsHandler.cpp, src/modules/fw_pos_control/ControlLimitsHandler.hpp, src/modules/fw_pos_control/FixedwingPositionControl.cpp, src/modules/fw_pos_control/FixedwingPositionControl.hpp
- airspeed handing split up between FW Position Control and LatLong Control
- both modules need performance model
- airspeed constraints are a bit awkward (e.g. not clear if they should override FW_AIRSPD_MIN/MAX or not), and unclear if they later then should be load_factor and weight adapted
- no min ground speed/ course feasibility handling
- FW Pos/LatLong Control: move airspeed handling to LatLongControl
- only optionally set airspeed setpoint in FWPosControl (through mission item or
in takeoff/landing modes)
- LatLongLimits: remove min/max airspeed limits (to be replaced with flap-based scaling)
- remove performance model form FWPosControl
- CourseToAirspeed: bring back option to increase airspeed to achieve bearing
- perfromance model: add FW_AIRSPD_FLP_SC option to reduce speed …
=> [against other PR] Move airspeed handling to FWLatLongControl and simplify

src/modules/land_detector/FixedwingLandDetector.cpp, src/modules/land_detector/land_detector_params_fw.c
Fixes [failed auto takeoff due to landed being false when started](https://discord.com/channels/1022170275984457759/1359063688958709862/1359473484555882506)
Takeoff is triggering easily if the plane is lifted prior to takeoff (hand-launch), and can cause issues for the auto takeoff state machine.
The rotational speed threshold on fixed-wing vehicles was added in https://github.com/PX4/PX4-Autopilot/pull/24133 with the intention to make it less error prone for airspeed-less vehicles to declare "land detected" due to invalid ground speed measurement (basically the land detector jumping to "landed" the instant you lose GPS e.g.).
What we didn't fully grasp in this moment was that a hand-launched vehicle will have a premature "takeoff detected" with that change, as when you hold the plane the …
=> FW land detector: only use LNDFW_ROT_MAX if speeds are not valid

src/modules/vtol_att_control/vtol_att_control_main.cpp, src/modules/vtol_att_control/vtol_att_control_main.h
Specific ADP ESCs lost communication when switching from MC -> FW in case of using DSHOT150. When switching back from FW -> MC the motors would still not spin.
The communication loss is due to incorrect DSHOT messages on the wire. As can be seen multiple DSHOT frames got packed into one large stream:
The cause of this is that a DSHOT transmission is started while an old one was still in progress. This occured only on DSHOT150 as the other ones are quick enough for this to not happen. The reason for this is a extremly fast scheduling of the DSHOT driver:
All this could be traced back to `vtol_att_control` being called too often due to it having configured 4 topic callbacks which are triggered by `MulticopterRateControl` and `FixedwingRateControl` which are triggered by an update of …
=> vtol: reduce schedule frequency, which causes DSHOT150 problems

docs/en/assembly/cable_wiring.md
Change CS! to CS1 in cable_wiring
Fixed a typo in cable wiring documentation
=> Fix typo in SPI signal table

src/modules/ekf2/EKF/output_predictor/output_predictor.cpp
I got the report that if you leave the yaw stick centered and hence absolute yaw locked but give cyclic roll, pitch input the vehicle drifts in yaw. And I verified this to be true e.g. you can fly in Position or Altitude mode with default settings and at the right rate of roll and pitch cyclic input you can turn the drone 360° in yaw relatively easily which is undesired.
After a quick discussion with @bresch he already told me that it's likely because of the way the unaided yaw is not calculated accurately enough and hence the yaw lock is constantly reset because the high-pass filter of difference between yaw state and unaided yaw change quickly.
```
Fix: cyclic roll and pitch input causes yaw drift on multicopters
```
- Tested extensively in SITL SIH simulation to verify the improvement …
=> Fix: cyclic roll and pitch input causes yaw drift on multicopters

docs/en/advanced_config/parameter_reference.md, src/modules/mc_att_control/mc_att_control.hpp, src/modules/mc_att_control/mc_att_control_main.cpp, src/modules/mc_pos_control/multicopter_position_control_params.c, src/modules/mc_pos_control/multicopter_stabilized_mode_params.c
Throttle curve rescaling using the Hover Thrust Estimator (HTE) causes throttle jumps, making the throttle response unpredictable for the pilot (see #24654).
A slew rate will be applied to the hover thrust used for throttle scaling. This will allow the hover throttle to gradually adjust towards the estimated value, improving predictability for the pilot.
@bresch @MaEtUgR
=> Make hover throttle more predictable in mc-stabilized mode

src/modules/mc_att_control/mc_att_control_main.cpp
When working on https://github.com/PX4/PX4-Autopilot/pull/24710 together with @dawr68 I added some suggestions and admittedly did this mistake which was apparently not found in review. It doesn't blow things up because the vehicle status is also regularly updated but it's of course completely wrong and hence worst a separate pr to fix.
See https://github.com/PX4/PX4-Autopilot/pull/24710/files#r2054448109
Updating the hover thrust estimate should be dependent on the correct topic's update.
I just found this while following up on reducing the parameter options like we discussed in the dev call. So it's purely based on reading the code again.
=> mc_att_control_main: fix check for hover thrust estimate update

boards/auterion/fmu-v6s/init/rc.board_mavlink
We accidentally started a mavlink connection on the external UART, which should instead be configurable by parameters.
- Tested on FMUv6s
=> [boards] Do not start Mavlink on external connector by default

src/modules/fw_mode_manager/ControllerConfigurationHandler.cpp, src/modules/fw_mode_manager/ControllerConfigurationHandler.hpp, src/modules/fw_mode_manager/FixedWingModeManager.cpp
- after an external mode has been running, publish immediately after taking over
- don't publish when we are not in control, e.g. when in hover mode
=> FixedWingModeManager: Fix configuration handler corner cases

src/modules/commander/failsafe/failsafe.cpp
[COM_POSCTL_NAVL](https://docs.px4.io/main/en/advanced_config/parameter_reference.html#COM_POSCTL_NAVL) decides which mode to fall back to upon navigation loss. Navigation loss can be caused eg by stopping the gps module in the MAVLink console. The if statement only catches Position mode, so when flying in Position Slow mode, the fallback is not the mode specified by COM_POSCTL_NAVL (Altitude mode by default) but Descend.
Also trigger the if statement when in Position Slow mode.
Tested fix with SIH on Freefly Systems Astro. Triggered navigation loss by setting EKF2_GPS_CTRL to 0.
=> fix: use COM_POSCTL_NAVL failsafe action for Position Slow mode too

docs/en/camera/camera_architecture.md, docs/en/camera/mavlink_v2_camera.md, docs/ko/camera/camera_architecture.md, docs/ko/camera/mavlink_v2_camera.md, docs/uk/camera/camera_architecture.md, docs/uk/camera/mavlink_v2_camera.md, docs/zh/camera/camera_architecture.md, docs/zh/camera/mavlink_v2_camera.md, src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp, src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.hpp, src/modules/mc_pos_control/multicopter_takeoff_land_params.c, src/modules/navigator/land.cpp, src/modules/navigator/mission_base.cpp, src/modules/navigator/mission_block.cpp, src/modules/navigator/navigator.h, src/modules/navigator/navigator_main.cpp
While looking into what would be necessary to command the gimbal back to neutral automatically very close to ground I found that the internal interface for that is not as straight forward as I hoped and instead it's necessary to go through a complicated MAVLink protocol dance in every spot within PX4 that wants to do that.
As part of studying that I came across these pieces which I really at least want to refactor for clarity to enable further improvements.
- Flight Task Auto crawl speed is not compliant with the parameter naming convention (1. commit)
- More clear `MPC_LAND_ALT3` parameter description
- Make navigator function `publish_vehicle_cmd` consume a reference instead of a pointer and rename it to `publish_vehicle_command`.
- Follow convention to name messages to publish …
=> Cleanup: Navigator: Vehicle command refactor, FlightTaskAuto: parameter clarification

src/modules/commander/HealthAndArmingChecks/checks/geofenceCheck.cpp
Geofence breaching messages had been overrunning length of STATUSTEXT.text by a few characters. This may in some events lead to invalid character being displayed in GCS.
-  Geofence vionaliton notification popup typo
```
Shortening geofence viloation messages to fit STATUSTEXT.text field.
```
=> [fix]reducing length of Geofence vilations to prevent STATUSTEXT message length overrun

src/modules/fw_rate_control/FixedwingRateControl.cpp
Crash due to bad `TRIM_PITCH` value resulting in torque offset that the rate controller is not able to compensate for.
E.g. `TRIM_PITCH` set to -0.15 but plane actually not needing any trim. If the airspeed is 2x the trim airspeed, the controller output is scale by *1/4, while the `TRIM_PITCH` is fully applied still. So e.g. a commanded pitch up torque of 0.6 (default integrator limit) is scaled down to 0.15, which is then offset to 0 by the `TRIM_PITCH`. 
The trimming needs to be scaled by airspeed, the same way as the controller output is scaled.
```
Bugfix: FW Rate Controller: scale static trim offsets with airspeed
```
=> FW Rate Controller: scale static trim offsets with airspeed

.github/workflows/docs_deploy.yml, docs/.vitepress/theme/index.js, docs/en/index.md
The docs are built and then previously the the rebuilt tree was added as a commit to the main branch of  https://github.com/PX4/docs.px4.io. This grows the main branch each time which makes the build longer. Further in several cases the build has failed and we've had to revert to significantly older builds.
What this does is 
- make the docs update always create a new deployment branch as a backup
- make the main branch only one commit deep.
- add a build date stamp at bottom of front page we can use to find actual last build time.
This should make build times more predictable, and easier to revert to a backup if needed.
=> docs_deploy.yml - update to create backup and always be single release

ROMFS/px4fmu_common/init.d-posix/px4-rc.gzsim, src/modules/simulation/gz_bridge/GZBridge.cpp, src/modules/simulation/gz_bridge/GZBridge.hpp, src/modules/simulation/gz_plugins/gstreamer/GstCameraSystem.cpp
- print version number in init
- remove gst plugin spam
- refactor topic subscriptions
- fix 0 timestamp issue causing problems with EKF (wait for clock topic before subscribing to others)
=> gz small improvements

src/modules/ekf2/EKF/aid_sources/magnetometer/mag_control.cpp
If the drone takes-off without mag aiding (i.e.: no mag_hdg nor mag_3D), the sanity reset at 1.5m after takeoff is skipped. It occurred that the checks are then passing because the error is pushed into the mag states and the heading is then not correctly reset, causing a large toilet bowl.
Never skip the heading reset, even if mag (hdg or 3D) fusion only starts later in the flight.
Note that the logic starts to be a bit more complicated now and we might want to go through some cleanup again.
SITL tested
=> [EKF2] Never skip post-takeoff mag yaw reset

.github/workflows/build_all_targets.yml
This will make it so the big expensive "builds all" GitHub action won't allow multiple concurrent runs per pull request, it will cancel any prior runs if it detects that a new one was triggered. Saving us hundreds per month.
=> ci: avoid multiple builds with concurrency checks

src/drivers/pps_capture/pps_capture_params.c
When talking to @tobias-auterion about GPS configuration options I found that the description of `PPS_CAP_ENABLE` seems outdated. It mentions a fixed PWM pin which is not hardcoded anymore but can be configured.
I clarify the description taking example from https://github.com/PX4/PX4-Autopilot/pull/24368
```
Doc: Clarify `PPS_CAP_ENABLE` description
```
=> Doc: Clarify `PPS_CAP_ENABLE` description

src/lib/rtl/rtl_time_estimator.cpp, src/modules/land_detector/RoverLandDetector.cpp, src/modules/land_detector/RoverLandDetector.h, src/modules/navigator/rtl_direct.cpp, src/modules/navigator/rtl_direct.h, src/modules/navigator/rtl_mission_fast_reverse.cpp
1. All the states prior to `LAND` in the direct RTL state machine are unnecessary if the vehicle is of type `ROVER`.
2. The parameter used for RTL time calculation for rovers is outdated
3. In mission fast reverse there is a hanging `NEXT` waypoint.
4. Rover land detection only detects landing during RTL if the return point is home, which does not work if the vehicle is supposed to return to a rally point etc.
1. Direclty skip to `LAND` state on activation if the vehicle type is `ROVER`.
2. Replace with correct parameter `RO_SPEED_LIM`.
3. Reset the `NEXT` waypoint when landing starts.
4. During RTL check if the `NEXT` waypoint is invalid which indicates that the `CURRENT` waypoint is the final waypoint.
Set the vehicle to `LANDED` if the distance to the current waypoint is less than …
=> Rover: Update RTL behaviour and land detection

.github/workflows/build_all_targets.yml, .github/workflows/compile_ubuntu.yml, .github/workflows/dev_container.yml, Tools/ci/generate_board_targets_json.py, Tools/ci/package_build_artifacts.sh, Tools/docker_run.sh, Tools/setup/Dockerfile, Tools/setup/docker-entrypoint.sh, Tools/setup/ubuntu.sh, src/drivers/uavcan/libdronecan/libuavcan/src/transport/uc_frame.cpp
Use the px4-dev container to build and publish all targets
* builds x86, and arm64 px4-dev images
* conditional to changes in either **ubuntu.sh** or **requirements.txt**
* updates **ubuntu.sh** for installing under both architectures
* fixes a stringop-overflow issue with gcc > 12
* uses the px4-dev container to build the build matrix of all boards
=> ci: introduce px4-dev container with multi arch support

docs/crowdin_docs.yml
This fixes upload errors in the crowdin upload workflow
=> crowdin_docs.yml - ignore the param reference

msg/CellularStatus.msg
When discussing about message documentation in https://discordapp.com/channels/1022170275984457759/1354222673953030376/1354222677577044171 I found that there are plenty of bad examples so I picked one that's even somewhat debatable why we keep it in PX4 to just check how I'd improve the description without even knowing the exact was the message is used. This is just an example.
- enums have field name prefix and ar listed directly below
- enum option values have the type of the field
- for bit fields the individual flag's definition has the value to mask that bit
- fields that are defined as enum like `type` here actually have the options properly defined
- `FLAG_FAILED=1 # velocity setpoint` wtf?
- no dubious alignment attempts, one space to separate names, operators, comments
```
Fix …
```
=> Fix cellular_status message definition

ROMFS/px4fmu_common/init.d-posix/px4-rc.gzsim, docs/en/sim_gazebo_gz/multi_vehicle_simulation.md
Updates the documentation for launching multi vehicle simulation. Subsequent instances need to specify standalone mode since only the first instance should spawn the world.
=> docs: gz: update docs for multi vehicle simulation

src/modules/mavlink/mavlink_timesync.cpp
Previously the system clock was only set if the "offboard" timestamp was valid and the "onboard" timestamp was invalid. This usually is not the desired behavior, since your onboard time could be valid but just hours/days/weeks behind the actual time. A system that sends the SYSTEM_TIME message (eg companion computer application) will update the PX4 time if PX4 is behind by more than a minute.
=> mavlink: set system clock from SYSTEM_TIME 

msg/AckermannVelocitySetpoint.msg, msg/CMakeLists.txt, msg/MecanumVelocitySetpoint.msg, msg/RoverThrottleSetpoint.msg, msg/RoverVelocitySetpoint.msg, msg/RoverVelocityStatus.msg, src/modules/logger/logged_topics.cpp, src/modules/rover_ackermann/AckermannPosControl/AckermannPosControl.cpp, src/modules/rover_ackermann/AckermannPosControl/AckermannPosControl.hpp, src/modules/rover_ackermann/AckermannVelControl/AckermannVelControl.cpp, src/modules/rover_ackermann/AckermannVelControl/AckermannVelControl.hpp, src/modules/rover_differential/DifferentialPosControl/DifferentialPosControl.cpp, src/modules/rover_differential/DifferentialPosControl/DifferentialPosControl.hpp, src/modules/rover_differential/DifferentialVelControl/DifferentialVelControl.cpp, src/modules/rover_differential/DifferentialVelControl/DifferentialVelControl.hpp, src/modules/rover_mecanum/MecanumPosControl/MecanumPosControl.cpp, src/modules/rover_mecanum/MecanumPosControl/MecanumPosControl.hpp, src/modules/rover_mecanum/MecanumVelControl/MecanumVelControl.cpp, src/modules/rover_mecanum/MecanumVelControl/MecanumVelControl.hpp
This PR consist of 2 contributions:
1. Clean up the velocity/speed terminology for ackermann/differential rovers:
Defining the speed in body-x direction is tricky for these types of rovers, because during corning the velocity is not actually aligned with the body-x direction. Therefor, for control purposes we instead now use the absolute speed of the rover.
However, since the intend of `speed_body_x` is clear, we leave it for the `RoverThrottleSetpoint.msg` since this way it is easier to extend the message for mecanum rovers which actually require the differentiation in `body_x` and `body_y`.
Also removes some unused fields from `RoverVelocityStatus.msg`.
2. Clean up rover velocity setpoints:
Currently the 3 rover types have their own `[RoverType]VelocitySetpoint.msg`. This PR merges them …
=> Rover: Clean up velocity terminology and setpoints

src/drivers/power_monitor/ina226/ina226_params.c, src/drivers/power_monitor/ina228/ina228.cpp, src/drivers/power_monitor/ina228/ina228.h, src/drivers/power_monitor/ina228/ina228_params.c, src/drivers/power_monitor/ina238/ina238.cpp, src/drivers/power_monitor/ina238/ina238.h, src/drivers/power_monitor/ina238/ina238_params.c
It turns out that we set the ADC range incorrectly leading to the measured current being capped at a certain level as the ADC on the sensor saturates.
Instead, we need to set the range according to the formula given in the interface datasheet.
https://www.ti.com/lit/ds/symlink/ina228.pdf
https://www.ti.com/lit/ds/symlink/ina238.pdf
=> ina228/ina238: correctly set ADC range, and a few fixes

src/drivers/rc/Kconfig
This is just a typo in a kconfig - it refers to magnetometers not RC.
=> RC driver config Kconfig -typo

src/drivers/power_monitor/ina226/ina226_params.c, src/drivers/power_monitor/ina228/ina228.cpp, src/drivers/power_monitor/ina228/ina228.h, src/drivers/power_monitor/ina228/ina228_params.c, src/drivers/power_monitor/ina238/ina238.cpp, src/drivers/power_monitor/ina238/ina238.h, src/drivers/power_monitor/ina238/ina238_params.c
=> [BACKPORT v1.16] ina228/ina238: correctly set ADC range, and a few fixes

.github/workflows/dev_container.yml
trigger manual builds of the px4-dev container, you can set the tag via text input when dispatching
=> ci: build px4-dev containers on demand

docs/en/concept/events_interface.md
When reading the documentation I found that this formatting looks off:
I think this bullet point was accidentally declared as code and remove that part.
In VS code markdown preview this fixes the problem:
@hamishwillee While making this pr I saw that translations "ko" and "zh" have this page as well and thought about adjusting them even though this is likely autogenerated at a lower rate. But then I saw that the entire indentation and hence markdown formating is screwed up for these translations 😱 
This also shows in the real docs and makes it almost impossible to read because you can't follow the structure:
=> Fix events interface docs

Makefile, docs/public/middleware/index.html
The uorb graph work for docs was done in FMU v5 timeframes and has not been updated. This adds generation of graphs for 5x and 6x.
@bkueng @julianoes There are other targets such as the 6c, and the RT variant. What are the considerations here for publishing? I mean we could add other build targets, but what is useful for developers?
=> Docs: uorb graph gen for 5x and 6x

src/drivers/osd/msp_osd/msp_osd.cpp
**MSP_OSD Update to support displaying battery status in DJI O3 OSD**
When running the MSP_OSD updates made in PR#24695, the battery status in the DJI OSD remains at 0V. This can be seen in the following image.
- Re-add the original battery status message to msp_osd.cpp to send the original battery status message while retaining the additions made in PR#24695 
- After re-adding the original battery status, the total battery status voltage displays correctly as seen in the following image:
* Note: The gps coordinates display correctly. At the time of these photos it was just disconnected.
```
```
=> MSP_OSD Update: Add original battery status msg.

Tools/px4moduledoc/markdownout.py, Tools/px4moduledoc/srcparser.py, src/drivers/rc/crsf_rc/CrsfRc.cpp, src/drivers/rc/dsm_rc/DsmRc.cpp, src/drivers/rc/ghst_rc/GhstRc.cpp, src/drivers/rc/sbus_rc/SbusRc.cpp, src/drivers/rc_input/RCInput.cpp
This puts the RC modules into their own subcategory "radio_control" for docs
That should make them much easier to group and spot changes for. 
While here, I've also updated the parser to use Python f-strings, as they are easier to read, made the markdown more consistent with prettier output, and ordered the subcategories alphabetically in lists.
=> RC modules into their own category docs

src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.cpp, src/modules/flight_mode_manager/tasks/Auto/FlightTaskAuto.hpp, src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp, src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.hpp, src/modules/mc_pos_control/multicopter_autonomous_params.c
Currently, only a slew rate is applied to the yaw setpoint, which causes issues on highly responsive platforms (e.g., helicopters) due to steep changes in the yaw setpoint.
Smooth the yaw setpoint by limiting the yaw acceleration.
Applying an acceleration limit leads to more realistic yaw and yaw rate setpoints, enabling improved yaw tracking performance.
=> Smooth yaw in auto mode by limiting acceleration

src/modules/commander/HealthAndArmingChecks/checks/batteryCheck.cpp, src/modules/commander/failsafe/framework.cpp
When setting [`COM_LOW_BAT_ACT`](https://docs.px4.io/main/en/advanced_config/parameter_reference.html#COM_LOW_BAT_ACT) to "Warning", low battery message is still reported as an `ERROR` and logs show failsafe is activated: 
Small fix in reporting logic: 
- For low and critical battery, set logging level to `WARN` instead of `ERROR`. (Regardless of failsafe action) 
- Only report "Failsafe activated" when the failsafe action =! Warn. 
```
Bugfix: Fixed incorrect error severity and failsafe activation when COM_LOW_BAT_ACT is set to Warning.
```
- Simulation testing logs: 
1. [SITL Test with main branch](https://review.px4.io/plot_app?log=fb04ab03-792e-4125-ab60-558b59695401): 
2. [SITL Test with PR branch](https://review.px4.io/plot_app?log=28250e11-b8bc-4afb-8ffb-7b40f8f10 …
=> Fix error severity and failsafe activation when COM_LOW_BAT_ACT set to Warning

boards/px4/fmu-v5x/init/rc.board_defaults, boards/px4/fmu-v6x/init/rc.board_defaults
We debugged an issue where the F9P GPS was connected to the Skynode primary breakout board together with an airspeed sensor. On arming the external mag and airspeed sensors would fail quite often. We checked the voltage rails for overcurrent conditions and found that the voltage rails collapse when the tone_alarm was running the speaker inside the F9P GPS. We reproduced it with three different F9P GPS modules, and could not reproduce it when `tone_alarm` was stopped.
1. The buzzer is connected directly to the 5V rail `VDD_5V_CAN1_GPS1` with a limit of only 0.45A.
2. The buzzer is actived using a FET on the baseboard that pulls to GND with ~0.2A (it's a 1W speaker!!!).
3. The e-fuse fails to restart only while the buzzer is still active due to inrush currents.
4. The e-fuse restart pattern …
=> [board] Disable buzzer on Skynode base boards

src/lib/timesync/Timesync.cpp, src/lib/timesync/Timesync.hpp, src/modules/uxrce_dds_client/uxrce_dds_client.cpp
When doing a timesync over DDS with a remote system under high load, the log gets spammed by timesync converge / RTT too high messages.
This primarily happens due to:
- The RTT gets calculated on the FMU as (`now() - originate_timestamp`)
- When the load is high or a lot of packets are send, there can be a considerable delay until those packages leave the DDS agents queue and that time incorrectly gets calculated as high RTT
- The same applies to the offset calculation
- Using UART for DDS makes the situation even worse due to buffering / lower transmission speed
The timesync itself still works, it will only observe more high RTT messages and may converge / non coverge occasionally
The function `on_time` will always receive an `args` argument due to the setup: …
=> dds: clean up timesync

Tools/ci/check_msg_versioning.sh, msg/versioned/VehicleCommand.msg
This updates the docs in VehicleMessage uorb topic to match our current docs standard, as discussed in https://github.com/PX4/PX4-Autopilot/pull/24574#pullrequestreview-2738523071 . There is no semantic change - merging this should change nothing.
But, when we start fixing things, it should be easier to see the changes.
NOTE, it primarily updates the _existing_ docs. I haven't tried to add anything to this.
=> VehicleCommand.msg - update existing to docs standard

msg/CellularStatus.msg
We moved to having the units and other metadata before description. This moves them as discussed.
=> CellularStatus.msg - fix to standard

Tools/docker_run.sh
Updates the `docker_run.sh` script to use the latest `px4-dev` development container. This new image is multi-platform, and will work with arm64 and amd64 platforms.
😇 macOS users rejoice!
=> tools: update docker_run.sh to use px4-dev

ROMFS/px4fmu_common/init.d-posix/rcS
When working on DDS configuration I found that PX4_UXRCE_DDS_NS is only used to override the namespace when not empty. But there are cases where an empty override is required (when setting an instance id but still want an empty namespace, e.g.).
- Add logic for PX4_UXRCE_DDS_NS being set but empty too.
```
Feature: Allow DDS namespece override with empty/default namespace 
```
- Simulation testing
=> feat: allow PX4_UXRCE_DDS_NS override with empty sting

src/drivers/osd/msp_osd/msp_defines.h, src/drivers/osd/msp_osd/uorb_to_msp.cpp
- In `mps_ods` the string used to store the number of satellites only had two chars, therefore only one digit was printed (last char needs to be `\0`).
- In `mps_ods` the strings used to store the number of satellites and the roll/pitch values where not cleared before writing. Because the entire buffer is sent to the VTX and che logic does not stop at the `\0` added by the `snprintf` functions, trailing random values in the buffer end up being displayed.
- Increase array size for number of satellites to 3.
- Clear the character buffers for number of satellites and the roll/pitch structures before writing them.
```
NONE
```
Instead of fixed lenght buffer structures, dynamic ones could be used across the entire driver
- Tested on Walksnail vtx and …
=> fix (msp_ods): clear buffers before writing and adjust sizes

src/modules/sensors/vehicle_air_data/VehicleAirData.cpp, src/modules/sensors/vehicle_air_data/VehicleAirData.hpp, src/modules/sensors/vehicle_air_data/params.c
Account for baro offset between GNSS heigth and baro height from very beginning. Store it as offset, since its not a bias but a "fixed" value from the start.
When vehicle is still on the ground, GNSS-height gets fused and GNSS is selected as the height reference (EKF2_HGT_REF) then the baro pressure offset gets adjusted to match the GNSS height.
Tested on hardware
=> Baro offset calibration based on GNSS height

src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/commander/commander_params.c
If [`COM_HOME_EN`](https://docs.px4.io/main/en/advanced_config/parameter_reference.html#COM_HOME_EN) is enabled, the home position will reset when landed. 
However, during mission execution, we want to prevent the home position from resetting if an intermediate landing occurs. Instead, the home position should remain fixed at the one set at the beginning of the mission.
- Check whether the vehicle is still executing a mission before updating home position
**To have multiple takeoff items in a mission:** I found [that this feasibility check](https://github.com/PX4/PX4-Autopilot/blob/main/src/modules/navigator/MissionFeasibility/FeasibilityChecker.cpp#L336-L341) fails and prevents you from uploading the mission. Commenting it out works for now, but is probably not a very robust solution. …
=> Commander: don't reset home position if landed during a mission

src/modules/ekf2/CMakeLists.txt, src/modules/ekf2/EKF/CMakeLists.txt, src/modules/ekf2/EKF/aid_sources/gnss/gnss_checks.cpp, src/modules/ekf2/EKF/aid_sources/gnss/gnss_checks.hpp, src/modules/ekf2/EKF/aid_sources/gnss/gnss_height_control.cpp, src/modules/ekf2/EKF/aid_sources/gnss/gnss_yaw_control.cpp, src/modules/ekf2/EKF/aid_sources/gnss/gps_checks.cpp, src/modules/ekf2/EKF/aid_sources/gnss/gps_control.cpp, src/modules/ekf2/EKF/common.h, src/modules/ekf2/EKF/ekf.cpp, src/modules/ekf2/EKF/ekf.h, src/modules/ekf2/EKF/estimator_interface.h
NOTE: easier to review commit-by-commit
I wanted to add something to the checks but let's do a bit of cleanup first.
- Scope all GNSS checks variables into a class
- Simplify names (since they are scoped in `GnssChecks`, prefixes are not needed)
- Slightly restructure to allow upcoming changes (see https://github.com/PX4/PX4-Autopilot/pull/24909)
unit tests
=> [EKF2] Move GNSS checks to their own class

src/modules/ekf2/EKF/estimator_interface.h, src/modules/ekf2/EKF/output_predictor/output_predictor.cpp, src/modules/ekf2/EKF/output_predictor/output_predictor.h, src/modules/ekf2/EKF2.cpp
External system using `vehicle_odometry` might want to use the `angular_velocity` field as a source of low-rate gyro data for another estimator. Currently, this signal is subject to aliasing as the last imu data is used to fill the message instead of properly down-sampling the gyro data.
Accumulate delta-angles between each publication to get the correct angular velocity between two attitudes. 
The resulting angular velocity is not the average of the gyro measurements, but the time derivative of shortest rotation (delta_angle) between two unaided attitudes. The angular velocity is bias-corrected (using the bias estimate of the EKF) but otherwise not directly affected by other aiding sources.
```
Bugfix: Avoid aliasing of angular vel in vehicle_odometry uORB topic
New …
```
=> Vehicle_odometry: protect angular_velocity field against aliasing

src/modules/commander/esc_calibration.cpp
Fixes #24401
Fixes #24645
Fixes #24639
I haven't been able to verify this since I can't seem to build a firmware on Mac arm. But I believe this fixes the problem. Hopefully someone else can verify. And then this needs to get into v1.16 as well however that happens.
=> Fix reporting of connected battery

src/modules/control_allocator/ControlAllocator.cpp, src/modules/control_allocator/ControlAllocator.hpp
backport of #24955 fixes #24230
=> [backport] Control Allocation: only run on torque setpoint, not thrust

src/modules/airship_att_control/airship_att_control_main.cpp, src/modules/fw_rate_control/FixedwingRateControl.cpp, src/modules/fw_rate_control/FixedwingRateControl.hpp, src/modules/mc_rate_control/MulticopterRateControl.cpp, src/modules/mc_rate_control/MulticopterRateControl.hpp, src/modules/vtol_att_control/vtol_att_control_main.cpp
I did not have the opportunity to review https://github.com/PX4/PX4-Autopilot/pull/24955 before it was merged. Even though the pr should work fine as is my remaining concern is that theoretically scheduling could get interleaved and the torque allocated with the previous thrust setpoint. In practise this is unlikely to cause problems because I would not expect scheduling on the work queues to get interleaved like this and also using the previous thrust setpoint should not produce any big issues. Still I'd like to keep it consistent and avoid any surprises.
Always publish the thrust setpoint before torque then the samples that were published together for sure get allocated together.
```
Make sure vehicle_thrust_setpoint is always published before vehicle_torque_setpoint
```
I have not …
=> Make sure vehicle_thrust_setpoint is always published before vehicle_torque_setpoint

src/modules/ekf2/EKF/aid_sources/gnss/gnss_checks.cpp, src/modules/ekf2/EKF/aid_sources/gnss/gnss_checks.hpp, src/modules/ekf2/test/test_EKF_gps.cpp
requires https://github.com/PX4/PX4-Autopilot/pull/24908
Thresholds of GNSS checks are supposed to be tight enough to make sure the drone starts with a good initial fix. However, currently, degradation of a single metric also stops the fusion (e.g.: high DOP) when other metrics are still good.
Add a "simplified" list of checks with large (arbitrary) thresholds. Those values can be discussed, but hopefully we can agree on a common value to avoid additional parameters.
```
Improvement: Simplified GNSS checks after initial fix 
```
unit tests
@haumarco flight tested
=> [EKF2] Run simplified GNSS checks after initial fix

src/modules/commander/Commander.cpp
Replaced the local variable landed_amid_mission with the class member _mission_in_progress for consistency and to reduce redundancy. No functional change.
=> commander: use existing class state to track mission progress

platforms/nuttx/src/px4/stm/stm32_common/dshot/dshot.c
**Problem**
RPM is off by a factor of 100. The scaling was incorrect.
**Solution**
To match Ardupilot and Betaflight
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_HAL_ChibiOS/RCOutput_bdshot.cpp#L848
https://github.com/betaflight/betaflight/blob/master/src/main/drivers/dshot.c#L190
=> dshot: fix scaling

docs/en/debug/system_wide_replay.md
Logging from boot is required for EKF Replay. Otherwise the produced results may not be the same.
=> docs: ekf replay: require log from boot

docs/en/middleware/uorb.md
Adds a section on the `ORB_QUEUE_LENGTH` "magic uorb constant" as discussed in https://github.com/PX4/PX4-Autopilot/pull/24843#discussion_r2120391591
=> Add ORB_QUEUE_LENGTH info

boards/3dr/ctrl-zero-h7-oem-revg/nuttx-config/scripts/script.ld, boards/3dr/ctrl-zero-h7-oem-revg/src/CMakeLists.txt, boards/3dr/ctrl-zero-h7-oem-revg/src/mtd.cpp
The MTD driver was unable to find the FRAM and mount the partition `/fs/mtd_params`, which prevented the user from saving and retrieving parameters. 
This PR solves issue #24925 
- Add a definition for the MTD driver
```
Fix: Adding MTD driver definition for 3DR Control Zero H7 OEM RevG
```
To check the legacy option, where the FRAM alone is defined in the absence of an MTD definition for a board (which is intended for custom definitions).
- Tested on hardware 
=> 3DR Control Zero H7 OEM RevG: MTD driver fix

msg/versioned/ActuatorMotors.msg
This fixes up the ActuatorMotors UORB topic to match the evolving doc standard (for similar, see #24662 , #24789).
- Single space for comments etc
- Sentence capitalize comments
- ~Enum values after the field that uses them~
- Uses the following markup
- `[<value>]` to mark units
- ~`[@enum <value>]` to mark allowed values~
- `[@range <minValue>,<maxValue>]` to mark ranges - inclusive
- ~`[@invalid <value>]` to mark the invalid/not-supplied value~
```
Fix actuator_motor message definition
```
See inline notes
=> ActuatorMotors.msg - uORB docs

msg/versioned/BatteryStatus.msg
This fixes up the BatteryStatus UORB topic to match the evolving doc standard (for similar, see #24662).
- Single space for comments etc
- Capitalize comments
- Enum values after the field that uses them
- Uses the following markup
- `[@enum <value>]` to mark allowed values
- `[<value>]` to mark units
- `[@range <minValue>,<maxValue>]` to mark ranges - inclusive
- `[@invalid <value>]` to mark the invalid/not-supplied value
```
Fix battery_status message definition
```
@MaEtUgR See inline notes
=> BatteryStatus.msg - docs update

src/modules/sensors/vehicle_angular_velocity/imu_gyro_parameters.c
Similar to https://github.com/PX4/PX4-Autopilot/pull/24968 we learned that on many lerger vehicles we had to slightly lower the angular acceleration cutoff which is the first order low pass filter applied to the state used for the derivative term of the PID rate controllers. It's there to avoid noise getting into the derivative term of the PID rate control loop on integration flights.
I suggest to lower from 30Hz to 20Hz. In huge vehicles that have severe low frequency vibrations we had to go as low as 10Hz, for small vehicles where vibrations are either very low or at a much higher frequency it can sometimes be increased to 60 or even 90Hz and allow for quicker attenuation.
```
Lower default angular acceleration filter cutoff from 30Hz to 20Hz
```
This setting is flown daily on many e.g. …
=> Lower default angular acceleration filter cutoff from 30Hz to 20Hz

src/drivers/distance_sensor/ll40ls_pwm/ll40ls.cpp
There are two lightware sensor modules, one for I2C/SPI and one for PWM.
- https://github.com/PX4/PX4-Autopilot/blob/main/src/drivers/distance_sensor/ll40ls/ll40ls.cpp#L63 - this is the I2C/SPI variant
- https://github.com/PX4/PX4-Autopilot/blob/main/src/drivers/distance_sensor/ll40ls_pwm/ll40ls.cpp#L153 - this is the PWM variant
They both have exactly the same name and category:
```
PRINT_MODULE_USAGE_NAME("ll40ls", "driver");
PRINT_MODULE_USAGE_SUBCATEGORY("distance_sensor");
```
This fixes the PWM variant to use the actual name of the module. This fixes errors in the docs build where all the module docs get mixed together.
Falls out of #24795
=> Update ll40ls.cpp - Fix module usage name to make unique 

ROMFS/CMakeLists.txt
fixes https://github.com/PX4/PX4-Autopilot/issues/20592
replaces https://github.com/PX4/PX4-Autopilot/pull/23158
**Problem**
The **rc.board_bootloader_upgrade** file was not getting generated because the build system tries to `configure_file()` before the `romfs_gen_root_dir` directory exists. 
**Solution**
Create a temporary copy of the file during configure and use a custom command to generate and update the file during build.
=> build: romf: fix generation of rc.board_bootloader_upgrade

src/drivers/gnss/septentrio/sbf/decoder.cpp
Follow-up to #25011
_message.header.length - 4 is passed as unsigned to the CRC method, so if _message.header.length < 4, the length wraps and causes invalid memory access.
This was found with fuzzing.
=> fix Septentrio memory bugs (2)

Tools/setup/requirements.txt
Needed for #24476 so the IDL parser can generate RIHS01 hashes
=> Add lark to python requirements for the rosidl parser

.github/workflows/ros_integration_tests.yml
This PR updates the rosdistro apt keys, and its a patch fix, the real fix is to update the container to include all of the dependencies, but that will have to come in a follow-up PR because its a lengthier process and will take more time
=> ci: update rosdistro apt keys

src/modules/mavlink/mavlink_mission.cpp, src/modules/mavlink/mavlink_mission.h
The message MISSION_CURRENT got extensions regarding mission state in https://github.com/mavlink/mavlink/pull/1869
This is an attempt to actually populate those fields.
Related to https://github.com/PX4/PX4-Autopilot/issues/24954 and https://github.com/PX4/PX4-Autopilot/pull/24946.
=> mavlink: implement extended MISSION_CURRENT

src/modules/commander/commander_params.c
Modified the description of the parameter COM_RC_LOSS_T to explicitly state that the timeout should not be set below the hardware capability. Otherwise, on limited hardware, a too low COM_RC_LOSS_T value may be smaller than the actual manual_control_setpoint update interval, thus triggering incorrect RC loss failsafe.
Fixes #25045
=> params: COM_RC_LOSS_T: clarify safe adjustment of RC loss timeout

src/drivers/magnetometer/bosch/bmm350/BMM350.cpp
When changing BMM350_ODR to a faster rate, self-test would fail on startup.
Turns out you've to wait atleast 6000us before doing self-test
NXP MR-Tropic board
@niklaut  I see that the FMU-V6S also has an BMM350, could you confirm if you've also have this issue? And that this fix solves it?
=> Bosch: BMM350: Fix self-test on high ODR rate

src/modules/ekf2/params_gnss.yaml
The description for EKF2_GPS_POS_X, Y, Z all refer to the Forward axis in the long description.
Note that I have referred to these as the Forward (roll), Right (pitch) and Down (yaw) axis. Not sure if this is correct - i.e. that you need roll/pitch/yaw.
=> EKF2_GPS_POS_X/Y/Z have same long description

docs/en/computer_vision/collision_prevention.md
Fixes #25053
Collision prevention only works with `MPC_POS_MODE` of acceleration based. THis adds the information.
@Claudio-Chies @dirksavage88 Let me know if there is anything else we missed.
=> [DOCS] Collision mode only works with mpc_pos_mode that is acceleration based

src/modules/commander/Commander.cpp, src/modules/commander/HomePosition.cpp, src/modules/commander/HomePosition.hpp, src/modules/commander/commander_params.c
When a drone takes off, its GNSS altitude might initially have a low uncertainty. However, as the drone ascends and can access more satellites, this position estimate often gets "corrected." This correction can cause the GNSS altitude reading to change significantly, even when the drone isn't physically moving vertically.
If the GNSS altitude is being used as the primary height reference, this sudden shift would incorrectly trigger the drone to move vertically in an attempt to maintain a constant GNSS altitude. This is problematic because the integrated GNSS velocity data does not exhibit the same behavior, indicating that the drone is not actually moving.
To address this, I've added a method that uses both the barometer and the integrated GNSS velocity to detect this GNSS "drift." We're …
=> Commander: adjust home position altitude after gnss altitude correction

docs/en/advanced_config/bootloader_update.md, docs/en/releases/main.md
Updates docs for the changes made in #25032
Specifically it explains how you tell if the bl update module is present, and how you can use it to update the bootloader. It also explains how you might enable the key in a config to enable it in a custom build.
The release note makes it clear this is a change, and the version it is present in.
=> [Docs] Update QGC Bootloader instructions

src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_main.h, src/modules/mavlink/mavlink_receiver.cpp
There was a race condition when closing the shell:
- the main thread checks if _mavlink_shell is not nullptr (which is true)
- the receiver thread closes the shell, which clears _mavlink_shell
- the main thread continues with _mavlink_shell->available()
Credits for finding this go to @xz0x
=> fix mavlink: add mutex for mavlink shell

docs/en/peripherals/dshot.md
- Remove mention of DShot1200
- Document Bidirectional DShot
=> docs: bidirectional dshot

docs/en/sensor_bus/i2c_general.md, docs/en/sensor_bus/translator_tfi2cadt.md
The docs pages related to I2C have obsolete links and descriptions.
Links were updated to the product documentation. The explanatory text was also updated. 
```
Docs: improve I2C wiring documentation and links
```
=> doc: Improve I2C devices links and explanation

ROMFS/px4fmu_common/init.d-posix/airframes/4011_gz_lawnmower
As the Rover controls kept changing, Lawnmower stopped working in Gazebo due to obsolete parameters settings.
I updated parameters and tested the rover in Gazebo (GZ)
The simulation can be run as follows:
```
make px4_sitl gz_lawnmower_lawn
or
make px4_sitl gz_lawnmower
```
In _QGroundControl_, upload any mission from this link and watch the rover execute missions:
https://github.com/slgrobotics/PX4-Autopilot/tree/dev/plans
**Note:** in my testing I observed that the velocity profile looks odd. The rover accelerates as it should to ~2.1 - 2.4 m/s, maintains that speed for about a third of the straight run, and then starts slowly decelerating for the rest 2/3rd of the leg.
I expected longer run with the set speed of 2.1 m/s, symmetrical deceleration. I couldn't find a combination of …
=> Update 4011_gz_lawnmower to match recent changes in Rover controls

.github/workflows/checks.yml, .github/workflows/clang-tidy.yml, .github/workflows/compile_macos.yml, .github/workflows/compile_ubuntu.yml, .github/workflows/ekf_functional_change_indicator.yml, .github/workflows/ekf_update_change_indicator.yml, .github/workflows/failsafe_sim.yml, .github/workflows/flash_analysis.yml, .github/workflows/itcm_check.yml, .github/workflows/mavros_mission_tests.yml, .github/workflows/mavros_offboard_tests.yml, .github/workflows/nuttx_env_config.yml, .github/workflows/python_checks.yml, .github/workflows/ros_translation_node.yml, .github/workflows/sitl_tests.yml
When we open a PR or push a commit to main (protected branch) certain workflows are skipped because they have '.github/**' in their paths-ignore.
If we want to label certain checks as _required_ we still want those tests to be started...
=> CI: remove .github paths-ignore in workflows

src/drivers/uavcan/Kconfig, src/drivers/uavcan/sensors/battery.cpp, src/drivers/uavcan/sensors/battery.hpp, src/drivers/uavcan/uavcan_params.c
Related to https://github.com/PX4/PX4-Autopilot/pull/24960 when trying to track the serial number of Tattu UAVCAN batteries, we found that they only provide this information in a separate `cuav::equipment::power::CBAT` message.
Closes #24088 
Add parsing for said message while stopping to pars the other UAVCAN battery information messages for any instance that provides CBAT because it contains a superset of the battery fields.
```
Support for CBAT uavcan message parsing
```
This kind of battery is the main way I'm testing the latest version of https://github.com/PX4/PX4-Autopilot/pull/24960#issue-3113730084 so please see there for results and screenshot.
=> Support for CBAT uavcan message parsing

msg/ManualControlSwitches.msg, src/modules/manual_control/ManualControl.cpp, src/modules/rc_update/RCUpdateTest.cpp, src/modules/rc_update/params.c, src/modules/rc_update/rc_update.cpp, src/modules/rc_update/rc_update.h
When I got asked how to support an RC 3-way-switch controlling the output power of a video transmitter e.g. 25mW, 200mW, 500mW I found that we had removed support to detect 3 states for switches except the mode switch in
https://github.com/PX4/PX4-Autopilot/commit/089c962d9208b3616ba505ab927fa399554035d4#diff-bc65e8936281291b7e9801b185ee1740a6f2d4207e3b539c059469daa6cdfcc9L527-L547
and there was a "payload power switch" added in
https://github.com/PX4/PX4-Autopilot/pull/23830/files#diff-bc65e8936281291b7e9801b185ee1740a6f2d4207e3b539c059469daa6cdfcc9R622-R625
I made the previously added payload power switch usable for other boards than ARK FPV, added the unit tests from
https://github.com/PX4/PX4-Autopilot/pull/21796/files#diff-d8e9502b8461830a414cb9f32098a0a7aaf5cb38e5f31dc37ea9e6bf43ae62 …
=> Make payload power usable on all boards optionally as a 3-way switch

src/modules/dataman/Kconfig, src/modules/navigator/Kconfig
The define CONFIG_NUM_MISSION_ITMES_SUPPORTED is used in dataman, not navigator, so this config variable needs to be moved to the dataman module, otherwise it breaks the build if navigator is not included in the build.
Follow up to https://github.com/PX4/PX4-Autopilot/pull/24252.
=> Move NUM_MISSION_ITEMS_SUPPORTED to dataman

ROMFS/px4fmu_common/init.d-posix/airframes/10041_sihsim_airplane
When flying the plane in SIH I realized the angular rate tracking was not so great
Tune the controllers (using https://github.com/Auterion/Flight_Control_Prototyping_Scripts/tree/master/autotune)
=> SIH-plane: tune angular rate controllers

src/drivers/cyphal/parameters.c, src/drivers/uavcan/uavcan_params.c
Updates links to http://uavcan.org in param docs to point at dronecan or opencyphal URLs.
This only changes documentation.
=> [Docs] Incorrect URLS for dronecan/cyphal in params

src/drivers/gnss/septentrio/septentrio.cpp, src/drivers/gnss/septentrio/septentrio.h, src/drivers/gps/gps.cpp
Follow up to: https://github.com/PX4/PX4-Autopilot/pull/25144
We dont want the driver to send any warnings regarding the spoofing state. This is all handled within the [estimatorChecks](https://github.com/PX4/PX4-Autopilot/blob/main/src/modules/commander/HealthAndArmingChecks/checks/estimatorCheck.cpp#L259-L273).
=> GNSS: Don't send 'spoofing' warnings form driver

.github/workflows/build_all_targets.yml, .github/workflows/checks.yml, .github/workflows/clang-tidy.yml, .github/workflows/compile_macos.yml, .github/workflows/compile_ubuntu.yml, .github/workflows/dev_container.yml, .github/workflows/docs_deploy.yml, .github/workflows/ekf_functional_change_indicator.yml, .github/workflows/failsafe_sim.yml, .github/workflows/flash_analysis.yml, .github/workflows/itcm_check.yml, .github/workflows/mavros_mission_tests.yml, .github/workflows/mavros_offboard_tests.yml, .github/workflows/nuttx_env_config.yml, .github/workflows/python_checks.yml, .github/workflows/ros_integration_tests.yml, .github/workflows/ros_translation_node.yml, .github/workflows/sitl_tests.yml, CMakeLists.txt, Makefile, ROMFS/px4fmu_common/init.d/rcS, Tools/serial/rc.serial_port.jinja, cmake/coverage.cmake
few commits to update CI throughout
* Single asterisk ('*') won't work for '**release/v1.16**' branches, updating to double asterisk fixes this
* Cancel concurrent jobs to save on computing time
* Enable workflows on changes to **.github/workflows** directory, otherwise it's hard to test changes on those files. Keeps the ignore path to workflows for push events.
* shellcheck fixes with updated compiler
* Fixes SC2268
* Fixes SC3014
* ignore lcov mismatch errors
* enable atomic profile updates for coverage builds
=> ci: use new container for checks workflow

src/modules/land_detector/FixedwingLandDetector.cpp
For catapult launch vehicles: Vehicle stays landed until whole launch sequence is through, instead of when acceleration is measured.
This has negative side effects:
- integrators stay locked while airborne
- Home position altitude gets updated to current altitude while already in-air
Switch to landed=false the moment the acceleration threshold is passed (launch detection != `AITING_FOR_LAUNCH`).
```
Bugfix: FW land detector: only force to landed if launch detection is WAITING_FOR_LAUNCH. Fixes: takeoff detection too late (which has effect on Home position altitude being set when already in air and integrators being locked when airborne).
```
=> FW land detector: only force to landed if launch detection is WAITING_FOR_LAUNCH

src/modules/mavlink/mavlink_main.h, src/modules/mavlink/mavlink_parameters.cpp, src/modules/mavlink/mavlink_parameters.h
During complete parameter fetching, [PARAM_VALUE](https://mavlink.io/en/messages/common.html#PARAM_VALUE) messages are sent from PX4 to the GCS at an unlimited rate. In case of a low-bandwidth link, such traffic can completely clog it causing high delays for other messages and requiring retransmission of many packets (further worsening the link status).
Add a new PX4 parameter `MAV_PRM_WAIT_S` that controls the delay between subsequent parameter transmissions. By default `MAV_PRM_WAIT_S=0` so that the default behaviour remains unchanged.
```
Feature/Bugfix Introduced MAV_PRM_WAIT_S to throttle parameter transmission 
New parameter: MAV_PRM_WAIT_S
```
=> mavlink_parameters: throttle MAVLink param transmission on low-bandwidth links

src/modules/commander/ModeUtil/mode_requirements.cpp
Noticed while working on https://github.com/PX4/PX4-Autopilot/pull/25083.
In https://github.com/PX4/PX4-Autopilot/pull/24280 we removed the dependency for FW vehicles on `vehicle_global_position` in Mission, Loiter and RTL, but seemed to have forgotten the takeoff modes. I'm handling the FW takeoff mode in https://github.com/PX4/PX4-Autopilot/pull/25083, and here just adapt the VTOL Takeoff separately.
When in the fixed-wing phase of the VTOL Takeoff we do not want to failsafe due to position inaccuracy and thus only require `local_position_relaxed`.
```
Improvement: Commander: for VTOL_Takeoff only require relaxed position if fixed-wing phase to not fail-safe due to position inaccuracy.
```
=> Commander: for VTOL_Takeoff only require relaxed position if fixed-wing phase

docs/.vitepress/config.mjs
Search engines seem to throw up random versions for our docs. It would generally be better if they found our latest version.
I understand the solution to this is to have docs point to their canonical version with a `head` link with `rel: "canonical"`. This attempts to add that to main - which would then propagate to later versions.
This will take a while to work because it only applies to vitepress - so v1.16 and v1.15 can take this, but maybe we'll have to wait before we can get v1.12 - 1.14 to disappear.
Fell out of this discussion https://discord.com/channels/1022170275984457759/1392008876077092924
=> Add cannonicalref support

src/modules/rover_ackermann/RoverAckermann.cpp, src/modules/rover_ackermann/RoverAckermann.hpp, src/modules/rover_differential/RoverDifferential.cpp, src/modules/rover_differential/RoverDifferential.hpp, src/modules/rover_mecanum/RoverMecanum.cpp, src/modules/rover_mecanum/RoverMecanum.hpp
Currently the rover modules generate setpoints based on the `vehicle_control_mode.msg` flags.
However, this can causes ambiguities if the rover is controlled via an external flight mode that uses the same control mode flags.
By basing the setpoint generation explicitly on PX4 internal flight modes, we eliminate this ambiguity.
=> Rover: base setpoint generation on nav_state

msg/versioned/HomePosition.msg, src/modules/commander/Commander.cpp, src/modules/commander/HomePosition.cpp, src/modules/commander/HomePosition.hpp, src/modules/mavlink/streams/HOME_POSITION.hpp
According to the mavlink spec we should be publishing the home attitude as a quaternion rather than just the yaw/heading.
Additionally, this allows setting the landing roll and pitch angle using DO_SET_HOME (this yet needs to go into the MAVLink spec though).
This is marked as draft for now because it depends on the outcome of the discussion of the MAVLink spec change: https://github.com/mavlink/mavlink/pull/1843
=> commander/mavlink: use home attitude, not only yaw

src/modules/mavlink/mavlink_mission.cpp, src/modules/mavlink/mavlink_mission.h
1. `mavlink_mission.cpp` checks for an updated `MissionResult` message twice in a row. As there is no new message on the second check, the `_mission_state` field isn't populated properly. 
2. `_mission_state` switches from `MISSION_STATE_ACTIVE` to `MISSION_STATE_NOT_STARTED` for cases in which the vehicle disarms mid mission (for example: delivery missions with multiple landings).  
1. Switch from Subscription to SubscriptionData so we can do a `.get()` operation on the latest message struct.   
2. Remove the armed requirement for a mission to be active, and robusity the conditional for `MISSION_STATE_NOT_STARTED` to be met. 
=> MAVLink streaming: report mission state with MISSION_CURRENT MAVLink message

src/drivers/distance_sensor/broadcom/afbrs50/AFBRS50.cpp, src/drivers/distance_sensor/broadcom/afbrs50/AFBRS50.hpp, src/drivers/distance_sensor/broadcom/afbrs50/API/Src/s2pi.cpp
The sensor will switch between Short and Long range modes depending on the distance. When I rewrote parts of this driver in https://github.com/PX4/PX4-Autopilot/pull/24837 I switched from manual triggering in the state machine to continuous triggering via an hrt. This can interfere with the range mode switching and cause it to fail
Changed state machine to be trigger/collect and reschedule based on the max update interval. I did notice there is some jitter and sometimes the sensor isn't ready, or reports that it is ready and fails to trigger a measurement. I removed the PX4_WARN for this and instead we can track it with the perf counters. It doesn't seem to impact the sensors operation.
```
afbr: fix Range Mode switching by switching to manually triggered state machine …
```
=> [bug] AFBRS40: fix Range Mode switching

Tools/astyle/check_code_style_all.sh
On Ubuntu 25.04 `GNU bash, version 5.2.37(1)-release (x86_64-pc-linux-gnu)` when I run `make format` I get the following error: `PX4-Autopilot/Tools/astyle/check_code_style_all.sh: line 46: [: too many arguments`
Honestly I asked GPT to fix the bash syntax based on the error and it suggested the structure in this pull request which I have tested to work. So a critical pair of reviewing eyes is welcome.
```
stylecheck script: improve bash condition to avoid error with newer terminal versions
```
I have no error anymore and the command fixes my style mistakes efficiently.
=> stylecheck script: improve bash condition to avoid error with newer terminal versions

src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp, src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.hpp
I got contacted that the 10m/s harcoded limit for orbit is too low for certain use cases e.g. one that requires 18m/s presumably for a larger circle. I followed the advice of @sfuhrer and made the limit dependent on the maximum velocity allowed by the multicopter configuration.
Instead of hardcoded 10m/s limit the maximum velocity for multicopter orbit by `MPC_XY_VEL_MAX`.
```
Multicopter Orbit: replace hardcoded 10m/s maximum speed with multicopter speed configuration
```
I tested using SITL SIH (`make px4_sitl sihsim_quadx`) of which to my surprise the model maxes out at ~10m/s but lowering `MPC_XY_VEL_MAX` correctly limits the velocity so the implementation works.
Note that there is still a hardcoded limit for 2m/s² maximum centripetal acceleration which means with smaller radius the …
=> Multicopter Orbit: replace hardcoded 10m/s maximum speed with multicopter speed configuration

src/modules/mavlink/mavlink_main.cpp
Mavlink module is missing the logic for handling the `low_bandwidth` MAVLink mode introduced by https://github.com/PX4/PX4-Autopilot/pull/24328
- SITL tested
=> mavlink_main: add  profile handling

docs/en/dev_airframes/adding_a_new_frame.md
THe PR #22813 added support for forcing parameter reset when an airframe is updated.
This attempts to capture the information.
=> [Docs] Airframe param reset on update

ROMFS/px4fmu_common/init.d-posix/airframes/10045_sihsim_rover_ackermann, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt, src/modules/simulation/simulator_sih/CMakeLists.txt, src/modules/simulation/simulator_sih/sih.cpp, src/modules/simulation/simulator_sih/sih.hpp, src/modules/simulation/simulator_sih/sih_params.c
Add SIH dynamics and airframe for ackermann rover.
The lateral dynamics are based on: https://srianumakonda.medium.com/everything-you-need-to-know-about-self-driving-in-30-minutes-b38d68bd3427
Tested with SIH as SITL ([Flight log](https://review.px4.io/plot_app?log=391beaad-1cbb-45db-9f5e-25e374757151))
=> ackermann: add SIH

src/modules/mc_pos_control/GotoControl/GotoControl.cpp, src/modules/mc_pos_control/GotoControl/GotoControl.hpp, src/modules/mc_pos_control/MulticopterPositionControl.cpp
Previously, when switching from a goto setpoint into a mode that publishes trajectory_setpoint, the previous goto setpoint was still used for 500ms, which then caused a setpoint jump.
This change makes sure that when a trajectory_setpoint is received, any existing goto setpoint is marked as invalid immediately.
Tested in SITL and on a quad.
Before:
https://logs.px4.io/plot_app?log=f52fe94d-087d-489c-8ab9-412cd32c63c5
After:
https://logs.px4.io/plot_app?log=f09140a0-3ada-4e65-817c-a3d6189c8c72
=> mc_pos_control: immediately switch out of goto setpoint when receiving trajectory_setpoint

src/modules/ekf2/EKF/aid_sources/aux_global_position/aux_global_position.cpp
Auxiliary Global Position (AGP) fusion control logic uses a different reset timeout than GNSS control, while being a really similar aid source. There is no reason for this.
Note that optical flow uses `no_aid_timeout_max` (1s) in case the EKF is doing inertial dead-reckoning.
Use `reset_timeout_max` as in [GNSS control](https://github.com/PX4/PX4-Autopilot/blob/84cdc051959135ec5cbf25001be69d562c302ff5/src/modules/ekf2/EKF/aid_sources/gnss/gps_control.cpp#L366-L367)
flight tested
=> ekf-agp: use same timeout value as other aid sources

src/modules/ekf2/EKF/position_fusion.cpp
When CONFIG_EKF2_RANGE_FINDER is not set, compilation fails due to 
`error: no declaration matches 'void Ekf::updateTerrainResetStatus(float)'`
The issue is that the method is declared under `#if defined(CONFIG_EKF2_TERRAIN)` but the definition is always present.
Add the `#if defined(CONFIG_EKF2_TERRAIN)` check for the method definition
=> EKF: fix compilation error when CONFIG_EKF2_TERRAIN is not defined

src/modules/mavlink/mavlink_mission.cpp
Improve mission state determination by explicitly checking mission_result.valid
in addition to the mission count. This makes the state machine more robust
in cases where mission_result may be uninitialized or temporarily invalid.
```
Feature/Bugfix Improve mission_state handling with mission_result validity check
```
=> mavlink_mission: Check mission_result.valid in mission_state handling

Tools/boot_now.py, Tools/compress.py, Tools/fetch_file.py, Tools/geotag_images_ulog.py, Tools/package_firmware.py, Tools/parameter_update.py, Tools/process_sensor_caldata.py, Tools/px4.py, Tools/px_mkfw.py, Tools/px_process_airframes.py, Tools/px_process_events.py, Tools/px_process_module_doc.py, Tools/px_romfs_pruner.py, Tools/run-clang-tidy.py, Tools/uorb_graph/create.py, Tools/validate_yaml.py
There are a variety of different shebangs in the Tools python files. 
- Update shebangs to python3
- Tested running many of the python scripts. Many of the python scripts can now be run directly (i.e. `./Tools/px4.py` instead of `python3 Tools/px4.py`). There are no algorithmic changes to the scripts.
=> Update tools shebangs to python3

docs/en/dev_setup/dev_env_windows_wsl.md
It said it was not possible to expose the USB inside WSL. However with USBIPD-WIN project it is possible. I installed and testing it and it seems to work fine. 
I can also write the steps inside the docs itself instead of linking to the project page if thats prefered instead. :)
=> Rewrote info about USB inside wsl

src/modules/ekf2/EKF2.cpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h
In hardware in the loop simulation, the battery voltage was hard coded. This triggers errors on our system.
The remaining value is still hard coded but the voltage is update using the battery configuration parameters so it depends on the custom configuration.
It allow us to have a simulated battery voltage depending of our airframe and corresponding to our system.
=> HITL/SIH: Battery status depend on battery configuration from parameters

msg/Airspeed.msg
This updates the Airspeed msg to our docs standard. 
@sfuhrer @MaEtUgR For you!
=> [Docs] msg/Airspeed.msg - to standard

src/drivers/px4io/px4io.cpp
I had two different flights where after loss of RC, and regain the vehicle switched from MISSION to HOLD, as there was some garbled data coming in on the SBUS.
Flight 1
Flight 2
I added a check in `io_publish_raw_rc` to only publish input_rc when on the io, the status flag for for the rc is set to OK
Open for input / opinions
As i'm unable to reliably reproduce the issue, i was currently unable to test it.
=> PX4IO | only publish input_rc, if the IO RC status in ok

docs/en/advanced_config/flight_termination.md
This improves the docs for Flight termination. I wanted to:
- Make it "instantly" clear that flight termination permanently shuts off controllers, sets outputs to failsafe values.
- Differs from kill (with link)
- Better highlight the triggers and results.
- Section for external activation. Currently says mavlink, but presumably we can update to uorb at some point.
Essentially adds structure.
Follows on from #25253
=> Improve flight termination docs

src/drivers/gps/gps.cpp, src/drivers/gps/params.c
* Some UBX modules have a FLASH that allows to store persistent configuration that will be loaded on start.
* PX4 does override all configuration parameters it needs in RAM, which takes precedence over the values in FLASH.
* However, configuration parameters that are not overriden by PX4 can still cause unexpected problems during flight.
- To avoid these kind of problems a clean config can be reached by wiping the FLASH on boot.
- The message CFG-CFG is not deprecated for this use-case, was confirmed by u-blox support
- Will rebase this as soon as https://github.com/PX4/PX4-GPSDrivers/pull/183 is merged
```
Feature/Bugfix: add option to wipe flash on u-blox
```
- Setting this to not always on has the disadvantage that users who forget to clean up their config will also …
=> ubx: add option to wipe flash

src/drivers/cdcacm_autostart/cdcacm_autostart_params.c
The low bandwdith mode is missing in the `cdcacm_autostart` params. This PR adds it.
=> cdcacm_autostart: add low bandwidth profile

src/modules/commander/failsafe/framework.cpp
The delay period (during which the vehicle is expected to hold/loiter before a failsafe action) is being unintentionally cleared, even when the failsafe is not deferred. As a result, the failsafe action is executed immediately, rather than after the intended delay.
Only clear hold delay when failsafes are being deferred, so that the delay action is still executed. 
```
Bugfix  Failsafe delay (hold/loiter) now works as expected before the failsafe action executes.
```
Tested in SITL:
=> [Fix] commander: only clear hold delay when failsafes are being deferred

msg/CMakeLists.txt, msg/versioned/Wind.msg
Was added as a default DDS topic recently, but I forgot to transition WInd to a versioned message. 
Add versioning to Wind.msg
```
Feature/Bugfix Add versioning to Wind.msg
```
=> msg: add Wind.msg to versioned messages

src/modules/ekf2/EKF/aid_sources/aux_global_position/aux_global_position.cpp, src/modules/ekf2/EKF/aid_sources/aux_global_position/aux_global_position.hpp, src/modules/ekf2/EKF/ekf.cpp, src/modules/ekf2/EKF2.cpp, src/modules/ekf2/params_aux_global_position.yaml, src/modules/flight_mode_manager/tasks/ManualAcceleration/FlightTaskManualAcceleration.cpp, src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.cpp, src/modules/flight_mode_manager/tasks/Utility/StickAccelerationXY.hpp
The EKF performs statistical consistency checks using normalized innovation tests. However, when the AGP measurement starts to fail a test, we directly reset to the measurement after a timeout period.
Add a "reset mode" parameter that tells the EKF whether it should always try to reset to the AGP position measurement when the statistical check fails or if the EKF is allowed to continue using solely velocity measurements.
New parameter: `EKF2_AGP_MODE`
- Automatic: reset on fusion timeout if no other source of position is available
- Dead-reckoning: reset on fusion timeout if no source of velocity is available
Additionally, the `VEHICLE_CMD_EXTERNAL_POSITION_ESTIMATE` is no longer filtered by the EKF2 front end. The command is sent and executed by the EKF as any other measurement. This …
=> EKF2: Aux Globlal Pos (AGP) reset mode

src/drivers/gnss/septentrio/septentrio.cpp, src/drivers/gnss/septentrio/septentrio.h, src/drivers/gps/gps.cpp, src/drivers/uavcan/sensors/gnss.cpp, src/drivers/uavcan/sensors/gnss.hpp
@cmic0 reported that it's not visible if and at what rate the RTCM injection works on GNSS receivers that are connected via UAVCAN.
I took example from the implementation in the ublox GPS driver and filled the two rtcm stream related telemtry fields:
https://github.com/PX4/PX4-Autopilot/blob/359cad3636d37931ae88a15745bf98cd475e12eb/src/drivers/gps/gps.cpp#L996-L1008
but I improved the variable naming. I'm happy to do so also in the other driver but wanted to keep the diff for this pr minimal. I'll open a separate one just for refactoring (**EDIT** here it is: https://github.com/PX4/PX4-Autopilot/pull/25316).
```
Publish RTCM stream telemetry also for UAVCAN GNSS receivers
```
I've not tested this myself. @ischollETH could you provide feedback from when it was used? :innocent:
=> Publish RTCM stream telemetry also for UAVCAN GNSS receivers

src/modules/logger/logged_topics.cpp
When working with drone setups that use 3 batteries, I found that the ulogs only list the data for 2 battery instances.
- Bump the max_num_instances value for the "battery_status" message to 4 instead of 2 so far.
- This is in line with the MAX_INSTANCES listed in the BatteryStatus Message here: https://github.com/PX4/PX4-Autopilot/blob/c9206d6bd1d0ec8c5f487024e7b8c6e2593d274f/msg/versioned/BatteryStatus.msg#L8
```
Improved logging: up to max. 4 battery status instead of 2
```
=> increase battery max logging instances

src/modules/mc_pos_control/MulticopterPositionControl.cpp, src/modules/mc_pos_control/MulticopterPositionControl.hpp
There is a race condition in PX4 that can result in an invalid setpoint during a failsafe event. Specifically, the Flight Mode Manager (FMM) and multicopter position controller can run before the Commander updates the nav_state in response to a failsafe (e.g., loss of manual control signal). For example when you: 
1. Start in Manual Position mode (nav_state = 2).
2. Lose manual control signal (e.g., RC link loss).
3. Before the Commander updates nav_state, the FMM and position controller execute assuming nav_state = 2.
4. Since manual input is no longer valid, the position controller generates an emergency failsafe setpoint (vx = vy = 0), which is not ideal if you are flying fast. 
- Add a timeout period in which the multicopter position controller that uses the last valid setpoint. After …
=> MC PositionControl: Add timeout for invalid TrajectorySetpoint

ROMFS/px4fmu_common/init.d-posix/px4-rc.gzsim
Update px4-rc.gzsim. Fix gz_world checking for PX4_GZ_STANDALONE=1 mode.  Priority of gz_world (really running) over PX4_GZ_WORLD
Currently in PX4_GZ_STANDALONE=1 mode script uses PX4_GZ_WORLD as true and does not see what world is really  runned. It leads to needing to adding PX4_GZ_WORLD=${PX4_GZ_WORLD:=default} with correct world name you planed to run. It is ok for NOT STANDALONE mode. But in STANDALONE it leads to double place for world configuring (airframe and same world in gazebo launcher). And you cant use any other world in Gazebo launcher (only same as in airframe).
I belive in PX4_GZ_STANDALONE script should attach to any really runned world (as it was in  PX4 v1.14 ).
I fix that with using really runned world attach to.
=> Update px4-rc.gzsim. Fix gz_world checking for PX4_GZ_STANDALONE=1

.editorconfig, .github/workflows/compile_macos.yml, Tools/setup/macos.sh
Try to use a newer toolchain for macOS (https://github.com/PX4/homebrew-px4/pull/93), and update missing dependencies from the formula. Cleaning up the `compile_macos.yml` GitHub Actions workflow.
=> Toos: Update macos dependencies

.github/workflows/ros_integration_tests.yml
Fixes the gazebo install for the ROS integration tests
=> [backport] v1.16 fix gazebo install on ROS integration tests

platforms/Kconfig
An earlier commit (https://github.com/PX4/PX4-Autopilot/commit/6474e5d7c1a752fe9d910dbd55aae2e30f751357) broke the VOXL 2 Posix and Qurt platform builds. This PR fixes the build issue.
=> Fixed Posix and Qurt platform build error introduced in earlier commit

platforms/common/include/px4_platform_common/defines.h, src/lib/matrix/matrix/Euler.hpp, src/lib/matrix/matrix/helper_functions.hpp, src/lib/matrix/test/MatrixAttitudeTest.cpp, src/lib/matrix/test/MatrixHelperTest.cpp, src/lib/matrix/test/MatrixUnwrapTest.cpp
A step towards sharing px4 libraries and reduce dependencies.
From [20458](https://github.com/PX4/PX4-Autopilot/pull/20458) it was known that not all math.h has math variables defined. However instead of defining a new variable name, one could just define `M_PI` if not defined.
=> Define M_PI if not defined in math.h

src/modules/mavlink/mavlink_main.cpp
The point of [PROTOCOL_VERSION](https://mavlink.io/en/messages/common.html#PROTOCOL_VERSION) is to indicate the maximum supported version of the protcol.
This is currently "3" in common.xml - https://github.com/mavlink/mavlink/blob/master/message_definitions/v1.0/common.xml#L4
This updates the max to match.
Note
1. It is disturbing that this number is hard coded rather than coming from MAVLink library - it will inevitably get out of sync.
2. In theory then the GCS should use a version no greater than 200, which would be very old. Clearly this isn't actually checked by anything because if it was, we'd have broken lots of things added since that release many years ago.
See:
- [Determining Protocol/Message Version](https://mavlink.io/en/guide/mavlink_version.html#determining-protocol-message- …
=> mavlink_main.cpp - PROTOCOL_VERSION to 203

boards/modalai/voxl2/target/voxl-px4-start
VOXL 2 relies on the parameter primary / remote architecture. The set default behavior was never updated to support that architecture so when it is done on the primary the remote doesn't see it. That will need to be fixed in a future PR. This PR offers a simple workaround to use for now until that is done as discussed in the 08/06/2025 developers call.
=> VOXL2: Updated startup script to patch EKF2_EV_CTRL set default

src/modules/airspeed_selector/airspeed_selector_params.c
The default is very low, leading to the ground-minus-wind airspeed approximation being declared invalid all the time.
Increase the default. And update the param meta data while on it.
I also consider removing the param and hard-code it. 
```
Improvement: AirspeedSelector: increase default of ASPD_WERR_THR to have ground-minus-wind airspeed approximation valid most 
```
I got to the new default of 2m/s by looking at a bunch of logs from different vehicles and different conditions. Screenshots attached below. We generally want to not yet validate it right after init (the variance was around 6 there usually), and when on very long straight flight paths (see second screenshot). 
The check is [here](https://github.com/PX4/PX4-Autopilot/blob/b8dacf5ae4323667915ff5633d771f38842 …
=> AirspeedSelector: increase default of ASPD_WERR_THR

src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_main.h, src/modules/mavlink/mavlink_parameters.cpp, src/modules/mavlink/mavlink_parameters.h, src/modules/mavlink/mavlink_receiver.cpp
GQC is hardly usable when parameters are not available. Due to that it is best if params are transmitted as fast as possible. On low bandwidth radios, there is not a lot of bandwidth available, so parameter transmission may be delayed due to other topics being transmitted.
- Reduce the rates of other topics as long as parameter transmission is active 
- Tested with a low bandwidth radio and a ARK v6x
=> mavlink: reduce rate multiplier to 0.25 while sending parameters

src/modules/ekf2/EKF/aid_sources/barometer/baro_height_control.cpp, src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp
This helps with plotting in plot juggler. I have a custom function which relies on the baro bias topic. If the topic is not present in the log the plot breaks.
=> ekf: always publish baro and gnss bias even if zero

ROMFS/px4fmu_common/init.d/airframes/1104_standard_ackermann_sih.hil, ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt
SIH support for ackermann rovers was added in https://github.com/PX4/PX4-Autopilot/pull/25194 but only with an airframe for SIH as SITL.
This PR adds an aiframe to run ackermann SIH on the flight controller.
To save flash in the default build, this aiframe is only added if the ackermann rover module is enabled (which is only enabled in the rover builds).
Tested mission mode on fmu v5x: https://review.px4.io/plot_app?log=63bfa0e4-99f2-4454-a2c0-3e317c0031c8
=> ackermann: add SIH airframe

msg/ActionRequest.msg, msg/Airspeed.msg, msg/CellularStatus.msg, msg/versioned/ActuatorMotors.msg, msg/versioned/ActuatorServos.msg, msg/versioned/ArmingCheckReply.msg, msg/versioned/ArmingCheckRequest.msg
In https://github.com/PX4/PX4-Autopilot/pull/25228#discussion_r2272259726 we discussed that the alignment of comments should be either 
- longest field/constant in file - add two spaces before comment and then align all other comments.
- longest field/constant in block- add two spaces before comment and then align all other comments in block.
I decided on the second as closest match to what we do.
This fixes up the messages that we had already updated to the standard. Work for you @sfuhrer
=> Fix up uorb message spacing to add whitespace

src/lib/rover_control/rovercontrol_params.c, src/modules/rover_ackermann/AckermannDriveModes/AckermannManualMode/AckermannManualMode.cpp, src/modules/rover_ackermann/AckermannDriveModes/AckermannManualMode/AckermannManualMode.hpp, src/modules/rover_differential/DifferentialDriveModes/DifferentialManualMode/DifferentialManualMode.cpp, src/modules/rover_differential/DifferentialDriveModes/DifferentialManualMode/DifferentialManualMode.hpp, src/modules/rover_differential/module.yaml, src/modules/rover_mecanum/MecanumDriveModes/MecanumManualMode/MecanumManualMode.cpp, src/modules/rover_mecanum/MecanumDriveModes/MecanumManualMode/MecanumManualMode.hpp, src/modules/rover_mecanum/module.yaml
The linear scaling from stick inputs to yaw rate setpoints makes it very difficult to "finely" steer the rover (particularly for differential and mecanum).
Additionally, in manual mode a normalized steering  input of `1` can be too aggressive for certain vehicles.
This PR introduces the use of the super exponential function to shape the input curve just as multicopter does in [acro mode](https://docs.px4.io/main/en/flight_modes_mc/acro.html#stick-input-mapping):
$$
\dot{\psi} = r \cdot \frac{(f \cdot x^3 + x(1-f)) \cdot (1-g)}{1-g \cdot |x|}
$$
with:
- $$\dot{\psi}:$$ Yaw rate setpoint 
- $$x \in [-1, 1]:$$ Normalized stick input
- $$r:$$
- `RO_YAW_RATE_LIM`: For all rovers in acro, stab or position mode
- `RX_YAW_STK_GAIN` $$\in [0.1, 1]$$: For differential/mecanum rovers in manual mode …
=> rover: add exponential scaling to manual yaw rate input

src/modules/commander/airspeed_calibration.cpp
From the user's perspective, the sensor status indicator turns green even when calibration fails, creating confusion about whether the calibration was successful.
What happens: We [write the determined value](https://github.com/PX4/PX4-Autopilot/blob/f161a32c55b5a979a02100433eb7339749dc6a77/src/modules/commander/airspeed_calibration.cpp#L125) of differental pressure offset to [SENS_DPRES_OFF](https://docs.px4.io/main/en/advanced_config/parameter_reference.html#SENS_DPRES_OFF) before [the sensor reverse connection check](https://github.com/PX4/PX4-Autopilot/blob/f161a32c55b5a979a02100433eb7339749dc6a77/src/modules/commander/airspeed_calibration.cpp#L147) passes and don't wipe it out even when no positive pressure was read
My suggestion: is to make sure that we pass all the checks before we …
=> airspeed calibration: save offset only when full procedure succeed

src/modules/fw_rate_control/FixedwingRateControl.cpp
When in an external mode that sends rate setpoints, the FW rate controller discards the yaw axis unless FW_ACRO_YAW_EN is set to 1 (by default it's off). 
This is wrong - the intend of FW_ACRO_YAW_EN is to only have effect in manual Acro mode.
Add a if(manual_control) to only enter in Acro mode.
```
Bugfix: FW rate controller: enable yaw rate controller when feeding in yaw rate setpoints outside of manual control
```
untested.
=> FW rate controller: enable yaw rate controller when feeding in yaw rate setpoints outside of manual control

src/modules/mavlink/mavlink_receiver.cpp
MAV_CMD_GET_MESSAGE_INTERVAL is deprecated in favour of MAV_CMD_REQUEST_MESSAGE, but that does not support getting `MESSAGE_INTERVAL`
This hacks the MAV_CMD_REQUEST_MESSAGE handler to call `get_message_interval()` for this particular message.
We could instead create a streaming class for `MESSAGE_INTERVAL` but we don't want to, because we don't want to stream this message - we only want to request it. So this is the right way to handle the case.
=> MAV_CMD_REQUEST_MESSAGE support for MESSAGE_INTERVAL

.github/workflows/docs_flaw_checker.yml
There is a flaw checker error because the update we did in #25419 results in invalid JSON (a forward slash in the generated file that is invalid JSON).
This attempts the suggestion of gemini AI to us the jq tool to clean up the json - replacing the direct echo with:
```js
echo "$ALL_CHANGED_FILES" | jq '.' > ./logs/prFiles.json
```
=> docs_flaw_checker.yml - attempt to fix the flaw safely

src/modules/commander/ModeManagement.cpp, src/modules/commander/ModeManagement.hpp, src/modules/commander/UserModeIntention.cpp, src/modules/commander/UserModeIntention.hpp
There were a number of cases where the state was not correct or not as desired after disarming, when running an external mode 'MyMission' with executor:
- run MyMission, which triggers Hold, then Land
- before: Mode: Hold, executor_in_charge: 1
- after:  Mode: MyMission, executor_in_charge: 1
- run MyMission, then user switches to RTL
- before: Mode: MyMission, executor_in_charge: 0
- after:  Mode: MyMission, executor_in_charge: 1
- run MyMission, then while in Hold mode, low battery failsafe (RTL)
- before: Mode: Hold, executor_in_charge: 1
- after:  Mode: MyMission, executor_in_charge: 1
- run MyMission, then stop external mode (terminate the process)
- before: Mode: (mode not available), executor_in_charge: 0
- after:  Mode: Hold, executor_in_charge: 0
This case is unchanged:
- run …
=> fix commander: handle mode executor correctly on disarm

src/modules/rover_ackermann/RoverAckermann.cpp, src/modules/rover_differential/RoverDifferential.cpp, src/modules/rover_mecanum/RoverMecanum.cpp
While testing I encountered the following issue: In manual modes the rate control had a substantial delay in **acro, stab and position** mode.
Turns out this was caused by the fact, that during setpoint generation I used `update` instead of `copy` to get the current  **nav state**. If there was no update to `vehicle_status` (which is periodically updated every second even if there are no changes to it), this would write `0` to the nav state which lead the (full) manual mode to be executed instead of the actual **nav_state**. 
This was only noticable as a short delay in **acro, stab and position** because if a setpoint higher in the rover control hierarchy is published, it will override the unwanted **throttle** and **steering** setpoints published by the unintentionally executed code for …
=> rover: fix setpoint generation

Kconfig, ROMFS/CMakeLists.txt, ROMFS/cannode/init.d/rcS, ROMFS/px4fmu_common/init.d/rcS, cmake/kconfig.cmake, docs/en/concept/system_startup.md
When having some board (especially cannode based ones, which don't have airframes) you often would need to copy the whole board just to set for example different default parameters or change some small part in the init scripts. This duplicates code and is harder to maintain.
- Adds the option to specify an additional dynamically selected init file by setting `CONFIG_BOARD_DYN_INIT`
- For example: We use it in our GCS GPS. Add a new file `gcs.px4board` and enter `CONFIG_BOARD_DYN_INIT="rc.dyn_init_gcs"`. This way the file `rc.dyn_init_gcs` will be used when compiling this variant.
- Duplicating the whole board is overkill
- Creating the concept of airframes for cannode based devices is also a bit overkill
- Tested on a ARK RTK GPS where we set different default parameters via a …
=> config: add dynamic init file

docs/en/sim_sih/index.md, src/modules/commander/Commander.cpp
It is currently not possible to send PWM while running in SIH (Software In Hardware) mode due to a boolean condition in the commander that blocks arming when SYS_HITL is set.
This PR addresses the issue in two parts:
- PX4 Code Change:
Removed a check for SYS_HITL in  `_actuator_armed.lockdown` boolean. 
- Documentation Update: Added documentation outlining the necessary steps to enable actuator control in SIH. 
This enables workflows where developers want to test actuator behavior during SIH simulation by simply adding SIH parameters to their existing airframe file or enabling SIH via SYS_HITL, while maintaining existing PWM output mappings.
```
Feature: Enable PWM output while running in SIH mode
Documentation: Added instructions for actuator control in SIH
```
Tested …
=> SIH: Support sending PWM over SIH  

src/modules/ekf2/EKF/aid_sources/gnss/gnss_height_control.cpp, src/modules/ekf2/EKF/aid_sources/gnss/gps_control.cpp, src/modules/ekf2/test/sensor_simulator/ekf_wrapper.cpp, src/modules/ekf2/test/sensor_simulator/ekf_wrapper.h, src/modules/ekf2/test/test_EKF_gps.cpp
follow up to https://github.com/PX4/PX4-Autopilot/pull/25297
In GNSS dead-reckoning mode, the velocity and height parts of the GNSS message are being fused even when `gnss_fault` is set.
Stop the velocity and altitude fusion when `gnss_fault` is set (only GNSS lat/lon fusion is allowed to clear the fault by passing the test ratio again)
Note that the bias update was moved in the "continuing condition" section to avoid fusing incorrect data that would have failed this check (e.g.: `gnss_fault`)
added unit test
=> EKF2: stop GNSS altittude and velocity aiding when gnss_fault is set

ROMFS/px4fmu_common/init.d/rc.logging, boards/auterion/fmu-v6s/init/rc.board_defaults, boards/holybro/kakuteh7mini/init/rc.board_defaults, boards/holybro/kakuteh7v2/init/rc.board_defaults, docs/en/dev_log/logging.md, src/lib/parameters/param_translation.cpp, src/modules/logger/params.c
In some situations it is not desired to either log via the mavlink backend or the SD card backend.
- Adds a new parameter `SDLOG_BACKEND` that allows to configure the backend
```
New parameter: SDLOG_BACKEND
```
- Tested on the bench with a v6x / v6s
=> logging: allow logging backend config

src/modules/ekf2/EKF/aid_sources/optical_flow/optical_flow_control.cpp, src/modules/ekf2/EKF/ekf.h
Currently, the "dist-to-bottom" value is always reset to the minimum range of the range sensor. This works in some cases, but when using smaller sensor noise values for optical flow, the test ratios fail consistently and the terrain estimate gets stuck at an unrealistic altitude.
When another source of horizontal aiding is available, we now use it to guide the terrain reset. Specifically, we leverage the current velocity to adjust the terrain estimate so that it aligns with the optical flow measurements. This ensures more realistic altitude behavior and prevents the estimator from getting stuck.
After this we can also merge https://github.com/PX4/PX4-Autopilot/pull/25365
I am also working on a reset-by-fusion method, but it requires some more work. 
Test in sitl and log replay
=> EFK2: reset terrain w flow based on current horizontal velocity

src/modules/uxrce_dds_client/dds_topics.yaml
This allows controlling the landing gear from external ROS2 flight modes.
=> dds_topics: accept landing_gear command from external modes

ROMFS/px4fmu_common/init.d/rc.sensors
The iis2mdc driver is only started on certain boards. I don't know how widely used this sensor is, but at least we are now using it on an airframe and not having it automatically probed for was quite confusing. 
Probe for this mag like for most other mags we have driver for.
```
Feature: add iis2mdc mag to list of automatically probed for sensors
```
Remove the iis2mdc startup in the boards (ark, cuav, nxp). It looks though as if it's there started with a certain rotation, so we likely want to keep it.
=> rc.sensors: add iis2mdc mag to list of probed for sensors

src/drivers/uavcan/uavcan_drivers/stm32h7/driver/src/uc_stm32h7_can.cpp, src/drivers/uavcannode/UavcanNode.cpp
*Topic 1*
When stopping and starting uavcan using `uavcan stop` and `uavcan start`, the init sometimes fails due to timing here:
```
// Request Init mode, then wait for completion
can_->CCCR |= FDCAN_CCCR_INIT;
if (!waitCCCRBitStateChange(FDCAN_CCCR_INIT, true)) {
UAVCAN_STM32H7_LOG("CCCR FDCAN_CCCR_INIT not set");
return -ErrCCCrINITNotSet;
}
```
*Topic 2*
Similar to https://github.com/PX4/PX4-Autopilot/issues/24179 there is the chance of the driver init failing causing follow-up errors in `uavcannode` as the errors are not handled at all.
*Topic 1*
The timeout function actually has a higher timeout implemented for NuttX targets, but this does not apply as the wrong macro is used. When using the correct one the init works.
*Topic 2*
Similar to …
=> uavcan: fix driver init after stop/start

platforms/nuttx/src/canbootloader/uavcan/main.c
For uavcan firmware over 500kB the flash can take longer than the watchdog timeout. This pets the watchdog during flashing.
=> uavcan bootloader watchdog_pet during long flashes

src/modules/mavlink/mavlink_main.cpp
With https://github.com/PX4/PX4-Autopilot/pull/24328 there was a new mode introduced. A comparison to "normal" showed these diffs:
- ODOMETRY
- ATTITUDE_QUATERNION
- EFI_STATUS
- GPS_STATUS
- HYGROMETER_SENSOR
- OPEN_DRONE_ID_LOCATION, OPEN_DRONE_ID_SYSTEM, OPEN_DRONE_ID_ARM_STATUS
- RAW_RPM
- SCALED_PRESSURE
- FIGURE_EIGHT_EXECUTION_STATUS
- GLOBAL_POSITION
For us the most important missing ones are 
- ATTITUDE_QUATERNION
- FIGURE_EIGHT_EXECUTION_STATUS
- GLOBAL_POSITION
In this PR I added them. 
I further:
- aligned (increased for 2 streams) the rate of positioning feedback streams to 2Hz
- reduced the rate of various secondary status streams
```
Improvement: Mavlink stream low bandwidth: add some important missing ones, update rates
```
To avoid missing some messages …
=> Mavlink stream low bandwidth: add some important missing ones, update rates

ROMFS/px4fmu_common/init.d-posix/airframes/60002_gz_uuv_bluerov2_heavy, ROMFS/px4fmu_common/init.d-posix/airframes/70000_gz_atmos, ROMFS/px4fmu_common/init.d/airframes/60002_uuv_bluerov2_heavy, ROMFS/px4fmu_common/init.d/airframes/70000_atmos, docs/assets/airframes/multicopter/amovlab_f410/amovlabf410_drone_v1.15.4.params, docs/en/config/safety.md, src/modules/commander/Commander.hpp, src/modules/commander/UserModeIntention.cpp, src/modules/commander/UserModeIntention.hpp, src/modules/commander/commander_params.c, src/modules/commander/failsafe/failsafe.cpp, src/modules/commander/failsafe/failsafe.h
This parameter repeataddly confuses users who are looking for a way to influence position loss failsafe behavior. In an effort to reduce confusion and configuration space I suggest to remove this option which I've not seen use for. If a pilot flies manually in position mode we assume he has some visual reference of the vehicle and can do better than an autonomous mode without position reference. If that assumption wouldn't hold he was in Position mode by mistake and the static option here doesn't help. Also by now we have nudging in Descend mode so the pilot can still give input and the only difference is it automatically goes down instead of the pilot having to descend by stick to land.
Remove COM_POSCTL_NAVL
```
Remove COM_POSCTL_NAVL
```
Someone posts a good reason to have this option …
=> Remove COM_POSCTL_NAVL

src/modules/logger/logger.cpp, src/modules/logger/logger.h, src/modules/logger/util.cpp, src/modules/logger/util.h
When I opened my ULog files I found that there was no way to determine the UTC timestamp of the messages. My drone does not have a GPS sensor, and thus I could not use the `time_utc_usec` field of the https://docs.px4.io/main/en/msg_docs/SensorGps message to compute the offset between the message timestamps and UTC time. 
This MR adds an Information Message to the ULog with the boot time in UTC microseconds from CLOCK_REALTIME which can be set by the GCS via Mavlink/DDS. To get the UTC timestamp of any message, just add the message's timestamp to the boot time saved in the ULog file. 
New ULog Information Message: `boot_time_utc_us`. Only present if a >=2D GPS fix was acquired or CLOCK_REALTIME was set by the GCS before logging began. Value is system start time with respect to Unix time …
=> Recovering UTC timestamps from ULog without sensor_gps

msg/RoverAttitudeSetpoint.msg, msg/RoverAttitudeStatus.msg, msg/RoverPositionSetpoint.msg, msg/RoverRateSetpoint.msg, msg/RoverRateStatus.msg, msg/RoverSpeedSetpoint.msg, msg/RoverSpeedStatus.msg, msg/RoverSteeringSetpoint.msg, msg/RoverThrottleSetpoint.msg
Recently we agreed that whitespace indentation before a uorb comment should be 2 spaces after the longest field in a group for all fields/enum values in a group. This moves RoverAttitudeSetpoint and friends to match. Note, #25544 covers purePursuitSetup
=> RoverAttitudeSetpoint et al - whitespace

msg/PurePursuitStatus.msg
Recently we agreed that whitespace indentation before a comment should be 2 spaces after the longest field in a group for all fields/enum values in a group. This moves PurePursuitStatus to match
=> PurePursuitStatus.msg - whitespace indentation

src/modules/flight_mode_manager/tasks/Utility/Gimbal.cpp, src/modules/flight_mode_manager/tasks/Utility/Gimbal.hpp
When switching between Position and Position Slow mode the gimbal does not behave as expected. Sometimes the  flag `GIMBAL_MANAGER_FLAGS_YAW_LOCK` remains in Position mode after switch.
- Only send gimbal manager status on change as an event
- Configure stream rate to 5 Hz as [recommended](https://mavlink.io/en/messages/common.html#GIMBAL_MANAGER_STATUS).
=> FlightTaskManualAccelerationSlow: Acquire gimbal control until expected IDs are reported

msg/versioned/ActuatorMotors.msg, msg/versioned/ActuatorServos.msg, msg/versioned/ArmingCheckReply.msg, msg/versioned/ArmingCheckRequest.msg, msg/versioned/BatteryStatus.msg
This updates some "already updated" uORB messages to use the latest version of the standard docs format.
Such as - indentation to two spaces, removing full stops etc.
There are no changes to the actual definitions, so can be merged.
=> uORB message layout fixes

.github/workflows/docs_deploy.yml
Avoids double build that isn't needed for translation branches
=> Don't build translations on push (only PR)

src/modules/commander/accelerometer_calibration.cpp
Fixes https://github.com/PX4/PX4-Autopilot/issues/25606
Introduced in https://github.com/PX4/PX4-Autopilot/pull/24118. The rotation was accidentally removed.
=> calibration: accel: rotate offsets/scales back into sensor frame before saving

Tools/mavlink_shell.py
Changed command ASCII used for backspace
ASCII used for backspace was actually the "Delete" key `ASCII Key 127`
Fixes #25601 
- ASCII used for backspace was actually the "Delete" key `ASCII Key 127`  changed it to the "Backspace" Key ASCII Key 8` in Tools/mavlink_shell.py
```
Feature/Bugfix  #25601 
New parameter: 
```
=> MavLinkShell: Corrected Backspace keystroke read

.github/workflows/docs_deploy_aws.yml
Deployment for the 1.16 branch
=> Docs deploy AWS to v1.16 branch

src/drivers/uavcan/actuators/esc.cpp, src/drivers/uavcan/actuators/esc.hpp, src/drivers/uavcan/uavcan_main.cpp
There is a race condition between dshot and uavcan to claim the first uORB `esc_status`. The ESC controller should not be initialized and the callback should not be registered when ESC control is not enabled.
=> uavcan: don't init ESC if UAVCAN_ENABLE isn't set for ESC

src/modules/ekf2/EKF/aid_sources/range_finder/range_height_control.cpp, src/modules/ekf2/EKF/ekf.h
- if bad vertical acceleration is detected there's an emergency case where rejected range finder observations are allowed to be used, but this still can't happen if the sample itself is known to be bag
=> ekf2: rng don't allow bad measurement in bad_acc_vertical

src/drivers/uavcan/actuators/esc.cpp
backport https://github.com/PX4/PX4-Autopilot/pull/25485
=> [BACKPORT 1.16] uavcan: esc: init msg to avoid publishing random values

src/modules/mavlink/streams/AVAILABLE_MODES.hpp
backport https://github.com/PX4/PX4-Autopilot/pull/25428
=> [BACKPORT 1.16] mavlink: add message spacing for AVAILABLE_MODES, for low bandwidth

src/modules/logger/logged_topics.cpp
When connecting an external baro over UAVCAN, the `sensor_baro` topic was only logging the instance of the internal baro. 
- Remove the `optional` from the `multi_topic` logging so all instances are logged. 
```
Feature/Bugfix log all `sensor_baro` instances
```
I don't know if this is the best way to do this. Happy to get feedback on this 
Two instances shown in the MAVLink shell: 
```
nsh> listener sensor_baro
TOPIC: sensor_baro 2 instances
Instance 0:
sensor_baro
timestamp: 755793708 (0.010079 seconds ago)
timestamp_sample: 755792762 (946 us before timestamp)
device_id: 7239457 (Type: 0x6E, I2C:4 (0x77))
pressure: 97468.40625
temperature: 57.69000
error_count: 0
Instance 1:
sensor_baro
timestamp: 755812747 (0.004100 seconds ago)
timestamp_sample: 755812746 (1 us …
```
=> logging: log sensor_baro with add_topic_multi
