src/modules/sensors/voted_sensors_update.cpp, src/modules/sensors/voted_sensors_update.h
Missing params or any baro cal at the moment.
=> sensors remove barometer enabled check for now

src/drivers/bmm150/bmm150.cpp
According to the board_config.h shown. bmm150 only on the external i2c bus
=> bmm150 has noting to do with spi bus

platforms/nuttx/NuttX/CMakeLists.txt
- fixes https://github.com/PX4/Firmware/issues/8239
- @bkueng this should improve the builtin generation issue you came across
=> cmake nuttx improvements (windows build + builtins)

src/drivers/mpu9250/main.cpp
Change the "mpu9250 test" command output magnetic flux units.
=> Change the "mpu9250 test" command output units

platforms/nuttx/NuttX/CMakeLists.txt
@santiago this should fix USB connectivity.
=> cmake nuttx keep builtins generated by nuttx apps

.travis.yml, Makefile
This should make it easier to catch when it stops working.
=> travis-ci fix coverity build

src/modules/systemlib/param/px4params/srcparser.py
This should reduce churn in the QGC, devguide, and user guide automated commits.
@hamishwillee
=> parameters.xml sort parameters by name, sort enums by value

.gitmodules, CMakeLists.txt, Tools/check_submodules.sh, cmake/common/px4_git.cmake, platforms/nuttx/NuttX/CMakeLists.txt, src/drivers/gps/CMakeLists.txt, src/firmware/posix/CMakeLists.txt, src/firmware/posix/sitl_target.cmake, src/lib/version/CMakeLists.txt, src/modules/ekf2/CMakeLists.txt, src/modules/mavlink/CMakeLists.txt, src/modules/simulator/CMakeLists.txt, src/modules/uavcan/CMakeLists.txt
- fix firmware build as a submodule (https://github.com/PX4/Firmware/issues/8255)
- add submodule intended branch for easy updating (eg `git submodule update --remote mavlink`)
- add proper dependencies for px4_add_git_submodule
=> submodule fixes and improvements

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
Based on this recent FW flight. https://logs.px4.io/plot_app?log=c412160a-56e3-4154-b3d8-2c582aa9b9f1
=> fw_pos_control_l1 increase stack by 100 Bytes

msg/CMakeLists.txt, msg/filtered_bottom_flow.msg, msg/output_pwm.msg, msg/tools/uorb_rtps_message_ids.py, msg/vehicle_force_setpoint.msg, src/drivers/drv_pwm_output.h, src/drivers/drv_rc_input.h, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h, src/platforms/ros/nodes/mavlink/mavlink.cpp, src/platforms/ros/nodes/mavlink/mavlink.h
- uorb_rtps_message_ids.py doesn't seem sustainable
=> delete more unused uORB messages

src/modules/sensors/parameters.cpp, src/modules/sensors/parameters.h, src/modules/sensors/sensor_params.c, src/modules/sensors/sensors.cpp, src/modules/sensors/voted_sensors_update.cpp, src/modules/sensors/voted_sensors_update.h
This has been disabled for a long time, but it's still available from a user's perspective.
A working feature like this would be extremely helpful, but we shouldn't keep dead code around.
=> sensors delete disabled ATT_VIBE_THRESH

src/modules/vtol_att_control/vtol_att_control_main.cpp
=> vtol_att_control increase stack by 30 Bytes (1200 -> 1230)

ROMFS/px4fmu_common/init.d/rcS, src/modules/micrortps_bridge/micrortps_client/microRTPS_client_main.cpp
Fixed the typo error in micrortps_client which was causing issue to update
baudrate and other options.
=> Fix typo error in micrortps_client module

src/modules/vtol_att_control/vtol_type.cpp, src/modules/vtol_att_control/vtol_type.h
Added some more QuadChute logic to cope with vehicles that still perform but don't make their setpoints.
=> QuadChute monitor tecs height rate

Jenkinsfile
- check format first to reduce build utilization
=> Jenkins temporarily disable coverage and clang-tidy

ROMFS/px4fmu_common/init.d/rcS
for slow companions that require forwarding
=> Add forwarding on telem2 normal telemetry option

Jenkinsfile
- combine default and rtps builds (ccache)
- set CCACHE_BASEDIR
=> Jenkinsfile small optimizations

Jenkinsfile
This is the last piece remaining on semaphoreci.
=> Jenkins add eagle_default build with docker credentials

src/modules/land_detector/MulticopterLandDetector.cpp, src/modules/mc_pos_control/mc_pos_control_main.cpp
Created as a placeholder for discussion in response to https://github.com/PX4/Firmware/issues/7202
Needs proper flight evaluation.
@dagar FYI
=> Reduce effect of estimator vertical velocity errors

src/modules/logger/logger.cpp
This would have helped with debugging issues like https://github.com/PX4/Firmware/issues/8468.
=> logger add home_position to the default set

src/modules/ekf2/ekf2_params.c
I updated the comment according to https://github.com/PX4/ecl/blob/master/EKF/common.h#L183
=> ekf2: update AID_MASK bitmask comment for QGC

src/modules/ekf2/ekf2_main.cpp, src/modules/ekf2/ekf2_params.c
Add beta innovation gate to parameters
=> ekf2: add beta innovation gate to parameters

msg/vehicle_status.msg, msg/vehicle_status_flags.msg, src/modules/commander/Commander.hpp, src/modules/commander/PreflightCheck.cpp, src/modules/commander/PreflightCheck.h, src/modules/commander/commander.cpp, src/modules/commander/state_machine_helper.cpp, src/modules/commander/state_machine_helper.h, src/modules/fw_att_control/fw_att_control_main.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
This is a much smaller version of https://github.com/PX4/Firmware/pull/7517. The previous PR was too large and interfered with ongoing development. I'm now going to try a more incremental approach.
=> commander initial class structure

src/modules/commander/PreflightCheck.cpp, src/modules/commander/airspeed_calibration.cpp, src/modules/commander/calibration_routines.cpp, src/modules/commander/commander.cpp, src/modules/commander/state_machine_helper.cpp, src/modules/commander/state_machine_helper.h
@px4dev This should help with what you experienced. Tested against a Pixhawk Mini.
=> Fix the preflight setup experience

src/modules/commander/commander.cpp, src/modules/commander/commander_params.c, src/modules/navigator/navigator_main.cpp
switch always to hold after takeoff. this makes sense for mc, but not sure if that also applies to FW. 
@dagar?
=> commander: switch to hold once takeoff is finished

ROMFS/px4fmu_common/init.d/rc.sensors, cmake/configs/nuttx_auav-x21_default.cmake, cmake/configs/nuttx_mindpx-v2_default.cmake, cmake/configs/nuttx_nxphlite-v3_default.cmake, cmake/configs/nuttx_px4-same70xplained-v1_default.cmake, cmake/configs/nuttx_px4fmu-v2_default.cmake, cmake/configs/nuttx_px4fmu-v2_test.cmake, cmake/configs/nuttx_px4fmu-v3_default.cmake, cmake/configs/nuttx_px4fmu-v4_default.cmake, cmake/configs/nuttx_px4fmu-v4pro_default.cmake, cmake/configs/nuttx_px4fmu-v5_default.cmake, cmake/configs/nuttx_px4nucleoF767ZI-v1_default.cmake, src/drivers/tfmini/CMakeLists.txt, src/drivers/tfmini/tfmini.cpp, src/drivers/tfmini/tfmini_parser.cpp, src/drivers/tfmini/tfmini_parser.h, src/modules/sensors/sensor_params.c
Rebased version of https://github.com/PX4/Firmware/pull/8537
=> Added support for TFmini-LiDAR

msg/estimator_status.msg, src/modules/ekf2/ekf2_main.cpp
Needs changes in ecl: https://github.com/PX4/ecl/pull/371
=> ekf2: added beta test ratio to estimator_status

src/modules/fw_att_control/fw_att_control_params.c
=> FW improve FW_ARSP_MODE metadata options

README.md
Signed-off-by: keenanjohnson <keenan.johnson@gmail.com>
=> Main Readme: Spelling correction

src/drivers/camera_trigger/camera_trigger.cpp, src/modules/commander/arm_auth.cpp, src/modules/commander/arm_auth.h, src/modules/commander/commander.cpp, src/modules/mavlink/mavlink_main.cpp, src/modules/navigator/datalinkloss.cpp, src/modules/navigator/enginefailure.cpp, src/modules/navigator/follow_target.cpp, src/modules/navigator/geofence.cpp, src/modules/navigator/gpsfailure.cpp, src/modules/navigator/land.cpp, src/modules/navigator/loiter.cpp, src/modules/navigator/mission.cpp, src/modules/navigator/navigator_main.cpp, src/modules/navigator/navigator_mode.cpp, src/modules/navigator/rcloss.cpp, src/modules/navigator/takeoff.cpp, src/modules/sensors/parameters.cpp, src/modules/sensors/temp_comp_params_accel.c, src/modules/sensors/temp_comp_params_baro.c, src/modules/sensors/temp_comp_params_gyro.c, src/modules/sensors/temperature_compensation.cpp, src/modules/systemlib/bson/tinybson.c, src/modules/systemlib/param/param.c
nsh> perf
...
param_set: 0 events, 0us elapsed, 0us avg, min 0us max 0us 0.000us rms
param_get: 5266 events, 55534us elapsed, 10us avg, min 4us max 1893us 57.558us rms
param_export: 0 events, 0us elapsed, 0us avg, min 0us max 0us 0.000us rms
nsh> param set SYS_AUTOSTART 2100
nsh> param save
nsh> perf
...
param_set: 0 events, 0us elapsed, 0us avg, min 0us max 0us 0.000us rms
param_get: 6960 events, 78366us elapsed, 11us avg, min 4us max 1896us 61.081us rms
param_export: 1 events, 1012771us elapsed, 1012771us avg, min 1012771us max 1012771us   NaNus rms
nsh> param set SYS_MC_EST_GROUP 1
SYS_MC_EST_GROUP: curr: 2 -> new: 1
nsh> param save
nsh> perf
...
param_set: 1 events, 86us elapsed, 86us avg, min 86us max 86us Infinityus rms
param_get: 18022 events, 196162us elapsed, 10us avg, min 4us …
=> param improvements

src/modules/mavlink/mavlink_messages.cpp, src/platforms/posix/drivers/df_mpu9250_wrapper/df_mpu9250_wrapper.cpp
@LorenzMeier @dagar 
As discussed on the messaging call, I did a temporary hack to get unfiltered IMU into VISLAM.
This replaces https://github.com/PX4/Firmware/pull/8517
=> Stream scaled IMU for Snapdragon Flight using VISLAM

src/drivers/adis16448/adis16448.cpp
No coning compensation for the accelerometers :-)
=> remove coning compensation for the accelerometers

src/modules/simulator/simulator.h, src/modules/simulator/simulator_mavlink.cpp
Hi,
I found that the mavlink version of simulator module was old.
So, I change the mavlink version for simulator (1.0 -> 2.0)
Thanks 
SungTae Moon
=> Change mavlink version for simulator

src/modules/events/temperature_calibration/polyfit.hpp
=> Master temp calib

src/modules/commander/PreflightCheck.cpp
=> commander ekf2Check respect reportFailures

src/platforms/posix/main.cpp
with this, lines can be edited with the lef/right arrow key in a posix PX4 shell
=> posix main: add left/right arrow to edit command

cmake/configs/posix_rpi_common.cmake, cmake/configs/posix_sitl_default.cmake, src/drivers/ll40ls/LidarLite.cpp, src/drivers/ll40ls/LidarLite.h, src/drivers/ll40ls/LidarLiteI2C.cpp, src/drivers/ll40ls/LidarLiteI2C.h, src/drivers/ll40ls/LidarLitePWM.cpp, src/drivers/ll40ls/LidarLitePWM.h, src/drivers/ll40ls/ll40ls.cpp
@belaidH I squashed your changes onto latest master and fixed a few things. The main thing you were missing is opening the PX4 virtual device (px4_open, px4_close, px4_ioctl, etc) instead of the real version when appropriate. It's rather unintuitive.
Can you give this another try?
=> LidarLite port to raspberrypi

src/drivers/iridiumsbd/IridiumSBD.cpp, src/drivers/iridiumsbd/IridiumSBD.h, src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_main.h, src/modules/mavlink/mavlink_messages.cpp, src/modules/mavlink/mavlink_mission.cpp, src/modules/mavlink/mavlink_mission.h, src/modules/mavlink/mavlink_receiver.cpp
@dagar this recuperates enough flash to get precision landing in. I will see if there are more offenders that need fixing and add commits. Could you review as soon as it fits so I can get the precision landing PR in?
=> Reduce flash footprint

src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp, src/modules/local_position_estimator/BlockLocalPositionEstimator.hpp, src/modules/local_position_estimator/params.c
I found some sensors don't have a selection chance for sensor fusion in LPE.
I added options for that sensors (MOCAP, LIDAR, and SONAR).
=> LPE minor improvement

Tools/process_sensor_caldata.py
Fixes indentation error preventing baro calibration.
Fixes error in documentation
Calibration tested using pixracer log: https://logs.px4.io/plot_app?log=34161e52-ce1e-494c-8ce7-6f6a8e2f9182 gathered using SDLOG_MODE=2 and SDLOG_PROFILE=4
Parameter File:
[09_26_29.ulg.params.txt](https://github.com/PX4/Firmware/files/1611115/09_26_29.ulg.params.txt)
Plots:
[09_26_29.ulg.pdf](https://github.com/PX4/Firmware/files/1611118/09_26_29.ulg.pdf)
=> Tools: Fix errors in thermal calibration script

posix-configs/eagle/200qx/mainapp.config, posix-configs/eagle/210qc/mainapp.config, posix-configs/eagle/flight/mainapp.config, posix-configs/eagle/hil/mainapphil.config
without this param set doesn't work -> adsp side never receives changes
Fixes https://github.com/PX4/Firmware/issues/8657
=> eagle posix-config: add sleep after muorb

src/modules/commander/commander.cpp
Potential fix for https://github.com/PX4/Firmware/issues/8727.
=> commander fix hil_state regression again

src/drivers/vmount/output.cpp, src/drivers/vmount/vmount_params.c, src/modules/mavlink/mavlink_mission.cpp, src/modules/navigator/mission.cpp, src/modules/navigator/mission.h, src/modules/navigator/mission_block.cpp, src/modules/navigator/mission_params.c
Continuation of https://github.com/PX4/Firmware/pull/8595
=> ROI heading fixes

ROMFS/px4fmu_common/init.d/rcS
Comment was a contradiction.
fixes https://github.com/PX4/Firmware/issues/8720
=> rcS: update comment on mavlink for FMUv4

src/modules/commander/commander.cpp
There's a bug in here causing most of the periodic ROS mission test failures. 
@lamping7 FYI
The actual parameter values (COM_POS_FS_DELAY and COM_POS_FS_PROB) were being ignored. @antiheavy
=> commander refactor position velocity validity checks

msg/CMakeLists.txt, msg/mc_att_ctrl_status.msg, msg/rate_ctrl_status.msg, src/modules/fw_att_control/fw_att_control_main.cpp, src/modules/logger/logger.cpp, src/modules/mc_att_control/mc_att_control_main.cpp, src/modules/sdlog2/sdlog2.c
Haven't tested this yet. Publishing FW att control status. Adding MC and FW att control status to logger (does the rate make sense?).
=> rate controller status logging

Jenkinsfile
This was the cause of occasional uorb_graphs failures.
=> Jenkins always distclean each build

src/modules/commander/commander.cpp
https://review.px4.io/plot_app?log=9ec3ef5b-e02d-41f1-9317-f77353ad3dd5
=> commander increase stack by 90 bytes (3160 -> 3250)

Tools/px_uploader.py
@julianoes This still needs a check for silicon revisions, but shows where we would need to fix it.
=> Uploader: Move flash size check into appropriate bootloader version 

src/modules/uavcan/CMakeLists.txt, src/modules/uavcanesc/CMakeLists.txt, src/modules/uavcannode/CMakeLists.txt
=> UAVCAN improve dependencies within libuavcan submodule

launch/single_vehcile_spawn.launch
Fixes: https://github.com/PX4/Firmware/issues/7937
=> Fix multi UAV launch, spawn urdf vehicles

ROMFS/px4fmu_common/init.d/rc.sensors
Causing bootup to fail on nuttx.
=> ROMFS fix LeddarOne nsh init

Tools/px4moduledoc/markdownout.py
So that they are unique.
@hamishwillee
=> modules documentation script: add anchor for '### Usage' sections

ROMFS/CMakeLists.txt, platforms/nuttx/CMakeLists.txt, src/drivers/px4io/CMakeLists.txt
=> cmake improve ROMFS dependencies for px4io inclusion

msg/templates/urtps/microRTPS_agent.cpp.template, src/modules/micrortps_bridge/micrortps_client/microRTPS_client_main.cpp
Adding aerofc baudrate 921600 into the list
=> Add aerofc baudrate to list

src/modules/mavlink/mavlink_receiver.cpp
this will be used by the ekf2 at some point
=> mavlink_receiver: add evh/evv to vision msg

msg/CMakeLists.txt, msg/obstacle_distance.msg, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h
=> Decode mavlink message obstacle_distance

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
- fixes https://github.com/PX4/Firmware/issues/7390
=> fw_pos_control_l1 move to ModuleBase

cmake/configs/nuttx_px4fmu-v4_default.cmake, src/drivers/imu/CMakeLists.txt
Hi,
This PR aligns the src/drivers/imu directory CMakeLists with other directories at that level.
Please let me know if you have any questions.  Thanks.
-Mark
=> Update CMakeLists for the drivers/imu directory.

src/modules/vtol_att_control/vtol_att_control_main.cpp
Signed-off-by: Roman <bapstroman@gmail.com>
=> vtol_att_control: prevent segfault when no command line args given

src/modules/vtol_att_control/vtol_att_control_main.cpp
=> vtol_att update poll fd before poll call

Jenkinsfile
Helpful for debugging hard faults. @bkueng FYI
I need to update the s3 deploy as well.
=> Jenkins archive elf files as well

src/lib/mixer/geometries/quad_plus.toml
Please refer to #8822 
I am not git guru so hope I did it right.
=> Fixed typo in rear motor name

src/modules/syslink/syslink_main.cpp
=> Beat's changes to make QGC connect with crazyflie

src/drivers/barometer/bmp280/bmp280_spi.cpp
just changed variable external to externalL.
=> shadow declaration issue.

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp, src/modules/fw_pos_control_l1/runway_takeoff/RunwayTakeoff.cpp, src/modules/fw_pos_control_l1/runway_takeoff/RunwayTakeoff.h, src/modules/gnd_pos_control/GroundRoverPositionControl.cpp, src/modules/gnd_pos_control/GroundRoverPositionControl.hpp
ECL side - https://github.com/PX4/ecl/pull/409
=> TECS and L1 switch to matrix math library

src/modules/vtol_att_control/vtol_att_control_main.cpp
Signed-off-by: Roman <bapstroman@gmail.com>
=> vtol_att_control: set flag in_transition_to_fw properly

src/modules/commander/commander.cpp
Now we complete these checks in preflightcheck.cpp
=> Clean-up :remove the ＥＫＦ pre-flight check variable that is not used in commander.

src/modules/mc_att_control/mc_att_control_main.cpp
While reading through the code I wrote I found a typo in my comment and while I'm fixing the typo I can improve clarity of that comment line.
=> trivial: improve a quaternion control comment

src/modules/mavlink/mavlink_messages.cpp
Hotfix for master. Not sure how it got through CI successfully.
=> mavlink : fix pointer for main_mode and sub_mode

src/modules/logger/logger.cpp
=> logger: remove some unneeded SITL topics

src/drivers/tap_esc/drv_tap_esc.h, src/drivers/tap_esc/tap_esc.cpp
There are a few minor things I forgot to add to the previous cleanup PR: #9313 
@bkueng Could you take another look? Should be an easy PR :) Sorry for the hassle.
=> tap_esc cleanup - addendum

Tools/astyle/check_code_style_all.sh, src/modules/navigator/follow_target.h, src/systemcmds/tests/test_matrix.cpp
=> Allow astyle version 3.1

ROMFS/px4fmu_common/init.d/4014_s500
This file is a work in progress and will be edited later after fine tuning the gains.
=> adding airframe config for s500

Jenkinsfile
I believe this is the cause of failures like -
http://ci.px4.io:8080/blue/organizations/jenkins/Firmware/detail/master/177/pipeline/810
=> Jenkins mission tests delete old build first

.github/issue_template.md
=> Delete old issue template

src/modules/mavlink/mavlink_mission.cpp
In the case a GCS would re-send the last mission item, which already successfully was received (but the GCS did not receive/handle the ack), the mission manager would send the message "IGN MISSION_ITEM: No transfer".
This PR fixes that.
Fixes #9505
=> mavlink mission: send an ack on duplicated last uploaded mission item

src/drivers/magnetometer/ist8310/ist8310.cpp
=> Added missing fields to IST8310 mag report.

cmake/configs/nuttx_px4fmu-v5_default.cmake, src/modules/commander/commander_helper.cpp
Fixes https://github.com/PX4/Firmware/issues/9537
=> FMUv5: Fix RGB led usage - these are individual status leds.

msg/estimator_status.msg, msg/optical_flow.msg, msg/vehicle_local_position.msg, src/drivers/px4flow/px4flow.cpp, src/modules/commander/commander.cpp, src/modules/ekf2/ekf2_main.cpp, src/modules/ekf2/ekf2_params.c, src/modules/land_detector/LandDetector.cpp, src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mc_pos_control/mc_pos_control_main.cpp, src/modules/mc_pos_control/mc_pos_control_params.c, src/modules/position_estimator_inav/position_estimator_inav_main.cpp, src/modules/sensors/sensor_params.c, src/modules/sensors/sensor_params_flow.c, src/modules/simulator/simulator_mavlink.cpp
Supersedes https://github.com/PX4/Firmware/pull/9509
Rebase only.
=> Optical Flow Use Improvements - supersedes #9509

platforms/nuttx/CMakeLists.txt
=> cmake nuttx fix upload target

src/modules/commander/state_machine_helper.cpp
Mostly taken from https://github.com/PX4/Firmware/pull/8175.
=> commander ignore failsafe transitions when in mission or loiter and disarmed

Tools/ecl_ekf/analyse_logdata_ekf.py
This pr fixes an issue with the 5s late start, early end buffer, adds a flag to turn it off and splits the imu sensor checks into vibration, bias and output predictor.
in detail:
- fix: only add the 5s buffer after takeoff and before landing when the log does not start or finish in air
- add a flag for turning the 5s late start early end buffer on/off
- split the combined imu sensor check into checks for vibration, bias and output predictor for the results table (the information is already there, but is currently not stored in the results table)
=> ecl-ekf-tools: fix the 5s late start early end buffer and split the imu checks

src/modules/mc_att_control/mc_att_control_main.cpp
@MaEtUgR as discussed, I changed the comment explaining why the rotation is done in that way based on your answer on Slack.
=> Modified comment regarding coordinate rotation of yaw_feedforward_rate

ROMFS/px4fmu_common/init.d/4100_tiltquadrotor, ROMFS/px4fmu_common/mixers/tilt_quad.aux.mix, ROMFS/px4fmu_common/mixers/tilt_quad.main.mix
Tilt-Quadrotor Airframe + Mixer Files
=> Tilt-Quadrotor 

CMakeLists.txt, src/lib/version/CMakeLists.txt, src/lib/version/px_update_git_header.py, src/lib/version/version.c, src/lib/version/version.h, src/modules/logger/logger.cpp, src/modules/mavlink/CMakeLists.txt, src/systemcmds/hardfault_log/CMakeLists.txt
@bkueng can we write arbitrary info messages into the log like this?
@priseborough FYI
=> version library add ECL

Jenkinsfile
Fixes https://github.com/PX4/Firmware/issues/9757. Also updates the ROS container tag.
=> Jenkins: add LPE CI test

Tools/px_uploader.py, platforms/nuttx/CMakeLists.txt
- px_uploader print board id and revision properly
- px_uploader print flash used percentage
- px_uploader stop printing OTP garbage by default
- cmake nuttx use USB vendor and product string directly
**Before**
**After**
=> px_uploader minor improvements

src/modules/ekf2/CMakeLists.txt, src/modules/ekf2/ekf2_main.cpp
~ 100 us to copy all data, and 250-300 us to run the EKF update.
=> EKF2 add perf counters

Tools/px_uploader.py
This removes a leftover commented out line and fixes some PEP8 warnings.
=> Small px_uploader.py files

cmake/configs/posix_eagle_hil.cmake, cmake/configs/posix_eagle_muorb.cmake, cmake/configs/posix_sdflight_default.cmake, cmake/configs/posix_sdflight_legacy.cmake, cmake/configs/posix_sitl_default.cmake, cmake/configs/qurt_eagle_hil.cmake, cmake/configs/qurt_eagle_muorb.cmake, cmake/configs/qurt_eagle_travis.cmake, cmake/configs/qurt_sdflight_default.cmake, cmake/configs/qurt_sdflight_legacy.cmake, platforms/posix/cmake/sitl_tests.cmake, src/modules/uORB/uORBDevices.cpp, src/modules/uORB/uORBDevices.hpp, src/modules/uORB/uORBManager.cpp, src/modules/uORB/uORBManager.hpp
Saves about a kilobyte of flash on fmu-v2. Needs a quick snapdragon test.
=> uORB add ORB_COMMUNICATOR define to enable remote uORB

ROMFS/px4fmu_common/init.d/13013_deltaquad
Based on latest flight testing and input from @sanderux
=> ROMFS: updated deltaquad autoconfig params

src/modules/uORB/uORBDevices.cpp, src/modules/uORB/uORBDevices.hpp
- keep portions of internal add/remove helpers
=> uORB fix ORB_COMMUNICATOR defined sections

src/drivers/px4flow/i2c_frame.h, src/drivers/px4flow/px4flow.cpp
Originates from https://github.com/PX4/px4_user_guide/pull/286.
@hamishwillee fyi
=> PX4 flow: add documentation

ROMFS/px4fmu_common/init.d/rc.mavlink, ROMFS/px4fmu_common/init.d/rcS
Hi,
This PR completes migration of hardware specific mavlink stream cases to rc.mavlink.
Let me know if you have any questions on this PR!
-Mark
=> Migrate hardware specific mavlink stream cases to rc.mavlink.

src/drivers/gps/gps.cpp
=> GPS driver increase stack

ROMFS/px4fmu_common/init.d/rc.fw_apps, ROMFS/px4fmu_common/init.d/rc.fw_defaults, ROMFS/px4fmu_common/init.d/rc.mc_apps, ROMFS/px4fmu_common/init.d/rc.mc_defaults, ROMFS/px4fmu_common/init.d/rc.ugv_apps, ROMFS/px4fmu_common/init.d/rc.ugv_defaults, ROMFS/px4fmu_common/init.d/rc.vtol_apps, ROMFS/px4fmu_common/init.d/rc.vtol_defaults, ROMFS/px4fmu_common/init.d/rcS
Hi,
This PR consists of comment updates and whitespace changes, there is little to no substance in this PR,... It simply aims to improve readability and intent of the scripts.
Let me know if you have any questions or would prefer to dismiss this PR, which I am certainly ok with. :)
-Mark
=> Format and comment fw, mc, vtol, and ugv vehicle apps and default startup scripts

msg/tools/px_generate_uorb_topic_helper.py
=> msg generated print support boolean

msg/airspeed.msg, src/modules/fw_att_control/FixedwingAttitudeControl.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/sensors/sensors.cpp, src/modules/vtol_att_control/standard.cpp
- closes https://github.com/PX4/Firmware/issues/9567
Need to verify the FW & VTOL controllers can handle this during ground testing.
=> sensors remove airspeed negative check

Tools/px_uploader.py
=> Small cleanup px_uploader.py after #9887

Tools/px_uploader.py
The correct determination of Windowed mode is critical to
maximise the speed on a USB based upload.
This commit bases the detection of a Serial (FTDI) on the
fact a CDC ACM port (USB) does not really have a baud rate.
We bump the baud rate to 233% of the requested baud rate to
see if the SYNC is acked. If it is Acked it must be a USB
port and Windowed mode is turned off. This removes unnessary
baud rate based delays from the programing logic. If it is a
real Serial port getSync will not get the ACK and Windowed
mode is turned on.
@LorenzMeier - I looked at the ttyS comparison but it look like it was there from way before in one form or another. I think it would be better to not filter the output text but let the baud rate be printed (Like it was before) While on USB it is not technically …
=> px_uploader:Platform and Timing independent Serial detection

src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_messages.cpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h
This PR updates the mavlink `TRAJECTORY` message to be compatible with the recently merged 
https://github.com/mavlink/mavlink/pull/915
This PR needs to be merged together with the update of the mavlink submodule otherwise master doesn't build anymore.
It would be great to also sync with the mavros update. Otherwise the pipeline is broken.
=> Update mavlink trajectory

ROMFS/px4fmu_common/init.d/rc.sensors, src/drivers/boards/omnibus-f4sd/board_config.h
=> omnibus: add support for Hobbywing XRotor F4 G2

ROMFS/CMakeLists.txt, cmake/common/px4_git.cmake, cmake/common/px4_metadata.cmake, cmake/toolchains/Toolchain-arm-none-eabi.cmake, src/drivers/px4io/CMakeLists.txt
@bkueng can you give this a try?
=> ROMFS cmake update dependency handling

ROMFS/px4fmu_common/init.d/13000_generic_vtol_standard, ROMFS/px4fmu_common/init.d/13005_vtol_AAERT_quad, ROMFS/px4fmu_common/init.d/13006_vtol_standard_delta, ROMFS/px4fmu_common/init.d/13007_vtol_AAVVT_quad, ROMFS/px4fmu_common/init.d/13008_QuadRanger, ROMFS/px4fmu_common/init.d/13009_vtol_spt_ranger, ROMFS/px4fmu_common/init.d/13010_claire, ROMFS/px4fmu_common/init.d/13012_convergence, ROMFS/px4fmu_common/init.d/13013_deltaquad, ROMFS/px4fmu_common/init.d/rc.interface, ROMFS/px4fmu_common/init.d/rc.mavlink, ROMFS/px4fmu_common/init.d/rcS
Hi,
In this PR I've relocated the UART mapping notes back to the top level rcS based on feedback from previous PR's.  I've also deprecated PWM_ACHDIS and replaced all instances with PWM_AUX_OUT and set that paramaeter directly in the config files to complete the transition of that variable per feedback on this PR.
Please let me know if have any questions on this work!
-Mark
=> Additional rcS work

src/modules/logger/logger.cpp, src/platforms/px4_defines.h
Thanks to @bkueng for suggesting this change in #9920 !
closes #9920
=> Fix logger signed unsigned error with GCC 7.3 in Cygwin

src/lib/bezier/BezierQuad.cpp, src/lib/bezier/BezierQuad.hpp, src/lib/bezier/CMakeLists.txt, src/lib/mathlib/math/SearchMin.hpp, src/systemcmds/tests/.clang-tidy, src/systemcmds/tests/CMakeLists.txt, src/systemcmds/tests/test_bezierQuad.cpp, src/systemcmds/tests/test_search_min.cpp, src/systemcmds/tests/tests_main.c, src/systemcmds/tests/tests_main.h
This PR adds the bezier library written by @Stifael .
=> Bezier Library

src/drivers/tap_esc/tap_esc.cpp
https://github.com/PX4/Firmware/issues/9984#issuecomment-407629837
=> tap_esc increase stack 1100 -> 1180 bytes

src/modules/px4iofirmware/mixer.h
This allows loading mixers with more inputs.
UNTESTED.
=> Increased mixer load buffer to allow larger mixer structures to fit.

src/modules/commander/commander_params.c
- fixes https://github.com/PX4/Firmware/issues/10028
=> commander parameters fix units

src/lib/FlightTasks/tasks/FlightTask.cpp, src/lib/FlightTasks/tasks/FlightTask.hpp, src/lib/FlightTasks/tasks/FlightTaskManualStabilized.cpp, src/lib/FlightTasks/tasks/FlightTaskManualStabilized.hpp
=> estimataor reset counter: set Flighttask-counter equal reset-counter 

Makefile
Small helper to make it easy to run doxygen.
@mcsauder @hamishwillee 
The current configuration takes quite a long time to generate (many graphs) and the output folder is ~ 1GB. Need to get auto generation and hosting setup. We could probably abuse github pages.
=> Makefile add doxygen helper

ROMFS/px4fmu_common/init.d/rc.axialracing_ax10_apps, ROMFS/px4fmu_common/init.d/rc.axialracing_ax10_defaults, ROMFS/px4fmu_common/init.d/rc.fw_defaults, ROMFS/px4fmu_common/init.d/rc.interface, ROMFS/px4fmu_common/init.d/rc.mc_apps, ROMFS/px4fmu_common/init.d/rc.mc_defaults, ROMFS/px4fmu_common/init.d/rc.sensors, ROMFS/px4fmu_common/init.d/rc.ugv_defaults, ROMFS/px4fmu_common/init.d/rc.vehicle_setup, ROMFS/px4fmu_common/init.d/rcS
Hi,
This PR is whitespace/comment cleanup in the startup scripts.  Hopefully it helps with readability, and if not, no worries, feel free to decline!
Thanks!
-Mark
=> Added full stops to comments and verbosity/prose sentence structure where relevant.

.travis.yml
Needs to be verified before merging. https://travis-ci.org/PX4
=> travis-ci update coverity_scan

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp, src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c, src/modules/gnd_pos_control/GroundRoverPositionControl.cpp
See https://github.com/PX4/ecl/pull/485
=> Pr l1 slew

appveyor.yml
Testing to see if this limits appveyor to pull requests only.
=> appveyor limit branch builds

src/modules/ekf2/ekf2_main.cpp
=> ekf2 fix GPS fix_type comparison

src/drivers/batt_smbus/CMakeLists.txt, src/drivers/batt_smbus/batt_smbus.cpp, src/drivers/batt_smbus/batt_smbus.h, src/drivers/batt_smbus/batt_smbus_i2c.cpp, src/drivers/batt_smbus/batt_smbus_main.cpp
Completely reworked this driver. Changed driver architecture to match other driver templates (e.g. lps22hb). Implemented *most* SMBus protocol functions and made sure they work exactly as described by the SMBus protocol (see http://smbus.org/specs/smbus20.pdf). Enabled writing to device flash via NSH. Supports multiple (i2c-int & i2c-ext) instances of the driver. 
Let me know if you have any questions or concerns!
Thanks, 
Jake
=> Batt smbus driver rework

src/modules/mavlink/mavlink_messages.cpp
Hi
This PR restarts PR #9520 back to essentially the first commit of that PR.  It adds classes for the SCALED_IMU2 and SCALED_IMU3 messages to mavlink_messages.cpp and corrects a sensor_gyro_s variable type.
The hardware I am testing on only has two IMUs and I have not been able to test on hardware with 3 IMUs.  For convenience, below are screen captures from QGC mavlink inspector of the current upstream master and this PR showing the message output by adding SCALED_IMU, SCALED_IMU2, and SCALED_IMU3 to the config stream list of mavlink_main.cpp and connecting via USB to QGC.
The values reported back through SCALED_IMU and SCALED_IMU2 do not seem to be correct, believed to be a driver level bug yet to be resolved.  Up to the present I have been unable to create a working templated …
=> Added classes for SCALED_IMU2 and SCALED_IMU3 to mavlink_messages.cpp.

msg/estimator_status.msg, src/modules/ekf2/ekf2_main.cpp, src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp, src/modules/mavlink/mavlink_messages.cpp
Semi related to https://github.com/PX4/Firmware/issues/9757.
=> estimator_status minor cleanup

Jenkinsfile
Split existing Tests stage into two.
=> Jenkinsfile add new Analysis stage

Jenkinsfile
This will make it easier to monitor everything. @hamishwillee
=> [WIP] Jenkins update Devguide, Userguide, QGC directly from pipeline

src/drivers/distance_sensor/ll40ls/ll40ls.cpp
Hi,
This PR is another mundane one, mostly doxy comments and whitespace formatting along with deprecating `goto` statements with calls to `stop()` and `return;`. The `stop()` method already existed and fulfilled the same calls that the `goto` statements relied on.
Let me know if you have any questions on this PR.  Thanks!
-Mark
=> Doxy documentation and replace goto statements with stop() calls and return statements in ll40ls.cpp.

src/modules/logger/log_writer_file.cpp
https://logs.px4.io/plot_app?log=bdfb66a8-03d8-4f85-a816-0d22ca81ef58
=> logger increase log_writer_file stack 1072 -> 1150

src/modules/mavlink/mavlink_ulog.cpp
- the uorb behavior got recently changed so that we now need to clear any potential existing messages when we start log streaming.
- ulog_stream_ack should also not use a queue, since the ack is done synchonous between mavlink and the logger.
=> mavlink_ulog: clear potential existing ulog_stream messages on start

cmake/configs/nuttx_px4fmu-v2_default.cmake, src/lib/FlightTasks/FlightTasks.cpp, src/lib/FlightTasks/FlightTasks.hpp, src/lib/FlightTasks/tasks/Auto/FlightTaskAuto.cpp, src/lib/FlightTasks/tasks/Auto/FlightTaskAuto.hpp, src/lib/FlightTasks/tasks/FlightTask/FlightTask.cpp, src/lib/FlightTasks/tasks/FlightTask/FlightTask.hpp, src/modules/mc_pos_control/mc_pos_control_main.cpp
Same as #9937, on top of current master.
Could we get this in?
=> Flight Task Avoidance Interface

src/lib/FlightTasks/tasks/Auto/FlightTaskAuto.cpp
=> heading update: do not update heading within NAV_ACC_RAD

src/modules/mc_pos_control/mc_pos_control_main.cpp
The current failure catching doesn't work as the nav state doesn't change and the tasks will be switched every iteration -> vehicle drifts.
I used the vehicle command to let the commander know to switch tasks. Not sure if this will be needed in the long term solution but with the current implementation it's needed.
=> flight task failure catch

Documentation/Doxyfile.in, posix-configs/bbblue/px4.config, posix-configs/bbblue/px4_fw.config, src/drivers/bbblue_adc/CMakeLists.txt, src/drivers/boards/bbblue/board_config.h, src/modules/commander/PreflightCheck.cpp
This PR just fixes up a number of trailing whitespace instances that git complains about.
Let me know if you have any questions on this PR.
-Mark
=> Trailing white space fixes

msg/vehicle_status_flags.msg, src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/commander/commander_helper.cpp, src/modules/commander/commander_params.c, src/modules/commander/commander_tests/state_machine_helper_test.cpp, src/modules/commander/state_machine_helper.cpp, src/modules/commander/state_machine_helper.h
=> commander cleanup battery failsafe handling

Jenkinsfile
=> Jenkins update cppcheck to px4io/px4-dev-base:2018-08-21 (ubuntu 18.04)

Jenkinsfile, Makefile, ROMFS/CMakeLists.txt, ROMFS/px4fmu_common/init.d-posix/1010_iris_opt_flow, ROMFS/px4fmu_common/init.d-posix/1011_iris_irlock, ROMFS/px4fmu_common/init.d-posix/1012_iris_rplidar, ROMFS/px4fmu_common/init.d-posix/1013_iris_vision, ROMFS/px4fmu_common/init.d-posix/1014_solo, ROMFS/px4fmu_common/init.d-posix/1030_plane, ROMFS/px4fmu_common/init.d-posix/1040_standard_vtol, ROMFS/px4fmu_common/init.d-posix/1041_tailsitter, ROMFS/px4fmu_common/init.d-posix/1042_tiltrotor, ROMFS/px4fmu_common/init.d-posix/1060_rover, ROMFS/px4fmu_common/init.d-posix/6011_typhoon_h480, ROMFS/px4fmu_common/init.d-posix/rcS, Tools/run-shellcheck.sh
=> Jenkins add ShellCheck

ROMFS/px4fmu_common/init.d/rc.sensors, src/drivers/distance_sensor/pga460/CMakeLists.txt, src/drivers/distance_sensor/pga460/parameters.c, src/drivers/distance_sensor/pga460/pga460.cpp, src/drivers/distance_sensor/pga460/pga460.h
This merge request is to add support to PX4 for the TI PGA460 Ultrasonic Signal Processor and Transducer Driver.
http://www.ti.com/lit/ds/symlink/pga460.pdf
https://review.px4.io/plot_app?log=961cf7f8-86ab-4d10-a912-77649316446b
=> Distance Sensor Driver: PGA460

src/modules/mc_pos_control/mc_pos_control_main.cpp
bug fix: add reference to parameter
=> mc_pos_control: smooth takeoff requires current position as reference

src/modules/events/send_event.cpp, src/modules/events/send_event.h, src/platforms/px4_module.h
Hi there,
This PR is just doxy commenting where I can fill in a bit of documentation and also providing the framework where I have not completed the documentation.  On that topic, I've listened to arguments in the past that "No documentation is better than incomplete documentation!", but I've never actually seen those arguments pass muster when put to the test in the real world.  In general, I think that when developers see a gap they work to fill it.  I hope this is useful, even if incomplete.
And on that note, if this PR generates the rest of the documentation, excellent!  Let me know what to add.
Let me know if you have questions on this PR!
-Mark
=> Doxy documentation in send_event.h and full stops in send_event.cpp.

src/modules/commander/Commander.cpp
=> commander send_vehicle_command don't ignore cmd argument

.ci/Jenkinsfile-compile, platforms/posix/CMakeLists.txt
For raspberrypi, snapdragon, and ocpoc testing.
=> Jenkins build and archive all packages

msg/vehicle_control_mode.msg, src/modules/commander/Commander.cpp, src/modules/commander/state_machine_helper.cpp, src/modules/commander/state_machine_helper.h
This removes two HITL thing that are, in my opinion, leftover and not needed anymore. See the commits for further info.
=> Remove unused HITL stuff

src/lib/FlightTasks/tasks/FlightTask/FlightTask.hpp, src/modules/logger/logger.cpp, src/modules/mc_pos_control/mc_pos_control_main.cpp
@mrivi could you look at the original issue #10345 and this PR? I'm not sure if it's the right solution, but we need to do something to limit the output. Ideally it would only publish and log noteworthy changes.
- fixes #10345
=> vehicle_trajectory_waypoint limit unnecessary updates and reduce logging

Tools/sitl_run.sh, platforms/posix/cmake/sitl_tests.cmake, posix-configs/SITL/init/test/test_mavlink, posix-configs/SITL/init/test/test_template.in, src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_main.h
@dagar Here you go. Could you review, please?
=> mavlink: moved to ModuleParams

platforms/nuttx/cmake/px4_impl_os.cmake, platforms/nuttx/nuttx-configs/Make.defs.in
This part is safe to merge immediately.
=> nuttx stack check restore

src/modules/mc_pos_control/mc_pos_control_main.cpp
The first waypoint should contain the desired velocity setpoint not the current vehicle velocity.
=> Fix desired trajectory waypoint

Tools/setup/OSX.sh
@dogmaphobic can you run this script on gusmacpro?
=> OSX setup helper install pip python dependencies with sudo

src/modules/mavlink/mavlink_ulog.cpp
This brings https://github.com/PX4/Firmware/pull/10192 to the stable branch.
=> [BACKPORT] mavlink_ulog: clear potential existing ulog_stream messages on start

.ci/Jenkinsfile-SITL_tests, cmake/common/sanitizers.cmake, platforms/posix/cmake/sitl_tests.cmake
- Environment variables for building with asan
- Docker argument for leak sanitizer
- Regex for tests to fail on sanitizer error
Signed-off-by: Lukas Woodtli <woodtli.lukas@gmail.com>
Please use [PX4 Discuss](http://discuss.px4.io/) or [Slack](http://slack.px4.io/) to align on pull requests if necessary.
Logs uploaded to http://logs.px4.io or screenshots.
A clear and concise description of the problem, if any, this feature will solve. E.g. I'm always frustrated when ...
**Additional …
=> Add address sanitizer to SITL pipeline

src/include/unit_test.h, src/modules/mavlink/mavlink_tests/mavlink_ftp_test.cpp
These leaks are not critical but the address-sanitizer complains.
And it's better programming practice anyway.
Signed-off-by: Lukas Woodtli <woodtli.lukas@gmail.com>
Please use [PX4 Discuss](http://discuss.px4.io/) or [Slack](http://slack.px4.io/) to align on pull requests if necessary.
Logs uploaded to http://logs.px4.io or screenshots.
A clear and concise description of the problem, if any, this feature will solve. E.g. I'm always frustrated when ...
Add any other …
=> Fix some test code related leaks

ROMFS/px4fmu_common/init.d-posix/1030_plane, src/drivers/pwm_out_sim/PWMSim.cpp, src/drivers/pwm_out_sim/PWMSim.hpp
=> FW SITL adjust landing throttle

src/drivers/imu/fxos8701cq/fxos8701cq.cpp
The previous removal of the mag was not complete. It just
disabled publishing. This commit conditionally removes all
the the mag functionality.
=> NXPHlite fxos8701cq:Fully remove the mag to facilitate calibration

ROMFS/px4fmu_common/init.d/rc.sensors
@dk7xe  please test with your hardware.
=> NXPHlite:rc.sensors start lis3mdl

ROMFS/px4fmu_common/init.d/rc.interface, ROMFS/px4fmu_common/init.d/rc.vtol_defaults
Hi there,
I think this PR will correct the issue observed by @rolandash with the deprecation of PWM_ACHDIS.
@rolandash , could you please advise if this is the correct fix?  Thanks!
-Mark
=> Correct PWM_AUX behavior.

ROMFS/px4fmu_common/init.d/13013_deltaquad, ROMFS/px4fmu_common/init.d/4070_aerofc, ROMFS/px4fmu_common/init.d/rc.mavlink, Tools/serial/generate_config.py
This should give us flexibility going forward and make deciphering configuration from parameters easy.
PR on top of https://github.com/PX4/Firmware/pull/10337
=> serial generate config add 10 generic serial ports

.ci/Jenkinsfile-SITL_tests, CMakeLists.txt, Makefile, cmake/common/sanitizers.cmake
- add to CMAKE_BUILD_TYPE options
- handle environment variable helpers outside of CMake
- ASan add minor optimization
- cleanup whitespace
@LukasWoodtli could you review?
=> sanitizer cleanup

msg/templates/px4/ros/msg.h.template, msg/templates/px4/uorb/msg.h.template, msg/templates/uorb/msg.cpp.template, msg/templates/uorb/msg.h.template, msg/templates/uorb/uORBTopics.cpp.template, msg/templates/uorb_microcdr/microRTPS_client.cpp.template, msg/templates/uorb_microcdr/msg.cpp.template, msg/templates/uorb_microcdr/msg.h.template, msg/templates/uorb_microcdr/uORBTopics.cpp.template, msg/templates/urtps/Publisher.cpp.template, msg/templates/urtps/Publisher.h.template, msg/templates/urtps/RtpsTopics.cpp.template, msg/templates/urtps/RtpsTopics.h.template, msg/templates/urtps/Subscriber.cpp.template, msg/templates/urtps/Subscriber.h.template, msg/templates/urtps/microRTPS_agent.cpp.template, msg/tools/generate_microRTPS_bridge.py, msg/tools/px_generate_uorb_topic_files.py, msg/tools/px_generate_uorb_topic_helper.py, src/modules/micrortps_bridge/micrortps_client/CMakeLists.txt
This addresses @bkueng request, which passes the RTPS ID mapping as a global variable to EmPy instead of doing a yaml file reading on each template.
=> msg: RTPS: pass RTPS ID msg definition file as an EmPy global var

msg/tools/generate_microRTPS_bridge.py, msg/tools/px_generate_uorb_topic_helper.py, msg/tools/uorb_rtps_message_ids.yaml
While we don't find a correct way of auto generating these ID's, we should at least add ID's to all the uORB topics available and its aliases for multi-topics.
=> update RTPS msg ID's

platforms/posix/CMakeLists.txt, platforms/posix/src/main.cpp, platforms/posix/src/px4-alias.sh_in
see https://github.com/PX4/DriverFramework/pull/229
fixes https://github.com/PX4/Firmware/issues/10342
=> Bebop 2: repair startup scripts, upload script and mpu6050 driver

src/modules/mc_pos_control/mc_pos_control_main.cpp
- use ModuleBase class
- limit the printf's to to only print when an failure state is entered
=> MC position controller cleanup

src/modules/land_detector/LandDetector.cpp, src/modules/land_detector/LandDetector.h, src/modules/land_detector/MulticopterLandDetector.cpp
- cleanup subscriptions & publications 
- move _parameterSub to the right place
Fixes #10593
=> Land detector cleanup fixes

integrationtests/python_src/px4_it/mavros/mission_test.py
Temporary work around for CI sanity until https://github.com/PX4/Firmware/issues/10590 can be resolved properly.
=> misison test increase landed timeout 60s -> 120s

.ci/Jenkinsfile-SITL_tests, cmake/common/sanitizers.cmake
Also some general minor sanitizer improvements.
Please use [PX4 Discuss](http://discuss.px4.io/) or [Slack](http://slack.px4.io/) to align on pull requests if necessary.
Logs uploaded to http://logs.px4.io or screenshots.
A clear and concise description of the problem, if any, this feature will solve. E.g. I'm always frustrated when ...
Add any other context or screenshots for the feature request here.
=> Improve the use of ubsan in SITL pipeline

README.md, msg/radio_status.msg, msg/templates/urtps/msg.idl.template, msg/tools/generate_microRTPS_bridge.py, msg/tools/px_generate_uorb_topic_helper.py, msg/tools/uorb_rtps_classifier.py, msg/tools/uorb_rtps_message_ids.yaml, src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/micrortps_bridge/CMakeLists.txt, src/modules/micrortps_bridge/micrortps_client/CMakeLists.txt
This is an ongoing work in order to classify the uORB topics depending on if we want them to be published to the RTPS stream, subscribed (or both) and ignored ("unclassified").
This replaces the CMake set of the topics to send and receive and reads the yaml description file and gets which topics are classified in which category.
TODO:
```bash
Traceback (most recent call last):
File "/home/nuno/PX4/Firmware/msg/tools/generate_microRTPS_bridge.py", line 333, in <module>
generate_agent(agent_out_dir)
File "/home/nuno/PX4/Firmware/msg/tools/generate_microRTPS_bridge.py", line 247, in generate_agent
package, px_generate_uorb_topic_files.INCL_DEFAULT, classifier.msg_id_map, uRTPS_AGENT_TEMPL_FILE)
File "/home/nuno/PX4/Firmware/msg/tools/px_generate_uorb_topic_files.py", line 215, in …
```
=> RTPS: classify msgs as "send", "receive" or "ignore"

platforms/posix/cmake/sitl_target.cmake
This follows the change in https://github.com/PX4/sitl_gazebo/pull/236.
=> sitl_gazebo: build with SEND_VISION_ESTIMATION_DATA set

Jenkinsfile
https://github.com/PX4/Firmware/issues/10678
e.g. http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2FFirmware/detail/PR-10414/8/pipeline
Retry the step (up to 3 total runs).
Retry a different amount of times?
I also moved the `make distclean` steps to `post` conditions which are guaranteed to execute regardless of build stage result.
=> jenkins: clang tidy retry

src/lib/FlightTasks/tasks/FlightTask/FlightTask.cpp, src/lib/FlightTasks/tasks/FlightTask/FlightTask.hpp
follow up of the discussion about Stabilized and local-position topic requirement.
=> FlightTask don't require vehicle-local-positiion topic

src/drivers/distance_sensor/pga460/pga460.cpp, src/drivers/distance_sensor/pga460/pga460.h
Removed `px4_poll` and the stupid `while` loop I was using. Pulled upstream and something broke it, but it was a bad implementation in the first place. If anyone wants to suggest a better implementation I am happy for suggestions, otherwise feel free to merge. Also did a little bit more housekeeping around the file.
=> PGA460 cleanup

ROMFS/px4fmu_common/init.d/4250_teal
We've finally launched, so here it is! Let me know if you have any questions, thanks!
=> TealOne airframe config file

src/lib/mathlib/CMakeLists.txt, src/lib/mathlib/math/filter/LowPassFilter2p.cpp, src/lib/mathlib/math/filter/LowPassFilter2p.hpp, src/lib/mathlib/math/filter/LowPassFilter2pVector3f.cpp, src/lib/mathlib/math/filter/LowPassFilter2pVector3f.hpp, src/modules/mc_att_control/mc_att_control.hpp, src/modules/mc_att_control/mc_att_control_main.cpp
=> mathlib: add Vector3f low pass filter

ROMFS/px4fmu_common/init.d/rc.mavlink
The TX2 serial port doesn't seem to like 921600.
=> rc.mavlink AV-X reduce companion baudrate

src/modules/fw_pos_control_l1/fw_pos_control_l1_params.c
Additional information is from the landing docs: https://docs.px4.io/en/flying/fixed_wing_landing.html#FW_LND_USETER
=> Add additional info to FW_LND_USETER

ROMFS/px4fmu_common/init.d/rc.sensors
@igalloway - plase test this with your HW. If it works we will merge it.
=> [DO NOT MERGE] nxphlite-v3:Add HolyBro GPS on I2C 2 using ist8310

msg/vehicle_trajectory_waypoint.msg
Fixes a typo in msg definition.
=> TRAJECTORY message renamed

platforms/posix/src/px4_daemon/client.cpp, platforms/posix/src/px4_daemon/server.cpp
=> Fix Posix daemon/client on Mac.

platforms/posix/cmake/sitl_tests.cmake, posix-configs/SITL/init/test/test_shutdown
Kind of lame, but at least makes sure these do something.
=> [WIP] add simple SITL shutdown test

Tools/uorb_graph/create.py, msg/vehicle_attitude_setpoint.msg, msg/vehicle_rates_setpoint.msg, src/examples/rover_steering_control/main.cpp, src/modules/fw_att_control/FixedwingAttitudeControl.cpp, src/modules/fw_att_control/FixedwingAttitudeControl.hpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/gnd_att_control/GroundRoverAttitudeControl.cpp, src/modules/gnd_pos_control/GroundRoverPositionControl.cpp, src/modules/mavlink/mavlink_messages.cpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mc_att_control/mc_att_control.hpp, src/modules/mc_att_control/mc_att_control_main.cpp, src/modules/mc_pos_control/Utility/ControlMath.cpp, src/modules/mc_pos_control/mc_pos_control_main.cpp, src/modules/navigator/gpsfailure.cpp, src/modules/vtol_att_control/standard.cpp, src/modules/vtol_att_control/standard.h, src/modules/vtol_att_control/tailsitter.cpp, src/modules/vtol_att_control/tailsitter.h, src/modules/vtol_att_control/tiltrotor.cpp, src/modules/vtol_att_control/tiltrotor.h, src/modules/vtol_att_control/tiltrotor_params.c, src/modules/vtol_att_control/vtol_att_control_main.cpp, src/modules/vtol_att_control/vtol_att_control_main.h, src/modules/vtol_att_control/vtol_att_control_params.c, src/modules/vtol_att_control/vtol_type.h, src/systemcmds/tests/test_controlmath.cpp
=> VTOL rate control improvements

src/modules/fw_att_control/FixedwingAttitudeControl.cpp, src/modules/fw_att_control/FixedwingAttitudeControl.hpp, src/modules/vtol_att_control/vtol_att_control_params.c
- fixes https://github.com/PX4/Firmware/issues/10896
=> remove unused VT_AIRSPD_RULE

Makefile, Tools/sitl_run.sh
@seanrowens @mrpollo please give this a try.
=> Makefile handle spaces in path

src/drivers/boards/px4fmu-v5/timer_config.c
Remove old comment that does not apply.
=> px4fmu-v5:Remove old comment

Tools/astyle/files_to_check_code_style.sh, src/modules/commander/Commander.cpp, src/modules/commander/PreflightCheck.cpp, src/modules/commander/accelerometer_calibration.cpp, src/modules/commander/airspeed_calibration.cpp, src/modules/commander/arm_auth.cpp, src/modules/commander/calibration_routines.cpp, src/modules/commander/calibration_routines.h, src/modules/commander/commander_helper.cpp, src/modules/commander/commander_tests/state_machine_helper_test.cpp, src/modules/commander/esc_calibration.cpp, src/modules/commander/esc_calibration.h, src/modules/commander/failure_detector/FailureDetector.cpp, src/modules/commander/gyro_calibration.cpp, src/modules/commander/mag_calibration.cpp, src/modules/commander/state_machine_helper.cpp
Commander is the last PX4 module that was exempt for code style enforcement. The transition is a bit messy, but this should ultimately help make things a bit easier going forward. Let's just get it over with.
=> commander fix and enforce code style

boards/px4/sitl/default.cmake, src/drivers/tone_alarm_sim/CMakeLists.txt, src/drivers/tone_alarm_sim/tone_alarm.cpp
- fixes #10925
```console
pxh> tune_control play -t 2
INFO  [tune_control] Publishing standard tune 2
```
=> tone_alarm_sim readd to sitl and drop DriverFramework

.ci/Jenkinsfile-SITL_tests, .ci/Jenkinsfile-compile, .ci/Jenkinsfile-hardware, Jenkinsfile
This is the number of builds kept for a branch or pull request.
PX4/Firmware master for example - http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-compile/activity?branch=master
=> Jenkins reduce number of builds kept (10 -> 5)

Tools/setup/OSX.sh, Tools/setup/requirements.txt
* Updates `requirements` list;
* Adds options to install sim tools and to reinstall the formulas
Tested on the `dronecode macmini` CI machine.
=> Update MacOSX install script

boards/px4/fmu-v5/src/init.c, boards/px4/fmu-v5/src/timer_config.c, src/drivers/kinetis/drv_led_pwm.cpp, src/drivers/stm32/drv_led_pwm.cpp
If the BOARD_HAS_CONTROL_STATUS_LEDS is set the status LED will
not be PWM controlled.
UI LED will always be PWM controlled.
=> pwm led coexist

src/modules/mc_pos_control/mc_pos_control_main.cpp
SITL jMAVsim testing on my machine.
There is some basic refactoring in the position controller I wanted to do for a long time now. The goal is to make it all more readable and modular and less error prone.
A big chunk of work was introduced with https://github.com/PX4/Firmware/pull/9731 but the whole project is not finished and not all goals are achieved yet. I'll follow up with more cleanups.
=> Position Control Module Initialization Cleanup

.gitignore, .vscode/cmake-kits.json, .vscode/cmake-variants.yaml, .vscode/extensions.json, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json
[Visual Studio Code](https://code.visualstudio.com/) with a few key plugins and a proper in tree configuration (this PR) is a close to perfect cross platform IDE option for PX4 development.
- perfect cmake integration
- driven by gui, but in sync with regular command line actions
- build, debug, test in IDE
- IDE uses actual build and current configuration to resolve symbols
- includes generated pieces like uORB messages
- debugging targets available from gui (defined in .vscode)
- embedded debugging (jlink, blackmagic, openocd)
- uses optional SVD file (like MCU Eclipse https://gnu-mcu-eclipse.github.io/ or commercial options)
TODO: 
- get all PX4 config and debug targets working
- embedded debug helpers (SVD files, jlink integration)
- simple setup instructions and usage instructions
- …
=> [WIP] vscode configuration

.vscode/cmake-kits.json, .vscode/cmake-variants.yaml, .vscode/extensions.json, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, platforms/posix/cmake/sitl_target.cmake
Debugging with GDB integrated and working well. Needs to be expanded to support all models and different simulators.
=> vscode update targets and gdb debugging

src/lib/parameters/CMakeLists.txt
Needed to keep Snapdragon parameters in sync. https://github.com/PX4/Firmware/issues/9971#issuecomment-444580245
@karliss FYI
=> parameters also include all module configs when scoping disabled

ROMFS/px4fmu_common/init.d-posix/rcS, src/modules/logger/logger.cpp, src/modules/logger/logger.h, src/modules/logger/params.c
Keeps things more modular.
@mrivi @baumanta fyi
=> Logger: add separate vision/avoidance profile

integrationtests/tests/configs/RTL_testing.yml, integrationtests/tests/run_tests.py, integrationtests/tests/test_runner.sh
Since it could be that a maneuver generates several log files, we want run the tests against all of them. This is done with this PR.
=> Integration testing ulog

src/modules/commander/Commander.cpp
=> commander set home position timestamp properly

.ci/Jenkinsfile-SITL_tests
Might be useful for users wanting to try SITL without building everything.
=> Jenkins archive SITL package

.ci/Jenkinsfile-SITL_tests, .ci/Jenkinsfile-compile, Jenkinsfile
=> CI: update container tags to '2019-01-01'

ROMFS/px4fmu_common/init.d/airframes/4041_beta75x
I went through the process of flashing PX4 on my BetaFPV 2S Whoop and had to make a few adjustments to make it fly properly.
=> 2S BetaFPV Whoop - Adjust config file

.github/stale.yml
Something that does this and actually works would still be quite helpful.
Trying again with a simpler configuration. Unless I'm missing something, there doesn't seem to be anyway to debug these "apps" without self hosting.
https://probot.github.io/apps/stale/
=> Probot attempt to fix configuration

boards/px4/raspberrypi/src/board_config.h
Simply added two definitions to pass the compilation from px4_raspberry_cross
=> Added two definitions to pass the compilation on raspi.

Tools/ecl_ekf/batch_process_metadata_ekf.py
There is a small bug where we try to close a plot and save figure without open them first.
=> Fixed small bug in batch_process_metadata_ekf.py

.gitignore, Jenkinsfile, msg/ros/actuator_controls_0.msg, msg/ros/actuator_controls_virtual_mc.msg, msg/tools/uorb_to_ros_msgs.py
This PR aims to create a Jenkins stage that allows auto generation and deployment of the uORB msg counterparts in ROS, with the deploy being done in [`px4_msgs`](https://github.com/PX4/px4_msgs).
The purpose is that  [`px4_msgs`](https://github.com/PX4/px4_msgs) has all the required and updated message definitions to build it as a standard package that can be used on ROS2 or ROS1, being [`px4_ros_com`](https://github.com/PX4/px4_ros_com), for now, the main target for this package.
=> Jenkins: set autobuild and deploy for generating px4_msgs repo ROS msg definitions files

.ci/Jenkinsfile-compile, .ci/Jenkinsfile-hardware, Jenkinsfile, Tools/docker_run.sh
This updates everything except ROS, arch, snapdragon, clang.
=> update docker containers to 2019-01-27

src/drivers/barometer/mpl3115a2/mpl3115a2.cpp
As reported by @LeoMustafaNXP in https://github.com/PX4/Firmware/issues/11296
=> Increase oversampling rate for MPL3115A2 pressure sensor

ROMFS/CMakeLists.txt, platforms/nuttx/CMakeLists.txt
These are minor annoyances that cause unnecessary rebuilding.
=> cmake fix two small build dependency issues

ROMFS/px4fmu_common/init.d-posix/1031_plane_cam
https://github.com/PX4/sitl_gazebo/pull/273
=> startup: add plane_cam

Jenkinsfile, msg/tools/uorb_to_ros_rtps_ids.py
This PR aims to implement auto deployment of the required tools for [`px4_ros_com`](https://github.com/PX4/px4_ros_com) to build the micro-RTPS bridge.
=> Jenkins CI: PX4 ROS2: deploy required tools

.ci/Jenkinsfile-SITL_tests_coverage, Jenkinsfile
A bit wasteful to nearly duplicate Jenkinsfile-SITL_tests, but this gets coverage running side by side.
=> Jenkins add SITL tests coverage pipeline

msg/estimator_status.msg
Update estimator_status message to match the implementation in ECL.
More info [here](https://github.com/PX4/ecl/pull/550#issuecomment-453870034)
This should be merged at the same time ECL is updated
=> msg: add gps_yaw and mag_aligned to estimator_status

src/modules/navigator/loiter.h, src/modules/navigator/mission.h, src/modules/navigator/mission_block.cpp, src/modules/navigator/mission_block.h, src/modules/navigator/navigator.h, src/modules/navigator/navigator_main.cpp
Fixing a few minor things as I encounter them.
=> navigator minor cleanup

src/modules/ekf2/ekf2_main.cpp
https://github.com/PX4/Firmware/issues/9371
=>  EKF2 always use IMU timestamp as now

cmake/px4_add_common_flags.cmake, src/lib/mathlib/math/Limits.hpp
- cleanup Limits.hpp
- add -Waddress-of-packed-member where available
- fixes #11408
=> mathlib Limits don't bother using references

Jenkinsfile, src/modules/mavlink/mavlink_messages.cpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/simulator/simulator_mavlink.cpp
- also requires minor changes in ODOMETRY
(https://mavlink.io/en/messages/common.html#ODOMETRY)
- enabling `-Waddress-of-packed-member` is a precaution related to https://github.com/PX4/Firmware/issues/11408
- https://github.com/ArduPilot/pymavlink/pull/267
=> update mavlink to latest with addr of packed fix

.ci/Jenkinsfile-SITL_tests, .ci/Jenkinsfile-SITL_tests_coverage
- waiting for https://github.com/PX4/Firmware/issues/11380
Currently working on a fix, but in the meantime these failures are distracting in every PR.
=> Jenkins SITL tests temporarily disable FW test

.ci/Jenkinsfile-SITL_tests, .ci/Jenkinsfile-SITL_tests_coverage, .ci/Jenkinsfile-compile, .ci/Jenkinsfile-hardware, Jenkinsfile, Tools/docker_run.sh
Includes everything except for px4-dev-snapdragon.
=> update px4 dev containers to 2019-02-09

src/modules/simulator/simulator.h, src/modules/simulator/simulator_mavlink.cpp
~~- fixes https://github.com/PX4/Firmware/issues/11380~~
=> simulator mavlink don't send_controls() until ready

Jenkinsfile
Same as what was done in https://github.com/PX4/Firmware/pull/11313, but now for the `ros1` branch.
=> Jenkins CI: PX4 ROS msgs stage: deploy message definitions to the 'ros1' branch of 'px4_msgs'

msg/templates/urtps/microRTPS_transport.cpp, msg/templates/urtps/microRTPS_transport.h
Rebased version of https://github.com/PX4/Firmware/pull/8152 by @gamoreno.
=> #8152 rebased - urtps: fix UART speed setting to work in Linux

src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/sensors/rc_params.c
=> commander auto disarm if kill switch engaged for 5 seconds

src/drivers/kinetis/tone_alarm/ToneAlarmInterface.cpp, src/drivers/px4fmu/fmu.cpp, src/drivers/stm32/tone_alarm/ToneAlarmInterface.cpp, src/modules/commander/PreflightCheck.cpp, src/modules/events/send_event.cpp, src/modules/land_detector/LandDetector.cpp, src/modules/px4iofirmware/mixer.cpp, src/modules/uORB/uORB_tests/uORBTest_UnitTest.cpp, src/modules/vmount/input_mavlink.cpp, src/modules/vmount/input_rc.cpp, src/modules/vmount/input_test.cpp, src/modules/vmount/output_mavlink.cpp, src/modules/vmount/vmount.cpp, src/platforms/posix/drivers/df_bebop_bus_wrapper/df_bebop_bus_wrapper.cpp, src/platforms/px4_defines.h, src/systemcmds/tests/test_float.cpp, src/systemcmds/tests/test_mathlib.cpp, src/systemcmds/tests/test_microbench_math.cpp, src/systemcmds/tests/test_parameters.cpp, src/systemcmds/tests/test_search_min.cpp, src/systemcmds/tests/test_smooth_z.cpp
A single consistent PX4_ISFINITE for all platforms with testing.
=> PX4_ISFINITE use builtin everywhere

src/modules/mc_att_control/mc_att_control_main.cpp
Problem description at:
http://discuss.px4.io/t/multicopter-lock-if-primary-gyro-fails/9685
Please use [PX4 Discuss](http://discuss.px4.io/) or [Slack](http://slack.px4.io/) to align on pull requests if necessary.
Logs uploaded to http://logs.px4.io or screenshots.
A clear and concise description of the problem, if any, this feature will solve. E.g. I'm always frustrated when ...
Add any other context or screenshots for the feature request here.
=> Failover in case of gyroscope failure

Tools/astyle/check_code_style_all.sh, Tools/astyle/files_to_check_code_style.sh, Tools/astyle/pre-commit, Tools/check_submodules.sh, Tools/serial/rc.serial.jinja, Tools/serial/rc.serial_port.jinja, Tools/setup/ubuntu.sh, Tools/sitl_run.sh, Tools/upload.sh
None
Shellscript style consistency.
https://unix.stackexchange.com/questions/48805/semicolon-in-conditional-structures
=> Tools: fix style consistency in shell scripts "if [...]; then"

src/lib/FlightTasks/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.hpp, src/lib/FlightTasks/tasks/ManualPositionSmoothVel/FlightTaskManualPositionSmoothVel.hpp, src/lib/FlightTasks/tasks/Utility/VelocitySmoothing.hpp
Coverity scan is running again.
=> FlightTasks minor coverity fixes

src/modules/vmount/output.cpp
The wrap (second commit) is successfully tested, the refactor (first commit) not, please review.
Yaw output was able to reach outside of the [-180°, 180°] range.
=> Fix ROI yaw wrapping

.ci/Jenkinsfile-hardware
The Jenkins slave is will now have the gdb started in the background.
=> Jenkins HIL test updates

.ci/Jenkinsfile-hardware
- add pixhack-v3 to Jenkins
- includes generic px4_fmu-v3_efault and pixhack-v3
- add pixhawk 3 pro (px4_fmu-v4pro)
=> WIP: Jenkins add more hardware

.ci/Jenkinsfile-hardware
Until https://github.com/PX4/Firmware/pull/11554 is under control.
=> Jenkins hardware test temporarily disable px4_fmu-v5_stachcheck tests

src/modules/mavlink/mavlink_receiver.h
This PR adds full stops and makes a few minor edits to comments in mavlink_receiver.h
This should be the last easy step to simplify the diff of #11274.
Let me know if you have any questions on this PR!
-Mark
@dagar
=> Format and edit a few comments in mavlink_receiver.h.  - (Break apart PR#11274 into easily verifiable steps - Step 4) 

CONTRIBUTING.md
Follow on from #11566
The link was good but the "root" is likely to change from master, so this is a better long term option.
=> CONTRIBUTING:Fix up code.html link to goto master

.ci/Jenkinsfile-SITL_tests, .ci/Jenkinsfile-SITL_tests_ASan, .ci/Jenkinsfile-SITL_tests_coverage, .ci/Jenkinsfile-compile, .ci/Jenkinsfile-hardware, Jenkinsfile, Tools/docker_run.sh
Docker hub is still building, but lets begin testing the new tag https://github.com/PX4/containers/releases/tag/2019-03-08
I'll re-trigger Jenkins later after Docker hub gets done, then probably grind it few times.
=> jenkins: update all image tags to 2019-03-08

Jenkinsfile
=> Jenkins re-enable Catkin and Colcon builds

cmake/px4_add_common_flags.cmake, src/modules/mavlink/mavlink_parameters.cpp
- https://github.com/ArduPilot/pymavlink/pull/268
- https://github.com/ArduPilot/pymavlink/pull/267
=> mavlink update to latest and enable address-of-packed-member warning

src/drivers/barometer/bmp280/CMakeLists.txt, src/drivers/distance_sensor/leddar_one/CMakeLists.txt, src/drivers/distance_sensor/sf0x/CMakeLists.txt, src/drivers/distance_sensor/vl53lxx/CMakeLists.txt, src/drivers/imu/adis16448/CMakeLists.txt, src/drivers/imu/bmi055/CMakeLists.txt, src/lib/parameters/flashparams/CMakeLists.txt
This PR just fixes up whitespace git hook complaints shown below.
Let me know if you have any feedback on this PR! Thanks!
-Mark
=> Whitespace fixes to quiet git hook.

src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp, src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
Continuation of https://github.com/PX4/Firmware/pull/11738
=> fw_pos_control_l1 reset internal takeoff and landing state when arming

src/lib/FlightTasks/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.cpp
revert https://github.com/PX4/Firmware/pull/11772
=> revert FlightTasks: fix mission DO_CHANGE_SPEED

ROMFS/CMakeLists.txt, platforms/nuttx/NuttX/CMakeLists.txt, platforms/nuttx/cmake/Toolchain-arm-none-eabi.cmake
Possible fix for https://github.com/PX4/Firmware/issues/11734.
=> cmake fix NuttX and ROMFS build dependencies

src/modules/logger/logger.cpp
https://review.px4.io/plot_app?log=0162574a-1a34-4465-9d32-6d4aa4c0a0af
=> logger increase stack 3600 -> 3700 bytes

Tools/check_submodules.sh, appveyor.yml
Follow-up to #11802 further cleaning up:
- remove commented submodule fetching
- remove unnecessary leftovers from early appveyor CI tests
- make all CI update submodules in parallel
=> Appveyor cleanup

.vscode/extensions.json
https://marketplace.visualstudio.com/itemdetails?itemName=Uavcan.dsdl
@pavel-kirienko FYI
=> vscode add uavcan.dsdl to recommend extensions

boards/airmind/mindpx-v2/init/rc.board_sensors, boards/auav/x21/init/rc.board_sensors, boards/nxp/fmuk66-v3/init/rc.board_sensors, boards/px4/fmu-v3/init/rc.board_sensors, boards/px4/fmu-v4/init/rc.board_sensors, boards/px4/fmu-v4pro/init/rc.board_sensors, boards/px4/fmu-v5/init/rc.board_sensors
@copterspace can you test this please?
fixes https://github.com/PX4/Firmware/issues/11736
=> rc.board_sensors: probe for external qmc5883

src/modules/simulator/accelsim/accelsim.cpp, src/modules/simulator/airspeedsim/meas_airspeed_sim.cpp, src/modules/simulator/barosim/baro.cpp, src/modules/simulator/gyrosim/gyrosim.cpp, src/modules/simulator/simulator_mavlink.cpp
CI SITL tests.
This PR cherry picks the simulator directory work from @dagar's PR #9756 to advance a portion of that work and decrease work remaining in that [WIP] PR.
@dagar 
Let me know if you have any other feedback on this PR. Thanks!
-Mark
=> Cherry pick `src/modules/simulator/` directory changes from PR #9756

src/drivers/barometer/bmp280/bmp280.cpp, src/drivers/barometer/bmp280/bmp280.h
fix the definition misspelling from BPM280 to BMP280
=> bmp280_fix_misspelling

src/lib/FlightTasks/tasks/Auto/FlightTaskAuto.cpp
Follow up to #11904 addressing my review comments.
As discussed with @bresch I'm additionally checking that both previous and current yaw setpoint are not `NAN` otherwise the whole calculation can get `NAN` spoiled. Not that the case where a task generates a sequence of setpoints like Yaw = [Pi, NaN, -Pi] is not covered. This is not to be expected and we'd need another approach to limit the rate in this case.
I made a yaw circle consisting of 3 goto waypoints both CW and CCW with 10°/s max in SITL:
And checked the yawspeed to constrain correctly with hardcoded "unit tests".
=> FlightTaskAuto: revisit yaw rate limit

ROMFS/px4fmu_common/init.d/rcS
Just a quick PR that fixes multiple "set IO_PRESENT" in rcS.
FYI @MaEtUgR
=> rcS: Fix multiple set IO_PRESENT.

Makefile
See https://github.com/mavlink/qgroundcontrol/issues/7360
=> Add nxp_fmuk66-v3 to QGC deploy

boards/px4/fmu-v2/fixedwing.cmake, boards/px4/fmu-v2/multicopter.cmake, boards/px4/fmu-v2/rover.cmake, boards/px4/fmu-v5/fixedwing.cmake, boards/px4/fmu-v5/multicopter.cmake, boards/px4/fmu-v5/rover.cmake
=> fmu-v2 & fmu-v5 add missing tone_alarm to example board variants

Tools/astyle/files_to_check_code_style.sh, msg/templates/urtps/microRTPS_agent_CMakeLists.txt.template, msg/templates/urtps/microRTPS_transport.cpp, msg/templates/urtps/msg.idl.template, msg/tools/generate_microRTPS_bridge.py
Fixes https://github.com/PX4/Firmware/issues/11816. Also, makes the template closer to the output of https://github.com/ros2/rosidl_dds/blob/master/rosidl_generator_dds_idl/resource/msg.idl.em.
@virtualclone FYI.
=> IDL generation: fix constants; improve template

src/lib/tunes/tunes.cpp, src/lib/tunes/tunes.h
fixes custom commands, like: `tune_control play -m MFT200CDEFGAB`
fixes https://github.com/PX4/Firmware/issues/12059
=> fix tunes: make sure a custom tune gets played

.vscode/extensions.json
=> vscode add linker script extension to recommended

boards/nxp/fmuk66-v3/init/rc.board_sensors, src/drivers/imu/fxas21002c/CMakeLists.txt, src/drivers/imu/fxas21002c/FXAS21002C.cpp, src/drivers/imu/fxas21002c/FXAS21002C.hpp, src/drivers/imu/fxas21002c/fxas21002c.cpp, src/drivers/imu/fxas21002c/fxas21002c_main.cpp, src/lib/drivers/accelerometer/PX4Accelerometer.hpp, src/lib/drivers/barometer/PX4Barometer.hpp, src/lib/drivers/gyroscope/PX4Gyroscope.hpp, src/lib/drivers/magnetometer/PX4Magnetometer.hpp
@PX4/testflights could you quick this is a quick flightest on an NXPhlite (nxp_fmuk66-v3)?
=> fxas21002c move to PX4Gyroscope and cleanup

src/modules/simulator/simulator_mavlink.cpp
The "len" variable was not defined and gave me an error, declaring it as "int" fixed it
=> Fixing missing declaration

integrationtests/python_src/px4_it/util/manual_input.py, msg/offboard_control_mode.msg, msg/vehicle_control_mode.msg, src/modules/commander/Commander.cpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mc_att_control/mc_att_control_main.cpp
Direct copy of #10892 with the commits untangled and trailing whitespaces removed.
=> RPYrT Support by Pedro-Roque

msg/collision_constraints.msg, src/lib/CollisionPrevention/CollisionPrevention.cpp, src/lib/CollisionPrevention/CollisionPrevention.hpp, src/lib/CollisionPrevention/collisionprevention_params.c, src/lib/FlightTasks/tasks/ManualPosition/FlightTaskManualPosition.cpp
The collision prevention as it was implemented so far is a heuristic approach not considering the acceleration limits of the airframe. This led to problems when running it on a larger, heavier vehicle as it was not able to stop in time.
This PR rewrites the the collision prevention algorithm. The maximum admissible velocity in each range bin direction is calculated such that it conforms with the maximum acceleration of the vehicle and enables it to stop at the correct distance. Also the axis constraints were removed such that the algorithm reacts symmetrical independent of the coordinate system axes.
SITL tests showed a much nicer behavior. The the drone was more stable in front of the obstacle and it kept the specified distance practically independent on the velocity with which the …
=> Collision prevention dynamics

src/modules/land_detector/FixedwingLandDetector.cpp, src/modules/land_detector/FixedwingLandDetector.h, src/modules/land_detector/LandDetector.cpp, src/modules/land_detector/LandDetector.h, src/modules/land_detector/MulticopterLandDetector.cpp, src/modules/land_detector/MulticopterLandDetector.h, src/modules/land_detector/RoverLandDetector.cpp, src/modules/land_detector/RoverLandDetector.h, src/modules/land_detector/VtolLandDetector.cpp, src/modules/land_detector/VtolLandDetector.h
Requires #12040 before merging.
=> land_detector move orb subscriptions to uORB::Subscription

src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/commander/accelerometer_calibration.cpp
Requires https://github.com/PX4/Firmware/pull/12040 before merging.
=>  commander move most orb subscriptions to uORB::Subscription

src/drivers/batt_smbus/batt_smbus.cpp, src/drivers/batt_smbus/batt_smbus.h
=> batt_smbus move to new WQ

src/platforms/common/px4_work_queue/WorkQueueManager.hpp
https://review.px4.io/plot_app?log=1fdeec0d-604f-473f-8e63-e40ff6e5d316
=> WQ increase stacks from 1200 to 1250 bytes

src/drivers/imu/mpu9250/MPU9250_mag.cpp, src/drivers/imu/mpu9250/MPU9250_mag.h, src/drivers/imu/mpu9250/mpu9250.cpp, src/drivers/imu/mpu9250/mpu9250.h
=> mpu9250 delete unused perf counters

boards/px4/fmu-v4/init/rc.board_sensors, src/drivers/barometer/bmp280/bmp280.cpp
=> Fix bmp280 on FMUv4

src/drivers/heater/heater.cpp, src/drivers/heater/heater.h
=> heater move to new WQ and uORB::Subscription

src/lib/drivers/magnetometer/PX4Magnetometer.cpp
- fixes #12193
@Tony3dr can you try this PR?
=>  PX4Magnetometer implement MAGIOCGSCALE (copy out scale)

src/modules/sensors/rc_update.cpp, src/modules/sensors/rc_update.h, src/modules/sensors/sensors.cpp
Moving `VotedSensorsUpdate` (where the main data is aggregated and choosen) will take a bit more effort later.
=> sensors partially move to new uORB::Subscription

src/drivers/distance_sensor/leddar_one/leddar_one.cpp, src/drivers/heater/heater.cpp, src/modules/logger/logger.cpp, src/modules/mc_att_control/mc_att_control_main.cpp, src/modules/mc_pos_control/mc_pos_control_main.cpp, src/modules/navigator/navigator_main.cpp, src/modules/vmount/vmount.cpp, src/systemcmds/led_control/led_control.cpp, src/systemcmds/tune_control/tune_control.cpp, src/templates/module/module.cpp
I'm not sure why, but astyle seems to stop processing once it hits our module descriptions (R"DESCR_STR). Unless someone feels inclined to dig into the root cause I propose we simply make a reasonable effort to keep these closer to the bottom of each file and still get most of the benefit.
=> astyle chokes on module descriptions

.vscode/launch.json
=> vscode launch.json add nxp_fmuk66-v3

.ci/Jenkinsfile-hardware, Tools/HIL/run_tests.py
These need to be wrapped in a proper test harness, but at least it gets them running on all hardware.
=> Jenkins HIL run more tests

.ci/Jenkinsfile-hardware, Tools/HIL/run_nsh_cmd.py, Tools/HIL/run_tests.py
Quick and dirty script to run a number of commands on each board.
- free
- ps
- ver all
- status of various modules
- etc
=> Jenkins HIL test run various commands to inspect system

src/modules/ekf2/ekf2_main.cpp
=> ekf2: fixed calculation of static pressure error

src/modules/logger/logger.cpp
Backport of https://github.com/PX4/Firmware/pull/12397 to `stable`
=> [BACKPORT] logger: handle 'char' type in messages

src/drivers/px4fmu/fmu.cpp
=> fmu: remove unused functions

boards/px4/fmu-v5x/src/board_config.h
This prevented booting. @eyeam3 - FYI for board bring up
=> GPIO ADC had bad definition

ROMFS/px4fmu_common/init.d/airframes/13014_vtol_babyshark
Improved tuning of the Babyshark VTOL in hover (switched to new smooth (velocity) flight task, de-tuned position control, improved land detector).
Log file:
https://review.px4.io/plot_app?log=57bb80c6-e730-4014-936a-1196e61b2dcc
=> Babyshark VTOL: updated config file (hover)

msg/tools/uorb_rtps_classifier.py, msg/tools/uorb_to_ros_rtps_ids.py
This should fix CI (https://github.com/PX4/Firmware/pull/11910#issuecomment-510278033)
=> yaml: use safe_load(f) instead of load(f, Loader=yaml.FullLoader)

src/modules/ekf2/ekf2_params.c
Fixes #12305
Note, these seem like right units, but really up to @priseborough to confirm.
=> Add units for EKF2_RNG_A_HMAX and EKF2_RNG_A_VMAX

.ci/Jenkinsfile-SITL_tests_coverage, Jenkinsfile
A few more updates needed for https://github.com/PX4/Firmware/pull/12533.
=> Jenkins fetch all tags

.vscode/cmake-variants.yaml, .vscode/launch.json
Minor development convenience.
=> vscode add v5x variant (for cmake configure)

src/drivers/barometer/bmp388/bmp388.cpp, src/drivers/barometer/bmp388/bmp388.h, src/drivers/barometer/bmp388/bmp388_i2c.cpp, src/drivers/barometer/bmp388/bmp3_defs.h
This is a WIP commit that provides a functioning BMP388 driver for FMUv5x bring up efforts for @davids5 that we discussed on a phone call today.  As the commit mentions, I'm submitting this PR now with the (legacy?) uORB publishing approach, and I'll need to refactor to use PX4Barometer but wanted to commit now to provide this for HW bring up use!
Tested using 'uorb top', and 'listener sensor_baro'
I basically followed what I saw in the bmp280 driver
I'm going to refactor to use PXBarometer and get rid of the bmp3_defs.h file
=> WIP Bosch bmp388 Support

boards/px4/fmu-v5x/default.cmake, src/drivers/drv_sensor.h, src/drivers/imu/bmi088/BMI088.hpp, src/drivers/imu/bmi088/BMI088_accel.cpp, src/drivers/imu/bmi088/BMI088_accel.hpp, src/drivers/imu/bmi088/BMI088_gyro.cpp, src/drivers/imu/bmi088/BMI088_gyro.hpp, src/drivers/imu/bmi088/CMakeLists.txt, src/drivers/imu/bmi088/bmi088_main.cpp
Continuation of the Bosch BMI088 driver (based on existing bmi055 driver) from @ksschwabe. https://github.com/PX4/Firmware/pull/12585
=> Bosch BMI088 initial driver

src/lib/drivers/accelerometer/PX4Accelerometer.cpp, src/lib/drivers/barometer/PX4Barometer.cpp, src/lib/drivers/gyroscope/PX4Gyroscope.cpp, src/lib/drivers/magnetometer/PX4Magnetometer.cpp, src/lib/drivers/rangefinder/PX4Rangefinder.cpp, src/lib/drivers/rangefinder/PX4Rangefinder.hpp
- this is no longer necessary with all publications outside of ISRs
=> drivers helper classes remove empty publication (forced advertise)

src/modules/mavlink/mavlink_parameters.cpp
Initialize everything to make clang-tidy happy.
=> mavlink uavcan parameters only process updates

msg/tools/generate_microRTPS_bridge.py, msg/tools/px_generate_uorb_topic_files.py, msg/tools/uorb_rtps_classifier.py, msg/tools/uorb_rtps_message_ids.yaml
Minor updates to the RTPS generation scripts:
- Adds support for using Python 3 with the scripts (an incompatibility with lists indexing was solved)
- Adds IDS for recently aliased topics
=> RTPS generation scripting updates

ROMFS/px4fmu_common/init.d/airframes/50003_aion_robotics_r1_rover, msg/CMakeLists.txt, msg/wheel_encoders.msg, src/drivers/roboclaw/CMakeLists.txt, src/drivers/roboclaw/RoboClaw.cpp, src/drivers/roboclaw/RoboClaw.hpp, src/drivers/roboclaw/module.yaml, src/drivers/roboclaw/roboclaw_main.cpp, src/drivers/roboclaw/roboclaw_params.c
Added functionality for reading wheel encoder data
Rewrote the Roboclaw driver, which communicates over UART with the Roboclaw motor driver on the Aion R1 rover. It now reads encoder data and publishes a UOrb topic
=> Rewrote Roboclaw driver

ROMFS/px4fmu_common/init.d/rcS, src/drivers/optical_flow/px4flow/parameters.c
- fixes https://github.com/PX4/Firmware/issues/12571
The new parameter (SENS_EN_PX4FLOW) needed to enable the PX4 Flow needs to be mentioned in release notes (migration guide) to help existing users transition.
=> px4flow add parameter to enable (SENS_EN_PX4FLOW)

src/lib/CollisionPrevention/CollisionPrevention.cpp
Reverts https://github.com/PX4/Firmware/pull/12616 since @mhkabir reported that it broke Collision Prevention.
@mhkabir I am reverting this because otherwise we will forget about it
=> Revert "CollisionPrevention only process distance_sensor updates"

src/modules/mc_pos_control/mc_pos_control_main.cpp
Fixed missing semicolon
FYI: @bkueng
=> mc_pos_control_main: Fixed missing semicolon

src/modules/sensors/voted_sensors_update.h
This PR adds uniform initialization and formats white space `in voted_sensors_update.h` to simplify remaining work in PR #9756 and #11874.
Flight tested on a 250 quad with pixhawk 4 mini.  Flight tests are identical to current PX4:master.
https://review.px4.io/plot_app?log=c80d3d21-afca-4571-b736-b1b9b23f1bf2
See PR #9756 and #11874.
Please let me know if you have any questions on this PR!  Thanks!
-Mark
=> Uniform initialization in voted_sensors_update.h.

Tools/px_mkfw.py
Useful to have that in there as well.
=> px_mkfw: add git commit hash to .px4 file

src/modules/vtol_att_control/vtol_att_control_main.cpp
Otherwise we get multiple updates which is problematic for SITL lockstep and a waste of cpu.
This is the behavior in current PX4 stable, but implement with polling.
=> VTOL: only run on MC actuator publications unless in full FW mode

.ci/Jenkinsfile-hardware_snapdragon, boards/atlflight/eagle/CMakeLists.txt, boards/atlflight/eagle/scripts/px4_snapflight_sanitytest.sh
=> px4_snapflight_sanitytest fix paths and drop legacy

src/lib/version/version.h, src/systemcmds/tests/test_versioning.cpp
This adds the "beta" tag and adds a dash before "rc" or "beta".
Follow up to #12782.
=> version: add beta tag

msg/tools/uorb_rtps_classifier.py, msg/tools/uorb_rtps_message_ids.yaml
- Increase ID space for non-alias topics (multi-topics start at 150 now)
- Small improvement on the alias check and verbosity
=> RTPS: small fixes

ROMFS/px4fmu_common/init.d/airframes/13014_vtol_babyshark
-increases front transition throttle to 1 (default)
-enables airmode on pitch and roll
-increased max roll angle in fixed-wing flight to 45°
=> BabyShark VTOL: update config file (increased transition throttle, enable airmode)

ROMFS/px4fmu_common/init.d-posix/1040_standard_vtol, ROMFS/px4fmu_common/init.d-posix/1041_tailsitter, ROMFS/px4fmu_common/init.d-posix/1042_tiltrotor, ROMFS/px4fmu_common/init.d/airframes/1002_standard_vtol.hil, ROMFS/px4fmu_common/init.d/airframes/13002_firefly6, ROMFS/px4fmu_common/init.d/airframes/13004_quad+_tailsitter, ROMFS/px4fmu_common/init.d/airframes/13005_vtol_AAERT_quad
=> VTOL airframes update legacy VT_MOT_COUNT parameter

boards/px4/fmu-v2/fixedwing.cmake, boards/px4/fmu-v2/multicopter.cmake, boards/px4/fmu-v2/rover.cmake, boards/px4/fmu-v2/test.cmake
=> px4_fmu-v2 variants disable mpu9250

src/modules/sensors/sensor_params.c
- fixes https://github.com/PX4/Firmware/issues/12866
=> SENS_BARO_QNH set reboot_required

src/drivers/uavcan/actuators/esc.hpp, src/drivers/uavcan/uavcan_main.cpp
- rather than only in UavcanEscController
Related: https://github.com/PX4/Firmware/pull/12874
=> uavcan: limit actuator controls poll interval

platforms/common/px4_work_queue/WorkQueueManager.cpp
I think clang complained about this at some point.
=> platforms: fix main function signature

src/drivers/pwm_out_sim/PWMSim.cpp, src/drivers/pwm_out_sim/PWMSim.hpp
Simple fix to delay advertising until we have valid data.
=> pwm_out_sim: don't advertise garbage

.ci/Jenkinsfile-hardware
Attempt to tone down the light show produced by the current hardware test rack.
=> Jenkins HIL disable rgbled

src/lib/CollisionPrevention/CollisionPrevention.cpp, src/lib/FlightTasks/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.cpp, src/lib/FlightTasks/tasks/Utility/TrajMath.hpp, src/lib/mathlib/math/TrajMath.hpp, src/lib/mathlib/mathlib.h
follows issue https://github.com/PX4/Firmware/issues/12982
Please feel free to add a version for doubles if required
Fixes #12982
=> TrajMath: replace type placeholder with floats

src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_main.h, src/modules/mavlink/mavlink_parameters.cpp, src/modules/mavlink/mavlink_receiver.cpp
Split out of https://github.com/PX4/Firmware/pull/12967.
=> Mavlink: ifdef networking code

Tools/fetch_file.py, Tools/geotag_images_ulog.py, Tools/run-clang-tidy.py, integrationtests/python_src/px4_it/dronekit/MissionCheck.py, src/modules/mavlink/mavlink_tests/mavlink_ftp_test_data.py
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.  100 days until Python 2 end of life.
A clear and concise description of the problem this proposed change will solve. E.g. For this use case I ran into...
**Describe possible …
=> Use print() function in both Python 2 and Python 3

Tools/run-clang-tidy.py, Tools/uorb_graph/create.py, integrationtests/python_src/px4_it/dronekit/MissionCheck.py
A clear and concise description of the problem this proposed change will solve. E.g. For this use case I ran into...
=> Old style exceptions are Python 3 syntax errors

src/systemcmds/topic_listener/listener_main.cpp
=> listener fix incorrect "never published" cases

src/modules/ekf2/ekf2_params.c, src/modules/mavlink/mavlink_receiver.cpp
=> Update mavlink receiver odometry parent frame

src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp
https://logs.px4.io/plot_app?log=eda0d033-187d-4f52-8bf3-8cc3c320ef71.
=> frsky_telemetry: increase stack by 40 bytes

src/drivers/uavcan/CMakeLists.txt, src/drivers/uavcan/sensors/battery.cpp, src/drivers/uavcan/sensors/battery.hpp, src/drivers/uavcan/sensors/sensor_bridge.cpp
~This is not working yet, opening to get some feedback/review.~
=> UAVCAN battery support

src/modules/sensors/voted_sensors_update.h
This PR is copy/paste only to organize a few vars, simplify the diff in PR #11874, and advance PR #9756
See PR #11857.
=> Organize vars in voted_sensors_update.h.

Tools/setup/ubuntu.sh
Just a typo from https://github.com/PX4/Firmware/pull/12912/files
=> ubuntu.sh: correct output during ccache installation

src/modules/navigator/mission.cpp
fix save_mission_state() function
Fixes https://github.com/PX4/Firmware/issues/12460
=> navigator: fix save mission state.

msg/tools/generate_microRTPS_bridge.py
=> generate_microRTPS_bridge: fix fastrtpsgen version check handler

msg/templates/urtps/Publisher.cpp.em, msg/templates/urtps/Publisher.h.em, msg/templates/urtps/RtpsTopics.cpp.em, msg/templates/urtps/Subscriber.cpp.em, msg/templates/urtps/Subscriber.h.em
=> microRTPS: templates: fix support for ROS2 Dashing

Jenkinsfile
Let's give this a try again before the release.
=> Jenkins CI: reactivate Catkin build stage

src/drivers/dshot/dshot.cpp
Addresses https://github.com/PX4/Firmware/pull/12854#discussion_r335857830
=> dshot telemetry: enable telemetry publishing for setups with only one ESC

.ci/Jenkinsfile-SITL_tests, .ci/Jenkinsfile-SITL_tests_ASan, .ci/Jenkinsfile-SITL_tests_coverage, .ci/Jenkinsfile-compile, .ci/Jenkinsfile-hardware, .circleci/config.yml, .github/workflows/ccpp.yml, Jenkinsfile, Tools/docker_run.sh
I don't know of the specific reason why this wasn't done before, but I do think it makes sense at this point.
=> Jenkins CI: move SITL tests to Melodic container

ROMFS/px4fmu_common/init.d/airframes/4250_teal
=> Updated maintainer on 4250_teal

src/modules/mc_pos_control/mc_pos_control_main.cpp
The problem is generated here: https://github.com/PX4/Firmware/pull/12572
=> mc_pos_control.cpp:Fix forced update parameters

src/drivers/uavcan/sensors/battery.cpp
- Set battery.voltage_filtered_v and battery.current_filtered_a value
- Fixed battery.remaining error when full_charge_capacity_wh is zero
=> Fixed CAN battery status

Tools/jmavsim_run.sh
=> Fixed typo for extra_args when HEADLESS mode chosen.

platforms/common/px4_work_queue/WorkQueueManager.cpp
Px4 work queue fails to set stack size when running on MacOs system.
Reproducing the bug is as simple as running jmavsim. The console always output the set of errors shown in the below picture
This apparently happens because the function pthread_attr_setstacksize() fails when the stacksize is not a multiple of the system page size.
The proposed solution does round up the stack size to the nearest multiplier when the firmware runs on an posix system.
I tested the solution on my macOS system and here are the results of the rounding operation
> name:wq:hp_default , stacksize: 14264 , rounded: 16384
name:wq:att_pos_ctrl , stacksize: 24464 , rounded: 24576
name:wq:rate_ctrl , stacksize: 14464 , rounded: 16384
=> SITL MacOs bugfix

.ci/Jenkinsfile-hardware
This spaces things out a bit more and no longer blocks the actual hardware testing on compiling all boards.
=> Jenkins hardware move to nested stages

platforms/common/px4_work_queue/WorkQueueManager.cpp, src/include/containers/BlockingList.hpp, src/include/containers/LockGuard.hpp
=> [BACKPORT] BlockingList: fix unsafe getLockGuard() API

src/drivers/distance_sensor/ll40ls/LidarLiteI2C.cpp
=> [BACKPORT] Removed lidar lite reset after intialization

src/drivers/imu/adis16448/adis16448_main.cpp, src/drivers/imu/adis16477/adis16477_main.cpp, src/drivers/imu/adis16497/adis16497_main.cpp
This fixes a few minor issues in the frontends of these drivers and makes them consistent.
=> ADIS IMU drivers cleanup and standardize main

Tools/uorb_graph/create.py
file() -> open()
dict_obj_A.keys() + dict_obj_B.keys() -> list(dict_obj_A.keys()) + list(dict_obj_B.keys())
=> Update create.py to support Python3.x

src/drivers/magnetometer/ak09916/ak09916.cpp, src/drivers/magnetometer/ak09916/ak09916.hpp
Cherry-picking https://github.com/PX4/Firmware/pull/13443 to v1.10.
=> ak09916 backport fix

boards/holybro/durandal-v1/default.cmake, boards/holybro/durandal-v1/init/rc.board_defaults, src/drivers/heater/heater.cpp, src/drivers/heater/heater_params.c, src/modules/sensors/sensor_params.c
Adds support for IMU heater on Durandal.
Additionally, the heater module is greatly simplified.
=> Durandal heater support

cmake/px4_find_python_module.cmake, cmake/px4_git.cmake, cmake/px4_parse_function_args.cmake
This is a small cmake configure time optimization.
=> cmake add a few include guards

msg/vehicle_status.msg, src/modules/commander/Commander.cpp, src/modules/commander/state_machine_helper.cpp, src/modules/navigator/mission_block.cpp, src/modules/navigator/navigator_main.cpp, src/modules/navigator/precland.cpp
Possibly helpful for https://github.com/PX4/Firmware/issues/13293.
=> commander: add vehicle-status nav_state change timestamp

boards/holybro/durandal-v1/stackcheck.cmake, boards/px4/fmu-v2/fixedwing.cmake, boards/px4/fmu-v2/multicopter.cmake, boards/px4/fmu-v2/test.cmake, boards/px4/fmu-v5/stackcheck.cmake, src/systemcmds/tests/test_matrix.cpp, src/systemcmds/tests/test_microbench_matrix.cpp
(starting to pull small pieces from #13351)
This PR updates matrix submodule with pseudoinverse implementation (https://github.com/PX4/Matrix/pull/102) and adds tests and benchmarks.
=> Update matrix submodule and add tests

src/modules/vmount/output.cpp, src/modules/vmount/output_mavlink.cpp, src/modules/vmount/vmount.cpp
This is required to get the Gremsy Pixy F with the latest beta firmware going. (Plus small cleanup.)
=> vmount: MAVLink output fixes

src/modules/vmount/output.cpp, src/modules/vmount/output_mavlink.cpp, src/modules/vmount/vmount.cpp
=> [BACKPORT] vmount mavlink fixes

ROMFS/px4fmu_common/init.d-posix/rcS, src/modules/navigator/mission_block.cpp, src/modules/navigator/navigator.h, src/modules/navigator/navigator_mode.cpp, src/modules/vtol_att_control/tailsitter.cpp
Simple small refactoring improvements I did while working on other things.
SITL testing.
=> Trivial: Conversion Refactor

boards/px4/fmu-v5x/init/rc.board_sensors, src/drivers/imu/bmi088/BMI088_gyro.cpp, src/drivers/imu/bmi088/BMI088_gyro.hpp
Fixed bmi088 sensor orientatino and bmi 088 gyro error handling
=> Fmu5x sensor rotatino and bmi088 gyro error handling fix

src/modules/mavlink/mavlink_mission.cpp
=> Fix warning on do jump

src/modules/control_allocator/ControlAllocator.cpp
=> control_allocator: fixed negative saturation status reporting

src/modules/fw_pos_control_l1/FixedwingPositionControl.hpp
A style inconsistency that came in here: https://github.com/PX4/Firmware/commit/af7b2cd22ff884c3619614ebeb0ca87ac52b3666#diff-1623c0ae5ae66f14c639e7c1ac03a77bR161
=> [Trivial] FixedWingPositionControl: ommit */ with ///< doxygen comments

src/modules/mavlink/mavlink_messages.cpp
This fills in the yaw_absolute field in the mount_orientation mavlink message. This is computed by adding the vehicle heading to the gimbal yaw.
It is required for geotagging photos because the gimbal yaw has to be in world frame and not body frame.
MOUNT_ORIENTATION: https://mavlink.io/en/messages/common.html#MOUNT_ORIENTATION
=> add yaw_absolute to mount_orientation

src/drivers/linux_pwm_out/linux_pwm_out.cpp
This reverts commit 25acd40ef00fdb5e615b921596829165b06a6f5d.
We can't use uORB::Subscription here because the uorb device_master isn't yet available when the constructor is called.
=> Revert "linux_pwm_out update orb usage"

boards/mro/ctrl-zero-f7/default.cmake, boards/mro/ctrl-zero-f7/init/rc.board_sensors, src/drivers/barometer/dps310/CMakeLists.txt, src/drivers/barometer/dps310/DPS310.cpp, src/drivers/barometer/dps310/DPS310.hpp, src/drivers/barometer/dps310/DPS310_I2C.cpp, src/drivers/barometer/dps310/DPS310_SPI.cpp, src/drivers/barometer/dps310/Infineon_DPS310_Registers.hpp, src/drivers/barometer/dps310/dps310_main.cpp, src/drivers/drv_sensor.h
- used on the mRo Control Zero F7
=> Infineon DPS310 Barometer

src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_main.h
Backport #13686 to 1.10.
Tested on Pixracer.
=> [BACKPORT] MAVLink: fixes for USB instance

.ci/Jenkinsfile-hardware
=> Jenkins hardware leave RGB LED defaults

.ci/Jenkinsfile-compile, boards/px4/raspberrypi/cross.cmake, boards/px4/raspberrypi/native.cmake
=> px4_raspberrypi cleanup configs and add to Jenkins

src/modules/navigator/mission.cpp
=> navigator: fix VTOL RTL corner case

.gitmodules
This fixes https://github.com/PX4/ecl/issues/682 for the v1.10.0 release.
=> ECL fix for v1.10.0 release

ROMFS/px4fmu_common/init.d/airframes/4016_holybro_px4vision, ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt
This adds a airframe config for the px4vision devkit drone produced by Holybro
Would it be possible to get this in for the 1.10 release?
=> Airframe config for px4vision devkit drone

Tools/uorb_graph/create.py, platforms/nuttx/Debug/Nuttx.py
As mentioned by @cclauss in https://github.com/PX4/Firmware/pull/13008.
=> Fix a couple of flake8 Python warnings

src/modules/commander/Commander.cpp
If you hit a geofence in position mode and you either let go of the stick or move it just a little bit the geofence reaction is overriden and it switches back to position mode.
The original logic was introduced here: https://github.com/PX4/Firmware/commit/a2ba34d1aedfc84b8ece97ebdaa9d17781ad07aa and probably made sense to allow the pilot to come out of the geofence again but things have changed: There's now the rc override by sticks and the pilot can come out by switching mode since https://github.com/PX4/Firmware/pull/12057.
Even though there are more problems than just this one I prefer to not accidentally switch out of the geofence reaction just by letting go of the stick. E.g. Full forward position mode -> RTL …
=> commander: remove manual mode before geofence handling

Jenkinsfile
- re-enable once the python issues are resolved
FYI @TSC21 @julianoes
=> Jenkins temporarily disable "PX4 ROS msgs" in master

src/lib/drivers/device/posix/I2C.cpp
I noticed this was missing in https://github.com/PX4/Firmware/pull/13814.
@SalimTerryLi
=> posix I2C::init() should also probe() (sync with NuttX)

platforms/posix/src/px4/common/main.cpp, test/mavsdk_tests/mavsdk_test_runner.py
- wait_to_exist() shouldn't depend on lockstep (px4_usleep)
=> posix main wait_to_exit() fix and catch SIGTERM

src/modules/fw_pos_control_l1/runway_takeoff/RunwayTakeoff.cpp
1. set parameter _param_rwto_ramp_time to 10s
2. set minium speed for takeoff 10m/s
3. start to takeoff and the speed reached 9m/s in 5s
4. need to change the stage to CLAMPED_TO_RUNWAY
=> fix bug if speed reach minium during ramp

Makefile, test/mavsdk_tests/CMakeLists.txt, test/mavsdk_tests/mavsdk_test_runner.py, test/mavsdk_tests/test_mission_multicopter.cpp, test/mavsdk_tests/test_mission_plane.cpp
Partial continuation of https://github.com/PX4/Firmware/pull/13830. The ECL changes are massive, so bringing in some of the smaller pieces separately.
=> mavsdk coverage small improvements from #13830

test/mavsdk_tests/mavsdk_test_runner.py
I just made a couple of simple changes to check whether the github actions run when a PR is made from a fork.
=> mavsdk_tests: fix PEP8 issues

msg/vehicle_status_flags.msg
Quick follow up to https://github.com/PX4/Firmware/pull/13876.
=> vehicle_status_flags: remove unused circuit_breaker_engaged_gpsfailure_check

boards/intel/aerofc-v1/aerofc_adc/AEROFC_ADC.cpp, boards/intel/aerofc-v1/aerofc_adc/AEROFC_ADC.hpp, boards/intel/aerofc-v1/aerofc_adc/CMakeLists.txt, boards/intel/aerofc-v1/aerofc_adc/aerofc_adc_main.cpp
Moving this from NuttX HPWORK to the PX4 WQ. I didn't touch any of the actual driver code.
=> aerfc_adc: move to PX4 WQ and cleanup

boards/aerotenna/ocpoc/default.cmake, boards/atlflight/eagle/default.cmake, boards/atlflight/excelsior/default.cmake, boards/beaglebone/blue/default.cmake, boards/emlid/navio2/default.cmake, boards/px4/raspberrypi/default.cmake, posix-configs/bbblue/px4.config, posix-configs/bbblue/px4_fw.config, posix-configs/ocpoc/px4.config, src/drivers/rc_input/RCInput.cpp, src/lib/rc/sbus.cpp
=> drivers/rc_input: port to linux for testing

.ci/Jenkinsfile-compile, Makefile, boards/atlflight/eagle/qurt.cmake, boards/atlflight/eagle/scripts/.gitignore, boards/atlflight/eagle/scripts/px4_snapflight_sanitytest.sh, boards/atlflight/excelsior/qurt.cmake, platforms/common/include/px4_platform_common/atomic.h, platforms/qurt/CMakeLists.txt, platforms/qurt/src/px4/common/px4_init.cpp, src/drivers/driver_framework_wrapper/df_ltc2946_wrapper/CMakeLists.txt, src/drivers/qshell/qurt/CMakeLists.txt, src/lib/drivers/device/posix/SPI.cpp, src/lib/drivers/device/qurt/SPI.cpp
- fixed df_ltc2946_wrapper battery depenency
- fixed px4::atomic fetch_add for QuRT
- updated PX4 QuRT SPI wrapper to set bus frequency
- renamed "qurt-default" configs to just "qurt"
=> atlflight/eagle: minor fixes to get it working again

Jenkinsfile
WIP for retrying to enable ROS 2 deployment.
=> Jenkins: re-enable microRTPS bridge templates and scripts deployment

src/drivers/driver_framework_wrapper/df_ak8963_wrapper/df_ak8963_wrapper.cpp, src/drivers/driver_framework_wrapper/df_lsm9ds1_wrapper/df_lsm9ds1_wrapper.cpp, src/drivers/driver_framework_wrapper/df_mpu9250_wrapper/df_mpu9250_wrapper.cpp, src/drivers/drv_mag.h, src/drivers/magnetometer/bmm150/bmm150.cpp, src/drivers/magnetometer/bmm150/bmm150.hpp, src/drivers/magnetometer/hmc5883/HMC5883.cpp, src/drivers/magnetometer/hmc5883/HMC5883.hpp, src/drivers/magnetometer/ist8310/ist8310.cpp, src/drivers/magnetometer/lis3mdl/lis3mdl.cpp, src/drivers/magnetometer/lis3mdl/lis3mdl.h, src/drivers/magnetometer/lis3mdl/lis3mdl_main.cpp, src/drivers/magnetometer/lsm303agr/LSM303AGR.cpp, src/drivers/magnetometer/qmc5883/qmc5883.cpp, src/drivers/magnetometer/rm3100/rm3100.cpp, src/drivers/magnetometer/rm3100/rm3100.h, src/drivers/magnetometer/rm3100/rm3100_main.cpp, src/drivers/qurt/fc_addon/mpu_spi/mpu9x50_main.cpp, src/modules/commander/mag_calibration.cpp, src/modules/sensors/voted_sensors_update.cpp
Small piece broken out of https://github.com/PX4/Firmware/pull/13900.
=> replace mag_report with sensor_mag_s

src/drivers/magnetometer/lsm9ds1_mag/LSM9DS1_MAG.cpp
=> lsm9ds1_mag: fix orientation

src/modules/logger/logger.cpp
Cleans up function by reducing duplicate code and local variable count
Signed-off-by: Tal Zaitsev <tal@corvus-robotics.com>
=> logger: refactor start_stop_logging

Tools/jmavsim_run.sh
=> edited jmavsim_run.sh for SIH display Only, flag -o

src/modules/commander/Commander.cpp
This PR gets rid of a duplicated variable used for battery checks in RC override and geofence logic.
It also changes the  _Autonomy off! Returned control to pilot_ message type from WARNING to INFO as this is not a safety critical info so there is no need to trigger a warning in QGC.
Tested in SITL.
=> Commander: small cleanup for rc override

.travis.yml
This change goes with disabling:
- Build pushed branches
- Build pushed pull requests
And adding a cron job on travis-ci to build master weekly.
=> travis: change coverity to run on master

msg/templates/urtps/Publisher.cpp.em, msg/templates/urtps/RtpsTopics.cpp.em, msg/templates/urtps/Subscriber.cpp.em, msg/templates/urtps/microRTPS_agent.cpp.em, msg/templates/urtps/microRTPS_transport.cpp
* Cleanup of all warnings beign found while building with `-Wall -Wextra -Wpedantic`;
* Improve and clean verbosity of the agent.
=> microRTPS bridge: clean build warnings; improve verbosity

Tools/setup/requirements.txt, Tools/setup/ubuntu.sh
I'm taking a passs over the ubuntu setup script.
This fixes https://github.com/PX4/Devguide/issues/917.
=> setup: Fix ubuntu.sh install script

src/modules/ekf2/ekf2_main.cpp
This is a combination of #13895 and #13939 
The ecl part has already been merged into master, see 
https://github.com/PX4/ecl/pull/701
https://github.com/PX4/ecl/pull/712
Testing results can be found in the individual PRs.
=> Moved barometer and magnetomter data preprocessing to ecl lib

src/modules/ekf2/ekf2_main.cpp
This updates the interface to the EKF for several sensors. Main goal here: standardization
**Related ECL PR:** https://github.com/PX4/ecl/pull/723
**Testing:** SITL tests running in CI
=> Updates to ECL interface

src/modules/ekf2/ekf2_main.cpp
This PR slightly adapts the interface for passing external vision data to ECL EKF.
See ECL PR for more information: https://github.com/PX4/ecl/pull/721
**Testing:** It compiles :) + SITL iris vision flight [log](https://review.px4.io/plot_app?log=27574e0e-e483-4ea9-9ff3-d62120f36c2b)
=> Update external vision interface

.github/workflows/sitl_tests.yml, platforms/common/px4_work_queue/WorkQueueManager.cpp, platforms/posix/src/px4/common/tasks.cpp, src/modules/simulator/simulator.h, src/modules/simulator/simulator_mavlink.cpp, test/mavsdk_tests/mavsdk_test_runner.py
This is follow-up and cleanup after #13772.
=> MAVSDK tests follow-up/cleanup

src/modules/ekf2/ekf2_main.cpp
This PR updates the optical flow interface to ECL EKF. 
see ECL PR for more information: https://github.com/PX4/ecl/pull/733
=> Update flow interface

src/modules/mavlink/CMakeLists.txt, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h, src/modules/sih/sih.cpp, src/modules/simulator/simulator_mavlink.cpp
~~Requires https://github.com/PX4/Firmware/pull/13955~~
- mavlink receiver use PX4Accelerometer/PX4Gyroscope for hil_sensor and hil_state_quaternion
- simulator module remove unnecessary fake scaling
- sih module remove unnecessary fake scaling
=> simulated sensors minor cleanup

.github/workflows/build_tests.yml, .github/workflows/ccpp.yml, .github/workflows/compile_nuttx.yml, .github/workflows/sitl_tests.yml, .github/workflows/sitl_tests_coverage.yml
With this change pull requests from forks are also built.
We yet need to verify if tags/releases are built or if we need to specify the tags as well.
=> workflows: build pull requests and master

src/modules/ekf2/ekf2_params.c
=> EKF params - clarify body frame origin/orientation

src/modules/commander/commander_params.c
Improves docs for param COM_RC_OVERRIDE
Follows on from https://github.com/PX4/Firmware/pull/13618
=> commander_params: subedit com_rc_override

codecov.yml
Let's see if we can make this slightly less annoying.
=> [WIP] codecov notification changes

ROMFS/px4fmu_common/init.d-posix/rcS
Fix syntax error introduced by #14126
=> Fix syntax in rcS

src/drivers/imu/invensense/icm20689/ICM20689.cpp, src/drivers/imu/invensense/icm20689/ICM20689.hpp, src/drivers/imu/invensense/icm20689/InvenSense_ICM20689_registers.hpp
- checked register mechanism and simple watchdog
- driver checks for errors gradually and can reconfigure itself
- respect IMU_GYRO_RATEMAX at the driver level
- fixed sensor INT16_MIN and INT16_MAX handling (y & z axis are flipped before publishing)
=> invensense icm20689 improvements

src/modules/simulator/simulator_mavlink.cpp
I've manually applied some of the changes proposed by @lovettchris in #13442 because the patches did not apply cleanly anymore.
This depends on https://github.com/mavlink/mavlink/pull/1311.
=> Small simulator/lockstep fixes

src/modules/commander/Commander.cpp
We were out flying with customers and none of them understood what this information was about. That was a clear indicator to me that it has to be adjusted.
Message says in novice understandable what happened.
We flew with this change and it was more clear to the operator.
=> Commander: clarify the rc override message

Tools/HIL/run_tests.py
Current jenkins ci hardware test is not fails if the test itself fail.
This pr fixes this.
As talked on https://github.com/PX4/Firmware/pull/14097 there is at least on hardware that fails on the test, the fmuk66
=> CI - exit from failed hardware check with error, so the check will fail

test/mavsdk_tests/mavsdk_test_runner.py
Allow the mavsdk-based tests to be run in debuggers. This is useful for finding segfaults/uninitialized memory, profiling, stepping through code, and more.
=> Add debugger options for mavsdk test runner

src/modules/logger/logger.h
=> logger: style fix

src/drivers/uavcan/uavcan_main.cpp
Uavcan:Fix null pointer de deference
@AlexKlimaj - this will fix the hard fault. But it is not the whole fix that is needed
=> Fixes Pixhawk4 mini hardfault.

boards/px4/fmu-v5x/p2_base_phy_LAN8742Ai.cmake
@dinomani - for ease of testing
=> px4_fmu-v5x:Add Serial test

src/modules/ekf2/ekf2_main.cpp
Fixes https://github.com/PX4/Firmware/issues/14321
=> ekf2_main.cpp: fixed bug in the calculation of the mag bias calibration

Jenkinsfile
Required to update the bridge on `px4_ros_com`.
=> Jenkins: add deployment of microRTPS_timesync to px4_ros_com

Jenkinsfile
Just fixing a typo on the deployment (wrong file names).
=> update files for microRTPS_timesync

Jenkinsfile
=> Jenkins: fix timesync filenames

.github/workflows/build_tests.yml, .github/workflows/compile_nuttx.yml, .github/workflows/sitl_tests.yml
This is a first pass. It might be possible to get better performance by saving with a key for the branch name and restoring based on that as a higher priority, with master as a backup.
=> Add ccache to github actions

platforms/common/include/px4_platform_common/posix.h
Include was added two times 4 years ago.
=> [Trivial] posix.h: remove duplicate stdint.h include

src/modules/logger/logger.cpp, src/modules/logger/logger.h
and some cleanups on main()
using ModuleParams in logger module.
@dagar can you confirm/fixme if while using ModuleParams should I call ModuleParams::updateParams() somewhere?
=> logger - using ModuleParams

src/lib/parameters/param_translation.cpp
In PR https://github.com/PX4/Firmware/pull/14048 we removed the d term filtering in the multicopter rate controller and started using the `vehicle_angular_acceleration` topic. We can also automatically migrate the parameter value from MC_DTERM_CUTOFF to IMU_DGYRO_CUTOFF to ensure a seamless upgrade.
=> parameters: handle MC_DTERM_CUTOFF -> IMU_DGYRO_CUTOFF migration

boards/aerotenna/ocpoc/default.cmake, boards/beaglebone/blue/default.cmake, boards/emlid/navio2/default.cmake, boards/px4/raspberrypi/default.cmake, platforms/posix/cmake/px4_impl_os.cmake
I found those TODOs in `px4_impl_os.cmake`. So I simply done the work. 
If it is OK then please merge this PR. If not, just close it.
=> move __PX4_LINUX definition out of px4_impl_os.cmake

test/mavsdk_tests/mavsdk_test_runner.py
These are improvements based on the review by @hamishwillee in https://github.com/PX4/Devguide/pull/982.
=> mavsdk_tests: improve usage text

src/drivers/imu/bmi055/BMI055_gyro.cpp, src/drivers/imu/bmi088/BMI088_gyro.cpp
Just came across this bug while working on something else.  Not sure who "owns" this driver, but figured someone might care about this.
And then I found another instance of this same bug in the BMI055 driver.  There may be more of these.
=> BMI088: Bug fix scheduling interval.

.ci/Jenkinsfile-SITL_tests, .ci/Jenkinsfile-SITL_tests_ASan, .ci/Jenkinsfile-SITL_tests_coverage, .ci/Jenkinsfile-compile, .ci/Jenkinsfile-hardware, .circleci/config.yml, .github/workflows/bloaty.yml, .github/workflows/build_tests.yml, .github/workflows/ccpp.yml, .github/workflows/compile_linux.yml, .github/workflows/compile_nuttx.yml, .github/workflows/sitl_tests.yml, Jenkinsfile, Tools/docker_run.sh
Following the addition of Ubuntu Focal Docker container, it's time to start adding a CI pipeline that may run over it as well.
=> Github Actions: Add jobs running in Ubuntu 20.04 Focal

README.md
Complements https://github.com/PX4/Firmware/pull/14524 using the new workflow naming.
=> README: add links on tokens for the Github Actions pages

src/modules/mavlink/mavlink_messages.cpp
https://github.com/PX4/Firmware/issues/14369
=> Add ACTUATOR_CONTROL_TARGET1

msg/battery_status.msg, src/lib/battery/battery.cpp
Same as https://github.com/PX4/Firmware/pull/14151, all credits go to @ItsTimmy 
I had some proposed changes but wasn't able to directly commit on top since it was a private branch: https://github.com/PX4/Firmware/pull/14151#pullrequestreview-382051676
Untested, @julianoes could you please review?
closes #14151
=> [Follow up] Fixed reporting of battery voltages in uORB

test/mavsdk_tests/mavsdk_test_runner.py, test/mavsdk_tests/process_helper.py
=> Fix CI MAVSDK tests timeout

msg/battery_status.msg, src/drivers/batt_smbus/batt_smbus.cpp, src/drivers/batt_smbus/batt_smbus.h, src/drivers/batt_smbus/parameters.c, src/modules/mavlink/mavlink_messages.cpp
This PR includes enhancement of smart battery. Existing batt_smbus app was bit outdate and not fully implemented. We will keep update this but current status would be good for first PR.
We've implemented more smart battery capabilities.
Tested with UVify smart battery (SMBUS standard battery).
=> SMBus battery (a.k.a. smart battery) enhancement.

boards/omnibus/f4sd/default.cmake, boards/omnibus/f4sd/init/rc.board_sensors, boards/omnibus/f4sd/nuttx-config/include/board.h, boards/omnibus/f4sd/nuttx-config/include/board_dma_map.h
Trying to keep this consistent with other boards. Broken out of https://github.com/PX4/Firmware/pull/14473.
=> boards: omnibus/f4sd add board_dma_map.h

msg/tools/px_generate_uorb_topic_files.py
This makes the error more user friendly and suggests what to do to fix it.
@TSC21 I beat you to it :smile:.
Fixes #14554.
=> tools: present nicer error for missing packaging

src/modules/ekf2/ekf2_main.cpp
This PR brings interface updates in ECL to the Firmware. 
See ECL PR for more information:
- https://github.com/PX4/ecl/pull/770
- https://github.com/PX4/ecl/pull/755
Complete diff: https://github.com/PX4/ecl/compare/870ec380f13707cde0e6adda5bf52838aa602ebd...2fa43419d2bd7319024682b311f52c78f9a86f52
=> Enable GPS flight without magnetometer

src/modules/mc_pos_control/mc_pos_control_params.c
- remove deprecated sport mode
- clarify wording
@bresch What do you think abou the working? Feel free to adjust.
It caught my attention when looking through https://github.com/PX4/px4_user_guide/pull/705, thanks @hamishwillee !
=> mc_pos_control_params: update MPC_POS_MODE description

src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp, src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.hpp, src/modules/commander/Arming/PreFlightCheck/checks/magnetometerCheck.cpp
I made a stupid little typo in https://github.com/PX4/Firmware/pull/13224/files#diff-e8ea7a7d060b73b8258a6ded55543eb4R96 and refactor to fix it here.
=> PreFlightCheck: fix magnometer typo

ROMFS/px4fmu_common/init.d-posix/1030_plane, ROMFS/px4fmu_common/init.d-posix/1040_standard_vtol, ROMFS/px4fmu_common/init.d-posix/1041_tailsitter, ROMFS/px4fmu_common/init.d-posix/1042_tiltrotor
- decrease L1 period for tighter mission tracking in fw mode
- increase backtransition duration, we can now do this as we have active
deceleration control
=> SITL VTOL and plane config update

src/drivers/uavcannode/UavcanNode.cpp, src/drivers/uavcannode/UavcanNode.hpp
Added publishing of the BatteryInfo message to the `uavcannode` module.
=> BatteryInfo publishing uavcannode

src/drivers/uavcannode/UavcanNode.cpp
=> uavcannode: fix format

Tools/setup/arch.sh, Tools/setup/ubuntu.sh
This always triggered an error when using in docker as root.
=> setup: fix usermod error as root

boards/holybro/durandal-v1/src/board_config.h, boards/holybro/durandal-v1/src/init.c
This is a test to fix https://github.com/PX4/Firmware/issues/13732
=> holybro_durandal-v1:Ensure SDMMC power sequencing is clean

src/modules/mavlink/mavlink_receiver.cpp
When disconnecting USB poll returns successfully, but the read returns
-1 with ENOTCONN.
In addition this also ensures there's no busy loop when poll returns an
error.
MAVLink continues to work after reconnecting USB.
fixes  #14600
@MaEtUgR
=> mavlink: fix potential busy loop upon USB disconnect

src/modules/commander/Arming/PreFlightCheck/checks/ekf2Check.cpp
=> commander: fix preflight check spam

.ci/Jenkinsfile-hardware
- /proc meminfo and uptime
- gps status, ekf2 status, attitude, local position
- try to force update px4io on a few boards
=> Jenkins: hardware print more status per board and cleanup SD card

ROMFS/px4fmu_common/init.d-posix/1033_plane_lidar, platforms/posix/cmake/sitl_target.cmake
This PR adds a distance sensor to the plane model to test terrain following with fixed wing
=> Add plane lidar model for testing fw terrain landing

src/modules/vtol_att_control/tailsitter.cpp, src/modules/vtol_att_control/tailsitter.h
=> tailsitter: remove unused code

platforms/common/i2c_spi_buses.cpp, platforms/common/include/px4_platform_common/i2c.h, platforms/common/include/px4_platform_common/i2c_spi_buses.h, platforms/common/include/px4_platform_common/spi.h, src/drivers/differential_pressure/sdp3x/SDP3X.cpp
Fixes https://github.com/PX4/Firmware/issues/14730
=> I2C & SPI drivers: improve info output for external buses

src/drivers/pwm_out/CMakeLists.txt, src/drivers/pwm_out/PWMOut.cpp, src/drivers/pwm_out/PWMOut.hpp, src/lib/cdev/CDev.hpp, src/lib/drivers/device/CDev.hpp
This reverts commit 0c8dcf94bc256801a45475cdd7bc6490e9fb8af7.
Found during testing today. I'll bring it back in later when I have some time to finish updating things for Linux.
=> Revert "drivers/pwm_out: cleanup for multi-platform use"

src/modules/simulator/simulator_mavlink.cpp
Not that important, but it's distracting.
=> simulator: temperature only updated with baro

.ci/Jenkinsfile-hardware, src/modules/uORB/uORBDeviceMaster.cpp, src/modules/uORB/uORBMain.cpp
- sleep slightly longer than 1s to capture 1 Hz topics (keeps the list stable and readable)
- roundf msg rate calculation
- add topic size to output
- by default only print topics with subscribers (the list is getting quite long)
- clear previous output (past cursor)
``` Console
nsh> uorb top
update: 1s, num topics: 78
TOPIC NAME                     INST #SUB RATE #LOST #Q SIZE
sensor_accel                      0    2  801     0  4   40
sensor_accel_integrated           0    3  200   174  1   48
sensor_accel_status               0    3   10     8  1   48
sensor_gyro                       0    2  801     0  4   40
sensor_gyro_integrated            0    4  200   174  1   48
sensor_gyro_status                0    3   10     8  1   56
sensor_accel                      1    1  799     0  4 …
```
=> uORB: top output improvements

src/drivers/gps/gps.cpp, src/modules/navigator/navigator_main.cpp
Done to make static analysis tools happy/silent.
=> gps: only use injected data if copy successful

boards/px4/fmu-v5x/src/board_config.h, boards/px4/fmu-v5x/src/init.c
The reflects the as built FMUv5x FMUM.
=> FMUv5x config fixes 

src/modules/commander/Commander.cpp
This is yet another thing that should probably be properly incorporated into a state machine.
=> commander: CMD_COMPONENT_ARM_DISARM don't block disarm if maybe_landed

src/systemcmds/gpio/gpio.cpp
@jkflying the module description string breaks astyle (everything below). 
I also added simple module documentation to fix failing CI. Feel free to improve it.
=> systemcmds/gpio: refactor slightly to fix astyle and add module documentation to fix CI

src/lib/circuit_breaker/circuit_breaker_params.c, src/modules/commander/failure_detector/failure_detector_params.c
Improve description.  @RicardoM17 - better?
=> CBRK_FLIGHTTERM: Does not affect takeoff failure safety detection

src/drivers/barometer/bmp388/bmp388.cpp, src/drivers/barometer/bmp388/bmp388.h
Just some things I noticed when going through it.
- avoid unnecessary sensor readout cycle during init
- check status register for data ready
=> bmp388: some cleanup

platforms/common/px4_log.cpp, test/mavsdk_tests/autopilot_tester.cpp, test/mavsdk_tests/autopilot_tester.h, test/mavsdk_tests/configs/sitl.json, test/mavsdk_tests/mavsdk_test_runner.py, test/mavsdk_tests/process_helper.py, test/mavsdk_tests/test_multicopter_offboard.cpp
Work in progress to fix #14835
=> Attempt to fix MAVSDK tests CI

src/drivers/barometer/bmp388/bmp388.cpp, src/drivers/barometer/bmp388/bmp388.h
From https://github.com/PX4/Firmware/pull/14993/checks?check_run_id=717184053#step:6:735
=> bmp388: fix variable shadowing warning

README.md
I'm sure about the fixed link but less sure about which boards should be on that list.
=> Some Readme cleanup

.ci/Jenkinsfile-SITL_tests, .ci/Jenkinsfile-SITL_tests_ASan, .ci/Jenkinsfile-SITL_tests_coverage
FYI @Jaeyoung-Lim @Pedro-Roque
=> Jenkins: SITL temporarily disable failing offboard tests

boards/cuav/x7pro/src/board_config.h
=> Fix X7 HIPOWER enabled state

src/lib/battery/battery.h, src/lib/flight_tasks/tasks/ManualAltitude/FlightTaskManualAltitude.hpp, src/modules/mc_att_control/mc_att_control.hpp
This pr updates the ecl submodule to current master.
Following the move of the AlphaFilter library in https://github.com/PX4/ecl/pull/843 the include paths have to be adjusted.
Builds SITL
=> Update ecl and adapt to new AlphaFilter location

src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h
- keep in sync with the simulator module
=> mavlink: HIL_SENSOR receiver respect fields_updated

boards/px4/fmu-v4/default.cmake, boards/px4/fmu-v5/default.cmake, boards/px4/sitl/default.cmake, src/examples/fake_magnetometer/CMakeLists.txt, src/examples/fake_magnetometer/FakeMagnetometer.cpp, src/examples/fake_magnetometer/FakeMagnetometer.hpp
Obviously there are lots of ways this could be bogus, but I've found it useful for comparing the expected magnetic field with sensors.
- requires attitude and GPS position
=> create fake_magnetometer "driver" to publish magnetic field in body frame

.github/workflows/bloaty.yml, .github/workflows/build_tests.yml, .github/workflows/compile_linux.yml, .github/workflows/compile_nuttx.yml, .github/workflows/sitl_tests.yml
On github actions ccache doesn't seem to be actually getting any cache hits. Investigating...
=> Github actions get ccache working

Jenkinsfile
There isn't much left in the top level Jenkinsfile, so merging these 2 stages into 1 actually saves a bit of time.
=> Jenkinsfile merge remaining 1st & 2nd stages

src/modules/mavlink/mavlink_mission.cpp, src/modules/mavlink/mavlink_mission.h
- current_seq -1 indicates nothing currently active
- fixes https://github.com/PX4/Firmware/issues/15153
=> mavlink: send MISSION_CURRENT respect signed sequence number

test/mavsdk_tests/configs/sitl.json
Let's give this a try again so to avoid it falls by the wayside.
=> mavsdk_tests: add iris_dual_gps tests

Tools/sitl_run.sh
Simplifying on aqcuiring the PID in `sitl_run.sh`
Follow up of https://github.com/PX4/Firmware/pull/15206#pullrequestreview-436356707
=> Simplify getting sim PID

ROMFS/px4fmu_common/init.d-posix/rcS, posix-configs/SITL/init/test/cmd_template.in, posix-configs/SITL/init/test/test_mavlink, posix-configs/SITL/init/test/test_shutdown, posix-configs/SITL/init/test/test_template.in, posix-configs/eagle/hil/mainapphil.config, src/modules/simulator/battery_simulator/BatterySimulator.cpp, src/modules/simulator/battery_simulator/BatterySimulator.hpp, src/modules/simulator/battery_simulator/CMakeLists.txt, src/modules/simulator/battery_simulator/battery_simulator_params.c, src/modules/simulator/simulator.h, src/modules/simulator/simulator_mavlink.cpp
As a small step towards unifying SITL and HITL I've broken the battery simulator portion of the simulator module out as a simple standalone module.
=> simulator: create standalone battery simulator module

test/mavsdk_tests/configs/sitl.json, test/mavsdk_tests/test_multicopter_offboard.cpp
=> Remove flaky tests

.ci/Jenkinsfile-hardware
- not quite ready for this one
=> Jenkins: hardware mRo Control Zero skip tests for now

src/lib/flight_tasks/tasks/FlightTask/FlightTask.hpp
Just found this while preparing dev summit slides :smiley:
=> FlightTask: correct activate() doxygen comment

.ci/Jenkinsfile-hardware
Run at least one board at high rate for comparison.
=> Jenkins: set IMU_GYRO_RATEMAX to 4kHz on holybro_durandal-v1_default

msg/cellular_status.msg, src/modules/mavlink/mavlink_receiver.cpp
This Commit includes a update of the mavlink submodule
since the CELLULAR_STATUS message was updated in https://github.com/mavlink/mavlink/pull/1323/files, the necessary changes were done together
This is a follow up PR of https://github.com/PX4/Firmware/pull/15278#event-3530042518
=> Update mavlink with cellular status message fixes

msg/templates/urtps/Publisher.cpp.em, msg/templates/urtps/Subscriber.cpp.em
I found there is some problem when checking the fastrtps version in case of 1.10.0.
=> fix the fastrtps version problem in case of v1.10.0

boards/px4/fmu-v5/debug.cmake, boards/px4/fmu-v5/stackcheck.cmake
- partially sync with fmu-v5 stackcheck build
=> boards: fmu-v5 debug variant disable unnecessary modules to save flash

boards/airmind/mindpx-v2/default.cmake
**Enable PMW3901 on MindPX/MindRacer**
Enable pmw3901 on default.cmake.
=> Enable PMW3901 on MindPX/MindRacer.

boards/hex/io-v2/src/board_config.h, boards/px4/io-v2/src/board_config.h
io firmware remove double definition of GPIO_HEATER_OFF
=> io firmware remove double definition of GPIO_HEATER_OFF

CMakeLists.txt, platforms/nuttx/CMakeLists.txt
- fixes #15400
@Pigwomaniak can you give this a try?
=> cmake: NuttX skip --print-memory-usage if using the GOLD linker

src/modules/uORB/Subscription.hpp
I found this while reviewing #15083
=> Subscription: correct doxygen comment

src/examples/fake_magnetometer/FakeMagnetometer.cpp, src/modules/attitude_estimator_q/attitude_estimator_q_main.cpp
~~Waiting on https://github.com/PX4/ecl/pull/851.~~
=> update ecl geo_lookup usage

src/drivers/camera_trigger/camera_trigger_params.c
follow-up to https://github.com/PX4/Firmware/pull/15482
=> TRIG_MODE: update description to support 78

.gitattributes
=> gitattributes eol=lf for nearly all file types

src/drivers/uavcan/uavcan_drivers/stm32h7/driver/include/uavcan_stm32h7/can.hpp, src/drivers/uavcan/uavcan_drivers/stm32h7/driver/src/uc_stm32h7_can.cpp
=> uavcan: stm32h7: Fix improper loopback handling

ROMFS/px4fmu_common/init.d/airframes/4053_holybro_kopis2, src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp
Requires https://github.com/PX4/NuttX/pull/112.
=> Frsky telemetry: add inverted singlewire support for F7 or later

msg/vehicle_global_position.msg, msg/vehicle_local_position.msg, src/drivers/telemetry/frsky_telemetry/frsky_data.cpp, src/drivers/telemetry/frsky_telemetry/sPort_data.cpp, src/lib/flight_tasks/tasks/FlightTask/FlightTask.cpp, src/lib/flight_tasks/tasks/FlightTask/FlightTask.hpp, src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/ekf2/ekf2_main.cpp, src/modules/local_position_estimator/BlockLocalPositionEstimator.cpp, src/modules/mavlink/mavlink_high_latency2.cpp, src/modules/mavlink/mavlink_messages.cpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mc_pos_control/PositionControl/ControlMath.cpp, src/modules/mc_pos_control/mc_pos_control_main.cpp, src/modules/navigator/follow_target.cpp, src/modules/navigator/loiter.cpp, src/modules/navigator/mission.cpp, src/modules/navigator/mission_block.cpp, src/modules/navigator/navigator_main.cpp, src/modules/navigator/rtl.cpp, src/modules/simulator/simulator_mavlink.cpp, src/modules/vmount/output.cpp, src/modules/vmount/output.h
@bresch how about something like this?
Followup to https://github.com/PX4/Firmware/pull/15512.
=> vehicle_local_position: rename yaw -> heading and add reset logic

launch/single_vehicle_spawn.launch
Just fixed a typo in the launch file comment.
=> Comment typo fixed

src/modules/navigator/mission_block.cpp, src/modules/sih/sih.cpp, src/modules/uuv_att_control/uuv_att_control.cpp, src/systemcmds/tests/test_mathlib.cpp, src/systemcmds/tests/test_matrix.cpp
Updates to newest master of matrix.
Adds SparseVector class.
Replaces deprecated matrix functions inside Firmware.
=> Pr update matrix

src/modules/sensors/analog_battery_params_deprecated.c
- fixes https://github.com/PX4/Firmware/issues/15505
=> sensors: keep legacy params active (BAT_V_DIV/BAT_A_PER_V) for QGC SITL

src/modules/navigator/rtl.cpp
Current formula used for distance in the rally point calculations didn't take map distortion into account.
Use a local correction for the longitude compression
Use the 'real' geo library distance. However this is slow, and overkill IMO
=> Fix map distortion due to high latitudes

src/lib/rc/sbus.cpp, src/lib/rc/sbus.h
Fix to issue #15253 found by George-avy
fixes #15253
=> Sbus comment fix, found by George-avy in issue 15253

Jenkinsfile
Failure in master. http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2FFirmware/detail/master/2900/pipeline
=> Jenkins: microRTPS agent fetch git tags for versioning

src/modules/mavlink/mavlink_main.cpp
=> mavlink: check type on instance getting by device or network port

src/lib/conversion/RotationTest.cpp, src/lib/conversion/rotation.cpp, src/modules/commander/mag_calibration.cpp
- this is the same as ROTATION_ROLL_180_YAW_90 (10)
@bresch found another one.
If anyone's looking for something to do we should really review the entire list. https://github.com/PX4/Firmware/blob/60a7f7f9f2091d8949d8bc08446d3a5408010ca2/src/lib/conversion/rotation.h#L52-L97
=> commander: mag calibration auto rotation skip duplicates

src/modules/battery_status/analog_battery.cpp
same as PR #15618 for same reasons
=> batterry_status: fix checking default v_div

src/modules/logger/logged_topics.cpp, src/modules/logger/logged_topics.h
Looking for ways to be able to affordably increase `ORB_MULTI_MAX_INSTANCES`.
=> logger: add_topic_multi optional specify max multi-instance

ROMFS/px4fmu_common/init.d-posix/rcS, boards/bitcraze/crazyflie/syslink/syslink_main.cpp, boards/bitcraze/crazyflie/syslink/syslink_main.h, src/drivers/power_monitor/ina226/ina226.cpp, src/drivers/power_monitor/ina226/ina226.h, src/drivers/power_monitor/voxlpm/voxlpm.cpp, src/drivers/power_monitor/voxlpm/voxlpm.hpp, src/lib/battery/battery.cpp, src/lib/battery/battery.h, src/lib/battery/battery_params_deprecated.c, src/modules/battery_status/analog_battery.cpp, src/modules/battery_status/analog_battery.h, src/modules/commander/commander_params.c, src/modules/simulator/battery_simulator/BatterySimulator.cpp, src/modules/simulator/battery_simulator/BatterySimulator.hpp
Port of #15616 to the v1.11 release branch resolving small conflicts around multi publication of the battery topic.
@dagar Since I got pinged in the dev call :stuck_out_tongue_winking_eye:
=> [Port v1.11] Fix Battery Parameter Migration

.ci/Jenkinsfile-hardware
Trying to prevent timeouts when there's a large queue.
=> Jenkins: hardware increase timeout

.vscode/tasks.json, platforms/posix/Debug/launch_sim.json.in
This PR add gazebo VTOL tiltrotor debug target for VSCode SITL  based on the tailsitter target
=> add gazebo VTOL tiltrotor debug target for VSCode SITL

src/drivers/magnetometer/isentek/ist8308/IST8308.cpp
Two small fixes from the ist8310 rewrite. https://github.com/PX4/Firmware/pull/14383
=> isentek/ist8308: set sensor_mag error count and fix bitwise AND

src/templates/template_module/CMakeLists.txt, src/templates/template_module/template_module.cpp, src/templates/template_module/template_module.h
fixes https://github.com/PX4/Firmware/issues/15593
=> rename templates/module to templates/template_module

boards/aerotenna/ocpoc/default.cmake, boards/px4/sitl/default.cmake, boards/px4/sitl/nolockstep.cmake, boards/px4/sitl/rtps.cmake, boards/px4/sitl/test.cmake, platforms/posix/CMakeLists.txt
Minor fallout from https://github.com/PX4/Firmware/pull/15714.
=> build fixes in master

src/modules/commander/commander_params.c
just fix the comment for param COM_ARM_AUTH
=> fix COM_ARM_AUTH comment

Tools/sitl_run.sh
Leftover from https://github.com/PX4/Firmware/pull/15745.
=> sitl_run.sh remove xtrace leftover from debugging

.gitmodules, ROMFS/px4fmu_common/init.d-posix/10017_quadrotor_x, ROMFS/px4fmu_common/init.d-posix/10018_hexarotor_x, Tools/setup_jsbsim.bash, Tools/sitl_run.sh, platforms/posix/cmake/sitl_target.cmake
Current SITL integrations either lack good aerodynamic simulation ([gazebo](https://github.com/PX4/sitl_gazebo)) or does not support lockstep ([flightgear](https://github.com/ThunderFly-aerospace/PX4-FlightGear-Bridge)). This has shown to be problematic on modeling complex aerodynamics for fixedwing / VTOL applications
This is a PX4 HIL/SITL integration into JSBSim. JSBSim is an open source flight dynamics model (http://jsbsim.sourceforge.net/), which allows simulating complex flight dynamics behavior.
The implementation comes from [Auterion/px4-jsbsim-bridge](https://github.com/Auterion/px4-jsbsim-bridge)
and is directly integrated into JSBSim, allowing lockstep with PX4 SITL simulations.
The difference with …
=> Add jsbsim bridge to enable jsbsim for px4 SITL on jsbsim

src/systemcmds/param/param.cpp
- simplifies creation of an airframe config
- could be done from QGC, but it only knows if a param is non-default from metadata, which can be incorrect/missing information
- for the list of exceptions we could look at '@ category', but we don't have that info in the build
- there might be some more exceptions to be added
=> param: add 'param show-for-airframe' command

Tools/px4moduledoc/srcparser.py, boards/modalai/fc-v1/init/rc.board_sensors, platforms/common/i2c_spi_buses.cpp, platforms/common/include/px4_platform_common/i2c_spi_buses.h, platforms/common/include/px4_platform_common/module.h, platforms/common/module.cpp, src/drivers/barometer/lps33hw/lps33hw.cpp, src/drivers/barometer/lps33hw/lps33hw.hpp, src/drivers/barometer/lps33hw/lps33hw_main.cpp, src/drivers/differential_pressure/sdp3x/SDP3X_main.cpp, src/drivers/power_monitor/ina226/ina226_main.cpp, src/drivers/power_monitor/voxlpm/voxlpm_main.cpp
And add '-k' flag for keep_running directly to BusCLIArguments
=> lps33hw: refactor and add -k flag to keep running even if no sensor found

.ci/Jenkinsfile-compile, .ci/Jenkinsfile-hardware, .devcontainer/devcontainer.json, .github/workflows/checks.yml, .github/workflows/compile_nuttx.yml, .github/workflows/coverage.yml, .github/workflows/metadata.yml, Jenkinsfile, Tools/docker_run.sh, Tools/make_can_boot_descriptor.py, src/drivers/uavcannode/CMakeLists.txt
We should really make an effort to keep these synchronized.
=> update all px4-dev-base and px4-dev-nuttx container usage uniformly

.vscode/tasks.json
=> vscode: SITL debug add gazebo world select

src/include/containers/IntrusiveSortedList.hpp
fixes #15756 by adding to #15770 
and making similar changes in IntrusiveSortedList
=> fix 15756 so clang 12 doesn't complain

src/modules/logger/log_writer_file.cpp
=> logger: log_writer_file increase stack 1170 -> 1472 bytes

Jenkinsfile
Disable "catkin build on ROS workspace" for now until we can fix it properly.
=> Jenkins: temporarily disable catkin build on ROS workspace

.ci/Jenkinsfile-hardware
This is currently bricking the board. https://github.com/PX4/Firmware/issues/15786
=> Jenkins: hardware disable holybro durdandal bootloader update

msg/battery_status.msg, src/modules/commander/Commander.hpp, src/modules/commander/mag_calibration.cpp, src/modules/logger/logged_topics.cpp, src/modules/logger/logged_topics.h, src/modules/mavlink/mavlink_high_latency2.cpp, src/modules/mavlink/mavlink_high_latency2.h, src/modules/mavlink/mavlink_messages.cpp, src/modules/uORB/uORB.h
- put more realistic bounds on maximum number of battery instances, gps, etc
I was going to do this as part of https://github.com/PX4/Firmware/pull/14650, but it might be safer to look at it in isolation.
=> uORB increase ORB_MULTI_MAX_INSTANCES 4 -> 10

msg/CMakeLists.txt, msg/templates/uorb/msg.cpp.em, msg/tools/px_generate_uorb_topic_helper.py
``` Console
nsh> listener vehicle_attitude
TOPIC: vehicle_attitude
vehicle_attitude_s
timestamp: 68497369  (0.002776 seconds ago)
timestamp_sample: 68496921  (448 us before timestamp)
q: [0.8747, -0.0552, -0.0294, 0.4804]  (Roll: -7.2 deg, Pitch: 0.1 deg, Yaw: 57.5 deg)
delta_q_reset: [0.9994, -0.0000, -0.0000, 0.0335]  (Roll: -0.0 deg, Pitch: -0.0 deg, Yaw: 3.8 deg)
quat_reset_counter: 2
nsh> listener vehicle_attitude_setpoint
TOPIC: vehicle_attitude_setpoint
vehicle_attitude_setpoint_s
timestamp: 195734964  (0.000654 seconds ago)
roll_body: 0.0000
pitch_body: 0.0000
yaw_body: 1.0107
yaw_sp_move_rate: 0.0000
q_d: [0.8750, 0.0000, 0.0000, 0.4841]  (Roll: 0.0 deg, Pitch: -0.0 deg, Yaw: 57.9 deg)
thrust_body: [0.0000, 0.0000, -0.0000]
roll_reset_integral: False
pitch_reset_integral: False …
```
=> msg: add quaternion euler angle pretty print

.ci/Jenkinsfile-hardware, Tools/HIL/run_nsh_cmd.py, Tools/HIL/run_tests.py
=> Jenkins: HIL script minor improvements

test/mavsdk_tests/process_helper.py
This updates the sitl_gazebo submodule to the latest
The update includes the folloiwng changes
- Fix for jinja transition and git ignores (https://github.com/PX4/sitl_gazebo/pull/602, https://github.com/PX4/sitl_gazebo/pull/600)
- Cleanup for received_actuator (https://github.com/PX4/sitl_gazebo/pull/597)
- Fix geotagged_images return (https://github.com/PX4/sitl_gazebo/pull/601)
- Move iris to jinja templates (https://github.com/PX4/sitl_gazebo/pull/609)
=> Update sitl_gazebo submodule

src/modules/ekf2/EKF2.cpp
issue raised [here](https://discuss.px4.io/t/ekf2-module-gyro-sensor-units/18819/3)
=> ekf2: fix odom body rate sign bug

src/systemcmds/hardfault_log/hardfault_log.c
This should fix https://github.com/PX4/Firmware/issues/15839#issuecomment-700209322
=> hardfault_log:Fix hard fault - while hard fault logging

src/systemcmds/mtd/mtd.cpp
Replaces https://github.com/PX4/Firmware/pull/15857 as this is rebased on the multi instance version on master. 
To define an N way split this define the following:
#define BOARD_HAS_MTD_PARTITION_OVERRIDE {"/fs/mtd_params", "/fs/mtd_waypoints","/fs/equal_part" }
OR
To define a percentage split this define the following:
#define BOARD_HAS_MTD_PARTITION_OVERRIDE {"/fs/mtd_params", "/fs/mtd_waypoints","/fs/tiny" }
#define BOARD_MTD_PARTITION_TABLE_SIZES {50.0f, 49.0f, 1.0f}
=> mtd:Allow a Board to set the partition sizes.

src/lib/flight_tasks/tasks/Auto/FlightTaskAuto.cpp
This is done to prevent yawing 180 degrees when switching to hold mode with high velocity and the overshoot causing a 180° yaw turn.
Lock down yaw when waypoint is reached. Previously it unlocked when the acceptance radius was left again.
The yaw is unlocked on waypoint updates and the yaw setpoint generation had to be put at the end because otherwise the first yaw calculation is with the old waypoint and immediately locks again.
As discussed yesterday in the dev call hold mode has too many meanings and individual implementations for brake down, takeoff, goto, loiter make a lot of currently unfeasible expected behaviours very simple to do.
SITL jmavsim …
=> FlightTaskAuto: Lock down yaw when waypoint is reached

src/lib/mathlib/math/filter/NotchFilter.hpp
https://github.com/PX4/Firmware/pull/14755#discussion_r512024790
=> mathlib: NotchFilter delete unused update method

msg/tools/uorb_rtps_message_ids.yaml
More of the same but now [caught by CI](https://travis-ci.com/github/PX4/px4_ros_com/jobs/413194017#L4686). These are the last ones.
=> msg: rtps: add IDs for missing estimator_* msgs

.github/workflows/sitl_tests.yml, test/mavsdk_tests/CMakeLists.txt
Possible fix for https://github.com/PX4/Firmware/issues/15940.
=> Github actions: SITL tests upgrade MAVSDK 0.30.1 -> 0.32.1

src/modules/ekf2/EKF2.cpp
- ecl in PX4/Firmware (f87b19f31b9918f73d336d10e68d39c659037582): https://github/commit/48a8992caf7a95e09a5e17235133894c072b96bd
- ecl current upstream: https://github/commit/a21092804a784d012939f96cc633e7da5f5e8cde
- Changes: https://github/compare/48a8992caf7a95e09a5e17235133894c072b96bd...a21092804a784d012939f96cc633e7da5f5e8cde
a210928 2020-11-01 Daniel Agar - EKF: remove virtual getters from estimator_interface
=> Update submodule ecl to latest Mon Nov  2 09:57:32 EST 2020

Tools/check_submodules.sh
- the interactive portion of check_git_submodule with hang waiting for user input
=> Tools/check_submodules.sh: always update if within vscode cmake configure

src/systemcmds/hardfault_log/hardfault_log.c
A bug reported has a FMU in a boot loop hardfaulting in the hard fault Handler. This was due to a TCB corruption of the stack pointer and stack size such that the effective address was not a valid bus access.  This PR does a sanity check on the stack and stack+size effective address' and does not allow the stack dump to fault.m but instead prints a message.
```
IRQ stack:
top:    0x20021600
sp:     0x20021590 Valid
bottom: 0x20021400
size:   0x00000200
used:   00000080
User stack:
top:    0xb69e1237
sp:     0x2000ddd0 Valid
bottom: 0x02904bc6
size:   0xb40dc671
Invalid Stack! (Corrupted TCB)  Stack base:  02904bc6 Stack size:  b40dc671
```
=> hardfault_log:Sanity check stack before dumping it

src/drivers/gps/gps.cpp
Useful for navio2/px4_raspberrypi when attaching a secondary (UART) GPS through one of the USB ports; the default navio2 onboard GPS is running SPI.
Example usage:
`gps start -d /dev/spidev0.0 -i spi -e /dev/ttyACM0 -j uart -p ubx`
Bonus: fixes error message.
Adds support for a secondary GPS through a USB (UART) port, when the primary GPS is running on SPI.
A way to specify secondary GPS interface when it's different than primary (example: navio2).
Using the dedicated UART port in navio2 but that could be unavailable when using the telemetry module.
Same can be done for protocol but for GPS blending it is recommended that both GPS modules are from the same manufacturer, so they …
=> add support for secondary GPS interface

.ci/Jenkinsfile-hardware, Tools/HIL/monitor_firmware_upload.py, Tools/HIL/run_nsh_cmd.py, Tools/HIL/run_tests.py
- separately handle cmd echo
- decrease timeout in checking for output
- handle error cases (eg nsh: command not found)
=> Jenkins: HIL improve run_nsh_cmd.py helper

ROMFS/cannode/init.d/rcS, ROMFS/px4fmu_common/init.d-posix/rcS, ROMFS/px4fmu_common/init.d/rc.interface, ROMFS/px4fmu_common/init.d/rc.thermal_cal, ROMFS/px4fmu_common/init.d/rcS
- not all build configurations have these parameters/modules
=> ROMFS: silently compare optional parameters

src/drivers/imu/st/lsm9ds1/CMakeLists.txt, src/drivers/imu/st/lsm9ds1/LSM9DS1.cpp, src/drivers/imu/st/lsm9ds1/LSM9DS1.hpp, src/drivers/imu/st/lsm9ds1/ST_LSM9DS1_Registers.hpp, src/drivers/imu/st/lsm9ds1/lsm9ds1_main.cpp
- register configuration captured in table and checked periodically
- simple state machine
- all driver sleeps removed
- driver respects IMU_GYRO_RATEMAX
=> imu/st/lsm9ds1: refactor to same form as other new IMU drivers

src/drivers/gps/params.c
The reset of the description is correct
=> GPS_YAW_OFFSET: fix param description

.ci/Jenkinsfile-hardware, Tools/HIL/monitor_firmware_upload.py, Tools/HIL/run_nsh_cmd.py, Tools/HIL/run_tests.py
Per build there's hundreds of commands executed across all the boards. Even a relatively rare character dropped in verifying a command across all the cases will cause the overall build to fail.
I'll revisit this later.
=> HIL: relax command retry for now

src/systemcmds/tests/CMakeLists.txt, src/systemcmds/tests/test_microbench_matrix.cpp
- split matrix tests to minimize stack usage
=> systemcmds/tests: always build with optimization

Tools/sitl_run.sh
the sitl_gazebo submodule supports gazebo models to be defined by the variable GAZEBO_MODEL_PATH. PX4 appends to this path, but apart from the run_sitl.sh script, there was no restriction on where the models were.
This pr adds to the run_sitl.sh script the functionality to loop over all paths defined in GAZEBO_MODEL_PATH (separated by :) and checks if the model is present there. If so, the loop is stopped early and that path is used. If no path is found, an error is raised by gazebo itself.
An alternative for the error handling would be to exit early in run_sitl.sh if no valid model path is found. This was not implemented to keep it simple, but can easily be added if required. …
=> Added support for models located in all paths defined in GAZEBO_MODEL_PATH

src/drivers/uavcan/CMakeLists.txt, src/drivers/uavcan/dsdl/ardupilot/indication/20000.SafetyState.uavcan, src/drivers/uavcan/safety_state.cpp, src/drivers/uavcan/safety_state.hpp, src/drivers/uavcan/uavcan_main.cpp, src/drivers/uavcan/uavcan_main.hpp
Enable cuav neo v2 pro safety state.
=> Enable cuav neo v2 pro safety state

src/modules/mc_pos_control/PositionControl/PositionControl.cpp
Like discussed in today's dev call porting https://github.com/PX4/PX4-Autopilot/pull/16030 back to the release.
=> [1.11] PositionControl: add check on sign before sqrtf

src/modules/logger/logged_topics.cpp
Fixes https://github.com/PX4/PX4-Autopilot/issues/16229
=> logger: log gps_dump if GPS_DUMP_COMM is set

src/modules/commander/Commander.cpp
Signed-off-by: Ricardo Marques <marques.ricardo17@gmail.com>
=> commander: Fix comment typos.

src/drivers/pca9685_pwm_out/PCA9685.cpp, src/drivers/pca9685_pwm_out/PCA9685.h, src/drivers/pca9685_pwm_out/main.cpp
1. ~~reduce I2C calls~~
2. enable EXTCLK support
3. add support for schedule rate limit, to reduce I2C bus transfer but still maintain higher outputting resolution.
4. refactor to use state machine.
Minor update.
=> pca9685_pwm_out small improvement

src/modules/commander/CMakeLists.txt, src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/commander/esc_calibration.cpp, src/modules/commander/worker_thread.cpp, src/modules/commander/worker_thread.hpp, src/modules/mavlink/mavlink_main.cpp
- removes race conditions
- removes dependencies on static data & methods
- reduces RAM usage by ~3.8KB
Tested:
- RC calib
- ESC calib
- sensor calib
- param reset
=>  commander: remove low priority thread, run tasks in a worker thread on demand

src/drivers/differential_pressure/ms4525/ms4525_airspeed.cpp
This isn't correct for all boards and we now have airspeed scale factor estimation. It also saves a little flash where we need it most (px4_fmu-v2).
=> ms4525: remove old voltage correction

src/lib/parameters/parameters.cpp
This avoids unnecessarily keeping params set to default value in memory or having to export them to non-volatile storage.
=> parameters: don't keep in memory if set to default

src/modules/ekf2/EKF2.cpp
- includes https://github.com/PX4/PX4-ECL/pull/938
- saves a bit of memory (depending on configuration) and about ~1.7 kB of flash (surprisingly)
=> ekf2: update to latest ecl

src/modules/commander/accelerometer_calibration.cpp, src/modules/mavlink/mavlink_command_sender.cpp, src/modules/mavlink/mavlink_command_sender.h, src/modules/mavlink/timestamped_list.h
=> Remove typedefs of anonymous structs

Tools/gazebo_sitl_multiple_run.sh
This commit fixes the problem when using scripting options, and Fixes https://github.com/PX4/PX4-Autopilot/issues/16182
This regression was introduced by #15463 . Sorry that this slipped through my review
Tested with the following script
```
Tools/gazebo_sitl_multiple_run.sh -s "iris:3,plane:2"
```
=> Fix gazebo_sitl_multiple_run.sh scripting

src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp, src/modules/logger/logged_topics.cpp
- https://github.com/PX4/PX4-ECL/pull/924
=> ekf2: use new ECL sensor bias and variance methods

msg/estimator_status.msg, src/modules/ekf2/EKF2.cpp
- estimator_status filter_fault_flags has exceeded 16 bits
The actual fault status was being clobbered. Requires https://github.com/PX4/PX4-ECL/pull/941
=> ekf2: update to new ecl to fix fault status getter

src/modules/navigator/mission_block.cpp
- this was overzealously removed in https://github.com/PX4/PX4-Autopilot/pull/15677
=> navigator: fix LOITER_TO_ALT

src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp
See https://github.com/PX4/PX4-Autopilot/pull/16364 for background.
=> commander: global position validity respect local position xy_valid

README.md
=> README.md update PX4/Firmware -> PX4/PX4-Autopilot

msg/actuator_armed.msg, msg/vehicle_status.msg, src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp, src/modules/commander/state_machine_helper.cpp, src/modules/mavlink/streams/FLIGHT_INFORMATION.hpp
- fixes https://github.com/PX4/PX4-Autopilot/issues/16393
=> Mavlink FLIGHT_INFORMATION fix arming time (ms -> us) and add takeoff time

.github/workflows/mavros_mission_tests.yml
=> Github Actions: skip Mavros tiltrotor mission for now

src/drivers/optical_flow/paw3902/PAW3902.cpp, src/drivers/optical_flow/paw3902/PAW3902.hpp, src/drivers/optical_flow/paw3902/PixArt_PAW3902JF_Registers.hpp, src/drivers/optical_flow/paw3902/paw3902_main.cpp
- verify register writes
- cleanly reset on lighting mode changes as per the datasheet
- perf counters for mode switches and other errors
- cleanly reset on false motion detection
- minimize sleeps
- allowing setting custom rotation yaw angle directly on command line with -Y (ignoring SENS_FLOW_ROT)
- enable LED output
=> paw3902 minor improvements

.github/workflows/mavros_mission_tests.yml
The tiltrotor gazebo model wasn't flying properly and the mavros mission tests were failing. 
Fixed the sitl_gazebo model in https://github.com/PX4/PX4-SITL_gazebo/pull/675
Tested in SITL using
```
make px4_sitl gazebo_tiltorotor
```
The plane is still swaying a bit during hover, would you mind if you can have a look? @sfuhrer 
- The test re-enables the test that was disabled in https://github.com/PX4/PX4-Autopilot/pull/16405
=> Fix tiltrotor model for SITL Gazebo

ROMFS/px4fmu_common/init.d-posix/airframes/1042_tiltrotor
This improves the over-all flight performance of the SITL tiltrotor and removes unnecessary params from the config.
=> ROMFS: Tiltrotor SITL: improve tuning

src/modules/commander/Commander.cpp, src/modules/commander/Commander.hpp
- stolen from @LorenzMeier's https://github.com/PX4/PX4-Autopilot/pull/16269
=> Commander: move static overload_start to class

src/modules/mavlink/mavlink_messages.cpp, src/modules/mavlink/streams/COLLISION.hpp
- this prevents unnecessarily discarding important valid data
=> mavlink: unlimited rate streams check tx buffer before send

test/mavsdk_tests/test_multicopter_failsafe.cpp
This is a quick test to see if it is in any way timeout related.
=> MAVSDK test: Increase timeout

src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
=> sensors/vehicle_magnetometer: reduce offset update info message length to fit

src/lib/flight_tasks/tasks/Transition/FlightTaskTransition.cpp, src/lib/flight_tasks/tasks/Transition/FlightTaskTransition.hpp, src/modules/flight_mode_manager/FlightModeManager.cpp, src/modules/vtol_att_control/standard.cpp, src/modules/vtol_att_control/tiltrotor.cpp
Potential replace for https://github.com/PX4/PX4-Autopilot/pull/16091.
@xdwgood @RicardoM17 fyi.
=> VTOL: direct MC throttle control during transition in not-altitude controlled modes

src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
- the magnetometer calibration offset setter returns false if the new offset change is negligible
=> sensors/vehicle_magnetometer: respect offset update success

src/modules/ekf2/EKF2Selector.cpp, src/modules/ekf2/EKF2Selector.hpp, src/modules/logger/logged_topics.cpp
- publish estimator_selector_status at minimal rate or immediately on change
- log all estimator_selector_status updates
=> ekf2: selector improve status reporting

src/modules/ekf2/EKF2Selector.cpp
In multi-EKF the ekf2 selector is scheduled to run after updates from the current primary ekf2 instance (or timeout). As a result there are scenarios where a fault impacting multiple estimators will result in back to back switches.
- 4 estimators total (2 IMUs * 2 mags)
- estimator 0 (IMU 0) is the current primary and experiences a fault
- estimator selector runs immediately after estimator 0, sees fault and switches to estimator 3 (also IMU 0)
- estimator 3 now runs, produces the same fault (same IMU 0 data)
- estimator selector runs immediately after estimator 3, sees fault and switches again
- if an ekf instance becomes unhealthy prefer switching to the next best healthy instance using a different IMU
- publish estimator_selector_status at minimal rate or immediately on change
- log …
=> ekf2: selector improve fallback selection when the primary becomes unhealthy

boards/scumaker/pilotpi/arm64.cmake, boards/scumaker/pilotpi/default.cmake, posix-configs/rpi/pilotpi_fw.config, posix-configs/rpi/pilotpi_mc.config
Update the most recent version of board configuration.
- QMC5883l mag enabled
- fixedwing script
- other fix.
=> [Board Support] PilotPi distributing update

Tools/setup/arch.sh
I installed a new arch VM and while doing so adjusted the arch setup script to the latest findings:
- support zsh with the directory retreival
- update to latest ARM GCC
- install gazebo from AUR without binary source
=> Arch setup script: zsh support, latest ARM GCC, gazebo AUR
